In [1]:
# -*- coding: utf-8 -*-
import json
import os
import requests
import pandas as pd
import numpy as np
import certifi
import string
import unicodedata
from datetime import datetime, date, timedelta
from bs4 import BeautifulSoup

from text_importer.importers.bcul.detect import detect_issues, BculIssueDir,dir2issue
from text_importer.importers.bcul.helpers import parse_date, find_mit_file, replace_alias

import pylcs

## Small tests

In [2]:
p = '/mnt/project_impresso/original/BCUL/Le_PÃ¨re_JÃ©rÃ´me/1831/01/01'
p2 = '/mnt/project_impresso/original/BCUL/Le_PÃ¨re_JÃ©rÃ´me/1831/01'

In [18]:
os.listdir('/mnt/project_impresso/original/BCUL/')

In [34]:
titles = ['Le_Touriste__La_Suisse_illustrÃ©e',
 'Le_Veveysan_1',
 'Le_messager',
 'Le_peuple_souverain',
 'Lâ\x80\x99ami_de_la_vÃ©ritÃ©__journal_du_Canton_de_Vaud',
 'Mercure_suisse',
 'Messager_boÃ®teux',
 'Nouvelliste_suisse']

for journal in titles:
    print(journal)
    for dir_path, dirs, files in os.walk(os.path.join('/mnt/project_impresso/original/BCUL/', journal)):
        title = journal.split('/')[-1]
        # check if we are in the directory of a (valid) issue
        #print(dir_path)
        if (
            len(files) > 1 and 
            "solr" not in dir_path and 
            len(os.listdir(os.path.dirname(dir_path))) > 1
        ):
            print(dir_path, ' : ', os.listdir(os.path.dirname(dir_path)))

Le_Touriste__La_Suisse_illustrÃ©e
/mnt/project_impresso/original/BCUL/Le_Touriste__La_Suisse_illustrÃ©e/1880/02/15/672279  :  ['672279', '672292']
/mnt/project_impresso/original/BCUL/Le_Touriste__La_Suisse_illustrÃ©e/1880/02/15/672292  :  ['672279', '672292']
/mnt/project_impresso/original/BCUL/Le_Touriste__La_Suisse_illustrÃ©e/1880/03/15/672277  :  ['672277', '672281']
/mnt/project_impresso/original/BCUL/Le_Touriste__La_Suisse_illustrÃ©e/1880/03/15/672281  :  ['672277', '672281']
/mnt/project_impresso/original/BCUL/Le_Touriste__La_Suisse_illustrÃ©e/1880/06/15/672285  :  ['672285', '672289']
/mnt/project_impresso/original/BCUL/Le_Touriste__La_Suisse_illustrÃ©e/1880/06/15/672289  :  ['672285', '672289']
/mnt/project_impresso/original/BCUL/Le_Touriste__La_Suisse_illustrÃ©e/1880/07/15/672278  :  ['672278', '698260']
/mnt/project_impresso/original/BCUL/Le_Touriste__La_Suisse_illustrÃ©e/1880/07/15/698260  :  ['672278', '698260']
/mnt/project_impresso/original/BCUL/Le_Touriste__La_Suisse_illustrÃ©e/1880/10/15/672280  :  ['672280', '672297']
/mnt/project_impresso/original/BCUL/Le_Touriste__La_Suisse_illustrÃ©e/1880/10/15/672297  :  ['672280', '672297']
/mnt/project_impresso/original/BCUL/Le_Touriste__La_Suisse_illustrÃ©e/1880/11/15/672272  :  ['672272', '672294']
/mnt/project_impresso/original/BCUL/Le_Touriste__La_Suisse_illustrÃ©e/1880/11/15/672294  :  ['672272', '672294']
/mnt/project_impresso/original/BCUL/Le_Touriste__La_Suisse_illustrÃ©e/1880/12/15/672276  :  ['672276', '672283']
/mnt/project_impresso/original/BCUL/Le_Touriste__La_Suisse_illustrÃ©e/1880/12/15/672283  :  ['672276', '672283']
Le_Veveysan_1
/mnt/project_impresso/original/BCUL/Le_Veveysan_1/1888/11/24/255823  :  ['255823', '.DS_Store']
/mnt/project_impresso/original/BCUL/Le_Veveysan_1/1888/11/28/255822  :  ['255822', '.DS_Store']
Le_messager
Le_peuple_souverain
Lâami_de_la_vÃ©ritÃ©__journal_du_Canton_de_Vaud
Mercure_suisse
Messager_boÃ®teux
Nouvelliste_suisse

In [28]:
dirs = os.listdir('/mnt/project_impresso/original/BCUL/Gazette_des_Villages/1867/08/31')
if '.DS_Store' in dirs:
    dirs.remove('.DS_Store')
dirs

['590435']

In [6]:
FAULTY_ISSUES = ['127626', '127627', '127628', '127629', '127630', '127631', '127625']

In [17]:
for dir_path, dirs, files in os.walk(p):
    if (
        len(files) > 1 and 
        "solr" not in dir_path and 
        os.path.basename(dir_path) not in FAULTY_ISSUES
    ):
        print(type(dir_path.split('/')[-1]), os.path.basename(dir_path), ' not in FAULTY_ISSUES')

<class 'str'> 170463  not in FAULTY_ISSUES
<class 'str'> 170464  not in FAULTY_ISSUES
<class 'str'> 170465  not in FAULTY_ISSUES
<class 'str'> 170466  not in FAULTY_ISSUES
<class 'str'> 170467  not in FAULTY_ISSUES
<class 'str'> 170468  not in FAULTY_ISSUES

In [2]:
def get_date(dayofyear: str, year: int) -> datetime.date:
        """Return the date corresponding to a day of year.

        Args:
            dayofyear (str): Numbered day in a year.
            year (int): Year in question.

        Returns:
            datetime.date: Date corresponding to the day of year.
        """
        start_date = datetime(year=year, month=1, day=1)
        return start_date + timedelta(days=int(dayofyear) - 1)

In [3]:
#uri = 'https://scriptorium.bcu-lausanne.ch/api/iiif/127765/manifest'
#uri = 'https://scriptorium.bcu-lausanne.ch/api/iiif/127571/manifest'
#uri = 'https://scriptorium.bcu-lausanne.ch/api/iiif/127901/manifest'
uri = 'https://scriptorium.bcu-lausanne.ch/api/iiif/128024/manifest'
page_number = 2
r = requests.get(uri)
if r.status_code == 200:
    page_canvas = r.json()["sequences"][0]["canvases"][page_number-1]
    page_canvas_num = int(page_canvas['label'])
    print(page_canvas_num)
    if page_canvas_num!=page_number:
        print("looking for the right page in the canvases")
        page_canvas = None
        for c in r.json()["sequences"][0]["canvases"].items():
            #if 
            if c['label'] == page_number:
                page_canvas = c
                break
    if page_canvas is None:
        print(f"ME-1732-12-01-a: Could not find the iiif link for page {page_number}.")
    iiif = page_canvas["images"][0]["resource"]["@id"]
    iiif = "/".join(iiif.split("/")[:-4])
iiif

2

'https://scriptorium.bcu-lausanne.ch/api/iiif-img/659775'

## Functions

In [2]:
def modif_str(name: str) -> str:
    # Format the string name to unify the collection names
    no_space = name.replace(':', ' ').replace(' ', '_').replace('/', '')
    
    if 'ami' in no_space:
        no_space = no_space.replace("'", "’")

    return no_space.lower()

In [3]:
def lower_to_utf8(bs):
    return str(bs.lower(), 'utf8')

In [4]:
matches = {
    b'\xc3\xaa': str(b'\xc3\xaa', 'utf-8'),
    b'\xe2\x80\x93': str(b'\xe2\x80\x93', 'utf-8'),
    b'\xc3\xae': str(b'\xc3\xae', 'utf-8'),
    b'\xc3\xa9': str(b'\xc3\xa9', 'utf-8'),
    b'\xc3\xa8': str(b'\xc3\xa8', 'utf-8'),
    b'\xc3\xb4': str(b'\xc3\xb4', 'utf-8'),
    b'\xe2\x80\x99': str(b'\xe2\x80\x99', 'utf-8'),
}
chars = [b'\xc3\xaa', b'\xe2\x80\x93', b'\xc3\xae', b'\xc3\xa9', b'\xc3\xa8', b'\xc3\xb4']

## Journal list

In [ ]:
csv_path = "../text_preparation/data/sample_data/BCUL/names_and_aliases_old.csv" # TODO replace with absolute path if needed
collection_path = '/mnt/project_impresso/original/BCUL'

# read the columns of interest of the csv
columns = ['Collection name','Journal Name','Start Year (in Scriptorium)','End Year (in Scriptorium)','Data Transfer Batch (with hard disk)']
bcul_titles = pd.read_csv(csv_path, header =1, usecols=columns, index_col=False)
# filter to only keep the first batch
# TODO change here to keep batches 3 and 4
batch_1_titles = bcul_titles[bcul_titles['Data Transfer Batch (with hard disk)'] == 'Batch 1 (21/12/23)'].copy()
batch_1_titles['End Year (in Scriptorium)'] = batch_1_titles['End Year (in Scriptorium)'].astype(int)
batch_1_titles

,Collection name,Journal Name,Start Year (in Scriptorium),End Year (in Scriptorium),Data Transfer Batch (with hard disk)
0,Gazettes suisses du 18e s.,Mercure suisse,1732,1747,Batch 1 (21/12/23)
2,Gazettes suisses du 18e s.,Nouvelliste suisse,1748,1769,Batch 1 (21/12/23)
4,Gazettes suisses du 18e s.,Journal helvétique,1738,1782,Batch 1 (21/12/23)
5,Almanachs vaudois,Messager boîteux,1748,1800,Batch 1 (21/12/23)
7,Nouvelliste vaudois,L'ami de la vérité: journal du Canton de Vaud,1822,1823,Batch 1 (21/12/23)
9,Annuaire vaudois,Almanach pour le commerce,1832,1832,Batch 1 (21/12/23)
10,Journaux satiriques vaudois,Le Père Jérôme,1831,1832,Batch 1 (21/12/23)
11,Journaux satiriques vaudois,Le Charivari [1],1839,1841,Batch 1 (21/12/23)
12,Presse de la Côte vaudoise,Le Phare de Nyon,1841,1841,Batch 1 (21/12/23)
13,Presse de la Côte vaudoise,Le Phare du Léman,1841,1842,Batch 1 (21/12/23)
14,Presse du Nord vaudois,Journal d'Yverdon 2,1842,1843,Batch 1 (21/12/23)
16,"Presse de la Broye, du Jorat et du Gros-de-Vaud",Feuille d'avis de Payerne,1843,1845,Batch 1 (21/12/23)
17,Journaux satiriques vaudois,Le Grelot,1843,1846,Batch 1 (21/12/23)
18,Presse du Nord vaudois,Le Peuple souverain,1845,1846,Batch 1 (21/12/23)
19,"Presse de la Broye, du Jorat et du Gros-de-Vaud","Feuille d'avis de Payerne, Moudon et Avenches",1852,1852,Batch 1 (21/12/23)
20,Journaux satiriques vaudois,La Guêpe [1],1851,1854,Batch 1 (21/12/23)
22,"Presse de la Broye, du Jorat et du Gros-de-Vaud",Feuille d'avis de Moudon,1859,1859,Batch 1 (21/12/23)
23,Presse de l'Est vaudois,L'Observateur du Léman,1865,1865,Batch 1 (21/12/23)
24,Journaux satiriques vaudois,La Griffe,1864,1866,Batch 1 (21/12/23)
25,Presse de la Côte vaudoise,Feuille d'avis de Nyon,1849,1867,Batch 1 (21/12/23)
26,Presse du Nord vaudois,Gazette des Villages,1867,1868,Batch 1 (21/12/23)
27,Journaux satiriques vaudois,La Fronde,1872,1872,Batch 1 (21/12/23)
28,Journaux satiriques vaudois,Le Charivari [2],1875,1877,Batch 1 (21/12/23)
29,Journaux satiriques vaudois,Castigat ridendo mores,1879,1880,Batch 1 (21/12/23)
30,Journaux satiriques vaudois,Le Moniteur,1879,1880,Batch 1 (21/12/23)
31,Presse de la Vallée de Joux,Le Messager,1879,1881,Batch 1 (21/12/23)
32,Journaux satiriques vaudois,Le Ouistiti,1882,1882,Batch 1 (21/12/23)
33,Magazines illustrés vaudois,Le Touriste / La Suisse Illustrée,1866,1882,Batch 1 (21/12/23)
34,Presse de l'Est vaudois,Journal de Vevey,1865,1882,Batch 1 (21/12/23)
35,Annuaire vaudois,Indicateur de Lausanne,1880,1886,Batch 1 (21/12/23)
36,Presse de l'Est vaudois,Courrier du Léman,1882,1886,Batch 1 (21/12/23)
37,Journaux satiriques vaudois,Croquis vaudois,1884,1887,Batch 1 (21/12/23)
38,Journaux satiriques vaudois,Le Moustique (Vevey),1887,1887,Batch 1 (21/12/23)
39,Journaux satiriques vaudois,La Bombe,1889,1889,Batch 1 (21/12/23)
40,Presse de l'Est vaudois,Le Veveysan 1,1888,1889,Batch 1 (21/12/23)
42,Presse de la Côte vaudoise,L'Echo de Morges,1883,1892,Batch 1 (21/12/23)
43,Presse de l'Est vaudois,Journal de Vevey et des étrangers,1891,1894,Batch 1 (21/12/23)
45,Journaux satiriques vaudois,La Guêpe [2],1887,1897,Batch 1 (21/12/23)
46,Journaux satiriques vaudois,La Cancoire,1898,1898,Batch 1 (21/12/23)
47,Revue de Lausanne,La Revue agricole,1891,1898,Batch 1 (21/12/23)

In [5]:
utf8_to_unicode = {}
utf8_dirs = {}
for dir_name1, dn2 in zip(os.listdir(b'/mnt/project_impresso/original/BCUL'), os.listdir(u'/mnt/project_impresso/original/BCUL')):
    utf8_to_unicode[dir_name1] = dn2
    utf8_dirs[lower_to_utf8(dir_name1)] = dir_name1

In [6]:
batch_1_titles['displayed_name_in_fs_lower'] = batch_1_titles['Journal Name'].apply(lambda x: modif_str(x))
batch_1_titles['binary_name_in_fs'] = batch_1_titles['displayed_name_in_fs_lower'].apply(lambda x: utf8_dirs[x] if x in utf8_dirs else None)
batch_1_titles['unicode_name_in_fs'] = batch_1_titles['binary_name_in_fs'].apply(lambda x: utf8_to_unicode[x] if x in utf8_to_unicode else None)
batch_1_titles.head()

,Collection name,Journal Name,Start Year (in Scriptorium),End Year (in Scriptorium),Data Transfer Batch (with hard disk),displayed_name_in_fs_lower,binary_name_in_fs,unicode_name_in_fs
0,Gazettes suisses du 18e s.,Mercure suisse,1732,1747,Batch 1 (21/12/23),mercure_suisse,b'Mercure_suisse',Mercure_suisse
2,Gazettes suisses du 18e s.,Nouvelliste suisse,1748,1769,Batch 1 (21/12/23),nouvelliste_suisse,b'Nouvelliste_suisse',Nouvelliste_suisse
4,Gazettes suisses du 18e s.,Journal helvétique,1738,1782,Batch 1 (21/12/23),journal_helvétique,b'Journal_helv\xc3\xa9tique',Journal_helvÃ©tique
5,Almanachs vaudois,Messager boîteux,1748,1800,Batch 1 (21/12/23),messager_boîteux,b'Messager_bo\xc3\xaeteux',Messager_boÃ®teux
7,Nouvelliste vaudois,L'ami de la vérité: journal du Canton de Vaud,1822,1823,Batch 1 (21/12/23),l’ami_de_la_vérité__journal_du_canton_de_vaud,b'L\xe2\x80\x99ami_de_la_v\xc3\xa9rit\xc3\xa9_...,Lâami_de_la_vÃ©ritÃ©__journal_du_Canton_de_Vaud

In [7]:
titles_not_in_batch = batch_1_titles[batch_1_titles['unicode_name_in_fs'].isna()]['Journal Name']
titles_not_in_batch

42    L'Echo de Morges
Name: Journal Name, dtype: object

In [17]:
batch_1_titles

,Collection name,Journal Name,Start Year (in Scriptorium),End Year (in Scriptorium),Data Transfer Batch (with hard disk),displayed_name_in_fs_lower,binary_name_in_fs,unicode_name_in_fs,alias
0,Gazettes suisses du 18e s.,Mercure suisse,1732,1747,Batch 1 (21/12/23),mercure_suisse,b'Mercure_suisse',Mercure_suisse,ME
2,Gazettes suisses du 18e s.,Nouvelliste suisse,1748,1769,Batch 1 (21/12/23),nouvelliste_suisse,b'Nouvelliste_suisse',Nouvelliste_suisse,NS
4,Gazettes suisses du 18e s.,Journal helvétique,1738,1782,Batch 1 (21/12/23),journal_helvétique,b'Journal_helv\xc3\xa9tique',Journal_helvÃ©tique,JH
5,Almanachs vaudois,Messager boîteux,1748,1800,Batch 1 (21/12/23),messager_boîteux,b'Messager_bo\xc3\xaeteux',Messager_boÃ®teux,MB
7,Nouvelliste vaudois,L'ami de la vérité: journal du Canton de Vaud,1822,1823,Batch 1 (21/12/23),l’ami_de_la_vérité__journal_du_canton_de_vaud,b'L\xe2\x80\x99ami_de_la_v\xc3\xa9rit\xc3\xa9_...,Lâami_de_la_vÃ©ritÃ©__journal_du_Canton_de_Vaud,NV
9,Annuaire vaudois,Almanach pour le commerce,1832,1832,Batch 1 (21/12/23),almanach_pour_le_commerce,b'Almanach_pour_le_commerce',Almanach_pour_le_commerce,ACI
10,Journaux satiriques vaudois,Le Père Jérôme,1831,1832,Batch 1 (21/12/23),le_père_jérôme,b'Le_P\xc3\xa8re_J\xc3\xa9r\xc3\xb4me',Le_PÃ¨re_JÃ©rÃ´me,PJ
11,Journaux satiriques vaudois,Le Charivari [1],1839,1841,Batch 1 (21/12/23),le_charivari_[1],b'Le_Charivari_[1]',Le_Charivari_[1],Charivari
12,Presse de la Côte vaudoise,Le Phare de Nyon,1841,1841,Batch 1 (21/12/23),le_phare_de_nyon,b'Le_Phare_de_Nyon',Le_Phare_de_Nyon,PDN
13,Presse de la Côte vaudoise,Le Phare du Léman,1841,1842,Batch 1 (21/12/23),le_phare_du_léman,b'Le_Phare_du_L\xc3\xa9man',Le_Phare_du_LÃ©man,PDL
14,Presse du Nord vaudois,Journal d'Yverdon 2,1842,1843,Batch 1 (21/12/23),journal_d'yverdon_2,"b""Journal_d'Yverdon_2""",Journal_d'Yverdon_2,JY2
16,"Presse de la Broye, du Jorat et du Gros-de-Vaud",Feuille d'avis de Payerne,1843,1845,Batch 1 (21/12/23),feuille_d'avis_de_payerne,"b""Feuille_d'avis_de_Payerne""",Feuille_d'avis_de_Payerne,feuilleP
17,Journaux satiriques vaudois,Le Grelot,1843,1846,Batch 1 (21/12/23),le_grelot,b'Le_Grelot',Le_Grelot,Grelot
18,Presse du Nord vaudois,Le Peuple souverain,1845,1846,Batch 1 (21/12/23),le_peuple_souverain,b'Le_peuple_souverain',Le_peuple_souverain,PS
19,"Presse de la Broye, du Jorat et du Gros-de-Vaud","Feuille d'avis de Payerne, Moudon et Avenches",1852,1852,Batch 1 (21/12/23),"feuille_d'avis_de_payerne,_moudon_et_avenches","b""Feuille_d'avis_de_Payerne,_Moudon_et_Avenches""","Feuille_d'avis_de_Payerne,_Moudon_et_Avenches",feuillePMA
20,Journaux satiriques vaudois,La Guêpe [1],1851,1854,Batch 1 (21/12/23),la_guêpe_[1],b'La_Gu\xc3\xaape_[1]',La_GuÃªpe_[1],Guepe1851
22,"Presse de la Broye, du Jorat et du Gros-de-Vaud",Feuille d'avis de Moudon,1859,1859,Batch 1 (21/12/23),feuille_d'avis_de_moudon,"b""Feuille_d'avis_de_Moudon""",Feuille_d'avis_de_Moudon,FAMDE
23,Presse de l'Est vaudois,L'Observateur du Léman,1865,1865,Batch 1 (21/12/23),l'observateur_du_léman,"b""L'Observateur_du_L\xc3\xa9man""",L'Observateur_du_LÃ©man,OBS
24,Journaux satiriques vaudois,La Griffe,1864,1866,Batch 1 (21/12/23),la_griffe,b'La_Griffe',La_Griffe,Griffe
25,Presse de la Côte vaudoise,Feuille d'avis de Nyon,1849,1867,Batch 1 (21/12/23),feuille_d'avis_de_nyon,"b""Feuille_d'avis_de_Nyon""",Feuille_d'avis_de_Nyon,FAN
26,Presse du Nord vaudois,Gazette des Villages,1867,1868,Batch 1 (21/12/23),gazette_des_villages,b'Gazette_des_Villages',Gazette_des_Villages,GAVi
27,Journaux satiriques vaudois,La Fronde,1872,1872,Batch 1 (21/12/23),la_fronde,b'La_Fronde',La_Fronde,Fronde
28,Journaux satiriques vaudois,Le Charivari [2],1875,1877,Batch 1 (21/12/23),le_charivari_[2],b'Le_Charivari_[2]',Le_Charivari_[2],CharivariCH
29,Journaux satiriques vaudois,Castigat ridendo mores,1879,1880,Batch 1 (21/12/23),castigat_ridendo_mores,b'Castigat_ridendo_mores',Castigat_ridendo_mores,Castigat
30,Journaux satiriques vaudois,Le Moniteur,1879,1880,Batch 1 (21/12/23),le_moniteur,b'Le_Moniteur',Le_Moniteur,Moniteur
31,Presse de la Vallée de Joux,Le Messager,1879,1881,Batch 1 (21/12/23),le_messager,b'Le_messager',Le_messager,MESSAGER
32,Journaux satiriques vaudois,Le Ouistiti,1882,1882,Batch 1 (21/12/23),le_ouistiti,b'Le_Ouistiti',Le_Ouistiti,ouistiti
33,Magazines illustrés vaudois,Le Touriste / La Suisse Illustrée,1866,1882,Batch 1 (21/12/23),le_touriste__la_suisse_illustrée,b'Le_Touriste__La_Suisse_illustr\xc3\xa9e',Le_Touriste__La_Suisse_illustrÃ©e,TouSuIl
34,Presse de l'Est vaudois,Journal de Vevey,1865,1882,Batch 1 (21/12/23),journal_de_vevey,b'Journal_de_Vevey',Journal_de_Vevey,JV
35,Annuaire vaudois,Indicateur de Lausanne,1880,1886,Batch 1 (21/12/23),indicateur_de_lausanne,b'Indicateur_de_Lausanne',Indicateur_de_Lausanne,AV
36,Presse de l'Est vaudois,Courrier du Léman,1882,1886,Batch 1 (21/12/23),courrier_du_léman,b'Courrier_du_L\xc3\xa9man',Courrier_du_LÃ©man,CL
37,Journaux satiriques vaudois,Croquis vaudois,1884,1887,Batch 1 (21/12/23),croquis_vaudois,b'Croquis_vaudois',Croquis_vaudois,Croquis
38,Journaux satiriques vaudois,Le Moustique (Vevey),1887,1887,Batch 1 (21/12/23),le_moustique_(vevey),b'Le_Moustique_(Vevey)',Le_Moustique_(Vevey),Moustique
39,Journaux satiriques vaudois,La Bombe,1889,1889,Batch 1 (21/12/23),la_bombe,b'La_Bombe',La_Bombe,Bombe
40,Presse de l'Est vaudois,Le Veveysan 1,1888,1889,Batch 1 (21/12/23),le_veveysan_1,b'Le_Veveysan_1',Le_Veveysan_1,VVS1
42,Presse de la Côte vaudoise,L'Echo de Morges,1883,1892,Batch 1 (21/12/23),l'echo_de_morges,None,None,None
43,Presse de l'Est vaudois,Journal de Vevey et des étrangers,1891,1894,Batch 1 (21/12/23),journal_de_vevey_et_des_étrangers,b'Journal_de_vevey_et_des_\xc3\xa9trangers',Journal_de_vevey_et_des_Ã©trangers,JVE
45,Journaux satiriques vaudois,La Guêpe [2],1887,1897,Batch 1 (21/12/23),la_guêpe_[2],b'La_Gu\xc3\xaape_[2]',La_GuÃªpe_[2],Guepe1887
46,Journaux satiriques vaudois,La Cancoire,1898,1898,Batch 1 (21/12/23),la_cancoire,b'La_Cancoire',La_Cancoire,Cancoire
47,Revue de Lausanne,La Revue agricole,1891,1898,Batch 1 (21/12/23),la_revue_agricole,b'La_revue_agricole',La_revue_agricole,RLA

## Fetching Aliases from each issue dir

Correction: There are aliases already inside each issue.

In [8]:
base_dir = '/mnt/project_impresso/original/BCUL/'

found_aliases = {
 '/mnt/project_impresso/original/BCUL/Almanach_pour_le_commerce': 'ACI',
 '/mnt/project_impresso/original/BCUL/Castigat_ridendo_mores': 'Castigat',
 '/mnt/project_impresso/original/BCUL/Croquis_vaudois': 'Croquis',
 '/mnt/project_impresso/original/BCUL/Courrier_du_LÃ©man': 'CL',
 "/mnt/project_impresso/original/BCUL/Feuille_d'avis_de_Moudon": 'FAMDE',
 "/mnt/project_impresso/original/BCUL/Feuille_d'avis_de_Nyon": 'FAN',
 "/mnt/project_impresso/original/BCUL/Feuille_d'avis_de_Payerne,_Moudon_et_Avenches": 'feuille',
 "/mnt/project_impresso/original/BCUL/Feuille_d'avis_de_Payerne": 'feuille',
 '/mnt/project_impresso/original/BCUL/Gazette_des_Villages': 'GAV',
 '/mnt/project_impresso/original/BCUL/Indicateur_de_Lausanne': 'AV',
 "/mnt/project_impresso/original/BCUL/Journal_d'Yverdon_2": 'JY2',
 '/mnt/project_impresso/original/BCUL/Journal_de_Vevey': 'JV'
}

aliases_json= {
    "Courrier_du_LÃ©man": 'CL',
    "Feuille_d'avis_de_Moudon": 'FAMDE',
    "Feuille_d'avis_de_Nyon": 'FAN',
    "Feuille_d'avis_de_Payerne,_Moudon_et_Avenches": "feuillePMA", #'feuille' in fs
    "Feuille_d'avis_de_Payerne": "feuilleP", # 'feuille' in fs
    "Gazette_des_Villages": "GAVi", # GAV
    "Journal_d'Yverdon_2": 'JY2', 
    "Journal_de_Vevey": 'JV',
    "Journal_de_vevey_et_des_Ã©trangers": 'JVE',
    "L'Observateur_du_LÃ©man": 'OBS',
    "Le_Moustique_(Vevey)": 'Moustique', 
    "Le_Phare_de_Nyon": 'PDN', 
    "Le_Phare_du_LÃ©man": 'PDL', # FAN in fs
    "Le_Touriste__La_Suisse_illustrÃ©e": "TouSuIl", #'TO-SU-IL' in fs
    "Le_Veveysan_1": 'VVS1', # VVS also for La_Veveysanne_–_La_Patrie/La_Veveysanne 
    "Le_messager": 'MESSAGER',
    "Le_peuple_souverain": 'PS'
}

In [9]:
name_to_alias = {}
name_to_type = {}

In [7]:
def check_title_alias_in_fs(title_unicode_name: str, base_dir: str = u'/mnt/project_impresso/original/BCUL') -> tuple[str, str]:
    # fetch the alias used in the filesystem for a given journal
    journal_dir = os.path.join(base_dir, title_unicode_name)
    for dir_path, dirs, files in os.walk(journal_dir):
        if len(files)>1 and 'solr' not in dir_path:
            print(f"{dir_path}: {files[:3]}")
            for file in files:
                if 'mit' in file:
                    return file.split('_')[0], file.split('.')[-1]

In [18]:
for j_name, unicode_name in zip(batch_1_titles['Journal Name'], batch_1_titles['unicode_name_in_fs']):
    # if a name already exists, for the name, use it
    if unicode_name is None:
        continue
    else:
        # otherwise check in the filesystem for the name that is used internally
        candidate_alias, file_type = check_title_alias_in_fs(unicode_name)

        if unicode_name in aliases_json:
            name_to_alias[unicode_name] = aliases_json[unicode_name]
        else:
            while candidate_alias in aliases_json.values():
                if candidate_alias[-1].isnumeric():
                    candidate_alias[-1] = str(int(candidate_alias[-1]) + 1)
                else:
                    candidate_alias = candidate_alias + '1'
                    
            name_to_alias[unicode_name] = candidate_alias
        name_to_type[unicode_name] = file_type

/mnt/project_impresso/original/BCUL/Mercure_suisse/1732/12/01/127765: ['ME_1732_12_00_0001_mit.xml', 'ME_1732_12_00.pdf', 'ME_1732_12_00_0001.jp2']
/mnt/project_impresso/original/BCUL/Nouvelliste_suisse/1748/01/01/128065: ['NS_1748_01_00_0001_mit.xml', 'NS_1748_01_00.pdf', 'NS_1748_01_00_0001.jp2']
/mnt/project_impresso/original/BCUL/Journal_helvÃ©tique/1738/01/01/127826: ['JH_1738_01_00_0001_mit.xml', 'JH_1738_01_00.pdf', 'JH_1738_01_00_0001.jp2']
/mnt/project_impresso/original/BCUL/Messager_boÃ®teux/1748/01/01/168341: ['MB_1748_00_00_0001_mit.xml', 'MB_1748_00_00.pdf', 'MB_1748_00_00_0001.jp2']
/mnt/project_impresso/original/BCUL/Lâami_de_la_vÃ©ritÃ©__journal_du_Canton_de_Vaud/1822/12/18/102037: ['NV_1822_12_18_0001_mit.xml', 'NV_1822_12_18.pdf', 'NV_1822_12_18_0001.jp2']
/mnt/project_impresso/original/BCUL/Almanach_pour_le_commerce/1832/01/01/171722: ['ACI_1832_00_00_0001_mit.xml', 'ACI_1832_00_00.pdf', 'ACI_1832_00_00_0001.jp2']
/mnt/project_impresso/original/BCUL/Le_PÃ¨re_JÃ©rÃ´me/1831/01/01/127626: ['PJ_0001_1831_00_00_0001.jp2', 'PJ_0001_1831_00_00.pdf', 'PJ_0001_1831_00_00_0001_mit.xml']
/mnt/project_impresso/original/BCUL/Le_Charivari_[1]/1839/04/01/127716: ['Charivari_0001_1839_04_00_0001_page_1.xml', 'Charivari_0001_1839_04_00.pdf', 'Charivari_0001_1839_04_00_0001.jp2']
/mnt/project_impresso/original/BCUL/Le_Phare_de_Nyon/1841/09/04/555099: ['20210324T163758_605b5cd6d9f1e_mit.json', '7619771.jp2', '7619771_exif.json']
/mnt/project_impresso/original/BCUL/Le_Phare_du_LÃ©man/1841/12/04/522239: ['7448592.jp2', '7448592.xml', '7448592_exif.json']
/mnt/project_impresso/original/BCUL/Journal_d'Yverdon_2/1842/10/08/315936: ['5557682.jp2', '5557682.xml', '5557682_exif.json']
/mnt/project_impresso/original/BCUL/Feuille_d'avis_de_Payerne/1843/04/29/605183: ['7885313.jp2', '7885313_exif.json', '7885315.jp2']
/mnt/project_impresso/original/BCUL/Le_Grelot/1843/10/01/127513: ['Grelot_0001_1843_10_01.pdf', 'Grelot_0001_1843_10_01_0001.jp2', 'Grelot_0001_1843_10_01_0001_mit.xml']
/mnt/project_impresso/original/BCUL/Le_peuple_souverain/1845/07/11/306429: ['5486198.jp2', '5486198.xml', '5486198_exif.json']
/mnt/project_impresso/original/BCUL/Feuille_d'avis_de_Payerne,_Moudon_et_Avenches/1852/12/25/605182: ['7885310.jp2', '7885310_exif.json', '7885311.jp2']
/mnt/project_impresso/original/BCUL/La_GuÃªpe_[1]/1851/02/05/127024: ['Guepe1851_0001_1851_02_05_0001_page_1.xml', 'Guepe1851_0001_1851_02_05.pdf', 'Guepe1851_0001_1851_02_05_0001.jp2']
/mnt/project_impresso/original/BCUL/Feuille_d'avis_de_Moudon/1859/02/05/539294: ['FAMDE_1859_02_05_mit.json', '7518776.jp2', '7518776.xml']
/mnt/project_impresso/original/BCUL/L'Observateur_du_LÃ©man/1865/03/25/255571: ['4464201.jp2', '4464201.xml', '4464201_exif.json']
/mnt/project_impresso/original/BCUL/La_Griffe/1864/07/02/126933: ['Griffe_0001_1864_07_02.pdf', 'Griffe_0001_1864_07_02_0001.jp2', 'Griffe_0001_1864_07_02_0001_mit.xml']
/mnt/project_impresso/original/BCUL/Feuille_d'avis_de_Nyon/1849/09/15/522214: ['7448374.jp2', '7448374.xml', '7448374_exif.json']
/mnt/project_impresso/original/BCUL/Gazette_des_Villages/1867/08/31/590435: ['7785861.jp2', '7785861.xml', '7785861_exif.json']
/mnt/project_impresso/original/BCUL/La_Fronde/1872/03/17/126902: ['Fronde_0001_1872_03_17.pdf', 'Fronde_0001_1872_03_17_0001.jp2', 'Fronde_0001_1872_03_17_0001_mit.xml']
/mnt/project_impresso/original/BCUL/Le_Charivari_[2]/1875/12/01/127364: ['CharivariCH_0001_1875_12_00_0001_page_1.xml', 'CharivariCH_0001_1875_12_00.pdf', 'CharivariCH_0001_1875_12_00_0001.jp2']
/mnt/project_impresso/original/BCUL/Castigat_ridendo_mores/1879/11/01/170474: ['Castigat_0001_1879_11_00.pdf', 'Castigat_0001_1879_11_00_0001.jp2', 'Castigat_0001_1879_11_00_0001_mit.xml']
/mnt/project_impresso/original/BCUL/Le_Moniteur/1879/08/15/127571: ['Moniteur_0001_1879_08_15.pdf', 'Moniteur_0001_1879_08_15_0001.jp2', 'Moniteur_0001_1879_08_15_0001_mit.xml']
/mnt/project_impresso/original/BCUL/Le_messager/1879/12/00/279344: ['MESSAGER_1879_12_00_mit.json', '4703253.jp2', '4703253.xml']
/mnt/project_impresso/original/BCUL/Le_Ouistiti/1882/05/31/171185: ['ouistiti_0001_1882_06_00_0001_page_10.xml', 'ouistiti_0001_1882_06_00.pdf', 'ouistiti_0001_1882_06_00_0001.jp2']
/mnt/project_impresso/original/BCUL/Le_Touriste__La_Suisse_illustrÃ©e/1866/02/01/197832: ['TO-SU-IL_0001_1866_00_00.pdf', '3720851.jp2', '3720851.xml']
/mnt/project_impresso/original/BCUL/Journal_de_Vevey/1865/08/29/246382: ['4406736.jp2', '4406736.xml', '4406736_exif.json']
/mnt/project_impresso/original/BCUL/Indicateur_de_Lausanne/1880/01/01/170197: ['AV_1880_0001.jp2', 'AV_1880_0001.xml', 'AV_1880_0001_mit.xml']
/mnt/project_impresso/original/BCUL/Courrier_du_LÃ©man/1882/09/30/257141: ['4478884.jp2', '4478884.xml.bz2', '4478884_exif.json']
/mnt/project_impresso/original/BCUL/Croquis_vaudois/1884/03/01/126485: ['Croquis_0001_1884_03_01.pdf', 'Croquis_0001_1884_03_01_0001.jp2', 'Croquis_0001_1884_03_01_0001_mit.xml']
/mnt/project_impresso/original/BCUL/Le_Moustique_(Vevey)/1887/12/31/588227: ['Moustique_18871231-OCR.pdf', '7775953.jp2', '7775953_exif.json']
/mnt/project_impresso/original/BCUL/La_Bombe/1889/11/15/126860: ['Bombe_0001_1889_11_15.pdf', 'Bombe_0001_1889_11_15_0001.jp2', 'Bombe_0001_1889_11_15_0001_mit.xml']
/mnt/project_impresso/original/BCUL/Le_Veveysan_1/1888/11/24/255823: ['4465315.jp2', '4465315.xml', '4465315_exif.json']
/mnt/project_impresso/original/BCUL/Journal_de_vevey_et_des_Ã©trangers/1891/04/04/258492: ['4484638.jp2', '4484638.xml.bz2', '4484638_exif.json']
/mnt/project_impresso/original/BCUL/La_GuÃªpe_[2]/1887/02/27/127026: ['Guepe1887_0001_1887_02_27_0001_page_1.xml', 'Guepe1887_0001_1887_02_27.pdf', 'Guepe1887_0001_1887_02_27_0001.jp2']
/mnt/project_impresso/original/BCUL/La_Cancoire/1898/01/08/126862: ['Cancoire_0001_1898_01_08.pdf', 'Cancoire_0001_1898_01_08_0001.jp2', 'Cancoire_0001_1898_01_08_0001_mit.xml']
/mnt/project_impresso/original/BCUL/La_revue_agricole/1891/12/10/165847: ['RLA_1891_12_10_0001_mit.xml', 'RLA_1891_12_10.pdf', 'RLA_1891_12_10_0001.jp2']

In [51]:
batch_1_titles['alias'] = batch_1_titles['unicode_name_in_fs'].apply(lambda n: name_to_alias[n] if n is not None else None)
batch_1_titles['file_type'] = batch_1_titles['unicode_name_in_fs'].apply(lambda n: name_to_type[n] if n is not None else None)
batch_1_titles['access_right'] = 'open_public'

In [54]:
indexed_titles = batch_1_titles.set_index('unicode_name_in_fs')[['alias', 'file_type', 'access_right']]
indexed_titles

,alias,file_type,access_right
unicode_name_in_fs,,,
Mercure_suisse,ME,xml,open_public
Nouvelliste_suisse,NS,xml,open_public
Journal_helvÃ©tique,JH,xml,open_public
Messager_boÃ®teux,MB,xml,open_public
Lâami_de_la_vÃ©ritÃ©__journal_du_Canton_de_Vaud,NV,xml,open_public
Almanach_pour_le_commerce,ACI,xml,open_public
Le_PÃ¨re_JÃ©rÃ´me,PJ,xml,open_public
Le_Charivari_[1],Charivari,xml,open_public
Le_Phare_de_Nyon,PDN,json,open_public
Le_Phare_du_LÃ©man,PDL,json,open_public
Journal_d'Yverdon_2,JY2,json,open_public
Feuille_d'avis_de_Payerne,feuilleP,json,open_public
Le_Grelot,Grelot,xml,open_public
Le_peuple_souverain,PS,json,open_public
"Feuille_d'avis_de_Payerne,_Moudon_et_Avenches",feuillePMA,json,open_public
La_GuÃªpe_[1],Guepe1851,xml,open_public
Feuille_d'avis_de_Moudon,FAMDE,json,open_public
L'Observateur_du_LÃ©man,OBS,json,open_public
La_Griffe,Griffe,xml,open_public
Feuille_d'avis_de_Nyon,FAN,json,open_public
Gazette_des_Villages,GAVi,json,open_public
La_Fronde,Fronde,xml,open_public
Le_Charivari_[2],CharivariCH,xml,open_public
Castigat_ridendo_mores,Castigat,xml,open_public
Le_Moniteur,Moniteur,xml,open_public
Le_messager,MESSAGER,json,open_public
Le_Ouistiti,ouistiti,xml,open_public
Le_Touriste__La_Suisse_illustrÃ©e,TouSuIl,json,open_public
Journal_de_Vevey,JV,json,open_public
Indicateur_de_Lausanne,AV,xml,open_public
Courrier_du_LÃ©man,CL,json,open_public
Croquis_vaudois,Croquis,xml,open_public
Le_Moustique_(Vevey),Moustique,json,open_public
La_Bombe,Bombe,xml,open_public
Le_Veveysan_1,VVS1,json,open_public
None,None,None,open_public
Journal_de_vevey_et_des_Ã©trangers,JVE,json,open_public
La_GuÃªpe_[2],Guepe1887,xml,open_public
La_Cancoire,Cancoire,xml,open_public
La_revue_agricole,RLA,xml,open_public

In [55]:
titles_as_dict = indexed_titles.to_dict('index')
titles_as_dict

{'Mercure_suisse': {'alias': 'ME',
  'file_type': 'xml',
  'access_right': 'open_public'},
 'Nouvelliste_suisse': {'alias': 'NS',
  'file_type': 'xml',
  'access_right': 'open_public'},
 'Journal_helvÃ©tique': {'alias': 'JH',
  'file_type': 'xml',
  'access_right': 'open_public'},
 'Messager_boÃ®teux': {'alias': 'MB',
  'file_type': 'xml',
  'access_right': 'open_public'},
 'Lâ\x80\x99ami_de_la_vÃ©ritÃ©__journal_du_Canton_de_Vaud': {'alias': 'NV',
  'file_type': 'xml',
  'access_right': 'open_public'},
 'Almanach_pour_le_commerce': {'alias': 'ACI',
  'file_type': 'xml',
  'access_right': 'open_public'},
 'Le_PÃ¨re_JÃ©rÃ´me': {'alias': 'PJ',
  'file_type': 'xml',
  'access_right': 'open_public'},
 'Le_Charivari_[1]': {'alias': 'Charivari',
  'file_type': 'xml',
  'access_right': 'open_public'},
 'Le_Phare_de_Nyon': {'alias': 'PDN',
  'file_type': 'json',
  'access_right': 'open_public'},
 'Le_Phare_du_LÃ©man': {'alias': 'PDL',
  'file_type': 'json',
  'access_right': 'open_public'},
 "Journal_d'Yverdon_2": {'alias': 'JY2',
  'file_type': 'json',
  'access_right': 'open_public'},
 "Feuille_d'avis_de_Payerne": {'alias': 'feuilleP',
  'file_type': 'json',
  'access_right': 'open_public'},
 'Le_Grelot': {'alias': 'Grelot',
  'file_type': 'xml',
  'access_right': 'open_public'},
 'Le_peuple_souverain': {'alias': 'PS',
  'file_type': 'json',
  'access_right': 'open_public'},
 "Feuille_d'avis_de_Payerne,_Moudon_et_Avenches": {'alias': 'feuillePMA',
  'file_type': 'json',
  'access_right': 'open_public'},
 'La_GuÃªpe_[1]': {'alias': 'Guepe1851',
  'file_type': 'xml',
  'access_right': 'open_public'},
 "Feuille_d'avis_de_Moudon": {'alias': 'FAMDE',
  'file_type': 'json',
  'access_right': 'open_public'},
 "L'Observateur_du_LÃ©man": {'alias': 'OBS',
  'file_type': 'json',
  'access_right': 'open_public'},
 'La_Griffe': {'alias': 'Griffe',
  'file_type': 'xml',
  'access_right': 'open_public'},
 "Feuille_d'avis_de_Nyon": {'alias': 'FAN',
  'file_type': 'json',
  'access_right': 'open_public'},
 'Gazette_des_Villages': {'alias': 'GAVi',
  'file_type': 'json',
  'access_right': 'open_public'},
 'La_Fronde': {'alias': 'Fronde',
  'file_type': 'xml',
  'access_right': 'open_public'},
 'Le_Charivari_[2]': {'alias': 'CharivariCH',
  'file_type': 'xml',
  'access_right': 'open_public'},
 'Castigat_ridendo_mores': {'alias': 'Castigat',
  'file_type': 'xml',
  'access_right': 'open_public'},
 'Le_Moniteur': {'alias': 'Moniteur',
  'file_type': 'xml',
  'access_right': 'open_public'},
 'Le_messager': {'alias': 'MESSAGER',
  'file_type': 'json',
  'access_right': 'open_public'},
 'Le_Ouistiti': {'alias': 'ouistiti',
  'file_type': 'xml',
  'access_right': 'open_public'},
 'Le_Touriste__La_Suisse_illustrÃ©e': {'alias': 'TouSuIl',
  'file_type': 'json',
  'access_right': 'open_public'},
 'Journal_de_Vevey': {'alias': 'JV',
  'file_type': 'json',
  'access_right': 'open_public'},
 'Indicateur_de_Lausanne': {'alias': 'AV',
  'file_type': 'xml',
  'access_right': 'open_public'},
 'Courrier_du_LÃ©man': {'alias': 'CL',
  'file_type': 'json',
  'access_right': 'open_public'},
 'Croquis_vaudois': {'alias': 'Croquis',
  'file_type': 'xml',
  'access_right': 'open_public'},
 'Le_Moustique_(Vevey)': {'alias': 'Moustique',
  'file_type': 'json',
  'access_right': 'open_public'},
 'La_Bombe': {'alias': 'Bombe',
  'file_type': 'xml',
  'access_right': 'open_public'},
 'Le_Veveysan_1': {'alias': 'VVS1',
  'file_type': 'json',
  'access_right': 'open_public'},
 None: {'alias': None, 'file_type': None, 'access_right': 'open_public'},
 'Journal_de_vevey_et_des_Ã©trangers': {'alias': 'JVE',
  'file_type': 'json',
  'access_right': 'open_public'},
 'La_GuÃªpe_[2]': {'alias': 'Guepe1887',
  'file_type': 'xml',
  'access_right': 'open_public'},
 'La_Cancoire': {'alias': 'Cancoire',
  'file_type': 'xml',
  'access_right': 'open_public'},
 'La_revue_agricole': {'alias': 'RLA',
  'file_type': 'xml',
  'access_right': 'open_public'}}

In [56]:
access_rights_and_aliases_file = '/home/piconti/impresso-text-acquisition/text_importer/data/sample_data/BCUL/access_rights_and_aliases.json'

with open(access_rights_and_aliases_file, 'w', encoding='utf-8') as f_out:
    json.dump(titles_as_dict, f_out, ensure_ascii=False, indent=4)

## Adding new aliases

Note: This is what I seem to have used for the creation of aliases for the second batch, but I don't remember what was contained in the `missing_aliases.json` file so it might be better to simply follow the logic on the issue.
However if things below prove to be useful that's perfect.

In [22]:
def check_title_alias_in_fs_2(title_name: str, base_dir: str = '/mnt/project_impresso/original/BCUL/') -> tuple[str, str]:
    # fetch the alias used in the filesystem for a given journal
    journal_dir = os.path.join(base_dir, title_name)
    for dir_path, dirs, files in os.walk(journal_dir):
        if len(files)>1 and 'solr' not in dir_path:
            print(f"{dir_path}: {files[:3]}")
            for file in files:
                if 'mit' in file:
                    return file.split('_')[0], file.split('.')[-1]

In [ ]:
base_dir = '/mnt/project_impresso/original/BCUL/'

access_rights_and_aliases_file = '../text_preparation/data/sample_data/BCUL/bcul_aliases.json'
missing_ars = '../text_preparation/data/sample_data/BCUL/missing_aliases.json'

with open(access_rights_and_aliases_file, "rb") as f:
        ar_and_alias = json.load(f)

with open(missing_ars, "rb") as f:
        missing_aliases = json.load(f)

Find all newly added titles that need an alias

In [43]:
existing_aliases = {k: v['alias'] for k, v in ar_and_alias.items()}

In [44]:
new_alias_needed = []

In [45]:
for j_name in os.listdir(base_dir):
    if j_name not in ar_and_alias and j_name not in ['wrong_BCUL', 'OLD', '.DS_Store', 'La_Veveysanne_â\x80\x93_La_Patrie']:
        if j_name == 'La_Veveysanne__La_Patrie':
            for sub_j_name in os.listdir(os.path.join(base_dir, j_name)):
                if all([sub_j_name not in v['bin_title'] for k,v in ar_and_alias.items()]):
                    print(f"Need new alias for {sub_j_name}")
                    new_alias_needed.append(sub_j_name)
        elif all([j_name not in v['bin_title'] for k,v in ar_and_alias.items()]):
            print(f"Need new alias for {j_name}")
            new_alias_needed.append(j_name)

Need new alias for Bulletins_du_Grand_Conseil
Need new alias for Feuille_d'avis_de_Morges_1
Need new alias for Feuille_d'avis_de_Vevey_1
Need new alias for L'Echo_de_Morges
Need new alias for L'Estafette_Journal_suisse
Need new alias for La_Patrie
Need new alias for La_Veveysane
Need new alias for Le_Nouvelliste_vaudois
Need new alias for Nouvelliste_vaudois_et_journal_national_suisse
Need new alias for Repertoires_de_Bulletins_du_Grand_Conseil
Need new alias for Travaux_des_Constituantes

In [46]:
new_aliases = {}
for j_name in new_alias_needed:
    if j_name in ['La_Patrie', 'La_Veveysane']:
        candidate_alias, file_type = check_title_alias_in_fs_2(os.path.join('La_Veveysanne__La_Patrie', j_name))
    else:
        # check in the filesystem for the name that is used internally
        candidate_alias, file_type = check_title_alias_in_fs_2(j_name)
    print(f"{j_name} first candidate: {candidate_alias}")
    while candidate_alias in existing_aliases.values():
        if candidate_alias[-1].isnumeric():
            candidate_alias = f"{candidate_alias[:-1]}{str(int(candidate_alias[-1]) + 1)}"
        else:
            candidate_alias = f"{candidate_alias}1"
                
    new_aliases[j_name] = {
        'alias': candidate_alias,
        'file_type': file_type,
        'access_right': 'open_public',
    }
    existing_aliases[j_name] = candidate_alias

/mnt/project_impresso/original/BCUL/Bulletins_du_Grand_Conseil/1829/06/06/287138: ['4926576.jp2', '4926576_exif.json', '4926577.jp2']
Bulletins_du_Grand_Conseil first candidate: RN
/mnt/project_impresso/original/BCUL/Feuille_d'avis_de_Morges_1/1854/06/10/381504: ['6224375.jp2', '6224375.xml', '6224375_exif.json']
Feuille_d'avis_de_Morges_1 first candidate: FAM
/mnt/project_impresso/original/BCUL/Feuille_d'avis_de_Vevey_1/1784/01/30/257835: ['4481734.jp2', '4481734.xml.bz2', '4481734_exif.json']
Feuille_d'avis_de_Vevey_1 first candidate: FAV1
/mnt/project_impresso/original/BCUL/L'Echo_de_Morges/1883/06/13/385203: ['6239346.jp2', '6239346.xml', '6239346_exif.json']
L'Echo_de_Morges first candidate: EM
/mnt/project_impresso/original/BCUL/L'Estafette_Journal_suisse/1862/12/15/91885: ['esta_1862_12_15_0001_mit.xml', 'esta_1862_12_15.pdf', 'esta_1862_12_15_0001.jp2']
L'Estafette_Journal_suisse first candidate: esta
/mnt/project_impresso/original/BCUL/La_Veveysanne__La_Patrie/La_Patrie/1841/10/30/255634: ['4464453.jp2', '4464453.xml', '4464453_exif.json']
La_Patrie first candidate: PAT
/mnt/project_impresso/original/BCUL/La_Veveysanne__La_Patrie/La_Veveysane/1840/06/11/256244: ['4467169.jp2', '4467169.xml', '4467169_exif.json']
La_Veveysane first candidate: VVS
/mnt/project_impresso/original/BCUL/Le_Nouvelliste_vaudois/1824/01/02/102038: ['NV_1824_01_02_0001_mit.xml', 'NV_1824_01_02.pdf', 'NV_1824_01_02_0001.jp2']
Le_Nouvelliste_vaudois first candidate: NV
/mnt/project_impresso/original/BCUL/Nouvelliste_vaudois_et_journal_national_suisse/1856/01/02/105737: ['NV_1856_01_02_0001_mit.xml', 'NV_1856_01_02.pdf', 'NV_1856_01_02_0001.jp2']
Nouvelliste_vaudois_et_journal_national_suisse first candidate: NV
/mnt/project_impresso/original/BCUL/Repertoires_de_Bulletins_du_Grand_Conseil/1803-1830/1907/00/00/287190: ['RN_REP_1803_1830_1_mit.json', '4960405.jp2', '4960405_exif.json']
Repertoires_de_Bulletins_du_Grand_Conseil first candidate: RN
/mnt/project_impresso/original/BCUL/Travaux_des_Constituantes/1861/1861/05/24/287141: ['4927750.jp2', '4927750_exif.json', '4927752.jp2']
Travaux_des_Constituantes first candidate: RN

In [47]:
new_aliases

{'Bulletins_du_Grand_Conseil': {'alias': 'RN',
  'file_type': 'json',
  'access_right': 'open_public'},
 "Feuille_d'avis_de_Morges_1": {'alias': 'FAM',
  'file_type': 'json',
  'access_right': 'open_public'},
 "Feuille_d'avis_de_Vevey_1": {'alias': 'FAV1',
  'file_type': 'json',
  'access_right': 'open_public'},
 "L'Echo_de_Morges": {'alias': 'EM',
  'file_type': 'json',
  'access_right': 'open_public'},
 "L'Estafette_Journal_suisse": {'alias': 'esta',
  'file_type': 'xml',
  'access_right': 'open_public'},
 'La_Patrie': {'alias': 'PAT',
  'file_type': 'json',
  'access_right': 'open_public'},
 'La_Veveysane': {'alias': 'VVS',
  'file_type': 'json',
  'access_right': 'open_public'},
 'Le_Nouvelliste_vaudois': {'alias': 'NV1',
  'file_type': 'xml',
  'access_right': 'open_public'},
 'Nouvelliste_vaudois_et_journal_national_suisse': {'alias': 'NV2',
  'file_type': 'xml',
  'access_right': 'open_public'},
 'Repertoires_de_Bulletins_du_Grand_Conseil': {'alias': 'RN1',
  'file_type': 'json',
  'access_right': 'open_public'},
 'Travaux_des_Constituantes': {'alias': 'RN2',
  'file_type': 'json',
  'access_right': 'open_public'}}

In [49]:
ar_and_alias.update(new_aliases)
ar_and_alias

{'Mercure_suisse': {'alias': 'ME',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'Mercure_suisse'},
 'Nouvelliste_suisse': {'alias': 'NS',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'Nouvelliste_suisse'},
 'Journal_helvétique': {'alias': 'JH',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'Journal_helvÃ©tique'},
 'Messager_boîteux': {'alias': 'MB',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'Messager_boÃ®teux'},
 'L’ami_de_la_vérité__journal_du_Canton_de_Vaud': {'alias': 'NV',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'Lâ\x80\x99ami_de_la_vÃ©ritÃ©__journal_du_Canton_de_Vaud'},
 'Almanach_pour_le_commerce': {'alias': 'ACI',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'Almanach_pour_le_commerce'},
 'Le_Père_Jérôme': {'alias': 'PJ',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'Le_PÃ¨re_JÃ©rÃ´me'},
 'Le_Charivari_[1]': {'alias': 'Charivari',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'Le_Charivari_[1]'},
 'Le_Phare_de_Nyon': {'alias': 'PDN',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': 'Le_Phare_de_Nyon'},
 'Le_Phare_du_Léman': {'alias': 'PDL',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': 'Le_Phare_du_LÃ©man'},
 "Journal_d'Yverdon_2": {'alias': 'JY2',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': "Journal_d'Yverdon_2"},
 "Feuille_d'avis_de_Payerne": {'alias': 'feuilleP',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': "Feuille_d'avis_de_Payerne"},
 'Le_Grelot': {'alias': 'Grelot',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'Le_Grelot'},
 'Le_peuple_souverain': {'alias': 'PS',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': 'Le_peuple_souverain'},
 "Feuille_d'avis_de_Payerne,_Moudon_et_Avenches": {'alias': 'feuillePMA',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': "Feuille_d'avis_de_Payerne,_Moudon_et_Avenches"},
 'La_Guêpe_[1]': {'alias': 'Guepe1851',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'La_GuÃªpe_[1]'},
 "Feuille_d'avis_de_Moudon": {'alias': 'FAMDE',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': "Feuille_d'avis_de_Moudon"},
 "L'Observateur_du_Léman": {'alias': 'OBS',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': "L'Observateur_du_LÃ©man"},
 'La_Griffe': {'alias': 'Griffe',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'La_Griffe'},
 "Feuille_d'avis_de_Nyon": {'alias': 'FAN',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': "Feuille_d'avis_de_Nyon"},
 'Gazette_des_Villages': {'alias': 'GAVi',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': 'Gazette_des_Villages'},
 'La_Fronde': {'alias': 'Fronde',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'La_Fronde'},
 'Le_Charivari_[2]': {'alias': 'CharivariCH',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'Le_Charivari_[2]'},
 'Castigat_ridendo_mores': {'alias': 'Castigat',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'Castigat_ridendo_mores'},
 'Le_Moniteur': {'alias': 'Moniteur',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'Le_Moniteur'},
 'Le_messager': {'alias': 'MESSAGER',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': 'Le_messager'},
 'Le_Ouistiti': {'alias': 'ouistiti',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'Le_Ouistiti'},
 'Le_Touriste__La_Suisse_illustrée': {'alias': 'TouSuIl',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': 'Le_Touriste__La_Suisse_illustrÃ©e'},
 'Journal_de_Vevey': {'alias': 'JV',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': 'Journal_de_Vevey'},
 'Indicateur_de_Lausanne': {'alias': 'AV',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'Indicateur_de_Lausanne'},
 'Courrier_du_Léman': {'alias': 'CL',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': 'Courrier_du_LÃ©man'},
 'Croquis_vaudois': {'alias': 'Croquis',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'Croquis_vaudois'},
 'Le_Moustique_(Vevey)': {'alias': 'Moustique',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': 'Le_Moustique_(Vevey)'},
 'La_Bombe': {'alias': 'Bombe',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'La_Bombe'},
 'Le_Veveysan_1': {'alias': 'VVS1',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': 'Le_Veveysan_1'},
 'Journal_de_vevey_et_des_étrangers': {'alias': 'JVE',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': 'Journal_de_vevey_et_des_Ã©trangers'},
 'La_Guêpe_[2]': {'alias': 'Guepe1887',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'La_GuÃªpe_[2]'},
 'La_Cancoire': {'alias': 'Cancoire',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'La_Cancoire'},
 'La_revue_agricole': {'alias': 'RLA',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'La_revue_agricole'},
 'Bulletins_du_Grand_Conseil': {'alias': 'RN',
  'file_type': 'json',
  'access_right': 'open_public'},
 "Feuille_d'avis_de_Morges_1": {'alias': 'FAM',
  'file_type': 'json',
  'access_right': 'open_public'},
 "Feuille_d'avis_de_Vevey_1": {'alias': 'FAV1',
  'file_type': 'json',
  'access_right': 'open_public'},
 "L'Echo_de_Morges": {'alias': 'EM',
  'file_type': 'json',
  'access_right': 'open_public'},
 "L'Estafette_Journal_suisse": {'alias': 'esta',
  'file_type': 'xml',
  'access_right': 'open_public'},
 'La_Patrie': {'alias': 'PAT',
  'file_type': 'json',
  'access_right': 'open_public'},
 'La_Veveysane': {'alias': 'VVS',
  'file_type': 'json',
  'access_right': 'open_public'},
 'Le_Nouvelliste_vaudois': {'alias': 'NV1',
  'file_type': 'xml',
  'access_right': 'open_public'},
 'Nouvelliste_vaudois_et_journal_national_suisse': {'alias': 'NV2',
  'file_type': 'xml',
  'access_right': 'open_public'},
 'Repertoires_de_Bulletins_du_Grand_Conseil': {'alias': 'RN1',
  'file_type': 'json',
  'access_right': 'open_public'},
 'Travaux_des_Constituantes': {'alias': 'RN2',
  'file_type': 'json',
  'access_right': 'open_public'}}

In [ ]:
access_rights_and_aliases_file = '../text_preparation/data/sample_data/BCUL/access_rights_and_aliases.json'

with open(access_rights_and_aliases_file, 'w', encoding='utf-8') as f_out:
    json.dump(ar_and_alias, f_out, ensure_ascii=False, indent=4)

Note all what is below is working or debug code for the next steps of the process. 
They might be useful in the future for refinement or debug so I keep them here but they are not necessary.

## Trying detect function

In [2]:
base_dir = '/mnt/project_impresso/original/BCUL/'

In [ ]:
access_rights_and_aliases_file = '../text_preparation/data/sample_data/BCUL/access_rights_and_aliases.json'
missing_ars = '../text_preparation/data/sample_data/BCUL/missing_aliases.json'

with open(access_rights_and_aliases_file, "rb") as f:
        ar_and_alias = json.load(f)

with open(missing_ars, "rb") as f:
        missing_aliases = json.load(f)

In [4]:
ar_and_alias

{'Mercure_suisse': {'alias': 'ME',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'Mercure_suisse'},
 'Nouvelliste_suisse': {'alias': 'NS',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'Nouvelliste_suisse'},
 'Journal_helvétique': {'alias': 'JH',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'Journal_helvÃ©tique'},
 'Messager_boîteux': {'alias': 'MB',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'Messager_boÃ®teux'},
 'L’ami_de_la_vérité__journal_du_Canton_de_Vaud': {'alias': 'NV',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'Lâ\x80\x99ami_de_la_vÃ©ritÃ©__journal_du_Canton_de_Vaud'},
 'Almanach_pour_le_commerce': {'alias': 'ACI',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'Almanach_pour_le_commerce'},
 'Le_Père_Jérôme': {'alias': 'PJ',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'Le_PÃ¨re_JÃ©rÃ´me'},
 'Le_Charivari_[1]': {'alias': 'Charivari',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'Le_Charivari_[1]'},
 'Le_Phare_de_Nyon': {'alias': 'PDN',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': 'Le_Phare_de_Nyon'},
 'Le_Phare_du_Léman': {'alias': 'PDL',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': 'Le_Phare_du_LÃ©man'},
 "Journal_d'Yverdon_2": {'alias': 'JY2',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': "Journal_d'Yverdon_2"},
 "Feuille_d'avis_de_Payerne": {'alias': 'feuilleP',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': "Feuille_d'avis_de_Payerne"},
 'Le_Grelot': {'alias': 'Grelot',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'Le_Grelot'},
 'Le_peuple_souverain': {'alias': 'PS',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': 'Le_peuple_souverain'},
 "Feuille_d'avis_de_Payerne,_Moudon_et_Avenches": {'alias': 'feuillePMA',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': "Feuille_d'avis_de_Payerne,_Moudon_et_Avenches"},
 'La_Guêpe_[1]': {'alias': 'Guepe1851',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'La_GuÃªpe_[1]'},
 "Feuille_d'avis_de_Moudon": {'alias': 'FAMDE',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': "Feuille_d'avis_de_Moudon"},
 "L'Observateur_du_Léman": {'alias': 'OBS',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': "L'Observateur_du_LÃ©man"},
 'La_Griffe': {'alias': 'Griffe',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'La_Griffe'},
 "Feuille_d'avis_de_Nyon": {'alias': 'FAN',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': "Feuille_d'avis_de_Nyon"},
 'Gazette_des_Villages': {'alias': 'GAVi',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': 'Gazette_des_Villages'},
 'La_Fronde': {'alias': 'Fronde',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'La_Fronde'},
 'Le_Charivari_[2]': {'alias': 'CharivariCH',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'Le_Charivari_[2]'},
 'Castigat_ridendo_mores': {'alias': 'Castigat',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'Castigat_ridendo_mores'},
 'Le_Moniteur': {'alias': 'Moniteur',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'Le_Moniteur'},
 'Le_messager': {'alias': 'MESSAGER',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': 'Le_messager'},
 'Le_Ouistiti': {'alias': 'ouistiti',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'Le_Ouistiti'},
 'Le_Touriste__La_Suisse_illustrée': {'alias': 'TouSuIl',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': 'Le_Touriste__La_Suisse_illustrÃ©e'},
 'Journal_de_Vevey': {'alias': 'JV',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': 'Journal_de_Vevey'},
 'Indicateur_de_Lausanne': {'alias': 'AV',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'Indicateur_de_Lausanne'},
 'Courrier_du_Léman': {'alias': 'CL',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': 'Courrier_du_LÃ©man'},
 'Croquis_vaudois': {'alias': 'Croquis',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'Croquis_vaudois'},
 'Le_Moustique_(Vevey)': {'alias': 'Moustique',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': 'Le_Moustique_(Vevey)'},
 'La_Bombe': {'alias': 'Bombe',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'La_Bombe'},
 'Le_Veveysan_1': {'alias': 'VVS1',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': 'Le_Veveysan_1'},
 'Journal_de_vevey_et_des_étrangers': {'alias': 'JVE',
  'file_type': 'json',
  'access_right': 'open_public',
  'bin_title': 'Journal_de_vevey_et_des_Ã©trangers'},
 'La_Guêpe_[2]': {'alias': 'Guepe1887',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'La_GuÃªpe_[2]'},
 'La_Cancoire': {'alias': 'Cancoire',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'La_Cancoire'},
 'La_revue_agricole': {'alias': 'RLA',
  'file_type': 'xml',
  'access_right': 'open_public',
  'bin_title': 'La_revue_agricole'}}

In [5]:
missing_aliases

{'Almanach_pour_le_commerce': ['Almanach_pour_le_commerce',
  {'alias': 'ACI', 'file_type': 'xml', 'access_right': 'open_public'}],
 'Castigat_ridendo_mores': ['Castigat_ridendo_mores',
  {'alias': 'Castigat', 'file_type': 'xml', 'access_right': 'open_public'}],
 'Croquis_vaudois': ['Croquis_vaudois',
  {'alias': 'Croquis', 'file_type': 'xml', 'access_right': 'open_public'}],
 'Courrier_du_Léman': ['Courrier_du_Léman', None],
 "Feuille_d'avis_de_Moudon": ["Feuille_d'avis_de_Moudon",
  {'alias': 'FAMDE', 'file_type': 'json', 'access_right': 'open_public'}],
 "Feuille_d'avis_de_Nyon": ["Feuille_d'avis_de_Nyon",
  {'alias': 'FAN', 'file_type': 'json', 'access_right': 'open_public'}],
 "Feuille_d'avis_de_Payerne,_Moudon_et_Avenches": ["Feuille_d'avis_de_Payerne,_Moudon_et_Avenches",
  {'alias': 'feuillePMA', 'file_type': 'json', 'access_right': 'open_public'}],
 "Feuille_d'avis_de_Payerne": ["Feuille_d'avis_de_Payerne",
  {'alias': 'feuilleP', 'file_type': 'json', 'access_right': 'open_public'}],
 'Gazette_des_Villages': ['Gazette_des_Villages',
  {'alias': 'GAVi', 'file_type': 'json', 'access_right': 'open_public'}],
 'Indicateur_de_Lausanne': ['Indicateur_de_Lausanne',
  {'alias': 'AV', 'file_type': 'xml', 'access_right': 'open_public'}],
 "Journal_d'Yverdon_2": ["Journal_d'Yverdon_2",
  {'alias': 'JY2', 'file_type': 'json', 'access_right': 'open_public'}],
 'Journal_de_Vevey': ['Journal_de_Vevey',
  {'alias': 'JV', 'file_type': 'json', 'access_right': 'open_public'}],
 'Journal_de_vevey_et_des_étrangers': ['Journal_de_vevey_et_des_étrangers',
  None],
 'Journal_helvétique': ['Journal_helvétique', None],
 "L'Observateur_du_Léman": ["L'Observateur_du_Léman", None],
 'La_Bombe': ['La_Bombe',
  {'alias': 'Bombe', 'file_type': 'xml', 'access_right': 'open_public'}],
 'La_Cancoire': ['La_Cancoire',
  {'alias': 'Cancoire', 'file_type': 'xml', 'access_right': 'open_public'}],
 'La_Fronde': ['La_Fronde',
  {'alias': 'Fronde', 'file_type': 'xml', 'access_right': 'open_public'}],
 'La_Griffe': ['La_Griffe',
  {'alias': 'Griffe', 'file_type': 'xml', 'access_right': 'open_public'}],
 'La_Guêpe_[1]': ['La_Guêpe_[1]', None],
 'La_Guêpe_[2]': ['La_Guêpe_[2]', None],
 'La_Veveysanne_–_La_Patrie': ['La_Veveysanne_–_La_Patrie', None],
 'La_revue_agricole': ['La_revue_agricole',
  {'alias': 'RLA', 'file_type': 'xml', 'access_right': 'open_public'}],
 'Le_Charivari_[1]': ['Le_Charivari_[1]',
  {'alias': 'Charivari', 'file_type': 'xml', 'access_right': 'open_public'}],
 'Le_Charivari_[2]': ['Le_Charivari_[2]',
  {'alias': 'CharivariCH', 'file_type': 'xml', 'access_right': 'open_public'}],
 'Le_Grelot': ['Le_Grelot',
  {'alias': 'Grelot', 'file_type': 'xml', 'access_right': 'open_public'}],
 'Le_Moniteur': ['Le_Moniteur',
  {'alias': 'Moniteur', 'file_type': 'xml', 'access_right': 'open_public'}],
 'Le_Moustique_(Vevey)': ['Le_Moustique_(Vevey)',
  {'alias': 'Moustique', 'file_type': 'json', 'access_right': 'open_public'}],
 'Le_Ouistiti': ['Le_Ouistiti',
  {'alias': 'ouistiti', 'file_type': 'xml', 'access_right': 'open_public'}],
 'Le_Phare_de_Nyon': ['Le_Phare_de_Nyon',
  {'alias': 'PDN', 'file_type': 'json', 'access_right': 'open_public'}],
 'Le_Phare_du_Léman': ['Le_Phare_du_Léman', None],
 'Le_Père_Jérôme': ['Le_Père_Jérôme', None],
 'Le_Touriste__La_Suisse_illustrée': ['Le_Touriste__La_Suisse_illustrée',
  None],
 'Le_Veveysan_1': ['Le_Veveysan_1',
  {'alias': 'VVS1', 'file_type': 'json', 'access_right': 'open_public'}],
 'Le_messager': ['Le_messager',
  {'alias': 'MESSAGER', 'file_type': 'json', 'access_right': 'open_public'}],
 'Le_peuple_souverain': ['Le_peuple_souverain',
  {'alias': 'PS', 'file_type': 'json', 'access_right': 'open_public'}],
 'L’ami_de_la_vérité__journal_du_Canton_de_Vaud': ['L’ami_de_la_vérité__journal_du_Canton_de_Vaud',
  None],
 'Mercure_suisse': ['Mercure_suisse',
  {'alias': 'ME', 'file_type': 'xml', 'access_right': 'open_public'}],
 'Messager_boîteux': ['Messager_boîteux', None],
 'Nouvelliste_suisse': ['Nouvelliste_suisse',
  {'alias': 'NS', 'file_type': 'xml', 'access_right': 'open_public'}],
 'Bulletins_du_Grand_Conseil': ['Bulletins_du_Grand_Conseil', None]}

In [40]:
def find_LCS(s1, s2):
    res = pylcs.lcs_string_idx(s1, s2)
    return ''.join([s2[i] for i in res if i != -1])

In [41]:
for k, v in ar_and_alias.items():
    print(f"-{k}:")
    v['matches'] = []
    v['lcs'] = {}
    for mk, mv in missing_aliases.items():
        if mv[1] is not None:
            if mv[1]['alias'] == v['alias']:
                print(f'  title added to {k}', mk)
                v['title'] = mk
                del v['lcs']
                del v['matches']
                break
        else:
            lcs = find_LCS(k, mk)
            v['lcs'][mk] = lcs
            if k.split('_')[0] == mk.split('_')[0]:
                print(f"  Potential match: {k} and {mk}")
                v['matches'].append(mk)
                if k[-2] == mk[-2]:
                    print(f"  ! VERY Potential match: {k} and {mk}")
                    v['matches'] = [mk]
            elif k.split('_')[-1] == mk.split('_')[-1]:
                print(f"  Potential match: {k} and {mk}")
                v['matches'].append(mk)

    if 'matches' in v and len(v['matches']) == 1:
        print(f"will add title {v['matches']} to {k}")
        v['title'] = v['matches'][0]
        del v['lcs']
        del v['matches']
    elif 'lcs' in v:
        max_l = 0
        title = ''
        for m in v['matches']:
            if len(v['lcs'][m]) > max_l:
                max_l = len(v['lcs'][m])
                title = m
        print(f"will add title {title} to {k}")
        v['title'] = title
        del v['lcs']
        del v['matches']

            #print(f'title missing for {k}', mk, str(mk), str(k))

-Mercure_suisse:
  title added to Mercure_suisse Mercure_suisse
-Nouvelliste_suisse:
  title added to Nouvelliste_suisse Nouvelliste_suisse
-Journal_helvÃ©tique:
  Potential match: Journal_helvÃ©tique and Journal_de_vevey_et_des_étrangers
  Potential match: Journal_helvÃ©tique and Journal_helvétique
  ! VERY Potential match: Journal_helvÃ©tique and Journal_helvétique
will add title ['Journal_helvétique'] to Journal_helvÃ©tique
-Messager_boÃ®teux:
  Potential match: Messager_boÃ®teux and Messager_boîteux
  ! VERY Potential match: Messager_boÃ®teux and Messager_boîteux
will add title ['Messager_boîteux'] to Messager_boÃ®teux
-Lâami_de_la_vÃ©ritÃ©__journal_du_Canton_de_Vaud:
  Potential match: Lâami_de_la_vÃ©ritÃ©__journal_du_Canton_de_Vaud and L’ami_de_la_vérité__journal_du_Canton_de_Vaud
will add title ['L’ami_de_la_vérité__journal_du_Canton_de_Vaud'] to Lâami_de_la_vÃ©ritÃ©__journal_du_Canton_de_Vaud
-Almanach_pour_le_commerce:
  title added to Almanach_pour_le_commerce Almanach_pour_le_commerce
-Le_PÃ¨re_JÃ©rÃ´me:
  Potential match: Le_PÃ¨re_JÃ©rÃ´me and Le_Phare_du_Léman
  Potential match: Le_PÃ¨re_JÃ©rÃ´me and Le_Père_Jérôme
  ! VERY Potential match: Le_PÃ¨re_JÃ©rÃ´me and Le_Père_Jérôme
  Potential match: Le_PÃ¨re_JÃ©rÃ´me and Le_Touriste__La_Suisse_illustrée
will add title Le_Père_Jérôme to Le_PÃ¨re_JÃ©rÃ´me
-Le_Charivari_[1]:
  Potential match: Le_Charivari_[1] and La_Guêpe_[1]
  title added to Le_Charivari_[1] Le_Charivari_[1]
-Le_Phare_de_Nyon:
  title added to Le_Phare_de_Nyon Le_Phare_de_Nyon
-Le_Phare_du_LÃ©man:
  Potential match: Le_Phare_du_LÃ©man and Le_Phare_du_Léman
  ! VERY Potential match: Le_Phare_du_LÃ©man and Le_Phare_du_Léman
  Potential match: Le_Phare_du_LÃ©man and Le_Père_Jérôme
  Potential match: Le_Phare_du_LÃ©man and Le_Touriste__La_Suisse_illustrée
will add title Le_Phare_du_Léman to Le_Phare_du_LÃ©man
-Journal_d'Yverdon_2:
  title added to Journal_d'Yverdon_2 Journal_d'Yverdon_2
-Feuille_d'avis_de_Payerne:
  title added to Feuille_d'avis_de_Payerne Feuille_d'avis_de_Payerne
-Le_Grelot:
  title added to Le_Grelot Le_Grelot
-Le_peuple_souverain:
  Potential match: Le_peuple_souverain and Le_Phare_du_Léman
  Potential match: Le_peuple_souverain and Le_Père_Jérôme
  Potential match: Le_peuple_souverain and Le_Touriste__La_Suisse_illustrée
  title added to Le_peuple_souverain Le_peuple_souverain
-Feuille_d'avis_de_Payerne,_Moudon_et_Avenches:
  title added to Feuille_d'avis_de_Payerne,_Moudon_et_Avenches Feuille_d'avis_de_Payerne,_Moudon_et_Avenches
-La_GuÃªpe_[1]:
  Potential match: La_GuÃªpe_[1] and La_Guêpe_[1]
  ! VERY Potential match: La_GuÃªpe_[1] and La_Guêpe_[1]
  Potential match: La_GuÃªpe_[1] and La_Guêpe_[2]
  Potential match: La_GuÃªpe_[1] and La_Veveysanne_–_La_Patrie
will add title La_Guêpe_[1] to La_GuÃªpe_[1]
-Feuille_d'avis_de_Moudon:
  title added to Feuille_d'avis_de_Moudon Feuille_d'avis_de_Moudon
-L'Observateur_du_LÃ©man:
  Potential match: L'Observateur_du_LÃ©man and L'Observateur_du_Léman
  ! VERY Potential match: L'Observateur_du_LÃ©man and L'Observateur_du_Léman
will add title ["L'Observateur_du_Léman"] to L'Observateur_du_LÃ©man
-La_Griffe:
  title added to La_Griffe La_Griffe
-Feuille_d'avis_de_Nyon:
  title added to Feuille_d'avis_de_Nyon Feuille_d'avis_de_Nyon
-Gazette_des_Villages:
  title added to Gazette_des_Villages Gazette_des_Villages
-La_Fronde:
  title added to La_Fronde La_Fronde
-Le_Charivari_[2]:
  Potential match: Le_Charivari_[2] and La_Guêpe_[2]
  title added to Le_Charivari_[2] Le_Charivari_[2]
-Castigat_ridendo_mores:
  title added to Castigat_ridendo_mores Castigat_ridendo_mores
-Le_Moniteur:
  title added to Le_Moniteur Le_Moniteur
-Le_messager:
  Potential match: Le_messager and Le_Phare_du_Léman
  Potential match: Le_messager and Le_Père_Jérôme
  Potential match: Le_messager and Le_Touriste__La_Suisse_illustrée
  title added to Le_messager Le_messager
-Le_Ouistiti:
  title added to Le_Ouistiti Le_Ouistiti
-Le_Touriste__La_Suisse_illustrÃ©e:
  Potential match: Le_Touriste__La_Suisse_illustrÃ©e and Le_Phare_du_Léman
  Potential match: Le_Touriste__La_Suisse_illustrÃ©e and Le_Père_Jérôme
  Potential match: Le_Touriste__La_Suisse_illustrÃ©e and Le_Touriste__La_Suisse_illustrée
will add title Le_Touriste__La_Suisse_illustrée to Le_Touriste__La_Suisse_illustrÃ©e
-Journal_de_Vevey:
  title added to Journal_de_Vevey Journal_de_Vevey
-Indicateur_de_Lausanne:
  title added to Indicateur_de_Lausanne Indicateur_de_Lausanne
-Courrier_du_LÃ©man:
  Potential match: Courrier_du_LÃ©man and Courrier_du_Léman
  ! VERY Potential match: Courrier_du_LÃ©man and Courrier_du_Léman
will add title ['Courrier_du_Léman'] to Courrier_du_LÃ©man
-Croquis_vaudois:
  title added to Croquis_vaudois Croquis_vaudois
-Le_Moustique_(Vevey):
  title added to Le_Moustique_(Vevey) Le_Moustique_(Vevey)
-La_Bombe:
  title added to La_Bombe La_Bombe
-Le_Veveysan_1:
  Potential match: Le_Veveysan_1 and Le_Phare_du_Léman
  Potential match: Le_Veveysan_1 and Le_Père_Jérôme
  Potential match: Le_Veveysan_1 and Le_Touriste__La_Suisse_illustrée
  title added to Le_Veveysan_1 Le_Veveysan_1
-Journal_de_vevey_et_des_Ã©trangers:
  Potential match: Journal_de_vevey_et_des_Ã©trangers and Journal_de_vevey_et_des_étrangers
  ! VERY Potential match: Journal_de_vevey_et_des_Ã©trangers and Journal_de_vevey_et_des_étrangers
  Potential match: Journal_de_vevey_et_des_Ã©trangers and Journal_helvétique
will add title Journal_de_vevey_et_des_étrangers to Journal_de_vevey_et_des_Ã©trangers
-La_GuÃªpe_[2]:
  Potential match: La_GuÃªpe_[2] and La_Guêpe_[1]
  Potential match: La_GuÃªpe_[2] and La_Guêpe_[2]
  ! VERY Potential match: La_GuÃªpe_[2] and La_Guêpe_[2]
  Potential match: La_GuÃªpe_[2] and La_Veveysanne_–_La_Patrie
will add title La_Guêpe_[2] to La_GuÃªpe_[2]
-La_Cancoire:
  title added to La_Cancoire La_Cancoire
-La_revue_agricole:
  Potential match: La_revue_agricole and La_Guêpe_[1]
  Potential match: La_revue_agricole and La_Guêpe_[2]
  Potential match: La_revue_agricole and La_Veveysanne_–_La_Patrie
  title added to La_revue_agricole La_revue_agricole

In [43]:
new_ar_and_alias = {}
for k, v in ar_and_alias.items():
    title = v['title']
    del v['title']
    v['bin_title'] = k
    new_ar_and_alias[title] = v

In [45]:
access_rights_and_aliases_file = '/home/piconti/impresso-text-acquisition/text_importer/data/sample_data/BCUL/access_rights_and_aliases.json'

with open(access_rights_and_aliases_file, 'w', encoding='utf-8') as f_out:
    json.dump(new_ar_and_alias, f_out, ensure_ascii=False, indent=4)

In [42]:
ar_and_alias

{'Mercure_suisse': {'alias': 'ME',
  'file_type': 'xml',
  'access_right': 'open_public',
  'title': 'Mercure_suisse'},
 'Nouvelliste_suisse': {'alias': 'NS',
  'file_type': 'xml',
  'access_right': 'open_public',
  'title': 'Nouvelliste_suisse'},
 'Journal_helvÃ©tique': {'alias': 'JH',
  'file_type': 'xml',
  'access_right': 'open_public',
  'title': 'Journal_helvétique'},
 'Messager_boÃ®teux': {'alias': 'MB',
  'file_type': 'xml',
  'access_right': 'open_public',
  'title': 'Messager_boîteux'},
 'Lâ\x80\x99ami_de_la_vÃ©ritÃ©__journal_du_Canton_de_Vaud': {'alias': 'NV',
  'file_type': 'xml',
  'access_right': 'open_public',
  'title': 'L’ami_de_la_vérité__journal_du_Canton_de_Vaud'},
 'Almanach_pour_le_commerce': {'alias': 'ACI',
  'file_type': 'xml',
  'access_right': 'open_public',
  'title': 'Almanach_pour_le_commerce'},
 'Le_PÃ¨re_JÃ©rÃ´me': {'alias': 'PJ',
  'file_type': 'xml',
  'access_right': 'open_public',
  'title': 'Le_Père_Jérôme'},
 'Le_Charivari_[1]': {'alias': 'Charivari',
  'file_type': 'xml',
  'access_right': 'open_public',
  'title': 'Le_Charivari_[1]'},
 'Le_Phare_de_Nyon': {'alias': 'PDN',
  'file_type': 'json',
  'access_right': 'open_public',
  'title': 'Le_Phare_de_Nyon'},
 'Le_Phare_du_LÃ©man': {'alias': 'PDL',
  'file_type': 'json',
  'access_right': 'open_public',
  'title': 'Le_Phare_du_Léman'},
 "Journal_d'Yverdon_2": {'alias': 'JY2',
  'file_type': 'json',
  'access_right': 'open_public',
  'title': "Journal_d'Yverdon_2"},
 "Feuille_d'avis_de_Payerne": {'alias': 'feuilleP',
  'file_type': 'json',
  'access_right': 'open_public',
  'title': "Feuille_d'avis_de_Payerne"},
 'Le_Grelot': {'alias': 'Grelot',
  'file_type': 'xml',
  'access_right': 'open_public',
  'title': 'Le_Grelot'},
 'Le_peuple_souverain': {'alias': 'PS',
  'file_type': 'json',
  'access_right': 'open_public',
  'title': 'Le_peuple_souverain'},
 "Feuille_d'avis_de_Payerne,_Moudon_et_Avenches": {'alias': 'feuillePMA',
  'file_type': 'json',
  'access_right': 'open_public',
  'title': "Feuille_d'avis_de_Payerne,_Moudon_et_Avenches"},
 'La_GuÃªpe_[1]': {'alias': 'Guepe1851',
  'file_type': 'xml',
  'access_right': 'open_public',
  'title': 'La_Guêpe_[1]'},
 "Feuille_d'avis_de_Moudon": {'alias': 'FAMDE',
  'file_type': 'json',
  'access_right': 'open_public',
  'title': "Feuille_d'avis_de_Moudon"},
 "L'Observateur_du_LÃ©man": {'alias': 'OBS',
  'file_type': 'json',
  'access_right': 'open_public',
  'title': "L'Observateur_du_Léman"},
 'La_Griffe': {'alias': 'Griffe',
  'file_type': 'xml',
  'access_right': 'open_public',
  'title': 'La_Griffe'},
 "Feuille_d'avis_de_Nyon": {'alias': 'FAN',
  'file_type': 'json',
  'access_right': 'open_public',
  'title': "Feuille_d'avis_de_Nyon"},
 'Gazette_des_Villages': {'alias': 'GAVi',
  'file_type': 'json',
  'access_right': 'open_public',
  'title': 'Gazette_des_Villages'},
 'La_Fronde': {'alias': 'Fronde',
  'file_type': 'xml',
  'access_right': 'open_public',
  'title': 'La_Fronde'},
 'Le_Charivari_[2]': {'alias': 'CharivariCH',
  'file_type': 'xml',
  'access_right': 'open_public',
  'title': 'Le_Charivari_[2]'},
 'Castigat_ridendo_mores': {'alias': 'Castigat',
  'file_type': 'xml',
  'access_right': 'open_public',
  'title': 'Castigat_ridendo_mores'},
 'Le_Moniteur': {'alias': 'Moniteur',
  'file_type': 'xml',
  'access_right': 'open_public',
  'title': 'Le_Moniteur'},
 'Le_messager': {'alias': 'MESSAGER',
  'file_type': 'json',
  'access_right': 'open_public',
  'title': 'Le_messager'},
 'Le_Ouistiti': {'alias': 'ouistiti',
  'file_type': 'xml',
  'access_right': 'open_public',
  'title': 'Le_Ouistiti'},
 'Le_Touriste__La_Suisse_illustrÃ©e': {'alias': 'TouSuIl',
  'file_type': 'json',
  'access_right': 'open_public',
  'title': 'Le_Touriste__La_Suisse_illustrée'},
 'Journal_de_Vevey': {'alias': 'JV',
  'file_type': 'json',
  'access_right': 'open_public',
  'title': 'Journal_de_Vevey'},
 'Indicateur_de_Lausanne': {'alias': 'AV',
  'file_type': 'xml',
  'access_right': 'open_public',
  'title': 'Indicateur_de_Lausanne'},
 'Courrier_du_LÃ©man': {'alias': 'CL',
  'file_type': 'json',
  'access_right': 'open_public',
  'title': 'Courrier_du_Léman'},
 'Croquis_vaudois': {'alias': 'Croquis',
  'file_type': 'xml',
  'access_right': 'open_public',
  'title': 'Croquis_vaudois'},
 'Le_Moustique_(Vevey)': {'alias': 'Moustique',
  'file_type': 'json',
  'access_right': 'open_public',
  'title': 'Le_Moustique_(Vevey)'},
 'La_Bombe': {'alias': 'Bombe',
  'file_type': 'xml',
  'access_right': 'open_public',
  'title': 'La_Bombe'},
 'Le_Veveysan_1': {'alias': 'VVS1',
  'file_type': 'json',
  'access_right': 'open_public',
  'title': 'Le_Veveysan_1'},
 'Journal_de_vevey_et_des_Ã©trangers': {'alias': 'JVE',
  'file_type': 'json',
  'access_right': 'open_public',
  'title': 'Journal_de_vevey_et_des_étrangers'},
 'La_GuÃªpe_[2]': {'alias': 'Guepe1887',
  'file_type': 'xml',
  'access_right': 'open_public',
  'title': 'La_Guêpe_[2]'},
 'La_Cancoire': {'alias': 'Cancoire',
  'file_type': 'xml',
  'access_right': 'open_public',
  'title': 'La_Cancoire'},
 'La_revue_agricole': {'alias': 'RLA',
  'file_type': 'xml',
  'access_right': 'open_public',
  'title': 'La_revue_agricole'}}

In [5]:
for j_dir in os.listdir(base_dir): 
    if j_dir not in ['OLD', 'wrong_BCUL', '.DS_Store']:
        if j_dir in ar_and_alias:
            print(j_dir, "OK: ", ar_and_alias[j_dir])
        else:
            print(j_dir, 'NOT OK!')

Almanach_pour_le_commerce OK:  {'alias': 'ACI', 'file_type': 'xml', 'access_right': 'open_public'}
Castigat_ridendo_mores OK:  {'alias': 'Castigat', 'file_type': 'xml', 'access_right': 'open_public'}
Croquis_vaudois OK:  {'alias': 'Croquis', 'file_type': 'xml', 'access_right': 'open_public'}
Courrier_du_LÃ©man OK:  {'alias': 'CL', 'file_type': 'json', 'access_right': 'open_public'}
Feuille_d'avis_de_Moudon OK:  {'alias': 'FAMDE', 'file_type': 'json', 'access_right': 'open_public'}
Feuille_d'avis_de_Nyon OK:  {'alias': 'FAN', 'file_type': 'json', 'access_right': 'open_public'}
Feuille_d'avis_de_Payerne,_Moudon_et_Avenches OK:  {'alias': 'feuillePMA', 'file_type': 'json', 'access_right': 'open_public'}
Feuille_d'avis_de_Payerne OK:  {'alias': 'feuilleP', 'file_type': 'json', 'access_right': 'open_public'}
Gazette_des_Villages OK:  {'alias': 'GAVi', 'file_type': 'json', 'access_right': 'open_public'}
Indicateur_de_Lausanne OK:  {'alias': 'AV', 'file_type': 'xml', 'access_right': 'open_public'}
Journal_d'Yverdon_2 OK:  {'alias': 'JY2', 'file_type': 'json', 'access_right': 'open_public'}
Journal_de_Vevey OK:  {'alias': 'JV', 'file_type': 'json', 'access_right': 'open_public'}
Journal_de_vevey_et_des_Ã©trangers OK:  {'alias': 'JVE', 'file_type': 'json', 'access_right': 'open_public'}
Journal_helvÃ©tique OK:  {'alias': 'JH', 'file_type': 'xml', 'access_right': 'open_public'}
L'Observateur_du_LÃ©man OK:  {'alias': 'OBS', 'file_type': 'json', 'access_right': 'open_public'}
La_Bombe OK:  {'alias': 'Bombe', 'file_type': 'xml', 'access_right': 'open_public'}
La_Cancoire OK:  {'alias': 'Cancoire', 'file_type': 'xml', 'access_right': 'open_public'}
La_Fronde OK:  {'alias': 'Fronde', 'file_type': 'xml', 'access_right': 'open_public'}
La_Griffe OK:  {'alias': 'Griffe', 'file_type': 'xml', 'access_right': 'open_public'}
La_GuÃªpe_[1] OK:  {'alias': 'Guepe1851', 'file_type': 'xml', 'access_right': 'open_public'}
La_GuÃªpe_[2] OK:  {'alias': 'Guepe1887', 'file_type': 'xml', 'access_right': 'open_public'}
La_Veveysanne_â_La_Patrie NOT OK!
La_revue_agricole OK:  {'alias': 'RLA', 'file_type': 'xml', 'access_right': 'open_public'}
Le_Charivari_[1] OK:  {'alias': 'Charivari', 'file_type': 'xml', 'access_right': 'open_public'}
Le_Charivari_[2] OK:  {'alias': 'CharivariCH', 'file_type': 'xml', 'access_right': 'open_public'}
Le_Grelot OK:  {'alias': 'Grelot', 'file_type': 'xml', 'access_right': 'open_public'}
Le_Moniteur OK:  {'alias': 'Moniteur', 'file_type': 'xml', 'access_right': 'open_public'}
Le_Moustique_(Vevey) OK:  {'alias': 'Moustique', 'file_type': 'json', 'access_right': 'open_public'}
Le_Ouistiti OK:  {'alias': 'ouistiti', 'file_type': 'xml', 'access_right': 'open_public'}
Le_Phare_de_Nyon OK:  {'alias': 'PDN', 'file_type': 'json', 'access_right': 'open_public'}
Le_Phare_du_LÃ©man OK:  {'alias': 'PDL', 'file_type': 'json', 'access_right': 'open_public'}
Le_PÃ¨re_JÃ©rÃ´me OK:  {'alias': 'PJ', 'file_type': 'xml', 'access_right': 'open_public'}
Le_Touriste__La_Suisse_illustrÃ©e OK:  {'alias': 'TouSuIl', 'file_type': 'json', 'access_right': 'open_public'}
Le_Veveysan_1 OK:  {'alias': 'VVS1', 'file_type': 'json', 'access_right': 'open_public'}
Le_messager OK:  {'alias': 'MESSAGER', 'file_type': 'json', 'access_right': 'open_public'}
Le_peuple_souverain OK:  {'alias': 'PS', 'file_type': 'json', 'access_right': 'open_public'}
Lâami_de_la_vÃ©ritÃ©__journal_du_Canton_de_Vaud OK:  {'alias': 'NV', 'file_type': 'xml', 'access_right': 'open_public'}
Mercure_suisse OK:  {'alias': 'ME', 'file_type': 'xml', 'access_right': 'open_public'}
Messager_boÃ®teux OK:  {'alias': 'MB', 'file_type': 'xml', 'access_right': 'open_public'}
Nouvelliste_suisse OK:  {'alias': 'NS', 'file_type': 'xml', 'access_right': 'open_public'}
Bulletins_du_Grand_Conseil NOT OK!

In [4]:
all([name in dirs for name in batch_1_titles['unicode_name_in_fs'] if name is not None])

NameError: name 'batch_1_titles' is not defined

In [9]:
def parse_date(mit_filename: str) -> tuple[date, str]:
    """Given the Mit filename, parse the Journal name and the date.

    Args:
        mit_filename (str): Filename of the 'mit' file.

    Returns:
        Tuple[date, str]: Publication date of the issue, and journal name.
    """
    split = mit_filename.split('/')
    # extract date of publication
    year, month, day = int(split[-5]), int(split[-4]), int(split[-3])
    #normalize the month & day values if they are out of range
    month = max(min(month, 12), 1)
    day = max(min(day, 31), 1)

    # extract journal name alias
    #basename = os.path.splitext(split[-1])[0]
    #journal_alias = replace_alias(basename.split('_')[0], split[-6])
    
    return datetime(year, month, day).date() #, journal_alias

In [25]:
from collections import namedtuple
BculIssueDir = namedtuple(
    "IssueDirectory", ["journal", "date", "edition", "path", "rights", "mit_file_type"]
)

In [26]:
def dir2issue(path: str, journal_info: dict[str, str]) -> BculIssueDir:
    """Create a `BculIssueDir` object from a directory.

    Note:
        This function is called internally by `detect_issues`

    Args:
        path (str): The path of the issue.
        access_rights (dict): Dictionary for access rights.

    Returns:
        Optional[BculIssueDir]: New `BculIssueDir` object.
    """
    mit_file = find_mit_file(path)
    if mit_file is None:
        logger.error("Could not find MIT file in %s", path)
        return None

    if not mit_file.endswith(journal_info["file_type"]):
        logger.warning(
            "Found mit file %s does not correspond to mit file type %s",
            path,
            journal_info["file_type"],
        )
        # override the mit file type if the extension of the file found does not match
        journal_info["file_type"] = mit_file.split(".")[-1]

    date = parse_date(mit_file)

    return BculIssueDir(
        journal=journal_info["alias"],
        date=date,
        edition="a",
        path=path,
        rights=journal_info["access_right"],
        mit_file_type=journal_info["file_type"],
    )

In [19]:
ar_and_alias.keys()

dict_keys(['Mercure_suisse', 'Nouvelliste_suisse', 'Journal_helvÃ©tique', 'Messager_boÃ®teux', 'Lâ\x80\x99ami_de_la_vÃ©ritÃ©__journal_du_Canton_de_Vaud', 'Almanach_pour_le_commerce', 'Le_PÃ¨re_JÃ©rÃ´me', 'Le_Charivari_[1]', 'Le_Phare_de_Nyon', 'Le_Phare_du_LÃ©man', "Journal_d'Yverdon_2", "Feuille_d'avis_de_Payerne", 'Le_Grelot', 'Le_peuple_souverain', "Feuille_d'avis_de_Payerne,_Moudon_et_Avenches", 'La_GuÃªpe_[1]', "Feuille_d'avis_de_Moudon", "L'Observateur_du_LÃ©man", 'La_Griffe', "Feuille_d'avis_de_Nyon", 'Gazette_des_Villages', 'La_Fronde', 'Le_Charivari_[2]', 'Castigat_ridendo_mores', 'Le_Moniteur', 'Le_messager', 'Le_Ouistiti', 'Le_Touriste__La_Suisse_illustrÃ©e', 'Journal_de_Vevey', 'Indicateur_de_Lausanne', 'Courrier_du_LÃ©man', 'Croquis_vaudois', 'Le_Moustique_(Vevey)', 'La_Bombe', 'Le_Veveysan_1', 'Journal_de_vevey_et_des_Ã©trangers', 'La_GuÃªpe_[2]', 'La_Cancoire', 'La_revue_agricole'])

In [20]:
ar_and_alias['Courrier_du_LÃ©man']

{'alias': 'CL', 'file_type': 'json', 'access_right': 'open_public'}

In [33]:
dir_path, dirs, files = next(os.walk(base_dir))
    
journal_dirs = [os.path.join(dir_path, _dir) 
                for _dir in dirs 
                if _dir not in ['OLD', 'wrong_BCUL'] and _dir in ar_and_alias]

issue_dirs = []
for journal in journal_dirs:
    #journal_info = titles_as_dict[journal.split('/')[-1]]
    #logger.info(f"Detecting issues for {journal}.")
    for dir_path, dirs, files in os.walk(journal):
        if len(files)>1 and 'solr' not in dir_path:
            title = dir_path.replace(base_dir, '').split('/')[0]
            if title != journal.split('/')[-1]:
                print(title, journal)
            if title not in ar_and_alias:
                print(dir_path, title, title in ar_and_alias)
            else:
                print(dir2issue(dir_path, ar_and_alias[title]))
                issue_dirs.append((dir_path, ar_and_alias[title]))
            break

issues = []
for _dir in issue_dirs:
    i_dir= dir2issue(_dir)
    print(i_dir)
    issues.append(i_dir)
#issues = [dir2issue(_dir) for _dir in issue_dirs]

IssueDirectory(journal='ACI', date=datetime.date(1832, 1, 1), edition='a', path='/mnt/project_impresso/original/BCUL/Almanach_pour_le_commerce/1832/01/01/171722', rights='open_public', mit_file_type='xml')
IssueDirectory(journal='Castigat', date=datetime.date(1879, 11, 1), edition='a', path='/mnt/project_impresso/original/BCUL/Castigat_ridendo_mores/1879/11/01/170474', rights='open_public', mit_file_type='xml')
IssueDirectory(journal='Croquis', date=datetime.date(1884, 3, 1), edition='a', path='/mnt/project_impresso/original/BCUL/Croquis_vaudois/1884/03/01/126485', rights='open_public', mit_file_type='xml')
IssueDirectory(journal='CL', date=datetime.date(1882, 9, 30), edition='a', path='/mnt/project_impresso/original/BCUL/Courrier_du_LÃ©man/1882/09/30/257141', rights='open_public', mit_file_type='json')
IssueDirectory(journal='FAMDE', date=datetime.date(1859, 2, 5), edition='a', path="/mnt/project_impresso/original/BCUL/Feuille_d'avis_de_Moudon/1859/02/05/539294", rights='open_public', mit_file_type='json')
IssueDirectory(journal='FAN', date=datetime.date(1849, 9, 15), edition='a', path="/mnt/project_impresso/original/BCUL/Feuille_d'avis_de_Nyon/1849/09/15/522214", rights='open_public', mit_file_type='json')
IssueDirectory(journal='feuillePMA', date=datetime.date(1852, 12, 25), edition='a', path="/mnt/project_impresso/original/BCUL/Feuille_d'avis_de_Payerne,_Moudon_et_Avenches/1852/12/25/605182", rights='open_public', mit_file_type='json')
IssueDirectory(journal='feuilleP', date=datetime.date(1843, 4, 29), edition='a', path="/mnt/project_impresso/original/BCUL/Feuille_d'avis_de_Payerne/1843/04/29/605183", rights='open_public', mit_file_type='json')
IssueDirectory(journal='GAVi', date=datetime.date(1867, 8, 31), edition='a', path='/mnt/project_impresso/original/BCUL/Gazette_des_Villages/1867/08/31/590435', rights='open_public', mit_file_type='json')
IssueDirectory(journal='AV', date=datetime.date(1880, 1, 1), edition='a', path='/mnt/project_impresso/original/BCUL/Indicateur_de_Lausanne/1880/01/01/170197', rights='open_public', mit_file_type='xml')
IssueDirectory(journal='JY2', date=datetime.date(1842, 10, 8), edition='a', path="/mnt/project_impresso/original/BCUL/Journal_d'Yverdon_2/1842/10/08/315936", rights='open_public', mit_file_type='json')
IssueDirectory(journal='JV', date=datetime.date(1865, 8, 29), edition='a', path='/mnt/project_impresso/original/BCUL/Journal_de_Vevey/1865/08/29/246382', rights='open_public', mit_file_type='json')
IssueDirectory(journal='JVE', date=datetime.date(1891, 4, 4), edition='a', path='/mnt/project_impresso/original/BCUL/Journal_de_vevey_et_des_Ã©trangers/1891/04/04/258492', rights='open_public', mit_file_type='json')
IssueDirectory(journal='JH', date=datetime.date(1738, 1, 1), edition='a', path='/mnt/project_impresso/original/BCUL/Journal_helvÃ©tique/1738/01/01/127826', rights='open_public', mit_file_type='xml')
IssueDirectory(journal='OBS', date=datetime.date(1865, 3, 25), edition='a', path="/mnt/project_impresso/original/BCUL/L'Observateur_du_LÃ©man/1865/03/25/255571", rights='open_public', mit_file_type='json')
IssueDirectory(journal='Bombe', date=datetime.date(1889, 11, 15), edition='a', path='/mnt/project_impresso/original/BCUL/La_Bombe/1889/11/15/126860', rights='open_public', mit_file_type='xml')
IssueDirectory(journal='Cancoire', date=datetime.date(1898, 1, 8), edition='a', path='/mnt/project_impresso/original/BCUL/La_Cancoire/1898/01/08/126862', rights='open_public', mit_file_type='xml')
IssueDirectory(journal='Fronde', date=datetime.date(1872, 3, 17), edition='a', path='/mnt/project_impresso/original/BCUL/La_Fronde/1872/03/17/126902', rights='open_public', mit_file_type='xml')
IssueDirectory(journal='Griffe', date=datetime.date(1864, 7, 2), edition='a', path='/mnt/project_impresso/original/BCUL/La_Griffe/1864/07/02/126933', rights='open_public', mit_file_type='xml')
IssueDirectory(journal='Guepe1851', date=datetime.date(1851, 2, 5), edition='a', path='/mnt/project_impresso/original/BCUL/La_GuÃªpe_[1]/1851/02/05/127024', rights='open_public', mit_file_type='xml')
IssueDirectory(journal='Guepe1887', date=datetime.date(1887, 2, 27), edition='a', path='/mnt/project_impresso/original/BCUL/La_GuÃªpe_[2]/1887/02/27/127026', rights='open_public', mit_file_type='xml')
IssueDirectory(journal='RLA', date=datetime.date(1891, 12, 10), edition='a', path='/mnt/project_impresso/original/BCUL/La_revue_agricole/1891/12/10/165847', rights='open_public', mit_file_type='xml')
IssueDirectory(journal='Charivari', date=datetime.date(1839, 4, 1), edition='a', path='/mnt/project_impresso/original/BCUL/Le_Charivari_[1]/1839/04/01/127716', rights='open_public', mit_file_type='xml')
IssueDirectory(journal='CharivariCH', date=datetime.date(1875, 12, 1), edition='a', path='/mnt/project_impresso/original/BCUL/Le_Charivari_[2]/1875/12/01/127364', rights='open_public', mit_file_type='xml')
IssueDirectory(journal='Grelot', date=datetime.date(1843, 10, 1), edition='a', path='/mnt/project_impresso/original/BCUL/Le_Grelot/1843/10/01/127513', rights='open_public', mit_file_type='xml')
IssueDirectory(journal='Moniteur', date=datetime.date(1879, 8, 15), edition='a', path='/mnt/project_impresso/original/BCUL/Le_Moniteur/1879/08/15/127571', rights='open_public', mit_file_type='xml')
IssueDirectory(journal='Moustique', date=datetime.date(1887, 12, 31), edition='a', path='/mnt/project_impresso/original/BCUL/Le_Moustique_(Vevey)/1887/12/31/588227', rights='open_public', mit_file_type='json')
IssueDirectory(journal='ouistiti', date=datetime.date(1882, 5, 31), edition='a', path='/mnt/project_impresso/original/BCUL/Le_Ouistiti/1882/05/31/171185', rights='open_public', mit_file_type='xml')
IssueDirectory(journal='PDN', date=datetime.date(1841, 9, 4), edition='a', path='/mnt/project_impresso/original/BCUL/Le_Phare_de_Nyon/1841/09/04/555099', rights='open_public', mit_file_type='json')
IssueDirectory(journal='PDL', date=datetime.date(1841, 12, 4), edition='a', path='/mnt/project_impresso/original/BCUL/Le_Phare_du_LÃ©man/1841/12/04/522239', rights='open_public', mit_file_type='json')
IssueDirectory(journal='PJ', date=datetime.date(1831, 1, 1), edition='a', path='/mnt/project_impresso/original/BCUL/Le_PÃ¨re_JÃ©rÃ´me/1831/01/01/127626', rights='open_public', mit_file_type='xml')
IssueDirectory(journal='TouSuIl', date=datetime.date(1866, 2, 1), edition='a', path='/mnt/project_impresso/original/BCUL/Le_Touriste__La_Suisse_illustrÃ©e/1866/02/01/197832', rights='open_public', mit_file_type='json')
IssueDirectory(journal='VVS1', date=datetime.date(1888, 11, 24), edition='a', path='/mnt/project_impresso/original/BCUL/Le_Veveysan_1/1888/11/24/255823', rights='open_public', mit_file_type='json')
IssueDirectory(journal='MESSAGER', date=datetime.date(1879, 12, 1), edition='a', path='/mnt/project_impresso/original/BCUL/Le_messager/1879/12/00/279344', rights='open_public', mit_file_type='json')
IssueDirectory(journal='PS', date=datetime.date(1845, 7, 11), edition='a', path='/mnt/project_impresso/original/BCUL/Le_peuple_souverain/1845/07/11/306429', rights='open_public', mit_file_type='json')
IssueDirectory(journal='NV', date=datetime.date(1822, 12, 18), edition='a', path='/mnt/project_impresso/original/BCUL/Lâ\x80\x99ami_de_la_vÃ©ritÃ©__journal_du_Canton_de_Vaud/1822/12/18/102037', rights='open_public', mit_file_type='xml')
IssueDirectory(journal='ME', date=datetime.date(1732, 12, 1), edition='a', path='/mnt/project_impresso/original/BCUL/Mercure_suisse/1732/12/01/127765', rights='open_public', mit_file_type='xml')
IssueDirectory(journal='MB', date=datetime.date(1748, 1, 1), edition='a', path='/mnt/project_impresso/original/BCUL/Messager_boÃ®teux/1748/01/01/168341', rights='open_public', mit_file_type='xml')
IssueDirectory(journal='NS', date=datetime.date(1748, 1, 1), edition='a', path='/mnt/project_impresso/original/BCUL/Nouvelliste_suisse/1748/01/01/128065', rights='open_public', mit_file_type='xml')

TypeError: dir2issue() missing 1 required positional argument: 'journal_info'

In [ ]:
def alias_and_mit_file_type(files):
    for f in files:
        if 'mit' in f:
            return f.split('.')[-1], f.split('_')[0]

In [ ]:
def _detect_issues(base_dir: str, access_rights: str, issue_dirs, mit_file_nature, aliases) -> list[BculIssueDir]:
    """Detect BCUL newspaper issues to import within the filesystem.

    This function expects the directory structure that BCUL used to
    organize the dump of Abbyy files.

    Args:
        base_dir (str): Path to the base directory of newspaper data.
        access_rights (str): Path to ``access_rights.json`` file.

    Returns:
        list[BculIssueDir]: List of `BCULIssueDir` instances, to be imported.
    """
    
    dir_path, dirs, files = next(os.walk(base_dir))
    
    journal_dirs = [os.path.join(dir_path, _dir) for _dir in dirs if _dir not in ['OLD', 'wrong_BCUL']]

    #mit_file_nature = {}
    #aliases = {}
    for journal in journal_dirs:
        print(f"\n Detecting issues for {journal}.")
        for dir_path, dirs, files in os.walk(journal):
            if len(files)>1 and 'solr' not in dir_path:
                issue_dirs.append(dir_path)
                print(dir_path)
                if journal not in aliases:
                    mit_file_nature[journal], aliases[journal] = alias_and_mit_file_type(files)
                    #aliases[journal] = replace_alias(aliases[journal], journal)

    return mit_file_nature, aliases, [dir2issue(_dir, None) for _dir in issue_dirs]

In [ ]:
issue_dirs = []
mit_file_nature, aliases = {}, {}
mit_file_nature, aliases, issues = _detect_issues(base_dir, '', issue_dirs, mit_file_nature, aliases)

In [ ]:
mit_file_nature

In [ ]:
found_aliases = {
 '/mnt/project_impresso/original/BCUL/Almanach_pour_le_commerce': 'ACI',
 '/mnt/project_impresso/original/BCUL/Castigat_ridendo_mores': 'Castigat',
 '/mnt/project_impresso/original/BCUL/Croquis_vaudois': 'Croquis',
 '/mnt/project_impresso/original/BCUL/Courrier_du_LÃ©man': 'CL',
 "/mnt/project_impresso/original/BCUL/Feuille_d'avis_de_Moudon": 'FAMDE',
 "/mnt/project_impresso/original/BCUL/Feuille_d'avis_de_Nyon": 'FAN',
 "/mnt/project_impresso/original/BCUL/Feuille_d'avis_de_Payerne,_Moudon_et_Avenches": 'feuille',
 "/mnt/project_impresso/original/BCUL/Feuille_d'avis_de_Payerne": 'feuille',
 '/mnt/project_impresso/original/BCUL/Gazette_des_Villages': 'GAV',
 '/mnt/project_impresso/original/BCUL/Indicateur_de_Lausanne': 'AV',
 "/mnt/project_impresso/original/BCUL/Journal_d'Yverdon_2": 'JY2',
 '/mnt/project_impresso/original/BCUL/Journal_de_Vevey': 'JV'
}

In [ ]:
aliases_json= {
    "Courrier_du_LÃ©man": 'CL',
    "Feuille_d'avis_de_Moudon": 'FAMDE',
    "Feuille_d'avis_de_Nyon": 'FAN',
    "Feuille_d'avis_de_Payerne,_Moudon_et_Avenches": "feuillePMA", #'feuille' in fs
    "Feuille_d'avis_de_Payerne": "feuilleP", # 'feuille' in fs
    "Gazette_des_Villages": "GAVi", # GAV
    "Journal_d'Yverdon_2": 'JY2', 
    "Journal_de_Vevey": 'JV',
    "Journal_de_vevey_et_des_Ã©trangers": 'JVE',
    "L'Observateur_du_LÃ©man": 'OBS',
    "Le_Moustique_(Vevey)": 'Moustique', 
    "Le_Phare_de_Nyon": 'PDN', 
    "Le_Phare_du_LÃ©man": 'PDL', # FAN in fs
    "Le_Touriste__La_Suisse_illustrÃ©e": "TouSuIl", #'TO-SU-IL' in fs
    "Le_Veveysan_1": 'VVS1', # VVS also for La_Veveysanne_–_La_Patrie/La_Veveysanne 
    "Le_messager": 'MESSAGER',
    "Le_peuple_souverain": 'PS'
}

In [ ]:
len(issue_dirs)

## Debug functions in helpers

In [2]:
from text_importer.importers.bcul.helpers import parse_textblock

In [3]:
page_xml_file = '/home/piconti/impresso-text-acquisition/text_importer/data/sample_data/BCUL/388793/6254688.xml'

with open(page_xml_file, encoding='utf-8') as f:
    xml_doc = BeautifulSoup(f, "xml")

xml_doc

<?xml version="1.0" encoding="utf-8"?>
<page height="5187" originalCoords="1" resolution="300" width="3629">
<block b="198" blockType="Text" l="111" r="409" t="152">
<region>
<rect b="198" l="111" r="409" t="152"/>
</region>
<text>
<par lineSpacing="1160">
<line b="191" baseline="191" l="117" r="403" t="158">
<formatting ff="Times New Roman" fs="10.5" lang="FrenchStandard">
<charParams b="191" charConfidence="100" l="117" meanStrokeWidth="37" r="136" serifProbability="255" t="159" wordFirst="1" wordFromDictionary="0" wordIdentifier="0" wordLeftMost="1" wordNormal="0" wordNumeric="0" wordPenalty="5">7</charParams>
<charParams b="191" charConfidence="100" l="140" meanStrokeWidth="37" r="159" serifProbability="255" t="159" wordFromDictionary="0" wordIdentifier="0" wordNormal="0" wordNumeric="0" wordPenalty="5">7</charParams>
</formatting>
<formatting ff="Times New Roman" fs="10.5" lang="FrenchStandard" superscript="1">
<charParams b="177" charConfidence="44" l="161" meanStrokeWidth="37" r="182" serifProbability="100" suspicious="1" t="164" wordFromDictionary="0" wordIdentifier="0" wordNormal="0" wordNumeric="0" wordPenalty="5">m</charParams>
<charParams b="177" charConfidence="24" l="186" meanStrokeWidth="37" r="197" serifProbability="77" suspicious="1" t="164" wordFromDictionary="0" wordIdentifier="0" wordNormal="0" wordNumeric="0" wordPenalty="5">c</charParams>
</formatting>
<formatting ff="Times New Roman" fs="10.5" lang="FrenchStandard">
<charParams b="191" l="198" r="242" t="159"> </charParams>
<charParams b="191" charConfidence="100" l="243" meanStrokeWidth="26" r="271" serifProbability="98" t="159" wordFirst="1" wordFromDictionary="1" wordIdentifier="0" wordLeftMost="1" wordNormal="1" wordNumeric="0" wordPenalty="0">A</charParams>
<charParams b="191" charConfidence="51" l="274" meanStrokeWidth="26" r="305" serifProbability="100" t="159" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">N</charParams>
<charParams b="191" charConfidence="57" l="308" meanStrokeWidth="26" r="340" serifProbability="100" t="158" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">N</charParams>
<charParams b="191" charConfidence="100" l="343" meanStrokeWidth="26" r="371" serifProbability="100" t="158" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">E</charParams>
<charParams b="191" charConfidence="100" l="374" meanStrokeWidth="26" r="403" serifProbability="100" t="158" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">E</charParams>
</formatting>
</line>
</par>
</text>
</block>
<block b="197" blockType="Text" l="1723" r="1832" t="151">
<region>
<rect b="197" l="1723" r="1832" t="151"/>
</region>
<text>
<par lineSpacing="1160">
<line b="191" baseline="191" l="1729" r="1826" t="157">
<formatting ff="Times New Roman" fs="10.5" lang="EnglishUnitedStates">
<charParams b="191" charConfidence="17" l="1729" meanStrokeWidth="26" r="1760" serifProbability="100" t="157" wordFirst="1" wordFromDictionary="0" wordIdentifier="0" wordLeftMost="1" wordNormal="0" wordNumeric="0" wordPenalty="0">N</charParams>
<charParams b="175" charConfidence="83" l="1762" meanStrokeWidth="26" r="1775" serifProbability="255" t="163" wordFromDictionary="0" wordIdentifier="0" wordNormal="0" wordNumeric="0" wordPenalty="0">°</charParams>
<charParams b="191" l="1776" r="1805" t="159"> </charParams>
<charParams b="191" charConfidence="45" l="1806" meanStrokeWidth="42" r="1826" serifProbability="77" t="159" wordFirst="1" wordFromDictionary="0" wordIdentifier="0" wordLeftMost="1" wordNormal="0" wordNumeric="1" wordPenalty="0">9</charParams>
</formatting>
</line>
</par>
</text>
</block>
<block b="201" blockType="Text" l="2831" r="3483" t="153">
<region>
<rect b="201" l="2831" r="3483" t="153"/>
</region>
<text>
<par lineSpacing="1160">
<line b="195" baseline="194" l="2837" r="3477" t="159">
<formatting ff="Times New Roman" fs="10.5" lang="FrenchStandard">
<charParams b="193" charConfidence="91" l="2837" meanStrokeWidth="49" r="2859" serifProbability="73" t="160" wordFirst="1" wordFromDictionary="1" wordIdentifier="0" wordLeftMost="1" wordNormal="1" wordNumeric="0" wordPenalty="0">S</charParams>
<charParams b="192" charConfidence="100" l="2863" meanStrokeWidth="49" r="2891" serifProbability="98" t="159" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">A</charParams>
<charParams b="193" charConfidence="100" l="2896" meanStrokeWidth="49" r="2928" serifProbability="100" t="160" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">M</charParams>
<charParams b="193" charConfidence="100" l="2933" meanStrokeWidth="49" r="2960" serifProbability="100" t="160" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">E</charParams>
<charParams b="193" charConfidence="100" l="2964" meanStrokeWidth="49" r="2993" serifProbability="89" t="160" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">D</charParams>
<charParams b="193" charConfidence="63" l="2997" meanStrokeWidth="49" r="3010" serifProbability="100" t="160" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">I</charParams>
<charParams b="194" l="3011" r="3056" t="160"> </charParams>
</formatting>
<formatting ff="Times New Roman" fs="10.5" lang="EnglishUnitedStates">
<charParams b="194" charConfidence="100" l="3057" meanStrokeWidth="49" r="3077" serifProbability="70" t="161" wordFirst="1" wordFromDictionary="0" wordIdentifier="0" wordLeftMost="1" wordNormal="0" wordNumeric="1" wordPenalty="0">3</charParams>
<charParams b="194" charConfidence="100" l="3080" meanStrokeWidth="49" r="3101" serifProbability="255" t="161" wordFromDictionary="0" wordIdentifier="0" wordNormal="0" wordNumeric="1" wordPenalty="0">0</charParams>
<charParams b="194" l="3102" r="3146" t="161"> </charParams>
<charParams b="193" charConfidence="24" l="3147" meanStrokeWidth="48" r="3164" serifProbability="100" t="161" wordFirst="1" wordFromDictionary="1" wordIdentifier="0" wordLeftMost="1" wordNormal="1" wordNumeric="0" wordPenalty="0">J</charParams>
<charParams b="194" charConfidence="100" l="3169" meanStrokeWidth="48" r="3196" serifProbability="98" t="161" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">A</charParams>
<charParams b="194" charConfidence="100" l="3200" meanStrokeWidth="48" r="3231" serifProbability="100" t="161" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">N</charParams>
<charParams b="195" charConfidence="100" l="3234" meanStrokeWidth="48" r="3263" serifProbability="50" t="161" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">V</charParams>
<charParams b="194" charConfidence="100" l="3265" meanStrokeWidth="48" r="3280" serifProbability="100" t="161" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">I</charParams>
<charParams b="194" charConfidence="100" l="3283" meanStrokeWidth="48" r="3311" serifProbability="100" t="161" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">E</charParams>
<charParams b="194" charConfidence="65" l="3314" meanStrokeWidth="48" r="3342" serifProbability="100" t="161" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">R</charParams>
<charParams b="195" l="3343" r="3391" t="161"> </charParams>
<charParams b="195" charConfidence="45" l="3392" meanStrokeWidth="49" r="3407" serifProbability="100" t="162" wordFirst="1" wordFromDictionary="0" wordIdentifier="0" wordLeftMost="1" wordNormal="0" wordNumeric="1" wordPenalty="0">1</charParams>
<charParams b="195" charConfidence="100" l="3412" meanStrokeWidth="49" r="3432" serifProbability="68" t="163" wordFromDictionary="0" wordIdentifier="0" wordNormal="0" wordNumeric="1" wordPenalty="0">9</charParams>
<charParams b="195" charConfidence="100" l="3435" meanStrokeWidth="49" r="3455" serifProbability="70" t="162" wordFromDictionary="0" wordIdentifier="0" wordNormal="0" wordNumeric="1" wordPenalty="0">3</charParams>
<charParams b="195" charConfidence="100" l="3458" meanStrokeWidth="49" r="3477" serifProbability="255" t="163" wordFromDictionary="0" wordIdentifier="0" wordNormal="0" wordNumeric="1" wordPenalty="0">7</charParams>
</formatting>
</line>
</par>
</text>
</block>
<block b="388" blockType="Text" l="234" r="514" t="278">
<region>
<rect b="388" l="234" r="514" t="278"/>
</region>
<text>
<par align="Justified">
<line b="388" baseline="388" l="251" r="507" t="297">
<formatting ff="Times New Roman" fs="21." italic="1" lang="EnglishUnitedStates">
<charParams b="388" charConfidence="15" l="251" meanStrokeWidth="67" r="357" serifProbability="100" suspicious="1" t="307" wordFirst="1" wordFromDictionary="0" wordIdentifier="0" wordLeftMost="1" wordNormal="1" wordNumeric="0" wordPenalty="0">W</charParams>
</formatting>
<formatting bold="1" ff="Times New Roman" fs="21." lang="EnglishUnitedStates" scaling="660">
<charParams b="388" l="358" r="458" t="297"> </charParams>
<charParams b="385" charConfidence="15" l="459" meanStrokeWidth="475" r="507" serifProbability="255" suspicious="1" t="297" wordFirst="1" wordFromDictionary="1" wordIdentifier="0" wordLeftMost="1" wordNormal="1" wordNumeric="0" wordPenalty="0">I</charParams>
</formatting>
</line>
</par>
</text>
</block>
<block b="704" blockType="Text" l="322" r="450" t="498">
<region>
<rect b="704" l="322" r="450" t="498"/>
</region>
<text>
<par lineSpacing="-1"/>
</text>
</block>
<block b="706" blockType="Text" l="518" r="1156" t="276">
<region>
<rect b="706" l="518" r="1156" t="276"/>
</region>
<text>
<par lineSpacing="15390">
<line b="696" baseline="688" l="520" r="1144" t="296">
<formatting bold="1" ff="Times New Roman" fs="139." lang="EnglishUnitedStates" scaling="600">
<charParams b="696" charConfidence="39" l="520" meanStrokeWidth="767" r="728" serifProbability="98" t="296" wordFirst="1" wordFromDictionary="1" wordIdentifier="0" wordLeftMost="1" wordNormal="1" wordNumeric="0" wordPenalty="0">A</charParams>
<charParams b="696" charConfidence="49" l="728" meanStrokeWidth="767" r="872" serifProbability="100" t="296" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">I</charParams>
<charParams b="696" charConfidence="100" l="872" meanStrokeWidth="767" r="1144" serifProbability="255" t="296" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">D</charParams>
</formatting>
</line>
</par>
</text>
</block>
<block b="704" blockType="Picture" l="1364" r="1768" t="308">
<region>
<rect b="704" l="1364" r="1768" t="308"/>
</region>
</block>
<block b="714" blockType="Text" l="1988" r="3342" t="278">
<region>
<rect b="714" l="1988" r="3342" t="278"/>
</region>
<text>
<par lineSpacing="15390">
<line b="712" baseline="704" l="2008" r="3336" t="296">
<formatting bold="1" ff="Times New Roman" fs="139." lang="EnglishUnitedStates" scaling="600">
<charParams b="712" charConfidence="30" l="2008" meanStrokeWidth="765" r="2296" serifProbability="94" suspicious="1" t="296" wordFirst="1" wordFromDictionary="0" wordIdentifier="0" wordLeftMost="1" wordNormal="1" wordNumeric="0" wordPenalty="0">M</charParams>
<charParams b="712" charConfidence="74" l="2296" meanStrokeWidth="765" r="2488" serifProbability="255" suspicious="1" t="296" wordFromDictionary="0" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">O</charParams>
<charParams b="712" charConfidence="16" l="2488" meanStrokeWidth="765" r="2712" serifProbability="94" suspicious="1" t="296" wordFromDictionary="0" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">H</charParams>
<charParams b="712" charConfidence="38" l="2728" meanStrokeWidth="765" r="2936" serifProbability="40" t="296" wordFromDictionary="0" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">G</charParams>
<charParams b="712" charConfidence="33" l="2936" meanStrokeWidth="765" r="3128" serifProbability="100" suspicious="1" t="312" wordFromDictionary="0" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">E</charParams>
<charParams b="712" charConfidence="26" l="3144" meanStrokeWidth="765" r="3336" serifProbability="73" t="312" wordFromDictionary="0" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">S</charParams>
</formatting>
</line>
</par>
</text>
</block>
<block b="1044" blockType="Text" l="138" r="686" t="778">
<region>
<rect b="1044" l="138" r="686" t="778"/>
</region>
<text>
<par align="Center" leftIndent="200" lineSpacing="940">
<line b="810" baseline="809" l="198" r="618" t="783">
<formatting ff="Times New Roman" fs="8.5" lang="FrenchStandard" spacing="20">
<charParams b="807" charConfidence="42" l="198" meanStrokeWidth="54" r="224" serifProbability="44" t="783" wordFirst="1" wordFromDictionary="1" wordIdentifier="0" wordLeftMost="1" wordNormal="1" wordNumeric="0" wordPenalty="0">P</charParams>
<charParams b="808" charConfidence="30" l="230" meanStrokeWidth="54" r="247" serifProbability="4" t="790" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">r</charParams>
<charParams b="808" charConfidence="16" l="252" meanStrokeWidth="54" r="259" serifProbability="255" t="784" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">i</charParams>
<charParams b="808" charConfidence="33" l="266" meanStrokeWidth="54" r="287" serifProbability="255" t="790" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">x</charParams>
<charParams b="809" l="288" r="309" t="785"> </charParams>
<charParams b="809" charConfidence="17" l="310" meanStrokeWidth="45" r="329" serifProbability="0" t="785" wordFirst="1" wordFromDictionary="1" wordIdentifier="0" wordLeftMost="1" wordNormal="1" wordNumeric="0" wordPenalty="0">d</charParams>
<charParams b="792" charConfidence="-1" l="337" meanStrokeWidth="45" r="343" serifProbability="255" t="785" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">'</charParams>
<charParams b="810" charConfidence="57" l="347" meanStrokeWidth="45" r="365" serifProbability="53" t="792" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">a</charParams>
<charParams b="809" charConfidence="33" l="374" meanStrokeWidth="45" r="393" serifProbability="42" t="785" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">b</charParams>
<charParams b="809" charConfidence="100" l="397" meanStrokeWidth="45" r="415" serifProbability="255" t="792" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">o</charParams>
<charParams b="809" charConfidence="56" l="421" meanStrokeWidth="45" r="440" serifProbability="0" t="792" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">n</charParams>
<charParams b="809" charConfidence="34" l="447" meanStrokeWidth="45" r="467" serifProbability="0" t="792" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">n</charParams>
<charParams b="809" charConfidence="36" l="473" meanStrokeWidth="45" r="491" serifProbability="71" t="792" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">e</charParams>
<charParams b="809" charConfidence="30" l="496" meanStrokeWidth="45" r="529" serifProbability="100" t="792" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">m</charParams>
<charParams b="808" charConfidence="92" l="535" meanStrokeWidth="45" r="553" serifProbability="71" t="791" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">e</charParams>
<charParams b="809" charConfidence="59" l="558" meanStrokeWidth="45" r="579" serifProbability="100" t="792" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">n</charParams>
<charParams b="809" charConfidence="100" l="583" meanStrokeWidth="45" r="599" serifProbability="61" t="786" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">t</charParams>
<charParams b="809" l="600" r="609" t="786"> </charParams>
</formatting>
<formatting ff="Times New Roman" fs="8.5" lang="EnglishUnitedStates" spacing="20">
<charParams b="809" charConfidence="22" l="610" meanStrokeWidth="45" r="618" serifProbability="255" t="793" wordFirst="1" wordFromDictionary="1" wordIdentifier="1" wordLeftMost="1" wordNormal="0" wordNumeric="0" wordPenalty="0">:</charParams>
</formatting>
</line>
</par>
<par align="Center" leftIndent="200" lineSpacing="1080">
<line b="868" baseline="864" l="146" r="672" t="837">
<formatting bold="1" ff="Times New Roman" fs="7.5" lang="EnglishUnitedStates">
<charParams b="862" charConfidence="21" l="146" meanStrokeWidth="39" r="151" serifProbability="0" suspicious="1" t="838" wordFirst="1" wordFromDictionary="0" wordIdentifier="0" wordLeftMost="1" wordNormal="0" wordNumeric="1" wordPenalty="1">1</charParams>
<charParams b="863" l="152" r="171" t="838"> </charParams>
</formatting>
<formatting ff="Times New Roman" fs="7.5" lang="EnglishUnitedStates">
<charParams b="863" charConfidence="56" l="172" meanStrokeWidth="33" r="184" serifProbability="72" t="849" wordFirst="1" wordFromDictionary="1" wordIdentifier="0" wordLeftMost="1" wordNormal="1" wordNumeric="0" wordPenalty="0">a</charParams>
<charParams b="863" charConfidence="100" l="187" meanStrokeWidth="33" r="200" serifProbability="100" t="849" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">n</charParams>
<charParams b="862" charConfidence="58" l="205" meanStrokeWidth="33" r="210" serifProbability="255" t="858" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">.</charParams>
<charParams b="864" l="211" r="225" t="837"> </charParams>
</formatting>
<formatting bold="1" ff="Times New Roman" fs="7.5" lang="EnglishUnitedStates">
<charParams b="864" charConfidence="34" l="226" meanStrokeWidth="32" r="236" serifProbability="50" t="837" wordFirst="1" wordFromDictionary="0" wordIdentifier="0" wordLeftMost="1" wordNormal="0" wordNumeric="1" wordPenalty="0">6</charParams>
<charParams b="864" l="237" r="252" t="837"> </charParams>
</formatting>
<formatting ff="Times New Roman" fs="7.5" lang="GermanStandard">
<charParams b="864" charConfidence="15" l="253" meanStrokeWidth="29" r="259" serifProbability="34" t="839" wordFirst="1" wordFromDictionary="1" wordIdentifier="0" wordLeftMost="1" wordNormal="1" wordNumeric="0" wordPenalty="3">f</charParams>
<charParams b="864" charConfidence="59" l="264" meanStrokeWidth="29" r="270" serifProbability="100" t="850" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="3">r</charParams>
<charParams b="864" charConfidence="96" l="275" meanStrokeWidth="29" r="280" serifProbability="255" t="860" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="3">.</charParams>
<charParams b="864" l="281" r="296" t="840"> </charParams>
</formatting>
<formatting ff="Times New Roman" fs="7.5" lang="EnglishUnitedStates">
<charParams b="864" charConfidence="84" l="297" meanStrokeWidth="34" r="312" serifProbability="6" t="840" wordFirst="1" wordFromDictionary="0" wordIdentifier="0" wordLeftMost="1" wordNormal="0" wordNumeric="1" wordPenalty="0">6</charParams>
<charParams b="865" l="313" r="328" t="840"> </charParams>
</formatting>
<formatting ff="Times New Roman" fs="7.5" lang="FrenchStandard">

In [4]:
text_blocks = xml_doc.findAll("block", {"blockType": "Text"})
page_data = [parse_textblock(tb, "FAM-1937-01-30-a-i0001") for tb in text_blocks]
page_data

inside parse_char_tokens: [<charParams b="191" charConfidence="100" l="117" meanStrokeWidth="37" r="136" serifProbability="255" t="159" wordFirst="1" wordFromDictionary="0" wordIdentifier="0" wordLeftMost="1" wordNormal="0" wordNumeric="0" wordPenalty="5">7</charParams>, <charParams b="191" charConfidence="100" l="140" meanStrokeWidth="37" r="159" serifProbability="255" t="159" wordFromDictionary="0" wordIdentifier="0" wordNormal="0" wordNumeric="0" wordPenalty="5">7</charParams>, <charParams b="177" charConfidence="44" l="161" meanStrokeWidth="37" r="182" serifProbability="100" suspicious="1" t="164" wordFromDictionary="0" wordIdentifier="0" wordNormal="0" wordNumeric="0" wordPenalty="5">m</charParams>, <charParams b="177" charConfidence="24" l="186" meanStrokeWidth="37" r="197" serifProbability="77" suspicious="1" t="164" wordFromDictionary="0" wordIdentifier="0" wordNormal="0" wordNumeric="0" wordPenalty="5">c</charParams>, <charParams b="191" l="198" r="242" t="159"> </charParams>, <charParams b="191" charConfidence="100" l="243" meanStrokeWidth="26" r="271" serifProbability="98" t="159" wordFirst="1" wordFromDictionary="1" wordIdentifier="0" wordLeftMost="1" wordNormal="1" wordNumeric="0" wordPenalty="0">A</charParams>, <charParams b="191" charConfidence="51" l="274" meanStrokeWidth="26" r="305" serifProbability="100" t="159" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">N</charParams>, <charParams b="191" charConfidence="57" l="308" meanStrokeWidth="26" r="340" serifProbability="100" t="158" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">N</charParams>, <charParams b="191" charConfidence="100" l="343" meanStrokeWidth="26" r="371" serifProbability="100" t="158" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">E</charParams>, <charParams b="191" charConfidence="100" l="374" meanStrokeWidth="26" r="403" serifProbability="100" t="158" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">E</charParams>]
None False 1 False
None False None False
None False None False
None False None False
None False None False
None False 1 False
None False None False
None False None False
None False None False
None False None False
inside parse_char_tokens: [<charParams b="191" charConfidence="17" l="1729" meanStrokeWidth="26" r="1760" serifProbability="100" t="157" wordFirst="1" wordFromDictionary="0" wordIdentifier="0" wordLeftMost="1" wordNormal="0" wordNumeric="0" wordPenalty="0">N</charParams>, <charParams b="175" charConfidence="83" l="1762" meanStrokeWidth="26" r="1775" serifProbability="255" t="163" wordFromDictionary="0" wordIdentifier="0" wordNormal="0" wordNumeric="0" wordPenalty="0">°</charParams>, <charParams b="191" l="1776" r="1805" t="159"> </charParams>, <charParams b="191" charConfidence="45" l="1806" meanStrokeWidth="42" r="1826" serifProbability="77" t="159" wordFirst="1" wordFromDictionary="0" wordIdentifier="0" wordLeftMost="1" wordNormal="0" wordNumeric="1" wordPenalty="0">9</charParams>]
None False 1 False
None False None False
None False None False
None False 1 False
inside parse_char_tokens: [<charParams b="193" charConfidence="91" l="2837" meanStrokeWidth="49" r="2859" serifProbability="73" t="160" wordFirst="1" wordFromDictionary="1" wordIdentifier="0" wordLeftMost="1" wordNormal="1" wordNumeric="0" wordPenalty="0">S</charParams>, <charParams b="192" charConfidence="100" l="2863" meanStrokeWidth="49" r="2891" serifProbability="98" t="159" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">A</charParams>, <charParams b="193" charConfidence="100" l="2896" meanStrokeWidth="49" r="2928" serifProbability="100" t="160" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">M</charParams>, <charParams b="193" charConfidence="100" l="2933" meanStrokeWidth="49" r="2960" serifProbability="100" t="160" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">E</charParams>, <charParams b="193" charConfidence="100" l="2964" meanStrokeWidth="49" r="2993" serifProbability="89" t="160" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">D</charParams>, <charParams b="193" charConfidence="63" l="2997" meanStrokeWidth="49" r="3010" serifProbability="100" t="160" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">I</charParams>, <charParams b="194" l="3011" r="3056" t="160"> </charParams>, <charParams b="194" charConfidence="100" l="3057" meanStrokeWidth="49" r="3077" serifProbability="70" t="161" wordFirst="1" wordFromDictionary="0" wordIdentifier="0" wordLeftMost="1" wordNormal="0" wordNumeric="1" wordPenalty="0">3</charParams>, <charParams b="194" charConfidence="100" l="3080" meanStrokeWidth="49" r="3101" serifProbability="255" t="161" wordFromDictionary="0" wordIdentifier="0" wordNormal="0" wordNumeric="1" wordPenalty="0">0</charParams>, <charParams b="194" l="3102" r="3146" t="161"> </charParams>, <charParams b="193" charConfidence="24" l="3147" meanStrokeWidth="48" r="3164" serifProbability="100" t="161" wordFirst="1" wordFromDictionary="1" wordIdentifier="0" wordLeftMost="1" wordNormal="1" wordNumeric="0" wordPenalty="0">J</charParams>, <charParams b="194" charConfidence="100" l="3169" meanStrokeWidth="48" r="3196" serifProbability="98" t="161" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">A</charParams>, <charParams b="194" charConfidence="100" l="3200" meanStrokeWidth="48" r="3231" serifProbability="100" t="161" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">N</charParams>, <charParams b="195" charConfidence="100" l="3234" meanStrokeWidth="48" r="3263" serifProbability="50" t="161" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">V</charParams>, <charParams b="194" charConfidence="100" l="3265" meanStrokeWidth="48" r="3280" serifProbability="100" t="161" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">I</charParams>, <charParams b="194" charConfidence="100" l="3283" meanStrokeWidth="48" r="3311" serifProbability="100" t="161" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">E</charParams>, <charParams b="194" charConfidence="65" l="3314" meanStrokeWidth="48" r="3342" serifProbability="100" t="161" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">R</charParams>, <charParams b="195" l="3343" r="3391" t="161"> </charParams>, <charParams b="195" charConfidence="45" l="3392" meanStrokeWidth="49" r="3407" serifProbability="100" t="162" wordFirst="1" wordFromDictionary="0" wordIdentifier="0" wordLeftMost="1" wordNormal="0" wordNumeric="1" wordPenalty="0">1</charParams>, <charParams b="195" charConfidence="100" l="3412" meanStrokeWidth="49" r="3432" serifProbability="68" t="163" wordFromDictionary="0" wordIdentifier="0" wordNormal="0" wordNumeric="1" wordPenalty="0">9</charParams>, <charParams b="195" charConfidence="100" l="3435" meanStrokeWidth="49" r="3455" serifProbability="70" t="162" wordFromDictionary="0" wordIdentifier="0" wordNormal="0" wordNumeric="1" wordPenalty="0">3</charParams>, <charParams b="195" charConfidence="100" l="3458" meanStrokeWidth="49" r="3477" serifProbability="255" t="163" wordFromDictionary="0" wordIdentifier="0" wordNormal="0" wordNumeric="1" wordPenalty="0">7</charParams>]
None False 1 False
None False None False
None False None False
None False None False
None False None False
None False None False
None False None False
None False 1 False
None False None False
None False None False
None False 1 False
None False None False
None False None False
None False None False
None False None False
None False None False
None False None False
None False None False
None False 1 False
None False None False
None False None False
None False None False
inside parse_char_tokens: [<charParams b="388" charConfidence="15" l="251" meanStrokeWidth="67" r="357" serifProbability="100" suspicious="1" t="307" wordFirst="1" wordFromDictionary="0" wordIdentifier="0" wordLeftMost="1" wordNormal="1" wordNumeric="0" wordPenalty="0">W</charParams>, <charParams b="388" l="358" r="458" t="297"> </charParams>, <charParams b="385" charConfidence="15" l="459" meanStrokeWidth="475" r="507" serifProbability="255" suspicious="1" t="297" wordFirst="1" wordFromDictionary="1" wordIdentifier="0" wordLeftMost="1" wordNormal="1" wordNumeric="0" wordPenalty="0">I</charParams>]
None False 1 False
None False None False
None False 1 False
inside parse_char_tokens: [<charParams b="696" charConfidence="39" l="520" meanStrokeWidth="767" r="728" serifProbability="98" t="296" wordFirst="1" wordFromDictionary="1" wordIdentifier="0" wordLeftMost="1" wordNormal="1" wordNumeric="0" wordPenalty="0">A</charParams>, <charParams b="696" charConfidence="49" l="728" meanStrokeWidth="767" r="872" serifProbability="100" t="296" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">I</charParams>, <charParams b="696" charConfidence="100" l="872" meanStrokeWidth="767" r="1144" serifProbability="255" t="296" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">D</charParams>]
None False 1 False
None False None False
None False None False
inside parse_char_tokens: [<charParams b="712" charConfidence="30" l="2008" meanStrokeWidth="765" r="2296" serifProbability="94" suspicious="1" t="296" wordFirst="1" wordFromDictionary="0" wordIdentifier="0" wordLeftMost="1" wordNormal="1" wordNumeric="0" wordPenalty="0">M</charParams>, <charParams b="712" charConfidence="74" l="2296" meanStrokeWidth="765" r="2488" serifProbability="255" suspicious="1" t="296" wordFromDictionary="0" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">O</charParams>, <charParams b="712" charConfidence="16" l="2488" meanStrokeWidth="765" r="2712" serifProbability="94" suspicious="1" t="296" wordFromDictionary="0" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">H</charParams>, <charParams b="712" charConfidence="38" l="2728" meanStrokeWidth="765" r="2936" serifProbability="40" t="296" wordFromDictionary="0" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">G</charParams>, <charParams b="712" charConfidence="33" l="2936" meanStrokeWidth="765" r="3128" serifProbability="100" suspicious="1" t="312" wordFromDictionary="0" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">E</charParams>, <charParams b="712" charConfidence="26" l="3144" meanStrokeWidth="765" r="3336" serifProbability="73" t="312" wordFromDictionary="0" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">S</charParams>]
None False 1 False
None False None False
None False None False
None False None False
None False None False
None False None False
inside parse_char_tokens: [<charParams b="807" charConfidence="42" l="198" meanStrokeWidth="54" r="224" serifProbability="44" t="783" wordFirst="1" wordFromDictionary="1" wordIdentifier="0" wordLeftMost="1" wordNormal="1" wordNumeric="0" wordPenalty="0">P</charParams>, <charParams b="808" charConfidence="30" l="230" meanStrokeWidth="54" r="247" serifProbability="4" t="790" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">r</charParams>, <charParams b="808" charConfidence="16" l="252" meanStrokeWidth="54" r="259" serifProbability="255" t="784" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">i</charParams>, <charParams b="808" charConfidence="33" l="266" meanStrokeWidth="54" r="287" serifProbability="255" t="790" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">x</charParams>, <charParams b="809" l="288" r="309" t="785"> </charParams>, <charParams b="809" charConfidence="17" l="310" meanStrokeWidth="45" r="329" serifProbability="0" t="785" wordFirst="1" wordFromDictionary="1" wordIdentifier="0" wordLeftMost="1" wordNormal="1" wordNumeric="0" wordPenalty="0">d</charParams>, <charParams b="792" charConfidence="-1" l="337" meanStrokeWidth="45" r="343" serifProbability="255" t="785" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">'</charParams>, <charParams b="810" charConfidence="57" l="347" meanStrokeWidth="45" r="365" serifProbability="53" t="792" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">a</charParams>, <charParams b="809" charConfidence="33" l="374" meanStrokeWidth="45" r="393" serifProbability="42" t="785" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">b</charParams>, <charParams b="809" charConfidence="100" l="397" meanStrokeWidth="45" r="415" serifProbability="255" t="792" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">o</charParams>, <charParams b="809" charConfidence="56" l="421" meanStrokeWidth="45" r="440" serifProbability="0" t="792" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">n</charParams>, <charParams b="809" charConfidence="34" l="447" meanStrokeWidth="45" r="467" serifProbability="0" t="792" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">n</charParams>, <charParams b="809" charConfidence="36" l="473" meanStrokeWidth="45" r="491" serifProbability="71" t="792" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">e</charParams>, <charParams b="809" charConfidence="30" l="496" meanStrokeWidth="45" r="529" serifProbability="100" t="792" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">m</charParams>, <charParams b="808" charConfidence="92" l="535" meanStrokeWidth="45" r="553" serifProbability="71" t="791" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">e</charParams>, <charParams b="809" charConfidence="59" l="558" meanStrokeWidth="45" r="579" serifProbability="100" t="792" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">n</charParams>, <charParams b="809" charConfidence="100" l="583" meanStrokeWidth="45" r="599" serifProbability="61" t="786" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0">t</charParams>, <charParams b="809" l="600" r="609" t="786"> </charParams>, <charParams b="809" charConfidence="22" l="610" meanStrokeWidth="45" r="618" serifProbability="255" t="793" wordFirst="1" wordFromDictionary="1" wordIdentifier="1" wordLeftMost="1" wordNormal="0" wordNumeric="0" wordPenalty="0">:</charParams>]
None False 1 False
None False None False
None False None False
None False None False
None False None False
None False 1 False
None False None False
None False None False
None False None False
None False None False
None False None False
None False None False
None False None False
None False None False
None False None False
None False None False
None False None False
None False None False
None False 1 False

[{'c': [111, 152, 298, 46],
  'p': [{'c': [111, 152, 298, 46],
    'l': [{'c': [117, 158, 286, 33],
      't': [{'c': [117, 159, 80, 18], 'tx': '77mc'},
       {'c': [243, 159, 160, 32], 'tx': 'ANNEE'}]}]}],
  'pOf': 'FAM-1937-01-30-a-i0001'},
 {'c': [1723, 151, 109, 46],
  'p': [{'c': [1723, 151, 109, 46],
    'l': [{'c': [1729, 157, 97, 34],
      't': [{'c': [1729, 157, 46, 18], 'tx': 'N°'},
       {'c': [1806, 159, 20, 32], 'tx': '9'}]}]}],
  'pOf': 'FAM-1937-01-30-a-i0001'},
 {'c': [2831, 153, 652, 48],
  'p': [{'c': [2831, 153, 652, 48],
    'l': [{'c': [2837, 159, 640, 36],
      't': [{'c': [2837, 160, 173, 33], 'tx': 'SAMEDI'},
       {'c': [3057, 161, 44, 33], 'tx': '30'},
       {'c': [3147, 161, 195, 33], 'tx': 'JANVIER'},
       {'c': [3392, 162, 85, 33], 'tx': '1937'}]}]}],
  'pOf': 'FAM-1937-01-30-a-i0001'},
 {'c': [234, 278, 280, 110],
  'p': [{'c': [234, 278, 280, 110],
    'l': [{'c': [251, 297, 256, 91],
      't': [{'c': [251, 307, 106, 81], 'tx': 'W'},
       {'c': [459, 297, 48, 88], 'tx': 'I'}]}]}],
  'pOf': 'FAM-1937-01-30-a-i0001'},
 {'c': [322, 498, 128, 206],
  'p': [{'c': [322, 498, 128, 206], 'l': []}],
  'pOf': 'FAM-1937-01-30-a-i0001'},
 {'c': [518, 276, 638, 430],
  'p': [{'c': [518, 276, 638, 430],
    'l': [{'c': [520, 296, 624, 400],
      't': [{'c': [520, 296, 624, 400], 'tx': 'AID'}]}]}],
  'pOf': 'FAM-1937-01-30-a-i0001'},
 {'c': [1988, 278, 1354, 436],
  'p': [{'c': [1988, 278, 1354, 436],
    'l': [{'c': [2008, 296, 1328, 416],
      't': [{'c': [2008, 296, 1328, 416], 'tx': 'MOHGES'}]}]}],
  'pOf': 'FAM-1937-01-30-a-i0001'},
 {'c': [138, 778, 548, 266],
  'p': [{'c': [138, 778, 548, 266],
    'l': [{'c': [198, 783, 420, 27],
      't': [{'c': [198, 783, 89, 25], 'tx': 'Prix'},
       {'c': [310, 785, 289, 24], 'tx': "d'abonnement"},
       {'c': [610, 793, 8, 16], 'tx': ':'}]},
     {'c': [146, 837, 526, 31],
      't': [{'c': [146, 838, 5, 24], 'tx': '1'},
       {'c': [172, 849, 38, 13], 'tx': 'an.'},
       {'c': [226, 837, 10, 27], 'tx': '6'},
       {'c': [253, 839, 27, 25], 'tx': 'fr.'},
       {'c': [297, 840, 15, 24], 'tx': '6'},
       {'c': [329, 851, 65, 16], 'tx': 'mois,'},
       {'c': [412, 838, 9, 27], 'tx': '3'},
       {'c': [437, 840, 27, 24], 'tx': 'fr.'},
       {'c': [481, 839, 15, 25], 'tx': '3'},
       {'c': [511, 850, 66, 18], 'tx': 'mois,'},
       {'c': [594, 837, 8, 28], 'tx': '1'},
       {'c': [613, 839, 29, 26], 'tx': 'fr.'},
       {'c': [650, 837, 22, 27], 'tx': '50'}]},
     {'c': [234, 884, 340, 32],
      't': [{'c': [234, 885, 111, 25], 'tx': 'Etranger'},
       {'c': [360, 895, 5, 15], 'tx': ':'},
       {'c': [385, 884, 20, 26], 'tx': 'le'},
       {'c': [419, 895, 50, 14], 'tx': 'port'},
       {'c': [483, 895, 29, 14], 'tx': 'en'},
       {'c': [527, 894, 47, 15], 'tx': 'sus.'}]},
     {'c': [149, 964, 519, 27],
      't': [{'c': [149, 964, 42, 25], 'tx': 'On'},
       {'c': [208, 975, 112, 14], 'tx': "s'abonne"},
       {'c': [333, 969, 12, 20], 'tx': 'à'},
       {'c': [361, 965, 5, 24], 'tx': '1'},
       {'c': [377, 975, 182, 14], 'tx': 'administration'},
       {'c': [573, 975, 22, 14], 'tx': 'et'},
       {'c': [609, 964, 59, 27], 'tx': 'dans'}]},
     {'c': [229, 1008, 351, 31],
      't': [{'c': [229, 1016, 50, 18], 'tx': 'tous'},
       {'c': [296, 1009, 32, 24], 'tx': 'les'},
       {'c': [344, 1010, 101, 23], 'tx': 'bureaux'},
       {'c': [462, 1008, 29, 25], 'tx': 'de'},
       {'c': [505, 1019, 75, 15], 'tx': 'poste.'}]}]}],
  'pOf': 'FAM-1937-01-30-a-i0001'},
 {'c': [142, 1122, 350, 38],
  'p': [{'c': [142, 1122, 350, 38],
    'l': [{'c': [158, 1122, 316, 32],
      't': [{'c': [158, 1127, 125, 27], 'tx': 'FONDÉ'},
       {'c': [321, 1129, 46, 25], 'tx': 'EN'},
       {'c': [407, 1128, 67, 26], 'tx': '1860'}]}]}],
  'pOf': 'FAM-1937-01-30-a-i0001'},
 {'c': [772, 770, 2022, 396],
  'p': [{'c': [772, 770, 2022, 396],
    'l': [{'c': [1093, 795, 1396, 108],
      't': [{'c': [1093, 797, 376, 102], 'tx': 'FEUILLE'},
       {'c': [1535, 799, 292, 102], 'tx': 'D’AVIS'},
       {'c': [1895, 799, 118, 100], 'tx': 'DU'},
       {'c': [2079, 797, 410, 104], 'tx': 'DISTRICT'}]},
     {'c': [787, 952, 2004, 51],
      't': [{'c': [787, 952, 249, 36], 'tx': 'Chronique'},
       {'c': [1067, 952, 138, 36], 'tx': 'locale'},
       {'c': [1237, 962, 40, 26], 'tx': 'et'},
       {'c': [1308, 962, 233, 28], 'tx': 'régionale.'},
       {'c': [1586, 973, 29, 6], 'tx': '-'},
       {'c': [1662, 954, 190, 35], 'tx': 'Résumé'},
       {'c': [1884, 953, 76, 37], 'tx': 'des'},
       {'c': [1992, 963, 226, 27], 'tx': 'nouvelles'},
       {'c': [2250, 964, 173, 27], 'tx': 'suisses'},
       {'c': [2456, 965, 41, 27], 'tx': 'et'},
       {'c': [2527, 954, 264, 41], 'tx': 'étrangères.'}]},
     {'c': [1242, 1042, 1096, 30],
      't': [{'c': [1242, 1042, 316, 30], 'tx': 'PARAISSANT'},
       {'c': [1593, 1045, 54, 27], 'tx': 'LE'},
       {'c': [1684, 1043, 251, 29], 'tx': 'MERCREDI'},
       {'c': [1971, 1043, 58, 28], 'tx': 'ET'},
       {'c': [2063, 1043, 55, 28], 'tx': 'LE'},
       {'c': [2152, 1042, 186, 29], 'tx': 'SAMEDI'}]},
     {'c': [938, 1115, 1731, 47],
      't': [{'c': [938, 1116, 191, 36], 'tx': 'Rédaction'},
       {'c': [1158, 1132, 32, 20], 'tx': 'et'},
       {'c': [1219, 1116, 280, 36], 'tx': 'Administration'},
       {'c': [1519, 1132, 8, 21], 'tx': ':'},
       {'c': [1561, 1116, 249, 36], 'tx': 'Imprimerie'},
       {'c': [1840, 1116, 86, 38], 'tx': 'Rue'},
       {'c': [1955, 1117, 53, 36], 'tx': 'du'},
       {'c': [2039, 1117, 79, 36], 'tx': 'Lac'},
       {'c': [2148, 1119, 53, 35], 'tx': '23'},
       {'c': [2232, 1120, 32, 34], 'tx': '&'},
       {'c': [2295, 1117, 105, 37], 'tx': 'Quai'},
       {'c': [2435, 1118, 234, 38], 'tx': 'Lochmann'}]}]}],
  'pOf': 'FAM-1937-01-30-a-i0001'},
 {'c': [2884, 774, 548, 282],
  'p': [{'c': [2884, 774, 548, 282],
    'l': [{'c': [2958, 785, 413, 28],
      't': [{'c': [2958, 785, 89, 24], 'tx': 'Prix'},
       {'c': [3070, 785, 66, 25], 'tx': 'des'},
       {'c': [3158, 793, 193, 20], 'tx': 'annonces'},
       {'c': [3365, 797, 6, 16], 'tx': 'i'}]},
     {'c': [2992, 829, 339, 29],
      't': [{'c': [2992, 832, 98, 24], 'tx': 'District'},
       {'c': [3103, 837, 5, 18], 'tx': 'I'},
       {'c': [3128, 829, 17, 27], 'tx': '5'},
       {'c': [3160, 843, 63, 12], 'tx': 'cent,'},
       {'c': [3239, 832, 22, 25], 'tx': 'le'},
       {'c': [3277, 844, 54, 14], 'tx': 'mm.'}]},
     {'c': [2923, 865, 479, 32],
      't': [{'c': [2923, 868, 95, 24], 'tx': 'Canton'},
       {'c': [3031, 872, 5, 18], 'tx': 't'},
       {'c': [3054, 865, 16, 26], 'tx': '7'},
       {'c': [3085, 878, 63, 13], 'tx': 'cent.'},
       {'c': [3166, 878, 6, 19], 'tx': ';'},
       {'c': [3194, 868, 81, 25], 'tx': 'Suisse'},
       {'c': [3308, 867, 17, 26], 'tx': '9'},
       {'c': [3339, 880, 63, 14], 'tx': 'ctoaS»'}]},
     {'c': [3035, 901, 269, 34],
      't': [{'c': [3035, 904, 112, 24], 'tx': 'Etranger'},
       {'c': [3159, 921, 6, -7], 'tx': '.*'},
       {'c': [3189, 901, 32, 26], 'tx': '12'},
       {'c': [3240, 915, 64, 15], 'tx': 'cent.'}]},
     {'c': [3059, 946, 219, 27],
      't': [{'c': [3059, 948, 198, 24], 'tx': 'Réclames'},
       {'c': [3269, 956, 9, 17], 'tx': 's'}]},
     {'c': [2900, 981, 528, 34],
      't': [{'c': [2900, 984, 81, 24], 'tx': 'Suisse'},
       {'c': [2994, 1002, 6, -8], 'tx': '.*'},
       {'c': [3021, 982, 35, 25], 'tx': '20'},
       {'c': [3071, 995, 63, 13], 'tx': 'cent.'},
       {'c': [3157, 985, 114, 24], 'tx': 'Etranger'},
       {'c': [3282, 990, 7, 18], 'tx': 'I'},
       {'c': [3309, 982, 36, 27], 'tx': '25'},
       {'c': [3363, 996, 65, 15], 'tx': 'cent.'}]},
     {'c': [2953, 1027, 427, 24],
      't': [{'c': [2953, 1028, 79, 18], 'tx': 'Rabais'},
       {'c': [3047, 1033, 38, 13], 'tx': 'sur'},
       {'c': [3098, 1029, 33, 17], 'tx': '/es'},
       {'c': [3147, 1034, 111, 12], 'tx': 'annonces'},
       {'c': [3273, 1034, 107, 13], 'tx': 'répétées.'}]}]}],
  'pOf': 'FAM-1937-01-30-a-i0001'},
 {'c': [3084, 1120, 392, 46],
  'p': [{'c': [3084, 1120, 392, 46],
    'l': [{'c': [3100, 1127, 359, 35],
      't': [{'c': [3100, 1134, 223, 27], 'tx': 'TÉLÉPHONE'},
       {'c': [3359, 1135, 100, 27], 'tx': '72.154'}]}]}],
  'pOf': 'FAM-1937-01-30-a-i0001'},
 {'c': [106, 1240, 1262, 84],
  'p': [{'c': [106, 1240, 1262, 84],
    'l': [{'c': [121, 1257, 1232, 64],
      't': [{'c': [121, 1257, 154, 62], 'tx': 'CASINO'},
       {'c': [313, 1259, 50, 60], 'tx': 'de'},
       {'c': [401, 1257, 176, 62], 'tx': 'MORSES'},
       {'c': [689, 1257, 156, 62], 'tx': 'Grande'},
       {'c': [883, 1259, 106, 62], 'tx': 'salle'},
       {'c': [1025, 1259, 52, 62], 'tx': 'du'},
       {'c': [1115, 1259, 238, 62], 'tx': 'Restaurant'}]}]}],
  'pOf': 'FAM-1937-01-30-a-i0001'},
 {'c': [300, 1386, 880, 56],
  'p': [{'c': [300, 1386, 880, 56],
    'l': [{'c': [317, 1387, 848, 52],
      't': [{'c': [317, 1397, 252, 32], 'tx': 'MERCREDI'},
       {'c': [609, 1397, 26, 32], 'tx': '3'},
       {'c': [675, 1397, 228, 42], 'tx': 'FÉVRIER,'},
       {'c': [943, 1397, 20, 32], 'tx': 'à'},
       {'c': [1001, 1397, 44, 32], 'tx': '20'},
       {'c': [1065, 1397, 36, 32], 'tx': 'h.'},
       {'c': [1121, 1397, 44, 32], 'tx': '30'}]}]}],
  'pOf': 'FAM-1937-01-30-a-i0001'},
 {'c': [1488, 1244, 600, 90],
  'p': [{'c': [1488, 1244, 600, 90],
    'l': [{'c': [1503, 1261, 570, 68],
      't': [{'c': [1503, 1261, 186, 62], 'tx': 'Chapelle'},
       {'c': [1715, 1263, 50, 60], 'tx': 'de'},
       {'c': [1791, 1261, 154, 62], 'tx': 'relise'},
       {'c': [1971, 1263, 102, 60], 'tx': 'libre'}]}]}],
  'pOf': 'FAM-1937-01-30-a-i0001'},
 {'c': [1674, 1338, 224, 34],
  'p': [{'c': [1674, 1338, 224, 34],
    'l': [{'c': [1690, 1341, 192, 25],
      't': [{'c': [1690, 1343, 192, 23], 'tx': 'MORGES'}]}]}],
  'pOf': 'FAM-1937-01-30-a-i0001'},
 {'c': [1448, 1416, 666, 56],
  'p': [{'c': [1448, 1416, 666, 56],
    'l': [{'c': [1463, 1425, 638, 43],
      't': [{'c': [1463, 1426, 197, 32], 'tx': 'Dimanche'},
       {'c': [1690, 1425, 39, 33], 'tx': '31'},
       {'c': [1754, 1426, 154, 39], 'tx': 'janvier,'},
       {'c': [1940, 1428, 20, 31], 'tx': 'à'},
       {'c': [1991, 1426, 43, 33], 'tx': '20'},
       {'c': [2065, 1426, 36, 32], 'tx': 'h.'}]}]}],
  'pOf': 'FAM-1937-01-30-a-i0001'},
 {'c': [148, 1476, 1968, 162],
  'p': [{'c': [148, 1476, 1968, 162],
    'l': [{'c': [166, 1482, 1940, 156],
      't': [{'c': [166, 1482, 548, 140], 'tx': 'Assemblée'},
       {'c': [810, 1482, 504, 144], 'tx': 'Populaire'},
       {'c': [1470, 1506, 636, 104], 'tx': 'conférence'}]}]}],
  'pOf': 'FAM-1937-01-30-a-i0001'},
 {'c': [322, 1648, 494, 114],
  'p': [{'c': [322, 1648, 494, 114],
    'l': [{'c': [338, 1657, 460, 48],
      't': [{'c': [338, 1662, 168, 38], 'tx': 'organisée'},
       {'c': [536, 1662, 57, 38], 'tx': 'par'},
       {'c': [622, 1657, 48, 43], 'tx': 'les'},
       {'c': [700, 1662, 98, 38], 'tx': 'partis'}]},
     {'c': [364, 1724, 427, 33],
      't': [{'c': [364, 1724, 12, 15], 'tx': '*'},
       {'c': [686, 1739, 105, 18], 'tx': 'contre'}]}]}],
  'pOf': 'FAM-1937-01-30-a-i0001'},
 {'c': [962, 1648, 200, 56],
  'p': [{'c': [962, 1648, 200, 56],
    'l': [{'c': [979, 1657, 168, 44],
      't': [{'c': [979, 1663, 28, 38], 'tx': 'et'},
       {'c': [1037, 1657, 110, 44], 'tx': 'literal'}]}]}],
  'pOf': 'FAM-1937-01-30-a-i0001'},
 {'c': [214, 1778, 1050, 190],
  'p': [{'c': [214, 1778, 1050, 190],
    'l': [{'c': [441, 1793, 598, 62],
      't': [{'c': [441, 1795, 266, 60], 'tx': 'L’Initiative'},
       {'c': [747, 1809, 292, 46], 'tx': 'communiste'}]},
     {'c': [231, 1891, 1018, 72],
      't': [{'c': [231, 1907, 116, 44], 'tx': 'pour'},
       {'c': [383, 1891, 42, 60], 'tx': 'la'},
       {'c': [463, 1905, 364, 46], 'tx': 'représentation'},
       {'c': [865, 1907, 384, 46], 'tx': 'proportionnelle'}]}]}],
  'pOf': 'FAM-1937-01-30-a-i0001'},
 {'c': [58, 2004, 298, 36],
  'p': [{'c': [58, 2004, 298, 36],
    'l': [{'c': [74, 2009, 265, 27],
      't': [{'c': [74, 2010, 265, 24], 'tx': 'ORATEURS'}]}]}],
  'pOf': 'FAM-1937-01-30-a-i0001'},
 {'c': [56, 2056, 1364, 1334],
  'p': [{'c': [56, 2056, 1364, 1334],
    'l': [{'c': [72, 2070, 1336, 55],
      't': [{'c': [72, 2072, 128, 46], 'tx': 'MM.'},
       {'c': [233, 2071, 258, 47], 'tx': 'Norbert'},
       {'c': [525, 2072, 230, 53], 'tx': 'Bosset,'},
       {'c': [789, 2080, 199, 33], 'tx': 'président'},
       {'c': [1019, 2070, 45, 44], 'tx': 'de'},
       {'c': [1093, 2070, 37, 44], 'tx': 'la'},
       {'c': [1162, 2071, 246, 43], 'tx': 'Commission'}]},
     {'c': [633, 2125, 775, 45],
      't': [{'c': [633, 2125, 67, 43], 'tx': 'des'},
       {'c': [728, 2125, 177, 44], 'tx': 'finances'},
       {'c': [935, 2125, 45, 43], 'tx': 'du'},
       {'c': [1011, 2126, 153, 43], 'tx': 'Conseil'},
       {'c': [1195, 2125, 67, 44], 'tx': 'des'},
       {'c': [1291, 2126, 117, 43], 'tx': 'Etats.'}]},
     {'c': [232, 2190, 948, 56],
      't': [{'c': [232, 2192, 202, 47], 'tx': 'André'},
       {'c': [474, 2192, 245, 54], 'tx': 'Cordey,'},
       {'c': [760, 2192, 146, 50], 'tx': 'député,'},
       {'c': [937, 2192, 20, 43], 'tx': 'à'},
       {'c': [987, 2192, 193, 43], 'tx': 'Lausanne'}]},
     {'c': [348, 2322, 769, 43],
      't': [{'c': [348, 2322, 196, 33], 'tx': 'Invitation'},
       {'c': [566, 2333, 159, 22], 'tx': 'cordiale'},
       {'c': [746, 2324, 19, 31], 'tx': 'à'},
       {'c': [788, 2326, 76, 29], 'tx': 'tous'},
       {'c': [883, 2323, 46, 32], 'tx': 'tes'},
       {'c': [950, 2333, 167, 22], 'tx': 'citoyens.'}]},
     {'c': [214, 2440, 1048, 53],
      't': [{'c': [214, 2442, 381, 51], 'tx': 'TEMPLE'},
       {'c': [666, 2442, 120, 50], 'tx': 'DE'},
       {'c': [857, 2442, 405, 51], 'tx': 'MORGES'}]},
     {'c': [214, 2572, 1048, 33],
      't': [{'c': [214, 2573, 211, 28], 'tx': 'Samedi'},
       {'c': [467, 2573, 32, 28], 'tx': '6'},
       {'c': [543, 2573, 198, 27], 'tx': 'Février'},
       {'c': [778, 2573, 18, 27], 'tx': '1'},
       {'c': [808, 2572, 131, 33], 'tx': '937,'},
       {'c': [982, 2572, 26, 28], 'tx': 'à'},
       {'c': [1050, 2573, 63, 27], 'tx': '20'},
       {'c': [1137, 2573, 42, 27], 'tx': 'h.'},
       {'c': [1200, 2573, 62, 28], 'tx': '30'}]},
     {'c': [561, 2627, 353, 32],
      't': [{'c': [561, 2627, 120, 26], 'tx': '(Portes'},
       {'c': [701, 2628, 16, 24], 'tx': 'à'},
       {'c': [736, 2627, 35, 25], 'tx': '20'},
       {'c': [790, 2627, 124, 31], 'tx': 'heures)'}]},
     {'c': [79, 2719, 1326, 110],
      't': [{'c': [79, 2719, 660, 110], 'tx': 'CONCERT'},
       {'c': [833, 2721, 572, 108], 'tx': 'ANNUEL'}]},
     {'c': [336, 2881, 807, 59],
      't': [{'c': [336, 2882, 65, 57], 'tx': 'de'},
       {'c': [444, 2882, 44, 58], 'tx': 'la'},
       {'c': [537, 2899, 20, 32], 'tx': '«'},
       {'c': [583, 2884, 197, 53], 'tx': 'Jeune'},
       {'c': [827, 2884, 267, 54], 'tx': 'Helvétie'},
       {'c': [1117, 2899, 26, 40], 'tx': '»'}]},
     {'c': [114, 2982, 1248, 34],
      't': [{'c': [114, 2990, 83, 17], 'tx': 'offert'},
       {'c': [216, 2983, 17, 25], 'tx': 'à'},
       {'c': [249, 2990, 51, 17], 'tx': 'ses'},
       {'c': [318, 2991, 152, 18], 'tx': 'membres'},
       {'c': [487, 2983, 176, 26], 'tx': 'honoraires'},
       {'c': [680, 2991, 27, 17], 'tx': 'et'},
       {'c': [727, 2991, 124, 25], 'tx': 'passifs,'},
       {'c': [869, 2991, 73, 19], 'tx': 'avec'},
       {'c': [958, 2984, 26, 26], 'tx': 'le'},
       {'c': [1000, 2990, 144, 19], 'tx': 'précieux'},
       {'c': [1162, 2992, 147, 18], 'tx': 'concours'},
       {'c': [1325, 2985, 37, 25], 'tx': 'de'}]},
     {'c': [88, 3045, 1303, 44],
      't': [{'c': [88, 3047, 121, 30], 'tx': 'Mme'},
       {'c': [237, 3049, 47, 28], 'tx': 'L.'},
       {'c': [313, 3048, 250, 36], 'tx': 'CARDON,'},
       {'c': [588, 3056, 168, 28], 'tx': 'pianiste,'},
       {'c': [778, 3046, 159, 32], 'tx': 'lauréate'},
       {'c': [962, 3046, 49, 32], 'tx': 'du'},
       {'c': [1032, 3045, 166, 33], 'tx': 'Conserv.'},
       {'c': [1220, 3047, 43, 32], 'tx': 'de'},
       {'c': [1288, 3046, 103, 34], 'tx': 'Paris'}]},
     {'c': [301, 3117, 875, 42],
      't': [{'c': [301, 3117, 43, 32], 'tx': 'de'},
       {'c': [373, 3120, 100, 29], 'tx': 'MM.'},
       {'c': [504, 3120, 175, 30], 'tx': 'Robert'},
       {'c': [707, 3121, 73, 30], 'tx': 'DU'},
       {'c': [789, 3121, 73, 30], 'tx': 'RG'},
       {'c': [871, 3121, 174, 38], 'tx': 'NARD,'},
       {'c': [1072, 3118, 104, 33], 'tx': 'basse'}]},
     {'c': [90, 3175, 1292, 35],
      't': [{'c': [90, 3175, 102, 24], 'tx': 'Grand,'},
       {'c': [204, 3183, 71, 18], 'tx': 'prix'},
       {'c': [290, 3176, 162, 25], 'tx': 'd’honneur'},
       {'c': [468, 3176, 38, 25], 'tx': 'du'},
       {'c': [524, 3175, 144, 27], 'tx': 'Concours'},
       {'c': [683, 3176, 48, 26], 'tx': 'des'},
       {'c': [750, 3177, 162, 25], 'tx': 'Chanteurs'},
       {'c': [926, 3177, 156, 25], 'tx': 'Amateurs'},
       {'c': [1096, 3178, 172, 24], 'tx': '(Lausanne'},
       {'c': [1285, 3176, 80, 27], 'tx': '1936'},
       {'c': [1367, 3179, 15, 31], 'tx': 'J'}]},
     {'c': [207, 3238, 812, 40],
      't': [{'c': [207, 3241, 201, 30], 'tx': 'Georges'},
       {'c': [435, 3241, 289, 37], 'tx': 'CRUCHET,'},
       {'c': [752, 3249, 267, 22], 'tx': 'violoncelliste'}]},
     {'c': [545, 3298, 727, 42],
      't': [{'c': [545, 3307, 32, 21], 'tx': 'et'},
       {'c': [606, 3299, 47, 29], 'tx': 'P.'},
       {'c': [658, 3314, 67, 15], 'tx': '-A.'},
       {'c': [755, 3299, 307, 39], 'tx': 'GAILLARD,'},
       {'c': [1089, 3308, 183, 22], 'tx': 'organiste'}]},
     {'c': [386, 3360, 705, 26],
      't': [{'c': [386, 3361, 192, 23], 'tx': 'Direction'},
       {'c': [594, 3367, 4, 18], 'tx': ':'},
       {'c': [623, 3361, 44, 23], 'tx': 'M.'},
       {'c': [691, 3361, 117, 23], 'tx': 'Henri'},
       {'c': [834, 3361, 257, 24], 'tx': 'LAVANCHY'}]}]}],
  'pOf': 'FAM-1937-01-30-a-i0001'},
 {'c': [58, 3452, 1362, 220],
  'p': [{'c': [58, 3452, 1362, 220],
    'l': [{'c': [73, 3462, 1334, 43],
      't': [{'c': [73, 3463, 65, 33], 'tx': 'AU'},
       {'c': [159, 3462, 296, 32], 'tx': 'PROGRAMME'},
       {'c': [469, 3474, 9, 20], 'tx': ':'},
       {'c': [524, 3462, 82, 33], 'tx': 'Sept'},
       {'c': [633, 3462, 116, 33], 'tx': 'beaux'},
       {'c': [769, 3473, 141, 21], 'tx': 'chœurs'},
       {'c': [931, 3462, 42, 31], 'tx': 'de'},
       {'c': [995, 3473, 67, 21], 'tx': 'van'},
       {'c': [1085, 3462, 211, 36], 'tx': 'Beethoven,'},
       {'c': [1325, 3463, 82, 23], 'tx': 'Via-'}]},
     {'c': [139, 3515, 1266, 45],
      't': [{'c': [139, 3516, 107, 35], 'tx': 'dana,'},
       {'c': [269, 3516, 86, 33], 'tx': 'Max'},
       {'c': [376, 3516, 135, 38], 'tx': 'Bruch,'},
       {'c': [532, 3516, 31, 31], 'tx': 'J.'},
       {'c': [584, 3516, 210, 38], 'tx': 'Apolhéloz,'},
       {'c': [815, 3516, 197, 26], 'tx': 'Plumhof,-'},
       {'c': [1024, 3515, 183, 39], 'tx': 'Piantoni,'},
       {'c': [1228, 3516, 123, 33], 'tx': 'Hegar'},
       {'c': [1375, 3528, 30, 21], 'tx': 'et'}]},
     {'c': [140, 3569, 1265, 43],
      't': [{'c': [140, 3570, 172, 32], 'tx': 'Rameau.'},
       {'c': [332, 3590, 43, 3], 'tx': '—'},
       {'c': [395, 3569, 54, 33], 'tx': 'En'},
       {'c': [467, 3580, 93, 26], 'tx': 'plus,'},
       {'c': [584, 3581, 67, 21], 'tx': 'une'},
       {'c': [667, 3581, 166, 21], 'tx': 'primeur'},
       {'c': [853, 3570, 42, 32], 'tx': 'de'},
       {'c': [914, 3569, 41, 33], 'tx': 'A.'},
       {'c': [978, 3569, 204, 33], 'tx': 'Dénéréaz:'},
       {'c': [1205, 3584, 14, 16], 'tx': '«'},
       {'c': [1237, 3570, 168, 33], 'tx': 'Chanson'}]},
     {'c': [139, 3623, 1266, 44],
      't': [{'c': [139, 3624, 48, 32], 'tx': 'du'},
       {'c': [208, 3623, 203, 33], 'tx': 'Printemps'},
       {'c': [429, 3638, 26, 23], 'tx': '»,'},
       {'c': [478, 3634, 124, 22], 'tx': 'chœur'},
       {'c': [622, 3624, 42, 32], 'tx': 'de'},
       {'c': [684, 3635, 110, 21], 'tx': 'choix'},
       {'c': [810, 3634, 96, 21], 'tx': 'pour'},

In [5]:
example_2 = '/home/piconti/impresso-text-acquisition/text_importer/data/sample_data/BCUL/171722/ACI_1832_00_00_0001_page_1.xml'

with open(example_2, encoding='utf-8') as f:
    xml_doc_2 = BeautifulSoup(f, "xml")

text_blocks = xml_doc_2.findAll("block", {"blockType": "Text"})
page_data = [parse_textblock(tb, "ACI-1832-01-01-a-i0001") for tb in text_blocks]
page_data

inside parse_char_tokens: [<charParams b="1526" charConfidence="98" l="359" meanStrokeWidth="32" r="395" serifProbability="81" t="1486" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="1">L</charParams>, <charParams b="1526" charConfidence="83" l="400" meanStrokeWidth="32" r="437" serifProbability="98" t="1485" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">A</charParams>, <charParams b="1525" charConfidence="80" l="442" meanStrokeWidth="32" r="482" serifProbability="100" t="1483" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">U</charParams>, <charParams b="1523" charConfidence="92" l="488" meanStrokeWidth="32" r="521" serifProbability="73" t="1482" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">S</charParams>, <charParams b="1521" charConfidence="94" l="525" meanStrokeWidth="32" r="563" serifProbability="98" t="1480" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">A</charParams>, <charParams b="1520" charConfidence="49" l="569" meanStrokeWidth="32" r="610" serifProbability="100" t="1479" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">N</charParams>, <charParams b="1519" charConfidence="80" l="613" meanStrokeWidth="32" r="655" serifProbability="100" t="1478" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">N</charParams>, <charParams b="1519" charConfidence="94" l="659" meanStrokeWidth="32" r="695" serifProbability="100" t="1478" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">E</charParams>]
1 False None False
0 False None False
0 False None False
0 False None False
0 False None False
0 False None False
0 False None False
0 False None False
inside parse_char_tokens: [<charParams b="1596" charConfidence="89" l="160" meanStrokeWidth="50" r="178" serifProbability="98" t="1571" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="1">A</charParams>, <charParams b="1596" charConfidence="96" l="180" meanStrokeWidth="50" r="201" serifProbability="100" t="1570" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">U</charParams>, <charParams b="1596" l="202" r="215" t="1570"> </charParams>, <charParams b="1595" charConfidence="92" l="216" meanStrokeWidth="51" r="236" serifProbability="43" t="1570" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="5" wordStart="1">B</charParams>, <charParams b="1594" charConfidence="96" l="239" meanStrokeWidth="51" r="258" serifProbability="98" t="1572" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="5" wordStart="0">A</charParams>, <charParams b="1595" charConfidence="94" l="262" meanStrokeWidth="51" r="281" serifProbability="255" t="1569" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="5" wordStart="0">Z</charParams>, <charParams b="1595" l="282" r="285" t="1569"> </charParams>, <charParams b="1594" charConfidence="89" l="286" meanStrokeWidth="51" r="304" serifProbability="98" t="1571" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="5" wordStart="1">A</charParams>, <charParams b="1593" charConfidence="83" l="307" meanStrokeWidth="51" r="327" serifProbability="255" t="1568" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="5" wordStart="0">R</charParams>, <charParams b="1593" l="328" r="340" t="1567"> </charParams>, <charParams b="1592" charConfidence="100" l="341" meanStrokeWidth="57" r="362" serifProbability="52" t="1567" wordFromDictionary="0" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="1">V</charParams>, <charParams b="1592" charConfidence="90" l="366" meanStrokeWidth="57" r="386" serifProbability="98" t="1568" wordFromDictionary="0" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">A</charParams>, <charParams b="1593" charConfidence="100" l="386" meanStrokeWidth="57" r="410" serifProbability="100" t="1566" wordFromDictionary="0" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">U</charParams>, <charParams b="1592" charConfidence="100" l="411" meanStrokeWidth="57" r="433" serifProbability="89" t="1566" wordFromDictionary="0" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">D</charParams>, <charParams b="1590" charConfidence="100" l="437" meanStrokeWidth="57" r="459" serifProbability="255" suspicious="1" t="1565" wordFromDictionary="0" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">O</charParams>, <charParams b="1589" charConfidence="100" l="461" meanStrokeWidth="57" r="472" serifProbability="100" t="1565" wordFromDictionary="0" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">I</charParams>, <charParams b="1590" charConfidence="96" l="473" meanStrokeWidth="57" r="491" serifProbability="73" t="1563" wordFromDictionary="0" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">S</charParams>, <charParams b="1594" l="492" r="501" t="1563"> </charParams>, <charParams b="1594" charConfidence="98" l="502" meanStrokeWidth="49" r="507" serifProbability="255" suspicious="1" t="1585" wordFromDictionary="0" wordIdentifier="1" wordNormal="0" wordNumeric="0" wordPenalty="0" wordStart="1">,</charParams>, <charParams b="1594" l="508" r="529" t="1565"> </charParams>, <charParams b="1587" charConfidence="96" l="530" meanStrokeWidth="56" r="549" serifProbability="98" t="1565" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="4" wordStart="1">A</charParams>, <charParams b="1588" charConfidence="98" l="552" meanStrokeWidth="56" r="573" serifProbability="100" t="1562" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="4" wordStart="0">U</charParams>, <charParams b="1588" l="574" r="584" t="1561"> </charParams>, <charParams b="1587" charConfidence="98" l="585" meanStrokeWidth="49" r="606" serifProbability="49" t="1561" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="1">C</charParams>, <charParams b="1588" charConfidence="98" l="606" meanStrokeWidth="49" r="631" serifProbability="94" t="1560" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">H</charParams>, <charParams b="1588" charConfidence="87" l="630" meanStrokeWidth="49" r="652" serifProbability="100" t="1561" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">E</charParams>, <charParams b="1587" charConfidence="90" l="656" meanStrokeWidth="49" r="681" serifProbability="93" t="1561" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">M</charParams>, <charParams b="1586" charConfidence="100" l="684" meanStrokeWidth="49" r="692" serifProbability="100" t="1561" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">I</charParams>, <charParams b="1586" charConfidence="87" l="696" meanStrokeWidth="49" r="718" serifProbability="100" t="1560" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">N</charParams>, <charParams b="1579" charConfidence="100" l="720" meanStrokeWidth="49" r="730" serifProbability="255" t="1576" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">-</charParams>, <charParams b="1586" charConfidence="63" l="732" meanStrokeWidth="49" r="754" serifProbability="100" t="1560" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">N</charParams>, <charParams b="1586" charConfidence="100" l="756" meanStrokeWidth="49" r="776" serifProbability="100" t="1560" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">E</charParams>, <charParams b="1585" charConfidence="100" l="779" meanStrokeWidth="49" r="800" serifProbability="100" t="1559" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">U</charParams>, <charParams b="1584" charConfidence="90" l="802" meanStrokeWidth="49" r="823" serifProbability="76" suspicious="1" t="1559" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">F</charParams>, <charParams b="1590" charConfidence="100" l="832" meanStrokeWidth="49" r="836" serifProbability="255" t="1580" wordFromDictionary="0" wordIdentifier="1" wordNormal="0" wordNumeric="0" wordPenalty="0" wordStart="1">,</charParams>, <charParams b="1590" l="837" r="854" t="1558"> </charParams>, <charParams b="1584" charConfidence="89" l="855" meanStrokeWidth="29" r="879" serifProbability="100" suspicious="1" t="1558" wordFromDictionary="0" wordIdentifier="0" wordNormal="0" wordNumeric="0" wordPenalty="0" wordStart="1">N</charParams>, <charParams b="1574" charConfidence="98" l="880" meanStrokeWidth="29" r="893" serifProbability="255" t="1562" wordFromDictionary="0" wordIdentifier="0" wordNormal="0" wordNumeric="0" wordPenalty="0" wordStart="0">°</charParams>, <charParams b="1591" l="894" r="903" t="1556"> </charParams>, <charParams b="1591" charConfidence="94" l="904" meanStrokeWidth="28" r="919" serifProbability="255" suspicious="1" t="1556" wordFromDictionary="0" wordIdentifier="0" wordNormal="0" wordNumeric="1" wordPenalty="13" wordStart="1">4</charParams>]
1 False None False
0 False None False
None False None False
1 False None False
0 False None False
0 False None False
None False None False
1 False None False
0 False None False
None False None False
1 False None False
0 False None False
0 False None False
0 False None False
0 False None False
0 False None False
0 False None False
None False None False
1 False None False
None False None False
1 False None False
0 False None False
None False None False
1 False None False
0 False None False
0 False None False
0 False None False
0 False None False
0 False None False
0 False None False
0 False None False
0 False None False
0 False None False
0 False None False
1 False None False
None False None False
1 False None False
0 False None False
None False None False
1 False None False
inside parse_char_tokens: [<charParams b="259" charConfidence="89" l="163" meanStrokeWidth="63" r="243" serifProbability="255" suspicious="1" t="211" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="3" wordStart="1">u</charParams>, <charParams b="257" charConfidence="94" l="247" meanStrokeWidth="63" r="303" serifProbability="100" suspicious="1" t="207" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="3" wordStart="0">s</charParams>, <charParams b="263" charConfidence="90" l="301" meanStrokeWidth="63" r="337" serifProbability="11" suspicious="1" t="209" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="1">s</charParams>]
1 False None False
0 False None False
1 False None False
inside parse_char_tokens: [<charParams b="413" charConfidence="96" l="303" meanStrokeWidth="187" r="361" serifProbability="98" t="359" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="1">A</charParams>, <charParams b="413" charConfidence="98" l="363" meanStrokeWidth="187" r="415" serifProbability="81" t="357" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">L</charParams>, <charParams b="411" charConfidence="92" l="421" meanStrokeWidth="187" r="487" serifProbability="94" t="357" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">M</charParams>, <charParams b="411" charConfidence="98" l="489" meanStrokeWidth="187" r="547" serifProbability="98" t="357" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">A</charParams>, <charParams b="411" charConfidence="72" l="549" meanStrokeWidth="187" r="605" serifProbability="255" suspicious="1" t="355" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">N</charParams>, <charParams b="411" charConfidence="98" l="607" meanStrokeWidth="187" r="663" serifProbability="98" t="357" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">A</charParams>, <charParams b="411" charConfidence="96" l="667" meanStrokeWidth="187" r="717" serifProbability="77" t="353" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">C</charParams>, <charParams b="409" charConfidence="85" l="721" meanStrokeWidth="187" r="783" serifProbability="255" t="355" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">H</charParams>]
1 False None False
0 False None False
0 False None False
0 False None False
0 False None False
0 False None False
0 False None False
0 False None False
inside parse_char_tokens: [<charParams b="517" charConfidence="98" l="490" meanStrokeWidth="50" r="509" serifProbability="96" t="494" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="1">P</charParams>, <charParams b="517" charConfidence="100" l="512" meanStrokeWidth="50" r="536" serifProbability="255" t="492" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">O</charParams>, <charParams b="517" charConfidence="94" l="538" meanStrokeWidth="50" r="560" serifProbability="100" t="494" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">U</charParams>, <charParams b="517" charConfidence="94" l="564" meanStrokeWidth="50" r="587" serifProbability="100" t="493" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">R</charParams>]
1 False None False
0 False None False
0 False None False
0 False None False
inside parse_char_tokens: [<charParams b="845" charConfidence="100" l="346" meanStrokeWidth="105" r="379" serifProbability="81" t="810" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="1">L</charParams>, <charParams b="821" charConfidence="94" l="387" meanStrokeWidth="105" r="394" serifProbability="255" t="810" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">'</charParams>, <charParams b="845" charConfidence="100" l="400" meanStrokeWidth="105" r="416" serifProbability="100" t="810" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">I</charParams>, <charParams b="844" charConfidence="60" l="421" meanStrokeWidth="105" r="455" serifProbability="100" t="808" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">N</charParams>, <charParams b="843" charConfidence="94" l="461" meanStrokeWidth="105" r="493" serifProbability="17" t="809" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">D</charParams>, <charParams b="844" charConfidence="81" l="496" meanStrokeWidth="105" r="530" serifProbability="100" t="808" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">U</charParams>, <charParams b="843" charConfidence="94" l="535" meanStrokeWidth="105" r="562" serifProbability="73" t="807" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">S</charParams>, <charParams b="842" charConfidence="100" l="566" meanStrokeWidth="105" r="600" serifProbability="255" t="807" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">T</charParams>, <charParams b="841" charConfidence="96" l="605" meanStrokeWidth="105" r="638" serifProbability="100" t="807" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">R</charParams>, <charParams b="840" charConfidence="100" l="643" meanStrokeWidth="105" r="658" serifProbability="100" t="806" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">I</charParams>, <charParams b="841" charConfidence="100" l="664" meanStrokeWidth="105" r="696" serifProbability="100" t="806" wordFromDictionary="1" wordIdentifier="0" wordNormal="1" wordNumeric="0" wordPenalty="0" wordStart="0">E</charParams>]
1 False None False
0 False None False
0 False None False
0 False None False
0 False None False
0 False None False
0 False None False
0 False None False
0 False None False
0 False None False
0 False None False

[{'c': [352, 1471, 350, 61],
  'p': [{'c': [352, 1471, 350, 61],
    'l': [{'c': [359, 1478, 336, 48],
      't': [{'c': [359, 1486, 336, 33], 'tx': 'LAUSANNE'}]}]}],
  'pOf': 'ACI-1832-01-01-a-i0001'},
 {'c': [153, 1552, 772, 51],
  'p': [{'c': [153, 1552, 772, 51],
    'l': [{'c': [160, 1556, 759, 40],
      't': [{'c': [160, 1571, 41, 25], 'tx': 'AU'},
       {'c': [216, 1570, 65, 25], 'tx': 'BAZ'},
       {'c': [286, 1571, 41, 22], 'tx': 'AR'},
       {'c': [341, 1567, 150, 23], 'tx': 'VAUDOIS'},
       {'c': [502, 1585, 5, 9], 'tx': ','},
       {'c': [530, 1565, 43, 23], 'tx': 'AU'},
       {'c': [585, 1561, 238, 23], 'tx': 'CHEMIN-NEUF'},
       {'c': [832, 1580, 4, 10], 'tx': ','},
       {'c': [855, 1558, 38, 16], 'tx': 'N°'},
       {'c': [904, 1556, 15, 35], 'tx': '4'}]}]}],
  'pOf': 'ACI-1832-01-01-a-i0001'},
 {'c': [162, 206, 172, 56],
  'p': [{'c': [162, 206, 172, 56],
    'l': [{'c': [163, 207, 174, 56],
      't': [{'c': [163, 211, 140, 46], 'tx': 'us'},
       {'c': [301, 209, 36, 54], 'tx': 's'}]}]}],
  'pOf': 'ACI-1832-01-01-a-i0001'},
 {'c': [288, 350, 498, 66],
  'p': [{'c': [288, 350, 498, 66],
    'l': [{'c': [303, 353, 480, 60],
      't': [{'c': [303, 359, 480, 50], 'tx': 'ALMANACH'}]}]}],
  'pOf': 'ACI-1832-01-01-a-i0001'},
 {'c': [474, 486, 130, 36],
  'p': [{'c': [474, 486, 130, 36],
    'l': [{'c': [490, 492, 97, 25],
      't': [{'c': [490, 494, 97, 23], 'tx': 'POUR'}]}]}],
  'pOf': 'ACI-1832-01-01-a-i0001'},
 {'c': [330, 796, 382, 54],
  'p': [{'c': [330, 796, 382, 54],
    'l': [{'c': [346, 806, 350, 39],
      't': [{'c': [346, 810, 350, 31], 'tx': "L'INDUSTRIE"}]}]}],
  'pOf': 'ACI-1832-01-01-a-i0001'},
 {'c': [140, 898, 804, 200],
  'p': [{'c': [140, 898, 804, 200],
    'l': [{'c': [157, 914, 771, 24],
      't': [{'c': [157, 919, 158, 18], 'tx': 'CONTENANT'},
       {'c': [328, 920, 43, 17], 'tx': 'LES'},
       {'c': [384, 919, 71, 16], 'tx': 'NOMS'},
       {'c': [467, 917, 32, 17], 'tx': 'ET'},
       {'c': [512, 917, 30, 17], 'tx': 'LA'},
       {'c': [562, 916, 122, 17], 'tx': 'DEMEURE'},
       {'c': [698, 915, 46, 18], 'tx': 'DES'},
       {'c': [761, 915, 167, 18], 'tx': 'PRINCIPALES'}]},
     {'c': [172, 946, 756, 36],
      't': [{'c': [172, 959, 145, 17], 'tx': 'AUTORITÉS'},
       {'c': [326, 971, 6, 11], 'tx': ','},
       {'c': [344, 958, 46, 17], 'tx': 'DES'},
       {'c': [402, 958, 147, 15], 'tx': 'RANQUIERS'},
       {'c': [559, 968, 6, 10], 'tx': ','},
       {'c': [577, 956, 148, 17], 'tx': 'NEGOCIANS'},
       {'c': [734, 966, 7, 11], 'tx': ','},
       {'c': [753, 954, 78, 18], 'tx': 'CHEFS'},
       {'c': [841, 954, 87, 15], 'tx': 'd’ATE-'}]},
     {'c': [174, 987, 755, 33],
      't': [{'c': [174, 997, 71, 18], 'tx': 'LIERS'},
       {'c': [258, 1010, 6, 10], 'tx': ','},
       {'c': [283, 996, 32, 18], 'tx': 'ET'},
       {'c': [327, 996, 33, 19], 'tx': 'EN'},
       {'c': [374, 996, 122, 16], 'tx': 'GÉNÉRAI.'},
       {'c': [506, 994, 45, 16], 'tx': 'DES'},
       {'c': [563, 993, 149, 16], 'tx': 'PERSONNES'},
       {'c': [726, 991, 136, 18], 'tx': 'EXERÇANT'},
       {'c': [878, 992, 51, 19], 'tx': 'UNE'}]},
     {'c': [171, 1028, 755, 33],
      't': [{'c': [171, 1035, 140, 18], 'tx': 'INDUSTRIE'},
       {'c': [329, 1037, 172, 12], 'tx': '(QUELCONQUE'},
       {'c': [518, 1030, 16, 19], 'tx': 'A'},
       {'c': [552, 1032, 135, 16], 'tx': 'LAUSANNE'},
       {'c': [699, 1030, 31, 17], 'tx': 'ET'},
       {'c': [744, 1030, 65, 17], 'tx': 'DANS'},
       {'c': [824, 1030, 41, 17], 'tx': 'LES'},
       {'c': [880, 1029, 46, 14], 'tx': 'AU¬'}]},
     {'c': [173, 1069, 497, 24],
      't': [{'c': [173, 1074, 63, 18], 'tx': 'TRES'},
       {'c': [255, 1074, 87, 18], 'tx': 'VILLES'},
       {'c': [364, 1074, 32, 16], 'tx': 'DU'},
       {'c': [416, 1072, 106, 17], 'tx': 'CANTON'},
       {'c': [537, 1071, 34, 17], 'tx': 'DE'},
       {'c': [589, 1069, 81, 17], 'tx': 'VAUD.'}]}]}],
  'pOf': 'ACI-1832-01-01-a-i0001'}]

In [6]:
example_3 = '/home/piconti/impresso-text-acquisition/text_importer/data/sample_data/BCUL/46165/FAL_1762_12_07_0001_page_1.xml'

with open(example_3, encoding='utf-8') as f:
    xml_doc_3 = BeautifulSoup(f, "xml")

text_blocks = xml_doc_3.findAll("block", {"blockType": "Text"})
page_data = [parse_textblock(tb, "ACI-1832-01-01-a-i0001") for tb in text_blocks]
page_data

inside parse_char_tokens: [<charParams b="147" charConfidence="34" l="925" meanStrokeWidth="44" r="941" serifProbability="255" t="99" wordFromDictionary="false" wordIdentifier="true" wordNormal="false" wordNumeric="false" wordPenalty="0" wordStart="true">)</charParams>, <charParams b="144" charConfidence="25" l="951" meanStrokeWidth="44" r="964" serifProbability="255" t="100" wordFromDictionary="false" wordIdentifier="true" wordNormal="false" wordNumeric="false" wordPenalty="0" wordStart="false">(</charParams>, <charParams b="145" l="964" r="979" t="100"> </charParams>, <charParams b="145" l="979" r="994" t="100"> </charParams>, <charParams b="145" l="994" r="1009" t="100"> </charParams>, <charParams b="145" l="1009" r="1024" t="100"> </charParams>, <charParams b="145" charConfidence="25" l="1024" meanStrokeWidth="39" r="1046" serifProbability="74" t="110" wordFromDictionary="false" wordIdentifier="false" wordNormal="false" wordNumeric="true" wordPenalty="2" wordStart="true">9</charParams>, <charParams b="143" charConfidence="17" l="1059" meanStrokeWidth="39" r="1076" serifProbability="100" suspicious="true" t="107" wordFromDictionary="false" wordIdentifier="false" wordNormal="false" wordNumeric="true" wordPenalty="2" wordStart="false">1</charParams>, <charParams b="145" l="1076" r="1090" t="92"> </charParams>, <charParams b="145" l="1090" r="1104" t="92"> </charParams>, <charParams b="145" l="1104" r="1118" t="92"> </charParams>, <charParams b="145" l="1118" r="1132" t="92"> </charParams>, <charParams b="145" l="1132" r="1147" t="92"> </charParams>, <charParams b="142" charConfidence="16" l="1147" meanStrokeWidth="77" r="1186" serifProbability="255" t="92" wordFromDictionary="false" wordIdentifier="true" wordNormal="false" wordNumeric="true" wordPenalty="0" wordStart="true">X</charParams>]
true False None False
false False None False
None False None False
None False None False
None False None False
None False None False
true False None False
false False None False
None False None False
None False None False
None False None False
None False None False
None False None False
true False None False
inside parse_char_tokens: [<charParams b="442" charConfidence="98" l="320" meanStrokeWidth="48" r="413" serifProbability="98" t="354" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="0" wordStart="true">A</charParams>, <charParams b="441" l="413" r="448" t="348"> </charParams>, <charParams b="441" l="448" r="483" t="348"> </charParams>, <charParams b="441" l="483" r="519" t="348"> </charParams>, <charParams b="441" charConfidence="100" l="519" meanStrokeWidth="48" r="613" serifProbability="100" t="348" wordFromDictionary="false" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="0" wordStart="true">N</charParams>, <charParams b="437" l="613" r="649" t="347"> </charParams>, <charParams b="437" l="649" r="685" t="347"> </charParams>, <charParams b="437" l="685" r="722" t="347"> </charParams>, <charParams b="437" charConfidence="55" l="722" meanStrokeWidth="48" r="814" serifProbability="100" t="347" wordFromDictionary="false" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="0" wordStart="true">N</charParams>, <charParams b="434" l="814" r="850" t="344"> </charParams>, <charParams b="434" l="850" r="886" t="344"> </charParams>, <charParams b="434" l="886" r="922" t="344"> </charParams>, <charParams b="434" charConfidence="100" l="922" meanStrokeWidth="48" r="1009" serifProbability="255" suspicious="true" t="344" wordFromDictionary="false" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="0" wordStart="true">O</charParams>, <charParams b="430" l="1009" r="1044" t="338"> </charParams>, <charParams b="430" l="1044" r="1080" t="338"> </charParams>, <charParams b="430" l="1080" r="1116" t="338"> </charParams>, <charParams b="429" charConfidence="100" l="1116" meanStrokeWidth="38" r="1208" serifProbability="100" t="338" wordFromDictionary="false" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="0" wordStart="true">N</charParams>, <charParams b="430" l="1208" r="1244" t="338"> </charParams>, <charParams b="430" l="1244" r="1280" t="338"> </charParams>, <charParams b="430" l="1280" r="1317" t="338"> </charParams>, <charParams b="429" charConfidence="33" l="1317" meanStrokeWidth="167" r="1400" serifProbability="30" t="340" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="0" wordStart="true">G</charParams>, <charParams b="430" l="1400" r="1435" t="336"> </charParams>, <charParams b="430" l="1435" r="1470" t="336"> </charParams>, <charParams b="430" l="1470" r="1506" t="336"> </charParams>, <charParams b="428" charConfidence="100" l="1506" meanStrokeWidth="56" r="1581" serifProbability="100" t="336" wordFromDictionary="false" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="0" wordStart="true">E</charParams>, <charParams b="430" l="1581" r="1615" t="336"> </charParams>, <charParams b="430" l="1615" r="1649" t="336"> </charParams>, <charParams b="430" l="1649" r="1684" t="336"> </charParams>, <charParams b="426" charConfidence="97" l="1684" meanStrokeWidth="128" r="1736" serifProbability="73" t="338" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="0" wordStart="true">S</charParams>, <charParams b="435" charConfidence="27" l="1758" meanStrokeWidth="128" r="1779" serifProbability="255" t="399" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="0" wordStart="false">,</charParams>]
true False None False
None False None False
None False None False
None False None False
true False None False
None False None False
None False None False
None False None False
true False None False
None False None False
None False None False
None False None False
true False None False
None False None False
None False None False
None False None False
true False None False
None False None False
None False None False
None False None False
true False None False
None False None False
None False None False
None False None False
true False None False
None False None False
None False None False
None False None False
true False None False
false False None False
inside parse_char_tokens: [<charParams b="535" charConfidence="43" l="608" meanStrokeWidth="81" r="648" serifProbability="100" t="485" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="0" wordStart="true">E</charParams>, <charParams b="533" charConfidence="68" l="670" meanStrokeWidth="81" r="718" serifProbability="255" t="483" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="0" wordStart="false">T</charParams>, <charParams b="533" l="718" r="739" t="483"> </charParams>, <charParams b="533" l="739" r="761" t="483"> </charParams>, <charParams b="533" l="761" r="783" t="483"> </charParams>, <charParams b="533" l="783" r="805" t="483"> </charParams>, <charParams b="533" charConfidence="45" l="805" meanStrokeWidth="75" r="852" serifProbability="98" t="483" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="0" wordStart="true">A</charParams>, <charParams b="532" charConfidence="29" l="874" meanStrokeWidth="75" r="921" serifProbability="50" suspicious="true" t="482" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="0" wordStart="false">V</charParams>, <charParams b="530" charConfidence="21" l="946" meanStrokeWidth="75" r="967" serifProbability="100" suspicious="true" t="481" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="0" wordStart="false">I</charParams>, <charParams b="530" charConfidence="100" l="993" meanStrokeWidth="75" r="1025" serifProbability="73" t="479" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="0" wordStart="false">S</charParams>, <charParams b="529" l="1025" r="1046" t="477"> </charParams>, <charParams b="529" l="1046" r="1067" t="477"> </charParams>, <charParams b="529" l="1067" r="1088" t="477"> </charParams>, <charParams b="529" l="1088" r="1109" t="477"> </charParams>, <charParams b="528" charConfidence="79" l="1109" meanStrokeWidth="80" r="1158" serifProbability="89" t="477" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="0" wordStart="true">D</charParams>, <charParams b="525" charConfidence="46" l="1183" meanStrokeWidth="80" r="1206" serifProbability="100" t="475" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="0" wordStart="false">I</charParams>, <charParams b="525" charConfidence="32" l="1229" meanStrokeWidth="80" r="1277" serifProbability="50" t="475" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="0" wordStart="false">V</charParams>, <charParams b="523" charConfidence="67" l="1301" meanStrokeWidth="80" r="1341" serifProbability="100" t="474" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="0" wordStart="false">E</charParams>, <charParams b="526" charConfidence="41" l="1365" meanStrokeWidth="80" r="1415" serifProbability="100" suspicious="true" t="476" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="0" wordStart="false">R</charParams>, <charParams b="527" charConfidence="100" l="1437" meanStrokeWidth="80" r="1468" serifProbability="73" suspicious="true" t="476" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="0" wordStart="false">S</charParams>, <charParams b="528" charConfidence="100" l="1475" meanStrokeWidth="80" r="1486" serifProbability="255" t="516" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="0" wordStart="false">.</charParams>]
true False None False
false False None False
None False None False
None False None False
None False None False
None False None False
true False None False
false False None False
false False None False
false False None False
None False None False
None False None False
None False None False
None False None False
true False None False
false False None False
false False None False
false False None False
false False None False
false False None False
false False None False
inside parse_char_tokens: [<charParams b="613" charConfidence="26" l="494" meanStrokeWidth="56" r="533" serifProbability="255" t="575" wordFromDictionary="false" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="27" wordStart="true">X</charParams>, <charParams b="612" charConfidence="12" l="551" meanStrokeWidth="56" r="590" serifProbability="255" t="573" wordFromDictionary="false" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="27" wordStart="false">X</charParams>, <charParams b="611" charConfidence="79" l="608" meanStrokeWidth="56" r="626" serifProbability="100" t="572" wordFromDictionary="false" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="27" wordStart="false">I</charParams>, <charParams b="611" charConfidence="43" l="646" meanStrokeWidth="56" r="678" serifProbability="50" t="572" wordFromDictionary="false" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="27" wordStart="false">V</charParams>, <charParams b="602" charConfidence="27" l="693" meanStrokeWidth="56" r="719" serifProbability="94" suspicious="true" t="578" wordFromDictionary="false" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="27" wordStart="false">m</charParams>, <charParams b="602" charConfidence="26" l="733" meanStrokeWidth="56" r="754" serifProbability="100" t="579" wordFromDictionary="false" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="27" wordStart="false">e</charParams>, <charParams b="611" charConfidence="57" l="758" meanStrokeWidth="56" r="767" serifProbability="255" t="601" wordFromDictionary="false" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="27" wordStart="false">.</charParams>, <charParams b="607" l="767" r="782" t="571"> </charParams>, <charParams b="607" l="782" r="797" t="571"> </charParams>, <charParams b="607" l="797" r="812" t="571"> </charParams>, <charParams b="607" l="812" r="828" t="571"> </charParams>, <charParams b="607" charConfidence="50" l="828" meanStrokeWidth="70" r="857" serifProbability="100" t="571" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="2" wordStart="true">F</charParams>, <charParams b="607" charConfidence="100" l="873" meanStrokeWidth="70" r="902" serifProbability="100" t="571" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="2" wordStart="false">E</charParams>, <charParams b="607" charConfidence="100" l="918" meanStrokeWidth="70" r="951" serifProbability="100" t="570" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="2" wordStart="false">U</charParams>, <charParams b="606" charConfidence="32" l="964" meanStrokeWidth="70" r="982" serifProbability="75" t="569" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="2" wordStart="false">I</charParams>, <charParams b="606" charConfidence="66" l="997" meanStrokeWidth="70" r="1025" serifProbability="81" t="569" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="2" wordStart="false">L</charParams>, <charParams b="606" charConfidence="34" l="1038" meanStrokeWidth="70" r="1068" serifProbability="100" t="568" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="2" wordStart="false">L</charParams>, <charParams b="606" charConfidence="100" l="1083" meanStrokeWidth="70" r="1114" serifProbability="100" t="568" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="2" wordStart="false">E</charParams>, <charParams b="605" l="1114" r="1130" t="566"> </charParams>, <charParams b="605" l="1130" r="1146" t="566"> </charParams>, <charParams b="605" l="1146" r="1162" t="566"> </charParams>, <charParams b="605" l="1162" r="1178" t="566"> </charParams>, <charParams b="605" charConfidence="21" l="1178" meanStrokeWidth="70" r="1207" serifProbability="98" t="566" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="6" wordStart="true">P</charParams>, <charParams b="602" charConfidence="18" l="1220" meanStrokeWidth="70" r="1248" serifProbability="100" t="549" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="6" wordStart="false">É</charParams>, <charParams b="601" charConfidence="37" l="1265" meanStrokeWidth="70" r="1297" serifProbability="100" t="562" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="6" wordStart="false">R</charParams>, <charParams b="600" charConfidence="86" l="1310" meanStrokeWidth="70" r="1328" serifProbability="100" t="561" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="6" wordStart="false">I</charParams>, <charParams b="600" charConfidence="97" l="1342" meanStrokeWidth="70" r="1377" serifProbability="255" t="562" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="6" wordStart="false">O</charParams>, <charParams b="602" charConfidence="53" l="1394" meanStrokeWidth="70" r="1430" serifProbability="89" t="563" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="6" wordStart="false">D</charParams>, <charParams b="602" charConfidence="44" l="1443" meanStrokeWidth="70" r="1459" serifProbability="100" t="564" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="6" wordStart="false">I</charParams>, <charParams b="612" charConfidence="13" l="1475" meanStrokeWidth="70" r="1518" serifProbability="78" t="560" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="6" wordStart="false">Q</charParams>, <charParams b="603" charConfidence="100" l="1531" meanStrokeWidth="70" r="1565" serifProbability="100" t="563" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="6" wordStart="false">U</charParams>, <charParams b="602" charConfidence="52" l="1581" meanStrokeWidth="70" r="1612" serifProbability="100" t="562" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="6" wordStart="false">E</charParams>, <charParams b="601" charConfidence="100" l="1615" meanStrokeWidth="70" r="1625" serifProbability="255" t="590" wordFromDictionary="true" wordIdentifier="false" wordNormal="true" wordNumeric="false" wordPenalty="6" wordStart="false">.</charParams>]
true False None False
false False None False
false False None False
false False None False
false False None False
false False None False
false False None False
None False None False
None False None False
None False None False
None False None False
true False None False
false False None False
false False None False
false False None False
false False None False
false False None False
false False None False
None False None False
None False None False
None False None False
None False None False
true False None False
false False None False
false False None False
false False None False
false False None False
false False None False
false False None False
false False None False
false False None False
false False None False
false False None False

[{'c': [306, 89, 1485, 710],
  'p': [{'c': [306, 89, 1485, 710],
    'l': [{'c': [925, 92, 261, 55],
      't': [{'c': [925, 99, 39, 45], 'tx': ')('},
       {'c': [1024, 110, 52, 33], 'tx': '91'},
       {'c': [1147, 92, 39, 50], 'tx': 'X'}]},
     {'c': [320, 336, 1459, 106],
      't': [{'c': [320, 354, 93, 88], 'tx': 'A'},
       {'c': [519, 348, 94, 93], 'tx': 'N'},
       {'c': [722, 347, 92, 90], 'tx': 'N'},
       {'c': [922, 344, 87, 90], 'tx': 'O'},
       {'c': [1116, 338, 92, 91], 'tx': 'N'},
       {'c': [1317, 340, 83, 89], 'tx': 'G'},
       {'c': [1506, 336, 75, 92], 'tx': 'E'},
       {'c': [1684, 338, 95, 97], 'tx': 'S,'}]},
     {'c': [608, 474, 878, 61],
      't': [{'c': [608, 485, 110, 48], 'tx': 'ET'},
       {'c': [805, 483, 220, 47], 'tx': 'AVIS'},
       {'c': [1109, 477, 377, 51], 'tx': 'DIVERS.'}]},
     {'c': [494, 549, 1131, 64],
      't': [{'c': [494, 575, 273, 36], 'tx': 'XXIVme.'},
       {'c': [828, 571, 286, 35], 'tx': 'FEUILLE'},
       {'c': [1178, 566, 447, 35], 'tx': 'PÉRIODIQUE.'}]},
     {'c': [647, 635, 814, 58],
      't': [{'c': [647, 643, 814, 40], 'tx': 'LAUSANNE'}]},
     {'c': [547, 708, 1009, 85],
      't': [{'c': [547, 720, 105, 56], 'tx': 'Du'},
       {'c': [700, 719, 203, 55], 'tx': 'Mardi'},
       {'c': [949, 731, 55, 42], 'tx': '7.'},
       {'c': [1045, 718, 298, 52], 'tx': 'Décembre'},
       {'c': [1390, 727, 166, 38], 'tx': 'ij6i.'}]}]}],
  'pOf': 'ACI-1832-01-01-a-i0001'},
 {'c': [195, 904, 1601, 1426],
  'p': [{'c': [195, 904, 1601, 1426],
    'l': [{'c': [831, 910, 446, 39],
      't': [{'c': [831, 913, 446, 34], 'tx': 'VENTES.'}]},
     {'c': [377, 971, 1409, 51],
      't': [{'c': [377, 985, 31, 29], 'tx': '1.'},
       {'c': [434, 978, 59, 36], 'tx': 'On'},
       {'c': [519, 989, 85, 23], 'tx': 'offre'},
       {'c': [625, 978, 18, 35], 'tx': 'à'},
       {'c': [671, 989, 127, 23], 'tx': 'vendre'},
       {'c': [823, 988, 46, 23], 'tx': 'un'},
       {'c': [895, 986, 77, 27], 'tx': 'tour'},
       {'c': [997, 978, 43, 35], 'tx': 'de'},
       {'c': [1065, 978, 55, 33], 'tx': 'Lit'},
       {'c': [1140, 987, 86, 23], 'tx': 'verd'},
       {'c': [1249, 974, 19, 35], 'tx': 'à'},
       {'c': [1303, 986, 46, 22], 'tx': 'un'},
       {'c': [1371, 986, 74, 24], 'tx': 'prix'},
       {'c': [1464, 987, 213, 22], 'tx': 'raifonnable.'},
       {'c': [1726, 975, 60, 35], 'tx': 'On'}]},
     {'c': [326, 1025, 835, 49],
      't': [{'c': [326, 1031, 93, 28], 'tx': "s'adr."},
       {'c': [441, 1039, 43, 22], 'tx': 'au'},
       {'c': [507, 1025, 133, 38], 'tx': 'Bureau'},
       {'c': [667, 1039, 58, 22], 'tx': 'qui'},
       {'c': [745, 1027, 174, 33], 'tx': 'indiquera'},
       {'c': [944, 1026, 30, 34], 'tx': 'la'},
       {'c': [992, 1039, 169, 19], 'tx': 'perfonne.'}]},
     {'c': [373, 1069, 1414, 51],
      't': [{'c': [373, 1084, 35, 24], 'tx': '2.'},
       {'c': [431, 1074, 102, 34], 'tx': 'Deux'},
       {'c': [561, 1086, 88, 23], 'tx': 'paire'},
       {'c': [678, 1076, 42, 32], 'tx': 'de'},
       {'c': [750, 1074, 128, 34], 'tx': 'Guêtes'},
       {'c': [900, 1074, 42, 34], 'tx': 'de'},
       {'c': [964, 1074, 141, 33], 'tx': 'Dragon'},
       {'c': [1118, 1095, 11, 18], 'tx': ','},
       {'c': [1157, 1073, 39, 36], 'tx': '&'},
       {'c': [1226, 1083, 65, 23], 'tx': 'une'},
       {'c': [1315, 1081, 89, 24], 'tx': 'paire'},
       {'c': [1429, 1071, 42, 34], 'tx': 'de'},
       {'c': [1497, 1069, 116, 36], 'tx': 'Bottes'},
       {'c': [1635, 1082, 81, 24], 'tx': 'avec'},
       {'c': [1739, 1071, 48, 35], 'tx': 'les'}]},
     {'c': [327, 1117, 1393, 51],
      't': [{'c': [327, 1121, 149, 36], 'tx': 'Eperons'},
       {'c': [497, 1124, 19, 32], 'tx': 'à'},
       {'c': [544, 1133, 45, 22], 'tx': 'un'},
       {'c': [612, 1134, 71, 23], 'tx': 'prix'},
       {'c': [709, 1134, 213, 20], 'tx': 'raifonnable.'},
       {'c': [972, 1122, 59, 34], 'tx': 'On'},
       {'c': [1055, 1134, 122, 21], 'tx': 'pourra'},
       {'c': [1201, 1120, 48, 35], 'tx': 'les'},
       {'c': [1265, 1132, 73, 21], 'tx': 'voir'},
       {'c': [1359, 1131, 42, 23], 'tx': 'au'},
       {'c': [1424, 1130, 131, 23], 'tx': 'préfent'},
       {'c': [1576, 1117, 144, 37], 'tx': 'Bureau.'}]},
     {'c': [376, 1165, 1412, 50],
      't': [{'c': [376, 1180, 33, 23], 'tx': '3.'},
       {'c': [434, 1169, 80, 35], 'tx': 'Une'},
       {'c': [538, 1171, 139, 31], 'tx': 'Montre'},
       {'c': [698, 1182, 42, 19], 'tx': 'en'},
       {'c': [762, 1179, 118, 25], 'tx': 'argent'},
       {'c': [903, 1170, 19, 33], 'tx': 'à'},
       {'c': [952, 1170, 31, 35], 'tx': 'la'},
       {'c': [1008, 1183, 99, 23], 'tx': 'mode'},
       {'c': [1129, 1169, 68, 37], 'tx': 'fans'},
       {'c': [1226, 1169, 115, 31], 'tx': 'défaut'},
       {'c': [1365, 1179, 66, 21], 'tx': 'que'},
       {'c': [1453, 1165, 69, 34], 'tx': "l'on"},
       {'c': [1543, 1177, 79, 22], 'tx': 'peut'},
       {'c': [1650, 1180, 138, 14], 'tx': 'mainte¬'}]},
     {'c': [326, 1203, 1461, 60],
      't': [{'c': [326, 1228, 51, 21], 'tx': 'nir'},
       {'c': [391, 1237, 12, 17], 'tx': ','},
       {'c': [432, 1216, 19, 33], 'tx': 'à'},
       {'c': [476, 1227, 45, 23], 'tx': 'un'},
       {'c': [542, 1227, 73, 22], 'tx': 'prix'},
       {'c': [638, 1226, 214, 19], 'tx': 'raifonnable.'},
       {'c': [901, 1210, 58, 34], 'tx': 'On'},
       {'c': [985, 1223, 95, 23], 'tx': "s'adr."},
       {'c': [1108, 1220, 43, 26], 'tx': 'au'},
       {'c': [1179, 1215, 135, 33], 'tx': 'Uureau'},
       {'c': [1345, 1224, 59, 22], 'tx': 'qui'},
       {'c': [1430, 1212, 176, 36], 'tx': 'indiquera'},
       {'c': [1635, 1214, 48, 35], 'tx': 'les'},
       {'c': [1712, 1226, 75, 15], 'tx': 'per-'}]},
     {'c': [328, 1263, 125, 35],
      't': [{'c': [328, 1263, 125, 33], 'tx': 'fonnes.'}]},
     {'c': [376, 1303, 1411, 55],
      't': [{'c': [376, 1328, 35, 16], 'tx': '<j.'},
       {'c': [438, 1309, 59, 34], 'tx': 'Un'},
       {'c': [518, 1310, 91, 32], 'tx': 'habit'},
       {'c': [633, 1308, 43, 34], 'tx': 'de'},
       {'c': [702, 1308, 82, 46], 'tx': 'drap'},
       {'c': [809, 1319, 73, 22], 'tx': 'noir'},
       {'c': [904, 1318, 84, 22], 'tx': 'pour'},
       {'c': [1014, 1317, 45, 22], 'tx': 'un'},
       {'c': [1084, 1305, 137, 35], 'tx': 'homme'},
       {'c': [1240, 1304, 44, 34], 'tx': 'de'},
       {'c': [1307, 1315, 170, 23], 'tx': 'médiocre'},
       {'c': [1504, 1316, 188, 33], 'tx': 'grandeur,'},
       {'c': [1720, 1321, 67, 23], 'tx': 'que'}]},
     {'c': [329, 1352, 1336, 50],
      't': [{'c': [329, 1357, 69, 34], 'tx': 'l*on'},
       {'c': [418, 1370, 78, 22], 'tx': 'aura'},
       {'c': [520, 1370, 17, 23], 'tx': 'a'},
       {'c': [566, 1366, 64, 26], 'tx': 'très'},
       {'c': [649, 1355, 67, 35], 'tx': 'bon'},
       {'c': [740, 1368, 144, 20], 'tx': 'compte.'},
       {'c': [934, 1353, 56, 36], 'tx': 'On'},
       {'c': [1012, 1366, 120, 22], 'tx': 'pourra'},
       {'c': [1154, 1353, 32, 36], 'tx': 'le'},
       {'c': [1209, 1366, 74, 20], 'tx': 'voir'},
       {'c': [1303, 1364, 42, 23], 'tx': 'au'},
       {'c': [1368, 1364, 129, 24], 'tx': 'préfent'},
       {'c': [1523, 1354, 142, 36], 'tx': 'Bureau.'}]},
     {'c': [379, 1400, 1408, 52],
      't': [{'c': [379, 1413, 32, 24], 'tx': '5.'},
       {'c': [438, 1405, 59, 32], 'tx': 'On'},
       {'c': [521, 1419, 82, 20], 'tx': 'offre'},
       {'c': [627, 1407, 18, 31], 'tx': 'à'},
       {'c': [669, 1418, 126, 21], 'tx': 'vendre'},
       {'c': [823, 1416, 65, 23], 'tx': 'une'},
       {'c': [909, 1415, 86, 21], 'tx': 'paire'},
       {'c': [1021, 1402, 42, 33], 'tx': 'de'},
       {'c': [1092, 1400, 128, 37], 'tx': 'Guêtes'},
       {'c': [1249, 1402, 43, 33], 'tx': 'de'},
       {'c': [1319, 1413, 69, 22], 'tx': 'cuir'},
       {'c': [1413, 1402, 18, 35], 'tx': 'à'},
       {'c': [1452, 1414, 47, 24], 'tx': 'un'},
       {'c': [1524, 1415, 72, 23], 'tx': 'prix'},
       {'c': [1624, 1416, 163, 18], 'tx': 'raifonna¬'}]},
     {'c': [331, 1449, 839, 48],
      't': [{'c': [331, 1452, 67, 34], 'tx': 'ble.'},
       {'c': [448, 1450, 58, 34], 'tx': 'On'},
       {'c': [522, 1462, 120, 21], 'tx': 'pourra'},
       {'c': [663, 1451, 47, 34], 'tx': 'les'},
       {'c': [730, 1464, 74, 20], 'tx': 'voir'},
       {'c': [821, 1463, 42, 22], 'tx': 'au'},
       {'c': [886, 1451, 129, 34], 'tx': 'Bureau'},
       {'c': [1041, 1450, 129, 37], 'tx': "d'Avis."}]},
     {'c': [381, 1497, 1407, 53],
      't': [{'c': [381, 1500, 33, 33], 'tx': '6.'},
       {'c': [435, 1500, 80, 35], 'tx': 'Une'},
       {'c': [538, 1498, 111, 36], 'tx': 'Table'},
       {'c': [669, 1498, 43, 35], 'tx': 'de'},
       {'c': [730, 1497, 121, 34], 'tx': 'Noyer'},
       {'c': [873, 1497, 18, 34], 'tx': 'à'},
       {'c': [910, 1498, 66, 34], 'tx': 'bon'},
       {'c': [1004, 1511, 143, 25], 'tx': 'compte.'},
       {'c': [1199, 1498, 57, 34], 'tx': 'On'},
       {'c': [1279, 1511, 96, 24], 'tx': "s'adr."},
       {'c': [1402, 1513, 44, 24], 'tx': 'au'},
       {'c': [1472, 1500, 133, 39], 'tx': 'Bureau'},
       {'c': [1627, 1515, 60, 24], 'tx': 'qui'},
       {'c': [1702, 1502, 86, 28], 'tx': 'indi¬'}]},
     {'c': [333, 1547, 342, 49],
      't': [{'c': [333, 1560, 101, 20], 'tx': 'quera'},
       {'c': [455, 1547, 31, 33], 'tx': 'la'},
       {'c': [506, 1558, 169, 25], 'tx': 'perfonne.'}]},
     {'c': [380, 1593, 1406, 54],
      't': [{'c': [380, 1603, 37, 26], 'tx': '7.'},
       {'c': [437, 1593, 102, 35], 'tx': 'Deux'},
       {'c': [557, 1595, 160, 35], 'tx': 'Râteliers'},
       {'c': [743, 1597, 38, 34], 'tx': '&'},
       {'c': [798, 1608, 47, 22], 'tx': 'un'},
       {'c': [869, 1608, 102, 23], 'tx': 'grand'},
       {'c': [997, 1597, 72, 34], 'tx': 'bois'},
       {'c': [1090, 1597, 43, 33], 'tx': 'de'},
       {'c': [1153, 1596, 56, 34], 'tx': 'Lit'},
       {'c': [1229, 1595, 42, 37], 'tx': 'de'},
       {'c': [1291, 1597, 119, 36], 'tx': 'Noyer'},
       {'c': [1431, 1599, 19, 33], 'tx': 'à'},
       {'c': [1469, 1607, 64, 27], 'tx': 'très'},
       {'c': [1553, 1599, 68, 36], 'tx': 'bon'},
       {'c': [1641, 1613, 145, 21], 'tx': 'compte.'}]},
     {'c': [333, 1641, 948, 51],
      't': [{'c': [333, 1643, 59, 34], 'tx': 'On'},
       {'c': [415, 1656, 96, 21], 'tx': "s'adr."},
       {'c': [536, 1654, 42, 23], 'tx': 'au'},
       {'c': [607, 1641, 132, 35], 'tx': 'Bureau'},
       {'c': [762, 1653, 59, 24], 'tx': 'qui'},
       {'c': [838, 1644, 170, 35], 'tx': 'indiquera'},
       {'c': [1029, 1644, 47, 34], 'tx': 'les'},
       {'c': [1097, 1655, 184, 27], 'tx': 'perfonnes.'}]},
     {'c': [381, 1690, 1405, 49],
      't': [{'c': [381, 1692, 34, 34], 'tx': '8.'},
       {'c': [441, 1692, 60, 33], 'tx': 'Un'},
       {'c': [521, 1700, 64, 25], 'tx': 'très'},
       {'c': [610, 1690, 86, 35], 'tx': 'beau'},
       {'c': [726, 1691, 39, 35], 'tx': '&'},
       {'c': [786, 1690, 66, 35], 'tx': 'bon'},
       {'c': [875, 1693, 125, 34], 'tx': 'Violon'},
       {'c': [1024, 1704, 58, 21], 'tx': 'qui'},
       {'c': [1107, 1702, 50, 24], 'tx': "n'a"},
       {'c': [1179, 1704, 94, 25], 'tx': 'point'},
       {'c': [1294, 1695, 42, 34], 'tx': 'de'},
       {'c': [1359, 1695, 113, 35], 'tx': 'défaut'},
       {'c': [1485, 1718, 11, 20], 'tx': ','},
       {'c': [1523, 1708, 44, 24], 'tx': 'on'},
       {'c': [1589, 1709, 42, 23], 'tx': 'en'},
       {'c': [1652, 1696, 68, 37], 'tx': 'fera'},
       {'c': [1740, 1709, 46, 23], 'tx': 'un'}]},
     {'c': [334, 1736, 1306, 55],
      't': [{'c': [334, 1751, 72, 22], 'tx': 'prix'},
       {'c': [423, 1751, 211, 22], 'tx': 'raifonnable.'},
       {'c': [684, 1737, 58, 34], 'tx': 'On'},
       {'c': [763, 1750, 96, 23], 'tx': "s'adr."},
       {'c': [883, 1753, 42, 25], 'tx': 'au'},
       {'c': [952, 1739, 131, 35], 'tx': 'Bureau'},
       {'c': [1110, 1752, 59, 24], 'tx': 'qui'},
       {'c': [1194, 1742, 173, 34], 'tx': 'indiquera'},
       {'c': [1391, 1742, 47, 37], 'tx': 'les'},
       {'c': [1458, 1756, 182, 24], 'tx': 'perfonnes.'}]},
     {'c': [392, 1785, 1395, 55],
      't': [{'c': [392, 1796, 32, 25], 'tx': 'o.'},
       {'c': [453, 1786, 78, 35], 'tx': 'Une'},
       {'c': [554, 1786, 97, 35], 'tx': 'Bible'},
       {'c': [675, 1798, 40, 22], 'tx': 'en'},
       {'c': [737, 1785, 158, 38], 'tx': 'François'},
       {'c': [920, 1801, 65, 22], 'tx': 'que'},
       {'c': [1006, 1787, 68, 34], 'tx': "l'on"},
       {'c': [1092, 1787, 147, 38], 'tx': 'donnera'},
       {'c': [1260, 1791, 19, 33], 'tx': 'à'},
       {'c': [1306, 1801, 45, 24], 'tx': 'un'},
       {'c': [1371, 1803, 73, 24], 'tx': 'prix'},
       {'c': [1472, 1805, 209, 21], 'tx': 'raifonnable.'},
       {'c': [1729, 1792, 58, 36], 'tx': 'On'}]},
     {'c': [336, 1832, 827, 51],
      't': [{'c': [336, 1845, 95, 22], 'tx': "s'adr."},
       {'c': [444, 1846, 41, 23], 'tx': 'au'},
       {'c': [504, 1834, 130, 35], 'tx': 'Bureau'},
       {'c': [652, 1847, 59, 22], 'tx': 'qui'},
       {'c': [729, 1835, 172, 36], 'tx': 'indiquera'},
       {'c': [916, 1838, 45, 34], 'tx': 'les'},
       {'c': [981, 1849, 182, 24], 'tx': 'perfonnes.'}]},
     {'c': [386, 1882, 1399, 56],
      't': [{'c': [386, 1892, 53, 22], 'tx': '10.'},
       {'c': [467, 1882, 62, 34], 'tx': 'Un'},
       {'c': [552, 1883, 92, 36], 'tx': 'habit'},
       {'c': [668, 1895, 73, 22], 'tx': 'noir'},
       {'c': [770, 1883, 79, 35], 'tx': "d'un"},
       {'c': [877, 1884, 67, 36], 'tx': 'fort'},
       {'c': [968, 1886, 85, 32], 'tx': 'beau'},
       {'c': [1084, 1884, 81, 49], 'tx': 'drap'},
       {'c': [1198, 1884, 71, 45], 'tx': 'fin,'},
       {'c': [1302, 1887, 127, 37], 'tx': 'doublé'},
       {'c': [1454, 1889, 44, 33], 'tx': 'de'},
       {'c': [1524, 1886, 89, 36], 'tx': 'Satin'},
       {'c': [1628, 1899, 41, 23], 'tx': 'en'},
       {'c': [1693, 1888, 92, 46], 'tx': 'foye,'}]},
     {'c': [336, 1929, 1401, 49],
      't': [{'c': [336, 1939, 66, 23], 'tx': 'que'},
       {'c': [425, 1929, 66, 34], 'tx': "l'on"},
       {'c': [511, 1941, 120, 25], 'tx': 'pourra'},
       {'c': [654, 1944, 91, 22], 'tx': 'avoir'},
       {'c': [768, 1931, 19, 36], 'tx': 'à'},
       {'c': [814, 1940, 64, 28], 'tx': 'très'},
       {'c': [906, 1934, 66, 34], 'tx': 'bon'},
       {'c': [996, 1944, 144, 23], 'tx': 'compte.'},
       {'c': [1191, 1933, 59, 36], 'tx': 'On'},
       {'c': [1273, 1949, 94, 24], 'tx': "s'adr."},
       {'c': [1391, 1950, 43, 23], 'tx': 'au'},
       {'c': [1454, 1936, 133, 35], 'tx': 'Bureau'},
       {'c': [1606, 1936, 131, 37], 'tx': "d'Avis."}]},
     {'c': [386, 1978, 1402, 57],
      't': [{'c': [386, 1985, 53, 25], 'tx': '11.'},
       {'c': [467, 1978, 60, 34], 'tx': 'Un'},
       {'c': [557, 1978, 68, 43], 'tx': 'joli,'},
       {'c': [648, 1991, 83, 22], 'tx': 'petit'},
       {'c': [756, 1979, 157, 37], 'tx': 'Pfeaume'},
       {'c': [940, 1983, 43, 33], 'tx': 'de'},
       {'c': [1008, 1993, 85, 24], 'tx': 'peau'},
       {'c': [1121, 1981, 43, 36], 'tx': 'de'},
       {'c': [1192, 1982, 176, 50], 'tx': 'Chagrin,'},
       {'c': [1413, 1986, 19, 34], 'tx': 'à'},
       {'c': [1462, 1997, 135, 23], 'tx': 'crochet'},
       {'c': [1625, 1985, 163, 39], 'tx': "d'argent."}]},
     {'c': [336, 2022, 732, 54],
      't': [{'c': [336, 2022, 59, 37], 'tx': 'On'},
       {'c': [426, 2036, 122, 24], 'tx': 'pourra'},
       {'c': [575, 2028, 31, 33], 'tx': 'le'},
       {'c': [628, 2040, 74, 22], 'tx': 'voir'},
       {'c': [721, 2041, 41, 22], 'tx': 'au'},
       {'c': [782, 2040, 128, 24], 'tx': 'préfent'},
       {'c': [926, 2029, 142, 34], 'tx': 'Bureau.'}]},
     {'c': [386, 2072, 1404, 62],
      't': [{'c': [386, 2081, 55, 26], 'tx': 'W.'},
       {'c': [469, 2072, 58, 35], 'tx': 'On'},
       {'c': [541, 2085, 82, 23], 'tx': 'offre'},
       {'c': [634, 2076, 19, 33], 'tx': 'à'},
       {'c': [667, 2087, 125, 24], 'tx': 'vendre'},
       {'c': [807, 2076, 89, 36], 'tx': 'deux'},
       {'c': [918, 2089, 121, 23], 'tx': 'grands'},
       {'c': [1060, 2090, 151, 27], 'tx': 'chevaux'},
       {'c': [1230, 2093, 88, 25], 'tx': 'noirs'},
       {'c': [1332, 2093, 85, 24], 'tx': 'pour'},
       {'c': [1440, 2080, 32, 37], 'tx': 'la'},
       {'c': [1488, 2094, 132, 25], 'tx': 'voiture'},
       {'c': [1638, 2097, 60, 23], 'tx': 'qui'},
       {'c': [1716, 2084, 74, 35], 'tx': 'font'}]},
     {'c': [336, 2119, 1454, 59],
      't': [{'c': [336, 2119, 74, 35], 'tx': 'déjà'},
       {'c': [429, 2119, 78, 36], 'tx': 'âgés'},
       {'c': [519, 2143, 11, 20], 'tx': ','},
       {'c': [556, 2122, 43, 33], 'tx': 'de'},
       {'c': [620, 2134, 73, 24], 'tx': 'plus'},
       {'c': [711, 2125, 142, 35], 'tx': 'diverfes'},
       {'c': [877, 2139, 144, 22], 'tx': 'voitures'},
       {'c': [1045, 2126, 43, 36], 'tx': 'de'},
       {'c': [1104, 2128, 173, 38], 'tx': 'différente'},
       {'c': [1299, 2141, 167, 24], 'tx': 'grandeur'},
       {'c': [1496, 2143, 66, 23], 'tx': 'que'},
       {'c': [1581, 2132, 65, 35], 'tx': "l'on"},
       {'c': [1671, 2147, 78, 23], 'tx': 'aura'},
       {'c': [1769, 2132, 21, 36], 'tx': 'à'}]},
     {'c': [334, 2166, 1359, 66],
      't': [{'c': [334, 2175, 65, 29], 'tx': 'très'},
       {'c': [412, 2170, 67, 35], 'tx': 'bon'},
       {'c': [503, 2182, 146, 26], 'tx': 'compte.'},
       {'c': [697, 2171, 59, 38], 'tx': 'On'},
       {'c': [767, 2185, 94, 28], 'tx': "s'adr,"},
       {'c': [874, 2173, 19, 37], 'tx': 'à'},
       {'c': [913, 2175, 70, 37], 'tx': 'Mr.'},
       {'c': [1000, 2174, 33, 37], 'tx': 'le'},
       {'c': [1048, 2174, 174, 42], 'tx': 'Capitaine'},
       {'c': [1242, 2179, 56, 37], 'tx': 'De'},
       {'c': [1308, 2181, 139, 35], 'tx': 'Middes'},
       {'c': [1466, 2191, 42, 27], 'tx': 'au'},
       {'c': [1522, 2179, 171, 41], 'tx': 'Dorigr.y.'}]},
     {'c': [1040, 2275, 749, 42],
      't': [{'c': [1040, 2275, 35, 37], 'tx': 'A'},
       {'c': [1098, 2287, 20, 25], 'tx': 'a'},
       {'c': [1549, 2277, 240, 34], 'tx': 'ANNON-'}]}]}],
  'pOf': 'ACI-1832-01-01-a-i0001'}]

In [7]:
int('True')

ValueError: invalid literal for int() with base 10: 'True'