# BL importer finalization & debug

## Imports

In [1]:
import os
import json

from impresso_essentials.utils import ALL_MEDIA, PARTNER_TO_MEDIA
import copy
from tqdm import tqdm
import pandas as pd
from random import shuffle
from text_preparation.importers.bl.detect import BlIssueDir, dir2issue, detect_issues, select_issues
from text_preparation.importers.bl.omni.classes import BlOmniNewspaperPage, BlOmniNewspaperIssue
from PIL import Image
from text_preparation.utils import draw_box_on_img, coords_to_xywh, coords_to_xy, rescale_coords
from text_preparation.importers import (
    CONTENTITEM_TYPES,
    CONTENTITEM_TYPE_IMAGE,
    CONTENTITEM_TYPE_ADVERTISEMENT,
)

## OmniPage Format

First, adapt BL_ocr_formats.json file to only keep the Aliases and issues corresponding to OmniPage-NLP format.
That will allow to only detect titles for this format and will already help a lot.
The document could have all the issues or be much much smaller with only Alias > NLP > list of dates for the given format. Or directly have the list of paths to mets files of the correct format.

Then the BL_extended_title_list.csv should also be processed to go from alias > NLP > date range > working title and variant titles so that each issue can have its variant title attached to it.

In [2]:
bl_source_data_dir = "/mnt/project_impresso/original/BL"
bl_w_source_data_dir = "/mnt/impresso_ocr_BL"
bl_sample_dir = "/home/piconti/impresso-text-acquisition/text_preparation/data/sample_data/BL"
bl_formats_filename = "BL_ocr_formats.json"
bl_titles_filename = "BL_extended_title_list.csv"
alias_to_NLP_filename = "BL_alias_to_NLP.json"
bl_titles_out_filename = "BL_all_titles.json"
bl_media_list_ext_path = os.path.join(bl_sample_dir, bl_titles_filename)
alias_to_NLP = os.path.join(bl_sample_dir, alias_to_NLP_filename)
bl_format_specific_issues = "BL_{format}_issues.json"
RENAMING_INFO_FILE = "renaming_info.json"
BL_IMG_TYPE = "illustration"
BL_AD_TYPE = "advert"
BL_CAPTION_TYPE = "caption"

ocr_formats = ["OmniPage-NLP", "BL-ALIAS", "Nuance-NLP", "ABBYY-ALIAS", "ABBYY-NLP"]

In [3]:
with open(os.path.join(bl_source_data_dir, bl_formats_filename), "r", encoding='utf-8') as fin:
    bl_ocr_formats = json.load(fin)

print(f"There are {len(bl_ocr_formats)} aliases in {bl_formats_filename}")

There are 368 aliases in BL_ocr_formats.json

### 1. Create format-specific json files

In [11]:
for format in ocr_formats:
    filepath = os.path.join(bl_source_data_dir, bl_format_specific_issues.format(format=format))
    print(filepath)

/mnt/project_impresso/original/BL/BL_OmniPage-NLP_issues.json
/mnt/project_impresso/original/BL/BL_BL-ALIAS_issues.json
/mnt/project_impresso/original/BL/BL_Nuance-NLP_issues.json
/mnt/project_impresso/original/BL/BL_ABBYY-ALIAS_issues.json
/mnt/project_impresso/original/BL/BL_ABBYY-NLP_issues.json

In [ ]:
mets_paths_per_format = {f: {} for f in ocr_formats}

for alias_idx, (alias, yearly_formats) in enumerate(bl_ocr_formats.items(), start=1):
    num_years = len(yearly_formats)
    print(f"Starting to process alias {alias} ({alias_idx}/368) - {num_years} years:")

    for year, issue_formats in tqdm(yearly_formats.items()):

        for issue_dir_path, formats in issue_formats.items():

            # keep track of which format is the first match for the priority list
            first_match = True
            for format in ocr_formats:

                if format in formats:
                    if alias not in mets_paths_per_format[format]:
                        # initialize the format dict for this alias is not already done
                        mets_paths_per_format[format][alias] = {
                            "priority_issues": {},
                            "other_issues_also_in_format": {},
                            "non_public_domain_post_1905": {}
                        }
                        
                    """# for each issue, the first format which matches is the 
                    # one which will be processed in priority, but we still want to keep track of other formats
                    issue_info = {
                        issue_dir_path: {
                            "current_format": formats[format],
                            "all_formats": formats.keys()
                        }
                    }"""
                    # select the mets filename or the first file (for BL alias case)
                    mets_or_example_file = formats[format][0]

                    # directly exclude any title after 1905
                    if int(year) > 1905:
                        mets_paths_per_format[format][alias]["non_public_domain_post_1905"][issue_dir_path] = mets_or_example_file
                    elif first_match:  
                        # set pairs of (issue_path, mets or example file)
                        mets_paths_per_format[format][alias]["priority_issues"][issue_dir_path] = mets_or_example_file
                        # all other formats for this issue are less of a priority
                        first_match = False
                    else:
                        mets_paths_per_format[format][alias]["other_issues_also_in_format"][issue_dir_path] = mets_or_example_file

    print(f"Saving to files the issues: latest alias {alias} ({alias_idx}/368).")

    for format in ocr_formats:
        filepath = os.path.join(bl_w_source_data_dir, bl_format_specific_issues.format(format=format))

        with open(filepath, "w", encoding="utf-8") as fout:
            json.dump(mets_paths_per_format[format], fout, indent=2)

### 2. Creating a file with all the variant titles

In [20]:
bl_media_lst_ext_raw_df = pd.read_csv(bl_media_list_ext_path, header=0, index_col=0)
print(bl_media_lst_ext_raw_df.info())
bl_media_lst_ext_raw_df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 647 entries, 1 to 628
Data columns (total 12 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Normalized Working Title           647 non-null    object
 1   Working title (BL)                 647 non-null    object
 2   Variant Title                      647 non-null    object
 3   NLP                                647 non-null    int64
 4   Alias (in file-syst or generated)  647 non-null    object
 5   Country                            549 non-null    object
 6   Start Year                         544 non-null    float64
 7   End Year                           544 non-null    float64
 8   Copy already shared with Impresso  647 non-null    object
 9   Start year in Impresso local copy  647 non-null    int64
 10  End year in Impresso local copy    647 non-null    int64
 11  Notes about local copy             87 non-null     object
dtypes: float64(2), int64(3), object(7)
memory usage: 65.7+ KB
None

,Normalized Working Title,Working title (BL),Variant Title,NLP,Alias (in file-syst or generated),Country,Start Year,End Year,Copy already shared with Impresso,Start year in Impresso local copy,End year in Impresso local copy,Notes about local copy
1,Aberdeen Press and Journal,Aberdeen Press and Journal,Aberdeen Journal and General Advertiser,31,ANJO,Scotland,1798.0,1876.0,"Yes, fully",1789,1876,NaN
2,Aberdeen Press and Journal,Aberdeen Press and Journal,Aberdeen Weekly Journal and General Advertiser,32,ANJO,Scotland,1876.0,1900.0,"Yes, fully",1877,1900,There were some small problems in the filenami...
444,Alston Herald and East Cumberland Advertiser,Alston Herald and East Cumberland Advertiser,"Alston Herald, and East Cumberland Advertiser.",3043,AHEC,England,1875.0,1879.0,"Yes, fully",1875,1879,Not separated in the data
492,Alston Herald and East Cumberland Advertiser,Alston Herald and East Cumberland Advertiser,"Alston Herald, and East Cumberland Advertiser",3043,AHEC,England,1880.0,1880.0,"Yes, fully",1880,1880,Not separated in the data
369,Baldwin's London Weekly Journal,Baldwin's London Weekly Journal,"Baldwin's London Weekly Journal, etc",2243,BLWJ,England,1803.0,1836.0,"Yes, fully",1803,1836,NaN

In [ ]:
cols_to_keep = ['Alias (in file-syst or generated)','Normalized Working Title', 'Working title (BL)', 'Variant Title', 'NLP', 'Time Period']

bl_media_lst_ext_raw_df['Time Period'] = bl_media_lst_ext_raw_df[['Start year in Impresso local copy', 'End year in Impresso local copy']].apply(lambda x: f"{x[0]}-{x[1]}", axis=1)
reduced_title_df = bl_media_lst_ext_raw_df[cols_to_keep]
reduced_title_df['NLP'] = reduced_title_df['NLP'].apply(lambda x: str(x).zfill(7))
reduced_title_df['Alias-NLP'] = reduced_title_df[['Alias (in file-syst or generated)', 'NLP']].apply(lambda x: f"{x[0]}-{x[1]}", axis=1)

for col in ['Normalized Working Title', 'Working title (BL)', "Variant Title"]:
    reduced_title_df[col] = reduced_title_df[col].apply(
        lambda x: x.rstrip('. ') if isinstance(x, str) else [y.rstrip('. ') for y in x]
    )

reduced_title_df

In [57]:
bl_titles = reduced_title_df.groupby(['Alias-NLP', 'Time Period']).agg({
        'Normalized Working Title': lambda x: x.unique()[0] if len(x.unique())==1 else x.unique(),
        'Working title (BL)': lambda x: x.unique()[0] if len(x.unique())==1 else x.unique(),
        "Variant Title": lambda x: x.unique()[0] if len(x.unique())==1 else x.unique(),
    },
).reset_index()

bl_titles

,Alias-NLP,Time Period,Normalized Working Title,Working title (BL),Variant Title
0,AATA-0003031,1846-1846,The Agricultural Advertiser and Tenant-Farmers...,Agricultural Advertiser and Tenant-Farmers' Ad...,The Agricultural Advertiser and Tenant-Farmers...
1,AGE52-0003023,1852-1853,The Age 1852,Age 1852,The Age
2,AGMO-0002364,1811-1811,The Anti-Gallican Monitor,Anti-Gallican Monitor,The Anti-Gallican Monitor
3,AGMO-0002365,1811-1814,The Anti-Gallican Monitor,Anti-Gallican Monitor,"The Anti-Gallican Monitor, and Anti-Corsican C..."
4,AGMO-0002366,1815-1817,The Anti-Gallican Monitor,Anti-Gallican Monitor,The Anti-Gallican Monitor
...,...,...,...,...,...
638,YOHD-0000497,1812-1813,The York Herald,York Herald,"The York Herald, County and General Advertiser"
639,YOHD-0000498,1814-1854,The York Herald,York Herald,The York Herald and General Advertiser
640,YOHD-0000499,1855-1889,The York Herald,York Herald,The York Herald
641,YOHD-0000500,1890-1900,The York Herald,York Herald,The Yorkshire Herald and the York Herald
642,YOHP-0004139,1879-1881,York House Papers,York House Papers,York House Papers: A weekly journal for the fa...

In [ ]:
titles_as_dict = bl_titles.to_dict(orient='records')
titles_as_dict

In [63]:
bl_titles_json = {}
for record in titles_as_dict:
    if (
        not isinstance(record['Normalized Working Title'], str) or 
        not isinstance(record['Working title (BL)'], str) or 
        not isinstance(record['Variant Title'], str)
    ):
        print(f"More than one value! {record}")
        if record['Alias-NLP']=='BRLU-0002378' and record['Time Period']=='1820-1821':
            record['Variant Title']=record['Variant Title'][0]
        if (
            (record['Alias-NLP']=='DCWR-0003408' and record['Time Period']=='1869-1895') or 
            (record['Alias-NLP']=='MEXA-0003398' and record['Time Period']=='1846-1848')
        ):
            record['Normalized Working Title']=record['Normalized Working Title'][1]
            record['Variant Title']=record['Variant Title'][1]
            record['Working title (BL)']=record['Working title (BL)'][1]
    bl_titles_json.update({
       record['Alias-NLP'] : {record['Time Period']: record}
    })

with open(os.path.join(bl_w_source_data_dir, bl_titles_out_filename), "w", encoding='utf-8') as fout:
    json.dump(bl_titles_json, fout, indent=2)

More than one value! {'Alias-NLP': 'BRLU-0002378', 'Time Period': '1820-1821', 'Normalized Working Title': 'The British Luminary', 'Working title (BL)': 'British Luminary', 'Variant Title': array(['The Weekly Intelligencer, and British Luminary',
       'The Weekly Intelligencer, and British Luminary. (30 July 1820-27 May 1821)'],
      dtype=object)}
More than one value! {'Alias-NLP': 'DCWR-0003408', 'Time Period': '1869-1895', 'Normalized Working Title': array(['Dewsbury Chronicle and West Riding Advertiser',
       'The Dewsbury Chronicle and West Riding Advertiser'], dtype=object), 'Working title (BL)': array(['Dewsbury Chronicle and West Riding Advertiser',
       'The Dewsbury Chronicle and West Riding Advertiser'], dtype=object), 'Variant Title': array(['Dewsbury Chronicle and West Riding Advertiser',
       'The Dewsbury Chronicle, and West Riding Advertiser'], dtype=object)}
More than one value! {'Alias-NLP': 'MEXA-0003398', 'Time Period': '1846-1848', 'Normalized Working Title': array(['Manchester Examiner', 'The Manchester Examiner'], dtype=object), 'Working title (BL)': array(['Manchester Examiner', 'The Manchester Examiner'], dtype=object), 'Variant Title': array(['Manchester Examiner', 'The Manchester Examiner'], dtype=object)}

### 3. Detect/Select functions

In [ ]:
omni_issues = mets_paths_per_format["OmniPage-NLP"]
omni_issues

In [80]:
all_issues = []
for alias, issues_of_alias in omni_issues.items():
    
    issue_paths = [dir2issue(path) for path in list(issues_of_alias['priority_issues'].keys())]
    print(f"{alias} - Found {len(issue_paths)} issues")
    all_issues.extend(issue_paths)

all_issues[10:-10]

AGMO - Found 691 issues
AATA - Found 31 issues
AGE52 - Found 37 issues
AHEC - Found 208 issues
ALBN - Found 26 issues
ALST - Found 1603 issues
ANWT - Found 669 issues
ARGB - Found 242 issues
AUBO - Found 41 issues
BBLT - Found 468 issues
BCE1 - Found 38 issues
BCL2 - Found 7 issues
BEHI - Found 725 issues
BELL - Found 118 issues
BFNP - Found 7 issues
BGFP - Found 515 issues
BGJO - Found 445 issues
BHFA - Found 2557 issues
BKNW - Found 3500 issues
BLHD - Found 3526 issues
BLOT - Found 97 issues
BLWJ - Found 939 issues
BPDH - Found 32 issues
BPHF - Found 10 issues
BQGA - Found 1083 issues
BRAD - Found 417 issues
BRBN - Found 730 issues
BREM - Found 61 issues
BREN - Found 313 issues
BRGA - Found 996 issues
BRIF - Found 226 issues
BRLB - Found 43 issues
BRLU - Found 282 issues
BRMG - Found 250 issues
BRMW - Found 687 issues
BRNP - Found 567 issues
BRPR - Found 313 issues
BRSS - Found 46 issues
BRST - Found 522 issues
BRTB - Found 29 issues
BTEP - Found 18 issues
BWNW - Found 382 issues
BWTE - Found 616 issues
CBEP - Found 55 issues
CCEX - Found 180 issues
CCGZ - Found 71 issues
CCWA - Found 68 issues
CFTM - Found 1823 issues
CGFG - Found 94 issues
CGGA - Found 637 issues
CHPL - Found 600 issues
CHSO - Found 1246 issues
CHTI - Found 374 issues
CICN - Found 293 issues
CKTC - Found 57 issues
CLDF - Found 150 issues
CLNW - Found 8 issues
CLTP - Found 56 issues
CMCH - Found 1269 issues
CMGA - Found 305 issues
CMSN - Found 80 issues
CNSN - Found 325 issues
COUR - Found 599 issues
CPAD - Found 289 issues
CRWN - Found 42 issues
CSMP - Found 401 issues
CSTT - Found 4 issues
CWPG - Found 19 issues
DCEA - Found 1477 issues
DCWR - Found 1340 issues
DDEN - Found 432 issues
DDIS - Found 26 issues
DHEX - Found 984 issues
DJWN - Found 254 issues
DPLT - Found 35 issues
DRHE - Found 709 issues
DSNR - Found 40 issues
EAST - Found 19 issues
EAWN - Found 44 issues
ECLA - Found 63 issues
ECWP - Found 4391 issues
ELAD - Found 169 issues
ENGL - Found 1197 issues
ERTG - Found 391 issues
EVST - Found 186 issues
EVT25 - Found 46 issues
EVTL - Found 25 issues
EXPR - Found 102 issues
FBFC - Found 299 issues
FFPR - Found 52 issues
FMNW - Found 11 issues
FODE - Found 211 issues
FONU - Found 15 issues
FWEX - Found 192 issues
GEVP - Found 2447 issues
GLCH - Found 841 issues
GLCO - Found 2484 issues
GLSE - Found 61 issues
GOTM - Found 4 issues
HAGZ - Found 1305 issues
HBOV - Found 102 issues
HLCM - Found 620 issues
HLLN - Found 14 issues
HMSA - Found 242 issues
HOUR - Found 1055 issues
HOWL - Found 421 issues
HTWD - Found 7 issues
HWCH - Found 23 issues
ICPG - Found 14 issues
ILNP - Found 42 issues
ILOL - Found 23 issues
ILT53 - Found 4 issues
ILWT - Found 6 issues
IMNW - Found 80 issues
IREX - Found 216 issues
ISNT - Found 279 issues
ISTM - Found 570 issues
ISWA - Found 180 issues
IWGZ - Found 345 issues
JSMN - Found 1168 issues
JWRC - Found 175 issues
KEAD - Found 2749 issues
KTGA - Found 138 issues
LCCR - Found 17 issues
LCHH - Found 103 issues
LCPP - Found 176 issues
LDGS - Found 75 issues
LEVP - Found 3 issues
LFPR - Found 24 issues
LHPN - Found 4 issues
LHTC - Found 103 issues
LIAL - Found 3236 issues
LITG - Found 81 issues
LIVC - Found 7 issues
LIWL - Found 14 issues
LJGA - Found 47 issues
LJPN - Found 65 issues
LLAD - Found 61 issues
LMNA - Found 367 issues
LNCH - Found 2621 issues
LNLF - Found 16 issues
LNM1 - Found 60 issues
LNM2 - Found 53 issues
LNM3 - Found 43 issues
LNPC - Found 142 issues
LNPT - Found 847 issues
LONM - Found 270 issues
LOPA - Found 255 issues
LOPH - Found 69 issues
LPNGA - Found 318 issues
LPNL - Found 3228 issues
LRNW - Found 8 issues
LSCA - Found 850 issues
LSCR - Found 10 issues
LSCT - Found 183 issues
LSGA - Found 1759 issues
LSIR - Found 443 issues
LTIM - Found 22 issues
LTLG - Found 48 issues
LWC - Found 1639 issues
LWI - Found 74 issues
MATN - Found 56 issues
MEWT - Found 193 issues
MEXA - Found 208 issues
MNTM - Found 127 issues
MOGA - Found 54 issues
MOMA - Found 136 issues
MRHD - Found 18888 issues
MRTT - Found 478 issues
MTPN - Found 30 issues
NATN - Found 66 issues
NCCO - Found 690 issues
NCEF - Found 14 issues
NCGA - Found 326 issues
NCRF - Found 350 issues
NDTM - Found 2294 issues
NGLB - Found 131 issues
NLON - Found 306 issues
NLRD - Found 577 issues
NOGU - Found 2834 issues
NSCS - Found 176 issues
NTNL - Found 11 issues
NTPR - Found 17 issues
NTRG - Found 54 issues
NTSD - Found 138 issues
NUNT - Found 50 issues
NWGZ - Found 3243 issues
NWLT - Found 226 issues
NWTM - Found 3834 issues
NWTS - Found 1 issues
OBTM - Found 162 issues
OKJL - Found 357 issues
OLEN - Found 483 issues
ORDA - Found 2490 issues
PADV - Found 249 issues
PATR - Found 3130 issues
PDHD - Found 330 issues
PELL - Found 192 issues
PHCW - Found 1 issues
PICT - Found 252 issues
PITM - Found 42 issues
PLDM - Found 116 issues
PLNT - Found 321 issues
PLOB - Found 5 issues
PLTO - Found 1599 issues
PNPC - Found 8 issues
POEX - Found 532 issues
POLL - Found 11 issues
PORC - Found 365 issues
POTG - Found 361 issues
PPLP - Found 332 issues
PRPL - Found 158 issues
PSEV - Found 13 issues
PSHE - Found 2200 issues
PUCA - Found 103 issues
PWRM - Found 11 issues
RADL - Found 22 issues
RBLD - Found 121 issues
REFM - Found 4 issues
REPR - Found 227 issues
RIOB - Found 1654 issues
RUEX - Found 2274 issues
RYRK - Found 19 issues
SATR - Found 978 issues
SCPR - Found 997 issues
SEGL - Found 34 issues
SESD - Found 86 issues
SGCV - Found 518 issues
SGHL - Found 2345 issues
SHCA - Found 64 issues
SHEP - Found 2060 issues
SHPA - Found 243 issues
SHRE - Found 179 issues
SHSD - Found 3079 issues
SJCH - Found 9411 issues
SJWL - Found 272 issues
SLAD - Found 156 issues
SLTL - Found 431 issues
SMHE - Found 13 issues
SMSD - Found 305 issues
SOFR - Found 171 issues
SPRT - Found 5 issues
SSCH - Found 20 issues
SSEX - Found 30 issues
STEX - Found 8 issues
STUE - Found 33 issues
SUGA - Found 99 issues
SUNW - Found 18 issues
SURY - Found 96 issues
SWME - Found 157 issues
SWRJ - Found 308 issues
TALN - Found 1030 issues
TCAA - Found 129 issues
TCDN - Found 63 issues
TDAY - Found 294 issues
TDIA - Found 231 issues
TFPR - Found 280 issues
THML - Found 61 issues
TIGA - Found 36 issues
TMEW - Found 118 issues
TNAJ - Found 13 issues
TNEW - Found 2000 issues
TONI - Found 359 issues
TPRD - Found 32 issues
TPRS - Found 327 issues
TRBT - Found 720 issues
TRSN - Found 1815 issues
TTK22 - Found 19 issues
TTLK - Found 2 issues
TUNI - Found 287 issues
UNIV - Found 133 issues
VERL - Found 12 issues
VIND - Found 12 issues
WAEX - Found 1761 issues
WAHD - Found 714 issues
WBGZ - Found 259 issues
WDEX - Found 2240 issues
WENW - Found 28 issues
WFSC - Found 67 issues
WGMC - Found 126 issues
WHEP - Found 154 issues
WJBS - Found 276 issues
WKAD - Found 58 issues
WKCH - Found 1424 issues
WKEC - Found 15 issues
WKGB - Found 63 issues
WKIN - Found 41 issues
WKIT - Found 39 issues
WKJL - Found 408 issues
WKML - Found 109 issues
WKNW - Found 391 issues
WKRV - Found 1025 issues
WKTN - Found 360 issues
WKTS - Found 493 issues
WLSA - Found 104 issues
WLTM - Found 368 issues
WMTG - Found 2031 issues
WMTM - Found 155 issues
WRLD - Found 27 issues
WSBN - Found 65 issues
WTCH - Found 64 issues
YOHP - Found 105 issues

[IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 8, 3), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/08/03', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 8, 10), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/08/10', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 8, 31), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/08/31', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 11, 2), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/11/02', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 11, 23), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/11/23', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 11, 30), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/11/30', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 11, 9), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/11/09', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 11, 16), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/11/16', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 4, 20), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/04/20', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 4, 27), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/04/27', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 4, 13), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/04/13', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 4, 6), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/04/06', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 1, 19), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/01/19', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 1, 5), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/01/05', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 1, 12), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/01/12', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 1, 26), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/01/26', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 9, 21), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/09/21', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 9, 14), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/09/14', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 9, 28), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/09/28', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 9, 7), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/09/07', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 12, 21), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/12/21', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 12, 14), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/12/14', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 12, 28), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/12/28', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 12, 7), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/12/07', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 6, 8), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/06/08', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 6, 15), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/06/15', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 6, 1), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/06/01', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 6, 22), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/06/22', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 6, 29), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/06/29', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 3, 2), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/03/02', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 3, 23), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/03/23', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 3, 30), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/03/30', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 3, 9), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/03/09', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 10, 19), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/10/19', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 10, 5), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/10/05', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 10, 12), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/10/12', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 10, 26), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/10/26', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 7, 20), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/07/20', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 7, 27), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/07/27', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 7, 13), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/07/13', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1817, 7, 6), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002366/1817/07/06', nlp='0002366'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 2, 8), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/02/08', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 2, 15), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/02/15', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 2, 1), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/02/01', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 2, 22), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/02/22', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 2, 29), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/02/29', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 5, 2), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/05/02', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 5, 23), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/05/23', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 5, 30), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/05/30', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 5, 9), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/05/09', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 5, 16), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/05/16', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 8, 8), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/08/08', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 8, 15), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/08/15', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 8, 1), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/08/01', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 8, 22), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/08/22', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 8, 29), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/08/29', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 11, 21), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/11/21', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 11, 14), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/11/14', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 11, 28), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/11/28', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 11, 7), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/11/07', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 4, 25), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/04/25', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 4, 18), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/04/18', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 4, 11), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/04/11', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 4, 4), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/04/04', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 1, 25), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/01/25', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 1, 18), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/01/18', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 1, 11), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/01/11', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 1, 4), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/01/04', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 9, 19), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/09/19', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 9, 5), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/09/05', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 9, 12), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/09/12', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 9, 26), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/09/26', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 12, 19), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/12/19', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 12, 5), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/12/05', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 12, 12), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/12/12', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 12, 26), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/12/26', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 6, 20), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/06/20', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 6, 27), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/06/27', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 6, 13), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/06/13', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 6, 6), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/06/06', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 3, 21), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/03/21', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 3, 14), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/03/14', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 3, 28), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/03/28', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 3, 7), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/03/07', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 10, 17), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/10/17', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 10, 24), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/10/24', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 10, 3), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/10/03', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 10, 10), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/10/10', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 10, 31), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/10/31', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 7, 25), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/07/25', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 7, 18), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/07/18', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 7, 11), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/07/11', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1824, 7, 4), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002367/1824/07/04', nlp='0002367'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1814, 2, 20), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002365/1814/02/20', nlp='0002365'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1814, 2, 27), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002365/1814/02/27', nlp='0002365'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1814, 2, 13), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002365/1814/02/13', nlp='0002365'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1814, 2, 6), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002365/1814/02/06', nlp='0002365'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1814, 5, 8), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002365/1814/05/08', nlp='0002365'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1814, 5, 15), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002365/1814/05/15', nlp='0002365'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1814, 5, 1), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002365/1814/05/01', nlp='0002365'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1814, 5, 22), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002365/1814/05/22', nlp='0002365'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1814, 5, 29), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002365/1814/05/29', nlp='0002365'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1814, 8, 21), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002365/1814/08/21', nlp='0002365'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1814, 8, 14), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002365/1814/08/14', nlp='0002365'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1814, 8, 28), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002365/1814/08/28', nlp='0002365'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1814, 8, 7), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002365/1814/08/07', nlp='0002365'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1814, 11, 20), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002365/1814/11/20', nlp='0002365'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1814, 11, 27), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002365/1814/11/27', nlp='0002365'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1814, 11, 13), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002365/1814/11/13', nlp='0002365'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1814, 11, 6), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002365/1814/11/06', nlp='0002365'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1814, 4, 17), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002365/1814/04/17', nlp='0002365'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1814, 4, 24), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002365/1814/04/24', nlp='0002365'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1814, 4, 3), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002365/1814/04/03', nlp='0002365'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1814, 4, 10), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002365/1814/04/10', nlp='0002365'),
 IssueDirectory(provider='BL', alias='AGMO', date=datetime.date(1814, 1, 2), edition='a', path='/mnt/project_impresso/original/BL/AGMO/0002365/1814/01/02', nlp='0002365'),

In [4]:
config_test_1 = {
    "titles": {
        "ILOL": [],
        "AGMO": [],
        "AATA": [],
        "AGE52": [],
        "AHEC": [],
        "ANJO": [],
        "BHCH": [],
    },
    "exclude_titles": [],
    "year_only": False
}

detected = detect_issues(bl_source_data_dir)

print(f"Detected {len(detected)} issues in total")

for title in config_test_1['titles']:
    print(f"Detected {len([i for i in detected if i.alias == title])} issues for {title}")

Detected 161486 issues in total
Detected 23 issues for ILOL
Detected 691 issues for AGMO
Detected 31 issues for AATA
Detected 37 issues for AGE52
Detected 208 issues for AHEC
Detected 0 issues for ANJO
Detected 0 issues for BHCH

In [5]:
selected = select_issues(bl_source_data_dir, config = config_test_1)

print(f"Selected  {len(selected)} issues in total")

for title in config_test_1['titles']:
    print(f"Detected {len([i for i in selected if i.alias == title])} issues for {title}")

Selected  990 issues in total
Detected 23 issues for ILOL
Detected 691 issues for AGMO
Detected 31 issues for AATA
Detected 37 issues for AGE52
Detected 208 issues for AHEC
Detected 0 issues for ANJO
Detected 0 issues for BHCH

In [16]:
config_test_2 = {
    "titles": {
        "AGMO": "1817/08/03-1817/12/21",
        "AATA": "1848/01/01-1849/01/01",
        "AGE52": [],
        "AHEC": ["1880/02/21", "1877/02/10"],
        "ANJO": [],
        "BHCH": [],
    },
    "exclude_titles": [],
    "year_only": False
}

selected = select_issues(bl_source_data_dir, config = config_test_2)

print(f"Selected  {len(selected )} issues in total")

for title in config_test_2['titles']:
    print(f"Detected {len([i for i in selected if i.alias == title])} issues for {title}")

Selected  60 issues in total
Detected 21 issues for AGMO
Detected 0 issues for AATA
Detected 37 issues for AGE52
Detected 2 issues for AHEC
Detected 0 issues for ANJO
Detected 0 issues for BHCH

### 4. BlOmniNewspaperIssue Class

In [3]:
titles_for_alias_nlp = {
    "1801-1811": {
      "Alias-NLP": "YOHD-0000186",
      "Time Period": "1801-1811",
      "Normalized Working Title": "The York Herald",
      "Working title (BL)": "York Herald",
      "Variant Title": "The York Herald"
    }
  }

period = [int(y) for p in titles_for_alias_nlp for y in p.split("-")]
period

[1801, 1811]

In [36]:
1857 in range(period[0], period[1]+1)
1801 in range(period[0], period[1]+1)

True

#### Debug issue

In [3]:
config_test_1 = {
    "titles": {
        "ILOL": [],
        "AGMO": [],
        "AATA": [],
        "AGE52": [],
        "AHEC": [],
        "ANJO": [],
        "BHCH": [],
    },
    "exclude_titles": [],
    "year_only": False
}

detected = detect_issues(bl_source_data_dir)

print(f"Detected {len(detected)} issues in total")

selected = select_issues(bl_source_data_dir, config = config_test_1)

print(f"Selected  {len(selected)} issues in total")

for title in config_test_1['titles']:
    print(f"Detected {len([i for i in selected if i.alias == title])} issues for {title}")

Detected 161486 issues in total
Selected  990 issues in total
Detected 23 issues for ILOL
Detected 691 issues for AGMO
Detected 31 issues for AATA
Detected 37 issues for AGE52
Detected 208 issues for AHEC
Detected 0 issues for ANJO
Detected 0 issues for BHCH

In [4]:
test_issue = selected[0]
test_issue

IssueDirectory(provider='BL', alias='ILOL', date=datetime.date(1843, 5, 21), edition='a', path='/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21', nlp='0003005')

In [5]:
os.listdir(test_issue.path)

['renaming_info.json',
 '0003005_18430521_0007.xml',
 '0003005_18430521_0009.xml',
 '0003005_18430521_0011.xml',
 '0003005_18430521_0008.xml',
 '0003005_18430521_0006.xml',
 '0003005_18430521_0012.xml',
 '0003005_18430521_0004.xml',
 '0003005_18430521_mets.xml',
 '0003005_18430521_0003.xml',
 '0003005_18430521_0002.xml',
 '0003005_18430521_0005.xml',
 '0003005_18430521_0010.xml',
 '0003005_18430521_0001.xml']

In [6]:
with open(os.path.join(test_issue.path, RENAMING_INFO_FILE), 'r') as fin:
    test_issue_renaming_info = json.load(fin)

test_issue_renaming_info

{'12': {'original_filename': '0003005_18430521_0012.jp2',
  'new_filename': 'ILOL-1843-05-21-a-p0012.jp2',
  'issue_id': 'ILOL-1843-05-21-a',
  'original_nlp': '0003005',
  'img_dir_path': '/mnt/impresso_images_BL/ILOL/1843/05/21/a',
  'ocr_dir_path': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21',
  'width': 4409,
  'height': 6504},
 '1': {'original_filename': '0003005_18430521_0001.jp2',
  'new_filename': 'ILOL-1843-05-21-a-p0001.jp2',
  'issue_id': 'ILOL-1843-05-21-a',
  'original_nlp': '0003005',
  'img_dir_path': '/mnt/impresso_images_BL/ILOL/1843/05/21/a',
  'ocr_dir_path': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21',
  'width': 4409,
  'height': 6504},
 '5': {'original_filename': '0003005_18430521_0005.jp2',
  'new_filename': 'ILOL-1843-05-21-a-p0005.jp2',
  'issue_id': 'ILOL-1843-05-21-a',
  'original_nlp': '0003005',
  'img_dir_path': '/mnt/impresso_images_BL/ILOL/1843/05/21/a',
  'ocr_dir_path': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21',
  'width': 4409,
  'height': 6504},
 '3': {'original_filename': '0003005_18430521_0003.jp2',
  'new_filename': 'ILOL-1843-05-21-a-p0003.jp2',
  'issue_id': 'ILOL-1843-05-21-a',
  'original_nlp': '0003005',
  'img_dir_path': '/mnt/impresso_images_BL/ILOL/1843/05/21/a',
  'ocr_dir_path': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21',
  'width': 4409,
  'height': 6504},
 '10': {'original_filename': '0003005_18430521_0010.jp2',
  'new_filename': 'ILOL-1843-05-21-a-p0010.jp2',
  'issue_id': 'ILOL-1843-05-21-a',
  'original_nlp': '0003005',
  'img_dir_path': '/mnt/impresso_images_BL/ILOL/1843/05/21/a',
  'ocr_dir_path': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21',
  'width': 4409,
  'height': 6504},
 '6': {'original_filename': '0003005_18430521_0006.jp2',
  'new_filename': 'ILOL-1843-05-21-a-p0006.jp2',
  'issue_id': 'ILOL-1843-05-21-a',
  'original_nlp': '0003005',
  'img_dir_path': '/mnt/impresso_images_BL/ILOL/1843/05/21/a',
  'ocr_dir_path': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21',
  'width': 4409,
  'height': 6504},
 '11': {'original_filename': '0003005_18430521_0011.jp2',
  'new_filename': 'ILOL-1843-05-21-a-p0011.jp2',
  'issue_id': 'ILOL-1843-05-21-a',
  'original_nlp': '0003005',
  'img_dir_path': '/mnt/impresso_images_BL/ILOL/1843/05/21/a',
  'ocr_dir_path': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21',
  'width': 4409,
  'height': 6504},
 '2': {'original_filename': '0003005_18430521_0002.jp2',
  'new_filename': 'ILOL-1843-05-21-a-p0002.jp2',
  'issue_id': 'ILOL-1843-05-21-a',
  'original_nlp': '0003005',
  'img_dir_path': '/mnt/impresso_images_BL/ILOL/1843/05/21/a',
  'ocr_dir_path': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21',
  'width': 4409,
  'height': 6504},
 '7': {'original_filename': '0003005_18430521_0007.jp2',
  'new_filename': 'ILOL-1843-05-21-a-p0007.jp2',
  'issue_id': 'ILOL-1843-05-21-a',
  'original_nlp': '0003005',
  'img_dir_path': '/mnt/impresso_images_BL/ILOL/1843/05/21/a',
  'ocr_dir_path': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21',
  'width': 4409,
  'height': 6504},
 '4': {'original_filename': '0003005_18430521_0004.jp2',
  'new_filename': 'ILOL-1843-05-21-a-p0004.jp2',
  'issue_id': 'ILOL-1843-05-21-a',
  'original_nlp': '0003005',
  'img_dir_path': '/mnt/impresso_images_BL/ILOL/1843/05/21/a',
  'ocr_dir_path': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21',
  'width': 4409,
  'height': 6504},
 '8': {'original_filename': '0003005_18430521_0008.jp2',
  'new_filename': 'ILOL-1843-05-21-a-p0008.jp2',
  'issue_id': 'ILOL-1843-05-21-a',
  'original_nlp': '0003005',
  'img_dir_path': '/mnt/impresso_images_BL/ILOL/1843/05/21/a',
  'ocr_dir_path': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21',
  'width': 4409,
  'height': 6504},
 '9': {'original_filename': '0003005_18430521_0009.jp2',
  'new_filename': 'ILOL-1843-05-21-a-p0009.jp2',
  'issue_id': 'ILOL-1843-05-21-a',
  'original_nlp': '0003005',
  'img_dir_path': '/mnt/impresso_images_BL/ILOL/1843/05/21/a',
  'ocr_dir_path': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21',
  'width': 4409,
  'height': 6504},
 'ocr_formats': {'OmniPage-NLP': ['0003005_18430521_0007.xml',
   '0003005_18430521_0009.xml',
   '0003005_18430521_0011.xml',
   '0003005_18430521_0008.xml',
   '0003005_18430521_0006.xml',
   '0003005_18430521_0012.xml',
   '0003005_18430521_0004.xml',
   '0003005_18430521_0003.xml',
   '0003005_18430521_0002.xml',
   '0003005_18430521_0005.xml',
   '0003005_18430521_0010.xml',
   '0003005_18430521_0001.xml',
   '0003005_18430521_mets.xml']}}

In [7]:
test_issue_renaming_info

{'12': {'original_filename': '0003005_18430521_0012.jp2',
  'new_filename': 'ILOL-1843-05-21-a-p0012.jp2',
  'issue_id': 'ILOL-1843-05-21-a',
  'original_nlp': '0003005',
  'img_dir_path': '/mnt/impresso_images_BL/ILOL/1843/05/21/a',
  'ocr_dir_path': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21',
  'width': 4409,
  'height': 6504},
 '1': {'original_filename': '0003005_18430521_0001.jp2',
  'new_filename': 'ILOL-1843-05-21-a-p0001.jp2',
  'issue_id': 'ILOL-1843-05-21-a',
  'original_nlp': '0003005',
  'img_dir_path': '/mnt/impresso_images_BL/ILOL/1843/05/21/a',
  'ocr_dir_path': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21',
  'width': 4409,
  'height': 6504},
 '5': {'original_filename': '0003005_18430521_0005.jp2',
  'new_filename': 'ILOL-1843-05-21-a-p0005.jp2',
  'issue_id': 'ILOL-1843-05-21-a',
  'original_nlp': '0003005',
  'img_dir_path': '/mnt/impresso_images_BL/ILOL/1843/05/21/a',
  'ocr_dir_path': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21',
  'width': 4409,
  'height': 6504},
 '3': {'original_filename': '0003005_18430521_0003.jp2',
  'new_filename': 'ILOL-1843-05-21-a-p0003.jp2',
  'issue_id': 'ILOL-1843-05-21-a',
  'original_nlp': '0003005',
  'img_dir_path': '/mnt/impresso_images_BL/ILOL/1843/05/21/a',
  'ocr_dir_path': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21',
  'width': 4409,
  'height': 6504},
 '10': {'original_filename': '0003005_18430521_0010.jp2',
  'new_filename': 'ILOL-1843-05-21-a-p0010.jp2',
  'issue_id': 'ILOL-1843-05-21-a',
  'original_nlp': '0003005',
  'img_dir_path': '/mnt/impresso_images_BL/ILOL/1843/05/21/a',
  'ocr_dir_path': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21',
  'width': 4409,
  'height': 6504},
 '6': {'original_filename': '0003005_18430521_0006.jp2',
  'new_filename': 'ILOL-1843-05-21-a-p0006.jp2',
  'issue_id': 'ILOL-1843-05-21-a',
  'original_nlp': '0003005',
  'img_dir_path': '/mnt/impresso_images_BL/ILOL/1843/05/21/a',
  'ocr_dir_path': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21',
  'width': 4409,
  'height': 6504},
 '11': {'original_filename': '0003005_18430521_0011.jp2',
  'new_filename': 'ILOL-1843-05-21-a-p0011.jp2',
  'issue_id': 'ILOL-1843-05-21-a',
  'original_nlp': '0003005',
  'img_dir_path': '/mnt/impresso_images_BL/ILOL/1843/05/21/a',
  'ocr_dir_path': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21',
  'width': 4409,
  'height': 6504},
 '2': {'original_filename': '0003005_18430521_0002.jp2',
  'new_filename': 'ILOL-1843-05-21-a-p0002.jp2',
  'issue_id': 'ILOL-1843-05-21-a',
  'original_nlp': '0003005',
  'img_dir_path': '/mnt/impresso_images_BL/ILOL/1843/05/21/a',
  'ocr_dir_path': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21',
  'width': 4409,
  'height': 6504},
 '7': {'original_filename': '0003005_18430521_0007.jp2',
  'new_filename': 'ILOL-1843-05-21-a-p0007.jp2',
  'issue_id': 'ILOL-1843-05-21-a',
  'original_nlp': '0003005',
  'img_dir_path': '/mnt/impresso_images_BL/ILOL/1843/05/21/a',
  'ocr_dir_path': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21',
  'width': 4409,
  'height': 6504},
 '4': {'original_filename': '0003005_18430521_0004.jp2',
  'new_filename': 'ILOL-1843-05-21-a-p0004.jp2',
  'issue_id': 'ILOL-1843-05-21-a',
  'original_nlp': '0003005',
  'img_dir_path': '/mnt/impresso_images_BL/ILOL/1843/05/21/a',
  'ocr_dir_path': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21',
  'width': 4409,
  'height': 6504},
 '8': {'original_filename': '0003005_18430521_0008.jp2',
  'new_filename': 'ILOL-1843-05-21-a-p0008.jp2',
  'issue_id': 'ILOL-1843-05-21-a',
  'original_nlp': '0003005',
  'img_dir_path': '/mnt/impresso_images_BL/ILOL/1843/05/21/a',
  'ocr_dir_path': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21',
  'width': 4409,
  'height': 6504},
 '9': {'original_filename': '0003005_18430521_0009.jp2',
  'new_filename': 'ILOL-1843-05-21-a-p0009.jp2',
  'issue_id': 'ILOL-1843-05-21-a',
  'original_nlp': '0003005',
  'img_dir_path': '/mnt/impresso_images_BL/ILOL/1843/05/21/a',
  'ocr_dir_path': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21',
  'width': 4409,
  'height': 6504},
 'ocr_formats': {'OmniPage-NLP': ['0003005_18430521_0007.xml',
   '0003005_18430521_0009.xml',
   '0003005_18430521_0011.xml',
   '0003005_18430521_0008.xml',
   '0003005_18430521_0006.xml',
   '0003005_18430521_0012.xml',
   '0003005_18430521_0004.xml',
   '0003005_18430521_0003.xml',
   '0003005_18430521_0002.xml',
   '0003005_18430521_0005.xml',
   '0003005_18430521_0010.xml',
   '0003005_18430521_0001.xml',
   '0003005_18430521_mets.xml']}}

In [8]:
bl_issue = BlOmniNewspaperIssue(test_issue)
bl_issue

In [9]:
bl_issue.issue_data

{'id': 'ILOL-1843-05-21-a',
 'cdt': '2025-08-25 18:22:31',
 'ts': '2025-08-25T16:22:31Z',
 'st': 'newspaper',
 'sm': 'print',
 'olr': True,
 'i': [{'m': {'id': 'ILOL-1843-05-21-a-i0001',
    'tp': 'article',
    'pp': [1],
    'var_t': 'Illustrated London Life',
    'lg': 'en',
    'ro': 1},
   'l': {'bl_nlp': '0003005',
    'src_files': {'mets_xml': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21/0003005_18430521_mets.xml',
     'alto_xml': ['/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21/0003005_18430521_0001.xml'],
     'page_image': ['0003005_18430521_0001.jp2']},
    'id': 'art0001',
    'parts': [{'comp_role': 'pagearea',
      'comp_id': 'pa0001001',
      'comp_label': 'textblock',
      'comp_fileid': 'img0001-alto',
      'comp_page_no': 1},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0001002',
      'comp_label': 'textblock',
      'comp_fileid': 'img0001-alto',
      'comp_page_no': 1},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0001003',
      'comp_label': 'textblock',
      'comp_fileid': 'img0001-alto',
      'comp_page_no': 1},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0001004',
      'comp_label': 'textblock',
      'comp_fileid': 'img0001-alto',
      'comp_page_no': 1},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0001005',
      'comp_label': 'illustration',
      'comp_fileid': 'img0001-alto',
      'comp_page_no': 1,
      'coords': [298, 4676, 2241, 1159]},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0001006',
      'comp_label': 'caption',
      'comp_fileid': 'img0001-alto',
      'comp_page_no': 1,
      'coords': [820, 5899, 1244, 40]},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0001007',
      'comp_label': 'illustration',
      'comp_fileid': 'img0001-alto',
      'comp_page_no': 1,
      'coords': [1649, 4794, 498, 191]}]}},
  {'m': {'id': 'ILOL-1843-05-21-a-i0002',
    'tp': 'image',
    'pp': [1],
    'iiif_link': 'https://impresso-project.ch/api/proxy/iiif/ILOL-1843-05-21-a-p0001/info.json',
    'var_t': 'Illustrated London Life',
    'ro': 2},
   'l': {'bl_nlp': '0003005',
    'src_files': {'mets_xml': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21/0003005_18430521_mets.xml',
     'alto_xml': ['/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21/0003005_18430521_0001.xml'],
     'page_image': ['0003005_18430521_0001.jp2']},
    'id': 'pa0001005',
    'parts': [{'comp_role': 'pagearea',
      'comp_id': 'pa0001005',
      'comp_label': 'illustration',
      'comp_fileid': 'img0001-alto',
      'comp_page_no': 1,
      'coords': [298, 4676, 2241, 1159]},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0001006',
      'comp_label': 'caption',
      'comp_fileid': 'img0001-alto',
      'comp_page_no': 1,
      'coords': [820, 5899, 1244, 40]}]},
   'c': [298, 4676, 2241, 1159],
   'pOf': 'ILOL-1843-05-21-a-i0001'},
  {'m': {'id': 'ILOL-1843-05-21-a-i0003',
    'tp': 'image',
    'pp': [1],
    'iiif_link': 'https://impresso-project.ch/api/proxy/iiif/ILOL-1843-05-21-a-p0001/info.json',
    'var_t': 'Illustrated London Life',
    'ro': 3},
   'l': {'bl_nlp': '0003005',
    'src_files': {'mets_xml': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21/0003005_18430521_mets.xml',
     'alto_xml': ['/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21/0003005_18430521_0001.xml'],
     'page_image': ['0003005_18430521_0001.jp2']},
    'id': 'pa0001007',
    'parts': [{'comp_role': 'pagearea',
      'comp_id': 'pa0001007',
      'comp_label': 'illustration',
      'comp_fileid': 'img0001-alto',
      'comp_page_no': 1,
      'coords': [1649, 4794, 498, 191]}]},
   'c': [1649, 4794, 498, 191],
   'pOf': 'ILOL-1843-05-21-a-i0001'},
  {'m': {'id': 'ILOL-1843-05-21-a-i0004',
    'tp': 'article',
    'pp': [1],
    'var_t': 'Illustrated London Life',
    'lg': 'en',
    'ro': 4},
   'l': {'bl_nlp': '0003005',
    'src_files': {'mets_xml': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21/0003005_18430521_mets.xml',
     'alto_xml': ['/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21/0003005_18430521_0001.xml'],
     'page_image': ['0003005_18430521_0001.jp2']},
    'id': 'art0002',
    'parts': [{'comp_role': 'pagearea',
      'comp_id': 'pa0001008',
      'comp_label': 'headline',
      'comp_fileid': 'img0001-alto',
      'comp_page_no': 1},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0001009',
      'comp_label': 'textblock',
      'comp_fileid': 'img0001-alto',
      'comp_page_no': 1},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0001010',
      'comp_label': 'textblock',
      'comp_fileid': 'img0001-alto',
      'comp_page_no': 1},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0001011',
      'comp_label': 'textblock',
      'comp_fileid': 'img0001-alto',
      'comp_page_no': 1},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0001012',
      'comp_label': 'textblock',
      'comp_fileid': 'img0001-alto',
      'comp_page_no': 1}]}},
  {'m': {'id': 'ILOL-1843-05-21-a-i0005',
    'tp': 'article',
    'pp': [1],
    'var_t': 'Illustrated London Life',
    'lg': 'en',
    'ro': 5},
   'l': {'bl_nlp': '0003005',
    'src_files': {'mets_xml': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21/0003005_18430521_mets.xml',
     'alto_xml': ['/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21/0003005_18430521_0001.xml'],
     'page_image': ['0003005_18430521_0001.jp2']},
    'id': 'art0003',
    'parts': [{'comp_role': 'pagearea',
      'comp_id': 'pa0001013',
      'comp_label': 'textblock',
      'comp_fileid': 'img0001-alto',
      'comp_page_no': 1}]}},
  {'m': {'id': 'ILOL-1843-05-21-a-i0006',
    'tp': 'article',
    'pp': [2],
    'var_t': 'Illustrated London Life',
    'lg': 'en',
    'ro': 6},
   'l': {'bl_nlp': '0003005',
    'src_files': {'mets_xml': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21/0003005_18430521_mets.xml',
     'alto_xml': ['/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21/0003005_18430521_0002.xml'],
     'page_image': ['0003005_18430521_0002.jp2']},
    'id': 'art0004',
    'parts': [{'comp_role': 'pagearea',
      'comp_id': 'pa0002001',
      'comp_label': 'headline',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0002002',
      'comp_label': 'textblock',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2}]}},
  {'m': {'id': 'ILOL-1843-05-21-a-i0007',
    'tp': 'article',
    'pp': [2],
    'var_t': 'Illustrated London Life',
    'lg': 'en',
    'ro': 7},
   'l': {'bl_nlp': '0003005',
    'src_files': {'mets_xml': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21/0003005_18430521_mets.xml',
     'alto_xml': ['/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21/0003005_18430521_0002.xml'],
     'page_image': ['0003005_18430521_0002.jp2']},
    'id': 'art0005',
    'parts': [{'comp_role': 'pagearea',
      'comp_id': 'pa0002003',
      'comp_label': 'headline',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0002004',
      'comp_label': 'textblock',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0002005',
      'comp_label': 'textblock',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0002006',
      'comp_label': 'textblock',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0002007',
      'comp_label': 'textblock',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0002008',
      'comp_label': 'textblock',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2}]}},
  {'m': {'id': 'ILOL-1843-05-21-a-i0008',
    'tp': 'article',
    'pp': [2],
    'var_t': 'Illustrated London Life',
    'lg': 'en',
    'ro': 8},
   'l': {'bl_nlp': '0003005',
    'src_files': {'mets_xml': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21/0003005_18430521_mets.xml',
     'alto_xml': ['/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21/0003005_18430521_0002.xml'],
     'page_image': ['0003005_18430521_0002.jp2']},
    'id': 'art0006',
    'parts': [{'comp_role': 'pagearea',
      'comp_id': 'pa0002009',
      'comp_label': 'headline',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0002010',
      'comp_label': 'headline',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0002011',
      'comp_label': 'textblock',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0002012',
      'comp_label': 'textblock',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0002013',
      'comp_label': 'textblock',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2}]}},
  {'m': {'id': 'ILOL-1843-05-21-a-i0009',
    'tp': 'article',
    'pp': [2],
    'var_t': 'Illustrated London Life',
    'lg': 'en',
    'ro': 9},
   'l': {'bl_nlp': '0003005',
    'src_files': {'mets_xml': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21/0003005_18430521_mets.xml',
     'alto_xml': ['/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21/0003005_18430521_0002.xml'],
     'page_image': ['0003005_18430521_0002.jp2']},
    'id': 'art0007',
    'parts': [{'comp_role': 'pagearea',
      'comp_id': 'pa0002014',
      'comp_label': 'headline',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0002015',
      'comp_label': 'headline',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0002016',
      'comp_label': 'textblock',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0002017',
      'comp_label': 'textblock',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0002018',
      'comp_label': 'textblock',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0002019',
      'comp_label': 'textblock',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0002020',
      'comp_label': 'textblock',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2}]}},
  {'m': {'id': 'ILOL-1843-05-21-a-i0010',
    'tp': 'article',
    'pp': [2],
    'var_t': 'Illustrated London Life',
    'lg': 'en',
    'ro': 10},
   'l': {'bl_nlp': '0003005',
    'src_files': {'mets_xml': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21/0003005_18430521_mets.xml',
     'alto_xml': ['/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21/0003005_18430521_0002.xml'],
     'page_image': ['0003005_18430521_0002.jp2']},
    'id': 'art0008',
    'parts': [{'comp_role': 'pagearea',
      'comp_id': 'pa0002021',
      'comp_label': 'headline',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0002022',
      'comp_label': 'textblock',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0002023',
      'comp_label': 'textblock',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0002024',
      'comp_label': 'textblock',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0002025',
      'comp_label': 'textblock',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0002026',
      'comp_label': 'textblock',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2}]}},
  {'m': {'id': 'ILOL-1843-05-21-a-i0011',
    'tp': 'article',
    'pp': [2, 3],
    'var_t': 'Illustrated London Life',
    'lg': 'en',
    'ro': 11},
   'l': {'bl_nlp': '0003005',
    'src_files': {'mets_xml': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21/0003005_18430521_mets.xml',
     'alto_xml': ['/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21/0003005_18430521_0002.xml',
      '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21/0003005_18430521_0003.xml'],
     'page_image': ['0003005_18430521_0002.jp2', '0003005_18430521_0003.jp2']},
    'id': 'art0009',
    'parts': [{'comp_role': 'pagearea',
      'comp_id': 'pa0002027',
      'comp_label': 'headline',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0002028',
      'comp_label': 'textblock',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0002029',
      'comp_label': 'textblock',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0002030',
      'comp_label': 'textblock',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0002031',
      'comp_label': 'textblock',
      'comp_fileid': 'img0002-alto',
      'comp_page_no': 2},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0003001',
      'comp_label': 'textblock',
      'comp_fileid': 'img0003-alto',
      'comp_page_no': 3},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0003002',
      'comp_label': 'textblock',
      'comp_fileid': 'img0003-alto',
      'comp_page_no': 3},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0003003',
      'comp_label': 'textblock',
      'comp_fileid': 'img0003-alto',
      'comp_page_no': 3},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0003004',
      'comp_label': 'textblock',
      'comp_fileid': 'img0003-alto',
      'comp_page_no': 3},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0003005',
      'comp_label': 'textblock',
      'comp_fileid': 'img0003-alto',
      'comp_page_no': 3},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0003006',
      'comp_label': 'textblock',
      'comp_fileid': 'img0003-alto',
      'comp_page_no': 3},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0003007',
      'comp_label': 'textblock',
      'comp_fileid': 'img0003-alto',
      'comp_page_no': 3},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0003008',
      'comp_label': 'textblock',
      'comp_fileid': 'img0003-alto',
      'comp_page_no': 3},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0003009',
      'comp_label': 'textblock',
      'comp_fileid': 'img0003-alto',
      'comp_page_no': 3},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0003010',
      'comp_label': 'illustration',
      'comp_fileid': 'img0003-alto',
      'comp_page_no': 3,
      'coords': [186, 457, 2499, 2970]}]}},
  {'m': {'id': 'ILOL-1843-05-21-a-i0012',
    'tp': 'image',
    'pp': [3],
    'iiif_link': 'https://impresso-project.ch/api/proxy/iiif/ILOL-1843-05-21-a-p0003/info.json',
    'var_t': 'Illustrated London Life',
    'ro': 12},
   'l': {'bl_nlp': '0003005',
    'src_files': {'mets_xml': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21/0003005_18430521_mets.xml',
     'alto_xml': ['/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21/0003005_18430521_0003.xml'],
     'page_image': ['0003005_18430521_0003.jp2']},
    'id': 'pa0003010',
    'parts': [{'comp_role': 'pagearea',
      'comp_id': 'pa0003010',
      'comp_label': 'illustration',
      'comp_fileid': 'img0003-alto',
      'comp_page_no': 3,
      'coords': [186, 457, 2499, 2970]}]},
   'c': [186, 457, 2499, 2970],
   'pOf': 'ILOL-1843-05-21-a-i0011'},
  {'m': {'id': 'ILOL-1843-05-21-a-i0013',
    'tp': 'article',
    'pp': [3],
    'var_t': 'Illustrated London Life',
    'lg': 'en',
    'ro': 13},
   'l': {'bl_nlp': '0003005',
    'src_files': {'mets_xml': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21/0003005_18430521_mets.xml',
     'alto_xml': ['/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21/0003005_18430521_0003.xml'],
     'page_image': ['0003005_18430521_0003.jp2']},
    'id': 'art0010',
    'parts': [{'comp_role': 'pagearea',
      'comp_id': 'pa0003011',
      'comp_label': 'headline',
      'comp_fileid': 'img0003-alto',
      'comp_page_no': 3},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0003012',
      'comp_label': 'textblock',
      'comp_fileid': 'img0003-alto',
      'comp_page_no': 3},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0003013',
      'comp_label': 'textblock',
      'comp_fileid': 'img0003-alto',
      'comp_page_no': 3},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0003014',
      'comp_label': 'textblock',
      'comp_fileid': 'img0003-alto',
      'comp_page_no': 3},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0003015',
      'comp_label': 'textblock',
      'comp_fileid': 'img0003-alto',
      'comp_page_no': 3},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0003016',
      'comp_label': 'textblock',
      'comp_fileid': 'img0003-alto',
      'comp_page_no': 3}]}},
  {'m': {'id': 'ILOL-1843-05-21-a-i0014',
    'tp': 'article',
    'pp': [4],
    'var_t': 'Illustrated London Life',
    'lg': 'en',
    'ro': 14},
   'l': {'bl_nlp': '0003005',
    'src_files': {'mets_xml': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21/0003005_18430521_mets.xml',
     'alto_xml': ['/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21/0003005_18430521_0004.xml'],
     'page_image': ['0003005_18430521_0004.jp2']},
    'id': 'art0011',
    'parts': [{'comp_role': 'pagearea',
      'comp_id': 'pa0004001',
      'comp_label': 'headline',
      'comp_fileid': 'img0004-alto',
      'comp_page_no': 4},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0004002',
      'comp_label': 'textblock',
      'comp_fileid': 'img0004-alto',
      'comp_page_no': 4},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0004003',
      'comp_label': 'textblock',
      'comp_fileid': 'img0004-alto',
      'comp_page_no': 4},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0004004',
      'comp_label': 'textblock',
      'comp_fileid': 'img0004-alto',
      'comp_page_no': 4},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0004005',
      'comp_label': 'textblock',
      'comp_fileid': 'img0004-alto',
      'comp_page_no': 4},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0004006',
      'comp_label': 'textblock',
      'comp_fileid': 'img0004-alto',
      'comp_page_no': 4},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0004007',
      'comp_label': 'textblock',
      'comp_fileid': 'img0004-alto',
      'comp_page_no': 4},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0004008',
      'comp_label': 'textblock',
      'comp_fileid': 'img0004-alto',
      'comp_page_no': 4},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0004009',
      'comp_label': 'textblock',
      'comp_fileid': 'img0004-alto',
      'comp_page_no': 4},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0004010',
      'comp_label': 'textblock',
      'comp_fileid': 'img0004-alto',
      'comp_page_no': 4},
     {'comp_role': 'pagearea',
      'comp_id': 'pa0004011',
      'comp_label': 'textblock',
      'comp_fileid': 'img0004-alto',
      'comp_page_no': 4}]}},
  {'m': {'id': 'ILOL-1843-05-21-a-i0015',
    'tp': 'article',
    'pp': [4],
    'var_t': 'Illustrated London Life',
    'lg': 'en',
    'ro': 15},
   'l': {'bl_nlp': '0003005',
    'src_files': {'mets_xml': '/mnt/project_impresso/original/BL/ILOL/0003005/1843/05/21/0003005_18430521_mets.xml',

In [11]:
%%timeit
[p.id for p in sorted(bl_issue.pages,key=lambda x:x.number)]

1.28 μs ± 24.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

#### Adapt `_parse_content_item_logic()` for handle images and store the original filename

In [ ]:
mets_doc = bl_issue.xml
content_items = []

# Get logical structure of issue
divs = (
    mets_doc.find("structMap", {"TYPE": "LOGICAL"})
    .find("div", {"TYPE": "ISSUE"})
    .findChildren("div")
)

# Sort to have same naming
#sorted_divs = sorted(divs, key=lambda x: int(''.join(filter(str.isdigit, x.get("DMDID")))))

#sorted_divs
divs

In [13]:
def all_equal(iterator):
    iterator = iter(iterator)
    try:
        first = next(iterator)
    except StopIteration:
        return True
    return all(first == x for x in iterator)

In [ ]:
found_types = set(x.get("TYPE") for x in divs)

phys_structmap = mets_doc.find("structMap", {"TYPE": "PHYSICAL"})
structlink = mets_doc.find("structLink")

print(found_types)
print(phys_structmap)
print(structlink)

#### `_parse_content_item`

In [15]:
def _get_part_dict(div, comp_role: str | None):
    """Construct the parts for a certain div entry of METS.

    Args:
        div (Tag): Content item div
        comp_role (str | None): Role of the component

    Returns:
        dict[str, Any]: Parts dict for given div.
    """
    comp_fileid = div.find("area", {"BETYPE": "IDREF"}).get("FILEID")
    comp_id = div.get("ID")
    comp_page_no = int(div.parent.get("ORDER"))
    # This is where illustrations will be identified
    comp_label = div.get("LABEL").lower()
    if comp_role is None:
        type_attr = div.get("TYPE")
        comp_role = type_attr.lower() if type_attr else None

    return {
        "comp_role": comp_role,
        "comp_id": comp_id,
        "comp_label": comp_label,
        "comp_fileid": comp_fileid,
        "comp_page_no": int(comp_page_no),
    }

In [38]:
def _get_image_and_captions(div, part_id, div_parts, curr_ci_parts, ci_image_parts, last_img_part_id):
    # for each illustration, store its coordinates and any potential caption
    if div.get("LABEL").lower() == BL_IMG_TYPE:
        img_xy_coords = div.find("area", {"SHAPE": "RECT"}).get("COORDS")
        # directly convert the coordinates to the wanted xywh format
        div_parts["coords"] = coords_to_xywh([int(c) for c in img_xy_coords.split(',')])
        if part_id not in ci_image_parts:
            ci_image_parts[part_id] = [div_parts]
        else:
            ci_image_parts[part_id].append(div_parts)
        # keep track of which illustration it is to make sure we can connect them back after
        last_img_part_id = part_id

    # if the next element is a caption, attach it directly
    if div.get("LABEL").lower() == BL_CAPTION_TYPE:
        if curr_ci_parts[-1]['comp_id'] == last_img_part_id:
            #ci_image_parts[last_img_part_id]["caption_parts"] = div_parts
            cap_xy_coords = div.find("area", {"SHAPE": "RECT"}).get("COORDS")
            # directly convert the coordinates to the wanted xywh format
            div_parts["coords"] = coords_to_xywh([int(c) for c in cap_xy_coords.split(',')])
            ci_image_parts[last_img_part_id].append(div_parts)
            #ci_image_parts[last_img_part_id]["caption_coords"] = coords_to_xywh([int(c) for c in cap_xy_coords.split(',')])
        else:
            print(f"curr_ci_parts[-1]: {curr_ci_parts[-1]}, last_img_part_id={last_img_part_id}")
            msg = f"{bl_issue.id}, {div_parts['comp_page_no']} - caption {div.get('ID')} does not follow an illustration!"
            print(msg)
            bl_issue._notes.append(msg)

    return ci_image_parts, last_img_part_id

In [27]:
counter = 1

item_div = divs[0]
#for div in divs:
#only for first for now
    # Parse Each contentitem
item_dmd_sec = mets_doc.find("dmdSec", {"ID": item_div.get("DMDID")})
    #content_items.append(test_issue._parse_content_item(div, counter, phys_structmap, structlink, dmd_sec))
 
div_type = item_div.get("TYPE").lower()

div_id = item_div.get("ID")

lang = item_dmd_sec.findChild("languageTerm").text

div_id, item_dmd_sec, div_type, lang

('art0001',
 <mets:dmdSec ID="modsarticle1">
 <mets:mdWrap MDTYPE="MODS">
 <mets:xmlData>
 <mods:mods>
 <mods:language>
 <mods:languageTerm authority="rfc3066" type="code">en</mods:languageTerm>
 </mods:language>
 </mods:mods>
 </mets:xmlData>
 </mets:mdWrap>
 </mets:dmdSec>,
 'article',
 'en')

In [ ]:
counter = 1
content_items = []
cis_img_parts = []

for idx, div in enumerate(divs):
    print(f"\n---- div #{idx} -----")
    print(f"counter = {counter}")
    dmd_sec = mets_doc.find("dmdSec", {"ID": div.get("DMDID")})
    div_type = div.get("TYPE").lower()

    item_dmd_sec = mets_doc.find("dmdSec", {"ID": div.get("DMDID")})
    lang = item_dmd_sec.findChild("languageTerm")

    if div_type == BL_IMG_TYPE:
        div_type = CONTENTITEM_TYPE_IMAGE
    elif div_type == BL_AD_TYPE:
        div_type = CONTENTITEM_TYPE_ADVERTISEMENT
    
    tag = tag = f"#{div.get('ID')}"
    print(tag)
    linkgrp = structlink.find("smLocatorLink", {"xlink:href": tag}).parent

    # Remove `#` from xlink:href
    div_parts_ids = [
        x.get("xlink:href")[1:]
        for x in linkgrp.findAll("smLocatorLink")
        if x.get("xlink:href") != tag
    ]

    ci_parts = []
    ci_image_parts = {}
    last_img_part_id = None
    last_img_part_idx = None
    for idx, p in enumerate(div_parts_ids):
        # Get element in physical map
        part_div = phys_structmap.find("div", {"ID": p})
        print(f"div {idx} from div parts: {div}")
        type_attr = part_div.get("TYPE")
        comp_role = type_attr.lower() if type_attr else None

        # In that case, need to add all parts
        if comp_role == "page":
            for sub_div in part_div.findAll("div"):
                subdiv_part_dict = _get_part_dict(sub_div, None)
                subdiv_part_id = sub_div.get("ID")
                assert subdiv_part_id == subdiv_part_dict['comp_id']#:
                #print(f"!!!!!!!subdiv_part_id={subdiv_part_id}, subdiv_part_dict['comp_id']:{subdiv_part_dict['comp_id']}")
                
                ci_image_parts, last_img_part_id = _get_image_and_captions(sub_div, subdiv_part_id, subdiv_part_dict, ci_parts, ci_image_parts, last_img_part_id)
                ci_parts.append(subdiv_part_dict)
                
        else:
            div_part_dict = _get_part_dict(part_div, comp_role)
            ci_image_parts, last_img_part_id = _get_image_and_captions(part_div, p, div_part_dict, ci_parts, ci_image_parts, last_img_part_id)
            ci_parts.append(div_part_dict)

    
    content_item = {
        "m": {
            "id": f"{bl_issue.id}-i{str(counter).zfill(4)}",
            "tp": div_type,
            "pp": [],
        },
        "l": {
            "bl_nlp": bl_issue.nlp,
            "id": div.get("ID"),
            "parts": ci_parts,
        },
    }

    if lang is not None:
        content_item['m']["lg"] = lang.text
    for p in content_item["l"]["parts"]:
        pge_no = p["comp_page_no"]
        if pge_no not in content_item["m"]["pp"]:
            content_item["m"]["pp"].append(pge_no)


    content_items.append(content_item)
    cis_img_parts.append(ci_image_parts)
    counter += 1

In [40]:
content_items[43]

{'m': {'id': 'ILOL-1843-05-21-a-i0044',
  'tp': 'article',
  'pp': [11],
  'lg': 'en'},
 'l': {'bl_nlp': '0003005',
  'id': 'art0044',
  'parts': [{'comp_role': 'pagearea',
    'comp_id': 'pa0011003',
    'comp_label': 'headline',
    'comp_fileid': 'img0011-alto',
    'comp_page_no': 11},
   {'comp_role': 'pagearea',
    'comp_id': 'pa0011004',
    'comp_label': 'textblock',
    'comp_fileid': 'img0011-alto',
    'comp_page_no': 11},
   {'comp_role': 'pagearea',
    'comp_id': 'pa0011005',
    'comp_label': 'textblock',
    'comp_fileid': 'img0011-alto',
    'comp_page_no': 11},
   {'comp_role': 'pagearea',
    'comp_id': 'pa0011006',
    'comp_label': 'textblock',
    'comp_fileid': 'img0011-alto',
    'comp_page_no': 11},
   {'comp_role': 'pagearea',
    'comp_id': 'pa0011007',
    'comp_label': 'textblock',
    'comp_fileid': 'img0011-alto',
    'comp_page_no': 11},
   {'comp_role': 'pagearea',
    'comp_id': 'pa0011008',
    'comp_label': 'textblock',
    'comp_fileid': 'img0011-alto',
    'comp_page_no': 11},
   {'comp_role': 'pagearea',
    'comp_id': 'pa0011009',
    'comp_label': 'textblock',
    'comp_fileid': 'img0011-alto',
    'comp_page_no': 11},
   {'comp_role': 'pagearea',
    'comp_id': 'pa0011010',
    'comp_label': 'textblock',
    'comp_fileid': 'img0011-alto',
    'comp_page_no': 11},
   {'comp_role': 'pagearea',
    'comp_id': 'pa0011011',
    'comp_label': 'textblock',
    'comp_fileid': 'img0011-alto',
    'comp_page_no': 11},
   {'comp_role': 'pagearea',
    'comp_id': 'pa0011012',
    'comp_label': 'textblock',
    'comp_fileid': 'img0011-alto',
    'comp_page_no': 11},
   {'comp_role': 'pagearea',
    'comp_id': 'pa0011013',
    'comp_label': 'textblock',
    'comp_fileid': 'img0011-alto',
    'comp_page_no': 11},
   {'comp_role': 'pagearea',
    'comp_id': 'pa0011014',
    'comp_label': 'textblock',
    'comp_fileid': 'img0011-alto',
    'comp_page_no': 11},
   {'comp_role': 'pagearea',
    'comp_id': 'pa0011015',
    'comp_label': 'textblock',
    'comp_fileid': 'img0011-alto',
    'comp_page_no': 11},
   {'comp_role': 'pagearea',
    'comp_id': 'pa0011016',
    'comp_label': 'textblock',
    'comp_fileid': 'img0011-alto',
    'comp_page_no': 11},
   {'comp_role': 'pagearea',
    'comp_id': 'pa0011017',
    'comp_label': 'textblock',
    'comp_fileid': 'img0011-alto',
    'comp_page_no': 11},
   {'comp_role': 'pagearea',
    'comp_id': 'pa0011018',
    'comp_label': 'textblock',
    'comp_fileid': 'img0011-alto',
    'comp_page_no': 11},
   {'comp_role': 'pagearea',
    'comp_id': 'pa0011019',
    'comp_label': 'textblock',
    'comp_fileid': 'img0011-alto',
    'comp_page_no': 11},
   {'comp_role': 'pagearea',
    'comp_id': 'pa0011020',
    'comp_label': 'textblock',
    'comp_fileid': 'img0011-alto',
    'comp_page_no': 11},
   {'comp_role': 'pagearea',
    'comp_id': 'pa0011021',
    'comp_label': 'textblock',
    'comp_fileid': 'img0011-alto',
    'comp_page_no': 11},
   {'comp_role': 'pagearea',
    'comp_id': 'pa0011022',
    'comp_label': 'textblock',
    'comp_fileid': 'img0011-alto',
    'comp_page_no': 11},
   {'comp_role': 'pagearea',
    'comp_id': 'pa0011023',
    'comp_label': 'illustration',
    'comp_fileid': 'img0011-alto',
    'comp_page_no': 11,
    'coords': [2887, 2183, 789, 575]},
   {'comp_role': 'pagearea',
    'comp_id': 'pa0011024',
    'comp_label': 'caption',
    'comp_fileid': 'img0011-alto',
    'comp_page_no': 11,
    'coords': [3047, 2805, 525, 38]}]}}

In [41]:
cis_img_parts[43]#38

{'pa0011023': [{'comp_role': 'pagearea',
   'comp_id': 'pa0011023',
   'comp_label': 'illustration',
   'comp_fileid': 'img0011-alto',
   'comp_page_no': 11,
   'coords': [2887, 2183, 789, 575]},
  {'comp_role': 'pagearea',
   'comp_id': 'pa0011024',
   'comp_label': 'caption',
   'comp_fileid': 'img0011-alto',
   'comp_page_no': 11,
   'coords': [3047, 2805, 525, 38]}]}

In [26]:
bl_issue.pages[9]

In [21]:
issue_images_path = "/mnt/impresso_images_BL/ILOL/1843/05/21/a"
pg_filename = 'ILOL-1843-05-21-a-p{num}.jp2'
pg_path = os.path.join(issue_images_path, pg_filename)

In [ ]:
ci_idx = 0
ci = content_items[ci_idx]
img_part = cis_img_parts[ci_idx]
page_n = ci['m']['pp'][0]
pg_1_path = pg_path.format(num=str(page_n).zfill(4))

pg_1_img = Image.open(pg_1_path)
for div_id, parts in img_part.items():
    coords_img_xy = coords_to_xy(parts['coords'])
    print(f"coords_img_xy:{coords_img_xy}")
    pg_1_img = draw_box_on_img(pg_1_path, coords_img_xy, pg_1_img, width=15)
    if 'caption_coords' in parts:
        coords_cap_xy = coords_to_xy(parts['caption_coords'])
        print(f"coords_cap_xy:{coords_cap_xy}")
        #coords_cap_xy = coords_to_xy([int(c) for c in str_coords])
        pg_1_img = draw_box_on_img(pg_1_path, coords_cap_xy, pg_1_img, width=10)
    print(f"showing with {div_id}")
    pg_1_img.show()

In [ ]:
ci_idx = 43
ci = content_items[ci_idx]
img_part = cis_img_parts[ci_idx]
page_n = ci['m']['pp'][0]
pg_1_path = pg_path.format(num=str(page_n).zfill(4))

pg_1_img = Image.open(pg_1_path)
for div_id, parts in img_part.items():
    coords_img_xy = [int(c) for c in parts['coords'].split(',')]
    #coords_img_xy = coords_to_xy([int(c) for c in str_coords])
    coords_img_xywh = coords_to_xywh(coords_img_xy)
    print(f"coords_img_xy:{coords_img_xy}, coords_img_xywh:{coords_img_xywh}")
    pg_1_img = draw_box_on_img(pg_1_path, coords_img_xy, pg_1_img, width=15)
    if 'caption_coords' in parts:
        coords_cap_xy = [int(c) for c in parts['caption_coords'].split(',')]
        #coords_cap_xy = coords_to_xy([int(c) for c in str_coords])
        coords_cap_xywh = coords_to_xywh(coords_cap_xy)
        print(f"coords_cap_xy:{coords_cap_xy}, coords_cap_xywh:{coords_cap_xywh}")
        pg_1_img = draw_box_on_img(pg_1_path, coords_cap_xy, pg_1_img, width=10)
    print(f"showing with {div_id}")
    pg_1_img.show()

In [ ]:
problem_div = divs[37]
problem_div

tag = tag = f"#{problem_div.get('ID')}"
linkgrp = structlink.find("smLocatorLink", {"xlink:href": tag}).parent
print(tag, linkgrp)

pb_div_parts_ids = [
    x.get("xlink:href")[1:]
    for x in linkgrp.findAll("smLocatorLink")
    if x.get("xlink:href") != tag
]

print(f"pb_div_parts = {pb_div_parts_ids}")

prb_div_part_div = phys_structmap.find("div", {"ID": pb_div_parts_ids[0]})

comp_role = prb_div_part_div.get('TYPE').lower() if type_attr else None

print(f"comp_role = {comp_role}")

prb_div_part_div

#### `_parse_content_parts`

In [ ]:
tag = tag = f"#{item_div.get('ID')}"
print(tag)

linkgrp = structlink.find("smLocatorLink", {"xlink:href": tag}).parent

# Remove `#` from xlink:href
parts_ids = [
    x.get("xlink:href")[1:]
    for x in linkgrp.findAll("smLocatorLink")
    if x.get("xlink:href") != tag
]

parts_ids

#art0001
<mets:smLinkGrp>
<mets:smLocatorLink xlink:href="#art0001" xlink:label="article" xlink:type="locator"/>
<mets:smLocatorLink xlink:href="#pa0001001" xlink:label="page1 area1" xlink:type="locator"/>
<mets:smLocatorLink xlink:href="#pa0001002" xlink:label="page1 area2" xlink:type="locator"/>
<mets:smLocatorLink xlink:href="#pa0001003" xlink:label="page1 area3" xlink:type="locator"/>
<mets:smLocatorLink xlink:href="#pa0001004" xlink:label="page1 area4" xlink:type="locator"/>
<mets:smLocatorLink xlink:href="#pa0001005" xlink:label="page1 area5" xlink:type="locator"/>
<mets:smLocatorLink xlink:href="#pa0001006" xlink:label="page1 area6" xlink:type="locator"/>
<mets:smLocatorLink xlink:href="#pa0001007" xlink:label="page1 area7" xlink:type="locator"/>
<mets:smArcLink ARCTYPE="logicalphysical" xlink:from="article" xlink:to="page1 area1" xlink:type="arc"/>
<mets:smArcLink ARCTYPE="logicalphysical" xlink:from="article" xlink:to="page1 area2" xlink:type="arc"/>
<mets:smArcLink ARCTYPE="logicalphysical" xlink:from="article" xlink:to="page1 area3" xlink:type="arc"/>
<mets:smArcLink ARCTYPE="logicalphysical" xlink:from="article" xlink:to="page1 area4" xlink:type="arc"/>
<mets:smArcLink ARCTYPE="logicalphysical" xlink:from="article" xlink:to="page1 area5" xlink:type="arc"/>
<mets:smArcLink ARCTYPE="logicalphysical" xlink:from="article" xlink:to="page1 area6" xlink:type="arc"/>
<mets:smArcLink ARCTYPE="logicalphysical" xlink:from="article" xlink:to="page1 area7" xlink:type="arc"/>
</mets:smLinkGrp>

['pa0001001',
 'pa0001002',
 'pa0001003',
 'pa0001004',
 'pa0001005',
 'pa0001006',
 'pa0001007']

In [15]:
def _get_part_dict(div, comp_role: str | None):
    """Construct the parts for a certain div entry of METS.

    Args:
        div (Tag): Content item div
        comp_role (str | None): Role of the component

    Returns:
        dict[str, Any]: Parts dict for given div.
    """
    comp_fileid = div.find("area", {"BETYPE": "IDREF"}).get("FILEID")
    comp_id = div.get("ID")
    comp_page_no = int(div.parent.get("ORDER"))
    # This is where illustrations will be identified
    comp_label = div.get("LABEL").lower()
    if comp_role is None:
        type_attr = div.get("TYPE")
        comp_role = type_attr.lower() if type_attr else None

    return {
        "comp_role": comp_role,
        "comp_id": comp_id,
        "comp_label": comp_label,
        "comp_fileid": comp_fileid,
        "comp_page_no": int(comp_page_no),
    }

In [17]:
div = phys_structmap.find("div", {"ID": parts_ids[0]})

div.get("LABEL")

'Textblock'

In [24]:
found_divs = phys_structmap.find_all('div', {"ID": lambda x: x in parts_ids})

all(d.get('LABEL') for d in found_divs)

True

In [16]:
parts = []
image_parts = {}
last_img_part_id = None
last_img_part_idx = None
for idx, p in enumerate(parts_ids):
    # Get element in physical map
    div = phys_structmap.find("div", {"ID": p})
    type_attr = div.get("TYPE")
    comp_role = type_attr.lower() if type_attr else None

    # In that case, need to add all parts
    if comp_role == "page":
        for x in div.findAll("div"):
            div_parts = _get_part_dict(x, None)
    else:
        div_parts = _get_part_dict(div, comp_role)
    
    # for each illustration, store its coordinates and any potential caption
    if div.get("LABEL").lower() == 'illustration':
        image_parts[p] = {
                "legacy_parts": div_parts,
                "coords": div.find("area", {"SHAPE": "RECT"}).get("COORDS"),
            }
        # keep track of which illustration it is to make sure we can connect them back after
        last_img_part_id = p
        last_img_part_idx = idx
    # if the next element is a caption, attach it directly
    if div.get("LABEL").lower() == 'caption':
        if idx-1 == last_img_part_idx:
            image_parts[last_img_part_id]['caption_parts'] = div_parts
        else:
            msg = f"self.id, {div_parts['comp_page_no']} - caption {div.get('ID')} does not follow an illustration!"
    
    parts.append(div_parts)

parts

[{'comp_role': 'pagearea',
  'comp_id': 'pa0001001',
  'comp_label': 'textblock',
  'comp_fileid': 'img0001-alto',
  'comp_page_no': 1},
 {'comp_role': 'pagearea',
  'comp_id': 'pa0001002',
  'comp_label': 'textblock',
  'comp_fileid': 'img0001-alto',
  'comp_page_no': 1},
 {'comp_role': 'pagearea',
  'comp_id': 'pa0001003',
  'comp_label': 'textblock',
  'comp_fileid': 'img0001-alto',
  'comp_page_no': 1},
 {'comp_role': 'pagearea',
  'comp_id': 'pa0001004',
  'comp_label': 'textblock',
  'comp_fileid': 'img0001-alto',
  'comp_page_no': 1},
 {'comp_role': 'pagearea',
  'comp_id': 'pa0001005',
  'comp_label': 'illustration',
  'comp_fileid': 'img0001-alto',
  'comp_page_no': 1},
 {'comp_role': 'pagearea',
  'comp_id': 'pa0001006',
  'comp_label': 'caption',
  'comp_fileid': 'img0001-alto',
  'comp_page_no': 1},
 {'comp_role': 'pagearea',
  'comp_id': 'pa0001007',
  'comp_label': 'illustration',
  'comp_fileid': 'img0001-alto',
  'comp_page_no': 1}]

In [55]:
image_parts

{'pa0001005': {'legacy_parts': {'comp_role': 'pagearea',
   'comp_id': 'pa0001005',
   'comp_label': 'illustration',
   'comp_fileid': 'img0001-alto',
   'comp_page_no': 1},
  'coords': '298,4676,2539,5835',
  'caption_parts': {'comp_role': 'pagearea',
   'comp_id': 'pa0001006',
   'comp_label': 'caption',
   'comp_fileid': 'img0001-alto',
   'comp_page_no': 1}},
 'pa0001007': {'legacy_parts': {'comp_role': 'pagearea',
   'comp_id': 'pa0001007',
   'comp_label': 'illustration',
   'comp_fileid': 'img0001-alto',
   'comp_page_no': 1},
  'coords': '1649,4794,2147,4985'}}

In [53]:
content_item = {
    "m": {
        "id": f"{bl_issue.id}-i{str(counter).zfill(4)}",
        "tp": div_type,
        "pp": [],
    },
    "l": {
        "bl_nlp": bl_issue.nlp,
        "id": item_div.get("ID"),
        "parts": parts,
    },
}
for p in content_item["l"]["parts"]:
    pge_no = p["comp_page_no"]
    if pge_no not in content_item["m"]["pp"]:
        content_item["m"]["pp"].append(pge_no)

content_item

{'m': {'id': 'ILOL-1843-05-21-a-i0001', 'tp': 'article', 'pp': [1]},
 'l': {'bl_nlp': '0003005',
  'id': 'art0001',
  'parts': [{'comp_role': 'pagearea',
    'comp_id': 'pa0001001',
    'comp_label': 'textblock',
    'comp_fileid': 'img0001-alto',
    'comp_page_no': 1},
   {'comp_role': 'pagearea',
    'comp_id': 'pa0001002',
    'comp_label': 'textblock',
    'comp_fileid': 'img0001-alto',
    'comp_page_no': 1},
   {'comp_role': 'pagearea',
    'comp_id': 'pa0001003',
    'comp_label': 'textblock',
    'comp_fileid': 'img0001-alto',
    'comp_page_no': 1},
   {'comp_role': 'pagearea',
    'comp_id': 'pa0001004',
    'comp_label': 'textblock',
    'comp_fileid': 'img0001-alto',
    'comp_page_no': 1},
   {'comp_role': 'pagearea',
    'comp_id': 'pa0001005',
    'comp_label': 'illustration',
    'comp_fileid': 'img0001-alto',
    'comp_page_no': 1},
   {'comp_role': 'pagearea',
    'comp_id': 'pa0001006',
    'comp_label': 'caption',
    'comp_fileid': 'img0001-alto',
    'comp_page_no': 1},
   {'comp_role': 'pagearea',
    'comp_id': 'pa0001007',
    'comp_label': 'illustration',
    'comp_fileid': 'img0001-alto',
    'comp_page_no': 1}]}}

In [ ]:
def _get_image_parts(parts_ids):
    """Construct the parts for a certain div entry of METS.

    Args:
        div (Tag): Content item div
        comp_role (str | None): Role of the component

    Returns:
        dict[str, Any]: Parts dict for given div.
    """
    comp_fileid = div.find("area", {"BETYPE": "IDREF"}).get("FILEID")
    comp_id = div.get("ID")
    comp_page_no = int(div.parent.get("ORDER"))
    # This is where illustrations will be identified
    comp_label = div.get("LABEL").lower()
    if comp_label == 'illustration':
        return div

In [ ]:
for p in
image_parts = [for p in parts_ids]

#### Debug page

In [ ]:
bl_issue.pages[0].

'ILOL-1843-05-21-a-p0001'

In [20]:
for p in bl_issue.pages:
    p.add_issue(bl_issue)
    p.parse()

bl_issue.pages[0].page_data

{'id': 'ILOL-1843-05-21-a-p0001',
 'cdt': '2025-08-25 10:58:49',
 'ts': '2025-08-25T08:58:49Z',
 'st': 'newspaper',
 'sm': 'print',
 'r': [{'c': [164, 2748, 1235, 345],
   'p': [{'c': [164, 2748, 1235, 345],
     'l': ({'c': [197, 2750, 1202, 46],
       't': [{'c': [197, 2756, 44, 27], 'tx': 'On'},
        {'c': [252, 2757, 137, 38], 'tx': 'Monday,'},
        {'c': [400, 2761, 58, 24], 'tx': 'Mr.'},
        {'c': [469, 2761, 91, 24], 'tx': 'James'},
        {'c': [578, 2759, 110, 28], 'tx': 'Travis,'},
        {'c': [701, 2756, 145, 30], 'tx': 'modeller,'},
        {'c': [863, 2756, 31, 27], 'tx': 'of'},
        {'c': [909, 2753, 208, 28], 'tx': 'Gresse-street,'},
        {'c': [1131, 2757, 55, 17], 'tx': 'was'},
        {'c': [1197, 2750, 118, 31], 'tx': 'charged'},
        {'c': [1331, 2750, 68, 25], 'tx': 'with'}]},
      {'c': [167, 2781, 1232, 41],
       't': [{'c': [167, 2786, 115, 36], 'tx': 'Wilfully'},
        {'c': [293, 2789, 135, 33], 'tx': 'breaking'},
        {'c': [438, 2797, 17, 17], 'tx': 'a'},
        {'c': [466, 2792, 60, 24], 'tx': 'cast'},
        {'c': [537, 2791, 30, 25], 'tx': 'of'},
        {'c': [575, 2797, 17, 19], 'tx': 'a'},
        {'c': [603, 2789, 93, 25], 'tx': 'naked'},
        {'c': [707, 2789, 112, 28], 'tx': 'female,'},
        {'c': [830, 2789, 79, 25], 'tx': 'three'},
        {'c': [920, 2786, 57, 25], 'tx': 'feet'},
        {'c': [987, 2786, 28, 24], 'tx': 'in'},
        {'c': [1027, 2783, 107, 31], 'tx': 'height,'},
        {'c': [1148, 2781, 57, 25], 'tx': 'and'},
        {'c': [1216, 2781, 101, 25], 'tx': 'valued'},
        {'c': [1334, 2781, 65, 30], 'tx': '10s.,'}]},
      {'c': [165, 2813, 1233, 44],
       't': [{'c': [165, 2816, 49, 28], 'tx': 'the'},
        {'c': [224, 2824, 135, 28], 'tx': 'property'},
        {'c': [367, 2820, 31, 25], 'tx': 'of'},
        {'c': [406, 2822, 128, 24], 'tx': 'Antonio'},
        {'c': [545, 2820, 132, 36], 'tx': 'Caproni,'},
        {'c': [687, 2819, 30, 25], 'tx': 'of'},
        {'c': [728, 2820, 54, 24], 'tx': 'No.'},
        {'c': [789, 2820, 44, 30], 'tx': "9'7,"},
        {'c': [844, 2817, 99, 31], 'tx': "Gray's"},
        {'c': [950, 2816, 143, 28], 'tx': 'Inn-lane,'},
        {'c': [1101, 2820, 38, 17], 'tx': 'an'},
        {'c': [1148, 2813, 135, 24], 'tx': 'itinerant'},
        {'c': [1294, 2813, 104, 24], 'tx': 'vendor'}]},
      {'c': [165, 2843, 1234, 43],
       't': [{'c': [165, 2846, 31, 25], 'tx': 'of'},
        {'c': [211, 2852, 202, 30], 'tx': 'images.—Mr.'},
        {'c': [425, 2852, 99, 25], 'tx': 'Travis'},
        {'c': [535, 2852, 109, 33], 'tx': 'praised'},
        {'c': [655, 2852, 49, 25], 'tx': 'the'},
        {'c': [717, 2850, 65, 25], 'tx': 'skill'},
        {'c': [795, 2850, 31, 27], 'tx': 'of'},
        {'c': [843, 2850, 47, 25], 'tx': 'the'},
        {'c': [901, 2847, 82, 27], 'tx': 'artist'},
        {'c': [994, 2846, 55, 25], 'tx': 'and'},
        {'c': [1060, 2844, 49, 25], 'tx': 'the'},
        {'c': [1120, 2843, 181, 31], 'tx': 'proportions'},
        {'c': [1312, 2843, 30, 25], 'tx': 'of'},
        {'c': [1350, 2843, 49, 25], 'tx': 'the'}]},
      {'c': [165, 2874, 1234, 38],
       't': [{'c': [165, 2877, 99, 35], 'tx': 'agure,'},
        {'c': [279, 2882, 50, 27], 'tx': "'but"},
        {'c': [339, 2883, 129, 25], 'tx': 'declared'},
        {'c': [483, 2883, 22, 25], 'tx': 'it'},
        {'c': [523, 2890, 55, 19], 'tx': 'was'},
        {'c': [587, 2883, 131, 25], 'tx': 'indecent'},
        {'c': [734, 2885, 30, 24], 'tx': 'to'},
        {'c': [781, 2882, 65, 25], 'tx': 'look'},
        {'c': [861, 2887, 87, 25], 'tx': 'upon.'},
        {'c': [981, 2877, 123, 31], 'tx': 'Caproni'},
        {'c': [1113, 2882, 57, 19], 'tx': 'was'},
        {'c': [1180, 2874, 134, 30], 'tx': 'exposing'},
        {'c': [1329, 2874, 24, 24], 'tx': 'it'},
        {'c': [1370, 2874, 28, 25], 'tx': 'in'}]},
      {'c': [165, 2904, 1234, 41],
       't': [{'c': [165, 2907, 80, 31], 'tx': 'Fleet'},
        {'c': [249, 2915, 107, 28], 'tx': '-street,'},
        {'c': [367, 2915, 58, 25], 'tx': 'and'},
        {'c': [435, 2921, 57, 19], 'tx': 'was'},
        {'c': [501, 2915, 129, 25], 'tx': 'followed'},
        {'c': [641, 2913, 36, 31], 'tx': 'by'},
        {'c': [690, 2920, 19, 17], 'tx': 'a'},
        {'c': [718, 2913, 91, 25], 'tx': 'crowd'},
        {'c': [825, 2912, 31, 25], 'tx': 'of'},
        {'c': [869, 2907, 236, 35], 'tx': 'boys.—Caproni'},
        {'c': [1120, 2904, 143, 35], 'tx': 'produced'},
        {'c': [1279, 2904, 120, 25], 'tx': 'another'}]},
      {'c': [164, 2934, 1235, 47],
       't': [{'c': [164, 2945, 82, 36], 'tx': 'ropy,'},
        {'c': [257, 2945, 58, 25], 'tx': 'and'},
        {'c': [332, 2945, 46, 25], 'tx': 'Sir'},
        {'c': [397, 2945, 85, 27], 'tx': 'Peter'},
        {'c': [491, 2945, 113, 30], 'tx': 'Laurie,'},
        {'c': [616, 2945, 76, 25], 'tx': 'after'},
        {'c': [701, 2943, 135, 31], 'tx': 'carefully'},
        {'c': [846, 2940, 157, 39], 'tx': 'inspecting'},
        {'c': [1022, 2940, 35, 28], 'tx': 'it,'},
        {'c': [1076, 2939, 61, 25], 'tx': 'said'},
        {'c': [1156, 2937, 24, 24], 'tx': 'it'},
        {'c': [1197, 2942, 57, 19], 'tx': 'was'},
        {'c': [1271, 2934, 74, 27], 'tx': 'unfit'},
        {'c': [1356, 2935, 43, 25], 'tx': 'for'}]},
      {'c': [164, 2967, 1235, 39],
       't': [{'c': [164, 2975, 157, 27], 'tx': 'exhibition'},
        {'c': [329, 2976, 30, 25], 'tx': 'in'},
        {'c': [370, 2976, 49, 27], 'tx': 'the'},
        {'c': [430, 2978, 109, 25], 'tx': 'streets.'},
        {'c': [570, 2976, 28, 25], 'tx': 'If'},
        {'c': [606, 2975, 124, 31], 'tx': 'Caproni'},
        {'c': [740, 2975, 139, 31], 'tx': 'persisted'},
        {'c': [894, 2981, 28, 17], 'tx': 'in'},
        {'c': [943, 2973, 85, 30], 'tx': 'doing'},
        {'c': [1046, 2978, 41, 22], 'tx': 'so,'},
        {'c': [1104, 2970, 36, 25], 'tx': 'he'},
        {'c': [1157, 2969, 91, 25], 'tx': 'would'},
        {'c': [1265, 2969, 35, 25], 'tx': 'be'},
        {'c': [1315, 2967, 83, 25], 'tx': 'liable'}]},
      {'c': [164, 3000, 1235, 35],
       't': [{'c': [164, 3002, 33, 25], 'tx': 'to'},
        {'c': [206, 3005, 35, 27], 'tx': 'be'},
        {'c': [249, 3008, 165, 25], 'tx': 'committed'},
        {'c': [424, 3009, 31, 25], 'tx': 'to'},
        {'c': [465, 3008, 148, 25], 'tx': 'Bridewell'},
        {'c': [630, 3008, 46, 24], 'tx': 'for'},
        {'c': [693, 3013, 19, 17], 'tx': 'a'},
        {'c': [729, 3006, 109, 25], 'tx': 'month.'},
        {'c': [871, 3005, 46, 27], 'tx': 'He'},
        {'c': [928, 3003, 145, 27], 'tx': 'dismissed'},
        {'c': [1083, 3003, 50, 24], 'tx': 'the'},
        {'c': [1150, 3008, 74, 22], 'tx': 'case,'},
        {'c': [1233, 3000, 60, 25], 'tx': 'and'},
        {'c': [1307, 3000, 91, 24], 'tx': 'added'}]},
      {'c': [164, 3030, 1235, 41],
       't': [{'c': [164, 3033, 65, 28], 'tx': 'that'},
        {'c': [238, 3044, 38, 19], 'tx': 'no'},
        {'c': [287, 3038, 162, 33], 'tx': 'magistrate'},
        {'c': [460, 3039, 82, 27], 'tx': 'could'},
        {'c': [553, 3041, 83, 30], 'tx': 'grant'},
        {'c': [646, 3038, 61, 25], 'tx': 'him'},
        {'c': [717, 3036, 211, 31], 'tx': 'compensation'},
        {'c': [943, 3035, 46, 27], 'tx': 'for'},
        {'c': [1000, 3035, 38, 25], 'tx': 'its'},
        {'c': [1052, 3030, 346, 31], 'tx': 'destruction.—Norning'}]},
      {'c': [164, 3065, 115, 28],
       't': [{'c': [164, 3065, 115, 28], 'tx': '2:terabit.'}]})}],
   'pOf': 'ILOL-1843-05-21-a-i0039'},
  {'c': [164, 3132, 1233, 627],
   'p': [{'c': [164, 3132, 1233, 627],
     'l': ({'c': [208, 3132, 1189, 52],
       't': [{'c': [208, 3137, 109, 38], 'tx': 'SOME'},
        {'c': [331, 3140, 213, 44], 'tx': 'peripatetic'},
        {'c': [565, 3140, 244, 44], 'tx': 'philosophers'},
        {'c': [824, 3150, 94, 33], 'tx': 'may,'},
        {'c': [928, 3140, 36, 31], 'tx': 'in'},
        {'c': [975, 3137, 63, 35], 'tx': 'the'},
        {'c': [1049, 3134, 216, 46], 'tx': 'superlative'},
        {'c': [1274, 3132, 106, 35], 'tx': 'refine-', 'hy': True}]},
      {'c': [165, 3186, 1232, 50],
       't': [{'c': [165, 3194, 101, 31], 'tx': 'ment', 'nf': 'refinement'},
        {'c': [290, 3194, 41, 33], 'tx': 'of'},
        {'c': [351, 3194, 96, 33], 'tx': 'their'},
        {'c': [472, 3197, 157, 39], 'tx': 'natures,'},
        {'c': [643, 3205, 85, 31], 'tx': 'carp'},
        {'c': [748, 3195, 39, 31], 'tx': 'at'},
        {'c': [809, 3192, 63, 33], 'tx': 'the'},
        {'c': [894, 3191, 124, 33], 'tx': 'classic'},
        {'c': [1041, 3187, 216, 36], 'tx': 'exhibitions'},
        {'c': [1274, 3186, 38, 33], 'tx': 'in'},
        {'c': [1334, 3195, 63, 24], 'tx': 'our'}]},
      {'c': [164, 3238, 1233, 43],
       't': [{'c': [164, 3241, 131, 36], 'tx': 'streets'},
        {'c': [320, 3244, 41, 35], 'tx': 'of'},
        {'c': [381, 3246, 63, 35], 'tx': 'the'},
        {'c': [469, 3246, 153, 33], 'tx': 'still-life'},
        {'c': [647, 3246, 41, 33], 'tx': 'of'},
        {'c': [707, 3244, 143, 35], 'tx': 'ancient'},
        {'c': [871, 3243, 131, 35], 'tx': 'female'},
        {'c': [1022, 3239, 219, 41], 'tx': 'loveliness;'},
        {'c': [1265, 3241, 39, 31], 'tx': 'to'},
        {'c': [1324, 3238, 72, 41], 'tx': 'wit,'}]},
      {'c': [164, 3288, 1233, 53],
       't': [{'c': [164, 3296, 66, 28], 'tx': 'our'},
        {'c': [244, 3293, 126, 36], 'tx': 'Venus'},
        {'c': [384, 3296, 46, 35], 'tx': 'de'},
        {'c': [444, 3298, 164, 43], 'tx': 'Medicis,'},
        {'c': [616, 3309, 66, 22], 'tx': 'our'},
        {'c': [704, 3298, 161, 33], 'tx': 'Mamma'},
        {'c': [877, 3298, 38, 31], 'tx': 'at'},
        {'c': [931, 3294, 63, 33], 'tx': 'the'},
        {'c': [1008, 3290, 191, 43], 'tx': 'Fountain,'},
        {'c': [1208, 3290, 65, 35], 'tx': 'the'},
        {'c': [1279, 3288, 118, 35], 'tx': 'Three'}]},
      {'c': [165, 3342, 1232, 52],
       't': [{'c': [165, 3342, 134, 36], 'tx': 'Graces'},
        {'c': [310, 3348, 43, 33], 'tx': 'of'},
        {'c': [364, 3348, 153, 46], 'tx': 'Canova,'},
        {'c': [526, 3351, 71, 35], 'tx': 'and'},
        {'c': [608, 3351, 104, 35], 'tx': 'other'},
        {'c': [721, 3350, 191, 33], 'tx': 'venerable'},
        {'c': [921, 3348, 112, 33], 'tx': 'ladies'},
        {'c': [1047, 3345, 41, 35], 'tx': 'of'},
        {'c': [1099, 3345, 61, 33], 'tx': 'the'},
        {'c': [1176, 3343, 88, 35], 'tx': 'attic'},
        {'c': [1276, 3342, 121, 41], 'tx': 'world,'}]},
      {'c': [164, 3392, 1233, 59],
       't': [{'c': [164, 3394, 82, 57], 'tx': '"ho'},
        {'c': [260, 3397, 91, 35], 'tx': 'have'},
        {'c': [365, 3400, 91, 35], 'tx': 'been'},
        {'c': [471, 3403, 173, 35], 'tx': 'snatched'},
        {'c': [658, 3403, 93, 35], 'tx': 'from'},
        {'c': [773, 3403, 63, 31], 'tx': 'the'},
        {'c': [858, 3402, 82, 33], 'tx': 'dust'},
        {'c': [962, 3400, 43, 33], 'tx': 'of'},
        {'c': [1020, 3397, 169, 41], 'tx': 'oblivion,'},
        {'c': [1202, 3394, 72, 36], 'tx': 'and'},
        {'c': [1293, 3392, 104, 35], 'tx': 'made'}]},
      {'c': [164, 3444, 1233, 52],
       't': [{'c': [164, 3449, 181, 35], 'tx': 'immortal'},
        {'c': [365, 3449, 38, 35], 'tx': 'in'},
        {'c': [425, 3454, 65, 33], 'tx': 'the'},
        {'c': [509, 3455, 220, 33], 'tx': 'revealment'},
        {'c': [751, 3455, 41, 33], 'tx': 'of'},
        {'c': [809, 3452, 250, 44], 'tx': 'metropolitan'},
        {'c': [1082, 3449, 162, 41], 'tx': 'lucidity.'},
        {'c': [1301, 3444, 96, 33], 'tx': 'Such'}]},
      {'c': [165, 3494, 1232, 51],
       't': [{'c': [165, 3506, 143, 36], 'tx': 'earpers'},
        {'c': [321, 3502, 91, 35], 'tx': 'have'},
        {'c': [438, 3513, 22, 22], 'tx': 'a'},
        {'c': [485, 3513, 87, 31], 'tx': 'very'},
        {'c': [586, 3504, 80, 33], 'tx': 'nice'},
        {'c': [690, 3507, 123, 30], 'tx': 'notion'},
        {'c': [839, 3506, 41, 31], 'tx': 'of'},
        {'c': [901, 3502, 134, 41], 'tx': 'ethics;'},
        {'c': [1058, 3501, 87, 41], 'tx': 'they'},
        {'c': [1170, 3509, 66, 24], 'tx': 'can'},
        {'c': [1260, 3494, 137, 35], 'tx': 'admire'}]},
      {'c': [164, 3546, 1231, 51],
       't': [{'c': [164, 3551, 132, 41], 'tx': 'female'},
        {'c': [309, 3557, 231, 36], 'tx': 'materialism'},
        {'c': [554, 3557, 38, 33], 'tx': 'in'},
        {'c': [608, 3556, 63, 35], 'tx': 'the'},
        {'c': [683, 3556, 129, 33], 'tx': 'ballets'},
        {'c': [824, 3556, 41, 33], 'tx': 'of'},
        {'c': [874, 3556, 63, 33], 'tx': 'the'},
        {'c': [951, 3564, 120, 33], 'tx': 'opera,'},
        {'c': [1082, 3553, 66, 33], 'tx': 'but'},
        {'c': [1161, 3561, 24, 22], 'tx': 'a'},
        {'c': [1197, 3546, 198, 46], 'tx': 'plaster-of-'}]},
      {'c': [165, 3597, 1231, 57],
       't': [{'c': [165, 3600, 102, 43], 'tx': 'Paris'},
        {'c': [282, 3611, 117, 43], 'tx': 'Hebe,'},
        {'c': [413, 3622, 47, 24], 'tx': 'on'},
        {'c': [485, 3611, 63, 35], 'tx': 'the'},
        {'c': [572, 3611, 107, 41], 'tx': 'caput'},
        {'c': [701, 3608, 41, 33], 'tx': 'of'},
        {'c': [757, 3617, 47, 22], 'tx': 'an'},
        {'c': [819, 3605, 131, 33], 'tx': 'Italian'},
        {'c': [964, 3605, 82, 39], 'tx': 'boy,'},
        {'c': [1058, 3603, 38, 30], 'tx': 'in'},
        {'c': [1112, 3600, 238, 38], 'tx': 'Fleet-street,'},
        {'c': [1364, 3597, 31, 33], 'tx': 'is'}]},
      {'c': [164, 3652, 1230, 52],
       't': [{'c': [164, 3661, 139, 43], 'tx': 'grossly'},
        {'c': [315, 3663, 235, 35], 'tx': 'intolerable!'},
        {'c': [583, 3661, 96, 35], 'tx': 'That'},
        {'c': [687, 3658, 71, 35], 'tx': 'Mr.'},
        {'c': [767, 3657, 124, 35], 'tx': 'James'},
        {'c': [899, 3654, 139, 41], 'tx': 'Travis,'},
        {'c': [1047, 3652, 91, 41], 'tx': 'who,'},
        {'c': [1153, 3660, 54, 24], 'tx': 'we'},
        {'c': [1220, 3658, 173, 35], 'tx': 'presume,'}]},
      {'c': [165, 3701, 1229, 58],
       't': [{'c': [165, 3709, 30, 36], 'tx': 'is'},
        {'c': [209, 3715, 65, 35], 'tx': 'the'},
        {'c': [287, 3717, 99, 33], 'tx': 'model'},
        {'c': [411, 3718, 43, 33], 'tx': 'of'},
        {'c': [471, 3718, 203, 41], 'tx': 'politeness,'},
        {'c': [688, 3712, 124, 38], 'tx': 'should'},
        {'c': [828, 3712, 90, 33], 'tx': 'have'},
        {'c': [943, 3709, 57, 33], 'tx': 'his'},
        {'c': [1022, 3704, 117, 47], 'tx': 'pupils'},
        {'c': [1153, 3702, 183, 44], 'tx': 'disgusted'},
        {'c': [1356, 3701, 38, 33], 'tx': 'in'}]})}],
   'pOf': 'ILOL-1843-05-21-a-i0039'},
  {'c': [1431, 2735, 1232, 316],
   'p': [{'c': [1431, 2735, 1232, 316],
     'l': ({'c': [1433, 2737, 1230, 52],
       't': [{'c': [1433, 2746, 238, 39], 'tx': 'Fleet-street,'},
        {'c': [1693, 2745, 49, 44], 'tx': 'by'},
        {'c': [1764, 2756, 22, 24], 'tx': 'a'},
        {'c': [1811, 2746, 109, 36], 'tx': 'tame,'},
        {'c': [1950, 2739, 231, 46], 'tx': 'unthinking,'},
        {'c': [2202, 2739, 175, 35], 'tx': 'moveless'},
        {'c': [2397, 2737, 96, 43], 'tx': 'lady,'},
        {'c': [2513, 2737, 91, 33], 'tx': 'done'},
        {'c': [2627, 2737, 36, 33], 'tx': 'in'}]},
      {'c': [1433, 2792, 1230, 51],
       't': [{'c': [1433, 2802, 120, 41], 'tx': 'white,'},
        {'c': [1567, 2800, 71, 33], 'tx': 'and'},
        {'c': [1652, 2800, 57, 41], 'tx': 'he,'},
        {'c': [1721, 2794, 220, 47], 'tx': 'unforgetful'},
        {'c': [1953, 2794, 41, 33], 'tx': 'of'},
        {'c': [2000, 2792, 63, 35], 'tx': 'the'},
        {'c': [2072, 2794, 113, 44], 'tx': 'living'},
        {'c': [2194, 2794, 191, 33], 'tx': 'loveliness'},
        {'c': [2398, 2792, 41, 35], 'tx': 'of'},
        {'c': [2450, 2794, 79, 31], 'tx': 'that'},
        {'c': [2543, 2792, 120, 39], 'tx': 'street,'}]},
      {'c': [1433, 2844, 1230, 53],
       't': [{'c': [1433, 2854, 175, 36], 'tx': 'executed'},
        {'c': [1617, 2854, 191, 43], 'tx': 'according'},
        {'c': [1817, 2855, 38, 30], 'tx': 'to'},
        {'c': [1866, 2850, 139, 38], 'tx': 'nature,'},
        {'c': [2013, 2846, 31, 33], 'tx': 'is'},
        {'c': [2052, 2847, 235, 35], 'tx': 'remarkable.'},
        {'c': [2318, 2846, 104, 44], 'tx': 'Why'},
        {'c': [2430, 2846, 112, 35], 'tx': 'break'},
        {'c': [2550, 2855, 24, 24], 'tx': 'a'},
        {'c': [2581, 2844, 82, 44], 'tx': 'lady'}]},
      {'c': [1433, 2896, 1230, 53],
       't': [{'c': [1433, 2907, 38, 33], 'tx': 'in'},
        {'c': [1485, 2906, 87, 43], 'tx': 'half,'},
        {'c': [1594, 2904, 102, 35], 'tx': 'three'},
        {'c': [1718, 2906, 76, 33], 'tx': 'feet'},
        {'c': [1819, 2901, 96, 44], 'tx': 'high,'},
        {'c': [1926, 2898, 71, 35], 'tx': 'and'},
        {'c': [2019, 2898, 102, 33], 'tx': 'leave'},
        {'c': [2145, 2912, 24, 22], 'tx': 'a'},
        {'c': [2191, 2899, 187, 43], 'tx': 'capacious'},
        {'c': [2400, 2899, 176, 39], 'tx': 'creature,'},
        {'c': [2594, 2896, 69, 33], 'tx': 'five'}]},
      {'c': [1431, 2948, 1232, 52],
       't': [{'c': [1431, 2959, 76, 35], 'tx': 'feet'},
        {'c': [1528, 2967, 69, 25], 'tx': 'one'},
        {'c': [1620, 2956, 38, 33], 'tx': 'in'},
        {'c': [1682, 2956, 137, 44], 'tx': 'height,'},
        {'c': [1833, 2951, 113, 35], 'tx': 'whole'},
        {'c': [1961, 2950, 72, 35], 'tx': 'and'},
        {'c': [2057, 2959, 47, 25], 'tx': 'an'},
        {'c': [2126, 2951, 142, 35], 'tx': 'entire?'},
        {'c': [2309, 2948, 90, 35], 'tx': 'This'},
        {'c': [2422, 2948, 164, 41], 'tx': 'anomaly'},
        {'c': [2611, 2957, 52, 24], 'tx': 'we'}]},
      {'c': [1433, 3008, 394, 43],
       't': [{'c': [1433, 3011, 140, 39], 'tx': 'despair'},
        {'c': [1586, 3008, 43, 36], 'tx': 'of'},
        {'c': [1638, 3008, 189, 43], 'tx': 'resolving.'}]})}],
   'pOf': 'ILOL-1843-05-21-a-i0039'},
  {'c': [1427, 3066, 1238, 678],
   'p': [{'c': [1427, 3066, 1238, 678],
     'l': ({'c': [1476, 3066, 1189, 54],
       't': [{'c': [1476, 3079, 77, 35], 'tx': 'The'},
        {'c': [1567, 3077, 198, 43], 'tx': 'inspection'},
        {'c': [1778, 3076, 49, 43], 'tx': 'by'},
        {'c': [1836, 3072, 60, 35], 'tx': 'Sir'},
        {'c': [1906, 3071, 109, 35], 'tx': 'Peter'},
        {'c': [2022, 3071, 131, 35], 'tx': 'Laurie'},
        {'c': [2167, 3071, 30, 35], 'tx': 'is'},
        {'c': [2211, 3069, 126, 46], 'tx': 'highly'},
        {'c': [2348, 3068, 194, 36], 'tx': 'creditable'},
        {'c': [2557, 3069, 36, 33], 'tx': 'to'},
        {'c': [2608, 3066, 57, 35], 'tx': 'his'}]},
      {'c': [1431, 3123, 1234, 52],
       't': [{'c': [1431, 3131, 254, 44], 'tx': 'investigating'},
        {'c': [1706, 3132, 140, 31], 'tx': 'nature.'},
        {'c': [1887, 3126, 58, 33], 'tx': 'Sir'},
        {'c': [1959, 3124, 110, 35], 'tx': 'Peter'},
        {'c': [2093, 3126, 31, 31], 'tx': 'is'},
        {'c': [2150, 3135, 46, 24], 'tx': 'no'},
        {'c': [2216, 3124, 142, 35], 'tx': 'surface'},
        {'c': [2383, 3134, 109, 30], 'tx': 'man;'},
        {'c': [2513, 3123, 47, 33], 'tx': 'he'},
        {'c': [2581, 3131, 83, 33], 'tx': 'goes'}]},
      {'c': [1433, 3172, 1232, 55],
       't': [{'c': [1433, 3184, 128, 43], 'tx': 'deeply'},
        {'c': [1573, 3184, 76, 33], 'tx': 'into'},
        {'c': [1665, 3183, 63, 33], 'tx': 'the'},
        {'c': [1740, 3181, 109, 33], 'tx': 'bottom'},
        {'c': [1863, 3178, 41, 36], 'tx': 'of'},
        {'c': [1923, 3186, 110, 33], 'tx': 'every'},
        {'c': [2046, 3175, 131, 46], 'tx': 'charge'},
        {'c': [2191, 3175, 156, 44], 'tx': 'brought'},
        {'c': [2361, 3175, 124, 35], 'tx': 'before'},
        {'c': [2499, 3173, 99, 43], 'tx': 'him;'},
        {'c': [2619, 3172, 46, 35], 'tx': 'he'}]},
      {'c': [1431, 3224, 1234, 55],
       't': [{'c': [1431, 3236, 124, 43], 'tx': 'unrips'},
        {'c': [1581, 3233, 195, 43], 'tx': 'swindlers,'},
        {'c': [1794, 3230, 195, 46], 'tx': 'pulverises'},

### TEST image coords for BL-alias format

In [ ]:
img_path = "/mnt/impresso_ocr_BL_old/0000104/1881/0729/0000104_18810729_0001.jp2"

page_coords = coords_to_xy([1525,347,7808,8125])
summer_coords = [94,96,383,150]
the_coords = [800,90,929,130]
eagle_coords = [945,92,1136,135]
packing_coords = [1149,96,1377,141]
sentence_coords = [the_coords[0], the_coords[1], packing_coords[2], packing_coords[3]]
article_1_coords = [52,62,6335,7829]

img = draw_box_on_img(img_path, article_1_coords, width=20)

img

In [ ]:
img_pat_2 = "/mnt/impresso_ocr_BL_old/0000104/1881/0729/0000104_18810729_0002.jp2"

article_2_coords = [0,45,4945,7872]
article_3_coords = [4183,35,5642,7822]
article_4_coords = [4903,25,6350,7817]

img_2 = draw_box_on_img(img_pat_2, article_3_coords, width=20)
img_2 = draw_box_on_img(img_pat_2, article_4_coords, img_2, width=10)

img_2