# Preprocessing of the RTS data to prepare for the Issue Index creation

In [2]:
import os
import json
from bs4 import BeautifulSoup
from datetime import datetime
import pandas as pd
from tqdm import tqdm
import csv

### Directory Structure: `/mnt/project_impresso/original/RTS`

The RTS directory contains radio content organized by program/show names. The filesystem structure is organized as follows:

```
/mnt/project_impresso/original/RTS/
│
├── News Programs (Journaux)
│   ├── j_mat/                    (morning news)  
│   │   ├── audio                       (all PM3 audio files)
│   │   ├── stt                         (all stt and xml files containing the text related to each audio file)
│   │   ├── ExpXml-20251106-122951.xml  (xml files with the metadata relating the MP3 audio and XML files for each listing)
│   │   ...  
│   │   └── ExpXml-20251113-171933.xml                   
│   ├── j_midi/                   (midday news)
│   ├── j13h/                     (1 PM news)
│   ├── j13h2/                    (1 PM news variant)
│   ├── j_soir/                   (evening news)
│   └── j_nuit/                   (night news)
│
...
│
└── Other Programs
    ├── petitdej/                 (breakfast)
    ├── ana_media/                (media analysis)
    ├── geneve_info/              (Geneva information)
    └── enquest/                  (enquête/investigation)
```

Each directory contains media files (audio recordings and associated metadata) for that specific radio program.

In [3]:
base_dir = "/mnt/project_impresso/original/RTS"

audios_subdir = 'audio'
asr_subdir = 'stt'
metadata_file_start = "ExpXml"

## Process an example of metadata xml file to extract the contents

In [4]:
example_program = "causerie_uni"

example_program_dir = os.path.join(base_dir, example_program)

ex_meta_files = [os.path.join(example_program_dir,f) for f in os.listdir(example_program_dir) if f.startswith(metadata_file_start)]
ex_meta_files

['/mnt/project_impresso/original/RTS/causerie_uni/ExpXml-20251029-131700.xml',
 '/mnt/project_impresso/original/RTS/causerie_uni/ExpXml-20251029-132007.xml']

In [25]:
with open(ex_meta_files[0], "r", encoding="utf-8") as f:
    raw_xml = f.read()

xml_doc = BeautifulSoup(raw_xml, "xml")
xml_doc

<?xml version="1.0" encoding="utf-8"?>

In [6]:
docs = xml_doc.find_all("DOCUMENT")
docs

[<DOCUMENT><CLSID>{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}</CLSID><OID>{3267F04D-657F-4DCB-BCB0-44B2B6C2682D}</OID><LOGIN/><TITLE>Adolphe Dygasinski, un Kipling avant Kipling. Causerie de Edouard Cros, privat-docent ? l'Universit? de Fribourg</TITLE><HIERARCHY OID="{3267F04D-657F-4DCB-BCB0-44B2B6C2682D}" current="*" depth="---" title="Adolphe Dygasinski, un Kipling avant Kipling. Causerie de Edouard Cros, privat-docent ? l'Universit? de Fribourg"/><SEQUENCE>1</SEQUENCE><BROADCAST>Causerie universitaire</BROADCAST><DOCUMENTTYPE>Parl?</DOCUMENTTYPE><GEOGRAPHICALDESCRIPTORS><GEOGRAPHICALDESCRIPTOR>Pologne</GEOGRAPHICALDESCRIPTOR></GEOGRAPHICALDESCRIPTORS><HIERARCHYLEVEL>Sujet</HIERARCHYLEVEL><MODIFIEDBY>albrecjo</MODIFIEDBY><MODIFIEDON>25.05.2022 03:56:53</MODIFIEDON><HISTORY>Disques 78T maison Radio-Lausanne 1466X A, 1467X A, 1466X B, 1467X B</HISTORY><PARTICIPANTS><PARTICIPANT><NAME>Cros, Edouard</NAME><FUNCTION>Conf?rencier/e</FUNCTION><ROLE>privat-docent ? l'Universit? de Fribourg</ROLE></PARTICIPANT></PARTICIPANTS><PERSONDESCRIPTORS><PERSONDESCRIPTOR>Dygasinski, Adolphe</PERSONDESCRIPTOR></PERSONDESCRIPTORS><PRODUCTIONTYPE>Production propre</PRODUCTIONTYPE><RECORDINGDATES><RECORDINGDATE>20/11/1939 - 20/11/1939</RECORDINGDATE></RECORDINGDATES><RECORDINGPLACE>Lausanne (Studio de Radio-Lausanne)</RECORDINGPLACE><RIGHTSNOTES>Memoriav</RIGHTSNOTES><RIGHTSSTATUS>Clarifi?</RIGHTSSTATUS><RIGHTSUSAGEPOSSIBILITIES><RIGHTSUSAGEPOSSIBILITY>Tous</RIGHTSUSAGEPOSSIBILITY></RIGHTSUSAGEPOSSIBILITIES><SERIESTITLE>Sauvegarde d'archives. Fribourg</SERIESTITLE><SUMMARY>Conf?rence sur l'oeuvre de l'?crivain polonais Dygasinsky, ? l'occasion du 100e anniversaire de sa naissance. Publiciste, conteur et traducteur, il repr?sente l'esprit positiviste de l'?poque et contribue ? la propagation des nouveaux courants d'id?es. Pr?curseur de Montessori. Romancier sensible ? la r?alit? des d?sh?rit?s des grandes villes, des paysans. Romancier animalier, il dresse le portrait psychologique des animaux de son pays natal, sans tomber dans l'anthropomorphisme. Exemple avec son portrait de la cigogne.</SUMMARY><THEMATICALDESCRIPTORS><THEMATICALDESCRIPTOR>?crivain</THEMATICALDESCRIPTOR><THEMATICALDESCRIPTOR>litt?rature</THEMATICALDESCRIPTOR><THEMATICALDESCRIPTOR>19e si?cle</THEMATICALDESCRIPTOR><THEMATICALDESCRIPTOR>paysan</THEMATICALDESCRIPTOR><THEMATICALDESCRIPTOR>portrait (art)</THEMATICALDESCRIPTOR><THEMATICALDESCRIPTOR>cigogne</THEMATICALDESCRIPTOR><THEMATICALDESCRIPTOR>naturalisme</THEMATICALDESCRIPTOR></THEMATICALDESCRIPTORS><WORKFLOWSTATUS>Valid?</WORKFLOWSTATUS><ASSEMBLYSTATUS>Brut</ASSEMBLYSTATUS><FIRSTBROADCASTDATES><FIRSTBROADCASTDATE>19/12/1939 - __/__/____</FIRSTBROADCASTDATE></FIRSTBROADCASTDATES><LIVE>Non live</LIVE><MODULATIONTYPE>Mono</MODULATIONTYPE><PROGRAMMES><PROGRAMME>Radio Sottens</PROGRAMME></PROGRAMMES><SUBDOMAINS><SUBDOMAIN>Conf?rence</SUBDOMAIN></SUBDOMAINS><WORKDURATION>00:13:38.975</WORKDURATION><WORKDURATIONCOMPL>Non</WORKDURATIONCOMPL><SUPPORTS><SUPPORT><CLSID>{9C19C69A-A4DC-479E-94F1-61FF72CA7889}</CLSID><OID>{4A6EE48F-FE63-41E9-A277-B3F05C91EC30}</OID><TITLE>Adolphe Dygasinski, un Kipling avant Kipling. Causerie de Edouard Cros, privat-docent ? l'Universit? de Fribourg</TITLE><ISDIGITAL>True</ISDIGITAL><FILENAME>1211554131-1466X_complet_wav_958-SIROM{CFEC57B3-AADF-47BB-8ACF-49BE06EB6AD3}.wav</FILENAME><CATALOGUINGSTATUS>D+A total</CATALOGUINGSTATUS><SOURCE>Quadriga</SOURCE><UNITDURATION>00:13:38.974</UNITDURATION><UNITDURATIONCOMPL>Non</UNITDURATIONCOMPL><PHYSICALPROPERTIES><ANNOTATIONS>Non</ANNOTATIONS><NUMBEROFCOPIES>0</NUMBEROFCOPIES><NUMBEROFSUPPORTS>0</NUMBEROFSUPPORTS></PHYSICALPROPERTIES></SUPPORT></SUPPORTS></DOCUMENT>,
 <DOCUMENT><CLSID>{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}</CLSID><OID>{C380E906-0487-4324-B232-70F6E3AB9191}</OID><LOGIN/><TITLE>Au coeur des lettres fran?aises : Georges Duhamel. Causerie de Ren? Bady, professeur ? l'Universit? de Fribourg</TITLE><HIERARCHY OID="{C380E906-0487-4324-B232-70F6E3AB9191}" current="*" depth="---" title="Au coeur des lettres fran?aises : Georges Duhamel. Causerie de Ren? Bady, professeur ? l'Universit? de Fribourg"/><SEQUENCE>1</SEQUENCE><BROADCAST>Causerie universitaire</BROADCAST><DOCUMENTTYPE>Parl?</DOCUMENTTYPE><GEOGRAPHICALDESCRIPTORS><GEOGRAPHICALDESCRIPTOR>France</GEOGRAPHICALDESCRIPTOR></GEOGRAPHICALDESCRIPTORS><HIERARCHYLEVEL>Sujet</HIERARCHYLEVEL><MODIFIEDBY>albrecjo</MODIFIEDBY><MODIFIEDON>30.05.2022 08:35:49</MODIFIEDON><NOTES>Laque piqu?e</NOTES><HISTORY>Disques 78T maison Radio-Lausanne 3151 Ab, 3152 A, 3151 B, 3152 B, 3153, 3151 Aa (bribe)</HISTORY><PARTICIPANTS><PARTICIPANT><NAME>Bady, Ren?</NAME><FUNCTION>Conf?rencier/e</FUNCTION><ROLE>professeur ? l'Universit? de Fribourg</ROLE></PARTICIPANT></PARTICIPANTS><PERSONDESCRIPTORS><PERSONDESCRIPTOR>Duhamel, Georges</PERSONDESCRIPTOR></PERSONDESCRIPTORS><PRODUCTIONTYPE>Production propre</PRODUCTIONTYPE><RECORDINGDATES><RECORDINGDATE>26/11/1940 - 26/11/1940</RECORDINGDATE></RECORDINGDATES><RECORDINGPLACE>Lausanne (Studio de Radio-Lausanne)</RECORDINGPLACE><RIGHTSNOTES>Memoriav</RIGHTSNOTES><RIGHTSSTATUS>Clarifi?</RIGHTSSTATUS><RIGHTSUSAGEPOSSIBILITIES><RIGHTSUSAGEPOSSIBILITY>Tous</RIGHTSUSAGEPOSSIBILITY></RIGHTSUSAGEPOSSIBILITIES><SERIESTITLE>Sauvegarde d'archives. Fribourg</SERIESTITLE><SUMMARY>Portrait de l'?crivain fran?ais. Une question traverse toute l'oeuvre de Duhamel : quels sont les pouvoirs de l'homme face ? sa destin?e? M?decin major durant la Grande Guerre et t?moin de l'h?ro?sme des soldats. La probl?matique du h?ros et du saint dans ses oeuvres. Humanisme, observation et recherche.</SUMMARY><THEMATICALDESCRIPTORS><THEMATICALDESCRIPTOR>litt?rature</THEMATICALDESCRIPTOR><THEMATICALDESCRIPTOR>guerre mondiale (premi?re)</THEMATICALDESCRIPTOR><THEMATICALDESCRIPTOR>religion et croyances</THEMATICALDESCRIPTOR><THEMATICALDESCRIPTOR>?crivain</THEMATICALDESCRIPTOR></THEMATICALDESCRIPTORS><WORKFLOWSTATUS>Valid?</WORKFLOWSTATUS><ASSEMBLYSTATUS>Brut</ASSEMBLYSTATUS><FIRSTBROADCASTDATES><FIRSTBROADCASTDATE>07/01/1941 - __/__/____</FIRSTBROADCASTDATE><FIRSTBROADCASTDATE>19/01/1941 - __/__/____</FIRSTBROADCASTDATE></FIRSTBROADCASTDATES><LIVE>Non live</LIVE><MODULATIONTYPE>Mono</MODULATIONTYPE><PROGRAMMES><PROGRAMME>Radio Sottens</PROGRAMME></PROGRAMMES><SUBDOMAINS><SUBDOMAIN>Conf?rence</SUBDOMAIN></SUBDOMAINS><WORKDURATION>00:13:51.582</WORKDURATION><WORKDURATIONCOMPL>Non</WORKDURATIONCOMPL><SUPPORTS><SUPPORT><CLSID>{9C19C69A-A4DC-479E-94F1-61FF72CA7889}</CLSID><OID>{D5EBA98B-8D5F-4CE7-AF13-6D28447B81D3}</OID><TITLE>Au coeur des lettres fran?aises : Georges Duhamel. Causerie de Ren? Bady, professeur ? l'Universit? de Fribourg</TITLE><ISDIGITAL>True</ISDIGITAL><FILENAME>1209129877-3151_p_complet_wav_958-SIROM{8357777C-7412-4674-98A8-B3AC6AB572DB}.wav</FILENAME><CATALOGUINGSTATUS>D+A total</CATALOGUINGSTATUS><SOURCE>Quadriga</SOURCE><UNITDURATION>00:13:51.582</UNITDURATION><UNITDURATIONCOMPL>Non</UNITDURATIONCOMPL><PHYSICALPROPERTIES><ANNOTATIONS>Non</ANNOTATIONS><NUMBEROFCOPIES>0</NUMBEROFCOPIES><NUMBEROFSUPPORTS>0</NUMBEROFSUPPORTS></PHYSICALPROPERTIES></SUPPORT></SUPPORTS></DOCUMENT>,
 <DOCUMENT><CLSID>{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}</CLSID><OID>{1656BB3F-A8EF-4BF4-BE9A-20483F5665C8}</OID><LOGIN/><TITLE>Epicure ou la religion du plaisir : Causerie de Ren? Schaerer, charg? de cours ? l'Universit? de Neuch?tel</TITLE><HIERARCHY OID="{1656BB3F-A8EF-4BF4-BE9A-20483F5665C8}" current="*" depth="---" title="Epicure ou la religion du plaisir : Causerie de Ren? Schaerer, charg? de cours ? l'Universit? de Neuch?tel"/><SEQUENCE>1</SEQUENCE><BROADCAST>Causerie universitaire</BROADCAST><DOCUMENTTYPE>Parl?</DOCUMENTTYPE><GEOGRAPHICALDESCRIPTORS><GEOGRAPHICALDESCRIPTOR>Gr?ce</GEOGRAPHICALDESCRIPTOR><GEOGRAPHICALDESCRIPTOR>Neuch?tel (canton)</GEOGRAPHICALDESCRIPTOR><GEOGRAPHICALDESCRIPTOR>Antiquit? (civilisation)</GEOGRAPHICALDESCRIPTOR></GEOGRAPHICALDESCRIPTORS><HIERARCHYLEVEL>Sujet</HIERARCHYLEVEL><MODIFIEDBY>suillojo</MODIFIEDBY><MODIFIEDON>27.11.2019 10:08:43</MODIFIEDON><HISTORY>Copie Mesures d'urgence. Disques 78t maison Radio-Lausanne 8802, 8803, 8804, 8805, 8806. en 5 plages; Copie Mesures d'urgence. Disques 78t maison Radio-Lausanne 8802, 8803, 8804, 8805, 8806. En 5 plages; Copie Mesures d'urgence. Disques 78t maison Radio-Lausanne 8802, 8803, 8804, 8805, 8806. En 5 plages</HISTORY><PARTICIPANTS><PARTICIPANT><NAME>Schaerer, Ren?</NAME><FUNCTION>Commentateur/trice</FUNCTION><ROLE>charg? de cours ? l'Universit? de Neuch?tel</ROLE></PARTICIPANT></PARTICIPANTS><PERSONDESCRIPTORS><PERSONDESCRIPTOR>Epicure</PERSONDESCRIPTOR></PERSONDESCRIPTORS><PRODUCTIONTYPE>Production propre</PRODUCTIONTYPE><RECORDINGDATES><RECORDINGDATE>03/10/1942 - 03/10/1942</RECORDINGDATE></RECORDINGDATES><RECORDINGPLACE>Neuch?tel</RECORDINGPLACE><SERIESTITLE>Sauvegarde d'archives</SERIESTITLE><SUMMARY>Vie d'Epicure. Ses adversaires et ses disciples. Sa morale en formules br?ves. Le bonheur r?side dans le plaisir. Comment faire durer le plaisir malgr? la douleur, la maladie, la vieillesse par le souvenir des plaisirs pass?s et par anticipation. L'?picurisme. La place d'Epicure dans l'histoire des id?es.</SUMMARY><THEMATICALDESCRIPTORS><THEMATICALDESCRIPTOR>philosophie</THEMATICALDESCRIPTOR><THEMATICALDESCRIPTOR>syst?me philosophique</THEMATICALDESCRIPTOR><THEMATICALDESCRIPTOR>bonheur</THEMATICALDESCRIPTOR></THEMATICALDESCRIPTORS><WORKFLOWSTATUS>Valid?</WORKFLOWSTATUS><ASSEMBLYSTATUS>Brut</ASSEMBLYSTATUS><FIRSTBROADCASTDATES><FIRSTBROADCASTDATE>05/01/1943 - 05/01/1943</FIRSTBROADCASTDATE></FIRSTBROADCASTDATES><LIVE>Non live</LIVE><MODULATIONTYPE>Mono</MODULATIONTYPE><PROGRAMMES><PROGRAMME>Radio Sottens</PROGRAMME></PROGRAMMES><SUBDOMAINS><SUBDOMAIN>COM</SUBDOMAIN></SUBDOMAINS><WORKDURATION>00:00:00.000</WORKDURATION><WORKDURATIONCOMPL>Non</WORKDURATIONCOMPL><SUPPORTS><SUPPORT><CLSID>{9C19C69A-A4DC-479E-94F1-61FF72CA7889}</CLSID><OID>{138DD605-F3B5-401F-A003-FF0BF2D2EE06}</OID><TITLE>Archives RSR (CDR 3947)</TITLE><ISDIGITAL>False</ISDIGITAL><SUPPORTIDS><SUPPORTID>CDR 3947</SUPPORTID></SUPPORTIDS><CATALOGUINGSTATUS>D+A total</CATALOGUINGSTATUS><SOURCE>Capri</SOURCE><UNITDURATION>00:17:06.000</UNITDURATION><UNITDURATIONCOMPL>Non</UNITDURATIONCOMPL><SIDE>01</SIDE><TRACK>01</TRACK><PHYSICALPROPERTIES><ANNOTATIONS>Non</ANNOTATIONS><LOCALISATIONS><LOCALISATION>Archives RSR S31</LOCALISATION></LOCALISATIONS><NUMBEROFCOPIES>1</NUMBEROFCOPIES><NUMBEROFSUPPORTS>0</NUMBEROFSUPPORTS><SUPPORTTYPE>CD enregistrable</SUPPORTTYPE></PHYSICALPROPERTIES></SUPPORT></SUPPORTS></DOCUMENT>,
 <DOCUMENT><CLSID>{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}</CLSID><OID>{964BAE7F-6642-4412-8256-2231828DF3B5}</OID><LOGIN/><TITLE>Le message de Claudel. Causerie de Marcel Pob?, professeur ? l'Universit? de Fribourg</TITLE><HIERARCHY OID="{964BAE7F-6642-4412-8256-2231828DF3B5}" current="*" depth="---" title="Le message de Claudel. Causerie de Marcel Pob?, professeur ? l'Universit? de Fribourg"/><SEQUENCE>1</SEQUENCE><BROADCAST>Causerie universitaire</BROADCAST><DOCUMENTTYPE>Parl?</DOCUMENTTYPE><GEOGRAPHICALDESCRIPTORS><GEOGRAPHICALDESCRIPTOR>France</GEOGRAPHICALDESCRIPTOR></GEOGRAPHICALDESCRIPTORS><HIERARCHYLEVEL>Sujet</HIERARCHYLEVEL><MODIFIEDBY>albrecjo</MODIFIEDBY><MODIFIEDON>01.06.2022 06:21:15</MODIFIEDON><NOTES>Gr?sillements</NOTES><HISTORY>Disques 78T maison Radio-Lausanne 1482X A, 1483X A, 1482X B, 1483X B</HISTORY><PARTICIPANTS><PARTICIPANT><NAME>Pob?, Marcel</NAME><FUNCTION>Conf?rencier/e</FUNCTION><ROLE>privat-docent chancelier de l'Universit? de Fribourg</ROLE></PARTICIPANT></PARTICIPANTS><PERSONDESCRIPTORS><PERSONDESCRIPTOR>Claudel, Paul</PERSONDESCRIPTOR></PERSONDESCRIPTORS><PRODUCTIONTYPE>Production propre</PRODUCTIONTYPE><RECORDINGDATES><RECORDINGDATE>23/11/1939 - 23/11/1939</RECORDINGDATE></RECORDINGDATES><RECORDINGPLACE>Fribourg</RECORDINGPLACE><RIGHTSNOTES>Memoriav</RIGHTSNOTES><RIGHTSSTATUS>Clarifi?</RIGHTSSTATUS><RIGHTSUSAGEPOSSIBILITIES><RIGHTSUSAGEPOSSIBILITY>Tous</RIGHTSUSAGEPOSSIBILITY></RIGHTSUSAGEPOSSIBILITIES><SERIESTITLE>Sauvegarde d'archives. Fribourg</SERIESTITLE><SUMMARY>Claudel s'est lui-m?me pench? sur son r?le d'?crivain. L'oeuvre n'est pas une fin en soi, mais un moyen de d?passement, au risque de contredire la th?orie de l'art pour l'art. Claudel, po?te libre prenant au s?rieux la spiritualit?. L'ordre et le sacrifice comme conditions ? la joie. </SUMMARY><THEMATICALDESCRIPTORS><THEMATICALDESCRIPTOR>litt?rature</THEMATICALDESCRIPTOR><THEMATICALDESCRIPTOR>po?sie</THEMATICALDESCRIPTOR><THEMATICALDESCRIPTOR>christianisme</THEMATICALDESCRIPTOR><THEMATICALDESCRIPTOR>courant artistique (20e)</THEMATICALDESCRIPTOR></THEMATICALDESCRIPTORS><WORKFLOWSTATUS>Valid?</WORKFLOWSTATUS><ASSEMBLYSTATUS>Brut</ASSEMBLYSTATUS><FIRSTBROADCASTDATES><FIRSTBROADCASTDATE>05/12/1939 - __/__/____</FIRSTBROADCASTDATE></FIRSTBROADCASTDATES><LIVE>Non live</LIVE><MODULATIONTYPE>Mono</MODULATIONTYPE><PROGRAMMES><PROGRAMME>Radio Sottens</PROGRAMME></PROGRAMMES><SUBDOMAINS><SUBDOMAIN>Conf?rence</SUBDOMAIN></SUBDOMAINS><WORKDURATION>00:13:01.087</WORKDURATION><WORKDURATIONCOMPL>Non</WORKDURATIONCOMPL><SUPPORTS><SUPPORT><CLSID>{9C19C69A-A4DC-479E-94F1-61FF72CA7889}</CLSID><OID>{80B686A3-704B-401D-A7B1-F47BF29CA31E}</OID><TITLE>Le message de Claudel. Causerie de Marcel Pob?, professeur ? l'Universit? de Fribourg</TITLE><ISDIGITAL>True</ISDIGITAL><FILENAME>1205742867-1482X_p_complet_wav958-SIROM{BDD1F56E-A6DE-428B-99D4-A1792628729F}.wav</FILENAME><CATALOGUINGSTATUS>D+A total</CATALOGUINGSTATUS><SOURCE>Quadriga</SOURCE><UNITDURATION>00:13:01.086</UNITDURATION><UNITDURATIONCOMPL>Non</UNITDURATIONCOMPL><PHYSICALPROPERTIES><ANNOTATIONS>Non</ANNOTATIONS><NUMBEROFCOPIES>0</NUMBEROFCOPIES><NUMBEROFSUPPORTS>0</NUMBEROFSUPPORTS></PHYSICALPROPERTIES></SUPPORT></SUPPORTS></DOCUMENT>,
 <DOCUMENT><CLSID>{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}</CLSID><OID>{87381313-87FD-4D31-AD19-8CDC08BA94DA}</OID><LOGIN/><TITLE>Le Tessin, facteur de coh?sion nationale : Causerie de Giovanni Laini, lecteur de langue fran?aise ? l'Universit? de Fribourg</TITLE><HIERARCHY OID="{87381313-87FD-4D31-AD19-8CDC08BA94DA}" current="*" depth="---" title="Le Tessin, facteur de coh?sion nationale : Causerie de Giovanni Laini, lecteur de langue fran?aise ? l'Universit? de Fribourg"/><SEQUENCE>7</SEQUENCE><BROADCAST>Causerie universitaire</BROADCAST><DOCUMENTTYPE>Parl?</DOCUMENTTYPE><GEOGRAPHICALDESCRIPTORS><GEOGRAPHICALDESCRIPTOR>Tessin</GEOGRAPHICALDESCRIPTOR><GEOGRAPHICALDESCRIPTOR>Suisse</GEOGRAPHICALDESCRIPTOR><GEOGRAPHICALDESCRIPTOR>Fribourg (ville)</GEOGRAPHICALDESCRIPTOR></GEOGRAPHICALDESCRIPTORS><HIERARCHYLEVEL>Sujet</HIERARCHYLEVEL><MODIFIEDBY>suillojo</MODIFIEDBY><MODIFIEDON>27.11.2019 10:25:59</MODIFIEDON><HISTORY>Copie Mesures d'urgence. Disques 78t maison Radio-Lausanne 1490X, 1491X. En 4 plages. Copi? sur bande A 20147; Copie Mesures d'urgence. Disques 78t maison Radio-Lausanne 1490X, 1491X. En 4 plages. Copi? sur bande A 20147</HISTORY><PARTICIPANTS><PARTICIPANT><NAME>Laini, Giovanni</NAME><FUNCTION>Conf?rencier/e</FUNCTION><ROLE>lecteur de langue fran?aise ? l'Universit? de Fribourg</ROLE></PARTICIPANT></PARTICIPANTS><PRODUCTIONTYPE>Production propre</PRODUCTIONTYPE><RECORDINGDATES><RECORDINGDATE>25/11/1939 - 25/11/1939</RECORDINGDATE></RECORDINGDATES><RECORDINGPLACE>Fribourg</RECORDINGPLACE><SERIESTITLE>Sauvegarde d'archives</SERIESTITLE><SUMMARY>Prestige d'hier et d'aujourd'hui du Tessin. Exemples du pass? au 12e et au 13e si?cle: r?voltes contre Barberousse puis contre le duc de Milan. L'enthousiasme r?publicain des Tessinois. Exemples de fid?lit? du Tessin ? la Suisse. Sa sagesse civique.</SUMMARY><THEMATICALDESCRIPTORS><THEMATICALDESCRIPTOR>guerre mondiale (deuxi?me)</THEMATICALDESCRIPTOR><THEMATICALDESCRIPTOR>patriotisme</THEMATICALDESCRIPTOR></THEMATICALDESCRIPTORS><WORKFLOWSTATUS>Valid?</WORKFLOWSTATUS><ASSEMBLYSTATUS>Brut</ASSEMBLYSTATUS><FIRSTBROADCASTDATES><FIRSTBROADCASTDATE>08/06/1940 - __/__/____</FIRSTBROADCASTDATE></FIRSTBROADCASTDATES><LIVE>Non live</LIVE><MODULATIONTYPE>Mono</MODULATIONTYPE><PROGRAMMES><PROGRAMME>Radio Sottens</PROGRAMME></PROGRAMMES><SUBDOMAINS><SUBDOMAIN>Conf?rence</SUBDOMAIN></SUBDOMAINS><WORKDURATION>00:00:00.000</WORKDURATION><WORKDURATIONCOMPL>Non</WORKDURATIONCOMPL><SUPPORTS><SUPPORT><CLSID>{9C19C69A-A4DC-479E-94F1-61FF72CA7889}</CLSID><OID>{CE61E9B1-3D3C-4260-A361-4E0240B0448B}</OID><TITLE>Archives RSR (CDR 3121)</TITLE><ISDIGITAL>False</ISDIGITAL><SUPPORTIDS><SUPPORTID>CDR 3121</SUPPORTID></SUPPORTIDS><CATALOGUINGSTATUS>D+A total</CATALOGUINGSTATUS><SOURCE>Capri</SOURCE><UNITDURATION>00:11:27.000</UNITDURATION><UNITDURATIONCOMPL>Non</UNITDURATIONCOMPL><SIDE>01</SIDE><TRACK>28</TRACK><PHYSICALPROPERTIES><ANNOTATIONS>Non</ANNOTATIONS><LOCALISATIONS><LOCALISATION>Archives RSR S31</LOCALISATION></LOCALISATIONS><NUMBEROFCOPIES>1</NUMBEROFCOPIES><NUMBEROFSUPPORTS>0</NUMBEROFSUPPORTS><SUPPORTTYPE>CD enregistrable</SUPPORTTYPE></PHYSICALPROPERTIES></SUPPORT></SUPPORTS></DOCUMENT>,

In [7]:
for child in docs[0].find_all(recursive=False):
    print(f"name: {child.name}")
    print(f"attrs: {child.attrs}")
    print(f"text: {child.get_text(strip=True)}")

name: CLSID
attrs: {}
text: {D2593F4E-C887-4E48-8982-5BD08BA4DAE0}
name: OID
attrs: {}
text: {3267F04D-657F-4DCB-BCB0-44B2B6C2682D}
name: LOGIN
attrs: {}
text:
name: TITLE
attrs: {}
text: Adolphe Dygasinski, un Kipling avant Kipling. Causerie de Edouard Cros, privat-docent ? l'Universit? de Fribourg
name: HIERARCHY
attrs: {'title': "Adolphe Dygasinski, un Kipling avant Kipling. Causerie de Edouard Cros, privat-docent ? l'Universit? de Fribourg", 'OID': '{3267F04D-657F-4DCB-BCB0-44B2B6C2682D}', 'depth': '---', 'current': '*'}
text:
name: SEQUENCE
attrs: {}
text: 1
name: BROADCAST
attrs: {}
text: Causerie universitaire
name: DOCUMENTTYPE
attrs: {}
text: Parl?
name: GEOGRAPHICALDESCRIPTORS
attrs: {}
text: Pologne
name: HIERARCHYLEVEL
attrs: {}
text: Sujet
name: MODIFIEDBY
attrs: {}
text: albrecjo
name: MODIFIEDON
attrs: {}
text: 25.05.2022 03:56:53
name: HISTORY
attrs: {}
text: Disques 78T maison Radio-Lausanne 1466X A, 1467X A, 1466X B, 1467X B
name: PARTICIPANTS
attrs: {}
text: Cros, EdouardConf?rencier/eprivat-docent ? l'Universit? de Fribourg
name: PERSONDESCRIPTORS
attrs: {}
text: Dygasinski, Adolphe
name: PRODUCTIONTYPE
attrs: {}
text: Production propre
name: RECORDINGDATES
attrs: {}
text: 20/11/1939 - 20/11/1939
name: RECORDINGPLACE
attrs: {}
text: Lausanne (Studio de Radio-Lausanne)
name: RIGHTSNOTES
attrs: {}
text: Memoriav
name: RIGHTSSTATUS
attrs: {}
text: Clarifi?
name: RIGHTSUSAGEPOSSIBILITIES
attrs: {}
text: Tous
name: SERIESTITLE
attrs: {}
text: Sauvegarde d'archives. Fribourg
name: SUMMARY
attrs: {}
text: Conf?rence sur l'oeuvre de l'?crivain polonais Dygasinsky, ? l'occasion du 100e anniversaire de sa naissance. Publiciste, conteur et traducteur, il repr?sente l'esprit positiviste de l'?poque et contribue ? la propagation des nouveaux courants d'id?es. Pr?curseur de Montessori. Romancier sensible ? la r?alit? des d?sh?rit?s des grandes villes, des paysans. Romancier animalier, il dresse le portrait psychologique des animaux de son pays natal, sans tomber dans l'anthropomorphisme. Exemple avec son portrait de la cigogne.
name: THEMATICALDESCRIPTORS
attrs: {}
text: ?crivainlitt?rature19e si?clepaysanportrait (art)cigognenaturalisme
name: WORKFLOWSTATUS
attrs: {}
text: Valid?
name: ASSEMBLYSTATUS
attrs: {}
text: Brut
name: FIRSTBROADCASTDATES
attrs: {}
text: 19/12/1939 - __/__/____
name: LIVE
attrs: {}
text: Non live
name: MODULATIONTYPE
attrs: {}
text: Mono
name: PROGRAMMES
attrs: {}
text: Radio Sottens
name: SUBDOMAINS
attrs: {}
text: Conf?rence
name: WORKDURATION
attrs: {}
text: 00:13:38.975
name: WORKDURATIONCOMPL
attrs: {}
text: Non
name: SUPPORTS
attrs: {}
text: {9C19C69A-A4DC-479E-94F1-61FF72CA7889}{4A6EE48F-FE63-41E9-A277-B3F05C91EC30}Adolphe Dygasinski, un Kipling avant Kipling. Causerie de Edouard Cros, privat-docent ? l'Universit? de FribourgTrue1211554131-1466X_complet_wav_958-SIROM{CFEC57B3-AADF-47BB-8ACF-49BE06EB6AD3}.wavD+A totalQuadriga00:13:38.974NonNon00

In [12]:
# define more intuitive names
simple_fields_renaming = {
    "CLSID": "cls_ID",
    "OID": "OID",
    "LOGIN": "login",
    "TITLE": "broadcast_episode_title",
    "SEQUENCE": "sequence", 
    "BROADCAST": "broadcast_program_name",
    "DOCUMENTTYPE": "document_type",
    "HIERARCHYLEVEL": "hierarchy_level",
    "MODIFIEDBY": "modified_by",
    "MODIFIEDON": "modified_on",
    "HISTORY": "physical_support_history",
    "PRODUCTIONTYPE": "production_type",
    "RECORDINGPLACE": "recording_place",
    "RIGHTSNOTES": "rights_notes",
    "RIGHTSSTATUS": "rights_status",
    "SERIESTITLE": "series_title",
    "SUMMARY": "content_summary",
    "WORKFLOWSTATUS": "workflow_status",
    "ASSEMBLYSTATUS": "assembly_status",
    "LIVE": "live",
    "MODULATIONTYPE": "modulation_type",
    "WORKDURATION": "work_duration",
    "WORKDURATIONCOMPL": "work_duration_compl",
}

list_fields_renaming = {
    'GEOGRAPHICALDESCRIPTORS': 'geographical_descriptors',
    'PERSONDESCRIPTORS': 'person_descriptors',
    'THEMATICALDESCRIPTORS': 'thematical_descriptors',
    'RIGHTSUSAGEPOSSIBILITIES': 'rights_usage_possibilities',
    'PROGRAMMES': 'radio_channels',
    'SUBDOMAINS': 'subdomains',
    'RECORDINGDATES': 'recording_dates',
    'FIRSTBROADCASTDATES': 'first_broadcast_dates'
}

support_keys = ['spt_clsid', 'spt_oid',
                'spt_title',
                'spt_isdigital',
                'spt_filename',
                'spt_cataloguing_status',
                'spt_source',
                'spt_unit_duration']

doc_keys = ["alias", "date_str", "stt_filename", "mp3_filenames", "stripped_OID", "exact_date", "broadcast_date"] + list(simple_fields_renaming.values()) + list(list_fields_renaming.values()) + ["supports", "spt_filenames", "participants"]

In [13]:
# Parse DOCUMENT elements into structured dictionaries
def parse_docs_in_xml(xml_doc, program, all_alias_stt, all_alias_audios, doc_keys=doc_keys, simple_fields_map=simple_fields_renaming, list_fields_map=list_fields_renaming):
    """
    Extract all DOCUMENT elements from XML into a list of dictionaries.
    Handles nested structures: PARTICIPANTS, GEOGRAPHICALDESCRIPTORS, 
    THEMATICALDESCRIPTORS, SUPPORTS, RECORDINGDATES, etc.
    """
    documents = []
    
    # Find all DOCUMENT elements
    doc_elements = xml_doc.find_all('DOCUMENT')
    skipped = 0
    
    print(f"\nStarting extracting {len(doc_elements)} documents for program {program}")
    for doc_idx, doc_elem in enumerate(doc_elements):
        doc_dict = {
            "alias": program,
            "date_str": None,
            "stt_filename": None,
            "mp3_filenames": None
        }
        
        # Extract simple text fields
        
        
        for og_field, renamed_field in simple_fields_map.items():
            elem = doc_elem.find(og_field)
            if elem:
                text = elem.get_text(strip=True)
                doc_dict[renamed_field] = text
                if og_field=='OID':
                    # the text is actually "{oid}", remove start and end brackets
                    doc_dict['stripped_OID'] = text[1:-1] if text else None
            else:
                doc_dict[renamed_field] = None
        
        if "stripped_OID" not in doc_dict or not doc_dict['stripped_OID']:
            print(f"Skipping document {doc_idx+1}/{len(doc_elements)} because it's missing an OID!!")
            skipped +=1
            continue


        stt_file = f"{doc_dict['stripped_OID']}_STT.xml"
        if stt_file not in all_alias_stt:
            stt_text_file = f"{doc_dict['stripped_OID']}_STT.txt"
            print(f"Skipping document {doc_idx+1}/{len(doc_elements)} with OID {doc_dict['OID']} because it's missing its XML file!! (stt exists: {stt_text_file in all_alias_stt})")
            skipped +=1
            continue
        else:
            doc_dict['stt_filename'] = stt_file

        # Extract PARTICIPANTS (list of dicts)
        participants = []
        for participant in doc_elem.find_all('PARTICIPANT'):
            name_elem = participant.find('NAME')
            function_elem = participant.find('FUNCTION')
            role_elem = participant.find('ROLE')
            participants.append({
                'name': name_elem.get_text(strip=True) if name_elem else None,
                'function': function_elem.get_text(strip=True) if function_elem else None,
                'role': role_elem.get_text(strip=True) if role_elem else None
            })
        if participants:
            doc_dict['participants'] = participants
        
        # Extract list fields (DESCRIPTORS, PROGRAMMES, SUBDOMAINS, etc.)
        list_fields = {
            'GEOGRAPHICALDESCRIPTORS': 'GEOGRAPHICALDESCRIPTOR',
            'PERSONDESCRIPTORS': 'PERSONDESCRIPTOR',
            'THEMATICALDESCRIPTORS': 'THEMATICALDESCRIPTOR',
            'RIGHTSUSAGEPOSSIBILITIES': 'RIGHTSUSAGEPOSSIBILITY',
            'PROGRAMMES': 'PROGRAMME',
            'SUBDOMAINS': 'SUBDOMAIN',
            'RECORDINGDATES': 'RECORDINGDATE',
            'FIRSTBROADCASTDATES': 'FIRSTBROADCASTDATE'
        }
        
        for container_name, renamed_field in list_fields_map.items():
            container = doc_elem.find(container_name)
            if container:
                doc_dict[renamed_field] = [elem.get_text(strip=True) for elem in container.find_all(list_fields[container_name])]
            else:
                # always define fields, set them to None if not defined
                doc_dict[renamed_field] = None

        date_strings = None
        broadcast_date = None
        # extract the date from first_braodcast_dates
        if doc_dict["first_broadcast_dates"]:
            date_strings = [d for rd in doc_dict["first_broadcast_dates"] for d in rd.split(" - ") if d != "__/__/____"]
            broadcast_date = True 
            
        if not date_strings and doc_dict["recording_dates"]:
            print(f"Did not find any date for doc with OID {doc_dict['OID']}. Trying to use the recording date. doc_dict: {doc_dict}")
            date_strings = [d for rd in doc_dict["recording_dates"] for d in rd.split(" - ") if d != "__/__/____" and "Avant" not in d and "Apr?s" not in d]
            broadcast_date = False

        # process the dates extracted
        if not date_strings:
            print(f"WARNING! MISSING DATE FOR DOC WITH OID {doc_dict['OID']}!! \nDocument: {doc_dict}, \noriginal: {doc_elem}")
            if doc_dict['stripped_OID'] == "5D740FA1-1A90-4878-A7E2-40C43C0F6430":
                print(f"Found and setting manually the correct date for {doc_dict['OID']}: 10/04/1989")
                doc_dict['date_str'] = "10/04/1989"
                doc_dict['exact_date'] = True
                doc_dict['broadcast_date'] = True
            #doc_dict['day'] = None
        else:
            # reformat each date and keep the earliest
            dates = []
            exact_dates = []
            for s in date_strings:
                exact = True
                if "__" in s:
                    old_s = s
                    s = s.replace("__", "01")
                    exact = False
                    print(f"The date for document with OID {doc_dict['OID']} was invalid ({old_s}) - changed it to {s}")
                if s.startswith('~'):
                    final_d = datetime.strptime(s[1:],  "%d/%m/%Y")
                else:   
                    final_d = datetime.strptime(s,  "%d/%m/%Y")
                dates.append(final_d)
                if exact:
                    exact_dates.append(final_d)
                

                    
            #dates = [datetime.strptime(s[1:] if s.startswith('~') else s, "%d/%m/%Y") for s in date_strings]
            #doc_dict['year'] = min(dates).year
            #doc_dict['month'] = min(dates).month
            #doc_dict['day'] = min(dates).day
            chosen_date = min(dates)
            doc_dict['date_str'] = chosen_date.strftime('%d/%m/%Y')
            doc_dict['exact_date'] = chosen_date in exact_dates
            doc_dict['broadcast_date'] = broadcast_date
            
        
        # Extract SUPPORTS (audio files and metadata)
        supports = []
        mp3_filenames = []

        for support in doc_elem.find_all('SUPPORT'):
            support_dict = {
                'spt_clsid': support.find('CLSID').get_text(strip=True) if support.find('CLSID') else None,
                'spt_oid': support.find('OID').get_text(strip=True) if support.find('OID') else None,
                'spt_title': support.find('TITLE').get_text(strip=True) if support.find('TITLE') else None,
                'spt_isdigital': support.find('ISDIGITAL').get_text(strip=True) if support.find('ISDIGITAL') else None,
                'spt_filename': support.find('FILENAME').get_text(strip=True) if support.find('FILENAME') else None,
                'spt_cataloguing_status': support.find('CATALOGUINGSTATUS').get_text(strip=True) if support.find('CATALOGUINGSTATUS') else None,
                'spt_source': support.find('SOURCE').get_text(strip=True) if support.find('SOURCE') else None,
                'spt_unit_duration': support.find('UNITDURATION').get_text(strip=True) if support.find('UNITDURATION') else None
            }

            if support_dict['spt_filename']:
                # remove '.wav' if it's in the filename
                spt_filename = support_dict['spt_filename'].replace('.wav', "")
                # populate the list of mp3 filenames with any mp3 file which has a matching filename
                mp3_filenames.extend([audio for audio in all_alias_audios if spt_filename in audio])

            supports.append(support_dict)

        if not supports or not mp3_filenames:
            print(f"Skipping document {doc_idx+1}/{len(doc_elements)} with OID {doc_dict['OID']} because it's missing its audio MP3 file!!")
            skipped +=1
            continue

        doc_dict['supports'] = supports
        doc_dict['spt_filenames'] = [s['spt_filename'] for s in supports]
        doc_dict['mp3_filenames'] = mp3_filenames

        # before adding to the list of docs, check it has all keys, and setting any missing one to None
        for k in doc_keys:
            if k not in doc_dict:
                doc_dict[k] = None
        
        documents.append(doc_dict)

    print(f"{program} - returning {len(documents)} documents, {skipped} were skipped due to missing necessary info.")
    
    return documents

Check that the function works correctly

In [9]:

audio_files = os.listdir(os.path.join(example_program_dir, audios_subdir))
text_files = os.listdir(os.path.join(example_program_dir, asr_subdir))

# Parse all documents from the example XML
all_documents = parse_docs_in_xml(xml_doc, example_program, text_files, audio_files)

print(f"Total documents found: {len(all_documents)}")
if all_documents:
    for idx, doc in enumerate(all_documents):
        #doc = all_documents[0]
        #print(f"\nFirst document keys: {list(doc.keys())}")
        print(f"\nTitle: {doc.get('title', 'N/A')[:80]}...")
        print(f"Broadcast program name: {doc.get('broadcast_program_name', 'N/A')}")
        print(f"Extracted boradcast date: {doc['date_str']} (year {doc['date_str'].split('/')[-1]})")
        print(f"Bradcast dates: {doc.get('first_broadcast_dates', ['N/A'])[0]}, Recording dates: {doc.get('recording_dates', ['N/A'])[0]}")
        print(f"MP3 filenames: {doc.get('mp3_filenames', ['N/A'])}")
        
        if doc['mp3_filenames']:
            for f in doc.get('mp3_filenames'):
                print(f" --> MP3 filename in audios: {f in audio_files}, OID in ASR files: {any(doc['stripped_OID'] in xml_f for xml_f in text_files)}")
        else:
            print(f"Doc {idx} has no mp3 filenames!! full doc:\n{doc}")
        #if doc.get('supports'):
        #    print(f"Audio file: {doc['supports'][0].get('filename', 'N/A')}")

Starting extracting 8 documents for program causerie_uni
Skipping document 3/8 with OID {1656BB3F-A8EF-4BF4-BE9A-20483F5665C8} because it's missing its XML file!! (stt exists: False)
Skipping document 5/8 with OID {87381313-87FD-4D31-AD19-8CDC08BA94DA} because it's missing its XML file!! (stt exists: False)
causerie_uni - returning 6 documents, 2 were skipped due to missing necessary info.
Total documents found: 6

Title: N/A...
Broadcast program name: Causerie universitaire
Extracted boradcast date: 19/12/1939 (year 1939)
Bradcast dates: 19/12/1939 - __/__/____, Recording dates: 20/11/1939 - 20/11/1939
MP3 filenames: ['3267f04d-657f-4dcb-bcb0-44b2b6c2682d_1211554131-1466X_complet_wav_958-SIROM{CFEC57B3-AADF-47BB-8ACF-49BE06EB6AD3}.mp3']
 --> MP3 filename in audios: True, OID in ASR files: True

Title: N/A...
Broadcast program name: Causerie universitaire
Extracted boradcast date: 07/01/1941 (year 1941)
Bradcast dates: 07/01/1941 - __/__/____, Recording dates: 26/11/1940 - 26/11/1940
MP3 filenames: ['c380e906-0487-4324-b232-70f6e3ab9191_1209129877-3151_p_complet_wav_958-SIROM{8357777C-7412-4674-98A8-B3AC6AB572DB}.mp3']
 --> MP3 filename in audios: True, OID in ASR files: True

Title: N/A...
Broadcast program name: Causerie universitaire
Extracted boradcast date: 05/12/1939 (year 1939)
Bradcast dates: 05/12/1939 - __/__/____, Recording dates: 23/11/1939 - 23/11/1939
MP3 filenames: ['964bae7f-6642-4412-8256-2231828df3b5_1205742867-1482X_p_complet_wav958-SIROM{BDD1F56E-A6DE-428B-99D4-A1792628729F}.mp3']
 --> MP3 filename in audios: True, OID in ASR files: True

Title: N/A...
Broadcast program name: Causerie universitaire
Extracted boradcast date: 26/03/1940 (year 1940)
Bradcast dates: 26/03/1940 - __/__/____, Recording dates: 04/11/1939 - 04/11/1939
MP3 filenames: ['7812b881-797e-4a2e-a26a-8926d073fe78_1204286700-1542X_p_complet_wav958-SIROM{A3020B9E-9A94-4DFD-B1E0-CC34FE2F13AC}.mp3']
 --> MP3 filename in audios: True, OID in ASR files: True

Title: N/A...
Broadcast program name: Causerie universitaire
Extracted boradcast date: 13/02/1940 (year 1940)
Bradcast dates: 13/02/1940 - __/__/____, Recording dates: 23/11/1939 - 23/11/1939
MP3 filenames: ['ba773a39-411f-4746-b132-44cc74c6feae_1204286698-1488X_p_complet_wav958-SIROM{649BB0B7-9038-4080-8480-BA8C06AB315C}.mp3']
 --> MP3 filename in audios: True, OID in ASR files: True

Title: N/A...
Broadcast program name: Causerie universitaire
Extracted boradcast date: 10/09/1940 (year 1940)
Bradcast dates: 10/09/1940 - __/__/____, Recording dates: 23/11/1939 - 23/11/1939
MP3 filenames: ['e24ed1ee-e680-4753-b2d9-a643b2b5051f_1204286697-1486X_p_complet_wav958-SIROM{65CACD7F-4AD0-44EF-AA62-C4EEDEC7F189}.mp3']
 --> MP3 filename in audios: True, OID in ASR files: True

In [10]:
all_documents[:5]

[{'alias': 'causerie_uni',
  'date_str': '19/12/1939',
  'mp3_filenames': ['3267f04d-657f-4dcb-bcb0-44b2b6c2682d_1211554131-1466X_complet_wav_958-SIROM{CFEC57B3-AADF-47BB-8ACF-49BE06EB6AD3}.mp3'],
  'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}',
  'OID': '{3267F04D-657F-4DCB-BCB0-44B2B6C2682D}',
  'stripped_OID': '3267F04D-657F-4DCB-BCB0-44B2B6C2682D',
  'login': '',
  'broadcast_episode_title': "Adolphe Dygasinski, un Kipling avant Kipling. Causerie de Edouard Cros, privat-docent ? l'Universit? de Fribourg",
  'sequence': '1',
  'broadcast_program_name': 'Causerie universitaire',
  'document_type': 'Parl?',
  'hierarchy_level': 'Sujet',
  'modified_by': 'albrecjo',
  'modified_on': '25.05.2022 03:56:53',
  'physical_support_history': 'Disques 78T maison Radio-Lausanne 1466X A, 1467X A, 1466X B, 1467X B',
  'production_type': 'Production propre',
  'recording_place': 'Lausanne (Studio de Radio-Lausanne)',
  'rights_notes': 'Memoriav',
  'rights_status': 'Clarifi?',
  'series_title': "Sauvegarde d'archives. Fribourg",
  'content_summary': "Conf?rence sur l'oeuvre de l'?crivain polonais Dygasinsky, ? l'occasion du 100e anniversaire de sa naissance. Publiciste, conteur et traducteur, il repr?sente l'esprit positiviste de l'?poque et contribue ? la propagation des nouveaux courants d'id?es. Pr?curseur de Montessori. Romancier sensible ? la r?alit? des d?sh?rit?s des grandes villes, des paysans. Romancier animalier, il dresse le portrait psychologique des animaux de son pays natal, sans tomber dans l'anthropomorphisme. Exemple avec son portrait de la cigogne.",
  'workflow_status': 'Valid?',
  'assembly_status': 'Brut',
  'live': 'Non live',
  'modulation_type': 'Mono',
  'work_duration': '00:13:38.975',
  'work_duration_compl': 'Non',
  'participants': [{'name': 'Cros, Edouard',
    'function': 'Conf?rencier/e',
    'role': "privat-docent ? l'Universit? de Fribourg"}],
  'geographical_descriptors': ['Pologne'],
  'person_descriptors': ['Dygasinski, Adolphe'],
  'thematical_descriptors': ['?crivain',
   'litt?rature',
   '19e si?cle',
   'paysan',
   'portrait (art)',
   'cigogne',
   'naturalisme'],
  'rights_usage_possibilities': ['Tous'],
  'radio_channels': ['Radio Sottens'],
  'subdomains': ['Conf?rence'],
  'recording_dates': ['20/11/1939 - 20/11/1939'],
  'first_broadcast_dates': ['19/12/1939 - __/__/____'],
  'supports': [{'spt_clsid': '{9C19C69A-A4DC-479E-94F1-61FF72CA7889}',
    'spt_oid': '{4A6EE48F-FE63-41E9-A277-B3F05C91EC30}',
    'spt_title': "Adolphe Dygasinski, un Kipling avant Kipling. Causerie de Edouard Cros, privat-docent ? l'Universit? de Fribourg",
    'spt_isdigital': 'True',
    'spt_filename': '1211554131-1466X_complet_wav_958-SIROM{CFEC57B3-AADF-47BB-8ACF-49BE06EB6AD3}.wav',
    'spt_cataloguing_status': 'D+A total',
    'spt_source': 'Quadriga',
    'spt_unit_duration': '00:13:38.974'}],
  'spt_filenames': ['1211554131-1466X_complet_wav_958-SIROM{CFEC57B3-AADF-47BB-8ACF-49BE06EB6AD3}.wav']},
 {'alias': 'causerie_uni',
  'date_str': '07/01/1941',
  'mp3_filenames': ['c380e906-0487-4324-b232-70f6e3ab9191_1209129877-3151_p_complet_wav_958-SIROM{8357777C-7412-4674-98A8-B3AC6AB572DB}.mp3'],
  'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}',
  'OID': '{C380E906-0487-4324-B232-70F6E3AB9191}',
  'stripped_OID': 'C380E906-0487-4324-B232-70F6E3AB9191',
  'login': '',
  'broadcast_episode_title': "Au coeur des lettres fran?aises : Georges Duhamel. Causerie de Ren? Bady, professeur ? l'Universit? de Fribourg",
  'sequence': '1',
  'broadcast_program_name': 'Causerie universitaire',
  'document_type': 'Parl?',
  'hierarchy_level': 'Sujet',
  'modified_by': 'albrecjo',
  'modified_on': '30.05.2022 08:35:49',
  'physical_support_history': 'Disques 78T maison Radio-Lausanne 3151 Ab, 3152 A, 3151 B, 3152 B, 3153, 3151 Aa (bribe)',
  'production_type': 'Production propre',
  'recording_place': 'Lausanne (Studio de Radio-Lausanne)',
  'rights_notes': 'Memoriav',
  'rights_status': 'Clarifi?',
  'series_title': "Sauvegarde d'archives. Fribourg",
  'content_summary': "Portrait de l'?crivain fran?ais. Une question traverse toute l'oeuvre de Duhamel : quels sont les pouvoirs de l'homme face ? sa destin?e? M?decin major durant la Grande Guerre et t?moin de l'h?ro?sme des soldats. La probl?matique du h?ros et du saint dans ses oeuvres. Humanisme, observation et recherche.",
  'workflow_status': 'Valid?',
  'assembly_status': 'Brut',
  'live': 'Non live',
  'modulation_type': 'Mono',
  'work_duration': '00:13:51.582',
  'work_duration_compl': 'Non',
  'participants': [{'name': 'Bady, Ren?',
    'function': 'Conf?rencier/e',
    'role': "professeur ? l'Universit? de Fribourg"}],
  'geographical_descriptors': ['France'],
  'person_descriptors': ['Duhamel, Georges'],
  'thematical_descriptors': ['litt?rature',
   'guerre mondiale (premi?re)',
   'religion et croyances',
   '?crivain'],
  'rights_usage_possibilities': ['Tous'],
  'radio_channels': ['Radio Sottens'],
  'subdomains': ['Conf?rence'],
  'recording_dates': ['26/11/1940 - 26/11/1940'],
  'first_broadcast_dates': ['07/01/1941 - __/__/____',
   '19/01/1941 - __/__/____'],
  'supports': [{'spt_clsid': '{9C19C69A-A4DC-479E-94F1-61FF72CA7889}',
    'spt_oid': '{D5EBA98B-8D5F-4CE7-AF13-6D28447B81D3}',
    'spt_title': "Au coeur des lettres fran?aises : Georges Duhamel. Causerie de Ren? Bady, professeur ? l'Universit? de Fribourg",
    'spt_isdigital': 'True',
    'spt_filename': '1209129877-3151_p_complet_wav_958-SIROM{8357777C-7412-4674-98A8-B3AC6AB572DB}.wav',
    'spt_cataloguing_status': 'D+A total',
    'spt_source': 'Quadriga',
    'spt_unit_duration': '00:13:51.582'}],
  'spt_filenames': ['1209129877-3151_p_complet_wav_958-SIROM{8357777C-7412-4674-98A8-B3AC6AB572DB}.wav']},
 {'alias': 'causerie_uni',
  'date_str': '05/12/1939',
  'mp3_filenames': ['964bae7f-6642-4412-8256-2231828df3b5_1205742867-1482X_p_complet_wav958-SIROM{BDD1F56E-A6DE-428B-99D4-A1792628729F}.mp3'],
  'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}',
  'OID': '{964BAE7F-6642-4412-8256-2231828DF3B5}',
  'stripped_OID': '964BAE7F-6642-4412-8256-2231828DF3B5',
  'login': '',
  'broadcast_episode_title': "Le message de Claudel. Causerie de Marcel Pob?, professeur ? l'Universit? de Fribourg",
  'sequence': '1',
  'broadcast_program_name': 'Causerie universitaire',
  'document_type': 'Parl?',
  'hierarchy_level': 'Sujet',
  'modified_by': 'albrecjo',
  'modified_on': '01.06.2022 06:21:15',
  'physical_support_history': 'Disques 78T maison Radio-Lausanne 1482X A, 1483X A, 1482X B, 1483X B',
  'production_type': 'Production propre',
  'recording_place': 'Fribourg',
  'rights_notes': 'Memoriav',
  'rights_status': 'Clarifi?',
  'series_title': "Sauvegarde d'archives. Fribourg",
  'content_summary': "Claudel s'est lui-m?me pench? sur son r?le d'?crivain. L'oeuvre n'est pas une fin en soi, mais un moyen de d?passement, au risque de contredire la th?orie de l'art pour l'art. Claudel, po?te libre prenant au s?rieux la spiritualit?. L'ordre et le sacrifice comme conditions ? la joie.",
  'workflow_status': 'Valid?',
  'assembly_status': 'Brut',
  'live': 'Non live',
  'modulation_type': 'Mono',
  'work_duration': '00:13:01.087',
  'work_duration_compl': 'Non',
  'participants': [{'name': 'Pob?, Marcel',
    'function': 'Conf?rencier/e',
    'role': "privat-docent chancelier de l'Universit? de Fribourg"}],
  'geographical_descriptors': ['France'],
  'person_descriptors': ['Claudel, Paul'],
  'thematical_descriptors': ['litt?rature',
   'po?sie',
   'christianisme',
   'courant artistique (20e)'],
  'rights_usage_possibilities': ['Tous'],
  'radio_channels': ['Radio Sottens'],
  'subdomains': ['Conf?rence'],
  'recording_dates': ['23/11/1939 - 23/11/1939'],
  'first_broadcast_dates': ['05/12/1939 - __/__/____'],
  'supports': [{'spt_clsid': '{9C19C69A-A4DC-479E-94F1-61FF72CA7889}',
    'spt_oid': '{80B686A3-704B-401D-A7B1-F47BF29CA31E}',
    'spt_title': "Le message de Claudel. Causerie de Marcel Pob?, professeur ? l'Universit? de Fribourg",
    'spt_isdigital': 'True',
    'spt_filename': '1205742867-1482X_p_complet_wav958-SIROM{BDD1F56E-A6DE-428B-99D4-A1792628729F}.wav',
    'spt_cataloguing_status': 'D+A total',
    'spt_source': 'Quadriga',
    'spt_unit_duration': '00:13:01.086'}],
  'spt_filenames': ['1205742867-1482X_p_complet_wav958-SIROM{BDD1F56E-A6DE-428B-99D4-A1792628729F}.wav']},
 {'alias': 'causerie_uni',
  'date_str': '26/03/1940',
  'mp3_filenames': ['7812b881-797e-4a2e-a26a-8926d073fe78_1204286700-1542X_p_complet_wav958-SIROM{A3020B9E-9A94-4DFD-B1E0-CC34FE2F13AC}.mp3'],
  'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}',
  'OID': '{7812B881-797E-4A2E-A26A-8926D073FE78}',
  'stripped_OID': '7812B881-797E-4A2E-A26A-8926D073FE78',
  'login': '',
  'broadcast_episode_title': "L'enseignement de l'histoire. Causerie de Gonzague de Reynold",
  'sequence': '1',
  'broadcast_program_name': 'Causerie universitaire',
  'document_type': 'Parl?',
  'hierarchy_level': 'Sujet',
  'modified_by': 'albrecjo',
  'modified_on': '05.10.2016 08:34:54',
  'physical_support_history': 'Disques 78T maison Radio-Lausanne 1542X A, 1543X A, 1542X B, 1543X B',
  'production_type': 'Production propre',
  'recording_place': 'Lausanne (Studio de Radio-Lausanne)',
  'rights_notes': 'Memoriav. IMVOCS',
  'rights_status': 'Clarifi?',
  'series_title': "Sauvegarde d'archives. Fribourg",
  'content_summary': "Cr?ation ? l'Universit? de Fribourg de la Chaire d'histoire de la civilisation moderne. L'enseignement de l'histoire a pour but d'initier les auditeurs ? la vie, de leur donner les connaissances et la compr?hension de l'Europe actuelle et tragique. L'?ducation de la pens?e doit d?velopper le sens critique en multipliant les termes de comparaison. La m?connaissance de l'histoire comme sympt?me de l'inculture d'une grande partie de la jeunesse. Devenir contemporain du pass? pour mieux le comprendre et appr?hender le pr?sent ? la lumi?re des origines.",
  'workflow_status': 'Valid?',
  'assembly_status': 'Brut',
  'live': 'Non live',
  'modulation_type': 'Mono',
  'work_duration': '00:14:16.308',
  'work_duration_compl': 'Non',
  'participants': [{'name': 'Reynold, Gonzague de',
    'function': 'Conf?rencier/e',
    'role': '?crivain'}],
  'geographical_descriptors': ['Fribourg (canton)', 'Europe'],
  'person_descriptors': None,
  'thematical_descriptors': ['universit?',
   'histoire',
   "enseignement de l'histoire",
   'temps (philosophie)'],
  'rights_usage_possibilities': ['Tous'],
  'radio_channels': ['Radio Sottens'],
  'subdomains': ['Conf?rence'],
  'recording_dates': ['04/11/1939 - 04/11/1939'],
  'first_broadcast_dates': ['26/03/1940 - __/__/____'],
  'supports': [{'spt_clsid': '{9C19C69A-A4DC-479E-94F1-61FF72CA7889}',
    'spt_oid': '{DA464B24-8E68-4FFF-B529-4641FED17BAB}',
    'spt_title': "L'enseignement de l'histoire. Causerie de Gonzague de Reynold",
    'spt_isdigital': 'True',
    'spt_filename': '1204286700-1542X_p_complet_wav958-SIROM{A3020B9E-9A94-4DFD-B1E0-CC34FE2F13AC}.wav',
    'spt_cataloguing_status': 'D+A total',
    'spt_source': 'Quadriga',
    'spt_unit_duration': '00:14:16.308'}],
  'spt_filenames': ['1204286700-1542X_p_complet_wav958-SIROM{A3020B9E-9A94-4DFD-B1E0-CC34FE2F13AC}.wav']},
 {'alias': 'causerie_uni',
  'date_str': '13/02/1940',
  'mp3_filenames': ['ba773a39-411f-4746-b132-44cc74c6feae_1204286698-1488X_p_complet_wav958-SIROM{649BB0B7-9038-4080-8480-BA8C06AB315C}.mp3'],
  'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}',
  'OID': '{BA773A39-411F-4746-B132-44CC74C6FEAE}',
  'stripped_OID': 'BA773A39-411F-4746-B132-44CC74C6FEAE',
  'login': '',
  'broadcast_episode_title': "L'introduction du code p?nal suisse et les attributions des cantons. Causerie d' Alfred von Overbeck, professeur de droit ? l'Universit? de Fribourg",
  'sequence': '1',
  'broadcast_program_name': 'Causerie universitaire',
  'document_type': 'Parl?',
  'hierarchy_level': 'Sujet',
  'modified_by': 'albrecjo',
  'modified_on': '30.05.2022 17:39:11',
  'physical_support_history': 'Disques 78T maison Radio-Lausanne 1488X A, 1489X A, 1488X B, 1489X B',
  'production_type': 'Production propre',
  'recording_place': 'Fribourg',
  'rights_notes': 'Memoriav',
  'rights_status': 'Clarifi?',
  'series_title': "Sauvegarde d'archives. Fribourg",
  'content_summary': "Le nouveau code p?nal suisse s'occupe des lois importantes. Les cantons devront l?gif?rer sur les contraventions de police et les sanctions mineures. R?le important des tribunaux cantonaux et libert? d'appr?ciation des juges, qui pourront rester fid?les aux traditions r?gionales. R?habilitation et droit de gr?ce.",
  'workflow_status': 'Valid?',
  'assembly_status': 'Brut',
  'live': 'Non live',
  'modulation_type': 'Mono',
  'work_duration': '00:14:04.234',
  'work_duration_compl': 'Non',
  'participants': [{'name': 'Overbeck, Alfred von',
    'function': 'Conf?rencier/e',
    'role': 'professeur de droit, Universit? de Fribourg'}],
  'geographical_descriptors': ['Suisse'],
  'person_descriptors': None,
  'thematical_descriptors': ['canton',
   'f?d?ralisme',
   'l?gislation',
   'droit p?nal',
   'juridiction p?nale',
   'juge'],
  'rights_usage_possibilities': ['Tous'],
  'radio_channels': ['Radio Sottens'],
  'subdomains': ['Conf?rence'],
  'recording_dates': ['23/11/1939 - 23/11/1939'],
  'first_broadcast_dates': ['13/02/1940 - __/__/____'],
  'supports': [{'spt_clsid': '{9C19C69A-A4DC-479E-94F1-61FF72CA7889}',
    'spt_oid': '{7D2B9FC3-B90C-4626-8995-C7C418B36104}',
    'spt_title': "L'introduction du code p?nal suisse et les attributions des cantons. Causerie d' Alfred von Overbeck, professeur de droit ? l'Universit? de Fribourg",
    'spt_isdigital': 'True',
    'spt_filename': '1204286698-1488X_p_complet_wav958-SIROM{649BB0B7-9038-4080-8480-BA8C06AB315C}.wav',
    'spt_cataloguing_status': 'D+A total',
    'spt_source': 'Quadriga',
    'spt_unit_duration': '00:14:04.233'}],
  'spt_filenames': ['1204286698-1488X_p_complet_wav958-SIROM{649BB0B7-9038-4080-8480-BA8C06AB315C}.wav']}]

In [171]:
doc_keys

dict_keys(['alias', 'date_str', 'mp3_filenames', 'cls_ID', 'OID', 'stripped_OID', 'login', 'broadcast_episode_title', 'sequence', 'broadcast_program_name', 'document_type', 'hierarchy_level', 'modified_by', 'modified_on', 'physical_support_history', 'production_type', 'recording_place', 'rights_notes', 'rights_status', 'series_title', 'content_summary', 'workflow_status', 'assembly_status', 'live', 'modilation_type', 'work_duration', 'work_duration_compl', 'participants', 'geographical_descriptors', 'person_descriptors', 'thematical_descriptors', 'rights_uage_possibilities', 'radio_channels', 'subdomains', 'recording_dates', 'first_broadcast_dates', 'supports', 'spt_filenames'])

In [11]:
doc_keys = all_documents[0].keys()

out_csv_name = "/home/piconti/impresso-text-acquisition/text_preparation/data/sample_data/RTS/debug_metadata.csv"
with open(out_csv_name, "w", newline='') as output_file:
    dict_writer = csv.DictWriter(output_file, doc_keys)
    dict_writer.writeheader()
    dict_writer.writerows(all_documents)

This works and yields the desired set of metadata. 

## Aggregating all the programs' metadata into a single file

Now we need to write an orchestrator function that opens and processes the XML documents for each provider, and stores the info in a dict or a dataframe, also extracting the first braodcast date to help with the creation of the issue index file

In [7]:
all_program_aliases = sorted([p for p in os.listdir(base_dir) if "DS_Store" not in p and "$RECYCLE" not in p and "System" not in p])
print(f"Found {len(all_program_aliases)} Radio programs: {all_program_aliases}")

Found 47 Radio programs: ['ana_media', 'bigbang', 'canal_euro', 'causerie_uni', 'chron_instit', 'chron_unesco', 'courrier_cr', 'culte', 'dos_sci', 'ecoute_paix', 'enquest', 'forum', 'forum_lau', 'geneve_info', 'hist_ondes', 'infopile', 'inst_monde', 'j13h', 'j13h2', 'j_mat', 'j_midi', 'j_nuit', 'j_soir', 'mag_eco', 'mag_info', 'mag_sci1', 'mag_sci2', 'mag_tv1', 'mag_tv2', 'mem_ondes', 'min_oecu', 'miroir_monde', 'miroir_temps', 'monde_ant', 'monde_sem', 'nickel', 'nu_parle', 'ombres_eco', 'paraboles', 'paris_parle', 'parole_prem', 'petitdej', 'suisse_euro', 'terre_ciel', 'trib_prem', 'vie_monde', 'vie_va']

In [8]:
out_csv_name = "/home/piconti/impresso-text-acquisition/text_preparation/data/sample_data/RTS/programs_metadata.rts.csv"

In [184]:
all_program_aliases.index("mem_ondes")

29

In [29]:
already_done = all_program_aliases[:all_program_aliases.index("mem_ondes")+1]
already_done = []

In [27]:
#already_done = all_program_aliases[:all_program_aliases.index("mem_ondes")+1]
#already_done = []
already_done

[]

In [30]:
all_docs = []
all_docs_dict = {}
#doc_keys = None

for p_idx, p_alias in tqdm(enumerate(all_program_aliases)):

    if p_alias in already_done:
        print(f"\n{p_alias} is already done, skipping!")
        continue
    
    # first find all the metadata xml docs
    program_dir = os.path.join(base_dir, p_alias)
    metadata_files = [os.path.join(program_dir,f) for f in os.listdir(program_dir) if f.startswith(metadata_file_start)]
    
    all_audios_for_alias = os.listdir(os.path.join(program_dir,'audio'))
    all_stt_for_alias = os.listdir(os.path.join(program_dir,'stt'))

    print(f"\nPROCESSING PROGRAM {p_alias} ({p_idx+1}/{len(all_program_aliases)}) - {len(metadata_files)} files:")

    program_docs = []
    for xml_doc_path in tqdm(metadata_files):
        with open(xml_doc_path, "r", encoding="utf-8") as f:
            raw_xml = f.read()

        program_docs.extend(parse_docs_in_xml(BeautifulSoup(raw_xml, "xml"), p_alias, all_stt_for_alias, all_audios_for_alias, doc_keys))
    
    all_docs.extend(program_docs)
    all_docs_dict[p_alias] = program_docs

    # Save the current list of documents to save the progress
    #if not doc_keys:
    #    doc_keys = all_docs[0].keys()

    print(f" --> Adding {len(program_docs)} to the out csv for {p_alias}")
    with open(out_csv_name, "a", newline='') as output_file:
        dict_writer = csv.DictWriter(output_file, doc_keys)
        if not already_done:
            dict_writer.writeheader()
        dict_writer.writerows(program_docs)

    already_done.append(p_alias)

0it [00:00, ?it/s]

PROCESSING PROGRAM ana_media (1/47) - 1 files:

100%|██████████| 1/1 [00:00<00:00, 15.58it/s]

Starting extracting 6 documents for program ana_media
ana_media - returning 6 documents, 0 were skipped due to missing necessary info.
 --> Adding 6 to the out csv for ana_media

PROCESSING PROGRAM bigbang (2/47) - 1 files:

100%|██████████| 1/1 [00:00<00:00,  3.70it/s]
2it [00:00,  5.57it/s]

Starting extracting 40 documents for program bigbang
Skipping document 1/40 with OID {06660C0A-1C9C-4EEB-B9F0-9DD8977CA087} because it's missing its XML file!! (stt exists: False)
Skipping document 4/40 with OID {781626D5-C9EA-41F0-B495-42812C3C3F3F} because it's missing its XML file!! (stt exists: False)
Skipping document 6/40 with OID {42FA7346-699C-4F81-A4EF-0415C88960CD} because it's missing its XML file!! (stt exists: False)
Skipping document 9/40 with OID {D34C4835-E7BB-4C5A-9C3A-DE295A646F37} because it's missing its XML file!! (stt exists: False)
Skipping document 10/40 with OID {DB2CEE23-A884-42FD-94D5-2806D2A2553F} because it's missing its XML file!! (stt exists: False)
Skipping document 12/40 with OID {276678AF-E2C5-4E28-B471-08ABDBFF2789} because it's missing its XML file!! (stt exists: False)
Skipping document 14/40 with OID {797ED203-EDDC-4DBB-B3D9-B316EC0C9C43} because it's missing its XML file!! (stt exists: False)
Skipping document 16/40 with OID {64B8E4FD-527A-4769-9E44-3205B4DE9684} because it's missing its XML file!! (stt exists: False)
Skipping document 17/40 with OID {E4CDF9B4-6325-4B80-9500-E8D6F8AD5A7B} because it's missing its XML file!! (stt exists: False)
Skipping document 19/40 with OID {107B1A20-4B2C-4E53-BE6E-9DB7BBA4AA48} because it's missing its XML file!! (stt exists: False)
Skipping document 21/40 with OID {936AAB2D-876F-402F-B92C-E39010C05E39} because it's missing its XML file!! (stt exists: False)
Skipping document 22/40 with OID {3EDD2E59-DA02-4C75-8F5D-6E5CC8D36D61} because it's missing its XML file!! (stt exists: False)
Skipping document 23/40 with OID {2CCEEE02-3D31-4573-80B1-98F663C37C2F} because it's missing its XML file!! (stt exists: False)
Skipping document 25/40 with OID {93BA7017-B7E4-4B12-B613-BD78A7475E0B} because it's missing its XML file!! (stt exists: False)
Skipping document 26/40 with OID {263DBC08-7279-4374-992A-B91D2AC22FB6} because it's missing its XML file!! (stt exists: False)
Skipping document 27/40 with OID {4F845A88-5D2F-41C7-8883-CCA694E568DC} because it's missing its XML file!! (stt exists: False)
Skipping document 29/40 with OID {B86B5273-7160-411E-896E-F3DC15A20D72} because it's missing its XML file!! (stt exists: False)
Skipping document 31/40 with OID {F646ABE4-84EA-402C-A3B2-D0E1DEE3DEE9} because it's missing its XML file!! (stt exists: False)
Skipping document 32/40 with OID {3AACF4DD-C590-4BA4-8E12-FB0BB76D5EB9} because it's missing its XML file!! (stt exists: False)
Skipping document 33/40 with OID {C8F46112-44A2-43DD-BB55-A7A568F441A9} because it's missing its XML file!! (stt exists: False)
Skipping document 34/40 with OID {3ECD2EA2-82DA-4669-97FF-F33F50106E30} because it's missing its XML file!! (stt exists: False)
Skipping document 36/40 with OID {590A36B6-D3DB-418E-ADBA-BC5A8CA16989} because it's missing its XML file!! (stt exists: False)
Skipping document 37/40 with OID {664258F8-B4B0-44CC-AAA8-04D256191FA2} because it's missing its XML file!! (stt exists: False)
Skipping document 38/40 with OID {3BE4F7EB-FB53-455E-8E37-32F05B63657C} because it's missing its XML file!! (stt exists: False)
Skipping document 40/40 with OID {DAA46A2F-D586-4D41-97A4-D8CFFD31A739} because it's missing its XML file!! (stt exists: False)
bigbang - returning 15 documents, 25 were skipped due to missing necessary info.
 --> Adding 15 to the out csv for bigbang

PROCESSING PROGRAM canal_euro (3/47) - 1 files:

Starting extracting 51 documents for program canal_euro

100%|██████████| 1/1 [00:00<00:00,  5.34it/s]
3it [00:00,  5.25it/s]

WARNING! MISSING DATE FOR DOC WITH OID {5D740FA1-1A90-4878-A7E2-40C43C0F6430}!!
Document: {'alias': 'canal_euro', 'date_str': None, 'stt_filename': '5D740FA1-1A90-4878-A7E2-40C43C0F6430_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{5D740FA1-1A90-4878-A7E2-40C43C0F6430}', 'stripped_OID': '5D740FA1-1A90-4878-A7E2-40C43C0F6430', 'login': '', 'broadcast_episode_title': "Canal Europe (37/50). L'audiovisuel et le march? unique de l'Europe des Douze", 'sequence': '1', 'broadcast_program_name': 'Canal Europe', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'AQT (NumA)', 'modified_on': '15.07.2022 09:23:54', 'physical_support_history': "Cote d'origine : A 21376Resp. RSR : AQTLot : Caisse 2008Voir feuille d'accomp.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': "Participant: inte:Lhoest, Holde;  inte:Schwartz, Ivo;  inte:Cascino, Antonio;  inte:Riehl, Fr?d?ric; Que fera la Suisse dans un domaine appel? ? se d?velopper rapidement ? Y aura-t-il une sorte d'int?gration ? froid, faisant de la Suisse un Etat associ? ? la Communaut? europ?enne ?", 'workflow_status': 'Accept?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Schenker, Ren?', 'function': 'Interview?/e', 'role': None}, {'name': 'Vouillamoz, Raymond', 'function': 'Interview?/e', 'role': None}, {'name': 'Riva, Antonio', 'function': 'Interview?/e', 'role': None}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': None, 'recording_dates': None, 'first_broadcast_dates': None},
original: <DOCUMENT><CLSID>{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}</CLSID><OID>{5D740FA1-1A90-4878-A7E2-40C43C0F6430}</OID><LOGIN/><TITLE>Canal Europe (37/50). L'audiovisuel et le march? unique de l'Europe des Douze</TITLE><HIERARCHY OID="{5D740FA1-1A90-4878-A7E2-40C43C0F6430}" current="*" depth="---" title="Canal Europe (37/50). L'audiovisuel et le march? unique de l'Europe des Douze"/><SEQUENCE>1</SEQUENCE><BROADCAST>Canal Europe</BROADCAST><DOCUMENTTYPE>Parl?</DOCUMENTTYPE><HIERARCHYLEVEL>Sujet</HIERARCHYLEVEL><MODIFIEDBY>AQT (NumA)</MODIFIEDBY><MODIFIEDON>15.07.2022 09:23:54</MODIFIEDON><NOTES>Emission 37/49. Fait partie du Journal du soir</NOTES><HISTORY>Cote d'origine : A 21376Resp. RSR : AQTLot : Caisse 2008Voir feuille d'accomp.</HISTORY><PARTICIPANTS><PARTICIPANT><NAME>Schenker, Ren?</NAME><FUNCTION>Interview?/e</FUNCTION></PARTICIPANT><PARTICIPANT><NAME>Vouillamoz, Raymond</NAME><FUNCTION>Interview?/e</FUNCTION></PARTICIPANT><PARTICIPANT><NAME>Riva, Antonio</NAME><FUNCTION>Interview?/e</FUNCTION></PARTICIPANT></PARTICIPANTS><PRODUCTIONTYPE>Production propre</PRODUCTIONTYPE><RIGHTSSTATUS>Clarifi?</RIGHTSSTATUS><RIGHTSUSAGEPOSSIBILITIES><RIGHTSUSAGEPOSSIBILITY>Tous</RIGHTSUSAGEPOSSIBILITY></RIGHTSUSAGEPOSSIBILITIES><SERIESTITLE>Sauvegarde d'archives</SERIESTITLE><SUMMARY>Participant: inte:Lhoest, Holde;  inte:Schwartz, Ivo;  inte:Cascino, Antonio;  inte:Riehl, Fr?d?ric; Que fera la Suisse dans un domaine appel? ? se d?velopper rapidement ? Y aura-t-il une sorte d'int?gration ? froid, faisant de la Suisse un Etat associ? ? la Communaut? europ?enne ?</SUMMARY><WORKFLOWSTATUS>Accept?</WORKFLOWSTATUS><ANNOUNCEMENT>Indicatif</ANNOUNCEMENT><ASSEMBLYSTATUS>Mont?</ASSEMBLYSTATUS><LIVE>Non live</LIVE><MODULATIONTYPE>Mono</MODULATIONTYPE><WORKDURATION>00:00:00.000</WORKDURATION><WORKDURATIONCOMPL>Non</WORKDURATIONCOMPL><SUPPORTS><SUPPORT><CLSID>{9C19C69A-A4DC-479E-94F1-61FF72CA7889}</CLSID><OID>{330CBB4D-035B-4F03-9230-C0623D3B55DE}</OID><TITLE>L'audiovisuel et le march? unique de l'Europe des Douze</TITLE><ISDIGITAL>True</ISDIGITAL><FILENAME>A21376{DAB6B690-226F-48F0-8EBD-3FB47C6ED210}.wav</FILENAME><ACQUISITIONDATES><ACQUISITIONDATE>19/09/2008</ACQUISITIONDATE></ACQUISITIONDATES><BRAND>Enr. RSR</BRAND><CATALOGUINGSTATUS>Transitoire</CATALOGUINGSTATUS><SOURCE>NumA</SOURCE><UNITDURATION>00:26:42.141</UNITDURATION><UNITDURATIONCOMPL>Non</UNITDURATIONCOMPL><PHYSICALPROPERTIES><ANNOTATIONS>Non</ANNOTATIONS><NUMBEROFCOPIES>0</NUMBEROFCOPIES><NUMBEROFSUPPORTS>0</NUMBEROFSUPPORTS></PHYSICALPROPERTIES></SUPPORT></SUPPORTS></DOCUMENT>
Found and setting manually the correct date for {5D740FA1-1A90-4878-A7E2-40C43C0F6430}: 10/04/1989
canal_euro - returning 51 documents, 0 were skipped due to missing necessary info.
 --> Adding 51 to the out csv for canal_euro

PROCESSING PROGRAM causerie_uni (4/47) - 2 files:

100%|██████████| 2/2 [00:00<00:00, 33.82it/s]

Starting extracting 8 documents for program causerie_uni
Skipping document 3/8 with OID {1656BB3F-A8EF-4BF4-BE9A-20483F5665C8} because it's missing its XML file!! (stt exists: False)
Skipping document 5/8 with OID {87381313-87FD-4D31-AD19-8CDC08BA94DA} because it's missing its XML file!! (stt exists: False)
causerie_uni - returning 6 documents, 2 were skipped due to missing necessary info.

Starting extracting 7 documents for program causerie_uni
Skipping document 7/7 with OID {D8092E5C-57F3-4BFF-98B8-F3C9380FD7E9} because it's missing its XML file!! (stt exists: False)
causerie_uni - returning 6 documents, 1 were skipped due to missing necessary info.
 --> Adding 12 to the out csv for causerie_uni

PROCESSING PROGRAM chron_instit (5/47) - 1 files:

Starting extracting 236 documents for program chron_instit
Skipping document 1/236 with OID {36993958-CC36-4058-B41C-717ACB601DED} because it's missing its XML file!! (stt exists: False)
Skipping document 2/236 with OID {C1166A0E-3B4B-4554-915E-F1C8AB56BB61} because it's missing its XML file!! (stt exists: False)
The date for document with OID {9B17EFE3-9A57-4C73-B3BE-31A0B7CD294A} was invalid (__/06/1949) - changed it to 01/06/1949
Skipping document 4/236 with OID {D187EB9A-1679-49B1-8DDF-B9CBCC830B38} because it's missing its XML file!! (stt exists: False)
Skipping document 5/236 with OID {93393999-811C-4806-8E45-9DDA258EA67A} because it's missing its XML file!! (stt exists: False)
Skipping document 6/236 with OID {826ACB35-FE97-45AD-ABA4-5E183AD09A91} because it's missing its XML file!! (stt exists: False)
Skipping document 7/236 with OID {79E28712-6F3F-41FD-8444-F259E79BF4BD} because it's missing its XML file!! (stt exists: False)
Skipping document 8/236 with OID {F796BD61-4663-4316-87B6-F8CD788CDD13} because it's missing its XML file!! (stt exists: False)
Skipping document 9/236 with OID {472D0ED7-0CBE-4F1F-A270-466AE1D65035} because it's missing its XML file!! (stt exists: False)
Skipping document 10/236 with OID {1BB7BC8C-EED7-4C04-97AC-C1659A4AE0CE} because it's missing its XML file!! (stt exists: False)
Skipping document 11/236 with OID {15899C10-E3ED-4DC2-87AE-5E1C918C0C60} because it's missing its XML file!! (stt exists: False)
Skipping document 12/236 with OID {BA4DC502-862D-458A-88CA-20C4DFB0AD93} because it's missing its XML file!! (stt exists: False)
Skipping document 13/236 with OID {F8997687-B913-490F-9BF9-5309D4ECE39F} because it's missing its XML file!! (stt exists: False)
Skipping document 14/236 with OID {9AC60CB8-8A74-490B-A1EF-230BDBC5D309} because it's missing its XML file!! (stt exists: False)
Skipping document 15/236 with OID {1E3BCD20-C5D5-4915-8AC0-1E818DA68889} because it's missing its XML file!! (stt exists: False)
Skipping document 16/236 with OID {0356177A-E03D-48CE-9481-7A732BA806E0} because it's missing its XML file!! (stt exists: False)
Skipping document 17/236 with OID {0D40E781-F000-4889-8BD6-6C3F06A9E509} because it's missing its XML file!! (stt exists: False)
Skipping document 18/236 with OID {5C08D6F1-EA30-410A-8013-7C8A08021366} because it's missing its XML file!! (stt exists: False)
Skipping document 19/236 with OID {583B98B3-2188-40E6-B396-4DF56030F129} because it's missing its XML file!! (stt exists: False)
Skipping document 20/236 with OID {38A47037-4F98-4F52-A70A-44A811185BAC} because it's missing its XML file!! (stt exists: False)
Skipping document 21/236 with OID {2EE5FE2B-68A5-41A0-A8A5-E816479935D5} because it's missing its XML file!! (stt exists: False)
Skipping document 22/236 with OID {D52B90BC-DC85-4BAB-A3EE-D35FCB653250} because it's missing its XML file!! (stt exists: False)
Skipping document 23/236 with OID {B1C1BD2E-6AC2-4941-9ECA-2C357D59D083} because it's missing its XML file!! (stt exists: False)
Skipping document 24/236 with OID {710B3286-22BC-4267-95FA-FDA7A281A092} because it's missing its XML file!! (stt exists: False)
Skipping document 25/236 with OID {E6E4C041-3B41-4BEE-A001-EFA395CA92C6} because it's missing its XML file!! (stt exists: False)
Skipping document 26/236 with OID {681C2BB9-FBDA-4E0A-9A51-CC8D0CC315AF} because it's missing its XML file!! (stt exists: False)
Skipping document 27/236 with OID {A2B0DA05-7781-4701-A414-F5532D0D8BFF} because it's missing its XML file!! (stt exists: False)
Skipping document 28/236 with OID {D56100D9-04FE-49E4-9EF8-C6A76DC21283} because it's missing its XML file!! (stt exists: False)
Skipping document 29/236 with OID {8CE1DC24-1F17-4748-A909-404212B47279} because it's missing its XML file!! (stt exists: False)
Skipping document 30/236 with OID {365AD6C3-C424-4C48-B660-BE050333E6BA} because it's missing its XML file!! (stt exists: False)
Skipping document 31/236 with OID {BDC1A8F6-43D0-4679-8315-7E75FE67B68F} because it's missing its XML file!! (stt exists: False)
Skipping document 32/236 with OID {ECFE0666-568A-467B-9325-B1A9E3098919} because it's missing its XML file!! (stt exists: False)
Skipping document 33/236 with OID {FE43E8C3-0332-463F-B483-E6EC776A25FB} because it's missing its XML file!! (stt exists: False)
The date for document with OID {49A79614-53C8-47CA-8FBF-8725441E6123} was invalid (~__/04/1948) - changed it to ~01/04/1948
The date for document with OID {49A79614-53C8-47CA-8FBF-8725441E6123} was invalid (~__/04/1948) - changed it to ~01/04/1948
Skipping document 35/236 with OID {93C92D34-ED94-483A-9DE5-0623928F3B28} because it's missing its XML file!! (stt exists: False)
Skipping document 36/236 with OID {8196BC3C-A76F-4C98-8615-4BDBA6A71D26} because it's missing its XML file!! (stt exists: False)
Skipping document 37/236 with OID {AA179BE7-EF68-431F-8823-4915A7C57894} because it's missing its XML file!! (stt exists: False)
The date for document with OID {8F529F10-90E4-404B-B986-977AF1C9F8DC} was invalid (__/08/1946) - changed it to 01/08/1946
Skipping document 39/236 with OID {8DEE8359-EC30-42C3-82D2-2ADF873267EB} because it's missing its XML file!! (stt exists: False)
Skipping document 40/236 with OID {0BE46818-134D-4601-A54A-A22242C491C9} because it's missing its XML file!! (stt exists: False)
Skipping document 41/236 with OID {CDF752BD-C9B7-4248-8FE5-C506E3330BF2} because it's missing its XML file!! (stt exists: False)
Skipping document 42/236 with OID {4820A74D-3769-442E-8390-EC72456ACEFA} because it's missing its XML file!! (stt exists: False)
Skipping document 43/236 with OID {1ABBD5DD-57EC-4DE1-B0D8-6BE048140C45} because it's missing its XML file!! (stt exists: False)
Skipping document 44/236 with OID {310DBABE-8952-4432-823F-73CBFED00169} because it's missing its XML file!! (stt exists: False)
Skipping document 45/236 with OID {6573406B-9B9D-433C-B590-4D866A2F2895} because it's missing its XML file!! (stt exists: False)
Skipping document 46/236 with OID {30C73F38-C18A-4C18-83E7-4F2C0DD39647} because it's missing its XML file!! (stt exists: False)
Skipping document 47/236 with OID {3F35D191-EC0C-45ED-AE04-7168FFB42DA1} because it's missing its XML file!! (stt exists: False)
Skipping document 48/236 with OID {2D20411A-861D-4B4F-AF21-E55025F0F4C7} because it's missing its XML file!! (stt exists: False)
Skipping document 49/236 with OID {F6BFCF2F-2F52-46DE-9B54-724899930B09} because it's missing its XML file!! (stt exists: False)
Skipping document 50/236 with OID {76B9A7EC-D42E-46F3-A53E-961D8651FD22} because it's missing its XML file!! (stt exists: False)
Skipping document 51/236 with OID {6C961B8F-B93C-4F89-B604-253B2D2D17CB} because it's missing its XML file!! (stt exists: False)
Skipping document 52/236 with OID {B4F87362-40E9-4B80-B565-506778BC7528} because it's missing its XML file!! (stt exists: False)
Skipping document 53/236 with OID {CB47030D-468F-4734-BE9D-4F795F3556D8} because it's missing its XML file!! (stt exists: False)
Skipping document 54/236 with OID {44B505CA-567E-48FE-BB7F-6E7C22A25BEE} because it's missing its XML file!! (stt exists: False)
The date for document with OID {A3BC1093-3ED9-435D-B649-360CA5BA1093} was invalid (~__/03/1948) - changed it to ~01/03/1948
Skipping document 56/236 with OID {E340D02C-A677-4FE1-8382-02FB8F9A1517} because it's missing its XML file!! (stt exists: False)
Skipping document 57/236 with OID {048CE450-B636-4199-8E56-4D21C9497658} because it's missing its XML file!! (stt exists: False)
Skipping document 58/236 with OID {2CD0598B-B330-4084-9761-E36B9ED0108A} because it's missing its XML file!! (stt exists: False)
Skipping document 59/236 with OID {6F41260A-A8A8-41F6-B419-B50464CDDB3B} because it's missing its XML file!! (stt exists: False)
Skipping document 60/236 with OID {E0AEC0F0-616C-4547-A5BF-3179011B4A6C} because it's missing its XML file!! (stt exists: False)
Skipping document 61/236 with OID {44427665-80C9-424E-BA3A-C26AF30DE4E3} because it's missing its XML file!! (stt exists: False)
Skipping document 62/236 with OID {9AB6A56A-F9B6-43BE-999F-AF4C8E69FEB9} because it's missing its XML file!! (stt exists: False)
Skipping document 63/236 with OID {3DCFF9AB-B6A8-43BD-8F27-0D3749D36F02} because it's missing its XML file!! (stt exists: False)
Skipping document 64/236 with OID {F5FFF720-426D-4F68-83F1-E811CC18154A} because it's missing its XML file!! (stt exists: False)
Skipping document 65/236 with OID {6633FB6D-A94C-4928-8160-8BBF693749A3} because it's missing its XML file!! (stt exists: False)
Skipping document 66/236 with OID {21A52594-58C8-45C1-A2B1-5DFB82A05D56} because it's missing its XML file!! (stt exists: False)
Skipping document 67/236 with OID {B0B9A708-19EF-4B3A-941C-80AFBAE44392} because it's missing its XML file!! (stt exists: False)
Skipping document 68/236 with OID {A5D09700-216F-47F9-A95D-E05C7DACBAC8} because it's missing its XML file!! (stt exists: False)
Skipping document 69/236 with OID {829D03A0-0337-46BD-8EA5-4B5546D80726} because it's missing its XML file!! (stt exists: False)
Skipping document 70/236 with OID {14FD0157-AB54-4EFC-8753-0F88FB7497D5} because it's missing its XML file!! (stt exists: False)
Skipping document 71/236 with OID {71BAFFE2-E7EA-4731-968E-4D7702BBBC14} because it's missing its XML file!! (stt exists: False)
Skipping document 72/236 with OID {BF6E2083-4016-48BF-8A3D-D9B7938233B6} because it's missing its XML file!! (stt exists: False)
Skipping document 73/236 with OID {3BCBC0C8-173A-4858-BB1D-380028FFBD87} because it's missing its XML file!! (stt exists: False)
Skipping document 74/236 with OID {6886B842-EC19-444F-BD36-3A9CA2E272E2} because it's missing its XML file!! (stt exists: False)
Skipping document 75/236 with OID {125B7AE9-33F3-45E3-B5B1-A24F43A973D0} because it's missing its XML file!! (stt exists: False)
Skipping document 76/236 with OID {08E14A3B-967A-4292-89D0-E2452E1EA01A} because it's missing its XML file!! (stt exists: False)
Skipping document 77/236 with OID {42D0EDA5-71A5-44A2-834C-B5AAED5DC936} because it's missing its XML file!! (stt exists: False)
Skipping document 78/236 with OID {33975B30-6FA8-4690-BD99-9A35BF5B5A27} because it's missing its XML file!! (stt exists: False)
Skipping document 79/236 with OID {41A5AE5C-6A72-42C3-A58C-4DCA9F2CB2AC} because it's missing its XML file!! (stt exists: False)
Skipping document 80/236 with OID {0656875F-864C-4902-A1FA-351F328EC863} because it's missing its XML file!! (stt exists: False)
Skipping document 81/236 with OID {15285DB5-B9C0-47A0-A05C-C6E265A1F1EC} because it's missing its XML file!! (stt exists: False)
Skipping document 82/236 with OID {81D96F73-F42A-4EE7-B0EB-12A2A2817921} because it's missing its XML file!! (stt exists: False)
Skipping document 83/236 with OID {4C252D9D-AD8A-4A40-B66B-EDD7332860A5} because it's missing its XML file!! (stt exists: False)
Skipping document 84/236 with OID {FD728DDE-F577-42EC-923E-A52E7C5E0FCD} because it's missing its XML file!! (stt exists: False)
Skipping document 85/236 with OID {9D3336A5-C9D4-4DD9-BB79-EE6CE34A1622} because it's missing its XML file!! (stt exists: False)
Skipping document 86/236 with OID {DC6ACC90-8588-4A76-A2BE-AEF4CB48941D} because it's missing its XML file!! (stt exists: False)
Skipping document 87/236 with OID {75CADDB0-6314-4547-8687-A7483F416FE1} because it's missing its XML file!! (stt exists: False)
Skipping document 88/236 with OID {C00B6DB6-7FB1-438D-AFE0-CDE8EC803EE9} because it's missing its XML file!! (stt exists: False)
Skipping document 89/236 with OID {AD678814-9588-439C-9E63-C2CD04EFAD13} because it's missing its XML file!! (stt exists: False)
Skipping document 90/236 with OID {9FD8B200-B64F-4E2E-B25E-98DEEEABE1DB} because it's missing its XML file!! (stt exists: False)
Skipping document 91/236 with OID {954FAB9F-5064-46AC-B50A-3DC3AC8B198C} because it's missing its XML file!! (stt exists: False)
Skipping document 92/236 with OID {2549D020-0584-4C33-AFDA-07E466400FCF} because it's missing its XML file!! (stt exists: False)
Skipping document 93/236 with OID {FF3FF66B-E69C-40D6-A0BE-5BF483E4B0E8} because it's missing its XML file!! (stt exists: False)
Skipping document 94/236 with OID {58CDE5CD-DFF6-4D76-BB2E-2C8556A37E6E} because it's missing its XML file!! (stt exists: False)
Skipping document 95/236 with OID {561730C7-16D4-43E3-A39D-C77A29A739DB} because it's missing its XML file!! (stt exists: False)
Skipping document 96/236 with OID {5D30CF21-154E-43AE-A2C4-932E65FE553F} because it's missing its XML file!! (stt exists: False)
Skipping document 97/236 with OID {256D0672-C272-405C-9C39-834BECC1B95C} because it's missing its XML file!! (stt exists: False)
Skipping document 98/236 with OID {8D103CAE-6F75-4C07-BD80-073464A07DF6} because it's missing its XML file!! (stt exists: False)
Skipping document 99/236 with OID {FD08518B-69B7-4CB5-BF9C-03190463466C} because it's missing its XML file!! (stt exists: False)
Skipping document 100/236 with OID {775FE041-F89F-4BC8-92AC-414A320C045D} because it's missing its XML file!! (stt exists: False)
Skipping document 101/236 with OID {54FFD134-3AE0-4865-B459-BAE24DFBE95E} because it's missing its XML file!! (stt exists: False)
Skipping document 102/236 with OID {5567A222-02BB-4C27-AF6A-EFBC5C040D0A} because it's missing its XML file!! (stt exists: False)
Skipping document 103/236 with OID {14D8A2A7-888F-477A-8262-A93FE582E3A7} because it's missing its XML file!! (stt exists: False)
Skipping document 104/236 with OID {EB7F52C6-2E88-42D3-B8B9-0956F774964B} because it's missing its XML file!! (stt exists: False)
Skipping document 106/236 with OID {97AA10FD-9B9A-4877-A886-DC22C845F3E5} because it's missing its XML file!! (stt exists: False)
Skipping document 107/236 with OID {3D64B06F-C886-4901-9CBA-7DC23EE16B41} because it's missing its XML file!! (stt exists: False)
Skipping document 108/236 with OID {45356CA4-D83B-4FE8-B3E2-7C6729E7C825} because it's missing its XML file!! (stt exists: False)
Skipping document 109/236 with OID {1090F955-F482-409C-8E23-E684992F3DF8} because it's missing its XML file!! (stt exists: False)
Skipping document 110/236 with OID {3EADFD0E-6B86-4941-B996-E276D39A6205} because it's missing its XML file!! (stt exists: False)
Skipping document 111/236 with OID {62811F43-894E-47B0-8C88-71247F5F58E7} because it's missing its XML file!! (stt exists: False)
Skipping document 112/236 with OID {8CABEB96-2496-448D-B4FB-30FF58FA55DC} because it's missing its XML file!! (stt exists: False)
Skipping document 113/236 with OID {D9446670-C33B-4E2D-9098-7AB85A81E0A7} because it's missing its XML file!! (stt exists: False)
Skipping document 114/236 with OID {5D6AAE03-9F38-4254-AEE1-05BE5598A88C} because it's missing its XML file!! (stt exists: False)
Skipping document 115/236 with OID {B2813E35-B1D3-457D-88F2-56804866EF4C} because it's missing its XML file!! (stt exists: False)
Skipping document 116/236 with OID {DA600ADE-41CB-4498-B24B-86D52749B0A2} because it's missing its XML file!! (stt exists: False)
Skipping document 117/236 with OID {6C04E016-9D23-42C3-8682-C16C51D74875} because it's missing its XML file!! (stt exists: False)
Skipping document 118/236 with OID {C5B50C0C-D609-49B4-9862-1E0DFA9899A6} because it's missing its XML file!! (stt exists: False)
Skipping document 119/236 with OID {1CD0FA52-5D3B-43CB-B8E3-4050B463A8D2} because it's missing its XML file!! (stt exists: False)
Skipping document 120/236 with OID {F4AB1561-6E51-449C-89E2-0C9CC27743F9} because it's missing its XML file!! (stt exists: False)
Skipping document 121/236 with OID {5D58A8A4-D6BC-41E5-AB9C-EDC1656A082F} because it's missing its XML file!! (stt exists: False)
Skipping document 122/236 with OID {3D0FF9A3-4371-41D3-9F05-A1469C643794} because it's missing its XML file!! (stt exists: False)
Skipping document 123/236 with OID {8DDD603C-2561-46C2-BABB-DFDD3B21097A} because it's missing its XML file!! (stt exists: False)
Skipping document 124/236 with OID {BD2B2CB9-C274-478A-AED6-14957FA2BF3E} because it's missing its XML file!! (stt exists: False)
Skipping document 125/236 with OID {1184E7A4-5297-40CF-A28D-463C23B806F7} because it's missing its XML file!! (stt exists: False)
Skipping document 126/236 with OID {2D74D214-D80A-4433-B218-BF0781A27363} because it's missing its XML file!! (stt exists: False)
Skipping document 127/236 with OID {3EC7F1DC-4BB3-44A9-9FF0-0B05B15C1EA0} because it's missing its XML file!! (stt exists: False)
The date for document with OID {3736053D-1CB1-4D46-B8F7-CE803EB30C6B} was invalid (~__/__/1947) - changed it to ~01/01/1947
The date for document with OID {3736053D-1CB1-4D46-B8F7-CE803EB30C6B} was invalid (~__/__/1947) - changed it to ~01/01/1947
Skipping document 129/236 with OID {B52B1CDA-02D0-4880-9302-DCC68CC5F93E} because it's missing its XML file!! (stt exists: False)
Skipping document 130/236 with OID {07DEAB8F-B0F2-4C63-9561-BC0222D4431F} because it's missing its XML file!! (stt exists: False)
Skipping document 131/236 with OID {73CB5572-12EE-4FC3-A124-90069D134CDD} because it's missing its XML file!! (stt exists: False)
Skipping document 132/236 with OID {D266E463-93EE-4395-A217-725398DD93CA} because it's missing its XML file!! (stt exists: False)
Skipping document 133/236 with OID {EFE98E24-A744-4E85-8994-86A22EFFE15B} because it's missing its XML file!! (stt exists: False)
Skipping document 134/236 with OID {E685D89C-5959-4806-ACF6-92DEEE0AB561} because it's missing its XML file!! (stt exists: False)
Skipping document 135/236 with OID {9043F613-2CF6-4ED4-BDB6-6C5C5841636B} because it's missing its XML file!! (stt exists: False)
Skipping document 136/236 with OID {D1B1B858-E894-4516-8E41-CE3EE4A80C43} because it's missing its XML file!! (stt exists: False)
Skipping document 137/236 with OID {65512F17-B0A5-4D65-88B4-A423DE1FA1F2} because it's missing its XML file!! (stt exists: False)
Skipping document 138/236 with OID {DA9571AF-ADEE-4A36-9C7F-88424E01AA15} because it's missing its XML file!! (stt exists: False)
Skipping document 139/236 with OID {33BEA170-70FE-489D-BD52-979669BB2196} because it's missing its XML file!! (stt exists: False)
Skipping document 140/236 with OID {5C67B7D4-4CC5-4FFD-85D5-1D592E307297} because it's missing its XML file!! (stt exists: False)
Skipping document 141/236 with OID {54416D0E-4E31-4DEC-ADF2-CF726CC1F1DE} because it's missing its XML file!! (stt exists: False)
Skipping document 142/236 with OID {D123B87B-7F6F-44F7-9FC6-6EFBCD190DD1} because it's missing its XML file!! (stt exists: False)
The date for document with OID {B3CF559E-22E8-4115-9B3C-DEC76A73A63C} was invalid (~__/06/1951) - changed it to ~01/06/1951
The date for document with OID {B3CF559E-22E8-4115-9B3C-DEC76A73A63C} was invalid (~__/06/1951) - changed it to ~01/06/1951
Skipping document 144/236 with OID {31858860-9BCF-4582-946E-286642F652BC} because it's missing its XML file!! (stt exists: False)
Skipping document 145/236 with OID {CF0BD9CB-6EA8-4D9E-A411-E3A885732763} because it's missing its XML file!! (stt exists: False)
Skipping document 146/236 with OID {B0A24B78-6698-4447-905C-2F4AB7346287} because it's missing its XML file!! (stt exists: False)
Skipping document 147/236 with OID {078B58C3-2DA8-4DAD-8E53-106FDABB9B17} because it's missing its XML file!! (stt exists: False)
Skipping document 148/236 with OID {B64294E8-0A7E-4FE4-948E-C042AA14AF32} because it's missing its XML file!! (stt exists: False)
Skipping document 149/236 with OID {830BA9B7-92AA-4408-9F28-4F8C5CD31716} because it's missing its XML file!! (stt exists: False)
Skipping document 150/236 with OID {62396511-C83E-4ADF-9230-F46E954F3D23} because it's missing its XML file!! (stt exists: False)
Skipping document 151/236 with OID {36C12224-1030-4D99-91BE-62D51D82EDC4} because it's missing its XML file!! (stt exists: False)
Skipping document 152/236 with OID {D08F10E7-484B-47F0-A032-FA0EEA1E79B4} because it's missing its XML file!! (stt exists: False)

100%|██████████| 1/1 [00:00<00:00,  1.45it/s]
5it [00:01,  3.36it/s]

The date for document with OID {C1236FA9-7285-41D0-99D2-D9326AC107BF} was invalid (~__/11/1950) - changed it to ~01/11/1950
The date for document with OID {C1236FA9-7285-41D0-99D2-D9326AC107BF} was invalid (~__/11/1950) - changed it to ~01/11/1950
Skipping document 190/236 with OID {80BD19D0-A5D9-4863-AD55-47BD49DAD22D} because it's missing its XML file!! (stt exists: False)
Skipping document 191/236 with OID {2FBD5C35-BB90-4469-A761-D003C57F9358} because it's missing its XML file!! (stt exists: False)
Skipping document 192/236 with OID {9B9076D2-8457-4A57-AD49-A3059E136ABD} because it's missing its XML file!! (stt exists: False)
Skipping document 193/236 with OID {BC74CFF9-1309-4C4B-AE58-E79A7F60F9FA} because it's missing its XML file!! (stt exists: False)
Skipping document 194/236 with OID {F92C9967-8E30-4266-95E5-C82CF53B50B2} because it's missing its XML file!! (stt exists: False)
Skipping document 195/236 with OID {B91DFD0B-03E7-4892-8917-976FC4BC80C8} because it's missing its XML file!! (stt exists: False)
Skipping document 196/236 with OID {A25AB318-CA53-487E-896C-F11BEFEB3610} because it's missing its XML file!! (stt exists: False)
Skipping document 197/236 with OID {B86BD9F1-81E7-438F-8EF9-C409B3C5DE2B} because it's missing its XML file!! (stt exists: False)
Skipping document 198/236 with OID {9377FA89-B0D4-47EC-9038-B523A7EDB5C3} because it's missing its XML file!! (stt exists: False)
Skipping document 199/236 with OID {922423E8-0237-4ADA-8DC8-403826945487} because it's missing its XML file!! (stt exists: False)
Skipping document 200/236 with OID {0C981F62-69B8-4553-94B9-1209774403AC} because it's missing its XML file!! (stt exists: False)
Skipping document 201/236 with OID {12287B51-E761-4BAD-81B7-35ED9412E725} because it's missing its XML file!! (stt exists: False)
Skipping document 202/236 with OID {15B0E75C-A3E6-4EEF-99A6-8CAF65CDC379} because it's missing its XML file!! (stt exists: False)
Skipping document 203/236 with OID {4B948ED1-12B9-464E-8A58-7076166DCE8E} because it's missing its XML file!! (stt exists: False)
The date for document with OID {8DE3EC2F-A83F-40EB-BF9E-099AE211D650} was invalid (~__/02/1946) - changed it to ~01/02/1946
The date for document with OID {8DE3EC2F-A83F-40EB-BF9E-099AE211D650} was invalid (~__/02/1946) - changed it to ~01/02/1946
Skipping document 205/236 with OID {4554AEAA-CD90-4A6A-86D0-4D137B5F0D15} because it's missing its XML file!! (stt exists: False)
Skipping document 206/236 with OID {F2A8ADE6-CAE8-4A19-99B6-60A0C509ACC7} because it's missing its XML file!! (stt exists: False)
Skipping document 207/236 with OID {4CF8BB12-0D10-42F9-AA05-F0F5E3D47F62} because it's missing its XML file!! (stt exists: False)
Skipping document 208/236 with OID {BDA809AB-91CC-4103-82F3-316CFC4DC105} because it's missing its XML file!! (stt exists: False)
Skipping document 209/236 with OID {0E5B12CB-4286-4F59-89B3-679E651DA005} because it's missing its XML file!! (stt exists: False)
Skipping document 210/236 with OID {15F14196-A749-4764-9ABE-E252AFB19E1C} because it's missing its XML file!! (stt exists: False)
Skipping document 211/236 with OID {BB3D7199-5C10-445F-AD8C-0C82BF3E6A6A} because it's missing its XML file!! (stt exists: False)
Skipping document 212/236 with OID {ED0CFA76-8D1E-4A30-B5BE-2DB287D25CEA} because it's missing its XML file!! (stt exists: False)
Skipping document 213/236 with OID {FC92BE20-AFA5-4684-B31E-7E3C44CC8777} because it's missing its XML file!! (stt exists: False)
Skipping document 214/236 with OID {167625C5-1C9B-403F-B912-2B641852A5D9} because it's missing its XML file!! (stt exists: False)
Skipping document 215/236 with OID {52E07B4B-1C31-4D3E-920F-6EDDB02378CB} because it's missing its XML file!! (stt exists: False)
Skipping document 216/236 with OID {78F3C904-93EB-4C03-B4D6-B17286924B55} because it's missing its XML file!! (stt exists: False)
Skipping document 217/236 with OID {AB2A030E-8F49-4AF9-BDF0-82100CE602F9} because it's missing its XML file!! (stt exists: False)
Skipping document 218/236 with OID {AEA63DAD-59E8-4D50-9D00-20131276F068} because it's missing its XML file!! (stt exists: False)
Skipping document 219/236 with OID {EFB335D0-7B98-4B3F-8DA9-009D2A7B4BDA} because it's missing its XML file!! (stt exists: False)
Skipping document 220/236 with OID {AF7232A1-03F0-4976-81DE-D3935E820CBA} because it's missing its XML file!! (stt exists: False)
Skipping document 221/236 with OID {47A2A8BE-3CDA-4596-BF77-E2A4292B6060} because it's missing its XML file!! (stt exists: False)
Skipping document 222/236 with OID {EFC94883-6631-4AE9-AAC3-E4DB1A6CE0C3} because it's missing its XML file!! (stt exists: False)
Skipping document 223/236 with OID {BD0E727B-1CA5-4832-A197-3481CEB936B7} because it's missing its XML file!! (stt exists: False)
Skipping document 224/236 with OID {59A0FDE4-C0CB-4157-ACFE-482E4D1ECEED} because it's missing its XML file!! (stt exists: False)
Skipping document 225/236 with OID {FB5DEC2D-F7EB-4C1A-BAFC-73E4A4B353AF} because it's missing its XML file!! (stt exists: False)
Skipping document 226/236 with OID {6BF516CE-E21C-46FE-B70B-70F78DAA86D0} because it's missing its XML file!! (stt exists: False)
Skipping document 227/236 with OID {211A666C-85E4-4E2F-A93F-A1FD9CEE6FF4} because it's missing its XML file!! (stt exists: False)
Skipping document 228/236 with OID {08BEA02B-8DBF-46A5-9568-DA973A482050} because it's missing its XML file!! (stt exists: False)
The date for document with OID {679E50E1-8F9A-44DC-8D06-7DC77060959E} was invalid (~__/01/1946) - changed it to ~01/01/1946
The date for document with OID {679E50E1-8F9A-44DC-8D06-7DC77060959E} was invalid (~__/01/1946) - changed it to ~01/01/1946
Skipping document 230/236 with OID {AD1BA45D-2489-4967-8550-A78853E0653E} because it's missing its XML file!! (stt exists: False)
Skipping document 231/236 with OID {7F8CD8F5-DE60-433D-B529-3DE4BC6A138F} because it's missing its XML file!! (stt exists: False)
Skipping document 232/236 with OID {23A53371-15D8-46F1-AA8C-40B54F029F30} because it's missing its XML file!! (stt exists: False)
Skipping document 233/236 with OID {6A163408-BB7F-4668-B07E-32B561E56D34} because it's missing its XML file!! (stt exists: False)
Skipping document 234/236 with OID {AEA0CC78-5929-4007-A276-9631F531B6B7} because it's missing its XML file!! (stt exists: False)
The date for document with OID {963269DE-1115-4F24-9234-BC3C8732A0D2} was invalid (~__/12/1947) - changed it to ~01/12/1947
The date for document with OID {963269DE-1115-4F24-9234-BC3C8732A0D2} was invalid (~__/12/1947) - changed it to ~01/12/1947
Skipping document 236/236 with OID {6397C956-4CAE-4C53-84D3-7874B0BA7EE0} because it's missing its XML file!! (stt exists: False)
chron_instit - returning 16 documents, 220 were skipped due to missing necessary info.
 --> Adding 16 to the out csv for chron_instit

PROCESSING PROGRAM chron_unesco (6/47) - 1 files:

100%|██████████| 1/1 [00:00<00:00,  7.15it/s]

Starting extracting 60 documents for program chron_unesco
Skipping document 1/60 with OID {66BC1A28-5594-40B5-926B-D21D2A8E8DE5} because it's missing its XML file!! (stt exists: False)
Skipping document 2/60 with OID {0A44E2AB-2AFF-4B33-A1A4-5803861D7B20} because it's missing its XML file!! (stt exists: False)
Skipping document 3/60 with OID {F9211F57-C3A1-4734-8FAE-E3A1F4B10425} because it's missing its XML file!! (stt exists: False)
Skipping document 4/60 with OID {5345F130-FE59-4534-A05F-B3C885F3B72B} because it's missing its XML file!! (stt exists: False)
Skipping document 5/60 with OID {9D5D9EEB-7D44-4586-A218-5BC386EE1EDE} because it's missing its XML file!! (stt exists: False)
Skipping document 6/60 with OID {F06ADD23-FCC4-401A-8A79-8F6FDCA9ADC3} because it's missing its XML file!! (stt exists: False)
The date for document with OID {58F25276-A592-4AC5-A153-E66B64E3CFCF} was invalid (__/__/1952) - changed it to 01/01/1952
The date for document with OID {5703A9EC-C10A-404F-B930-5C874146FBF7} was invalid (__/__/1952) - changed it to 01/01/1952
Skipping document 9/60 with OID {FE7B43E9-07F4-49E1-9A0B-350BA733165E} because it's missing its XML file!! (stt exists: False)
Skipping document 10/60 with OID {93FC203F-990C-4330-9959-5E5A7DCE577E} because it's missing its XML file!! (stt exists: False)
Skipping document 11/60 with OID {6867EA80-597E-40CA-BDC2-CE9B13AD6ABC} because it's missing its XML file!! (stt exists: False)
Skipping document 12/60 with OID {F1160AB7-16C5-4C89-A801-FCC4D552869D} because it's missing its XML file!! (stt exists: False)
Skipping document 13/60 with OID {2A5F392B-11B6-453B-B379-E694AD332F97} because it's missing its XML file!! (stt exists: False)
Skipping document 14/60 with OID {D5FC5C52-D6C3-4799-975C-2D3C2F4FA2A8} because it's missing its XML file!! (stt exists: False)
Skipping document 15/60 with OID {CDD90465-B5AB-47BE-AAC0-2C722A944AFE} because it's missing its XML file!! (stt exists: False)
Skipping document 16/60 with OID {886B9133-40C7-4129-A40B-1C2EAD0F9358} because it's missing its XML file!! (stt exists: False)
Skipping document 17/60 with OID {447A7D53-C2DA-4D0F-8355-7542D31A43E6} because it's missing its XML file!! (stt exists: False)
Skipping document 18/60 with OID {DBE3B188-1527-4144-B89E-0E99D98BE224} because it's missing its XML file!! (stt exists: False)
Skipping document 19/60 with OID {8089FF04-DE58-4AA2-92A3-F72F7E8C732E} because it's missing its XML file!! (stt exists: False)
Skipping document 20/60 with OID {1C1BAC3E-62D6-4206-97FD-563B01A1C5E7} because it's missing its XML file!! (stt exists: False)
Skipping document 21/60 with OID {40CC6ED4-854E-4E54-B810-89AA67440F24} because it's missing its XML file!! (stt exists: False)
Skipping document 22/60 with OID {5954B5EE-435F-44B8-BB7F-D3C8918FAAFA} because it's missing its XML file!! (stt exists: False)
Skipping document 23/60 with OID {282C0A0B-B003-49CD-886F-D703F74BE628} because it's missing its XML file!! (stt exists: False)
Skipping document 24/60 with OID {22AECE30-5887-419B-89BA-E2D0504FCB22} because it's missing its XML file!! (stt exists: False)
Skipping document 25/60 with OID {B1A74725-6994-4B44-9C8C-70B683F786EB} because it's missing its XML file!! (stt exists: False)
Skipping document 26/60 with OID {D803716C-A8A0-4235-B128-481DCCF6778C} because it's missing its XML file!! (stt exists: False)
Skipping document 27/60 with OID {794F4F6D-D879-469F-9056-BD6FC2B88DC3} because it's missing its XML file!! (stt exists: False)
Skipping document 28/60 with OID {B512443B-7496-4C0A-BC06-1F0C6BF68D36} because it's missing its XML file!! (stt exists: False)
Skipping document 29/60 with OID {E256CB13-FA4E-434D-B045-B2A944D75B2D} because it's missing its XML file!! (stt exists: False)
Skipping document 30/60 with OID {5C3DDAE1-6A60-4033-B505-259826A4C429} because it's missing its XML file!! (stt exists: False)
Skipping document 31/60 with OID {56AEF585-A470-4B28-BA5D-A4B22BBC83D8} because it's missing its XML file!! (stt exists: False)
Skipping document 32/60 with OID {AADC6DA1-BC2E-4D03-AD71-008B3F837EC2} because it's missing its XML file!! (stt exists: False)
Skipping document 33/60 with OID {4813C443-FB52-4634-A696-A95FA84D4AED} because it's missing its XML file!! (stt exists: False)
Skipping document 34/60 with OID {E66C4935-3525-481F-BD62-F8C237B82E8F} because it's missing its XML file!! (stt exists: False)
Skipping document 35/60 with OID {C3C5545F-2429-44D8-8444-3C66717CC570} because it's missing its XML file!! (stt exists: False)
Skipping document 36/60 with OID {0C48EF27-4258-4D96-A863-2A70CE7E2B29} because it's missing its XML file!! (stt exists: False)
Skipping document 37/60 with OID {7C3A66AC-D336-4F92-B5B0-4E621AD2A2C9} because it's missing its XML file!! (stt exists: False)
Skipping document 38/60 with OID {8B16F3CD-1A7F-4F1F-80C1-43B814155B98} because it's missing its XML file!! (stt exists: False)
Skipping document 39/60 with OID {972D71AD-6F51-407E-B198-A3E062D54FE3} because it's missing its XML file!! (stt exists: False)
Skipping document 40/60 with OID {1B1DF5D1-9031-4D2A-B398-A65B66F47ED5} because it's missing its XML file!! (stt exists: False)
Skipping document 41/60 with OID {28CD238A-6C14-41EC-8595-7EEC687E79B8} because it's missing its XML file!! (stt exists: False)
Skipping document 42/60 with OID {308C5AF8-CA90-4B9F-AD60-F6209E6B404F} because it's missing its XML file!! (stt exists: False)
Skipping document 43/60 with OID {561D1E6C-EED0-47A0-8D19-643A72DDDE97} because it's missing its XML file!! (stt exists: False)
Skipping document 44/60 with OID {6C1062E2-9860-400A-B954-F72674642ECE} because it's missing its XML file!! (stt exists: False)
Skipping document 45/60 with OID {AD978345-E824-4911-9116-27E019669C4D} because it's missing its XML file!! (stt exists: False)
Skipping document 46/60 with OID {9AB30FCF-9F94-401B-B026-D20264863D50} because it's missing its XML file!! (stt exists: False)
Skipping document 47/60 with OID {0CA3BC58-3715-4C3A-B256-1A852C2E6A55} because it's missing its XML file!! (stt exists: False)
Skipping document 48/60 with OID {9C34CC6B-45F9-47A2-BBA7-9598F877E0EB} because it's missing its XML file!! (stt exists: False)
Skipping document 49/60 with OID {C7DB8B6F-D75F-4A75-8AE8-636AB3ED54C4} because it's missing its XML file!! (stt exists: False)
Skipping document 50/60 with OID {FF5BDEC9-76FC-4D6D-9A7E-780AE44B018B} because it's missing its XML file!! (stt exists: False)
Skipping document 51/60 with OID {DA5796AC-3F8B-4AD6-B79A-30CEF8F63970} because it's missing its XML file!! (stt exists: False)
Skipping document 52/60 with OID {68872F6D-BCBC-4FD5-8AA6-2C89F5579E3B} because it's missing its XML file!! (stt exists: False)
Skipping document 53/60 with OID {566C477D-1DDB-46B1-A66E-150DE1A1736C} because it's missing its XML file!! (stt exists: False)
Skipping document 54/60 with OID {E7EE12DC-C362-4E9C-BBCE-F9A4790BB795} because it's missing its XML file!! (stt exists: False)
Skipping document 55/60 with OID {D573F01F-CCBB-4383-9E62-2DFF6661EF01} because it's missing its XML file!! (stt exists: False)
Skipping document 56/60 with OID {03F8A2D4-299E-4D5A-AD99-9098144587E9} because it's missing its XML file!! (stt exists: False)
Skipping document 57/60 with OID {36956C20-BC19-4044-95D9-C061AB24E0B0} because it's missing its XML file!! (stt exists: False)
Skipping document 58/60 with OID {8EB99A9E-AE76-42D9-BD9D-0F67908A95C3} because it's missing its XML file!! (stt exists: False)
Skipping document 59/60 with OID {58C84C3B-B84E-4EF8-A804-E0AE98F11B52} because it's missing its XML file!! (stt exists: False)
Skipping document 60/60 with OID {0D676689-FC39-43F5-A143-C8A2FE3734A1} because it's missing its XML file!! (stt exists: False)
chron_unesco - returning 2 documents, 58 were skipped due to missing necessary info.

6it [00:01,  3.90it/s]

 --> Adding 2 to the out csv for chron_unesco

PROCESSING PROGRAM courrier_cr (7/47) - 1 files:

100%|██████████| 1/1 [00:00<00:00, 28.01it/s]

Starting extracting 15 documents for program courrier_cr
Skipping document 1/15 with OID {1073E6EE-E4F3-4964-BACE-0AB21E977484} because it's missing its XML file!! (stt exists: False)
Skipping document 2/15 with OID {65C1F992-0CB0-4915-8933-922AF48B40EC} because it's missing its XML file!! (stt exists: False)
Skipping document 3/15 with OID {7C060C62-3B86-4636-8F6A-AC0D15346922} because it's missing its XML file!! (stt exists: False)
Skipping document 4/15 with OID {6B1092F7-BD6D-4224-A2B0-1093A9DF21BD} because it's missing its XML file!! (stt exists: False)
Skipping document 5/15 with OID {7E26CAE8-DC8A-43AF-9878-DB3AA45298E5} because it's missing its XML file!! (stt exists: False)
Skipping document 6/15 with OID {AA4C5329-EBD6-4B1E-8813-4234C2B31052} because it's missing its XML file!! (stt exists: False)
Skipping document 7/15 with OID {8DBADE0E-F273-47D7-8B44-37CDB2B69DCF} because it's missing its XML file!! (stt exists: False)
Skipping document 8/15 with OID {F57F6900-1CDD-4D32-86F2-59C6ACA0489B} because it's missing its XML file!! (stt exists: False)
Skipping document 9/15 with OID {42C21776-E85D-478F-A992-21C5889A2911} because it's missing its XML file!! (stt exists: False)
Skipping document 10/15 with OID {C5BEEE97-0DBF-4D88-A357-6D8068F1D9D3} because it's missing its XML file!! (stt exists: False)
Skipping document 11/15 with OID {8B1186F4-6D68-4DE6-96BA-B6EC5BAB56C6} because it's missing its XML file!! (stt exists: False)
Skipping document 12/15 with OID {24973ED0-06B4-4F43-9EAC-5D74D99ECA7D} because it's missing its XML file!! (stt exists: False)
Skipping document 13/15 with OID {68AE5A24-8BB1-4EB5-BC74-9C4165012EE9} because it's missing its XML file!! (stt exists: False)
Skipping document 14/15 with OID {7C8B77DD-6B8B-4017-84EF-1D01B7192E3D} because it's missing its XML file!! (stt exists: False)
Skipping document 15/15 with OID {6E14774E-5865-4A1C-9A21-D82CC23C5548} because it's missing its XML file!! (stt exists: False)
courrier_cr - returning 0 documents, 15 were skipped due to missing necessary info.
 --> Adding 0 to the out csv for courrier_cr

PROCESSING PROGRAM culte (8/47) - 1 files:

Starting extracting 219 documents for program culte
Skipping document 6/219 with OID {A9F197FC-FCB0-4CCA-B8D7-9BA0C07DA1FE} because it's missing its XML file!! (stt exists: False)
Skipping document 11/219 with OID {3911571A-6E64-44FB-B186-F6C86B30D933} because it's missing its XML file!! (stt exists: False)
Skipping document 20/219 with OID {88E9DCA8-3E14-4EDB-A805-CBAF972D9812} because it's missing its XML file!! (stt exists: False)
Skipping document 25/219 with OID {8CE1645D-03A3-45D9-B932-4CA900F857B8} because it's missing its XML file!! (stt exists: False)
Skipping document 26/219 with OID {5CA2BCEB-5247-4ABB-B4B5-4C796D70E4D7} because it's missing its XML file!! (stt exists: False)
Skipping document 28/219 with OID {D3BD691C-A6D0-4A27-9BB2-EC425EE78A7F} because it's missing its XML file!! (stt exists: False)
Skipping document 32/219 with OID {D2A170D1-26A6-4084-8F3F-952E082078B7} because it's missing its XML file!! (stt exists: False)
Skipping document 33/219 with OID {271B2CF1-9201-44F6-A56B-5D6F3FB61484} because it's missing its XML file!! (stt exists: False)
Skipping document 34/219 with OID {D7EB3B6A-D6D8-49B4-B09C-0DA2FA914768} because it's missing its XML file!! (stt exists: False)
Skipping document 35/219 with OID {E4DB7B12-FFFE-4CDD-9059-FA473FC79E4A} because it's missing its XML file!! (stt exists: False)
Skipping document 37/219 with OID {20AE7DDD-9D52-4E16-B4F9-DECBE9221315} because it's missing its XML file!! (stt exists: False)
Skipping document 40/219 with OID {8FD11B0E-D51A-4434-A4EE-1CC65C91EA50} because it's missing its XML file!! (stt exists: False)
Skipping document 41/219 with OID {DBE74C50-E5D2-4DF7-A2B6-6B397C4514BD} because it's missing its XML file!! (stt exists: False)
Skipping document 53/219 with OID {4ED3150D-C6A9-4094-ABF6-875F10D508CE} because it's missing its XML file!! (stt exists: False)
Skipping document 54/219 with OID {4B8B558D-D4D8-4FB8-8CBA-20C8074F8EBB} because it's missing its XML file!! (stt exists: False)
Skipping document 55/219 with OID {9E023AB5-E1E0-4511-BD17-1E0D916A267B} because it's missing its XML file!! (stt exists: False)
Skipping document 56/219 with OID {F61B0A3E-22BD-43B6-BB3D-E282E9BA8006} because it's missing its XML file!! (stt exists: False)
Skipping document 62/219 with OID {8FEE510D-2532-4A57-8622-7EA1F679FA06} because it's missing its XML file!! (stt exists: False)
Skipping document 67/219 with OID {679512D1-42DB-491B-B912-295CD755FFE4} because it's missing its XML file!! (stt exists: False)
Skipping document 74/219 with OID {79405F41-232B-420C-8A11-980F921EFA6C} because it's missing its XML file!! (stt exists: False)
Skipping document 75/219 with OID {AC4FD2F9-9B34-41DC-9102-0F4CCEEE25EC} because it's missing its XML file!! (stt exists: False)
Skipping document 77/219 with OID {22B8A604-03B8-4F5F-8E4A-BF2F5BA697FC} because it's missing its XML file!! (stt exists: False)

100%|██████████| 1/1 [00:00<00:00,  1.17it/s]
8it [00:02,  2.86it/s]

Skipping document 117/219 with OID {517A70C9-12B2-4D55-A818-FD27C3478AF8} because it's missing its XML file!! (stt exists: False)
Skipping document 121/219 with OID {2DCAAEF0-EF29-4E92-BD82-C0EB16541740} because it's missing its XML file!! (stt exists: False)
Skipping document 129/219 with OID {39786B0B-AAAD-4367-A28D-E0B0356D395F} because it's missing its XML file!! (stt exists: False)
Skipping document 161/219 with OID {7F122966-B194-466B-83C2-5695E79033EA} because it's missing its XML file!! (stt exists: False)
Skipping document 178/219 with OID {13751DB0-9C8E-42A4-B5DC-6FCF7C961FF5} because it's missing its XML file!! (stt exists: False)
Skipping document 191/219 with OID {6D06A2C9-130B-42E6-B698-FD336F7517B0} because it's missing its XML file!! (stt exists: False)
Skipping document 208/219 with OID {356EA631-2E2B-4C00-99D7-87CAD37A8C99} because it's missing its XML file!! (stt exists: False)
Skipping document 209/219 with OID {8B5EF25B-2E1F-4B11-AD62-CEE8613C1037} because it's missing its XML file!! (stt exists: False)
Skipping document 211/219 with OID {AA8F9C2A-836C-44AA-BE91-410ACA5D9213} because it's missing its XML file!! (stt exists: False)
Skipping document 212/219 with OID {B021AEE0-E8E7-4BD6-A1A9-50F8D5CBA690} because it's missing its XML file!! (stt exists: False)
Skipping document 213/219 with OID {B84DF8F9-8AE9-4578-A95E-0D67BAF640C2} because it's missing its XML file!! (stt exists: False)
Skipping document 215/219 with OID {3C8B4608-F3DA-4400-A621-14E758A915A2} because it's missing its XML file!! (stt exists: False)
culte - returning 185 documents, 34 were skipped due to missing necessary info.
 --> Adding 185 to the out csv for culte

PROCESSING PROGRAM dos_sci (9/47) - 1 files:

Starting extracting 95 documents for program dos_sci
Skipping document 15/95 with OID {024E3A67-49F3-4660-861B-935F0BE9582F} because it's missing its XML file!! (stt exists: False)
Skipping document 47/95 with OID {805DD91A-5A56-482D-AFC2-1E7239C8EE31} because it's missing its XML file!! (stt exists: False)
Skipping document 51/95 with OID {6A01C6FF-93D3-4238-90EB-0A076874AC35} because it's missing its XML file!! (stt exists: False)
Skipping document 56/95 with OID {17007885-D124-4D8B-9DD9-1A89933325B1} because it's missing its XML file!! (stt exists: False)
Skipping document 58/95 with OID {BCC933E9-817D-4EB9-9379-2347524A614E} because it's missing its XML file!! (stt exists: False)
Skipping document 61/95 with OID {058CAC48-2B2B-4F32-8A15-FD87059848E1} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {CE9E2F0B-0C13-4E3B-B81B-7A55A6DEDC30}. Trying to use the recording date. doc_dict: {'alias': 'dos_sci', 'date_str': None, 'stt_filename': 'CE9E2F0B-0C13-4E3B-B81B-7A55A6DEDC30_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{CE9E2F0B-0C13-4E3B-B81B-7A55A6DEDC30}', 'stripped_OID': 'CE9E2F0B-0C13-4E3B-B81B-7A55A6DEDC30', 'login': '', 'broadcast_episode_title': 'Les r?ves lucides', 'sequence': '2', 'broadcast_program_name': 'Dossier : sciences', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'bbr (NumA)', 'modified_on': '22.07.2022 19:10:39', 'physical_support_history': "Cote d'origine : Bd 4273 Resp. RSR : bbr Lot : Caisse 1327", 'production_type': 'Production propre', 'recording_place': 'Gen?ve', 'rights_notes': None, 'rights_status': None, 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Guilleminault, Christian', 'function': 'Interview?/e', 'role': 'chercheur, Univ. de Stanford (Californie)'}, {'name': 'Schaerlig, Eric', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}, {'name': 'Ypsilantis, Nancy', 'function': 'Pr?sentateur/trice', 'role': 'collaborateur/trice RSR'}, {'name': 'Inconnue', 'function': 'Pr?sentateur/trice', 'role': 'collaborateur/trice RSR (Elisabeth ?)'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': ['r?ve'], 'rights_usage_possibilities': None, 'radio_channels': ['Espace 2'], 'subdomains': ['Interview'], 'recording_dates': ['~__/10/1988 - ~__/10/1988'], 'first_broadcast_dates': None}
The date for document with OID {CE9E2F0B-0C13-4E3B-B81B-7A55A6DEDC30} was invalid (~__/10/1988) - changed it to ~01/10/1988
The date for document with OID {CE9E2F0B-0C13-4E3B-B81B-7A55A6DEDC30} was invalid (~__/10/1988) - changed it to ~01/10/1988
Skipping document 74/95 with OID {15128C3E-2A12-4DA8-8D4E-45B7C3E7CDD1} because it's missing its XML file!! (stt exists: False)
Skipping document 76/95 with OID {B9C3766E-4EA0-496B-A5A1-850298FEA1DD} because it's missing its XML file!! (stt exists: False)
Skipping document 77/95 with OID {EF48CC6F-6046-4F36-9EED-34233F14540A} because it's missing its XML file!! (stt exists: False)

100%|██████████| 1/1 [00:00<00:00,  2.22it/s]
9it [00:02,  2.63it/s]

Skipping document 80/95 with OID {D27D4B91-5A36-4A77-A994-47D97428D356} because it's missing its XML file!! (stt exists: False)
Skipping document 81/95 with OID {173B18B3-271F-472D-B5D5-336831000CA1} because it's missing its XML file!! (stt exists: False)
Skipping document 92/95 with OID {4BB3BEBB-CC19-4C6D-9357-ED343C37C04F} because it's missing its XML file!! (stt exists: False)
dos_sci - returning 83 documents, 12 were skipped due to missing necessary info.
 --> Adding 83 to the out csv for dos_sci

PROCESSING PROGRAM ecoute_paix (10/47) - 1 files:

100%|██████████| 1/1 [00:00<00:00,  2.46it/s]
10it [00:03,  2.57it/s]

Starting extracting 125 documents for program ecoute_paix
Skipping document 1/125 with OID {9590C9BC-874D-4A91-84B9-89EF0B250D68} because it's missing its XML file!! (stt exists: False)
The date for document with OID {5BF47ED2-2B35-430F-B74B-12884F25292E} was invalid (~__/06/1947) - changed it to ~01/06/1947
The date for document with OID {BC0687B2-629E-4498-BD7E-592EDAD404A1} was invalid (~__/02/1947) - changed it to ~01/02/1947
The date for document with OID {BC0687B2-629E-4498-BD7E-592EDAD404A1} was invalid (~__/02/1947) - changed it to ~01/02/1947
Skipping document 4/125 with OID {10F4448C-EB47-486C-84D1-4E4269DA4AA3} because it's missing its XML file!! (stt exists: False)
Skipping document 5/125 with OID {EB75D4BA-E7A8-49EA-903E-9F876FBBF3B5} because it's missing its XML file!! (stt exists: False)
Skipping document 6/125 with OID {E5E5197A-3AB8-44F1-AA0C-A8F06EF7101D} because it's missing its XML file!! (stt exists: False)
Skipping document 7/125 with OID {C3BB5A60-4693-4A45-A4AD-112DF00F2696} because it's missing its XML file!! (stt exists: False)
Skipping document 8/125 with OID {F313AE1B-FB0C-475A-B26D-1F42C08AD2BC} because it's missing its XML file!! (stt exists: False)
Skipping document 9/125 with OID {54834B2E-E5BD-4A40-8FC4-09DBC5854A15} because it's missing its XML file!! (stt exists: False)
Skipping document 10/125 with OID {BBC32648-4BAA-457E-8FAB-4B3D480DD16C} because it's missing its XML file!! (stt exists: False)
Skipping document 11/125 with OID {B43BC1B0-D82C-4E9B-A8D4-B1DF1D763950} because it's missing its XML file!! (stt exists: False)
Skipping document 12/125 with OID {CDACD642-EF27-4101-84BF-71318108712E} because it's missing its XML file!! (stt exists: False)
Skipping document 13/125 with OID {8A0D9BF6-30EB-4771-BADD-0BC1CC1A3563} because it's missing its XML file!! (stt exists: False)
Skipping document 14/125 with OID {0D5AE4F0-9413-489F-8519-1973FCB3930D} because it's missing its XML file!! (stt exists: False)
Skipping document 15/125 with OID {5EF83DBE-F02F-4091-AD9A-964AC4DC9A6C} because it's missing its XML file!! (stt exists: False)
Skipping document 16/125 with OID {BEA00F94-D3CF-480F-88A5-489DEECBB2E6} because it's missing its XML file!! (stt exists: False)
Skipping document 17/125 with OID {86DB6D1A-1593-4044-B301-B49A73514DBC} because it's missing its XML file!! (stt exists: False)
Skipping document 18/125 with OID {0AE159F0-8A7A-49AE-B820-64EF2FA1526D} because it's missing its XML file!! (stt exists: False)
Skipping document 19/125 with OID {5FFC49BB-BBE7-4623-80B0-4E1B561EE4B4} because it's missing its XML file!! (stt exists: False)
Skipping document 20/125 with OID {556FA1CD-4A2E-4301-9449-CD3B820D263F} because it's missing its XML file!! (stt exists: False)
Skipping document 21/125 with OID {BA3C23E5-742D-40B7-B5B0-EA8EA67DFE21} because it's missing its XML file!! (stt exists: False)
Skipping document 22/125 with OID {BF4085FD-9D48-47A4-B152-132CD1AD9F7B} because it's missing its XML file!! (stt exists: False)
Skipping document 23/125 with OID {CB1BC67C-B8F4-409D-97FA-A71AABF29765} because it's missing its XML file!! (stt exists: False)
Skipping document 24/125 with OID {D39C0266-EF6D-446B-8F51-60673F968904} because it's missing its XML file!! (stt exists: False)
Skipping document 25/125 with OID {7B0A043C-5F69-4093-B007-AF8800D233B7} because it's missing its XML file!! (stt exists: False)
Skipping document 26/125 with OID {A929A416-BCB1-45D7-BB3D-D3CFCE4C04EF} because it's missing its XML file!! (stt exists: False)
Skipping document 27/125 with OID {573C1B02-5C1A-4F11-8CF2-B9518214DFC2} because it's missing its XML file!! (stt exists: False)
Skipping document 28/125 with OID {8879ED49-77CE-4C07-89EB-4F62B200FC8E} because it's missing its XML file!! (stt exists: False)
Skipping document 29/125 with OID {4280230C-569E-4EB2-BE4A-F27654BE579A} because it's missing its XML file!! (stt exists: False)
Skipping document 30/125 with OID {F937C960-5ED5-4CC4-AC04-66338C666593} because it's missing its XML file!! (stt exists: False)
Skipping document 31/125 with OID {EEBE076A-B6E9-43B7-AFA9-2A83CF5BCC2B} because it's missing its XML file!! (stt exists: False)
Skipping document 32/125 with OID {6D7C0692-7171-47FC-BF7D-1D71D6BCA229} because it's missing its XML file!! (stt exists: False)
Skipping document 33/125 with OID {72A367C9-E5EE-4CAD-85B6-BB858EE9DEDF} because it's missing its XML file!! (stt exists: False)
Skipping document 34/125 with OID {D236FE00-7435-47FF-8C9A-50177650F8C2} because it's missing its XML file!! (stt exists: False)
Skipping document 35/125 with OID {07BD0FE0-F68C-4891-9F81-3E4F4CD2AB1D} because it's missing its XML file!! (stt exists: False)
Skipping document 36/125 with OID {C4A87FF8-01E6-4099-BC64-8C8CEE3E2D58} because it's missing its XML file!! (stt exists: False)
Skipping document 37/125 with OID {A6E2DF8C-094D-478E-A721-7E0E55C7A8D6} because it's missing its XML file!! (stt exists: False)
Skipping document 38/125 with OID {AE1C7C8F-C1EA-4E65-99A2-79435AF9F6C2} because it's missing its XML file!! (stt exists: False)
Skipping document 39/125 with OID {6AC67B88-230D-47E9-9048-E4170C1F14D2} because it's missing its XML file!! (stt exists: False)
Skipping document 40/125 with OID {4FB9887F-A58D-44E3-9FDD-A51F30AAA6A4} because it's missing its XML file!! (stt exists: False)
Skipping document 41/125 with OID {24E60872-38FF-4CAB-859D-046D5D98607E} because it's missing its XML file!! (stt exists: False)
Skipping document 42/125 with OID {CE71B24B-21B2-4D57-80DA-6DB8182B656D} because it's missing its XML file!! (stt exists: False)
Skipping document 43/125 with OID {4B7003AC-0E6D-4F94-B806-995F3689E61E} because it's missing its XML file!! (stt exists: False)
Skipping document 44/125 with OID {1441D894-F600-42AD-854A-AC40D63EBA3E} because it's missing its XML file!! (stt exists: False)
Skipping document 45/125 with OID {82225C7F-1EBB-423B-B520-B1697F82DDF5} because it's missing its XML file!! (stt exists: False)
Skipping document 46/125 with OID {3896EC86-5CB0-40EB-823A-C0905DEC03A0} because it's missing its XML file!! (stt exists: False)
Skipping document 47/125 with OID {6529B593-FC2C-43F3-B348-93845D69B050} because it's missing its XML file!! (stt exists: False)
Skipping document 48/125 with OID {7BF173E2-9BAB-44B2-BC01-A5B3078BEC11} because it's missing its XML file!! (stt exists: False)
Skipping document 49/125 with OID {54CC45B3-0B8F-4A91-A2E6-D3A5122641D9} because it's missing its XML file!! (stt exists: False)
Skipping document 50/125 with OID {F0345603-1470-4AAE-BD88-C5338E1ED9F6} because it's missing its XML file!! (stt exists: False)
Skipping document 51/125 with OID {9AEE8883-2203-42E5-BAF4-3FE7C93459F4} because it's missing its XML file!! (stt exists: False)
Skipping document 52/125 with OID {DAACBDE5-C79C-4836-9CD2-1C28B0E9B094} because it's missing its XML file!! (stt exists: False)
Skipping document 53/125 with OID {A41FAB3B-FC4A-4ECD-8047-9F1D451936EA} because it's missing its XML file!! (stt exists: False)
Skipping document 54/125 with OID {7E8B4362-42EC-4ED8-B04D-8B80FAFE0419} because it's missing its XML file!! (stt exists: False)
Skipping document 55/125 with OID {214454AE-3B7E-42B6-BE97-A5FD6C5D6CC2} because it's missing its XML file!! (stt exists: False)
Skipping document 56/125 with OID {C331468A-8518-46FB-B658-0F6BD0686C21} because it's missing its XML file!! (stt exists: False)
Skipping document 57/125 with OID {06569DF4-5532-4720-8E13-419D486DAD59} because it's missing its XML file!! (stt exists: False)
Skipping document 58/125 with OID {797AFF12-9FED-441F-8C17-497B26C7DA1C} because it's missing its XML file!! (stt exists: False)
Skipping document 59/125 with OID {CF488CAD-8E9E-4F6D-9993-1185263E53DA} because it's missing its XML file!! (stt exists: False)
Skipping document 60/125 with OID {124F02EE-943F-4D3D-A1B3-BC7809262D3E} because it's missing its XML file!! (stt exists: False)
Skipping document 61/125 with OID {CEC18255-76EF-4ED0-BF20-5BED05C79A3D} because it's missing its XML file!! (stt exists: False)
Skipping document 62/125 with OID {A6198E31-4AB7-4C2D-9240-5DAC027587E9} because it's missing its XML file!! (stt exists: False)
Skipping document 63/125 with OID {5DFFA375-75EC-4937-BC0E-CA17F7EAA28C} because it's missing its XML file!! (stt exists: False)
Skipping document 64/125 with OID {AF29B255-E9FF-4E84-B36B-6A1F70D62390} because it's missing its XML file!! (stt exists: False)
Skipping document 65/125 with OID {558E2DFA-CCF5-4776-A7C9-A1C8DF7D69A7} because it's missing its XML file!! (stt exists: False)
Skipping document 66/125 with OID {23A95502-8452-494F-B76F-1CA2247D4B67} because it's missing its XML file!! (stt exists: False)
Skipping document 67/125 with OID {A7A7681A-6D5F-4536-8A91-7DCB44FEF5A5} because it's missing its XML file!! (stt exists: False)
Skipping document 68/125 with OID {F347BAF8-C7FC-4CA0-9033-CB5F7512EC6B} because it's missing its XML file!! (stt exists: False)
Skipping document 69/125 with OID {379F145F-0662-4C7A-8801-B4A2B9D94100} because it's missing its XML file!! (stt exists: False)
Skipping document 70/125 with OID {217DE3FA-AFB4-4832-9F5E-19149986641A} because it's missing its XML file!! (stt exists: False)
Skipping document 71/125 with OID {FC4FBB45-1364-461E-80C1-3A7BE3DC61C8} because it's missing its XML file!! (stt exists: False)
Skipping document 72/125 with OID {9BC69B1A-A4F6-4B52-B20F-B27DB426FA82} because it's missing its XML file!! (stt exists: False)
Skipping document 73/125 with OID {BD598718-07BE-4BE6-B037-7D8559E1F7B0} because it's missing its XML file!! (stt exists: False)
Skipping document 74/125 with OID {6DA58AA1-7844-4FB6-B655-97B77A393B54} because it's missing its XML file!! (stt exists: False)
Skipping document 75/125 with OID {61E5A372-F811-4569-8F39-CDAC0B9F1B00} because it's missing its XML file!! (stt exists: False)
Skipping document 76/125 with OID {2B76E13D-A7A7-4BFA-AF47-855DCFD3B220} because it's missing its XML file!! (stt exists: False)
Skipping document 77/125 with OID {56C3ABF0-BEA4-410F-B651-A6F783AB5C4E} because it's missing its XML file!! (stt exists: False)
The date for document with OID {DD078C49-06F1-4FF7-94AE-87F0797FEDFD} was invalid (~__/02/1946) - changed it to ~01/02/1946
Skipping document 79/125 with OID {589B1EEF-ED54-4544-8B41-C71ECE4D2D95} because it's missing its XML file!! (stt exists: False)
Skipping document 80/125 with OID {E49A2EA8-6DB7-43E2-9A44-89B8BF7E5F89} because it's missing its XML file!! (stt exists: False)
Skipping document 81/125 with OID {2E620BBD-676D-4C48-AC7E-709FE0393774} because it's missing its XML file!! (stt exists: False)
Skipping document 82/125 with OID {58EF1FF1-A5E6-432D-83E4-51323DFEFBDF} because it's missing its XML file!! (stt exists: False)
Skipping document 83/125 with OID {859CCB8C-18EC-44C3-A55B-4F0E95889606} because it's missing its XML file!! (stt exists: False)
Skipping document 84/125 with OID {F19DDAFB-4503-4075-AADB-48B69F90A4E6} because it's missing its XML file!! (stt exists: False)
Skipping document 85/125 with OID {F36C4D3D-8F17-4CBA-A1A5-BC0B3608BB33} because it's missing its XML file!! (stt exists: False)
Skipping document 86/125 with OID {54CD2CFC-5FB8-46C9-9424-559779E9F09E} because it's missing its XML file!! (stt exists: False)
Skipping document 87/125 with OID {8F54F8C9-4D85-48B8-8167-615688F8589F} because it's missing its XML file!! (stt exists: False)
Skipping document 88/125 with OID {9729F9C0-40CB-4341-9450-078001654049} because it's missing its XML file!! (stt exists: False)
Skipping document 89/125 with OID {5A166369-AAA8-4E48-BB73-FF7F536D0BB1} because it's missing its XML file!! (stt exists: False)
Skipping document 90/125 with OID {497DDC96-8545-488C-856C-20467C8924A1} because it's missing its XML file!! (stt exists: False)
Skipping document 91/125 with OID {A708216D-C544-416F-94C9-B5E9075CD1FD} because it's missing its XML file!! (stt exists: False)
Skipping document 92/125 with OID {84CFBFC9-C4D5-4745-86AD-E58E7CDC355F} because it's missing its XML file!! (stt exists: False)
Skipping document 93/125 with OID {4B824B30-4179-4C33-A696-46C5384D4091} because it's missing its XML file!! (stt exists: False)
Skipping document 94/125 with OID {AB2563D2-F855-415D-8FF7-C195880E2D6C} because it's missing its XML file!! (stt exists: False)
Skipping document 95/125 with OID {1E2DA24E-D08C-4C10-83C5-45B80F1F87DE} because it's missing its XML file!! (stt exists: False)
Skipping document 96/125 with OID {AFAEA823-C5D9-48CA-9BC6-B1834F48763F} because it's missing its XML file!! (stt exists: False)
Skipping document 97/125 with OID {2D947AC6-79D3-4561-BB70-EF1E921CF777} because it's missing its XML file!! (stt exists: False)
Skipping document 98/125 with OID {24277D39-2061-4A0E-9C70-7B15A5BADCCA} because it's missing its XML file!! (stt exists: False)
Skipping document 99/125 with OID {8B1FD554-0767-4304-9A59-019CF8D79027} because it's missing its XML file!! (stt exists: False)
Skipping document 100/125 with OID {221C5FA6-34CE-45FC-8C78-EC06C06D6BD4} because it's missing its XML file!! (stt exists: False)
Skipping document 101/125 with OID {847B2043-2817-48D7-BF71-0C18BBF7CE15} because it's missing its XML file!! (stt exists: False)
Skipping document 102/125 with OID {29991343-738E-429B-B4FC-6CCD4644D1B4} because it's missing its XML file!! (stt exists: False)
The date for document with OID {CEFF1408-A795-4568-B989-A71FD9484C21} was invalid (~__/04/1947) - changed it to ~01/04/1947
The date for document with OID {CEFF1408-A795-4568-B989-A71FD9484C21} was invalid (~__/04/1947) - changed it to ~01/04/1947
Skipping document 104/125 with OID {A7E23167-E7E1-4540-B1F5-DB2270D00E68} because it's missing its XML file!! (stt exists: False)
Skipping document 105/125 with OID {4AFAA0FC-0534-4C4F-86FB-64B4E4ADA623} because it's missing its XML file!! (stt exists: False)
Skipping document 106/125 with OID {0D0982EA-F5A9-4C18-AFAD-9AEB40744FF0} because it's missing its XML file!! (stt exists: False)
The date for document with OID {ABF047BC-C741-4098-AAB5-E3F764936CAA} was invalid (~__/05/1947) - changed it to ~01/05/1947
The date for document with OID {ABF047BC-C741-4098-AAB5-E3F764936CAA} was invalid (~__/05/1947) - changed it to ~01/05/1947
Skipping document 108/125 with OID {A55F154A-B5BE-427B-827A-6C56DEE2B21C} because it's missing its XML file!! (stt exists: False)
Skipping document 109/125 with OID {C58E0885-8279-4700-8B14-9151B4625529} because it's missing its XML file!! (stt exists: False)
Skipping document 110/125 with OID {D705D7BD-8D66-435C-93C4-E9189AACA3F7} because it's missing its XML file!! (stt exists: False)
Skipping document 113/125 with OID {B1FDFBAB-F39D-4460-9887-46FAD6EC4F08} because it's missing its XML file!! (stt exists: False)
Skipping document 114/125 with OID {1D6E707B-825D-44D5-9BA9-28A1C3B94378} because it's missing its XML file!! (stt exists: False)
Skipping document 115/125 with OID {16C6500B-375C-4552-86B4-A98A752D9C76} because it's missing its XML file!! (stt exists: False)
The date for document with OID {5ADD3657-30C6-4935-B771-AB11FDA7A8F9} was invalid (~__/12/1946) - changed it to ~01/12/1946
The date for document with OID {5ADD3657-30C6-4935-B771-AB11FDA7A8F9} was invalid (~__/12/1946) - changed it to ~01/12/1946
Skipping document 117/125 with OID {1FEDED40-76E0-4D4F-8171-CBA6A3D94B97} because it's missing its XML file!! (stt exists: False)
Skipping document 118/125 with OID {7BB2BE83-16DE-4EB0-BF41-5E319AFE92B9} because it's missing its XML file!! (stt exists: False)
The date for document with OID {F996F9AF-E077-4BA5-9ECA-B592C288896E} was invalid (~__/03/1947) - changed it to ~01/03/1947
Skipping document 120/125 with OID {434FCEB9-EA7F-4317-B916-B43F39EBF3E9} because it's missing its XML file!! (stt exists: False)
Skipping document 121/125 with OID {7ED29B07-D18E-4E63-B8DF-CD287D96972D} because it's missing its XML file!! (stt exists: False)
Skipping document 122/125 with OID {29718FB7-80C6-43D0-9041-A00E2D6577D7} because it's missing its XML file!! (stt exists: False)
The date for document with OID {C9F9B975-416A-4110-9DE0-A9F175CB75BF} was invalid (~__/04/1947) - changed it to ~01/04/1947
The date for document with OID {C9F9B975-416A-4110-9DE0-A9F175CB75BF} was invalid (~__/04/1947) - changed it to ~01/04/1947
Skipping document 124/125 with OID {9D664F8E-FC8F-47EA-B42D-F67FCD75E941} because it's missing its XML file!! (stt exists: False)
The date for document with OID {C5292D63-F451-4A16-B759-7A460B6CFD03} was invalid (~__/05/1947) - changed it to ~01/05/1947
The date for document with OID {C5292D63-F451-4A16-B759-7A460B6CFD03} was invalid (~__/05/1947) - changed it to ~01/05/1947
ecoute_paix - returning 11 documents, 114 were skipped due to missing necessary info.
 --> Adding 11 to the out csv for ecoute_paix

PROCESSING PROGRAM enquest (11/47) - 2 files:

Starting extracting 120 documents for program enquest
Skipping document 87/120 with OID {3055598F-87D5-4120-8F2D-F6570E49D3AB} because it's missing its XML file!! (stt exists: False)
Skipping document 94/120 with OID {59B38FA9-976E-4E14-87A8-172935248216} because it's missing its XML file!! (stt exists: False)
Skipping document 96/120 with OID {345F9ED0-471C-4C54-ADB9-3D6706F84EBF} because it's missing its XML file!! (stt exists: False)
The date for document with OID {18490C22-82F5-4AC3-9451-E1EFB2D9F100} was invalid (__/__/1979) - changed it to 01/01/1979

Skipping document 117/120 with OID {553708D4-F74C-4522-8275-CCB9E42B0F95} because it's missing its XML file!! (stt exists: False)
Skipping document 118/120 with OID {E00B1CB8-651F-414D-9896-5D6BEF5FACCD} because it's missing its XML file!! (stt exists: False)
enquest - returning 115 documents, 5 were skipped due to missing necessary info.

Starting extracting 998 documents for program enquest
Skipping document 4/998 with OID {35D79AA6-B71C-4887-AC82-6874D4134D48} because it's missing its XML file!! (stt exists: True)
The date for document with OID {F3A9B93C-30EE-4560-881E-3E0778370132} was invalid (__/10/1981) - changed it to 01/10/1981
Skipping document 109/998 with OID {62B32C4F-DDEB-42FC-A99A-8297997F809B} because it's missing its XML file!! (stt exists: True)
The date for document with OID {5A457892-5EAE-4E93-8BFB-45285816A589} was invalid (__/__/1979) - changed it to 01/01/1979
The date for document with OID {5A457892-5EAE-4E93-8BFB-45285816A589} was invalid (__/__/1979) - changed it to 01/01/1979
The date for document with OID {292B0233-F5D3-4CC8-B964-256B8B58CD99} was invalid (__/__/1973) - changed it to 01/01/1973
The date for document with OID {B41A3402-57A8-42ED-9DAD-AF4DB4ADE46C} was invalid (__/__/1976) - changed it to 01/01/1976
The date for document with OID {077A0AA4-5768-4815-AACD-3EFEDCEFE529} was invalid (__/__/1979) - changed it to 01/01/1979
The date for document with OID {F8B394D8-0E30-419D-AEC1-C972A9DB095F} was invalid (__/01/1975) - changed it to 01/01/1975
The date for document with OID {B1EE2069-74F2-4305-A78A-CCAB4E5A8193} was invalid (__/__/1976) - changed it to 01/01/1976
The date for document with OID {B1EE2069-74F2-4305-A78A-CCAB4E5A8193} was invalid (__/__/1976) - changed it to 01/01/1976

100%|██████████| 2/2 [00:04<00:00,  2.09s/it]
11it [00:07,  1.45s/it]

The date for document with OID {69A42ABD-196A-408E-9369-327E5455D3F5} was invalid (__/__/1975) - changed it to 01/01/1975
enquest - returning 996 documents, 2 were skipped due to missing necessary info.
 --> Adding 1111 to the out csv for enquest

PROCESSING PROGRAM forum (12/47) - 1 files:

100%|██████████| 1/1 [00:00<00:00,  2.54it/s]

Starting extracting 80 documents for program forum
Skipping document 2/80 with OID {B8B2EA61-7318-4C0F-A748-928C386C5C8F} because it's missing its XML file!! (stt exists: True)
Skipping document 7/80 with OID {1464A07B-A546-4B1B-9D1D-A2A4128AF91A} because it's missing its XML file!! (stt exists: False)
Skipping document 12/80 with OID {19B465C2-5832-4449-972A-0E2E94D801EC} because it's missing its XML file!! (stt exists: False)
Skipping document 13/80 with OID {B8B87301-D321-4BFF-85FD-58224B6FDBAD} because it's missing its XML file!! (stt exists: False)
Skipping document 14/80 with OID {35B50FC5-6425-44BB-94C7-6131E70314B4} because it's missing its XML file!! (stt exists: False)
Skipping document 15/80 with OID {D8A84F6F-DE38-4D90-BCD7-3CE387910F12} because it's missing its XML file!! (stt exists: False)
Skipping document 16/80 with OID {96ECDEB5-270E-4BA0-90B8-4CEF8354716A} because it's missing its XML file!! (stt exists: True)
Skipping document 19/80 with OID {EE0132B8-F3A0-4FBE-81CF-76358B2D01D7} because it's missing its XML file!! (stt exists: False)
Skipping document 20/80 with OID {7CBC4BD1-FC26-4828-9C9F-F216476C8FEF} because it's missing its XML file!! (stt exists: False)
Skipping document 22/80 with OID {8D245715-DEA8-4476-BAE6-06F5CC6940C2} because it's missing its XML file!! (stt exists: False)
Skipping document 23/80 with OID {6A372556-BE7F-46C8-B82D-9435CF0E079B} because it's missing its XML file!! (stt exists: False)
Skipping document 24/80 with OID {4571BAC4-C1D4-49F2-8BD5-79A38B88892E} because it's missing its XML file!! (stt exists: False)
Skipping document 25/80 with OID {8D78FE7E-76B1-47FF-B3B1-EDBBC27697BC} because it's missing its XML file!! (stt exists: False)
Skipping document 28/80 with OID {7E77F340-804C-4ED4-B7B4-694E44C59B86} because it's missing its XML file!! (stt exists: False)
Skipping document 31/80 with OID {156B724F-9FAE-439F-90E1-69D529ACD19A} because it's missing its XML file!! (stt exists: False)
Skipping document 32/80 with OID {BEB67DDB-C998-4B1E-AE08-89C81C8C304F} because it's missing its XML file!! (stt exists: False)
Skipping document 33/80 with OID {557ACCED-F540-4885-8BE3-DF240EECE82D} because it's missing its XML file!! (stt exists: False)
Skipping document 34/80 with OID {BFE826DC-9B0B-401C-9244-4776509487E5} because it's missing its XML file!! (stt exists: False)
Skipping document 43/80 with OID {30E99473-CC9F-4AF2-9FD3-AA3CC8257715} because it's missing its XML file!! (stt exists: False)
Skipping document 45/80 with OID {DB37748E-5C83-4A56-AC59-0C344E9AAB81} because it's missing its XML file!! (stt exists: False)
Skipping document 49/80 with OID {7FF09F60-61EB-445C-AAD1-E77B651BF8B2} because it's missing its XML file!! (stt exists: True)
Skipping document 50/80 with OID {2D168BAB-EBF5-4E38-8991-732EA008E2DB} because it's missing its XML file!! (stt exists: False)
Skipping document 53/80 with OID {A80273AC-643A-4CAB-A5CD-93EFEF24B30A} because it's missing its XML file!! (stt exists: False)
Skipping document 57/80 with OID {910F1226-BF0F-4E21-9E75-4FFAC79866EC} because it's missing its XML file!! (stt exists: True)
Skipping document 58/80 with OID {9B32D2E4-396E-454C-A1C3-0C4B0F4F7E1E} because it's missing its XML file!! (stt exists: True)
Skipping document 59/80 with OID {A22100AE-7E72-4677-91D2-D644E23353D4} because it's missing its XML file!! (stt exists: False)
Skipping document 61/80 with OID {D98BB21A-EBA3-4B41-A342-9829E9CCD046} because it's missing its XML file!! (stt exists: False)
Skipping document 67/80 with OID {1CD475BE-F118-42A7-96EE-E43AE4049E8E} because it's missing its XML file!! (stt exists: False)
Skipping document 70/80 with OID {9495D3EA-B520-4617-A1FC-1493BF31588C} because it's missing its XML file!! (stt exists: False)
Skipping document 73/80 with OID {F740CC41-C033-4C4A-8F81-BDCBA917C63B} because it's missing its XML file!! (stt exists: False)
Skipping document 76/80 with OID {84755A35-28CB-434A-B6C1-D071E8C80422} because it's missing its XML file!! (stt exists: False)
Skipping document 77/80 with OID {E4BB421C-E5DD-4123-B0FD-D8EC3F1728FB} because it's missing its XML file!! (stt exists: False)
Skipping document 80/80 with OID {4544F592-6793-4EBF-B795-32E5CE7C384E} because it's missing its XML file!! (stt exists: True)
forum - returning 47 documents, 33 were skipped due to missing necessary info.

12it [00:08,  1.18s/it]

 --> Adding 47 to the out csv for forum

PROCESSING PROGRAM forum_lau (13/47) - 1 files:

100%|██████████| 1/1 [00:00<00:00, 11.16it/s]
13it [00:08,  1.14it/s]

Starting extracting 28 documents for program forum_lau
Skipping document 2/28 with OID {7C1DE208-F419-4484-9489-AED83DD6B1F0} because it's missing its XML file!! (stt exists: False)
Skipping document 3/28 with OID {F11EBA74-C46B-431C-9D7D-BF1ED2A4BCE9} because it's missing its XML file!! (stt exists: False)
Skipping document 4/28 with OID {CD9F154A-2878-451A-8FB5-F34E70D350BB} because it's missing its XML file!! (stt exists: False)
Skipping document 5/28 with OID {86A033D0-646C-4A86-B05E-FF262329F637} because it's missing its XML file!! (stt exists: False)
Skipping document 6/28 with OID {62AA878D-49E0-4FC0-8B20-182966FAE995} because it's missing its XML file!! (stt exists: False)
Skipping document 7/28 with OID {BB0F80E8-03D3-42D0-AE2D-20CE880262D7} because it's missing its XML file!! (stt exists: False)
Skipping document 8/28 with OID {C175FE3A-3714-48CC-8C1C-A478E4784711} because it's missing its XML file!! (stt exists: False)
Skipping document 10/28 with OID {EA2B2B6D-05F9-42CD-962B-7D9DC3ABDC2C} because it's missing its XML file!! (stt exists: False)
Skipping document 11/28 with OID {794B6CD6-617A-4D54-8325-0B0E1F640B73} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {217FF2D2-0827-439B-BFA1-B40EE57D5528}. Trying to use the recording date. doc_dict: {'alias': 'forum_lau', 'date_str': None, 'stt_filename': '217FF2D2-0827-439B-BFA1-B40EE57D5528_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{217FF2D2-0827-439B-BFA1-B40EE57D5528}', 'stripped_OID': '217FF2D2-0827-439B-BFA1-B40EE57D5528', 'login': '', 'broadcast_episode_title': "Forum Radio-Lausanne. D?bat sur la bombe atomique apr?s les bombardements atomiques d'Hiroshima et Nagasaki [son retravaill?]", 'sequence': '1', 'broadcast_program_name': 'Forum de Radio-Lausanne', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '28.05.2018 09:09:31', 'physical_support_history': "Cotes d'origine: Disques 78T maison Radio-Lausanne 18415, 18416, 18417, 18418, 18419, 18420", 'production_type': 'Production propre', 'recording_place': 'Studio Radio-Lausanne', 'rights_notes': 'Memoriav 2017 (135-140)', 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': "[n.134-140 : Montage simple et complet, ? 7'30'': silence de 5 secondes]. (11:53) Colonel de Montmollin. (15:50) Edmond Jaloux. (22:43) Charles Schurch.", 'workflow_status': 'Valid?', 'assembly_status': 'PAD', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Burnier, Edouard', 'function': 'Interview?/e', 'role': 'professeur'}, {'name': 'Perrier, Albert', 'function': 'Interview?/e', 'role': "professeur de physique ? l'Universit? de Lausanne"}, {'name': 'Gaillard, Jean-Jacques', 'function': 'Interview?/e', 'role': 'pasteur'}, {'name': 'Jaloux, Edmond', 'function': 'Interview?/e', 'role': '?crivain'}, {'name': 'Schurch, Charles', 'function': 'Interview?/e', 'role': "secr?taire de l'Union syndicale suisse"}, {'name': 'Montmollin, Louis de', 'function': 'Interview?/e', 'role': "colonel, commandant de corps et chef d'?tat-major g?n?ral"}, {'name': 'Romieux, Benjamin', 'function': 'Intervieweur/euse', 'role': 'collaborateur Radio-Lausanne'}], 'geographical_descriptors': ['Nagasaki', 'Hiroshima', 'Japon'], 'person_descriptors': None, 'thematical_descriptors': ['arme atomique', 'guerre mondiale (deuxi?me)', 'arme nucl?aire', 'guerre mondiale (premi?re)'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Radio-Lausanne'], 'subdomains': ['D?bat'], 'recording_dates': ['01/02/1946 - 01/02/1946'], 'first_broadcast_dates': None}
Skipping document 13/28 with OID {F1645102-4991-45A6-9F0E-D28A8EBC080B} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {E82762CC-F588-4716-95D9-BB6CEDE781C9}. Trying to use the recording date. doc_dict: {'alias': 'forum_lau', 'date_str': None, 'stt_filename': 'E82762CC-F588-4716-95D9-BB6CEDE781C9_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{E82762CC-F588-4716-95D9-BB6CEDE781C9}', 'stripped_OID': 'E82762CC-F588-4716-95D9-BB6CEDE781C9', 'login': '', 'broadcast_episode_title': "La lassitude du peuple suisse ? l'?gard de l'aide aux r?fugi?s en Europe", 'sequence': '1', 'broadcast_program_name': 'Forum de Radio-Lausanne', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '07.05.2022 05:13:46', 'physical_support_history': 'Disques 78T maison Radio-Lausanne 347 Gf A + 348 Gf A', 'production_type': 'Production propre', 'recording_place': 'Lausanne (Studio Radio-Lausanne)', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': '(0.15? 1.41): Professeur Secr?tan, ? propos de la lassitude vis-?-vis des r?fugi?s. (2.25 ? 5.30): Ma?tre ?: Il faut faire une distinction entre les ?migrants entr?s en Suisse au milieu de la guerre en 1942, afin de pr?parer leur d?part outre-mer, et les r?fugi?s qui ?taient ? la charge d\'organisations priv?es. Nombre de gens qui sont chez nous actuellement sont des vieillards et des enfants orphelins qui souhaitent passer le reste de leur vie en Suisse. (5.31): M. "Tout le monde" (= repr?sentant l\'opinion publique): "Il y a trop d\'?trangers, ne peut-on pas inviter poliment mais fermement un certain nombre de ces r?fugi?s ? prendre plus rapidement le chemin d\'outre-mer? R?ponse de Ma?tre ?: Tout sera fait pour retrouver la famille d\'un r?fugi? afin qu\'il puisse rentrer chez lui. Mais si nous nous trouvons en pr?sence de personnes qui ont tout perdu, leur famille, leur biens mat?riels, leur sant?, nous ne pouvons pas les renvoyer, personne ne les accepteraient. Roger Nordmann apporte un t?moignage personnel d\'une visite qu\'il vient d\'effectuer ? La Nich?e, institution du Mont P?lerin abritant des enfants de r?fugi?s. (8.06): M. "Tout le monde" : J\'ai entendu dire qu\'? l\'universit? les ?tudiants suisses doivent laisser la place ? des r?fugi?s ?trangers et n\'ont pas acc?s aux laboratoires, ils n\'ont que les derniers si?ges, on donne toujours la premi?re place aux ?trangers. On abuse, on va trop loin. (8.30 ? 10.02): M. Secr?tan: "Il s\'agit d\'un bobard! Il y a m?me un journal lausannois qui a publi? sur ce sujet. Il s\'agit d\'une rumeur qui est fausse car les ?tudiants suisses ont toujours pass? avant les r?fugi?s. Lorsque nous avons eu cet afflux de r?fugi?s, nous n\'avons accept? que le nombre de r?fugi?s qui ne g?naient pas les ?tudes de nos ?tudiants.  (10.03): Ma?tre ? parle de la loi en discussion ? l\'assembl?e f?d?rale, loi modifiant et compl?tant la loi sur le s?jour de l\'?tablissement des ?trangers. Des personnalit?s politiques, des savants ont pu b?n?ficier de l\'hospitalit? suisse. (16.08): Mme "Tout le monde": Pourquoi faut-il avoir encore des comit?s, des personnes qui travaillent dans ces comit?s que l\'on doit payer, et organiser des collectes? Ces r?fugi?s sont en situation ill?gale. S\'ils ne peuvent pas rentrer chez eux pourquoi ne pas les nationaliser (=naturaliser), tout cela cr?e des frais inutiles. (17.22): R?ponse de l\'avocat ?voquant l\'Arr?t? du 7 mars 1947 en vigueur. (19.25): Roger Nordmann donne la parole ? Mlle Vallotton qui annonce que tous les comit?s d\'aide aux r?fugi?s attendent avec impatience de l\'argent car les fonds recueillis ne suffisent pas ? les entretenir.', 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:22:31.904', 'work_duration_compl': 'Non', 'participants': [{'name': 'Inconnu', 'function': 'Interview?/e', 'role': 'professeur Secretan'}, {'name': 'Inconnu', 'function': 'Interview?/e', 'role': 'avocat'}, {'name': 'Inconnu', 'function': 'Interview?/e', 'role': "M. Tout le monde, repr?sentant l'opinion publique"}, {'name': 'Inconnue', 'function': 'Interview?/e', 'role': "Mlle Tout le monde, repr?sentant l'opinion publique"}, {'name': 'Vallotton, Paul', 'function': 'Interview?/e', 'role': 'collaboratrice Radio-Lausanne'}, {'name': 'Nordmann, Roger (homme de radio)', 'function': 'Intervieweur/euse', 'role': 'collaborateur Radio-Lausanne'}], 'geographical_descriptors': ['Buchenwald', 'Bergen-Belsen', 'France', 'Italie'], 'person_descriptors': None, 'thematical_descriptors': ['guerre mondiale (deuxi?me)', 'camp de concentration', 'r?fugi?', 'x?nophobie', "droit d'asile", 'collecte', 'aide humanitaire'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Radio Sottens'], 'subdomains': ['D?bat'], 'recording_dates': ['29/06/1948 - 29/06/1948'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {0C20BAAC-C093-42BC-A1B4-0CB04B64765D}. Trying to use the recording date. doc_dict: {'alias': 'forum_lau', 'date_str': None, 'stt_filename': '0C20BAAC-C093-42BC-A1B4-0CB04B64765D_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{0C20BAAC-C093-42BC-A1B4-0CB04B64765D}', 'stripped_OID': '0C20BAAC-C093-42BC-A1B4-0CB04B64765D', 'login': '', 'broadcast_episode_title': "La lassitude du peuple suisse et l'Aide suisse ? l'Europe", 'sequence': '1', 'broadcast_program_name': 'Forum de Radio-Lausanne', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '23.07.2022 03:38:24', 'physical_support_history': 'Disques 78T maison Radio-Lausanne 343 Gf B + 344 Gf B', 'production_type': 'Production propre', 'recording_place': 'Lausanne (Studio Radio-Lausanne)', 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': '(0.55 ? 4.08): M. "Opinion publique": les collectes sont trop nombreuses, la publicit? n\'est pas bien faite car souvent on ignore le num?ro du compte de ch?que postal, les ouvriers se plaignent d\'?tre trop souvent sollicit?s et trouvent que cela tourne en imp?t (proposition a ?t? faite ? tous, ouvriers, patrons, ind?pendants... de verser l\'?quivalent d\'une journ?e de salaire, ? titre indicatif). (4.12 ? 5.50): R. Nordmann: Il y a eu effectivement une erreur ou un manque de psychologie, car certains fonctionnaires ont ?t? presque "tax?s" et la collecte a ?t? tellement bien organis?e que les gens ont cru qu\'elle ?tait obligatoire. M. Olgiati s\'exprime ? ce sujet. (5.56 ? 8.50): M. "Opinion publique": la Cha?ne du bonheur fond?e par M. Nordmann a le m?rite de dire aux gens o? va leur argent ce qui n\'est pas le cas des collectes dont on parle. Explications de Ma?tre Gaillard. (9.03): R. Nordmann "Ce n\'est pas tr?s chic de comparer la Cha?ne du bonheur ? l\'Aide suisse ? l\'Europe". (9.50) : Marc Maison de la Croix-Rouge suisse pr?cise que la campagne lanc?e a pour but de construire un centre de transfusion sanguin. Il explique les frais g?n?raux entra?n?s par de telles campagnes. (12.31): M. "Opinion publique": Exige que les gens soient mieux inform?s et assur?s que leur argent arrive directement aux personnes n?cessiteuses. Souci que les journalistes fassent trop de voyages et que le salaire des personnes travaillant pour ces r?coltes de don soit trop important. R?ponse de R. Nordmann et intervention de Ma?tre Gaillard qui s\'explique ? propos de son salaire. (14.52): Que pensez-vous de l\'aide b?n?vole? (16.18): M. Olgiati: "Nous ne pouvons pas nous d?sint?resser du sort des pays voisins de la Suisse". Conclusion de Roger Nordmann.', 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:19:24.640', 'work_duration_compl': 'Non', 'participants': [{'name': 'Gaillard', 'function': 'Interview?/e', 'role': "avocat, responsable pour la Suisse romande de la collecte de l'Aide suisse ? l'Europe"}, {'name': 'Olgiati', 'function': 'Interview?/e', 'role': 'directeur du Don suisse'}, {'name': 'Maison, Marc', 'function': 'Interview?/e', 'role': 'pr?sident de la section de Lausanne de la Croix-Rouge suisse'}, {'name': 'Inconnu', 'function': 'Interview?/e', 'role': "repr?sentant de l'opinion publique"}, {'name': 'Nordmann, Roger (homme de radio)', 'function': 'Intervieweur/euse', 'role': 'collaborateur Radio-Lausanne'}], 'geographical_descriptors': ['Suisse', 'Europe'], 'person_descriptors': ["Aide suisse ? l'Europe", 'Cha?ne du bonheur', 'Secours suisse aux enfants (Le)', 'Croix-Rouge suisse', 'Don suisse'], 'thematical_descriptors': ['aide humanitaire', 'organisation humanitaire', 'collecte', 'b?n?volat'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Radio Sottens'], 'subdomains': ['D?bat'], 'recording_dates': ['__/05/1948 - __/05/1948'], 'first_broadcast_dates': None}
The date for document with OID {0C20BAAC-C093-42BC-A1B4-0CB04B64765D} was invalid (__/05/1948) - changed it to 01/05/1948
The date for document with OID {0C20BAAC-C093-42BC-A1B4-0CB04B64765D} was invalid (__/05/1948) - changed it to 01/05/1948
Skipping document 20/28 with OID {4730D4DB-8851-4D76-B2B8-3B759166F973} because it's missing its XML file!! (stt exists: False)
Skipping document 22/28 with OID {3DC8A76C-5995-41DA-ADA3-6290DFDADDE8} because it's missing its XML file!! (stt exists: False)
Skipping document 23/28 with OID {765E73DE-7F0D-48ED-8344-8A15366DD811} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {5B033B9A-8A9D-4BDD-B2A5-5F73C461D415}. Trying to use the recording date. doc_dict: {'alias': 'forum_lau', 'date_str': None, 'stt_filename': '5B033B9A-8A9D-4BDD-B2A5-5F73C461D415_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{5B033B9A-8A9D-4BDD-B2A5-5F73C461D415}', 'stripped_OID': '5B033B9A-8A9D-4BDD-B2A5-5F73C461D415', 'login': '', 'broadcast_episode_title': "L'industrialisation de l'architecture moderne. R?union ? Lausanne le 28 juin 1948 de l'Union internationale des architectes (UIA), pr?sid?e par Sir Patrick Abercrombie", 'sequence': '1', 'broadcast_program_name': 'Forum de Radio-Lausanne', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '20.07.2022 13:04:16', 'physical_support_history': 'Disques 78T maison Radio-Lausanne 347Gf B, 348 Gf B', 'production_type': 'Production propre', 'recording_place': 'Lausanne (Studio Radio-Lausanne)', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': "L'UIA a ?t? cr??e afin d'unir les architectes de tous les pays du monde, sans distinction de nationalit?, de race, de religion ou de doctrine architecturale, et f?d?rer leurs organisations nationales. (0.38 ? 1.58): Patrick Abercrombie, pr?sident de l'UIA, ? propos des buts de cette premi?re rencontre internationale : la cr?ation de l'UIA et la recherche des meilleurs moyens que les architectes peuvent apporter pour la reconstruction de l'Europe apr?s les d?g?ts d?s ? la guerre. (2.00 ? 4.54) : Architecte fran?ais ? propos de la pr?fabrication et l'industrialisation des b?timents. (4.57 ? 5.45) : D?l?gu? de Sofia. (5.50 ? 7.28) : D?l?gu? am?ricain. 7.38 : D?l?gu? fran?ais: Qu'est-ce que l'industrialisation du b?timent?  Il faut revoir la gestion des chantiers : rationnaliser par exemple en construisant les fen?tres, les portes en s?rie afin de r?duire les co?ts et le gaspillage de temps. 11.41 : D?l?gu? de Sofia. 15.45 : La politique a-t-elle divis? les congressistes? 17.18 : La fabrication en s?rie ne va-t-elle pas nuire ? la cr?ativit? des architectes ?", 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:23:14.400', 'work_duration_compl': 'Non', 'participants': [{'name': 'Abercrombie, Patrick', 'function': 'Interview?/e', 'role': "pr?sident de l'UIA, Union internatinoale des architectes"}, {'name': 'Inconnu', 'function': 'Interview?/e', 'role': 'd?l?gu? bulgare de Sofia'}, {'name': 'Inconnu', 'function': 'Interview?/e', 'role': 'd?l?gu? fran?ais'}, {'name': 'Nordmann, Roger (homme de radio)', 'function': 'Intervieweur/euse', 'role': 'collaborateur Radio-Lausanne'}], 'geographical_descriptors': ['Lausanne', 'France', 'Etats-Unis', 'Bulgarie', 'Europe'], 'person_descriptors': ['UIA (Union Internationale des Architectes)'], 'thematical_descriptors': ['r?union internationale', 'guerre mondiale (deuxi?me)', 'architecture', 'reconstruction', 'urbanisme'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Radio Sottens'], 'subdomains': ['D?bat'], 'recording_dates': ['30/06/1948 - 30/06/1948'], 'first_broadcast_dates': None}
The date for document with OID {CCC74626-56BD-4919-ADA6-A3B677F0277D} was invalid (__/12/1961) - changed it to 01/12/1961
Skipping document 26/28 with OID {D7A1F792-4B52-4334-BD2C-3799DEA5D02C} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {ABB6D4B2-5AB6-4B71-9E9E-A0C5C41EABB5}. Trying to use the recording date. doc_dict: {'alias': 'forum_lau', 'date_str': None, 'stt_filename': 'ABB6D4B2-5AB6-4B71-9E9E-A0C5C41EABB5_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{ABB6D4B2-5AB6-4B71-9E9E-A0C5C41EABB5}', 'stripped_OID': 'ABB6D4B2-5AB6-4B71-9E9E-A0C5C41EABB5', 'login': '', 'broadcast_episode_title': 'Pour ou contre la hausse des loyers', 'sequence': '1', 'broadcast_program_name': 'Forum de Radio-Lausanne', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '22.07.2022 18:57:03', 'physical_support_history': 'Disques 78T maison Radio-Lausanne 343 Gf A + 344 Gf A', 'production_type': 'Production propre', 'recording_place': 'Lausanne (Studio Radio-Lausanne)', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:19:23.018', 'work_duration_compl': 'Non', 'participants': [{'name': 'Bassin', 'function': 'Interview?/e', 'role': 'repr?sentant des locataires'}, {'name': 'Carrard (Madame) [ortho?]', 'function': 'Interview?/e', 'role': "secr?taire-adjointe du Comit? de l'Alliance nationale des soci?t?s f?minines suisses"}, {'name': 'Pfund', 'function': 'Interview?/e', 'role': 'pr?sident de la F?d?ration romande des int?r?ts immobiliers'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': ['logement', 'protection des locataires', 'crise ?conomique', 'industrie automobile'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Radio Sottens'], 'subdomains': ['D?bat'], 'recording_dates': ['__/05/1948 - __/05/1948'], 'first_broadcast_dates': None}
The date for document with OID {ABB6D4B2-5AB6-4B71-9E9E-A0C5C41EABB5} was invalid (__/05/1948) - changed it to 01/05/1948
The date for document with OID {ABB6D4B2-5AB6-4B71-9E9E-A0C5C41EABB5} was invalid (__/05/1948) - changed it to 01/05/1948
Skipping document 28/28 with OID {83FD428B-1B48-48C4-9347-FBC9F5262563} because it's missing its XML file!! (stt exists: False)
forum_lau - returning 13 documents, 15 were skipped due to missing necessary info.
 --> Adding 13 to the out csv for forum_lau

PROCESSING PROGRAM geneve_info (14/47) - 1 files:

Starting extracting 29 documents for program geneve_info
Skipping document 7/29 with OID {4BA4914F-E47C-46B5-A511-FE934E4BCBED} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {F4C49936-ADB8-4332-B191-0FED38AD182F}. Trying to use the recording date. doc_dict: {'alias': 'geneve_info', 'date_str': None, 'stt_filename': 'F4C49936-ADB8-4332-B191-0FED38AD182F_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{F4C49936-ADB8-4332-B191-0FED38AD182F}', 'stripped_OID': 'F4C49936-ADB8-4332-B191-0FED38AD182F', 'login': '', 'broadcast_episode_title': "Interview de Charles Towns; professeur de physique ? l'universit? Columbia (2/2) : Exp?rience pr?vue avec l'horloge atomique sur les origines de l'univers", 'sequence': '1', 'broadcast_program_name': 'Gen?ve vous informe', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '19.03.2020 15:32:41', 'physical_support_history': "Cote d'origine: MA 58.38 PL. E.", 'production_type': 'Production propre', 'recording_place': 'New-York', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': "Il souhaite v?rifier que l'univers est en expansion constante : l'effet Doppler.", 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:05:43.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Towns, Charles', 'function': 'Interview?/e', 'role': "professeur de physique ? l'universit? Columbia"}, {'name': 'Besnard, Max', 'function': 'Intervieweur/euse', 'role': 'collaborateur/trice RSR'}], 'geographical_descriptors': ['New-York'], 'person_descriptors': None, 'thematical_descriptors': ['physique', 'horloge', 'temps (physique)', 'lumi?re'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Premier programme'], 'subdomains': ['Interview'], 'recording_dates': ['10/11/1958 - 10/11/1958'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {B3D17909-A270-4BC8-A786-39F1E8290F19}. Trying to use the recording date. doc_dict: {'alias': 'geneve_info', 'date_str': None, 'stt_filename': 'B3D17909-A270-4BC8-A786-39F1E8290F19_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{B3D17909-A270-4BC8-A786-39F1E8290F19}', 'stripped_OID': 'B3D17909-A270-4BC8-A786-39F1E8290F19', 'login': '', 'broadcast_episode_title': 'Interview de Joseph Szigeti, violoniste', 'sequence': '1', 'broadcast_program_name': 'Gen?ve vous informe', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '24.02.2020 16:07:02', 'physical_support_history': "Cote d'origine: MA 58.38 PL. H.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': "Le violon signification ?motive chez les Hongrois, c'est l'instrument des nomades. Son violon. D?s 3.50 musique.", 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:09:25.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Szigeti, Joseph', 'function': 'Interview?/e', 'role': 'violoniste'}, {'name': 'Lorrain, Marine', 'function': 'Intervieweur/euse', 'role': 'collaborateur/trice RSR'}], 'geographical_descriptors': ['Hongrie'], 'person_descriptors': ['Szigeti, Joseph'], 'thematical_descriptors': ['violon', 'instrumentiste'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Radio Sottens'], 'subdomains': ['Interview'], 'recording_dates': ['14/11/1958 - 14/11/1958'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {806FB8A0-62D9-4CF5-B28C-C0C9CDDF9CCB}. Trying to use the recording date. doc_dict: {'alias': 'geneve_info', 'date_str': None, 'stt_filename': '806FB8A0-62D9-4CF5-B28C-C0C9CDDF9CCB_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{806FB8A0-62D9-4CF5-B28C-C0C9CDDF9CCB}', 'stripped_OID': '806FB8A0-62D9-4CF5-B28C-C0C9CDDF9CCB', 'login': '', 'broadcast_episode_title': 'Interview de la compositrice vaudoise Andr?e Rochat', 'sequence': '1', 'broadcast_program_name': 'Gen?ve vous informe', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '14.08.2018 11:11:22', 'physical_support_history': "Cote d'origine: MA 58.38 Pl. I. Attention pas de son entre 5.05 et 5.15!", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': 'Sa vocation de composer lui vient de l\'enfance. A ?tudi? le contrepoint en dehors de ses ?tudes de piano. La r?v?lation vient avec la composition "Pierrot lunaire" d\'Arnod Schoenberg. Elle compose avant tout de la musique de chambre. Andr?e Rochat habite en Italie. (4.51) Extrait de l\'oeuvre "Chants d\'outre-mer". !! Pas de son entre 5.05 et 5.15 !!', 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:06:21.756', 'work_duration_compl': 'Non', 'participants': [{'name': 'Rochat, Andr?e', 'function': 'Interview?/e', 'role': 'compositrice'}, {'name': 'Lorrain, Marine', 'function': 'Intervieweur/euse', 'role': 'collaboratrice Radio-Gen?ve'}], 'geographical_descriptors': None, 'person_descriptors': ['Rochat, Andr?e'], 'thematical_descriptors': ['compositrice', 'composition musicale'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Radio-Gen?ve'], 'subdomains': ['Interview'], 'recording_dates': ['17/11/1958 - 17/11/1958'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {95B640BB-2E7A-4883-843F-BCA61B284714}. Trying to use the recording date. doc_dict: {'alias': 'geneve_info', 'date_str': None, 'stt_filename': '95B640BB-2E7A-4883-843F-BCA61B284714_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{95B640BB-2E7A-4883-843F-BCA61B284714}', 'stripped_OID': '95B640BB-2E7A-4883-843F-BCA61B284714', 'login': '', 'broadcast_episode_title': "Interview de l'essayiste, historien et romancier fran?ais Andr? Chamson, de l'Acad?mie fran?aise", 'sequence': '1', 'broadcast_program_name': 'Gen?ve vous informe', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '24.02.2020 16:07:02', 'physical_support_history': "Cote d'origine: MA 58.38 Pl. J", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': "Les ?crivains ?lus ? l'Acad?mie fran?aise sont plus ?g?s. (8:45) Les raisons pour lesquelles les femmes ne sont pas ?lues ? l'Acad?mie. (12:15) Quelle est l'?volution du roman et de la po?sie? (16.45) musique. Emulation f?conde due au cotoiement de belles personnalit?s.", 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:19:03.000', 'work_duration_compl': 'Non', 'geographical_descriptors': ['France'], 'person_descriptors': ['Chamson, Andr?', 'Acad?mie fran?aise', 'Colette'], 'thematical_descriptors': ['?crivain', '?crivaine', 'historien', 'vieillesse', 'jeunesse', '?criture', 'ann?es 1920', 'roman', 'langue fran?aise'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Radio-Gen?ve'], 'subdomains': ['Interview'], 'recording_dates': ['19/11/1958 - 19/11/1958'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {9EEA654D-952F-4F16-8516-8C5E3B7E859E}. Trying to use the recording date. doc_dict: {'alias': 'geneve_info', 'date_str': None, 'stt_filename': '9EEA654D-952F-4F16-8516-8C5E3B7E859E_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{9EEA654D-952F-4F16-8516-8C5E3B7E859E}', 'stripped_OID': '9EEA654D-952F-4F16-8516-8C5E3B7E859E', 'login': '', 'broadcast_episode_title': 'Interview de Ren? Helg, chef du d?partement de justice et police du canton de Gen?ve : A propos de son d?partement', 'sequence': '1', 'broadcast_program_name': 'Gen?ve vous informe', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '12.05.2020 10:51:57', 'physical_support_history': "Cote d'origine: MA 60.37 PL. E.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:17:09.608', 'work_duration_compl': 'Non', 'participants': [{'name': 'Helg, Ren?', 'function': 'Interview?/e', 'role': 'chef du d?partement de justice et police du canton de Gen?ve'}, {'name': 'Bauer, Bernard', 'function': 'Intervieweur/euse', 'role': 'collaborateur/trice RSR'}], 'geographical_descriptors': ['Gen?ve (canton)', 'Gen?ve (ville)'], 'person_descriptors': None, 'thematical_descriptors': ['justice', 'police', 'circulation routi?re', 'parking'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Premier programme'], 'subdomains': ['Interview'], 'recording_dates': ['23/03/1960 - 23/03/1960'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {E2ED4656-161B-4E9B-A132-340E9633F67D}. Trying to use the recording date. doc_dict: {'alias': 'geneve_info', 'date_str': None, 'stt_filename': 'E2ED4656-161B-4E9B-A132-340E9633F67D_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{E2ED4656-161B-4E9B-A132-340E9633F67D}', 'stripped_OID': 'E2ED4656-161B-4E9B-A132-340E9633F67D', 'login': '', 'broadcast_episode_title': "Interview de Serge Lifar, danseur et chor?graphe : Sur son d?part de l'Op?ra de Paris", 'sequence': '1', 'broadcast_program_name': 'Gen?ve vous informe', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '15.01.2020 16:31:35', 'physical_support_history': "Cote d'origine: MA 58.38 PL. F.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': "L'abandonne apr?s 29 ans, car il d?nonce le manque de professionnalisme de personnes arriv?es dans la maison et qui l'on transform?e en un march?.", 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:06:29.147', 'work_duration_compl': 'Non', 'participants': [{'name': 'Lifar, Serge', 'function': 'Interview?/e', 'role': 'danseur, chor?graphe'}, {'name': 'Roch, Fran?ois-Achille', 'function': 'Intervieweur/euse', 'role': 'collaborateur/trice RSR'}], 'geographical_descriptors': None, 'person_descriptors': ['Lifar, Serge', 'Op?ra de Paris'], 'thematical_descriptors': ['danse (art chor?graphique)', 'chor?graphie', 'op?ra (b?timent)'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Radio Sottens'], 'subdomains': ['Interview'], 'recording_dates': ['10/11/1958 - 10/11/1958'], 'first_broadcast_dates': None}

100%|██████████| 1/1 [00:00<00:00, 10.90it/s]
14it [00:08,  1.53it/s]

Did not find any date for doc with OID {C48C7DCD-9127-40E1-81FD-E37A130B4376}. Trying to use the recording date. doc_dict: {'alias': 'geneve_info', 'date_str': None, 'stt_filename': 'C48C7DCD-9127-40E1-81FD-E37A130B4376_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{C48C7DCD-9127-40E1-81FD-E37A130B4376}', 'stripped_OID': 'C48C7DCD-9127-40E1-81FD-E37A130B4376', 'login': '', 'broadcast_episode_title': 'La troisi?me force : Commentaire Alexandre Metaxas, journaliste', 'sequence': '1', 'broadcast_program_name': 'Gen?ve vous informe', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '03.02.2020 12:01:48', 'physical_support_history': "Cote d'origine: MA 58.38 PL. G.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': "Les pays qui constituent ce groupe souhaiteraient service d'interm?diaire entre les blocs capitaliste et communiste.", 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:09:23.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Metaxas, Alexandre', 'function': 'Interview?/e', 'role': 'collaborateur/trice RSR'}, {'name': 'Darmsteter, Jean-Paul', 'function': 'Intervieweur/euse', 'role': 'collaborateur/trice RSR'}], 'geographical_descriptors': ['Inde', 'Japon', 'Indon?sie', 'Egypte'], 'person_descriptors': None, 'thematical_descriptors': ['relations internationales', 'diplomatie', 'guerre froide', 'communisme', '?conomie capitaliste'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Radio Sottens'], 'subdomains': ['Commentaire'], 'recording_dates': ['12/11/1958 - 12/11/1958'], 'first_broadcast_dates': None}
geneve_info - returning 28 documents, 1 were skipped due to missing necessary info.
 --> Adding 28 to the out csv for geneve_info

PROCESSING PROGRAM hist_ondes (15/47) - 1 files:

Starting extracting 9 documents for program hist_ondes
Skipping document 5/9 with OID {7748497C-639B-491F-8B16-61762F50386D} because it's missing its XML file!! (stt exists: False)
Skipping document 6/9 with OID {68734C5E-1721-4E8A-8C7A-D13CE1B68053} because it's missing its XML file!! (stt exists: False)

100%|██████████| 1/1 [00:00<00:00, 18.17it/s]

hist_ondes - returning 7 documents, 2 were skipped due to missing necessary info.
 --> Adding 7 to the out csv for hist_ondes

PROCESSING PROGRAM infopile (16/47) - 1 files:

Starting extracting 198 documents for program infopile
Skipping document 1/198 with OID {7E1453BE-3EF7-423B-9147-BE25DC3348E9} because it's missing its XML file!! (stt exists: True)
Skipping document 7/198 with OID {C5AF20CA-9699-455B-A8AD-2847051D73A1} because it's missing its XML file!! (stt exists: False)
Skipping document 8/198 with OID {1331710F-85D5-4767-87E4-3F9172A92C64} because it's missing its XML file!! (stt exists: False)
Skipping document 9/198 with OID {00D21B01-8F78-4F8A-AA3C-1ABC07F8BB93} because it's missing its XML file!! (stt exists: False)
Skipping document 10/198 with OID {DC22379F-AAEF-4591-952E-1EAC3FC12A2A} because it's missing its XML file!! (stt exists: False)
Skipping document 11/198 with OID {81429DE6-4E49-46E8-933B-54670E811A89} because it's missing its XML file!! (stt exists: False)
Skipping document 13/198 with OID {1BDD195F-BDCA-4894-9E9F-19F7ADBACC63} because it's missing its XML file!! (stt exists: True)
Skipping document 15/198 with OID {F4AF053D-F916-4B1D-A41E-0C4FD1FCEF84} because it's missing its XML file!! (stt exists: True)
Did not find any date for doc with OID {12B77B0D-6CF3-4F45-ADD0-0D0A3E1E3B2B}. Trying to use the recording date. doc_dict: {'alias': 'infopile', 'date_str': None, 'stt_filename': '12B77B0D-6CF3-4F45-ADD0-0D0A3E1E3B2B_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{12B77B0D-6CF3-4F45-ADD0-0D0A3E1E3B2B}', 'stripped_OID': '12B77B0D-6CF3-4F45-ADD0-0D0A3E1E3B2B', 'login': '', 'broadcast_episode_title': "Affaire Elisabeth Kopp : Verdict du proc?s d'Elisabeth Kopp, ancienne conseill?re f?d?rale : Commentaire d'Yves Seydoux, collaborateur RSR", 'sequence': '1', 'broadcast_program_name': 'Info-pile', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'comtesi', 'modified_on': '11.06.2022 12:02:52', 'physical_support_history': "Cote d'origine: 26537 Pl. 6.", 'production_type': 'Production propre', 'recording_place': 'Lausanne', 'rights_notes': 'Memoriav. (SRG 75)', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:01:01.853', 'work_duration_compl': 'Non', 'participants': [{'name': 'Seydoux, Yves', 'function': 'Commentateur/trice', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Suisse'], 'person_descriptors': ['Kopp, Elisabeth'], 'thematical_descriptors': ['conseiller f?d?ral', 'femme', 'proc?s', '?v?nement du 20e si?cle'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Commentaire'], 'recording_dates': ['23/02/1990 - 23/02/1990'], 'first_broadcast_dates': None}
Skipping document 18/198 with OID {8D549D90-1A0D-444B-97E9-81929F534417} because it's missing its XML file!! (stt exists: False)
Skipping document 20/198 with OID {5EEB7C15-1BD0-455F-B87D-1F8B149DDDD0} because it's missing its XML file!! (stt exists: False)
Skipping document 21/198 with OID {5E5C47CC-C679-4B32-B35D-7A0535E71E08} because it's missing its XML file!! (stt exists: False)
Skipping document 23/198 with OID {36BD5D93-39F5-449C-B78A-547200C5EF7F} because it's missing its XML file!! (stt exists: False)
Skipping document 25/198 with OID {F80CD5D7-014A-4C2F-9AE8-B2330EF3F724} because it's missing its XML file!! (stt exists: False)
Skipping document 27/198 with OID {D0F0CF3E-3097-4B66-A72B-CD663835A154} because it's missing its XML file!! (stt exists: True)
Skipping document 28/198 with OID {3246573A-4354-41BC-B586-E3DE0BE042FF} because it's missing its XML file!! (stt exists: True)
Skipping document 29/198 with OID {C256AC8A-21DD-438D-BA73-C01C8E8FBCA2} because it's missing its XML file!! (stt exists: True)
Skipping document 32/198 with OID {B7C81A47-92A8-4B4F-85C5-1F460C096FE1} because it's missing its XML file!! (stt exists: True)
Skipping document 35/198 with OID {034C9A61-EA83-47ED-ACA9-61AE2F1E7689} because it's missing its XML file!! (stt exists: False)
Skipping document 37/198 with OID {DC4D3A8C-026C-4CCA-BE81-7DDB5870B615} because it's missing its XML file!! (stt exists: False)
Skipping document 39/198 with OID {8D1DE05B-1E68-4CD3-B977-57265FE0BB4F} because it's missing its XML file!! (stt exists: False)
Skipping document 40/198 with OID {05BBE7BF-6658-4B82-A4CE-8E339143A87E} because it's missing its XML file!! (stt exists: False)
Skipping document 43/198 with OID {2364D68D-B6B0-44F6-836B-149AD84653E4} because it's missing its XML file!! (stt exists: True)
Skipping document 44/198 with OID {B00DD6D1-AB64-4CBC-9189-67BB2ED7F964} because it's missing its XML file!! (stt exists: True)
Skipping document 46/198 with OID {DE13EDB0-D146-4B67-8B15-684417DED4FB} because it's missing its XML file!! (stt exists: False)
Skipping document 47/198 with OID {5A47D330-20B7-4502-B5D9-B1E65F558B48} because it's missing its XML file!! (stt exists: True)
Skipping document 61/198 with OID {BFDFD3A5-09D1-457D-A91F-BF1A7335CD57} because it's missing its XML file!! (stt exists: False)
Skipping document 64/198 with OID {AE3ABF57-F174-4EA7-94C6-B22B7378D5F5} because it's missing its XML file!! (stt exists: False)
Skipping document 65/198 with OID {34C19B61-A6B9-4E31-B551-B60AAEE92D73} because it's missing its XML file!! (stt exists: True)
Skipping document 67/198 with OID {AED23D95-1B87-456E-8124-535B15D077D3} because it's missing its XML file!! (stt exists: False)
Skipping document 69/198 with OID {749FA43A-4009-4C69-B66B-721899C222E6} because it's missing its XML file!! (stt exists: False)
Skipping document 70/198 with OID {31250DFF-1619-47FA-9520-6CBE90989898} because it's missing its XML file!! (stt exists: False)
Skipping document 71/198 with OID {6D706728-B50C-4AB7-ABD1-B6C574662B08} because it's missing its XML file!! (stt exists: False)
Skipping document 72/198 with OID {C1A35177-21B9-4913-A242-8C6B1242C9B3} because it's missing its XML file!! (stt exists: False)
Skipping document 73/198 with OID {08A539AF-B926-4C59-8553-BFF3C0E4201A} because it's missing its XML file!! (stt exists: False)
Skipping document 74/198 with OID {4F697D92-DA13-46F7-8B74-33CD4DB77F64} because it's missing its XML file!! (stt exists: True)
Skipping document 76/198 with OID {0C6F03B0-5957-42A5-A56E-E2AC9C0C7299} because it's missing its XML file!! (stt exists: False)
Skipping document 77/198 with OID {3458E084-CE4F-4C19-A47D-9CB5D4A7AB7F} because it's missing its XML file!! (stt exists: False)
Skipping document 78/198 with OID {B1A64B2F-3193-491A-AE78-A97D69DD669A} because it's missing its XML file!! (stt exists: False)
Skipping document 79/198 with OID {71EC11E7-97FC-4F6B-8931-EA7223FAB84F} because it's missing its XML file!! (stt exists: True)
Skipping document 87/198 with OID {8C2C2F87-0806-44DC-8CEC-75C752D14F54} because it's missing its XML file!! (stt exists: False)
Skipping document 89/198 with OID {871B1266-5832-4A54-91E2-E506209A7826} because it's missing its XML file!! (stt exists: False)
Skipping document 90/198 with OID {E0FFAC9C-4E72-4050-A533-53FFBE02F8F7} because it's missing its XML file!! (stt exists: False)
Skipping document 92/198 with OID {FF5B0016-AAB2-4240-A5D9-8A3B7B5447E4} because it's missing its XML file!! (stt exists: False)
Skipping document 93/198 with OID {621003E8-305B-4478-A992-3A44F3C480EC} because it's missing its XML file!! (stt exists: False)
Skipping document 95/198 with OID {3A45E002-B1A7-4B95-BD8E-D0304C057882} because it's missing its XML file!! (stt exists: False)
Skipping document 96/198 with OID {B0AA2F4E-3B66-4CA1-A983-EBDAF7099901} because it's missing its XML file!! (stt exists: False)
Skipping document 97/198 with OID {98A2AA28-DC61-424A-9EFE-536D83E6EC00} because it's missing its XML file!! (stt exists: False)
Skipping document 98/198 with OID {F0E6FB7F-25C3-47E3-A99C-E31ABAB3AE9E} because it's missing its XML file!! (stt exists: False)
Skipping document 100/198 with OID {2F4AE5EC-0869-4236-BBDF-63C4DAA0C186} because it's missing its XML file!! (stt exists: True)
Skipping document 101/198 with OID {5DD4A467-1DEB-4F84-9D81-6168606EF2B4} because it's missing its XML file!! (stt exists: False)
Skipping document 102/198 with OID {1B035901-6D6C-4073-A37A-B95E977D764E} because it's missing its XML file!! (stt exists: True)
Skipping document 103/198 with OID {E4EC2175-D9A7-415F-8005-C9E3A4F4DB43} because it's missing its XML file!! (stt exists: True)
Skipping document 111/198 with OID {CBE1725D-B4B4-414F-BF9B-45B32D140022} because it's missing its XML file!! (stt exists: False)
Skipping document 113/198 with OID {36414BD2-9F13-4E55-B03F-5137964DEC9B} because it's missing its XML file!! (stt exists: True)
Skipping document 115/198 with OID {6E0E046E-B356-4DB3-8306-FD6516512DEB} because it's missing its XML file!! (stt exists: False)
Skipping document 117/198 with OID {9A632F08-B179-438E-B8B3-3DC6243A6F77} because it's missing its XML file!! (stt exists: False)
Skipping document 118/198 with OID {2878AF38-E127-4999-87D5-BAE81A66CB6C} because it's missing its XML file!! (stt exists: False)
Skipping document 119/198 with OID {F9472142-1A91-402B-B817-9D91D6D404F6} because it's missing its XML file!! (stt exists: True)
Skipping document 120/198 with OID {176D0D29-06AE-4115-B410-6756ACA80CA6} because it's missing its XML file!! (stt exists: True)

100%|██████████| 1/1 [00:00<00:00,  1.50it/s]
16it [00:09,  1.89it/s]

Skipping document 125/198 with OID {70EFE7AD-70C7-425B-9217-02434908BA65} because it's missing its XML file!! (stt exists: False)
Skipping document 126/198 with OID {1CAD9E88-0B2E-4111-8527-9D544F2F4008} because it's missing its XML file!! (stt exists: True)
Skipping document 129/198 with OID {839F1D00-4E23-4579-BD70-C471C8D62064} because it's missing its XML file!! (stt exists: True)
Skipping document 131/198 with OID {86B6CEFD-E698-4FFA-9A46-C8E89B56CF1C} because it's missing its XML file!! (stt exists: True)
Skipping document 132/198 with OID {B67DE574-3316-4380-96F1-D26F1F3BCFB1} because it's missing its XML file!! (stt exists: True)
Skipping document 135/198 with OID {DDA58DDA-6931-4ECA-BEAE-EBE8169242AF} because it's missing its XML file!! (stt exists: False)
Skipping document 137/198 with OID {9416A745-4837-4990-897A-A6A2D95FE523} because it's missing its XML file!! (stt exists: False)
Skipping document 139/198 with OID {54D040F0-6BA7-402B-8F2F-821C199B2BCD} because it's missing its XML file!! (stt exists: True)
Skipping document 142/198 with OID {2B64A62E-653F-43B9-A176-B9C0C3726294} because it's missing its XML file!! (stt exists: False)
Skipping document 144/198 with OID {167B6B45-A479-4D4F-AE83-E90BA83BFE9B} because it's missing its XML file!! (stt exists: False)
Skipping document 145/198 with OID {075E6B7B-B547-4125-9E5F-C96AB1B94753} because it's missing its XML file!! (stt exists: True)
Skipping document 148/198 with OID {BAC0A7DF-0D59-4745-B02B-4A035903CCAD} because it's missing its XML file!! (stt exists: True)
Skipping document 156/198 with OID {89A9C7A5-7A5A-406E-9715-BA8D803B5BAE} because it's missing its XML file!! (stt exists: False)
Skipping document 158/198 with OID {F1FFE8C8-2DF0-45FA-AA5E-8C6A1EE0BA67} because it's missing its XML file!! (stt exists: True)
Skipping document 159/198 with OID {A503CA82-736E-40ED-92F2-D6EB28E350E8} because it's missing its XML file!! (stt exists: False)
Skipping document 160/198 with OID {E57EFE55-9AE4-42CF-800A-0E3DD672B724} because it's missing its XML file!! (stt exists: True)
Skipping document 164/198 with OID {25497E7B-08F2-409F-B94F-2DDD703E234D} because it's missing its XML file!! (stt exists: False)
Skipping document 166/198 with OID {9A8D0DB2-2701-4800-A877-FFEBA3613736} because it's missing its XML file!! (stt exists: True)
Skipping document 169/198 with OID {F1D9FA42-1999-460E-BB73-08868338F0BE} because it's missing its XML file!! (stt exists: False)
Skipping document 170/198 with OID {47DDBB69-6E54-4CC4-9174-570C28777133} because it's missing its XML file!! (stt exists: True)
Skipping document 171/198 with OID {04812F30-96F4-4BAD-95EF-2FCFE0910B5B} because it's missing its XML file!! (stt exists: True)
Skipping document 172/198 with OID {AAC421C9-20B7-482B-ADE0-287979565177} because it's missing its XML file!! (stt exists: False)
Skipping document 173/198 with OID {F73FEFAC-0827-434B-88F8-FBE5FD0E5EBC} because it's missing its XML file!! (stt exists: False)
Skipping document 174/198 with OID {69C4933E-591D-45C7-86C0-5960095A1A48} because it's missing its XML file!! (stt exists: True)
Skipping document 175/198 with OID {064BD16D-E265-4A4F-B87A-FCA9DE80B092} because it's missing its XML file!! (stt exists: False)
Skipping document 180/198 with OID {D0D84353-D826-42E1-9597-6BC439B43DB8} because it's missing its XML file!! (stt exists: True)
Skipping document 181/198 with OID {F5F18701-1C5F-490A-A711-22A674FD2803} because it's missing its XML file!! (stt exists: False)
Skipping document 182/198 with OID {23A26DA4-4C90-41B7-B485-8CC57EB28C72} because it's missing its XML file!! (stt exists: True)
Skipping document 183/198 with OID {9380006D-33EE-4C04-97B8-771E77B18D19} because it's missing its XML file!! (stt exists: True)
Skipping document 184/198 with OID {27F213C5-7533-41F1-8B45-D7520E2BAC05} because it's missing its XML file!! (stt exists: False)
Skipping document 185/198 with OID {F6A44AC9-8853-4F28-B286-D741136F6112} because it's missing its XML file!! (stt exists: False)
Skipping document 188/198 with OID {7D88D1B4-DB6E-475E-B797-52B21EE87D1C} because it's missing its XML file!! (stt exists: False)
Skipping document 190/198 with OID {52B1D182-2709-4931-A95A-EDAA64DA8413} because it's missing its XML file!! (stt exists: True)
Skipping document 192/198 with OID {1B7B8464-1974-43B3-B529-209B9C1FD1DC} because it's missing its XML file!! (stt exists: False)
Skipping document 193/198 with OID {D9C488B8-1EC8-47E2-AB44-5998AED18275} because it's missing its XML file!! (stt exists: False)
Skipping document 194/198 with OID {647144E7-B297-40F7-AEC3-CDD776CEF872} because it's missing its XML file!! (stt exists: False)
infopile - returning 103 documents, 95 were skipped due to missing necessary info.
 --> Adding 103 to the out csv for infopile

PROCESSING PROGRAM inst_monde (17/47) - 1 files:

Starting extracting 581 documents for program inst_monde
Did not find any date for doc with OID {0B62FCAF-6201-4A70-BAE6-8452641F5418}. Trying to use the recording date. doc_dict: {'alias': 'inst_monde', 'date_str': None, 'stt_filename': '0B62FCAF-6201-4A70-BAE6-8452641F5418_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{0B62FCAF-6201-4A70-BAE6-8452641F5418}', 'stripped_OID': '0B62FCAF-6201-4A70-BAE6-8452641F5418', 'login': '', 'broadcast_episode_title': "10?me anniversaire de l'Organisation europ?enne de coop?ration ?conomique (OECE) : D?claration de Max Petitpierre, conseiller f?d?ral neuch?telois", 'sequence': '1', 'broadcast_program_name': 'Instants du monde', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '31.10.2016 14:10:55', 'physical_support_history': "Cote d'origine: MA 58.9", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Le bilan positif de cette organisation apr?s-guerre, la participation de la Suisse, la question des droits de douane entre les pays membres. La position de la Suisse souvent frileuse devant la nouveaut? et la collaboration internationale.', 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:06:29.333', 'work_duration_compl': 'Non', 'participants': [{'name': 'Petitpierre, Max', 'function': "Auteur d'une d?claration", 'role': 'conseiller f?d?ral'}], 'geographical_descriptors': ['Europe', 'Suisse'], 'person_descriptors': ['OECE'], 'thematical_descriptors': ['politique ?conomique'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Radio Sottens'], 'subdomains': ['D?claration'], 'recording_dates': ['16/04/1958 - 16/04/1958'], 'first_broadcast_dates': None}
Skipping document 12/581 with OID {FD8AF0FE-D657-46B1-83FF-64015BF994C6} because it's missing its XML file!! (stt exists: False)
Skipping document 14/581 with OID {017A9336-EB54-4B8C-A9F8-A99C099F15A6} because it's missing its XML file!! (stt exists: False)
Skipping document 15/581 with OID {A0B7A182-78F0-4963-8FC7-2D9B8F9994C6} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {4762B10E-F3BD-48E6-A5B7-5C5C78B22623}. Trying to use the recording date. doc_dict: {'alias': 'inst_monde', 'date_str': None, 'stt_filename': '4762B10E-F3BD-48E6-A5B7-5C5C78B22623_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{4762B10E-F3BD-48E6-A5B7-5C5C78B22623}', 'stripped_OID': '4762B10E-F3BD-48E6-A5B7-5C5C78B22623', 'login': '', 'broadcast_episode_title': "A propos de l'accident routier de Fran?oise Sagan, ?crivaine : 1. Commentaire de Jacques Ferry. - La Valse. Po?me de et par Fran?oise Sagan", 'sequence': '1', 'broadcast_program_name': 'Instants du monde', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'prongudo', 'modified_on': '17.10.2016 07:37:59', 'physical_support_history': "Cote d'origine : MA 5711.cLot : Caisse 3048", 'production_type': 'Production propre', 'recording_place': 'Paris', 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Ferry, Jacques', 'function': 'Commentateur/trice', 'role': 'correspondant Radio-Gen?ve Paris'}, {'name': 'Sagan, Fran?oise', 'function': 'R?citant/e', 'role': '?crivaine'}], 'geographical_descriptors': None, 'person_descriptors': ['Sagan, Fran?oise'], 'thematical_descriptors': ['?crivaine', 'accident routier'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Commentaire'], 'recording_dates': ['15/05/1957 - 15/05/1957'], 'first_broadcast_dates': None}
Skipping document 18/581 with OID {17CA33C3-42A0-4114-8212-C428279598D8} because it's missing its XML file!! (stt exists: False)
Skipping document 21/581 with OID {34534C6A-E7DB-4538-BD9E-D74B1B115295} because it's missing its XML file!! (stt exists: False)
WARNING! MISSING DATE FOR DOC WITH OID {D9A04FB4-F141-4C99-8F43-59B8A1BE051B}!!
Document: {'alias': 'inst_monde', 'date_str': None, 'stt_filename': 'D9A04FB4-F141-4C99-8F43-59B8A1BE051B_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{D9A04FB4-F141-4C99-8F43-59B8A1BE051B}', 'stripped_OID': 'D9A04FB4-F141-4C99-8F43-59B8A1BE051B', 'login': '', 'broadcast_episode_title': "Allocution d'Urho Kekkonen, pr?sident de la R?publique de Finlande : A propos de la comm?moration de l'ind?pendance de la Finlande", 'sequence': '1', 'broadcast_program_name': 'Instants du monde', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '31.01.2019 11:17:21', 'physical_support_history': "Cote d'origine : MA 5746.gResp. RSR : AQTLot : Caisse 3336", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Participant: decl:Kekkonen, Urkho', 'workflow_status': 'Accept?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Premier programme'], 'subdomains': None, 'recording_dates': None, 'first_broadcast_dates': None},
original: <DOCUMENT><CLSID>{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}</CLSID><OID>{D9A04FB4-F141-4C99-8F43-59B8A1BE051B}</OID><LOGIN/><TITLE>Allocution d'Urho Kekkonen, pr?sident de la R?publique de Finlande : A propos de la comm?moration de l'ind?pendance de la Finlande</TITLE><HIERARCHY OID="{D9A04FB4-F141-4C99-8F43-59B8A1BE051B}" current="*" depth="---" title="Allocution d'Urho Kekkonen, pr?sident de la R?publique de Finlande : A propos de la comm?moration de l'ind?pendance de la Finlande"/><SEQUENCE>1</SEQUENCE><BROADCAST>Instants du monde</BROADCAST><DOCUMENTTYPE>Parl?</DOCUMENTTYPE><HIERARCHYLEVEL>Sujet</HIERARCHYLEVEL><MODIFIEDBY>suillojo</MODIFIEDBY><MODIFIEDON>31.01.2019 11:17:21</MODIFIEDON><NOTES>dat_enr : 1957. Copi? Agfa en mars 1989 par J.F. Ku?s. En 3 parties</NOTES><HISTORY>Cote d'origine : MA 5746.gResp. RSR : AQTLot : Caisse 3336</HISTORY><PRODUCTIONTYPE>Production propre</PRODUCTIONTYPE><RIGHTSSTATUS>Clarifi?</RIGHTSSTATUS><RIGHTSUSAGEPOSSIBILITIES><RIGHTSUSAGEPOSSIBILITY>Tous</RIGHTSUSAGEPOSSIBILITY></RIGHTSUSAGEPOSSIBILITIES><SERIESTITLE>Sauvegarde d'archives</SERIESTITLE><SUMMARY>Participant: decl:Kekkonen, Urkho</SUMMARY><WORKFLOWSTATUS>Accept?</WORKFLOWSTATUS><LIVE>Non live</LIVE><MODULATIONTYPE>Mono</MODULATIONTYPE><PROGRAMMES><PROGRAMME>Premier programme</PROGRAMME></PROGRAMMES><WORKDURATION>00:00:00.000</WORKDURATION><WORKDURATIONCOMPL>Non</WORKDURATIONCOMPL><SUPPORTS><SUPPORT><CLSID>{9C19C69A-A4DC-479E-94F1-61FF72CA7889}</CLSID><OID>{504ACF44-2298-4E62-8FC1-24C10A225D54}</OID><TITLE>Allocution d'Urho Kekkonen, pr?sident de la R?publique de Finlande : A propos de la comm?moration de l'ind?pendance de la Finlande</TITLE><ISDIGITAL>True</ISDIGITAL><FILENAME>MA5746.g{C67239DB-5FF2-4121-9AD5-845542588FAC}.wav</FILENAME><ACQUISITIONDATES><ACQUISITIONDATE>03/08/2010</ACQUISITIONDATE></ACQUISITIONDATES><BRAND>Enr. RSR</BRAND><CATALOGUINGSTATUS>Transitoire</CATALOGUINGSTATUS><SOURCE>NumA</SOURCE><UNITDURATION>00:02:09.323</UNITDURATION><UNITDURATIONCOMPL>Non</UNITDURATIONCOMPL><PHYSICALPROPERTIES><ANNOTATIONS>Non</ANNOTATIONS><NUMBEROFCOPIES>0</NUMBEROFCOPIES><NUMBEROFSUPPORTS>0</NUMBEROFSUPPORTS></PHYSICALPROPERTIES></SUPPORT></SUPPORTS></DOCUMENT>
Skipping document 25/581 with OID {5585DF20-6819-4289-8F34-E1B9D15A7FD7} because it's missing its XML file!! (stt exists: False)
Skipping document 27/581 with OID {1FE10266-01E8-4919-8EEB-1F87E0888D5B} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {4E407364-41E5-4128-B650-A9533416F171}. Trying to use the recording date. doc_dict: {'alias': 'inst_monde', 'date_str': None, 'stt_filename': '4E407364-41E5-4128-B650-A9533416F171_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{4E407364-41E5-4128-B650-A9533416F171}', 'stripped_OID': '4E407364-41E5-4128-B650-A9533416F171', 'login': '', 'broadcast_episode_title': 'Arriv?e ? Wellington du Dr Vivian Fuchs et de Edmund Hillary, premiers explorateurs du p?le sud', 'sequence': '1', 'broadcast_program_name': 'Instants du monde', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '25.11.2016 16:06:54', 'physical_support_history': "Cote d'origine: MA 58.3 Pl I", 'production_type': 'Production propre', 'recording_place': 'Wellington', 'rights_notes': 'Memoriav', 'rights_status': 'A rechercher', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Son des sir?nes de bateaux dans le port de Wellingtone (Nouvelle Z?lande). Jacques-Olivier Chattard, relate le discours du docteur Vivian Fuchs lors de la r?ception donn?e en son honneur ? Welligton. ? 01.06 : Extrait du discours du Dr Fuchs [en anglais].', 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:02:09.493', 'work_duration_compl': 'Non', 'participants': [{'name': 'Chattard, Jacques-Olivier', 'function': 'Commentateur/trice', 'role': 'journaliste fran?ais'}, {'name': 'Fuchs, Vivian', 'function': "Auteur d'une d?claration", 'role': 'explorateur britannique'}], 'geographical_descriptors': ['P?le Sud', 'Grande-Bretagne'], 'person_descriptors': ['Fuchs, Vivian'], 'thematical_descriptors': ['exp?dition scientifique'], 'rights_usage_possibilities': ['FM'], 'radio_channels': ['Premier programme'], 'subdomains': ['Commentaire', 'D?claration'], 'recording_dates': ['17/04/1958 - 17/04/1958'], 'first_broadcast_dates': None}
Skipping document 29/581 with OID {06B353F7-5055-4248-B718-F973DB3E6D47} because it's missing its XML file!! (stt exists: False)
Skipping document 30/581 with OID {DE7A4024-CEA4-419F-B791-05DC16A5FC1C} because it's missing its XML file!! (stt exists: False)
Skipping document 31/581 with OID {9E708A84-1A83-4660-A021-6034887691FE} because it's missing its XML file!! (stt exists: False)
Skipping document 32/581 with OID {FD859DEC-8CB6-4F00-AC6D-C86D36AC2868} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {C07F3402-97CD-4942-8DBF-D9255CC3ACFE}. Trying to use the recording date. doc_dict: {'alias': 'inst_monde', 'date_str': None, 'stt_filename': 'C07F3402-97CD-4942-8DBF-D9255CC3ACFE_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{C07F3402-97CD-4942-8DBF-D9255CC3ACFE}', 'stripped_OID': 'C07F3402-97CD-4942-8DBF-D9255CC3ACFE', 'login': '', 'broadcast_episode_title': 'Autoportrait de Fran?oise Rosay, actrice fran?aise', 'sequence': '1', 'broadcast_program_name': 'Instants du monde', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '05.11.2016 02:36:44', 'physical_support_history': "Cote d'origine : MA 5754.bResp. RSR : AQTLot : Caisse 3337", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Son travail au th??tre "Les fantaisies parisiennes". Conservatoire ? 16 ans et demi. Th??tre Charles Dullin. Sa rencontre avec Jacques Fedeyr avec qui elle se mariera. Conservatoire et op?ra. Ses trois enfants. D?part ? Hollywood avec son mari. Cin?ma muet et d?but du parlant. Elle a une grande admiration pour son mari. Jacques Feyder est en clinique ? Prangins. La vie apr?s la mort de son mari.', 'workflow_status': 'Valid?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Rosay, Fran?oise', 'function': 'Interview?/e', 'role': 'com?dienne'}, {'name': 'Roch, Fran?ois-Achille', 'function': 'Intervieweur/euse', 'role': 'collaborateur/trice RSR'}], 'geographical_descriptors': ['Paris'], 'person_descriptors': ['Rosay, Fran?oise', 'Antoine', 'Feyder,Jacques', 'Carn?, Marcel'], 'thematical_descriptors': ['art dramatique', '?ducation', 'com?die', 'mariage', 'cin?ma muet', 'cin?ma', 'conservatoire de musique', 'enfant (filiation)'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Radio Sottens'], 'subdomains': ['Interview'], 'recording_dates': ['06/04/1957 - 06/04/1957'], 'first_broadcast_dates': None}
WARNING! MISSING DATE FOR DOC WITH OID {1BFBBEC8-5834-418A-BE5B-0C707B7593CF}!!
Document: {'alias': 'inst_monde', 'date_str': None, 'stt_filename': '1BFBBEC8-5834-418A-BE5B-0C707B7593CF_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{1BFBBEC8-5834-418A-BE5B-0C707B7593CF}', 'stripped_OID': '1BFBBEC8-5834-418A-BE5B-0C707B7593CF', 'login': '', 'broadcast_episode_title': 'Autoportrait de Gaby Morlay, actrice fran?aise', 'sequence': '1', 'broadcast_program_name': 'Instants du monde', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '20.10.2016 08:44:24', 'physical_support_history': "Cote d'origine : MA 5754.cLot : Caisse 3337", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': "Elle d?bute comme figurante au th??tre des Capucines ? l'?ge de 15 ans et demi. Origine de son nom. Premier r?le int?ressant. Travaillera pour Henry Bernstein, Louis Verneuil, Lucien Guitry, Henri Duvernois dans les ann?es vingt. Elle est la premi?re femme ? obtenir le brevet de pilote de dirigeable. Ses principaux partenaires au cin?ma. Gaby Morlay a re?u la L?gion d'honneur.", 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Morlay, Gaby', 'function': 'Interview?/e', 'role': 'actrice et com?dienne'}, {'name': 'Roch, Fran?ois-Achille', 'function': 'Intervieweur/euse', 'role': 'collaborateur/trice RSR'}], 'geographical_descriptors': ['Paris'], 'person_descriptors': ['Morlay, Gaby', 'Guitry, Lucien', 'Bernstein, Henry', 'Verneuil, Louis', "L?gion d'honneur"], 'thematical_descriptors': ['art dramatique', 'cin?ma', 'dirigeable', 'ann?es 1920'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Radio Sottens'], 'subdomains': ['Interview'], 'recording_dates': None, 'first_broadcast_dates': None},
original: <DOCUMENT><CLSID>{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}</CLSID><OID>{1BFBBEC8-5834-418A-BE5B-0C707B7593CF}</OID><LOGIN/><TITLE>Autoportrait de Gaby Morlay, actrice fran?aise</TITLE><HIERARCHY OID="{1BFBBEC8-5834-418A-BE5B-0C707B7593CF}" current="*" depth="---" title="Autoportrait de Gaby Morlay, actrice fran?aise"/><SEQUENCE>1</SEQUENCE><BROADCAST>Instants du monde</BROADCAST><DOCUMENTTYPE>Parl?</DOCUMENTTYPE><GEOGRAPHICALDESCRIPTORS><GEOGRAPHICALDESCRIPTOR>Paris</GEOGRAPHICALDESCRIPTOR></GEOGRAPHICALDESCRIPTORS><HIERARCHYLEVEL>Sujet</HIERARCHYLEVEL><MODIFIEDBY>colombis</MODIFIEDBY><MODIFIEDON>20.10.2016 08:44:24</MODIFIEDON><NOTES>Copi? Agfa en juin1989 par J.F. Ku?s. Dat_enr : 1957. Probl?me de son par moment, passant du canal gauche au droit.</NOTES><HISTORY>Cote d'origine : MA 5754.cLot : Caisse 3337</HISTORY><PARTICIPANTS><PARTICIPANT><NAME>Morlay, Gaby</NAME><FUNCTION>Interview?/e</FUNCTION><ROLE>actrice et com?dienne</ROLE></PARTICIPANT><PARTICIPANT><NAME>Roch, Fran?ois-Achille</NAME><FUNCTION>Intervieweur/euse</FUNCTION><ROLE>collaborateur/trice RSR</ROLE></PARTICIPANT></PARTICIPANTS><PERSONDESCRIPTORS><PERSONDESCRIPTOR>Morlay, Gaby</PERSONDESCRIPTOR><PERSONDESCRIPTOR>Guitry, Lucien</PERSONDESCRIPTOR><PERSONDESCRIPTOR>Bernstein, Henry</PERSONDESCRIPTOR><PERSONDESCRIPTOR>Verneuil, Louis</PERSONDESCRIPTOR><PERSONDESCRIPTOR>L?gion d'honneur</PERSONDESCRIPTOR></PERSONDESCRIPTORS><PRODUCTIONTYPE>Production propre</PRODUCTIONTYPE><RIGHTSSTATUS>Clarifi?</RIGHTSSTATUS><RIGHTSUSAGEPOSSIBILITIES><RIGHTSUSAGEPOSSIBILITY>Tous</RIGHTSUSAGEPOSSIBILITY></RIGHTSUSAGEPOSSIBILITIES><SERIESTITLE>Sauvegarde d'archives</SERIESTITLE><SUMMARY>Elle d?bute comme figurante au th??tre des Capucines ? l'?ge de 15 ans et demi. Origine de son nom. Premier r?le int?ressant. Travaillera pour Henry Bernstein, Louis Verneuil, Lucien Guitry, Henri Duvernois dans les ann?es vingt. Elle est la premi?re femme ? obtenir le brevet de pilote de dirigeable. Ses principaux partenaires au cin?ma. Gaby Morlay a re?u la L?gion d'honneur.</SUMMARY><THEMATICALDESCRIPTORS><THEMATICALDESCRIPTOR>art dramatique</THEMATICALDESCRIPTOR><THEMATICALDESCRIPTOR>cin?ma</THEMATICALDESCRIPTOR><THEMATICALDESCRIPTOR>dirigeable</THEMATICALDESCRIPTOR><THEMATICALDESCRIPTOR>ann?es 1920</THEMATICALDESCRIPTOR></THEMATICALDESCRIPTORS><WORKFLOWSTATUS>Valid?</WORKFLOWSTATUS><ASSEMBLYSTATUS>Brut</ASSEMBLYSTATUS><LIVE>Non live</LIVE><MODULATIONTYPE>Mono</MODULATIONTYPE><PROGRAMMES><PROGRAMME>Radio Sottens</PROGRAMME></PROGRAMMES><SUBDOMAINS><SUBDOMAIN>Interview</SUBDOMAIN></SUBDOMAINS><WORKDURATION>00:00:00.000</WORKDURATION><WORKDURATIONCOMPL>Non</WORKDURATIONCOMPL><SUPPORTS><SUPPORT><CLSID>{9C19C69A-A4DC-479E-94F1-61FF72CA7889}</CLSID><OID>{2347C174-39CD-4992-938D-3DB935EF9A59}</OID><TITLE>Autoportrait de Gaby Morlay, actrice fran?aise</TITLE><ISDIGITAL>True</ISDIGITAL><FILENAME>MA5754.c{92BAA238-FCEA-40E1-B817-10E616D05183}.wav</FILENAME><ACQUISITIONDATES><ACQUISITIONDATE>03/08/2010</ACQUISITIONDATE></ACQUISITIONDATES><BRAND>Enr. RSR</BRAND><CATALOGUINGSTATUS>D+A total</CATALOGUINGSTATUS><SOURCE>NumA</SOURCE><UNITDURATION>00:14:34.784</UNITDURATION><UNITDURATIONCOMPL>Non</UNITDURATIONCOMPL><PHYSICALPROPERTIES><ANNOTATIONS>Non</ANNOTATIONS><NUMBEROFCOPIES>0</NUMBEROFCOPIES><NUMBEROFSUPPORTS>0</NUMBEROFSUPPORTS></PHYSICALPROPERTIES></SUPPORT></SUPPORTS></DOCUMENT>

100%|██████████| 1/1 [00:02<00:00,  2.14s/it]
17it [00:11,  1.06it/s]

Skipping document 520/581 with OID {1574F9D6-1A6C-42DD-B309-1BF707571F6E} because it's missing its XML file!! (stt exists: False)
Skipping document 523/581 with OID {DBEFFA3B-1632-449B-9D2E-B0DB13CFE95D} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {69EEA0FE-656F-40A4-ADB3-5A82FDEB3E7C}. Trying to use the recording date. doc_dict: {'alias': 'inst_monde', 'date_str': None, 'stt_filename': '69EEA0FE-656F-40A4-ADB3-5A82FDEB3E7C_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{69EEA0FE-656F-40A4-ADB3-5A82FDEB3E7C}', 'stripped_OID': '69EEA0FE-656F-40A4-ADB3-5A82FDEB3E7C', 'login': '', 'broadcast_episode_title': "R?cit de l'accident de voiture de Fran?oise Sagan : Interview d'un passager de la voiture, ami de Fran?oise Sagan", 'sequence': '1', 'broadcast_program_name': 'Instants du monde', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'prongudo', 'modified_on': '22.11.2016 20:04:43', 'physical_support_history': "Cote d'origine : MA 5731.dLot : Caisse 3048", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Inconnu', 'function': 'Interview?/e', 'role': 'ami de Fran?oise Sagan'}, {'name': 'Inconnu', 'function': 'Intervieweur/euse', 'role': 'collaborateur Radio-Gen?ve'}], 'geographical_descriptors': None, 'person_descriptors': ['Sagan, Fran?oise'], 'thematical_descriptors': ['accident routier'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Interview'], 'recording_dates': ['15/05/1957 - 15/05/1957'], 'first_broadcast_dates': None}
Skipping document 526/581 with OID {EBE13B38-BBB3-40BC-9A6A-E418F46B5399} because it's missing its XML file!! (stt exists: False)
Skipping document 527/581 with OID {FD1FA06C-26A5-47E4-9B13-7655D4014882} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {383F051A-83F5-4F0C-8DC5-0D42EDD24253}. Trying to use the recording date. doc_dict: {'alias': 'inst_monde', 'date_str': None, 'stt_filename': '383F051A-83F5-4F0C-8DC5-0D42EDD24253_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{383F051A-83F5-4F0C-8DC5-0D42EDD24253}', 'stripped_OID': '383F051A-83F5-4F0C-8DC5-0D42EDD24253', 'login': '', 'broadcast_episode_title': 'Reportage dans le Sahara alg?rien ? Hassi-Messaoud : le p?trole au Sahara (2/2) [?l?ments bruts]', 'sequence': '1', 'broadcast_program_name': 'Instants du monde', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '22.07.2022 22:34:43', 'physical_support_history': "Cote d'origine: MA 58.42 Pl. A", 'production_type': 'Production propre', 'recording_place': 'Alg?rie (Hassi-Messaoud)', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': "La main d'oeuvre qui travaille sur le site p?trolier, les sp?cialit?s du personnel, les foreurs, environ cinquante personnes travaillent par foreuse. La r?partition raciale du travail, beaucoup d'anciens Fran?ais d'Alg?rie, de m?tropole, et des indig?nes trait?s de mani?re ?gales (environ 20 ? 25 %). L'organisation sociale des villages d'Hassi Messaoud, la mobilit? des camps, les loisirs, le cin?ma trois fois par semaines, le rythme de travail. Le transport du p?trole et la fabrication du pipeline d'Hassi Messaoud ? Touggourt, le gas d?gag? est br?l?.  Le personnel ?tranger employ? : Italiens, Espagnols, Anglais, le manque de techniciens, la possibilit? pour des Suisses de venir travailler sur le site.", 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:15:32.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Laurent, Bernard', 'function': 'Reporter', 'role': 'collaborateur RSR'}, {'name': 'Inconnu', 'function': 'Interview?/e', 'role': "responsable du chantier d'Hassi-Messaoud"}], 'geographical_descriptors': ['Alg?rie', 'Sahara', 'France'], 'person_descriptors': None, 'thematical_descriptors': ['p?trole', 'forage', 'vie sociale'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Premier programme'], 'subdomains': ['Interview'], 'recording_dates': ['__/02/1958 - __/02/1958'], 'first_broadcast_dates': None}
The date for document with OID {383F051A-83F5-4F0C-8DC5-0D42EDD24253} was invalid (__/02/1958) - changed it to 01/02/1958
The date for document with OID {383F051A-83F5-4F0C-8DC5-0D42EDD24253} was invalid (__/02/1958) - changed it to 01/02/1958
Skipping document 538/581 with OID {6D64379F-CF6D-4ADC-A5FD-BB34AC4A210D} because it's missing its XML file!! (stt exists: False)
Skipping document 540/581 with OID {00F6C018-2CBA-45D3-95A2-3DD61F2D584E} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {F818EA8B-DFE4-4379-A793-A17551D06395}. Trying to use the recording date. doc_dict: {'alias': 'inst_monde', 'date_str': None, 'stt_filename': 'F818EA8B-DFE4-4379-A793-A17551D06395_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{F818EA8B-DFE4-4379-A793-A17551D06395}', 'stripped_OID': 'F818EA8B-DFE4-4379-A793-A17551D06395', 'login': '', 'broadcast_episode_title': 'Seconde rencontre de n?gociations franco-?gyptiennes ? Gen?ve', 'sequence': '1', 'broadcast_program_name': 'Instants du monde', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '09.03.2023 13:41:26', 'physical_support_history': "Cote d'origine: MA 5743.g", 'production_type': 'Production propre', 'recording_place': 'Gen?ve', 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Robert, J.', 'function': 'Interview?/e', 'role': 'inspecteur g?n?ral des finances, pr?sident de la d?l?gation fran?aise'}, {'name': 'Darmsteter, Jean-Paul', 'function': 'Intervieweur/euse', 'role': 'collaborateur Radio-Gen?ve'}, {'name': 'Inconnu', 'function': 'Intervieweur/euse', 'role': 'journaliste'}], 'geographical_descriptors': ['France', 'Egypte'], 'person_descriptors': None, 'thematical_descriptors': ['n?gociation', 'relations internationales'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Radio Sottens'], 'subdomains': ['Interview'], 'recording_dates': ['20/09/1957 - 20/09/1957'], 'first_broadcast_dates': None}
Skipping document 542/581 with OID {710DFCDE-3122-4C65-8D58-7D85C9D74A5F} because it's missing its XML file!! (stt exists: False)
Skipping document 574/581 with OID {BC5BFDE7-F2B4-4595-899E-E51540F45BD5} because it's missing its XML file!! (stt exists: False)
Skipping document 575/581 with OID {E71CADFD-50C7-44C2-8757-C1C04E027FF1} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {9EABA90B-7544-4108-B121-4EC0EE39B19A}. Trying to use the recording date. doc_dict: {'alias': 'inst_monde', 'date_str': None, 'stt_filename': '9EABA90B-7544-4108-B121-4EC0EE39B19A_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{9EABA90B-7544-4108-B121-4EC0EE39B19A}', 'stripped_OID': '9EABA90B-7544-4108-B121-4EC0EE39B19A', 'login': '', 'broadcast_episode_title': 'Voix myst?rieuse 05.03.10 - Paul Guth', 'sequence': '2', 'broadcast_program_name': 'Instants du monde', 'document_type': 'Parl?', 'hierarchy_level': 'Extrait', 'modified_by': 'suillojo', 'modified_on': '09.03.2023 09:12:36', 'physical_support_history': "Cote d'origine : MA 5717.eLot : Caisse 3048", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Guth, Paul', 'function': 'Interview?/e', 'role': '?crivain'}, {'name': 'Roch, Fran?ois-Achille', 'function': 'Intervieweur/euse', 'role': 'collaborateur/trice RSR'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': ['litt?rature', '?crivain'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Interview'], 'recording_dates': ['08/08/1957 - 08/08/1957'], 'first_broadcast_dates': None}
inst_monde - returning 422 documents, 159 were skipped due to missing necessary info.
 --> Adding 422 to the out csv for inst_monde

PROCESSING PROGRAM j13h (18/47) - 1 files:

100%|██████████| 1/1 [00:00<00:00,  2.17it/s]
18it [00:11,  1.22it/s]

Starting extracting 90 documents for program j13h
Did not find any date for doc with OID {E9DF5F99-0E1A-4618-B254-FCC1B7806882}. Trying to use the recording date. doc_dict: {'alias': 'j13h', 'date_str': None, 'stt_filename': 'E9DF5F99-0E1A-4618-B254-FCC1B7806882_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{E9DF5F99-0E1A-4618-B254-FCC1B7806882}', 'stripped_OID': 'E9DF5F99-0E1A-4618-B254-FCC1B7806882', 'login': '', 'broadcast_episode_title': 'Interview d\'Alfred Willener : Son rapport intitul� "La situation sociologique des m�dias en Suisse : Communications �mancipatrices?', 'sequence': '1', 'broadcast_program_name': 'Journal de 13h', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '28.05.2022 06:00:35', 'physical_support_history': "Cote d'origine : A 3027", 'production_type': 'Production propre', 'recording_place': 'Lausanne (Studio RSR)', 'rights_notes': None, 'rights_status': 'Clarifi�', 'series_title': None, 'content_summary': 'Conception globale des m�dias.', 'workflow_status': 'Valid�', 'assembly_status': 'Mont�', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Martel, Jean', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur RSR'}, {'name': 'Willener, Alfred', 'function': 'Interview�/e', 'role': "professeur,  directeur de l'Institut de sociologie et des communications de masse � l'Universit� de Lausanne"}, {'name': 'Gfeller, Urs', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Suisse'], 'person_descriptors': None, 'thematical_descriptors': ['mass m�dia', 'livre (imprim�)', 'vedettariat', 'radio', 't�l�vision', 'presse'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Deuxi�me programme'], 'subdomains': ['Interview'], 'recording_dates': ['27/02/1982 - 27/02/1982'], 'first_broadcast_dates': None}
Skipping document 54/90 with OID {C379A0D5-C539-470A-A56F-18FBA6C4F442} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {602F781C-6391-4FAF-B897-022B9BC3E077}. Trying to use the recording date. doc_dict: {'alias': 'j13h', 'date_str': None, 'stt_filename': '602F781C-6391-4FAF-B897-022B9BC3E077_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{602F781C-6391-4FAF-B897-022B9BC3E077}', 'stripped_OID': '602F781C-6391-4FAF-B897-022B9BC3E077', 'login': '', 'broadcast_episode_title': "Interview du secr�taire g�n�ral de l'ONU Kurt Waldheim, � propos du Proche-Orient", 'sequence': '1', 'broadcast_program_name': 'Journal de 13h', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '01.06.2022 11:31:34', 'physical_support_history': "Cote d'origine: 7535", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': None, 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid�', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Waldheim, Kurt', 'function': 'Interview�/e', 'role': "secr�taire g�n�ral de l'ONU"}, {'name': 'Inconnus', 'function': 'Interview�/e', 'role': 'journalistes RSR'}], 'geographical_descriptors': ['Proche-Orient', 'Portugal', 'Iran'], 'person_descriptors': ["Conseil de s�curit� de l'ONU", 'ONU'], 'thematical_descriptors': ['diplomatie', 'relations internationales', 'Palestiniens', 'd�colonisation'], 'rights_usage_possibilities': None, 'radio_channels': ['Deuxi�me programme'], 'subdomains': ['Interview'], 'recording_dates': ['30/04/1982 - 30/04/1982'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {EF110BC5-28F8-4578-A06F-ABE7767F4E2E}. Trying to use the recording date. doc_dict: {'alias': 'j13h', 'date_str': None, 'stt_filename': 'EF110BC5-28F8-4578-A06F-ABE7767F4E2E_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{EF110BC5-28F8-4578-A06F-ABE7767F4E2E}', 'stripped_OID': 'EF110BC5-28F8-4578-A06F-ABE7767F4E2E', 'login': '', 'broadcast_episode_title': "La pluralit� des langues en Suisse. D�bat � l'occasion de la conf�rence organis�e � Lausanne par les Rencontres suisses", 'sequence': '1', 'broadcast_program_name': 'Journal de 13h', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'albrecjo', 'modified_on': '27.05.2022 09:57:26', 'physical_support_history': "Cote d'origine: A 20426. 2 plages", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi�', 'series_title': "Sauvegarde d'archives. Fribourg", 'content_summary': "Quel avenir? La tension va-t-elle encore monter? L'anglais va-t-il devenir la nouvelle langue nationale de la Suisse au XXIe si�cle ?", 'workflow_status': 'Valid�', 'assembly_status': 'Mont�', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:27:36.560', 'work_duration_compl': 'Non', 'participants': [{'name': 'Cotti, Flavio', 'function': 'Participant/e au d�bat', 'role': "conseiller f�d�ral, chef du d�partement f�d�ral de l'int�rieur"}, {'name': 'Bergier, Jean-Fran�ois', 'function': 'Participant/e au d�bat', 'role': "professeur d'histoire � l'Ecole polytechnique f�d�rale et pr�sident du Comit� des Rencontres suisses"}, {'name': 'Ruffieux, Roland', 'function': 'Participant/e au d�bat', 'role': "professeur de science politique � l'Universit� de Fribourg et de Lausanne"}, {'name': 'Tschopp, G�rard', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Suisse', 'Suisse romande', 'Suisse al�manique', 'Suisse italienne'], 'person_descriptors': None, 'thematical_descriptors': ['langue', 'langue anglaise', 'langue suisse allemande', 'histoire', 'politique', 'constitution', 'langue fran�aise', 'f�d�ralisme', 'r�gionalisme', 'langue italienne', 'Suisses al�maniques', 'Suisses romands', 'Suisses italiens', 'langue romanche'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Espace 2'], 'subdomains': ['D�bat'], 'recording_dates': ['14/11/1987 - 14/11/1987'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {E48A1EB5-B6DD-43FB-9AFF-4B6D63FB9D53}. Trying to use the recording date. doc_dict: {'alias': 'j13h', 'date_str': None, 'stt_filename': 'E48A1EB5-B6DD-43FB-9AFF-4B6D63FB9D53_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{E48A1EB5-B6DD-43FB-9AFF-4B6D63FB9D53}', 'stripped_OID': 'E48A1EB5-B6DD-43FB-9AFF-4B6D63FB9D53', 'login': '', 'broadcast_episode_title': "La situation de la Suisse dans une Europe en mutation. D�bat organis� suite � l'annonce faite � Ankara concernant la prochaine demande d'adh�sion de la Turquie � la Communaut� europ�enne", 'sequence': '1', 'broadcast_program_name': 'Journal de 13h', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'mertenpi', 'modified_on': '15.07.2022 01:32:18', 'physical_support_history': "Cote d'origine: A 21069", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi�', 'series_title': "Sauvegarde d'archives. Fribourg", 'content_summary': "La Suisse se marginalise-t-elle? L'avenir de la Suisse n'est-il pas au sein de la CEE? Comment concilier adh�sion et neutralit�? Laurent Butty, auteur d'une motion transform�e en postulat sur la question, fait part de son inqui�tude quant � une �ventuelle marginalisation de la Suisse. Philippe L�vy reconna�t l'�volution de l'Europe, mais rappelle que les objectifs fondamentaux de la communaut� europ�eenne n'ont pas chang�.", 'workflow_status': 'Valid�', 'assembly_status': 'Mont�', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:28:51.992', 'work_duration_compl': 'Non', 'participants': [{'name': 'Butty, Laurent', 'function': 'Participant/e au d�bat', 'role': 'conseiller national d�mocrate-chr�tien fribourgeois'}, {'name': 'L�vy, Philippe', 'function': 'Participant/e au d�bat', 'role': 'd�l�gu� du Conseil f�d�ral aux accords commerciaux'}], 'geographical_descriptors': ['Europe', 'Suisse'], 'person_descriptors': None, 'thematical_descriptors': ['accord de libre �change', 'politique', '�conomie', 'neutralit�', 'int�gration europ�enne'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Espace 2'], 'subdomains': ['D�bat'], 'recording_dates': ['13/12/1986 - 13/12/1986'], 'first_broadcast_dates': None}
Skipping document 78/90 with OID {D179A995-BD88-4798-80ED-5CEF28B9E5F9} because it's missing its XML file!! (stt exists: False)
j13h - returning 88 documents, 2 were skipped due to missing necessary info.
 --> Adding 88 to the out csv for j13h

PROCESSING PROGRAM j13h2 (19/47) - 1 files:

Starting extracting 66 documents for program j13h2

100%|██████████| 1/1 [00:00<00:00,  3.46it/s]
19it [00:12,  1.43it/s]

Did not find any date for doc with OID {E9DF5F99-0E1A-4618-B254-FCC1B7806882}. Trying to use the recording date. doc_dict: {'alias': 'j13h2', 'date_str': None, 'stt_filename': 'E9DF5F99-0E1A-4618-B254-FCC1B7806882_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{E9DF5F99-0E1A-4618-B254-FCC1B7806882}', 'stripped_OID': 'E9DF5F99-0E1A-4618-B254-FCC1B7806882', 'login': '', 'broadcast_episode_title': 'Interview d\'Alfred Willener : Son rapport intitul� "La situation sociologique des m�dias en Suisse : Communications �mancipatrices?', 'sequence': '1', 'broadcast_program_name': 'Journal de 13h', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '28.05.2022 06:00:35', 'physical_support_history': "Cote d'origine : A 3027", 'production_type': 'Production propre', 'recording_place': 'Lausanne (Studio RSR)', 'rights_notes': None, 'rights_status': 'Clarifi�', 'series_title': None, 'content_summary': 'Conception globale des m�dias.', 'workflow_status': 'Valid�', 'assembly_status': 'Mont�', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Martel, Jean', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur RSR'}, {'name': 'Willener, Alfred', 'function': 'Interview�/e', 'role': "professeur,  directeur de l'Institut de sociologie et des communications de masse � l'Universit� de Lausanne"}, {'name': 'Gfeller, Urs', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Suisse'], 'person_descriptors': None, 'thematical_descriptors': ['mass m�dia', 'livre (imprim�)', 'vedettariat', 'radio', 't�l�vision', 'presse'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Deuxi�me programme'], 'subdomains': ['Interview'], 'recording_dates': ['27/02/1982 - 27/02/1982'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {602F781C-6391-4FAF-B897-022B9BC3E077}. Trying to use the recording date. doc_dict: {'alias': 'j13h2', 'date_str': None, 'stt_filename': '602F781C-6391-4FAF-B897-022B9BC3E077_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{602F781C-6391-4FAF-B897-022B9BC3E077}', 'stripped_OID': '602F781C-6391-4FAF-B897-022B9BC3E077', 'login': '', 'broadcast_episode_title': "Interview du secr�taire g�n�ral de l'ONU Kurt Waldheim, � propos du Proche-Orient", 'sequence': '1', 'broadcast_program_name': 'Journal de 13h', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '01.06.2022 11:31:34', 'physical_support_history': "Cote d'origine: 7535", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': None, 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid�', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Waldheim, Kurt', 'function': 'Interview�/e', 'role': "secr�taire g�n�ral de l'ONU"}, {'name': 'Inconnus', 'function': 'Interview�/e', 'role': 'journalistes RSR'}], 'geographical_descriptors': ['Proche-Orient', 'Portugal', 'Iran'], 'person_descriptors': ["Conseil de s�curit� de l'ONU", 'ONU'], 'thematical_descriptors': ['diplomatie', 'relations internationales', 'Palestiniens', 'd�colonisation'], 'rights_usage_possibilities': None, 'radio_channels': ['Deuxi�me programme'], 'subdomains': ['Interview'], 'recording_dates': ['30/04/1982 - 30/04/1982'], 'first_broadcast_dates': None}
Skipping document 57/66 with OID {D179A995-BD88-4798-80ED-5CEF28B9E5F9} because it's missing its XML file!! (stt exists: False)
j13h2 - returning 65 documents, 1 were skipped due to missing necessary info.
 --> Adding 65 to the out csv for j13h2

PROCESSING PROGRAM j_mat (20/47) - 11 files:

Starting extracting 0 documents for program j_mat
j_mat - returning 0 documents, 0 were skipped due to missing necessary info.

Starting extracting 999 documents for program j_mat
Skipping document 1/999 with OID {26ED9EB6-C7C9-4056-88A8-FB0FBF8B0915} because it's missing its XML file!! (stt exists: False)
Skipping document 2/999 with OID {9F3AE870-279E-45B9-9F8F-1B6400A2A04D} because it's missing its XML file!! (stt exists: False)
Skipping document 3/999 with OID {1CEE59EC-D842-49CF-B56A-2A4A6DCEE493} because it's missing its XML file!! (stt exists: False)
Skipping document 4/999 with OID {71974CAA-7079-455C-8F73-0C8C2B4255CD} because it's missing its XML file!! (stt exists: True)
Skipping document 5/999 with OID {6729CC58-BD78-456C-B8C1-90A9B233D88F} because it's missing its XML file!! (stt exists: True)
Skipping document 6/999 with OID {28755BC1-3D12-4FC3-9247-3DF5DC8125A3} because it's missing its XML file!! (stt exists: True)
Skipping document 7/999 with OID {DC5CFE35-ABFB-4319-944A-D26BDD0B99AB} because it's missing its XML file!! (stt exists: False)
Skipping document 8/999 with OID {477F12A4-04CD-4B49-9F87-ED1DC6451261} because it's missing its XML file!! (stt exists: True)
Skipping document 9/999 with OID {7504DAAE-A2C8-4F64-9BEB-6C4425CDB905} because it's missing its XML file!! (stt exists: True)
Skipping document 10/999 with OID {BE71D304-259D-4EC6-A145-CD354A604689} because it's missing its XML file!! (stt exists: False)
Skipping document 11/999 with OID {E535FD09-5604-4C7F-A9CE-7015F6B85EFA} because it's missing its XML file!! (stt exists: False)
Skipping document 26/999 with OID {A7CEC483-3251-4676-897E-0DF3FD068AD0} because it's missing its XML file!! (stt exists: False)
Skipping document 29/999 with OID {EE66025A-BA32-4D63-8CF9-2EFF72860C9B} because it's missing its XML file!! (stt exists: False)
Skipping document 30/999 with OID {D1E7388E-072B-42D3-BB3F-8CD12987ECB9} because it's missing its XML file!! (stt exists: False)
Skipping document 33/999 with OID {C6179746-8A4B-469E-A11D-32DC659D0B4A} because it's missing its XML file!! (stt exists: True)
Skipping document 34/999 with OID {DD24E7FC-6E6A-40BB-AB86-9F6AA7F50F7F} because it's missing its XML file!! (stt exists: True)
Skipping document 35/999 with OID {2A461CE9-CEFF-4E21-8D4B-A5B209576627} because it's missing its XML file!! (stt exists: True)
Skipping document 37/999 with OID {AAA0208F-5899-47B1-80EE-92D8FE7E789E} because it's missing its XML file!! (stt exists: False)
Skipping document 38/999 with OID {1D876C4E-A5E9-49C0-A312-7F2C0313DA1C} because it's missing its XML file!! (stt exists: False)
Skipping document 39/999 with OID {C7DF1C55-83A2-4418-B341-5BF7BCE59747} because it's missing its XML file!! (stt exists: False)
Skipping document 41/999 with OID {5D377E1C-F572-425F-B28E-6B7D01582C6E} because it's missing its XML file!! (stt exists: True)
Skipping document 42/999 with OID {D56E8D8A-DE55-4D87-B410-209BAB2EA19E} because it's missing its XML file!! (stt exists: False)
Skipping document 43/999 with OID {A5DFD7A1-C429-42E0-8E81-BA4DDC377547} because it's missing its XML file!! (stt exists: False)
Skipping document 47/999 with OID {F316C3CE-C236-4EDB-A6E4-E8D713EAF53F} because it's missing its XML file!! (stt exists: False)
Skipping document 48/999 with OID {DE33E21A-F715-42B7-9D03-5ED6321BE2AE} because it's missing its XML file!! (stt exists: True)
Skipping document 49/999 with OID {532E2BE0-A4CE-4E92-B0C4-F2F7500E6584} because it's missing its XML file!! (stt exists: False)
Skipping document 53/999 with OID {619D0052-5E5F-4961-A192-77B905D0DC71} because it's missing its XML file!! (stt exists: False)
Skipping document 54/999 with OID {7E6C229F-3CF3-4EB4-BA32-207138E8B3A5} because it's missing its XML file!! (stt exists: False)
Skipping document 55/999 with OID {8DC34971-80B6-4252-9DFA-CE3B0EDDF3DA} because it's missing its XML file!! (stt exists: False)
Skipping document 56/999 with OID {7EE84E55-63CD-45F4-A00E-6E5FE51C419D} because it's missing its XML file!! (stt exists: False)
Skipping document 57/999 with OID {6F6A276C-4F1B-4318-ACA0-FE124C5E1272} because it's missing its XML file!! (stt exists: False)
Skipping document 59/999 with OID {FE85083D-69F3-4B70-8310-23FD04F55CE8} because it's missing its XML file!! (stt exists: True)
Skipping document 60/999 with OID {D023B236-2632-47C3-B289-5439C15A5FC9} because it's missing its XML file!! (stt exists: True)
Skipping document 63/999 with OID {5AF61AF3-46F1-4CC7-A523-62BBC31E81EE} because it's missing its XML file!! (stt exists: False)
Skipping document 64/999 with OID {F9091119-BDF8-4D5A-A297-AE9A1703F5AF} because it's missing its XML file!! (stt exists: False)
Skipping document 67/999 with OID {1D3899C5-C1F3-43ED-BA26-21377FAC4DA4} because it's missing its XML file!! (stt exists: False)
Skipping document 71/999 with OID {11566E23-5297-402A-AF91-A76ADCADA145} because it's missing its XML file!! (stt exists: False)
Skipping document 74/999 with OID {FF70A175-0C53-481B-AB39-38403820CED0} because it's missing its XML file!! (stt exists: False)
Skipping document 78/999 with OID {6D1DEEB1-C8DD-4939-9141-4E71315D6FFC} because it's missing its XML file!! (stt exists: False)
Skipping document 79/999 with OID {539989FA-08CE-4E97-98A1-8CD4FAF4B8B1} because it's missing its XML file!! (stt exists: False)
Skipping document 84/999 with OID {61619E77-74C4-42A5-8E77-060704B2EC90} because it's missing its XML file!! (stt exists: False)
Skipping document 85/999 with OID {5DE27FC6-BAB4-4DFE-BA19-AF2D3541C34D} because it's missing its XML file!! (stt exists: False)
Skipping document 86/999 with OID {129CC6F6-57FE-45BD-9588-4B6F73E6458B} because it's missing its XML file!! (stt exists: False)
Skipping document 89/999 with OID {8CEE7505-E0AF-44F2-85E7-F006529D0C3B} because it's missing its XML file!! (stt exists: False)
Skipping document 93/999 with OID {941CCAA5-B979-413B-9480-683423B17636} because it's missing its XML file!! (stt exists: False)
Skipping document 94/999 with OID {FF06BC98-BA01-413E-B85E-EC7A246E1738} because it's missing its XML file!! (stt exists: False)
Skipping document 95/999 with OID {B7A93754-944D-40B4-9F4F-779088769BAF} because it's missing its XML file!! (stt exists: False)
Skipping document 96/999 with OID {F7D8F464-26BC-410F-B4E8-76E685942323} because it's missing its XML file!! (stt exists: False)
Skipping document 99/999 with OID {8D556CE4-A9DE-4EE8-A4A3-515607EB7894} because it's missing its XML file!! (stt exists: True)
Skipping document 100/999 with OID {BE817AFE-3EE7-4E9A-9036-A5EB39F11CA1} because it's missing its XML file!! (stt exists: False)
Skipping document 103/999 with OID {76380A10-F487-4BFF-AF39-DCAD4AF9A41D} because it's missing its XML file!! (stt exists: False)
Skipping document 104/999 with OID {9A180E45-C75A-41AD-9F25-2D04B4192F61} because it's missing its XML file!! (stt exists: False)
Skipping document 105/999 with OID {EA69C7DF-63C0-4CEA-9CE3-22723B3EC1E9} because it's missing its XML file!! (stt exists: False)
Skipping document 110/999 with OID {CEE86EA8-02EE-410D-9082-EDFF5C70D210} because it's missing its XML file!! (stt exists: False)
Skipping document 111/999 with OID {77ADD2CE-91C1-41D0-AF39-B58EE245FCE3} because it's missing its XML file!! (stt exists: False)
Skipping document 112/999 with OID {3A949B4B-2CFB-44A9-A142-FA0D4927187A} because it's missing its XML file!! (stt exists: True)
Skipping document 113/999 with OID {2FA0F591-85A5-43F2-BBF8-2C400505105F} because it's missing its XML file!! (stt exists: False)
Skipping document 114/999 with OID {61AA35FD-943E-47FD-87CA-0593DDB53645} because it's missing its XML file!! (stt exists: False)
Skipping document 131/999 with OID {0593AAA5-EA44-40C6-B419-9F5459813680} because it's missing its XML file!! (stt exists: True)
Skipping document 132/999 with OID {540DEA7A-A9EB-4F3E-A756-060B11CFC8E8} because it's missing its XML file!! (stt exists: True)
Skipping document 134/999 with OID {E82C3044-9DA0-4B4E-BF92-ECE51461EF7F} because it's missing its XML file!! (stt exists: False)
Skipping document 139/999 with OID {D1B5E35A-EC4A-4E71-A38D-59B729363272} because it's missing its XML file!! (stt exists: False)
Skipping document 144/999 with OID {79331F52-79CC-4D44-A1A1-45172DD36D13} because it's missing its XML file!! (stt exists: False)
Skipping document 151/999 with OID {480B3B5C-3F21-4FA5-941E-76DDBD718B7D} because it's missing its XML file!! (stt exists: True)
Skipping document 152/999 with OID {1A385274-40BA-498A-B2F8-D92C2E7FBAAB} because it's missing its XML file!! (stt exists: False)
Skipping document 153/999 with OID {C28C0934-FDFF-4B54-922A-4F1B272DF720} because it's missing its XML file!! (stt exists: False)
Skipping document 155/999 with OID {92604900-978F-49C5-8A07-586EA488F286} because it's missing its XML file!! (stt exists: True)
Skipping document 160/999 with OID {64BACB86-67D6-43F2-B1E4-9221C563C6E9} because it's missing its XML file!! (stt exists: False)
Skipping document 162/999 with OID {E48F1539-EF87-4B89-BB3C-98FA0084E6EC} because it's missing its XML file!! (stt exists: False)
Skipping document 163/999 with OID {ED19BF03-4DF0-4421-B84D-82359F0D105D} because it's missing its XML file!! (stt exists: False)
Skipping document 164/999 with OID {99F0F41E-373F-4E39-B56B-6497CF7489D3} because it's missing its XML file!! (stt exists: False)
Skipping document 168/999 with OID {D4AF38C0-90EA-4855-A53E-CDEAEFC2DFDD} because it's missing its XML file!! (stt exists: True)
Skipping document 170/999 with OID {5E7BD8D9-6882-4819-B0FA-115B8EAE32A6} because it's missing its XML file!! (stt exists: False)
Skipping document 171/999 with OID {74AB562E-173D-4048-A773-FAD0EC5251BB} because it's missing its XML file!! (stt exists: False)
Skipping document 175/999 with OID {3AC5B507-3A02-44FD-87B9-3A6F7DC9F409} because it's missing its XML file!! (stt exists: True)
Skipping document 177/999 with OID {E935E42F-32E1-46C1-B2E6-17141B3C4B12} because it's missing its XML file!! (stt exists: False)
Skipping document 179/999 with OID {4703386A-4E72-4D89-AD2C-1D006CA5443A} because it's missing its XML file!! (stt exists: True)
Skipping document 180/999 with OID {6865641E-0142-4697-BB62-7E5D7624508B} because it's missing its XML file!! (stt exists: True)
Skipping document 181/999 with OID {30386EB0-7C5B-4FF3-BDD7-6976919DAEB7} because it's missing its XML file!! (stt exists: True)
Skipping document 183/999 with OID {B9457F25-CD76-47B5-8DCE-0C29BCA47016} because it's missing its XML file!! (stt exists: False)
Skipping document 187/999 with OID {DA64F69A-DA76-4102-B019-D6DD5499742F} because it's missing its XML file!! (stt exists: False)
Skipping document 188/999 with OID {5D2C6DDB-7A6C-47D1-B876-61C7F2BB259D} because it's missing its XML file!! (stt exists: False)
Skipping document 189/999 with OID {369C0B68-24DD-4A3A-9CD1-5D09FD0276CD} because it's missing its XML file!! (stt exists: False)
Skipping document 193/999 with OID {E10DED78-3B55-4E7E-87EC-1AE239E65CD6} because it's missing its XML file!! (stt exists: False)
Skipping document 201/999 with OID {DDC2F37C-DADF-4781-A35F-1426927A1792} because it's missing its XML file!! (stt exists: False)
Skipping document 207/999 with OID {CEF2DDBA-6211-47A5-AD53-1616B8B9DDA3} because it's missing its XML file!! (stt exists: False)
Skipping document 208/999 with OID {D889B40F-F865-4531-B107-03AF62A2543C} because it's missing its XML file!! (stt exists: True)
Skipping document 209/999 with OID {C7F58B0D-8416-4C57-B52C-6580608D6C38} because it's missing its XML file!! (stt exists: False)
Skipping document 212/999 with OID {2F476A24-CF59-4F83-AFE8-FAB7A4279661} because it's missing its XML file!! (stt exists: True)
Skipping document 214/999 with OID {1193221D-3E6F-436F-A20E-CB7638B93041} because it's missing its XML file!! (stt exists: True)
Skipping document 216/999 with OID {0CE55DB9-D9E5-449C-8A0E-7D2F54F3A4EA} because it's missing its XML file!! (stt exists: False)
Skipping document 220/999 with OID {A8549201-90EB-48F2-9069-FD650AFA30DA} because it's missing its XML file!! (stt exists: False)
Skipping document 223/999 with OID {37895705-6E8C-4CE2-9935-04A4337EF453} because it's missing its XML file!! (stt exists: False)
Skipping document 226/999 with OID {DBA44269-412E-4872-B44A-A8932C25D05C} because it's missing its XML file!! (stt exists: False)
Skipping document 227/999 with OID {5F0D9077-6FFE-4438-BCA3-7FB4A60A653E} because it's missing its XML file!! (stt exists: False)
Skipping document 233/999 with OID {90CB044A-E723-47AD-9A14-FFEA141DD563} because it's missing its XML file!! (stt exists: False)
Skipping document 237/999 with OID {5044FD72-111B-4450-BB06-93A8F6479C81} because it's missing its XML file!! (stt exists: False)
Skipping document 238/999 with OID {4ED52CEE-83EC-4319-8508-98624E979DE1} because it's missing its XML file!! (stt exists: False)
Skipping document 239/999 with OID {E9B2F66A-F72F-4087-B2D3-361F1B6E57C7} because it's missing its XML file!! (stt exists: False)
Skipping document 242/999 with OID {19D4383C-1A1E-462F-BD92-6C87699C7A8B} because it's missing its XML file!! (stt exists: True)
Skipping document 243/999 with OID {FF911890-0658-402F-9302-4B4072B64ADE} because it's missing its XML file!! (stt exists: True)
Skipping document 244/999 with OID {B2963AE5-8F18-4E82-A3C5-067F955E885E} because it's missing its XML file!! (stt exists: True)
Skipping document 245/999 with OID {CE244503-7FDB-4120-AE50-F5CDE69D3F98} because it's missing its XML file!! (stt exists: False)
Skipping document 246/999 with OID {34159E6C-FF20-4034-B1A6-3FA6BBB01913} because it's missing its XML file!! (stt exists: False)
Skipping document 247/999 with OID {A7C5CC43-CCA4-4E2C-8789-07A3ACABE237} because it's missing its XML file!! (stt exists: False)
Skipping document 248/999 with OID {9873418E-AC14-4966-8264-852D6F63FA9B} because it's missing its XML file!! (stt exists: True)
Skipping document 249/999 with OID {44463162-A2ED-4BEC-94B0-2DB061E9F4D9} because it's missing its XML file!! (stt exists: True)
Skipping document 250/999 with OID {96C946B7-614E-4990-AC17-37CD8DFF3E17} because it's missing its XML file!! (stt exists: True)
Skipping document 251/999 with OID {9DC217EE-9045-426B-99C2-01F39639F870} because it's missing its XML file!! (stt exists: True)
Skipping document 252/999 with OID {5DA539A8-FB0C-4DE0-841F-8847959BC4F7} because it's missing its XML file!! (stt exists: True)
Skipping document 253/999 with OID {827FD616-4CCB-4DFE-9378-39B42C34E8A9} because it's missing its XML file!! (stt exists: True)
Skipping document 255/999 with OID {AF1F9E28-5B20-4250-856E-04117E0E8799} because it's missing its XML file!! (stt exists: True)
Skipping document 257/999 with OID {A895162B-33AB-4F60-B0A0-78D48CBCEB88} because it's missing its XML file!! (stt exists: False)
Skipping document 258/999 with OID {2C9CD5F2-2866-4F88-B0F1-6B5FB8BD20F8} because it's missing its XML file!! (stt exists: False)
Skipping document 259/999 with OID {A3707615-7A01-46DB-BBB1-E5A6779E4A33} because it's missing its XML file!! (stt exists: False)
Skipping document 261/999 with OID {2935312C-D3CB-458A-A7BC-07B3B0C51A45} because it's missing its XML file!! (stt exists: False)
Skipping document 262/999 with OID {B775389E-4742-4787-AF17-3BC4E9170895} because it's missing its XML file!! (stt exists: False)
Skipping document 263/999 with OID {178E37CE-02E8-4C53-9192-1FAD5BAF7573} because it's missing its XML file!! (stt exists: False)
Skipping document 265/999 with OID {6B515B33-5AFE-4F41-8456-67121CDE254B} because it's missing its XML file!! (stt exists: False)
Skipping document 266/999 with OID {0A34AF4C-C08A-40C1-BEEA-088CB0C5CFDC} because it's missing its XML file!! (stt exists: False)
Skipping document 267/999 with OID {DBC99878-55C5-4876-9F32-6D14D735109C} because it's missing its XML file!! (stt exists: False)
Skipping document 268/999 with OID {394662C1-3771-44DD-89FC-FC66053E4B5B} because it's missing its XML file!! (stt exists: False)
Skipping document 269/999 with OID {3542C460-A6D6-449C-B36C-95DBE6A261E7} because it's missing its XML file!! (stt exists: False)
Skipping document 270/999 with OID {B91AD6A1-CA62-4D8F-AB6B-3B3A8BA1FFBB} because it's missing its XML file!! (stt exists: False)
Skipping document 273/999 with OID {F9381019-746E-419B-A4FD-6631B34E5625} because it's missing its XML file!! (stt exists: False)
Skipping document 274/999 with OID {677811C0-4EE8-4433-88F0-C0260B414D95} because it's missing its XML file!! (stt exists: False)
Skipping document 275/999 with OID {1510EB92-B240-411F-BEE0-FE7F580A706F} because it's missing its XML file!! (stt exists: False)
Skipping document 276/999 with OID {8B63591D-6B3E-4D6E-829B-7D6B2027AA62} because it's missing its XML file!! (stt exists: False)
Skipping document 280/999 with OID {E73E1A58-0A1A-4ED6-8199-20F8AA9FC74A} because it's missing its XML file!! (stt exists: False)
Skipping document 281/999 with OID {1AB66F62-0F46-4D35-93CB-12C18FA35230} because it's missing its XML file!! (stt exists: False)
Skipping document 285/999 with OID {60BB7C58-F9EC-41CD-B5EC-69D362C7DBC7} because it's missing its XML file!! (stt exists: False)
Skipping document 286/999 with OID {C13EC580-FEAA-4C1E-886A-5D831B73D28D} because it's missing its XML file!! (stt exists: True)
Skipping document 287/999 with OID {F9C5FADD-7802-46CD-A40F-CBDCCECF881F} because it's missing its XML file!! (stt exists: True)
Skipping document 289/999 with OID {64EF313F-F469-4135-AA94-A8A9460051EE} because it's missing its XML file!! (stt exists: True)
Skipping document 291/999 with OID {D830F246-16B7-43FB-BBC9-03357829BD11} because it's missing its XML file!! (stt exists: True)
Skipping document 295/999 with OID {DFDF5348-00CE-4B8F-B0A5-68FB7426CAA8} because it's missing its XML file!! (stt exists: True)
Skipping document 297/999 with OID {DF7745DE-C838-4FC3-BB7B-D366C5F36B88} because it's missing its XML file!! (stt exists: False)
Skipping document 298/999 with OID {2A2308BC-5D83-4E7D-ABBF-3016768A7DCD} because it's missing its XML file!! (stt exists: False)
Skipping document 305/999 with OID {70DC1098-7266-49E9-B983-A1412DF1A2E3} because it's missing its XML file!! (stt exists: False)
Skipping document 307/999 with OID {13B6C7F3-8349-4367-8ED2-C333815ACD94} because it's missing its XML file!! (stt exists: False)
Skipping document 308/999 with OID {5CACB450-9886-4904-985E-F9D5BD6C490B} because it's missing its XML file!! (stt exists: False)
Skipping document 309/999 with OID {289F391F-3FE3-45D7-8AF8-94F17C457F50} because it's missing its XML file!! (stt exists: False)
Skipping document 312/999 with OID {D7EABEEE-8746-454A-82E9-78D350A8973B} because it's missing its XML file!! (stt exists: False)
Skipping document 318/999 with OID {CB25CF08-E0B6-4DE4-8844-35F9591A1373} because it's missing its XML file!! (stt exists: False)
Skipping document 319/999 with OID {D4E6B443-132A-41A0-9859-74D4DDD41FD7} because it's missing its XML file!! (stt exists: True)
Skipping document 320/999 with OID {5066E664-5F98-49A1-BA37-4614ED56F710} because it's missing its XML file!! (stt exists: False)
Skipping document 322/999 with OID {37CC3C9B-9344-4170-BE23-2ADFB62C2539} because it's missing its XML file!! (stt exists: True)
Skipping document 323/999 with OID {1FBA91BD-8AC9-4446-B6A7-75F46D43939A} because it's missing its XML file!! (stt exists: True)
Skipping document 331/999 with OID {0A99ADA1-3142-4BC8-A705-DECA134EF6A9} because it's missing its XML file!! (stt exists: False)
Skipping document 337/999 with OID {6B15E66E-4E6F-44DF-9277-68ECCA4E32DE} because it's missing its XML file!! (stt exists: False)
Skipping document 339/999 with OID {2024C14F-EAB4-40FF-B770-EA0E6B759554} because it's missing its XML file!! (stt exists: False)
Skipping document 340/999 with OID {BD93AFF7-9FF5-41E9-84A0-BC51353EC21A} because it's missing its XML file!! (stt exists: False)
Skipping document 341/999 with OID {6F8AD249-9ADA-4C50-8EC5-7AC26FA22D96} because it's missing its XML file!! (stt exists: False)

Skipping document 901/999 with OID {A426DEEE-68C1-4987-A4E4-2E47BA086AB1} because it's missing its XML file!! (stt exists: False)
Skipping document 902/999 with OID {8495A7E9-7DCE-4389-BA64-962EA7D44057} because it's missing its XML file!! (stt exists: False)
Skipping document 903/999 with OID {B7C4B81A-D1FF-4DC7-9529-CB5EB9A6D0A8} because it's missing its XML file!! (stt exists: False)
Skipping document 904/999 with OID {9236BE44-6CA9-474B-85C8-A78C51418A46} because it's missing its XML file!! (stt exists: False)
Skipping document 907/999 with OID {7D0721AE-EA44-4C86-97FD-B99CF5F1BC10} because it's missing its XML file!! (stt exists: False)
Skipping document 914/999 with OID {CB69F524-D0F0-4154-BDBE-96ACBB559A84} because it's missing its XML file!! (stt exists: False)
Skipping document 917/999 with OID {6F69DAE7-0B09-4366-9F80-8091F6A25E71} because it's missing its XML file!! (stt exists: True)
Skipping document 920/999 with OID {D503CCC6-A8F2-4C6C-8D63-194D465A32F3} because it's missing its XML file!! (stt exists: False)
Skipping document 923/999 with OID {95B01FC7-4711-421B-B157-E145A57BE4D2} because it's missing its XML file!! (stt exists: False)
Skipping document 924/999 with OID {E6C4C440-CC98-4ECB-9040-6AED3E44FD8C} because it's missing its XML file!! (stt exists: False)
Skipping document 925/999 with OID {33161EDA-E4F4-4BB4-B2EA-C928D130C3F6} because it's missing its XML file!! (stt exists: False)
Skipping document 930/999 with OID {12C8664C-745B-4B51-8709-7E2C0F21D8BE} because it's missing its XML file!! (stt exists: False)
Skipping document 931/999 with OID {ACF8A52F-5BDA-4BA6-A73B-28B80C0182EA} because it's missing its XML file!! (stt exists: False)
Skipping document 932/999 with OID {847D29F8-5B30-4C92-8601-B38418367CE3} because it's missing its XML file!! (stt exists: False)
Skipping document 941/999 with OID {53674CEB-5955-4D73-9384-68BA8D587AEE} because it's missing its XML file!! (stt exists: False)
Skipping document 942/999 with OID {0B395959-82A8-4AB2-89C5-71E1E5269079} because it's missing its XML file!! (stt exists: False)
Skipping document 943/999 with OID {D03D9B2B-E1BA-4B57-B9AA-7EAEE70AE622} because it's missing its XML file!! (stt exists: False)
Skipping document 944/999 with OID {DE1F472C-9CA1-424B-80B1-E63AFB7A0C70} because it's missing its XML file!! (stt exists: False)
Skipping document 945/999 with OID {B4FCF8F7-37CF-45EB-82E9-BD62AD85C219} because it's missing its XML file!! (stt exists: False)
Skipping document 948/999 with OID {3F68221D-CE21-4EDB-944A-D38CD949E9F7} because it's missing its XML file!! (stt exists: False)
Skipping document 950/999 with OID {682E290B-4A1A-405A-AFBC-8B6789B46645} because it's missing its XML file!! (stt exists: False)
Skipping document 951/999 with OID {1162CF18-BE69-4AEA-8767-DA966EB9C7A0} because it's missing its XML file!! (stt exists: False)
Skipping document 954/999 with OID {CC53A3AD-A78D-4D80-9455-AEFF0A7DA583} because it's missing its XML file!! (stt exists: False)
Skipping document 955/999 with OID {20FE83B0-E4F1-4220-8087-32FEA4596935} because it's missing its XML file!! (stt exists: False)
Skipping document 956/999 with OID {9CF2241E-0C94-4A8F-AB7A-3F82959E566A} because it's missing its XML file!! (stt exists: False)
Skipping document 960/999 with OID {96BC57FC-90D8-4AE1-B820-8C6AA4021ABB} because it's missing its XML file!! (stt exists: False)
Skipping document 961/999 with OID {0FD0DD6A-6C51-44B5-B69A-31689A9FEF83} because it's missing its XML file!! (stt exists: False)
Skipping document 962/999 with OID {1109DE50-43A1-4E46-9165-3A6CBD791563} because it's missing its XML file!! (stt exists: False)
Skipping document 966/999 with OID {A10AB123-C328-4C51-8A0A-F16A5DA2DD08} because it's missing its XML file!! (stt exists: False)
Skipping document 968/999 with OID {86CF8FDF-DD78-421C-B10B-051910041104} because it's missing its XML file!! (stt exists: False)
Skipping document 972/999 with OID {0C17E193-8C5F-4889-B138-D04FD5FCB93B} because it's missing its XML file!! (stt exists: False)
Skipping document 976/999 with OID {3E3B8A77-E058-4A4B-AC57-C1937EE70FE2} because it's missing its XML file!! (stt exists: True)
Skipping document 977/999 with OID {FAFE5B5A-6E42-4473-BF7E-E56C8EB9579D} because it's missing its XML file!! (stt exists: False)
Skipping document 979/999 with OID {A03901CE-C46B-4188-86A0-E5AA2DFF7EB2} because it's missing its XML file!! (stt exists: False)
Skipping document 980/999 with OID {B3905F92-1298-456A-A809-E1DEE58006CD} because it's missing its XML file!! (stt exists: False)
Skipping document 981/999 with OID {CD393BDB-C235-472F-A48F-D1788A61A86D} because it's missing its XML file!! (stt exists: False)
Skipping document 982/999 with OID {960A8FDF-7C80-4231-BA5D-3B300E5D44D7} because it's missing its XML file!! (stt exists: False)
Skipping document 984/999 with OID {A1A20AE6-A3EC-431C-BF0C-9F35DFA16ECA} because it's missing its XML file!! (stt exists: True)
Skipping document 993/999 with OID {EFDAA6E8-3E38-4135-9462-8CF3D26494C3} because it's missing its XML file!! (stt exists: True)
Skipping document 996/999 with OID {111D6F29-CEDA-40C3-9B88-D844B46DDE6C} because it's missing its XML file!! (stt exists: False)
Skipping document 997/999 with OID {3FDAF7AF-B6C7-4F69-A869-FA1ACEC3217E} because it's missing its XML file!! (stt exists: False)
j_mat - returning 623 documents, 376 were skipped due to missing necessary info.

Starting extracting 999 documents for program j_mat
Skipping document 13/999 with OID {CC277DEC-994C-4134-92F4-E5DDD380BB0F} because it's missing its XML file!! (stt exists: False)
Skipping document 14/999 with OID {1B993CF2-5270-4A47-93C8-D9F383A3E596} because it's missing its XML file!! (stt exists: True)
Skipping document 18/999 with OID {C5581742-F191-4640-933C-27CA04925B82} because it's missing its XML file!! (stt exists: False)
Skipping document 19/999 with OID {9732F173-EDC6-43EB-BD95-5BD3837A0D85} because it's missing its XML file!! (stt exists: False)
Skipping document 27/999 with OID {9B101273-39FA-4374-A1E5-49EF02668D7A} because it's missing its XML file!! (stt exists: False)
Skipping document 29/999 with OID {3CC1EFC4-D7B9-425E-A2D4-5E3A988AB1A8} because it's missing its XML file!! (stt exists: False)
Skipping document 36/999 with OID {397D4C10-F228-4D2B-BCB8-737B7D187B05} because it's missing its XML file!! (stt exists: False)
Skipping document 39/999 with OID {B2BDC61C-8D24-4C64-AFAD-FD20BF2EA1D6} because it's missing its XML file!! (stt exists: False)
Skipping document 47/999 with OID {183E69B8-E3BF-4034-BE21-75824E1C6FBA} because it's missing its XML file!! (stt exists: False)
Skipping document 55/999 with OID {88D5AC4A-A16D-4DBC-8CD2-3BB1DAD0712C} because it's missing its XML file!! (stt exists: True)
Skipping document 56/999 with OID {730560EA-5C89-495E-A37D-86A2A6B5266D} because it's missing its XML file!! (stt exists: False)
Skipping document 59/999 with OID {D5E3E1A5-8671-435B-836E-39968DB98C0F} because it's missing its XML file!! (stt exists: True)
Skipping document 64/999 with OID {B7EDD96D-F27C-4EF3-9105-1F38DFEFEBDF} because it's missing its XML file!! (stt exists: False)
Skipping document 65/999 with OID {CE10F663-E63F-401A-A2A6-3AEB1C851484} because it's missing its XML file!! (stt exists: False)
Skipping document 69/999 with OID {A10279F4-A72E-42ED-A96C-63778A94A594} because it's missing its XML file!! (stt exists: False)
Skipping document 71/999 with OID {C90AAFA6-8995-43EC-806E-ECE2BB966D2D} because it's missing its XML file!! (stt exists: True)
Skipping document 74/999 with OID {C21E552D-ECDE-4E44-8B2B-ABBDF93CDF4B} because it's missing its XML file!! (stt exists: False)
Skipping document 75/999 with OID {8E739092-05AD-4B47-9617-BCDA90B9646E} because it's missing its XML file!! (stt exists: False)
Skipping document 76/999 with OID {4FAF0B3E-C6D7-4B54-9621-AC396CC5BDF6} because it's missing its XML file!! (stt exists: True)
Skipping document 79/999 with OID {16A7C22A-11E7-481E-A042-1869F5648EBA} because it's missing its XML file!! (stt exists: False)
Skipping document 83/999 with OID {95FA0176-D129-4A36-91D8-805E8363E777} because it's missing its XML file!! (stt exists: True)
Skipping document 84/999 with OID {A6D757C7-3639-495C-8CF8-FB1A3B7EF810} because it's missing its XML file!! (stt exists: True)
Skipping document 85/999 with OID {AE466B13-6D6D-43AF-BD88-4F15560DEE28} because it's missing its XML file!! (stt exists: True)
Skipping document 86/999 with OID {8ACB161A-95D5-48F1-B48C-0262C63DCC03} because it's missing its XML file!! (stt exists: True)
Skipping document 87/999 with OID {1C7F660E-2C10-45B1-A798-D307B3632488} because it's missing its XML file!! (stt exists: False)
Skipping document 88/999 with OID {671232C7-376E-4186-9BC4-D4EF6FF31EBD} because it's missing its XML file!! (stt exists: False)
Skipping document 93/999 with OID {6BE91F81-EBE6-4C0E-BD46-CBC22D346EBE} because it's missing its XML file!! (stt exists: False)
Skipping document 95/999 with OID {48704ED4-8EA9-4B74-9BD6-EF0E2CD977FC} because it's missing its XML file!! (stt exists: True)
Skipping document 96/999 with OID {CA3CE667-1206-4D18-8709-D046A13AA278} because it's missing its XML file!! (stt exists: True)
Skipping document 97/999 with OID {5A06779F-B3F5-4672-A7CF-7EAAD747B887} because it's missing its XML file!! (stt exists: True)
Skipping document 98/999 with OID {039B9CFF-EA6D-4346-A0A3-5265F72FD988} because it's missing its XML file!! (stt exists: True)
Skipping document 100/999 with OID {0B52D26B-9522-4525-B65E-129FDC2C112B} because it's missing its XML file!! (stt exists: True)
Skipping document 101/999 with OID {747B30FC-D41C-4AE2-9002-153CEBD65E1A} because it's missing its XML file!! (stt exists: True)
Skipping document 102/999 with OID {80770D1C-B199-4CB4-AB33-FE31397BC644} because it's missing its XML file!! (stt exists: False)
Skipping document 108/999 with OID {44885334-FFAD-475E-9944-70B8367802BF} because it's missing its XML file!! (stt exists: False)
Skipping document 111/999 with OID {99B7EF06-1EA8-4460-A655-9E4C51121FC7} because it's missing its XML file!! (stt exists: True)
Skipping document 112/999 with OID {1862BAF9-8EDE-460F-BC8F-26D9AC05E136} because it's missing its XML file!! (stt exists: True)
Skipping document 113/999 with OID {8E86522B-D8A1-4629-9814-251E84361318} because it's missing its XML file!! (stt exists: True)
Skipping document 114/999 with OID {BD72995B-0DD6-4D24-A49C-8DE4CD8AEC24} because it's missing its XML file!! (stt exists: True)
Skipping document 115/999 with OID {AC3583A9-E351-47A8-86BB-23CD2884F5C0} because it's missing its XML file!! (stt exists: True)
Skipping document 116/999 with OID {2DA5AD62-922E-4867-9F21-3D7FDF7558E8} because it's missing its XML file!! (stt exists: True)
Skipping document 117/999 with OID {C9274842-B618-4DD3-B6DD-61ACF28FB18E} because it's missing its XML file!! (stt exists: True)
Skipping document 118/999 with OID {80D276DE-EE7A-4924-91F1-35FDE035F245} because it's missing its XML file!! (stt exists: True)
Skipping document 119/999 with OID {41C81713-6386-49BA-8DA5-A717B777FE96} because it's missing its XML file!! (stt exists: True)
Skipping document 120/999 with OID {4A8C544C-F79C-4BBA-8E8F-24AEC145710F} because it's missing its XML file!! (stt exists: True)
Skipping document 121/999 with OID {525861FB-B5B4-4BF4-AC73-293AE8C268CF} because it's missing its XML file!! (stt exists: True)
Skipping document 122/999 with OID {F0DDA8B2-D540-4CB0-88B6-D3AA19108355} because it's missing its XML file!! (stt exists: True)
Skipping document 124/999 with OID {0F44C4E5-12EE-4B72-9D9B-80EAC8B6405C} because it's missing its XML file!! (stt exists: False)
Skipping document 128/999 with OID {E609A856-ED85-4450-9387-1C4E1DF9987A} because it's missing its XML file!! (stt exists: False)
Skipping document 129/999 with OID {D078FD4E-7133-4C33-A6CE-591278562503} because it's missing its XML file!! (stt exists: False)
Skipping document 130/999 with OID {24BC911B-D79F-4A63-9B7A-2E9B5C2C799A} because it's missing its XML file!! (stt exists: True)
Skipping document 131/999 with OID {92DA2DEF-AB16-409A-8337-C8E9938D5AFC} because it's missing its XML file!! (stt exists: True)
Skipping document 132/999 with OID {CF6236EA-C52A-426D-A972-2B2D16F88456} because it's missing its XML file!! (stt exists: False)
Skipping document 133/999 with OID {EB1BD5F7-9C1A-4758-B0FA-66A9665F3A3A} because it's missing its XML file!! (stt exists: True)
Skipping document 137/999 with OID {94FA0143-1D05-48E6-878C-3E263D713C65} because it's missing its XML file!! (stt exists: True)
Skipping document 138/999 with OID {3AE3A25C-9429-4786-BC74-9A85C83FF725} because it's missing its XML file!! (stt exists: False)
Skipping document 139/999 with OID {DEF7832B-F2F0-46E0-9114-72A6CDC30008} because it's missing its XML file!! (stt exists: False)
Skipping document 142/999 with OID {6DE307D4-7168-427E-B44B-BBAFE5CBCD7D} because it's missing its XML file!! (stt exists: False)
Skipping document 149/999 with OID {FE3FE28D-107D-45CF-94E2-AB163E7BD7DB} because it's missing its XML file!! (stt exists: False)
Skipping document 157/999 with OID {57D5C677-7EF0-4242-BC3D-2839C1662C33} because it's missing its XML file!! (stt exists: True)
Skipping document 158/999 with OID {A500C846-2A4B-4256-8BEB-C8AA311DF0EE} because it's missing its XML file!! (stt exists: True)
Skipping document 159/999 with OID {36758B74-E522-4C57-976D-DBA7766E7144} because it's missing its XML file!! (stt exists: True)
Skipping document 162/999 with OID {7647B635-A4AC-4BF0-8E13-72199257BBCD} because it's missing its XML file!! (stt exists: False)
Skipping document 165/999 with OID {FF111699-2A38-445A-92F7-17037A982917} because it's missing its XML file!! (stt exists: False)
Skipping document 166/999 with OID {9756B892-49B5-4D9C-AA99-582E41DF487F} because it's missing its XML file!! (stt exists: True)
Skipping document 167/999 with OID {FBD3EFD1-EA03-4E77-AD26-10D81B9D880C} because it's missing its XML file!! (stt exists: True)
Skipping document 169/999 with OID {B8FE6F13-92BA-4ADF-AF1F-F6FA2C496974} because it's missing its XML file!! (stt exists: True)
Skipping document 174/999 with OID {4AEB6D10-F91A-45A9-A776-1B878ED23667} because it's missing its XML file!! (stt exists: False)
Skipping document 177/999 with OID {E384BE72-67D5-4B2D-BF57-B022325BA758} because it's missing its XML file!! (stt exists: False)
Skipping document 178/999 with OID {DC9AF905-D86A-4CEF-AE7B-BCE379EE1103} because it's missing its XML file!! (stt exists: False)
Skipping document 179/999 with OID {E31742A4-B6B9-4FCB-BDD6-D93A82640520} because it's missing its XML file!! (stt exists: False)
Skipping document 180/999 with OID {35B8B308-B3CD-42FB-A396-66AF2D0F9CBC} because it's missing its XML file!! (stt exists: True)
Skipping document 181/999 with OID {E76D4FB9-8AF6-4B0C-9B1B-5D98EF282493} because it's missing its XML file!! (stt exists: False)
Skipping document 183/999 with OID {D486B4CD-7B44-486C-AC13-0DA101FCC2DB} because it's missing its XML file!! (stt exists: True)
Skipping document 184/999 with OID {E64D0BFB-9B80-4CC6-BD54-DA543C135E35} because it's missing its XML file!! (stt exists: True)
Skipping document 185/999 with OID {165A7AE9-956A-442A-8763-3B2405E0C952} because it's missing its XML file!! (stt exists: True)
Skipping document 186/999 with OID {247FC895-0CA1-4D65-A17F-53C55037B1BB} because it's missing its XML file!! (stt exists: False)
Skipping document 187/999 with OID {DA34FE04-8C3F-4AE8-B1C4-C1F69EB6192A} because it's missing its XML file!! (stt exists: True)
Skipping document 188/999 with OID {E0A034C9-3472-445E-8F3F-B1E7FD73118E} because it's missing its XML file!! (stt exists: True)
Skipping document 190/999 with OID {15823E76-4222-4E08-A45C-703CB44FF07F} because it's missing its XML file!! (stt exists: True)
Skipping document 191/999 with OID {5D237CD0-A3DB-4DE8-8927-48B784240E1C} because it's missing its XML file!! (stt exists: True)
Skipping document 196/999 with OID {0323C9BC-5951-489D-8BB5-FBA7576DE9C5} because it's missing its XML file!! (stt exists: True)
Skipping document 201/999 with OID {FB728007-D061-4E99-B52C-601E4FC2ACA2} because it's missing its XML file!! (stt exists: False)
Skipping document 202/999 with OID {9707F160-8263-418B-B592-5DCEC120AAE0} because it's missing its XML file!! (stt exists: True)
Skipping document 204/999 with OID {27D83783-B9E9-4082-8AD6-FC8D681D590D} because it's missing its XML file!! (stt exists: False)
Skipping document 209/999 with OID {477C6024-A692-48DC-9EEA-F811FBC4EEC7} because it's missing its XML file!! (stt exists: False)
Skipping document 215/999 with OID {2043FDBC-DD3F-418E-B861-A5CD798214C8} because it's missing its XML file!! (stt exists: True)
Skipping document 218/999 with OID {A9E0B3C4-CEC2-4C2C-8524-7DB3631E56F3} because it's missing its XML file!! (stt exists: True)
Skipping document 219/999 with OID {391EEA35-D3F7-45BA-848B-03A11AB835C9} because it's missing its XML file!! (stt exists: False)
Skipping document 220/999 with OID {6364CA72-F83F-478E-9A9C-D5EE1148F18F} because it's missing its XML file!! (stt exists: False)
Skipping document 221/999 with OID {1FFD83F3-826B-43E7-8B52-DEA438CF609D} because it's missing its XML file!! (stt exists: False)
Skipping document 223/999 with OID {CC5329C0-3B6A-446E-B590-0F3AC215596F} because it's missing its XML file!! (stt exists: False)
Skipping document 227/999 with OID {5957053A-0B4A-4674-84F0-CB616D198300} because it's missing its XML file!! (stt exists: True)
Skipping document 228/999 with OID {7E1EEA02-FAC2-455E-AC02-FA9E60B57DF4} because it's missing its XML file!! (stt exists: True)
Skipping document 229/999 with OID {41796A0A-0093-4D80-9395-6618FF3878AC} because it's missing its XML file!! (stt exists: True)
Skipping document 230/999 with OID {E71245B5-2065-4B08-8EEB-820A904B1486} because it's missing its XML file!! (stt exists: True)
Skipping document 231/999 with OID {99A54EF2-E87E-4B71-9408-E1516C1FB7B4} because it's missing its XML file!! (stt exists: True)
Skipping document 232/999 with OID {B59EE5B1-7D27-4296-9994-FD260761FFD9} because it's missing its XML file!! (stt exists: True)
Skipping document 233/999 with OID {7FFE990D-9DB6-42F5-BB76-804F220B9C0D} because it's missing its XML file!! (stt exists: True)
Skipping document 234/999 with OID {5B17233C-7D40-4D7B-B3A4-3CC18560EC88} because it's missing its XML file!! (stt exists: True)
Skipping document 238/999 with OID {C58FB8B8-5242-4664-82B7-A2C88AE783E8} because it's missing its XML file!! (stt exists: True)
Skipping document 245/999 with OID {27BFA632-9959-4C6D-9413-E29D57482BFE} because it's missing its XML file!! (stt exists: False)
Skipping document 246/999 with OID {773643C0-F617-4E33-B052-3A65261B336C} because it's missing its XML file!! (stt exists: False)
Skipping document 249/999 with OID {11F80F12-89C5-4FD8-A587-8F21345B2C19} because it's missing its XML file!! (stt exists: False)
Skipping document 250/999 with OID {B9401CC5-44D3-4DF2-A9CA-1CA3BA0EEF7B} because it's missing its XML file!! (stt exists: False)
Skipping document 251/999 with OID {1C847B49-967A-46B3-B6FA-94313B14FE7F} because it's missing its XML file!! (stt exists: True)
Skipping document 252/999 with OID {2C318D78-28E4-49B0-A2D6-5898F527B3B2} because it's missing its XML file!! (stt exists: True)
Skipping document 253/999 with OID {F8F61220-BD8B-42D2-9A27-015A288AAB19} because it's missing its XML file!! (stt exists: False)
Skipping document 254/999 with OID {87542469-0441-4B13-83FB-EC438094F8EC} because it's missing its XML file!! (stt exists: True)
Skipping document 255/999 with OID {CCE255DC-3ED2-4A66-B814-32570312F3EE} because it's missing its XML file!! (stt exists: True)
Skipping document 256/999 with OID {FD820162-3940-4DC6-93BE-7A09FD2DAA9F} because it's missing its XML file!! (stt exists: False)
Skipping document 258/999 with OID {0AAA3BFD-1C00-4224-91AA-636C065F0327} because it's missing its XML file!! (stt exists: False)

Skipping document 902/999 with OID {4FD146D6-0100-48CA-BB9A-80C4BA08DD3F} because it's missing its XML file!! (stt exists: False)
Skipping document 903/999 with OID {99682EB6-E4B8-4154-BD64-A6394BD2BE35} because it's missing its XML file!! (stt exists: False)
Skipping document 906/999 with OID {81D7D191-4789-4682-A851-3C619C4A0EE1} because it's missing its XML file!! (stt exists: False)
Skipping document 920/999 with OID {FBBE3C74-78B4-493E-95BC-F098F5C20D83} because it's missing its XML file!! (stt exists: True)
Skipping document 924/999 with OID {9A866C74-4544-4543-BE22-89A1FCB37AFA} because it's missing its XML file!! (stt exists: False)
Skipping document 928/999 with OID {13CA4A81-F13D-4F5C-A8E6-3E37590F3292} because it's missing its XML file!! (stt exists: False)
Skipping document 932/999 with OID {6F134BBF-67A2-419D-A039-4754C01CB6A3} because it's missing its XML file!! (stt exists: False)
Skipping document 933/999 with OID {3F0EAC87-44B8-4845-8A83-A1D5A85B9AF3} because it's missing its XML file!! (stt exists: False)
Skipping document 937/999 with OID {11481C68-FCD7-4912-BD49-3969D54C1EE4} because it's missing its XML file!! (stt exists: False)
Skipping document 947/999 with OID {8D5CC73E-02C3-4990-90BD-B632D7595547} because it's missing its XML file!! (stt exists: True)
Skipping document 950/999 with OID {9890D781-98CF-4254-8508-2ECD1D3B5BDD} because it's missing its XML file!! (stt exists: False)
Skipping document 956/999 with OID {6E839575-4C70-44E0-B4F1-B51EC313684B} because it's missing its XML file!! (stt exists: False)
Skipping document 958/999 with OID {E57B3E6F-1CFE-4D34-9118-0EFDBBDCF6E9} because it's missing its XML file!! (stt exists: False)
Skipping document 959/999 with OID {E8C6AE96-0E40-43F7-8474-B3A55E37FF25} because it's missing its XML file!! (stt exists: False)
Skipping document 968/999 with OID {7A98BE50-783B-4566-854D-617AFEAFFA4B} because it's missing its XML file!! (stt exists: False)
Skipping document 969/999 with OID {BD967759-1C45-4DB2-9E3E-F1ABA6A07603} because it's missing its XML file!! (stt exists: False)
Skipping document 970/999 with OID {85DD6EA0-4B6A-4D74-812F-BF4D1005670A} because it's missing its XML file!! (stt exists: False)
Skipping document 971/999 with OID {8EDC873C-130B-4FE7-A9E2-6FC713F308FF} because it's missing its XML file!! (stt exists: False)
Skipping document 972/999 with OID {1960A3EF-9D5A-4C4A-BC96-179D33220D1F} because it's missing its XML file!! (stt exists: False)
Skipping document 979/999 with OID {6070BBAB-EEDA-4681-BB4B-8CC0B08B6EEA} because it's missing its XML file!! (stt exists: False)
Skipping document 984/999 with OID {454841B3-5F50-4ED1-95AE-B9224ECDA631} because it's missing its XML file!! (stt exists: False)
Skipping document 985/999 with OID {6E0F29F9-C1E5-48E7-8089-02C2570803E6} because it's missing its XML file!! (stt exists: False)
Skipping document 986/999 with OID {24E0BEA0-E0BB-436E-A666-DED339F597D2} because it's missing its XML file!! (stt exists: False)
Skipping document 988/999 with OID {C6F48C01-AFB6-4EF7-AA2C-D3BF81DFB0C2} because it's missing its XML file!! (stt exists: False)
Skipping document 994/999 with OID {05A415C7-E9C4-4987-8CFF-A12A6D48CB97} because it's missing its XML file!! (stt exists: False)
j_mat - returning 605 documents, 394 were skipped due to missing necessary info.

Starting extracting 999 documents for program j_mat
Skipping document 1/999 with OID {00FA1C07-3215-4E3C-8F5F-D3A152EA8EC0} because it's missing its XML file!! (stt exists: False)
Skipping document 3/999 with OID {A7BEF0BF-8E3C-4211-AD53-F92885EACD09} because it's missing its XML file!! (stt exists: True)
Skipping document 4/999 with OID {F638EB80-E3B9-4122-94AE-1CF62C5D1E9E} because it's missing its XML file!! (stt exists: False)
Skipping document 5/999 with OID {A8A4F07B-299F-4E8D-BF2A-324A036FDD41} because it's missing its XML file!! (stt exists: False)
Skipping document 10/999 with OID {180375F5-78C4-4B8C-8B85-A602762EE55A} because it's missing its XML file!! (stt exists: False)
Skipping document 13/999 with OID {E1AAD020-79EE-4939-9B80-42CD2837F5B7} because it's missing its XML file!! (stt exists: False)
Skipping document 18/999 with OID {1B5C3445-BB55-44DF-B97D-D2A35B585EB0} because it's missing its XML file!! (stt exists: True)
Skipping document 19/999 with OID {55419F25-1DD3-4F2D-A747-9453485C9081} because it's missing its XML file!! (stt exists: False)
Skipping document 20/999 with OID {EC5EAC69-0FB2-44B2-B6C9-0B46A4AC6627} because it's missing its XML file!! (stt exists: False)
Skipping document 21/999 with OID {6DC7D37C-77BF-4CD5-9077-448A2AE1CF87} because it's missing its XML file!! (stt exists: False)
Skipping document 26/999 with OID {65A2E50B-894D-4997-9D75-B51E39D10D29} because it's missing its XML file!! (stt exists: True)
Skipping document 28/999 with OID {BFBEFBBB-2F83-4549-BDFD-9B41FE9DD7C8} because it's missing its XML file!! (stt exists: False)
Skipping document 29/999 with OID {9CA139AB-432C-46C6-948C-B32511F3405D} because it's missing its XML file!! (stt exists: False)
Skipping document 32/999 with OID {353C8F50-3A82-4725-ACD7-BC41BE834D2F} because it's missing its XML file!! (stt exists: False)
Skipping document 33/999 with OID {EB01C845-81BF-4DA1-96F2-C7D64BFEF2BE} because it's missing its XML file!! (stt exists: True)
Skipping document 35/999 with OID {6319EC7F-F78A-47EE-9FB5-A90AFD75DB8B} because it's missing its XML file!! (stt exists: True)
Skipping document 38/999 with OID {C3896214-2C63-4BEE-8F61-42472679EBFE} because it's missing its XML file!! (stt exists: False)
Skipping document 42/999 with OID {00B21D24-20DF-4C2E-9483-369D83E21170} because it's missing its XML file!! (stt exists: True)
Skipping document 43/999 with OID {4539A70D-8A9F-4737-BF4F-97ADE843DE12} because it's missing its XML file!! (stt exists: False)
Skipping document 45/999 with OID {30999727-BC22-4140-A307-351D8D02B636} because it's missing its XML file!! (stt exists: False)
Skipping document 46/999 with OID {4328FD21-4801-4597-A48A-70B74593B9DD} because it's missing its XML file!! (stt exists: False)
Skipping document 49/999 with OID {0F950153-C93E-43D4-B2F4-C67520DBCE93} because it's missing its XML file!! (stt exists: False)
Skipping document 50/999 with OID {3F7C40B1-5F1F-4949-B5E2-5EA36DA0EEC4} because it's missing its XML file!! (stt exists: False)
Skipping document 51/999 with OID {456B5BCB-C337-42D1-9454-FD95523B6311} because it's missing its XML file!! (stt exists: False)
Skipping document 52/999 with OID {48AB79B0-E992-4419-A423-FB94C2F54E54} because it's missing its XML file!! (stt exists: False)
Skipping document 57/999 with OID {96CFD766-8F88-4779-B490-B28F20A9F37D} because it's missing its XML file!! (stt exists: False)
Skipping document 63/999 with OID {701FC0FE-1ED9-4831-8185-4DA40DEA7044} because it's missing its XML file!! (stt exists: False)
Skipping document 65/999 with OID {16D03642-C17D-4964-A4FB-0C5126472A1D} because it's missing its XML file!! (stt exists: False)
Skipping document 69/999 with OID {8FC72F6E-A49A-4FBA-AB2B-219CA7134DD1} because it's missing its XML file!! (stt exists: True)
Skipping document 71/999 with OID {EDA07836-43CB-4CB9-90CC-6EEE48A8B41C} because it's missing its XML file!! (stt exists: False)
Skipping document 72/999 with OID {8B57969C-B0D8-4269-A674-2E8C956DFD46} because it's missing its XML file!! (stt exists: False)
Skipping document 73/999 with OID {0A4A8EDC-9A39-415A-985B-19AAB4F98D7E} because it's missing its XML file!! (stt exists: False)
Skipping document 77/999 with OID {336233BD-F8EF-4AE0-8826-F48DD2FD0B2B} because it's missing its XML file!! (stt exists: False)
Skipping document 79/999 with OID {CC8A91B2-2523-40D6-8595-568BF35BF04C} because it's missing its XML file!! (stt exists: False)
Skipping document 85/999 with OID {4F25DF72-7E76-40E7-8881-9CE9F2837117} because it's missing its XML file!! (stt exists: False)
Skipping document 87/999 with OID {2E9BC8AC-2016-4539-9949-9B59AFE223AE} because it's missing its XML file!! (stt exists: True)
Skipping document 90/999 with OID {6DAF3B09-C7F3-4A3B-8AED-B854A8D5D2E0} because it's missing its XML file!! (stt exists: False)
Skipping document 91/999 with OID {012CD0B2-0B07-45D1-B74A-C47F65E4572B} because it's missing its XML file!! (stt exists: False)
Skipping document 97/999 with OID {31BC5166-B3D9-4CD2-AB00-0CE3B3E28515} because it's missing its XML file!! (stt exists: False)
Skipping document 98/999 with OID {DAED697F-0683-4689-BB9E-F5DBC9F172F9} because it's missing its XML file!! (stt exists: False)
Skipping document 99/999 with OID {3486B3AB-31D9-4B2C-9E25-5FB9B34E84AA} because it's missing its XML file!! (stt exists: False)
Skipping document 103/999 with OID {7DFD2B2B-C8AD-4133-B18F-B9FB6EB1818B} because it's missing its XML file!! (stt exists: False)
Skipping document 107/999 with OID {02C26670-9972-4ABA-A148-C3C08C76B563} because it's missing its XML file!! (stt exists: False)
Skipping document 108/999 with OID {DA72CD8F-51F0-4821-9A5F-2BF404AFB6B5} because it's missing its XML file!! (stt exists: False)
Skipping document 110/999 with OID {F72F5C0D-53ED-49AD-8ED3-084BD8F43C3E} because it's missing its XML file!! (stt exists: True)
Skipping document 111/999 with OID {B23590B1-8348-4CA4-A4AF-190CA2939BB6} because it's missing its XML file!! (stt exists: False)
Skipping document 112/999 with OID {079687C6-6433-43AD-B680-19D6938C1868} because it's missing its XML file!! (stt exists: False)
Skipping document 113/999 with OID {1CC3CA8A-DB68-40AE-8684-ADCBDCFEB191} because it's missing its XML file!! (stt exists: False)
Skipping document 125/999 with OID {B141E496-7C4D-4577-BD2A-0A06957702DB} because it's missing its XML file!! (stt exists: False)
Skipping document 126/999 with OID {CCFDBE5D-BDB7-441B-9589-6E79C5BC6D56} because it's missing its XML file!! (stt exists: False)
Skipping document 127/999 with OID {198BF107-C067-4B8A-A53F-1C9B13EF3C39} because it's missing its XML file!! (stt exists: False)
Skipping document 128/999 with OID {516DBB5F-F49E-4ECA-97D0-7A960DF53146} because it's missing its XML file!! (stt exists: False)
Skipping document 130/999 with OID {808AABC0-5518-4731-8D40-59345B57349D} because it's missing its XML file!! (stt exists: False)
Skipping document 135/999 with OID {771FE856-FB5B-42D2-9C46-9464EAAF78C6} because it's missing its XML file!! (stt exists: False)
Skipping document 136/999 with OID {ED395000-A3F7-45C5-B56A-52F290EE737E} because it's missing its XML file!! (stt exists: False)
Skipping document 138/999 with OID {7A33C869-4388-4075-914D-F214827DABDB} because it's missing its XML file!! (stt exists: True)
Skipping document 139/999 with OID {E83EA0F1-59EF-4D38-B1E1-E123DDA1BD8B} because it's missing its XML file!! (stt exists: False)
Skipping document 144/999 with OID {153D8774-07A4-4638-9393-932722B99B23} because it's missing its XML file!! (stt exists: False)
Skipping document 145/999 with OID {422A8715-5F5E-49F9-AE21-E367AA9D30BA} because it's missing its XML file!! (stt exists: False)
Skipping document 152/999 with OID {0CBC45E6-5B2E-4A60-8449-EF8763CC3C3F} because it's missing its XML file!! (stt exists: False)
Skipping document 153/999 with OID {9E75BD91-4A62-4ECC-BC4E-0402929DC47C} because it's missing its XML file!! (stt exists: False)
Skipping document 159/999 with OID {22325B72-CAFE-4A69-B4D0-0FD4639FE78E} because it's missing its XML file!! (stt exists: False)
Skipping document 162/999 with OID {0D6E13FF-21C4-4FA0-B2E8-B54E01811C62} because it's missing its XML file!! (stt exists: False)
Skipping document 171/999 with OID {0AF341C5-FB95-4B4B-98CF-5E15C8684470} because it's missing its XML file!! (stt exists: False)
Skipping document 172/999 with OID {6D3ABD9B-02E9-47D2-B415-7697AC3027C9} because it's missing its XML file!! (stt exists: False)
Skipping document 174/999 with OID {409B40AC-E96B-46EA-86FA-3A2C7BD14BE7} because it's missing its XML file!! (stt exists: False)
Skipping document 175/999 with OID {441E0FCF-5D84-4286-9389-E12C885ABDC7} because it's missing its XML file!! (stt exists: False)
Skipping document 181/999 with OID {E457483A-B739-4B79-9E4D-2B47E77995EE} because it's missing its XML file!! (stt exists: False)
Skipping document 182/999 with OID {F09E5224-4AF3-4754-B98A-46DC318F4095} because it's missing its XML file!! (stt exists: False)
Skipping document 183/999 with OID {0CD8C5C9-F2A2-4473-9BEF-0B964A551009} because it's missing its XML file!! (stt exists: False)
Skipping document 184/999 with OID {306C416E-7E82-45A1-9CBA-792122E6845C} because it's missing its XML file!! (stt exists: False)
Skipping document 185/999 with OID {C4AD2339-3536-4480-903E-EC1408765A15} because it's missing its XML file!! (stt exists: False)
Skipping document 188/999 with OID {646AFD8B-51E6-465D-9DB1-55AC18EAFD7E} because it's missing its XML file!! (stt exists: False)
Skipping document 190/999 with OID {899AB38A-1148-470D-908C-117EFD3CB3DC} because it's missing its XML file!! (stt exists: False)
Skipping document 198/999 with OID {F1DFEB2B-1100-43C3-A701-371574BBB5E6} because it's missing its XML file!! (stt exists: False)
Skipping document 199/999 with OID {25FF54AA-7887-496D-9057-65223EEF0A2F} because it's missing its XML file!! (stt exists: False)
Skipping document 200/999 with OID {373A20BD-CEDE-4CBC-B822-E414C07CC4E7} because it's missing its XML file!! (stt exists: False)
Skipping document 204/999 with OID {12258648-340C-46D7-95D8-5816A00A2950} because it's missing its XML file!! (stt exists: False)
Skipping document 207/999 with OID {D67EEE05-33F8-493B-A343-FA062F616F1B} because it's missing its XML file!! (stt exists: False)
Skipping document 208/999 with OID {09DD780E-1D98-42D1-93B8-666BFA48712B} because it's missing its XML file!! (stt exists: False)
Skipping document 209/999 with OID {DD925CB1-0BBB-4C23-8CB3-351ACB0D12E6} because it's missing its XML file!! (stt exists: True)
Skipping document 213/999 with OID {47B0F66F-8B42-43EC-8108-44A0AC45B684} because it's missing its XML file!! (stt exists: False)
Skipping document 215/999 with OID {49403224-ABA3-48DC-AF6E-FA258C283D03} because it's missing its XML file!! (stt exists: False)
Skipping document 216/999 with OID {B7832554-7A55-494E-9E03-7CFF57FD4469} because it's missing its XML file!! (stt exists: True)
Skipping document 217/999 with OID {B2E2C984-C44E-41BC-91F7-04C251E4AF94} because it's missing its XML file!! (stt exists: True)
Skipping document 218/999 with OID {373E145E-49A3-45CE-AD54-73C2CD41310B} because it's missing its XML file!! (stt exists: False)
Skipping document 219/999 with OID {6A4D1CB0-1C68-47BC-8E34-E4C916037C65} because it's missing its XML file!! (stt exists: False)
Skipping document 220/999 with OID {681C8666-861C-45FA-90D7-86781EC01AC8} because it's missing its XML file!! (stt exists: False)
Skipping document 227/999 with OID {158CC547-0D4B-49DB-84F0-D70B942B04A1} because it's missing its XML file!! (stt exists: True)
Skipping document 228/999 with OID {A9B6D68B-44FC-414D-94BB-64B5D74359EB} because it's missing its XML file!! (stt exists: True)
Skipping document 229/999 with OID {59BCCB46-4A25-4610-8F5C-AEA97C7135CB} because it's missing its XML file!! (stt exists: False)
Skipping document 230/999 with OID {5687FA88-EF30-4C59-8057-09DE5639D7F9} because it's missing its XML file!! (stt exists: True)
Skipping document 232/999 with OID {2B8AF040-71CB-4157-B15B-8E209366A3FB} because it's missing its XML file!! (stt exists: False)
Skipping document 234/999 with OID {DC7B075F-8992-44A7-983A-3B9CF39895AF} because it's missing its XML file!! (stt exists: False)
Skipping document 236/999 with OID {CCF16BB2-ED3C-48C7-B9F9-CEACFCE159C1} because it's missing its XML file!! (stt exists: False)
Skipping document 240/999 with OID {A5605728-EEE4-4B0B-86E6-70DC116576A2} because it's missing its XML file!! (stt exists: False)
Skipping document 241/999 with OID {D9B528F8-88EB-4C17-BAFF-7730692A25A9} because it's missing its XML file!! (stt exists: False)
Skipping document 243/999 with OID {B055C17B-22AA-4D21-886D-5178EC2CE2FE} because it's missing its XML file!! (stt exists: True)
Did not find any date for doc with OID {875C3A20-3D9D-408B-BC6E-7C1BE9D0C3FC}. Trying to use the recording date. doc_dict: {'alias': 'j_mat', 'date_str': None, 'stt_filename': '875C3A20-3D9D-408B-BC6E-7C1BE9D0C3FC_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{875C3A20-3D9D-408B-BC6E-7C1BE9D0C3FC}', 'stripped_OID': '875C3A20-3D9D-408B-BC6E-7C1BE9D0C3FC', 'login': '', 'broadcast_episode_title': 'Le g?n?ral Czeslaw Kiszczak a ?t? ?lu au poste de premier ministre de la Pologne : Il a annonc? que la priorit? de la nouvelle ?quipe ira ? la situation ?conomique uqi ne cesse de se d?grader', 'sequence': '1', 'broadcast_program_name': 'Journal du matin', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '26.06.2017 15:07:46', 'physical_support_history': "Cote d'origine : 29418 Pl. 19", 'production_type': 'Production propre', 'recording_place': 'Lausanne (Studio)', 'rights_notes': None, 'rights_status': 'A rechercher', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:01:40.616', 'work_duration_compl': 'Non', 'participants': [{'name': 'Aubert, Rapha?l', 'function': 'Pr?sentateur/trice', 'role': 'collaborateur RSR'}, {'name': 'Inconnue', 'function': 'Interview?/e', 'role': 'm?nag?re habitant Varsovie'}], 'geographical_descriptors': ['Pologne'], 'person_descriptors': ['Kiszczak, Czeslaw'], 'thematical_descriptors': ['?conomie', 'inflation'], 'rights_usage_possibilities': ['FM'], 'radio_channels': ['Premier programme'], 'subdomains': ['Interview'], 'recording_dates': ['03/08/1989 - 03/08/1989'], 'first_broadcast_dates': None}
Skipping document 246/999 with OID {0CCE8C3A-535B-4BD5-B15F-3E7E42DFEE2F} because it's missing its XML file!! (stt exists: True)
Skipping document 248/999 with OID {830C12EC-5060-49EF-BDBC-51EF47379E83} because it's missing its XML file!! (stt exists: True)
Skipping document 249/999 with OID {D407ABA6-F93F-45EA-A1A2-B1DA2C351DA1} because it's missing its XML file!! (stt exists: False)
Skipping document 254/999 with OID {18223AF5-677D-45E6-9904-4534EFF4F7CB} because it's missing its XML file!! (stt exists: True)
Skipping document 266/999 with OID {A858882D-0721-4EB6-AAFC-4032E2E0C37D} because it's missing its XML file!! (stt exists: False)
Skipping document 267/999 with OID {2E154BE0-F9FB-4B05-97F0-B629C09468A4} because it's missing its XML file!! (stt exists: False)
Skipping document 269/999 with OID {CB7268CD-67E2-49F6-BB17-36813EA90ADD} because it's missing its XML file!! (stt exists: False)
Skipping document 270/999 with OID {A9DB0CB8-AD84-4BEA-8B49-E427EA62B0DE} because it's missing its XML file!! (stt exists: False)
Skipping document 275/999 with OID {7D12C5E1-6BD1-4B60-8820-EE9F024ED41C} because it's missing its XML file!! (stt exists: True)
Skipping document 276/999 with OID {F9ADA750-3611-459C-B8C8-B521C904EE47} because it's missing its XML file!! (stt exists: True)
Skipping document 278/999 with OID {655D488D-B246-48A2-BD92-69F6060392D4} because it's missing its XML file!! (stt exists: False)
Skipping document 279/999 with OID {A3BD3088-6134-462B-9277-B25435F1C190} because it's missing its XML file!! (stt exists: False)
Skipping document 286/999 with OID {8B314DC5-FC3A-48C6-9BE4-718FF1724651} because it's missing its XML file!! (stt exists: False)
Skipping document 288/999 with OID {BB5C4EFE-DEE5-46EA-AAD8-2188D8E137EB} because it's missing its XML file!! (stt exists: True)
Skipping document 293/999 with OID {B949B681-63DF-453C-8C8F-B2A970195333} because it's missing its XML file!! (stt exists: False)
Skipping document 294/999 with OID {31CE1835-DDBA-4C19-8684-6FA39898C231} because it's missing its XML file!! (stt exists: False)

Skipping document 989/999 with OID {0B9B6C16-A743-488F-9F2D-48A331661F66} because it's missing its XML file!! (stt exists: False)
Skipping document 990/999 with OID {5F5D1320-BE5B-48A3-A6F3-8AD5B832E747} because it's missing its XML file!! (stt exists: False)
Skipping document 992/999 with OID {E646270A-2370-4A25-80B8-219829667222} because it's missing its XML file!! (stt exists: False)
Skipping document 993/999 with OID {B7B8E55A-1F9C-4897-9B2D-40B632759F92} because it's missing its XML file!! (stt exists: False)
Skipping document 994/999 with OID {27234CBE-7304-4552-8C16-A37849720FA0} because it's missing its XML file!! (stt exists: False)
Skipping document 998/999 with OID {34FBB968-3208-47BE-AAD5-1C605100A08A} because it's missing its XML file!! (stt exists: True)
j_mat - returning 650 documents, 349 were skipped due to missing necessary info.

Starting extracting 998 documents for program j_mat
Skipping document 2/998 with OID {F378A6EF-2FAF-4FBD-95D9-B0CC03272469} because it's missing its XML file!! (stt exists: False)
Skipping document 3/998 with OID {67CA3A7E-43AF-48E6-83EC-C7F938A6B1DD} because it's missing its XML file!! (stt exists: False)
Skipping document 6/998 with OID {44252B83-4EED-4E34-9C85-4269D265A363} because it's missing its XML file!! (stt exists: True)
Skipping document 15/998 with OID {DA2A2AC9-30AD-474C-8DBE-23A745F14D6F} because it's missing its XML file!! (stt exists: True)
Skipping document 16/998 with OID {695EA18B-8AD1-4CA3-ACA4-1F32B84E7FB0} because it's missing its XML file!! (stt exists: True)
Skipping document 17/998 with OID {D7AAF4C5-81F6-4365-9F17-2638B1D7C7D8} because it's missing its XML file!! (stt exists: True)
Skipping document 18/998 with OID {43321E68-216F-4E7A-82E2-F2C9418F9B1F} because it's missing its XML file!! (stt exists: False)
Skipping document 19/998 with OID {AFE8E231-AB22-4C07-9BAE-D8DD86E43495} because it's missing its XML file!! (stt exists: False)
Skipping document 20/998 with OID {27ECA23B-7F9B-49C1-ABCD-21625FC90AC0} because it's missing its XML file!! (stt exists: False)
Skipping document 21/998 with OID {C4039BF6-13B7-4CBB-AB2C-48868FDAE99C} because it's missing its XML file!! (stt exists: False)
Skipping document 22/998 with OID {1618B0B7-5907-4731-8979-45754F421356} because it's missing its XML file!! (stt exists: False)
Skipping document 24/998 with OID {13AAB118-D909-42D3-903C-21880E9D9B2B} because it's missing its XML file!! (stt exists: True)
Skipping document 27/998 with OID {49071636-61B6-41C3-83C3-890C4C4458E8} because it's missing its XML file!! (stt exists: False)
Skipping document 28/998 with OID {23245977-D7DC-4A30-93F0-7F0578F2543C} because it's missing its XML file!! (stt exists: False)
Skipping document 30/998 with OID {850DEE65-312F-4334-8FAD-BA68B1AA9710} because it's missing its XML file!! (stt exists: True)
Skipping document 37/998 with OID {01CC7D0E-F532-4A39-93A5-21B67842B046} because it's missing its XML file!! (stt exists: False)
Skipping document 39/998 with OID {FEE8601C-2A4E-4251-9EE2-C520FFB2F4C6} because it's missing its XML file!! (stt exists: False)
Skipping document 42/998 with OID {A00CB93F-A17B-4E87-8D29-F8AE9C2CAE2E} because it's missing its XML file!! (stt exists: True)
Skipping document 44/998 with OID {1998561D-EE7D-4523-BE86-D4CD1C730FCD} because it's missing its XML file!! (stt exists: True)
Skipping document 51/998 with OID {49F70472-89ED-47D6-8BF3-662D96381AFB} because it's missing its XML file!! (stt exists: False)
Skipping document 58/998 with OID {E7960581-B1D3-4755-9B1F-24859CD23A78} because it's missing its XML file!! (stt exists: False)
Skipping document 60/998 with OID {A49ED4BF-F8B8-443B-8118-EF30A734D6BD} because it's missing its XML file!! (stt exists: True)
Skipping document 68/998 with OID {D97E5907-270E-4073-8249-06AE6CE37A56} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {2C915363-21AD-488D-A08C-EBCD46636014}. Trying to use the recording date. doc_dict: {'alias': 'j_mat', 'date_str': None, 'stt_filename': '2C915363-21AD-488D-A08C-EBCD46636014_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{2C915363-21AD-488D-A08C-EBCD46636014}', 'stripped_OID': '2C915363-21AD-488D-A08C-EBCD46636014', 'login': '', 'broadcast_episode_title': 'Bilan du sommet de la Ligue arabe ? Amman', 'sequence': '1', 'broadcast_program_name': 'Journal du matin', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'freudial', 'modified_on': '23.01.2025 10:03:54', 'physical_support_history': "Cote d'origine: 25347.06", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': "Journal du matin 7h00. Sommet extraordinaire de la Ligue arabe en Jordanie. R?conciliation entre l'Irak et la Syrie. Autorisation de la restauration des relations diplomatiques avec l'Egypte, suspendues depuis 8 ans. R?solution quant ? la guerre Iran-Irak. R?solution quant au conflit isra?lo-arabe.", 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:02:19.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Roch, Dominique', 'function': 'Commentateur/trice', 'role': 'envoy?e sp?ciale ? Amman'}, {'name': 'Inconnu', 'function': 'Pr?sentateur/trice', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Pays arabes', 'Egypte', 'Irak'], 'person_descriptors': ['Arafat, Yasser', 'Ligue arabe'], 'thematical_descriptors': ['relations internationales', 'diplomatie'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Commentaire'], 'recording_dates': ['11/11/1987 - 11/11/1987'], 'first_broadcast_dates': None}
Skipping document 74/998 with OID {FA02D436-1CBC-442D-947F-14B6103262A5} because it's missing its XML file!! (stt exists: False)
Skipping document 78/998 with OID {09FDB1BC-BE3B-44D6-A161-026CF573F32E} because it's missing its XML file!! (stt exists: True)
Skipping document 79/998 with OID {6FA4BA68-0A9F-48B2-818A-4BDEF32437EB} because it's missing its XML file!! (stt exists: True)
Skipping document 80/998 with OID {BDE2CC45-AB14-4878-9FEE-749ACFBB365E} because it's missing its XML file!! (stt exists: False)
Skipping document 81/998 with OID {C548C081-73A3-4D8F-A3E5-38D119AE1063} because it's missing its XML file!! (stt exists: False)
Skipping document 84/998 with OID {2E731A95-E2FA-4C08-BB7C-CA6C4D6DEDD7} because it's missing its XML file!! (stt exists: False)
Skipping document 86/998 with OID {5346D22C-5E29-4D0F-B3B7-F04A133BB4B2} because it's missing its XML file!! (stt exists: True)
Skipping document 87/998 with OID {682E98D2-C092-4F29-9E04-EE8369EF90B3} because it's missing its XML file!! (stt exists: True)
Skipping document 88/998 with OID {D86705A2-6DE6-4021-80F6-FFD4A9AF2043} because it's missing its XML file!! (stt exists: False)
Skipping document 89/998 with OID {CBD92077-B643-4AB5-B993-02331057C778} because it's missing its XML file!! (stt exists: False)
Skipping document 91/998 with OID {A39C9446-0204-460E-A35B-88E22950F911} because it's missing its XML file!! (stt exists: False)
Skipping document 94/998 with OID {5D6C4967-24AE-4FD9-B584-C86ACC66AE26} because it's missing its XML file!! (stt exists: False)
Skipping document 95/998 with OID {0A168CEC-577E-417C-B862-B1A5B0656D5A} because it's missing its XML file!! (stt exists: False)
Skipping document 97/998 with OID {8A3BA436-2702-4565-88ED-354C37CEB7F4} because it's missing its XML file!! (stt exists: False)
Skipping document 98/998 with OID {FDDB89A0-5992-49A9-B4DA-8A3CA5A66C20} because it's missing its XML file!! (stt exists: True)
Skipping document 100/998 with OID {A1D740A4-BB93-42AA-98DB-FC3D14B2E13B} because it's missing its XML file!! (stt exists: False)
Skipping document 101/998 with OID {C850E7D4-30DB-4FCB-9F6D-D22BEC018D93} because it's missing its XML file!! (stt exists: False)
Skipping document 103/998 with OID {73456392-891E-4CF2-9321-E17AD15ECEF2} because it's missing its XML file!! (stt exists: False)
Skipping document 104/998 with OID {DCBAB2C2-2DAA-41FC-89D7-451AE7067658} because it's missing its XML file!! (stt exists: False)
Skipping document 107/998 with OID {1F3A8D4F-086C-4F8E-9EB7-4F697BA9D7FE} because it's missing its XML file!! (stt exists: False)
Skipping document 108/998 with OID {EA4EB784-5E2C-4B56-8CBF-DD557516DC18} because it's missing its XML file!! (stt exists: False)
Skipping document 109/998 with OID {EDE9BB58-887C-4EDD-98B3-C2323864C293} because it's missing its XML file!! (stt exists: False)
Skipping document 111/998 with OID {54299803-0E2C-4EA3-A3FE-427CA3461673} because it's missing its XML file!! (stt exists: True)
Skipping document 114/998 with OID {6179AF48-1C28-4F86-8F0B-4B830972C6F0} because it's missing its XML file!! (stt exists: False)
Skipping document 118/998 with OID {944E7EF9-EB52-4A89-8400-ACD28822700F} because it's missing its XML file!! (stt exists: True)
Skipping document 119/998 with OID {9E0FC9CB-5E41-4E0A-9B3F-DC2519CDA63A} because it's missing its XML file!! (stt exists: False)
Skipping document 123/998 with OID {A1E000AB-7BE1-4AFE-B96B-1B41605A6DE2} because it's missing its XML file!! (stt exists: False)
Skipping document 124/998 with OID {BE8CEEB0-637C-4D41-9993-4F1154FF70C2} because it's missing its XML file!! (stt exists: True)
Skipping document 129/998 with OID {1DB5CF48-E0E2-4FE4-AB3C-F789BFD68306} because it's missing its XML file!! (stt exists: False)
Skipping document 130/998 with OID {27AFBD0D-1EA0-4FAD-B808-7BAF90B7D5B9} because it's missing its XML file!! (stt exists: False)
Skipping document 131/998 with OID {EAFA8034-759E-4E29-824E-E30704475E77} because it's missing its XML file!! (stt exists: False)
Skipping document 146/998 with OID {B2D0BFA4-5F3C-402F-995B-C584E90A726C} because it's missing its XML file!! (stt exists: True)
Skipping document 147/998 with OID {987880B2-F300-4654-8E8E-FE9DC808F67A} because it's missing its XML file!! (stt exists: True)
Skipping document 148/998 with OID {D08B321D-3D72-4DF0-A64E-49BB62100BF3} because it's missing its XML file!! (stt exists: True)
Skipping document 149/998 with OID {F108E566-A6D6-4453-96EB-3D84CA5AB07A} because it's missing its XML file!! (stt exists: True)
Skipping document 150/998 with OID {BDA4A858-4EAE-45BF-87EB-D99ACA5C74CC} because it's missing its XML file!! (stt exists: True)
Skipping document 151/998 with OID {66523447-D048-4190-AE9D-12E91E914F23} because it's missing its XML file!! (stt exists: True)
Skipping document 152/998 with OID {A259628B-7551-4C0B-B07E-F214D4306025} because it's missing its XML file!! (stt exists: True)
Skipping document 153/998 with OID {B09857F8-56DB-4859-B5E9-3990FEE72FBE} because it's missing its XML file!! (stt exists: True)
Skipping document 154/998 with OID {E5065D6A-DEAE-4C54-9AD3-C5C9B0A0ADFF} because it's missing its XML file!! (stt exists: True)
Skipping document 155/998 with OID {44738A7C-1A41-4947-A687-B92556B75C7C} because it's missing its XML file!! (stt exists: True)
Skipping document 156/998 with OID {62F749DD-CB3D-42B5-82C2-BA579BF3A6F0} because it's missing its XML file!! (stt exists: True)
Skipping document 157/998 with OID {5B418F49-0B67-4505-84E0-F14AF7F89BDF} because it's missing its XML file!! (stt exists: True)
Skipping document 158/998 with OID {B8CBFF2A-D0D7-4052-A137-76982600FAA4} because it's missing its XML file!! (stt exists: True)
Skipping document 159/998 with OID {AF669CDB-3911-499E-822D-EF544835831D} because it's missing its XML file!! (stt exists: True)
Skipping document 160/998 with OID {6E5DB6DE-9C1C-4D08-B30D-1DCCA11CB210} because it's missing its XML file!! (stt exists: True)
Skipping document 161/998 with OID {CFB288F8-3BBE-4C30-BE71-85B19CED1D44} because it's missing its XML file!! (stt exists: True)
Skipping document 163/998 with OID {3788E319-CE82-4B8B-8609-AB4938E754AF} because it's missing its XML file!! (stt exists: True)
Skipping document 164/998 with OID {1A2F1948-A871-46FE-9313-C267AC0BD181} because it's missing its XML file!! (stt exists: True)
Skipping document 165/998 with OID {9A5BD40A-3321-43A8-BC4C-E8AFFA0A62FC} because it's missing its XML file!! (stt exists: True)
Skipping document 168/998 with OID {611F0EC2-D3B0-40F7-8FD4-870B60978D4C} because it's missing its XML file!! (stt exists: True)
Skipping document 169/998 with OID {E6ADAFBE-7384-4D60-98A4-3A9D49071E74} because it's missing its XML file!! (stt exists: True)
Skipping document 172/998 with OID {9C5053CE-9F0B-4762-9361-E80F7613B36F} because it's missing its XML file!! (stt exists: True)
Skipping document 173/998 with OID {05635067-99A6-480C-BD25-2E60182F6EAD} because it's missing its XML file!! (stt exists: False)
Skipping document 174/998 with OID {89E4C320-8272-405F-853E-316D2F3FF482} because it's missing its XML file!! (stt exists: True)
Skipping document 175/998 with OID {ABEAA76A-1C28-4E05-ADE2-9EF8A174B6CE} because it's missing its XML file!! (stt exists: False)
Skipping document 176/998 with OID {6F97745B-8E7F-4D17-96FF-A39844DAC541} because it's missing its XML file!! (stt exists: True)
Skipping document 177/998 with OID {5705FD42-2C10-40DD-85BD-36BE25DDE278} because it's missing its XML file!! (stt exists: False)
Skipping document 178/998 with OID {C4950CFB-37CE-4B4A-9F5D-1C804B5A6D8B} because it's missing its XML file!! (stt exists: False)
Skipping document 182/998 with OID {16D57A82-78D1-4BDA-8480-FECEFFCC4C02} because it's missing its XML file!! (stt exists: False)
Skipping document 183/998 with OID {1B4B1EB3-9988-40DB-9B15-93049046B546} because it's missing its XML file!! (stt exists: False)
Skipping document 185/998 with OID {5BC9A3E2-0E44-484B-9C27-43C1B4C11C2C} because it's missing its XML file!! (stt exists: True)
Skipping document 186/998 with OID {3FE0A253-C6B9-46E9-ACA0-2E1AEDD13BB5} because it's missing its XML file!! (stt exists: True)
Skipping document 187/998 with OID {DE3C4365-D3AF-4809-B9E5-DEB925FA59F8} because it's missing its XML file!! (stt exists: False)
Skipping document 189/998 with OID {93EF46E5-846A-4D98-900C-6BDCACF4CA0D} because it's missing its XML file!! (stt exists: False)
Skipping document 190/998 with OID {77DD876A-6838-46C3-A956-038B9C550E92} because it's missing its XML file!! (stt exists: False)
Skipping document 191/998 with OID {3CC04C55-64F9-407F-9797-9ADB7754EBE4} because it's missing its XML file!! (stt exists: False)
Skipping document 192/998 with OID {24405F80-2473-448A-BB9B-D9259EFE0617} because it's missing its XML file!! (stt exists: False)
Skipping document 194/998 with OID {F4845346-C3C8-4A9C-AD38-514F75DEC309} because it's missing its XML file!! (stt exists: False)
Skipping document 195/998 with OID {228DFB9D-3AFA-43FB-8423-BAA034E4AB2C} because it's missing its XML file!! (stt exists: False)
Skipping document 198/998 with OID {13924E9C-5123-4F59-A2FE-E3DBA62E9E1F} because it's missing its XML file!! (stt exists: False)
Skipping document 203/998 with OID {7F50989A-5C77-48A5-B7BF-15F9E4743E92} because it's missing its XML file!! (stt exists: False)
Skipping document 205/998 with OID {63E8A88A-CCA0-4D9D-A66F-C7ADFAB188C5} because it's missing its XML file!! (stt exists: False)
Skipping document 208/998 with OID {1E01BED5-645D-4728-A355-98F10ED9D84E} because it's missing its XML file!! (stt exists: False)
Skipping document 209/998 with OID {0F126444-EE4D-4E5E-9D76-C9121D7BFC5F} because it's missing its XML file!! (stt exists: False)
Skipping document 210/998 with OID {4043177F-A01E-4A5C-920E-8AC52013A6FA} because it's missing its XML file!! (stt exists: False)
Skipping document 217/998 with OID {E5096FF0-EA06-43BD-8A5B-DC182A64EB9E} because it's missing its XML file!! (stt exists: False)
Skipping document 218/998 with OID {521278D5-0110-4616-BE61-FF344A58D150} because it's missing its XML file!! (stt exists: False)
Skipping document 219/998 with OID {BDEFFD2C-C848-4A65-870E-E9A51BD3FC7F} because it's missing its XML file!! (stt exists: False)
Skipping document 220/998 with OID {5A5895D6-8D5C-47C4-B5DE-B80A060FB2E1} because it's missing its XML file!! (stt exists: False)
Skipping document 221/998 with OID {3DB8C849-80ED-420F-8215-2F04B9AD6345} because it's missing its XML file!! (stt exists: False)
Skipping document 224/998 with OID {A1BEA179-3FB6-4AA5-9D4C-A88EAA71E196} because it's missing its XML file!! (stt exists: False)
Skipping document 241/998 with OID {54B42F29-BB5B-4D67-86A0-19458272F536} because it's missing its XML file!! (stt exists: False)
Skipping document 262/998 with OID {B42E55B0-D384-49DC-9DE0-452CDEC5496D} because it's missing its XML file!! (stt exists: False)
Skipping document 273/998 with OID {AE335F1A-E7FE-4E5D-91AD-A832E968C3A8} because it's missing its XML file!! (stt exists: False)
Skipping document 274/998 with OID {67C9A42A-9165-4DBD-89F4-5CDECA362C79} because it's missing its XML file!! (stt exists: False)
Skipping document 275/998 with OID {CCCFF442-0EE7-4E46-B515-338E421D8293} because it's missing its XML file!! (stt exists: False)
Skipping document 276/998 with OID {450B0DF9-914B-4FE7-8162-8B3D59400F48} because it's missing its XML file!! (stt exists: False)
Skipping document 278/998 with OID {66D032E2-B6B9-4C30-A37F-56314F43A21B} because it's missing its XML file!! (stt exists: False)
Skipping document 279/998 with OID {6C0F558B-0225-4765-99C5-DF84C7028F8B} because it's missing its XML file!! (stt exists: False)
Skipping document 282/998 with OID {A9C13294-F921-4581-A8C0-ED09B4C93AA2} because it's missing its XML file!! (stt exists: True)
Skipping document 285/998 with OID {CA7F32C7-02B4-44BC-9408-7A4575E7608A} because it's missing its XML file!! (stt exists: True)
Skipping document 287/998 with OID {B777811C-5ED7-4981-BBFB-002263642166} because it's missing its XML file!! (stt exists: False)
Skipping document 297/998 with OID {ADB30765-0772-40A2-AA57-8C1EFD144C99} because it's missing its XML file!! (stt exists: False)
Skipping document 298/998 with OID {76A13A2D-1188-4522-BD80-E969DEAF8C1F} because it's missing its XML file!! (stt exists: False)
Skipping document 300/998 with OID {3D232C57-9BB2-4C78-A05C-F1A13361F411} because it's missing its XML file!! (stt exists: False)
Skipping document 301/998 with OID {6F14B8BB-4953-4C9A-8117-6AC29909FBF1} because it's missing its XML file!! (stt exists: False)
Skipping document 302/998 with OID {71699344-DC12-47EA-B706-ABCB1503E283} because it's missing its XML file!! (stt exists: False)
Skipping document 303/998 with OID {6A67EA9B-60F5-4C09-94F5-164F2208B213} because it's missing its XML file!! (stt exists: True)
Skipping document 305/998 with OID {F0DDC356-6BF1-476F-9D18-B0A24A1522D9} because it's missing its XML file!! (stt exists: True)
Skipping document 313/998 with OID {E3237D5E-2EC9-43AE-A7A7-F88109A632FF} because it's missing its XML file!! (stt exists: False)
Skipping document 317/998 with OID {FA946C99-D09C-4D13-90DC-FE247A57D198} because it's missing its XML file!! (stt exists: False)
Skipping document 319/998 with OID {FEFDC440-256B-4F81-8B53-9A269D240D36} because it's missing its XML file!! (stt exists: False)
Skipping document 321/998 with OID {A7284523-E364-4DA7-A831-418D7123574D} because it's missing its XML file!! (stt exists: False)
Skipping document 325/998 with OID {75D340CE-D9E9-4C76-966C-CCD1D6282C1B} because it's missing its XML file!! (stt exists: False)
Skipping document 326/998 with OID {69AD8D4A-39EF-4F85-9CA2-4BA3D26C2811} because it's missing its XML file!! (stt exists: False)
Skipping document 327/998 with OID {B014724B-7F92-4040-8EBB-1977BFB6ACF2} because it's missing its XML file!! (stt exists: False)
Skipping document 328/998 with OID {4FB50782-1AEC-4392-8D86-079A97F6D778} because it's missing its XML file!! (stt exists: False)
Skipping document 329/998 with OID {3B0AD406-19FC-40FD-9D59-4E347B91518C} because it's missing its XML file!! (stt exists: False)

Skipping document 987/998 with OID {8586E6C9-B899-4F4C-859E-5327B39AC2EC} because it's missing its XML file!! (stt exists: False)
Skipping document 992/998 with OID {211C0425-D479-45E1-A722-ED1F715F8E54} because it's missing its XML file!! (stt exists: False)
Skipping document 993/998 with OID {4E40C48E-DF75-482B-855A-A41DF3214B9F} because it's missing its XML file!! (stt exists: False)
Skipping document 994/998 with OID {9F981A76-4E2F-49B1-89F4-225533807ED3} because it's missing its XML file!! (stt exists: False)
j_mat - returning 660 documents, 338 were skipped due to missing necessary info.

Starting extracting 998 documents for program j_mat
Skipping document 3/998 with OID {849599D0-AB9B-4B5D-8A47-D28DBA2C2EE6} because it's missing its XML file!! (stt exists: False)
Skipping document 6/998 with OID {F7CD3758-1220-4E94-BA43-08760579076D} because it's missing its XML file!! (stt exists: False)
Skipping document 7/998 with OID {39642BCC-3126-48CB-AB4A-1446004B188C} because it's missing its XML file!! (stt exists: False)
Skipping document 8/998 with OID {79166C64-2784-49BA-9A29-2FA06F5F42B2} because it's missing its XML file!! (stt exists: False)
Skipping document 9/998 with OID {D3E5B794-483A-46F4-9663-8E9053CDB244} because it's missing its XML file!! (stt exists: False)
Skipping document 10/998 with OID {ACDA9540-0014-42C8-BF1F-A113EAC1ACC6} because it's missing its XML file!! (stt exists: False)
Skipping document 11/998 with OID {17DD2F91-4993-4CCF-845C-22FC2F179B0E} because it's missing its XML file!! (stt exists: False)
Skipping document 12/998 with OID {57D4F41F-9898-4059-A9CB-6C738E13F721} because it's missing its XML file!! (stt exists: False)
Skipping document 14/998 with OID {D89ED2A4-7FF6-40B8-978E-A3D0681C5921} because it's missing its XML file!! (stt exists: False)
Skipping document 22/998 with OID {0A0B0FD8-9D5C-414F-BE00-BFE072152CA4} because it's missing its XML file!! (stt exists: True)
Skipping document 28/998 with OID {BFA7E0BC-5282-4F42-B00B-3F274CAD1763} because it's missing its XML file!! (stt exists: False)
Skipping document 29/998 with OID {78761FA7-0288-4707-8FD1-2AADAE579B89} because it's missing its XML file!! (stt exists: False)
Skipping document 32/998 with OID {8852997F-3EB2-47B1-8333-BE22C4B2497C} because it's missing its XML file!! (stt exists: False)
Skipping document 33/998 with OID {D8AD3895-F83D-486F-A614-9362A43F2E05} because it's missing its XML file!! (stt exists: False)
Skipping document 35/998 with OID {C1E9CC75-F672-4E0D-9CC5-CE382EB78945} because it's missing its XML file!! (stt exists: False)
Skipping document 36/998 with OID {02920926-EB50-40EC-A481-C6014226D95F} because it's missing its XML file!! (stt exists: False)
Skipping document 38/998 with OID {6C6F119D-96C4-4C09-8424-E3A1ED391E6B} because it's missing its XML file!! (stt exists: False)
Skipping document 41/998 with OID {5B7B98C9-04EB-4BF5-B905-32393BE7E1AF} because it's missing its XML file!! (stt exists: False)
Skipping document 42/998 with OID {14AF0951-6B09-4505-B2CE-6765D9A5AD4E} because it's missing its XML file!! (stt exists: False)
Skipping document 46/998 with OID {5E91150D-F2F2-4E57-8957-716584DB36A6} because it's missing its XML file!! (stt exists: False)
Skipping document 47/998 with OID {51EFD9BC-C85F-405B-A798-FDEBB253C35D} because it's missing its XML file!! (stt exists: False)
Skipping document 48/998 with OID {DAA08D0A-E89F-4734-9011-4CF8821731CF} because it's missing its XML file!! (stt exists: False)
Skipping document 49/998 with OID {3C2DEED5-234A-4470-B24D-400FA9FD1EE6} because it's missing its XML file!! (stt exists: False)
Skipping document 50/998 with OID {1B75D3D8-0BAD-458F-90CB-D22F60FE4200} because it's missing its XML file!! (stt exists: False)
Skipping document 52/998 with OID {E1FCFDA3-909F-4546-B586-0546117238C0} because it's missing its XML file!! (stt exists: False)
Skipping document 54/998 with OID {0512AFFA-2AC5-4F8A-AAA3-C125475B07DF} because it's missing its XML file!! (stt exists: False)
Skipping document 55/998 with OID {683FBF10-5C88-4391-B858-048037F0742A} because it's missing its XML file!! (stt exists: False)
Skipping document 56/998 with OID {185F8D6E-7BA6-4458-92B8-A739F42D2B95} because it's missing its XML file!! (stt exists: False)
Skipping document 61/998 with OID {143A7B91-CF8E-4042-BCD1-502B83DD7584} because it's missing its XML file!! (stt exists: False)
Skipping document 62/998 with OID {E9875AD5-CE4D-4E10-AA7D-0295DC146EBB} because it's missing its XML file!! (stt exists: False)
Skipping document 63/998 with OID {00828253-16E1-4854-AE22-DF8BB5D06762} because it's missing its XML file!! (stt exists: True)
Skipping document 64/998 with OID {10BF9434-C9D3-4B21-8599-E7E77F81DC29} because it's missing its XML file!! (stt exists: True)
Skipping document 66/998 with OID {E3A1AF53-6C87-4248-95E8-031AE3A9B7E3} because it's missing its XML file!! (stt exists: False)
Skipping document 67/998 with OID {0812D90D-92B7-4E94-B71C-030C59F058F4} because it's missing its XML file!! (stt exists: True)
Skipping document 68/998 with OID {A5A4E088-773C-4F9E-AC38-AE9235C90071} because it's missing its XML file!! (stt exists: False)
Skipping document 70/998 with OID {2F3F0029-22C1-435A-8F6C-C8796A9FD321} because it's missing its XML file!! (stt exists: True)
Skipping document 73/998 with OID {31382C0B-2770-4EF8-AAFD-275FD09EC002} because it's missing its XML file!! (stt exists: False)
Skipping document 74/998 with OID {336AEF1E-08E6-46FC-B6FA-50F8273956B9} because it's missing its XML file!! (stt exists: False)
Skipping document 76/998 with OID {42AC54DE-FA9A-4C41-BCD9-BD2649EA676D} because it's missing its XML file!! (stt exists: False)
Skipping document 77/998 with OID {C0FF05D8-2021-4DAA-B240-2E2D9BBE202E} because it's missing its XML file!! (stt exists: False)
Skipping document 84/998 with OID {C56D137A-9B9E-4896-83A9-F4133DE78B3D} because it's missing its XML file!! (stt exists: False)
Skipping document 85/998 with OID {6EDA1706-07C5-4D2A-8990-B159F485A36C} because it's missing its XML file!! (stt exists: False)
Skipping document 86/998 with OID {A4C9180B-8C7D-46FD-B854-4683A059DC20} because it's missing its XML file!! (stt exists: False)
Skipping document 89/998 with OID {79DCBD3F-0814-43D9-A574-E5D8DE177C92} because it's missing its XML file!! (stt exists: False)
Skipping document 90/998 with OID {930BF2C9-A950-40C6-9A60-90A292478A03} because it's missing its XML file!! (stt exists: True)
Skipping document 92/998 with OID {9C2BFAAC-FC56-4178-AFC5-8F19D435FA67} because it's missing its XML file!! (stt exists: True)
Skipping document 93/998 with OID {A9D771C2-9CB1-4F54-810B-9C7E3130E370} because it's missing its XML file!! (stt exists: False)
Skipping document 98/998 with OID {1C7A8461-E86E-4922-B1BC-3CEA207A7DF8} because it's missing its XML file!! (stt exists: False)
Skipping document 100/998 with OID {940B888D-7CA5-4C36-99BE-FCDFEB09A123} because it's missing its XML file!! (stt exists: True)
Skipping document 101/998 with OID {0E962A02-99FD-44A3-8737-D2AD982FFC41} because it's missing its XML file!! (stt exists: False)
Skipping document 102/998 with OID {D837407C-AD76-4640-ACE1-60C8C169786A} because it's missing its XML file!! (stt exists: False)
Skipping document 103/998 with OID {7BFEB07F-9406-4CB0-8D9D-B265C05E3722} because it's missing its XML file!! (stt exists: False)
Skipping document 106/998 with OID {162F8608-9B4D-4514-A159-9BEBC12552AC} because it's missing its XML file!! (stt exists: False)
Skipping document 107/998 with OID {61F01512-2598-4D15-AD46-7C4E768E7BBC} because it's missing its XML file!! (stt exists: False)
Skipping document 108/998 with OID {4ED5F5FD-A951-4C3E-BB95-2B258F00F76F} because it's missing its XML file!! (stt exists: False)
Skipping document 109/998 with OID {C65AD64B-4FB8-4DFE-87E0-E21FC28EFC75} because it's missing its XML file!! (stt exists: False)
Skipping document 110/998 with OID {29469916-BB9B-4084-9271-B358339E660F} because it's missing its XML file!! (stt exists: False)
Skipping document 111/998 with OID {3B284B07-9FCF-4150-B155-15161D8DD493} because it's missing its XML file!! (stt exists: False)
Skipping document 112/998 with OID {BFF3E5D9-B750-4231-A47B-AAAA0BF59F06} because it's missing its XML file!! (stt exists: False)
Skipping document 114/998 with OID {88153042-12C7-43BF-A910-59AA6640E7A6} because it's missing its XML file!! (stt exists: False)
Skipping document 115/998 with OID {D5F80EB3-2D6E-4B2A-9F1A-8BD46AB77FA1} because it's missing its XML file!! (stt exists: False)
Skipping document 119/998 with OID {67932538-A684-4261-893A-20537C39805A} because it's missing its XML file!! (stt exists: False)
Skipping document 120/998 with OID {F5907CFA-1183-407D-929E-54CC588F3F54} because it's missing its XML file!! (stt exists: False)
Skipping document 121/998 with OID {678FA44E-7A28-48C3-996D-78D5ABEA02F5} because it's missing its XML file!! (stt exists: False)
Skipping document 122/998 with OID {4B579C97-1600-4BE3-BE5F-DBC9C0ABB671} because it's missing its XML file!! (stt exists: False)
Skipping document 124/998 with OID {3B0E8D14-B364-4762-8E53-E424DD2C1BED} because it's missing its XML file!! (stt exists: True)
Skipping document 125/998 with OID {413D6955-599B-45D2-94BD-FF08B187D52A} because it's missing its XML file!! (stt exists: True)
Skipping document 126/998 with OID {6A8C01F1-CC43-4321-82C4-129D6D67685C} because it's missing its XML file!! (stt exists: False)
Skipping document 127/998 with OID {CD04DD11-8A61-46FB-BC53-A36E89266CB4} because it's missing its XML file!! (stt exists: False)
Skipping document 131/998 with OID {BCB00D8B-42C6-4D5D-9D95-36F25BACC5C3} because it's missing its XML file!! (stt exists: False)
Skipping document 134/998 with OID {D4D522CE-D636-428C-8DF2-04E118881C9C} because it's missing its XML file!! (stt exists: False)
Skipping document 135/998 with OID {8C8064F8-F410-489F-87D2-84F789EA72A7} because it's missing its XML file!! (stt exists: False)
Skipping document 136/998 with OID {33DBB26F-7B3A-41D3-9515-22AD266214E3} because it's missing its XML file!! (stt exists: False)
Skipping document 140/998 with OID {E332D8F9-130A-49AE-97FC-43D65E1059CD} because it's missing its XML file!! (stt exists: True)
Skipping document 141/998 with OID {EA46866D-176C-4C05-AFFC-EF14506F2992} because it's missing its XML file!! (stt exists: True)
Skipping document 142/998 with OID {A2918833-7B42-4DF0-BC83-922CCDF9DE05} because it's missing its XML file!! (stt exists: True)
Skipping document 143/998 with OID {89C49291-E3BF-4327-8B46-3E4B13BD2EED} because it's missing its XML file!! (stt exists: True)
Skipping document 145/998 with OID {72AFA5FA-E5A6-42AC-A4DB-C9B5399D090A} because it's missing its XML file!! (stt exists: False)
Skipping document 146/998 with OID {E54AEA0A-5395-43C9-AFA8-22283A83EE07} because it's missing its XML file!! (stt exists: False)
Skipping document 149/998 with OID {CC161234-ED9E-4B25-9639-386553F93F5F} because it's missing its XML file!! (stt exists: False)
Skipping document 152/998 with OID {98528019-734F-4CDF-BC87-9F62AA65FE82} because it's missing its XML file!! (stt exists: False)
Skipping document 154/998 with OID {22BAE901-5B0F-4F8B-A6FC-76C0CB8EBC1F} because it's missing its XML file!! (stt exists: False)
Skipping document 155/998 with OID {7C3E7CC7-1EE1-4D65-96C3-C7DE1A1ACD02} because it's missing its XML file!! (stt exists: False)
Skipping document 156/998 with OID {A6BF20A2-670D-4AA1-B1CE-A9865B427EF7} because it's missing its XML file!! (stt exists: False)
Skipping document 157/998 with OID {9318C623-6CF7-40A5-BB35-F0E27228AC98} because it's missing its XML file!! (stt exists: False)
Skipping document 161/998 with OID {4E34CF3A-FF29-4659-9FAE-03AE209E1BB3} because it's missing its XML file!! (stt exists: False)
Skipping document 162/998 with OID {A671830D-C728-4E15-BB12-AD337B8D7137} because it's missing its XML file!! (stt exists: False)
Skipping document 163/998 with OID {E2FF1E53-41AE-41FC-B607-0FE1D9E51059} because it's missing its XML file!! (stt exists: False)
Skipping document 167/998 with OID {8E485372-F3F2-4123-A9BE-798C493E0048} because it's missing its XML file!! (stt exists: False)
Skipping document 169/998 with OID {EB3A52AF-BAFD-4E98-A7C7-DFCFA85E0399} because it's missing its XML file!! (stt exists: False)
Skipping document 170/998 with OID {ECF57288-E8DE-409C-A451-3689D345A57A} because it's missing its XML file!! (stt exists: False)
Skipping document 172/998 with OID {FCB2195C-751A-4296-840B-CC837307C447} because it's missing its XML file!! (stt exists: False)
Skipping document 173/998 with OID {3B037F66-4162-4ACE-B99C-A72DCA20EE24} because it's missing its XML file!! (stt exists: False)
Skipping document 179/998 with OID {CA4DD2B5-1F22-40E2-BB3B-C549B61792E9} because it's missing its XML file!! (stt exists: False)
Skipping document 182/998 with OID {797639A0-2FE7-44AA-9AAB-FE40CFEF0791} because it's missing its XML file!! (stt exists: False)
Skipping document 185/998 with OID {EDC4C461-ED3B-428C-905A-F5EC803C5EE8} because it's missing its XML file!! (stt exists: False)
Skipping document 186/998 with OID {BB8B90E8-CF87-4A00-8DB6-54C179B698E4} because it's missing its XML file!! (stt exists: False)
Skipping document 187/998 with OID {26A2BFF4-781D-433F-AC24-E21DC9533698} because it's missing its XML file!! (stt exists: False)
Skipping document 188/998 with OID {9B737292-0DB9-4292-A57D-D8BC5BF739D3} because it's missing its XML file!! (stt exists: False)
Skipping document 191/998 with OID {0FD88B75-A052-4F8B-82D3-A740453EE3F3} because it's missing its XML file!! (stt exists: False)
Skipping document 194/998 with OID {9305D707-C40D-460D-899B-9FE95C6905ED} because it's missing its XML file!! (stt exists: False)
Skipping document 197/998 with OID {B633609C-5C0E-4254-9B1B-5C329243130C} because it's missing its XML file!! (stt exists: False)
Skipping document 198/998 with OID {C62BE1FC-7F5C-46B9-8AE5-C09964B8496A} because it's missing its XML file!! (stt exists: False)
Skipping document 202/998 with OID {10924786-A179-4640-B2B2-692E7623B647} because it's missing its XML file!! (stt exists: False)
Skipping document 203/998 with OID {3726D96E-3DEB-4ED2-A8D2-D651A918E801} because it's missing its XML file!! (stt exists: False)
Skipping document 204/998 with OID {2C0F2A98-D002-4486-B87A-DA818E245729} because it's missing its XML file!! (stt exists: False)
Skipping document 206/998 with OID {325A8C24-EC46-4E80-8DAD-411D7FE98C9E} because it's missing its XML file!! (stt exists: False)
Skipping document 208/998 with OID {6F1BFC0C-2897-46A4-886C-D88CA310B2AD} because it's missing its XML file!! (stt exists: False)
Skipping document 212/998 with OID {668CB310-F4FF-401C-B20F-AA04BFEE1F70} because it's missing its XML file!! (stt exists: False)
Skipping document 221/998 with OID {FE8421E2-992D-4CE9-8CCC-BEACF2F0BB3B} because it's missing its XML file!! (stt exists: True)
Skipping document 222/998 with OID {39167E7E-2E7F-47D5-AE74-FAFF4EDF810E} because it's missing its XML file!! (stt exists: True)
Skipping document 223/998 with OID {32BE9F0F-B108-4994-98BD-269681098481} because it's missing its XML file!! (stt exists: True)
Skipping document 231/998 with OID {6C16E8A4-ED3C-43DE-B702-3AE3F7EDA73B} because it's missing its XML file!! (stt exists: False)
Skipping document 232/998 with OID {1F217CED-DFAB-4CE0-A90B-66183B34B636} because it's missing its XML file!! (stt exists: False)
Skipping document 233/998 with OID {FD26D6FE-E965-4939-BD3A-D0216FB66D78} because it's missing its XML file!! (stt exists: False)
Skipping document 234/998 with OID {92A2C476-5091-4997-8977-DE16BD2E4E86} because it's missing its XML file!! (stt exists: True)
Skipping document 235/998 with OID {99C4AF8F-9562-4E4C-9159-2E8EA65945CC} because it's missing its XML file!! (stt exists: False)
Skipping document 238/998 with OID {74D57F91-AC2D-4864-8498-28928C0D8989} because it's missing its XML file!! (stt exists: False)
Skipping document 241/998 with OID {B50E88CC-EACA-413B-9C36-DA8B308FFBA3} because it's missing its XML file!! (stt exists: False)
Skipping document 243/998 with OID {42C6F901-2A94-4686-BDBE-F473034B4CDC} because it's missing its XML file!! (stt exists: False)
Skipping document 244/998 with OID {5CEEE541-E259-471E-9D24-4E3A80253837} because it's missing its XML file!! (stt exists: False)
Skipping document 251/998 with OID {83C30F06-26FC-471D-AEBE-0FAA1438A567} because it's missing its XML file!! (stt exists: False)
Skipping document 252/998 with OID {81F9D503-E051-4AAF-88A7-066CC57D3D8E} because it's missing its XML file!! (stt exists: False)
Skipping document 253/998 with OID {E85FE403-A5D5-4109-8312-E449F091E84F} because it's missing its XML file!! (stt exists: False)
Skipping document 254/998 with OID {0C1FDC8A-7D88-4132-ACE1-8EB109B4B2B7} because it's missing its XML file!! (stt exists: False)
Skipping document 258/998 with OID {ACB9D769-2E53-4C3B-9F16-66E6935311A2} because it's missing its XML file!! (stt exists: False)
Skipping document 263/998 with OID {2DB88E31-2622-4915-ABE0-BA2D5A0BA653} because it's missing its XML file!! (stt exists: False)
Skipping document 264/998 with OID {3521771F-EC02-447F-AC97-CEB6683DF0E4} because it's missing its XML file!! (stt exists: False)
Skipping document 265/998 with OID {A7B67B5A-092E-43D2-9BE8-A5C703D54617} because it's missing its XML file!! (stt exists: False)
Skipping document 266/998 with OID {5D6F2103-D4D6-4BEB-89C4-EB1D6A04DCDD} because it's missing its XML file!! (stt exists: False)
Skipping document 268/998 with OID {75171C69-58A1-4459-91F6-FE270DCB7E32} because it's missing its XML file!! (stt exists: False)
Skipping document 270/998 with OID {630129D7-25D6-47F7-8CF1-7A501BF130F7} because it's missing its XML file!! (stt exists: False)
Skipping document 271/998 with OID {2C6CC1DD-B325-47F3-9150-5A735E724F0E} because it's missing its XML file!! (stt exists: False)
Skipping document 275/998 with OID {D1F68BA4-BD73-4765-A360-B00BE7162D89} because it's missing its XML file!! (stt exists: False)
Skipping document 279/998 with OID {906CA49C-8512-4A77-BF1A-E720FEDC7232} because it's missing its XML file!! (stt exists: False)
Skipping document 282/998 with OID {3D9C869A-C608-4445-AA08-4ECD8409AA6F} because it's missing its XML file!! (stt exists: False)
Skipping document 290/998 with OID {E30AF420-98D7-4D20-B5FB-FE095C346AFC} because it's missing its XML file!! (stt exists: False)
Skipping document 291/998 with OID {D71C49C5-25E5-4195-95ED-36737C592C94} because it's missing its XML file!! (stt exists: False)
Skipping document 295/998 with OID {F57422DF-795C-4555-ACFC-A179A2A1B260} because it's missing its XML file!! (stt exists: False)
Skipping document 299/998 with OID {43125A10-A48B-43F8-8664-1A6C711B3CD3} because it's missing its XML file!! (stt exists: False)
Skipping document 300/998 with OID {11C43641-3EDF-4636-83AE-9015D88D8942} because it's missing its XML file!! (stt exists: False)
Skipping document 301/998 with OID {65CBFA8A-548E-4699-BC65-B29CE093E567} because it's missing its XML file!! (stt exists: False)
Skipping document 305/998 with OID {918283FA-5345-4FDC-B26F-FD93DB689A23} because it's missing its XML file!! (stt exists: False)
Skipping document 307/998 with OID {8EFCE0A7-99EC-4C23-AE98-18960EE869E9} because it's missing its XML file!! (stt exists: True)
Skipping document 308/998 with OID {82311356-B038-48C9-B57C-27D52EC19F92} because it's missing its XML file!! (stt exists: False)
Skipping document 312/998 with OID {7E1490A1-BB32-431A-BAF9-D37F6473B5CA} because it's missing its XML file!! (stt exists: True)
Skipping document 313/998 with OID {D2AB8B58-058F-49FB-99C1-23B004610813} because it's missing its XML file!! (stt exists: True)
Skipping document 316/998 with OID {1CBA1552-E64E-450E-B949-AA4A3CA1006F} because it's missing its XML file!! (stt exists: True)
Skipping document 317/998 with OID {EDE7C730-038D-48A5-822F-3F88172F65D6} because it's missing its XML file!! (stt exists: True)

Skipping document 982/998 with OID {086C7EF5-DBB7-4D11-9E8E-A4699440E574} because it's missing its XML file!! (stt exists: False)
Skipping document 983/998 with OID {1C34AA0B-FCCB-404F-9031-676398E0BAA2} because it's missing its XML file!! (stt exists: False)
Skipping document 985/998 with OID {C4C044FC-FC58-4D2E-AB42-4CE7C444EA73} because it's missing its XML file!! (stt exists: False)
Skipping document 986/998 with OID {9C783E2D-A6D1-4E36-A7A3-03321B7D3D27} because it's missing its XML file!! (stt exists: False)
Skipping document 987/998 with OID {25233384-1BC0-467B-A85F-74364B205F40} because it's missing its XML file!! (stt exists: False)
Skipping document 988/998 with OID {6B3212DE-F8A3-4720-A03D-0091DAFBB179} because it's missing its XML file!! (stt exists: False)
Skipping document 989/998 with OID {AA118050-40C9-4E44-9901-B5178C64ECE1} because it's missing its XML file!! (stt exists: False)
Skipping document 994/998 with OID {F4E8A3A3-04BC-4B6E-8719-28CFA9DED581} because it's missing its XML file!! (stt exists: False)
Skipping document 995/998 with OID {B427A72F-C36A-433E-B3B7-514A989426A2} because it's missing its XML file!! (stt exists: True)
Skipping document 996/998 with OID {E45CDDD5-8090-4CB1-BA29-FDF0E3C540A1} because it's missing its XML file!! (stt exists: False)
Skipping document 997/998 with OID {EDAB6E2E-DDE7-4790-A806-903A1EEBE54D} because it's missing its XML file!! (stt exists: False)
j_mat - returning 616 documents, 382 were skipped due to missing necessary info.

Starting extracting 323 documents for program j_mat
Skipping document 2/323 with OID {64D0E395-4E8F-4B45-BB9A-9A0E62C7BC34} because it's missing its XML file!! (stt exists: False)
Skipping document 4/323 with OID {036F80D1-231B-40CA-927A-39AAAA11850E} because it's missing its XML file!! (stt exists: False)
Skipping document 10/323 with OID {9E2C90D5-E82C-41DE-80F5-542E49B3F3F4} because it's missing its XML file!! (stt exists: False)
Skipping document 11/323 with OID {116AD8D7-F176-4119-835F-7115A8B44438} because it's missing its XML file!! (stt exists: False)
Skipping document 12/323 with OID {7F11EFB2-3147-4F3B-97D5-346A4A5C730C} because it's missing its XML file!! (stt exists: False)
Skipping document 23/323 with OID {B468B7DF-4D64-424C-9B6F-81CFE773C4A9} because it's missing its XML file!! (stt exists: False)
Skipping document 26/323 with OID {25FC8DBB-95FB-4894-B929-51BFFFF379B0} because it's missing its XML file!! (stt exists: False)
Skipping document 27/323 with OID {B82BC272-E613-404A-89B7-6CDB3562D32C} because it's missing its XML file!! (stt exists: False)
Skipping document 32/323 with OID {D1C09AA2-20E7-49F9-8718-88DDBC9B3838} because it's missing its XML file!! (stt exists: True)
Skipping document 33/323 with OID {90E8D7B3-C68C-42EC-A546-6E309BC785C7} because it's missing its XML file!! (stt exists: True)
Skipping document 34/323 with OID {14C483AA-0CED-4B4A-9264-3541A2D90245} because it's missing its XML file!! (stt exists: False)
Skipping document 35/323 with OID {DDF2FD28-CE43-461C-A343-2FE3EC478CD4} because it's missing its XML file!! (stt exists: True)
Skipping document 37/323 with OID {7EBDA77A-C211-4214-8EFB-FB7C3CB7AA93} because it's missing its XML file!! (stt exists: True)
Skipping document 38/323 with OID {EA087E03-E73D-432C-8C61-6A1D70DA3A1D} because it's missing its XML file!! (stt exists: True)
Skipping document 48/323 with OID {00794995-C8A8-438F-BC3B-26906521D09C} because it's missing its XML file!! (stt exists: False)
Skipping document 49/323 with OID {A1163513-A39A-449B-BB35-2127B36AD8CA} because it's missing its XML file!! (stt exists: False)
Skipping document 52/323 with OID {D9A0CA16-0637-4948-9670-85E2D0554756} because it's missing its XML file!! (stt exists: True)
Skipping document 59/323 with OID {91AB41FD-E72D-4D2D-8100-2A533278C226} because it's missing its XML file!! (stt exists: False)
Skipping document 63/323 with OID {0CFE3914-7350-4480-AD34-D04CA96A82FF} because it's missing its XML file!! (stt exists: False)
Skipping document 64/323 with OID {B3F41117-1DED-4920-A353-9010C9E4C1BB} because it's missing its XML file!! (stt exists: False)
Skipping document 65/323 with OID {955B8B1A-B1B2-4EE6-983D-DA39329EF8DE} because it's missing its XML file!! (stt exists: False)
Skipping document 74/323 with OID {550ED9F2-D0B0-493D-AC55-ECF3A023434D} because it's missing its XML file!! (stt exists: False)
Skipping document 75/323 with OID {CFEE817C-FC53-46B5-A59A-1EBDE0B57F5B} because it's missing its XML file!! (stt exists: False)
Skipping document 76/323 with OID {12524AD3-1365-4655-BAF8-513E9E3E1427} because it's missing its XML file!! (stt exists: True)
Skipping document 77/323 with OID {17B765B9-A294-4611-A0BC-DB6CE748F02A} because it's missing its XML file!! (stt exists: True)
Skipping document 80/323 with OID {11D6001E-784D-4854-858C-08FD035E8DA2} because it's missing its XML file!! (stt exists: False)
Skipping document 90/323 with OID {AF4D51F1-D2B9-4731-A66D-7F8F04F45D43} because it's missing its XML file!! (stt exists: False)
Skipping document 91/323 with OID {4083E193-90A9-43D2-AEF3-35BA22E1BBED} because it's missing its XML file!! (stt exists: False)
Skipping document 92/323 with OID {8A65F5E2-E72F-4ECE-9070-A5032422ABBB} because it's missing its XML file!! (stt exists: False)
Skipping document 96/323 with OID {E6D32CF9-F17D-4700-ABE9-3A8B9285C9E4} because it's missing its XML file!! (stt exists: False)
Skipping document 99/323 with OID {1E1D5187-3AEF-4547-BD3E-2C6C00BD2EA9} because it's missing its XML file!! (stt exists: False)
Skipping document 104/323 with OID {73BAA007-BF8D-4644-B6C5-935226660C48} because it's missing its XML file!! (stt exists: False)
Skipping document 107/323 with OID {7B183C3E-38EC-483E-B823-9D5ACEDCE775} because it's missing its XML file!! (stt exists: False)
Skipping document 108/323 with OID {BD9804B7-ADCF-4FE9-9568-9F1F45FE8294} because it's missing its XML file!! (stt exists: False)
Skipping document 117/323 with OID {E06DD5E3-0C82-44D4-8932-AEEB7E116427} because it's missing its XML file!! (stt exists: False)
Skipping document 122/323 with OID {79808DDD-F1C2-4D4D-94AF-BD8271958F88} because it's missing its XML file!! (stt exists: False)
Skipping document 124/323 with OID {682BFF83-314E-41A3-8A9C-83B08D2E58DE} because it's missing its XML file!! (stt exists: True)
Skipping document 127/323 with OID {C328AAB4-E666-4877-8BDC-CFF4F3E2AD89} because it's missing its XML file!! (stt exists: False)
Skipping document 130/323 with OID {78DC2D25-B1A6-4434-A93D-4CEA0E9ED31F} because it's missing its XML file!! (stt exists: True)
Skipping document 131/323 with OID {2A55E0B8-5EFB-436B-A5FE-8808A55ECF73} because it's missing its XML file!! (stt exists: False)
Skipping document 134/323 with OID {80D8FD65-6E61-4CE2-8DA9-2E2F31B81CE5} because it's missing its XML file!! (stt exists: False)
Skipping document 138/323 with OID {DD1DAA77-9A60-49B9-A1B0-E627BEB2393B} because it's missing its XML file!! (stt exists: False)
Skipping document 146/323 with OID {D0E7A09F-4BAC-4E4D-B943-5B03ABF7892D} because it's missing its XML file!! (stt exists: False)
Skipping document 147/323 with OID {83E10BD7-37E5-40AC-8A01-E35771B3D9E9} because it's missing its XML file!! (stt exists: True)
Skipping document 154/323 with OID {72144CA2-44EE-4FFD-B98B-E8F3C7098F60} because it's missing its XML file!! (stt exists: False)
Skipping document 155/323 with OID {3E795D52-75C3-4022-854C-313395A2E74E} because it's missing its XML file!! (stt exists: False)
Skipping document 156/323 with OID {128FAD44-378E-4981-9B8C-3F474461B161} because it's missing its XML file!! (stt exists: False)
Skipping document 165/323 with OID {3D963F79-344E-4FFE-9FDA-E8B478752CDB} because it's missing its XML file!! (stt exists: False)
Skipping document 169/323 with OID {2B288BFC-1E35-4003-9D25-231319316A8D} because it's missing its XML file!! (stt exists: False)
Skipping document 170/323 with OID {7533DD21-3A5E-4A93-BE81-2001203A2901} because it's missing its XML file!! (stt exists: False)
Skipping document 171/323 with OID {2A6EE066-8639-4D1D-B8C4-6250D78BF34A} because it's missing its XML file!! (stt exists: False)
Skipping document 177/323 with OID {64FD8BD7-3FFE-4F85-B8DE-1C3A3CC9D304} because it's missing its XML file!! (stt exists: False)
Skipping document 179/323 with OID {A1724820-EB52-4D47-8CA4-0CC8ECF67995} because it's missing its XML file!! (stt exists: False)
Skipping document 180/323 with OID {BC626E61-E751-4948-8110-1E1F064BD97C} because it's missing its XML file!! (stt exists: True)
Skipping document 181/323 with OID {2FC69507-AA51-41F8-A85D-591C9DBE970D} because it's missing its XML file!! (stt exists: False)
Skipping document 191/323 with OID {09EF3771-DA51-41BB-A4FF-D1469B9EA977} because it's missing its XML file!! (stt exists: False)
Skipping document 192/323 with OID {F70331EC-76E3-40B9-A4CD-436E1A3088EA} because it's missing its XML file!! (stt exists: False)
Skipping document 193/323 with OID {0BB83142-9CA3-4549-BE7C-AB4DCD70F9B3} because it's missing its XML file!! (stt exists: False)
Skipping document 195/323 with OID {42708443-3027-4447-B462-97BE3A7DAD94} because it's missing its XML file!! (stt exists: False)
Skipping document 196/323 with OID {0F830BC9-76C9-4418-8F9B-239DB354FDED} because it's missing its XML file!! (stt exists: False)
Skipping document 197/323 with OID {5D4B0133-B061-4503-9B3F-9B0658FFCCFF} because it's missing its XML file!! (stt exists: False)
Skipping document 198/323 with OID {FC620E35-ED77-472B-B0D7-7B778AD4C2D1} because it's missing its XML file!! (stt exists: False)
Skipping document 199/323 with OID {EB71A07D-60EC-4DF1-93AB-F14774B9FFEB} because it's missing its XML file!! (stt exists: False)
Skipping document 200/323 with OID {680FF7C8-FB11-48A4-BE08-B4015C841031} because it's missing its XML file!! (stt exists: False)
Skipping document 201/323 with OID {61E1419E-549B-4E30-AC48-44D9F46A9055} because it's missing its XML file!! (stt exists: False)
Skipping document 205/323 with OID {D667DA4A-74AE-42D9-8703-B51378E05494} because it's missing its XML file!! (stt exists: False)
Skipping document 212/323 with OID {B89AD723-CF46-41C8-9C7A-C69D637B5C60} because it's missing its XML file!! (stt exists: False)
Skipping document 219/323 with OID {C253FB73-6A57-416D-B0CD-77486A3B4937} because it's missing its XML file!! (stt exists: False)
Skipping document 220/323 with OID {D582B52C-5528-47A9-A428-72072064AA2B} because it's missing its XML file!! (stt exists: True)
Skipping document 224/323 with OID {B06E7BF1-A947-4B6B-8951-2E1156F3DEA5} because it's missing its XML file!! (stt exists: True)
Skipping document 225/323 with OID {C9986EC4-E579-4E12-A015-167F05BCDCAA} because it's missing its XML file!! (stt exists: True)
Skipping document 227/323 with OID {5031EC39-AE3A-42E3-9BB4-E4A6AF7D9E32} because it's missing its XML file!! (stt exists: False)
Skipping document 228/323 with OID {F0DBB912-A7AF-489A-B836-78364490F4FF} because it's missing its XML file!! (stt exists: False)
Skipping document 230/323 with OID {A176FCF8-01C9-4435-9C6E-2735CF05A971} because it's missing its XML file!! (stt exists: False)
Skipping document 231/323 with OID {A0FD9684-CE5A-41D0-B019-C6ADABBDB45D} because it's missing its XML file!! (stt exists: True)
Skipping document 232/323 with OID {B9705F80-51C6-4A4B-9345-7CB697C29E73} because it's missing its XML file!! (stt exists: False)
Skipping document 233/323 with OID {9AA5B045-8143-4926-B2E1-64F995BE9CC6} because it's missing its XML file!! (stt exists: False)
Skipping document 234/323 with OID {8F365E8D-9321-4945-B951-2CEBFC0F4BEB} because it's missing its XML file!! (stt exists: False)
Skipping document 236/323 with OID {AECCBA96-04EF-415E-82A6-F2E554B6E10F} because it's missing its XML file!! (stt exists: True)
Skipping document 237/323 with OID {3CC7D734-7E60-4719-A3F0-91DD41DC2786} because it's missing its XML file!! (stt exists: False)
Skipping document 238/323 with OID {9A038473-AED1-420C-9CBC-D665251E2E71} because it's missing its XML file!! (stt exists: True)
Skipping document 239/323 with OID {E3E4B42C-B59B-4D82-96B3-CA2FC8DD1943} because it's missing its XML file!! (stt exists: False)
Skipping document 240/323 with OID {3FF4E8BD-8236-476A-A917-AB4E08A9FEBD} because it's missing its XML file!! (stt exists: True)
Skipping document 241/323 with OID {5106695F-0C2B-498E-A568-D787BE29DEFD} because it's missing its XML file!! (stt exists: False)
Skipping document 242/323 with OID {83DA63A5-AE86-4D6B-89EA-FE4E39DCBDD9} because it's missing its XML file!! (stt exists: False)
Skipping document 243/323 with OID {EF5B4974-DFC8-4B86-89E3-BEB6B5AB9D59} because it's missing its XML file!! (stt exists: False)
Skipping document 244/323 with OID {0E7CF1F3-7A09-407E-893E-F4992F408D78} because it's missing its XML file!! (stt exists: True)
Skipping document 245/323 with OID {78956E3C-9E21-4889-BF3E-2B39E2661380} because it's missing its XML file!! (stt exists: False)
Skipping document 246/323 with OID {347ADF84-A33F-4152-B4D7-95622444CE78} because it's missing its XML file!! (stt exists: False)
Skipping document 247/323 with OID {DBD7531B-8025-448C-9C75-F269F5717D90} because it's missing its XML file!! (stt exists: False)
Skipping document 248/323 with OID {04AF4742-D8BC-44DC-8B4E-147429FEC02E} because it's missing its XML file!! (stt exists: False)
Skipping document 249/323 with OID {5EAF898E-3605-4FC9-983E-5543E1197BF0} because it's missing its XML file!! (stt exists: False)
Skipping document 260/323 with OID {26C0F3AA-8D72-4F20-AC9F-BDC116372083} because it's missing its XML file!! (stt exists: False)
Skipping document 261/323 with OID {5539A51D-27DC-4F1B-B7D9-359DE3BAFF6A} because it's missing its XML file!! (stt exists: False)
Skipping document 262/323 with OID {F8B3E9D3-49B0-435F-BE36-747E79A7D7FD} because it's missing its audio MP3 file!!
Skipping document 263/323 with OID {FF210ADE-1A7F-4626-866A-1336874BC13C} because it's missing its XML file!! (stt exists: False)
Skipping document 265/323 with OID {BB40CA93-F595-4AC0-9A53-870B1274FB31} because it's missing its XML file!! (stt exists: False)
Skipping document 266/323 with OID {52E0DE99-984D-4DE9-A800-DB9D023D0457} because it's missing its XML file!! (stt exists: False)
Skipping document 276/323 with OID {AA4ECC87-6A62-4E04-A8BF-E8E1A13A78B6} because it's missing its XML file!! (stt exists: False)
Skipping document 277/323 with OID {E2FC2CBE-7B51-4FDF-B43C-D1422D122B08} because it's missing its XML file!! (stt exists: True)
Skipping document 278/323 with OID {4DF92B24-2C48-43C8-8F09-DAB35F8EC78F} because it's missing its XML file!! (stt exists: False)
Skipping document 279/323 with OID {377E1293-3199-40A6-9848-28DB2D995981} because it's missing its XML file!! (stt exists: False)
Skipping document 282/323 with OID {74272070-BDF1-4D65-B38A-242CD341C2F6} because it's missing its XML file!! (stt exists: True)
Skipping document 284/323 with OID {A2E70E09-07D5-4480-A909-5F9881E828BD} because it's missing its XML file!! (stt exists: False)
Skipping document 287/323 with OID {B55875A5-9CF6-4634-AE22-C2F418196964} because it's missing its XML file!! (stt exists: False)
Skipping document 295/323 with OID {17CA213D-2F0C-404B-B2EF-9C5C87CE24F2} because it's missing its XML file!! (stt exists: False)
Skipping document 296/323 with OID {8063550E-F248-4858-8C90-12DB63537870} because it's missing its XML file!! (stt exists: False)
Skipping document 297/323 with OID {443F9154-92B3-43CE-B2E7-8B5A09C4BD49} because it's missing its XML file!! (stt exists: False)
Skipping document 304/323 with OID {7E1EDD2E-7787-4615-ABC3-B562F389FD9A} because it's missing its XML file!! (stt exists: True)
Skipping document 305/323 with OID {C458D3CB-BADA-44C1-836E-87DE0915289F} because it's missing its XML file!! (stt exists: False)
Skipping document 306/323 with OID {EBBE3AA0-C5F6-4E1B-86E8-8EA97ADEA4DE} because it's missing its XML file!! (stt exists: True)
Skipping document 307/323 with OID {4CD28B21-8048-4D82-BA7D-EDA9A02BD599} because it's missing its XML file!! (stt exists: False)

Skipping document 308/323 with OID {E486D578-D5A0-42C6-9214-A0873EA386A5} because it's missing its XML file!! (stt exists: True)
Skipping document 309/323 with OID {A9841B99-1B6A-42FD-B2E0-892009A10145} because it's missing its XML file!! (stt exists: True)
Skipping document 310/323 with OID {B9A1736E-3766-431B-BE68-0E72FBA4DBE3} because it's missing its XML file!! (stt exists: True)
Skipping document 311/323 with OID {67EC1637-0F0A-4C3B-A3E0-43502789C8D5} because it's missing its XML file!! (stt exists: True)
Skipping document 312/323 with OID {E9BEC593-E4AB-443A-A0A5-DAC2E69EC352} because it's missing its XML file!! (stt exists: True)
Skipping document 313/323 with OID {72A9D610-88D1-4370-88D1-60C6B08B3412} because it's missing its XML file!! (stt exists: True)
Skipping document 317/323 with OID {62FC7E3F-3D2D-46BE-B6FA-0DD5273DA49A} because it's missing its XML file!! (stt exists: False)
Skipping document 319/323 with OID {A795C480-4FBC-4ECF-9D17-80C2A7FB934E} because it's missing its XML file!! (stt exists: True)
Skipping document 320/323 with OID {AF865019-1D29-4D39-9583-C34FD4004227} because it's missing its XML file!! (stt exists: False)
Skipping document 321/323 with OID {40E6C7E5-206E-4312-9745-CE97F4A39E6C} because it's missing its XML file!! (stt exists: True)
Skipping document 322/323 with OID {24BA74D9-2C0C-4B2D-B27D-81E3D6BF8E96} because it's missing its XML file!! (stt exists: True)
Skipping document 323/323 with OID {1DA9F005-F131-4BFD-8CBC-5A00551A53A9} because it's missing its XML file!! (stt exists: False)
j_mat - returning 199 documents, 124 were skipped due to missing necessary info.

Starting extracting 0 documents for program j_mat
j_mat - returning 0 documents, 0 were skipped due to missing necessary info.

Starting extracting 999 documents for program j_mat
Skipping document 5/999 with OID {758F6D75-CE59-4FA3-9FF8-207EF487E407} because it's missing its XML file!! (stt exists: False)
Skipping document 6/999 with OID {D9D0B4B7-026A-4F55-9035-8C8F32CC6B40} because it's missing its XML file!! (stt exists: False)
Skipping document 7/999 with OID {AF61227E-B648-4193-A428-8101D1815C8E} because it's missing its XML file!! (stt exists: False)
Skipping document 8/999 with OID {A1DDFC6A-D664-4FA6-B5E7-1478F1C2EB9F} because it's missing its XML file!! (stt exists: True)
Skipping document 11/999 with OID {E257C83F-D33E-4C2C-8591-C3FEBCB56C08} because it's missing its XML file!! (stt exists: False)
Skipping document 12/999 with OID {4C9BDA24-9EB2-455C-B0A3-6A2FD4C5920B} because it's missing its XML file!! (stt exists: False)
Skipping document 13/999 with OID {00A99E89-3308-4259-A0A1-FF25FC3EAB33} because it's missing its XML file!! (stt exists: False)
Skipping document 24/999 with OID {FCC50CC8-6570-4C0D-BCA1-3C49660FAA21} because it's missing its audio MP3 file!!
Skipping document 29/999 with OID {DDC05952-ED02-42AD-9353-2A5254AFF905} because it's missing its XML file!! (stt exists: False)
Skipping document 30/999 with OID {DA26FEAD-AD49-424C-84DB-4512C616331D} because it's missing its XML file!! (stt exists: False)
Skipping document 31/999 with OID {41D324BA-F3C1-4855-A702-982695D207A2} because it's missing its XML file!! (stt exists: False)
Skipping document 32/999 with OID {251017D3-B3EF-4CD7-8981-0DD5049FFA2B} because it's missing its XML file!! (stt exists: False)
Skipping document 35/999 with OID {60C161ED-EE76-48BA-9EA9-F0C89C4D041B} because it's missing its XML file!! (stt exists: False)
Skipping document 36/999 with OID {03741A44-6C37-43BE-A562-69581A857343} because it's missing its XML file!! (stt exists: False)
Skipping document 40/999 with OID {1662B7B9-3016-41A6-B044-A91E72A449CB} because it's missing its XML file!! (stt exists: False)
Skipping document 48/999 with OID {570BBB5C-3D6D-48A6-A9DA-426B4230169D} because it's missing its XML file!! (stt exists: False)
Skipping document 49/999 with OID {C8C8A02E-33D9-4E51-9D96-8B8BA4928DDB} because it's missing its XML file!! (stt exists: False)
Skipping document 50/999 with OID {ADE7B54A-B9EF-4927-A749-1E4A05A3ADAB} because it's missing its XML file!! (stt exists: False)
Skipping document 53/999 with OID {DB3FACEE-6C02-4C24-83F6-BDC9513F4794} because it's missing its XML file!! (stt exists: False)
Skipping document 54/999 with OID {D6C949C9-0BA1-4AFB-B333-42E189DA7D54} because it's missing its XML file!! (stt exists: False)
Skipping document 60/999 with OID {8A9FE69A-BCD4-49D4-8E67-36ABD75C7C08} because it's missing its XML file!! (stt exists: False)
Skipping document 70/999 with OID {D741CB0E-83B0-468E-B7A9-2F0E6C6A1641} because it's missing its XML file!! (stt exists: False)
Skipping document 74/999 with OID {076ACD32-D5A2-4061-B6EF-D18D37DFEAA3} because it's missing its XML file!! (stt exists: False)
Skipping document 77/999 with OID {0AB8C185-772A-463F-BEE9-40C762D19633} because it's missing its XML file!! (stt exists: False)
Skipping document 79/999 with OID {8A582A5C-0E83-46A9-9B91-6284A1597CEC} because it's missing its XML file!! (stt exists: False)
Skipping document 80/999 with OID {FF345138-49A3-45FC-9F06-F08631F9351B} because it's missing its XML file!! (stt exists: False)
Skipping document 82/999 with OID {987BC0B6-CE3C-4BA6-B161-DF99688EE812} because it's missing its XML file!! (stt exists: True)
Skipping document 94/999 with OID {60DC5E67-A19E-44D3-A9C9-5F356E908151} because it's missing its XML file!! (stt exists: False)
Skipping document 95/999 with OID {6DB9898E-BC10-468E-8F6A-1BE37BF226F5} because it's missing its XML file!! (stt exists: False)
Skipping document 96/999 with OID {1BEE0E32-8BD5-42E3-A52C-B0FA26A1F881} because it's missing its XML file!! (stt exists: False)
Skipping document 98/999 with OID {C64D9D03-9487-444F-AC66-1791E2D8049A} because it's missing its XML file!! (stt exists: True)
Skipping document 100/999 with OID {96C2A8DD-3535-4BCD-B2DD-4B5BC7A2AB0E} because it's missing its XML file!! (stt exists: False)
Skipping document 101/999 with OID {2635BB55-2E75-45B8-BF2D-82D8C21604F7} because it's missing its XML file!! (stt exists: False)
Skipping document 102/999 with OID {560CBD48-F827-4375-A7FC-649921484C8A} because it's missing its XML file!! (stt exists: True)
Skipping document 105/999 with OID {F34A002C-48A9-4628-B5F4-F37CEC80E8D1} because it's missing its XML file!! (stt exists: False)
Skipping document 106/999 with OID {22F39B37-F6DD-4443-BD2E-9477AC78EF4A} because it's missing its XML file!! (stt exists: True)
Skipping document 111/999 with OID {F756D786-70F9-40CA-91EB-41BE507EA2F2} because it's missing its XML file!! (stt exists: True)
Skipping document 113/999 with OID {44CED103-63D2-4AF5-A71E-FEEDC32AB1D6} because it's missing its XML file!! (stt exists: False)
Skipping document 114/999 with OID {CBF9B653-0A52-42D7-B4AB-843D8F99A727} because it's missing its XML file!! (stt exists: False)
Skipping document 115/999 with OID {60CAF928-020F-49E3-ADAA-EBF383A80ED9} because it's missing its XML file!! (stt exists: False)
Skipping document 129/999 with OID {0028B494-2B08-46BD-8CE7-04E405C001B2} because it's missing its XML file!! (stt exists: False)
Skipping document 131/999 with OID {D3E788BC-198A-4392-9445-4DC8EAEE10C3} because it's missing its XML file!! (stt exists: False)
Skipping document 135/999 with OID {C230F493-4DDA-46D2-9509-37DBF1FAB626} because it's missing its XML file!! (stt exists: True)
Skipping document 136/999 with OID {DE56584E-6044-4CA3-BBA5-C5B826554063} because it's missing its XML file!! (stt exists: False)
Skipping document 139/999 with OID {411DD62F-FFA0-421E-8A64-43B4F6B523CF} because it's missing its XML file!! (stt exists: False)
Skipping document 141/999 with OID {A31B20FE-3788-42D0-B863-AB08E30BF52A} because it's missing its XML file!! (stt exists: False)
Skipping document 146/999 with OID {46207534-0FF1-4077-A7D9-C5CC05BC82EC} because it's missing its XML file!! (stt exists: False)
Skipping document 147/999 with OID {40510F49-9E9B-4AEC-A792-86959F0093FA} because it's missing its XML file!! (stt exists: False)
Skipping document 148/999 with OID {8396FC02-5DBE-48DF-9769-ADDE7CBBCB84} because it's missing its XML file!! (stt exists: False)
Skipping document 150/999 with OID {9ADA19C1-EB60-44F1-850C-E6398B8F8DF2} because it's missing its XML file!! (stt exists: False)
Skipping document 166/999 with OID {B1BA29BF-0230-4F91-AE84-BC77DCECBAA4} because it's missing its XML file!! (stt exists: False)
Skipping document 167/999 with OID {81FD121D-D636-4CC3-BD24-AB0BBDB3F078} because it's missing its XML file!! (stt exists: False)
Skipping document 169/999 with OID {CE8CEB03-6F73-4598-A22D-FD6CD7486D1C} because it's missing its XML file!! (stt exists: False)
Skipping document 178/999 with OID {77E4C1D7-0284-468D-BEB7-ADF427C2BEA4} because it's missing its XML file!! (stt exists: False)
Skipping document 179/999 with OID {8C1D657A-0411-495E-9986-5216736F9DF5} because it's missing its XML file!! (stt exists: False)
Skipping document 190/999 with OID {E98CE624-C3F3-4F80-BBC2-9C7DF4A24DF5} because it's missing its XML file!! (stt exists: False)
Skipping document 192/999 with OID {EBBD8B4A-0681-4184-BA23-D99FBD5D8E53} because it's missing its XML file!! (stt exists: False)
Skipping document 193/999 with OID {65E29320-FEB9-4E2C-A06B-48E066E82E2F} because it's missing its XML file!! (stt exists: False)
Skipping document 194/999 with OID {CFD812FE-15AC-45C3-8F97-B29C0446A408} because it's missing its XML file!! (stt exists: False)
Skipping document 198/999 with OID {260CDD10-C982-4D97-A41D-3858D776407D} because it's missing its XML file!! (stt exists: False)
Skipping document 199/999 with OID {BAE7A670-F33D-4084-AB87-FA1BA8C7045A} because it's missing its XML file!! (stt exists: False)
Skipping document 200/999 with OID {0568F445-337D-441D-8894-3D331EF3AB7F} because it's missing its XML file!! (stt exists: True)
Skipping document 204/999 with OID {4D89326D-6639-4E60-812D-A4E7739C9041} because it's missing its XML file!! (stt exists: False)
Skipping document 208/999 with OID {9EAC9A18-374D-447E-962B-46D8BF9C9C12} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {60835155-6A49-4131-9031-05B8CC2F8C51}. Trying to use the recording date. doc_dict: {'alias': 'j_mat', 'date_str': None, 'stt_filename': '60835155-6A49-4131-9031-05B8CC2F8C51_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{60835155-6A49-4131-9031-05B8CC2F8C51}', 'stripped_OID': '60835155-6A49-4131-9031-05B8CC2F8C51', 'login': '', 'broadcast_episode_title': "Interview du g?n?ral Aoun, chef du gouvernement int?rimaire au Liban, la veille de l'attaque d'Hafez el-Assad le 13 octobre 1990", 'sequence': '1', 'broadcast_program_name': 'Journal du matin', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '20.04.2020 10:16:30', 'physical_support_history': "Cote d'origine: 19103.05", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'A rechercher', 'series_title': None, 'content_summary': 'Journal de 7 heures.', 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:52.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Aoun, Michel', 'function': 'Interview?/e', 'role': 'g?n?ral libanais, chef du gouvernement int?rimaire'}, {'name': 'Inconnue', 'function': 'Intervieweur/euse', 'role': 'journaliste fran?aise'}], 'geographical_descriptors': ['Liban', 'Syrie'], 'person_descriptors': None, 'thematical_descriptors': ['conflit arm?', 'si?ge (militaire)'], 'rights_usage_possibilities': None, 'radio_channels': None, 'subdomains': ['Interview'], 'recording_dates': ['12/10/1990 - 12/10/1990'], 'first_broadcast_dates': None}
Skipping document 231/999 with OID {FFF94630-89B2-4732-9D90-1AADF2125350} because it's missing its XML file!! (stt exists: False)
Skipping document 232/999 with OID {CB2801E0-A85F-4222-97C0-B4F2014D8B2D} because it's missing its XML file!! (stt exists: False)
Skipping document 239/999 with OID {F9397CAF-7B48-4AE4-9DB6-8724523A3EAD} because it's missing its XML file!! (stt exists: False)
Skipping document 248/999 with OID {C097BB7C-9F1C-49E8-8595-1F2ABA3C13AF} because it's missing its XML file!! (stt exists: False)
Skipping document 249/999 with OID {3B40D595-6D43-48B3-9135-EC38A91EA603} because it's missing its XML file!! (stt exists: False)
Skipping document 253/999 with OID {4DB6AE99-E6D9-41FE-8BDA-D8723503544D} because it's missing its XML file!! (stt exists: False)
Skipping document 254/999 with OID {7519955B-DAB3-45F4-B695-BD15F13F3851} because it's missing its XML file!! (stt exists: False)
Skipping document 257/999 with OID {6E5AE616-EEBE-4634-A4C3-6C85E4F52D39} because it's missing its XML file!! (stt exists: False)
Skipping document 268/999 with OID {219D5392-9AFA-4757-8797-A2C7DB27ACB5} because it's missing its XML file!! (stt exists: False)
Skipping document 269/999 with OID {CF59588A-2C3E-4F35-82E5-FB8D6EA9E7C0} because it's missing its XML file!! (stt exists: False)
Skipping document 270/999 with OID {DB9737DC-E627-4730-B016-D8D46A23BB69} because it's missing its XML file!! (stt exists: False)
Skipping document 271/999 with OID {8390F1B0-FD71-45AD-900B-4FF5E0282C0D} because it's missing its XML file!! (stt exists: False)
Skipping document 272/999 with OID {F5F34CFF-CF2B-417C-943D-237399E10498} because it's missing its XML file!! (stt exists: False)
Skipping document 273/999 with OID {7BBEEFD4-923B-4A05-8635-67EA5DD004D9} because it's missing its XML file!! (stt exists: False)
Skipping document 274/999 with OID {258F91EF-BE07-4D2C-AC1B-DD9514C6FD4D} because it's missing its XML file!! (stt exists: False)
Skipping document 275/999 with OID {3795521D-C5E4-4F98-B6B7-B63257C66FD9} because it's missing its XML file!! (stt exists: False)
Skipping document 276/999 with OID {1BC72191-F410-438E-B61E-7DBD6714677D} because it's missing its XML file!! (stt exists: False)
Skipping document 277/999 with OID {55A4AEF1-8900-495A-93C8-4B2CBF0A5AB3} because it's missing its XML file!! (stt exists: False)
Skipping document 278/999 with OID {7CBC5261-2A4E-46F6-AEA2-CB420072A0B3} because it's missing its XML file!! (stt exists: False)
Skipping document 279/999 with OID {5242BFE6-F182-40D4-A43D-C074858D2E83} because it's missing its XML file!! (stt exists: False)
Skipping document 280/999 with OID {3BFF300C-E975-4BC9-9BF3-370194067408} because it's missing its XML file!! (stt exists: False)
Skipping document 281/999 with OID {891C37C7-AD6C-4B16-AAD0-56C47767B965} because it's missing its XML file!! (stt exists: False)
Skipping document 282/999 with OID {CA54F512-A382-487D-82C1-1DDBB02B1B8F} because it's missing its XML file!! (stt exists: False)
Skipping document 284/999 with OID {69D92ABF-D375-438F-8DE6-244022970F65} because it's missing its XML file!! (stt exists: False)
Skipping document 286/999 with OID {D3A2ED3E-DDEB-475D-89C9-E93AC8B6E140} because it's missing its XML file!! (stt exists: False)
Skipping document 299/999 with OID {88E0814C-246C-45F3-A1C8-D85A05972D31} because it's missing its XML file!! (stt exists: True)
Skipping document 300/999 with OID {60284735-E3BD-4689-835D-9A11D536B1E9} because it's missing its XML file!! (stt exists: True)
Skipping document 302/999 with OID {C97C3078-CC57-4B71-ABDF-6426E3DDFE4D} because it's missing its XML file!! (stt exists: True)
Skipping document 306/999 with OID {62BBF35B-BAC2-4AC4-A59E-77375D5DD523} because it's missing its XML file!! (stt exists: False)
Skipping document 312/999 with OID {8550E7C0-F737-4FE1-B2F0-CCD8A7B61320} because it's missing its XML file!! (stt exists: False)
Skipping document 314/999 with OID {0CBACF2A-A227-488C-8B98-E6C37EECDC01} because it's missing its XML file!! (stt exists: True)
Skipping document 315/999 with OID {7212468A-93C0-4284-BB02-727FB62820F4} because it's missing its XML file!! (stt exists: False)
Skipping document 317/999 with OID {FD12F6BE-325F-4168-AD92-39BCA98BB4A1} because it's missing its XML file!! (stt exists: True)
Skipping document 318/999 with OID {827C858F-958D-4516-8B9B-8767601BA02C} because it's missing its XML file!! (stt exists: False)
Skipping document 320/999 with OID {D69F6337-2B3A-4755-9BDE-C96D1A9D229B} because it's missing its XML file!! (stt exists: False)
Skipping document 321/999 with OID {B766618E-3072-4893-AE78-4A9E0673F442} because it's missing its XML file!! (stt exists: False)
Skipping document 323/999 with OID {5E06099E-F740-44CB-A900-745B80396DAD} because it's missing its XML file!! (stt exists: False)
Skipping document 325/999 with OID {C84E7312-D804-44C0-941F-71F7309D2A40} because it's missing its XML file!! (stt exists: False)
Skipping document 328/999 with OID {BFAFBD9D-1C0E-41F1-B859-DB2AEA39FB7F} because it's missing its XML file!! (stt exists: False)
Skipping document 329/999 with OID {358FDFB0-5349-47DD-98BF-60E1E4AA9D18} because it's missing its XML file!! (stt exists: False)
Skipping document 337/999 with OID {93526D03-0868-47BC-A39C-0B6131EBD13A} because it's missing its XML file!! (stt exists: False)
Skipping document 338/999 with OID {9E1FCE8A-A3CF-47D9-B577-36F0C3C3CBAB} because it's missing its XML file!! (stt exists: False)
Skipping document 341/999 with OID {49115D7C-DC57-4D95-9713-7C4FDED5379E} because it's missing its XML file!! (stt exists: True)
Skipping document 342/999 with OID {06356997-1A57-4CC6-8379-AFC841964739} because it's missing its XML file!! (stt exists: True)
Skipping document 343/999 with OID {E69FC202-5A61-4467-BCDD-FB4EA375B5DD} because it's missing its XML file!! (stt exists: True)
Skipping document 344/999 with OID {25E07673-9AC5-4D46-967F-B07485A49F95} because it's missing its XML file!! (stt exists: True)
Skipping document 346/999 with OID {91782C9A-99C8-4003-B500-531CB630BBCE} because it's missing its XML file!! (stt exists: True)
Skipping document 347/999 with OID {0E33358C-1E8C-4A0D-978F-1549AD61A53B} because it's missing its XML file!! (stt exists: True)
Skipping document 350/999 with OID {B3DDC14F-EC25-4E07-A784-22D66802D154} because it's missing its XML file!! (stt exists: True)
Skipping document 351/999 with OID {9A195F78-51FD-47BE-8C2A-713FD306F29B} because it's missing its XML file!! (stt exists: True)
Skipping document 353/999 with OID {C3EA3690-434C-48D5-A2B5-E20E627EC7CC} because it's missing its XML file!! (stt exists: True)
Skipping document 355/999 with OID {FE60A787-E693-49DD-AAB3-7A279B6D299D} because it's missing its XML file!! (stt exists: False)
Skipping document 367/999 with OID {F648588F-9B51-4EBC-B784-AD7FEAB1E82A} because it's missing its XML file!! (stt exists: True)
Skipping document 368/999 with OID {4752BE4C-84D7-4F49-BF38-C17EFBFB5E35} because it's missing its XML file!! (stt exists: True)
Skipping document 369/999 with OID {15C0F219-A286-4244-A25F-8DBB9880E148} because it's missing its XML file!! (stt exists: True)
Skipping document 370/999 with OID {F2FC6298-D973-4ECF-B1F4-7D93230F92E1} because it's missing its XML file!! (stt exists: True)
Skipping document 371/999 with OID {51E9E411-2DF0-4960-85E7-D5A7AB19FB63} because it's missing its XML file!! (stt exists: True)
Skipping document 372/999 with OID {D8E423D9-D79C-49CC-8EFD-3A4BE7A13DF5} because it's missing its XML file!! (stt exists: True)
Skipping document 373/999 with OID {81149195-B2F0-458F-B28B-715C682F7726} because it's missing its XML file!! (stt exists: True)
Skipping document 374/999 with OID {24AB3CAE-9BDA-47AC-A712-30C0B117DF2E} because it's missing its XML file!! (stt exists: True)
Skipping document 376/999 with OID {4DCB7398-C140-419B-95FA-C47C4FB1C06B} because it's missing its XML file!! (stt exists: False)
Skipping document 378/999 with OID {63B771C9-2FCD-4F2E-A52D-DC50970C9E02} because it's missing its XML file!! (stt exists: False)
Skipping document 379/999 with OID {3FE069F8-06F0-4735-875B-51E87E106153} because it's missing its XML file!! (stt exists: False)

Skipping document 987/999 with OID {D25DB230-8095-42DE-848E-162E75D56E62} because it's missing its XML file!! (stt exists: False)
Skipping document 988/999 with OID {AB171598-DA2C-466F-B4E3-E2BC5B2B562D} because it's missing its XML file!! (stt exists: False)
Skipping document 989/999 with OID {7800BAB2-0000-445D-883C-11C7DBD0A0AD} because it's missing its XML file!! (stt exists: True)
Skipping document 992/999 with OID {ACA4AFB2-E29F-45EE-9BC1-CC60EBE501FA} because it's missing its XML file!! (stt exists: False)
Skipping document 994/999 with OID {43796C3E-09C9-481D-9BCB-AB9B4B79E414} because it's missing its XML file!! (stt exists: False)
Skipping document 995/999 with OID {95FDBF59-D18B-45A9-A6E0-7D02441D8B3A} because it's missing its XML file!! (stt exists: False)
Skipping document 997/999 with OID {0EAEF454-967B-4BB4-A8DC-4C5FF4416645} because it's missing its XML file!! (stt exists: True)
j_mat - returning 652 documents, 347 were skipped due to missing necessary info.

Starting extracting 999 documents for program j_mat
Skipping document 10/999 with OID {ED4AC483-7344-4A8F-B5FF-A5DD7D11BAC4} because it's missing its XML file!! (stt exists: False)
Skipping document 15/999 with OID {325EF019-0028-4568-9278-5BF338D81C51} because it's missing its XML file!! (stt exists: False)
Skipping document 16/999 with OID {CAF27E1A-E100-4B9B-841A-744729E47B25} because it's missing its XML file!! (stt exists: False)
Skipping document 22/999 with OID {14F5591C-0029-49B9-8156-B51418B412A9} because it's missing its XML file!! (stt exists: False)
Skipping document 23/999 with OID {DB8D9DCB-A345-4E6C-BB4A-89FE3BEFE12E} because it's missing its XML file!! (stt exists: False)
Skipping document 24/999 with OID {3CE3E0EF-2F75-47DA-9427-AD6287620B2F} because it's missing its XML file!! (stt exists: False)
Skipping document 28/999 with OID {3CDA0B30-DD2A-4B2C-854F-05D4FEA7FB62} because it's missing its XML file!! (stt exists: False)
Skipping document 30/999 with OID {CB84476F-75EC-4122-A6D9-8AA5FE0BC958} because it's missing its XML file!! (stt exists: False)
Skipping document 31/999 with OID {15D8D5B0-14AC-4B81-B6CE-07995D1B8434} because it's missing its XML file!! (stt exists: True)
Skipping document 32/999 with OID {6E7066E6-8C61-4EDC-978F-D67B4D332397} because it's missing its XML file!! (stt exists: False)
Skipping document 33/999 with OID {8C17742D-7047-4817-B46A-97DD47EE6396} because it's missing its XML file!! (stt exists: False)
Skipping document 34/999 with OID {F74BAC5B-657E-4892-9A73-65460BED8C31} because it's missing its XML file!! (stt exists: False)
Skipping document 36/999 with OID {5F339F2B-A0E4-4EB6-915C-E753B987A383} because it's missing its XML file!! (stt exists: False)
Skipping document 38/999 with OID {CE1E959F-20A4-46CE-BF06-7BD661B91A78} because it's missing its XML file!! (stt exists: False)
Skipping document 41/999 with OID {7F3E9604-60B5-4A54-B14A-2D15C8D4373F} because it's missing its XML file!! (stt exists: False)
Skipping document 43/999 with OID {EE707EC7-AC5E-494C-B0D3-6910A217ABCF} because it's missing its XML file!! (stt exists: False)
Skipping document 44/999 with OID {CA5FB545-D1FD-4955-8C54-0E8C9D823742} because it's missing its XML file!! (stt exists: True)
Skipping document 50/999 with OID {F7D04251-3F61-4F17-B521-EB7D7B887F43} because it's missing its XML file!! (stt exists: False)
Skipping document 51/999 with OID {9786893E-3512-41A6-A308-718063F65DA0} because it's missing its XML file!! (stt exists: True)
Skipping document 57/999 with OID {7651BBA1-01CA-486B-83BA-368A0629BB51} because it's missing its XML file!! (stt exists: False)
Skipping document 59/999 with OID {A98FC2E3-4F66-4D8C-9FB4-FF595CCAA79C} because it's missing its XML file!! (stt exists: False)
Skipping document 65/999 with OID {BE82E459-9E70-4276-A205-4A55C42670A1} because it's missing its XML file!! (stt exists: False)
Skipping document 66/999 with OID {2C8B0E46-7278-4E72-A0A2-2445C02DDE43} because it's missing its XML file!! (stt exists: False)
Skipping document 67/999 with OID {FE5D69C3-2109-4588-80EB-658511720683} because it's missing its XML file!! (stt exists: False)
Skipping document 68/999 with OID {A86CE721-A14A-49BD-B2D9-B2BD1207D56F} because it's missing its XML file!! (stt exists: False)
Skipping document 70/999 with OID {FB814711-5C4F-4F51-B295-F8F096E4FA12} because it's missing its XML file!! (stt exists: False)
Skipping document 85/999 with OID {953AC1DE-D8B4-4706-93E4-A4AED57C94ED} because it's missing its XML file!! (stt exists: False)
Skipping document 89/999 with OID {C201E18A-C13C-411A-AB96-4267D28D9BCF} because it's missing its XML file!! (stt exists: False)
Skipping document 94/999 with OID {4E0D2583-BCAF-4E33-A8FF-4B14BDD49C55} because it's missing its XML file!! (stt exists: False)
Skipping document 98/999 with OID {7495F944-725E-46F5-A5B5-E4AB043ED89D} because it's missing its XML file!! (stt exists: False)
Skipping document 103/999 with OID {105FBD32-0325-4F39-825C-E43EA18552A1} because it's missing its XML file!! (stt exists: False)
Skipping document 109/999 with OID {DCF05063-9684-43CA-A211-E7F0DDAB6681} because it's missing its XML file!! (stt exists: True)
Skipping document 112/999 with OID {D57B8FAC-9EFF-43C9-BDCA-C9F701F6035B} because it's missing its XML file!! (stt exists: True)
Skipping document 115/999 with OID {65D8DE61-7297-4005-9D78-248144960B8A} because it's missing its XML file!! (stt exists: False)
Skipping document 116/999 with OID {443AE871-7CC1-45B1-A3CF-20F2225A0D16} because it's missing its XML file!! (stt exists: False)
Skipping document 121/999 with OID {A3AABF2A-C8A7-45E6-9887-FB812F267ECA} because it's missing its XML file!! (stt exists: False)
Skipping document 127/999 with OID {E4D3F05C-8C42-4377-BD2C-CEBB7B73837E} because it's missing its XML file!! (stt exists: False)
Skipping document 134/999 with OID {D36D666E-CB78-4050-9586-8E6A9E46F106} because it's missing its XML file!! (stt exists: False)
Skipping document 135/999 with OID {948023C9-ED80-47D3-B0F1-839597D706F7} because it's missing its XML file!! (stt exists: False)
Skipping document 136/999 with OID {F13D0A03-9C80-4C12-8540-8804751B604A} because it's missing its XML file!! (stt exists: False)
Skipping document 139/999 with OID {09F306E4-FB3C-45FA-BACB-9A46D0F847B8} because it's missing its XML file!! (stt exists: False)
Skipping document 140/999 with OID {A5F8A965-70C5-41AF-A51A-BC9A7BE64525} because it's missing its XML file!! (stt exists: True)
Skipping document 141/999 with OID {AB1C6987-79F9-4952-A9EA-A6DE0A6BF1CD} because it's missing its XML file!! (stt exists: False)
Skipping document 142/999 with OID {9937C1D9-D8DE-4194-B2D6-E13BBC3BC86F} because it's missing its XML file!! (stt exists: False)
Skipping document 143/999 with OID {8CB3D58E-0F83-439B-9513-82E08B049CB8} because it's missing its XML file!! (stt exists: False)
Skipping document 149/999 with OID {AB79CC25-6F42-4E43-837A-CA0FB346D9A1} because it's missing its XML file!! (stt exists: False)
Skipping document 158/999 with OID {2072C134-7FA1-4398-915B-BC0E4E9E9FF7} because it's missing its XML file!! (stt exists: False)
Skipping document 161/999 with OID {2EB344E0-232B-4E00-8EB0-435FFEED6C6E} because it's missing its XML file!! (stt exists: False)
Skipping document 163/999 with OID {BFDC55E9-56BD-4F7A-A778-B7118C28034D} because it's missing its XML file!! (stt exists: False)
Skipping document 164/999 with OID {E7A73985-1623-4083-9905-07FA5381D230} because it's missing its XML file!! (stt exists: False)
Skipping document 165/999 with OID {E5FB2EB0-ED65-4972-84EF-CBB6769B9040} because it's missing its XML file!! (stt exists: False)
Skipping document 169/999 with OID {1F890CB8-9CB5-4CCD-BBC7-ADE3D5D373D1} because it's missing its XML file!! (stt exists: False)
Skipping document 170/999 with OID {55056BFD-E451-440B-897F-89F073C06A07} because it's missing its XML file!! (stt exists: False)
Skipping document 171/999 with OID {F0B0AAA3-9A73-4792-9CEF-413CC7578CE3} because it's missing its XML file!! (stt exists: False)
Skipping document 172/999 with OID {8AD64987-9EB0-4C2C-8EC8-EB680A13571B} because it's missing its XML file!! (stt exists: False)
Skipping document 173/999 with OID {5F3D9D82-A429-4179-A1EE-5614AF5F113B} because it's missing its XML file!! (stt exists: False)
Skipping document 181/999 with OID {A25222B3-4160-43A3-9131-9009C8FBA2CA} because it's missing its XML file!! (stt exists: True)
Skipping document 182/999 with OID {6404A691-CED7-472A-B0D4-35C23969DC9C} because it's missing its XML file!! (stt exists: False)
Skipping document 184/999 with OID {02EAD62F-9D8D-48B0-8898-00516C55D4F6} because it's missing its XML file!! (stt exists: False)
Skipping document 185/999 with OID {7793A6E3-1B0A-456C-9AAF-4B7DA8A3EAA8} because it's missing its XML file!! (stt exists: False)
Skipping document 192/999 with OID {94D4AC40-DE25-44E8-BD5C-546D4C57E46C} because it's missing its XML file!! (stt exists: False)
Skipping document 193/999 with OID {272017E1-A91D-490F-9041-5C1069E59E7E} because it's missing its XML file!! (stt exists: False)
Skipping document 194/999 with OID {400CD269-F039-4D87-ABC3-1327F131B3E9} because it's missing its XML file!! (stt exists: False)
Skipping document 195/999 with OID {B65BCE87-82C7-4270-9CBA-1E99E5C3BCC9} because it's missing its XML file!! (stt exists: False)
Skipping document 198/999 with OID {EB9A7E5C-EDD4-4B31-8B39-14E0FCA90D7C} because it's missing its XML file!! (stt exists: False)
Skipping document 202/999 with OID {8D40195D-04CC-4B9F-84E4-4E955464C680} because it's missing its XML file!! (stt exists: True)
Skipping document 203/999 with OID {0DF3A1B1-7695-4D72-90A1-2391C4A00825} because it's missing its XML file!! (stt exists: True)
Skipping document 204/999 with OID {361BA94A-C40E-4E11-9E3A-F0FE9AE3F2CC} because it's missing its XML file!! (stt exists: True)
Skipping document 205/999 with OID {F61BE466-C42A-4927-8EFB-0D8E6BB74B49} because it's missing its XML file!! (stt exists: True)
Skipping document 206/999 with OID {D78E651F-F178-45F1-B5BC-E62FE8E0883D} because it's missing its XML file!! (stt exists: False)
Skipping document 207/999 with OID {9FD2D96B-BF69-40FF-8B11-727E4D8673B1} because it's missing its XML file!! (stt exists: False)
Skipping document 209/999 with OID {2C5D0192-EB64-4DD3-8B2E-682B5C3193FF} because it's missing its XML file!! (stt exists: False)
Skipping document 210/999 with OID {3DABA9EF-A818-46D8-941F-827294538A3C} because it's missing its XML file!! (stt exists: True)
Skipping document 211/999 with OID {8C85D1FE-4CAE-4A09-9AF4-0DA69EB2F369} because it's missing its XML file!! (stt exists: True)
Skipping document 212/999 with OID {D9F6D41F-F9A8-4D94-B106-990F3BE2E606} because it's missing its XML file!! (stt exists: True)
Skipping document 235/999 with OID {08A0E412-C3A9-47BC-B14B-F4EBE208943B} because it's missing its XML file!! (stt exists: False)
Skipping document 236/999 with OID {B12563A7-3E9A-45DE-ABE9-52397E7F6434} because it's missing its XML file!! (stt exists: False)
Skipping document 237/999 with OID {50945AC4-AB10-4F05-9DF4-2BDABE4103A6} because it's missing its XML file!! (stt exists: False)
Skipping document 239/999 with OID {E17AE4FF-6D39-43A9-ADA2-19E6A1A2BD07} because it's missing its XML file!! (stt exists: False)
Skipping document 245/999 with OID {B7F441EB-5B69-4CC5-9CBE-4237F30118E2} because it's missing its XML file!! (stt exists: False)
Skipping document 246/999 with OID {917975D3-9377-42BE-8FFA-27DBC2E15627} because it's missing its XML file!! (stt exists: False)
Skipping document 257/999 with OID {5FE3276D-F4E7-4CC3-88F0-652CDDE0AC4B} because it's missing its XML file!! (stt exists: True)
Skipping document 258/999 with OID {C842493F-8EA2-4A83-A153-70A352A46F1F} because it's missing its XML file!! (stt exists: True)
Skipping document 259/999 with OID {635071CD-D3A9-4580-9AC5-7F9F853DB447} because it's missing its XML file!! (stt exists: True)
Skipping document 260/999 with OID {138792C4-C50B-4D59-88ED-7AF2EC20EB1D} because it's missing its XML file!! (stt exists: True)
Skipping document 261/999 with OID {91798F93-B821-4A37-B088-2582DDD0681E} because it's missing its XML file!! (stt exists: True)
Skipping document 262/999 with OID {3992BFA8-A0F8-41A1-A3FF-334B8A7639F4} because it's missing its XML file!! (stt exists: False)
Skipping document 263/999 with OID {9C517E43-A95E-4B9C-B700-F30B8C62AB78} because it's missing its XML file!! (stt exists: False)
Skipping document 264/999 with OID {E9E725E6-4794-4BF7-9D2E-3298E2FDD1EB} because it's missing its XML file!! (stt exists: True)
Skipping document 265/999 with OID {FAEAA695-94FF-492C-B058-CB2E3E6D2D5E} because it's missing its XML file!! (stt exists: True)
Skipping document 267/999 with OID {27E9CB7C-8955-486C-865A-6B942FAFF950} because it's missing its XML file!! (stt exists: False)
Skipping document 268/999 with OID {B855605E-8747-4EE5-B16F-E5E9FCE70877} because it's missing its XML file!! (stt exists: False)
Skipping document 283/999 with OID {A524BF39-7B10-4B4A-ABB6-2F84F44D3831} because it's missing its XML file!! (stt exists: False)
Skipping document 284/999 with OID {A91055BB-89A2-47D5-BAE8-2DEE19B22AED} because it's missing its XML file!! (stt exists: False)
Skipping document 285/999 with OID {E77809F4-E0DC-4D44-A596-11CAD0B1CCF8} because it's missing its XML file!! (stt exists: False)
Skipping document 293/999 with OID {941041F6-CC9B-4609-ADF7-48EC435B50E2} because it's missing its XML file!! (stt exists: False)
Skipping document 294/999 with OID {7109B48B-25EA-4983-A247-56827EF928C7} because it's missing its XML file!! (stt exists: False)
Skipping document 295/999 with OID {19FAF58C-6D72-4B13-8775-44F504965FAF} because it's missing its XML file!! (stt exists: False)
Skipping document 296/999 with OID {7C696072-6A34-4368-929E-050BEDD8C9E0} because it's missing its XML file!! (stt exists: False)
Skipping document 297/999 with OID {49FDA3BD-1ABD-403A-A28D-A272ED3095D8} because it's missing its XML file!! (stt exists: False)
Skipping document 298/999 with OID {CD43DC65-633C-47E3-B8CE-D8803BFA5631} because it's missing its XML file!! (stt exists: False)
Skipping document 299/999 with OID {55F613FB-2D8F-4D45-ACD8-9899E79613EA} because it's missing its XML file!! (stt exists: False)
Skipping document 300/999 with OID {AAB36BD9-8879-457E-81B9-43E73A817F81} because it's missing its XML file!! (stt exists: False)
Skipping document 301/999 with OID {339CA154-CB2E-4F2A-9FD1-9EDEF186F04E} because it's missing its XML file!! (stt exists: False)
Skipping document 312/999 with OID {F96C4662-277E-4D52-B0EE-6900803F5040} because it's missing its XML file!! (stt exists: False)
Skipping document 313/999 with OID {F9C2BC3E-DE76-4208-9546-3C19737740DC} because it's missing its XML file!! (stt exists: False)
Skipping document 319/999 with OID {4C80C5D0-762F-4D8B-9473-7BCF75DF36F1} because it's missing its XML file!! (stt exists: False)
Skipping document 334/999 with OID {65FF29E5-2D1C-42F8-8E8C-C5D82537FCF9} because it's missing its XML file!! (stt exists: False)
Skipping document 335/999 with OID {8264447A-B8BC-41E6-BB3A-1A20BF465D4F} because it's missing its XML file!! (stt exists: False)
Skipping document 346/999 with OID {10E21549-168D-4C5E-A5D5-E7BC639DFD1D} because it's missing its XML file!! (stt exists: False)
Skipping document 348/999 with OID {1D3C72DF-3890-4B36-8022-4180F21F112E} because it's missing its XML file!! (stt exists: False)
Skipping document 362/999 with OID {52917892-C9B8-4566-9B2F-CB73A657237A} because it's missing its XML file!! (stt exists: False)
Skipping document 365/999 with OID {5EBEED5B-8A0E-4DFA-8F86-245CAB6A3D59} because it's missing its XML file!! (stt exists: False)
Skipping document 374/999 with OID {0475CE2F-A923-4920-80F3-4EFEA1C3E73E} because it's missing its XML file!! (stt exists: False)
Skipping document 375/999 with OID {56014AD1-4833-474E-A3D1-E552D2FE669A} because it's missing its XML file!! (stt exists: False)
Skipping document 380/999 with OID {64B797FD-065D-45A6-B259-840C97C4DCFB} because it's missing its XML file!! (stt exists: False)
Skipping document 397/999 with OID {5424D4EE-AA40-4A59-AEE6-6D2DC6893886} because it's missing its XML file!! (stt exists: False)
Skipping document 398/999 with OID {29F7E5F9-1E4C-4379-9E50-EA1366F4A916} because it's missing its XML file!! (stt exists: False)
Skipping document 401/999 with OID {99A17C61-4A89-4473-8417-08C73BDA969E} because it's missing its XML file!! (stt exists: True)
Skipping document 406/999 with OID {98001117-33C7-420C-A022-C390CAC4C351} because it's missing its XML file!! (stt exists: True)
Skipping document 407/999 with OID {6114DDF4-1614-4E53-9276-0B0BEA2E6DE1} because it's missing its XML file!! (stt exists: True)
Skipping document 408/999 with OID {4F00DBC5-1FD2-4D19-9954-6B21B237EE45} because it's missing its XML file!! (stt exists: True)
Skipping document 414/999 with OID {406A505F-00DC-499E-ADD5-4732CB3655D4} because it's missing its XML file!! (stt exists: True)
Skipping document 415/999 with OID {3D6BF172-67F4-45DD-91CC-F0C31F1D2934} because it's missing its XML file!! (stt exists: True)
Skipping document 416/999 with OID {AE30603D-BE39-4E76-92CF-630B9C7607BA} because it's missing its XML file!! (stt exists: True)
Skipping document 417/999 with OID {1C8CCB17-C84C-43D4-A8CC-90A82F578431} because it's missing its XML file!! (stt exists: False)
Skipping document 418/999 with OID {AAB0E8AB-F0DA-44E3-A685-929FFBA132D5} because it's missing its XML file!! (stt exists: False)
Skipping document 419/999 with OID {7043801B-9A4A-4F3C-8351-54A81C91346B} because it's missing its XML file!! (stt exists: False)
Skipping document 429/999 with OID {D197528F-DB73-4A1B-8065-2ACCE2311A82} because it's missing its XML file!! (stt exists: True)
Skipping document 430/999 with OID {7C4A77B8-AD75-473A-9B0D-D1B6AB24BB62} because it's missing its XML file!! (stt exists: False)
Skipping document 431/999 with OID {3E824F6F-F182-4822-8C2F-275147C78C18} because it's missing its XML file!! (stt exists: False)
Skipping document 437/999 with OID {0447D5F0-7995-4A35-AAA2-A8FE38BD0512} because it's missing its XML file!! (stt exists: False)
Skipping document 438/999 with OID {D9D9A3FE-27C1-4786-9295-15BDA2EB99F1} because it's missing its XML file!! (stt exists: False)
Skipping document 439/999 with OID {FB331BF9-F352-4ADF-9AA9-109FC731EE18} because it's missing its XML file!! (stt exists: False)
Skipping document 440/999 with OID {70481844-6E3D-4A3C-93ED-C9D699001769} because it's missing its XML file!! (stt exists: False)
Skipping document 441/999 with OID {57A5486E-0AB3-4146-B977-8BBA219CA145} because it's missing its XML file!! (stt exists: False)
Skipping document 442/999 with OID {E2A4CAAA-4B51-443E-9EB5-A8671B7D3E55} because it's missing its XML file!! (stt exists: False)
Skipping document 443/999 with OID {4FCFB851-6047-4D7B-BF75-8C4B290ECE0E} because it's missing its XML file!! (stt exists: False)
Skipping document 452/999 with OID {63AF3AD9-83D8-4FF2-A844-F1DC979A2441} because it's missing its XML file!! (stt exists: False)
Skipping document 453/999 with OID {A11B46EC-E3DF-446D-90EE-6F79628F87C8} because it's missing its XML file!! (stt exists: False)
Skipping document 454/999 with OID {B3A3053C-F33F-4C41-8714-DD8E07873AB1} because it's missing its XML file!! (stt exists: True)
Skipping document 455/999 with OID {6A9B6A39-ED75-40F8-B169-5F3E22037163} because it's missing its XML file!! (stt exists: True)
Skipping document 470/999 with OID {C4C381BE-EBAD-449D-BC6C-978D53FACEE2} because it's missing its XML file!! (stt exists: False)
Skipping document 471/999 with OID {1FD739C7-F898-4E6A-B6A3-483BAE8D493A} because it's missing its XML file!! (stt exists: False)
Skipping document 472/999 with OID {898974B3-1A93-477A-83E6-D4AEF2B08E16} because it's missing its XML file!! (stt exists: False)
Skipping document 477/999 with OID {B6E6F05E-32CC-4CC4-B7D5-69ACAE8F7DE7} because it's missing its XML file!! (stt exists: False)

Skipping document 955/999 with OID {960DE70F-C64E-4752-8064-456ACD28756D} because it's missing its XML file!! (stt exists: False)
Skipping document 956/999 with OID {5D1217CF-7A31-491A-9E80-BC305DD09C20} because it's missing its XML file!! (stt exists: False)
Skipping document 957/999 with OID {07CAE8C1-09A4-4121-90C4-7B3181124DE7} because it's missing its XML file!! (stt exists: False)
Skipping document 960/999 with OID {27E4F311-8F5B-40FA-91C9-B818B4FC627B} because it's missing its XML file!! (stt exists: False)
Skipping document 966/999 with OID {9450D488-BA00-4529-B998-603E30BC4978} because it's missing its XML file!! (stt exists: False)
Skipping document 970/999 with OID {649352B4-EB28-41E9-ADF5-F270FF72C846} because it's missing its XML file!! (stt exists: False)
Skipping document 973/999 with OID {442A111E-249B-4D3D-BC04-24490B7D8DEE} because it's missing its XML file!! (stt exists: False)
Skipping document 974/999 with OID {495C526E-0105-485C-ACB0-3A2B613B58A1} because it's missing its XML file!! (stt exists: False)
Skipping document 975/999 with OID {28C09BF8-CDCB-4306-8DB4-DAAF783331C0} because it's missing its XML file!! (stt exists: False)
Skipping document 976/999 with OID {E603DAE5-2BD0-4E68-A073-856D1D9B8780} because it's missing its XML file!! (stt exists: False)
Skipping document 977/999 with OID {D86311A4-B35E-474A-BECC-B31B8E4180A4} because it's missing its XML file!! (stt exists: False)
Skipping document 983/999 with OID {7A7007FF-F9EA-4000-8687-B811667EFB63} because it's missing its XML file!! (stt exists: False)
Skipping document 984/999 with OID {09FC6DAC-299A-4EE1-B9CB-58DFE82CDAAC} because it's missing its XML file!! (stt exists: False)
Skipping document 986/999 with OID {35D6D0AE-13FF-4AA2-8DA8-FEA04D4F8885} because it's missing its XML file!! (stt exists: False)
Skipping document 987/999 with OID {F49B9158-DF5B-4CB1-8892-6AAD5B4465D7} because it's missing its XML file!! (stt exists: False)
Skipping document 991/999 with OID {82F66DA0-A5BE-44F0-BBE5-0BF9454A4A53} because it's missing its XML file!! (stt exists: False)
Skipping document 993/999 with OID {6C700887-A49F-411F-9336-11F971FA355F} because it's missing its XML file!! (stt exists: True)
Skipping document 999/999 with OID {0430BEC6-F028-41D4-8864-115C85A10E73} because it's missing its XML file!! (stt exists: True)
j_mat - returning 646 documents, 353 were skipped due to missing necessary info.

Starting extracting 999 documents for program j_mat
Skipping document 1/999 with OID {88351909-9E98-447E-B198-98B3E8C9B8F8} because it's missing its XML file!! (stt exists: False)
Skipping document 2/999 with OID {1851FE43-A8C3-453E-87D8-FD26E7ED2F1F} because it's missing its XML file!! (stt exists: False)
Skipping document 6/999 with OID {7A1E62BA-9550-43EF-8C12-6E4DBE5B7CBF} because it's missing its XML file!! (stt exists: False)
Skipping document 12/999 with OID {7610C8A8-3894-48BC-8EA4-F81274D05655} because it's missing its XML file!! (stt exists: False)
Skipping document 13/999 with OID {B34683FD-9E3A-431B-A172-5FFA60F92DDF} because it's missing its XML file!! (stt exists: False)
Skipping document 15/999 with OID {6B5E64B0-8C98-4965-8EC1-8E280A05A361} because it's missing its XML file!! (stt exists: True)
Skipping document 16/999 with OID {D520BCFE-6302-4E49-A4B8-1BFE4533D083} because it's missing its XML file!! (stt exists: True)
Skipping document 26/999 with OID {0FA31875-1441-4895-BEB4-F75E70281A42} because it's missing its XML file!! (stt exists: False)
Skipping document 33/999 with OID {E726D9D0-A584-42F9-9805-6743E0BB251A} because it's missing its XML file!! (stt exists: False)
Skipping document 34/999 with OID {BCD82C18-8A03-4457-9778-B6C25078F8CF} because it's missing its XML file!! (stt exists: False)
Skipping document 35/999 with OID {771C43E6-472F-4549-B3FB-CAB197ECACB8} because it's missing its XML file!! (stt exists: False)
Skipping document 36/999 with OID {2FD55F06-94D6-47F3-85C4-2AE10326A924} because it's missing its XML file!! (stt exists: False)
Skipping document 37/999 with OID {84367328-26AF-41E1-AF01-BA18D7EB714B} because it's missing its XML file!! (stt exists: False)
Skipping document 38/999 with OID {D4024F7C-56AF-44D5-BB38-5C05BF822C53} because it's missing its XML file!! (stt exists: False)
Skipping document 39/999 with OID {95C9110D-4593-4A23-A540-340636F14B61} because it's missing its XML file!! (stt exists: False)
Skipping document 41/999 with OID {E2D19929-3B62-4515-A27B-B86B2735752D} because it's missing its XML file!! (stt exists: False)
Skipping document 42/999 with OID {0ACFF89D-78E2-4DA9-8044-8FB81B8D1CD6} because it's missing its XML file!! (stt exists: False)
Skipping document 43/999 with OID {8A91DBBE-91A1-4E79-B1C1-CA8254467662} because it's missing its XML file!! (stt exists: False)
Skipping document 44/999 with OID {11AA0B69-C449-42AC-98BE-EDF5C1B29E2E} because it's missing its XML file!! (stt exists: False)
Skipping document 55/999 with OID {15EBBA3F-03E2-4B2C-8C77-9239D1FC7553} because it's missing its XML file!! (stt exists: False)
Skipping document 56/999 with OID {5D7D94B5-9067-4DD3-9E67-77AD38B0E957} because it's missing its XML file!! (stt exists: False)
Skipping document 59/999 with OID {4B64474E-F225-458A-9A99-30C823C6DD7C} because it's missing its XML file!! (stt exists: False)
Skipping document 60/999 with OID {B4003A26-EF5C-434A-96C6-9827278B73FE} because it's missing its XML file!! (stt exists: False)
Skipping document 61/999 with OID {D0EC1C47-C28E-4787-B253-53504FCEA5DE} because it's missing its XML file!! (stt exists: False)
Skipping document 62/999 with OID {FD4A16CB-D112-475A-AA0A-41E07C2A1E9E} because it's missing its XML file!! (stt exists: False)
Skipping document 70/999 with OID {C7DEDE45-207C-42C8-BCF8-A54F316576BA} because it's missing its XML file!! (stt exists: False)
Skipping document 72/999 with OID {77790084-29CF-499B-A159-C01606AAD56F} because it's missing its XML file!! (stt exists: True)
Skipping document 79/999 with OID {1153E4EC-74C7-4CFA-BEC0-81824606A5CB} because it's missing its XML file!! (stt exists: False)
Skipping document 84/999 with OID {644ACF6E-CDF5-46DE-868F-864C13F878B8} because it's missing its XML file!! (stt exists: False)
Skipping document 91/999 with OID {64499600-B616-4B78-98D3-F26720EAFC38} because it's missing its XML file!! (stt exists: False)
Skipping document 92/999 with OID {4DD5E490-CA62-4449-894E-8728C4A8FBFE} because it's missing its XML file!! (stt exists: False)
Skipping document 93/999 with OID {E821FE9F-8C2E-4DC2-AC45-70406B72EFAD} because it's missing its XML file!! (stt exists: False)
Skipping document 94/999 with OID {51826372-FC00-4E48-B92C-84B5E26AAA46} because it's missing its XML file!! (stt exists: False)
Skipping document 103/999 with OID {AE61328F-6496-418C-A166-47A6FE69358D} because it's missing its XML file!! (stt exists: False)
Skipping document 108/999 with OID {C8E5BB1C-7E86-4E9F-983C-5895EA82CFC6} because it's missing its XML file!! (stt exists: False)
Skipping document 109/999 with OID {D3E12D04-D5F4-4F7E-91F6-86F06C899D32} because it's missing its XML file!! (stt exists: False)
Skipping document 110/999 with OID {38827C81-2021-406A-BA2E-A980DC85357C} because it's missing its XML file!! (stt exists: False)
Skipping document 116/999 with OID {397CC8E9-F4CB-4A69-B488-0BAF1FA0F48C} because it's missing its XML file!! (stt exists: False)
Skipping document 119/999 with OID {78717F7B-2073-4D7B-A378-FDE808A3F55C} because it's missing its XML file!! (stt exists: True)
Skipping document 120/999 with OID {80EF9111-BEA2-4B14-B69A-6CC350CC5972} because it's missing its XML file!! (stt exists: True)
Skipping document 123/999 with OID {9F347204-8B7A-49EE-B37B-250128625338} because it's missing its XML file!! (stt exists: False)
Skipping document 131/999 with OID {4450B1CD-3ECE-415B-8A62-AF4C65EDB95D} because it's missing its XML file!! (stt exists: False)
Skipping document 132/999 with OID {EDF36AA1-C0C1-4D71-94AA-A32A6A37286F} because it's missing its XML file!! (stt exists: False)
Skipping document 137/999 with OID {4AD83AA8-0D24-4BD5-95C7-DF29E10BE9FF} because it's missing its XML file!! (stt exists: False)
Skipping document 138/999 with OID {36B88156-1801-4B7B-9BF8-D9A1329EBFD0} because it's missing its XML file!! (stt exists: False)
Skipping document 139/999 with OID {C33E65A4-6550-42C9-8CD7-7DABA7D43D3B} because it's missing its XML file!! (stt exists: False)
Skipping document 144/999 with OID {1BC5CF5F-EFF2-4672-BFF4-8100EBB39CB3} because it's missing its XML file!! (stt exists: True)
Skipping document 148/999 with OID {83EDA13A-375A-469D-A611-C922DCBB8AE5} because it's missing its XML file!! (stt exists: False)
Skipping document 149/999 with OID {8C87E21C-C704-4C59-9783-6BEACBBCC2F4} because it's missing its XML file!! (stt exists: False)
Skipping document 153/999 with OID {B8536A77-75A6-41A4-BBCE-5794EE624199} because it's missing its XML file!! (stt exists: True)
Skipping document 154/999 with OID {9D88362E-0116-4BA4-A138-7FA2302B37A0} because it's missing its XML file!! (stt exists: False)
Skipping document 157/999 with OID {9A1414D9-0432-47CA-BB90-E143D11668D1} because it's missing its XML file!! (stt exists: False)
Skipping document 158/999 with OID {2EBDC0E5-8547-42AA-8098-160BDF9FDBF4} because it's missing its XML file!! (stt exists: False)
Skipping document 165/999 with OID {FB0F6749-A41D-4DFA-912B-116C848161EF} because it's missing its XML file!! (stt exists: False)
Skipping document 167/999 with OID {BD646F99-8642-48DD-96A8-4D0B01EA73E0} because it's missing its XML file!! (stt exists: False)
Skipping document 168/999 with OID {AA9C1EDA-E368-4CA5-B23F-FF22A344B042} because it's missing its XML file!! (stt exists: False)
Skipping document 170/999 with OID {A322BF97-38C9-468C-A935-D7CD0D519550} because it's missing its XML file!! (stt exists: False)
Skipping document 172/999 with OID {EEF9F194-1601-42C1-9053-88428766012F} because it's missing its XML file!! (stt exists: True)
Skipping document 175/999 with OID {DC26FDDE-AD0A-4E2E-9585-B0B379F8EA05} because it's missing its XML file!! (stt exists: False)
Skipping document 176/999 with OID {0A87FB53-FACF-4531-B551-38111B3D779F} because it's missing its XML file!! (stt exists: False)
Skipping document 187/999 with OID {B1DDCBF3-76CF-4DBD-A553-CBB33111DD3C} because it's missing its XML file!! (stt exists: False)
Skipping document 192/999 with OID {75FEF044-E063-4425-878F-B20E7328091D} because it's missing its XML file!! (stt exists: False)
Skipping document 193/999 with OID {3D0043DF-8DD1-4066-9318-2442AE2A10A5} because it's missing its XML file!! (stt exists: False)
Skipping document 196/999 with OID {25074CC5-F424-45C3-A5E5-973F8CE0082A} because it's missing its XML file!! (stt exists: False)
Skipping document 197/999 with OID {4AB83DBB-03DB-40C8-93FC-F7CF682F19E8} because it's missing its XML file!! (stt exists: False)
Skipping document 198/999 with OID {205E0A10-AF4B-46DD-AD80-58D9C3688BDE} because it's missing its XML file!! (stt exists: False)
Skipping document 203/999 with OID {D0586D2F-2934-4FE1-9656-D5222D6B3946} because it's missing its XML file!! (stt exists: False)
Skipping document 205/999 with OID {DC2D50BE-0558-4BA2-A5BB-5072922AF09E} because it's missing its XML file!! (stt exists: False)
Skipping document 210/999 with OID {C98C3323-A59A-4A09-B093-5616DBC7BDA4} because it's missing its XML file!! (stt exists: False)
Skipping document 211/999 with OID {4D6820F4-F477-45CC-BBD2-0929D1BA4949} because it's missing its XML file!! (stt exists: False)
Skipping document 214/999 with OID {0F24CFDA-00FF-4DA7-A1B6-9DCC43190262} because it's missing its XML file!! (stt exists: False)
Skipping document 216/999 with OID {53C747D4-D68D-42A2-8D35-0E0CA1018FDB} because it's missing its XML file!! (stt exists: False)
Skipping document 220/999 with OID {C485DA80-877E-45F7-B0D0-1DF80AA948DD} because it's missing its XML file!! (stt exists: False)
Skipping document 223/999 with OID {A42471F0-AE7A-4CD7-926C-010A68D7DBFB} because it's missing its XML file!! (stt exists: False)
Skipping document 227/999 with OID {BCB20881-FEE4-4719-B721-412A46CA9C29} because it's missing its XML file!! (stt exists: False)
Skipping document 234/999 with OID {0510DDE6-981E-40E5-B672-53D4329CD33A} because it's missing its XML file!! (stt exists: False)
Skipping document 235/999 with OID {C02794EA-EE62-4E58-A073-8F3333B5652D} because it's missing its XML file!! (stt exists: False)
Skipping document 236/999 with OID {5350B61F-8814-421B-B0AE-FE8B3D6BFBE7} because it's missing its XML file!! (stt exists: False)
Skipping document 240/999 with OID {8DCEBD9C-AB32-49F2-9118-E820764A3042} because it's missing its XML file!! (stt exists: False)
Skipping document 241/999 with OID {70B89C1B-82FD-47C0-A14B-615AB9CA6883} because it's missing its XML file!! (stt exists: False)
Skipping document 242/999 with OID {DAD4E515-23AE-4AB4-9FDD-D310235508E8} because it's missing its XML file!! (stt exists: False)
Skipping document 246/999 with OID {A4859193-2356-4BFF-8B3A-DA54074060E9} because it's missing its XML file!! (stt exists: False)
Skipping document 254/999 with OID {C55B26CD-0861-4C41-9D7A-17324117812B} because it's missing its XML file!! (stt exists: False)
Skipping document 255/999 with OID {ECA667AB-09A4-446B-BAC6-0B577792DE46} because it's missing its XML file!! (stt exists: False)
Skipping document 258/999 with OID {2BD4F191-432E-457C-8ADA-527A49BC1436} because it's missing its XML file!! (stt exists: False)
Skipping document 259/999 with OID {C09CB751-764F-4A23-A8F3-93A38E70D98B} because it's missing its XML file!! (stt exists: False)
Skipping document 264/999 with OID {170A5F30-CA7C-4F18-9CC3-82A71E2674EB} because it's missing its XML file!! (stt exists: True)
Skipping document 266/999 with OID {413CE88A-52F7-4CCD-8D21-E0D32CB58AB7} because it's missing its XML file!! (stt exists: False)
Skipping document 268/999 with OID {693927E2-E796-490F-85F7-3142198744F1} because it's missing its XML file!! (stt exists: False)
Skipping document 269/999 with OID {D0A26EFA-DF05-4167-A5C9-C1C308AA5218} because it's missing its XML file!! (stt exists: False)
Skipping document 270/999 with OID {74C412D6-FCFD-43BB-9E2C-73FDD503379C} because it's missing its XML file!! (stt exists: False)
Skipping document 272/999 with OID {DD4DAC22-F46C-48AE-A501-49D4E65714FB} because it's missing its XML file!! (stt exists: False)
Skipping document 273/999 with OID {DC3C57EF-14A6-4782-9AFE-A7174526A45E} because it's missing its XML file!! (stt exists: False)
Skipping document 280/999 with OID {C94BDAF2-963B-4816-B5A5-6959C132C9F2} because it's missing its XML file!! (stt exists: False)
Skipping document 284/999 with OID {B270111D-D435-43BE-A487-4D2CE00FF4A1} because it's missing its XML file!! (stt exists: False)
Skipping document 285/999 with OID {815570FF-D44E-442B-A3DC-EB53470EA81E} because it's missing its XML file!! (stt exists: False)
Skipping document 286/999 with OID {B01A36D6-90AC-485A-8A02-9732B4E4054C} because it's missing its XML file!! (stt exists: False)
Skipping document 287/999 with OID {42972580-9AF1-4AF0-A881-59F892DEB13D} because it's missing its XML file!! (stt exists: False)
Skipping document 289/999 with OID {CC3E44E5-B352-40EA-9CF5-95F4AB202269} because it's missing its XML file!! (stt exists: False)
Skipping document 291/999 with OID {EC47ADFA-377C-4C78-9684-37F122D23187} because it's missing its XML file!! (stt exists: False)
Skipping document 292/999 with OID {C4898112-9F7F-4E97-BF08-9A5752FDEEA4} because it's missing its XML file!! (stt exists: False)
Skipping document 293/999 with OID {E8DCD884-407D-45C7-9BF2-3CD59D4FB555} because it's missing its XML file!! (stt exists: False)
Skipping document 294/999 with OID {C63D1343-E8B1-4B56-915D-AC891D3581A3} because it's missing its XML file!! (stt exists: False)
Skipping document 295/999 with OID {4E5D386A-02F3-4BB2-961D-A4A43DE82A9D} because it's missing its XML file!! (stt exists: False)
Skipping document 296/999 with OID {87B3B063-4AED-4B23-8D4A-3DDC9BF65D7D} because it's missing its XML file!! (stt exists: False)
Skipping document 297/999 with OID {29841A5F-9512-4512-943E-56F59A298EC5} because it's missing its XML file!! (stt exists: False)
Skipping document 298/999 with OID {89792853-484C-4C66-9428-09C9C2707B0C} because it's missing its XML file!! (stt exists: False)
Skipping document 299/999 with OID {5317BF2D-398C-4E4A-86DF-1703D42FA250} because it's missing its XML file!! (stt exists: False)
Skipping document 300/999 with OID {46DCC105-513F-40CF-8822-C1D17B2BEE35} because it's missing its XML file!! (stt exists: False)
Skipping document 301/999 with OID {0A064965-CC7A-4C92-80FD-652FB450AB6A} because it's missing its XML file!! (stt exists: False)
Skipping document 302/999 with OID {4FD7765B-2E0D-48FD-9A52-6E2363C92C9B} because it's missing its XML file!! (stt exists: False)
Skipping document 303/999 with OID {1A92235D-31CA-40BC-B259-C70CBDE90DF1} because it's missing its XML file!! (stt exists: False)
Skipping document 304/999 with OID {BC14B30D-9972-41CF-8E1B-DC69B678A527} because it's missing its XML file!! (stt exists: False)
Skipping document 305/999 with OID {1D52D88E-5E49-4E00-8639-D92D451ECA9F} because it's missing its XML file!! (stt exists: False)
Skipping document 306/999 with OID {7B719BFF-6AB0-4B48-B594-E35169DBA157} because it's missing its XML file!! (stt exists: False)
Skipping document 307/999 with OID {33716CC0-E068-4836-89C8-64CC6E7F2417} because it's missing its XML file!! (stt exists: False)
Skipping document 309/999 with OID {6991A0AD-5D99-4AFF-9246-72A3F1723365} because it's missing its XML file!! (stt exists: False)
Skipping document 310/999 with OID {AB802DE2-1835-4543-8425-A25621541CEE} because it's missing its XML file!! (stt exists: False)
Skipping document 311/999 with OID {574F6620-CD99-40C6-836C-6B31F74126D7} because it's missing its XML file!! (stt exists: False)
Skipping document 312/999 with OID {32CD5F5D-B2F3-4F45-9186-8F6CCFBDD31F} because it's missing its XML file!! (stt exists: False)
Skipping document 313/999 with OID {E8B76841-67EF-4E58-AD19-6FF39B957FC4} because it's missing its XML file!! (stt exists: False)
Skipping document 314/999 with OID {31A912B0-39F2-49BA-B1A3-8867448E66D4} because it's missing its XML file!! (stt exists: False)
Skipping document 315/999 with OID {AFE3DE8C-8E24-48C3-92E4-DB820948A38F} because it's missing its XML file!! (stt exists: False)
Skipping document 317/999 with OID {6224CCEF-654A-4280-B559-97263F61763A} because it's missing its XML file!! (stt exists: False)
Skipping document 318/999 with OID {982B1D10-6F74-40E6-BA7D-493BB0F17E2C} because it's missing its XML file!! (stt exists: False)
Skipping document 319/999 with OID {BF826591-4558-43D8-B69C-14CFEC1E0183} because it's missing its XML file!! (stt exists: False)
Skipping document 320/999 with OID {0B3A1BB2-D966-48FB-A2C9-D8BFE39F81C3} because it's missing its XML file!! (stt exists: False)
Skipping document 322/999 with OID {8ADD8527-5820-44FD-AFD5-DC4F3CBD6764} because it's missing its XML file!! (stt exists: False)
Skipping document 323/999 with OID {FD3D633A-14DB-48E4-991F-A8D72B6CF696} because it's missing its XML file!! (stt exists: False)
Skipping document 324/999 with OID {D6CC18DC-7975-4BAC-9C30-25A0E1E8D307} because it's missing its XML file!! (stt exists: False)
Skipping document 325/999 with OID {E8414344-8304-4D2A-A102-CBCECC2F0CB4} because it's missing its XML file!! (stt exists: False)
Skipping document 326/999 with OID {E3C71464-B452-4B27-A63B-D520DAC6654D} because it's missing its XML file!! (stt exists: False)
Skipping document 327/999 with OID {4AF77ADA-CDEF-4ADA-98CF-46AA88B1C054} because it's missing its XML file!! (stt exists: False)
Skipping document 328/999 with OID {4F206425-6A8B-47D2-89B1-82A1BDAEE747} because it's missing its XML file!! (stt exists: False)
Skipping document 332/999 with OID {11ED2F54-B544-45EE-AE08-24B21BF32B32} because it's missing its XML file!! (stt exists: False)

100%|██████████| 11/11 [00:33<00:00,  3.08s/it]

Skipping document 926/999 with OID {91A71D4F-26A6-4119-9C2A-9733ECD8E0C1} because it's missing its XML file!! (stt exists: True)
Skipping document 927/999 with OID {828677C5-8E4A-4F80-8B7A-E9F25D95435A} because it's missing its XML file!! (stt exists: True)
Skipping document 928/999 with OID {D19A071E-40E0-411A-AACD-3AD19A495BAB} because it's missing its XML file!! (stt exists: False)
Skipping document 940/999 with OID {1A6500AE-9F81-4B1E-BDD9-27C093CE06E6} because it's missing its XML file!! (stt exists: False)
Skipping document 945/999 with OID {9FCC11EE-90F0-4E1C-BA21-9B95627AD255} because it's missing its XML file!! (stt exists: False)
Skipping document 947/999 with OID {53305BC9-4215-4BC7-99FC-604CABE62262} because it's missing its XML file!! (stt exists: False)
Skipping document 949/999 with OID {5E1121E9-E87C-499E-829A-E403D0523B05} because it's missing its XML file!! (stt exists: False)
Skipping document 956/999 with OID {5422907B-4B59-4649-920B-3E775718937C} because it's missing its XML file!! (stt exists: True)
Skipping document 957/999 with OID {70923F42-D975-46E0-84F3-CD63745D64B2} because it's missing its XML file!! (stt exists: False)
Skipping document 962/999 with OID {8F8C0B34-520D-41AA-BCB5-7E8B7F1B39F7} because it's missing its XML file!! (stt exists: False)
Skipping document 964/999 with OID {91714FBF-D486-4578-8F4E-EECCCDAE21FD} because it's missing its XML file!! (stt exists: False)
Skipping document 967/999 with OID {523F39EB-4E3A-4833-A30B-6A5D56D7092D} because it's missing its XML file!! (stt exists: True)
Skipping document 974/999 with OID {CAC802CA-4256-4A0E-8E4A-22A93145CD90} because it's missing its XML file!! (stt exists: True)
Skipping document 979/999 with OID {AD31E3D6-8F38-46F9-BEE4-EB8212D0ACE1} because it's missing its XML file!! (stt exists: True)
Skipping document 980/999 with OID {074AD35B-19AE-4F31-8BAB-7D6A61967489} because it's missing its XML file!! (stt exists: True)
Skipping document 982/999 with OID {83BEE558-E670-4292-A439-7B069B08CA68} because it's missing its XML file!! (stt exists: True)
Skipping document 983/999 with OID {1FDF21C3-A7F0-40DC-BE67-D1534DE68A01} because it's missing its XML file!! (stt exists: True)
Skipping document 984/999 with OID {CAE6D5B5-932E-42E5-88D6-991C0C049D11} because it's missing its XML file!! (stt exists: True)
Skipping document 985/999 with OID {B7AD2BB4-0468-4A31-ADFC-0844FD99C77F} because it's missing its XML file!! (stt exists: True)
Skipping document 986/999 with OID {05DBC785-7E59-4967-817F-6D80C0319D57} because it's missing its XML file!! (stt exists: True)
Skipping document 992/999 with OID {61BBBC3B-71E6-43F8-92BC-5E522F170970} because it's missing its XML file!! (stt exists: True)
Skipping document 993/999 with OID {8CC6A6F2-A10C-4148-B3FE-D26ADA725F68} because it's missing its XML file!! (stt exists: True)
Skipping document 994/999 with OID {7EDAC7F2-525F-407B-AB55-D9AAA0A7F10E} because it's missing its XML file!! (stt exists: False)
Skipping document 995/999 with OID {A7ECDAE3-2115-4C01-93BF-4A7BD092EAEE} because it's missing its XML file!! (stt exists: True)
Skipping document 996/999 with OID {1D69C6A3-1E7C-4E14-968E-2BED5FDE69DB} because it's missing its XML file!! (stt exists: False)
Skipping document 997/999 with OID {A993F8E5-E042-4F34-A9B8-ACD369FAAC2B} because it's missing its XML file!! (stt exists: False)
Skipping document 998/999 with OID {45D41914-E9E8-4316-8B29-1E5DC89912AC} because it's missing its XML file!! (stt exists: False)
Skipping document 999/999 with OID {F0A72CE5-2160-4F10-B27A-25DC42209772} because it's missing its XML file!! (stt exists: False)
j_mat - returning 627 documents, 372 were skipped due to missing necessary info.
 --> Adding 5278 to the out csv for j_mat

20it [00:48, 10.67s/it]

PROCESSING PROGRAM j_midi (21/47) - 7 files:

Starting extracting 999 documents for program j_midi
Skipping document 1/999 with OID {9A8DAD76-EC7F-432E-9FFF-A7C09F5BB3B8} because it's missing its XML file!! (stt exists: False)
Skipping document 2/999 with OID {13F9BA24-7277-4A92-B7E9-6E9C695C01AD} because it's missing its XML file!! (stt exists: False)
Skipping document 3/999 with OID {9BCF38D9-7FBF-4A4E-8193-1AFD519A9B38} because it's missing its XML file!! (stt exists: False)
Skipping document 9/999 with OID {E24CCE52-F76F-45D4-98D8-498AEC8701CA} because it's missing its XML file!! (stt exists: False)
Skipping document 10/999 with OID {A066D541-E9E5-4F2B-807E-FC596B570553} because it's missing its XML file!! (stt exists: False)
Skipping document 12/999 with OID {31700ABD-27CB-46B6-96F5-7C5BD1703987} because it's missing its XML file!! (stt exists: False)
Skipping document 16/999 with OID {52F80052-8B34-47EC-AFDC-885037ADB671} because it's missing its XML file!! (stt exists: False)
Skipping document 18/999 with OID {87B0C497-F6A9-4AFA-9E6D-D6C78BEA6014} because it's missing its XML file!! (stt exists: False)
Skipping document 19/999 with OID {DADB0BF2-C001-4668-B832-6F94B9966D85} because it's missing its XML file!! (stt exists: False)
Skipping document 35/999 with OID {0932E25A-3BA8-4B26-BBCB-A77004AB8AA3} because it's missing its XML file!! (stt exists: True)
Skipping document 38/999 with OID {01E14FB3-04AE-4D32-92CC-0ECA30473E3B} because it's missing its XML file!! (stt exists: True)
Skipping document 42/999 with OID {66A7E844-F684-4410-931E-A8A49781D7BE} because it's missing its XML file!! (stt exists: False)
Skipping document 73/999 with OID {C0AEB922-9822-4D3A-A34C-C36414F52DFC} because it's missing its XML file!! (stt exists: False)
Skipping document 78/999 with OID {6C5BB53D-D5B8-4E4D-82FE-38BBD08DE125} because it's missing its XML file!! (stt exists: False)
Skipping document 90/999 with OID {724B3516-B8D6-4E90-A615-A4021ABE91D7} because it's missing its XML file!! (stt exists: False)
Skipping document 95/999 with OID {3499BC02-BF1B-4969-87B9-78A7FF5827A1} because it's missing its XML file!! (stt exists: False)
Skipping document 97/999 with OID {86F70CA3-250E-4891-AF6B-6D41D657C59C} because it's missing its XML file!! (stt exists: False)
Skipping document 103/999 with OID {E6FE5212-A56D-40DA-81E5-F6C5C3668FD3} because it's missing its XML file!! (stt exists: False)
Skipping document 104/999 with OID {872D9F15-1C6E-4DF2-982B-800C523BA74C} because it's missing its XML file!! (stt exists: False)
Skipping document 105/999 with OID {FEDA0931-0280-4C52-99D2-D78C24DBA3A6} because it's missing its XML file!! (stt exists: False)
Skipping document 110/999 with OID {F22CF516-9BF6-4637-A7BC-D9B270A1B047} because it's missing its XML file!! (stt exists: True)
Skipping document 111/999 with OID {A4B8CF24-E43B-470E-B6B5-9BAE44D120C4} because it's missing its XML file!! (stt exists: True)
Skipping document 112/999 with OID {40945A46-F913-4B70-A1D1-66B3C225161C} because it's missing its XML file!! (stt exists: True)
Skipping document 113/999 with OID {AEFEFD62-93BC-4A33-B57B-A41C0A3AAAF5} because it's missing its XML file!! (stt exists: True)
Skipping document 114/999 with OID {13A73B11-1330-4AF0-AFF4-20CD7CB6EDFD} because it's missing its XML file!! (stt exists: True)
Skipping document 116/999 with OID {0D06E6FE-259D-4558-B1EB-1B042596F440} because it's missing its XML file!! (stt exists: False)
Skipping document 117/999 with OID {C7326ED9-73D9-4F39-B80A-B4B7B5A28604} because it's missing its XML file!! (stt exists: False)
Skipping document 121/999 with OID {BC0D2AD1-39E0-4DC0-B0FF-C2F77BCB0AFA} because it's missing its XML file!! (stt exists: False)
Skipping document 122/999 with OID {FE969549-1E86-432D-8403-73A6D4B7EF16} because it's missing its XML file!! (stt exists: True)
Skipping document 123/999 with OID {1FCC25E8-85D0-45BA-81D1-3756F41FDDE3} because it's missing its XML file!! (stt exists: True)
Skipping document 130/999 with OID {47DF6AA3-3345-4943-B569-E89574791E42} because it's missing its XML file!! (stt exists: False)
Skipping document 137/999 with OID {60884A56-FB3F-4AB4-9C7E-47D93F7D0CCA} because it's missing its XML file!! (stt exists: False)
Skipping document 138/999 with OID {AEC32441-1D93-43A5-8DE3-E12BA0AF46F8} because it's missing its XML file!! (stt exists: False)
Skipping document 140/999 with OID {8025AD8D-9527-4E4A-918B-FEBAAAD15AA6} because it's missing its XML file!! (stt exists: True)
Skipping document 147/999 with OID {E8C0E177-C047-48FE-A5B3-D8BC04F89615} because it's missing its XML file!! (stt exists: True)
Skipping document 150/999 with OID {82AC1BE1-B782-4044-B5A6-25595FE41636} because it's missing its XML file!! (stt exists: True)
Skipping document 152/999 with OID {38432692-F51C-432E-9B41-DC91436071D7} because it's missing its XML file!! (stt exists: False)
Skipping document 154/999 with OID {CDC584F6-BC8D-4E5F-838F-438C789171F4} because it's missing its XML file!! (stt exists: True)
Skipping document 155/999 with OID {58FF8549-E216-43F7-BD50-33FB49E56EA7} because it's missing its XML file!! (stt exists: True)
Skipping document 156/999 with OID {E1B4463F-30C1-4B57-B86D-C8684FB40CC6} because it's missing its XML file!! (stt exists: False)
Skipping document 157/999 with OID {D6144493-4E07-4B74-964C-03203CE58CFB} because it's missing its XML file!! (stt exists: True)
Skipping document 158/999 with OID {70674ADE-F28F-45C6-9C95-D61E6DE7827B} because it's missing its XML file!! (stt exists: True)
Skipping document 159/999 with OID {26ED696A-333F-42D2-B6CA-E9C5C1B4E337} because it's missing its XML file!! (stt exists: True)
Skipping document 164/999 with OID {63BA0DA8-D5C6-4CF3-95BD-889602759813} because it's missing its XML file!! (stt exists: True)
Skipping document 165/999 with OID {575CCC54-4EC8-4500-B68A-6DE78A3575C3} because it's missing its XML file!! (stt exists: True)
Skipping document 166/999 with OID {E87F28F0-1712-4B24-A9D7-B7067E48EF93} because it's missing its XML file!! (stt exists: True)
Skipping document 167/999 with OID {60140059-17FB-4B2C-A288-F8729A1A42A0} because it's missing its XML file!! (stt exists: True)
Skipping document 175/999 with OID {7E27FB79-FBE1-4044-912B-97368BEF44F8} because it's missing its XML file!! (stt exists: False)
Skipping document 177/999 with OID {F64F54ED-ED46-401B-B4E6-7A6267FE1036} because it's missing its XML file!! (stt exists: False)
Skipping document 180/999 with OID {88401258-AA7D-43E1-AE4D-CC2BDC92612C} because it's missing its XML file!! (stt exists: True)
Skipping document 181/999 with OID {37655661-3E98-432A-93BE-733C5986754C} because it's missing its XML file!! (stt exists: False)
Skipping document 183/999 with OID {70D50106-D362-493A-ACB4-102585EC27E2} because it's missing its XML file!! (stt exists: False)
Skipping document 192/999 with OID {4038BDBC-0212-4086-82FC-825A20727F85} because it's missing its XML file!! (stt exists: True)
Skipping document 193/999 with OID {87B592F6-202F-4783-ACDC-46DB152C1C86} because it's missing its XML file!! (stt exists: True)
Skipping document 195/999 with OID {4BC2AF60-8DB9-4FEA-BCB4-566E856BA439} because it's missing its XML file!! (stt exists: True)
Skipping document 196/999 with OID {8EF4A3A2-E56C-4F5C-8732-8BB641CA58F6} because it's missing its XML file!! (stt exists: False)
Skipping document 197/999 with OID {6FFC9ED7-6360-4BE8-AB51-A4B3EB1E7183} because it's missing its XML file!! (stt exists: False)
Skipping document 198/999 with OID {81AC97C0-EA06-4072-91AA-A7F864411B1A} because it's missing its XML file!! (stt exists: True)
Skipping document 199/999 with OID {95850469-0A4E-498F-9301-12B46CD17F4F} because it's missing its XML file!! (stt exists: True)
Skipping document 237/999 with OID {36E77B27-61E8-4FB9-81B0-BFA847C7D8AC} because it's missing its XML file!! (stt exists: False)
Skipping document 238/999 with OID {0C6EE25F-1F30-4DEA-9897-E60952544D8C} because it's missing its XML file!! (stt exists: False)
Skipping document 241/999 with OID {9715EF2F-8A89-47DC-B545-1CB1BDDF0A39} because it's missing its XML file!! (stt exists: True)
Did not find any date for doc with OID {39282913-2F02-4C07-9FD7-C82762259C3C}. Trying to use the recording date. doc_dict: {'alias': 'j_midi', 'date_str': None, 'stt_filename': '39282913-2F02-4C07-9FD7-C82762259C3C_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{39282913-2F02-4C07-9FD7-C82762259C3C}', 'stripped_OID': '39282913-2F02-4C07-9FD7-C82762259C3C', 'login': '', 'broadcast_episode_title': 'Histoires proven?ales (1/5) : Le village de Fourvieil et Cl?mence centenaire', 'sequence': '1', 'broadcast_program_name': 'Journal de midi', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'prongudo', 'modified_on': '09.03.2023 11:21:31', 'physical_support_history': "Cote d'origine: NUSSLE 03. Bobino choisi par Dominique Prongu? et Michel Bory, en collaboration avec Andr? Nussl?, au domicile de ce dernier, le 14 avril 2011.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': None, 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:07:42.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Audouard, Yvan', 'function': 'Interview?/e', 'role': '?crivain'}, {'name': 'Nussl?, Andr?', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Fourvieil'], 'person_descriptors': None, 'thematical_descriptors': ['village'], 'rights_usage_possibilities': None, 'radio_channels': ['Premier programme'], 'subdomains': ['Interview'], 'recording_dates': ['14/05/1974 - 14/05/1974'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {012335CE-CA7D-4427-BE00-B03AD455176B}. Trying to use the recording date. doc_dict: {'alias': 'j_midi', 'date_str': None, 'stt_filename': '012335CE-CA7D-4427-BE00-B03AD455176B_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{012335CE-CA7D-4427-BE00-B03AD455176B}', 'stripped_OID': '012335CE-CA7D-4427-BE00-B03AD455176B', 'login': '', 'broadcast_episode_title': 'Histoires proven?ales (2/5) : Marseille et son accent', 'sequence': '1', 'broadcast_program_name': 'Journal de midi', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'prongudo', 'modified_on': '09.03.2023 11:15:01', 'physical_support_history': "Cote d'origine: NUSSLE 04. Bobino choisi par Dominique Prongu? et Michel Bory, en collaboration avec Andr? Nussl?, au domicile de ce dernier, le 14 avril 2011.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': None, 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:07:30.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Audouard, Yvan', 'function': 'Interview?/e', 'role': '?crivain'}, {'name': 'Nussl?, Andr?', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Marseille'], 'person_descriptors': None, 'thematical_descriptors': ['langue'], 'rights_usage_possibilities': None, 'radio_channels': ['Premier programme'], 'subdomains': ['Interview'], 'recording_dates': ['28/05/1974 - 28/05/1974'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {A42E6958-0E97-4D2F-BC9E-27E31E903F97}. Trying to use the recording date. doc_dict: {'alias': 'j_midi', 'date_str': None, 'stt_filename': 'A42E6958-0E97-4D2F-BC9E-27E31E903F97_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{A42E6958-0E97-4D2F-BC9E-27E31E903F97}', 'stripped_OID': 'A42E6958-0E97-4D2F-BC9E-27E31E903F97', 'login': '', 'broadcast_episode_title': 'Histoires proven?ales (3/5) : Les boules', 'sequence': '1', 'broadcast_program_name': 'Journal de midi', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'prongudo', 'modified_on': '20.05.2022 10:44:22', 'physical_support_history': "Cote d'origine: NUSSLE 04 BIS. Bobino choisi par Dominique Prongu? et Michel Bory, en collaboration avec Andr? Nussl?, au domicile de ce dernier, le 14 avril 2011.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': None, 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:08:36.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Audouard, Yvan', 'function': 'Interview?/e', 'role': '?crivain'}, {'name': 'Nussl?, Andr?', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Provence'], 'person_descriptors': None, 'thematical_descriptors': ['jeu'], 'rights_usage_possibilities': None, 'radio_channels': ['Premier programme'], 'subdomains': ['Interview'], 'recording_dates': ['31/05/1974 - 31/05/1974'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {4F17EE06-ECBF-4259-9D03-1D589EEC6FB3}. Trying to use the recording date. doc_dict: {'alias': 'j_midi', 'date_str': None, 'stt_filename': '4F17EE06-ECBF-4259-9D03-1D589EEC6FB3_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{4F17EE06-ECBF-4259-9D03-1D589EEC6FB3}', 'stripped_OID': '4F17EE06-ECBF-4259-9D03-1D589EEC6FB3', 'login': '', 'broadcast_episode_title': "Histoires proven?ales (4/5) : Le village de Paradou et Baptiste l'instituteur", 'sequence': '1', 'broadcast_program_name': 'Journal de midi', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'prongudo', 'modified_on': '11.06.2022 08:47:20', 'physical_support_history': "Cote d'origine: NUSSLE 71.  Bobino choisi par Dominique Prongu? et Michel Bory, en collaboration avec Andr? Nussl?, au domicile de ce dernier, le 14 avril 2011.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': None, 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:09:42.449', 'work_duration_compl': 'Non', 'participants': [{'name': 'Audouard, Yvan', 'function': 'Interview?/e', 'role': '?crivain'}, {'name': 'Nussl?, Andr?', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Provence'], 'person_descriptors': None, 'thematical_descriptors': ['village'], 'rights_usage_possibilities': None, 'radio_channels': ['Premier programme'], 'subdomains': ['Interview'], 'recording_dates': ['15/05/1971 - 15/05/1971'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {31D88C37-561F-4856-A664-586B9D7621AE}. Trying to use the recording date. doc_dict: {'alias': 'j_midi', 'date_str': None, 'stt_filename': '31D88C37-561F-4856-A664-586B9D7621AE_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{31D88C37-561F-4856-A664-586B9D7621AE}', 'stripped_OID': '31D88C37-561F-4856-A664-586B9D7621AE', 'login': '', 'broadcast_episode_title': 'Histoires proven?ales (5/5) : Ile-sur-Sorgue', 'sequence': '1', 'broadcast_program_name': 'Journal de midi', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'prongudo', 'modified_on': '09.03.2023 09:02:50', 'physical_support_history': "Cote d'origine: NUSSLE 75.  Bobino choisi par Dominique Prongu? et Michel Bory, en collaboration avec Andr? Nussl?, au domicile de ce dernier, le 14 avril 2011.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': None, 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:07:07.950', 'work_duration_compl': 'Non', 'participants': [{'name': 'Audouard, Yvan', 'function': 'Interview?/e', 'role': '?crivain'}, {'name': 'Nussl?, Andr?', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Provence'], 'person_descriptors': ['Char, Ren?'], 'thematical_descriptors': ['village', 'po?sie'], 'rights_usage_possibilities': None, 'radio_channels': ['Premier programme'], 'subdomains': ['Interview'], 'recording_dates': ['13/05/1974 - 13/05/1974'], 'first_broadcast_dates': None}
Skipping document 249/999 with OID {390861E9-7833-4ED9-8368-3E7D7E4801CE} because it's missing its XML file!! (stt exists: False)
Skipping document 251/999 with OID {9C8D54DA-B2BB-4F70-B558-C7FF725D1F90} because it's missing its XML file!! (stt exists: False)
Skipping document 252/999 with OID {8038B312-1AB9-4DCD-AD4C-046231CA0B2D} because it's missing its XML file!! (stt exists: False)
Skipping document 253/999 with OID {CBEADAD1-2DD2-42F6-A4AE-C9B8326E60EE} because it's missing its XML file!! (stt exists: False)
Skipping document 254/999 with OID {C9D00F6E-4896-4B05-BEC3-21AD4412C0B0} because it's missing its XML file!! (stt exists: False)
Skipping document 255/999 with OID {CC3CFE63-6236-4CE4-8EE2-117C28442137} because it's missing its XML file!! (stt exists: False)
Skipping document 256/999 with OID {8E74D126-9F74-41B9-A143-A8E594A86047} because it's missing its XML file!! (stt exists: False)
Skipping document 257/999 with OID {70395960-2537-405F-B8E9-C9EE7CA2AB74} because it's missing its XML file!! (stt exists: False)
Skipping document 258/999 with OID {55D2F6D9-3C10-436D-A6DD-20B82FB23582} because it's missing its XML file!! (stt exists: False)
Skipping document 259/999 with OID {2EB2461F-5974-4477-B47E-F35C6E4AD81A} because it's missing its XML file!! (stt exists: False)
Skipping document 260/999 with OID {DD7D9646-4A6C-4AC3-8E27-BFF52CAB7C80} because it's missing its XML file!! (stt exists: False)
Skipping document 264/999 with OID {37ACB32F-961D-45E2-9775-3F302E180881} because it's missing its XML file!! (stt exists: False)

Skipping document 939/999 with OID {75CB15CD-AC86-4C03-BDEA-8C1B28374C86} because it's missing its XML file!! (stt exists: False)
Skipping document 942/999 with OID {940235A5-C088-4E58-A413-07D882946B2E} because it's missing its XML file!! (stt exists: False)
Skipping document 946/999 with OID {C8B2DB73-0799-4AD6-80E8-58879D055ABD} because it's missing its XML file!! (stt exists: True)
Skipping document 949/999 with OID {D2535814-405A-4B65-9700-8C1817A2C8F6} because it's missing its XML file!! (stt exists: False)
Skipping document 951/999 with OID {50A9B154-A089-42F7-8AC3-757A501DA699} because it's missing its XML file!! (stt exists: False)
Skipping document 954/999 with OID {D1AA4F7A-493F-4866-8437-F37088A7B4A9} because it's missing its XML file!! (stt exists: False)
Skipping document 955/999 with OID {BF7D6B4F-C0CD-409F-BEB8-AAE13979A721} because it's missing its XML file!! (stt exists: False)
Skipping document 956/999 with OID {E7F71A28-2CAA-4626-B195-CA083D651DCD} because it's missing its XML file!! (stt exists: False)
Skipping document 961/999 with OID {60CEA002-0ABF-45B0-B1C7-90CFA3178969} because it's missing its XML file!! (stt exists: False)
Skipping document 962/999 with OID {BBC3B1A1-D187-4725-9331-AAC76DB91C5B} because it's missing its XML file!! (stt exists: False)
Skipping document 963/999 with OID {BE28A4EE-3A18-46C1-81B5-2F9641AD2878} because it's missing its XML file!! (stt exists: False)
Skipping document 964/999 with OID {2C967731-D970-4D4F-8025-57C69EE1BCBC} because it's missing its XML file!! (stt exists: False)
Skipping document 965/999 with OID {E294622C-7BDB-45B6-9022-202FDC2C741E} because it's missing its XML file!! (stt exists: False)
Skipping document 966/999 with OID {32B99E50-B192-4A22-9839-36F844999FFF} because it's missing its XML file!! (stt exists: False)
Skipping document 967/999 with OID {398E0F50-CC6F-48C7-8DF3-70B407B567C4} because it's missing its XML file!! (stt exists: False)
Skipping document 968/999 with OID {03D22B3C-3A54-49ED-B483-D64CEC5BCB51} because it's missing its XML file!! (stt exists: False)
Skipping document 969/999 with OID {DC386087-178B-4D67-885F-357CABAF67B4} because it's missing its XML file!! (stt exists: False)
Skipping document 970/999 with OID {5D3C3A6B-0E01-4742-852C-E54F396ADDC9} because it's missing its XML file!! (stt exists: False)
Skipping document 971/999 with OID {D73B3359-666D-43C6-88C8-6B09DE75406C} because it's missing its XML file!! (stt exists: False)
Skipping document 981/999 with OID {7F2E30D1-036B-4320-97A9-FFE93F62419D} because it's missing its XML file!! (stt exists: False)
Skipping document 982/999 with OID {BA9DF307-F4B2-400E-B084-5A3427CA5FD8} because it's missing its XML file!! (stt exists: False)
Skipping document 983/999 with OID {9365A6D5-8ED0-49A7-9882-B505380FDC43} because it's missing its XML file!! (stt exists: False)
Skipping document 984/999 with OID {4533BB35-5BE9-44C2-8D66-0058DA12A6C0} because it's missing its XML file!! (stt exists: False)
Skipping document 985/999 with OID {30ADF7B6-CE45-4338-806D-C4D19A2CAFD7} because it's missing its XML file!! (stt exists: False)
Skipping document 987/999 with OID {A089773D-F5C0-463B-A4C8-0F02870D526B} because it's missing its XML file!! (stt exists: False)
Skipping document 991/999 with OID {96A28E78-5237-4339-A975-A17AAAC24BB4} because it's missing its XML file!! (stt exists: True)
Skipping document 993/999 with OID {33C0839B-C35F-4B03-9E45-462339AE4D34} because it's missing its XML file!! (stt exists: False)
Skipping document 994/999 with OID {25C19CC1-4BAA-4906-8774-6220A0CDECEE} because it's missing its XML file!! (stt exists: False)
Skipping document 995/999 with OID {6DB04438-FF6C-48D1-A900-B9B4EF85003B} because it's missing its XML file!! (stt exists: False)
Skipping document 997/999 with OID {8308AB3F-C229-4923-B3AD-400B4E44BB8D} because it's missing its XML file!! (stt exists: False)
Skipping document 998/999 with OID {EC6D4A74-7C1F-4650-AEFA-997EE4332F37} because it's missing its XML file!! (stt exists: False)
Skipping document 999/999 with OID {1D2B90E5-7C98-4A33-AB82-4E8ADB4B17B9} because it's missing its XML file!! (stt exists: False)
j_midi - returning 588 documents, 411 were skipped due to missing necessary info.

Starting extracting 999 documents for program j_midi
Skipping document 1/999 with OID {223447BF-E751-4AA0-AFD5-73258C3512F0} because it's missing its XML file!! (stt exists: False)
Skipping document 2/999 with OID {C44E4CD3-3155-4B60-8CE5-9D147B4D199A} because it's missing its XML file!! (stt exists: False)
Skipping document 3/999 with OID {0088EAC4-57F3-4A20-AF36-167DDF8BDCB5} because it's missing its XML file!! (stt exists: False)
Skipping document 4/999 with OID {25E3489A-40AF-4165-ACE3-C2D6814B861B} because it's missing its XML file!! (stt exists: False)
Skipping document 6/999 with OID {20249D1C-BBC3-47BB-9BC5-5D5B5F47622F} because it's missing its XML file!! (stt exists: False)
Skipping document 7/999 with OID {A5113951-0BBE-49A6-922E-C983AB657D29} because it's missing its XML file!! (stt exists: False)
Skipping document 8/999 with OID {B98A3DD8-F79B-4DCA-9E8A-B259CB2FA1A8} because it's missing its XML file!! (stt exists: False)
Skipping document 9/999 with OID {D9CB1B0D-40E9-49C0-9A1C-427AD4CDB6B1} because it's missing its XML file!! (stt exists: False)
Skipping document 10/999 with OID {641E2DC6-E4EA-4341-9FD9-A482A1A823E3} because it's missing its XML file!! (stt exists: False)
Skipping document 11/999 with OID {4DF17D05-D61B-4819-B83C-C0B69E7DDABA} because it's missing its XML file!! (stt exists: False)
Skipping document 12/999 with OID {CCF61C7D-3C69-4C3C-8C11-A9DD29CBEF3C} because it's missing its XML file!! (stt exists: False)
Skipping document 13/999 with OID {1214418F-96B6-4835-AAF3-3DAFDDCAF089} because it's missing its XML file!! (stt exists: False)
Skipping document 14/999 with OID {4C01593A-DDCD-4967-BFF3-7526B69F992B} because it's missing its XML file!! (stt exists: False)
Skipping document 15/999 with OID {C34618F2-A45F-433B-AA12-2EA7FE929D70} because it's missing its XML file!! (stt exists: False)
Skipping document 16/999 with OID {4070D494-72D2-4071-82CF-566F7589C596} because it's missing its XML file!! (stt exists: False)
Skipping document 17/999 with OID {EA7D46F6-8871-48F2-B099-4B98C199DAF2} because it's missing its XML file!! (stt exists: False)
Skipping document 18/999 with OID {6AB62204-C2B7-4217-AA51-85BE4EFC7FC1} because it's missing its XML file!! (stt exists: False)
Skipping document 19/999 with OID {00CCAE2F-3549-400E-89BC-64BF43FCAD5D} because it's missing its XML file!! (stt exists: False)
Skipping document 20/999 with OID {2116AF90-7C4E-45BE-A4CC-0DBF81D4B572} because it's missing its XML file!! (stt exists: False)
Skipping document 21/999 with OID {28A5254E-BAF3-408C-B9B9-55D8679B467D} because it's missing its XML file!! (stt exists: False)
Skipping document 22/999 with OID {43D3A1D6-8EEB-482D-A032-A558EF9269CE} because it's missing its XML file!! (stt exists: False)
Skipping document 23/999 with OID {F031A4DC-1B47-47F7-B66A-145087A5942B} because it's missing its XML file!! (stt exists: False)
Skipping document 24/999 with OID {793717EB-AC38-44FB-971F-4D1033C6EEE3} because it's missing its XML file!! (stt exists: False)
Skipping document 25/999 with OID {35BA34F8-66BA-4A79-A17B-43936867B6CD} because it's missing its XML file!! (stt exists: False)
Skipping document 26/999 with OID {E5A62E6B-3B14-4E06-B0E3-482A03B967ED} because it's missing its XML file!! (stt exists: False)
Skipping document 27/999 with OID {6D1D5015-5013-494A-BF83-AB8B2DF497A4} because it's missing its XML file!! (stt exists: False)
Skipping document 28/999 with OID {E39136F8-DD4E-4177-85AA-1589053E1056} because it's missing its XML file!! (stt exists: False)
Skipping document 29/999 with OID {B1BAF377-943F-4143-B219-7CA19B995BFE} because it's missing its XML file!! (stt exists: False)
Skipping document 30/999 with OID {035AE122-9F92-4719-91BA-20E89139E69D} because it's missing its XML file!! (stt exists: False)
Skipping document 31/999 with OID {69DFA398-DE4B-4188-9AE6-4C1B636FB584} because it's missing its XML file!! (stt exists: False)
Skipping document 32/999 with OID {F08D61F5-F75F-459A-8C35-CE84E1C7A1AE} because it's missing its XML file!! (stt exists: False)
Skipping document 33/999 with OID {BFADAD52-D467-4A03-81E2-58A8881EB45C} because it's missing its XML file!! (stt exists: False)
Skipping document 34/999 with OID {5F866B70-96CF-4A46-9613-E2F46841451B} because it's missing its XML file!! (stt exists: False)
Skipping document 36/999 with OID {E4BEAFD8-18FF-40EB-B2CB-E26032B6A3ED} because it's missing its XML file!! (stt exists: False)
Skipping document 38/999 with OID {2F58E829-EC28-4980-AB55-C05D8B07B371} because it's missing its XML file!! (stt exists: False)
Skipping document 39/999 with OID {E8E5DACF-DC6D-4133-AC01-CD35C3876FF0} because it's missing its XML file!! (stt exists: False)
Skipping document 40/999 with OID {CF249D10-2B99-4136-B90F-66AEFC44722C} because it's missing its XML file!! (stt exists: False)
Skipping document 41/999 with OID {95DD69C9-7341-4A3B-A89C-47471261EE6B} because it's missing its XML file!! (stt exists: False)
Skipping document 42/999 with OID {B443ED5F-D3D6-4633-9D50-3E6BBD947E3D} because it's missing its XML file!! (stt exists: False)
Skipping document 43/999 with OID {D1E60060-915B-40D1-8AF5-FA874DE794E0} because it's missing its XML file!! (stt exists: False)
Skipping document 45/999 with OID {E81B763C-D605-48DB-AE16-8F6ACA14B6DA} because it's missing its XML file!! (stt exists: False)
Skipping document 46/999 with OID {340EB9E9-853E-4A6A-B9F7-6A14E41BF1EB} because it's missing its XML file!! (stt exists: False)
Skipping document 47/999 with OID {2AABA6A3-0269-4979-9B62-4981C4CED390} because it's missing its XML file!! (stt exists: False)
Skipping document 48/999 with OID {9493101E-F835-42BF-B07D-89FFE8D4E734} because it's missing its XML file!! (stt exists: False)
Skipping document 49/999 with OID {B28E0425-7720-42C5-8E2E-C2A6FF363C42} because it's missing its XML file!! (stt exists: False)
Skipping document 50/999 with OID {CBDFDD65-BF60-4EA5-B7CB-1E8807A82C1C} because it's missing its XML file!! (stt exists: False)
Skipping document 51/999 with OID {6D3116DA-A271-41FC-A96F-86F5EB19525D} because it's missing its XML file!! (stt exists: False)
Skipping document 55/999 with OID {9926B9E4-F286-41FB-8DA7-E74A306635D3} because it's missing its XML file!! (stt exists: False)
Skipping document 57/999 with OID {B38CEDF3-7337-4B87-8040-ED239C1DE03E} because it's missing its XML file!! (stt exists: False)
Skipping document 61/999 with OID {601B6B70-E7EE-4531-9A71-7CF195009470} because it's missing its XML file!! (stt exists: False)
Skipping document 62/999 with OID {6C528D39-ACF5-4318-89FC-EDA4EC534CF4} because it's missing its XML file!! (stt exists: False)
Skipping document 65/999 with OID {A5DBF465-3402-4F1B-A4CE-1944F8C8CC71} because it's missing its XML file!! (stt exists: False)
Skipping document 69/999 with OID {6A16628E-77B9-42A5-9FC8-6C8C1E18312C} because it's missing its XML file!! (stt exists: False)
Skipping document 111/999 with OID {D0B71E97-3721-44B9-9B54-225EA3CFF50D} because it's missing its XML file!! (stt exists: False)
Skipping document 119/999 with OID {CF4963FB-CB08-425F-93D7-4D492B60AA3C} because it's missing its XML file!! (stt exists: True)
Did not find any date for doc with OID {9DE9E219-A622-45CB-835D-7F51786E30F4}. Trying to use the recording date. doc_dict: {'alias': 'j_midi', 'date_str': None, 'stt_filename': '9DE9E219-A622-45CB-835D-7F51786E30F4_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{9DE9E219-A622-45CB-835D-7F51786E30F4}', 'stripped_OID': '9DE9E219-A622-45CB-835D-7F51786E30F4', 'login': '', 'broadcast_episode_title': 'Congr?s du Groupement f?minin de Force d?mocratique ? Court', 'sequence': '1', 'broadcast_program_name': 'Journal de midi', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '21.05.2015 01:05:38', 'physical_support_history': "Cote d'origine: 31244 (4)", 'production_type': 'Production propre', 'recording_place': 'Court (BE)', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives. Jura", 'content_summary': 'Mme Aubry a tenu conf?rence de presse ? Malleray: volont? de faire obstacle ? tout s?paratisme. Les femmes du GFFD veulent  renforcer leur pr?sence et leur action politique. M. Kobel parle des s?paratistes qui "depuis 30 ans s?ment la haine, la calomnie, la division, les pleurs, la violence, la souffrance... ". M. Martignoni souligne le fait que les jurassiens bernois sont nombreux ? avoir voulu rester dans le canton de Berne.', 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Live', 'modulation_type': 'Mono', 'work_duration': '00:08:52.833', 'work_duration_compl': 'Non', 'participants': [{'name': 'Aubry, Genevi?ve', 'function': 'Interview?/e', 'role': 'pr?sidente du GFFD'}, {'name': 'Kobel, Roger', 'function': 'Interview?/e', 'role': 'maire de Court, membre de Force d?mocratique'}, {'name': 'Martignoni, Werner', 'function': 'Interview?/e', 'role': 'pr?sident du gouvernement bernois'}], 'geographical_descriptors': ['Jura bernois', 'Court', 'Malleray'], 'person_descriptors': None, 'thematical_descriptors': ['question jurassienne'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Interview'], 'recording_dates': ['07/05/1977 - 07/05/1977'], 'first_broadcast_dates': None}
Skipping document 135/999 with OID {2A727724-0258-45FA-85E3-0BC2107DD09F} because it's missing its XML file!! (stt exists: False)
Skipping document 139/999 with OID {9D9436B1-5E1A-4E96-A565-B997AEBC0A6B} because it's missing its XML file!! (stt exists: False)
Skipping document 140/999 with OID {077256B4-44DD-4E5A-96EC-1C57C1C43BAE} because it's missing its XML file!! (stt exists: False)
Skipping document 142/999 with OID {90FBAD9E-92A2-4B4A-A87E-E47791172F9E} because it's missing its XML file!! (stt exists: False)
Skipping document 145/999 with OID {A8E72F10-4736-4F92-B78C-D806A25BD755} because it's missing its XML file!! (stt exists: False)
Skipping document 147/999 with OID {37C87FB9-BE87-42B4-AAFA-62957EC72FCD} because it's missing its XML file!! (stt exists: False)
Skipping document 148/999 with OID {E1832D03-5F52-42E7-9B5B-759242FEA9E2} because it's missing its XML file!! (stt exists: False)
Skipping document 149/999 with OID {B3E84CFA-3872-496A-B21D-D699D8CD3C2C} because it's missing its XML file!! (stt exists: False)
Skipping document 150/999 with OID {59187FB4-B49A-4B30-9B51-9075C880564A} because it's missing its XML file!! (stt exists: False)
Skipping document 151/999 with OID {8A46F6A9-E63F-4182-857F-F9C8612B5752} because it's missing its XML file!! (stt exists: False)
Skipping document 153/999 with OID {A34A974E-B0F8-4EE3-B579-A4AAE21665E8} because it's missing its XML file!! (stt exists: False)
Skipping document 155/999 with OID {E7DBA736-958B-4769-B3F6-E3F459970B84} because it's missing its XML file!! (stt exists: False)
The date for document with OID {FAC2ABE5-ED13-4DBB-B920-2F3225B0156F} was invalid (__/07/1973) - changed it to 01/07/1973
Skipping document 158/999 with OID {4ACC473A-E3B9-4628-B23F-3485F829486E} because it's missing its XML file!! (stt exists: False)
Skipping document 160/999 with OID {D83B591F-31CF-40B4-842F-17E5AC71B0B6} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {EEA03989-05EF-4920-93C3-C36F914260C0}. Trying to use the recording date. doc_dict: {'alias': 'j_midi', 'date_str': None, 'stt_filename': 'EEA03989-05EF-4920-93C3-C36F914260C0_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{EEA03989-05EF-4920-93C3-C36F914260C0}', 'stripped_OID': 'EEA03989-05EF-4920-93C3-C36F914260C0', 'login': '', 'broadcast_episode_title': 'Correspondance de Albert Tille ? Berne, avec les d?clarations de M. Gabuz, porte-parole de Nestl? et de M. Von Der Weid, du groupe de travail Tiers-Monde - RSR - SGEN', 'sequence': '1', 'broadcast_program_name': 'Journal de midi', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'albrecjo', 'modified_on': '01.10.2024 13:38:14', 'physical_support_history': "Cote d'origine: 30498.03. 3?me ?l?ment sur 13", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'A rechercher', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Affaire Nestl? Par Albert Tille (Journal de Midi)', 'workflow_status': 'A Contr?ler', 'assembly_status': 'Brut', 'live': None, 'modulation_type': 'Mono', 'work_duration': '00:04:49.614', 'work_duration_compl': 'Non', 'participants': [{'name': 'Tille, Albert', 'function': 'Commentateur/trice', 'role': 'collaborateur RSR'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': None, 'radio_channels': ['Premier programme'], 'subdomains': None, 'recording_dates': ['24/06/1976 - 24/06/1976'], 'first_broadcast_dates': None}
Skipping document 167/999 with OID {B58386C6-6F55-439A-8677-B157B6BD9E5E} because it's missing its XML file!! (stt exists: False)
Skipping document 168/999 with OID {85F32EAA-EF1A-4347-87D0-CC4390A78F07} because it's missing its XML file!! (stt exists: False)
Skipping document 169/999 with OID {C2C0A869-6EA5-43E6-B46A-85A576447418} because it's missing its XML file!! (stt exists: False)
Skipping document 174/999 with OID {AB13D4A2-5625-4735-ABB9-BD8EA588DA2F} because it's missing its XML file!! (stt exists: False)
Skipping document 179/999 with OID {FD35EB39-19DE-4936-8E76-20F994A80E7F} because it's missing its XML file!! (stt exists: False)
Skipping document 185/999 with OID {BFCEC441-E38F-460F-8A3F-F4A116CDC3C1} because it's missing its XML file!! (stt exists: False)
Skipping document 187/999 with OID {AB7A8A53-B6E0-4F6B-8467-C51EC6717572} because it's missing its XML file!! (stt exists: False)
Skipping document 191/999 with OID {E5C2D630-3697-4CBE-AB66-2A3D8CDF3939} because it's missing its XML file!! (stt exists: False)
Skipping document 201/999 with OID {0A48AB02-264B-4D8C-8D0A-B92F02CEAB26} because it's missing its XML file!! (stt exists: False)
Skipping document 203/999 with OID {44E71F5C-6D1A-43C6-A371-AB06FE062F95} because it's missing its XML file!! (stt exists: False)
Skipping document 206/999 with OID {8BFFE9D1-CC01-4EEC-8FC2-97F0D3F9101E} because it's missing its XML file!! (stt exists: False)
Skipping document 210/999 with OID {89226504-D88B-4D38-B046-972968BC46A0} because it's missing its XML file!! (stt exists: False)
Skipping document 212/999 with OID {79CB2B0B-509E-4F5C-98BD-31033A688109} because it's missing its XML file!! (stt exists: False)
Skipping document 213/999 with OID {0C762076-9F57-43FD-8996-AEDC8CA33C7D} because it's missing its XML file!! (stt exists: False)
Skipping document 214/999 with OID {D1A1F998-9425-4EAA-ABF6-D4CDB0E63136} because it's missing its XML file!! (stt exists: False)
Skipping document 231/999 with OID {02F3DD14-97B5-4AAD-A71F-C3B610C72637} because it's missing its XML file!! (stt exists: False)
Skipping document 234/999 with OID {3E43FAE6-7FE1-4ADC-98F3-03B9705B404D} because it's missing its XML file!! (stt exists: True)
Skipping document 235/999 with OID {A9E44AE4-AAB5-4636-89E6-CDDCDECD94C6} because it's missing its XML file!! (stt exists: False)
Skipping document 242/999 with OID {72E56C02-6DC2-42D2-8602-02BBFA778306} because it's missing its XML file!! (stt exists: True)
Skipping document 246/999 with OID {A9C0B2D1-B012-496D-A827-2AD6070E8851} because it's missing its XML file!! (stt exists: False)
Skipping document 247/999 with OID {187CEA87-BB85-41F4-BD45-B32746C07649} because it's missing its XML file!! (stt exists: False)

Skipping document 890/999 with OID {E064CF7C-9226-4CC9-B884-5B4CDE00A4DA} because it's missing its XML file!! (stt exists: True)
Skipping document 891/999 with OID {BAA1CC00-724C-49E6-8481-995A3E53C047} because it's missing its XML file!! (stt exists: False)
Skipping document 892/999 with OID {46D99342-1E13-4264-9E80-7AF10DA15F4C} because it's missing its XML file!! (stt exists: False)
Skipping document 893/999 with OID {DA3E9417-A605-41E2-B391-A629D957781F} because it's missing its XML file!! (stt exists: False)
Skipping document 894/999 with OID {83BABC6B-4B76-48BE-A57E-483FC258D971} because it's missing its XML file!! (stt exists: False)
Skipping document 897/999 with OID {1AAAA513-9E94-4B97-8142-D1A4637F080F} because it's missing its XML file!! (stt exists: False)
Skipping document 901/999 with OID {4C0DA78A-6F76-4E50-AD50-E5B297AEA6AB} because it's missing its XML file!! (stt exists: False)
Skipping document 904/999 with OID {A18CEB6C-7F57-4633-BE58-9C5C0EF4A7DC} because it's missing its XML file!! (stt exists: False)
Skipping document 905/999 with OID {030FA625-CB12-4728-8FAC-51A79631CB0D} because it's missing its XML file!! (stt exists: False)
Skipping document 910/999 with OID {6BDC1BC0-E2B5-41A1-930A-3B261F9818D6} because it's missing its XML file!! (stt exists: False)
Skipping document 914/999 with OID {DE4D10E1-F8FD-4554-86B4-B0636C7A874E} because it's missing its XML file!! (stt exists: False)
Skipping document 918/999 with OID {23DB7A4B-E285-49A6-BC53-07FAE6CC09B4} because it's missing its XML file!! (stt exists: False)
Skipping document 928/999 with OID {CF11DF90-93BB-49D8-8680-B2E88B702132} because it's missing its XML file!! (stt exists: False)
Skipping document 929/999 with OID {DC87F2CA-39F9-47F1-AD1C-9C6E742647E7} because it's missing its XML file!! (stt exists: False)
Skipping document 930/999 with OID {6C2AEBC8-DA93-412F-8691-5D6AB38A60F1} because it's missing its XML file!! (stt exists: False)
Skipping document 932/999 with OID {F61AA9D9-8ABE-4776-B9BF-80B7ACCAF04B} because it's missing its XML file!! (stt exists: False)
Skipping document 933/999 with OID {1DBDFB0F-0F01-42C5-8919-1863F34E1A8F} because it's missing its XML file!! (stt exists: False)
Skipping document 934/999 with OID {4ADFEE5A-D702-4C18-98D1-BE1CC7B0D8E4} because it's missing its XML file!! (stt exists: False)
Skipping document 937/999 with OID {9DC05B2E-CAF3-4434-A344-2644F7550E72} because it's missing its XML file!! (stt exists: True)
Skipping document 938/999 with OID {412695F0-3592-439C-AC1A-20821CC3661F} because it's missing its XML file!! (stt exists: True)
Skipping document 939/999 with OID {1187C8BF-8A70-4D9E-A0BC-7725335985E2} because it's missing its XML file!! (stt exists: True)
Skipping document 940/999 with OID {FBD54E33-E5C4-45D6-AA50-0719365288D5} because it's missing its XML file!! (stt exists: False)
Skipping document 941/999 with OID {E0DB236D-E834-4E27-B3E9-ECB3B5C3AFFD} because it's missing its XML file!! (stt exists: True)
Skipping document 952/999 with OID {53D6CCAD-F91E-48AC-AF72-4FDE27C5275A} because it's missing its XML file!! (stt exists: False)
Skipping document 953/999 with OID {CDD5976D-1C61-45B2-B862-FCBD899A6988} because it's missing its XML file!! (stt exists: False)
Skipping document 954/999 with OID {1570E808-CCC8-4BF6-87E5-7B0DA1EA41BF} because it's missing its XML file!! (stt exists: False)
Skipping document 955/999 with OID {438F5F0B-EBB5-4C1A-BFCE-9F0665B202F3} because it's missing its XML file!! (stt exists: False)
Skipping document 956/999 with OID {DCBFC47A-6FAA-4842-B017-0E16AE7EF01F} because it's missing its XML file!! (stt exists: False)
Skipping document 958/999 with OID {599EA919-49E0-4F48-9A2B-70CF84CBB505} because it's missing its XML file!! (stt exists: False)
Skipping document 959/999 with OID {C948EC84-5C3D-49B3-958D-F6406647E706} because it's missing its XML file!! (stt exists: False)
Skipping document 960/999 with OID {9CADC49A-8D53-4E10-B7F5-9C7171186991} because it's missing its XML file!! (stt exists: False)
Skipping document 961/999 with OID {D81C5C1D-D1A0-4DEF-8092-09526EC9CAEA} because it's missing its XML file!! (stt exists: False)
Skipping document 963/999 with OID {E3537293-0433-4E8C-9DE6-1D8EABEE316F} because it's missing its XML file!! (stt exists: False)
Skipping document 964/999 with OID {C60F0062-625B-4474-B68D-772675387185} because it's missing its XML file!! (stt exists: False)
Skipping document 965/999 with OID {19B08383-52B0-4D10-AC68-FC24DCE7E3D7} because it's missing its XML file!! (stt exists: False)
Skipping document 966/999 with OID {4A3A3495-AC9E-45EB-847C-E6C07016B413} because it's missing its XML file!! (stt exists: False)
Skipping document 969/999 with OID {94C96E0D-E9A6-45F0-8635-A5D1FE5C2D2A} because it's missing its XML file!! (stt exists: False)
Skipping document 973/999 with OID {2C507F2A-3AE1-4486-8759-CB18FCBCC417} because it's missing its XML file!! (stt exists: False)
Skipping document 974/999 with OID {8F9FC535-DC39-4768-83AE-B9D338D9B949} because it's missing its XML file!! (stt exists: False)
Skipping document 975/999 with OID {B9DFD345-2B2B-4588-AA1C-D5CFA126101D} because it's missing its XML file!! (stt exists: False)
Skipping document 976/999 with OID {B6376BB4-4629-4D22-8048-EA9A2368CAE5} because it's missing its XML file!! (stt exists: False)
Skipping document 980/999 with OID {3937E9AC-10DC-44DB-9E11-C57C33501A20} because it's missing its XML file!! (stt exists: False)
Skipping document 981/999 with OID {C37935E0-B4DF-4870-AAD3-D78DB52F68E7} because it's missing its XML file!! (stt exists: False)
Skipping document 982/999 with OID {7B81DC54-2642-4534-A1E2-29966B2866F5} because it's missing its XML file!! (stt exists: False)
Skipping document 983/999 with OID {3FB11785-EF05-4446-8DD2-F95BAB39E015} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {AD982611-12E5-4AE8-9051-51099282EEC6}. Trying to use the recording date. doc_dict: {'alias': 'j_midi', 'date_str': None, 'stt_filename': 'AD982611-12E5-4AE8-9051-51099282EEC6_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{AD982611-12E5-4AE8-9051-51099282EEC6}', 'stripped_OID': 'AD982611-12E5-4AE8-9051-51099282EEC6', 'login': '', 'broadcast_episode_title': "Extrait d'Interview de Guy B?art ? propos de ses chansons [Brut]", 'sequence': '1', 'broadcast_program_name': 'Journal de midi', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '31.05.2022 09:32:59', 'physical_support_history': "Cote d'origine: 24686 Pl. 02", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': 'Chansons fantaisie', 'content_summary': "!! Plusieurs phrases sont tronqu?es!! C'est le public qui choisit les chansons. La chanson doit arriver par hasard. Le public aime la na?vet? et la fra?cheur. (3:00) Une chanson de Guy B?art.", 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:05:36.918', 'work_duration_compl': 'Non', 'participants': [{'name': 'B?art, Guy', 'function': 'Interview?/e', 'role': 'auteur compositeur interpr?te'}], 'geographical_descriptors': None, 'person_descriptors': ['B?art, Guy'], 'thematical_descriptors': ["chanson d'auteur", 'chanson de vari?t?s', 'interpr?tation musicale'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Premier programme'], 'subdomains': ['Interview'], 'recording_dates': ['01/01/1970 - 01/01/1970'], 'first_broadcast_dates': None}
Skipping document 985/999 with OID {3866F91B-9FA9-4DDB-BFDF-7AE3016FDBCA} because it's missing its XML file!! (stt exists: False)
Skipping document 986/999 with OID {0DB61812-0E86-471D-B8B4-E895BB580185} because it's missing its XML file!! (stt exists: False)
Skipping document 987/999 with OID {8D038EFE-9118-4427-9D99-0E649559D20A} because it's missing its XML file!! (stt exists: False)
Skipping document 988/999 with OID {7B360391-1FC0-4038-97B0-650088CDEE45} because it's missing its XML file!! (stt exists: False)
Skipping document 989/999 with OID {D24B3A01-1D13-42FB-BDB0-B300AB76DAE5} because it's missing its XML file!! (stt exists: False)
Skipping document 990/999 with OID {913056C2-41A5-49B3-B62B-9EFE78F7E612} because it's missing its XML file!! (stt exists: False)
Skipping document 993/999 with OID {5BFF74AE-AB22-4E2C-A3EE-860CE9EF5BA7} because it's missing its XML file!! (stt exists: False)
Skipping document 995/999 with OID {2CAFC4A7-962E-4A30-BF6B-165BC23AF392} because it's missing its XML file!! (stt exists: False)
Skipping document 996/999 with OID {20DEF8BA-FB33-4A6D-A75A-5E00BB107E17} because it's missing its XML file!! (stt exists: False)
Skipping document 998/999 with OID {618C75E3-E5A0-4954-8668-9AFF7533C7D1} because it's missing its XML file!! (stt exists: False)
Skipping document 999/999 with OID {060A4F2C-0C66-4B8E-8DFC-768F48E81093} because it's missing its XML file!! (stt exists: False)
j_midi - returning 673 documents, 326 were skipped due to missing necessary info.

Starting extracting 999 documents for program j_midi
Skipping document 1/999 with OID {9BC159E4-7C6A-4905-8991-90B393C8DA8D} because it's missing its XML file!! (stt exists: False)
Skipping document 2/999 with OID {2020D8E2-7257-4665-978C-4F2F652095FC} because it's missing its XML file!! (stt exists: True)
Skipping document 3/999 with OID {2257FF8E-C5AB-47FF-BB38-93B8A8ED33E9} because it's missing its XML file!! (stt exists: False)
Skipping document 5/999 with OID {BE5FA96F-819A-457E-8261-1CDC311D1BC6} because it's missing its XML file!! (stt exists: False)
Skipping document 7/999 with OID {BE7FB452-D2D9-41DE-84F9-12AE9AE79EC7} because it's missing its XML file!! (stt exists: False)
Skipping document 11/999 with OID {582883E8-D512-4E50-9406-F9B8B2FA8BF8} because it's missing its XML file!! (stt exists: False)
Skipping document 14/999 with OID {25AC66F9-7B3E-400D-A74D-6FF9796E254E} because it's missing its XML file!! (stt exists: False)
Skipping document 19/999 with OID {B80AA3F1-B3F3-46F4-BF9F-644A688819E2} because it's missing its XML file!! (stt exists: False)
Skipping document 20/999 with OID {C4CF4358-7DD7-4FFB-80EF-C2BB2C03301B} because it's missing its XML file!! (stt exists: False)
Skipping document 21/999 with OID {F8702535-AF47-4D68-99DA-81021CD99B22} because it's missing its XML file!! (stt exists: False)
Skipping document 29/999 with OID {8182F1C3-38D6-424F-8A97-5B97E7415496} because it's missing its XML file!! (stt exists: False)
Skipping document 30/999 with OID {F9259880-1240-4FF8-BDEE-7B8596CEEDED} because it's missing its XML file!! (stt exists: False)
Skipping document 31/999 with OID {AC89C302-C31D-4632-AFC0-9EBC719CD30A} because it's missing its XML file!! (stt exists: False)
Skipping document 32/999 with OID {789B65DE-5EB6-4B08-81AC-182252F52CCF} because it's missing its XML file!! (stt exists: False)
Skipping document 33/999 with OID {AFF5ED67-2AE3-4A44-A219-E985087F0BC0} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {6794E4C7-D0E3-4A97-B597-56D836593959}. Trying to use the recording date. doc_dict: {'alias': 'j_midi', 'date_str': None, 'stt_filename': '6794E4C7-D0E3-4A97-B597-56D836593959_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{6794E4C7-D0E3-4A97-B597-56D836593959}', 'stripped_OID': '6794E4C7-D0E3-4A97-B597-56D836593959', 'login': '', 'broadcast_episode_title': "1. D?part du DC-3 de l'a?rodrome de la Bl?cherette : Commentaire de Manuel Girardin, collaborateur RSR. - 2. Vol en DC-3 au d?part de l'a?roport de Sion : Interview de B?at, le pilote du DC-3", 'sequence': '2', 'broadcast_program_name': 'Journal de midi', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'AQT (NumA)', 'modified_on': '21.05.2015 04:15:04', 'physical_support_history': "Cote d'origine : Bd 9599Resp. RSR : AQTLot : Caisse 3207", 'production_type': 'Production propre', 'recording_place': 'Lausanne (La Bl?cherette). Sion', 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Girardin, Manuel', 'function': 'Commentateur/trice', 'role': 'collaborateur/trice RSR'}, {'name': 'Inconnu', 'function': 'Interview?/e', 'role': 'B?at, pilote du DC-3'}, {'name': 'Girardin, Manuel', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['La Bl?cherette', 'Sion', 'Suisse'], 'person_descriptors': None, 'thematical_descriptors': ['aviation priv?e', 'avion civil', 'vol a?rien'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Reportage'], 'recording_dates': ['18/10/1986 - 19/10/1986'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {CA1E2B62-6D1A-4691-A32B-D7D9DF9A6403}. Trying to use the recording date. doc_dict: {'alias': 'j_midi', 'date_str': None, 'stt_filename': 'CA1E2B62-6D1A-4691-A32B-D7D9DF9A6403_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{CA1E2B62-6D1A-4691-A32B-D7D9DF9A6403}', 'stripped_OID': 'CA1E2B62-6D1A-4691-A32B-D7D9DF9A6403', 'login': '', 'broadcast_episode_title': "1. Sur fond de l'affaire des caisses noires, le Rassemblement jurassien a tenu conf?rence de presse lors de la traditionnelle F?te du peuple jurassien ? Del?mont. Il remet en cause la validit? des consultations populaires de 1975 et leurs cons?quences, en particulier ? Moutier. - 2. Force d?mocratique, mouvement anti-s?paratiste, tient son congr?s annuel ? P?ry : Interview d'Andr? Ory, vice-pr?sident de Force d?mocratique", 'sequence': '1', 'broadcast_program_name': 'Journal de midi', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'prongudo', 'modified_on': '23.08.2016 04:57:10', 'physical_support_history': "Cote d'origine: 34119 Plage 8", 'production_type': 'Production propre', 'recording_place': 'Del?mont. P?ry', 'rights_notes': None, 'rights_status': 'A rechercher', 'series_title': "Sauvegarde d'archives. Jura", 'content_summary': "1. Marcel Boillat, ancien chef du FLJ a envoy? une cassette depuis l'Espagne. Il met en garde la Berne cantonale et affrme qu'un deuxi?me FLJ pourrait voir le jour. Les dirigeants du Rassemblement jurassien savaient depuis longtemps que des malversations avaient eu lieu en faveur des anti-s?paratistes. - 2. Andr? Ory estime que le Jura bernois s'organise et que les institutions prennent doucement leur vitesse de croisi?re et la population est contente", 'workflow_status': 'Valid?', 'assembly_status': 'Pr?t', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:04:55.564', 'work_duration_compl': 'Non', 'participants': [{'name': 'Boillat, Marcel', 'function': "Auteur d'une d?claration", 'role': 'ancien chef du FLJ, exil? en Espagne'}, {'name': 'Crevoisier, Jean-Claude', 'function': "Auteur d'une d?claration", 'role': 'vice-pr?sident du Rassemblement jurassien'}, {'name': 'B?guelin, Roland', 'function': "Auteur d'une d?claration", 'role': 'secr?taire g?n?ral du Rassemblement jurassien'}, {'name': 'Ross?, Jean-Fran?ois', 'function': 'Correspondant/e', 'role': 'collaborateur RSR'}, {'name': 'Ory, Andr?', 'function': 'Interview?/e', 'role': 'vice-pr?sident de Force D?mocratique'}, {'name': 'Bernasconi, Roberto', 'function': 'Intervieweur/euse', 'role': 'correspondant RSR dans le Jura Bernois'}, {'name': 'Luyet, Pierre', 'function': 'Pr?sentateur/trice', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Jura (canton)', 'Jura bernois'], 'person_descriptors': ['Rassemblement jurassien', 'Force D?mocratique'], 'thematical_descriptors': ['question jurassienne'], 'rights_usage_possibilities': None, 'radio_channels': ['La Premi?re'], 'subdomains': ['Interview', 'D?claration'], 'recording_dates': ['08/09/1985 - 08/09/1985'], 'first_broadcast_dates': None}
Skipping document 63/999 with OID {F2367F2A-C079-48DB-8D56-8E2DBE16D8C1} because it's missing its XML file!! (stt exists: True)
Skipping document 64/999 with OID {9C21B142-B381-4437-9413-25C2CCF0E152} because it's missing its XML file!! (stt exists: False)
Skipping document 67/999 with OID {D9FB07AA-B611-4F1C-8EBD-E12CCD1C62A2} because it's missing its XML file!! (stt exists: False)
Skipping document 71/999 with OID {2B41E4B0-39E9-43A6-9602-29094F32B57D} because it's missing its XML file!! (stt exists: False)
Skipping document 75/999 with OID {6DCA7665-1E91-4AFF-A2EC-0AAE5DD2A84F} because it's missing its XML file!! (stt exists: False)
Skipping document 83/999 with OID {7CCE826C-FEA9-497A-869C-6A202B3F2194} because it's missing its XML file!! (stt exists: False)
Skipping document 86/999 with OID {E06CC14A-9F8C-4F43-8149-5F635028D17D} because it's missing its XML file!! (stt exists: True)
Skipping document 89/999 with OID {D78F325F-790D-44D6-A25B-945012F3B896} because it's missing its XML file!! (stt exists: False)
Skipping document 92/999 with OID {B63D3729-CE38-47A3-93FB-EFC6F8868E34} because it's missing its XML file!! (stt exists: False)
Skipping document 93/999 with OID {1993874D-243C-4FFA-9B24-015CDE78E8D4} because it's missing its XML file!! (stt exists: False)
Skipping document 96/999 with OID {4B191DD6-3C2C-4021-A1B5-B4DF0804977A} because it's missing its XML file!! (stt exists: False)
Skipping document 104/999 with OID {CB35F1DE-4766-4A3F-8D24-B7915DF759BE} because it's missing its XML file!! (stt exists: False)
Skipping document 105/999 with OID {3A1F5EB1-B79A-42CF-9441-62927EF8EAE4} because it's missing its XML file!! (stt exists: False)
Skipping document 108/999 with OID {F5E4F424-E996-4216-9820-1FA871F44723} because it's missing its XML file!! (stt exists: False)
Skipping document 109/999 with OID {DA145775-A951-4849-9B5A-266CF7ED638A} because it's missing its XML file!! (stt exists: False)
Skipping document 113/999 with OID {25C0BA43-E05B-4347-980A-02C17FA3E158} because it's missing its XML file!! (stt exists: False)
Skipping document 114/999 with OID {096CE42B-9718-4C4D-B9F9-A7CCB7177E94} because it's missing its XML file!! (stt exists: False)
Skipping document 118/999 with OID {31A5628E-042D-471F-94A9-1E38993DFCE6} because it's missing its XML file!! (stt exists: False)
Skipping document 122/999 with OID {8D8E43E4-72FE-47B2-BCB0-8BA0A99D19F7} because it's missing its XML file!! (stt exists: False)
Skipping document 126/999 with OID {E60417A8-A824-4A81-81C9-B07217994D55} because it's missing its XML file!! (stt exists: False)
Skipping document 127/999 with OID {899FA96B-2A30-4BD9-8CA0-D5325900F0E8} because it's missing its XML file!! (stt exists: False)
Skipping document 128/999 with OID {190AE110-B9D9-46F9-9687-67A6996E462F} because it's missing its XML file!! (stt exists: False)
Skipping document 129/999 with OID {3D30608A-0907-4EFA-8EE6-6E747E1BA759} because it's missing its XML file!! (stt exists: False)
Skipping document 142/999 with OID {251A2A43-E7AD-4A87-8280-4D3498347C39} because it's missing its XML file!! (stt exists: False)
Skipping document 146/999 with OID {9022A973-6317-4484-9460-E90F1E7847E6} because it's missing its XML file!! (stt exists: False)
Skipping document 148/999 with OID {4CFED08C-9EC9-4159-B8E4-6D0E4EC9DB4C} because it's missing its XML file!! (stt exists: False)
Skipping document 149/999 with OID {AAEEE720-79EE-48CC-80E5-FDD5DAE356C5} because it's missing its XML file!! (stt exists: False)
Skipping document 151/999 with OID {A5CF3F1E-A05B-49B8-86D9-AA5F215F8A67} because it's missing its XML file!! (stt exists: False)
Skipping document 152/999 with OID {64E03A36-B94C-4558-9085-A678E52A667F} because it's missing its XML file!! (stt exists: False)

Skipping document 979/999 with OID {32C26A44-6293-499A-A2D3-801311F060B1} because it's missing its XML file!! (stt exists: False)
Skipping document 980/999 with OID {9D0B1328-C03F-4D9E-80FD-99382E4E2277} because it's missing its XML file!! (stt exists: False)
Skipping document 981/999 with OID {E09FCAF3-22C7-473B-B0E7-DDA0F5580EA1} because it's missing its XML file!! (stt exists: False)
Skipping document 982/999 with OID {1FDA1936-E5DC-4EB1-9E63-DFB0F68B7CB7} because it's missing its XML file!! (stt exists: False)
Skipping document 983/999 with OID {32D64EFA-DB69-4FD5-B0BE-E8A88E68C68F} because it's missing its XML file!! (stt exists: False)
Skipping document 984/999 with OID {061074B8-2D8E-483E-8805-FD190D49EF28} because it's missing its XML file!! (stt exists: False)
Skipping document 985/999 with OID {1D1235E5-240D-41BB-BAD3-261AF96ADA8F} because it's missing its XML file!! (stt exists: False)
Skipping document 986/999 with OID {6178E64F-CADD-415F-80F1-13E740DD7D9D} because it's missing its XML file!! (stt exists: False)
Skipping document 987/999 with OID {DAC49217-DA45-4D85-9F03-0FA0858C1AD9} because it's missing its XML file!! (stt exists: False)
Skipping document 988/999 with OID {72C717BB-4FE7-4C2F-B3D8-038B5B5B0E68} because it's missing its XML file!! (stt exists: False)
Skipping document 989/999 with OID {421BB639-0EFE-4B8C-BD9C-57005B21A9D2} because it's missing its XML file!! (stt exists: False)
Skipping document 990/999 with OID {4D7CDFD4-BB13-41B4-959C-35D4673C0BD9} because it's missing its XML file!! (stt exists: False)
Skipping document 991/999 with OID {D306BD6F-745C-4EFE-80C4-DF125EBFE036} because it's missing its XML file!! (stt exists: False)
Skipping document 992/999 with OID {DD9A06AF-47B8-472A-8A82-77BCA77BD24E} because it's missing its XML file!! (stt exists: False)
Skipping document 993/999 with OID {181981D5-9DDA-43A6-AD24-6F08359505E3} because it's missing its XML file!! (stt exists: False)
Skipping document 994/999 with OID {CAE02953-3950-4862-AFCD-8DB79752D1E2} because it's missing its XML file!! (stt exists: False)
Skipping document 996/999 with OID {E87FA0F2-FCBA-4441-A75E-AB530AA3C26F} because it's missing its XML file!! (stt exists: False)
Skipping document 997/999 with OID {8FFE09D3-0A19-498B-80F3-94B48FE11514} because it's missing its XML file!! (stt exists: False)
Skipping document 998/999 with OID {BE194D08-5F74-4445-A9DE-B336682D627E} because it's missing its XML file!! (stt exists: False)
Skipping document 999/999 with OID {D3743747-6D9E-41B2-A93E-AAB912B5BF4C} because it's missing its XML file!! (stt exists: False)
j_midi - returning 656 documents, 343 were skipped due to missing necessary info.

Starting extracting 999 documents for program j_midi
Skipping document 1/999 with OID {F59132C4-058C-445B-B3DF-1C7CF41D7D0A} because it's missing its XML file!! (stt exists: False)
Skipping document 2/999 with OID {25B84815-3DAB-45E0-85C4-13AA4D15C989} because it's missing its XML file!! (stt exists: False)
Skipping document 7/999 with OID {0E17D8D9-8C7E-4F3A-9B9E-6FEE77E4A844} because it's missing its XML file!! (stt exists: False)
Skipping document 9/999 with OID {5B644738-2460-43EF-95C2-E595CED5CC83} because it's missing its XML file!! (stt exists: False)
Skipping document 11/999 with OID {4974C0F1-3A76-40A8-A3AF-F8FFF5A61D21} because it's missing its XML file!! (stt exists: True)
Skipping document 15/999 with OID {0C7EDA86-C60B-4E37-A21D-2CD42FED100B} because it's missing its XML file!! (stt exists: False)
Skipping document 20/999 with OID {F54CFB75-435C-4E12-B708-F0DE6459F18D} because it's missing its XML file!! (stt exists: False)
Skipping document 27/999 with OID {9A6E9FF3-9D16-46C8-A1CF-DC0BBF84A929} because it's missing its XML file!! (stt exists: False)
Skipping document 29/999 with OID {D64B5E3A-2B75-4F53-B4E0-359B8DD2AC66} because it's missing its XML file!! (stt exists: False)
Skipping document 30/999 with OID {2779CF1B-E398-4DED-87D1-7EDAFA59C465} because it's missing its XML file!! (stt exists: True)
Skipping document 38/999 with OID {2FA91D6E-AE15-4FB8-9C34-04B16D64E433} because it's missing its XML file!! (stt exists: False)
Skipping document 41/999 with OID {A46A7BD0-3623-465C-87FB-CCDA9CF75BD6} because it's missing its XML file!! (stt exists: False)
Skipping document 43/999 with OID {417D2B45-88BF-407A-8EA3-C7038BA353B5} because it's missing its XML file!! (stt exists: False)
Skipping document 46/999 with OID {C53A783C-B13F-4ECC-8BD4-7370BC3D0D19} because it's missing its XML file!! (stt exists: False)
Skipping document 50/999 with OID {3F5C275F-0736-4050-A521-E9FBC9DCB662} because it's missing its XML file!! (stt exists: False)
Skipping document 51/999 with OID {C59A7396-08F5-4E50-918C-9C65100AF47D} because it's missing its XML file!! (stt exists: False)
Skipping document 52/999 with OID {15DE6FD5-3A4B-4A16-8308-758EE1B430A8} because it's missing its XML file!! (stt exists: True)
Skipping document 53/999 with OID {0529CB52-88AB-49C8-B4BE-96049DC80B15} because it's missing its XML file!! (stt exists: False)
Skipping document 57/999 with OID {1A2D9F11-BB41-4CC7-8836-48FD974102A7} because it's missing its XML file!! (stt exists: False)
Skipping document 58/999 with OID {72D588D7-2038-4E97-943D-F5E88F9E1EDB} because it's missing its XML file!! (stt exists: False)
Skipping document 59/999 with OID {247CEFE8-56D0-446F-B8A2-94A0005C74DA} because it's missing its XML file!! (stt exists: False)
Skipping document 60/999 with OID {A2502961-8A81-4694-8C25-F8E45E14CDD5} because it's missing its XML file!! (stt exists: True)
Skipping document 64/999 with OID {18FA0E86-E66E-43BC-B6E9-D5F45D640B12} because it's missing its XML file!! (stt exists: False)
Skipping document 65/999 with OID {A26071BF-BB86-4873-A9E4-0CC051920F41} because it's missing its XML file!! (stt exists: False)
Skipping document 66/999 with OID {DD548C40-DD84-4A7A-BB6F-09A3EC1A9708} because it's missing its XML file!! (stt exists: False)
Skipping document 69/999 with OID {6EA08507-DC34-40C5-8843-CD277CC0860B} because it's missing its XML file!! (stt exists: False)
Skipping document 72/999 with OID {D2C7641D-E835-4A4C-9273-701B5EC90656} because it's missing its XML file!! (stt exists: False)
Skipping document 75/999 with OID {5F334D26-5A49-4F45-98C4-B3F4AA55073E} because it's missing its XML file!! (stt exists: False)
Skipping document 76/999 with OID {A8F8DA95-8BCE-42E1-BE15-CC21725DD276} because it's missing its XML file!! (stt exists: False)
Skipping document 78/999 with OID {9944CA65-5E0A-432C-AA03-5E57C904BBAE} because it's missing its XML file!! (stt exists: False)
Skipping document 81/999 with OID {57FFAFB9-8127-45CB-A5A4-047D524BB544} because it's missing its XML file!! (stt exists: False)
Skipping document 84/999 with OID {EE6AB789-C480-4B4F-9F4F-DC402A79FA36} because it's missing its XML file!! (stt exists: False)
Skipping document 85/999 with OID {1EEB08FA-7962-4564-9FD4-EC21E975CF8B} because it's missing its XML file!! (stt exists: False)
Skipping document 86/999 with OID {317AB7C2-AD2A-4D57-913C-82FBF71F8CA3} because it's missing its XML file!! (stt exists: False)
Skipping document 87/999 with OID {5FF104FA-7DD4-4156-A017-B2BDDEF0A214} because it's missing its XML file!! (stt exists: False)
Skipping document 88/999 with OID {C05AC0CC-080D-4208-BC30-775CB6502B81} because it's missing its XML file!! (stt exists: False)
Skipping document 93/999 with OID {9AD5399A-ADCD-40E4-AB4C-A65B60C15F55} because it's missing its XML file!! (stt exists: False)
Skipping document 94/999 with OID {7C797F5B-E7E3-4569-9FA5-3ACB20E62150} because it's missing its XML file!! (stt exists: False)
Skipping document 96/999 with OID {1A5D177E-B1FD-41F8-BF66-D85A1CD4CA85} because it's missing its XML file!! (stt exists: False)
Skipping document 98/999 with OID {BEEE6273-145E-48E1-B8D7-9B5461FF44DE} because it's missing its XML file!! (stt exists: False)
Skipping document 99/999 with OID {F01BE595-1080-4D09-A5CB-20E09AD6490E} because it's missing its XML file!! (stt exists: True)
Skipping document 101/999 with OID {EFFC6A56-5078-4FAC-B986-8F63898B1842} because it's missing its XML file!! (stt exists: False)
Skipping document 107/999 with OID {8A0317C8-50EE-4A97-ADB1-4B714A0DCB88} because it's missing its XML file!! (stt exists: False)
Skipping document 108/999 with OID {B3AF7975-CDDB-4D11-B28D-76429A4704D6} because it's missing its XML file!! (stt exists: False)
Skipping document 113/999 with OID {35013AAD-48BA-4986-AE31-874C2BD2EB3A} because it's missing its XML file!! (stt exists: False)
Skipping document 119/999 with OID {4C4C6351-DAB5-44CC-85E7-CAAE7C918C10} because it's missing its XML file!! (stt exists: False)
Skipping document 120/999 with OID {71AB08BE-7028-4E0B-84B4-579D68C4729A} because it's missing its XML file!! (stt exists: False)
Skipping document 121/999 with OID {5794D872-6FDF-47B8-95A0-D217CEDB1EAB} because it's missing its XML file!! (stt exists: False)
Skipping document 122/999 with OID {67DB8198-3DA9-4FA7-88B3-7088DEE15DE7} because it's missing its XML file!! (stt exists: False)
Skipping document 123/999 with OID {A68CEE62-A0C9-4CDF-888F-D2B6831BD543} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {F00E0457-0347-49BC-BCA5-387133CCEC79}. Trying to use the recording date. doc_dict: {'alias': 'j_midi', 'date_str': None, 'stt_filename': 'F00E0457-0347-49BC-BCA5-387133CCEC79_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{F00E0457-0347-49BC-BCA5-387133CCEC79}', 'stripped_OID': 'F00E0457-0347-49BC-BCA5-387133CCEC79', 'login': '', 'broadcast_episode_title': "Le gouvernement jurassien s'empare de l'affaire dite des caisses noires, d?nonc?e par le rapport Hafner : Commentaire de Denis Moine, correspondant RSR Jura et interview de Pierre Boillat, ministre jurassien, chef du D?partement de la justice et de l'int?rieur", 'sequence': '1', 'broadcast_program_name': 'Journal de midi', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'prongudo', 'modified_on': '22.05.2015 10:52:17', 'physical_support_history': "Cote d'origine: 33216 Plage 12", 'production_type': 'Production propre', 'recording_place': 'Del?mont (studio RSR)', 'rights_notes': None, 'rights_status': 'A rechercher', 'series_title': "Midi premi?re. Sauvegarde d'archives. Jura", 'content_summary': "Le gouvernement jurassien in corpore a tenu une conf?rence de presse ? Del?mont. Pierre Boillat : Le pr?judice n'est pas d'abord financier, mais politique, avec l'?clatement du Jura. D?j? durant les pl?biscites, les s?paratistes avaient protest? contre certaines pratiques et entraves ? la libert? d?mocratique durant la proc?dure pl?biscitaire. Le gouvernement jurassien a ?crit au Conseil f?d?ral. Cette affaire montre qu'il y a eu tripatouillage. Le gouvernement jurassien demande au Conseil f?d?ral de faire des enqu?tes suppl?ementaires pour ?tablir l'ensemble des malversations et manipulations. Le pl?biscite du 23 juin 1974 a ?t? vici?, mais sans que le r?sultat doive ?tre remis en cause. L'affaire sera port?e devant le Tribunal f?d?ral. Denis Moine : Les Jurassiens ont le sentiment d'avoir ?t? tromp?es, dans les pl?biscites, comme dans le partage des biens", 'workflow_status': 'Valid?', 'assembly_status': 'Pr?t', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:14:03.896', 'work_duration_compl': 'Non', 'participants': [{'name': 'Moine, Denis', 'function': 'Commentateur/trice', 'role': 'correspondant RSR Jura'}, {'name': 'Boillat, Pierre (homme politique jurassien)', 'function': 'Interview?/e', 'role': 'ministre jurassien: chef du D?partement de la justice'}, {'name': 'Froidevaux, Claude', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}, {'name': 'Moine, Denis', 'function': 'Intervieweur/euse', 'role': 'correspondant RSR Jura'}, {'name': 'Inconnu', 'function': 'Pr?sentateur/trice', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Jura (canton)', 'Jura bernois', 'Berne (canton)'], 'person_descriptors': None, 'thematical_descriptors': ['question jurassienne', 'votation'], 'rights_usage_possibilities': None, 'radio_channels': ['La Premi?re'], 'subdomains': ['Interview'], 'recording_dates': ['15/11/1985 - 15/11/1985'], 'first_broadcast_dates': None}
Skipping document 128/999 with OID {4914C231-4F70-4C36-B09F-46BF2801B5F9} because it's missing its XML file!! (stt exists: False)
Skipping document 141/999 with OID {659D9C0C-ADA8-47ED-BF2B-C2F91C59DDA7} because it's missing its XML file!! (stt exists: False)
Skipping document 143/999 with OID {84BF89EB-0987-4C0E-8BF0-F6BA2E95F0F6} because it's missing its XML file!! (stt exists: False)
Skipping document 144/999 with OID {B62E87F9-64E0-4AE9-AF00-B25054BEAC67} because it's missing its XML file!! (stt exists: False)
Skipping document 152/999 with OID {3C3D16A9-4BBD-47BE-AD65-B77FB8D09315} because it's missing its XML file!! (stt exists: False)
Skipping document 156/999 with OID {158C7D49-E597-431A-A045-3B1E2D6E56A4} because it's missing its XML file!! (stt exists: False)
Skipping document 157/999 with OID {5F8BED6A-5C8D-47CA-B926-C2F34B943CC9} because it's missing its XML file!! (stt exists: False)
Skipping document 161/999 with OID {B086307D-1936-41F6-8A48-C4C9F7A8B458} because it's missing its XML file!! (stt exists: True)
Skipping document 165/999 with OID {FBBCF7CC-3FC6-4571-A27C-E61626D17A87} because it's missing its XML file!! (stt exists: False)
Skipping document 167/999 with OID {9D67BF4C-6D1B-429F-A990-87B39DF14E15} because it's missing its XML file!! (stt exists: False)
Skipping document 171/999 with OID {459EF969-9E75-44B6-B94A-8C48906C7A14} because it's missing its XML file!! (stt exists: False)
Skipping document 173/999 with OID {3962CDCC-0BCA-4ECB-9EB4-E4A9DF6D6E2C} because it's missing its XML file!! (stt exists: False)
Skipping document 178/999 with OID {DCC7795A-008C-4520-9F58-36F4C9F56098} because it's missing its XML file!! (stt exists: False)
Skipping document 198/999 with OID {C316AC3F-4B76-44B1-B42E-8F1421F8BA68} because it's missing its XML file!! (stt exists: False)
Skipping document 200/999 with OID {F8BFF71A-AE2C-4D7B-A395-E1DED6C93D8A} because it's missing its XML file!! (stt exists: True)
Skipping document 205/999 with OID {0C11B1CA-646B-479A-99C1-E2C4CEC62606} because it's missing its XML file!! (stt exists: False)
Skipping document 211/999 with OID {C2AB9016-7B18-4CB5-99E7-8097F442684E} because it's missing its XML file!! (stt exists: False)
Skipping document 212/999 with OID {B8571D7F-6E18-400E-AE0B-7856F9650808} because it's missing its XML file!! (stt exists: False)
Skipping document 213/999 with OID {770F5068-5662-415F-AA12-736E0D85BED5} because it's missing its XML file!! (stt exists: False)
Skipping document 216/999 with OID {4162CC77-94DF-4049-9457-3D4CB8123E3A} because it's missing its XML file!! (stt exists: False)
Skipping document 217/999 with OID {164BEC6E-6EE4-41A4-A6EF-B9045F00E89F} because it's missing its XML file!! (stt exists: False)
Skipping document 220/999 with OID {8643763E-3C47-4E1C-8821-C1BB1045C574} because it's missing its XML file!! (stt exists: False)
Skipping document 222/999 with OID {D23F1A79-B647-4EC4-BF5E-CAEE768ECCDD} because it's missing its XML file!! (stt exists: False)
Skipping document 224/999 with OID {9FE264D0-9199-45D0-B3CE-56D5A6973F5F} because it's missing its XML file!! (stt exists: False)
Skipping document 227/999 with OID {ED16E4AC-FE63-419E-AC22-C3E1F0133C9E} because it's missing its XML file!! (stt exists: False)
Skipping document 228/999 with OID {5455C2CB-9486-4E23-B2C5-21AC156E7416} because it's missing its XML file!! (stt exists: False)
Skipping document 230/999 with OID {C190A58D-DB12-4233-BC92-1F6D6BD14F6B} because it's missing its XML file!! (stt exists: False)
Skipping document 235/999 with OID {31B00E92-55B3-491B-B703-BAE259BCC311} because it's missing its XML file!! (stt exists: False)
Skipping document 236/999 with OID {82B72E5C-9240-425F-96CC-3D61B8282794} because it's missing its XML file!! (stt exists: False)
Skipping document 239/999 with OID {0A027AF9-C31C-47CA-9858-D0833432C5B5} because it's missing its XML file!! (stt exists: False)
Skipping document 245/999 with OID {B4CD565D-B3C1-4F70-A952-740C261F04B4} because it's missing its XML file!! (stt exists: False)
Skipping document 246/999 with OID {930D3E0A-87FC-46F7-B990-46DC7BC4FFB8} because it's missing its XML file!! (stt exists: False)
Skipping document 252/999 with OID {E9D0B784-D24E-4812-A26B-7A8B8E191AEC} because it's missing its XML file!! (stt exists: False)
Skipping document 256/999 with OID {C5FFAFAD-8A91-41DD-B489-AB93D8E44879} because it's missing its XML file!! (stt exists: False)
Skipping document 260/999 with OID {56930F92-0EAD-4562-9248-66DBDEE1558F} because it's missing its XML file!! (stt exists: False)
Skipping document 263/999 with OID {2234BB9D-88FE-4134-99CD-B9F49C7EE40B} because it's missing its XML file!! (stt exists: False)
Skipping document 270/999 with OID {DCDA89E0-4B12-4325-8853-0E6606DD7488} because it's missing its XML file!! (stt exists: False)
Skipping document 271/999 with OID {C38D8D93-C070-4967-B9F1-F828CB82F619} because it's missing its XML file!! (stt exists: False)
Skipping document 276/999 with OID {D9ED0DAA-7BE4-4E15-9253-17B0F486649F} because it's missing its XML file!! (stt exists: False)
Skipping document 277/999 with OID {5A20C4BE-F3C1-4029-B8ED-746835D64259} because it's missing its XML file!! (stt exists: False)
Skipping document 281/999 with OID {F4384AC0-C54D-448F-9F9A-EFCA787B854F} because it's missing its XML file!! (stt exists: True)
Skipping document 282/999 with OID {5AA1398E-6F37-468A-9771-7B2F6433F2A2} because it's missing its XML file!! (stt exists: False)
Skipping document 295/999 with OID {2483B0CE-5D60-4C25-9AB7-FA6530F16365} because it's missing its XML file!! (stt exists: False)
Skipping document 296/999 with OID {756AEC1F-6068-4E04-8084-8C5109DEC859} because it's missing its XML file!! (stt exists: False)
Skipping document 300/999 with OID {DB01A229-5D45-45B6-A78B-FA641EACCD6E} because it's missing its XML file!! (stt exists: False)
Skipping document 302/999 with OID {D697DC16-F96A-4DA9-86AF-A6F9D9A393BC} because it's missing its XML file!! (stt exists: False)
Skipping document 306/999 with OID {6EB134D2-D44B-431F-9E26-09E64FFB211D} because it's missing its XML file!! (stt exists: False)
Skipping document 307/999 with OID {62342592-F4FC-4A6B-87A7-D117DF514BF6} because it's missing its XML file!! (stt exists: False)
Skipping document 311/999 with OID {C85205D3-6118-47BD-9C2F-D9DFAD383E57} because it's missing its XML file!! (stt exists: False)
Skipping document 312/999 with OID {39096315-0D4A-44BD-9AFF-78430489735F} because it's missing its XML file!! (stt exists: False)
Skipping document 313/999 with OID {3EDDB227-15A2-478B-85E6-FDD59CCE961C} because it's missing its XML file!! (stt exists: False)
Skipping document 322/999 with OID {DA150A41-C6BA-436F-B466-B63996263DD0} because it's missing its audio MP3 file!!
Skipping document 325/999 with OID {D43DCA42-DDA8-436A-9301-983F3622932B} because it's missing its XML file!! (stt exists: False)
Skipping document 328/999 with OID {CC1E7447-1E41-46E0-8361-0BDB61FC0380} because it's missing its XML file!! (stt exists: False)
Skipping document 330/999 with OID {97EC581A-AC47-4DB7-A80A-CFF76690FF1F} because it's missing its XML file!! (stt exists: False)
Skipping document 337/999 with OID {0391AACF-C1FC-45A2-AF40-68E7BDF00FE2} because it's missing its XML file!! (stt exists: False)
Skipping document 340/999 with OID {BD5F0888-F169-438A-8171-048066BAD4A8} because it's missing its XML file!! (stt exists: False)
Skipping document 345/999 with OID {799A44C5-C74C-4953-9658-E88D9DE7D1C1} because it's missing its XML file!! (stt exists: False)
Skipping document 349/999 with OID {A3978B93-E462-48C0-BA6B-5C59F905794F} because it's missing its XML file!! (stt exists: False)

Skipping document 977/999 with OID {313D6B4B-CFE0-4680-9017-CF1EB9EEDA7E} because it's missing its XML file!! (stt exists: False)
Skipping document 979/999 with OID {49E96F58-0BC0-476A-A950-5CECE9D2F49A} because it's missing its XML file!! (stt exists: True)
Skipping document 984/999 with OID {5A8DECF9-6F99-49E4-8F05-FA589492535C} because it's missing its XML file!! (stt exists: False)
Skipping document 988/999 with OID {091BA2DA-9708-43D2-9E2E-6DA7D6757845} because it's missing its XML file!! (stt exists: False)
Skipping document 993/999 with OID {B0E4345E-75AC-4F08-B0DA-892D3608E4D0} because it's missing its XML file!! (stt exists: True)
Skipping document 994/999 with OID {47B01321-E8E0-42F9-9C44-90E6526E470A} because it's missing its XML file!! (stt exists: False)
Skipping document 995/999 with OID {FA9B2E71-5BE6-4791-A6E4-6895E1D0ABCF} because it's missing its XML file!! (stt exists: True)
Skipping document 996/999 with OID {5622D1D2-7778-47B0-8CFC-12162B3E910A} because it's missing its XML file!! (stt exists: False)
j_midi - returning 680 documents, 319 were skipped due to missing necessary info.

Starting extracting 999 documents for program j_midi
Skipping document 1/999 with OID {3AEE9A0A-6873-40E1-AE57-DC08FBF6EBCF} because it's missing its XML file!! (stt exists: False)
Skipping document 2/999 with OID {45BAC5CF-F8D9-41EF-B652-2C50905560C9} because it's missing its XML file!! (stt exists: False)
Skipping document 3/999 with OID {3E0A0E24-0E80-4730-BBD3-5EDFC6EC2148} because it's missing its XML file!! (stt exists: False)
Skipping document 4/999 with OID {CDA07800-6B2C-4716-918E-3D87F4183FC6} because it's missing its XML file!! (stt exists: False)
Skipping document 6/999 with OID {8961FC91-8148-4C06-B4F7-8B4C6D0A5E3F} because it's missing its XML file!! (stt exists: False)
Skipping document 7/999 with OID {18DAAE03-AD9C-4D70-B4B9-54ED18E5AC42} because it's missing its XML file!! (stt exists: False)
Skipping document 9/999 with OID {F2143621-B347-4A6F-9528-87D08A96EE8E} because it's missing its XML file!! (stt exists: False)
Skipping document 10/999 with OID {6A351AC5-0DC6-4FE0-84B6-28030C37B5E4} because it's missing its XML file!! (stt exists: False)
Skipping document 13/999 with OID {7B906932-960E-4502-9480-6967DB333F17} because it's missing its XML file!! (stt exists: False)
Skipping document 16/999 with OID {1C0E8B95-DE92-44F0-BE2C-4F5764F1CF9D} because it's missing its XML file!! (stt exists: False)
Skipping document 17/999 with OID {25042292-8640-4064-9B7B-80799467938C} because it's missing its XML file!! (stt exists: False)
Skipping document 18/999 with OID {58DCBDA9-DB24-426A-89B1-7F08E7C814E2} because it's missing its XML file!! (stt exists: False)
Skipping document 19/999 with OID {98345E56-1B49-4746-B94C-2E50AA6562DA} because it's missing its XML file!! (stt exists: False)
Skipping document 21/999 with OID {68663676-52DC-44B6-82EA-7759F27F3BE4} because it's missing its XML file!! (stt exists: False)
Skipping document 22/999 with OID {5E08CF5B-41CA-47A3-A4F4-690F00F74DF5} because it's missing its XML file!! (stt exists: False)
Skipping document 23/999 with OID {8B159B1A-3711-424C-874F-278C793DB7C0} because it's missing its XML file!! (stt exists: False)
Skipping document 24/999 with OID {998EFD02-7986-4275-8B16-05EADCA00A0E} because it's missing its XML file!! (stt exists: False)
Skipping document 25/999 with OID {2B661ABA-04AF-44F5-B12C-729D4956AE64} because it's missing its XML file!! (stt exists: False)
Skipping document 26/999 with OID {2FBCBA07-C120-4428-95E3-CF7206AA5800} because it's missing its XML file!! (stt exists: False)
Skipping document 32/999 with OID {0C8C4093-DE96-481D-BEA1-9131403F2D65} because it's missing its XML file!! (stt exists: False)
Skipping document 34/999 with OID {B5A02559-3F3C-481C-9236-D5F0DD7B7017} because it's missing its XML file!! (stt exists: False)
Skipping document 37/999 with OID {D3469084-22BF-4C64-A154-FD7AD25A2CD4} because it's missing its XML file!! (stt exists: False)
Skipping document 38/999 with OID {32E83B80-47EB-41A4-8C65-3213BF8F96FC} because it's missing its XML file!! (stt exists: False)
Skipping document 44/999 with OID {0A72B07A-A1C7-4955-823E-AD5F5FA09523} because it's missing its XML file!! (stt exists: False)
Skipping document 45/999 with OID {D9CD4AA1-C1B6-4231-86A3-3EC0BB9C1542} because it's missing its XML file!! (stt exists: False)
Skipping document 48/999 with OID {F6D6CEDE-028E-4886-B45C-5929ECDAC27E} because it's missing its XML file!! (stt exists: False)
Skipping document 50/999 with OID {1B8F8AED-AC66-40DD-8772-217056441803} because it's missing its XML file!! (stt exists: False)
Skipping document 51/999 with OID {80A47C60-6A24-4C7C-B1EA-FA76C157948F} because it's missing its XML file!! (stt exists: False)
Skipping document 52/999 with OID {B01F0752-CEF8-4880-B510-BB4E346EA507} because it's missing its XML file!! (stt exists: False)
Skipping document 53/999 with OID {056C8A23-216C-40B3-BAC6-B436423D3347} because it's missing its XML file!! (stt exists: False)
Skipping document 54/999 with OID {A4DAA5F2-D3E9-4BDE-883E-DB066170F230} because it's missing its XML file!! (stt exists: False)
Skipping document 57/999 with OID {12CF1052-517B-4E00-89B9-AE92C80FE7F8} because it's missing its XML file!! (stt exists: False)
Skipping document 59/999 with OID {45CB345E-B1A9-41CA-81EE-894482636469} because it's missing its XML file!! (stt exists: True)
Skipping document 62/999 with OID {7C21D07A-1BD9-4FE1-BEF6-7813D87E1C74} because it's missing its XML file!! (stt exists: False)
Skipping document 63/999 with OID {FAEFE165-B330-432C-B7DC-9E9B2F0D9133} because it's missing its XML file!! (stt exists: False)
Skipping document 68/999 with OID {9C52E2FF-5521-4DF4-9BB6-47454361619D} because it's missing its XML file!! (stt exists: False)
Skipping document 72/999 with OID {0BFBDFB9-B6C3-43A5-9EAE-3066C6C27F04} because it's missing its XML file!! (stt exists: False)
Skipping document 73/999 with OID {D7C32878-81D9-46E0-A98E-A7D12641D580} because it's missing its XML file!! (stt exists: False)
Skipping document 74/999 with OID {B44D54B3-8977-403D-ABF5-5ADDC95C47EC} because it's missing its XML file!! (stt exists: False)
Skipping document 75/999 with OID {1804508F-050B-4705-9869-A32B94DAD80B} because it's missing its XML file!! (stt exists: False)
Skipping document 77/999 with OID {7DF2BBBA-32F6-425F-9234-05F28987D0B9} because it's missing its XML file!! (stt exists: False)
Skipping document 78/999 with OID {FAA912F1-1EDB-47C8-A4B6-BF3BB7E60A4E} because it's missing its XML file!! (stt exists: False)
Skipping document 79/999 with OID {3E8F1323-01AA-4F4E-BA56-16137EC19726} because it's missing its XML file!! (stt exists: False)
Skipping document 82/999 with OID {872386ED-D252-41A7-972F-DA9A998B8A9D} because it's missing its XML file!! (stt exists: False)
Skipping document 84/999 with OID {012BD8F4-489D-4EA4-8C88-62E55CC2DA69} because it's missing its XML file!! (stt exists: True)
Skipping document 88/999 with OID {951EA9C3-90B1-4C05-B85C-14D9BAB84197} because it's missing its XML file!! (stt exists: False)
Skipping document 89/999 with OID {649F353A-79CF-46A3-9BB5-BCE507709BB5} because it's missing its XML file!! (stt exists: False)
Skipping document 92/999 with OID {45340A52-D9D8-41F8-9C2A-1A6E0E1CE922} because it's missing its XML file!! (stt exists: False)
Skipping document 95/999 with OID {DDBD1070-35E2-40A1-89A4-35739BB7EBD0} because it's missing its XML file!! (stt exists: False)
Skipping document 96/999 with OID {80DDABB3-010C-4F21-80EB-487F8C091028} because it's missing its XML file!! (stt exists: False)
Skipping document 97/999 with OID {F1E22842-07F5-4788-A1B9-1F69E983BADD} because it's missing its XML file!! (stt exists: False)
Skipping document 99/999 with OID {FB78093C-CAA3-4A9C-B418-9A1484ADBEED} because it's missing its XML file!! (stt exists: False)
Skipping document 101/999 with OID {DC74C4A6-F855-4A0A-95CA-021323A7418A} because it's missing its XML file!! (stt exists: False)
Skipping document 107/999 with OID {97A6AC13-CCB6-4BF4-BEF1-A8DBA94D5114} because it's missing its XML file!! (stt exists: False)
Skipping document 108/999 with OID {705D3182-A2F2-4AE3-94C9-425ED10F3C0D} because it's missing its XML file!! (stt exists: False)
Skipping document 109/999 with OID {61640975-24AA-4970-880D-B9F135DC026E} because it's missing its XML file!! (stt exists: True)
Skipping document 111/999 with OID {2CCC66E0-27AD-455A-AAF6-581F24C747C2} because it's missing its XML file!! (stt exists: False)
Skipping document 114/999 with OID {37AB94D5-C8BB-4EC9-8A41-16FD3397008E} because it's missing its XML file!! (stt exists: False)
Skipping document 116/999 with OID {0DDC91CC-AF46-4CC6-8036-3037A69DC99A} because it's missing its XML file!! (stt exists: False)
Skipping document 117/999 with OID {84D6CCA6-0613-4336-9502-4F9158E773A4} because it's missing its XML file!! (stt exists: False)
Skipping document 119/999 with OID {47915156-22A0-4C41-92F9-469B9C3E7DEF} because it's missing its XML file!! (stt exists: True)
Skipping document 120/999 with OID {8768CB6B-3AD1-4F55-B2F2-430C24DB29AA} because it's missing its XML file!! (stt exists: False)
Skipping document 121/999 with OID {063D7E8B-B07D-44FD-8CF7-5B5BF7F60AD9} because it's missing its XML file!! (stt exists: False)
Skipping document 123/999 with OID {E15D5DA6-AEE2-4AF7-B8C8-5E67C54E715A} because it's missing its XML file!! (stt exists: False)
Skipping document 124/999 with OID {5159FA87-F5DC-40C5-8CB0-E11B1FCF4AFE} because it's missing its XML file!! (stt exists: False)
Skipping document 125/999 with OID {A6CD9A2E-EA79-4085-9BDB-6DAF874FF6A6} because it's missing its XML file!! (stt exists: False)
Skipping document 130/999 with OID {F5F37A02-6D01-43DE-B711-9A21CEFE934C} because it's missing its audio MP3 file!!
Skipping document 134/999 with OID {F3BEFA70-973F-4D75-902A-7AE1837FA5CE} because it's missing its XML file!! (stt exists: False)
Skipping document 135/999 with OID {09F134C7-073B-4767-B7C4-1C0C2CB0FD31} because it's missing its XML file!! (stt exists: False)
Skipping document 136/999 with OID {6B3DC035-1014-4C83-BDEC-B7355651A83C} because it's missing its XML file!! (stt exists: False)
Skipping document 137/999 with OID {38FB9C27-E040-44D6-94F7-9D38262530A8} because it's missing its XML file!! (stt exists: False)
Skipping document 140/999 with OID {E3ADD5DE-53B6-4326-ACE4-1EFBAD24B99A} because it's missing its XML file!! (stt exists: False)
Skipping document 141/999 with OID {7C757DC6-CE9C-4C44-881E-E0616D2A77B1} because it's missing its XML file!! (stt exists: False)
Skipping document 142/999 with OID {126B8935-DC6F-4122-BC16-847B257CD1A6} because it's missing its XML file!! (stt exists: False)
Skipping document 147/999 with OID {A63B3182-8FE4-4268-A762-84BA50651EFD} because it's missing its XML file!! (stt exists: False)
Skipping document 148/999 with OID {78CAA533-2876-44E8-B991-37407732067C} because it's missing its XML file!! (stt exists: False)
Skipping document 149/999 with OID {AE063920-CD21-4DBB-BBB6-184BC0F43DE5} because it's missing its XML file!! (stt exists: False)
Skipping document 150/999 with OID {5A039C2F-7A21-469D-8BA0-8271FA51E6D1} because it's missing its XML file!! (stt exists: False)
Skipping document 151/999 with OID {6F1CE899-5D27-4938-B9F8-2B8D4D8D38AB} because it's missing its XML file!! (stt exists: False)
Skipping document 152/999 with OID {5D4B60AA-714F-4A2F-A064-2B727118F241} because it's missing its XML file!! (stt exists: False)
Skipping document 153/999 with OID {24CBD326-EF43-4867-ACFB-E0B49775FF5D} because it's missing its XML file!! (stt exists: False)
Skipping document 154/999 with OID {99BE2113-010B-4856-B2A8-58BAC89543AA} because it's missing its XML file!! (stt exists: False)
Skipping document 155/999 with OID {4A48B61B-D7E0-4396-A32E-75E89C88A1C6} because it's missing its XML file!! (stt exists: False)
Skipping document 156/999 with OID {D2E6DEB9-E583-4F43-8DE6-6DAB7F37E977} because it's missing its XML file!! (stt exists: False)
Skipping document 157/999 with OID {50E62C7E-E3CB-438D-96E2-F1CDC79479AC} because it's missing its XML file!! (stt exists: False)
Skipping document 159/999 with OID {999DE51C-57C7-4C71-9762-C1126D00281C} because it's missing its XML file!! (stt exists: False)
Skipping document 160/999 with OID {9679D9DD-E521-4A3C-ACE5-4638E82E6F66} because it's missing its XML file!! (stt exists: False)
Skipping document 162/999 with OID {57A23C87-5F62-49DF-989F-38D11FBC8DFE} because it's missing its XML file!! (stt exists: False)
Skipping document 163/999 with OID {A10C2EA4-2F8E-4336-BAD7-53E569DB06AE} because it's missing its XML file!! (stt exists: False)
Skipping document 164/999 with OID {BB55A3BD-0FC8-4BA1-AAEE-88990337BCE1} because it's missing its XML file!! (stt exists: False)
Skipping document 165/999 with OID {2D9FC471-9980-464F-8E85-5748B5E40416} because it's missing its XML file!! (stt exists: False)
Skipping document 167/999 with OID {A2973F2D-D5D8-432B-90A9-D937A0DFBA44} because it's missing its XML file!! (stt exists: False)
Skipping document 168/999 with OID {7346049B-A8C3-4EDD-8FA7-68096882D1E2} because it's missing its XML file!! (stt exists: False)
Skipping document 174/999 with OID {592712E4-B52C-4CC7-8BB3-D1E010BC9261} because it's missing its XML file!! (stt exists: True)
Skipping document 176/999 with OID {A28CDE66-89A0-4BE1-9EC0-63BCD0407A92} because it's missing its XML file!! (stt exists: False)
Skipping document 177/999 with OID {ED9B408B-FB72-445F-BCCA-4FA3B1CA2F8A} because it's missing its XML file!! (stt exists: False)
Skipping document 180/999 with OID {72B1EB80-5E81-41CF-9904-A6081A6B5761} because it's missing its XML file!! (stt exists: True)
Skipping document 186/999 with OID {D623DAF9-DE7C-4B37-9708-96002507CD91} because it's missing its XML file!! (stt exists: False)
Skipping document 187/999 with OID {E64F52C8-757D-4557-8EC4-14C29F1FB75D} because it's missing its XML file!! (stt exists: False)
Skipping document 190/999 with OID {305A3187-0BF5-4EE1-A768-C99EF171C18E} because it's missing its XML file!! (stt exists: False)
Skipping document 192/999 with OID {DABA93C6-70F0-41AF-B249-A3B9E899B344} because it's missing its XML file!! (stt exists: False)
Skipping document 193/999 with OID {AB84D55D-897D-4EA8-865C-2B4453604B86} because it's missing its XML file!! (stt exists: False)
Skipping document 195/999 with OID {1E5908DF-E113-42FF-BB32-649A628D6093} because it's missing its XML file!! (stt exists: False)
Skipping document 197/999 with OID {285E0FF7-836F-4578-A481-75A00EAF9328} because it's missing its XML file!! (stt exists: False)
Skipping document 200/999 with OID {C23F63A0-14D4-45AB-ACC2-A26378533C13} because it's missing its XML file!! (stt exists: False)
Skipping document 201/999 with OID {644B3769-FE33-4BC3-A5FE-C04AFCD36E98} because it's missing its XML file!! (stt exists: False)
Skipping document 202/999 with OID {3FF9ED3A-BCEE-4E1D-BF84-35A13A252109} because it's missing its XML file!! (stt exists: False)
Skipping document 204/999 with OID {CD6DB054-A614-4AD0-92CB-918280102F36} because it's missing its XML file!! (stt exists: False)
Skipping document 209/999 with OID {B85A064E-7762-4442-8007-6F42912496D5} because it's missing its XML file!! (stt exists: False)
Skipping document 210/999 with OID {36F84883-7BCF-4ED9-97A5-0ED21546578E} because it's missing its XML file!! (stt exists: False)
Skipping document 213/999 with OID {47D218CC-A3A4-438D-9BA1-10571F34A3EC} because it's missing its XML file!! (stt exists: False)
Skipping document 214/999 with OID {521BB894-A31D-4537-8837-12089903711F} because it's missing its XML file!! (stt exists: False)
Skipping document 215/999 with OID {3274A3B3-F90F-46DF-8589-C13E5EEA970D} because it's missing its XML file!! (stt exists: False)
Skipping document 216/999 with OID {EB315204-3F09-4A16-A34E-2733EE6994CD} because it's missing its XML file!! (stt exists: False)
Skipping document 217/999 with OID {234E5557-C561-437D-97F1-0ECFC3A0804B} because it's missing its XML file!! (stt exists: False)
Skipping document 218/999 with OID {97116462-C5BF-4BD5-AF7B-D4C2A4581771} because it's missing its XML file!! (stt exists: False)
Skipping document 221/999 with OID {97255E7B-7BE4-4111-82D7-BE4A0945480E} because it's missing its XML file!! (stt exists: False)
Skipping document 222/999 with OID {3937E639-2277-43B2-A52C-18C947B0B49E} because it's missing its XML file!! (stt exists: False)
Skipping document 223/999 with OID {50D014A9-455E-4408-B84C-562D09EC7822} because it's missing its XML file!! (stt exists: False)
Skipping document 224/999 with OID {9A8A0CB3-AD75-4A37-AAC9-46F6AE2CB880} because it's missing its XML file!! (stt exists: False)
Skipping document 227/999 with OID {DD8F9C4D-E722-4069-98A7-50B90DD6E99B} because it's missing its XML file!! (stt exists: False)
Skipping document 228/999 with OID {0FB07FFD-C4DD-4DFF-9DA2-93512654BC63} because it's missing its XML file!! (stt exists: False)
Skipping document 229/999 with OID {3F1548EF-EC43-4DBF-8ED3-55404DEB593F} because it's missing its XML file!! (stt exists: False)
Skipping document 234/999 with OID {409A63E2-0A84-4804-B250-803A49D34AF6} because it's missing its XML file!! (stt exists: False)
Skipping document 236/999 with OID {EC9F5D09-D25D-49F7-BCBD-3A7888681F94} because it's missing its XML file!! (stt exists: False)
Skipping document 237/999 with OID {2B72A808-892B-49E5-8772-9A8F6A24DC28} because it's missing its XML file!! (stt exists: False)
Skipping document 239/999 with OID {D975F54C-3085-464D-8702-79BB81F24B2E} because it's missing its XML file!! (stt exists: True)
Skipping document 241/999 with OID {0B9C2345-B8C1-475C-9014-9C52FEBB7A01} because it's missing its XML file!! (stt exists: False)
Skipping document 242/999 with OID {30671C3A-1732-45AC-AF8C-BC754A24C6F3} because it's missing its XML file!! (stt exists: False)
Skipping document 243/999 with OID {F04D09A6-4B1F-4A0F-B105-51CCC0A40E25} because it's missing its XML file!! (stt exists: False)
Skipping document 244/999 with OID {B4E63B8F-3C26-4F22-88AD-DCD217B76E17} because it's missing its XML file!! (stt exists: False)
Skipping document 245/999 with OID {A35FB7BE-EA73-479C-B1CC-F5F64FE4B26C} because it's missing its XML file!! (stt exists: False)
Skipping document 249/999 with OID {E31B3B58-EEEB-42C5-9537-41295B98D101} because it's missing its XML file!! (stt exists: False)
Skipping document 250/999 with OID {8AC59459-894B-4D0C-8691-BA29065DE210} because it's missing its XML file!! (stt exists: False)
Skipping document 251/999 with OID {E8AA3E8D-BF46-4B4A-BA2A-102052A61D26} because it's missing its XML file!! (stt exists: False)
Skipping document 257/999 with OID {463FB38F-602B-473B-BC7D-1213F24E1088} because it's missing its XML file!! (stt exists: False)
Skipping document 260/999 with OID {A52BD70F-E051-4DD6-9A77-AD9172DF88D6} because it's missing its XML file!! (stt exists: False)
Skipping document 263/999 with OID {3FB2D4F0-2A05-481A-B8B7-9F51B04E9604} because it's missing its XML file!! (stt exists: False)
Skipping document 265/999 with OID {A0CD7CCD-1A5A-422D-BC2A-0CB57D75DAFF} because it's missing its XML file!! (stt exists: False)
Skipping document 266/999 with OID {BC706FB6-8D73-4FA0-8A14-02BAEF8AC6DE} because it's missing its XML file!! (stt exists: False)
Skipping document 267/999 with OID {272321EF-FA96-4796-879C-84560DCB007F} because it's missing its XML file!! (stt exists: False)
Skipping document 268/999 with OID {47B73E4C-08B8-490A-A338-4967EB669E1F} because it's missing its XML file!! (stt exists: False)
Skipping document 269/999 with OID {498F91F8-6EFD-46C1-821D-A1AA0411D3EF} because it's missing its XML file!! (stt exists: False)
Skipping document 270/999 with OID {C1096CB6-58E0-4203-8E56-22FF2746CB76} because it's missing its XML file!! (stt exists: False)
Skipping document 274/999 with OID {9823EEAE-0A43-483A-B8BB-8317E6B23F48} because it's missing its XML file!! (stt exists: False)

Skipping document 926/999 with OID {A08350B0-851C-4B48-BFC6-374816A8DD3E} because it's missing its XML file!! (stt exists: False)
Skipping document 928/999 with OID {821DE259-9214-4680-AD24-035BB3C91E3F} because it's missing its XML file!! (stt exists: True)
Skipping document 929/999 with OID {C6455B34-4506-4D2A-9C6F-04AE30CD6B34} because it's missing its XML file!! (stt exists: False)
Skipping document 931/999 with OID {CFFFCDD7-9E93-4769-8BEA-2909CDA7CEB2} because it's missing its XML file!! (stt exists: False)
Skipping document 935/999 with OID {40F75BEF-19AC-44B7-AF1E-E22D66B2F804} because it's missing its XML file!! (stt exists: False)
Skipping document 938/999 with OID {D5208033-7B82-4C64-8E20-BDF811C6668B} because it's missing its XML file!! (stt exists: False)
Skipping document 940/999 with OID {FB7FB926-9943-41EE-A5AF-62E6130F87AB} because it's missing its XML file!! (stt exists: True)
Skipping document 942/999 with OID {CA7F4387-2FC8-4801-B954-22575D814445} because it's missing its XML file!! (stt exists: False)
Skipping document 945/999 with OID {2954734B-228D-4E86-B8F2-938869B1BD38} because it's missing its XML file!! (stt exists: False)
Skipping document 947/999 with OID {1181BEA9-5FF6-40DA-9BD9-3D747CC27D83} because it's missing its XML file!! (stt exists: False)
Skipping document 950/999 with OID {3A4D7A4A-EF90-40BC-8C1E-9663203C321A} because it's missing its XML file!! (stt exists: False)
Skipping document 952/999 with OID {BE3506D3-7944-467F-8053-3CC9993451A0} because it's missing its XML file!! (stt exists: False)
Skipping document 954/999 with OID {240C2523-B8CB-4F05-96E5-D0357C963EDC} because it's missing its XML file!! (stt exists: False)
Skipping document 956/999 with OID {F11992DB-13D2-4108-A062-C3C8F0F4D704} because it's missing its XML file!! (stt exists: False)
Skipping document 958/999 with OID {190E3DCE-8738-4013-B874-CA6427E01A3A} because it's missing its XML file!! (stt exists: False)
Skipping document 959/999 with OID {ABB9EC4D-8680-4DFE-B0E7-4ADDD1DC3772} because it's missing its XML file!! (stt exists: False)
Skipping document 961/999 with OID {83C4D578-46FA-4535-827E-29F5494016D6} because it's missing its XML file!! (stt exists: False)
Skipping document 966/999 with OID {BD5B4619-E04B-4E89-A98D-0AE844DEEAF4} because it's missing its XML file!! (stt exists: False)
Skipping document 967/999 with OID {6FB486B1-9883-452C-B2DC-BD84A71EC94C} because it's missing its XML file!! (stt exists: False)
Skipping document 970/999 with OID {E7725979-2163-49AB-8914-E3986EB67247} because it's missing its XML file!! (stt exists: False)
Skipping document 971/999 with OID {A3B4C7B2-00B1-43B2-9766-2D7739F43F7E} because it's missing its XML file!! (stt exists: True)
Skipping document 972/999 with OID {8B20368C-3A38-4F79-A5A6-D50AB13EEAA5} because it's missing its XML file!! (stt exists: True)
Skipping document 973/999 with OID {7C96DBC9-D278-44A5-840B-B05ECC11DFE0} because it's missing its XML file!! (stt exists: False)
Skipping document 974/999 with OID {20D78494-CD6F-4245-91E2-9BC891C09864} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {72282086-EE69-4FCD-96BD-4ED9E6A376DE}. Trying to use the recording date. doc_dict: {'alias': 'j_midi', 'date_str': None, 'stt_filename': '72282086-EE69-4FCD-96BD-4ED9E6A376DE_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{72282086-EE69-4FCD-96BD-4ED9E6A376DE}', 'stripped_OID': '72282086-EE69-4FCD-96BD-4ED9E6A376DE', 'login': '', 'broadcast_episode_title': "L'avenir de l'Europe spatiale", 'sequence': '1', 'broadcast_program_name': 'Journal de midi', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'freudial', 'modified_on': '23.01.2025 10:04:04', 'physical_support_history': "Cote d'origine: 25347.08", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': "Midi-premi?re futur: L'avenir de l'Europe spatiale avec les interviews de Fr?d?ric Allest, directeur d'Ariane 5 sur les programmes en cours, et la position de la Grande Bretagne. Et l'interview de Franz Muheim repr?sentant la Suisse ? la conf?rence de la Haye. Concurrencer les deux poids lourds de l'exploration de l'espace, les Etats-Unis et les Sovi?tiques. Le programme Herm?s. Satisfaction des r?sultats obtenu par les pays europ?ens, malgr? la d?fection de la Grande-Bretagne. Discussions sur la station spatiale internationale.", 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:17:02.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Schaerlig, Eric', 'function': 'Commentateur/trice', 'role': 'collaborateur RSR'}, {'name': "Allest, Fr?d?ric d'", 'function': 'Interview?/e', 'role': "directeur d'Ariane 5"}, {'name': 'Muheim, Franz', 'function': 'Interview?/e', 'role': 'repr?sentant suisse'}, {'name': 'Inconnu', 'function': 'Pr?sentateur/trice', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Europe', 'Grande-Bretagne'], 'person_descriptors': ['CEE'], 'thematical_descriptors': ['conqu?te spatiale', 'industrie spatiale'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Commentaire', 'Interview'], 'recording_dates': ['11/11/1987 - 11/11/1987'], 'first_broadcast_dates': None}
Skipping document 983/999 with OID {FD4FE4C5-8A51-45A6-9A00-30F15F669DB0} because it's missing its XML file!! (stt exists: False)
Skipping document 985/999 with OID {2D2EF94B-B26B-476C-9B5A-6AF620245302} because it's missing its XML file!! (stt exists: False)
Skipping document 986/999 with OID {37E1178B-4A9E-4088-857B-E4124EBBFDF4} because it's missing its XML file!! (stt exists: False)
Skipping document 987/999 with OID {6D9B9AD6-54AE-419E-B697-EF70A56772DC} because it's missing its XML file!! (stt exists: False)
Skipping document 990/999 with OID {A6D9F52C-04BC-4815-A5B9-CFA0DC4E2D97} because it's missing its XML file!! (stt exists: False)
Skipping document 993/999 with OID {0FBECB71-5F2F-43BC-B83C-2C08BF90BD7C} because it's missing its XML file!! (stt exists: False)
Skipping document 998/999 with OID {D611C6FF-9400-4991-A721-0E60CE943D9A} because it's missing its XML file!! (stt exists: False)
Skipping document 999/999 with OID {731E145A-14EB-4440-ACDE-3C0444503182} because it's missing its XML file!! (stt exists: False)
j_midi - returning 583 documents, 416 were skipped due to missing necessary info.

Starting extracting 418 documents for program j_midi
Skipping document 3/418 with OID {E1E78720-9E24-442D-83D5-F66F779F8599} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {4DF97388-426C-4335-8095-2F220DCEBA47}. Trying to use the recording date. doc_dict: {'alias': 'j_midi', 'date_str': None, 'stt_filename': '4DF97388-426C-4335-8095-2F220DCEBA47_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{4DF97388-426C-4335-8095-2F220DCEBA47}', 'stripped_OID': '4DF97388-426C-4335-8095-2F220DCEBA47', 'login': '', 'broadcast_episode_title': "Souvenirs sur L?nine ? l'occasion du centenaire de sa naissance (1/3)", 'sequence': '1', 'broadcast_program_name': 'Journal de midi', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'comtesi', 'modified_on': '21.05.2015 03:11:21', 'physical_support_history': "Cote d'origine: A 16606 Pl. 1", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives. Communisme, URSS, Pile ou Face", 'content_summary': 'Une dame t?moigne de la vie L?nine au moment de son s?jour ? Z?rich', 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:01:59.040', 'work_duration_compl': 'Non', 'participants': [{'name': 'Inconnue', 'function': 'Interview?/e', 'role': 'connaissance de L?nine'}, {'name': 'Inconnu', 'function': 'Intervieweur/euse', 'role': 'collaborateur Radio-Lausanne'}], 'geographical_descriptors': ['Zurich (ville)', 'URSS'], 'person_descriptors': ['L?nine (r?volutionnaire russe)'], 'thematical_descriptors': ['communisme', 'fonction politique'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Interview'], 'recording_dates': ['01/01/1970 - 01/01/1970'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {945A98F6-C721-4F0D-AEFF-978DB66AE59A}. Trying to use the recording date. doc_dict: {'alias': 'j_midi', 'date_str': None, 'stt_filename': '945A98F6-C721-4F0D-AEFF-978DB66AE59A_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{945A98F6-C721-4F0D-AEFF-978DB66AE59A}', 'stripped_OID': '945A98F6-C721-4F0D-AEFF-978DB66AE59A', 'login': '', 'broadcast_episode_title': "Souvenirs sur L?nine ? l'occasion du centenaire de sa naissance (2/3) : Un paysan des Plans-sur-Bex parle de l'arriv?e et la vie de L?nine et de sa famille dans la r?gion au d?but du si?cle", 'sequence': '1', 'broadcast_program_name': 'Journal de midi', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'comtesi', 'modified_on': '20.05.2015 12:46:11', 'physical_support_history': "Cote d'origine: A 16606 Pl. 2", 'production_type': 'Production propre', 'recording_place': 'Plans-sur-Bex', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives. Communisme, URSS, pile ou face.", 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:04:25.173', 'work_duration_compl': 'Non', 'participants': [{'name': 'Inconnu', 'function': 'Interview?/e', 'role': 'paysan de Plan-sur-Bey'}, {'name': 'Inconnue', 'function': 'Intervieweur/euse', 'role': 'journaliste Radio-Lausanne'}], 'geographical_descriptors': ['Plans-sur-Bex'], 'person_descriptors': ['L?nine (r?volutionnaire russe)'], 'thematical_descriptors': ['vie quotidienne'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Interview'], 'recording_dates': ['01/01/1970 - 01/01/1970'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {36F3665A-1AD4-45D3-9933-9E2C4CF23699}. Trying to use the recording date. doc_dict: {'alias': 'j_midi', 'date_str': None, 'stt_filename': '36F3665A-1AD4-45D3-9933-9E2C4CF23699_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{36F3665A-1AD4-45D3-9933-9E2C4CF23699}', 'stripped_OID': '36F3665A-1AD4-45D3-9933-9E2C4CF23699', 'login': '', 'broadcast_episode_title': "Souvenirs sur L?nine ? l'occasion du centenaire de sa naissance (3/3) : La rencontre de Jules Humbert-Droz, journaliste et homme politique, avec L?nine et r?cit de quelques anecdotes montrant son cot? humain", 'sequence': '1', 'broadcast_program_name': 'Journal de midi', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'comtesi', 'modified_on': '21.05.2015 06:18:34', 'physical_support_history': "Cote d'origine: A 16606 Pl.3", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives. Communisme, URSS, pile ou face.", 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:03:45.493', 'work_duration_compl': 'Non', 'participants': [{'name': 'Humbert-Droz, Jules', 'function': 'Interview?/e', 'role': 'journaliste et homme politique'}, {'name': 'Inconnu', 'function': 'Intervieweur/euse', 'role': 'journaliste'}], 'geographical_descriptors': None, 'person_descriptors': ['L?nine (r?volutionnaire russe)'], 'thematical_descriptors': ['politique', 'humanisme'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Interview'], 'recording_dates': ['01/01/1970 - 01/01/1970'], 'first_broadcast_dates': None}
Skipping document 20/418 with OID {AD6C4DAA-033C-4A16-B366-224D4A3F949F} because it's missing its XML file!! (stt exists: False)
Skipping document 22/418 with OID {9621020A-1E51-49D1-ABEA-A525F428C98D} because it's missing its XML file!! (stt exists: False)
Skipping document 26/418 with OID {8CBFDE9C-1093-4AD2-88D2-96B0B31A4FD7} because it's missing its XML file!! (stt exists: False)
Skipping document 28/418 with OID {C8D1202F-18A2-4C36-905B-AA4F6B9DE7E7} because it's missing its XML file!! (stt exists: False)
Skipping document 29/418 with OID {3E51A55C-DE2B-44A6-B65E-AFBBC318D1D1} because it's missing its XML file!! (stt exists: False)
Skipping document 30/418 with OID {10D9ABB7-49EC-4C6C-8A1A-3DA0C90DDD54} because it's missing its XML file!! (stt exists: False)
Skipping document 31/418 with OID {D7488372-F4B4-4179-8209-75527CFD32A2} because it's missing its XML file!! (stt exists: False)
Skipping document 32/418 with OID {4C859EB6-3C22-4FD6-A6D6-F77F5B762207} because it's missing its XML file!! (stt exists: True)
Skipping document 35/418 with OID {69C779C8-DF7B-4B42-96E9-9B915E739F41} because it's missing its XML file!! (stt exists: False)
Skipping document 36/418 with OID {DAFADE11-C2EB-4774-BA47-641BE80A56EB} because it's missing its XML file!! (stt exists: False)
Skipping document 42/418 with OID {32A60C7F-EEE1-440C-895E-E02EB27C23D8} because it's missing its XML file!! (stt exists: False)
Skipping document 43/418 with OID {10FA7DE8-B584-433F-8C45-D44E79353C44} because it's missing its XML file!! (stt exists: False)
Skipping document 51/418 with OID {7A7B69ED-FB8A-47E3-BD7F-A1FEFBD5C818} because it's missing its XML file!! (stt exists: False)
Skipping document 52/418 with OID {D8C0CDF0-5035-4F46-B174-0105764408BA} because it's missing its XML file!! (stt exists: False)
Skipping document 55/418 with OID {583583ED-D0C1-49B3-880F-67A50243CB30} because it's missing its XML file!! (stt exists: False)
Skipping document 56/418 with OID {28C454E1-1A52-4BC5-BBFF-2B010023C303} because it's missing its XML file!! (stt exists: False)
Skipping document 57/418 with OID {BD67F9C4-AFB1-4425-8E3D-49671750CE20} because it's missing its XML file!! (stt exists: False)
Skipping document 59/418 with OID {5A9F430D-10D0-454A-94DB-B3D772A9256B} because it's missing its XML file!! (stt exists: False)
Skipping document 62/418 with OID {4DD5BAAD-F692-45B6-8EA4-C192D2CE8D4B} because it's missing its XML file!! (stt exists: False)
Skipping document 63/418 with OID {B4F97196-E4C0-461F-914E-67998A8D71BF} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {E82D92F7-5A6C-4B49-A3EB-845A9CF2FC72}. Trying to use the recording date. doc_dict: {'alias': 'j_midi', 'date_str': None, 'stt_filename': 'E82D92F7-5A6C-4B49-A3EB-845A9CF2FC72_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{E82D92F7-5A6C-4B49-A3EB-845A9CF2FC72}', 'stripped_OID': 'E82D92F7-5A6C-4B49-A3EB-845A9CF2FC72', 'login': '', 'broadcast_episode_title': "Sur les sentiers valaisans : Savi?se. Interviews de M. Luyet, pr?sident de la commune, de bergers, d'habitants et d'un peintre", 'sequence': '1', 'broadcast_program_name': 'Journal de midi', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'albrecjo', 'modified_on': '23.05.2015 04:11:57', 'physical_support_history': "Cote d'origine: A17013.", 'production_type': 'Production propre', 'recording_place': 'Savi?se', 'rights_notes': None, 'rights_status': 'A rechercher', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': None, 'modulation_type': 'Mono', 'work_duration': '00:28:50.258', 'work_duration_compl': 'Non', 'participants': [{'name': 'Musy, Frank', 'function': 'Reporter', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Valais', 'Savi?se'], 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': None, 'radio_channels': None, 'subdomains': ['Interview', 'Reportage'], 'recording_dates': ['17/07/1972 - 17/07/1972'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {C9840253-BDBE-46E9-8433-88C6BA407B3C}. Trying to use the recording date. doc_dict: {'alias': 'j_midi', 'date_str': None, 'stt_filename': 'C9840253-BDBE-46E9-8433-88C6BA407B3C_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{C9840253-BDBE-46E9-8433-88C6BA407B3C}', 'stripped_OID': 'C9840253-BDBE-46E9-8433-88C6BA407B3C', 'login': '', 'broadcast_episode_title': "Sur les sentiers valaisans : Savi?se. Interviews de M. Luyet, pr?sident de la commune, de bergers, d'habitants et d'un peintre [extrait]", 'sequence': '2', 'broadcast_program_name': 'Journal de midi', 'document_type': 'Parl?', 'hierarchy_level': 'Extrait', 'modified_by': 'albrecjo', 'modified_on': '09.10.2022 20:29:21', 'physical_support_history': "Cote d'origine: A17013.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'A rechercher', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': None, 'modulation_type': 'Mono', 'work_duration': '00:28:50.258', 'work_duration_compl': 'Non', 'participants': [{'name': 'Musy, Frank', 'function': 'Reporter', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Valais', 'Savi?se'], 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': None, 'radio_channels': None, 'subdomains': ['Reportage', 'Interview'], 'recording_dates': ['17/07/1972 - 17/07/1972'], 'first_broadcast_dates': None}
Skipping document 69/418 with OID {6A17D56B-77C4-4E01-9C61-E81141FDEA23} because it's missing its XML file!! (stt exists: False)
Skipping document 72/418 with OID {B9C46C3A-8F8D-4BA3-88CA-7B2A5A70214B} because it's missing its XML file!! (stt exists: False)
Skipping document 75/418 with OID {E84751EB-3F78-4695-AEBF-01188DBD56B7} because it's missing its XML file!! (stt exists: False)
Skipping document 76/418 with OID {7C273281-87AC-46B7-9981-B3410C414FD2} because it's missing its XML file!! (stt exists: False)
Skipping document 78/418 with OID {3CE094D6-1869-47C9-B674-997C9FAD7221} because it's missing its XML file!! (stt exists: False)
Skipping document 80/418 with OID {8A9A7961-9A15-4C92-B23C-A7CDA561D209} because it's missing its XML file!! (stt exists: True)
Skipping document 92/418 with OID {01C95858-B8DA-43BE-8264-CCF7F876AE32} because it's missing its XML file!! (stt exists: False)
Skipping document 93/418 with OID {A2FF539D-D646-434A-9031-97F5554CCD8D} because it's missing its XML file!! (stt exists: False)
Skipping document 95/418 with OID {D31CCCD0-7E24-4C2A-9D5D-6DDEE4CC8D23} because it's missing its XML file!! (stt exists: False)
Skipping document 99/418 with OID {6279720E-8486-4BC7-A90D-0DFA56234FEF} because it's missing its XML file!! (stt exists: False)
Skipping document 101/418 with OID {2A4FA2A7-C17F-4D1A-B708-5A3B00348C98} because it's missing its XML file!! (stt exists: False)
Skipping document 108/418 with OID {1CDFD2C1-D818-4205-8AB7-F0B9F61D874C} because it's missing its XML file!! (stt exists: False)
Skipping document 109/418 with OID {75678DC9-7E92-4F47-B24E-12B753D37AC2} because it's missing its XML file!! (stt exists: False)
Skipping document 110/418 with OID {DABBEB6C-7C8F-493C-ACE3-CA0C9A49729D} because it's missing its XML file!! (stt exists: False)
Skipping document 112/418 with OID {99829376-5A48-4D72-BA11-EE16C9F68D0E} because it's missing its XML file!! (stt exists: False)
Skipping document 114/418 with OID {992DAF47-888B-4822-BD96-06EAAB617DE7} because it's missing its XML file!! (stt exists: False)
Skipping document 115/418 with OID {6A3B2A43-9E0B-4D6B-9E63-4BC499594817} because it's missing its XML file!! (stt exists: False)

Skipping document 411/418 with OID {BBCED5EE-69E3-46FB-BA02-F92DF602FE30} because it's missing its XML file!! (stt exists: True)
Skipping document 414/418 with OID {66A51CF7-8033-4D67-A3DA-AD03ABF22D3B} because it's missing its XML file!! (stt exists: True)
Skipping document 418/418 with OID {BF31431D-F34C-4884-9CD1-BDA96E76471D} because it's missing its XML file!! (stt exists: True)
j_midi - returning 291 documents, 127 were skipped due to missing necessary info.

Starting extracting 999 documents for program j_midi
Skipping document 2/999 with OID {5C81CE34-8235-452F-A8D4-2CEBED726B14} because it's missing its XML file!! (stt exists: False)
Skipping document 3/999 with OID {3F5E2CBB-1635-4D68-94DF-47E89C5E3F6C} because it's missing its XML file!! (stt exists: False)
Skipping document 5/999 with OID {1F607EA8-B8C2-468C-92DF-B0313F6AA9EF} because it's missing its XML file!! (stt exists: True)
Skipping document 6/999 with OID {098D07E4-48C9-442D-9775-5C95474618EF} because it's missing its XML file!! (stt exists: False)
Skipping document 8/999 with OID {B40B3532-75CD-4825-AAD8-CAC19739224A} because it's missing its XML file!! (stt exists: False)
Skipping document 9/999 with OID {A6F177C5-5564-4B49-8BFB-BDF267AAB543} because it's missing its XML file!! (stt exists: False)
Skipping document 10/999 with OID {DCADC225-3798-4D91-9FF0-2D8F3473D730} because it's missing its XML file!! (stt exists: False)
Skipping document 11/999 with OID {6630E831-2C72-466F-AF4E-8ADB8482EEEA} because it's missing its XML file!! (stt exists: False)
Skipping document 13/999 with OID {4942FFC0-C4F6-46FA-B640-F5BD456DA9E3} because it's missing its XML file!! (stt exists: False)
Skipping document 26/999 with OID {D015827A-293F-419C-B4DD-07B4C1DAEA4D} because it's missing its XML file!! (stt exists: False)
Skipping document 28/999 with OID {A757C3CC-1AD8-484A-9C0A-BC0582424BCC} because it's missing its XML file!! (stt exists: False)
Skipping document 32/999 with OID {B66A8E87-3004-4FBF-922E-3FE41BAD11E5} because it's missing its XML file!! (stt exists: False)
Skipping document 35/999 with OID {E30A13AA-5EBD-49EB-A1A7-105B0D5A4CCF} because it's missing its XML file!! (stt exists: True)
Skipping document 40/999 with OID {8389C0B4-E45A-4553-89F7-8630103FF595} because it's missing its XML file!! (stt exists: False)
Skipping document 41/999 with OID {0D8942EB-9AF0-45D0-A030-E2C563E376A4} because it's missing its XML file!! (stt exists: False)
Skipping document 44/999 with OID {73094FE6-E19A-4AA9-B0E8-F8F0E490902C} because it's missing its XML file!! (stt exists: False)
Skipping document 45/999 with OID {67D1D6DE-4033-4B81-996D-5FA40266F6C5} because it's missing its XML file!! (stt exists: False)
Skipping document 46/999 with OID {09E4150D-8291-4331-A4DA-A5F85856D1D3} because it's missing its XML file!! (stt exists: False)
Skipping document 47/999 with OID {A2090358-CE08-46ED-9E1A-4EA476E9809A} because it's missing its XML file!! (stt exists: False)
Skipping document 48/999 with OID {4577BEF5-D8A1-4D93-9F68-3E91558757AB} because it's missing its XML file!! (stt exists: False)
Skipping document 49/999 with OID {BE6EF1D9-59DC-4220-A404-E75D5A3E37D5} because it's missing its XML file!! (stt exists: False)
Skipping document 51/999 with OID {AE3DDC77-3BFD-4A1B-B76C-EB6BB8211630} because it's missing its XML file!! (stt exists: False)
Skipping document 52/999 with OID {D367811D-BE89-40F6-B07B-493935A3CE7C} because it's missing its XML file!! (stt exists: False)
Skipping document 56/999 with OID {163918E0-83E6-4C11-9E43-A843D8CCB688} because it's missing its XML file!! (stt exists: False)
Skipping document 61/999 with OID {3D735466-DC5F-4B6C-835D-89CDC6DCAF0C} because it's missing its XML file!! (stt exists: True)
Skipping document 63/999 with OID {A112F6D7-5762-4D07-9935-1793102C343F} because it's missing its XML file!! (stt exists: False)
Skipping document 64/999 with OID {F2B00225-1B9A-4367-9C88-D069E7EE51A4} because it's missing its XML file!! (stt exists: False)
Skipping document 65/999 with OID {7D8620E7-D5F2-452E-8E9A-43FB73A733A6} because it's missing its XML file!! (stt exists: False)
Skipping document 66/999 with OID {C0638230-0708-4B4C-B9EB-1AC704A35FA8} because it's missing its XML file!! (stt exists: False)
Skipping document 69/999 with OID {CA014900-3220-456E-B72B-B613304D73D7} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {EE361146-1A6C-4982-93DA-A763093D39FD}. Trying to use the recording date. doc_dict: {'alias': 'j_midi', 'date_str': None, 'stt_filename': 'EE361146-1A6C-4982-93DA-A763093D39FD_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{EE361146-1A6C-4982-93DA-A763093D39FD}', 'stripped_OID': 'EE361146-1A6C-4982-93DA-A763093D39FD', 'login': '', 'broadcast_episode_title': "Op?ration sp?ciale RSR La Tamponne : de Lausanne ? Bellinzone, en passant par Morat et Bienne. Montage d'?l?ments diffus?s quotidiennement dans le Journal de Midi", 'sequence': '1', 'broadcast_program_name': 'Journal de midi', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'prongudo', 'modified_on': '19.05.2015 13:00:09', 'physical_support_history': "Cote d'origine: 7773. 6 plages. Plusieurs jours dans la date.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives. Fribourg", 'content_summary': 'Impressions de voyage au d?part de la gare de Lausanne; interview ? chaque arr?t avec micro-quai de gare ? Pal?zieux, Moudon, Payerne, Morat. Incroyable entretien avec une passante de langue al?manique; (? 08\'40\'\') vente de porcelets ? la foire de Morat; probl?mes de la fili?re "viande de porc"; l\'importance des march?s au b?tail; (? 15h46) visite de la ville de Morat avec Etienne Chatton, conservateur des monuments historiques du canton de Fribourg : vue g?n?rale, ?glise de Sainte-Catherine, pr?sentation critique de l\'int?rieur et des vitraux saint-sulpiciens; pr?sentation de la Grand-rue, discussion autour de la pr?sence des voitures en ville; pr?sentation de la maison R?benloch et de son ?clairage "tape-?-l\'oeil"; pr?sentation de l\'?glise r?form?e allemande; alors que la ville d?pendait de Saint-Maurice, Fribourg g?rait les aspects militaires et Berne les questions religieuses. Napol?on fit int?grer Morat au canton de Fribourg; iconographie protestante de l\'?glise et du retable : l\'ours de Berne et les armoiries de la ville de Fribourg; armoiries de la ville de Morat; importance du r?le de la Conf?d?ration dans la restauration des monuments historiques; beaut? des remparts et des toits de Morat; description de la bataille de Morat par Etienne Chatton; (? 38\'13\'\') Les Jodleurs de Morat, escapade en for?t et rencontre avec le club des jodleurs en pic-nic (belle mise en sc?ne d\'une rencontre improbable ! ); productions du Jodler-club; incursion de l\'?quipe de la Tamponne dans un cin?ma porno ? Bienne; description implicite des lieux en jouant sur la m?taphore fil?e des la d?couverte des Alpes bavaroises (sic!); (? 53\'50\'\'), premiers plaisirs de ski au Tessin; r?cit de vie du P?p? Giacomo, passionn? de montagne, 82 ans et engag? ? gauche (marxiste);', 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '01:04:51.188', 'work_duration_compl': 'Non', 'participants': [{'name': 'Jean Charles [= Brunschwiler, Jean-Charles ]', 'function': 'Pr?sentateur/trice', 'role': 'collaborateur RSR'}, {'name': 'D?n?riaz, Michel', 'function': 'Animateur/trice', 'role': 'collaborateur RSR'}, {'name': 'Musy, Frank', 'function': 'Reporter', 'role': 'collaborateur RSR'}, {'name': 'Donzel, Jacques', 'function': 'Reporter', 'role': 'collaborateur RSR'}, {'name': 'Chatton, Etienne', 'function': 'Interview?/e', 'role': 'conservateur des monuments historiques du canton de Fribourg'}, {'name': 'B?rnersenne de M?nchenwiler', 'function': 'Ensemble / orchestre', 'role': 'jodler-club de Morat et environs'}, {'name': 'p?p? giacomo', 'function': 'Interview?/e', 'role': 'p?re de famille, 82 ans, Bellinzona'}], 'geographical_descriptors': ['Suisse', 'Fribourg (canton)', 'Lac (district, FR)', 'Morat', 'Vully', 'Berne (canton)', 'Bienne', 'Tessin', 'Bellinzone'], 'person_descriptors': ['Chatton, Etienne'], 'thematical_descriptors': ['porc', 'foire commerciale', 'vente', 'viande', 'Celtes', 'chant populaire', 'jodel', 'ski (mat?riel)'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Premier programme'], 'subdomains': ['Interview'], 'recording_dates': ['01/07/1975 - 01/07/1975'], 'first_broadcast_dates': None}
Skipping document 75/999 with OID {A6A1AAF5-6E8A-4949-9A19-A3788DBBBA66} because it's missing its XML file!! (stt exists: True)
Skipping document 77/999 with OID {AA8E61DE-F691-4D0A-B2E7-4248BDBC581C} because it's missing its XML file!! (stt exists: False)
Skipping document 79/999 with OID {4405A960-B25F-4FD0-9E3E-920C837F42B4} because it's missing its XML file!! (stt exists: False)
Skipping document 80/999 with OID {C167D959-59AA-4A6E-8694-D035E5319294} because it's missing its XML file!! (stt exists: False)
Skipping document 88/999 with OID {08C69247-545E-4298-8847-21175F0BB470} because it's missing its XML file!! (stt exists: False)
Skipping document 97/999 with OID {8415CA54-2657-48C5-BCC8-AC649268D890} because it's missing its XML file!! (stt exists: False)
Skipping document 98/999 with OID {7F6BA744-38E7-4913-A26F-DD7BC2B613AC} because it's missing its XML file!! (stt exists: False)
Skipping document 100/999 with OID {ED451E04-D48B-4B31-9987-06F14A69EFEE} because it's missing its XML file!! (stt exists: False)
Skipping document 101/999 with OID {4DAC1177-0D7F-4AE8-AD16-CA812B38C64B} because it's missing its XML file!! (stt exists: False)
Skipping document 109/999 with OID {765FCC2E-CBED-47AD-ACBB-C3FC9BB2D384} because it's missing its XML file!! (stt exists: False)
Skipping document 112/999 with OID {A5A75450-BFE2-4937-A033-43488008796D} because it's missing its XML file!! (stt exists: True)
Skipping document 117/999 with OID {9C458D99-F60D-4022-A20B-F9BC2A0AD6CA} because it's missing its XML file!! (stt exists: False)
Skipping document 123/999 with OID {297AAAF2-D23A-4B67-B3A5-5A3B444789F7} because it's missing its XML file!! (stt exists: False)
Skipping document 128/999 with OID {40958075-CCF0-40AD-BBBA-D234BACD1CF7} because it's missing its XML file!! (stt exists: True)
Skipping document 133/999 with OID {29CDC703-45E3-4871-8755-C3F1D8967503} because it's missing its XML file!! (stt exists: True)
Skipping document 138/999 with OID {D75349A1-D7C1-498E-9E51-4BC3B10EA9BB} because it's missing its XML file!! (stt exists: False)
Skipping document 141/999 with OID {84A6ADAF-85CC-407D-91D9-DB0BD53976B5} because it's missing its XML file!! (stt exists: False)
Skipping document 142/999 with OID {33EF8DE2-E4E4-4A6F-94F0-BA1089907F3D} because it's missing its XML file!! (stt exists: False)
Skipping document 144/999 with OID {1950BA3D-FE60-47E5-9099-484F03271959} because it's missing its XML file!! (stt exists: False)
Skipping document 146/999 with OID {B48D4885-AFEA-405C-B899-9A3D140077D1} because it's missing its XML file!! (stt exists: True)
Skipping document 148/999 with OID {9C7B24D9-DD7A-4DD7-9D99-66198441CFF7} because it's missing its XML file!! (stt exists: False)
Skipping document 151/999 with OID {926B4DF5-9E1F-4CC1-9044-91350733DE63} because it's missing its XML file!! (stt exists: False)
Skipping document 153/999 with OID {8EA2FDA1-FD47-4382-9CBF-C5C8592C11A1} because it's missing its XML file!! (stt exists: False)
Skipping document 154/999 with OID {A305C1D0-6744-4E25-9A33-47EAAFF256F4} because it's missing its XML file!! (stt exists: False)
Skipping document 157/999 with OID {C1DAD481-263F-47E0-8447-55DF5CAC4995} because it's missing its XML file!! (stt exists: False)
Skipping document 158/999 with OID {567F418C-C875-45A3-A263-C8F0DB12CD23} because it's missing its XML file!! (stt exists: True)
Skipping document 159/999 with OID {95092705-3AE2-4A30-8F00-7C0AD0C4941E} because it's missing its XML file!! (stt exists: False)
Skipping document 163/999 with OID {3CDFDF6B-02C7-4D55-961C-35ACABC50877} because it's missing its XML file!! (stt exists: False)
Skipping document 165/999 with OID {FE9E5809-5C7C-4D01-B865-6AD2A0368541} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {28E1B323-C83E-4BFE-9DA4-A7F10F56F967}. Trying to use the recording date. doc_dict: {'alias': 'j_midi', 'date_str': None, 'stt_filename': '28E1B323-C83E-4BFE-9DA4-A7F10F56F967_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{28E1B323-C83E-4BFE-9DA4-A7F10F56F967}', 'stripped_OID': '28E1B323-C83E-4BFE-9DA4-A7F10F56F967', 'login': '', 'broadcast_episode_title': 'Personnage savoureux. Fritz Jean Begert, p?dagogue et enseignant', 'sequence': '1', 'broadcast_program_name': 'Journal de midi', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '13.06.2017 14:13:43', 'physical_support_history': "Cote d'origine: 24682 Pl. 4", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': '[Fritz Jean Begert (19.8.1907-8.12.1984). Folkloriste et ?crivain ? Interlaken de 1942-1944, au ch?teau de Surpierre de 1947-1948, et ? Romainm?tier depuis 1968. Nourrie par son exp?rience de directeur des colonies de vacances de Thoune et par la psychologie sociale de Rudolf Maria Holzapfel, sa p?dagogie repose essentiellement sur les groupes homog?nes, sur un enseignement adapt? aux besoins des ?l?ves et sur les communaut?s de travail librement constitu?es]. In: Dictionnaire historique de la Suisse.', 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:06:33.343', 'work_duration_compl': 'Non', 'participants': [{'name': 'Begert, Fritz Jean', 'function': 'Interview?/e', 'role': 'p?dagogue, enseignant'}, {'name': 'Bory, Michel', 'function': 'Intervieweur/euse', 'role': None}], 'geographical_descriptors': ['Vaud', 'Romainm?tier-Envy'], 'person_descriptors': ['Begert, Fritz Jean'], 'thematical_descriptors': ['franc-ma?onnerie', 'p?dagogie', 'enseignement obligatoire', '?criture'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Premier programme'], 'subdomains': ['Interview'], 'recording_dates': ['01/01/1970 - 01/01/1970'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {AEE5A879-F194-4399-A918-889F57126887}. Trying to use the recording date. doc_dict: {'alias': 'j_midi', 'date_str': None, 'stt_filename': 'AEE5A879-F194-4399-A918-889F57126887_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{AEE5A879-F194-4399-A918-889F57126887}', 'stripped_OID': 'AEE5A879-F194-4399-A918-889F57126887', 'login': '', 'broadcast_episode_title': 'Personnages savoureux. Julien Perrin, le policier devenu ermite', 'sequence': '1', 'broadcast_program_name': 'Journal de midi', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '04.03.2021 14:37:35', 'physical_support_history': "Cote d'origine: 24682 Pl.1", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:05:27.008', 'work_duration_compl': 'Non', 'participants': [{'name': 'Perrin, Julien', 'function': 'Interview?/e', 'role': 'policier devenu ermite'}, {'name': 'Bory, Michel', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}], 'geographical_descriptors': None, 'person_descriptors': ['Perrin, Julien'], 'thematical_descriptors': ['ermite'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Interview'], 'recording_dates': ['01/01/1970 - 01/01/1970'], 'first_broadcast_dates': None}
The date for document with OID {2FDCF936-0C60-44E9-910A-4916D6E83547} was invalid (__/__/1970) - changed it to 01/01/1970
The date for document with OID {ED039290-4ADE-4361-B141-00923E43042E} was invalid (__/__/1970) - changed it to 01/01/1970
The date for document with OID {7ECB38A3-FFB0-41EA-ADD5-2B7CC112D025} was invalid (__/__/1970) - changed it to 01/01/1970
The date for document with OID {339707B3-6D95-4F2C-B8B3-54632C855321} was invalid (__/__/1970) - changed it to 01/01/1970
The date for document with OID {339707B3-6D95-4F2C-B8B3-54632C855321} was invalid (__/__/1970) - changed it to 01/01/1970
The date for document with OID {4D3C4A90-E90D-4A85-B01F-650BE82AB84E} was invalid (__/__/1970) - changed it to 01/01/1970
The date for document with OID {29AA5A3F-48D6-49FA-B293-5D909FED3D07} was invalid (__/__/1970) - changed it to 01/01/1970
The date for document with OID {A88DFE0F-BB48-4088-8BF5-D9CC869B6903} was invalid (__/__/1970) - changed it to 01/01/1970
The date for document with OID {72BD3970-A4E1-458E-8B43-F577BCF8482B} was invalid (__/__/1970) - changed it to 01/01/1970
The date for document with OID {EF7F0B9E-B578-42A4-82DD-5B0571F476B1} was invalid (__/__/1970) - changed it to 01/01/1970
The date for document with OID {1352DAF1-82AF-4504-A812-E42FCF223204} was invalid (__/__/1970) - changed it to 01/01/1970
The date for document with OID {603326C3-EA08-4FB8-822F-AB637ED8F903} was invalid (__/__/1970) - changed it to 01/01/1970
The date for document with OID {3637F2AA-9C8F-4DB7-9635-B222AB29B4E9} was invalid (__/__/1970) - changed it to 01/01/1970
The date for document with OID {2CD2530F-7F0C-4B03-83CC-7EA28181F946} was invalid (__/__/1970) - changed it to 01/01/1970
Skipping document 181/999 with OID {92074D6F-D350-4DF1-8071-703FC105C95F} because it's missing its XML file!! (stt exists: True)
Skipping document 183/999 with OID {20C35CAE-CE27-4CA1-92F6-7B92B1419D63} because it's missing its XML file!! (stt exists: False)
Skipping document 184/999 with OID {9EE38868-0F13-4372-A005-9E3761F893E3} because it's missing its XML file!! (stt exists: False)
Skipping document 193/999 with OID {E1B4FA2B-709D-4128-BA87-293C055A2B03} because it's missing its XML file!! (stt exists: False)
Skipping document 197/999 with OID {CD2ADA3A-E869-4DD4-8094-569E8ED71E23} because it's missing its XML file!! (stt exists: False)
Skipping document 199/999 with OID {CE88B2BA-DD41-430E-9B3C-448670CEC572} because it's missing its XML file!! (stt exists: False)
Skipping document 200/999 with OID {AE2C2B44-3C0B-4B58-8381-5815F25DFD56} because it's missing its XML file!! (stt exists: False)
Skipping document 202/999 with OID {EDB29B54-8E60-49FC-B606-11934A6C352E} because it's missing its XML file!! (stt exists: False)
Skipping document 208/999 with OID {2212C9CB-2C2B-4F4D-8D9D-719F7422DE83} because it's missing its XML file!! (stt exists: False)
Skipping document 209/999 with OID {416D6D7C-3879-4184-917B-9C53D9C02ABF} because it's missing its XML file!! (stt exists: False)
Skipping document 210/999 with OID {FC81B0F0-59EC-4222-86BE-334BB8BD3D30} because it's missing its XML file!! (stt exists: False)
Skipping document 216/999 with OID {7F715AEE-CAC5-4590-AF78-B3954A0AFFE5} because it's missing its XML file!! (stt exists: False)
Skipping document 221/999 with OID {EF9A114F-BFC4-4AEC-8769-7794668319B8} because it's missing its XML file!! (stt exists: False)
Skipping document 225/999 with OID {81025F9E-73EA-450A-8329-B5DA9362811B} because it's missing its XML file!! (stt exists: False)
Skipping document 226/999 with OID {2BAF6582-B1F5-4445-BEFD-EC10BB951916} because it's missing its XML file!! (stt exists: False)
Skipping document 228/999 with OID {84D92AC8-0308-4068-BACC-67F4628495B4} because it's missing its XML file!! (stt exists: False)

100%|██████████| 7/7 [00:25<00:00,  3.60s/it]

Skipping document 925/999 with OID {BE05F3C2-DB3A-4F75-8723-FD9C4A309F25} because it's missing its XML file!! (stt exists: False)
Skipping document 926/999 with OID {AEF84014-6F75-4E13-B131-BAF7145734D8} because it's missing its XML file!! (stt exists: False)
Skipping document 928/999 with OID {CBE81CAD-FC13-43C2-93E6-A9753F9D7FB9} because it's missing its XML file!! (stt exists: True)
Skipping document 934/999 with OID {2287776F-0223-4CA5-BEE2-D25C82C9BB31} because it's missing its XML file!! (stt exists: False)
Skipping document 938/999 with OID {CCC88B8F-024F-41D3-9730-1C6C54E0E7CE} because it's missing its XML file!! (stt exists: False)
Skipping document 944/999 with OID {075CD766-E9A8-4D97-A72B-5189A81811BC} because it's missing its XML file!! (stt exists: False)
Skipping document 947/999 with OID {47192059-AB51-47A5-A00B-6C18E932CC1F} because it's missing its XML file!! (stt exists: False)
Skipping document 951/999 with OID {DAA737B4-A669-4BCE-A558-0D83D0A1B7D6} because it's missing its XML file!! (stt exists: False)
Skipping document 952/999 with OID {6141AA34-E433-466F-A25A-9E3E61EBC247} because it's missing its XML file!! (stt exists: False)
Skipping document 953/999 with OID {FE1B8834-C99C-4AFE-9EBD-DB12B5975AEB} because it's missing its XML file!! (stt exists: False)
Skipping document 954/999 with OID {39B7E607-A9D4-4865-B473-D01B4626731B} because it's missing its XML file!! (stt exists: False)
Skipping document 955/999 with OID {006CA862-0EBF-41DC-88E0-8142E3FD92F9} because it's missing its XML file!! (stt exists: False)
Skipping document 956/999 with OID {E066C358-529A-42F7-9198-2968FA5949C8} because it's missing its XML file!! (stt exists: False)
Skipping document 957/999 with OID {FF3AEF7A-11D0-40EE-B949-23651C86AAEA} because it's missing its XML file!! (stt exists: False)
Skipping document 958/999 with OID {476C55EA-43BE-4B9A-BBE1-39CB26022D86} because it's missing its XML file!! (stt exists: False)
Skipping document 959/999 with OID {48DE27A6-F461-448F-9B3A-F37B73C0C01B} because it's missing its XML file!! (stt exists: False)
Skipping document 960/999 with OID {4B81684B-D5AC-497B-A3D6-7367A7A0386B} because it's missing its XML file!! (stt exists: False)
Skipping document 961/999 with OID {DA686172-FED4-4144-9706-0FF1387CE6D5} because it's missing its XML file!! (stt exists: False)
Skipping document 962/999 with OID {DD9311E6-3CCE-409A-B80B-BD3A07C851F0} because it's missing its XML file!! (stt exists: False)
Skipping document 963/999 with OID {9AF6CCE0-9F70-442E-9265-FCD79C48EAF6} because it's missing its XML file!! (stt exists: False)
Skipping document 964/999 with OID {667F0024-1296-4623-9065-69DF95716A7C} because it's missing its XML file!! (stt exists: False)
Skipping document 965/999 with OID {696116FC-74C0-497D-9B4B-C7CD690228E7} because it's missing its XML file!! (stt exists: False)
Skipping document 966/999 with OID {128B38F6-5473-4310-AC68-E7E9AF3E0865} because it's missing its XML file!! (stt exists: False)
Skipping document 967/999 with OID {930CEC63-87A6-4112-8ABE-79A87A6B5C99} because it's missing its XML file!! (stt exists: False)
Skipping document 968/999 with OID {EA0D64D2-81C1-4CFC-8504-B3028C36BF47} because it's missing its XML file!! (stt exists: False)
Skipping document 969/999 with OID {75714F10-F148-484A-A843-D33FC3307153} because it's missing its XML file!! (stt exists: False)
Skipping document 970/999 with OID {5F6DA703-0FAA-4826-B0FD-6C63B58D4020} because it's missing its XML file!! (stt exists: False)
Skipping document 971/999 with OID {51914C83-4DA8-47B2-ADE1-0B4AFE98C66D} because it's missing its XML file!! (stt exists: False)
Skipping document 972/999 with OID {120563D8-B0A3-4B47-9B8E-585204D759E2} because it's missing its XML file!! (stt exists: False)
Skipping document 973/999 with OID {D85BAB1B-4B5C-4270-A2FA-F7959890EC7C} because it's missing its XML file!! (stt exists: False)
Skipping document 976/999 with OID {3A987E3E-CE90-4DE1-878C-A968E0E00CD7} because it's missing its XML file!! (stt exists: False)
Skipping document 986/999 with OID {B3EC271A-4197-4464-AD27-0A61026B4289} because it's missing its XML file!! (stt exists: False)
Skipping document 987/999 with OID {4E958E20-FDBE-41E7-BB26-956D7910230D} because it's missing its XML file!! (stt exists: False)
Skipping document 988/999 with OID {DA786EFE-05AD-4424-878A-C5F704DDC380} because it's missing its XML file!! (stt exists: False)
Skipping document 989/999 with OID {1D38414F-5F97-4000-88AA-CD4272DCD7B8} because it's missing its XML file!! (stt exists: False)
Skipping document 990/999 with OID {DB9C45E9-A43F-467B-9D56-A539C2D23501} because it's missing its XML file!! (stt exists: False)
Skipping document 992/999 with OID {FA4E3D99-2256-4114-AA7D-54B604A98D76} because it's missing its XML file!! (stt exists: False)
Skipping document 996/999 with OID {10D4582E-FB27-463E-9990-980EC4106144} because it's missing its XML file!! (stt exists: True)
j_midi - returning 638 documents, 361 were skipped due to missing necessary info.
 --> Adding 4109 to the out csv for j_midi

21it [01:15, 15.38s/it]

PROCESSING PROGRAM j_nuit (22/47) - 1 files:

100%|██████████| 1/1 [00:00<00:00,  7.21it/s]
22it [01:16, 10.99s/it]

Starting extracting 35 documents for program j_nuit
Skipping document 1/35 with OID {7E1D0E93-ABEC-4578-9562-9F8014747173} because it's missing its XML file!! (stt exists: False)
Skipping document 2/35 with OID {EFDEA34F-913A-472A-9BBB-3FBADD88628C} because it's missing its XML file!! (stt exists: False)
Skipping document 6/35 with OID {E40023C5-247C-498F-B800-0E2BE4F8D082} because it's missing its XML file!! (stt exists: False)
Skipping document 7/35 with OID {F9325037-0119-4571-8FB9-D05CFA61C915} because it's missing its XML file!! (stt exists: True)
Skipping document 9/35 with OID {4ABA159F-6A72-4C82-A1A9-2D3615D2189B} because it's missing its XML file!! (stt exists: False)
Skipping document 10/35 with OID {674F05E6-1283-4E82-BB42-25ABB8C2EE3B} because it's missing its XML file!! (stt exists: True)
Skipping document 17/35 with OID {7A59CC55-3879-4BEB-B329-2867500FC1A2} because it's missing its XML file!! (stt exists: False)
Skipping document 18/35 with OID {9F466BFB-BA3E-4134-8AAE-800B684284A8} because it's missing its XML file!! (stt exists: False)
Skipping document 22/35 with OID {8C4BADC8-92F7-4410-BB56-614F10ACA084} because it's missing its XML file!! (stt exists: False)
Skipping document 23/35 with OID {0F3DCB9F-FE22-4BD4-9A9D-FBE9EDD5D103} because it's missing its XML file!! (stt exists: False)
Skipping document 25/35 with OID {C449F224-9501-4173-9425-5FBC48FEC2B8} because it's missing its XML file!! (stt exists: True)
Skipping document 28/35 with OID {0A975856-D999-4A5D-A5A6-6662727C78FE} because it's missing its XML file!! (stt exists: False)
Skipping document 31/35 with OID {79586A9D-8A31-4406-B288-31563CFA0596} because it's missing its XML file!! (stt exists: False)
Skipping document 32/35 with OID {A3ADB8A6-79F4-4A9E-A893-1FBE22903D1B} because it's missing its XML file!! (stt exists: True)
Did not find any date for doc with OID {C820E2C5-9659-49DB-958F-3339D98BAED2}. Trying to use the recording date. doc_dict: {'alias': 'j_nuit', 'date_str': None, 'stt_filename': 'C820E2C5-9659-49DB-958F-3339D98BAED2_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{C820E2C5-9659-49DB-958F-3339D98BAED2}', 'stripped_OID': 'C820E2C5-9659-49DB-958F-3339D98BAED2', 'login': '', 'broadcast_episode_title': "Mort de Georges Brassens. Extrait de l'interview du chanteur r?alis?e en 1975 ? Besan?on, avec les t?moignages de Raymond Devos et Guy B?art", 'sequence': '1', 'broadcast_program_name': 'Journal de nuit', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '04.01.2021 14:00:19', 'physical_support_history': "Cote d'origine: 31560 Pl. 22", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': "L'interview de 1975 a ?t? r?alis?e par Frank Musy et Jacques Donzel.", 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:04:23.904', 'work_duration_compl': 'Non', 'participants': [{'name': 'Brassens, Georges', 'function': 'Interview?/e', 'role': 'chanteur (Archives RTS, 1975)'}, {'name': 'Devos, Raymond', 'function': 'Interview?/e', 'role': 'humoriste'}, {'name': 'B?art, Guy', 'function': 'Interview?/e', 'role': 'chanteur'}, {'name': 'Musy, Frank', 'function': 'Pr?sentateur/trice', 'role': 'collaborateur RSR'}, {'name': 'Donzel, Jacques', 'function': 'Pr?sentateur/trice', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Paris'], 'person_descriptors': ['Brassens, Georges'], 'thematical_descriptors': ['chanteur', 'Dieu'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Interview'], 'recording_dates': ['30/10/1981 - 30/10/1981'], 'first_broadcast_dates': None}
Skipping document 35/35 with OID {67094B89-299B-4745-A645-26B4F5CE8101} because it's missing its XML file!! (stt exists: False)
j_nuit - returning 20 documents, 15 were skipped due to missing necessary info.
 --> Adding 20 to the out csv for j_nuit

PROCESSING PROGRAM j_soir (23/47) - 8 files:

Starting extracting 999 documents for program j_soir
Skipping document 2/999 with OID {1FA80336-ACBF-49C7-9DB2-39D255A66187} because it's missing its XML file!! (stt exists: False)
Skipping document 3/999 with OID {C36D5146-6E66-431B-A487-0130E43DBB8F} because it's missing its XML file!! (stt exists: False)
Skipping document 4/999 with OID {26FD5AB7-0E2C-42CB-B190-78B6AEC08F43} because it's missing its XML file!! (stt exists: False)
Skipping document 7/999 with OID {E7DACDF7-D579-48D3-AC76-BF94A39793C0} because it's missing its XML file!! (stt exists: False)
Skipping document 9/999 with OID {7BE6AE82-31FA-450A-9168-50CBCA4437B7} because it's missing its XML file!! (stt exists: False)
Skipping document 11/999 with OID {E7E62159-6D0A-460F-8AC0-5EC0F77A0FD5} because it's missing its XML file!! (stt exists: False)
Skipping document 13/999 with OID {8A906148-4A41-477C-988F-A3D194438C88} because it's missing its XML file!! (stt exists: False)
Skipping document 16/999 with OID {70AB66A7-5D5F-4233-812B-60CD47F22E36} because it's missing its XML file!! (stt exists: True)
Skipping document 17/999 with OID {491B72B4-131C-4977-90BE-D5794525D250} because it's missing its XML file!! (stt exists: False)
Skipping document 18/999 with OID {1B200AFB-E518-4417-934D-D802D77C151B} because it's missing its XML file!! (stt exists: False)
Skipping document 20/999 with OID {1433AABB-BDCD-4DCE-AAAC-F6D627D2F910} because it's missing its XML file!! (stt exists: False)
Skipping document 23/999 with OID {6846EB49-FD53-44FE-8A80-6DB6EAF39006} because it's missing its XML file!! (stt exists: False)
Skipping document 24/999 with OID {EE020335-49E3-4AC7-8992-70CC503AAB5C} because it's missing its XML file!! (stt exists: False)
Skipping document 25/999 with OID {7270C0C0-C711-433A-8F02-6D51CC0D909A} because it's missing its XML file!! (stt exists: False)
Skipping document 26/999 with OID {55BD6F3A-464D-4A59-A227-746B67BBB581} because it's missing its XML file!! (stt exists: False)
Skipping document 30/999 with OID {1247F70C-8B7C-4986-BB42-A267158BC95C} because it's missing its XML file!! (stt exists: False)
Skipping document 34/999 with OID {DF7E6F26-4C81-479C-9848-FF3E9CF5DCA0} because it's missing its XML file!! (stt exists: False)
Skipping document 35/999 with OID {3A21AA16-523C-4D31-803E-F77430EF48A7} because it's missing its XML file!! (stt exists: False)
Skipping document 36/999 with OID {9B774B6D-1717-43E2-BFEF-C5CD1619BF92} because it's missing its XML file!! (stt exists: False)
Skipping document 40/999 with OID {A3FDC3D4-9834-458F-84B4-B0050871D2F0} because it's missing its XML file!! (stt exists: False)
Skipping document 49/999 with OID {26E8D3C8-5CDF-46CC-8C9F-38A39144EA43} because it's missing its XML file!! (stt exists: False)
Skipping document 52/999 with OID {B23C915E-0404-4762-A985-258C416BD580} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {AD571C94-FB53-4F0F-AD48-C6342112C6CD}. Trying to use the recording date. doc_dict: {'alias': 'j_soir', 'date_str': None, 'stt_filename': 'AD571C94-FB53-4F0F-AD48-C6342112C6CD_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{AD571C94-FB53-4F0F-AD48-C6342112C6CD}', 'stripped_OID': 'AD571C94-FB53-4F0F-AD48-C6342112C6CD', 'login': '', 'broadcast_episode_title': 'Interview de L?on Schlumpf, pr?sident de la Conf?d?ration : A propos du projet de limitation de la vitesse sur les autoroutes', 'sequence': '1', 'broadcast_program_name': 'Journal du soir', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '09.03.2023 11:44:25', 'physical_support_history': "Cote d'origine: 35162 Pl. 23", 'production_type': 'Production propre', 'recording_place': 'Locarno (Festival)', 'rights_notes': 'Memoriav (SRG 75)', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Il indique que le projet de limitation de vitesse sur les semi-autoroutes et les autoroutes ? 80 et 100 km/h sera discut? par le Conseil f?d?ral les semaines suivantes et une d?cision suivra, la proc?dure de consultation ne sera pas d?terminante.', 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:01:32.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Schlumpf, Leon', 'function': 'Interview?/e', 'role': 'pr?sident de la Conf?d?ration'}, {'name': 'Inconnu', 'function': 'Intervieweur/euse', 'role': 'journal de la RTSI'}, {'name': 'Pop, Georges', 'function': 'Pr?sentateur/trice', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Suisse'], 'person_descriptors': None, 'thematical_descriptors': ['autoroute', 'vitesse (physique)'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Commentaire', 'Interview'], 'recording_dates': ['12/08/1984 - 12/08/1984'], 'first_broadcast_dates': None}
Skipping document 57/999 with OID {C92E106E-4212-4DD1-8CED-61496C98AC59} because it's missing its XML file!! (stt exists: False)
Skipping document 59/999 with OID {5FDF1DB9-37F0-4884-BFCF-96D6C0E8F480} because it's missing its XML file!! (stt exists: False)
Skipping document 61/999 with OID {A9FC7B74-60AF-4A07-A645-007B8C5C6FEB} because it's missing its XML file!! (stt exists: False)
Skipping document 64/999 with OID {2EE4FC70-2CEF-4B43-BEC1-B7D8E4B3A0E9} because it's missing its XML file!! (stt exists: False)
Skipping document 65/999 with OID {91DB9A60-903F-4B87-B69A-38AA7102BDBF} because it's missing its XML file!! (stt exists: False)
Skipping document 66/999 with OID {952520B1-0FE4-432C-9928-0CADE1EC0431} because it's missing its XML file!! (stt exists: False)
Skipping document 96/999 with OID {C406329E-57B0-47B0-AD17-028CAFCF7EB4} because it's missing its XML file!! (stt exists: False)
Skipping document 124/999 with OID {EFDAF436-C87A-44A1-97E3-72562F60CCAE} because it's missing its XML file!! (stt exists: False)
Skipping document 127/999 with OID {CA8F7735-F237-4FA3-9E7D-700CC241E276} because it's missing its XML file!! (stt exists: False)
Skipping document 128/999 with OID {41D1BC81-FF47-4F68-89D5-267BD6466B09} because it's missing its XML file!! (stt exists: False)
Skipping document 131/999 with OID {63C4E693-3B1C-4F17-BA8A-1DFC29EBB346} because it's missing its XML file!! (stt exists: False)
Skipping document 132/999 with OID {A86ABAB3-6DA1-4BEB-BC40-09A0BFC41ABB} because it's missing its XML file!! (stt exists: True)
Skipping document 134/999 with OID {5A3FC37A-A30A-4486-8B31-8A39E6BE5318} because it's missing its XML file!! (stt exists: False)
Skipping document 135/999 with OID {B5CFDCB0-E103-4422-BAA3-FF09DE817E4D} because it's missing its XML file!! (stt exists: False)
Skipping document 136/999 with OID {A5EF494A-CF48-4F18-AA2A-0A020F4A0C90} because it's missing its XML file!! (stt exists: False)
Skipping document 137/999 with OID {6F6334DF-85CE-4412-836C-6C18F9CBF933} because it's missing its XML file!! (stt exists: False)
Skipping document 138/999 with OID {C7D973FE-B070-4F8B-A843-9A4FE37C0C84} because it's missing its XML file!! (stt exists: False)
Skipping document 139/999 with OID {C690EEFF-A8E8-4A6F-A8A9-9A591FBB52CD} because it's missing its XML file!! (stt exists: False)
Skipping document 144/999 with OID {28BD41ED-7069-4FD3-BCAC-E8D5912CA2ED} because it's missing its XML file!! (stt exists: False)
Skipping document 145/999 with OID {4A296BE4-EEB9-45BA-9A02-BC1E16DB652D} because it's missing its XML file!! (stt exists: False)
Skipping document 148/999 with OID {223AA14E-8EDB-4397-BCB8-FF250B8AAC6F} because it's missing its XML file!! (stt exists: False)
Skipping document 149/999 with OID {BD3904A9-952B-4317-AA2D-DADB077C26B7} because it's missing its XML file!! (stt exists: False)
Skipping document 150/999 with OID {B4805079-1EAE-4AB7-8DE8-3B246BC1B155} because it's missing its XML file!! (stt exists: False)
Skipping document 151/999 with OID {AA5E6B2C-FE49-4336-A9C5-10EB6B3B25E8} because it's missing its XML file!! (stt exists: False)
Skipping document 152/999 with OID {9A57752C-EEF4-465B-A356-BBE387895565} because it's missing its XML file!! (stt exists: False)
Skipping document 154/999 with OID {425F7399-85AD-4AD7-B4CD-AF18BD29407E} because it's missing its XML file!! (stt exists: False)
Skipping document 155/999 with OID {50B21819-B023-47C8-A3AC-DF8316627669} because it's missing its XML file!! (stt exists: False)
Skipping document 156/999 with OID {DD242ABF-6554-4047-BA88-D9216B50D6F5} because it's missing its XML file!! (stt exists: False)
Skipping document 157/999 with OID {690BFE6B-3DE5-4239-A975-D61EAC383C9D} because it's missing its XML file!! (stt exists: False)
Skipping document 160/999 with OID {A87E1F50-AD70-4A2B-96C3-F4A935181746} because it's missing its XML file!! (stt exists: False)
Skipping document 161/999 with OID {43DBF1C2-63FC-43B1-900D-87AE8DA7410B} because it's missing its XML file!! (stt exists: False)
Skipping document 164/999 with OID {B78AE1E2-06C1-499F-B693-E20477183ACE} because it's missing its XML file!! (stt exists: False)
Skipping document 172/999 with OID {9367FF27-C7FA-460B-948D-518222171824} because it's missing its XML file!! (stt exists: False)
Skipping document 173/999 with OID {0F5511A2-1C4C-4AB1-A488-BE8C1B9D50E3} because it's missing its XML file!! (stt exists: False)
Skipping document 174/999 with OID {7AC6048D-22E6-4D37-8188-6A5455F27D36} because it's missing its XML file!! (stt exists: False)
Skipping document 175/999 with OID {60CE9B3C-8C7E-4381-84A2-D5F7C4C734B3} because it's missing its XML file!! (stt exists: False)
Skipping document 178/999 with OID {D7AFA311-AFC1-4B90-9D1B-17374F94FD5B} because it's missing its XML file!! (stt exists: False)
Skipping document 182/999 with OID {2025A560-E673-4B3A-AB3B-220B1DFEC21F} because it's missing its XML file!! (stt exists: False)
Skipping document 183/999 with OID {B1417397-FDA2-4C69-8CDF-0EC2765AFE4C} because it's missing its XML file!! (stt exists: False)
Skipping document 186/999 with OID {E20F5E22-DF4D-41F7-B8A7-B11E28647742} because it's missing its XML file!! (stt exists: False)
Skipping document 188/999 with OID {D22FDD12-C195-45FA-B411-DA44529337BC} because it's missing its XML file!! (stt exists: False)
Skipping document 194/999 with OID {9D7E64A0-2A00-4A7F-A6BD-8203EB1CB93F} because it's missing its XML file!! (stt exists: False)
Skipping document 197/999 with OID {A804872F-B561-41EC-9A8F-4D6F05F259D6} because it's missing its XML file!! (stt exists: False)
Skipping document 200/999 with OID {7BB33237-DF76-4FEC-BAA3-93A27213FFF6} because it's missing its XML file!! (stt exists: False)
Skipping document 201/999 with OID {3295706F-E764-4F8D-851B-3B0867523C0D} because it's missing its XML file!! (stt exists: False)
Skipping document 202/999 with OID {6B88E1D0-FB59-4A30-A260-DC311E874188} because it's missing its XML file!! (stt exists: False)
Skipping document 204/999 with OID {3BDAFCD9-498A-4AAE-A9D0-49BC93C1BAAB} because it's missing its XML file!! (stt exists: False)
Skipping document 205/999 with OID {289A0D0C-F60D-424C-AFE3-B62C9C164CE7} because it's missing its XML file!! (stt exists: False)
Skipping document 207/999 with OID {C8C398E5-5ACA-4DCB-8C0D-CD0D89688CF7} because it's missing its XML file!! (stt exists: False)
Skipping document 209/999 with OID {5D51DF9C-DF72-4008-947D-4C54F72C448B} because it's missing its XML file!! (stt exists: False)
Skipping document 212/999 with OID {A0AE53EF-CA51-4519-8FC8-D51045E11CEB} because it's missing its XML file!! (stt exists: False)
Skipping document 220/999 with OID {FD321D57-DF37-48FA-8757-39DB3FF6A40B} because it's missing its XML file!! (stt exists: False)
Skipping document 221/999 with OID {A80BAE22-2495-4714-9379-CA013D4ACD3B} because it's missing its XML file!! (stt exists: False)
Skipping document 223/999 with OID {7CCE1AEF-C384-4E04-8A84-687C665D41AC} because it's missing its XML file!! (stt exists: False)
Skipping document 226/999 with OID {1AD2268F-1BA9-4341-9062-378EFA242E50} because it's missing its XML file!! (stt exists: False)
Skipping document 228/999 with OID {112EC8D7-0D44-4DC4-B4DA-ED3F0AF84491} because it's missing its XML file!! (stt exists: False)
Skipping document 229/999 with OID {5DCFF27F-2806-4BC3-8FEF-3655AA457022} because it's missing its XML file!! (stt exists: False)
Skipping document 230/999 with OID {9040D1E4-8CFC-4EA6-AF28-900D592F32B4} because it's missing its XML file!! (stt exists: False)
Skipping document 232/999 with OID {7A8CF210-856C-4BDF-8BDC-A4146D587D94} because it's missing its XML file!! (stt exists: False)
Skipping document 235/999 with OID {8CC188EB-4564-49B7-B39D-D20E20E438E7} because it's missing its XML file!! (stt exists: False)
Skipping document 240/999 with OID {6F7537C7-DA2A-4E01-B0DC-41C85E3B0DA4} because it's missing its XML file!! (stt exists: False)
Skipping document 242/999 with OID {C10BB8B9-7119-46D4-97B6-50AFF6477332} because it's missing its XML file!! (stt exists: False)
Skipping document 245/999 with OID {3E1CF79A-8743-4B40-8C7B-296B2D456F3E} because it's missing its XML file!! (stt exists: False)
Skipping document 246/999 with OID {243E78CF-C570-4E24-8254-1564B7B2C362} because it's missing its XML file!! (stt exists: False)
Skipping document 247/999 with OID {98E6089A-5C54-4F1B-9039-0B30BB0AB381} because it's missing its XML file!! (stt exists: False)
Skipping document 248/999 with OID {9701120D-F7DC-425D-A1EE-CD73B99A32CE} because it's missing its XML file!! (stt exists: False)
Skipping document 249/999 with OID {9546D815-4B1E-4E74-BC03-CB2507891013} because it's missing its XML file!! (stt exists: False)
Skipping document 250/999 with OID {76D5258B-8CA9-45D1-B8E1-BC7658735758} because it's missing its XML file!! (stt exists: False)
Skipping document 251/999 with OID {FF779A8E-8EE3-46AC-9050-A939E202566B} because it's missing its XML file!! (stt exists: False)
Skipping document 252/999 with OID {59F9A80C-4C1C-41F6-94C3-6E17E955308A} because it's missing its XML file!! (stt exists: False)
Skipping document 253/999 with OID {F2E16367-88A4-4497-BF9F-7997967FC23C} because it's missing its XML file!! (stt exists: False)
Skipping document 254/999 with OID {81171E94-BF9F-4452-97DD-1CA54F660F17} because it's missing its XML file!! (stt exists: False)
Skipping document 255/999 with OID {5731BBCE-E7B7-4400-8A5C-8D451812DB76} because it's missing its XML file!! (stt exists: False)
Skipping document 256/999 with OID {F90B30B0-BA3B-4A44-9876-E4D292A78308} because it's missing its XML file!! (stt exists: False)
Skipping document 257/999 with OID {981AAA4F-8466-4C91-9F4E-20438BDE4711} because it's missing its XML file!! (stt exists: False)
Skipping document 259/999 with OID {17E1302E-B969-49DD-A765-20D2CF65F46D} because it's missing its XML file!! (stt exists: False)
Skipping document 260/999 with OID {FE31B922-49AB-45C1-906C-9D648932E430} because it's missing its XML file!! (stt exists: False)
Skipping document 261/999 with OID {744DB291-0089-4794-BED9-19E615837F9B} because it's missing its XML file!! (stt exists: False)
Skipping document 262/999 with OID {6145C349-8CF6-458A-BE61-E68AF8D6D12F} because it's missing its XML file!! (stt exists: False)
Skipping document 266/999 with OID {6CFE15DD-D644-44B6-9A11-8446C40E11F1} because it's missing its XML file!! (stt exists: False)
Skipping document 267/999 with OID {1CC868E1-0D1C-472D-B167-C6E0858A3665} because it's missing its XML file!! (stt exists: False)
Skipping document 269/999 with OID {A1DACD61-44C5-448D-A7EF-47B5C1416EC6} because it's missing its XML file!! (stt exists: False)
Skipping document 271/999 with OID {CEE20111-1FE4-4961-9BB2-9E24A85F2A45} because it's missing its XML file!! (stt exists: False)
Skipping document 272/999 with OID {9DD778ED-575C-4572-BB6C-CEFA47CBC403} because it's missing its XML file!! (stt exists: False)
Skipping document 273/999 with OID {744E97DD-D314-4EED-86A8-74805D8CC8DF} because it's missing its XML file!! (stt exists: False)
Skipping document 275/999 with OID {79D6552C-CEEB-4311-8D1A-FEA56488C8AB} because it's missing its XML file!! (stt exists: False)
Skipping document 276/999 with OID {A3A6C551-23B9-401B-BEE4-65E03168015A} because it's missing its XML file!! (stt exists: False)
Skipping document 277/999 with OID {5E2F5D07-7575-4024-AE35-8D9294C21205} because it's missing its XML file!! (stt exists: False)
Skipping document 278/999 with OID {E319705A-5B22-4534-BF88-2A67249EC342} because it's missing its XML file!! (stt exists: False)
Skipping document 279/999 with OID {F5CD2B89-6B1C-47CD-BD22-C18E2B009434} because it's missing its XML file!! (stt exists: False)
Skipping document 280/999 with OID {1206E9C0-BA3F-4C3F-B4AA-DC15C12CBE3D} because it's missing its XML file!! (stt exists: False)
Skipping document 281/999 with OID {D02DC941-6A89-4E0C-8A57-B8FD26744110} because it's missing its XML file!! (stt exists: False)
Skipping document 282/999 with OID {B2ADB675-FC60-4FF5-B7BC-138B5929BEAF} because it's missing its XML file!! (stt exists: False)
Skipping document 283/999 with OID {07DA048E-7F63-424E-A327-37FB8BDB7B7A} because it's missing its XML file!! (stt exists: False)
Skipping document 284/999 with OID {3210D9D1-DC31-4561-A04B-A5CD58E88B56} because it's missing its XML file!! (stt exists: False)
Skipping document 285/999 with OID {2A8CBAEA-6D3A-4D07-B91C-0A752107AFD0} because it's missing its XML file!! (stt exists: False)
Skipping document 286/999 with OID {3366521E-3BCC-4E4F-9CBE-BBADD5DE9058} because it's missing its XML file!! (stt exists: False)
Skipping document 287/999 with OID {AB99109B-2118-4891-99A6-7F7900E8705E} because it's missing its XML file!! (stt exists: False)
Skipping document 291/999 with OID {8E8657C7-361E-4F27-934C-7E0C40FA169B} because it's missing its XML file!! (stt exists: False)
Skipping document 294/999 with OID {33E62AF7-1351-4894-931A-03EB18A62E8C} because it's missing its XML file!! (stt exists: False)
Skipping document 298/999 with OID {B113FFB7-7A5F-4759-B453-7CAEC46D59B4} because it's missing its XML file!! (stt exists: False)
Skipping document 301/999 with OID {3680898E-E348-406C-B14D-16826F000B55} because it's missing its XML file!! (stt exists: False)
Skipping document 302/999 with OID {9E336F14-EC0D-476B-8E88-15D70A3CA5F1} because it's missing its XML file!! (stt exists: False)
Skipping document 303/999 with OID {495D90F3-F989-48ED-A9CB-873FFD3DA4A1} because it's missing its XML file!! (stt exists: False)
Skipping document 304/999 with OID {9FE065E8-94CC-45A9-AE79-F6CA51CC48EF} because it's missing its XML file!! (stt exists: False)
Skipping document 305/999 with OID {696844A0-16FC-4218-BEB3-A211411C2035} because it's missing its XML file!! (stt exists: False)
Skipping document 306/999 with OID {210EF0EC-7478-4C0E-B8F5-D8527339E1FC} because it's missing its XML file!! (stt exists: False)
Skipping document 308/999 with OID {5ADF3ED0-7DF1-4ED4-BC2F-453B75C9FB17} because it's missing its XML file!! (stt exists: False)
Skipping document 309/999 with OID {FBD03B00-DF34-4304-B3B0-CC96AAA75440} because it's missing its XML file!! (stt exists: False)
Skipping document 310/999 with OID {1507D523-62E3-46AB-91FF-6ACB69F2CC53} because it's missing its XML file!! (stt exists: False)
Skipping document 311/999 with OID {DDED2CD0-7875-4B88-A8EA-66D50CE328E0} because it's missing its XML file!! (stt exists: False)
Skipping document 313/999 with OID {4D14AF82-FADA-4E79-B1EB-0FE445BC9F34} because it's missing its XML file!! (stt exists: False)
Skipping document 317/999 with OID {F29B76C0-F2C1-4EEF-B00E-BFAA0D0BF93E} because it's missing its XML file!! (stt exists: False)
Skipping document 321/999 with OID {6A6FE259-498D-425C-BAD7-776873770CE7} because it's missing its XML file!! (stt exists: False)
Skipping document 327/999 with OID {76EA80FB-29BA-423A-AB6A-172FE1A1555F} because it's missing its XML file!! (stt exists: False)

Skipping document 959/999 with OID {079CFE6A-C699-459F-95C3-A71FBCC36A70} because it's missing its XML file!! (stt exists: False)
Skipping document 962/999 with OID {005B8200-7DF0-4015-B851-2DA193D70C37} because it's missing its XML file!! (stt exists: True)
Skipping document 963/999 with OID {9F25FEE8-F069-49EA-BDA2-CF46B8C1575A} because it's missing its XML file!! (stt exists: False)
Skipping document 974/999 with OID {207325E3-F25F-44B1-BD08-C2321B274853} because it's missing its XML file!! (stt exists: False)
Skipping document 975/999 with OID {6FE044B4-CF8A-49E7-8B8D-15197EDCD1D6} because it's missing its XML file!! (stt exists: False)
Skipping document 976/999 with OID {C6A9A08E-20A9-4ED4-92F2-E2702E444CBE} because it's missing its XML file!! (stt exists: False)
Skipping document 980/999 with OID {06C7AA23-EC61-45F7-B008-9BE58A8981DE} because it's missing its XML file!! (stt exists: False)
Skipping document 981/999 with OID {A945506D-4863-467C-A33F-880FA35AD01B} because it's missing its XML file!! (stt exists: False)
Skipping document 989/999 with OID {5E155DD1-855F-4663-AE7A-38F64B17C36D} because it's missing its XML file!! (stt exists: True)
Skipping document 993/999 with OID {CCB50731-DEB6-4D39-8360-D256D602464A} because it's missing its XML file!! (stt exists: False)
j_soir - returning 637 documents, 362 were skipped due to missing necessary info.

Starting extracting 999 documents for program j_soir
Skipping document 4/999 with OID {B06B9A2E-7650-4009-919D-19BBBB39A16E} because it's missing its XML file!! (stt exists: False)
Skipping document 5/999 with OID {C0A5214E-DD95-4805-BAB6-B8C32DD86E58} because it's missing its XML file!! (stt exists: False)
Skipping document 6/999 with OID {D61B5F22-47FE-45A6-BD9F-D3C42C07CEB2} because it's missing its XML file!! (stt exists: False)
Skipping document 7/999 with OID {8285015E-A17E-423E-BDCE-6EA873FF5239} because it's missing its XML file!! (stt exists: False)
Skipping document 8/999 with OID {436CA1FD-BA82-47FE-94E8-FB72DE7D8CE1} because it's missing its XML file!! (stt exists: False)
Skipping document 10/999 with OID {5C9753B3-5BF0-4567-8498-4A28C9358E23} because it's missing its XML file!! (stt exists: False)
Skipping document 14/999 with OID {D4EF76CD-7A83-426B-B752-00DC48AF6B6B} because it's missing its XML file!! (stt exists: False)
Skipping document 21/999 with OID {811C7BD1-FA44-4DEB-9918-34CBC4454F09} because it's missing its XML file!! (stt exists: False)
Skipping document 22/999 with OID {E3876ADE-B1E2-4D51-B889-8CB5C3D6435F} because it's missing its XML file!! (stt exists: False)
Skipping document 24/999 with OID {C9898322-D5F7-44A6-AC3C-CF1912E0DAC2} because it's missing its XML file!! (stt exists: False)
Skipping document 37/999 with OID {15E58807-0AAA-40A0-9238-F94FAADED1FD} because it's missing its XML file!! (stt exists: True)
Skipping document 38/999 with OID {A8C3310D-6ACC-4A88-8418-4EEF195F91FE} because it's missing its XML file!! (stt exists: False)
Skipping document 40/999 with OID {3B9D77AC-8307-4FD8-849F-88867EFA330B} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {6A27BB53-4248-44A2-91CB-7F43CF9BDF81}. Trying to use the recording date. doc_dict: {'alias': 'j_soir', 'date_str': None, 'stt_filename': '6A27BB53-4248-44A2-91CB-7F43CF9BDF81_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{6A27BB53-4248-44A2-91CB-7F43CF9BDF81}', 'stripped_OID': '6A27BB53-4248-44A2-91CB-7F43CF9BDF81', 'login': '', 'broadcast_episode_title': 'Entr?e en vigueur officielle de la nouvelle orthographe : Pr?sentation et enjeux', 'sequence': '1', 'broadcast_program_name': 'Journal du soir', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'saudouce', 'modified_on': '08.06.2022 23:15:06', 'physical_support_history': "Cote d'origine: 13456", 'production_type': 'Production propre', 'recording_place': 'Studio Radio-Lausanne ; Paris', 'rights_notes': 'Memoriav. Interview de Renaud appartient ? Radio-France.', 'rights_status': 'A rechercher', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Extrait d\'une chanson de Serge Gainsbourg "En relisant ta lettre". La Suisse n\'a pas ?t? consult?e mais se conformera probablement. Renaud rejette certaines modifications et continuera ? utiliser accents cinconflexes et tr?mas.', 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:06:25.165', 'work_duration_compl': 'Non', 'participants': [{'name': 'Duployer, Didier', 'function': 'Pr?sentateur/trice', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Kottelat, Philippe', 'function': 'Commentateur/trice', 'role': 'collaborateur Radio-Lausane ? Paris'}, {'name': 'Gerbex, Robert', 'function': 'Interview?/e', 'role': 'secr?taire g?n?ral de la Conf?rence des chefs du DIP de Suisse Romande et du Tessin'}, {'name': 'Gfeller, Urs', 'function': 'Intervieweur/euse', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Renaud', 'function': "Auteur d'une d?claration", 'role': "chanteur (Extrait d'une interview sur Radio-France)"}], 'geographical_descriptors': ['France', 'Suisse'], 'person_descriptors': ['Renaud', 'Gainbourg, Serge'], 'thematical_descriptors': ['orthographe', 'fran?ais r?nov?', 'langue fran?aise'], 'rights_usage_possibilities': ['FM'], 'radio_channels': None, 'subdomains': ['Interview', 'Commentaire'], 'recording_dates': ['06/12/1990 - 06/12/1990'], 'first_broadcast_dates': None}
Skipping document 45/999 with OID {D54ED863-2B24-43B6-95E7-13D7DDF28C26} because it's missing its XML file!! (stt exists: False)
Skipping document 48/999 with OID {46E70F02-EC3F-4408-BE4A-740B38BA59B5} because it's missing its XML file!! (stt exists: False)
Skipping document 56/999 with OID {4D470737-2A36-4329-BF05-0B129857D929} because it's missing its XML file!! (stt exists: False)
Skipping document 60/999 with OID {A738CA60-CE89-4D0F-A3F2-311E8D627012} because it's missing its XML file!! (stt exists: False)
Skipping document 69/999 with OID {75365B34-67CF-4265-829E-CB90A26AAA12} because it's missing its XML file!! (stt exists: False)
Skipping document 77/999 with OID {585406CA-4FEF-43CF-A036-379FD610B3F6} because it's missing its XML file!! (stt exists: False)
Skipping document 92/999 with OID {122D5C84-3308-47C6-9FB1-6587F01F3DF6} because it's missing its XML file!! (stt exists: False)
Skipping document 96/999 with OID {87C6A479-1BD8-4DF7-A8D1-4DE4C874F12D} because it's missing its XML file!! (stt exists: False)
Skipping document 97/999 with OID {B1C07DE0-FDB2-4E46-86A8-D52F7AE23FBB} because it's missing its XML file!! (stt exists: False)
Skipping document 101/999 with OID {AA432C20-3D29-4487-BC45-3E20B3EFB010} because it's missing its XML file!! (stt exists: False)
Skipping document 102/999 with OID {F95BF907-1993-4956-8E9E-E1B94E8E98D2} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {B56E8C11-6142-4E4B-8711-BD77B590DFE5}. Trying to use the recording date. doc_dict: {'alias': 'j_soir', 'date_str': None, 'stt_filename': 'B56E8C11-6142-4E4B-8711-BD77B590DFE5_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{B56E8C11-6142-4E4B-8711-BD77B590DFE5}', 'stripped_OID': 'B56E8C11-6142-4E4B-8711-BD77B590DFE5', 'login': '', 'broadcast_episode_title': "Espagne. Tentative de coup d'Etat aux Cort?s : Extrait du discours de Juan Carlos I, roi d'Espagne [en espagnol]", 'sequence': '1', 'broadcast_program_name': 'Journal du soir', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'prongudo', 'modified_on': '09.03.2023 12:22:13', 'physical_support_history': "Cote d'origine: 33763.03.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Son non diffus?', 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:34.122', 'work_duration_compl': 'Non', 'participants': [{'name': "Juan Carlos Ier (roi d'Espagne)", 'function': "Auteur d'une d?claration", 'role': "roi d'Espagne"}], 'geographical_descriptors': ['Espagne'], 'person_descriptors': ['Terejo, Antonio'], 'thematical_descriptors': ["coup d'Etat", 'd?mocratie (r?gime)'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Premier programme'], 'subdomains': ['D?claration'], 'recording_dates': ['24/02/1981 - 24/02/1981'], 'first_broadcast_dates': None}
Skipping document 109/999 with OID {D976D578-41DB-486E-A003-8E245B86803A} because it's missing its XML file!! (stt exists: False)
Skipping document 110/999 with OID {9EE4B0FD-FD77-4484-9582-265EC5D74F02} because it's missing its XML file!! (stt exists: False)
Skipping document 118/999 with OID {98F91148-ADFF-47D8-B906-0A871A34C7DE} because it's missing its XML file!! (stt exists: False)
Skipping document 121/999 with OID {CED85261-93C6-4B8B-BFCF-8C89C2EBA1E1} because it's missing its XML file!! (stt exists: False)
Skipping document 122/999 with OID {FD692864-8244-425B-8FE0-E0E24DEF28D5} because it's missing its XML file!! (stt exists: False)
Skipping document 123/999 with OID {87B71D10-BE99-4E4A-AAAF-C8B3725AD59B} because it's missing its XML file!! (stt exists: False)
Skipping document 131/999 with OID {F424C7EC-84E1-432D-9699-1001A0A37AAE} because it's missing its XML file!! (stt exists: False)
Skipping document 132/999 with OID {3BD9321B-C3F8-4F45-A502-7E7A64B439F4} because it's missing its XML file!! (stt exists: False)
Skipping document 133/999 with OID {F9BAE830-9DF2-4277-95CA-D8C7DF18039D} because it's missing its XML file!! (stt exists: False)
Skipping document 139/999 with OID {47718A32-8E0F-4D7A-9AA7-CF60E3093251} because it's missing its XML file!! (stt exists: False)
Skipping document 140/999 with OID {8EE62DED-C499-4DDD-A3DF-E492A949B71E} because it's missing its XML file!! (stt exists: False)
Skipping document 147/999 with OID {FE030750-C6DB-4D70-9108-98393AD33198} because it's missing its XML file!! (stt exists: False)
Skipping document 149/999 with OID {A40F5D47-3AD7-48F5-84C7-09D5E997B0E1} because it's missing its XML file!! (stt exists: False)
Skipping document 154/999 with OID {D48C6735-B3E8-475C-8B9B-5A037E504C18} because it's missing its XML file!! (stt exists: False)
Skipping document 160/999 with OID {D37522CC-C2DD-49A7-AF23-9A9DC0D57B71} because it's missing its XML file!! (stt exists: True)
Skipping document 161/999 with OID {A5B86E54-3A88-48EA-9BCF-11954D8A7C7B} because it's missing its XML file!! (stt exists: True)
Skipping document 162/999 with OID {D7813A51-EA90-4474-8677-2CECA7C6A496} because it's missing its XML file!! (stt exists: False)
Skipping document 164/999 with OID {99500A17-9853-45C4-8EDF-786459659A84} because it's missing its XML file!! (stt exists: False)
Skipping document 165/999 with OID {F6166A7B-CF8B-41D2-9124-AF84EE75052A} because it's missing its XML file!! (stt exists: False)
Skipping document 177/999 with OID {4BF40513-EECF-4EC9-9222-6CACAAA7C167} because it's missing its XML file!! (stt exists: False)
Skipping document 178/999 with OID {D476E588-8570-4AA1-97F2-051EE3A27833} because it's missing its XML file!! (stt exists: False)
Skipping document 179/999 with OID {DB301C0C-7D90-42F2-87C2-1243F2FBB96C} because it's missing its XML file!! (stt exists: True)
Skipping document 180/999 with OID {77D39950-59CD-4A8E-92C4-8B45FEB9D034} because it's missing its XML file!! (stt exists: False)
Skipping document 181/999 with OID {65A7A731-CF79-4113-BF7B-F6B60A213366} because it's missing its XML file!! (stt exists: False)
Skipping document 183/999 with OID {D613F4DE-0976-4D13-A4A8-CC1EBB067A89} because it's missing its XML file!! (stt exists: False)
Skipping document 186/999 with OID {628E6D77-8058-4306-B1BA-82D99328DA4B} because it's missing its XML file!! (stt exists: False)
Skipping document 187/999 with OID {A6A1D175-99F8-4F8B-8949-741F0A62328B} because it's missing its XML file!! (stt exists: False)
Skipping document 190/999 with OID {BCEA02DD-E2B3-45FC-8F33-6AB18F9221C7} because it's missing its XML file!! (stt exists: False)
Skipping document 192/999 with OID {365A382E-8FB1-48EE-9928-01ADA2C5D68D} because it's missing its XML file!! (stt exists: False)
Skipping document 193/999 with OID {958B06FA-E0BD-4F08-8D7A-A633CD5EC4CD} because it's missing its XML file!! (stt exists: False)
Skipping document 194/999 with OID {8A021408-9591-44BF-903A-94E9E4F84F65} because it's missing its XML file!! (stt exists: False)
Skipping document 195/999 with OID {368ECB75-1206-435C-884C-04AAF1D8A61F} because it's missing its XML file!! (stt exists: False)
Skipping document 198/999 with OID {9D3027A3-6F20-4628-9858-747B8FC6E398} because it's missing its XML file!! (stt exists: False)
Skipping document 199/999 with OID {3C674A9F-5A89-469B-8C75-4F14C76A3331} because it's missing its XML file!! (stt exists: False)
Skipping document 203/999 with OID {555CFD2A-0B26-43DE-9EC8-E7F6105C2345} because it's missing its XML file!! (stt exists: False)
Skipping document 204/999 with OID {E2C901B2-D5F5-438E-97FE-03C41BE9BAE1} because it's missing its XML file!! (stt exists: False)
Skipping document 208/999 with OID {6F39A112-D82D-4B39-AF4E-A5531B5B6767} because it's missing its XML file!! (stt exists: True)
Skipping document 209/999 with OID {04F6913D-695C-43F0-AB03-3EDBDECD759B} because it's missing its XML file!! (stt exists: False)
Skipping document 211/999 with OID {2A16257A-4085-4E22-A4D8-85D80B580B74} because it's missing its XML file!! (stt exists: False)
Skipping document 214/999 with OID {0EE349E8-CFFB-4BC8-888D-2C58095FECAF} because it's missing its XML file!! (stt exists: False)
Skipping document 215/999 with OID {465D2137-017A-4BF7-AB01-4093265FB881} because it's missing its XML file!! (stt exists: False)
Skipping document 218/999 with OID {09221044-365F-407F-ABDB-F2C7D27141FE} because it's missing its XML file!! (stt exists: False)
Skipping document 221/999 with OID {C13F2763-1AAD-4FC1-BF91-1AB9C042DF94} because it's missing its XML file!! (stt exists: False)
Skipping document 226/999 with OID {BDDD90F8-DA15-412F-A586-2DA0A9417B5F} because it's missing its XML file!! (stt exists: False)
Skipping document 229/999 with OID {14818951-F11C-4609-B562-A399029C4246} because it's missing its XML file!! (stt exists: False)
Skipping document 230/999 with OID {A2B905DD-D845-44C5-8B97-41AC57F60496} because it's missing its XML file!! (stt exists: False)
Skipping document 233/999 with OID {572AFC7D-41CE-41D4-8FF3-4CAA3E61E928} because it's missing its XML file!! (stt exists: False)
Skipping document 234/999 with OID {6A9F431D-0D85-415C-9266-EF1AB35FADE3} because it's missing its XML file!! (stt exists: False)
Skipping document 239/999 with OID {C37693B7-32D0-4353-8C5C-97831E85D3E4} because it's missing its XML file!! (stt exists: False)
Skipping document 241/999 with OID {2D9FCF54-4131-4373-8F61-DEFD0DDC87F8} because it's missing its XML file!! (stt exists: False)
Skipping document 244/999 with OID {3619FA31-8AEF-4D03-A6A1-546DA61A9E5D} because it's missing its XML file!! (stt exists: False)
Skipping document 251/999 with OID {9A26ABAB-1C3A-4C6C-A9AA-8AA2F8CD6C98} because it's missing its XML file!! (stt exists: True)
Skipping document 253/999 with OID {B5A77E3A-675E-458D-9B37-A4EC3FFB9363} because it's missing its XML file!! (stt exists: True)
Skipping document 259/999 with OID {45376B47-80BB-4AC4-AF3A-DC2A5A934B9B} because it's missing its XML file!! (stt exists: False)
Skipping document 260/999 with OID {57E84CC4-6309-4FA0-B63B-47EF32FF2342} because it's missing its XML file!! (stt exists: False)
Skipping document 264/999 with OID {509CB4A4-0274-46BC-A431-B799CFA42268} because it's missing its XML file!! (stt exists: False)
Skipping document 265/999 with OID {718D7347-539D-4898-A05E-71A11CD3F349} because it's missing its XML file!! (stt exists: False)
Skipping document 267/999 with OID {9A0685CD-828D-4822-A686-1C4490C0C6F1} because it's missing its XML file!! (stt exists: False)
Skipping document 268/999 with OID {EA55379D-9D31-4732-A7F2-AC66DD3ACC45} because it's missing its XML file!! (stt exists: False)
Skipping document 269/999 with OID {4DC40EB3-0F53-48B5-9924-82B800E718BE} because it's missing its XML file!! (stt exists: False)
Skipping document 279/999 with OID {765B4B64-9E2B-4317-8AAB-28C8204B5978} because it's missing its XML file!! (stt exists: False)
Skipping document 280/999 with OID {01E8CD16-58D1-4687-A358-EC494079785F} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {2EC0DE26-1093-4C74-BA69-5FF3106AC149}. Trying to use the recording date. doc_dict: {'alias': 'j_soir', 'date_str': None, 'stt_filename': '2EC0DE26-1093-4C74-BA69-5FF3106AC149_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{2EC0DE26-1093-4C74-BA69-5FF3106AC149}', 'stripped_OID': '2EC0DE26-1093-4C74-BA69-5FF3106AC149', 'login': '', 'broadcast_episode_title': "Fin de la prise d'otages ? l'ambassade de Pologne ? Berne le 6 septembre 1982 : Interview de Kurt Furgler, chef du D?partement de Justice et Police, sur l'?tat-major de crise et le d?nouement de l'affaire", 'sequence': '1', 'broadcast_program_name': 'Journal du soir', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '11.05.2022 13:26:20', 'physical_support_history': "Cote d'origine: 35168 Pl. 6", 'production_type': 'Production propre', 'recording_place': 'Berne', 'rights_notes': 'Memoriav. (SRG 75)', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives. Fribourg", 'content_summary': 'La personnalit? du chef des assaillants, Florian Krusik.', 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:13:51.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Furgler, Kurt', 'function': 'Interview?/e', 'role': 'conseiller f?d?ral, chef du D?partement de Justice et Police'}, {'name': 'Othenin-Girard, Eric', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}, {'name': 'Bochenski, Joseph', 'function': 'Interview?/e', 'role': 'm?diateur'}, {'name': 'Triverio, Philippe', 'function': 'Intervieweur/euse', 'role': 'journaliste'}, {'name': 'Froidevaux, Claude', 'function': 'Pr?sentateur/trice', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Pologne', 'Berne (ville)'], 'person_descriptors': None, 'thematical_descriptors': ["prise d'otage", 'forces sp?ciales de police'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Commentaire', 'Interview'], 'recording_dates': ['09/09/1982 - 09/09/1982'], 'first_broadcast_dates': None}
Skipping document 295/999 with OID {B75087DD-DA8D-4892-B26A-689586C2F44A} because it's missing its XML file!! (stt exists: False)
Skipping document 298/999 with OID {98782588-9DF6-4B7C-A97B-07E55FB267F7} because it's missing its XML file!! (stt exists: False)
Skipping document 304/999 with OID {9474B1BC-CFA3-4353-9062-201B891C5465} because it's missing its XML file!! (stt exists: True)
Skipping document 306/999 with OID {B58467FF-6874-4E5E-8720-45D13AD0F245} because it's missing its XML file!! (stt exists: False)
Skipping document 307/999 with OID {2A94D2CE-B105-45D9-AA2A-330FC44DED29} because it's missing its XML file!! (stt exists: False)
Skipping document 308/999 with OID {34F1F61E-3DC4-490D-8D6C-76E3139E7C24} because it's missing its XML file!! (stt exists: False)
Skipping document 313/999 with OID {6D0DA6E0-8209-401F-8A54-8D29B75EB902} because it's missing its XML file!! (stt exists: False)
Skipping document 315/999 with OID {F7106C55-79E3-4FEA-83A2-ECC652580CD5} because it's missing its XML file!! (stt exists: False)
Skipping document 318/999 with OID {A9F0B051-72C2-415E-9EC0-22C4D7392C05} because it's missing its XML file!! (stt exists: False)

Skipping document 886/999 with OID {6C510E2B-F153-487F-B3BD-604A1580AD50} because it's missing its XML file!! (stt exists: False)
Skipping document 896/999 with OID {D615A75D-9DAC-4DD3-B5C6-C4B972D241F8} because it's missing its XML file!! (stt exists: False)
Skipping document 901/999 with OID {F1D3493B-5EE1-4298-B681-4862B8B93C83} because it's missing its XML file!! (stt exists: False)
Skipping document 903/999 with OID {D0510A69-69F6-4E5D-A6D2-01543AF0CF9A} because it's missing its XML file!! (stt exists: False)
Skipping document 905/999 with OID {CF2E37BB-657C-481A-A64D-57CE9DB5C42D} because it's missing its XML file!! (stt exists: False)
Skipping document 906/999 with OID {92E26A3D-AA70-4570-96FA-20921CD2456E} because it's missing its XML file!! (stt exists: False)
Skipping document 910/999 with OID {E3CC476A-25AF-4CD0-9C80-AE68F945AEA1} because it's missing its XML file!! (stt exists: False)
Skipping document 913/999 with OID {E94FC474-4464-4775-A8AA-F95F13607D50} because it's missing its XML file!! (stt exists: False)
Skipping document 914/999 with OID {C465AAEB-1014-4BA4-A905-AF9F1B2C8DED} because it's missing its XML file!! (stt exists: False)
Skipping document 915/999 with OID {FD88C6E0-14A2-4603-B4D0-2E32E679B317} because it's missing its XML file!! (stt exists: False)
Skipping document 917/999 with OID {FC8D9C59-5A98-4D5F-8121-07D9F054B9FB} because it's missing its XML file!! (stt exists: False)
Skipping document 919/999 with OID {630D5239-0CF9-4488-B086-09F97D40775C} because it's missing its XML file!! (stt exists: False)
Skipping document 920/999 with OID {088BB666-F577-4CCD-A846-886736133920} because it's missing its XML file!! (stt exists: False)
Skipping document 921/999 with OID {71387F93-FCFD-4F46-B7F7-BA351C390F76} because it's missing its XML file!! (stt exists: False)
Skipping document 922/999 with OID {393B981B-84E2-40E3-9392-50CC3F5834B0} because it's missing its XML file!! (stt exists: False)
Skipping document 927/999 with OID {D0656AE6-30BC-4912-8EA6-C09BB54D21BD} because it's missing its XML file!! (stt exists: False)
Skipping document 928/999 with OID {033FEE14-0955-432A-B493-912F0FC9670B} because it's missing its XML file!! (stt exists: False)
Skipping document 930/999 with OID {23C33F9B-5BB3-44D1-8EE9-E306A1F21AEA} because it's missing its XML file!! (stt exists: False)
Skipping document 931/999 with OID {6E43877B-283D-4E7C-9224-E96E1B7543A3} because it's missing its XML file!! (stt exists: False)
Skipping document 932/999 with OID {E6CD80E6-4990-4672-860A-00862E77CDC1} because it's missing its XML file!! (stt exists: False)
Skipping document 933/999 with OID {E6687FD3-225F-4799-9272-9EB1645B8376} because it's missing its XML file!! (stt exists: False)
Skipping document 934/999 with OID {D77C34E3-900B-47B4-9108-9D07A2FDAADA} because it's missing its XML file!! (stt exists: False)
Skipping document 936/999 with OID {0355094F-908B-493E-A85F-4FFB6C727073} because it's missing its XML file!! (stt exists: False)
Skipping document 938/999 with OID {E7A137CB-44C7-4329-A9CE-90CDCD3C278C} because it's missing its XML file!! (stt exists: False)
Skipping document 939/999 with OID {A24EBEDB-CDA7-4666-9FD9-84AC555C0ABC} because it's missing its XML file!! (stt exists: False)
Skipping document 940/999 with OID {0134ADFA-28ED-4E60-BD24-259AC21625A4} because it's missing its XML file!! (stt exists: False)
Skipping document 941/999 with OID {4C63EC74-A3CC-4CEC-94A5-92CF835AA40E} because it's missing its XML file!! (stt exists: False)
Skipping document 942/999 with OID {87F8B58F-7954-4268-BF0B-8883EF8DB5D6} because it's missing its XML file!! (stt exists: False)
Skipping document 944/999 with OID {3B3004E9-1E75-49EC-8FF7-B081DC4EC85F} because it's missing its XML file!! (stt exists: True)
Skipping document 948/999 with OID {3F0D1C0B-E256-4C57-B0E5-387B3072D0DA} because it's missing its XML file!! (stt exists: False)
Skipping document 951/999 with OID {F80421FA-846E-4EB0-9B60-30CD6D972EFA} because it's missing its XML file!! (stt exists: False)
Skipping document 952/999 with OID {FC673F56-01CE-4E48-8D4D-29EEDD24FDA8} because it's missing its XML file!! (stt exists: False)
Skipping document 954/999 with OID {F2F941BA-448D-42EF-8B85-D949A25B29AF} because it's missing its XML file!! (stt exists: False)
Skipping document 955/999 with OID {4BEA3A3B-8939-4B20-B63E-1635E2A96722} because it's missing its XML file!! (stt exists: False)
Skipping document 957/999 with OID {07F88188-1A3D-4700-BE01-6883D5D54E79} because it's missing its XML file!! (stt exists: False)
Skipping document 963/999 with OID {DE4483B1-6762-4A64-BBD1-5D309ED89971} because it's missing its XML file!! (stt exists: False)
Skipping document 964/999 with OID {D5740927-15B2-433C-9FD9-C9A3470B9C56} because it's missing its XML file!! (stt exists: False)
Skipping document 965/999 with OID {77C5AF12-9E21-4FC1-9438-D5E25DFBBE38} because it's missing its XML file!! (stt exists: False)
Skipping document 966/999 with OID {2820884C-83C8-4EC8-B512-8306DBD775BE} because it's missing its XML file!! (stt exists: False)
Skipping document 967/999 with OID {81609B0A-A5B0-455D-9EDB-D1637EBE2F4A} because it's missing its XML file!! (stt exists: False)
Skipping document 968/999 with OID {1412047B-1288-4D00-BC5E-CE44DD14CED0} because it's missing its XML file!! (stt exists: False)
Skipping document 972/999 with OID {13DC745F-3783-426E-95D6-16F60CACC2F0} because it's missing its XML file!! (stt exists: False)
Skipping document 973/999 with OID {D53A7075-96BA-4A7A-AB99-21FE4841F80C} because it's missing its XML file!! (stt exists: False)
Skipping document 974/999 with OID {12C03723-8455-4696-8CA7-3347F4712311} because it's missing its XML file!! (stt exists: False)
Skipping document 977/999 with OID {A78249DE-E01E-4A94-AECA-ECC5FCA41E4F} because it's missing its XML file!! (stt exists: False)
Skipping document 978/999 with OID {4293026D-FD66-4C3E-AF0F-E333512D9DFE} because it's missing its XML file!! (stt exists: True)
Skipping document 980/999 with OID {B6F4D62B-A2A2-4E60-8505-2DE79EA46859} because it's missing its XML file!! (stt exists: False)
Skipping document 981/999 with OID {4C782E7F-3185-4914-B918-5D464D95C34F} because it's missing its XML file!! (stt exists: False)
Skipping document 983/999 with OID {BE69647C-A2DD-4747-9301-C908A53BEB4D} because it's missing its XML file!! (stt exists: False)
Skipping document 987/999 with OID {0C6BC48D-F537-4496-9141-467A8895912D} because it's missing its XML file!! (stt exists: False)
Skipping document 990/999 with OID {DD160121-36B3-4EDB-A85A-0D1DB0B1BF7A} because it's missing its XML file!! (stt exists: False)
Skipping document 992/999 with OID {C5636014-9F92-408E-99C0-CDF04437B511} because it's missing its XML file!! (stt exists: False)
Skipping document 994/999 with OID {A86DF0A2-BEBC-468A-A436-B97D94A15D39} because it's missing its XML file!! (stt exists: False)
Skipping document 995/999 with OID {82348C1F-71C3-4CBF-A119-A2AEEE6EBE06} because it's missing its XML file!! (stt exists: False)
Skipping document 996/999 with OID {CFB0E38E-CF01-49FC-AE93-E92309ACC1D1} because it's missing its XML file!! (stt exists: False)
Skipping document 997/999 with OID {C96D6728-DC6F-44AC-982F-D87B289ED2CA} because it's missing its XML file!! (stt exists: False)
Skipping document 998/999 with OID {BD639EF9-3DA4-4848-9F42-35B0A4150479} because it's missing its XML file!! (stt exists: False)
j_soir - returning 629 documents, 370 were skipped due to missing necessary info.

Starting extracting 999 documents for program j_soir
Skipping document 2/999 with OID {A7763980-5D1D-49DB-A99B-9F9AAAC521BD} because it's missing its XML file!! (stt exists: False)
Skipping document 7/999 with OID {07158DD3-50E4-4ACC-B2BF-C878ABF85683} because it's missing its XML file!! (stt exists: False)
Skipping document 8/999 with OID {599D9119-D522-4E41-81BA-D10C5660E1DA} because it's missing its XML file!! (stt exists: False)
Skipping document 11/999 with OID {640A3A6A-3DD0-4902-A9B3-481DF1E08C75} because it's missing its XML file!! (stt exists: False)
Skipping document 12/999 with OID {4304CB3F-1F82-4D26-AFAA-B6430449CE26} because it's missing its XML file!! (stt exists: False)
Skipping document 30/999 with OID {F5E8B485-74B4-4A73-B399-B7F031082E53} because it's missing its XML file!! (stt exists: False)
Skipping document 48/999 with OID {E0C29B34-EB4A-44D7-AE5C-34F0E433EF04} because it's missing its XML file!! (stt exists: False)
Skipping document 49/999 with OID {1CA5E3B3-CE8F-4F70-9964-691ED894CE1D} because it's missing its XML file!! (stt exists: False)
Skipping document 55/999 with OID {B683BC49-C82C-4976-BB56-E90304E739C6} because it's missing its XML file!! (stt exists: False)
Skipping document 67/999 with OID {FDF552BF-290A-428C-B5BB-3DF0E47F8CB9} because it's missing its XML file!! (stt exists: False)
Skipping document 77/999 with OID {C72EFCDC-34AA-40A9-8E43-4A832889A720} because it's missing its XML file!! (stt exists: False)
Skipping document 85/999 with OID {6976914D-C6F9-43DF-B6BE-442E28F5D6AF} because it's missing its XML file!! (stt exists: False)
Skipping document 92/999 with OID {FC2B6280-D8C8-4397-8632-0F5AF0F39F94} because it's missing its XML file!! (stt exists: False)
Skipping document 93/999 with OID {DE881F5B-117D-483E-AD89-78FD8D624A5D} because it's missing its XML file!! (stt exists: False)
Skipping document 96/999 with OID {4E1A2048-6851-4D81-AEF2-94BA0D0C32FA} because it's missing its XML file!! (stt exists: False)
Skipping document 98/999 with OID {A75DC9EE-5F68-4BFD-BFB0-3B025AD57FEC} because it's missing its XML file!! (stt exists: False)
Skipping document 105/999 with OID {5418F08E-E997-409E-9754-36E99516E7DF} because it's missing its XML file!! (stt exists: False)
Skipping document 110/999 with OID {DDA50286-13A4-40D3-9A59-67AF42B82838} because it's missing its XML file!! (stt exists: False)
Skipping document 114/999 with OID {C7347AA5-3463-4653-BEE8-140CFBF40A04} because it's missing its XML file!! (stt exists: False)
Skipping document 128/999 with OID {BA97AC11-C981-4FB2-A85D-F006A1A32BD5} because it's missing its XML file!! (stt exists: False)
Skipping document 131/999 with OID {875365D4-10AA-4E8C-9AB0-B21D166AE97A} because it's missing its XML file!! (stt exists: False)
Skipping document 133/999 with OID {A0562F63-A163-4256-AA21-129E54AD8711} because it's missing its XML file!! (stt exists: False)
Skipping document 134/999 with OID {B5951EB1-4601-4A15-A001-FE455502EDE3} because it's missing its XML file!! (stt exists: False)
Skipping document 135/999 with OID {8D1B26C1-6AA3-4D9F-8783-B25D48D8F70E} because it's missing its XML file!! (stt exists: False)
Skipping document 137/999 with OID {B2672DEF-ADAF-464E-901E-6949928BD191} because it's missing its XML file!! (stt exists: False)
Skipping document 138/999 with OID {42D1636A-76F2-4C58-99F6-9EB778CE8796} because it's missing its XML file!! (stt exists: False)
Skipping document 140/999 with OID {DAFB58D7-EA76-4BB3-B46F-A9D5E9305FAC} because it's missing its XML file!! (stt exists: False)
Skipping document 142/999 with OID {2FD0FB0D-625C-4ED8-8F60-B1E475179B83} because it's missing its XML file!! (stt exists: False)
Skipping document 145/999 with OID {2E271BB8-8D6A-4D91-BC0B-0DCD3371E081} because it's missing its XML file!! (stt exists: False)
Skipping document 151/999 with OID {6CB48018-5AC8-4059-B680-78D2261AFB56} because it's missing its XML file!! (stt exists: False)
Skipping document 157/999 with OID {17F5BD7B-11E7-4445-8750-0F167A2E59E9} because it's missing its XML file!! (stt exists: False)
Skipping document 163/999 with OID {4433A213-AE24-4120-97CE-BA3DBC8CFB97} because it's missing its XML file!! (stt exists: False)
Skipping document 166/999 with OID {FCF3C669-FA34-42B1-9660-E43495AFCC0E} because it's missing its XML file!! (stt exists: False)
Skipping document 172/999 with OID {7384D2B1-CFE0-4E7F-9405-17A97610219F} because it's missing its XML file!! (stt exists: False)
Skipping document 178/999 with OID {F83EEEDF-88F4-47AF-BF61-7D24E37206F9} because it's missing its XML file!! (stt exists: False)
Skipping document 180/999 with OID {74004158-CCF3-41E1-B705-3EF88458ABB7} because it's missing its XML file!! (stt exists: False)
Skipping document 190/999 with OID {294B2ECE-21AD-4DCF-8913-55CA2C6235E4} because it's missing its XML file!! (stt exists: False)
Skipping document 193/999 with OID {0E81D145-D197-4806-A3B2-B244D0717F61} because it's missing its XML file!! (stt exists: False)
Skipping document 195/999 with OID {95D325AA-29E2-4DEC-BC19-E4E46FF31F70} because it's missing its XML file!! (stt exists: False)
Skipping document 208/999 with OID {2077526A-CAD6-4AB2-AFBA-3A97DC9E7295} because it's missing its XML file!! (stt exists: False)
Skipping document 210/999 with OID {94678972-2E44-4D3B-AD0A-4C006C0E9E61} because it's missing its XML file!! (stt exists: False)
Skipping document 212/999 with OID {B2534362-B44B-4F18-854A-4587B76D0AE9} because it's missing its XML file!! (stt exists: True)
Skipping document 217/999 with OID {0FC84799-B38A-44A4-AB68-026BEBCF9286} because it's missing its XML file!! (stt exists: False)
Skipping document 219/999 with OID {89EEED75-4B91-4290-BCFC-3C713EDE314B} because it's missing its XML file!! (stt exists: True)
Skipping document 220/999 with OID {FFC86716-0269-43A2-8121-1BB06FA1F462} because it's missing its XML file!! (stt exists: False)
Skipping document 221/999 with OID {6D0F068C-20D6-4077-8960-03D0832F331D} because it's missing its XML file!! (stt exists: False)
Skipping document 223/999 with OID {1350E0BB-A92A-47DA-A839-D406B4F7C335} because it's missing its XML file!! (stt exists: False)
Skipping document 229/999 with OID {563E2362-DB8B-4276-9CD0-210656E45A8D} because it's missing its XML file!! (stt exists: False)
Skipping document 231/999 with OID {848D9212-4309-473B-83F6-4B1B9EB92AE9} because it's missing its XML file!! (stt exists: False)
Skipping document 232/999 with OID {AC9BDE9B-C232-49A5-9F80-B4F19D67DC8E} because it's missing its XML file!! (stt exists: True)
Skipping document 237/999 with OID {95B2BF6B-7901-4C5F-BCE2-9D118BA1B3D1} because it's missing its XML file!! (stt exists: False)
Skipping document 242/999 with OID {0D551F25-E1BD-4DF7-8118-1F55CD339661} because it's missing its XML file!! (stt exists: False)
Skipping document 243/999 with OID {953F51D1-4B9D-403D-AEFB-FBBBBF87BD82} because it's missing its XML file!! (stt exists: False)
Skipping document 254/999 with OID {A7C0B2BF-8D0C-43EE-982B-8E24D2C05D9C} because it's missing its XML file!! (stt exists: False)
Skipping document 255/999 with OID {581AF08A-D4F9-4310-8E46-EB8720689413} because it's missing its XML file!! (stt exists: False)
Skipping document 256/999 with OID {8E23559A-A5E5-4BF6-A28E-915BB83DC6E7} because it's missing its XML file!! (stt exists: False)
Skipping document 271/999 with OID {AC4B1638-E48F-42C6-B125-E3F9FF02DC9C} because it's missing its XML file!! (stt exists: False)
Skipping document 274/999 with OID {A986A6F9-9A11-4634-AAFE-F463129B1709} because it's missing its XML file!! (stt exists: True)
Skipping document 275/999 with OID {443FE9C7-EEC4-421D-927D-EEE3FD391B70} because it's missing its XML file!! (stt exists: False)
Skipping document 276/999 with OID {7FB58528-A896-495A-9CED-8D4FF84AF557} because it's missing its XML file!! (stt exists: False)
Skipping document 279/999 with OID {831FDAEE-CD52-4D77-A817-B0065F063D0E} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {A48602F2-AC9E-4C03-A9A7-EAD627609ACC}. Trying to use the recording date. doc_dict: {'alias': 'j_soir', 'date_str': None, 'stt_filename': 'A48602F2-AC9E-4C03-A9A7-EAD627609ACC_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{A48602F2-AC9E-4C03-A9A7-EAD627609ACC}', 'stripped_OID': 'A48602F2-AC9E-4C03-A9A7-EAD627609ACC', 'login': '', 'broadcast_episode_title': "Lancement de la campagne contre le SIDA ? Berne : Pr?sentation par l'Aide Suisse contre le Sida et l'Office f?d?ral de la sant? publique d'une campagne de pr?vention sans pr?c?dent contre le SIDA, avec pour priorit? l'utilisation du pr?servatif . Le point de vue cl?rical par Mgr Schwery", 'sequence': '1', 'broadcast_program_name': 'Journal du soir', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '09.03.2023 11:51:11', 'physical_support_history': "Cote d'origine: 35622 Pl. 8", 'production_type': 'Production propre', 'recording_place': 'Lausanne (Studio)', 'rights_notes': 'Publi? sur : site Archives (2011)', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:03:34.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Inconnu', 'function': 'Pr?sentateur/trice', 'role': 'collaborateur RSR'}, {'name': 'Tschanz, Pierre-Andr?', 'function': 'Commentateur/trice', 'role': 'collaborateur RSR'}, {'name': 'Schwery, Henri', 'function': 'Interview?/e', 'role': 'Ev?que de Sion et pr?sident de la conf?rence ?piscopale'}, {'name': 'Michel, Michel', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': ['sida', 'sexualit?', 'comportement', 'pr?servatif'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Premier programme'], 'subdomains': ['Interview'], 'recording_dates': ['03/02/1987 - 03/02/1987'], 'first_broadcast_dates': None}
Skipping document 283/999 with OID {43A2BDD2-AF53-4AD1-87D5-ED99AD6181E4} because it's missing its XML file!! (stt exists: False)
Skipping document 288/999 with OID {3B73D457-6CB8-4136-B3C5-47378BB7D33A} because it's missing its XML file!! (stt exists: False)
Skipping document 291/999 with OID {CFBF8D2F-FCB3-458D-A280-57AB44BC1589} because it's missing its XML file!! (stt exists: False)

Skipping document 925/999 with OID {73329ADB-E3EC-4CC1-907E-6409EFD57514} because it's missing its XML file!! (stt exists: False)
Skipping document 937/999 with OID {88560D57-1B03-49CD-A52E-9C5E127CC456} because it's missing its XML file!! (stt exists: False)
Skipping document 939/999 with OID {44FFFFE7-B6A5-42E2-BFD9-7EEA2CA9EAC3} because it's missing its XML file!! (stt exists: False)
Skipping document 947/999 with OID {5EFC9B28-76CA-4F1D-A5FD-7B79C0B099EC} because it's missing its XML file!! (stt exists: False)
Skipping document 948/999 with OID {863FFE97-4F6A-451D-8126-BDFABCEDEC26} because it's missing its XML file!! (stt exists: False)
Skipping document 949/999 with OID {557DA3D7-E53F-4EC9-AC12-B04DCD2F8F44} because it's missing its XML file!! (stt exists: False)
Skipping document 950/999 with OID {7D827E1D-B7FD-4CD2-B76A-003715B6F703} because it's missing its XML file!! (stt exists: False)
Skipping document 952/999 with OID {8C452457-7F86-49F1-A1C9-7B457B3091A2} because it's missing its XML file!! (stt exists: False)
Skipping document 954/999 with OID {E52F93CC-B7D8-46BD-B27B-E1A6EA1DAFA2} because it's missing its XML file!! (stt exists: False)
Skipping document 956/999 with OID {7ED0DDFD-3A5C-4CAC-9E78-BD36BB9484D9} because it's missing its XML file!! (stt exists: False)
Skipping document 957/999 with OID {580F255D-F43A-4EA6-8713-86C3A8661B70} because it's missing its XML file!! (stt exists: False)
Skipping document 959/999 with OID {2001F2C7-68D2-4D7A-8D3E-76B2708BC426} because it's missing its XML file!! (stt exists: True)
Skipping document 962/999 with OID {D31FCF05-B952-46E2-B266-222DBB7F6D95} because it's missing its XML file!! (stt exists: False)
Skipping document 966/999 with OID {E3E58B8F-618C-4118-BCA0-B430C0CAF0B9} because it's missing its XML file!! (stt exists: False)
Skipping document 967/999 with OID {DAC6E1E3-F62B-456F-AFF5-E2FCC6618B3E} because it's missing its XML file!! (stt exists: False)
Skipping document 970/999 with OID {1159D33E-CE42-4F8C-969F-15B130370EBA} because it's missing its XML file!! (stt exists: False)
Skipping document 971/999 with OID {264F57E7-9686-4932-84AA-FA46D5E1C789} because it's missing its XML file!! (stt exists: False)
Skipping document 974/999 with OID {AC5C3391-52BC-48C6-8EB4-A9789AAD73E2} because it's missing its XML file!! (stt exists: False)
Skipping document 977/999 with OID {0E4575E9-F7D0-4278-BD8E-7A9F2812085B} because it's missing its XML file!! (stt exists: False)
Skipping document 983/999 with OID {CE77B691-2934-4BBD-8D7C-3F9C3727DC3F} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {109F4502-5DEE-46A7-947E-6A71C386B982}. Trying to use the recording date. doc_dict: {'alias': 'j_soir', 'date_str': None, 'stt_filename': '109F4502-5DEE-46A7-947E-6A71C386B982_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{109F4502-5DEE-46A7-947E-6A71C386B982}', 'stripped_OID': '109F4502-5DEE-46A7-947E-6A71C386B982', 'login': '', 'broadcast_episode_title': 'Les cons?quences des fortes intemp?ries (5/6) : Interview du pr?sident de la commune de M?nster dans la vall?e de Conches [1/2]', 'sequence': '1', 'broadcast_program_name': 'Journal du soir', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '09.06.2022 13:18:02', 'physical_support_history': "Cote d'origine: 25445 Pl. 8", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav (SRG 75)', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:00:54.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Inconnu', 'function': 'Interview?/e', 'role': 'pr?sident de la commune de M?nster dans la Vall?e de Conches'}, {'name': 'Preux, Jean de', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['M?nster'], 'person_descriptors': None, 'thematical_descriptors': ['inondation', 'catastrophe naturelle', 'pluie'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Interview'], 'recording_dates': ['25/08/1987 - 25/08/1987'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {BD6B61BB-BBCF-43D3-AD18-5672BB787307}. Trying to use the recording date. doc_dict: {'alias': 'j_soir', 'date_str': None, 'stt_filename': 'BD6B61BB-BBCF-43D3-AD18-5672BB787307_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{BD6B61BB-BBCF-43D3-AD18-5672BB787307}', 'stripped_OID': 'BD6B61BB-BBCF-43D3-AD18-5672BB787307', 'login': '', 'broadcast_episode_title': 'Les cons?quences des fortes intemp?ries (6/6) : Interview du pr?sident de la commune de M?nster dans la vall?e de Conches [2/2]', 'sequence': '1', 'broadcast_program_name': 'Journal du soir', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '09.03.2023 12:24:40', 'physical_support_history': "Cote d'origine: 25445 Pl. 9", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav (SRG 75)', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:01:39.396', 'work_duration_compl': 'Non', 'participants': [{'name': 'Inconnu', 'function': 'Interview?/e', 'role': 'pr?sident de la commune de M?nster dans la Vall?e de Conches'}, {'name': 'Preux, Jean de', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['M?nster'], 'person_descriptors': None, 'thematical_descriptors': ['inondation', 'catastrophe naturelle', 'pluie'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Interview'], 'recording_dates': ['25/08/1987 - 25/08/1987'], 'first_broadcast_dates': None}
Skipping document 990/999 with OID {74E29A49-551C-40AA-8875-A66AA0805408} because it's missing its XML file!! (stt exists: False)
Skipping document 991/999 with OID {6E9004B4-7F2C-4FE7-8841-87D6E5327DE2} because it's missing its XML file!! (stt exists: False)
Skipping document 992/999 with OID {EC142267-6EC5-4D53-8B5A-94425D78D90D} because it's missing its XML file!! (stt exists: False)
Skipping document 995/999 with OID {F7764777-697A-4115-B581-B235280BA9D5} because it's missing its XML file!! (stt exists: False)
j_soir - returning 748 documents, 251 were skipped due to missing necessary info.

Starting extracting 999 documents for program j_soir
Skipping document 1/999 with OID {7F4E7D18-27DF-483A-8662-C32880FED995} because it's missing its XML file!! (stt exists: True)
Skipping document 3/999 with OID {A27F28AA-F37E-4334-A2CF-FEABB3F7EA42} because it's missing its XML file!! (stt exists: False)
Skipping document 9/999 with OID {F739AE0F-9981-4180-9BB4-B98831132436} because it's missing its XML file!! (stt exists: False)
Skipping document 11/999 with OID {88ADC0A4-07CE-4B12-869F-AA917D441037} because it's missing its XML file!! (stt exists: False)
Skipping document 14/999 with OID {2D2F44EE-C265-47BB-91AA-65E132AFAF84} because it's missing its XML file!! (stt exists: False)
Skipping document 15/999 with OID {FB92ED44-32C4-4063-9E75-65CCA9FB8701} because it's missing its XML file!! (stt exists: False)
Skipping document 16/999 with OID {B7B29622-86EA-4D87-9757-A4945B5A1CB5} because it's missing its XML file!! (stt exists: False)
Skipping document 17/999 with OID {E177C23F-CB6C-443D-8071-506DBE6B4ABD} because it's missing its XML file!! (stt exists: False)
Skipping document 27/999 with OID {66EE8A80-7932-4797-8286-7AE1DEA3CE5B} because it's missing its XML file!! (stt exists: False)
Skipping document 32/999 with OID {F30E350E-0348-4585-9F45-821AB33F6A64} because it's missing its XML file!! (stt exists: False)
Skipping document 35/999 with OID {7F0B8731-29C3-4251-8CE8-BF9645AAC97A} because it's missing its XML file!! (stt exists: False)
Skipping document 36/999 with OID {68798F21-72C9-4826-BDF1-944A7268A942} because it's missing its XML file!! (stt exists: False)
Skipping document 37/999 with OID {E66E697D-BD6E-4DFA-B826-5D32B450891B} because it's missing its XML file!! (stt exists: False)
Skipping document 41/999 with OID {44A8A46C-519A-4DD0-B7F2-EED3590F74EC} because it's missing its XML file!! (stt exists: False)
Skipping document 44/999 with OID {1A7D8F64-D614-4CBC-AA39-27E8904764DD} because it's missing its XML file!! (stt exists: False)
Skipping document 45/999 with OID {AE4A0FD5-33B7-48D5-9012-DE10BA28164A} because it's missing its XML file!! (stt exists: False)
Skipping document 54/999 with OID {5E1E265B-CF20-4EE8-8FC8-F1FBE5E6F985} because it's missing its XML file!! (stt exists: False)
Skipping document 68/999 with OID {50BAEE48-631A-4E32-80CF-A3B9F649F6C5} because it's missing its XML file!! (stt exists: False)
Skipping document 69/999 with OID {BEAB94A5-0854-4333-8065-11436E4F1238} because it's missing its XML file!! (stt exists: False)
Skipping document 70/999 with OID {D7B76D00-ECE6-4CD1-ACBE-8DE09A8CB034} because it's missing its XML file!! (stt exists: False)
Skipping document 72/999 with OID {5BB2AF31-7DDA-4D83-93C2-0521187EA1BF} because it's missing its XML file!! (stt exists: False)
Skipping document 73/999 with OID {A6AD698D-4830-4890-A00A-FF354F78B956} because it's missing its XML file!! (stt exists: False)
Skipping document 75/999 with OID {648BD798-3FE9-412A-A115-B55F762FB578} because it's missing its XML file!! (stt exists: False)
Skipping document 76/999 with OID {469D7F9E-3C89-4506-9653-78E41765B4AE} because it's missing its XML file!! (stt exists: False)
Skipping document 79/999 with OID {74B9CEDD-C12C-4469-A26A-F433853869E2} because it's missing its XML file!! (stt exists: False)
Skipping document 81/999 with OID {0EAFEADF-76BE-4F0C-AB23-697CE0BC046E} because it's missing its XML file!! (stt exists: False)
Skipping document 82/999 with OID {059E577F-8361-490A-9706-AB6E3FF6F90A} because it's missing its XML file!! (stt exists: False)
Skipping document 83/999 with OID {15609C83-B767-4645-80A5-5A891BF5C7CB} because it's missing its XML file!! (stt exists: False)
Skipping document 87/999 with OID {CD25D44A-CEEF-46B1-A25F-823D174D95CF} because it's missing its XML file!! (stt exists: False)
Skipping document 88/999 with OID {67F8221D-B205-496A-8EE6-036B3CB2333F} because it's missing its XML file!! (stt exists: False)
Skipping document 89/999 with OID {56ECD344-9324-45EF-9F60-0AB284BC6443} because it's missing its XML file!! (stt exists: False)
Skipping document 90/999 with OID {C38BA4E9-7F18-4385-85F2-D804791C978F} because it's missing its XML file!! (stt exists: False)
Skipping document 91/999 with OID {43A04130-E99B-4C99-926F-D1711E76B030} because it's missing its XML file!! (stt exists: False)
Skipping document 92/999 with OID {B1D763BE-0AEB-406B-B5E0-922ADAF0AB13} because it's missing its XML file!! (stt exists: False)
Skipping document 93/999 with OID {B6309226-E911-4919-A1BA-A42D64313B1E} because it's missing its XML file!! (stt exists: False)
Skipping document 94/999 with OID {DF272CCA-7A1C-4AB3-A9A6-76E0C73EA0CA} because it's missing its XML file!! (stt exists: False)
Skipping document 95/999 with OID {215593AE-D02A-4727-9896-EE3F4E545A72} because it's missing its XML file!! (stt exists: False)
Skipping document 96/999 with OID {8F021284-9C38-4A9D-AE8A-9B5F0B5053DC} because it's missing its XML file!! (stt exists: False)
Skipping document 97/999 with OID {FC197297-A902-4EE0-AF27-A1B63520F19C} because it's missing its XML file!! (stt exists: False)
Skipping document 98/999 with OID {5C72DB72-7C0A-4156-B0FA-06E871FFABA1} because it's missing its XML file!! (stt exists: False)
Skipping document 99/999 with OID {1F0D49AE-26C5-406E-B2B9-2A5E3573D4AD} because it's missing its XML file!! (stt exists: False)
Skipping document 100/999 with OID {DA3C38E6-F300-451F-AFBF-ADFD54613AF3} because it's missing its XML file!! (stt exists: False)
Skipping document 101/999 with OID {079FB0AB-A7F7-4A2C-BCC7-048CB179768F} because it's missing its XML file!! (stt exists: False)
Skipping document 102/999 with OID {0564B062-999B-4FF1-8D5D-7CA812525137} because it's missing its XML file!! (stt exists: False)
Skipping document 103/999 with OID {F7593624-C0C1-48D6-B804-A8FDB40ABA3E} because it's missing its XML file!! (stt exists: False)
Skipping document 104/999 with OID {FCC99B8C-5AA1-4024-988C-5543DDA17368} because it's missing its XML file!! (stt exists: False)
Skipping document 105/999 with OID {64FA3364-E19C-43BD-9B54-1888CBEEA0B1} because it's missing its XML file!! (stt exists: False)
Skipping document 107/999 with OID {2B7E910D-9DBB-4355-9A81-EBB34541CBFD} because it's missing its XML file!! (stt exists: False)
Skipping document 108/999 with OID {34567778-D525-4C4D-9AA6-E1C4283A2684} because it's missing its XML file!! (stt exists: False)
Skipping document 109/999 with OID {7BEA4618-CC20-4DA9-BB86-D7B0C0A3AA0C} because it's missing its XML file!! (stt exists: False)
Skipping document 110/999 with OID {6F875AFC-1815-43F3-A668-9DA300ED7CD5} because it's missing its XML file!! (stt exists: False)
Skipping document 111/999 with OID {8FFFF58C-4FD2-41DE-919E-F3A960E27EE1} because it's missing its XML file!! (stt exists: False)
Skipping document 112/999 with OID {7143F5D3-D9FC-4BE9-8DE3-A2C2FEA57B66} because it's missing its XML file!! (stt exists: False)
Skipping document 113/999 with OID {14B06939-3821-4FDF-B236-1244E4B11838} because it's missing its XML file!! (stt exists: False)
Skipping document 114/999 with OID {7A5D8988-1C91-4CB7-9304-6982D3E2EFB9} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {68301411-AC2B-4549-B3B1-B877AE44D9C6}. Trying to use the recording date. doc_dict: {'alias': 'j_soir', 'date_str': None, 'stt_filename': '68301411-AC2B-4549-B3B1-B877AE44D9C6_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{68301411-AC2B-4549-B3B1-B877AE44D9C6}', 'stripped_OID': '68301411-AC2B-4549-B3B1-B877AE44D9C6', 'login': '', 'broadcast_episode_title': 'Commentaire de Pascale Cheulet, envoy?e sp?ciale France Info au Cap : A propos de la lib?ration de Nelson mandela', 'sequence': '1', 'broadcast_program_name': 'Journal du soir', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '09.03.2023 11:23:15', 'physical_support_history': "Cote d'origine : 1720.17 Lot : Caisse 3043", 'production_type': 'Production propre', 'recording_place': 'Le Cap', 'rights_notes': None, 'rights_status': 'A rechercher', 'series_title': "Sauvegarde d'archives", 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Cheulet, Pascale', 'function': 'Commentateur/trice', 'role': 'journaliste Radio France'}], 'geographical_descriptors': ['Afrique du Sud'], 'person_descriptors': ['Mandela, Nelson'], 'thematical_descriptors': ['lib?ration de d?tenu', 'prisonnier politique'], 'rights_usage_possibilities': ['FM'], 'radio_channels': ['Premier programme'], 'subdomains': ['Commentaire'], 'recording_dates': ['11/02/1990 - 11/02/1990'], 'first_broadcast_dates': None}
Skipping document 116/999 with OID {F5B8EC19-8ED9-4132-A699-A9496898DABA} because it's missing its XML file!! (stt exists: False)
Skipping document 117/999 with OID {351DDF58-1D82-4E8C-AE03-B68ECE5ACAD7} because it's missing its XML file!! (stt exists: False)
Skipping document 118/999 with OID {D98EC710-E57A-4D88-BB64-2C65BC981ADC} because it's missing its XML file!! (stt exists: False)
Skipping document 119/999 with OID {3FC0A400-0843-4638-99F3-140EB4B304AC} because it's missing its XML file!! (stt exists: False)
Skipping document 120/999 with OID {9E8FA728-CAE9-45CA-B1D0-1416E9E3BD02} because it's missing its XML file!! (stt exists: False)
Skipping document 122/999 with OID {E0FA9009-67E0-40F6-AAB2-4A9095926204} because it's missing its XML file!! (stt exists: False)
Skipping document 123/999 with OID {1E28AF15-4ECC-4E56-885F-6A5F01E38DBB} because it's missing its XML file!! (stt exists: False)
Skipping document 124/999 with OID {9277D461-56A0-41FD-AC97-2609836A7F81} because it's missing its XML file!! (stt exists: False)
Skipping document 126/999 with OID {7317AB6D-D8B6-40DE-9491-B13568B795CD} because it's missing its XML file!! (stt exists: False)
Skipping document 127/999 with OID {28BEC43D-E406-4DBC-9772-B3A812C80B0D} because it's missing its XML file!! (stt exists: False)
Skipping document 129/999 with OID {1C49DE3B-E6FC-4A56-AA67-37774ACADD80} because it's missing its XML file!! (stt exists: False)
Skipping document 132/999 with OID {6CF03503-7DFE-4924-B89D-EA2ED8C658A5} because it's missing its XML file!! (stt exists: False)
Skipping document 133/999 with OID {26AE382E-2454-4CBF-B4C8-BD6B2ADCF89D} because it's missing its XML file!! (stt exists: False)
Skipping document 134/999 with OID {6E382232-E58A-487E-A946-6FFED98A5DB9} because it's missing its XML file!! (stt exists: False)
Skipping document 135/999 with OID {BF385166-350C-4CBC-B304-513228BC9966} because it's missing its XML file!! (stt exists: False)
Skipping document 136/999 with OID {5CCC6C5C-CFAF-41A2-BA51-C2AE111A0693} because it's missing its XML file!! (stt exists: False)
Skipping document 137/999 with OID {D9303181-6650-48D1-BE22-331CA0F762BC} because it's missing its XML file!! (stt exists: False)
Skipping document 142/999 with OID {D3AEF9AD-F277-4A97-8D87-C2B0ADECFA2C} because it's missing its XML file!! (stt exists: True)
Skipping document 149/999 with OID {0CC599F2-3AD2-4977-B508-203E8C9AD5FA} because it's missing its XML file!! (stt exists: False)
Skipping document 150/999 with OID {BEF74F31-EAB5-4646-966C-8A06D01AF48F} because it's missing its XML file!! (stt exists: False)
Skipping document 151/999 with OID {5E063D85-D771-4DF0-928A-2751A537A12E} because it's missing its XML file!! (stt exists: False)
Skipping document 154/999 with OID {FF90D54B-34B8-4EDB-91E8-7639142B708C} because it's missing its XML file!! (stt exists: False)
Skipping document 156/999 with OID {0726BE33-5AFD-4C76-A581-EE849F1E7417} because it's missing its XML file!! (stt exists: False)
Skipping document 168/999 with OID {8002BE3B-2212-47EF-9BF2-04E4BC568110} because it's missing its XML file!! (stt exists: False)
Skipping document 170/999 with OID {5B17F84E-C364-46DF-89F6-A2E0016C73FB} because it's missing its XML file!! (stt exists: False)
Skipping document 171/999 with OID {E7DC9105-3965-4448-B0F8-76E4DFA0BBE1} because it's missing its XML file!! (stt exists: False)
Skipping document 172/999 with OID {B4CD86AC-8BA1-412B-86BA-EA3A4BF26413} because it's missing its XML file!! (stt exists: False)
Skipping document 174/999 with OID {DCC3C064-BB86-4F70-8C84-E9FFFA945C48} because it's missing its XML file!! (stt exists: False)
Skipping document 178/999 with OID {34D95D61-5432-4736-AA92-86909322F5A9} because it's missing its XML file!! (stt exists: False)
Skipping document 183/999 with OID {FE2E634C-DFF5-4FAD-B25D-7DC3EE16F5AA} because it's missing its XML file!! (stt exists: False)
Skipping document 200/999 with OID {50A74654-2805-4219-A0EA-6ADB1DE4D9B3} because it's missing its XML file!! (stt exists: False)
Skipping document 211/999 with OID {BF6496D1-7F8F-4C02-BB3C-6F61D5902A2B} because it's missing its XML file!! (stt exists: False)
Skipping document 221/999 with OID {130E6CB7-A213-43E6-8468-0782565DBF7F} because it's missing its XML file!! (stt exists: False)
Skipping document 248/999 with OID {F474928D-A0C8-4A7F-BAAC-A9D768967C46} because it's missing its XML file!! (stt exists: False)

Skipping document 914/999 with OID {ED41E9D5-9DAF-48C4-A02F-3D47BB0FA348} because it's missing its XML file!! (stt exists: False)
Skipping document 917/999 with OID {25F14D80-8821-4624-81B6-CED91CBF6E7D} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {EF66873F-C9C8-4354-910A-3413E0D42BCB}. Trying to use the recording date. doc_dict: {'alias': 'j_soir', 'date_str': None, 'stt_filename': 'EF66873F-C9C8-4354-910A-3413E0D42BCB_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{EF66873F-C9C8-4354-910A-3413E0D42BCB}', 'stripped_OID': 'EF66873F-C9C8-4354-910A-3413E0D42BCB', 'login': '', 'broadcast_episode_title': 'Elections f?d?rales. Interview de Mario Soldini, conseiller national genevois, sur la r?partition des si?ges au Conseil national', 'sequence': '1', 'broadcast_program_name': 'Journal du soir', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'dupasqbl', 'modified_on': '24.05.2022 04:53:26', 'physical_support_history': "Cote d'origine: 31790 Pl. 1", 'production_type': 'Production propre', 'recording_place': 'Studio de Lausanne', 'rights_notes': 'Memoriav. (SRG 75)', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:03:02.613', 'work_duration_compl': 'Non', 'participants': [{'name': 'Soldini, Mario', 'function': 'Interview?/e', 'role': 'conseiller national genevois, membre du parti Vigilance'}, {'name': 'Boder, Francis', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Suisse'], 'person_descriptors': ['Conseil National'], 'thematical_descriptors': ['?lection', 'l?gislatif national'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Interview'], 'recording_dates': ['23/10/1979 - 23/10/1979'], 'first_broadcast_dates': None}
Skipping document 931/999 with OID {BA280FA3-2D86-4AE8-BEE0-13653353D08C} because it's missing its XML file!! (stt exists: False)
Skipping document 937/999 with OID {1538C6DF-C095-434C-9393-149F181A1074} because it's missing its XML file!! (stt exists: False)
Skipping document 941/999 with OID {42EA215E-07F4-4A9C-8D35-93282C4D0FE8} because it's missing its XML file!! (stt exists: False)
Skipping document 946/999 with OID {4B861098-09C2-43DB-A2DC-ED62988F2A75} because it's missing its XML file!! (stt exists: False)
Skipping document 947/999 with OID {49D8739E-E54D-45DB-AECC-976BE912AB1C} because it's missing its XML file!! (stt exists: False)
Skipping document 948/999 with OID {B2EF6659-4014-4B53-9D58-F6ECFD79B0F1} because it's missing its XML file!! (stt exists: False)
Skipping document 949/999 with OID {B47562D9-EB2D-4C51-B7D1-EE4FB0D7F0E5} because it's missing its XML file!! (stt exists: False)
Skipping document 952/999 with OID {8E88050C-E707-494C-8FAC-DA49A1E764D0} because it's missing its XML file!! (stt exists: False)
Skipping document 955/999 with OID {3B79A546-E9C4-4A47-A429-906E0EC1D617} because it's missing its XML file!! (stt exists: False)
Skipping document 957/999 with OID {FFC2366C-E28C-4A13-9A9B-9511CD852F0B} because it's missing its XML file!! (stt exists: False)
Skipping document 959/999 with OID {EE9677C2-1B76-4FA2-9167-764E2C5CB1BC} because it's missing its XML file!! (stt exists: False)
Skipping document 960/999 with OID {FA20C6FF-391C-4F81-BA60-3DE3B726068C} because it's missing its XML file!! (stt exists: False)
Skipping document 961/999 with OID {14B07E26-4A85-4F66-95C4-E3234CD4329D} because it's missing its XML file!! (stt exists: False)
Skipping document 962/999 with OID {1908BA36-F67B-4CF9-B4EB-26D4AE1D12C8} because it's missing its XML file!! (stt exists: False)
Skipping document 965/999 with OID {D4BCF570-D390-44A1-B884-ECEDF7B3C5C4} because it's missing its XML file!! (stt exists: False)
Skipping document 972/999 with OID {011C020D-0229-4CA4-9211-AFC8FD66D66B} because it's missing its XML file!! (stt exists: False)
Skipping document 978/999 with OID {1767240E-06BE-4D94-9F4F-D3FAC8D5D8A9} because it's missing its XML file!! (stt exists: False)
Skipping document 979/999 with OID {9D836E38-4648-46EF-BF2A-E20CE2ABC247} because it's missing its XML file!! (stt exists: False)
Skipping document 980/999 with OID {7EBF70D2-171A-49FA-B9D6-ACB822EE12AF} because it's missing its XML file!! (stt exists: False)
Skipping document 981/999 with OID {320ED9C2-BC40-462A-85FA-9B8947377AE3} because it's missing its XML file!! (stt exists: False)
Skipping document 982/999 with OID {35D4639E-68D9-41C7-B3E2-7D20DE827A3E} because it's missing its XML file!! (stt exists: False)
Skipping document 987/999 with OID {272D4100-9110-4FBC-A6C8-F68B2BD840A7} because it's missing its XML file!! (stt exists: False)
Skipping document 988/999 with OID {724B7BDF-4EB1-47D0-9DF6-F0A1008F97FF} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {92F3A2E4-922E-4B49-BD6F-F018F6069384}. Trying to use the recording date. doc_dict: {'alias': 'j_soir', 'date_str': None, 'stt_filename': '92F3A2E4-922E-4B49-BD6F-F018F6069384_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{92F3A2E4-922E-4B49-BD6F-F018F6069384}', 'stripped_OID': '92F3A2E4-922E-4B49-BD6F-F018F6069384', 'login': '', 'broadcast_episode_title': "En marge des travaux de la Constituante jurassienne : Interview de Daniel Jeanbourquin, qui a particip? au groupe de travail de l'ADIJ (Association pour la d?fense des int?r?ts du Jura) au projet d'office de d?veloppement pour le Jura", 'sequence': '1', 'broadcast_program_name': 'Journal du soir', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '09.03.2023 10:49:27', 'physical_support_history': "Cote d'origine: 30950 Plage 8", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives. Jura", 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:03:01.883', 'work_duration_compl': 'Non', 'participants': [{'name': 'Jeanbourquin, Daniel', 'function': 'Interview?/e', 'role': "membre du groupe de travail de l'ADIJ au projet d'office de d?veloppement pour le Jura"}, {'name': 'Boillat, Pierre (journaliste)', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Jura (canton)'], 'person_descriptors': ['ADIJ (Association pour la d?fense des int?r?ts du Jura)'], 'thematical_descriptors': ['question jurassienne', '?conomie'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Interview'], 'recording_dates': ['23/12/1976 - 23/12/1976'], 'first_broadcast_dates': None}
j_soir - returning 754 documents, 245 were skipped due to missing necessary info.

Starting extracting 999 documents for program j_soir
Skipping document 1/999 with OID {B918BAE4-D1FC-4BFA-B2F2-22AB349E4085} because it's missing its XML file!! (stt exists: False)
Skipping document 18/999 with OID {3B4A1E16-6E2C-4970-99AF-1500346F1C5F} because it's missing its XML file!! (stt exists: False)
Skipping document 31/999 with OID {75D2D6B5-030F-4B53-885A-FF0E8EB70226} because it's missing its XML file!! (stt exists: False)
Skipping document 37/999 with OID {5C9F7521-B383-45AB-BF54-EBEFDA6C3CE6} because it's missing its XML file!! (stt exists: False)
Skipping document 41/999 with OID {B8F0373B-10EA-43C0-89EB-D209898E6330} because it's missing its XML file!! (stt exists: False)
Skipping document 44/999 with OID {01969A51-58C8-43B1-BBF4-C9CCA7546F97} because it's missing its XML file!! (stt exists: False)
Skipping document 47/999 with OID {78B00247-2299-4C71-A442-1B572CF930E9} because it's missing its XML file!! (stt exists: False)
Skipping document 51/999 with OID {AC8329BB-679F-4F8B-8F37-AFB1D862DA78} because it's missing its XML file!! (stt exists: False)
Skipping document 61/999 with OID {AEA1226C-D243-42DB-AB4E-2D66D4BD464C} because it's missing its XML file!! (stt exists: False)
Skipping document 66/999 with OID {511165D8-5BF9-4671-80EC-CB65F7647524} because it's missing its XML file!! (stt exists: False)
Skipping document 68/999 with OID {D019340F-AA87-450A-84A3-552F6A763F25} because it's missing its XML file!! (stt exists: False)
Skipping document 73/999 with OID {B32DABD3-22A9-49E8-9F61-A045DAF00083} because it's missing its XML file!! (stt exists: False)
Skipping document 86/999 with OID {8D92AA00-EC73-4C56-8DCC-F8A82AB5268B} because it's missing its XML file!! (stt exists: False)
Skipping document 87/999 with OID {36CA12FD-3E69-47F4-94C3-188E18F7010C} because it's missing its XML file!! (stt exists: False)
Skipping document 88/999 with OID {6678B050-F577-495F-97C8-E3C3A6169CB5} because it's missing its XML file!! (stt exists: False)
Skipping document 89/999 with OID {5EAE137D-87A2-46D8-ABE1-B04AFAE25E6C} because it's missing its XML file!! (stt exists: False)
Skipping document 91/999 with OID {01225A75-E9DF-4752-883B-64C4842FAFDC} because it's missing its XML file!! (stt exists: False)
Skipping document 99/999 with OID {EB569C99-E82B-4D97-B58D-B0066BA85150} because it's missing its XML file!! (stt exists: False)
Skipping document 103/999 with OID {BAED6E1F-5700-4E2F-8A69-5567C7EDB22C} because it's missing its XML file!! (stt exists: False)
Skipping document 108/999 with OID {53D597E9-0456-4EF9-B7D3-5BD2C1F84D22} because it's missing its XML file!! (stt exists: False)
Skipping document 110/999 with OID {B99FFFDC-257A-4CAB-9780-32F53D0518A9} because it's missing its XML file!! (stt exists: False)
Skipping document 111/999 with OID {612637C8-F36E-44FA-B5A0-17B8B1201A34} because it's missing its XML file!! (stt exists: False)
Skipping document 118/999 with OID {6B4DD8A9-D543-43EE-B9AE-ACB378263505} because it's missing its XML file!! (stt exists: False)
Skipping document 124/999 with OID {04A11011-9559-472E-BD35-34187DAD03E2} because it's missing its XML file!! (stt exists: True)
Skipping document 128/999 with OID {5202EB73-5629-40E0-80D3-DD3A0F406711} because it's missing its XML file!! (stt exists: False)
Skipping document 132/999 with OID {5DAA7BBD-ED35-46DB-8B43-E0E2204F195F} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {3CA60A16-F93F-45BC-B2A8-1C5379398CE4}. Trying to use the recording date. doc_dict: {'alias': 'j_soir', 'date_str': None, 'stt_filename': '3CA60A16-F93F-45BC-B2A8-1C5379398CE4_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{3CA60A16-F93F-45BC-B2A8-1C5379398CE4}', 'stripped_OID': '3CA60A16-F93F-45BC-B2A8-1C5379398CE4', 'login': '', 'broadcast_episode_title': "Les radios locales en Suisse romande et leur avenir � l'occasion de la publication par la SSR de son rapport sur les radios locales en 1989 : Extraits d'archives, interviews et d�bat", 'sequence': '1', 'broadcast_program_name': 'Journal du soir', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '11.06.2022 02:26:18', 'physical_support_history': "Cote d'origine : A 21711", 'production_type': 'Production propre', 'recording_place': 'Lausanne (Studio RSR).', 'rights_notes': None, 'rights_status': None, 'series_title': None, 'content_summary': "Informations internationales. (02:22) Les radios locales en Suisse romande et leur avenir � l'occasion de la publication par la SSR de son rapport sur les radios locales en 1989. Extrait d'archive du 12.12.1983, entr�e en ondes de la premi�re radio locale, Radio Gen�ve Information et Musique de Suisse romande. Extraits capt�s de plusieur autres radios locales. (06:52) La fin de Radio-L, le 28 mars 1990. Interview de Fran�ois Pidoux, chef du marketing � la RTSR.(10:15) Pierre-Ami Chevallier, �diteur du Journal de Gen�ve, � propos du succ�s ou de l'�chec de plusieurs radios en Suisse romande. (  ) Fr�d�ric Riehl, responsable au D�partement f�d�ral des transports et communications des affaires concernant la Suisse romande. (15:03) Antonio Riva directeur g�n�ral de la SSR, sur un �ventuel partage de la redevance avec les radios locales.", 'workflow_status': 'Valid�', 'assembly_status': 'Mont�', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Girardin, Manuel', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur RSR'}, {'name': 'Graf, Yvan', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur RSR'}, {'name': 'Gfeller, Urs', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur RSR'}, {'name': 'Pidoux, Fran�ois', 'function': 'Interview�/e', 'role': 'collaborateur RSR'}, {'name': 'Chevalier, Pierre-Ami', 'function': 'Interview�/e', 'role': '�diteur du Journal de Gen�ve'}, {'name': 'Riehl, Fr�d�ric', 'function': 'Interview�/e', 'role': 'responsable au D�partement f�d�ral des transports et communications des affaires concernant la Suisse romande'}, {'name': 'Riva, Antonio', 'function': 'Interview�/e', 'role': 'directeur g�n�ral de la SSR'}, {'name': 'Pasche, Marcel', 'function': 'Interview�/e', 'role': 'responsable Radio-L'}, {'name': 'D�fago, Claude', 'function': 'Interview�/e', 'role': 'patron de Radio-Chablais'}, {'name': 'Sapey, G�rald', 'function': 'Interview�/e', 'role': 'directeur de RSR La Premi�re'}, {'name': 'Bonnard, Laurent', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Lausanne', 'Suisse romande'], 'person_descriptors': ['SSR', 'RTSR'], 'thematical_descriptors': ['radio locale', 'radio', 'publicit�'], 'rights_usage_possibilities': None, 'radio_channels': None, 'subdomains': ['Interview', 'D�bat'], 'recording_dates': ['06/04/1990 - 06/04/1990'], 'first_broadcast_dates': None}
Skipping document 136/999 with OID {70AD5AC2-1516-4A36-91FF-6964C77301EF} because it's missing its XML file!! (stt exists: False)
Skipping document 140/999 with OID {B9E56868-84C9-4B38-B0F6-B53D1B85E7AF} because it's missing its XML file!! (stt exists: False)
Skipping document 145/999 with OID {F773A888-F3D3-47CE-AD94-B388E8611D35} because it's missing its XML file!! (stt exists: False)
The date for document with OID {48224334-CEBE-4748-879F-07242AE7D5F4} was invalid (__/__/1956) - changed it to 01/01/1956
Skipping document 151/999 with OID {0405D27A-BABF-4FFB-8AFA-35889EEF48E5} because it's missing its XML file!! (stt exists: False)
Skipping document 155/999 with OID {6E559328-92E5-4292-8DF9-43323AE60273} because it's missing its XML file!! (stt exists: False)
Skipping document 157/999 with OID {B97214CA-2F45-43C6-BD16-BFED70DAFF6B} because it's missing its XML file!! (stt exists: False)
Skipping document 159/999 with OID {E0552D1D-22BC-4FB2-9959-60BCFB40C9F8} because it's missing its audio MP3 file!!
Skipping document 161/999 with OID {37587545-8189-4BB8-94F7-384DFEC0A330} because it's missing its XML file!! (stt exists: False)
Skipping document 164/999 with OID {D52CB27A-7F64-4D69-94B3-AADAB1BFF0B1} because it's missing its XML file!! (stt exists: False)
Skipping document 165/999 with OID {0E0AE698-DA70-4EEA-A465-33B51045F38C} because it's missing its XML file!! (stt exists: False)
Skipping document 173/999 with OID {C150197E-B5FF-4A2B-BA50-2DC6F5F3EF4B} because it's missing its XML file!! (stt exists: False)
Skipping document 174/999 with OID {1E41B4A4-5871-4D69-99E7-484A550FCEA7} because it's missing its XML file!! (stt exists: False)
Skipping document 179/999 with OID {E5B63D8A-D0F4-40FC-A859-E430B8258F4A} because it's missing its XML file!! (stt exists: False)
Skipping document 180/999 with OID {FF60E466-98A1-4A91-A327-5C526756330B} because it's missing its XML file!! (stt exists: False)
Skipping document 185/999 with OID {C89B49B9-FAC7-46DF-A7EE-ED5AC82428E2} because it's missing its XML file!! (stt exists: False)
Skipping document 193/999 with OID {FC4CDFB2-4C0F-40EE-9980-BFC4F872F88A} because it's missing its XML file!! (stt exists: False)
Skipping document 198/999 with OID {5E7CCFED-45EC-46BF-8D74-9EF4BCE1D129} because it's missing its XML file!! (stt exists: False)
Skipping document 199/999 with OID {A3AA928E-96EB-4F5C-984D-7BAD86600558} because it's missing its XML file!! (stt exists: False)
Skipping document 202/999 with OID {DDADC24E-B837-4AA4-820E-28F96F1BDD8A} because it's missing its XML file!! (stt exists: False)
Skipping document 208/999 with OID {8D7A75B1-D06C-4847-83FD-072C97DE1460} because it's missing its XML file!! (stt exists: True)
Skipping document 210/999 with OID {43FBAEAD-B55B-4414-AF6A-2775946446EF} because it's missing its XML file!! (stt exists: False)
Skipping document 211/999 with OID {A9EED77D-6F44-49BF-80FB-D624D3E0AEBE} because it's missing its XML file!! (stt exists: False)
Skipping document 212/999 with OID {41E15418-4306-4C49-A8CD-D06B5CE44BA7} because it's missing its XML file!! (stt exists: False)
Skipping document 214/999 with OID {89326E49-3706-4635-BAA5-98DB92C9E685} because it's missing its XML file!! (stt exists: False)
Skipping document 215/999 with OID {167198AE-A574-43B9-B417-9FCFEBEFF4D3} because it's missing its XML file!! (stt exists: False)
Skipping document 220/999 with OID {B139BB41-652C-46CD-8EAF-770DEFF6D093} because it's missing its XML file!! (stt exists: False)
Skipping document 234/999 with OID {11BA8CBE-0313-44CC-85EB-C99186FC8482} because it's missing its XML file!! (stt exists: True)
Skipping document 239/999 with OID {41E0AC8A-BF1A-476A-B82E-002E358F46F8} because it's missing its XML file!! (stt exists: False)
Skipping document 242/999 with OID {5F56F73D-C030-4634-98DC-2E95C671AA4B} because it's missing its XML file!! (stt exists: False)
Skipping document 244/999 with OID {3B004C4B-B918-4435-A97C-F2FD48A78017} because it's missing its XML file!! (stt exists: False)
Skipping document 251/999 with OID {2F2FB17C-FFE3-40A2-93FF-842EA1F1D8B6} because it's missing its XML file!! (stt exists: False)
Skipping document 253/999 with OID {F6A488A6-BA05-4F55-B343-872638A7B982} because it's missing its XML file!! (stt exists: True)
Skipping document 254/999 with OID {D32C60F1-B648-4246-B6FB-2A15868BC1E9} because it's missing its XML file!! (stt exists: False)
Skipping document 255/999 with OID {378F04F5-377B-4629-8B67-7FE52E531052} because it's missing its XML file!! (stt exists: False)
Skipping document 257/999 with OID {F5A6B6BE-22BF-429B-B61B-DBD0CC42E74E} because it's missing its XML file!! (stt exists: False)
Skipping document 258/999 with OID {618D03FD-1BEA-4A2A-BF2E-C9448FA22887} because it's missing its XML file!! (stt exists: False)
Skipping document 259/999 with OID {0BD20C74-EB95-46F6-B07D-AD464418EA35} because it's missing its XML file!! (stt exists: False)
Skipping document 260/999 with OID {8506039D-1596-46C1-B77E-A2C359B868C7} because it's missing its XML file!! (stt exists: False)
Skipping document 261/999 with OID {3CD1C6E4-26BB-4759-9DCB-C4659BDCFFF5} because it's missing its XML file!! (stt exists: False)
Skipping document 262/999 with OID {12CCCCC1-F6DE-46A5-A5C6-37D6B61A24A4} because it's missing its XML file!! (stt exists: False)
Skipping document 263/999 with OID {C56C3556-D9E5-4F7C-B059-38EBB5005A19} because it's missing its XML file!! (stt exists: False)
Skipping document 264/999 with OID {097509D7-2CB5-4C4E-99F2-F7897963E633} because it's missing its XML file!! (stt exists: False)
Skipping document 265/999 with OID {977E461C-6676-4C8C-8A64-F118ED31EE04} because it's missing its XML file!! (stt exists: False)
Skipping document 266/999 with OID {FF4A4533-ECEE-441E-8961-70FCF6F4E086} because it's missing its XML file!! (stt exists: False)
Skipping document 267/999 with OID {668F6FF9-538C-46E2-92D3-852190F8228C} because it's missing its XML file!! (stt exists: False)

Skipping document 963/999 with OID {8E073D50-2D10-4B76-BC59-E86A4ABA970F} because it's missing its XML file!! (stt exists: False)
Skipping document 971/999 with OID {6132571F-7DB4-460D-A7C8-78EE1C2E83EE} because it's missing its XML file!! (stt exists: False)
Skipping document 976/999 with OID {A1E2358C-1304-466B-B9B4-B8B6381BA388} because it's missing its XML file!! (stt exists: False)
Skipping document 977/999 with OID {B6C62EBB-8AE4-4571-B6B8-3AE567AF4B4F} because it's missing its XML file!! (stt exists: False)
Skipping document 984/999 with OID {DC660BE2-5576-4A7B-8F32-46539A01F4E5} because it's missing its XML file!! (stt exists: False)
Skipping document 985/999 with OID {94F68FDF-F3C8-4384-B5D0-B67935C6CE2E} because it's missing its XML file!! (stt exists: False)
Skipping document 987/999 with OID {93FDD7C4-2C79-436F-82BF-319459740160} because it's missing its XML file!! (stt exists: False)
Skipping document 988/999 with OID {809CD216-18CF-4E0A-9F6D-5ACC2A9C9C35} because it's missing its XML file!! (stt exists: False)
Skipping document 992/999 with OID {92529EE2-1619-4441-BB11-92118F1C298F} because it's missing its XML file!! (stt exists: False)
Skipping document 999/999 with OID {5FEF1C0D-7A9A-4AF0-88DF-F7890722A3B0} because it's missing its XML file!! (stt exists: False)
j_soir - returning 710 documents, 289 were skipped due to missing necessary info.

Starting extracting 999 documents for program j_soir
Skipping document 3/999 with OID {3E81D140-6C00-4859-BB7D-E08D5CEA7D3A} because it's missing its XML file!! (stt exists: False)
Skipping document 11/999 with OID {9F9557FB-4183-4B25-B99D-CDDA1FA4353D} because it's missing its XML file!! (stt exists: False)
Skipping document 20/999 with OID {8B272E80-14D6-49CA-A605-F25A68202196} because it's missing its XML file!! (stt exists: False)
Skipping document 29/999 with OID {1FF14C95-B588-413C-B30D-B490B56830B4} because it's missing its XML file!! (stt exists: False)
Skipping document 40/999 with OID {59DC2363-C336-4374-8402-9BD8FC1E83AC} because it's missing its XML file!! (stt exists: False)
Skipping document 52/999 with OID {D709EDD5-B97D-479C-8D6B-E86637CCBD63} because it's missing its XML file!! (stt exists: False)
Skipping document 53/999 with OID {04F3690F-FCA5-4EA8-937E-10DE443163C8} because it's missing its XML file!! (stt exists: False)
Skipping document 54/999 with OID {65E0412E-4166-43B9-AA15-121E7E1C998C} because it's missing its XML file!! (stt exists: False)
Skipping document 59/999 with OID {13D5D463-4BB6-46BE-9BA4-4C00876BA522} because it's missing its XML file!! (stt exists: False)
Skipping document 61/999 with OID {DC0C9932-4E6D-457E-AB74-0CAF0CB2F6AC} because it's missing its XML file!! (stt exists: False)
Skipping document 63/999 with OID {D3A60BF8-553A-4AF8-9E5A-6C497E603D24} because it's missing its XML file!! (stt exists: False)
Skipping document 71/999 with OID {DF05BB27-F242-4157-A37A-9531A71F4EE9} because it's missing its XML file!! (stt exists: False)
Skipping document 74/999 with OID {6B64583D-D4A8-41BC-90E5-D9B8FDA2CCD3} because it's missing its XML file!! (stt exists: True)
Skipping document 75/999 with OID {09CBC3EC-7A12-4343-851C-B5BAA28D744E} because it's missing its XML file!! (stt exists: True)
Skipping document 77/999 with OID {0472C403-C0E5-4330-A94D-ACD4DAC83EF1} because it's missing its XML file!! (stt exists: False)
Skipping document 85/999 with OID {7ED7ACB4-651D-4783-9365-234FB858B956} because it's missing its XML file!! (stt exists: False)
Skipping document 86/999 with OID {DC6105B4-9A32-4179-B785-78FFAC34D05A} because it's missing its XML file!! (stt exists: False)
Skipping document 87/999 with OID {3A4C0526-3117-4F9C-9500-559F835269E1} because it's missing its XML file!! (stt exists: False)
Skipping document 88/999 with OID {37CAAB53-3A70-4541-AFA7-6F6D421CAB96} because it's missing its XML file!! (stt exists: False)
Skipping document 89/999 with OID {5236BD31-068E-47A3-87D3-807CE27D24DF} because it's missing its XML file!! (stt exists: False)
Skipping document 107/999 with OID {80C68DB6-A455-4C2C-BD1F-6B1ED3B04AB0} because it's missing its XML file!! (stt exists: True)
Skipping document 108/999 with OID {C8970461-3767-456F-A333-40973B70CB0D} because it's missing its XML file!! (stt exists: False)
Skipping document 109/999 with OID {143E80D2-6277-4B83-B24F-A24B8DAAA88C} because it's missing its XML file!! (stt exists: False)
Skipping document 110/999 with OID {2EA3235B-FA72-4DC6-BED8-68DF8BCA32E4} because it's missing its XML file!! (stt exists: False)
Skipping document 111/999 with OID {B91FFF9C-3E47-43E1-A113-F7AAEDD6FF5B} because it's missing its XML file!! (stt exists: False)
Skipping document 121/999 with OID {EFBFC7DB-0316-4570-A30D-53CDA589CD84} because it's missing its XML file!! (stt exists: False)
Skipping document 122/999 with OID {CFF138F6-E382-4070-BA72-6DFF87EC6EE9} because it's missing its XML file!! (stt exists: False)
Skipping document 123/999 with OID {89617207-003B-4FD5-B48C-DA53BE7D6BA2} because it's missing its XML file!! (stt exists: False)
Skipping document 124/999 with OID {CBEC90C3-EC7E-4F5A-9350-65F9AD3A0517} because it's missing its XML file!! (stt exists: False)
Skipping document 125/999 with OID {9C15DC82-4EC5-489E-A874-FAB50EE3D304} because it's missing its XML file!! (stt exists: False)
Skipping document 129/999 with OID {81F8A0BE-8760-4335-8CD5-935AFA1E8A82} because it's missing its XML file!! (stt exists: False)
Skipping document 131/999 with OID {7BC3B642-2F3C-48EC-A6A9-3DE1E2A1AEA0} because it's missing its XML file!! (stt exists: False)
Skipping document 135/999 with OID {EC28B190-B1D5-46CC-9D2C-D4C12625790A} because it's missing its XML file!! (stt exists: False)
Skipping document 136/999 with OID {95380E98-7F4B-436D-8645-1AE5069CD205} because it's missing its XML file!! (stt exists: False)
Skipping document 137/999 with OID {4F62E07E-DEBA-4496-909D-EB28EE92DA09} because it's missing its XML file!! (stt exists: False)
Skipping document 138/999 with OID {27E3AC8F-5A46-456B-B965-C45570AAA134} because it's missing its XML file!! (stt exists: False)
Skipping document 139/999 with OID {129EA3B0-BD57-48E8-AFAD-04A540AB7AA0} because it's missing its XML file!! (stt exists: False)
Skipping document 147/999 with OID {8B1A1521-80EC-4728-8761-CA0A4051EE2B} because it's missing its XML file!! (stt exists: False)
Skipping document 148/999 with OID {0A79B31B-A1FD-4026-B720-4D250FDA73BE} because it's missing its XML file!! (stt exists: False)
Skipping document 152/999 with OID {301E7ADB-84F6-4F1F-9ED9-8D7E34CE0669} because it's missing its XML file!! (stt exists: False)
Skipping document 154/999 with OID {B7EBDC9D-35CE-4755-BAB2-18CBC27EBE2E} because it's missing its XML file!! (stt exists: False)
Skipping document 155/999 with OID {49898F1C-A46C-4AE0-9FCB-629603CCDBC1} because it's missing its XML file!! (stt exists: False)
Skipping document 156/999 with OID {02289A07-F8A2-4D26-9994-9C5629B10568} because it's missing its XML file!! (stt exists: False)
Skipping document 161/999 with OID {7FDAD019-F98D-4435-9445-082AE06F1BDF} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {DA9B87F2-BED3-431D-9697-2571881C56F1}. Trying to use the recording date. doc_dict: {'alias': 'j_soir', 'date_str': None, 'stt_filename': 'DA9B87F2-BED3-431D-9697-2571881C56F1_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{DA9B87F2-BED3-431D-9697-2571881C56F1}', 'stripped_OID': 'DA9B87F2-BED3-431D-9697-2571881C56F1', 'login': '', 'broadcast_episode_title': "R?actions du fils du colonel brigadier Jean-Louis Jeanmaire suite ? l'arrestation de son p?re", 'sequence': '1', 'broadcast_program_name': 'Journal du soir', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '01.06.2022 00:20:44', 'physical_support_history': "Cote d'origine: 30644 Pl. 2", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav (SRG 75)', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': "Jean-Louis Jeanmaire est accus? d'espionnage avec l'URSS. Sa famille n'a aucune nouvelle de lui ni de l'endroit o? il se trouve.", 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:04:38.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Jeanmaire (nom de famille)', 'function': 'Interview?/e', 'role': 'fils du colonel brigadier Jean-Louis Jeanmaire'}, {'name': 'Valloton, Jacques', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Suisse', 'URSS'], 'person_descriptors': ['Jeanmaire, Jean-Louis'], 'thematical_descriptors': ['arrestation', 'espionnage'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Interview'], 'recording_dates': ['17/08/1976 - 17/08/1976'], 'first_broadcast_dates': None}
Skipping document 171/999 with OID {890AA5DA-C03D-4064-8A27-31E7DA24C5F6} because it's missing its XML file!! (stt exists: False)
Skipping document 173/999 with OID {876C0E37-BE6C-4B71-8A88-4C999B02A9E7} because it's missing its XML file!! (stt exists: False)
Skipping document 176/999 with OID {55B5ECC2-BEB3-4F48-AF6D-53D3B552C9E5} because it's missing its XML file!! (stt exists: False)
Skipping document 177/999 with OID {6E3EF262-8B36-42B0-9B02-7DB81AE68000} because it's missing its XML file!! (stt exists: False)
Skipping document 179/999 with OID {1B119D74-49B3-41D2-AE89-F93F73B46E73} because it's missing its XML file!! (stt exists: False)
Skipping document 181/999 with OID {25A3650B-FC48-469C-995B-C1D1CE81BD41} because it's missing its XML file!! (stt exists: False)
Skipping document 182/999 with OID {2473455A-AF42-4F91-B302-FA53276E99AB} because it's missing its XML file!! (stt exists: False)
Skipping document 185/999 with OID {B70F0321-5382-45CD-9D0D-9B126655C2E8} because it's missing its XML file!! (stt exists: False)
Skipping document 189/999 with OID {C3CF64E7-9DAF-413D-956D-E8457EA6EFE4} because it's missing its XML file!! (stt exists: False)
Skipping document 190/999 with OID {D1A64BB1-2A35-4C89-A093-940E14FB20E4} because it's missing its XML file!! (stt exists: False)
Skipping document 194/999 with OID {CC109D49-C5D9-4855-B4A5-EA4945A9EF9B} because it's missing its XML file!! (stt exists: False)
Skipping document 195/999 with OID {B00EF769-594C-42CE-AEA2-D20C436E5BA6} because it's missing its XML file!! (stt exists: False)
Skipping document 197/999 with OID {DD522C7C-F8AE-41AB-A7E0-75DD2FCEF818} because it's missing its XML file!! (stt exists: False)
Skipping document 200/999 with OID {4C4A1DE9-511A-47A3-9341-52B959479BE4} because it's missing its XML file!! (stt exists: False)
Skipping document 206/999 with OID {A86E7CD1-17A8-4280-9E60-5BC9C2CDF7FC} because it's missing its XML file!! (stt exists: False)
Skipping document 207/999 with OID {83521221-1DE9-43FF-B297-3AAA177AE983} because it's missing its XML file!! (stt exists: False)
Skipping document 209/999 with OID {C6FE92C0-BD23-415E-8250-FF122C3BC07D} because it's missing its XML file!! (stt exists: False)
Skipping document 223/999 with OID {471B947A-A3DF-4DCB-979C-A740847BB5C8} because it's missing its XML file!! (stt exists: False)
Skipping document 224/999 with OID {28B8A22D-1158-42FA-B7A4-5C5B1D8A6D61} because it's missing its XML file!! (stt exists: False)
Skipping document 225/999 with OID {798F82D3-94A0-43F9-9E0B-3D57757C341A} because it's missing its XML file!! (stt exists: False)
Skipping document 226/999 with OID {C75E6489-A705-4132-B9AD-076AD359C4EC} because it's missing its XML file!! (stt exists: False)
Skipping document 227/999 with OID {8D511503-D9A4-4E9B-8DC8-2BB4EBB10748} because it's missing its XML file!! (stt exists: False)
Skipping document 228/999 with OID {FCC95F23-5F48-48DC-A475-6EDE8AF6C087} because it's missing its XML file!! (stt exists: False)
Skipping document 229/999 with OID {86C9621C-CE9E-488F-81F3-5111B2BA22CD} because it's missing its XML file!! (stt exists: False)
Skipping document 230/999 with OID {A5BA5044-DA06-45FA-8A9F-14E51AF8D7C5} because it's missing its XML file!! (stt exists: False)
Skipping document 231/999 with OID {DDD5A03D-395E-47DA-85BA-1002266B2313} because it's missing its XML file!! (stt exists: False)
Skipping document 232/999 with OID {8982F199-D53E-489B-B6AC-841951096796} because it's missing its XML file!! (stt exists: False)
Skipping document 233/999 with OID {FE9909E1-4600-4AB1-BAD0-EB1EF6EDC56D} because it's missing its XML file!! (stt exists: False)
Skipping document 245/999 with OID {E8464FA0-23B9-4EB6-8075-8B1684B5DADA} because it's missing its XML file!! (stt exists: False)
Skipping document 246/999 with OID {CBE49EB8-059D-4246-9F38-72F719C4D4F7} because it's missing its XML file!! (stt exists: False)
Skipping document 247/999 with OID {D9363055-32C3-4B6E-B205-19B34FEA2696} because it's missing its XML file!! (stt exists: False)
Skipping document 248/999 with OID {E1C9AC0F-B920-4181-B2B0-81FEE68AAD79} because it's missing its XML file!! (stt exists: False)
Skipping document 249/999 with OID {356921C0-4ADD-4F1E-B7A6-AD9667FFFD4D} because it's missing its XML file!! (stt exists: False)
Skipping document 252/999 with OID {0A58E5D1-C790-419A-AD83-896ACD24B956} because it's missing its XML file!! (stt exists: False)
Skipping document 256/999 with OID {BEAB211C-E569-4EA3-98E5-671EE0775C09} because it's missing its XML file!! (stt exists: False)
Skipping document 257/999 with OID {0AB7C336-3D08-4B0A-BFF5-8AE12EDDC3D6} because it's missing its XML file!! (stt exists: False)
Skipping document 275/999 with OID {D1D15A25-12E7-4FF7-8827-1092266547B7} because it's missing its XML file!! (stt exists: False)
Skipping document 278/999 with OID {D48A1857-2252-445A-8241-95BA6F1561C9} because it's missing its XML file!! (stt exists: False)
Skipping document 279/999 with OID {7498BA63-9BE3-4CC3-919E-10196DD0F757} because it's missing its XML file!! (stt exists: False)
Skipping document 280/999 with OID {0AA82872-2069-43B3-8CE0-D174E878C80C} because it's missing its XML file!! (stt exists: False)
Skipping document 283/999 with OID {BC8CC9DE-7AA9-4B56-A631-695D8C575BC9} because it's missing its XML file!! (stt exists: False)
Skipping document 284/999 with OID {91F04E2E-59DB-465B-97B6-363E024DEC27} because it's missing its XML file!! (stt exists: False)
Skipping document 287/999 with OID {091EE2A6-0439-4045-9842-18F7B4DC8593} because it's missing its XML file!! (stt exists: False)
Skipping document 291/999 with OID {58F34ABF-9A2F-4883-8001-734F4D8430B3} because it's missing its XML file!! (stt exists: False)
Skipping document 297/999 with OID {503C1527-B043-4474-A95C-EB928897D86F} because it's missing its XML file!! (stt exists: False)
Skipping document 301/999 with OID {21A5D57B-0255-440B-86F7-C872CA07F5D5} because it's missing its XML file!! (stt exists: False)
Skipping document 303/999 with OID {2B741555-8A1B-4CB3-8700-9E404061DD13} because it's missing its XML file!! (stt exists: False)
Skipping document 304/999 with OID {32F26E37-92C4-4789-AB41-D4343BE02D37} because it's missing its XML file!! (stt exists: False)
Skipping document 311/999 with OID {F75A1745-8976-4A5A-94CF-2A1F7E8297B4} because it's missing its XML file!! (stt exists: False)
Skipping document 329/999 with OID {C4C97B89-1667-488F-9244-B71A4B58B696} because it's missing its XML file!! (stt exists: False)
Skipping document 330/999 with OID {25E14779-44D9-474C-B022-0FC19413818C} because it's missing its XML file!! (stt exists: False)
Skipping document 333/999 with OID {D7367C28-8605-4FEA-AF77-06E1D63B5EDF} because it's missing its XML file!! (stt exists: False)
Skipping document 334/999 with OID {3BD13F7A-672D-4326-99B6-1F4099B865A4} because it's missing its XML file!! (stt exists: False)
Skipping document 340/999 with OID {AFA318A2-D446-4D7E-A888-6DB690DEFF8D} because it's missing its XML file!! (stt exists: False)
Skipping document 341/999 with OID {520D7609-4ED7-4F6E-8D23-94CCB5571DE6} because it's missing its XML file!! (stt exists: False)
Skipping document 344/999 with OID {2691D7BF-5FF1-4678-BB16-BF093709A0D4} because it's missing its XML file!! (stt exists: False)
Skipping document 348/999 with OID {7B2B2A43-26CB-4D50-AB80-229332907A19} because it's missing its XML file!! (stt exists: False)
Skipping document 349/999 with OID {03432D95-2114-4B4F-B5C5-6BD1E9C33AA6} because it's missing its XML file!! (stt exists: False)
Skipping document 351/999 with OID {643E4593-583F-433E-9CDB-41AEE4731C09} because it's missing its XML file!! (stt exists: False)
Skipping document 369/999 with OID {4CD0A389-B4F3-4F37-B6E2-8C0A885C5EBA} because it's missing its XML file!! (stt exists: False)
Skipping document 370/999 with OID {3D746719-DD2C-4A96-ADD7-F3AFD49962F2} because it's missing its XML file!! (stt exists: False)
Skipping document 371/999 with OID {FF312971-C964-4E52-9B29-AF69E7A3A37F} because it's missing its XML file!! (stt exists: False)
Skipping document 372/999 with OID {A1B4302E-2BE5-415D-B77F-0981A381DA2B} because it's missing its XML file!! (stt exists: False)
Skipping document 373/999 with OID {BE589B81-794C-4C4B-9F4B-356C77AB9AA8} because it's missing its XML file!! (stt exists: False)
Skipping document 374/999 with OID {0CDC8D8D-85E4-4F00-83B7-BEF43EA0F758} because it's missing its XML file!! (stt exists: False)
Skipping document 375/999 with OID {7B1F390D-5618-4A70-84E6-B71486E7C3F8} because it's missing its XML file!! (stt exists: False)
Skipping document 376/999 with OID {412D54F9-6FBE-4C35-B4D2-1098A1BA471A} because it's missing its XML file!! (stt exists: False)
Skipping document 386/999 with OID {2815E469-729A-4186-8DE0-EE4222FFE027} because it's missing its XML file!! (stt exists: False)
Skipping document 396/999 with OID {FD103155-2F1B-4341-A4FD-367DC27EA3C5} because it's missing its XML file!! (stt exists: False)
Skipping document 398/999 with OID {9D0D3937-3818-4AB1-B20D-4565366A1A4B} because it's missing its XML file!! (stt exists: False)
Skipping document 400/999 with OID {20CCF2EB-BA0E-49DA-8351-3B3484F28EF8} because it's missing its XML file!! (stt exists: True)
Skipping document 405/999 with OID {264310E7-F9A0-41FE-B283-FDC2883AC214} because it's missing its XML file!! (stt exists: True)
Skipping document 411/999 with OID {BA265FE3-F73B-4024-A3C7-7B31633BA113} because it's missing its XML file!! (stt exists: False)
Skipping document 412/999 with OID {3C077683-F9E0-471D-A88B-AABECB19C47B} because it's missing its XML file!! (stt exists: False)
Skipping document 422/999 with OID {6B8AB205-CC20-4427-9A76-CC8768AFCC13} because it's missing its XML file!! (stt exists: False)
Skipping document 426/999 with OID {2166CFF3-6A3A-402A-8CC4-19FB18A4BED5} because it's missing its XML file!! (stt exists: False)
Skipping document 427/999 with OID {D24662C0-A1B6-4929-9E20-C975C8FD0305} because it's missing its XML file!! (stt exists: False)
Skipping document 428/999 with OID {642EA7AD-047F-4835-A0E1-F518E8BA3FDC} because it's missing its XML file!! (stt exists: False)
Skipping document 431/999 with OID {9C7CC8C9-8145-4BC2-9B15-D1AEFC8DA7BC} because it's missing its XML file!! (stt exists: False)
Skipping document 433/999 with OID {49868BDE-BFCE-416F-A331-539646DB6DF7} because it's missing its XML file!! (stt exists: False)
Skipping document 434/999 with OID {B031B9FA-6F1D-471E-AD7F-8E986D55B8E1} because it's missing its XML file!! (stt exists: False)
Skipping document 435/999 with OID {8D322998-1AE9-4949-A018-8772543651C6} because it's missing its XML file!! (stt exists: False)
Skipping document 437/999 with OID {1EBCE782-1F94-4799-B808-5C970604F302} because it's missing its XML file!! (stt exists: False)
Skipping document 439/999 with OID {07E9A058-6864-487C-B268-B765A2CA9DFE} because it's missing its XML file!! (stt exists: False)

Skipping document 992/999 with OID {6913ACEE-A0EA-4251-A1FA-CBC3177DD502} because it's missing its XML file!! (stt exists: True)
Skipping document 994/999 with OID {3FDF8B6A-047C-418F-B924-ED26F78AAD61} because it's missing its XML file!! (stt exists: True)
j_soir - returning 719 documents, 280 were skipped due to missing necessary info.

Starting extracting 998 documents for program j_soir
Skipping document 4/998 with OID {8DB402EC-CD29-430E-A690-AF6F0FB06202} because it's missing its XML file!! (stt exists: False)
Skipping document 5/998 with OID {641B1565-457F-4928-91A8-3AFE31D51B46} because it's missing its XML file!! (stt exists: False)
Skipping document 6/998 with OID {9DF2ED51-2A05-4D00-A405-9D40390EE577} because it's missing its XML file!! (stt exists: False)
Skipping document 7/998 with OID {1E9143AF-FE35-46D6-B134-85160CB31395} because it's missing its XML file!! (stt exists: False)
Skipping document 8/998 with OID {1A818A71-3FBA-4EDA-AED2-EC937A0EBED2} because it's missing its XML file!! (stt exists: False)
Skipping document 9/998 with OID {F0C93DC2-22D3-4065-A61A-1C4D82503B4A} because it's missing its XML file!! (stt exists: False)
Skipping document 14/998 with OID {B9CDFEB6-28EC-4953-B4E1-FFC838C9BE8F} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {E1314418-AB8A-4C0C-BBE0-85BD77711319}. Trying to use the recording date. doc_dict: {'alias': 'j_soir', 'date_str': None, 'stt_filename': 'E1314418-AB8A-4C0C-BBE0-85BD77711319_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{E1314418-AB8A-4C0C-BBE0-85BD77711319}', 'stripped_OID': 'E1314418-AB8A-4C0C-BBE0-85BD77711319', 'login': '', 'broadcast_episode_title': "[Extrait] L'annonce de la derni?re pi?ce polici?re du lundi soir ? la Radio suisse romande : Interview de William Jacques", 'sequence': '2', 'broadcast_program_name': 'Journal du soir', 'document_type': 'Parl?', 'hierarchy_level': 'Extrait', 'modified_by': 'favreni', 'modified_on': '09.03.2023 14:00:01', 'physical_support_history': "Cote d'origine : Bd 9892 Resp. RSR : AQT Lot : Caisse 3207", 'production_type': 'Production propre', 'recording_place': 'Lausanne (studio RSR). Gen?ve.', 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Magazine. Sauvegarde d'archives", 'content_summary': 'Ce reportage ?voque la production de la pi?ce polici?re.', 'workflow_status': 'Valid?', 'assembly_status': 'Pr?t', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Jacques, William', 'function': 'Interview?/e', 'role': 'metteur en ondes et com?dien'}, {'name': 'Girardin, Manuel', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Suisse romande'], 'person_descriptors': None, 'thematical_descriptors': ['art dramatique', 'radio', '?mission de radio', 'pi?ce polici?re radiophonique'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Interview'], 'recording_dates': ['__/11/1989 - __/11/1989'], 'first_broadcast_dates': None}
The date for document with OID {E1314418-AB8A-4C0C-BBE0-85BD77711319} was invalid (__/11/1989) - changed it to 01/11/1989
The date for document with OID {E1314418-AB8A-4C0C-BBE0-85BD77711319} was invalid (__/11/1989) - changed it to 01/11/1989
Skipping document 32/998 with OID {E5B3CDF2-C31F-4AB5-BF25-226E1FF9DC23} because it's missing its XML file!! (stt exists: False)
Skipping document 47/998 with OID {A85044E4-FB73-4533-82D0-7166BCC90854} because it's missing its XML file!! (stt exists: False)
Skipping document 62/998 with OID {35AAE7F4-E6B0-4B6D-86A0-B26DA1033F9B} because it's missing its XML file!! (stt exists: False)
Skipping document 70/998 with OID {5CC745FB-2BCD-418C-9D5F-5CC2DDD6D96E} because it's missing its XML file!! (stt exists: False)
Skipping document 71/998 with OID {5AE6D882-7F66-493F-9285-72BBA6041D7E} because it's missing its XML file!! (stt exists: False)
Skipping document 72/998 with OID {C481F0C4-D2A9-4494-8D79-B7549E6A12EA} because it's missing its XML file!! (stt exists: False)
Skipping document 73/998 with OID {A3226909-E329-497C-88EF-643A3A1BBFF6} because it's missing its XML file!! (stt exists: False)
Skipping document 79/998 with OID {F3C5390D-6CDA-467D-BE50-E3796EB8D9CE} because it's missing its XML file!! (stt exists: False)
Skipping document 81/998 with OID {AEEE674B-6D5C-457A-B2EC-AB4D40C7AE2F} because it's missing its XML file!! (stt exists: False)
Skipping document 83/998 with OID {CCB65417-7089-45FE-8877-B25B0CA34FDF} because it's missing its XML file!! (stt exists: False)
Skipping document 88/998 with OID {9EA1DEE6-A5CC-49CF-8AD3-2072C89B7B78} because it's missing its XML file!! (stt exists: False)
Skipping document 90/998 with OID {4914D461-3460-4DE0-B173-F1EE558EBA4C} because it's missing its XML file!! (stt exists: False)
Skipping document 94/998 with OID {80DD0387-ED13-4596-AFA3-4920F7E43A80} because it's missing its XML file!! (stt exists: False)
Skipping document 95/998 with OID {6C0642AE-B30B-4C2A-8DAE-25E27F913991} because it's missing its XML file!! (stt exists: False)
Skipping document 97/998 with OID {DDF320C5-002D-4A77-ADCA-D5CED929B0A2} because it's missing its XML file!! (stt exists: False)
Skipping document 99/998 with OID {E7AAB0DE-48CF-4A3D-9FA2-B051B0922A55} because it's missing its XML file!! (stt exists: False)
Skipping document 102/998 with OID {348F3FBC-0B93-4BF3-B249-66A082F7619A} because it's missing its XML file!! (stt exists: False)
Skipping document 103/998 with OID {84B3136C-330B-4D81-AD1F-539169A6D02A} because it's missing its XML file!! (stt exists: False)
Skipping document 107/998 with OID {35736678-B1DA-418E-9925-72E13118B15E} because it's missing its XML file!! (stt exists: False)
Skipping document 109/998 with OID {FBDF8E53-39A3-45B5-91B4-230E93FBE53F} because it's missing its XML file!! (stt exists: False)
Skipping document 110/998 with OID {04D986C0-EC47-4D48-B277-3E2CBB64EE88} because it's missing its XML file!! (stt exists: False)
Skipping document 111/998 with OID {AC18DE74-1EC3-42FE-B176-C7084F2D23E9} because it's missing its XML file!! (stt exists: False)
Skipping document 112/998 with OID {5F8C55DC-04D2-433C-9D25-4B42B6B4BD5F} because it's missing its XML file!! (stt exists: False)
Skipping document 113/998 with OID {D40269D6-CA43-4630-AC53-7CE58F061EC6} because it's missing its XML file!! (stt exists: False)
Skipping document 116/998 with OID {9EB5DC83-377B-427F-92C9-9F090704B71A} because it's missing its XML file!! (stt exists: False)
Skipping document 122/998 with OID {D574B9ED-375E-4656-AA46-434711DC2AFB} because it's missing its XML file!! (stt exists: False)
Skipping document 124/998 with OID {DF2B4D56-3617-4E6D-BCF3-53AB8C46E8EC} because it's missing its XML file!! (stt exists: False)
Skipping document 125/998 with OID {55E5D4CE-A0E7-4E54-90C4-2B7B0C2352C8} because it's missing its XML file!! (stt exists: False)
Skipping document 128/998 with OID {B444A6DB-B192-4B28-BE87-A69B03EB1E40} because it's missing its XML file!! (stt exists: False)
Skipping document 130/998 with OID {A449C54B-9229-4616-A19A-A3913597E152} because it's missing its XML file!! (stt exists: False)
Skipping document 131/998 with OID {A3213BAD-915C-4721-9F87-FD718904491D} because it's missing its XML file!! (stt exists: False)
Skipping document 136/998 with OID {4570D8E1-06EB-48DB-8679-5BB24FD44B3D} because it's missing its XML file!! (stt exists: False)
Skipping document 137/998 with OID {34504D0E-F643-4770-9D9E-381AE04D2E00} because it's missing its XML file!! (stt exists: False)
Skipping document 138/998 with OID {50DA219F-C8B1-4345-8C25-FBAC25949A32} because it's missing its XML file!! (stt exists: False)
Skipping document 139/998 with OID {67F76497-F464-4285-8CEA-201A116FE635} because it's missing its XML file!! (stt exists: False)
Skipping document 140/998 with OID {2830FA61-8516-4712-BC2D-C7FBE49A24A4} because it's missing its XML file!! (stt exists: False)
Skipping document 143/998 with OID {7569CBAE-0536-45A2-900C-15F0091E8FDB} because it's missing its XML file!! (stt exists: True)
Skipping document 148/998 with OID {22B47894-C7D4-4B1C-ACEB-7FA86B613EDF} because it's missing its XML file!! (stt exists: False)
Skipping document 149/998 with OID {22F3CC60-FF6F-44F2-9E28-52503888E7FE} because it's missing its XML file!! (stt exists: False)
Skipping document 150/998 with OID {148DA5F1-3FBB-4B9C-B4C0-9653532A5433} because it's missing its XML file!! (stt exists: False)
Skipping document 151/998 with OID {A5887E14-DA37-4FAB-BF89-04763BD648F0} because it's missing its XML file!! (stt exists: False)
Skipping document 155/998 with OID {5E2D6541-2888-490E-92A5-B07F2EFD3182} because it's missing its XML file!! (stt exists: False)
Skipping document 158/998 with OID {9E73D940-8732-4ED9-9423-92076AD349CF} because it's missing its XML file!! (stt exists: False)
Skipping document 172/998 with OID {A672F1FE-BE6A-4DD4-880B-874BBE2FD589} because it's missing its XML file!! (stt exists: False)
Skipping document 176/998 with OID {BD94AAC8-9363-4BA5-9507-7FDD45806C1D} because it's missing its XML file!! (stt exists: False)
Skipping document 177/998 with OID {41A9D1D3-E03C-4568-B94D-44AA3E40D909} because it's missing its XML file!! (stt exists: False)
Skipping document 180/998 with OID {8CB029ED-5E5A-4793-AA5E-E3345836E83F} because it's missing its XML file!! (stt exists: False)
Skipping document 181/998 with OID {C6787717-FB60-4C5A-A2C5-80A362EF0DA0} because it's missing its XML file!! (stt exists: False)
Skipping document 182/998 with OID {34EA47C2-1E48-4C87-90AE-97D5AE9C0F57} because it's missing its XML file!! (stt exists: False)
Skipping document 184/998 with OID {FF9EF8D1-86CF-4CD4-8FD4-024D545A08C8} because it's missing its XML file!! (stt exists: False)
Skipping document 188/998 with OID {2EB4BDD4-6089-402E-A093-20B824CAFC79} because it's missing its XML file!! (stt exists: False)
Skipping document 191/998 with OID {19A6C05B-207E-4550-9389-3C2C38293F47} because it's missing its XML file!! (stt exists: False)
Skipping document 195/998 with OID {30EADCAD-F2AB-417B-A22F-8593F4D58A00} because it's missing its XML file!! (stt exists: False)
Skipping document 197/998 with OID {6BD64EAE-4099-4C45-9214-EAC000309118} because it's missing its XML file!! (stt exists: False)
Skipping document 198/998 with OID {0973E394-8359-4324-8D0D-D51C1EFA2C57} because it's missing its XML file!! (stt exists: False)
Skipping document 199/998 with OID {153A834F-40CC-44A5-BDA9-2ABB4A5F39C0} because it's missing its XML file!! (stt exists: False)
Skipping document 212/998 with OID {E5B75BB4-12EF-413C-AD96-779517A12AC0} because it's missing its XML file!! (stt exists: False)
Skipping document 213/998 with OID {2123A8C2-8EE2-4554-BDBC-3AABB0A330D9} because it's missing its XML file!! (stt exists: False)
Skipping document 214/998 with OID {F94AACD6-D3A0-48B4-A031-AF2F2348E126} because it's missing its XML file!! (stt exists: False)
Skipping document 215/998 with OID {F0D6C2AF-EE6C-4D75-8C0B-0F9482444902} because it's missing its XML file!! (stt exists: False)
Skipping document 216/998 with OID {99C840D2-926B-4227-94E3-0291D8AB0C8F} because it's missing its XML file!! (stt exists: False)
Skipping document 218/998 with OID {CB11A069-78F7-4BBE-880D-FC3B515D7629} because it's missing its XML file!! (stt exists: False)
Skipping document 220/998 with OID {4A9E2E89-DA68-4BE8-A359-AAD9BDE7E05F} because it's missing its XML file!! (stt exists: False)
Skipping document 221/998 with OID {C11B53E9-0598-4CC1-BA0C-D57B47F9743B} because it's missing its XML file!! (stt exists: False)
Skipping document 223/998 with OID {F9930F20-FB93-45D6-83EA-41C739DC9434} because it's missing its XML file!! (stt exists: False)
Skipping document 226/998 with OID {5566EC04-1236-4673-A3A7-5518D3E8FE36} because it's missing its XML file!! (stt exists: False)
Skipping document 227/998 with OID {EA46CFBE-2D34-493A-B684-5654516C0EF6} because it's missing its XML file!! (stt exists: False)
Skipping document 234/998 with OID {E8E01202-939A-4FBA-A4AC-CCF3C1D96FF5} because it's missing its XML file!! (stt exists: False)
Skipping document 241/998 with OID {FF59C7E8-4BE6-4609-8C68-75CB6978B965} because it's missing its XML file!! (stt exists: False)
Skipping document 242/998 with OID {ED095F90-1DFC-44E0-876C-6B462D469C6F} because it's missing its XML file!! (stt exists: False)
Skipping document 243/998 with OID {6D8D4C7D-021E-4B1F-B3D9-396B5B47004F} because it's missing its XML file!! (stt exists: False)
Skipping document 244/998 with OID {EE20AC8E-834B-4E99-911B-257B24A0FB1A} because it's missing its XML file!! (stt exists: True)
Skipping document 245/998 with OID {8E960549-2452-4433-9FCE-B7148EEF872C} because it's missing its XML file!! (stt exists: False)
Skipping document 247/998 with OID {FF20CA09-DBA3-4D7A-ACF2-94DAE886F1F8} because it's missing its XML file!! (stt exists: False)
Skipping document 254/998 with OID {3ABEDADE-592B-4BEE-8351-93269C12CAAC} because it's missing its XML file!! (stt exists: False)
Skipping document 255/998 with OID {D34793FC-21A7-44CE-ACF6-E56EDC43F8B4} because it's missing its XML file!! (stt exists: False)
Skipping document 257/998 with OID {50E52BD9-371C-4F97-80F2-9DA0FD619E31} because it's missing its XML file!! (stt exists: False)
Skipping document 259/998 with OID {FAF8337A-86AC-4EAE-8DB3-30DB430F5A6B} because it's missing its XML file!! (stt exists: False)
Skipping document 260/998 with OID {F0DEA399-E8B9-4E15-B370-AC630789EF40} because it's missing its XML file!! (stt exists: False)
Skipping document 268/998 with OID {51164CF5-E328-4DCC-A5C6-3B69B75F2F9A} because it's missing its XML file!! (stt exists: False)
Skipping document 269/998 with OID {DD6EE92F-4EEB-483A-AC06-23053F988139} because it's missing its XML file!! (stt exists: False)
Skipping document 272/998 with OID {32D0A674-D9CD-4F5C-90FF-2389A4D3201A} because it's missing its XML file!! (stt exists: False)
Skipping document 273/998 with OID {3128ECF0-D303-4C86-8340-7CF5259B047C} because it's missing its XML file!! (stt exists: False)
Skipping document 278/998 with OID {81C5CBAE-EF34-478E-85C1-03EB98F2D458} because it's missing its XML file!! (stt exists: False)
Skipping document 284/998 with OID {ADD5DAA8-7347-415F-A63F-C571BB623EDD} because it's missing its XML file!! (stt exists: False)
Skipping document 285/998 with OID {E28D3E7E-6EC8-4476-9336-3736BBF703FA} because it's missing its XML file!! (stt exists: False)
Skipping document 286/998 with OID {9C09F570-BCEB-4AFF-94A7-DE96E889510D} because it's missing its XML file!! (stt exists: False)
Skipping document 290/998 with OID {8DA13C78-DE67-4F20-AA3B-A62E6306BFB6} because it's missing its XML file!! (stt exists: True)
Skipping document 294/998 with OID {929ACCC4-B8E7-46A0-9DCC-27C98C564492} because it's missing its XML file!! (stt exists: False)
Skipping document 295/998 with OID {F2023F26-7A68-4CB4-AFFA-C12EA32755CF} because it's missing its XML file!! (stt exists: False)
Skipping document 297/998 with OID {8212F81C-6CC2-4AC0-92D8-F07A640B0A93} because it's missing its XML file!! (stt exists: True)
Skipping document 298/998 with OID {A4F790E5-4D5C-4D0A-B5F6-CA936E883E55} because it's missing its XML file!! (stt exists: True)
Skipping document 317/998 with OID {36A2DF46-B38B-4FA7-875E-40E67CC8F93F} because it's missing its XML file!! (stt exists: False)
Skipping document 320/998 with OID {52ED6F10-0DE9-4DF7-91B7-BB8E92178686} because it's missing its XML file!! (stt exists: False)
Skipping document 321/998 with OID {502A8160-917C-42D0-B042-F3A6BD74D0E6} because it's missing its XML file!! (stt exists: False)
Skipping document 322/998 with OID {B33A086F-DBC5-4DC0-A1EE-6FA0085D2218} because it's missing its XML file!! (stt exists: False)
Skipping document 323/998 with OID {1A4531EA-7341-473E-BA8D-F44D4D9DB49A} because it's missing its XML file!! (stt exists: False)
Skipping document 326/998 with OID {231E72E3-8DD3-4E0D-9145-C24CB96D5D03} because it's missing its XML file!! (stt exists: False)
Skipping document 328/998 with OID {34FF8DE3-E0A2-45A3-A711-3C2E57DE31D7} because it's missing its XML file!! (stt exists: False)
Skipping document 329/998 with OID {B849A0F1-1CF2-42DE-9ACC-4B0D9BFC28B8} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {33BB83E2-F482-43E9-9FD1-93B2AC804687}. Trying to use the recording date. doc_dict: {'alias': 'j_soir', 'date_str': None, 'stt_filename': '33BB83E2-F482-43E9-9FD1-93B2AC804687_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{33BB83E2-F482-43E9-9FD1-93B2AC804687}', 'stripped_OID': '33BB83E2-F482-43E9-9FD1-93B2AC804687', 'login': '', 'broadcast_episode_title': "Affaire des fiches (1/2) : Surprise et d?ception d'Arnold Koller, pr?sident de la Conf?d?ration, chef du DJP. Interviews de Moritz Leuenberger, pr?sident de la commission d'enqu?te, et d'Amilcare Franchini, secr?taire g?n?ral adjoint de la Croix-Rouge suisse", 'sequence': '1', 'broadcast_program_name': 'Journal du soir', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'prongudo', 'modified_on': '09.03.2023 09:16:47', 'physical_support_history': "Cote d'origine: 8294 Pl. 1", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav (SRG 75)', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives. Jura", 'content_summary': 'Nouvelles d?couvertes dans les archives du Minist?re public f?d?ral : Arnold Koller annonce que des fiches ont ?t? trouv?es sur des extr?mistes, des fonctionnaires f?d?raux, des Jurassiens, des enfants ?trangers plac?s en Suisse par la Croix-Rouge.', 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:05:52.398', 'work_duration_compl': 'Non', 'participants': [{'name': 'Koller, Arnold', 'function': 'Interview?/e', 'role': 'pr?sident de la Conf?d?ration, chef du DJP'}, {'name': 'Tschanz, Pierre-Andr?', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}, {'name': 'Leuenberger, Moritz', 'function': 'Interview?/e', 'role': "pr?sident de la commission d'enqu?te"}, {'name': 'Reusser, Claude', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}, {'name': 'Franchini, Amilcare', 'function': 'Interview?/e', 'role': 'secr?taire g?n?ral adjoint de la Croix Rouge Suisse'}, {'name': 'Krammer, Evelyne', 'function': 'Intervieweur/euse', 'role': 'collaboratrice RSR'}], 'geographical_descriptors': ['Suisse'], 'person_descriptors': ['Koller, Arnold'], 'thematical_descriptors': ['fichier de renseignements', 'enqu?te judiciaire'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Interview', 'Commentaire'], 'recording_dates': ['16/02/1990 - 16/02/1990'], 'first_broadcast_dates': None}
Skipping document 340/998 with OID {FDF2F4DD-9179-4AA0-A3F1-7EED5376A736} because it's missing its XML file!! (stt exists: True)
Skipping document 342/998 with OID {732B9E9D-8C03-42A5-A9BD-031CAC9CFA0B} because it's missing its XML file!! (stt exists: False)
Skipping document 343/998 with OID {8B7D8BCC-30A3-497E-B99D-8708BD281E17} because it's missing its XML file!! (stt exists: False)
Skipping document 351/998 with OID {98D63E59-6B67-414B-908A-9BE8101E985B} because it's missing its XML file!! (stt exists: False)
Skipping document 353/998 with OID {0502394D-5CAB-4917-AA71-585B3C69144E} because it's missing its XML file!! (stt exists: False)
Skipping document 371/998 with OID {91874FA4-1654-43F0-B480-615FEA12497A} because it's missing its XML file!! (stt exists: False)
Skipping document 393/998 with OID {3AEBEBEB-6172-4D20-8814-20DF6C28B872} because it's missing its XML file!! (stt exists: False)
Skipping document 405/998 with OID {3F805061-9556-4024-B438-99FB008BCDB0} because it's missing its XML file!! (stt exists: False)

Did not find any date for doc with OID {90132942-68A2-491A-94D1-2F89BAC33BF7}. Trying to use the recording date. doc_dict: {'alias': 'j_soir', 'date_str': None, 'stt_filename': '90132942-68A2-491A-94D1-2F89BAC33BF7_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{90132942-68A2-491A-94D1-2F89BAC33BF7}', 'stripped_OID': '90132942-68A2-491A-94D1-2F89BAC33BF7', 'login': '', 'broadcast_episode_title': 'Caserne militaire de Colombier (Ne). Les jeunes recrues qui ont ing?r? 30 grammes de plastite sont hors de danger : Interview de Patrick Cudr?-Mauroux, porte-parole du DMF', 'sequence': '1', 'broadcast_program_name': 'Journal du soir', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '30.05.2022 18:05:43', 'physical_support_history': "Cote d'origine : 21064 Pl. 05", 'production_type': 'Production propre', 'recording_place': 'Lausanne (Studio RSR)', 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Cudr?-Mauroux, Patrick', 'function': 'Interview?/e', 'role': 'porte-parole du DMF'}, {'name': 'Gfeller, Urs', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Colombier (NE)'], 'person_descriptors': None, 'thematical_descriptors': ['explosif', 'arm?e', '?cole de recrues'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Interview'], 'recording_dates': ['13/09/1990 - 13/09/1990'], 'first_broadcast_dates': None}
Skipping document 943/998 with OID {5DC535F5-EF76-4FAA-B3FB-9524DA06AD88} because it's missing its XML file!! (stt exists: False)
Skipping document 953/998 with OID {8D8A1F84-5374-4BA9-89FE-D9138ED6BB85} because it's missing its XML file!! (stt exists: False)
Skipping document 955/998 with OID {D0481C39-ECCA-4A56-B226-E76F1CC560B7} because it's missing its XML file!! (stt exists: False)
Skipping document 957/998 with OID {96234D1F-A0E8-4E31-9C81-DBAFF597175E} because it's missing its XML file!! (stt exists: False)
Skipping document 958/998 with OID {BCEDC058-4948-4EDA-8368-74A72204B920} because it's missing its XML file!! (stt exists: False)
Skipping document 960/998 with OID {D7633122-6A86-4FC3-B609-DA08E260FF68} because it's missing its XML file!! (stt exists: False)
Skipping document 962/998 with OID {0E76CDC8-4A5D-4C82-8C28-8F3CE6A4548A} because it's missing its XML file!! (stt exists: False)
Skipping document 965/998 with OID {40E02369-BD7E-46B6-BE6B-C527A0911546} because it's missing its XML file!! (stt exists: False)
Skipping document 966/998 with OID {B31DD403-7A17-405E-A770-4DAF2CCD12F2} because it's missing its XML file!! (stt exists: False)
Skipping document 972/998 with OID {40B70CF4-A785-4A2A-854A-EBFBC9E59554} because it's missing its XML file!! (stt exists: False)
Skipping document 974/998 with OID {7FC81DA4-35C9-4E42-84DF-54A9E963DFBE} because it's missing its XML file!! (stt exists: True)
Skipping document 980/998 with OID {BD7F1112-0977-419D-98EC-F71D14C46D0C} because it's missing its XML file!! (stt exists: False)
Skipping document 982/998 with OID {603EAE37-66A2-45A4-B114-3694BC8B5770} because it's missing its XML file!! (stt exists: False)
Skipping document 984/998 with OID {9858F0AE-9FF7-4858-A4D0-226C15A5FF54} because it's missing its XML file!! (stt exists: False)
Skipping document 985/998 with OID {F67D2867-98A7-4271-8418-14E1F410EC74} because it's missing its XML file!! (stt exists: False)
Skipping document 987/998 with OID {45293F61-5A01-4FCA-B277-E8542EF4D767} because it's missing its XML file!! (stt exists: False)
Skipping document 989/998 with OID {6B12AC15-4158-4EDF-9813-940EAFCEB095} because it's missing its XML file!! (stt exists: False)
Skipping document 990/998 with OID {5B0208E7-F189-4BAC-8D9B-9322C79D4355} because it's missing its XML file!! (stt exists: False)
Skipping document 991/998 with OID {7647A652-F931-4A8E-862C-68C00DD63EEB} because it's missing its XML file!! (stt exists: False)
Skipping document 992/998 with OID {2C2F137D-FE04-483A-B861-F49FB57A2164} because it's missing its XML file!! (stt exists: False)
Skipping document 993/998 with OID {484A169F-3627-4B05-A60B-002976FFC18A} because it's missing its XML file!! (stt exists: False)
Skipping document 995/998 with OID {BF30FD4F-B3C7-40BC-8DFE-AD0418920CAB} because it's missing its XML file!! (stt exists: False)
Skipping document 996/998 with OID {38C29E35-56A5-4567-B53A-B46104D6DA1C} because it's missing its XML file!! (stt exists: False)
j_soir - returning 685 documents, 313 were skipped due to missing necessary info.

Starting extracting 291 documents for program j_soir
Skipping document 1/291 with OID {3BEB9F38-0CBF-4383-8953-970C6B19C52C} because it's missing its XML file!! (stt exists: False)
Skipping document 9/291 with OID {3A2600BB-A769-4D98-8B9E-B4D10353EB47} because it's missing its XML file!! (stt exists: False)
Skipping document 11/291 with OID {D445C078-6A0D-4993-97EA-98764B8208C1} because it's missing its XML file!! (stt exists: True)
Skipping document 13/291 with OID {E6BAAEC5-15D0-42D5-ACDB-B02EA80B7AA8} because it's missing its XML file!! (stt exists: False)
Skipping document 14/291 with OID {A37340C6-6273-40BE-B16E-523E5A014E9B} because it's missing its XML file!! (stt exists: False)
Skipping document 15/291 with OID {AA83CCE4-575A-4DDF-8D4F-5465D675F918} because it's missing its XML file!! (stt exists: False)
Skipping document 16/291 with OID {0BEB63D1-BCFA-4AB6-BFBD-C3A5E9F8B095} because it's missing its XML file!! (stt exists: False)
Skipping document 36/291 with OID {CD070F5D-B83F-4007-A788-2D888F51EA16} because it's missing its XML file!! (stt exists: False)
Skipping document 41/291 with OID {3243D2E2-4958-4021-B68E-6037E838FB96} because it's missing its XML file!! (stt exists: False)
Skipping document 42/291 with OID {EBC68FED-A63D-41E4-807A-2348C92133BB} because it's missing its XML file!! (stt exists: False)
Skipping document 47/291 with OID {3239A070-F550-444E-B38C-168AEFEC9213} because it's missing its XML file!! (stt exists: False)
Skipping document 48/291 with OID {7EE4E682-751D-4A17-8F77-23972ACCF5D6} because it's missing its XML file!! (stt exists: False)
Skipping document 49/291 with OID {95801980-5EC5-4E03-A121-C5F3752C1BC4} because it's missing its XML file!! (stt exists: False)
Skipping document 50/291 with OID {193659D9-6C42-454F-BFD3-85B6344B19E1} because it's missing its XML file!! (stt exists: False)
Skipping document 52/291 with OID {CF33B1E4-B87C-4080-81B8-4F5E2262772D} because it's missing its XML file!! (stt exists: False)
Skipping document 54/291 with OID {5D5E8648-E1CD-4134-B45A-31B25DD0745D} because it's missing its XML file!! (stt exists: False)
Skipping document 55/291 with OID {667C58F2-1BC6-4BA9-8059-E9730D89DCF6} because it's missing its XML file!! (stt exists: False)
Skipping document 57/291 with OID {8B7F7245-2CAA-4511-8FA9-2EDAB8E96D42} because it's missing its XML file!! (stt exists: False)
Skipping document 59/291 with OID {BE17E21E-9A47-485F-B845-C6B958866862} because it's missing its XML file!! (stt exists: False)
Skipping document 62/291 with OID {46C816A8-6863-428F-9626-2C3212F7BDB9} because it's missing its XML file!! (stt exists: False)
Skipping document 72/291 with OID {35D586FA-1E5F-44E7-8592-BB9D450C7BC7} because it's missing its XML file!! (stt exists: False)
Skipping document 76/291 with OID {E76455A7-0C64-409A-95CE-3D5EC88F949C} because it's missing its XML file!! (stt exists: False)
Skipping document 77/291 with OID {2AE8C517-11A0-4986-9BCA-CB28EA472842} because it's missing its XML file!! (stt exists: False)
Skipping document 78/291 with OID {8C701A88-F05D-435B-8FEE-276E31A15041} because it's missing its XML file!! (stt exists: False)
Skipping document 79/291 with OID {BDF42428-6C01-4DCD-8C70-13B7523A1192} because it's missing its XML file!! (stt exists: False)
Skipping document 82/291 with OID {412236C3-9248-4BC8-8515-EEAC6ADC5F63} because it's missing its XML file!! (stt exists: True)
Skipping document 83/291 with OID {936F30B0-05C9-4A98-9FDF-533AF71C31DE} because it's missing its XML file!! (stt exists: True)
Skipping document 86/291 with OID {EE814D4B-380D-4742-8075-DC7DAC381375} because it's missing its XML file!! (stt exists: True)
Skipping document 90/291 with OID {D9987BFA-9678-41BB-A906-F27EEAAA4BF2} because it's missing its XML file!! (stt exists: False)
Skipping document 102/291 with OID {4DF8147A-6CF0-4DDA-BD8B-4EC4245016F1} because it's missing its XML file!! (stt exists: False)
Skipping document 104/291 with OID {F22274BC-BB0D-43F2-B258-25B4431D750E} because it's missing its XML file!! (stt exists: False)
Skipping document 106/291 with OID {61466391-FB74-415B-8C56-FF5CFF0A29C1} because it's missing its XML file!! (stt exists: False)
Skipping document 108/291 with OID {0AC31CDC-BC11-4C97-B748-10FE5AB26683} because it's missing its XML file!! (stt exists: False)
Skipping document 109/291 with OID {F630171D-759D-4223-82C3-FE6887C3BC3C} because it's missing its XML file!! (stt exists: False)
Skipping document 110/291 with OID {DEEB04DF-249F-462A-9F2C-744B9953F05F} because it's missing its XML file!! (stt exists: False)
Skipping document 112/291 with OID {305B7CD0-DDBB-46BC-86F8-00D6A63804EE} because it's missing its XML file!! (stt exists: False)
Skipping document 116/291 with OID {9D98EE5C-F91F-4FA5-A05F-6D0722E01EE0} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {37F4A9DE-4C84-4ED7-B232-6F9715C42CFC}. Trying to use the recording date. doc_dict: {'alias': 'j_soir', 'date_str': None, 'stt_filename': '37F4A9DE-4C84-4ED7-B232-6F9715C42CFC_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{37F4A9DE-4C84-4ED7-B232-6F9715C42CFC}', 'stripped_OID': '37F4A9DE-4C84-4ED7-B232-6F9715C42CFC', 'login': '', 'broadcast_episode_title': 'Verdict du proc?s des fr?res Jean et Barkev Magharian', 'sequence': '1', 'broadcast_program_name': 'Journal du soir', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '30.05.2022 01:29:56', 'physical_support_history': "Cote d'origine : 21064 Pl. 06", 'production_type': 'Production propre', 'recording_place': 'Lausanne (Studio RSR). Bellinzone.', 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Dahinden, Philippe', 'function': 'Commentateur/trice', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Bellinzone', 'Suisse'], 'person_descriptors': None, 'thematical_descriptors': ['proc?s', 'blanchiment de capitaux', 'trafic de stup?fiants'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Commentaire'], 'recording_dates': ['13/09/1990 - 13/09/1990'], 'first_broadcast_dates': None}
Skipping document 120/291 with OID {FA6751AD-E866-46B3-A970-30587F6E174C} because it's missing its XML file!! (stt exists: False)
Skipping document 121/291 with OID {26941413-628D-4902-8D18-6A89AA2C90AB} because it's missing its XML file!! (stt exists: False)
Skipping document 122/291 with OID {5EDEE78A-8DEA-41C4-BAA0-6A8F904E1958} because it's missing its XML file!! (stt exists: False)
Skipping document 123/291 with OID {A88B15D6-B540-4D11-A24B-295090C00874} because it's missing its XML file!! (stt exists: False)
Skipping document 124/291 with OID {E171B27E-A598-4328-8AC8-912BFA239E11} because it's missing its XML file!! (stt exists: True)
Did not find any date for doc with OID {A5B6FB97-B1D6-4E33-AE5E-6C7FB59C6D41}. Trying to use the recording date. doc_dict: {'alias': 'j_soir', 'date_str': None, 'stt_filename': 'A5B6FB97-B1D6-4E33-AE5E-6C7FB59C6D41_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{A5B6FB97-B1D6-4E33-AE5E-6C7FB59C6D41}', 'stripped_OID': 'A5B6FB97-B1D6-4E33-AE5E-6C7FB59C6D41', 'login': '', 'broadcast_episode_title': 'Victoire des int?gristes aux ?lections en Alg?rie : Interview de Ben Bella', 'sequence': '1', 'broadcast_program_name': 'Journal du soir', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'ISM (NumA)', 'modified_on': '09.03.2023 11:41:24', 'physical_support_history': "Cote d'origine : 26085.17\nResp. RSR : ISM\nLot : Caisse 3325", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': "Participant: inte:Bella, Ben; \nInterview reprise du T?l?journal. N'a pas ?t? diffus?e", 'workflow_status': 'Accept?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': None, 'recording_dates': ['13/06/1990 - 13/06/1990'], 'first_broadcast_dates': None}
Skipping document 138/291 with OID {0425D8E0-B8D3-4577-9ACA-1E1FCD46AA9A} because it's missing its XML file!! (stt exists: False)
Skipping document 140/291 with OID {E2FA4FFF-0074-4356-B3D5-E6A93FDA3BCF} because it's missing its XML file!! (stt exists: False)
Skipping document 146/291 with OID {72964491-14A2-4DD1-BDD7-18223F480452} because it's missing its XML file!! (stt exists: False)
Skipping document 149/291 with OID {D69E6E48-74F4-4E5E-A15A-0E86E19ECE53} because it's missing its XML file!! (stt exists: False)
Skipping document 152/291 with OID {34BBCB35-ACCF-4338-BF19-FD5C46E74A9A} because it's missing its XML file!! (stt exists: False)
Skipping document 153/291 with OID {07E86410-19C5-47A8-8BDA-2917D0532562} because it's missing its XML file!! (stt exists: False)
Skipping document 154/291 with OID {4CD4D006-2621-4585-980F-93DCFD939D6B} because it's missing its XML file!! (stt exists: False)
Skipping document 155/291 with OID {85274E1F-7EAC-499E-B5CB-6532304D7E8C} because it's missing its XML file!! (stt exists: False)
Skipping document 156/291 with OID {5446C110-49B7-4596-AC35-89F557E68CC6} because it's missing its XML file!! (stt exists: False)
Skipping document 164/291 with OID {F862DFAD-C22F-4005-A021-1BB2F3970EA5} because it's missing its XML file!! (stt exists: False)
Skipping document 168/291 with OID {C32A24E8-A00D-4F24-95CD-1CE6FFC2BB3B} because it's missing its XML file!! (stt exists: False)
Skipping document 174/291 with OID {282666CC-6C51-4222-9B4C-A8FE31350D5C} because it's missing its XML file!! (stt exists: False)
Skipping document 178/291 with OID {FCE3E534-5FD4-4880-AF08-5B7D3F134ED1} because it's missing its XML file!! (stt exists: True)
Skipping document 179/291 with OID {866E8A4B-6755-4E58-B727-A7FE55FBB270} because it's missing its XML file!! (stt exists: False)
Skipping document 181/291 with OID {62398238-F016-4D18-B594-F3D10EC2C323} because it's missing its XML file!! (stt exists: False)
Skipping document 183/291 with OID {BD4B39AA-631C-4719-B6FA-C55AF5903439} because it's missing its XML file!! (stt exists: False)
Skipping document 192/291 with OID {3F66E893-AEF7-4E02-90CF-FB8A98546271} because it's missing its XML file!! (stt exists: False)
Skipping document 199/291 with OID {3A3D8F5F-EE23-4D97-9840-AD9AA327EE2C} because it's missing its XML file!! (stt exists: False)
Skipping document 201/291 with OID {8CB696E3-7482-45C0-8302-E54DA0D9CCC0} because it's missing its XML file!! (stt exists: False)
Skipping document 203/291 with OID {B581F94B-3CA3-453C-ACF9-61DD502982FD} because it's missing its XML file!! (stt exists: True)
Skipping document 212/291 with OID {CBB85592-F155-48AB-98B0-FC1E9B2D43EF} because it's missing its XML file!! (stt exists: False)
Skipping document 213/291 with OID {B3487A7E-8398-43DC-A8B0-69DACD7272DB} because it's missing its XML file!! (stt exists: False)
Skipping document 214/291 with OID {D2E9302B-0DFC-4A55-945A-4FAEC3C9BAA0} because it's missing its XML file!! (stt exists: False)
Skipping document 215/291 with OID {D219B30F-DD33-4D12-AAFF-AAEBE4EFCC1C} because it's missing its XML file!! (stt exists: False)

100%|██████████| 8/8 [00:28<00:00,  3.62s/it]

Skipping document 222/291 with OID {010ABDF9-D54F-4B2C-A73B-28D35D4EE766} because it's missing its XML file!! (stt exists: False)
Skipping document 224/291 with OID {3F258717-165B-4489-88F2-B126266BE117} because it's missing its XML file!! (stt exists: False)
Skipping document 225/291 with OID {F810C92B-F28A-4BCB-B0DD-BCE31480AF48} because it's missing its XML file!! (stt exists: False)
Skipping document 228/291 with OID {48393D68-68E5-49CD-B530-D827822ACD00} because it's missing its XML file!! (stt exists: False)
Skipping document 238/291 with OID {9445A246-7B97-45A3-8F69-02DA2449912D} because it's missing its XML file!! (stt exists: False)
Skipping document 241/291 with OID {625CC25F-8887-4684-9E47-552219B0743C} because it's missing its XML file!! (stt exists: False)
Skipping document 243/291 with OID {11EA886E-2FDE-47EB-A49C-686D11061259} because it's missing its XML file!! (stt exists: False)
Skipping document 244/291 with OID {645106CA-3536-44BB-B3C5-DBC3CC3902BF} because it's missing its XML file!! (stt exists: False)
Skipping document 251/291 with OID {1622E858-C41F-47C8-9BC8-391805298DC1} because it's missing its XML file!! (stt exists: False)
Skipping document 263/291 with OID {0A88490C-DC3F-468A-B461-D62301530C44} because it's missing its XML file!! (stt exists: False)
Skipping document 273/291 with OID {EB0A7731-ED9A-41D8-8DD5-5849606C0196} because it's missing its XML file!! (stt exists: False)
Skipping document 274/291 with OID {6B62A218-865C-4252-B368-D268A6DD2CFA} because it's missing its XML file!! (stt exists: True)
Skipping document 278/291 with OID {F3F8C37C-19E4-477F-93F4-D78FDEBFF7A6} because it's missing its XML file!! (stt exists: False)
Skipping document 279/291 with OID {4CCD0A70-9697-4044-9F3B-E65EB32A5189} because it's missing its XML file!! (stt exists: True)
Skipping document 280/291 with OID {B4B3CB2D-D1DF-4515-BD3F-EE36D8B20580} because it's missing its XML file!! (stt exists: True)
Skipping document 283/291 with OID {946EF3C4-42C7-4D6F-9DDA-C1EF039558B3} because it's missing its XML file!! (stt exists: False)
Skipping document 284/291 with OID {1D367820-C40B-4EC0-ACB0-76E6471F826D} because it's missing its XML file!! (stt exists: True)
Skipping document 287/291 with OID {54873337-9BFF-4CCC-BA0C-AD75A44314EE} because it's missing its XML file!! (stt exists: False)
Skipping document 291/291 with OID {AA022F31-B96E-4EE6-9E5D-0CF77F8B0E15} because it's missing its XML file!! (stt exists: False)
j_soir - returning 206 documents, 85 were skipped due to missing necessary info.
 --> Adding 5088 to the out csv for j_soir

23it [01:47, 17.07s/it]

PROCESSING PROGRAM mag_eco (24/47) - 2 files:

Starting extracting 22 documents for program mag_eco
Skipping document 20/22 with OID {0B188853-0430-41C3-A41B-9B0B6202DB22} because it's missing its XML file!! (stt exists: False)
mag_eco - returning 21 documents, 1 were skipped due to missing necessary info.

Starting extracting 21 documents for program mag_eco

100%|██████████| 2/2 [00:00<00:00,  8.88it/s]
24it [01:48, 12.12s/it]

mag_eco - returning 21 documents, 0 were skipped due to missing necessary info.
 --> Adding 42 to the out csv for mag_eco

PROCESSING PROGRAM mag_info (25/47) - 2 files:

Starting extracting 999 documents for program mag_info
Skipping document 14/999 with OID {4D46DF11-E4F3-4BAB-B86D-FD1CC2188F07} because it's missing its XML file!! (stt exists: False)
Skipping document 20/999 with OID {E40D02FF-5B96-4122-BA3E-71D5D4883497} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {8D4E894D-0784-4C04-85C5-2FC996CD833C}. Trying to use the recording date. doc_dict: {'alias': 'mag_info', 'date_str': None, 'stt_filename': '8D4E894D-0784-4C04-85C5-2FC996CD833C_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{8D4E894D-0784-4C04-85C5-2FC996CD833C}', 'stripped_OID': '8D4E894D-0784-4C04-85C5-2FC996CD833C', 'login': '', 'broadcast_episode_title': '1. Interview de Simone Signoret, com?dienne. - 2. Interview de Yves Montand, com?dien', 'sequence': '1', 'broadcast_program_name': 'Magazine (Emission Info)', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '14.01.2020 15:15:46', 'physical_support_history': "Cote d'origine: 10772 PL. 2.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': 'D?s 5.45:  Yves Montand.', 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:06:37.526', 'work_duration_compl': 'Non', 'participants': [{'name': 'Signoret, Simone', 'function': 'Interview?/e', 'role': 'com?dienne'}, {'name': 'Montand, Yves', 'function': 'Interview?/e', 'role': 'com?dien'}, {'name': 'P?russet, Suzanne', 'function': 'Intervieweur/euse', 'role': 'collaborateur/trice RTS'}], 'geographical_descriptors': ['France'], 'person_descriptors': ['Signoret, Simone'], 'thematical_descriptors': ['com?dienne', 'com?dien'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Interview'], 'recording_dates': ['19/03/1956 - 19/03/1956'], 'first_broadcast_dates': None}
Skipping document 127/999 with OID {7843EA4D-6D61-4814-A57D-B19BB82871C3} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {93571197-481E-47FE-A714-20A5119475E7}. Trying to use the recording date. doc_dict: {'alias': 'mag_info', 'date_str': None, 'stt_filename': '93571197-481E-47FE-A714-20A5119475E7_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{93571197-481E-47FE-A714-20A5119475E7}', 'stripped_OID': '93571197-481E-47FE-A714-20A5119475E7', 'login': '', 'broadcast_episode_title': "1. Les nouvelles techniques de vente dans les grandes surfaces. - 2. Entretien avec Soeur Hortense Berthet, docteur en physique nucl?aire, qui entrera prochainement en fonction d'abbesse du couvent de la Fille-Dieu ? Romont", 'sequence': '1', 'broadcast_program_name': 'Magazine (Emission Info)', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'tissotyv', 'modified_on': '02.06.2022 10:34:15', 'physical_support_history': "Cote d'origine: 25755", 'production_type': 'Production propre', 'recording_place': 'Romont (Couvent de la Fille-Dieu)', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives. Fribourg", 'content_summary': "Journal du soir. 1. Reportage dans les grands magasins et commentaires par Norbert Chatenet, ing?nieur conseil, Yvette Jaggi et Janine Chassot, de la F?d?ration romande des consommatrice. - 2. Le lien philosophique entre son pass? de physicienne et sa vie de moniale, la connaissance de la mati?re aide ? approcher les r?alit?s spirituelles, les raisons du choix de la vie monastique, les difficult?s de la voie spirituelle. Le rythme de vie du couvent, les offices, le travail, la lecture de la Bible et la pri?re. Le r?le des ordres clo?tr?s. Interm?des musicaux enregistr?s lors d'un office.", 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '01:00:11.272', 'work_duration_compl': 'Non', 'participants': [{'name': 'Chatenet, Norbert', 'function': 'Interview?/e', 'role': 'ing?nieur conseil en technique de vente'}, {'name': 'Chassot, Janine', 'function': 'Interview?/e', 'role': 'conseill?re de la FRC'}, {'name': 'Jaggi, Yvette', 'function': 'Interview?/e', 'role': 'pr?sidente de la FRC'}, {'name': 'M?re Hortense', 'function': 'Interview?/e', 'role': 'abbesse de la Fille-Dieu ? Romont'}, {'name': 'Inconnu', 'function': 'Reporter', 'role': 'collaborateur RSR'}, {'name': 'Inconnu', 'function': 'Pr?sentateur/trice', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Romont', 'Fribourg (canton)', 'Gl?ne (district, FR)'], 'person_descriptors': ['M?re Hortense'], 'thematical_descriptors': ['vente', 'marketing', 'consommation', 'supermarch?', 'couvent', 'catholicisme', 'pri?re', 'c?r?monie religieuse', 'physique nucl?aire', 'ordre religieux', 'religieuse'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Premier programme'], 'subdomains': ['Interview'], 'recording_dates': ['05/12/1975 - 05/12/1975'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {F9A913C1-9C99-4A17-A80C-C2D9DC402269}. Trying to use the recording date. doc_dict: {'alias': 'mag_info', 'date_str': None, 'stt_filename': 'F9A913C1-9C99-4A17-A80C-C2D9DC402269_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{F9A913C1-9C99-4A17-A80C-C2D9DC402269}', 'stripped_OID': 'F9A913C1-9C99-4A17-A80C-C2D9DC402269', 'login': '', 'broadcast_episode_title': 'A la recherche des us et coutumes de Carnaval en Gruy?re', 'sequence': '1', 'broadcast_program_name': 'Magazine (Emission Info)', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'albrecjo', 'modified_on': '28.05.2018 09:46:37', 'physical_support_history': "Cote d'origine: 31129.02. plage 2 sur 2", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives. Fribourg", 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:31:20.775', 'work_duration_compl': 'Non', 'participants': [{'name': 'Brodard, Fran?ois-Xavier', 'function': 'Interview?/e', 'role': 'abb?'}, {'name': 'Gremaud, Henri', 'function': 'Interview?/e', 'role': 'conservateur du Mus?e gru?rien ? Bulle'}, {'name': 'Tena, Boniface', 'function': 'Interview?/e', 'role': 'ancien syndic de Grandvillard'}, {'name': 'Luisoni, Joseph', 'function': 'Interview?/e', 'role': "secr?taire communal et ancien ma?tre d'?cole de Neirivue"}, {'name': 'Ecoffey, L?on', 'function': 'Interview?/e', 'role': 'agriculteur ? Villars-sous-Mont'}, {'name': 'Voix diverses', 'function': 'Interview?/e', 'role': 'enfants'}], 'geographical_descriptors': ['Fribourg (canton)', 'Gruy?re (district, FR)'], 'person_descriptors': None, 'thematical_descriptors': ['carnaval', 'moeurs et coutumes', 'religion et croyances', 'l?gende'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Premier programme'], 'subdomains': ['Reportage', 'Interview'], 'recording_dates': ['18/02/1977 - 18/02/1977'], 'first_broadcast_dates': None}
Skipping document 209/999 with OID {03B30C6E-DCF5-428D-AE57-5EDB0609B231} because it's missing its XML file!! (stt exists: False)
The date for document with OID {D26B3CBD-B64E-4395-BB4B-8238A22E161F} was invalid (__/05/1968) - changed it to 01/05/1968
The date for document with OID {4484A513-3209-4DA7-8DFE-8095BB80C9A5} was invalid (__/__/1969) - changed it to 01/01/1969
Skipping document 282/999 with OID {802F1B70-3AF5-4E1D-A1A5-71F7ED8FB7A8} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {5BBA5312-170E-4236-B48C-9B53AD5CC419}. Trying to use the recording date. doc_dict: {'alias': 'mag_info', 'date_str': None, 'stt_filename': '5BBA5312-170E-4236-B48C-9B53AD5CC419_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{5BBA5312-170E-4236-B48C-9B53AD5CC419}', 'stripped_OID': '5BBA5312-170E-4236-B48C-9B53AD5CC419', 'login': '', 'broadcast_episode_title': "Crise de l'emploi chez les scientifiques", 'sequence': '1', 'broadcast_program_name': 'Magazine (Emission Info)', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'RCR (NumA)', 'modified_on': '27.05.2022 08:00:31', 'physical_support_history': "Cote d'origine : MA 7234.a Resp. RSR : RCR Lot : Caisse 3233", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Participant: pres:Sch?rlig, Eric;  inte:Voix diverses,;  Prod.: prod:Sch?rlig, Eric', 'workflow_status': 'Accept?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': None, 'recording_dates': ['27/07/1972 - 27/07/1972'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {A17872EA-1104-441B-9AA0-5AD410C478E3}. Trying to use the recording date. doc_dict: {'alias': 'mag_info', 'date_str': None, 'stt_filename': 'A17872EA-1104-441B-9AA0-5AD410C478E3_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{A17872EA-1104-441B-9AA0-5AD410C478E3}', 'stripped_OID': 'A17872EA-1104-441B-9AA0-5AD410C478E3', 'login': '', 'broadcast_episode_title': 'Entretien avec Pierre Mend?s France, homme politique fran?ais : A propos de son voyage en Extr?me-Orient', 'sequence': '2', 'broadcast_program_name': 'Magazine (Emission Info)', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'aqt (NumA)', 'modified_on': '09.03.2023 11:52:01', 'physical_support_history': "Cote d'origine : Bd 8887 Resp. RSR : aqt Lot : Caisse 1123", 'production_type': 'Production propre', 'recording_place': 'Paris (Studio de la Radiodiffusion suisse)', 'rights_notes': None, 'rights_status': None, 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Mend?s France, Pierre', 'function': 'Interview?/e', 'role': 'homme politique fran?ais'}, {'name': 'Mairet, Claude (journaliste)', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['France', 'Japon', 'Chine', 'Inde', 'Europe', 'Etats-Unis'], 'person_descriptors': ['Mend?s France, Pierre'], 'thematical_descriptors': ['fonction politique'], 'rights_usage_possibilities': None, 'radio_channels': None, 'subdomains': ['Interview'], 'recording_dates': ['__/__/1972 - __/__/1972'], 'first_broadcast_dates': None}
The date for document with OID {A17872EA-1104-441B-9AA0-5AD410C478E3} was invalid (__/__/1972) - changed it to 01/01/1972
The date for document with OID {A17872EA-1104-441B-9AA0-5AD410C478E3} was invalid (__/__/1972) - changed it to 01/01/1972
Skipping document 486/999 with OID {48DDAFCB-8A2F-4A5D-B8FE-91959B08E596} because it's missing its XML file!! (stt exists: False)
Skipping document 512/999 with OID {EFBB5D66-FBF8-45C0-9458-D4C77B4324AB} because it's missing its XML file!! (stt exists: False)
Skipping document 542/999 with OID {0C19A1A1-E7C5-47BA-8736-56CC573556A8} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {1B55EC6E-306A-4DB6-9961-FBB48418DEAB}. Trying to use the recording date. doc_dict: {'alias': 'mag_info', 'date_str': None, 'stt_filename': '1B55EC6E-306A-4DB6-9961-FBB48418DEAB_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{1B55EC6E-306A-4DB6-9961-FBB48418DEAB}', 'stripped_OID': '1B55EC6E-306A-4DB6-9961-FBB48418DEAB', 'login': '', 'broadcast_episode_title': 'Hostilit?s au Moyen-Orient (2/2) : Interview de Jean Wolf', 'sequence': '1', 'broadcast_program_name': 'Magazine (Emission Info)', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'AQT (NumA)', 'modified_on': '12.05.2022 11:36:10', 'physical_support_history': "Cote d'origine : MA 702.d Resp. RSR : AQT Lot : Caisse 3140", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': None, 'workflow_status': 'Accept?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Wolf, Jean', 'function': 'Interview?/e', 'role': None}, {'name': 'Bofford, Jacques', 'function': 'Intervieweur/euse', 'role': 'collaborateur/trice RSR'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': None, 'recording_dates': ['09/02/1970 - 09/02/1970'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {C93D09F3-CE1D-45EF-B39D-7356C73E7519}. Trying to use the recording date. doc_dict: {'alias': 'mag_info', 'date_str': None, 'stt_filename': 'C93D09F3-CE1D-45EF-B39D-7356C73E7519_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{C93D09F3-CE1D-45EF-B39D-7356C73E7519}', 'stripped_OID': 'C93D09F3-CE1D-45EF-B39D-7356C73E7519', 'login': '', 'broadcast_episode_title': 'Interview d\'Andr? Castelot, historien, ? propos de son livre "L\'Histoire ? table : si la cuisine m\'?tait cont?e" (Ed. Plon /Perrin, 1972)', 'sequence': '1', 'broadcast_program_name': 'Magazine (Emission Info)', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '12.05.2022 04:50:02', 'physical_support_history': "Cote d'origine: A 6417", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': "Les pratiques culinaires au cour des si?cles et des pays. L'origine du pain, du caf? et du fromage. Etymologie de certains termes li?s ? la cuisine. Introduction ? la cuisine moderne", 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:22:40.511', 'work_duration_compl': 'Non', 'participants': [{'name': 'Castelot, Andr?', 'function': 'Interview?/e', 'role': 'historien'}, {'name': 'Duch?teau, Jean-Jacques', 'function': 'Intervieweur/euse', 'role': 'collaborateur Radio-Lausanne'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': ['coutume alimentaire', 'menu', 'art culinaire', 'histoire', 'repas'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Interview'], 'recording_dates': ['09/12/1972 - 09/12/1972'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {DC54CBB6-A010-4107-BFE6-43D2551F54D0}. Trying to use the recording date. doc_dict: {'alias': 'mag_info', 'date_str': None, 'stt_filename': 'DC54CBB6-A010-4107-BFE6-43D2551F54D0_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{DC54CBB6-A010-4107-BFE6-43D2551F54D0}', 'stripped_OID': 'DC54CBB6-A010-4107-BFE6-43D2551F54D0', 'login': '', 'broadcast_episode_title': "Interview de Jean-Christian Spahni ethnologue et arch?ologue suisse, de retour d'une exp?dition de deux ans au P?rou", 'sequence': '1', 'broadcast_program_name': 'Magazine (Emission Info)', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '05.02.2019 12:23:45', 'physical_support_history': "Cote d'origine: MA 66.5 Pl. A", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': "Indiens de la Cordili?re des Andes. Il n'y a pas de propri?taires p?ruviens, tous sont blancs.", 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:18:03.812', 'work_duration_compl': 'Non', 'participants': [{'name': 'Spahni, Jean-Christian', 'function': 'Interview?/e', 'role': 'ethnologue et arch?ologue suisse'}, {'name': 'Moss?, Claude', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['P?rou', 'Les Andes'], 'person_descriptors': None, 'thematical_descriptors': ['voyage', 'ethnographie', 'mineur (m?tier)', 'mine (site)', 'moeurs et coutumes', 'culture', 'pomme de terre', 'c?r?ale', "Indiens d'Am?rique"], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Interview'], 'recording_dates': ['11/03/1966 - 11/03/1966'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {D15F9B7D-83AC-4495-8DA4-D679D947695D}. Trying to use the recording date. doc_dict: {'alias': 'mag_info', 'date_str': None, 'stt_filename': 'D15F9B7D-83AC-4495-8DA4-D679D947695D_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{D15F9B7D-83AC-4495-8DA4-D679D947695D}', 'stripped_OID': 'D15F9B7D-83AC-4495-8DA4-D679D947695D', 'login': '', 'broadcast_episode_title': "Interview de l'homme politique et ?crivain martiniquais Aim? C?saire : A propos de ses oeuvres litt?raires et de la Martinique", 'sequence': '1', 'broadcast_program_name': 'Magazine (Emission Info)', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '09.03.2023 13:26:23', 'physical_support_history': "Cote d'origine: MA 69.3 Pl. B", 'production_type': 'Production propre', 'recording_place': 'Fort-de-France', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:06:02.565', 'work_duration_compl': 'Non', 'participants': [{'name': 'C?saire, Aim?', 'function': 'Interview?/e', 'role': 'homme politique et ?crivain martiniquais'}], 'geographical_descriptors': ['Martinique', 'Antilles', 'Fort-de-France'], 'person_descriptors': ['C?saire, Aim?'], 'thematical_descriptors': ['litt?rature', 'po?sie', 'art dramatique', 'race noire'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Radio-Gen?ve'], 'subdomains': ['Interview'], 'recording_dates': ['01/01/1969 - 01/01/1969'], 'first_broadcast_dates': None}

mag_info - returning 991 documents, 8 were skipped due to missing necessary info.

Starting extracting 772 documents for program mag_info
Skipping document 62/772 with OID {DD8F1682-D785-4881-858E-FD8F1666FDF5} because it's missing its XML file!! (stt exists: False)
Skipping document 100/772 with OID {D29E8A8F-5AC7-4479-861D-6FF413D77547} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {9E0FE0C9-737D-4E68-9B04-E67C925996E9}. Trying to use the recording date. doc_dict: {'alias': 'mag_info', 'date_str': None, 'stt_filename': '9E0FE0C9-737D-4E68-9B04-E67C925996E9_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{9E0FE0C9-737D-4E68-9B04-E67C925996E9}', 'stripped_OID': '9E0FE0C9-737D-4E68-9B04-E67C925996E9', 'login': '', 'broadcast_episode_title': "La situation en Allemagne de l'Est. L'heure des r?formes est-elle arriv?e?: 1. Indicatif de Radio-Glasnost, radio locale berlinoise de l'Ouest destin?e aux Allemands de l'Est. - 2. Interview de membres de Neues Forum....", 'sequence': '1', 'broadcast_program_name': 'Magazine (Emission Info)', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'Administrateur WorkFlow', 'modified_on': '11.02.2017 07:06:21', 'physical_support_history': "Cote d'origine: 27430 PL.2.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': None, 'workflow_status': 'Accept?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:23:27.445', 'work_duration_compl': 'Non', 'participants': [{'name': 'Gfeller, Urs', 'function': 'Commentateur/trice', 'role': 'collaborateur RSR'}, {'name': 'Eymann, Michel', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}, {'name': 'Silberstein, Monique', 'function': 'Intervieweur/euse', 'role': 'collaboratrice RSR'}], 'geographical_descriptors': ["Allemagne de l'Est", "Allemagne de l'Ouest", 'Berlin'], 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': None, 'recording_dates': ['12/10/1989 - 12/10/1989'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {470DB327-B4FD-48BE-90BA-0A35EACDB7D6}. Trying to use the recording date. doc_dict: {'alias': 'mag_info', 'date_str': None, 'stt_filename': '470DB327-B4FD-48BE-90BA-0A35EACDB7D6_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{470DB327-B4FD-48BE-90BA-0A35EACDB7D6}', 'stripped_OID': '470DB327-B4FD-48BE-90BA-0A35EACDB7D6', 'login': '', 'broadcast_episode_title': 'La zone op?rationnelle de Sa?da : Commentaire de Pierre Moser envoy? ? Oran', 'sequence': '1', 'broadcast_program_name': 'Magazine (Emission Info)', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '08.05.2017 16:08:08', 'physical_support_history': "Cote d'origine: MA 5952 Pl. C", 'production_type': 'Production propre', 'recording_place': 'Oron', 'rights_notes': 'Memoriav', 'rights_status': 'A rechercher', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:04:19.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Moser, Pierre', 'function': 'Commentateur/trice', 'role': 'correspondant Radio-Gen?ve ? Oran'}], 'geographical_descriptors': ['Alg?rie', 'Sa?da'], 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': None, 'radio_channels': ['Radio-Gen?ve'], 'subdomains': ['Commentaire'], 'recording_dates': ['16/11/1959 - 16/11/1959'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {8F7DF5FE-6F87-4D52-AEC6-8FAB6C6488DE}. Trying to use the recording date. doc_dict: {'alias': 'mag_info', 'date_str': None, 'stt_filename': '8F7DF5FE-6F87-4D52-AEC6-8FAB6C6488DE_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{8F7DF5FE-6F87-4D52-AEC6-8FAB6C6488DE}', 'stripped_OID': '8F7DF5FE-6F87-4D52-AEC6-8FAB6C6488DE', 'login': '', 'broadcast_episode_title': 'Le Jura Sud avant le 16 mars 1975. Prises de positions pour le deuxi?me pl?bisicite jurassien du 16 mars 1975 des repr?sentants des mouvements politiques jurassiens, des repr?sentants des partis politiques jurassiens et du repr?sentant du D?partement f?d?ral de Justice et Police', 'sequence': '1', 'broadcast_program_name': 'Magazine (Emission Info)', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '30.05.2022 21:25:14', 'physical_support_history': "Cote d'origine: 28972", 'production_type': 'Production propre', 'recording_place': 'Lausanne (Studio RSR)', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives. Jura", 'content_summary': "Rapport d'?coute d?taill? en annexe. Aucun(e)  intervenant(e) n'est pr?sent?(e)", 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:39:14.949', 'work_duration_compl': 'Non', 'participants': [{'name': 'Inconnu', 'function': 'Interview?/e', 'role': 'repr?sentant du mouvement anti-s?paratiste'}, {'name': 'Inconnu', 'function': 'Interview?/e', 'role': 'repr?sentant du RJ'}, {'name': 'Inconnu', 'function': 'Interview?/e', 'role': "repr?sentant du Comit? d'information du Jura Sud"}, {'name': 'Aubry, Genevi?ve', 'function': 'Interview?/e', 'role': 'pr?sidente du Groupement f?minin de Force d?mocratique (GFFD)'}, {'name': 'Inconnu', 'function': 'Interview?/e', 'role': 'repr?sentant de Jura Sud Autonome (veut cr?er un demi-canton)'}, {'name': 'Inconnu', 'function': 'Interview?/e', 'role': 'romand de Bienne'}, {'name': 'Inconnue', 'function': 'Interview?/e', 'role': 'repr?sentante du Mouvement des Romands de Bienne'}, {'name': 'M?hlenen, Jean-Michel von', 'function': 'Interview?/e', 'role': 'correspondant du Journal du Jura ? Moutier'}, {'name': 'Inconnu', 'function': 'Interview?/e', 'role': 'repr?sentant du Parti lib?ral-radical jurassien (Maurice P?quignot?)'}, {'name': 'Inconnu', 'function': 'Interview?/e', 'role': 'repr?sentant du parti socialiste jurassien'}, {'name': 'Inconnu', 'function': 'Interview?/e', 'role': "repr?sentant de l'UDC jurassienne"}, {'name': 'Inconnu', 'function': 'Interview?/e', 'role': 'repr?sentant du PDC jurassien'}, {'name': 'Inconnu', 'function': 'Interview?/e', 'role': 'repr?sentant du parti radical ind?pendant'}, {'name': 'Inconnu', 'function': 'Interview?/e', 'role': 'repr?sentant du D?partement f?d?ral de Justice et Police (commission du Conseil f?d?ral pour les affaires jurassiennes?)'}, {'name': 'Inconnu', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Jura bernois', 'Bienne', 'Moutier', 'La Neuveville', 'Courtelary'], 'person_descriptors': None, 'thematical_descriptors': ['question jurassienne', 'autonomisme', 'parti politique', 'canton', 'votation'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Premier programme'], 'subdomains': ['Reportage'], 'recording_dates': ['07/03/1975 - 07/03/1975'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {B7B292E2-4093-47D7-AE2F-BFDFDB7004F6}. Trying to use the recording date. doc_dict: {'alias': 'mag_info', 'date_str': None, 'stt_filename': 'B7B292E2-4093-47D7-AE2F-BFDFDB7004F6_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{B7B292E2-4093-47D7-AE2F-BFDFDB7004F6}', 'stripped_OID': 'B7B292E2-4093-47D7-AE2F-BFDFDB7004F6', 'login': '', 'broadcast_episode_title': 'Le Mato-Grosso : Interview de Rachel Steingruber; infirmi?re au Br?sil', 'sequence': '1', 'broadcast_program_name': 'Magazine (Emission Info)', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '12.05.2020 14:35:18', 'physical_support_history': "Cote d'origine: MA 66.9 PL. C.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': "Au Br?sil depuis 1950 avec un interm?de de 4 ans pour se former en obst?trique. Elle soigne la population dans sa maison ? Rosario Ueste. Elle est seule, sans m?decine, eau ou ?lectricit?. Elle se d?place souvent. Elle fait face ? des pathologies comme la malaria, la variole, des h?morsagies... Elle s'est longetemps d?placee ? cheval, mais poss?de  maintenant une jeep. La situation est souvent d?sesp?rantes. Les m?dicaments sont trop chers. elle a lontemps financ? ses activit?s gr?ce ? ses ?conomies, mais elle a maintenant besoin d'aide. La population est tr?s reconnaissante.", 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:18:23.647', 'work_duration_compl': 'Non', 'participants': [{'name': 'Barde, Olivier', 'function': 'Interview?/e', 'role': 'ami de Rachel Steingruber'}, {'name': 'Steingruber, Rachel', 'function': 'Interview?/e', 'role': 'infirmi?re'}, {'name': 'Bofford, Jacques', 'function': 'Intervieweur/euse', 'role': 'colalborateur/trice RSR'}], 'geographical_descriptors': ['Br?sil', 'Mato Grosso'], 'person_descriptors': None, 'thematical_descriptors': ['infirmier', 'femme', 'm?decine', 'aide au d?veloppement'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Premier programme'], 'subdomains': ['Interview'], 'recording_dates': ['19/07/1966 - 19/07/1966'], 'first_broadcast_dates': None}
Skipping document 302/772 with OID {FB7EE7A0-06E0-451A-8FB9-992BC260F25F} because it's missing its XML file!! (stt exists: False)
The date for document with OID {0DCCCA37-649F-42F1-A365-5BC70444313D} was invalid (__/09/1967) - changed it to 01/09/1967
Did not find any date for doc with OID {EFF02F48-8651-40E3-8DC1-197849B23B99}. Trying to use the recording date. doc_dict: {'alias': 'mag_info', 'date_str': None, 'stt_filename': 'EFF02F48-8651-40E3-8DC1-197849B23B99_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{EFF02F48-8651-40E3-8DC1-197849B23B99}', 'stripped_OID': 'EFF02F48-8651-40E3-8DC1-197849B23B99', 'login': '', 'broadcast_episode_title': "L'homme dans la grande ville", 'sequence': '1', 'broadcast_program_name': 'Magazine (Emission Info)', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'freudial', 'modified_on': '23.01.2025 09:46:21', 'physical_support_history': "Cote d'origine: MA 66.5 PL. C", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': "Probl?me g?n?ral de la vie dans les grandes villes. Interview du Dr. Pichot: la sant? mentale dans les grandes villes et les risques pour le psychisme. 3.17 Interview de M. Delouvrier, d?l?gu? grand district parisien. Le Paris de demain. 6.15 Interview de M. Baudoin: nous vivons une ?poque de mutation de civilisation. 6.41 Interview de M. Balladur: diagnostic de l'homme dans la grande ville. La ville est d'abord un outil pour ses habitants. 15.16 Interview de M. Friedman: la ville spatiale. 17.47 Interview de M. Patrix: baser l'architecture sur l'outil industriel. 22.01 Interview du Dr. Derolle: il reste des lacunes dans la compr?hension des probl?mes de l'homme dans la grande ville.", 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:24:19.332', 'work_duration_compl': 'Non', 'participants': [{'name': 'Pichot, Pierre', 'function': 'Interview?/e', 'role': 'psychiatre'}, {'name': 'Delouvrier, Paul', 'function': 'Interview?/e', 'role': 'd?l?gu? du Grand district parisien'}, {'name': 'Baudoin, Eug?ne', 'function': 'Interview?/e', 'role': "pr?sident de l'Association Internationale des Architectes"}, {'name': 'Balladur, Jean', 'function': 'Interview?/e', 'role': "professeur d'urbanisme ? l'Ecole des Arts et M?tiers"}, {'name': 'Friedman, Yona', 'function': 'Interview?/e', 'role': 'architecte'}, {'name': 'Patrix, Georges', 'function': 'Interview?/e', 'role': 'urbaniste'}, {'name': 'Derolle, Pierre', 'function': 'Interview?/e', 'role': "directeur-adjoint de l'OMS"}, {'name': 'Darmsteter, Jean-Paul', 'function': 'Intervieweur/euse', 'role': 'collaborateur/trice RSR'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': ['ville', 'm?gapole', 'urbanisme', 'vie quotidienne', 'maladie psychosomatique', 'circulation routi?re', 'habitat', 'habitat et urbanisme', 'architecture'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Premier programme'], 'subdomains': ['Interview'], 'recording_dates': ['06/04/1966 - 06/04/1966'], 'first_broadcast_dates': None}
Skipping document 500/772 with OID {D8ADC65F-B217-4A0E-A07C-F1DB5885A2E5} because it's missing its XML file!! (stt exists: False)
Skipping document 523/772 with OID {CA3E1362-13AA-459B-97FC-3C68E7744E99} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {2CFF89F1-8A42-4172-85EB-D3F0979C83A7}. Trying to use the recording date. doc_dict: {'alias': 'mag_info', 'date_str': None, 'stt_filename': '2CFF89F1-8A42-4172-85EB-D3F0979C83A7_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{2CFF89F1-8A42-4172-85EB-D3F0979C83A7}', 'stripped_OID': '2CFF89F1-8A42-4172-85EB-D3F0979C83A7', 'login': '', 'broadcast_episode_title': 'Notre diplomatie est-elle sous-?quip?e? D?bat', 'sequence': '2', 'broadcast_program_name': 'Magazine (Emission Info)', 'document_type': 'Parl?', 'hierarchy_level': 'Extrait', 'modified_by': 'tissotyv', 'modified_on': '31.05.2022 01:22:54', 'physical_support_history': "Cote d'origine: 24389. Bande t?moin", 'production_type': 'Production propre', 'recording_place': 'Lausanne (RSR)', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives. Fribourg", 'content_summary': "A la suite des ?v?nements du Proche-Orient (d?tournement d'avion ? Beyrouth) et de l'implication de la Suisse, Pierre B?guin m?ne le d?bat sur la faiblesse du r?seau diplomatique f?d?ral. Antonino Janner d?crit la politique de la Conf?d?ration et son d?sir de se remettre en question. Jean Vincent se montre tr?s critique au sujet des ambassadeurs, notamment leur manque de comp?tence et la faiblesse de leur travail de renseignements. Pierre Barras estime que les lacunes se situent plus au niveau des relations diplomatiques. Le d?bat porte ensuite sur les techniques de renseignement, puis sur le recrutement et la formation du corps diplomatique.", 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:59:55.582', 'work_duration_compl': 'Non', 'participants': [{'name': 'Vincent, Jean', 'function': 'Participant/e au d?bat', 'role': 'conseiller national genevois (Parti du travail)'}, {'name': 'Janner, Antonino', 'function': 'Participant/e au d?bat', 'role': 'chef de division au D?partement politique f?d?ral'}, {'name': 'Barras, Pierre', 'function': 'Participant/e au d?bat', 'role': 'r?dacteur en chef de "La Libert?"'}, {'name': 'Evard, Blaise', 'function': 'Pr?sentateur/trice', 'role': 'collaborateur RSR'}, {'name': 'B?guin, Pierre', 'function': 'Animateur/trice', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Suisse', 'Proche-Orient', 'Liban', 'Palestine'], 'person_descriptors': ['OLP'], 'thematical_descriptors': ['diplomatie', 'relations internationales', 'politique internationale', 'attentat', 'terrorisme'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Premier programme'], 'subdomains': ['D?bat'], 'recording_dates': ['20/10/1970 - 20/10/1970'], 'first_broadcast_dates': None}

100%|██████████| 2/2 [00:07<00:00,  3.83s/it]

Skipping document 693/772 with OID {641647ED-E17F-450F-80ED-6DB9DB87194B} because it's missing its XML file!! (stt exists: False)
Skipping document 760/772 with OID {C82B8342-DFA0-4F9A-9D1B-C211332493DB} because it's missing its XML file!! (stt exists: False)
mag_info - returning 764 documents, 8 were skipped due to missing necessary info.
 --> Adding 1755 to the out csv for mag_info

25it [01:56, 11.10s/it]

PROCESSING PROGRAM mag_sci1 (26/47) - 1 files:

Starting extracting 161 documents for program mag_sci1
Did not find any date for doc with OID {57686BE0-266E-4ADA-86AE-C44E99CF9ED4}. Trying to use the recording date. doc_dict: {'alias': 'mag_sci1', 'date_str': None, 'stt_filename': '57686BE0-266E-4ADA-86AE-C44E99CF9ED4_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{57686BE0-266E-4ADA-86AE-C44E99CF9ED4}', 'stripped_OID': '57686BE0-266E-4ADA-86AE-C44E99CF9ED4', 'login': '', 'broadcast_episode_title': "1. Interview d'Aldo Fossati, sp?cialiste ? la station f?d?rale de Changins. - 2. Commentaire du physicien Jean Rossel. - 3. Interview du prix Nobel de m?decine Roger Guillemin. - 4. Interview des m?decins Peter de Graad et Pierre Cattan", 'sequence': '1', 'broadcast_program_name': 'Magazine des sciences', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '11.09.2018 10:02:19', 'physical_support_history': "Cote d'origine: MA 86.100", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': None, 'series_title': None, 'content_summary': "1. Aldo Fossati a travaill? de nombreuses ann?es ? am?liorer les vari?t?s de bl? avec des m?thodes de s?lections traditionnelles. A permis de doubler le rendement des c?r?ales. Production de 60 quintaux ? l'hectare pour le bl? en 1986. Les m?thodes traditionnelles permettent par croisements successifs d'obtenir une nouvelle vari?t? au bout de 10 ? 15 ans. L'am?lioration des techniques de cultures ont contribu? ? ce r?sultat. Revers de la m?daille: on oblige le paysan a acheter la semence chaque ann?e. Les bl?s ?chappent au contr?le des maisons de production des semences. Enorme int?r?t commercial dans ce secteur des semences. L'objectif du Conseil f?d?ral vise une agriculture int?gr?e; bonne productivit? mais avec le moins d'intervention chimique et avec les engrais. - 2. Le terrorisme nucl?aire. - 3. Neurologie, complexit? de notre cerveau. - 4. Lutte contre la maladie du sommeil, le programme de l'OMS en Afrique. M?decine tropicale.", 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Rossel, Sylvie', 'function': 'Pr?sentateur/trice', 'role': 'collaboratrice RSR'}, {'name': 'Fossati, Aldo', 'function': 'Interview?/e', 'role': 'sp?cialiste ? la station f?d?rale de Changins, responsable de la s?lection des c?r?ales'}, {'name': 'Rossel, Jean', 'function': 'Commentateur/trice', 'role': 'physicien'}, {'name': 'Guillemin, Roger', 'function': 'Interview?/e', 'role': 'prix Nobel de m?decine en 1977'}, {'name': 'Inconnus', 'function': 'Interview?/e', 'role': 'Peter de Graad et Pierre Cattan (orthographe incertaine)'}], 'geographical_descriptors': ['Afrique', 'France'], 'person_descriptors': ['OMS'], 'thematical_descriptors': ['bl?', 'science biologique', 'ma?s', 'graine', 'agronomie', 'physique', 'terrorisme', 'maladie tropicale'], 'rights_usage_possibilities': None, 'radio_channels': ['Espace 2'], 'subdomains': ['Interview'], 'recording_dates': ['27/10/1986 - 27/10/1986'], 'first_broadcast_dates': None}
Skipping document 36/161 with OID {68B13ECA-8E61-42B7-B32A-E19637AB63E0} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {C7F87D6B-4A2F-4C19-8691-8132A9872066}. Trying to use the recording date. doc_dict: {'alias': 'mag_sci1', 'date_str': None, 'stt_filename': 'C7F87D6B-4A2F-4C19-8691-8132A9872066_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{C7F87D6B-4A2F-4C19-8691-8132A9872066}', 'stripped_OID': 'C7F87D6B-4A2F-4C19-8691-8132A9872066', 'login': '', 'broadcast_episode_title': "Histoires d'animaux (23/38) : L'hypnose", 'sequence': '1', 'broadcast_program_name': 'Magazine des sciences', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'BBR (NumA)', 'modified_on': '09.03.2023 12:15:09', 'physical_support_history': "Cote d'origine : MA 84151.b Resp. RSR : BBR Lot : Caisse 3141", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Production Radio-France. Pas de date de diff.', 'workflow_status': 'Accept?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': None, 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Tr?molin, Jacques', 'function': 'Pr?sentateur/trice', 'role': 'collaborateur/trice RSR'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Espace 2'], 'subdomains': None, 'recording_dates': ['12/09/1984 - 12/09/1984'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {FDF2494B-F925-47E6-A512-878E1FE0A553}. Trying to use the recording date. doc_dict: {'alias': 'mag_sci1', 'date_str': None, 'stt_filename': 'FDF2494B-F925-47E6-A512-878E1FE0A553_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{FDF2494B-F925-47E6-A512-878E1FE0A553}', 'stripped_OID': 'FDF2494B-F925-47E6-A512-878E1FE0A553', 'login': '', 'broadcast_episode_title': "Histoires d'animaux (24/38) : Le bouvreuil", 'sequence': '1', 'broadcast_program_name': 'Magazine des sciences', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '13.05.2022 19:14:23', 'physical_support_history': "Cote d'origine : MA 84151.c Lot : Caisse 3141", 'production_type': 'Production ext?rieure (?change)', 'recording_place': None, 'rights_notes': 'Production Radio-France.', 'rights_status': 'A rechercher', 'series_title': "Sauvegarde d'archives", 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': None, 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Tr?molin, Jacques', 'function': 'Interview?/e', 'role': 'conteur animalier'}, {'name': 'Inconnue', 'function': 'Intervieweur/euse', 'role': 'collaborateur/trice Radio-France'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': ['oiseau'], 'rights_usage_possibilities': ['FM'], 'radio_channels': ['Espace 2'], 'subdomains': ['Interview'], 'recording_dates': ['13/09/1984 - 13/09/1984'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {C52D606C-8AF6-411B-B466-138AF8EE594C}. Trying to use the recording date. doc_dict: {'alias': 'mag_sci1', 'date_str': None, 'stt_filename': 'C52D606C-8AF6-411B-B466-138AF8EE594C_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{C52D606C-8AF6-411B-B466-138AF8EE594C}', 'stripped_OID': 'C52D606C-8AF6-411B-B466-138AF8EE594C', 'login': '', 'broadcast_episode_title': "Histoires d'animaux (25/38) : La punaise", 'sequence': '1', 'broadcast_program_name': 'Magazine des sciences', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'BBR (NumA)', 'modified_on': '10.06.2022 18:01:04', 'physical_support_history': "Cote d'origine : MA 84151.d Resp. RSR : BBR Lot : Caisse 3141", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Production Radio-France. Pas de date de diff.', 'workflow_status': 'Accept?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': None, 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Tr?molin, Jacques', 'function': 'Pr?sentateur/trice', 'role': 'collaborateur/trice RSR'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Espace 2'], 'subdomains': None, 'recording_dates': ['14/09/1984 - 14/09/1984'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {F4C65B0C-C11F-4E0E-900E-ADA53197DCA6}. Trying to use the recording date. doc_dict: {'alias': 'mag_sci1', 'date_str': None, 'stt_filename': 'F4C65B0C-C11F-4E0E-900E-ADA53197DCA6_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{F4C65B0C-C11F-4E0E-900E-ADA53197DCA6}', 'stripped_OID': 'F4C65B0C-C11F-4E0E-900E-ADA53197DCA6', 'login': '', 'broadcast_episode_title': "Histoires d'animaux (26/38) : Le suicide des animaux", 'sequence': '1', 'broadcast_program_name': 'Magazine des sciences', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'BBR (NumA)', 'modified_on': '09.03.2023 14:02:50', 'physical_support_history': "Cote d'origine : MA 84151.e Resp. RSR : BBR Lot : Caisse 3141", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Production Radio-France. Pas de date de diff.', 'workflow_status': 'Accept?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': None, 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Tr?molin, Jacques', 'function': 'Pr?sentateur/trice', 'role': 'collaborateur/trice RSR'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Espace 2'], 'subdomains': None, 'recording_dates': ['19/09/1984 - 19/09/1984'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {C2ED80DF-F08F-41E0-B0FE-B5BCEC5CDD59}. Trying to use the recording date. doc_dict: {'alias': 'mag_sci1', 'date_str': None, 'stt_filename': 'C2ED80DF-F08F-41E0-B0FE-B5BCEC5CDD59_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{C2ED80DF-F08F-41E0-B0FE-B5BCEC5CDD59}', 'stripped_OID': 'C2ED80DF-F08F-41E0-B0FE-B5BCEC5CDD59', 'login': '', 'broadcast_episode_title': "Histoires d'animaux (27/38) : Les ?nes sauvages", 'sequence': '1', 'broadcast_program_name': 'Magazine des sciences', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'BBR (NumA)', 'modified_on': '09.03.2023 12:04:28', 'physical_support_history': "Cote d'origine : MA 84151.f Resp. RSR : BBR Lot : Caisse 3141", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Production Radio-France. Pas de date de diff.', 'workflow_status': 'Accept?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': None, 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Tr?molin, Jacques', 'function': 'Pr?sentateur/trice', 'role': 'collaborateur/trice RSR'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Espace 2'], 'subdomains': None, 'recording_dates': ['20/09/1984 - 20/09/1984'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {1ED4133A-2BD5-4D95-A5A0-4792C5A42DD3}. Trying to use the recording date. doc_dict: {'alias': 'mag_sci1', 'date_str': None, 'stt_filename': '1ED4133A-2BD5-4D95-A5A0-4792C5A42DD3_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{1ED4133A-2BD5-4D95-A5A0-4792C5A42DD3}', 'stripped_OID': '1ED4133A-2BD5-4D95-A5A0-4792C5A42DD3', 'login': '', 'broadcast_episode_title': 'Interview de Catherine Rivier : A propos du stress et de la fertilit?', 'sequence': '1', 'broadcast_program_name': 'Magazine des sciences', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'BBR (NumA)', 'modified_on': '25.05.2022 13:51:04', 'physical_support_history': "Cote d'origine : MA 8595.d Resp. RSR : BBR Lot : Caisse 3142", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Participant: inte:Rivier, Catherine;  Pas de date de diff', 'workflow_status': 'Accept?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': None, 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Schaerlig, Eric', 'function': 'Intervieweur/euse', 'role': 'collaborateur/trice RSR'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': None, 'recording_dates': ['11/09/1985 - 11/09/1985'], 'first_broadcast_dates': None}

100%|██████████| 1/1 [00:00<00:00,  1.19it/s]
26it [01:57,  8.08s/it]

Did not find any date for doc with OID {511F8FD1-D3CC-4C0B-B027-EC86B87BA507}. Trying to use the recording date. doc_dict: {'alias': 'mag_sci1', 'date_str': None, 'stt_filename': '511F8FD1-D3CC-4C0B-B027-EC86B87BA507_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{511F8FD1-D3CC-4C0B-B027-EC86B87BA507}', 'stripped_OID': '511F8FD1-D3CC-4C0B-B027-EC86B87BA507', 'login': '', 'broadcast_episode_title': 'Interview de Robert Hainard, sculpteur, peintre et naturaliste : A propos de la r??dition de son ouvrage "D?fense de l\'image" (Ed- La Baconni?re" et de sa position face ? l\'art abstrait', 'sequence': '1', 'broadcast_program_name': 'Magazine des sciences humaines', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'BBR (NumA)', 'modified_on': '12.05.2022 21:14:29', 'physical_support_history': "Cote d'origine : MP 8661.a Resp. RSR : BBR Lot : Caisse 3146", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': "Date d'enregistrement ? compl?ter", 'workflow_status': 'Accept?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Hainard, Robert', 'function': 'Interview?/e', 'role': None}, {'name': 'Lambelet, Sylvie', 'function': 'Intervieweur/euse', 'role': 'collaborateur/trice RSR'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': None, 'recording_dates': ['__/06/1987 - __/06/1987'], 'first_broadcast_dates': None}
The date for document with OID {511F8FD1-D3CC-4C0B-B027-EC86B87BA507} was invalid (__/06/1987) - changed it to 01/06/1987
The date for document with OID {511F8FD1-D3CC-4C0B-B027-EC86B87BA507} was invalid (__/06/1987) - changed it to 01/06/1987
Did not find any date for doc with OID {2733351D-64EF-4266-ABD5-770F0751AC1A}. Trying to use the recording date. doc_dict: {'alias': 'mag_sci1', 'date_str': None, 'stt_filename': '2733351D-64EF-4266-ABD5-770F0751AC1A_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{2733351D-64EF-4266-ABD5-770F0751AC1A}', 'stripped_OID': '2733351D-64EF-4266-ABD5-770F0751AC1A', 'login': '', 'broadcast_episode_title': 'Interview du professeur Louis Dubertret : A propos de la peau artificielle et de ses progr?s', 'sequence': '1', 'broadcast_program_name': 'Magazine des sciences', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'BBR (NumA)', 'modified_on': '12.05.2022 05:42:44', 'physical_support_history': "Cote d'origine : MA 8581.a Resp. RSR : BBR Lot : Caisse 3141", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Participant: inte:Dubertret, Louis;  pas de date diff. Modulation: mono', 'workflow_status': 'Accept?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': None, 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Scheps, Ruth', 'function': 'Intervieweur/euse', 'role': 'collaborateur/trice RSR'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': None, 'recording_dates': ['04/02/1985 - 04/02/1985'], 'first_broadcast_dates': None}
Skipping document 112/161 with OID {1846D353-FEAC-4E8E-9D9E-B5A7C2B48321} because it's missing its XML file!! (stt exists: False)
Skipping document 113/161 with OID {3782AF24-09D4-4A17-B903-FFDEA9D097D6} because it's missing its XML file!! (stt exists: False)
mag_sci1 - returning 158 documents, 3 were skipped due to missing necessary info.
 --> Adding 158 to the out csv for mag_sci1

PROCESSING PROGRAM mag_sci2 (27/47) - 1 files:

100%|██████████| 1/1 [00:00<00:00,  4.84it/s]
27it [01:58,  5.75s/it]

Starting extracting 62 documents for program mag_sci2
Did not find any date for doc with OID {516065DB-5296-41C7-9AF7-E9B5A076C7EB}. Trying to use the recording date. doc_dict: {'alias': 'mag_sci2', 'date_str': None, 'stt_filename': '516065DB-5296-41C7-9AF7-E9B5A076C7EB_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{516065DB-5296-41C7-9AF7-E9B5A076C7EB}', 'stripped_OID': '516065DB-5296-41C7-9AF7-E9B5A076C7EB', 'login': '', 'broadcast_episode_title': "Interviee d'Hugo Thiemann, Maurice Paquet, Roger Lacroix : A propos de la recherche scientifique", 'sequence': '1', 'broadcast_program_name': 'Magazine de la science', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'RCR (NumA)', 'modified_on': '29.05.2022 05:00:20', 'physical_support_history': "Cote d'origine : MP 657.c Resp. RSR : RCR Lot : Caisse 3038", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Participant: inte:Thiemann, Hugo;  inte:Paquet, Maurice;  inte:Lacroix, Roger', 'workflow_status': 'Accept?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Darmsteter, Jean-Paul', 'function': 'Intervieweur/euse', 'role': 'collaborateur/trice RSR'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Deuxi?me programme'], 'subdomains': None, 'recording_dates': ['20/01/1965 - 20/01/1965'], 'first_broadcast_dates': None}
mag_sci2 - returning 62 documents, 0 were skipped due to missing necessary info.
 --> Adding 62 to the out csv for mag_sci2

PROCESSING PROGRAM mag_tv1 (28/47) - 0 files:

0it [00:00, ?it/s]

 --> Adding 0 to the out csv for mag_tv1

PROCESSING PROGRAM mag_tv2 (29/47) - 1 files:

Starting extracting 72 documents for program mag_tv2
Skipping document 1/72 with OID {CC7B9112-89B2-48F4-9A1A-4A57AC994F7B} because it's missing its XML file!! (stt exists: False)
Skipping document 2/72 with OID {23CA5B60-4C6C-414E-A37B-BFD79F76884B} because it's missing its XML file!! (stt exists: False)
Skipping document 5/72 with OID {52A89335-F61D-4884-85D1-346173D2C8CD} because it's missing its XML file!! (stt exists: False)
Skipping document 6/72 with OID {D93909A9-4CC9-4347-9B4A-2B4C9FC03151} because it's missing its XML file!! (stt exists: False)
Skipping document 7/72 with OID {AB266DA5-DB6C-4174-A737-FBE98A62609F} because it's missing its XML file!! (stt exists: False)
Skipping document 8/72 with OID {C09CAE17-02CA-42BB-BE9F-213DF51AF30D} because it's missing its XML file!! (stt exists: False)
Skipping document 9/72 with OID {FEBF832C-BF2D-47D0-9405-0EAB15501514} because it's missing its XML file!! (stt exists: False)
Skipping document 10/72 with OID {D57668E8-F1F6-4576-B2F2-AFA070F22783} because it's missing its XML file!! (stt exists: False)
Skipping document 11/72 with OID {A1C8F274-413C-47FE-8D55-FD340226A07F} because it's missing its XML file!! (stt exists: False)
Skipping document 12/72 with OID {ABE57718-E408-45B4-8CB8-84246BCD07DC} because it's missing its XML file!! (stt exists: False)
Skipping document 13/72 with OID {87C732C9-1537-4C9B-8BD3-D0D248923704} because it's missing its XML file!! (stt exists: False)

100%|██████████| 1/1 [00:00<00:00,  3.72it/s]
29it [01:58,  3.17s/it]

Skipping document 16/72 with OID {67DC8B6C-878E-4F41-AA3C-8C8D8F1E3E67} because it's missing its XML file!! (stt exists: False)
Skipping document 17/72 with OID {E03DCECF-C05A-44F6-B939-7F2214212ACD} because it's missing its XML file!! (stt exists: False)
Skipping document 18/72 with OID {8E1FBEB9-26D8-4882-95E7-9106AD6A7E04} because it's missing its XML file!! (stt exists: False)
Skipping document 19/72 with OID {D55C947C-A3BF-4A2D-9E06-066ADECD3554} because it's missing its XML file!! (stt exists: False)
Skipping document 20/72 with OID {043AF4E8-A4F0-4E7A-A9CB-4BE2D022FC86} because it's missing its XML file!! (stt exists: False)
Skipping document 21/72 with OID {4FEEE59C-4861-42E2-8E5C-751E923CF389} because it's missing its XML file!! (stt exists: False)
Skipping document 22/72 with OID {71E77E43-12D8-4C21-97FD-1F04BC0948DE} because it's missing its XML file!! (stt exists: False)
Skipping document 23/72 with OID {E0B571C6-83F6-4F5C-8813-101307A573BF} because it's missing its XML file!! (stt exists: False)
Skipping document 24/72 with OID {4C76E0E5-252D-440A-8AF3-F21996E77615} because it's missing its XML file!! (stt exists: False)
Skipping document 25/72 with OID {6E649A70-B85C-43C7-88EF-4E3F8517E7A6} because it's missing its XML file!! (stt exists: False)
Skipping document 26/72 with OID {D3E3C9CA-88FB-4D0F-B4C5-DA0561049025} because it's missing its XML file!! (stt exists: False)
Skipping document 27/72 with OID {B797E50D-0327-42F7-8321-34BF9B827C95} because it's missing its XML file!! (stt exists: False)
Skipping document 28/72 with OID {4010D1FC-3E9E-4892-82B2-A8530518E71A} because it's missing its XML file!! (stt exists: False)
Skipping document 29/72 with OID {F196DA60-63BD-45D2-8CFF-949028129B80} because it's missing its XML file!! (stt exists: False)
Skipping document 30/72 with OID {A2E81CE6-FD17-4649-BE78-CBF7ACA23B6B} because it's missing its XML file!! (stt exists: False)
Skipping document 31/72 with OID {A5829A81-7488-4187-84C9-D3505F601854} because it's missing its XML file!! (stt exists: False)
Skipping document 32/72 with OID {2A20637B-C3DE-4AEB-9C24-9B4B271FFE38} because it's missing its XML file!! (stt exists: False)
Skipping document 33/72 with OID {FB419200-ED3B-4FE0-8E79-D92960A840C2} because it's missing its XML file!! (stt exists: False)
Skipping document 36/72 with OID {DB651180-78E1-4A35-8CFD-D50BF7607EE6} because it's missing its XML file!! (stt exists: False)
Skipping document 38/72 with OID {D7C3877F-972A-410A-9745-E0B01C2D0E68} because it's missing its XML file!! (stt exists: False)
Skipping document 39/72 with OID {4A238C64-EFE0-40B7-A372-11318A5C8C31} because it's missing its XML file!! (stt exists: False)
Skipping document 40/72 with OID {1B212856-AD33-453F-ADB5-5D2879DC555B} because it's missing its XML file!! (stt exists: False)
Skipping document 41/72 with OID {B4904019-C426-470F-80E0-736A86615112} because it's missing its XML file!! (stt exists: False)
Skipping document 42/72 with OID {14D6463B-3E84-4112-A66F-8033FF89030C} because it's missing its XML file!! (stt exists: False)
Skipping document 43/72 with OID {D87DFC8B-C18E-4EEB-86D0-2995E860A8E6} because it's missing its XML file!! (stt exists: False)
Skipping document 44/72 with OID {81F6E907-6FEE-42C8-B64D-EB683AF6C1CE} because it's missing its XML file!! (stt exists: False)
Skipping document 45/72 with OID {20DEB2DB-5BD5-4BFD-A298-474EDC1B9B65} because it's missing its XML file!! (stt exists: False)
Skipping document 46/72 with OID {D724657C-D7D9-4926-B0EC-8536176419A1} because it's missing its XML file!! (stt exists: False)
Skipping document 47/72 with OID {FBCE6FEE-0EA1-4923-B5BE-EE1653ECB12B} because it's missing its XML file!! (stt exists: False)
Skipping document 48/72 with OID {FA20944B-139D-4085-BE65-836968184153} because it's missing its XML file!! (stt exists: False)
Skipping document 49/72 with OID {4EF3E274-FF7B-40B4-AC3A-E13CDBADAEDA} because it's missing its XML file!! (stt exists: False)
Skipping document 50/72 with OID {40CAF0E4-7931-481C-95AC-D10136C2C1C9} because it's missing its XML file!! (stt exists: False)
Skipping document 51/72 with OID {6CADF1E2-C61C-4937-9F3F-923EC0B71E06} because it's missing its XML file!! (stt exists: False)
Skipping document 52/72 with OID {1FF97B92-3EAF-4169-8041-DE9A6EB8C244} because it's missing its XML file!! (stt exists: False)
Skipping document 53/72 with OID {B5F7A003-6691-4A91-8F57-06C80285145C} because it's missing its XML file!! (stt exists: False)
Skipping document 54/72 with OID {ACDA9A8E-FEE9-4DF3-9426-6E6A66C6170C} because it's missing its XML file!! (stt exists: False)
Skipping document 55/72 with OID {16249FBC-937F-4D1F-BA32-14C81F7A641D} because it's missing its XML file!! (stt exists: False)
Skipping document 56/72 with OID {94F4888D-3122-4F08-A0E6-BA71F2578BCE} because it's missing its XML file!! (stt exists: False)
Skipping document 57/72 with OID {5AA51769-4152-404A-B9C0-D230F68A20A9} because it's missing its XML file!! (stt exists: False)
Skipping document 58/72 with OID {50C8BF23-CEC9-40CB-9529-773B2BCAB73E} because it's missing its XML file!! (stt exists: False)
Skipping document 59/72 with OID {318BE565-5AC1-4C33-A1B1-CE54A8E02FE3} because it's missing its XML file!! (stt exists: False)
Skipping document 60/72 with OID {DAD5D783-8DBE-4FFA-95B9-F6F0C6D8EC58} because it's missing its XML file!! (stt exists: False)
Skipping document 61/72 with OID {0F9D0A47-849F-4D79-8B1B-F4B0AD1E7CE9} because it's missing its XML file!! (stt exists: False)
Skipping document 62/72 with OID {07A90FA5-503E-48BC-90E3-98AEB4777674} because it's missing its XML file!! (stt exists: False)
Skipping document 63/72 with OID {D212A945-98EC-4D06-ABC4-A0335D3581AB} because it's missing its XML file!! (stt exists: False)
Skipping document 64/72 with OID {9461D30C-CC05-450F-8CE9-8D32F6853491} because it's missing its XML file!! (stt exists: False)
Skipping document 65/72 with OID {2A6933F5-09C6-45AD-897A-C9223C85836A} because it's missing its XML file!! (stt exists: False)
Skipping document 66/72 with OID {AD439C9B-4FDC-47E1-956D-2A3BDE095D5C} because it's missing its XML file!! (stt exists: False)
Skipping document 67/72 with OID {776EDF2C-4D13-408F-A031-A63393FB2733} because it's missing its XML file!! (stt exists: False)
Skipping document 68/72 with OID {F65D64B5-2F50-4EE8-A57F-740DC409850E} because it's missing its XML file!! (stt exists: False)
Skipping document 69/72 with OID {61451B33-CC5F-4C26-B738-A5556EC98E01} because it's missing its XML file!! (stt exists: False)
Skipping document 70/72 with OID {830AD522-FA13-482D-93A7-489CD478E68F} because it's missing its XML file!! (stt exists: False)
Skipping document 71/72 with OID {B345FBAD-3C88-4E60-BE5D-B40D5F243C52} because it's missing its XML file!! (stt exists: False)
Skipping document 72/72 with OID {42D62FA5-48F9-4452-A563-1F8D2BA084D3} because it's missing its XML file!! (stt exists: False)
mag_tv2 - returning 7 documents, 65 were skipped due to missing necessary info.
 --> Adding 7 to the out csv for mag_tv2

PROCESSING PROGRAM mem_ondes (30/47) - 1 files:

Starting extracting 95 documents for program mem_ondes
Skipping document 1/95 with OID {F96F2E2E-3E38-4840-9E21-535415D78768} because it's missing its XML file!! (stt exists: False)
Skipping document 11/95 with OID {CF570038-08F3-4B01-B869-5316291A261D} because it's missing its XML file!! (stt exists: False)
Skipping document 25/95 with OID {DAD396AC-77D3-437A-807F-E2A167A256FC} because it's missing its XML file!! (stt exists: False)
Skipping document 40/95 with OID {185156B1-88C9-45B8-A96A-114FCD5C002F} because it's missing its XML file!! (stt exists: False)
Skipping document 46/95 with OID {51E72952-65BF-4B0A-80A2-9DD14473882F} because it's missing its XML file!! (stt exists: False)
Skipping document 52/95 with OID {7CB48CC9-A595-41FD-A7CA-C18BB584E96E} because it's missing its XML file!! (stt exists: False)
Skipping document 60/95 with OID {BAF371B9-7F37-47AA-B8E7-DB6FC8B75AC1} because it's missing its XML file!! (stt exists: False)
Skipping document 71/95 with OID {66C11247-BF10-4D8C-9958-3E1C0FA7F5C1} because it's missing its XML file!! (stt exists: False)

100%|██████████| 1/1 [00:00<00:00,  1.61it/s]
30it [01:59,  2.56s/it]

Skipping document 79/95 with OID {57C10FBF-DE66-4ED4-916F-EB1D8FCD7C17} because it's missing its XML file!! (stt exists: False)
Skipping document 80/95 with OID {2760ED8D-E681-428A-AF29-D2A183721E44} because it's missing its XML file!! (stt exists: False)
Skipping document 81/95 with OID {FA63854B-5C8B-4415-B19F-E6B5C7339545} because it's missing its XML file!! (stt exists: False)
Skipping document 82/95 with OID {14C3BE63-5D6A-4050-85A6-B8C4756FA1D1} because it's missing its XML file!! (stt exists: False)
Skipping document 87/95 with OID {1EB814C5-4C38-46F0-AC35-D5E2C2B420F1} because it's missing its XML file!! (stt exists: False)
Skipping document 92/95 with OID {9EDD62C4-0BF7-4496-93B9-5557B1EF46C5} because it's missing its XML file!! (stt exists: False)
mem_ondes - returning 81 documents, 14 were skipped due to missing necessary info.
 --> Adding 81 to the out csv for mem_ondes

PROCESSING PROGRAM min_oecu (31/47) - 1 files:

Starting extracting 334 documents for program min_oecu
The date for document with OID {4F103868-7C11-4440-BC6F-00872A969A43} was invalid (__/__/1987) - changed it to 01/01/1987
The date for document with OID {4F103868-7C11-4440-BC6F-00872A969A43} was invalid (__/__/1988) - changed it to 01/01/1988
Did not find any date for doc with OID {F17322A4-51C4-4ABC-BC4A-7C722E33183F}. Trying to use the recording date. doc_dict: {'alias': 'min_oecu', 'date_str': None, 'stt_filename': 'F17322A4-51C4-4ABC-BC4A-7C722E33183F_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{F17322A4-51C4-4ABC-BC4A-7C722E33183F}', 'stripped_OID': 'F17322A4-51C4-4ABC-BC4A-7C722E33183F', 'login': '', 'broadcast_episode_title': 'A la veille du Je?ne f?d?ral. Chronique de et par Pierre Pascal, pr?tre', 'sequence': '1', 'broadcast_program_name': 'Minute oecum?nique', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'mertenpi', 'modified_on': '09.03.2023 13:49:31', 'physical_support_history': None, 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:01:04.992', 'work_duration_compl': 'Non', 'participants': [{'name': 'Pascal, Pierre', 'function': 'Commentateur/trice', 'role': 'pr?tre'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': ['croyance religieuse', 'catholicisme', 'Je?ne f?d?ral'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Commentaire'], 'recording_dates': ['31/12/1981 - 31/12/1981 / Avant', '31/12/1974 - 31/12/1974 / Apr?s'], 'first_broadcast_dates': None}
The date for document with OID {A8841F18-8176-4923-A314-7DB3D4CF4295} was invalid (__/__/1975) - changed it to 01/01/1975
The date for document with OID {A8841F18-8176-4923-A314-7DB3D4CF4295} was invalid (__/__/1981) - changed it to 01/01/1981
The date for document with OID {21B26C32-CCA5-4F15-9001-C7FF29EE0D30} was invalid (__/__/1986) - changed it to 01/01/1986
The date for document with OID {040636AF-F631-4978-9A2A-78A2FC824039} was invalid (__/__/1986) - changed it to 01/01/1986
The date for document with OID {16DE4581-0F5C-4AE3-86B7-E0C958FC7A34} was invalid (__/__/1986) - changed it to 01/01/1986
The date for document with OID {BD83965F-3F5D-4A3F-B6E9-64BDBC1B26FA} was invalid (__/__/1986) - changed it to 01/01/1986
The date for document with OID {6B42DE5F-06B3-4837-95E2-F88D28394FE9} was invalid (__/__/1977) - changed it to 01/01/1977
The date for document with OID {004CAF31-0FC4-419C-8305-919AEE8D4088} was invalid (__/__/1977) - changed it to 01/01/1977
The date for document with OID {004CAF31-0FC4-419C-8305-919AEE8D4088} was invalid (__/__/1977) - changed it to 01/01/1977
The date for document with OID {2F96FFEB-DE06-42BF-AE44-C8DD9BEEC722} was invalid (__/__/1986) - changed it to 01/01/1986
The date for document with OID {539C453F-47AC-4BA1-8629-57155CAD58D6} was invalid (__/__/1987) - changed it to 01/01/1987
The date for document with OID {539C453F-47AC-4BA1-8629-57155CAD58D6} was invalid (__/__/1988) - changed it to 01/01/1988
The date for document with OID {14DD13EC-A31B-4AD7-9976-37AA73FBEB06} was invalid (__/__/1977) - changed it to 01/01/1977
The date for document with OID {7D60B400-CD7E-4035-B25C-55BD33CD71D0} was invalid (__/__/1987) - changed it to 01/01/1987
The date for document with OID {7D60B400-CD7E-4035-B25C-55BD33CD71D0} was invalid (__/__/1988) - changed it to 01/01/1988
The date for document with OID {97108FED-E5BF-48FD-B868-061B336F9B4B} was invalid (__/__/1986) - changed it to 01/01/1986
The date for document with OID {49B6F53F-FEB3-49A4-BF5C-A5239AF450AA} was invalid (__/03/1981) - changed it to 01/03/1981
Did not find any date for doc with OID {63110215-CE83-4827-AF31-D487B3D9717E}. Trying to use the recording date. doc_dict: {'alias': 'min_oecu', 'date_str': None, 'stt_filename': '63110215-CE83-4827-AF31-D487B3D9717E_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{63110215-CE83-4827-AF31-D487B3D9717E}', 'stripped_OID': '63110215-CE83-4827-AF31-D487B3D9717E', 'login': '', 'broadcast_episode_title': 'Bagages de vacances. Chronique de et par Pierre Pascal, pr?tre', 'sequence': '1', 'broadcast_program_name': 'Minute oecum?nique', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'mertenpi', 'modified_on': '18.03.2023 20:23:10', 'physical_support_history': None, 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:01:02.472', 'work_duration_compl': 'Non', 'participants': [{'name': 'Pascal, Pierre', 'function': 'Commentateur/trice', 'role': 'pr?tre'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': ['croyance religieuse', 'catholicisme', 'vacances', 'bagage'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Commentaire'], 'recording_dates': ['31/12/1981 - 31/12/1981 / Avant', '31/12/1974 - 31/12/1974 / Apr?s'], 'first_broadcast_dates': None}
The date for document with OID {CC489988-3386-4582-9907-1BE5C6686DE8} was invalid (__/__/1977) - changed it to 01/01/1977
The date for document with OID {AB2FC64E-75D5-4941-A2F1-074D02E83E31} was invalid (__/__/1987) - changed it to 01/01/1987
The date for document with OID {AB2FC64E-75D5-4941-A2F1-074D02E83E31} was invalid (__/__/1988) - changed it to 01/01/1988
The date for document with OID {1EF7F867-D9CA-4FE0-A5A3-E87995398DAF} was invalid (__/03/1987) - changed it to 01/03/1987
The date for document with OID {D0A5A92F-DB33-4A95-9BFA-395517DFF4A1} was invalid (__/__/1986) - changed it to 01/01/1986
The date for document with OID {E545728D-74CB-4958-BEE6-2D63733C63F9} was invalid (__/__/1986) - changed it to 01/01/1986
The date for document with OID {6771B2EB-9F59-4C41-B896-BA4DD03C968E} was invalid (__/__/1986) - changed it to 01/01/1986
Did not find any date for doc with OID {26A109AD-F8AE-441A-804B-28D855ECBEE2}. Trying to use the recording date. doc_dict: {'alias': 'min_oecu', 'date_str': None, 'stt_filename': '26A109AD-F8AE-441A-804B-28D855ECBEE2_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{26A109AD-F8AE-441A-804B-28D855ECBEE2}', 'stripped_OID': '26A109AD-F8AE-441A-804B-28D855ECBEE2', 'login': '', 'broadcast_episode_title': 'Confort versus ouverture. Chronique de et par Pierre Pascal, pr?tre', 'sequence': '1', 'broadcast_program_name': 'Minute oecum?nique', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'mertenpi', 'modified_on': '09.06.2022 05:36:12', 'physical_support_history': None, 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:01:03.936', 'work_duration_compl': 'Non', 'participants': [{'name': 'Pascal, Pierre', 'function': 'Commentateur/trice', 'role': 'pr?tre'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': ['croyance religieuse', 'catholicisme', 'pauvret?'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Commentaire'], 'recording_dates': ['31/12/1981 - 31/12/1981 / Avant', '31/12/1974 - 31/12/1974 / Apr?s'], 'first_broadcast_dates': None}
The date for document with OID {A29245A8-8240-4ED5-93F1-968E471369F3} was invalid (__/03/1987) - changed it to 01/03/1987
The date for document with OID {475B5199-6A18-48BD-837B-18249E5F24A6} was invalid (__/03/1987) - changed it to 01/03/1987
The date for document with OID {C19DBA0D-9001-451A-995F-84B39933E84F} was invalid (__/__/1986) - changed it to 01/01/1986
The date for document with OID {CB83B22B-BF73-4B2E-AF9F-FA20861999DB} was invalid (__/__/1986) - changed it to 01/01/1986
The date for document with OID {ECC9CCDC-F1F9-4670-A467-DE1BB8299D6A} was invalid (__/__/1975) - changed it to 01/01/1975
The date for document with OID {ECC9CCDC-F1F9-4670-A467-DE1BB8299D6A} was invalid (__/__/1981) - changed it to 01/01/1981
The date for document with OID {AB5FB1AE-C397-46A9-9CA8-DB820461D7F6} was invalid (__/__/1986) - changed it to 01/01/1986
The date for document with OID {0C428A11-185B-420F-9CDA-B8BFD3F2ADE7} was invalid (__/__/1987) - changed it to 01/01/1987
The date for document with OID {0C428A11-185B-420F-9CDA-B8BFD3F2ADE7} was invalid (__/__/1988) - changed it to 01/01/1988
Did not find any date for doc with OID {60D59D25-EAF4-4080-8FB0-2042A95875F8}. Trying to use the recording date. doc_dict: {'alias': 'min_oecu', 'date_str': None, 'stt_filename': '60D59D25-EAF4-4080-8FB0-2042A95875F8_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{60D59D25-EAF4-4080-8FB0-2042A95875F8}', 'stripped_OID': '60D59D25-EAF4-4080-8FB0-2042A95875F8', 'login': '', 'broadcast_episode_title': 'Demain, le temps des martyrs. Chronique de et par Pierre Pascal, pr?tre', 'sequence': '1', 'broadcast_program_name': 'Minute oecum?nique', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'mertenpi', 'modified_on': '28.05.2022 17:46:22', 'physical_support_history': None, 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:01:13.920', 'work_duration_compl': 'Non', 'participants': [{'name': 'Pascal, Pierre', 'function': 'Commentateur/trice', 'role': 'pr?tre'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': ['croyance religieuse', 'catholicisme', 'pauvret?'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Commentaire'], 'recording_dates': ['31/12/1981 - 31/12/1981 / Avant', '31/12/1974 - 31/12/1974 / Apr?s'], 'first_broadcast_dates': None}
The date for document with OID {B14332A8-1896-4B30-A405-BADE080E3FC8} was invalid (__/__/1987) - changed it to 01/01/1987
The date for document with OID {B14332A8-1896-4B30-A405-BADE080E3FC8} was invalid (__/__/1988) - changed it to 01/01/1988
Did not find any date for doc with OID {2AAECBA1-57E5-4735-B8C1-3AA2375999BB}. Trying to use the recording date. doc_dict: {'alias': 'min_oecu', 'date_str': None, 'stt_filename': '2AAECBA1-57E5-4735-B8C1-3AA2375999BB_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{2AAECBA1-57E5-4735-B8C1-3AA2375999BB}', 'stripped_OID': '2AAECBA1-57E5-4735-B8C1-3AA2375999BB', 'login': '', 'broadcast_episode_title': 'D?noncer, oui, mais aimer quand m?me. Chronique de et par Pierre Pascal, pr?tre', 'sequence': '1', 'broadcast_program_name': 'Minute oecum?nique', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'mertenpi', 'modified_on': '24.05.2022 13:30:20', 'physical_support_history': None, 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:01:05.448', 'work_duration_compl': 'Non', 'participants': [{'name': 'Pascal, Pierre', 'function': 'Commentateur/trice', 'role': 'pr?tre'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': ['croyance religieuse', 'catholicisme', 'morale'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Commentaire'], 'recording_dates': ['31/12/1981 - 31/12/1981 / Avant', '31/12/1974 - 31/12/1974 / Apr?s'], 'first_broadcast_dates': None}
The date for document with OID {4360E178-7FDB-45BA-AB12-622EB3E7EA85} was invalid (__/__/1984) - changed it to 01/01/1984
The date for document with OID {41F6799E-632B-4A90-ABC9-63BDB35CB2DE} was invalid (__/__/1987) - changed it to 01/01/1987
The date for document with OID {41F6799E-632B-4A90-ABC9-63BDB35CB2DE} was invalid (__/__/1988) - changed it to 01/01/1988
The date for document with OID {A6F6014E-6290-4D10-A80D-A9939032F51C} was invalid (__/__/1986) - changed it to 01/01/1986
The date for document with OID {62227FFE-1314-4D61-8F79-4A99C2008339} was invalid (__/__/1986) - changed it to 01/01/1986
The date for document with OID {65711702-8240-4CF9-B78A-F6AD64DB7A20} was invalid (__/__/1975) - changed it to 01/01/1975
The date for document with OID {65711702-8240-4CF9-B78A-F6AD64DB7A20} was invalid (__/__/1981) - changed it to 01/01/1981
The date for document with OID {BAEFB8B2-6A32-481A-87BE-8EA1413F94B2} was invalid (__/__/1982) - changed it to 01/01/1982
Did not find any date for doc with OID {3B1F0480-6CBA-4CAF-BF7B-F4DE641501E9}. Trying to use the recording date. doc_dict: {'alias': 'min_oecu', 'date_str': None, 'stt_filename': '3B1F0480-6CBA-4CAF-BF7B-F4DE641501E9_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{3B1F0480-6CBA-4CAF-BF7B-F4DE641501E9}', 'stripped_OID': '3B1F0480-6CBA-4CAF-BF7B-F4DE641501E9', 'login': '', 'broadcast_episode_title': 'Entre la th?orie et la pratique. Chronique de et par Andr? Babel, pr?tre', 'sequence': '1', 'broadcast_program_name': 'Minute oecum?nique', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'mertenpi', 'modified_on': '30.05.2022 12:11:56', 'physical_support_history': None, 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:02:01.080', 'work_duration_compl': 'Non', 'participants': [{'name': 'Babel, Andr?', 'function': 'Commentateur/trice', 'role': 'pr?tre'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': ['croyance religieuse', 'catholicisme'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Commentaire'], 'recording_dates': ['__/08/1965 - __/08/1965'], 'first_broadcast_dates': None}
The date for document with OID {3B1F0480-6CBA-4CAF-BF7B-F4DE641501E9} was invalid (__/08/1965) - changed it to 01/08/1965
The date for document with OID {3B1F0480-6CBA-4CAF-BF7B-F4DE641501E9} was invalid (__/08/1965) - changed it to 01/08/1965
The date for document with OID {0E292246-797E-4548-96A3-737537A6B553} was invalid (__/__/1984) - changed it to 01/01/1984
The date for document with OID {0E292246-797E-4548-96A3-737537A6B553} was invalid (__/__/1985) - changed it to 01/01/1985
The date for document with OID {35BFDFA5-D67A-4600-B193-D14F7F10FCEE} was invalid (__/__/1987) - changed it to 01/01/1987
The date for document with OID {35BFDFA5-D67A-4600-B193-D14F7F10FCEE} was invalid (__/__/1988) - changed it to 01/01/1988
Did not find any date for doc with OID {31A50690-3FBE-4944-AA31-0127B70AFB8E}. Trying to use the recording date. doc_dict: {'alias': 'min_oecu', 'date_str': None, 'stt_filename': '31A50690-3FBE-4944-AA31-0127B70AFB8E_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{31A50690-3FBE-4944-AA31-0127B70AFB8E}', 'stripped_OID': '31A50690-3FBE-4944-AA31-0127B70AFB8E', 'login': '', 'broadcast_episode_title': 'Face au d?couragement. Chronique de et par Pierre Pascal, pr?tre', 'sequence': '1', 'broadcast_program_name': 'Minute oecum?nique', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'mertenpi', 'modified_on': '10.06.2022 10:15:57', 'physical_support_history': None, 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:01:01.200', 'work_duration_compl': 'Non', 'participants': [{'name': 'Pascal, Pierre', 'function': 'Commentateur/trice', 'role': 'pr?tre'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': ['croyance religieuse', 'catholicisme', 'vie (philosophie)'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Commentaire'], 'recording_dates': ['31/12/1981 - 31/12/1981 / Avant', '31/12/1974 - 31/12/1974 / Apr?s'], 'first_broadcast_dates': None}
The date for document with OID {EB641936-DC2A-44E2-818A-CF151787EF2A} was invalid (__/03/1987) - changed it to 01/03/1987
The date for document with OID {EB641936-DC2A-44E2-818A-CF151787EF2A} was invalid (__/03/1987) - changed it to 01/03/1987
The date for document with OID {D9F02C45-3F44-4788-8702-8BF46CF64A07} was invalid (__/__/1986) - changed it to 01/01/1986
The date for document with OID {341551E8-DB19-4193-B8DE-56F95ECB0861} was invalid (__/01/1978) - changed it to 01/01/1978
The date for document with OID {42D8DE0F-B4E2-4DA7-8CC8-822E7591A59D} was invalid (__/__/1975) - changed it to 01/01/1975
The date for document with OID {42D8DE0F-B4E2-4DA7-8CC8-822E7591A59D} was invalid (__/__/1981) - changed it to 01/01/1981
The date for document with OID {9A86A660-B09C-40D9-BEED-593A84B23E00} was invalid (__/__/1984) - changed it to 01/01/1984
The date for document with OID {7A7C5F46-183E-495D-9472-5CF6F1B82C7D} was invalid (__/__/1987) - changed it to 01/01/1987
The date for document with OID {7A7C5F46-183E-495D-9472-5CF6F1B82C7D} was invalid (__/__/1988) - changed it to 01/01/1988
The date for document with OID {5DD13BB8-CD57-4B7D-BC80-A7A88C8CE374} was invalid (__/__/1986) - changed it to 01/01/1986
The date for document with OID {8BAE99FD-9469-40B1-BE20-CD39CAC90169} was invalid (__/__/1977) - changed it to 01/01/1977
The date for document with OID {26C40E47-3813-41B5-8E14-BDA0841A84E4} was invalid (__/02/1987) - changed it to 01/02/1987
Did not find any date for doc with OID {F398E482-763A-49A5-A9B9-5A12A3F5684B}. Trying to use the recording date. doc_dict: {'alias': 'min_oecu', 'date_str': None, 'stt_filename': 'F398E482-763A-49A5-A9B9-5A12A3F5684B_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{F398E482-763A-49A5-A9B9-5A12A3F5684B}', 'stripped_OID': 'F398E482-763A-49A5-A9B9-5A12A3F5684B', 'login': '', 'broadcast_episode_title': 'Indicatif de l\'?mission "Minute oecum?nique"', 'sequence': '2', 'broadcast_program_name': 'Minute oecum?nique', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'aqt (NumA)', 'modified_on': '31.05.2022 09:21:42', 'physical_support_history': "Cote d'origine : Bd 14294.01 Resp. RSR : aqt Lot : Caisse 1243", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': None, 'series_title': 'Indicatifs RSR', 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': '[musique]', 'function': 'Divers', 'role': None}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': None, 'radio_channels': ['La Premi?re', 'Espace 2'], 'subdomains': ['Indicatif', 'Parl? divers'], 'recording_dates': ['~__/__/1970 - ~__/__/1970'], 'first_broadcast_dates': None}

100%|██████████| 1/1 [00:01<00:00,  1.33s/it]

Did not find any date for doc with OID {C20C8415-4063-4F58-BEF6-42FDF208563A}. Trying to use the recording date. doc_dict: {'alias': 'min_oecu', 'date_str': None, 'stt_filename': 'C20C8415-4063-4F58-BEF6-42FDF208563A_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{C20C8415-4063-4F58-BEF6-42FDF208563A}', 'stripped_OID': 'C20C8415-4063-4F58-BEF6-42FDF208563A', 'login': '', 'broadcast_episode_title': 'Les r?troviseurs. Chronique de et par Pierre Pascal, pr?tre', 'sequence': '1', 'broadcast_program_name': 'Minute oecum?nique', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'mertenpi', 'modified_on': '25.05.2022 07:21:09', 'physical_support_history': None, 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:01:09.696', 'work_duration_compl': 'Non', 'participants': [{'name': 'Pascal, Pierre', 'function': 'Commentateur/trice', 'role': 'pr?tre'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': ['croyance religieuse', 'catholicisme'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Commentaire'], 'recording_dates': ['31/12/1981 - 31/12/1981 / Avant', '31/12/1974 - 31/12/1974 / Apr?s'], 'first_broadcast_dates': None}
The date for document with OID {8E7436CE-C9BC-4005-A53F-E1B13222C0CC} was invalid (__/01/1978) - changed it to 01/01/1978
The date for document with OID {86D8247A-AFCA-44BE-9DD2-32A7F5DE8D65} was invalid (__/__/1984) - changed it to 01/01/1984
The date for document with OID {0549CF11-DD81-40E3-8A16-010E1F84CF13} was invalid (__/__/1986) - changed it to 01/01/1986
The date for document with OID {28B8D68D-5676-49A6-A95E-3A2E37E96383} was invalid (__/__/1977) - changed it to 01/01/1977
The date for document with OID {C7A7BD5B-42FC-4E3E-8B42-271CA566983A} was invalid (__/__/1987) - changed it to 01/01/1987
The date for document with OID {C7A7BD5B-42FC-4E3E-8B42-271CA566983A} was invalid (__/__/1988) - changed it to 01/01/1988
The date for document with OID {9B859823-CDCE-4235-B30A-8ABA4998099E} was invalid (__/01/1978) - changed it to 01/01/1978
The date for document with OID {8A9B6E8C-8454-4256-89C0-5AAE0D3D62A3} was invalid (__/__/1986) - changed it to 01/01/1986
Did not find any date for doc with OID {9903883B-6C5A-4AEF-9E3B-78C4DF754652}. Trying to use the recording date. doc_dict: {'alias': 'min_oecu', 'date_str': None, 'stt_filename': '9903883B-6C5A-4AEF-9E3B-78C4DF754652_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{9903883B-6C5A-4AEF-9E3B-78C4DF754652}', 'stripped_OID': '9903883B-6C5A-4AEF-9E3B-78C4DF754652', 'login': '', 'broadcast_episode_title': "L'?tat de veille. Chronique de et par Pierre Pascal, pr?tre", 'sequence': '1', 'broadcast_program_name': 'Minute oecum?nique', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'mertenpi', 'modified_on': '09.03.2023 11:23:08', 'physical_support_history': None, 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:01:09.936', 'work_duration_compl': 'Non', 'participants': [{'name': 'Pascal, Pierre', 'function': 'Commentateur/trice', 'role': 'pr?tre'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': ['croyance religieuse', 'catholicisme', 'relation interpersonnelle'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Commentaire'], 'recording_dates': ['31/12/1981 - 31/12/1981 / Avant', '31/12/1974 - 31/12/1974 / Apr?s'], 'first_broadcast_dates': None}
The date for document with OID {E5F2C30B-6F39-4E67-AF03-F51427179FE3} was invalid (__/__/1984) - changed it to 01/01/1984
The date for document with OID {E5F2C30B-6F39-4E67-AF03-F51427179FE3} was invalid (__/__/1985) - changed it to 01/01/1985
The date for document with OID {0D94BEB4-DC56-464D-ADB8-4CA782677681} was invalid (__/04/1981) - changed it to 01/04/1981
The date for document with OID {4248D6AE-02D6-4284-B39F-023781FED4D6} was invalid (__/__/1975) - changed it to 01/01/1975
The date for document with OID {4248D6AE-02D6-4284-B39F-023781FED4D6} was invalid (__/__/1981) - changed it to 01/01/1981
The date for document with OID {0C453843-0CAA-4AFE-9B7D-2A39D228B25C} was invalid (__/__/1986) - changed it to 01/01/1986
The date for document with OID {9D76CF91-714E-495C-A359-31D778977B0F} was invalid (__/__/1984) - changed it to 01/01/1984
The date for document with OID {40E49D5C-747F-4A78-AF7C-418B692A75CB} was invalid (__/02/1987) - changed it to 01/02/1987
The date for document with OID {BC2041F3-A765-4BB3-A8C7-86267ECD594E} was invalid (__/04/1981) - changed it to 01/04/1981
The date for document with OID {81314138-A162-4794-A21D-88A58383F705} was invalid (__/__/1986) - changed it to 01/01/1986
The date for document with OID {6230AD47-ED1F-4864-B6EE-64FCE0558F2B} was invalid (__/__/1984) - changed it to 01/01/1984
The date for document with OID {0F0A4E86-AAFE-4A5F-B451-238E04185F21} was invalid (__/03/1981) - changed it to 01/03/1981
The date for document with OID {C22048A6-37E9-4775-A23D-0BF5686899B6} was invalid (__/__/1986) - changed it to 01/01/1986
Did not find any date for doc with OID {D4F98883-E96C-4369-B946-F128DCB78445}. Trying to use the recording date. doc_dict: {'alias': 'min_oecu', 'date_str': None, 'stt_filename': 'D4F98883-E96C-4369-B946-F128DCB78445_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{D4F98883-E96C-4369-B946-F128DCB78445}', 'stripped_OID': 'D4F98883-E96C-4369-B946-F128DCB78445', 'login': '', 'broadcast_episode_title': 'Minorit?s versus majorit?s. Chronique de et par Pierre Pascal, pr?tre', 'sequence': '1', 'broadcast_program_name': 'Minute oecum?nique', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'mertenpi', 'modified_on': '09.03.2023 13:25:56', 'physical_support_history': None, 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:01:05.064', 'work_duration_compl': 'Non', 'participants': [{'name': 'Pascal, Pierre', 'function': 'Commentateur/trice', 'role': 'pr?tre'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': ['croyance religieuse', 'catholicisme', 'minorit?'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Commentaire'], 'recording_dates': ['31/12/1981 - 31/12/1981 / Avant', '31/12/1974 - 31/12/1974 / Apr?s'], 'first_broadcast_dates': None}
The date for document with OID {1E3953CE-F615-4B3D-BC9A-D6A6F45C9C43} was invalid (__/01/1971) - changed it to 01/01/1971
The date for document with OID {1E3953CE-F615-4B3D-BC9A-D6A6F45C9C43} was invalid (__/01/1971) - changed it to 01/01/1971
The date for document with OID {74B5037C-2FB3-4447-8245-8FB8E405E4A7} was invalid (__/07/1970) - changed it to 01/07/1970
The date for document with OID {419C89F2-5076-4FD8-B3FE-E19BAF7BA329} was invalid (__/05/1970) - changed it to 01/05/1970
The date for document with OID {CE1F32AC-BC9C-423C-8F58-6AF88DD7B4E5} was invalid (__/02/1987) - changed it to 01/02/1987
The date for document with OID {AFAA4511-F22C-437C-ADF4-62FA49896AEB} was invalid (__/__/1977) - changed it to 01/01/1977
Did not find any date for doc with OID {4A79CF02-4639-4F00-8381-A9E06D784174}. Trying to use the recording date. doc_dict: {'alias': 'min_oecu', 'date_str': None, 'stt_filename': '4A79CF02-4639-4F00-8381-A9E06D784174_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{4A79CF02-4639-4F00-8381-A9E06D784174}', 'stripped_OID': '4A79CF02-4639-4F00-8381-A9E06D784174', 'login': '', 'broadcast_episode_title': 'Nomades en roulottes. Chronique de et par Pierre Pascal, pr?tre', 'sequence': '1', 'broadcast_program_name': 'Minute oecum?nique', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'mertenpi', 'modified_on': '31.05.2022 00:46:27', 'physical_support_history': None, 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:01:12.240', 'work_duration_compl': 'Non', 'participants': [{'name': 'Pascal, Pierre', 'function': 'Commentateur/trice', 'role': 'pr?tre'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': ['croyance religieuse', 'catholicisme', 'nomadisme'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Commentaire'], 'recording_dates': ['31/12/1981 - 31/12/1981 / Avant', '31/12/1974 - 31/12/1974 / Apr?s'], 'first_broadcast_dates': None}
The date for document with OID {395FF03D-4548-4746-A109-C1E7B3C900D2} was invalid (__/__/1986) - changed it to 01/01/1986
The date for document with OID {380E0A7D-047D-41C6-B5D7-60B28A15713A} was invalid (__/__/1987) - changed it to 01/01/1987
The date for document with OID {380E0A7D-047D-41C6-B5D7-60B28A15713A} was invalid (__/__/1988) - changed it to 01/01/1988
The date for document with OID {AFA72EE1-7848-4D62-AA19-1ACC881F0448} was invalid (__/__/1975) - changed it to 01/01/1975
The date for document with OID {AFA72EE1-7848-4D62-AA19-1ACC881F0448} was invalid (__/__/1981) - changed it to 01/01/1981
Did not find any date for doc with OID {DFE1ED2A-AA54-427F-9045-66808EC84424}. Trying to use the recording date. doc_dict: {'alias': 'min_oecu', 'date_str': None, 'stt_filename': 'DFE1ED2A-AA54-427F-9045-66808EC84424_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{DFE1ED2A-AA54-427F-9045-66808EC84424}', 'stripped_OID': 'DFE1ED2A-AA54-427F-9045-66808EC84424', 'login': '', 'broadcast_episode_title': 'Offrir. Chronique de et par Georges Juvet, pr?tre, responsable des aum?neries de la jeunessse', 'sequence': '1', 'broadcast_program_name': 'Minute oecum?nique', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'mertenpi', 'modified_on': '09.03.2023 13:36:11', 'physical_support_history': None, 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:01:21.120', 'work_duration_compl': 'Non', 'participants': [{'name': 'Juvet, Georges', 'function': 'Commentateur/trice', 'role': 'pr?tre, responsable des aum?neries de la jeunesse'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': ['croyance religieuse', 'catholicisme'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Commentaire'], 'recording_dates': ['__/04/1964 - __/04/1964 / Apr?s', '__/11/1964 - __/11/1964'], 'first_broadcast_dates': None}
The date for document with OID {DFE1ED2A-AA54-427F-9045-66808EC84424} was invalid (__/04/1964) - changed it to 01/04/1964
The date for document with OID {DFE1ED2A-AA54-427F-9045-66808EC84424} was invalid (__/11/1964) - changed it to 01/11/1964
The date for document with OID {DFE1ED2A-AA54-427F-9045-66808EC84424} was invalid (__/11/1964) - changed it to 01/11/1964
Did not find any date for doc with OID {586071B5-ED3B-467F-A8C0-8A2AB408FBBF}. Trying to use the recording date. doc_dict: {'alias': 'min_oecu', 'date_str': None, 'stt_filename': '586071B5-ED3B-467F-A8C0-8A2AB408FBBF_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{586071B5-ED3B-467F-A8C0-8A2AB408FBBF}', 'stripped_OID': '586071B5-ED3B-467F-A8C0-8A2AB408FBBF', 'login': '', 'broadcast_episode_title': "O? est l'Evangile? Chronique de et par Pierre Pascal, pr?tre", 'sequence': '1', 'broadcast_program_name': 'Minute oecum?nique', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'mertenpi', 'modified_on': '09.03.2023 11:29:05', 'physical_support_history': None, 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:01:08.352', 'work_duration_compl': 'Non', 'participants': [{'name': 'Pascal, Pierre', 'function': 'Commentateur/trice', 'role': 'pr?tre'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': ['croyance religieuse', 'catholicisme', 'Bible', '?vang?lisation'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Commentaire'], 'recording_dates': ['31/12/1981 - 31/12/1981 / Avant', '31/12/1974 - 31/12/1974 / Apr?s'], 'first_broadcast_dates': None}
The date for document with OID {29D4531A-FEF3-408F-87AA-0FBD4D7A0D11} was invalid (__/__/1986) - changed it to 01/01/1986
The date for document with OID {66D925E7-B2BA-4574-B96B-98B8A4222E80} was invalid (__/__/1986) - changed it to 01/01/1986
The date for document with OID {C5E0B8B3-0AE2-4B98-9405-3B07B3A5D471} was invalid (__/__/1975) - changed it to 01/01/1975
The date for document with OID {C5E0B8B3-0AE2-4B98-9405-3B07B3A5D471} was invalid (__/__/1981) - changed it to 01/01/1981
The date for document with OID {3F8AE7E7-AABD-47A2-B8A2-1B3071DB4678} was invalid (__/__/1980) - changed it to 01/01/1980
Did not find any date for doc with OID {D43E546E-4EAF-4CF5-AC37-DF866390E4E2}. Trying to use the recording date. doc_dict: {'alias': 'min_oecu', 'date_str': None, 'stt_filename': 'D43E546E-4EAF-4CF5-AC37-DF866390E4E2_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{D43E546E-4EAF-4CF5-AC37-DF866390E4E2}', 'stripped_OID': 'D43E546E-4EAF-4CF5-AC37-DF866390E4E2', 'login': '', 'broadcast_episode_title': 'Pictogrammes. Chronique de et par Andr? Babel, pr?tre', 'sequence': '1', 'broadcast_program_name': 'Minute oecum?nique', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'mertenpi', 'modified_on': '08.03.2023 17:46:37', 'physical_support_history': None, 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:01:30.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Babel, Andr?', 'function': 'Commentateur/trice', 'role': 'pr?tre'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': ['croyance religieuse', 'catholicisme', 'signalisation', 'gare ferroviaire', 'chemin de fer'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Commentaire'], 'recording_dates': ['__/08/1965 - __/08/1965'], 'first_broadcast_dates': None}
The date for document with OID {D43E546E-4EAF-4CF5-AC37-DF866390E4E2} was invalid (__/08/1965) - changed it to 01/08/1965
The date for document with OID {D43E546E-4EAF-4CF5-AC37-DF866390E4E2} was invalid (__/08/1965) - changed it to 01/08/1965
The date for document with OID {9C5233DA-F72A-441D-8BE1-B764B5536992} was invalid (__/__/1986) - changed it to 01/01/1986
Did not find any date for doc with OID {8D5DEA09-EB23-4C6B-A7A5-91BBE453253E}. Trying to use the recording date. doc_dict: {'alias': 'min_oecu', 'date_str': None, 'stt_filename': '8D5DEA09-EB23-4C6B-A7A5-91BBE453253E_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{8D5DEA09-EB23-4C6B-A7A5-91BBE453253E}', 'stripped_OID': '8D5DEA09-EB23-4C6B-A7A5-91BBE453253E', 'login': '', 'broadcast_episode_title': 'Plaintes. Chronique de et par Georges Juvet, pr?tre, responsable des aum?neries de la jeunessse', 'sequence': '1', 'broadcast_program_name': 'Minute oecum?nique', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'mertenpi', 'modified_on': '09.03.2023 09:48:41', 'physical_support_history': None, 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:01:17.184', 'work_duration_compl': 'Non', 'participants': [{'name': 'Juvet, Georges', 'function': 'Commentateur/trice', 'role': 'pr?tre, responsable des aum?neries de la jeunesse'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': ['croyance religieuse', 'catholicisme'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Commentaire'], 'recording_dates': ['__/04/1964 - __/04/1964 / Apr?s', '__/11/1964 - __/11/1964 / Avant'], 'first_broadcast_dates': None}
The date for document with OID {8D5DEA09-EB23-4C6B-A7A5-91BBE453253E} was invalid (__/04/1964) - changed it to 01/04/1964
The date for document with OID {8D5DEA09-EB23-4C6B-A7A5-91BBE453253E} was invalid (__/11/1964) - changed it to 01/11/1964
The date for document with OID {2542DB5F-96A5-4FF8-A425-F8904C5696BC} was invalid (__/__/1984) - changed it to 01/01/1984
The date for document with OID {73FF42A3-9595-4F6C-8B8B-F3054564B115} was invalid (__/__/1986) - changed it to 01/01/1986
The date for document with OID {16A2ED2F-2A46-4F1E-9C4B-475BD550A589} was invalid (__/__/1986) - changed it to 01/01/1986
The date for document with OID {A5899272-F6A1-4E55-A0D8-9EC2399BE8E6} was invalid (__/__/1984) - changed it to 01/01/1984
The date for document with OID {A5899272-F6A1-4E55-A0D8-9EC2399BE8E6} was invalid (__/__/1985) - changed it to 01/01/1985
The date for document with OID {89345056-2F85-4712-8F55-D6E898E449CF} was invalid (__/__/1987) - changed it to 01/01/1987
The date for document with OID {89345056-2F85-4712-8F55-D6E898E449CF} was invalid (__/__/1988) - changed it to 01/01/1988
The date for document with OID {B5EA5FAA-5990-4DF1-9BFC-4C628BAD61AB} was invalid (__/03/1987) - changed it to 01/03/1987
The date for document with OID {31977C4A-14AE-4774-ACB1-F72E975CE8D5} was invalid (__/__/1987) - changed it to 01/01/1987
The date for document with OID {31977C4A-14AE-4774-ACB1-F72E975CE8D5} was invalid (__/__/1988) - changed it to 01/01/1988

31it [02:00,  2.30s/it]

PROCESSING PROGRAM miroir_monde (32/47) - 4 files:

Starting extracting 852 documents for program miroir_monde
Did not find any date for doc with OID {CBC63EAF-62DC-4F4B-B8BE-17CEA54C8FA7}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': 'CBC63EAF-62DC-4F4B-B8BE-17CEA54C8FA7_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{CBC63EAF-62DC-4F4B-B8BE-17CEA54C8FA7}', 'stripped_OID': 'CBC63EAF-62DC-4F4B-B8BE-17CEA54C8FA7', 'login': '', 'broadcast_episode_title': "Guerre d'Alg�rie. D�cision du GPRA de ne pas se rendre � Paris : Commentaire de Pierre Moser sur le g�n�ral De Gaulle", 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'brucklbo', 'modified_on': '06.08.2020 10:51:35', 'physical_support_history': "Cote d'origine: MA 60.51 PL. C.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi�', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid�', 'assembly_status': 'Mont�', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:01:50.373', 'work_duration_compl': 'Non', 'participants': [{'name': 'Moser, Pierre', 'function': 'Commentateur/trice', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Alg�rie'], 'person_descriptors': ['Gaulle, Charles de'], 'thematical_descriptors': ["guerre d'Alg�rie", 'ind�pendantisme'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Radio-Gen�ve'], 'subdomains': ['Commentaire'], 'recording_dates': ['04/07/1960 - 04/07/1960'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {D75C0794-0E6D-42E4-BA94-F251060977CC}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': 'D75C0794-0E6D-42E4-BA94-F251060977CC_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{D75C0794-0E6D-42E4-BA94-F251060977CC}', 'stripped_OID': 'D75C0794-0E6D-42E4-BA94-F251060977CC', 'login': '', 'broadcast_episode_title': "Hommage � Aneurin Bevan, avec extrait de son discours pour la cr�ation de l'OTAN.", 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'farinana', 'modified_on': '26.12.2024 14:56:44', 'physical_support_history': "Cote d'origine: MA 60.51 PL. G.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi�', 'series_title': None, 'content_summary': "hommage � Aneurin Bevan, Ancien Secr�taire d'�tat � la Sant� et � la Protection sociale du Royaume-Uni\nHommage avec extrait de son discours pour la cr�ation de l'OTAN.\nAvec Jean�Paul DARMSTETER et Guy PLATIN", 'workflow_status': 'Valid�', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:02:51.311', 'work_duration_compl': 'Non', 'participants': [{'name': 'Veniz�los, Sophokl�s', 'function': 'Interview�/e', 'role': 'ancien premier ministre grec'}], 'geographical_descriptors': ['Grande-Bretagne'], 'person_descriptors': ['Bevan, Aneurin'], 'thematical_descriptors': ['politique'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': None, 'recording_dates': ['06/07/1960 - 06/07/1960'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {9D9542E1-F231-456A-AC0D-8803CB67552B}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': '9D9542E1-F231-456A-AC0D-8803CB67552B_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{9D9542E1-F231-456A-AC0D-8803CB67552B}', 'stripped_OID': '9D9542E1-F231-456A-AC0D-8803CB67552B', 'login': '', 'broadcast_episode_title': "Hommage � Aneurin Bevan, homme politique du parti travailliste britannique, lors d'une s�ance parlementaire", 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'saudouce', 'modified_on': '09.03.2023 09:11:43', 'physical_support_history': "Cote d'origine: A 902", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi�', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Portrait de Aneurin Bevan, leader du parti travailliste, respect� par le peuple (il �tait lui-m�me mineur). Connu pour son franc-parler et son engagement politique dans le socialisme, le parlement lui rend hommage. Voix de Bevan (court extrait).', 'workflow_status': 'Valid�', 'assembly_status': 'Mont�', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:04:36.267', 'work_duration_compl': 'Non', 'participants': [{'name': 'Bevan, Aneurin', 'function': "Auteur d'une d�claration", 'role': 'homme politique anglais, socialiste, ancien mineur'}, {'name': 'Romieux, Benjamin', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Pierre, Henri', 'function': 'Correspondant/e', 'role': 'collaborateur Radio-Lausanne � Londres'}], 'geographical_descriptors': ['Londres', 'Angleterre'], 'person_descriptors': ['Bevan, Aneurin'], 'thematical_descriptors': ['fonction politique', 'socialisme', 'parti politique', 'mineur (m�tier)'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Commentaire', 'D�claration'], 'recording_dates': ['07/07/1959 - 07/07/1959'], 'first_broadcast_dates': None}
Skipping document 13/852 with OID {E81D7146-01CE-4DEC-9AB1-2EC18C142F7A} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {9C852303-7BBA-4BB3-95A0-5EC58B471CF5}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': '9C852303-7BBA-4BB3-95A0-5EC58B471CF5_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{9C852303-7BBA-4BB3-95A0-5EC58B471CF5}', 'stripped_OID': '9C852303-7BBA-4BB3-95A0-5EC58B471CF5', 'login': '', 'broadcast_episode_title': 'Hommage � Jules Supervielle; po�te', 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'farinana', 'modified_on': '08.11.2024 15:25:33', 'physical_support_history': "Cote d'origine: MA 60.54 PL. A.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'A rechercher', 'series_title': None, 'content_summary': 'ill. sonore\nmort � dans domicile parisien � 76 ans\nEnfance en Urugay\nPo�te de la France malheureuse\n3.51 Int. archives\nCite ses oeuvres favorites\nAmour de l\'enfance, 6 enfants\nSe sent + Fran�ais\n6.45 Lit "Le cheveaux du temps"', 'workflow_status': 'Valid�', 'assembly_status': 'Brut', 'live': None, 'modulation_type': 'Mono', 'work_duration': '00:07:28.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Schlumberger, Evelyne', 'function': 'Intervieweur/euse', 'role': 'collaboratrice � Radio Lausannne'}, {'name': 'Supervielle, Jules', 'function': 'Commentateur/trice', 'role': None}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': ['hommage'], 'rights_usage_possibilities': None, 'radio_channels': None, 'subdomains': ['Interview'], 'recording_dates': ['12/05/1960 - 12/05/1960'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {1B7BA16C-41BB-4C2E-929D-43790AB8D288}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': '1B7BA16C-41BB-4C2E-929D-43790AB8D288_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{1B7BA16C-41BB-4C2E-929D-43790AB8D288}', 'stripped_OID': '1B7BA16C-41BB-4C2E-929D-43790AB8D288', 'login': '', 'broadcast_episode_title': 'Hommage au cardinal Georges Grente', 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'farinana', 'modified_on': '14.01.2025 16:01:40', 'physical_support_history': "Cote d'origine: MA 59.28 PL. D.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi�', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid�', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'St�r�o', 'work_duration': '00:03:21.577', 'work_duration_compl': 'Non', 'participants': [{'name': 'Dijon, Ren�', 'function': "Auteur d'une d�claration", 'role': None}], 'geographical_descriptors': None, 'person_descriptors': ['Grente, Georges'], 'thematical_descriptors': ['hommage'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': None, 'recording_dates': ['04/05/1959 - 04/05/1959'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {8E11D51E-D37A-42A9-AD0A-C5CD883C2078}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': '8E11D51E-D37A-42A9-AD0A-C5CD883C2078_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{8E11D51E-D37A-42A9-AD0A-C5CD883C2078}', 'stripped_OID': '8E11D51E-D37A-42A9-AD0A-C5CD883C2078', 'login': '', 'broadcast_episode_title': 'Hommage au duc Maurice de Broglie, physicien', 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'brucklbo', 'modified_on': '02.10.2020 09:33:46', 'physical_support_history': "Cote d'origine: MA 60.55 PL. D.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi�', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid�', 'assembly_status': 'Mont�', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:02:40.901', 'work_duration_compl': 'Non', 'participants': [{'name': 'Martin, Charles-No�l', 'function': 'Commentateur/trice', 'role': 'physicien nucl�aire fran�ais et vulgarisateur scientifique'}], 'geographical_descriptors': None, 'person_descriptors': ['Broglie, Maurice De'], 'thematical_descriptors': ['mort (biologie)', 'physique'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Commentaire'], 'recording_dates': ['16/07/1960 - 16/07/1960'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {7389C8B0-890C-4931-B6AA-CBBE04C4370A}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': '7389C8B0-890C-4931-B6AA-CBBE04C4370A_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{7389C8B0-890C-4931-B6AA-CBBE04C4370A}', 'stripped_OID': '7389C8B0-890C-4931-B6AA-CBBE04C4370A', 'login': '', 'broadcast_episode_title': "Hommage au pape Pie XII � l'occasion de sa mort", 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '09.03.2023 11:00:43', 'physical_support_history': "Cote d'origine: 14384", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi�', 'series_title': "Sauvegarde d'archives. Fribourg", 'content_summary': "Hommage de Mgr Charri�re, �v�que de Lausanne, Gen�ve et Fribourg : Pie XII unissait dans sa personne des dons exceptionnels. Grande sensibilit�. Fermet� intr�pide. Rappel de son attitude en 1917 � Munich, alors nonce en Allemagne au moment d'une r�volte. A pr�sent� la doctrine chr�tienne aux non croyants. A sauv� Rome de la destruction durant la seconde guerre mondiale. A encourag� la diffusion de la parole par les moyens modernes que sont la radio et la t�l�vision. Les catholiques suisses perdent un ami qui connaissait bien la Suisse.\nBiographie du pape avec documents sonores de sa nomination : Issu d'une haute famille de l'aristocratie romaine. N� le 2 mars 1876. 1894 : Ordonn� pr�tre. 1917 : Nonce apostolique en Allemagne. 1929 : Elev� au rang de cardinal et nomm� secr�taire d'Etat. 2 mars 1939 : Elu pape (Archives RSR). 12 mars 1939 : Intronisation (Archives RSR). \nHommage de l'abb� Haas : Pie XII prendra place parmi les tous grands papes. Dons exceptionnels. Il fut un homme de son temps. Diplomate et homme politique, patient et conciliateur. Autorit� et fermet� dans la doctrine. Il �tait un p�re sans compromission mais plein de la plus grande charit�. Il marqu� l'Eglise par sa puissante personnalit�. Il  a donn� une impulsion � l'action catholique. Il �tait avant tout pr�tre, un homme consacr� totalement � Dieu. Exemple extraordinaire, pi�t� vive � l'�gard de la Sainte Vierge. Il fut vraiment un homme de Dieu. Am�lioration de Radio Vatican. En automne 1946 il s'est adress� au peuple suisse (Archives RSR). D�claration de Pie XII sur la t�l�vision (Archives RSR). T�moignage de l'abb� Pierre recueilli par Paul Daniel en Haute Savoie.", 'workflow_status': 'Valid�', 'assembly_status': 'Mont�', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Romieux, Benjamin', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur de Radio-Lausanne'}, {'name': 'Charri�re, Fran�ois', 'function': "Auteur d'une d�claration", 'role': '�v�que de Lausanne, Gen�ve et Fribourg'}, {'name': 'Inconnu', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur de Radio-Lausanne'}, {'name': 'Pie XII [= Pacelli, Eugenio]', 'function': "Auteur d'une d�claration", 'role': 'pape (Archives RSR 02.03.1939, 12.03.1939)'}, {'name': 'Haas, Jacques', 'function': "Auteur d'une d�claration", 'role': 'abb�, collaborateur Radio-Lausanne'}, {'name': 'Pie XII [= Pacelli, Eugenio]', 'function': "Auteur d'une d�claration", 'role': 'pape (Archives RSR 1946 + non dat�)'}, {'name': 'Abb� Pierre', 'function': 'Interview�/e', 'role': 'fondateur des communaut�s Emma�s'}, {'name': 'Daniel, Paul', 'function': 'Intervieweur/euse', 'role': 'journaliste'}], 'geographical_descriptors': ['Vatican', 'Suisse'], 'person_descriptors': ['Pie XII [= Pacelli, Eugenio]'], 'thematical_descriptors': ['pape'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['D�claration', 'Interview'], 'recording_dates': ['09/10/1958 - 09/10/1958', '02/03/1939 - 02/03/1939', '12/03/1939 - 12/03/1939', '__/__/1946 - __/__/1946'], 'first_broadcast_dates': None}
The date for document with OID {7389C8B0-890C-4931-B6AA-CBBE04C4370A} was invalid (__/__/1946) - changed it to 01/01/1946
The date for document with OID {7389C8B0-890C-4931-B6AA-CBBE04C4370A} was invalid (__/__/1946) - changed it to 01/01/1946
Skipping document 29/852 with OID {160C782C-6B82-4BEB-A81A-DF23298345B2} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {398143D9-B0E2-47C3-88F1-ACB287779A6E}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': '398143D9-B0E2-47C3-88F1-ACB287779A6E_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{398143D9-B0E2-47C3-88F1-ACB287779A6E}', 'stripped_OID': '398143D9-B0E2-47C3-88F1-ACB287779A6E', 'login': '', 'broadcast_episode_title': 'Ind�pendance de Madagascar. Reportage de la journaliste Roseline Denis', 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '26.10.2020 13:39:39', 'physical_support_history': "Cote d'origine: MA 60.32 Pl. E", 'production_type': 'Production propre', 'recording_place': 'Tananarive', 'rights_notes': 'Memoriav\nD�tenteur : Cin�math�que fran�aise, Radiodiffusion fran�aise', 'rights_status': 'A rechercher', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid�', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'St�r�o', 'work_duration': '00:04:09.243', 'work_duration_compl': 'Non', 'participants': [{'name': 'Denis, Roseline', 'function': 'Commentateur/trice', 'role': 'correspondante � Tananarive pour la Radiodiffusion de Madagascar'}], 'geographical_descriptors': ['Madagascar', 'Ethiopie'], 'person_descriptors': None, 'thematical_descriptors': ['ind�pendantisme'], 'rights_usage_possibilities': ['FM'], 'radio_channels': ['Radio-Gen�ve'], 'subdomains': ['Commentaire', 'Interview'], 'recording_dates': ['27/06/1960 - 27/06/1960'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {90BAB0C6-8E1D-456D-9B4F-DADFB69E736F}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': '90BAB0C6-8E1D-456D-9B4F-DADFB69E736F_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{90BAB0C6-8E1D-456D-9B4F-DADFB69E736F}', 'stripped_OID': '90BAB0C6-8E1D-456D-9B4F-DADFB69E736F', 'login': '', 'broadcast_episode_title': "Ind�pendance du S�n�gal : Explications sur la d�cision du S�n�gal de se retirer de la F�d�ration du Mali. Interrogations sur l'avenir politique du Mali et du Soudan suite � l'�clatement de la F�d�ration", 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'saudouce', 'modified_on': '07.05.2022 07:45:17', 'physical_support_history': "Cote d'origine: A 1921", 'production_type': 'Production propre', 'recording_place': 'Studio Radio-Lausanne ; Paris ; Dakar', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi�', 'series_title': "Sauvegarde d'archives", 'content_summary': "L'ind�pendance congolaise se fait trop brusquement : Le S�n�gal et le Soudan sollicitent d'autres alliances et prennent l'habitude de faire appel � l'ONU pour r�gler les affaires courantes et en esp�rant que l'ONU leur apportera la solution miracle.", 'workflow_status': 'Valid�', 'assembly_status': 'Mont�', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:12:08.533', 'work_duration_compl': 'Non', 'participants': [{'name': 'Romieux, Benjamin', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Suler, Christian', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Rougemont, Andr�', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Lacouture, Jean', 'function': 'Commentateur/trice', 'role': 'journaliste'}, {'name': 'Lef�vre, Jean', 'function': 'Commentateur/trice', 'role': 'envoy� sp�cial � Dakar'}, {'name': 'Senghor, L�opold S�dar', 'function': "Auteur d'une d�claration", 'role': "chef de l'union progressiste s�n�galaise"}, {'name': 'Dia, Mamadou', 'function': 'Interview�/e', 'role': 'premier ministre du S�n�gal'}, {'name': 'Inconnu', 'function': 'Intervieweur/euse', 'role': 'journaliste'}], 'geographical_descriptors': ['Mali', 'S�n�gal', 'Soudan', 'France'], 'person_descriptors': ['Senghor, L�opold S�dar'], 'thematical_descriptors': ['autonomisme', 'ind�pendantisme', 'colonialisme', 'dictature'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['D�claration', 'Commentaire'], 'recording_dates': ['23/08/1960 - 23/08/1960'], 'first_broadcast_dates': None}

Did not find any date for doc with OID {1B80A675-183B-4E37-A8CF-012DB0D2C336}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': '1B80A675-183B-4E37-A8CF-012DB0D2C336_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{1B80A675-183B-4E37-A8CF-012DB0D2C336}', 'stripped_OID': '1B80A675-183B-4E37-A8CF-012DB0D2C336', 'login': '', 'broadcast_episode_title': "Visite de Benyoucef Ben Khedda, pr�sident du GPRA (Gouvernement Provisoire de la R�publique d'Alg�rie), �  Hassan II, roi du Maroc", 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '10.06.2022 09:47:35', 'physical_support_history': "Cote d'origine: A 4703 Pl. 4", 'production_type': 'Production propre', 'recording_place': 'Rabat', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi�', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Enjeux politiques de cette visite. Le Maroc constitue le seul lien diplomatique entre le gouvernement fran�ais et le GPRA.', 'workflow_status': 'Valid�', 'assembly_status': 'Mont�', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:04:29.733', 'work_duration_compl': 'Non', 'participants': [{'name': 'Lagni, Andr�', 'function': 'Commentateur/trice', 'role': 'correspondant Radio-Lausanne � Rabat'}], 'geographical_descriptors': ['Alg�rie', 'Maroc', 'Rabat'], 'person_descriptors': ['GPRA (Gouvernement Provisoire de la R�publique Alg�rienne)'], 'thematical_descriptors': ["guerre d'Alg�rie", 'd�colonisation', 'politique'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Premier programme'], 'subdomains': ['Commentaire'], 'recording_dates': ['02/01/1962 - 02/01/1962'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {9021CB6B-FDF0-42DA-8933-E86D3B475734}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': '9021CB6B-FDF0-42DA-8933-E86D3B475734_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{9021CB6B-FDF0-42DA-8933-E86D3B475734}', 'stripped_OID': '9021CB6B-FDF0-42DA-8933-E86D3B475734', 'login': '', 'broadcast_episode_title': 'Visite de Charles de Gaulle, g�n�ral fran�ais, � Dijon', 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'saudouce', 'modified_on': '09.03.2023 11:07:49', 'physical_support_history': "Cote d'origine: A 45", 'production_type': 'Production propre', 'recording_place': 'H�tel de ville et Place de la Lib�ration de Dijon', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi�', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Reportage de la visite, d�claration de de Gaulle adress�e au chanoine Kir, maire de Dijon, ainsi que discours � la population.', 'workflow_status': 'Valid�', 'assembly_status': 'Mont�', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:08:39.986', 'work_duration_compl': 'Non', 'participants': [{'name': 'Nordmann, Roger (homme de radio)', 'function': 'Commentateur/trice', 'role': 'collaborateur Radio-Lausanne � Dijon'}, {'name': 'Romieux, Benjamin', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Gaulle, Charles de', 'function': "Auteur d'une d�claration", 'role': "homme d'�tat et g�n�ral fran�ais"}], 'geographical_descriptors': ['France', 'Bourgogne', 'Dijon'], 'person_descriptors': ['Kir, F�lix'], 'thematical_descriptors': ['c�r�monie publique', 'chant patriotique'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Reportage', 'D�claration'], 'recording_dates': ['19/04/1959 - 19/04/1959'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {75CF0326-E5AC-43A6-AB09-A09A702A4441}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': '75CF0326-E5AC-43A6-AB09-A09A702A4441_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{75CF0326-E5AC-43A6-AB09-A09A702A4441}', 'stripped_OID': '75CF0326-E5AC-43A6-AB09-A09A702A4441', 'login': '', 'broadcast_episode_title': 'Visite de la Cit� interdite de P�kin par Fernand Gigon, reporter Radio-Lausanne', 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'comtesi', 'modified_on': '30.05.2022 05:16:31', 'physical_support_history': "cote d'origine: 6104", 'production_type': 'Production propre', 'recording_place': 'P�kin', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi�', 'series_title': "Sauvegarde d'archives. Jura", 'content_summary': "Description architecturale des habitations des anciens empereurs et de leur suite. La cit� est extr�mement belle et t�moigne du go�t fastueux des empereurs. Description de l'ext�rieur, de l'entr�e de la Cit�, des cours et de l'int�rieur du palais. Le gouvernement a reconstruit pratiquement tous les murs de la Cit� interdite.", 'workflow_status': 'Valid�', 'assembly_status': 'Mont�', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Gigon, Fernand', 'function': 'Commentateur/trice', 'role': 'Reporter Radio-Lausanne'}], 'geographical_descriptors': ['R�publique populaire de Chine'], 'person_descriptors': None, 'thematical_descriptors': ['architecture', 'sculpture', 'folklore', 'art sacr�', 'empereur', 'art d�coratif', 'dragon'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Commentaire'], 'recording_dates': ['01/01/1956 - 01/01/1956'], 'first_broadcast_dates': None}
Skipping document 826/852 with OID {AD432D4A-1211-4D3D-8BD7-804772995C52} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {6E733ECE-5C21-45EF-A4D9-5448819862EC}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': '6E733ECE-5C21-45EF-A4D9-5448819862EC_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{6E733ECE-5C21-45EF-A4D9-5448819862EC}', 'stripped_OID': '6E733ECE-5C21-45EF-A4D9-5448819862EC', 'login': '', 'broadcast_episode_title': "Visite du pape Paul VI � Gen�ve le 10 juin 1969 (2/8). Discours de Paul VI � l'ONU � l'occasion du 50e anniversaire de l'OIT. Version antenne", 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '09.03.2023 09:27:09', 'physical_support_history': "Cote d'origine: MA 69.8", 'production_type': 'Production propre', 'recording_place': 'Gen�ve (Organisation internationale du travail).', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi�', 'series_title': None, 'content_summary': 'Discours du pape Paul VI. (41:23) Remerciements de M. Meury, pr�sident de la conf�rence internationale du travail.', 'workflow_status': 'Valid�', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '01:31:22.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Paul VI (Pape)', 'function': "Auteur d'une d�claration", 'role': None}, {'name': 'Meury', 'function': "Auteur d'une d�claration", 'role': 'pr�sident de la conf�rence internationale du travail'}, {'name': 'Inconnu', 'function': 'Commentateur/trice', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Suisse', 'Gen�ve (ville)'], 'person_descriptors': ['Paul VI (Pape)', 'OIT', 'ONU'], 'thematical_descriptors': ['pape', 'oecum�nisme', 'catholicisme', 'solidarit�', 'paix', 'travail (activit�)', 'institution religieuse'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Premier programme'], 'subdomains': ['Reportage', 'Interview'], 'recording_dates': ['10/06/1969 - 10/06/1969'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {10F5F4E2-17CC-49A3-8959-08EDDF1281F2}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': '10F5F4E2-17CC-49A3-8959-08EDDF1281F2_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{10F5F4E2-17CC-49A3-8959-08EDDF1281F2}', 'stripped_OID': '10F5F4E2-17CC-49A3-8959-08EDDF1281F2', 'login': '', 'broadcast_episode_title': "Visite du pape Paul VI � Gen�ve le 10 juin 1969 (4/8). A l'H�tel de ville de Gen�ve et Au Conseil oecum�nique des �glises (1/2). Version antenne", 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '07.06.2022 18:39:33', 'physical_support_history': "Cote d'origine: MA 69.10", 'production_type': 'Production propre', 'recording_place': "Gen�ve (H�tel de ville, salle du Conseil d'Etat). Grand Saconnex (Conseil oecum�nique des �glises).", 'rights_notes': 'Memoriav', 'rights_status': 'A rechercher', 'series_title': None, 'content_summary': "1. A l'H�tel de ville de Gen�ve, salle du Conseil d'Etat. (3:55-32:29) Discours de Ludwig von Moos, pr�sident de la Conf�d�ration. (10:47) Discours de Gilbert Duboule, conseiller d'Etat genevois. (16:09-22:34) Discours du pape Paul VI. Commentaires, sons d'ambiance et musique. (47:00) Commentaire de Jacques Bofford � la salle jaune de l'H�tel de ville. (54:48) Visite du souverain pontife au Conseil oecum�nique des �glises. (56:14) Quelques manifestants irlandais ont d�fil�. (57:00) Le pasteur Philippe Gill�ron parle d'oecum�nisme.", 'workflow_status': 'Valid�', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '01:23:30.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Moos, Ludwig von', 'function': "Auteur d'une d�claration", 'role': 'pr�sident de la Conf�d�ration'}, {'name': 'Duboule, Gilbert', 'function': "Auteur d'une d�claration", 'role': "conseiller d'Etat genevois, pr�sident du Grand conseil"}, {'name': 'Paul VI (Pape)', 'function': "Auteur d'une d�claration", 'role': None}, {'name': 'Gilli�ron, Philippe', 'function': 'Interview�/e', 'role': 'pasteur'}, {'name': 'Bofford, Jacques', 'function': 'Reporter', 'role': 'collaborateur RSR'}, {'name': 'Martel, Jean', 'function': 'Reporter', 'role': 'collaborateur RSR'}, {'name': 'Livio, Antoine', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Gen�ve (ville)', 'Suisse'], 'person_descriptors': ['Paul VI (Pape)'], 'thematical_descriptors': ['catholicisme', 'pape', 'oecum�nisme'], 'rights_usage_possibilities': None, 'radio_channels': ['Premier programme'], 'subdomains': ['Reportage', 'D�claration'], 'recording_dates': ['10/06/1969 - 10/06/1969'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {674E4310-0485-4FAD-83EA-D84848CC6AA4}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': '674E4310-0485-4FAD-83EA-D84848CC6AA4_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{674E4310-0485-4FAD-83EA-D84848CC6AA4}', 'stripped_OID': '674E4310-0485-4FAD-83EA-D84848CC6AA4', 'login': '', 'broadcast_episode_title': 'Visite du pape Paul VI � Gen�ve le 10 juin 1969 (5/8). Au Conseil oecum�nique des �glises (2/2). Version antenne', 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '12.03.2023 00:06:31', 'physical_support_history': "Cote d'origine: MA 69.11", 'production_type': 'Production propre', 'recording_place': 'Garand Saconnex (Conseil oecum�nique des �glises).', 'rights_notes': 'Memoriav', 'rights_status': 'A rechercher', 'series_title': None, 'content_summary': 'Bande 5. Allocution du pasteur Eugene Carson Blake. (7:50) Allocution de paul VI. (22;15) Pri�re par MM. Thomas, pr�sident du COE. Pri�re par S.E. le cardinal Jean Willebrands. Litanies par le M�tropolite de Chac�doine Meliton. (22:20) Pri�re de Pauline Webb en anglais, avec traduction. Cantique "B�nissons Dieu l\'Eternel" par l\'assembl�e. (31:35)Reprise des commentaires avec Jean Martel, le pasteur Philippe Gilli�ron et du p�re dominicain Ren� Beaup�re, directeur du centre Saint Ir�n�e de Lyon. Discours de Paul VI. Discours du pasteur Edmond Sauty. Reprise des commentairess. Bulletin d\'informations de l\'ATS.', 'workflow_status': 'Valid�', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '01:14:57.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Blake, Eugene Carson', 'function': "Auteur d'une d�claration", 'role': 'secr�taire g�n�ral du Conseil �cum�nique des �glises (COE) de 1966 � 1974'}, {'name': 'Paul VI (Pape)', 'function': "Auteur d'une d�claration", 'role': None}, {'name': 'Martel, Jean', 'function': 'Reporter', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Gen�ve (ville)', 'Suisse'], 'person_descriptors': ['COE (Conseil O�cum�nique des Eglises)'], 'thematical_descriptors': ['oecum�nisme', 'catholicisme', 'pape'], 'rights_usage_possibilities': None, 'radio_channels': ['Premier programme'], 'subdomains': ['Reportage'], 'recording_dates': ['10/06/1969 - 10/06/1969'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {B98FA96F-54C4-494C-9449-DE7BF0034EAE}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': 'B98FA96F-54C4-494C-9449-DE7BF0034EAE_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{B98FA96F-54C4-494C-9449-DE7BF0034EAE}', 'stripped_OID': 'B98FA96F-54C4-494C-9449-DE7BF0034EAE', 'login': '', 'broadcast_episode_title': 'Visite du pape Paul VI � Gen�ve le 10 juin 1969 (6/8). Messe pontificale au Parc La Grange c�l�br�e par le pape Paul VI (1/2). Version antenne', 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'freudial', 'modified_on': '08.03.2023 17:45:45', 'physical_support_history': "Cote d'origine: MA 69.12", 'production_type': 'Production propre', 'recording_place': 'Gen�ve (Parc La Grange)', 'rights_notes': 'Memoriav', 'rights_status': 'A rechercher', 'series_title': None, 'content_summary': 'Commentaires. (20:00) Arriv�e au parc La Grange avec J. Bofford et Mgr Bouvier. (60:00) Messe pontificale au Parc de la Grange (1�re partie) c�l�br�e par le pape Paul VI. Entr�e - Gloria - Oraison - Lecture - Hom�lie - Credo - Pri�re universelle - Offrandes - Pri�re eucharistique - Pater - Communion - B�n�diction finale.', 'workflow_status': 'Valid�', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '01:26:18.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Roch, Fran�ois-Achille', 'function': "Auteur d'une d�claration", 'role': 'collaborateur RSR'}, {'name': 'Bofford, Jacques', 'function': 'Reporter', 'role': 'collaborateur RSR'}, {'name': 'Bouvier, Paul', 'function': 'Interview�/e', 'role': 'Mgr'}, {'name': 'Paul VI (Pape)', 'function': "Auteur d'une d�claration", 'role': 'pape'}], 'geographical_descriptors': ['Suisse', 'Gen�ve (ville)'], 'person_descriptors': ['Paul VI (Pape)', 'OIT', 'ONU'], 'thematical_descriptors': ['pape', 'catholicisme', 'oecum�nisme', 'messe (c�r�monie)'], 'rights_usage_possibilities': None, 'radio_channels': ['Premier programme'], 'subdomains': ['Reportage', 'D�claration'], 'recording_dates': ['10/06/1969 - 10/06/1969'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {A038926F-A0DF-4419-8B50-F3531728DDC9}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': 'A038926F-A0DF-4419-8B50-F3531728DDC9_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{A038926F-A0DF-4419-8B50-F3531728DDC9}', 'stripped_OID': 'A038926F-A0DF-4419-8B50-F3531728DDC9', 'login': '', 'broadcast_episode_title': 'Visite du pape Paul VI � Gen�ve le 10 juin 1969 (7/8). Messe pontificale (2/2), visite au Bureau international du travail. Version antenne', 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '24.10.2017 16:07:36', 'physical_support_history': "Cote d'origine: MA 69.13", 'production_type': 'Production propre', 'recording_place': 'Gen�ve (Parc La Grange)', 'rights_notes': 'Memoriav', 'rights_status': 'A rechercher', 'series_title': None, 'content_summary': "Fin de la Messe pontificale au Parc La Grange. Musique. Fran�ois-Achille Roch + musique. Jean Martel. Discours du pape Paul VI (avec traduction). Discours d'Ha�l� S�lassi� 1er (avec traduction). Reprise des commentaires + musique. D�part et commentaires.", 'workflow_status': 'Valid�', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '01:20:09.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Paul VI (Pape)', 'function': "Auteur d'une d�claration", 'role': None}, {'name': 'Roch, Fran�ois-Achille', 'function': 'Reporter', 'role': 'collaborateur RSR'}, {'name': 'Martel, Jean', 'function': 'Reporter', 'role': 'collaborateur RSR'}, {'name': 'Selassi�, Hail�', 'function': "Auteur d'une d�claration", 'role': "empereur d'Ethiopie"}], 'geographical_descriptors': ['Gen�ve (ville)', 'Suisse'], 'person_descriptors': ['Selassi�, Hail�', 'Paul VI (Pape)'], 'thematical_descriptors': ['messe (c�r�monie)', 'travail (activit�)'], 'rights_usage_possibilities': None, 'radio_channels': ['Premier programme'], 'subdomains': ['Reportage', 'D�claration'], 'recording_dates': ['10/06/1969 - 10/06/1969'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {2C780829-8C55-4826-9207-37742534C98A}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': '2C780829-8C55-4826-9207-37742534C98A_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{2C780829-8C55-4826-9207-37742534C98A}', 'stripped_OID': '2C780829-8C55-4826-9207-37742534C98A', 'login': '', 'broadcast_episode_title': 'Visite du pape Paul VI � Gen�ve le 10 juin 1969 (8/8). D�part de Cointrin. Version antenne', 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '24.05.2022 08:24:14', 'physical_support_history': "Cote d'origine: MA 69.14", 'production_type': 'Production propre', 'recording_place': 'Gen�ve (a�roport)', 'rights_notes': 'Memoriav', 'rights_status': 'A rechercher', 'series_title': None, 'content_summary': 'Commentaires et musique. (13:38) Reporters: Jacques Bofford et Alex D�cotte. Discours du pape Paul VI. Commentaires par Jacques Bofford et Mgr Paul Bouvier.', 'workflow_status': 'Valid�', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:39:53.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Livio, Antoine', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur RSR'}, {'name': 'Paul VI (Pape)', 'function': "Auteur d'une d�claration", 'role': None}, {'name': 'Bofford, Jacques', 'function': 'Reporter', 'role': 'collaborateur RSR'}, {'name': 'D�cotte, Alex', 'function': "Auteur d'une d�claration", 'role': 'collaborateur RSR'}, {'name': 'Bouvier, Paul', 'function': "Auteur d'une d�claration", 'role': 'Mgr'}], 'geographical_descriptors': ['Gen�ve (ville)'], 'person_descriptors': ['Paul VI (Pape)'], 'thematical_descriptors': ['pape'], 'rights_usage_possibilities': None, 'radio_channels': ['Premier programme'], 'subdomains': ['Reportage', 'D�claration'], 'recording_dates': ['10/06/1969 - 10/06/1969'], 'first_broadcast_dates': None}

miroir_monde - returning 208 documents, 791 were skipped due to missing necessary info.

Starting extracting 998 documents for program miroir_monde
Skipping document 2/998 with OID {A9CDAAE8-BFA3-4136-80DA-A5690A482AAA} because it's missing its XML file!! (stt exists: False)
Skipping document 13/998 with OID {8D7FE6FD-DBBC-4B5C-8DBD-A89AD7C41948} because it's missing its XML file!! (stt exists: False)
Skipping document 14/998 with OID {C53AB09D-B6AD-43A0-97A0-5197AE8B4CE5} because it's missing its XML file!! (stt exists: False)
Skipping document 16/998 with OID {1F868277-9CF7-4E31-9735-FC7657DF1014} because it's missing its XML file!! (stt exists: False)
Skipping document 17/998 with OID {DAFFB5A3-139F-4B47-AC6E-05D960411200} because it's missing its XML file!! (stt exists: False)
Skipping document 18/998 with OID {C2D4C291-5AAF-4FEC-8596-0661018A94F1} because it's missing its XML file!! (stt exists: False)
Skipping document 19/998 with OID {08C4D8F6-67EC-4191-B92D-09F35541AB43} because it's missing its XML file!! (stt exists: False)
Skipping document 20/998 with OID {4D5EDF0A-1384-40B4-AFE8-0F2713919078} because it's missing its XML file!! (stt exists: False)
Skipping document 22/998 with OID {2B9E4142-3D1C-4051-8650-17B028B295DF} because it's missing its XML file!! (stt exists: False)
Skipping document 24/998 with OID {16424BA0-8C71-494C-830A-2044735AD5DD} because it's missing its XML file!! (stt exists: False)
Skipping document 25/998 with OID {C4F12C5C-4D3D-48B2-A123-34835CBF6733} because it's missing its XML file!! (stt exists: False)
Skipping document 26/998 with OID {61D57A78-37BD-4C9C-ADD5-3AF827267620} because it's missing its XML file!! (stt exists: False)
Skipping document 27/998 with OID {F7E4ED7D-0B50-461F-94C4-DA02CA346D05} because it's missing its XML file!! (stt exists: False)
Skipping document 28/998 with OID {3DA708B8-7EE8-4FC9-9FF9-CFCD5332827C} because it's missing its XML file!! (stt exists: False)
Skipping document 29/998 with OID {8A45A848-A82F-4513-8396-90D77AB84345} because it's missing its XML file!! (stt exists: False)
Skipping document 31/998 with OID {5DE97E48-3D44-4D52-A9A6-9AD09511940C} because it's missing its XML file!! (stt exists: False)
Skipping document 32/998 with OID {04D3F0A8-4B42-44DA-A343-D34BCD0460C6} because it's missing its XML file!! (stt exists: False)
Skipping document 33/998 with OID {9C1E2C1A-5F97-4AD6-8408-B402BD0E9499} because it's missing its XML file!! (stt exists: False)
Skipping document 34/998 with OID {437F8333-D2DE-410E-A421-0B515A007A0D} because it's missing its XML file!! (stt exists: False)
Skipping document 35/998 with OID {7B1D95E9-5F58-461B-9915-3262A2FA847F} because it's missing its XML file!! (stt exists: False)
Skipping document 36/998 with OID {1FADF92D-2596-4B14-AEAB-5D0CF1B7A5C0} because it's missing its XML file!! (stt exists: False)
Skipping document 41/998 with OID {41A5E5BE-A63F-4750-8299-75EBC98469CF} because it's missing its XML file!! (stt exists: False)
Skipping document 42/998 with OID {29DDE3B3-BAFB-4632-B2F0-7CABB69F58EC} because it's missing its XML file!! (stt exists: False)
Skipping document 43/998 with OID {6F25660E-1D10-4C8C-8493-22961C48F8CA} because it's missing its XML file!! (stt exists: False)
Skipping document 44/998 with OID {0989297B-1CE1-4752-94F6-9B33B6A5E04A} because it's missing its XML file!! (stt exists: False)
Skipping document 47/998 with OID {4EBE7C94-C8DD-420A-91C0-169EC12A6163} because it's missing its XML file!! (stt exists: False)
Skipping document 51/998 with OID {DF8C1A96-3A8A-4915-8786-1E12FD808FA2} because it's missing its XML file!! (stt exists: False)
Skipping document 53/998 with OID {A76535FC-DA16-44A6-8CEC-9C7AFB487A6B} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {8D7DBDD2-02DB-4B86-B1E1-71AD2B692828}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': '8D7DBDD2-02DB-4B86-B1E1-71AD2B692828_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{8D7DBDD2-02DB-4B86-B1E1-71AD2B692828}', 'stripped_OID': '8D7DBDD2-02DB-4B86-B1E1-71AD2B692828', 'login': '', 'broadcast_episode_title': "1. 51i�me congr�s national du parti socialiste fran�ais : Interview de Guy Mollet, secr�taire g�n�ral de la SFIO. - 2. Commentaire sur la Conf�rence de Gen�ve � l'ONU en vue de la conf�rence au sommet visant � r�guler le statut de Berlin.", 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'maffliis', 'modified_on': '09.03.2023 09:29:59', 'physical_support_history': "Cote d'origine: A 961", 'production_type': 'Production propre', 'recording_place': 'Paris ; Studio Radio-Lausanne ; Gen�ve � la Maison de la Presse', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi�', 'series_title': "Sauvegarde d'archives", 'content_summary': '1. Malgr� les divergences au sein de la gauche fran�aise, Guy Mollet cherche � trouver un front commun concernant la politique sociale et �conomique fran�aise.', 'workflow_status': 'Valid�', 'assembly_status': 'Mont�', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:08:56.747', 'work_duration_compl': 'Non', 'participants': [{'name': 'Mollet, Guy', 'function': 'Interview�/e', 'role': 'homme politique fran�ais'}, {'name': 'Mairet, Claude (journaliste)', 'function': 'Intervieweur/euse', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Romieux, Benjamin', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Ferrier, Jacques', 'function': 'Interview�/e', 'role': "correspondant � Gen�ve � l'ONU"}, {'name': 'Darmsteter, Jean-Paul', 'function': 'Intervieweur/euse', 'role': 'collaborateur Radio-Lausanne'}], 'geographical_descriptors': ['France', 'Berlin'], 'person_descriptors': ['Gaulle, Charles de', 'ONU', 'Conf�rence de Gen�ve 1959'], 'thematical_descriptors': ['politique', 'parti politique', "guerre d'Alg�rie", 'socialisme', 'relations internationales', 'r�union internationale'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Interview'], 'recording_dates': ['13/07/1959 - 13/07/1959'], 'first_broadcast_dates': None}
Skipping document 66/998 with OID {5E87EE8A-436C-40E3-B43A-3ABBA7814E73} because it's missing its XML file!! (stt exists: False)
Skipping document 67/998 with OID {6B1FCA70-65DA-4001-9F9C-41F461A33703} because it's missing its XML file!! (stt exists: False)
Skipping document 117/998 with OID {862BB6CF-42E9-4C11-A9CE-74981B79D27B} because it's missing its XML file!! (stt exists: False)
Skipping document 223/998 with OID {50AD786B-FE26-4FD1-8EBD-67E6428AB854} because it's missing its XML file!! (stt exists: False)
Skipping document 304/998 with OID {08A57A73-758C-4313-95C7-EF4BDDBF1ADC} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {F4A3F4F2-B572-47CA-A83C-3C553BD33B72}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': 'F4A3F4F2-B572-47CA-A83C-3C553BD33B72_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{F4A3F4F2-B572-47CA-A83C-3C553BD33B72}', 'stripped_OID': 'F4A3F4F2-B572-47CA-A83C-3C553BD33B72', 'login': '', 'broadcast_episode_title': "1. Actualit�s internationales. - 2. D�lib�ration au proc�s des conjur�s du Mont Faron contre le g�n�ral de Gaulle : Interview de Fr�d�ric Pottecher, journaliste. - 3. Affaires europ�ennes. - 4. D�bat � la commission s�natoriale des Etats-Unis sur la guerre du Vietnam. - 5. Fin du congr�s annuel de la commission nationale suisse pour l'Unesco : Interview de Madame Bugnon, cheffe de la section jeunesse pour la commission. - 6. Sports", 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'freudial', 'modified_on': '06.09.2023 13:34:11', 'physical_support_history': "Cote d'origine: A 3532", 'production_type': 'Production propre', 'recording_place': 'Lausanne (Studio RSR). Paris. New York.', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi�', 'series_title': "Sauvegarde d'archives", 'content_summary': "2. � 07.06 : Analyse du verdict et de l'affaire. - 3. � 14.30 : Pascal Couchepin, alors collaborateur RSR, commente les changements politiques en Italie, Belgique et Vietnam. 4. � 17.27 : Th�o Loir commente la position de Dean Rusk, secr�taire d'Etat am�ricain, les divergences entre s�nateurs, la r�action de la presse et de l'opinion publique am�ricaine. - 5. � 21.00 : Daniel Favre tire le bilan de ces s�ances de travail. �  22.00 : Madame Bugnon commente le manque de soutien financier de l'Etat � l'�gard des associations extra-scolaires. - 6. � 25.54 : Commentaires de Daniel Teisser. M�t�o.", 'workflow_status': 'Valid�', 'assembly_status': 'Mont�', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:27:33.547', 'work_duration_compl': 'Non', 'participants': [{'name': 'Curchod, Blaise', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur RSR'}, {'name': 'Pottecher, Fr�d�ric', 'function': 'Interview�/e', 'role': 'chroniqueur judiciaire fran�ais'}, {'name': 'Zbinden, Louis-Albert', 'function': 'Intervieweur/euse', 'role': 'correspondant RSR � Paris'}, {'name': 'Loir, Th�o', 'function': 'Commentateur/trice', 'role': 'correspondant RSR � New York'}, {'name': 'Couchepin, Pascal', 'function': 'Commentateur/trice', 'role': 'collaborateur/trice RSR'}, {'name': 'Favre, Daniel', 'function': 'Commentateur/trice', 'role': 'collaborateur RSR'}, {'name': 'Bugnon, (Madame)', 'function': 'Interview�/e', 'role': 'cheffe de la section jeunesse pour la commission'}, {'name': 'Teisser, Daniel [orthographe ?]', 'function': 'Commentateur/trice', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Etats-Unis', 'Vietnam', 'Suisse'], 'person_descriptors': ['Gaulle, Charles de', 'UNESCO'], 'thematical_descriptors': ['proc�s', 'guerre du Vietnam', '�ducation', 'subvention', "politique de l'�ducation", 'sport'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Premier programme'], 'subdomains': ['Commentaire', 'Interview'], 'recording_dates': ['20/02/1966 - 20/02/1966'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {E090727D-E6BA-4295-BB17-27DC9BCCEF56}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': 'E090727D-E6BA-4295-BB17-27DC9BCCEF56_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{E090727D-E6BA-4295-BB17-27DC9BCCEF56}', 'stripped_OID': 'E090727D-E6BA-4295-BB17-27DC9BCCEF56', 'login': '', 'broadcast_episode_title': "1. Actualit�s internationales. - 2. Enqu�te sur l'assassinat du g�n�ral portugais Delgado. - 3. D�but du proc�s de l'attentat terroriste du Mont-Faron contre le g�n�ral de Gaulle - Interview de Lehmann ex-l�gionnaire suisse [archive 1965]. - 4. Verdict dans le proc�s des �crivains russes Siniavski-Daniel. - 5. L'action am�ricaine dans le sud-Vietnam. - 6. Interview d'Edouard Delby [orthographe ?], sp�cialiste de l'Am�rique latine : A propos de la", 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '20.05.2022 10:54:41', 'physical_support_history': "Cote d'origine: A 3570", 'production_type': 'Production propre', 'recording_place': 'Lausanne (Studio RSR). Moscou. Paris. Neuch�tel', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi�', 'series_title': "Sauvegarde d'archives", 'content_summary': "2. � 05.25 : Commentaires de Blaise Curchod sur les derniers �l�ments de l'enqu�te. - 3. � 08.13 : Rappel de cet attentat manqu� par Blaise Curchod. � 09.16 : Interview de Lehmann, ex-l�gionnaire suisse impliqu� dans cette affaire, raconte le d�roulement de l'attentat. - 4. � 11.54 : Rappel des �v�nements. � 12.25 : Interview d'Henri Pierre, correspondant RSR � Moscou qui commente la condamnation des peines de 7 et 5 ans pour les �crivains, la place des intellectuels dans le syst�me sovi�tique, la confidentialit� de ce proc�s. - 5. � 16.10 : Le renforcement militaire et l'aide �conomique am�ricaine pr�vue par la conf�rence d'Honolulu au Vietnam. - 6. � 19.19 : L'origine de la crise �conomique et sociale qui soul�ve St-Domingue, la gr�ve qui paralyse l'�conomie du pays, l'action des leaders de droite, la prochaine campagne pour les �lections pr�sidentielles. - 7. � 24.13 : La question de la semaine de 44 heures. � 25.05 : Projet de loi pour assurer la protection des cr�tes du Jura; � 25.45 : Andr� Rougemeont commente la d�cision des d�put�s neuch�telois qui ont vot� un contre-projet. M�t�o.", 'workflow_status': 'Valid�', 'assembly_status': 'Mont�', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:30:00.832', 'work_duration_compl': 'Non', 'participants': [{'name': 'Margot, Michel', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur RSR'}, {'name': 'Curchod, Blaise', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur RSR'}, {'name': 'Lehmann (Monsieur)', 'function': 'Interview�/e', 'role': 'ex-l�gionnaire suisse'}, {'name': 'Goretta, Jean-Pierre', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}, {'name': 'Sulser, Christian', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}, {'name': 'Pierre, Henri', 'function': 'Interview�/e', 'role': 'collaborateur RSR � Moscou'}, {'name': 'Delby, Edouard (orthographe incertaine)', 'function': 'Interview�/e', 'role': "sp�cialiste de l'Am�rique du Sud"}, {'name': 'Mairet, Claude (journaliste)', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR � Paris'}, {'name': 'Daniel, Paul', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur RSR'}, {'name': 'Grosjean, Carlos', 'function': 'Interview�/e', 'role': "conseiller d'Etat neuch�telois"}, {'name': 'Rougemont, Andr�', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['URSS', 'Etats-Unis', 'Vietnam', 'Saint-Domingue', 'Suisse', 'Jura (r�gion)'], 'person_descriptors': ['Delgado'], 'thematical_descriptors': ['proc�s', 'enqu�te judiciaire', 'attentat', '�crivain', 'guerre du Vietnam', 'gr�ve', 'crise �conomique', 'crise politique', 'projet'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Premier programme'], 'subdomains': ['Commentaire', 'Interview'], 'recording_dates': ['14/02/1966 - 14/02/1966'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {253E07C7-3C0C-45B0-8F39-1165A164121F}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': '253E07C7-3C0C-45B0-8F39-1165A164121F_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{253E07C7-3C0C-45B0-8F39-1165A164121F}', 'stripped_OID': '253E07C7-3C0C-45B0-8F39-1165A164121F', 'login': '', 'broadcast_episode_title': "1. Ajournement de la Conf�rence de Gen�ve apr�s six semaines de n�gociations. Interview de Henry Schavoir (orthographe incertaine), journaliste. 2. Visite priv�e d'Istvan Dobi, pr�sident hongrois � Aleksander Zawadski, pr�sident polonais. - 3. R�actions internationales � l'ajournement de la Conf�rence de Gen�ve. Interview de Maurice Couve de Murville, ministre fran�ais des affaires �trang�res.", 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'comtesi', 'modified_on': '10.06.2022 17:27:56', 'physical_support_history': "Cote d'origine: A 1591", 'production_type': 'Production propre', 'recording_place': 'Gen�ve, Vienne, Paris, Washington', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi�', 'series_title': "Sauvegarde d'archives", 'content_summary': '1. Commentaires pessimistes de Gen�ve et Paris. R�actions internationales.', 'workflow_status': 'Valid�', 'assembly_status': 'Mont�', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:33:30.880', 'work_duration_compl': 'Non', 'participants': [{'name': 'Ferrier, Jacques', 'function': 'Commentateur/trice', 'role': 'correspondant Radio-Lausanne � Gen�ve'}, {'name': 'Moser, Pierre', 'function': 'Commentateur/trice', 'role': 'correspondant Radio-Lausanne � Gen�ve'}, {'name': 'Schavoir, Henry (orthographe incertaine)', 'function': 'Interview�/e', 'role': 'journaliste DPA (Deutsche Press Agenthur)'}, {'name': 'Balvanyi, Jean', 'function': 'Commentateur/trice', 'role': 'correspondant Radio-Lausanne � Vienne'}, {'name': 'Moulin, Jean-Pierre', 'function': 'Commentateur/trice', 'role': 'correspondant Radio-Lausanne � Paris'}, {'name': 'Pierre, Henri', 'function': 'Commentateur/trice', 'role': 'correspondant Radio-Lausanne � Washington'}, {'name': 'Couve de Murville, Maurice', 'function': 'Interview�/e', 'role': 'ministre fran�ais des Affaires �trang�res'}, {'name': 'Moser, Pierre', 'function': 'Intervieweur/euse', 'role': 'correspondant Radio-Lausanne � Paris'}, {'name': 'Rougemont, Andr�', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur Radio-Lausanne'}], 'geographical_descriptors': ['Etats-Unis', 'Angleterre', 'URSS', 'France'], 'person_descriptors': None, 'thematical_descriptors': ['r�union internationale', 'politique internationale', 'relations internationales', 'n�gociation', 'guerre froide'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Premier programme'], 'subdomains': ['Commentaire', 'Interview'], 'recording_dates': ['20/06/1958 - 20/06/1958'], 'first_broadcast_dates': None}

miroir_monde - returning 933 documents, 65 were skipped due to missing necessary info.

Starting extracting 999 documents for program miroir_monde
Did not find any date for doc with OID {A2F03FCC-C3B9-44A3-BFF0-8231CCCD1364}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': 'A2F03FCC-C3B9-44A3-BFF0-8231CCCD1364_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{A2F03FCC-C3B9-44A3-BFF0-8231CCCD1364}', 'stripped_OID': 'A2F03FCC-C3B9-44A3-BFF0-8231CCCD1364', 'login': '', 'broadcast_episode_title': "1. La succession � John Fitzgerald Kennedy et la nouvelle pr�sidence de Lyndon Johnson. - 2.  L'enqu�te sur le double assassinat de Dallas : John Fitzgerald Kennedy et Lee Harvey Oswald. - 3. Interview de Karl Studer, professeur texan d'origine suisse. - 4. Analyse de Jaques Matthey-Doret sur la continuit� politique de Lyndon Johnson. - 5. Commentaire d'Albert Zbinden sur les relations entre le g�n�ral de Gaulle et Lyndon Johnson. - 6. Les Am�ric", 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'pittetma', 'modified_on': '26.05.2022 03:08:36', 'physical_support_history': "Cote d'origine: A 7901", 'production_type': 'Production propre', 'recording_place': 'Lausanne (Studio). Dallas. Paris.', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi�', 'series_title': "Sauvegarde d'archives", 'content_summary': "1. Le nouveau gouvernement de Lyndon Johnson et les interrogations sur la politique qu'il va mener. - 2. � 02.18 : La police de Dallas et le Minist�re de la \nJustice en d�saccord sur la culpabilit� unique de Lee Harvey Oswald. - 3. � 06.50 : La composition du peuple texan, la s�gr�gation, pas de mafia au Texas, son opinion sur le meurtrier de L-H. Oswald, Jack Ruby, la mentalit� texanne. - 4. � 11.59 : La conjugaison politique des prochaines �lections pr�sidentielles et de l'assassinat de L-H. Oswald. - 5. � 17.08 : Comment parer en France � une �ventuelle disparition du pr�sident de Gaulle, la question de la vice-pr�sidence en France. - 6. � 20.09 : Nouvelle donne g�opolitique : le Cambodge renonce � l'aide am�ricaine et signe un accord a�rien avec la Chine.\n\nAssassinat JF Kennedy. Doutes sur la culpabibilit� de Oswald. 3 enqu�tes\nInt. Studer sur la soci�t� du Texas\nContinuit� de Lindon Johnson\nInvitation de Johnson � de Gaulle\nGuerre sud-est asiatique\nInt. Lacouture sur Cambodge et neutralisation zone", 'workflow_status': 'Valid�', 'assembly_status': 'Mont�', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:24:26.830', 'work_duration_compl': 'Non', 'participants': [{'name': 'Sulser, Christian', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur RSR'}, {'name': 'Matthey-Doret, Jacques', 'function': 'Commentateur/trice', 'role': 'collaborateur RSR'}, {'name': 'Simonin, Pierre-Yves', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur RSR'}, {'name': 'Studer, Karl', 'function': 'Interview�/e', 'role': 'professeur'}, {'name': 'Mairet, Claude (journaliste)', 'function': 'Intervieweur/euse', 'role': 'correspondant RSR � Dallas'}, {'name': 'Zbinden, Louis-Albert', 'function': 'Commentateur/trice', 'role': 'correspondant RSR � Paris'}, {'name': 'Lacouture, Jean', 'function': 'Interview�/e', 'role': 'historien'}, {'name': 'Mairet, Claude (journaliste)', 'function': 'Intervieweur/euse', 'role': 'correspondant RSR � Paris'}], 'geographical_descriptors': ['Etats-Unis', 'Texas', 'Cambodge', 'Asie du Sud-Est'], 'person_descriptors': ['Kennedy, John Fitzgerald', 'Oswald, Lee Harvey', 'Johnson, Lyndon B.', 'Gaulle, Charles de', 'Sihanouk, Norodom'], 'thematical_descriptors': ['politique', 'relations internationales', 'assassinat politique', 'enqu�te judiciaire', 'communisme'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Premier programme'], 'subdomains': ['Commentaire', 'Interview'], 'recording_dates': ['26/11/1963 - 26/11/1963'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {565DB806-4B82-4D49-AF40-3642DF5D7F32}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': '565DB806-4B82-4D49-AF40-3642DF5D7F32_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{565DB806-4B82-4D49-AF40-3642DF5D7F32}', 'stripped_OID': '565DB806-4B82-4D49-AF40-3642DF5D7F32', 'login': '', 'broadcast_episode_title': "1. Lancement de la fus�e sovi�tique vers la lune, le 3 janvier 1959. - 2. Rejet des propositions russes au sujet de Berlin par les trois puissances occidentales et le gouvernement de l'Allemagne f�d�rale : Commentaires de Jacques Ferrier, correspondant � Bonn - 3. Tour d'horizon de Londres pr�sent� par Jean Wetz, correspondant � Londres. 4 .- Non participation des socialistes au nouveau gouvernement  qui sera certainement pr�sid� par Michel Debr�", 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'saudouce', 'modified_on': '24.05.2022 14:24:20', 'physical_support_history': "Cote d'origine: 7727", 'production_type': 'Production propre', 'recording_place': 'Studio Radio-Lausanne', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi�', 'series_title': "Sauvegarde d'archives", 'content_summary': "1. Commentaires d'albert Ducrocq, astronaute fran�ais, sur les aspects techniques du lancement de la fus�e russe vers la lune et sur l'impact scientifique de cette nouvelle exploration spatiale. - 3. D�marrage du march� commun, rappel du lancement de la fus�e sovi�tique vers la lune et �num�ration de personnalit�s britanniques qui ont re�u une distinction.", 'workflow_status': 'Valid�', 'assembly_status': 'Mont�', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:31:24.503', 'work_duration_compl': 'Non', 'participants': [{'name': 'Romieux, Benjamin', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Inconnu', 'function': 'Annonceur/euse', 'role': 'collaborateur Radio-Moscou'}, {'name': 'Ducrocq, Albert', 'function': 'Interview�/e', 'role': 'astronaute'}, {'name': 'Mairet, Claude (journaliste)', 'function': 'Intervieweur/euse', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Wetz, Jean', 'function': 'Correspondant/e', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Ferrier, Jacques', 'function': 'Correspondant/e', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Lombard, Ren�', 'function': 'Reporter', 'role': 'collaborateur Radio-Lausanne'}], 'geographical_descriptors': ['URSS', 'Allemagne', 'Berlin', 'Angleterre', 'Londres', 'France', 'Etats-Unis'], 'person_descriptors': ['Khrouchtchev, Nikita Sergue�evitch', 'McMillan, Ernest', 'Debr�, Michel'], 'thematical_descriptors': ['astronomie', "satellite d'observation", 'exp�dition scientifique', 'lune', 'politique internationale', 'd�sarmement', 'guerre froide'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Interview', 'Commentaire'], 'recording_dates': ['03/01/1959 - 03/01/1959'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {CD91FF43-63CB-493B-A81C-4774355845D5}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': 'CD91FF43-63CB-493B-A81C-4774355845D5_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{CD91FF43-63CB-493B-A81C-4774355845D5}', 'stripped_OID': 'CD91FF43-63CB-493B-A81C-4774355845D5', 'login': '', 'broadcast_episode_title': '1. Lancement du satellite am�ricain "Atlas" sur une orbite autour de la terre. - 2. Compte-rendu de la Conf�rence des Peuples africains tenue � Accra du 8 au 13 d�cembre 1958. - 3. Interview de Paul Delouvrier, d�l�gu� g�n�ral en Alg�rie : Description de ses t�ches politiques et administratives. - 4. Pr�paration de l\'�lection pr�sidentielle fran�aise qui donne De Gaulle gagnant.', 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'gogniala', 'modified_on': '25.05.2022 15:41:49', 'physical_support_history': "Cote d'origine: 13341", 'production_type': 'Production propre', 'recording_place': 'Studio Radio-Lausanne ; Paris ; Brazzaville ; Alger ; Paris', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi�', 'series_title': "Sauvegarde d'archives", 'content_summary': "1. Commentaires sur l'exploit de l'arm�e am�ricaine : Projection de missile autour de la terre et construction de rampes de lancement. Les enjeux li�s � l'astronomie, � propos de la strat�gie militaire et politique de la France par rapport aux fus�es am�ricaines (budget, mission). Le traitement des armes nucl�aires. - 2. Mauvaise organisation de la conf�rence : peu de d�l�gations. - 4. Le r�le de Ren� Cassin dans cette �lection pr�sidentielle et les m�canismes de la Commission constitutionnelle consultative.", 'workflow_status': 'Valid�', 'assembly_status': 'Mont�', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:25:26.827', 'work_duration_compl': 'Non', 'participants': [{'name': 'Romieux, Benjamin', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Bloch-Morhange, Jacques', 'function': 'Interview�/e', 'role': "auteur d'un livre sur la strat�gie des fus�es"}, {'name': 'Acheson, Dean', 'function': 'Interview�/e', 'role': "pr�sident de l'Union Europ�enne Occidentale (UEO)"}, {'name': 'Cassin, Ren�', 'function': 'Interview�/e', 'role': "pr�sident de la commission constitutionnelle consultative et vice-pr�sident du Conseil d'Etat fran�ais"}, {'name': 'Mairet, Claude (journaliste)', 'function': 'Intervieweur/euse', 'role': 'collaborateur Radio-Lausanne � Paris'}, {'name': 'Blanchet, Andr�', 'function': 'Interview�/e', 'role': 'journaliste'}, {'name': 'Inconnu', 'function': 'Intervieweur/euse', 'role': 'collaborateur Radio-Lausanne'}], 'geographical_descriptors': ['France', 'Etats-Unis', 'Afrique', 'Accra', 'Alg�rie'], 'person_descriptors': ['OTAN', 'UEO'], 'thematical_descriptors': ["satellite d'observation", 'satellite de t�l�communication', 'bombe � hydrog�ne', 'arme nucl�aire', 'n�gociation', 'guerre froide', 'strat�gie militaire', 'ind�pendantisme', 'd�colonisation', '�lection pr�sidentielle'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Interview', 'Commentaire'], 'recording_dates': ['21/12/1958 - 21/12/1958'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {7BB147C6-5E21-4D3B-B1B5-DF470B755D0A}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': '7BB147C6-5E21-4D3B-B1B5-DF470B755D0A_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{7BB147C6-5E21-4D3B-B1B5-DF470B755D0A}', 'stripped_OID': '7BB147C6-5E21-4D3B-B1B5-DF470B755D0A', 'login': '', 'broadcast_episode_title': "1. Lancement du vaisseau multiplace sovi�tique Voskhod 1. - 2. Interview d'Albert Ducrocq, scientifique : A propos des objectifs du vol de Voskhod 1. - 3. R�action aux Etats-Unis � propos du vol Voskhod 1. - 4. Elections en Grande-Bretagne. - 5. Elections municipales en Belgique. - 6. Campagne des legislatives en France. - 7. Actualit�s internationales", 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '28.05.2022 15:28:23', 'physical_support_history': "Cote d'origine: A 7731", 'production_type': 'Production propre', 'recording_place': 'Lausanne (Studio RSR). Moscou. Paris. Washington. Bruxelles. Londres.', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi�', 'series_title': "Sauvegarde d'archives", 'content_summary': "1. � 00.50 : Son de l'�mission du vaisseau sovi�tique Voskhod I. � 01.53 : Yuri Levitan annonce le lancement du vol, l'�quipage du vaisseau ( Vladimir Komarov, Dr Boris Yegorov, Konstantin Feokistov) et les recherches scientifiques qui auront lieu. � 05.25 : Jean Forestier en ligne de Moscou commente la retransmission t�l�vis�e qui a montr� les astronautes en direct dans leurs manipulations, l'enjeu scientifique de cette mission, la question de l'atterrissage des astronautes. - 2. � 10.22 : Premier vol spatial � emmener plus d'une personne dans l'espace, l'avanc�e scientifique de cette mission. - 3. � 16.50 : Jean Sagnier commente la concurence spatiale am�ricaine. - 4. � 19.48 : Henri Pierre commente l'avantage des travaillistes. - 5. � 21.40 : Jacques Birandies [orthographe ?] commente la victoire du parti de l'opposition : La Libert� et du Progr�s. � 22.25 : D�claration du pr�sident du parti de la Libert� et du Progr�s sur l'anticipation des l�gislatives. - 6. � 23.23 : Jean-Pierre Moulin commente les strat�gies et alliances politiques, la position de Gaston Defferre, maire de Marseille et candidat � la pr�sidence, celle de Jean-Louis Tixier-Vignancour, �galement candidat � l'�lection pr�sidentielle fran�aise. - 7. � 26.18. � 28.34 : Henri Pierre fait le bilan de la conf�rence au Caire des pays non-engag�s, souligne l'attitude de bonne volont� et de compr�hension des Britanniques � l'�gard des pays non-align�s.", 'workflow_status': 'Valid�', 'assembly_status': 'Mont�', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:30:19.044', 'work_duration_compl': 'Non', 'participants': [{'name': 'Romieux, Benjamin', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur RSR'}, {'name': 'Matthey-Doret, Jacques', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur RSR'}, {'name': 'Levitan, Yuri', 'function': 'Commentateur/trice', 'role': 'speaker de Radio Moscou'}, {'name': 'Forestier, Jean', 'function': 'Commentateur/trice', 'role': 'correspondant RSR � Moscou'}, {'name': 'Ducrocq, Albert', 'function': 'Intervieweur/euse', 'role': 'journaliste et scientifique fran�ais'}, {'name': 'Mairet, Claude (journaliste)', 'function': 'Intervieweur/euse', 'role': 'correspondant RSR � Paris'}, {'name': 'Sagnier, Jean', 'function': 'Commentateur/trice', 'role': 'correspondant RSR � Washington'}, {'name': 'Pierre, Henri', 'function': 'Commentateur/trice', 'role': 'correspondant RSR � Londres'}, {'name': 'Birandies, Jacques (orthographe incertaine)', 'function': 'Commentateur/trice', 'role': 'journaliste RTB � Bruxelles'}, {'name': 'Inconnu', 'function': "Auteur d'une d�claration", 'role': 'pr�sident du parti de la libert� et du progr�s belge'}, {'name': 'Moulin, Jean-Pierre', 'function': 'Commentateur/trice', 'role': 'correspondant RSR � Paris'}], 'geographical_descriptors': ['URSS', 'Etats-Unis', 'Belgique', 'France'], 'person_descriptors': ['Defferre, Gaston', 'Tixier-Vignancour, Jean-Louis'], 'thematical_descriptors': ['vol spatial habit�', 'exp�dition scientifique', 'astronaute', 'politique', '�lection', '�lection communale', '�lection l�gislative', 'non alignement'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Premier programme'], 'subdomains': ['Commentaire', 'D�claration'], 'recording_dates': ['12/10/1964 - 12/10/1964'], 'first_broadcast_dates': None}
Skipping document 13/999 with OID {C68868BF-0324-419E-A8B8-046320213750} because it's missing its XML file!! (stt exists: False)
Skipping document 14/999 with OID {CA0CF361-EBD4-4BAB-99B8-78299543D3C7} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {E218C877-B78B-46E8-A0E0-7C30979CE561}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': 'E218C877-B78B-46E8-A0E0-7C30979CE561_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{E218C877-B78B-46E8-A0E0-7C30979CE561}', 'stripped_OID': 'E218C877-B78B-46E8-A0E0-7C30979CE561', 'login': '', 'broadcast_episode_title': '1. Le cosmodrome de Ba�konour et les vols de Vostok 3 et 4. - 2. Rumeur sur la r�union � Berlin des ministres des Affaires �trang�res occidentaux. - 3. Contraste entre Berlin-est et Berlin-ouest. - 4. Echec de la conf�rence du d�sarmenent � Gen�ve.', 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'pittetma', 'modified_on': '22.07.2022 15:55:36', 'physical_support_history': "Cote d'origine: A 1270", 'production_type': 'Production propre', 'recording_place': 'Lausanne (Studio RSR), Moscou.  Bonn. Gen�ve.', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi�', 'series_title': "Sauvegarde d'archives", 'content_summary': "1. Description du cosmodraume de Ba�konour. La vie du site scientifique, le suivi des missions Vostok 3 et 4 et des cosmonautes � bord. - 2. � 02.15 : Pr�sageant une intervention du pr�sident Khroutchev au sujet de Berlin � l'ONU, Bonn souhaite r�unir les ministres des Affaires �trang�res occidentaux pour mettre au point une attitude commune en pr�vision d'un nouveau d�veloppement. - 3. � 06.17 : T�moignage de Paul Reynaud qui raconte les diff�rences entre Berlin-est, ville occup�e, sans animation et triste ; et Berlin-ouest, ville prosp�re, en plein d�veloppement. Il rapporte l'histoire d'un couple de r�fugi� qui a fui Berlin-est. - 4. � 11.26 : Les n�gociations entre les puissances occidentales et sovi�tiques autour du d�sarmement n'ont pas abouti. Dans un contexte international incertain, l'Union Sovi�tique ne veut pas renoncer � ses essais nucl�aires.", 'workflow_status': 'Valid�', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:14:48.436', 'work_duration_compl': 'Non', 'participants': [{'name': 'Inconnu', 'function': 'Reporter', 'role': 'correspondant RSR � Moscou'}, {'name': 'Bernard, Jacques', 'function': 'Commentateur/trice', 'role': 'correspondant RSR � Bonn'}, {'name': 'Reynaud, Paul', 'function': 'Interview�/e', 'role': 'homme politique fran�ais'}, {'name': 'Legros, Marcel', 'function': 'Commentateur/trice', 'role': 'correspondant RSR � Gen�ve'}], 'geographical_descriptors': ["Allemagne de l'Est", "Allemagne de l'Ouest", 'Berlin'], 'person_descriptors': None, 'thematical_descriptors': ['astronaute', "sciences de l'univers", 'occupation militaire', 'd�sarmement'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Premier programme'], 'subdomains': ['Reportage', 'Commentaire', 'Interview'], 'recording_dates': ['14/08/1962 - 14/08/1962'], 'first_broadcast_dates': None}

100%|██████████| 4/4 [00:18<00:00,  4.62s/it]

Skipping document 909/999 with OID {3FA72EB5-AFE0-444E-A7B7-24FC2C84ECE0} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {6DAD3B23-F71B-49BE-9A86-E31CC97175A9}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': '6DAD3B23-F71B-49BE-9A86-E31CC97175A9_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{6DAD3B23-F71B-49BE-9A86-E31CC97175A9}', 'stripped_OID': '6DAD3B23-F71B-49BE-9A86-E31CC97175A9', 'login': '', 'broadcast_episode_title': 'Dix-neuvi�me f�te du peuple jurassien : extraits de discours et interview de Roland B�guelin, secr�taire g�n�ral du Rassemblement jurassien', 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '28.05.2022 07:27:31', 'physical_support_history': "Cote d'origine: A 10745", 'production_type': 'Production propre', 'recording_place': 'Lausanne (Studio RSR). Del�mont', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi�', 'series_title': "Sauvegarde d'archives. Jura", 'content_summary': 'Rapport d\'�coute d�taill� en annexe. Fragment de "Miroir du Monde"  : le document commence � 18.53 jusqu\'� 27.20.', 'workflow_status': 'Valid�', 'assembly_status': 'Brut', 'live': 'Live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'B�guelin, Roland', 'function': 'Interview�/e', 'role': 'secr�taire g�n�ral du Rassemblement jurassien'}, {'name': 'Nicod, Alain', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur RSR'}, {'name': 'Margot, Michel', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Del�mont', 'Jura bernois'], 'person_descriptors': ['B�guelin, Roland'], 'thematical_descriptors': ['question jurassienne', 'f�te populaire', 'manifestation politique'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Premier programme'], 'subdomains': ['D�claration', 'Interview'], 'recording_dates': ['11/09/1966 - 11/09/1966'], 'first_broadcast_dates': None}
Skipping document 911/999 with OID {05934E98-824D-4BD1-A2B9-FF50171E9C3B} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {CE70D61C-3FD2-4F83-B4B6-F78B9D14622C}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': 'CE70D61C-3FD2-4F83-B4B6-F78B9D14622C_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{CE70D61C-3FD2-4F83-B4B6-F78B9D14622C}', 'stripped_OID': 'CE70D61C-3FD2-4F83-B4B6-F78B9D14622C', 'login': '', 'broadcast_episode_title': "Editorial de Pierre Moser sur l'intervention de Jules Moch sur la conf�rence du d�sarmement � Gen�ve", 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'freudial', 'modified_on': '20.01.2025 16:00:54', 'physical_support_history': "Cote d'origine: MA 60.27 PL. B.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi�', 'series_title': None, 'content_summary': "Avec sommaire de l'�mission enti�re. M. Moch, d�l�gu� fran�ais et porte-parole des pays occidentaux, a comment� les propositions sovi�tiques.", 'workflow_status': 'Valid�', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:04:10.011', 'work_duration_compl': 'Non', 'participants': [{'name': 'Moser, Pierre', 'function': 'Commentateur/trice', 'role': 'collaborateur Radio-Gen�ve'}, {'name': 'Inconnu', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur Radio-Gen�ve'}], 'geographical_descriptors': ['France', 'URSS'], 'person_descriptors': ['Moch, Jules'], 'thematical_descriptors': ['d�sarmement', 'r�union internationale', 'relations Est Ouest', 'guerre froide'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Radio-Gen�ve'], 'subdomains': ['Commentaire'], 'recording_dates': ['13/06/1960 - 13/06/1960'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {A550CADB-21A1-47E0-BD32-8288AD7D7954}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': 'A550CADB-21A1-47E0-BD32-8288AD7D7954_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{A550CADB-21A1-47E0-BD32-8288AD7D7954}', 'stripped_OID': 'A550CADB-21A1-47E0-BD32-8288AD7D7954', 'login': '', 'broadcast_episode_title': "Editorial et commentaire � propos du Gouvernement Provisoire de la R�publique Alg�rienne et de l'ind�pendance de l'Alg�rie", 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'brucklbo', 'modified_on': '24.01.2020 15:25:59', 'physical_support_history': "Cote d'origine: MA 60_20.I.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi�', 'series_title': None, 'content_summary': "Lecture d'extrait du communiqu� du GPRA\n2.08 Moser: dialogue de sourds entre Fehrat Abbas et de Gaulle. Danger pour politique internationale", 'workflow_status': 'Valid�', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'St�r�o', 'work_duration': '00:03:20.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Moser, Pierre', 'function': 'Commentateur/trice', 'role': 'collaborateur RSR'}, {'name': 'Inconnu', 'function': 'Commentateur/trice', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Alg�rie', 'Alg�rie fran�aise'], 'person_descriptors': None, 'thematical_descriptors': ['colonialisme', 'd�colonisation', "guerre d'Alg�rie"], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Commentaire'], 'recording_dates': ['14/03/1960 - 14/03/1960'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {8C7B72EE-A1FA-41B8-9314-1680612B08FD}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': '8C7B72EE-A1FA-41B8-9314-1680612B08FD_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{8C7B72EE-A1FA-41B8-9314-1680612B08FD}', 'stripped_OID': '8C7B72EE-A1FA-41B8-9314-1680612B08FD', 'login': '', 'broadcast_episode_title': "Election � l'Acad�mie fran�aise de Marcel Achard, dramaturge et �crivain fran�ais", 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '11.06.2022 08:47:19', 'physical_support_history': "Cote d'origine: MA 59.19 Pl. M", 'production_type': 'Production propre', 'recording_place': 'Paris', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi�', 'series_title': "Sauvegarde d'archives", 'content_summary': '� 00.15 : Louis-Albert Zbinden commente l\'�lection du successeur de l\'historien Andr� Chevrillon, les candidats propos�s au fauteuil. � 03.29 : Andr� Rougemeont fait le portrait de Marcel Achard, auteur de "Jean de la Lune", son arriv�e � Paris. � 05.00 : Rediffusion d\'une interview de Marcel Achard par Claude Mairet, raconte comment il a �crit sa premi�re pi�ce "La Messe est dite", puis "Voulez-vous jouer avec mo�", mont�e par Charles Dullin et avec Marcel Achard, elle remporta un grand succ�s. Andr� Rougemeont poursuit son portrait sur le bon caract�re de Marcel Achard. � 08.27 : Extrait de la pi�ce "Jean de la lune", avec Michel Simon dans le r�le de Clo-Clo et Marcel Achard dans le r�le de Jef.', 'workflow_status': 'Valid�', 'assembly_status': 'Mont�', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:09:26.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Romieux, Benjamin', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur RSR'}, {'name': 'Zbinden, Louis-Albert', 'function': 'Commentateur/trice', 'role': 'correspondant RSR � Paris'}, {'name': 'Rougemont, Andr�', 'function': 'Commentateur/trice', 'role': 'collaborateur RSR'}, {'name': 'Achard, Marcel', 'function': 'Interview�/e', 'role': 'dramaturge et �crivain fran�ais [Archive RSR]'}, {'name': 'Mairet, Claude (journaliste)', 'function': 'Intervieweur/euse', 'role': 'correspondant RSR � Paris'}, {'name': 'Simon, Michel', 'function': 'Acteur /trice', 'role': 'Clo-Clo'}, {'name': 'Achard, Marcel', 'function': 'Acteur /trice', 'role': 'Jef'}], 'geographical_descriptors': ['France'], 'person_descriptors': ['Acad�mie fran�aise', 'Achard, Marcel'], 'thematical_descriptors': ['�lection', '�crivain', 'art dramatique', 'pi�ce de th��tre'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Premier programme'], 'subdomains': ['Commentaire'], 'recording_dates': ['29/05/1959 - 29/05/1959'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {9F781C07-53EC-4352-800D-B8D7583CF7F9}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': '9F781C07-53EC-4352-800D-B8D7583CF7F9_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{9F781C07-53EC-4352-800D-B8D7583CF7F9}', 'stripped_OID': '9F781C07-53EC-4352-800D-B8D7583CF7F9', 'login': '', 'broadcast_episode_title': "Election � l'Acad�mie Fran�aise de Ren� Clair, cin�aste, romancier et essayiste. R�actions des membres de l'Acad�mie � leur sortie du vote", 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'comtesi', 'modified_on': '09.03.2023 09:12:11', 'physical_support_history': "Cote d'origine: A 858 Pl.2", 'production_type': 'Production propre', 'recording_place': 'Paris', 'rights_notes': 'Memoriav. IMVOCS', 'rights_status': 'Clarifi�', 'series_title': "Sauvegarde d'archives", 'content_summary': None, 'workflow_status': 'Valid�', 'assembly_status': 'Mont�', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:03:46.347', 'work_duration_compl': 'Non', 'participants': [{'name': 'Mairet, Claude (journaliste)', 'function': 'Commentateur/trice', 'role': 'correspondant Radio-Lausanne � Paris'}, {'name': 'Maurois, Andr�', 'function': 'Interview�/e', 'role': '�crivain fran�ais'}, {'name': 'Cocteau, Jean', 'function': 'Interview�/e', 'role': '�crivain et cin�aste fran�ais'}, {'name': 'Pagnol, Marcel', 'function': 'Interview�/e', 'role': '�crivain et cin�aste'}, {'name': 'Chamson, Andr�', 'function': 'Interview�/e', 'role': '�crivain fran�ais'}, {'name': 'Mairet, Claude (journaliste)', 'function': 'Intervieweur/euse', 'role': 'correspondant Radio-Lausanne � Paris'}], 'geographical_descriptors': None, 'person_descriptors': ['Acad�mie fran�aise'], 'thematical_descriptors': ['�lection'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Commentaire', 'Interview'], 'recording_dates': ['16/06/1960 - 16/06/1960'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {B5C80543-FEC4-45D9-A128-3680DC38BAC8}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': 'B5C80543-FEC4-45D9-A128-3680DC38BAC8_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{B5C80543-FEC4-45D9-A128-3680DC38BAC8}', 'stripped_OID': 'B5C80543-FEC4-45D9-A128-3680DC38BAC8', 'login': '', 'broadcast_episode_title': 'Election de John-Fitzgerald Kennedy � la pr�sidence des Etats-Unis : Commentaires de journalistes correspondants dans quelques capitales', 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '23.11.2020 14:13:09', 'physical_support_history': "Cote d'origine: MA 60.65 Pl. F", 'production_type': 'Production propre', 'recording_place': 'Studio de Radio-Gen�ve', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi�', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid�', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'St�r�o', 'work_duration': '00:14:16.337', 'work_duration_compl': 'Non', 'participants': [{'name': 'Dumur, Jean', 'function': 'Commentateur/trice', 'role': 'collaborateur RSR'}, {'name': 'Tatu, Michel', 'function': 'Commentateur/trice', 'role': 'journaliste correspondant � Moscou'}, {'name': 'Kistler, Eric', 'function': 'Commentateur/trice', 'role': 'journaliste � Bonn'}, {'name': 'Nussl�, Etienne', 'function': 'Commentateur/trice', 'role': 'journaliste correspondant � Londres'}, {'name': 'Cartigny, Hector', 'function': 'Commentateur/trice', 'role': 'journaliste correspondant � Paris'}], 'geographical_descriptors': ['Etats-Unis', 'Angleterre'], 'person_descriptors': ['Kennedy, John Fitzgerald', 'Nixon'], 'thematical_descriptors': ['�lection pr�sidentielle'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Radio-Gen�ve'], 'subdomains': ['Commentaire'], 'recording_dates': ['09/11/1960 - 09/11/1960'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {3507BFE6-2D6A-4390-9B4F-B024885C4DB8}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': '3507BFE6-2D6A-4390-9B4F-B024885C4DB8_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{3507BFE6-2D6A-4390-9B4F-B024885C4DB8}', 'stripped_OID': '3507BFE6-2D6A-4390-9B4F-B024885C4DB8', 'login': '', 'broadcast_episode_title': "Elections alg�riennes. 1. Commentaire du correspondant sur place. - 2. Interviews Jean-Marie Le Pen, homme politique fran�ais, de Babette Lagaillarde, �lue qui remplace son mari Pierre Lagaillarde, et de Mohamed Ben Amer [orthographe incertaine], homme politique �lu sur la liste d'union apolitique pour l'Alg�rie francaise nouvelle par le plan de Constantine", 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'brucklbo', 'modified_on': '05.11.2020 12:04:30', 'physical_support_history': "Cote d'origine: MA 60.26 PL. D.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'A rechercher', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid�', 'assembly_status': 'Mont�', 'live': None, 'modulation_type': 'Mono', 'work_duration': '00:03:51.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Le Pen, Jean-Marie', 'function': 'Interview�/e', 'role': 'homme politique fran�ais'}, {'name': 'Lagaillarde, Babette', 'function': 'Interview�/e', 'role': 'femme politique fran�aise'}, {'name': 'Ben Amer, Mohamed [ortho?]', 'function': 'Interview�/e', 'role': 'homme politique Alg�rien'}, {'name': 'Darmsteter, Jean-Paul', 'function': 'Commentateur/trice', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Alg�rie', 'Alg�rie fran�aise'], 'person_descriptors': None, 'thematical_descriptors': ['�lection', 'd�colonisation', 'ind�pendantisme'], 'rights_usage_possibilities': None, 'radio_channels': None, 'subdomains': ['Commentaire', 'Interview'], 'recording_dates': ['30/05/1960 - 30/05/1960'], 'first_broadcast_dates': None}
Skipping document 929/999 with OID {83B512EB-CE51-4307-B3C7-FF64BB360BB0} because it's missing its XML file!! (stt exists: False)
Skipping document 932/999 with OID {0E16F32B-BA1A-4886-92D1-7DC9836A27D4} because it's missing its XML file!! (stt exists: False)
Skipping document 934/999 with OID {81F1C0A8-A233-46B3-AA29-7D65AC5215E3} because it's missing its XML file!! (stt exists: False)
Skipping document 935/999 with OID {AE299E97-A017-4219-91B4-0E64E5910DCD} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {7B5B7336-858D-4525-919B-6ED0E5428129}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': '7B5B7336-858D-4525-919B-6ED0E5428129_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{7B5B7336-858D-4525-919B-6ED0E5428129}', 'stripped_OID': '7B5B7336-858D-4525-919B-6ED0E5428129', 'login': '', 'broadcast_episode_title': "El�ments de Radio Alger, diverses d�clarations, appel du colonel S�bastien Silvani aux Corses, il annonce son arriv�e le 31 mai � Ajaccio, manifestation sur la place de la R�publique � Paris, chanson, extrait de l'hymne national fran�ais", 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'gogniala', 'modified_on': '09.03.2023 09:35:21', 'physical_support_history': "Cote d'origine: 9712 PL. 02.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'A rechercher', 'series_title': "Sauvegarde d'archives", 'content_summary': '(A 1.10) D�claration du colonel Silvani', 'workflow_status': 'Valid�', 'assembly_status': 'Brut', 'live': None, 'modulation_type': 'Mono', 'work_duration': '00:06:05.853', 'work_duration_compl': 'Non', 'participants': [{'name': 'Voix diverses', 'function': 'Divers', 'role': 'non-identifi�es'}, {'name': 'Silvani, S�bastien (colonel)', 'function': "Auteur d'une d�claration", 'role': 'pr�sident de la F�d�ration des groupements corses d�Alg�rie'}], 'geographical_descriptors': ['France', 'Alg�rie', 'Corse'], 'person_descriptors': ['Gaulle, Charles de'], 'thematical_descriptors': ["coup d'Etat", 'patriotisme'], 'rights_usage_possibilities': None, 'radio_channels': ['Premier programme'], 'subdomains': ['D�claration', 'Reportage'], 'recording_dates': ['01/06/1958 - 01/06/1958'], 'first_broadcast_dates': None}
Skipping document 937/999 with OID {D385E49E-6456-45BA-BAE5-B5C4EFDBF9EF} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {1CC65C5C-6B77-45D1-B5B2-7C8FD0874253}. Trying to use the recording date. doc_dict: {'alias': 'miroir_monde', 'date_str': None, 'stt_filename': '1CC65C5C-6B77-45D1-B5B2-7C8FD0874253_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{1CC65C5C-6B77-45D1-B5B2-7C8FD0874253}', 'stripped_OID': '1CC65C5C-6B77-45D1-B5B2-7C8FD0874253', 'login': '', 'broadcast_episode_title': "Emission de vendredi saint : Entretien sur les chances de l'oecum�nisme entre un pasteur et un pr�tre", 'sequence': '1', 'broadcast_program_name': 'Miroir du monde', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '12.05.2022 06:09:56', 'physical_support_history': "Cote d'origine: A 1697", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi�', 'series_title': "Sauvegarde d'archives", 'content_summary': 'D�bat sur des aspects dogmatiques qui divergent entre protestantisme et catholicisme.', 'workflow_status': 'Valid�', 'assembly_status': 'Mont�', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:21:14.880', 'work_duration_compl': 'Non', 'participants': [{'name': 'Romieux, Benjamin', 'function': 'Pr�sentateur/trice', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Bosc (nom)', 'function': 'Interview�/e', 'role': 'pasteur'}, {'name': 'Zbinden, Louis-Albert', 'function': 'Intervieweur/euse', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Danielou (nom)', 'function': 'Interview�/e', 'role': 'r�v�rend p�re'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': ['oecum�nisme', 'catholicisme', 'protestantisme'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Commentaire', 'D�bat'], 'recording_dates': ['15/04/1960 - 15/04/1960'], 'first_broadcast_dates': None}
Skipping document 943/999 with OID {E56037EC-7A4B-4A65-959D-431B21DE3FA1} because it's missing its XML file!! (stt exists: False)

32it [02:20,  7.20s/it]

PROCESSING PROGRAM miroir_temps (33/47) - 1 files:

Starting extracting 304 documents for program miroir_temps
Did not find any date for doc with OID {BE024A39-EFAD-45AD-A943-DB6F94C87F7E}. Trying to use the recording date. doc_dict: {'alias': 'miroir_temps', 'date_str': None, 'stt_filename': 'BE024A39-EFAD-45AD-A943-DB6F94C87F7E_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{BE024A39-EFAD-45AD-A943-DB6F94C87F7E}', 'stripped_OID': 'BE024A39-EFAD-45AD-A943-DB6F94C87F7E', 'login': '', 'broadcast_episode_title': "25?me anniversaire du couronnement de Hail? S?lassi? 1er, empereur d'Ethiopie", 'sequence': '1', 'broadcast_program_name': 'Miroir du temps', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '22.07.2022 16:38:11', 'physical_support_history': "Cote d'origine: 10474", 'production_type': 'Production propre', 'recording_place': 'Addis-Abeba (Ethiopie)', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': 'Reportage avec chants et bruits ambiants. Portrait du N?gus, sa carri?re, description des c?r?monies de comm?moration', 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Favrod, Charles-Henri', 'function': 'Commentateur/trice', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Ethiopie', 'Addis-Abeba'], 'person_descriptors': ['Hail? S?lassi? 1er'], 'thematical_descriptors': ['roi', 'politique'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Documentaire'], 'recording_dates': ['12/11/1955 - 12/11/1955'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {1EBD2A5E-3F4F-4B1C-8F83-22F20D2061A0}. Trying to use the recording date. doc_dict: {'alias': 'miroir_temps', 'date_str': None, 'stt_filename': '1EBD2A5E-3F4F-4B1C-8F83-22F20D2061A0_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{1EBD2A5E-3F4F-4B1C-8F83-22F20D2061A0}', 'stripped_OID': '1EBD2A5E-3F4F-4B1C-8F83-22F20D2061A0', 'login': '', 'broadcast_episode_title': "Accouchement naturel ? l'H?pital Saint-Antoine : T?moignages de femmes qui sont sur le point d'accoucher suivant cette m?thode et celles qui ont d?j? pratiqu? l'accouchement naturel", 'sequence': '1', 'broadcast_program_name': 'Miroir du temps', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'saudouce', 'modified_on': '01.06.2022 15:50:49', 'physical_support_history': "Cote d'origine: 11013", 'production_type': 'Production propre', 'recording_place': 'Paris', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': "Reportage documentaire ? l'H?pital St-Antoine de Paris qui est le seul ?tablissement de France ? pratiquer l'accouchement naturel. Explication de la m?thode d'accouchement naturel et suivi de chaque ?tape.", 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Rimbaud (nom)', 'function': 'Interview?/e', 'role': 'sage-femme'}, {'name': 'Anonyme', 'function': 'Interview?/e', 'role': 'femme qui accouche'}, {'name': 'Anonyme', 'function': 'Participant/e au d?bat', 'role': "sage-femme donnant un cours sur l'accouchement naturel"}, {'name': 'Voix diverses', 'function': 'Participant/e au d?bat', 'role': "groupes de femmes qui assistent au cours de l'accouchement naturel"}, {'name': 'Meier (nom)', 'function': "Auteur d'une d?claration", 'role': "professeur ? l'h?pital Saint-Antoine de Paris"}, {'name': 'Voix diverses', 'function': 'Interview?/e', 'role': 'femmes qui accouchent'}, {'name': 'Zbinden, Louis-Albert', 'function': 'Intervieweur/euse', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Zbinden, Louis-Albert', 'function': 'Pr?sentateur/trice', 'role': 'collaborateur Radio-Lausanne'}], 'geographical_descriptors': ['Paris'], 'person_descriptors': None, 'thematical_descriptors': ['accouchement', 'maternit? (?tat)', 'grossesse', 'gyn?cologie', 'h?pital'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Documentaire'], 'recording_dates': ['06/06/1956 - 06/06/1956'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {2360A594-EEBF-41BD-99F3-197074D64F31}. Trying to use the recording date. doc_dict: {'alias': 'miroir_temps', 'date_str': None, 'stt_filename': '2360A594-EEBF-41BD-99F3-197074D64F31_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{2360A594-EEBF-41BD-99F3-197074D64F31}', 'stripped_OID': '2360A594-EEBF-41BD-99F3-197074D64F31', 'login': '', 'broadcast_episode_title': "Ainsi va le monde 1955 : R?trospective de Benjamin Romieux, avec les voix des grands acteurs politiques de l'ann?e (1/3)", 'sequence': '1', 'broadcast_program_name': 'Miroir du temps', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '10.06.2022 21:41:07', 'physical_support_history': None, 'production_type': 'Production propre', 'recording_place': 'Lausanne. Londres. Paris. Washington. Moscou. Vienne.', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': "Tous les intervenants n'ont pas pu ?tre r?pertori?s sous Interpr?te/Participant vu leur grand nombre.", 'workflow_status': 'Valid?', 'assembly_status': 'Pr?t', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Romieux, Benjamin', 'function': 'Commentateur/trice', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Rougemont, Andr?', 'function': 'Commentateur/trice', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Sulser, Christian', 'function': 'Commentateur/trice', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Faure, Edgar', 'function': "Auteur d'une d?claration", 'role': 'pr?sident du Conseil fran?ais'}, {'name': 'Poujade, Pierre', 'function': "Auteur d'une d?claration", 'role': 'homme politique fran?ais'}, {'name': 'Churchill, Winston', 'function': "Auteur d'une d?claration", 'role': 'premier ministre anglais'}, {'name': 'Inconnu', 'function': 'Commentateur/trice', 'role': 'journaliste anglais'}, {'name': "Margareth d'Angleterre", 'function': "Auteur d'une d?claration", 'role': "princesse d'Angleterre"}, {'name': 'Eisenhower, Dwight David', 'function': "Auteur d'une d?claration", 'role': 'pr?sident des Etats-Unis'}, {'name': 'Salk, Jonas', 'function': "Auteur d'une d?claration", 'role': 'Docteur, auteur du vaccin contre la polyomi?lite'}, {'name': 'Boulganine, Nikola? Aleksandrovitch', 'function': "Auteur d'une d?claration", 'role': "pr?sident du conseil des ministres d'Union Sovi?tique"}, {'name': 'Khrouchtchev, Nikita Sergue?evitch', 'function': "Auteur d'une d?claration", 'role': 'secr?taire g?n?ral du parti communiste sovi?tique'}, {'name': 'Nordmann, Roger (homme de radio)', 'function': 'Intervieweur/euse', 'role': 'correspondant Radio-Gen?ve ? Moscou'}, {'name': 'Tito', 'function': "Auteur d'une d?claration", 'role': 'mar?chal, dirigeant yougoslave'}, {'name': 'Raab, Julius', 'function': "Auteur d'une d?claration", 'role': 'chancellier f?d?ral autrichien'}, {'name': 'Inconnu', 'function': 'Commentateur/trice', 'role': 'journaliste'}, {'name': 'Adenauer, Konrad', 'function': "Auteur d'une d?claration", 'role': 'chancellier allemand'}], 'geographical_descriptors': ['France', 'Etats-Unis', 'Angleterre', 'URSS', 'Yougoslavie'], 'person_descriptors': None, 'thematical_descriptors': ['politique', 'politique internationale', 'relations internationales'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Premier programme'], 'subdomains': ['Commentaire'], 'recording_dates': ['26/12/1955 - 26/12/1955'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {7F7B30BF-3C11-4D8E-9C24-270D67330889}. Trying to use the recording date. doc_dict: {'alias': 'miroir_temps', 'date_str': None, 'stt_filename': '7F7B30BF-3C11-4D8E-9C24-270D67330889_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{7F7B30BF-3C11-4D8E-9C24-270D67330889}', 'stripped_OID': '7F7B30BF-3C11-4D8E-9C24-270D67330889', 'login': '', 'broadcast_episode_title': 'Allocution de Salazar, pr?sident du conseil portugais, apr?s les ?lections pr?sidentielles du 8 juin 1958 gagn?es par Americo Tomas', 'sequence': '1', 'broadcast_program_name': 'Miroir du temps', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'saudouce', 'modified_on': '19.05.2022 23:05:44', 'physical_support_history': "Cote d'origine: 10779", 'production_type': 'Production propre', 'recording_place': 'Lisbonne', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Extraits du discours de Salazar sur la politique portugaise', 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Savreux, Paul', 'function': 'Pr?sentateur/trice', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Salazar, Antonio de Oliveira', 'function': "Auteur d'une d?claration", 'role': 'pr?sident du conseil portugais'}], 'geographical_descriptors': ['Portugal'], 'person_descriptors': ['Salazar, Antonio de Oliveira'], 'thematical_descriptors': ['?lection pr?sidentielle', 'r?gime politique', 'dictature', 'politique sociale'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['D?claration'], 'recording_dates': ['08/06/1958 - 08/06/1958'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {626DE220-7ED0-43A4-B519-165EC20ABFA3}. Trying to use the recording date. doc_dict: {'alias': 'miroir_temps', 'date_str': None, 'stt_filename': '626DE220-7ED0-43A4-B519-165EC20ABFA3_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{626DE220-7ED0-43A4-B519-165EC20ABFA3}', 'stripped_OID': '626DE220-7ED0-43A4-B519-165EC20ABFA3', 'login': '', 'broadcast_episode_title': "Allocution radiophonique du g?n?ral de Gaulle, sur son retour au gouvernement, l'Alg?rie, les relations de la France avec les pays associ?s d'Afrique du Nord et ses projets de r?forme de la politique fran?aise", 'sequence': '1', 'broadcast_program_name': 'Miroir du temps', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'blochge', 'modified_on': '09.06.2022 10:47:26', 'physical_support_history': "Cote d'origine: 14766 Ecoute", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'A rechercher', 'series_title': "Sauvegarde d'archives", 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Gaulle, Charles de', 'function': "Auteur d'une d?claration", 'role': 'pr?sident de la r?publique fran?aise'}], 'geographical_descriptors': ['Alg?rie', 'France', 'Afrique du Nord'], 'person_descriptors': ['Gaulle, Charles de'], 'thematical_descriptors': ['politique', "guerre d'Alg?rie", 'd?colonisation', 'relations internationales'], 'rights_usage_possibilities': ['FM'], 'radio_channels': None, 'subdomains': ['D?claration'], 'recording_dates': ['13/06/1958 - 13/06/1958'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {67CFF89A-E115-407A-A64A-0C118E6ECC28}. Trying to use the recording date. doc_dict: {'alias': 'miroir_temps', 'date_str': None, 'stt_filename': '67CFF89A-E115-407A-A64A-0C118E6ECC28_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{67CFF89A-E115-407A-A64A-0C118E6ECC28}', 'stripped_OID': '67CFF89A-E115-407A-A64A-0C118E6ECC28', 'login': '', 'broadcast_episode_title': "Antoine de Saint-Exup?ry (1/3) : Interview de Pierre Clostermann, aviateur, sur l'importance de la fonction d'aviateur de l'?crivain", 'sequence': '1', 'broadcast_program_name': 'Miroir du temps', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '10.06.2022 17:08:07', 'physical_support_history': "Cote d'origine: 12838 Pl. A", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Clostermann, Pierre', 'function': 'Interview?/e', 'role': 'aviateur'}, {'name': 'Zbinden, Louis-Albert', 'function': 'Intervieweur/euse', 'role': 'collaborateur Radio-Lausanne'}], 'geographical_descriptors': None, 'person_descriptors': ['Saint-Exup?ry, Antoine de'], 'thematical_descriptors': ['avion civil', 'aviation', 'patrie', '?crivain'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Interview'], 'recording_dates': ['30/09/1957 - 30/09/1957'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {F204A49C-3411-4F21-B54D-20BAD073993C}. Trying to use the recording date. doc_dict: {'alias': 'miroir_temps', 'date_str': None, 'stt_filename': 'F204A49C-3411-4F21-B54D-20BAD073993C_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{F204A49C-3411-4F21-B54D-20BAD073993C}', 'stripped_OID': 'F204A49C-3411-4F21-B54D-20BAD073993C', 'login': '', 'broadcast_episode_title': "Antoine de Saint-Exup?ry (2/3) : Interview de Jean Dabry, commandant aviateur, sur l'importance de la fonction d'aviateur de l'?crivain", 'sequence': '1', 'broadcast_program_name': 'Miroir du temps', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '02.06.2022 07:03:48', 'physical_support_history': "Cote d'origine: 12838 Pl. B", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': "Relations de Saint-Exup?ry avec ses camarades d'aviation, caract?re de l'homme pilote et ?crivain. Conditions de la fin tragique de Saint-Exup?ry : probablement abattu par un pilote allemand en mission de guerre sur la M?diterran?e.", 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Dabry, Jean', 'function': 'Interview?/e', 'role': 'commandant'}, {'name': 'Zbinden, Louis-Albert', 'function': 'Intervieweur/euse', 'role': 'collaborateur Radio-Lausanne'}], 'geographical_descriptors': None, 'person_descriptors': ['Saint-Exup?ry, Antoine de'], 'thematical_descriptors': ['?crivain', 'avion civil', 'avion militaire', 'aviation'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Interview'], 'recording_dates': ['30/09/1957 - 30/09/1957'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {F5B1DE0D-64E0-4AD2-BC11-F1B93F007F73}. Trying to use the recording date. doc_dict: {'alias': 'miroir_temps', 'date_str': None, 'stt_filename': 'F5B1DE0D-64E0-4AD2-BC11-F1B93F007F73_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{F5B1DE0D-64E0-4AD2-BC11-F1B93F007F73}', 'stripped_OID': 'F5B1DE0D-64E0-4AD2-BC11-F1B93F007F73', 'login': '', 'broadcast_episode_title': "Antoine de Saint-Exup?ry (3/3) : Interview de Didier Daurat, commandant des lignes a?riennes, sur l'importance de la fonction d'aviateur de l'?crivain", 'sequence': '1', 'broadcast_program_name': 'Miroir du temps', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'saudouce', 'modified_on': '12.05.2022 18:46:02', 'physical_support_history': "Cote d'origine: 12838 Pl. C", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Les d?buts dans l\'aviation Saint-Exup?ry, aptitudes litt?raires de Saint-Exup?ry, ses valeurs morales, pr?sentation du livre "Vol de nuit" ? son commandant.', 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Daurat, Didier', 'function': 'Interview?/e', 'role': 'commandant de lignes a?riennes, premier patron de Saint-Exup?ry'}, {'name': 'Zbinden, Louis-Albert', 'function': 'Intervieweur/euse', 'role': 'collaborateur Radio-Lausanne'}], 'geographical_descriptors': None, 'person_descriptors': ['Saint-Exup?ry, Antoine de'], 'thematical_descriptors': ['?crivain', 'aviation', 'pilote de ligne'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Interview'], 'recording_dates': ['30/09/1957 - 30/09/1957'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {4E3076AF-703B-4DF3-B47A-FA7FF1E2374D}. Trying to use the recording date. doc_dict: {'alias': 'miroir_temps', 'date_str': None, 'stt_filename': '4E3076AF-703B-4DF3-B47A-FA7FF1E2374D_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{4E3076AF-703B-4DF3-B47A-FA7FF1E2374D}', 'stripped_OID': '4E3076AF-703B-4DF3-B47A-FA7FF1E2374D', 'login': '', 'broadcast_episode_title': 'Arriv?e de Ren? Coty,  pr?sident de la R?publique fran?aise, ? Rome pour rencontrer Giovanni Gronchi, son homologue italien', 'sequence': '1', 'broadcast_program_name': 'Miroir du temps', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'gogniala', 'modified_on': '12.05.2022 12:30:49', 'physical_support_history': "Cote d'origine: 12526", 'production_type': 'Production propre', 'recording_place': 'Rome', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Sadorge, Henri', 'function': 'Reporter', 'role': 'collaborateur Radio-Lausanne ? Rome'}, {'name': 'Simon, Samy', 'function': 'Reporter', 'role': 'collaborateur Radio-Lausanne ? Rome'}, {'name': 'Tupini, Umberto', 'function': "Auteur d'une d?claration", 'role': 'maire de Rome'}, {'name': 'Coty, Ren?', 'function': "Auteur d'une d?claration", 'role': 'pr?sident de la R?publique fran?aise'}], 'geographical_descriptors': ['Rome', 'Italie', 'Paris', 'France'], 'person_descriptors': ['Coty, Ren?', 'Gronchi, Giovanni'], 'thematical_descriptors': ['relations publiques', 'relations internationales', 'r?publique', 'd?mocratie (id?ologie)'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['D?claration'], 'recording_dates': ['09/05/1957 - 09/05/1957'], 'first_broadcast_dates': None}

100%|██████████| 1/1 [00:01<00:00,  1.53s/it]
33it [02:22,  5.68s/it]

Did not find any date for doc with OID {5BB86C73-B2DE-45EF-89BE-DAA627B63E70}. Trying to use the recording date. doc_dict: {'alias': 'miroir_temps', 'date_str': None, 'stt_filename': '5BB86C73-B2DE-45EF-89BE-DAA627B63E70_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{5BB86C73-B2DE-45EF-89BE-DAA627B63E70}', 'stripped_OID': '5BB86C73-B2DE-45EF-89BE-DAA627B63E70', 'login': '', 'broadcast_episode_title': 'Les relations franco-tunisiennes en 1957 [son brut]', 'sequence': '7', 'broadcast_program_name': 'Miroir du temps', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'vonimhma', 'modified_on': '11.03.2023 21:23:17', 'physical_support_history': "Copie Mesures d'urgence. Disque 78t maison Radio-Lausanne 3253H. En 1 plage", 'production_type': 'Production propre', 'recording_place': 'Tunis', 'rights_notes': None, 'rights_status': None, 'series_title': "Sauvegarde d'archives", 'content_summary': "Chronique hebdomadaire de Bourguiba ? la radio. R?cent incident de fronti?re. Bourguiba consid?re que c'est une provocation de la part de la France. Rappel de l'ambassadeur de Tunisie ? Paris. Appel au calme lanc? par Bourguiba, qui est pr?t ? ouvrir des n?gociations loyales.", 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Favrod, Charles-Henri', 'function': 'Commentateur/trice', 'role': 'journaliste'}, {'name': 'Bourguiba, Habib', 'function': "Auteur d'une d?claration", 'role': 'pr?sident de la Tunisie'}], 'geographical_descriptors': ['Tunisie', 'France'], 'person_descriptors': ['Bourguiba, Habib'], 'thematical_descriptors': ['ind?pendantisme', 'colonialisme', 'relations internationales', 'crise politique'], 'rights_usage_possibilities': None, 'radio_channels': None, 'subdomains': ['Commentaire', 'D?claration'], 'recording_dates': ['03/10/1957 - 03/10/1957'], 'first_broadcast_dates': None}
Skipping document 241/304 with OID {5BB86C73-B2DE-45EF-89BE-DAA627B63E70} because it's missing its audio MP3 file!!
Skipping document 242/304 with OID {E29CCE49-CC62-44C2-A202-B65AB872F08C} because it's missing its XML file!! (stt exists: False)
Skipping document 243/304 with OID {7859234F-8AFA-4FE9-96CB-71C5444DA985} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {4EB71CB9-681E-48E2-B6D7-69C0FBE4E2AD}. Trying to use the recording date. doc_dict: {'alias': 'miroir_temps', 'date_str': None, 'stt_filename': '4EB71CB9-681E-48E2-B6D7-69C0FBE4E2AD_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{4EB71CB9-681E-48E2-B6D7-69C0FBE4E2AD}', 'stripped_OID': '4EB71CB9-681E-48E2-B6D7-69C0FBE4E2AD', 'login': '', 'broadcast_episode_title': 'Manifestations du 13 mai 1958 : reportages ? Paris et Alger (1/3)', 'sequence': '1', 'broadcast_program_name': 'Miroir du temps', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '09.03.2023 09:46:12', 'physical_support_history': "Cote d'origine: 14387 Pl. A", 'production_type': 'Production propre', 'recording_place': 'Paris. Alger', 'rights_notes': 'Memoriav', 'rights_status': 'A rechercher', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Manifestation ? Paris : compte rendu, avec un enregistrement de "La Marseillaise" scand?e par les manifestants. Reportage ? Alger, o? les manifestants, r?unis pour comm?morer l\'ex?cution de trois soldats fran?ais par le FLN chantent "La Marseillaise" . Slogan "Alg?rie fran?aise". Description de l\'assaut du minist?re de l\'Alg?rie par quelques manifestants.', 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Inconnu', 'function': 'Pr?sentateur/trice', 'role': 'collaborateur RTF'}, {'name': 'Inconnu', 'function': 'Commentateur/trice', 'role': 'correspondant ? Paris'}, {'name': 'Inconnus', 'function': 'Divers', 'role': 'manifestants ? Paris chantant "La Marseillaise"'}, {'name': 'Inconnu', 'function': "Auteur d'une d?claration", 'role': "auteur d'un discours ? Alger, durant la manifestation"}, {'name': 'Inconnus', 'function': 'Divers', 'role': 'manifestants ? Alger chantant "La Marseillaise" et scandant "Alg?rie fran?aise"'}, {'name': 'Bernier, Philippe', 'function': 'Reporter', 'role': 'correspondant RTF ? Alger'}, {'name': 'Grand, Jean-Gabriel', 'function': 'Reporter', 'role': 'correspondant RTF ? Alger'}], 'geographical_descriptors': ['Alg?rie', 'Alger', 'France', 'Paris'], 'person_descriptors': None, 'thematical_descriptors': ["guerre d'Alg?rie", 'manifestation politique', 'politique', 'foule', 'nationalisme', 'pied-noir'], 'rights_usage_possibilities': None, 'radio_channels': ['Premier programme'], 'subdomains': ['Reportage', 'Commentaire'], 'recording_dates': ['13/05/1958 - 13/05/1958'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {ED670B72-0244-4F32-A96E-5FDC9D63B2A5}. Trying to use the recording date. doc_dict: {'alias': 'miroir_temps', 'date_str': None, 'stt_filename': 'ED670B72-0244-4F32-A96E-5FDC9D63B2A5_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{ED670B72-0244-4F32-A96E-5FDC9D63B2A5}', 'stripped_OID': 'ED670B72-0244-4F32-A96E-5FDC9D63B2A5', 'login': '', 'broadcast_episode_title': 'Manifestations du 13 mai 1958 : reportages ? Paris et Alger (2/3)', 'sequence': '1', 'broadcast_program_name': 'Miroir du temps', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '11.05.2022 12:39:12', 'physical_support_history': "Cote d'origine: 14387 Pl. B", 'production_type': 'Production propre', 'recording_place': 'Alger. Paris', 'rights_notes': 'Memoriav', 'rights_status': 'A rechercher', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Alger, le minist?re est envahi. La gr?ve g?n?rale est d?clar?e. La foule scande "Alg?rie fran?aise" et "La Marseillaise", derri?re la description du commentateur. Lecture par le commentateur de la motion r?dig?e par le comit? de vigilance. Analyse et compte-rendu du discours de Pierre Pflimlin sur sa politique en Alg?rie. Reportage de la manifestation ? Paris, aux Champs-Elys?es. Slogan "Alg?rie fran?aise" et chant "La Marseillaise". Altercations avec les barrages de police. Les manifestants sont en g?n?ral jeunes, ils forcent facilement les barrages. C?r?monie de comm?moration ? Bonn ? la m?moire des 3 soldats fran?ais tu?s par le FLN. Nouvelles de la manifestation ? Alger. Au balcon du minist?re sont apparus notamment le g?n?ral Massu, tr?s acclam?. Retour ? la manifestation de Paris ou les CRS frappent les manifestants.', 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Inconnu', 'function': 'Reporter', 'role': 'correspondant ? Alger'}, {'name': 'Inconnu', 'function': 'Commentateur/trice', 'role': 'commentateur du discours de P.Pflimlin'}, {'name': 'Voix diverses', 'function': 'Reporter', 'role': 'reporters ? Paris'}, {'name': 'Degei, Jean-Claude (orthographe incertaine)', 'function': 'Reporter', 'role': 'reporter ? Paris'}, {'name': 'Besan?on, Julien', 'function': 'Reporter', 'role': 'reporter Radio-Lausanne ? Paris (trouv? en candidat)'}, {'name': 'Inconnu', 'function': 'Pr?sentateur/trice', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Teillex, Andr?', 'function': 'Reporter', 'role': 'envoy? sp?cial Radio-Lausanne ? Baulnes'}, {'name': 'Inconnu', 'function': 'Reporter', 'role': 'correspondant Radio-Luxembourg ? Alger'}, {'name': 'Courri?re, Yves', 'function': 'Reporter', 'role': 'correspondant Radio-Lausanne ? Paris'}], 'geographical_descriptors': ['Alger', 'Paris'], 'person_descriptors': None, 'thematical_descriptors': ['manifestation politique', 'foule', "guerre d'Alg?rie", 'colonialisme'], 'rights_usage_possibilities': None, 'radio_channels': None, 'subdomains': ['Reportage'], 'recording_dates': ['13/05/1958 - 13/05/1958'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {1E9C0A87-D764-48F2-8AA5-AF20C04C3D0E}. Trying to use the recording date. doc_dict: {'alias': 'miroir_temps', 'date_str': None, 'stt_filename': '1E9C0A87-D764-48F2-8AA5-AF20C04C3D0E_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{1E9C0A87-D764-48F2-8AA5-AF20C04C3D0E}', 'stripped_OID': '1E9C0A87-D764-48F2-8AA5-AF20C04C3D0E', 'login': '', 'broadcast_episode_title': "Manifestations du 13 mai 1958 : reportages ? Paris et Alger (3/3). Rappel ? l'ordre de Ren? Coty, pr?sident de la R?publique fran?aise et de Pierre Pflimlin, premier ministre", 'sequence': '1', 'broadcast_program_name': 'Miroir du temps', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '09.03.2023 08:47:05', 'physical_support_history': "Cote d'origine: 14387 Pl. C", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': "Ren? Coty rappelle ? l'ordre et ? la discipline les officiers fran?ais en Alg?rie et Pierre Pflimlin nie que la France exerce une politique d'abandon en Alg?rie", 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Coty, Ren?', 'function': "Auteur d'une d?claration", 'role': 'pr?sident de la R?publique fran?aise'}, {'name': 'Inconnu', 'function': 'Pr?sentateur/trice', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Pflimlin, Pierre', 'function': "Auteur d'une d?claration", 'role': 'premier ministre, pr?sident du conseil national fran?ais'}], 'geographical_descriptors': ['Alg?rie', 'France'], 'person_descriptors': ['Coty, Ren?', 'Pflimlin, Pierre'], 'thematical_descriptors': ["guerre d'Alg?rie", 'manifestation politique', 'politique'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['D?claration'], 'recording_dates': ['14/05/1958 - 14/05/1958'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {727C00D6-F2D6-4F5A-A8F1-A7DF8C8D68DE}. Trying to use the recording date. doc_dict: {'alias': 'miroir_temps', 'date_str': None, 'stt_filename': '727C00D6-F2D6-4F5A-A8F1-A7DF8C8D68DE_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{727C00D6-F2D6-4F5A-A8F1-A7DF8C8D68DE}', 'stripped_OID': '727C00D6-F2D6-4F5A-A8F1-A7DF8C8D68DE', 'login': '', 'broadcast_episode_title': "M?morial de l'ann?e 1956 dans le monde des arts et des lettres (1/2)", 'sequence': '1', 'broadcast_program_name': 'Miroir du temps', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'crottari', 'modified_on': '27.05.2022 08:42:34', 'physical_support_history': "Cote d'origine: 11339 Pl. A", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Le Monde o? nous vivons : M?morial. Sauvegarde d'archives", 'content_summary': '1. Fian?ailles de Grace Kelly, actrice am?ricaine avec le prince Rainier III de Monaco. - 2. Mort de Mistinguett, actrice de music-hall et extrait d\'interview sur sa d?finition de la chanson - 3. Mort de El Glaoui, sultan marocain, bref portrait. - 4. Mort de Gustave Charpentier, compositeur de son op?ra comique "Louise" et extrait d\'une de ses oeuvres. - 5. Mort de Paul L?autaud, ?crivain acerbe et misogyne. - 6. Mort de Louis Bromfield, ?crivain retir? dans son ranch aux Etats-Unis. - 7. F?te du bicentenaire de Mozart ? Salzburg, extrait musical (violon du compositeur). - 8. Mort de Ir?ne Joliot-Curie, physicienne qui poursuivit les recherches sur le radium. - 9. Compte-rendu de la c?r?monie de mariage entre Rainer III de Monaco et de Grace Kelly. - 10. 75i?me anniversaire de Pablo Picasso sur la C?te d\'Azur. -11. Grand prix d\'interpr?tation pour Maria Schell re?u pour son r?le Gervaise dans le film "L\'Assomoir" r?alis? par Ren? Cl?ment lors du 17i?me festival du film de Venise. - 12. Mort de Marie Laurencin et extrait d\'interview sur ses palettes de couleurs si particuli?res. - 13. Extrait de discours de la Reine Elisabeth de Belgique : Un de ses rares messages de paix diffus? ? la radio.', 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Inconnu', 'function': 'Pr?sentateur/trice', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Kelly, Grace', 'function': 'Interview?/e', 'role': 'actrice am?ricaine'}, {'name': 'Inconnu', 'function': 'Intervieweur/euse', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Inconnue', 'function': 'Pr?sentateur/trice', 'role': 'collaboratrice Radio-Lausanne'}, {'name': 'Mistinguett', 'function': 'Interview?/e', 'role': 'chanteuse fran?aise'}, {'name': 'El Glaoui, Medhi', 'function': "Auteur d'une d?claration", 'role': 'pacha de Marrakech'}, {'name': 'L?autaud, Paul', 'function': 'Commentateur/trice', 'role': 'chroniqueur, critique et com?dien fran?ais'}, {'name': 'Bromfield, Louis', 'function': 'Interview?/e', 'role': '?crivain am?ricain'}, {'name': 'Roy, Michel', 'function': 'Intervieweur/euse', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'korner (nom)', 'function': "Auteur d'une d?claration", 'role': 'pr?sident de la R?publique autrichienne'}, {'name': 'Joliot-Curie, Ir?ne', 'function': 'Interview?/e', 'role': 'physicienne'}, {'name': 'Rainier III', 'function': "Auteur d'une d?claration", 'role': 'prince de Monaco'}, {'name': 'Barthe ( Monseigneur)', 'function': 'R?citant/e', 'role': '?v?que de Monaco'}, {'name': 'Inconnu', 'function': 'Commentateur/trice', 'role': 'reporter ? Monaco'}, {'name': 'Picasso, Pablo', 'function': 'Interview?/e', 'role': 'peintre espagnol'}, {'name': 'Madoura (nom)', 'function': 'Interview?/e', 'role': None}, {'name': 'Schell, Maria', 'function': 'Interview?/e', 'role': 'actrice'}, {'name': 'Inconnu', 'function': 'Intervieweur/euse', 'role': 'journaliste'}, {'name': 'Laurencin, Marie', 'function': 'Interview?/e', 'role': 'peintre'}, {'name': 'Elisabeth de Belgique', 'function': "Auteur d'une d?claration", 'role': 'reine de Belgique'}, {'name': 'Rosier, Jane', 'function': 'Intervieweur/euse', 'role': 'collaboratrice Radio-Lausanne'}], 'geographical_descriptors': ['Monaco', 'Paris', "C?te d'Azur"], 'person_descriptors': ['Kelly, Grace', 'Mistinguett', 'Rainier III', 'El Glaoui, Mehdi', 'Charpentier, Gustave', 'L?autaud, Paul', 'Bromfield, Louis', 'Joliot-Curie, Ir?ne', 'Picasso, Pablo', 'Laurencin, Marie', 'Elisabeth de Belgique'], 'thematical_descriptors': ['mariage', 'noblesse', 'music-hall', 'chanson fran?aise', 'op?ra comique', 'compositeur', '?crivain', 'd?couverte scientifique', 'radium', 'festival de cin?ma', 'paix', 'd?c?s'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Interview', 'Commentaire'], 'recording_dates': ['29/12/1956 - 29/12/1956'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {B6DB1992-9B7B-4BAD-ACA3-DE08AD06A723}. Trying to use the recording date. doc_dict: {'alias': 'miroir_temps', 'date_str': None, 'stt_filename': 'B6DB1992-9B7B-4BAD-ACA3-DE08AD06A723_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{B6DB1992-9B7B-4BAD-ACA3-DE08AD06A723}', 'stripped_OID': 'B6DB1992-9B7B-4BAD-ACA3-DE08AD06A723', 'login': '', 'broadcast_episode_title': 'Miroir du temps : ?mission sp?ciale 2000?me (1/2). R?trospective et anecdotes par les journalistes et correspondants de Radio-Lausanne', 'sequence': '1', 'broadcast_program_name': 'Miroir du temps', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '08.03.2023 17:44:50', 'physical_support_history': "Cote d'origine: 9700 A", 'production_type': 'Production propre', 'recording_place': 'Lausanne. Paris. Rome', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives. Jura", 'content_summary': "Historique de l'?mission, traitement de l'actualit? dans le contexte de la guerre, puis grand changement ? partir du moment ou les journalistes deviennent reporters. Les premiers correspondants du Miroir du temps, une grande aventure. R?cit de plusieurs anecdotes de reportages ? travers le monde et de leur r?ception ? Radio-Lausanne. Le d?calage entre la vie dangereuse des reporters et celle du r?dacteur et des auditeurs.  L'accueil des journalistes ? l'?tranger, les rencontres et relations avec les indig?nes.  Les al?as des interviews de personnages importants. Le meilleur souvenir des correspondants de Radio-Lausanne. La fraternit? entre les journalistes du Miroir du temps. Anecdotes et hommage ? leur courage.", 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Nordmann, Roger (homme de radio)', 'function': 'Commentateur/trice', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Favrod, Charles-Henri', 'function': 'Commentateur/trice', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Gigon, Fernand', 'function': 'Commentateur/trice', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Romieux, Benjamin', 'function': 'Commentateur/trice', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Zbinden, Louis-Albert', 'function': 'Commentateur/trice', 'role': 'correspondant Radio-Lausanne ? Paris'}, {'name': 'Mairet, Claude (journaliste)', 'function': 'Commentateur/trice', 'role': 'correspondant Radio-Lausanne ? Paris'}, {'name': 'Rabaud, Jean', 'function': 'Commentateur/trice', 'role': 'correspondant Radio-Lausanne ? Paris'}, {'name': 'Pasetti, John', 'function': 'Commentateur/trice', 'role': 'correspondant Radio-Lausanne ? Rome'}, {'name': 'Ferrier, Jacques', 'function': 'Commentateur/trice', 'role': 'correspondant Radio-Lausanne ? Bonn'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': ['information', 'journalisme', 'reportage (technique)', 'journaliste', 'radio', '?mission de radio'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Premier programme'], 'subdomains': ['Commentaire'], 'recording_dates': ['24/08/1956 - 24/08/1956'], 'first_broadcast_dates': None}

100%|██████████| 1/1 [00:00<00:00,  2.91it/s]
34it [02:23,  4.17s/it]

Starting extracting 58 documents for program monde_ant
Skipping document 40/58 with OID {C0CC88F3-41BE-436B-BEA8-FE919717E729} because it's missing its XML file!! (stt exists: False)
Skipping document 44/58 with OID {AB7FAD8E-5B30-49AD-A69D-884DF0ECE7FF} because it's missing its XML file!! (stt exists: False)
Skipping document 46/58 with OID {37165753-F955-43E5-A74C-27C4F1CEE407} because it's missing its XML file!! (stt exists: False)
Skipping document 51/58 with OID {2DAF91F6-C90F-41DC-8E52-B8CB2A44DECE} because it's missing its XML file!! (stt exists: False)
Skipping document 52/58 with OID {FC3CD100-A590-4AD2-A8DC-1CD2B1DF9976} because it's missing its XML file!! (stt exists: False)
Skipping document 56/58 with OID {533580B8-F8AB-409A-A29F-FED15F4A279B} because it's missing its XML file!! (stt exists: False)
Skipping document 58/58 with OID {9A440AFE-AA25-4D38-90FF-476267D61E98} because it's missing its XML file!! (stt exists: False)
monde_ant - returning 51 documents, 7 were skipped due to missing necessary info.
 --> Adding 51 to the out csv for monde_ant

PROCESSING PROGRAM monde_sem (35/47) - 1 files:

Starting extracting 81 documents for program monde_sem
Did not find any date for doc with OID {3704418C-4687-4D9E-A965-08B4AC14E091}. Trying to use the recording date. doc_dict: {'alias': 'monde_sem', 'date_str': None, 'stt_filename': '3704418C-4687-4D9E-A965-08B4AC14E091_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{3704418C-4687-4D9E-A965-08B4AC14E091}', 'stripped_OID': '3704418C-4687-4D9E-A965-08B4AC14E091', 'login': '', 'broadcast_episode_title': "1. Annonce du mariage du Prince Rainier avec l'actrice am?ricaine, Grace Kelly. - 2. Ind?pendance du Maroc : le gouvernement provisoire entame les n?gociations de modalit?. - 3. Le pape Pie XII s'exprime devant 700 gyn?cologues sur l'accouchement sans douleur. - 4. Obs?ques de la chanteuse fran?aise et vedette de music-hall Mistinguett. - 5. Rencontre entre le r?sident g?n?ral du Maroc, Henri Dubois, et le lieutenant Garcia Valino, haut commissai", 'sequence': '1', 'broadcast_program_name': 'Monde cette semaine', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'quartian', 'modified_on': '11.06.2022 00:25:30', 'physical_support_history': "Cote d'origine: 9611", 'production_type': 'Production propre', 'recording_place': 'Lausanne ; Paris ; Bonn', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': "1. Br?ve pr?sentation de la famille de Grace Kelly et courte allocution du prince annon?ant son mariage. - 2. Commentaires de jeunes ministres marocains sur l'ind?pendance de leur pays et les bonnes relations qu'ils entretiennent avec la France. - 4. T?moignage de Fernandel. - 5. Entretien qui marque un climat de d?tente entre le Maroc et la France. - 6. Opposition de la Jordanie ? la signature du pacte de Bagdad soutenu par les britanniques. - 7. Les socialistes fran?ais sont contre une adh?sion des communistes ? leur parti. Allocution des principaux chefs des partis socialistes et communistes sur le contenu de leurs programmes politiques - 8. Le pr?sident br?silien Kubitschek rencontre les chefs d'?tat europ?en afin de resserrer les liens diplomates et finanicers. - 10. Paul Moguin, collaborateur de Radio-France, pr?sente la nouvelle arm?e intronis?e par le chancelier allemand Adenauer en pr?sence du ministre de la d?fense.", 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Inconnu', 'function': 'Pr?sentateur/trice', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Rainier III', 'function': "Auteur d'une d?claration", 'role': 'prince de Monaco'}, {'name': 'Inconnu', 'function': 'Commentateur/trice', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Fernandel', 'function': 'Interview?/e', 'role': 'acteur fran?ais'}, {'name': 'Inconnu', 'function': 'Intervieweur/euse', 'role': 'collaborateur Radio-Lausanne ? Paris'}, {'name': 'Bouabid, Abderrahim', 'function': 'Interview?/e', 'role': 'ministre marocain'}, {'name': 'Inconnu', 'function': 'Intervieweur/euse', 'role': 'collaborateur Radio-Lausanne'}, {'name': 'Mend?s France, Pierre', 'function': 'Interview?/e', 'role': 'homme politique fran?ais'}, {'name': 'Duclos, Jacques', 'function': 'Interview?/e', 'role': 'homme politique fran?ais'}, {'name': 'Pinay, Antoine', 'function': "Auteur d'une d?claration", 'role': 'homme politique fran?ais'}, {'name': 'Mairet, Claude (journaliste)', 'function': 'Intervieweur/euse', 'role': 'collaborateur Radio-Lausanne ? Paris'}, {'name': 'Poujade, Pierre', 'function': "Auteur d'une d?claration", 'role': 'homme politique fran?ais'}, {'name': 'Kubitschek, Juscelino', 'function': "Auteur d'une d?claration", 'role': 'pr?sident du Br?sil'}, {'name': 'Moguin, Paul', 'function': 'Commentateur/trice', 'role': 'collaborateur Radio-France ? Bonn'}, {'name': 'Adenauer, Konrad', 'function': "Auteur d'une d?claration", 'role': 'chancelier allemand'}], 'geographical_descriptors': ['Monaco', 'France', 'Maroc', 'Jordanie', 'Angleterre', 'Br?sil', 'Allemagne'], 'person_descriptors': ['Rainier III', 'Kelly, Grace', 'Pie XII', 'Mistinguett', 'Mend?s France, Pierre', 'Mollet, Guy', 'Kubitschek, Juscelino', 'Adenauer, Konrad'], 'thematical_descriptors': ['mariage', 'noblesse', 'ind?pendantisme', 'relations internationales', 'politique internationale', 'accouchement', 'gyn?cologie', 'music-hall', 'chanteuse', 'politique', '?lection l?gislative', 'parti politique', 'guerre froide', 'arm?e', 'c?r?monie publique'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['D?claration', 'Commentaire', 'Interview'], 'recording_dates': ['22/01/1956 - 22/01/1956'], 'first_broadcast_dates': None}
The date for document with OID {1907982C-1266-4EDC-87F4-5833BB0C7852} was invalid (__/__/1956) - changed it to 01/01/1956
The date for document with OID {1907982C-1266-4EDC-87F4-5833BB0C7852} was invalid (__/__/1956) - changed it to 01/01/1956
Skipping document 6/81 with OID {F3ECB22B-C0DA-4423-A0B1-58C26EB9DEF8} because it's missing its XML file!! (stt exists: False)
Skipping document 7/81 with OID {D7CD10D7-C6C9-42F6-8DE6-59B183A9BB65} because it's missing its XML file!! (stt exists: False)
Skipping document 8/81 with OID {4D98022C-B3F5-4921-93AF-B6E715DA1AD7} because it's missing its XML file!! (stt exists: False)
Skipping document 9/81 with OID {816BB15A-534A-4402-8B58-BE85C64314EC} because it's missing its XML file!! (stt exists: False)
Skipping document 11/81 with OID {317FDBAC-7755-4165-AC75-C94FC709B80B} because it's missing its XML file!! (stt exists: False)
Skipping document 12/81 with OID {AE197F82-3B49-45FE-A3FE-CEC3D7B83CC6} because it's missing its XML file!! (stt exists: False)
Skipping document 13/81 with OID {12A3E7A7-F54F-46DC-B908-D8C93803509E} because it's missing its XML file!! (stt exists: False)
Skipping document 14/81 with OID {3307A3DC-4F99-47D4-AA50-62DB9BB76FBE} because it's missing its XML file!! (stt exists: False)
Skipping document 15/81 with OID {F1F702F2-7E6D-4896-9C99-659BD5F0001C} because it's missing its XML file!! (stt exists: False)
Skipping document 16/81 with OID {31124110-7BB0-4493-B555-67F049227EFE} because it's missing its XML file!! (stt exists: False)
Skipping document 17/81 with OID {30BDE62E-EB01-4438-9A79-795419449FCA} because it's missing its XML file!! (stt exists: False)
Skipping document 18/81 with OID {77CAD11E-2FB1-4008-86AB-7B578B422FF2} because it's missing its XML file!! (stt exists: False)
Skipping document 19/81 with OID {98C47EA7-93D5-4428-9D4E-7DDBA7F81C1A} because it's missing its XML file!! (stt exists: False)
Skipping document 20/81 with OID {EE21D8C7-23F2-439A-849B-83E8A2E8B14B} because it's missing its XML file!! (stt exists: False)
Skipping document 21/81 with OID {AC0C52DA-B89E-4DD9-B4DB-288663D7D135} because it's missing its XML file!! (stt exists: False)
Skipping document 22/81 with OID {827FFE63-CB23-43CD-A770-379C06899042} because it's missing its XML file!! (stt exists: False)
Skipping document 23/81 with OID {AED5DAB5-10FE-403C-BFAA-3C7B53528A41} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {DD9F8770-B983-4938-97D8-3F3309891AB5}. Trying to use the recording date. doc_dict: {'alias': 'monde_sem', 'date_str': None, 'stt_filename': 'DD9F8770-B983-4938-97D8-3F3309891AB5_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{DD9F8770-B983-4938-97D8-3F3309891AB5}', 'stripped_OID': 'DD9F8770-B983-4938-97D8-3F3309891AB5', 'login': '', 'broadcast_episode_title': "Passage en revue de l'actualit? de la semaine", 'sequence': '1', 'broadcast_program_name': 'Monde cette semaine', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'vonimhma', 'modified_on': '20.07.2022 17:32:19', 'physical_support_history': "Cote d'origine: 9515. Texte complet dans carton", 'production_type': 'Production propre', 'recording_place': 'Lausanne (Studio Radio-Lausanne)', 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Romieux, Benjamin', 'function': 'Pr?sentateur/trice', 'role': 'collaborateur Radio-Lausanne'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': ['politique internationale'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Premier programme'], 'subdomains': ['Parl? divers'], 'recording_dates': ['07/04/1956 - 07/04/1956'], 'first_broadcast_dates': None}

100%|██████████| 1/1 [00:00<00:00,  3.52it/s]
35it [02:23,  3.05s/it]

Skipping document 25/81 with OID {6AACBAE3-1C54-4B44-BFA2-437083CFB22A} because it's missing its XML file!! (stt exists: False)
Skipping document 26/81 with OID {20FB06CE-CB2A-4B49-A6B2-46EEDA02D2DC} because it's missing its XML file!! (stt exists: False)
Skipping document 27/81 with OID {14E5F18D-A48E-417D-BFE9-4CA9799E593C} because it's missing its XML file!! (stt exists: False)
Skipping document 28/81 with OID {AFC289FA-0E59-4D63-A97B-0998EE33C469} because it's missing its XML file!! (stt exists: False)
Skipping document 29/81 with OID {FC0242D8-2954-4F8C-AE0A-1318728426F8} because it's missing its XML file!! (stt exists: False)
Skipping document 30/81 with OID {45164427-E07B-482D-9B69-AC7A7F5B5FBE} because it's missing its XML file!! (stt exists: False)
Skipping document 31/81 with OID {A3533F6F-8995-41D2-9284-D31EC1936210} because it's missing its XML file!! (stt exists: False)
Skipping document 32/81 with OID {2A637D36-212E-485F-8E60-17CBE6D470F8} because it's missing its XML file!! (stt exists: False)
Skipping document 33/81 with OID {A53B6D6B-C49A-472B-AAAE-1CD3AB759275} because it's missing its XML file!! (stt exists: False)
Skipping document 34/81 with OID {AD7FF54D-385E-4203-9070-25D105160EC4} because it's missing its XML file!! (stt exists: False)
Skipping document 35/81 with OID {F0488751-820A-4956-9162-8871D228AC62} because it's missing its XML file!! (stt exists: False)
Skipping document 36/81 with OID {52DE6795-078F-4687-B061-95D609572F45} because it's missing its XML file!! (stt exists: False)
Skipping document 37/81 with OID {5940330F-3529-484D-A610-9B2A72353BE6} because it's missing its XML file!! (stt exists: False)
Skipping document 38/81 with OID {A907EAA6-A7A5-42F5-AE64-B5186A98E079} because it's missing its XML file!! (stt exists: False)
Skipping document 39/81 with OID {1DC34F89-A4F1-42AE-97E9-B6BBD64BC7A8} because it's missing its XML file!! (stt exists: False)
Skipping document 40/81 with OID {3A2AC54B-D6F0-43CE-8C5A-BB1F6AB10AB2} because it's missing its XML file!! (stt exists: False)
Skipping document 41/81 with OID {236A1DA6-C037-424B-AD99-C6D1EB203028} because it's missing its XML file!! (stt exists: False)
Skipping document 42/81 with OID {8923FEE2-8C92-4577-BCF6-DBB1208DD8A0} because it's missing its XML file!! (stt exists: False)
Skipping document 43/81 with OID {9A677962-2EDD-4610-84BE-01A843734968} because it's missing its XML file!! (stt exists: False)
Skipping document 44/81 with OID {B96EA4CE-D867-4E48-90F9-0614EAD05CC5} because it's missing its XML file!! (stt exists: False)
Skipping document 45/81 with OID {9033F970-1A27-4E53-8249-100611ACC85D} because it's missing its XML file!! (stt exists: False)
Skipping document 46/81 with OID {1ACBB255-48AD-4C3C-839D-166415DAB78D} because it's missing its XML file!! (stt exists: False)
Skipping document 47/81 with OID {CF67AE3D-88B5-45E1-9C71-1830F96F6124} because it's missing its XML file!! (stt exists: False)
Skipping document 48/81 with OID {2FBA84F0-0C30-4933-A626-203C6F9CEA77} because it's missing its XML file!! (stt exists: False)
Skipping document 49/81 with OID {4CFB1F28-8500-443E-820F-2A187244214C} because it's missing its XML file!! (stt exists: False)
Skipping document 51/81 with OID {36458ED9-DDE3-41B8-B1AB-3E4401F68E8C} because it's missing its XML file!! (stt exists: False)
Skipping document 52/81 with OID {0934971F-F41D-4B20-A2C4-412DC4AF9622} because it's missing its XML file!! (stt exists: False)
Skipping document 53/81 with OID {55EEE580-E4EE-4C73-85CE-464C2CD49204} because it's missing its XML file!! (stt exists: False)
Skipping document 54/81 with OID {9112DC7D-9B07-4773-A862-4BA48303AA68} because it's missing its XML file!! (stt exists: False)
Skipping document 55/81 with OID {86C5CCF1-C15A-42BD-A544-52534722F9A5} because it's missing its XML file!! (stt exists: False)
Skipping document 56/81 with OID {190B7180-3B34-4B3D-AE7A-4ECE93CC1634} because it's missing its XML file!! (stt exists: False)
Skipping document 57/81 with OID {E9B695C1-79F0-4DCA-A40A-551C0A8D1B2A} because it's missing its XML file!! (stt exists: False)
Skipping document 58/81 with OID {D971BB22-D706-4DDA-8F26-597EDB1C0322} because it's missing its XML file!! (stt exists: False)
Skipping document 59/81 with OID {728E5F33-CDD8-4ED0-8D74-5D7FF3C641E6} because it's missing its XML file!! (stt exists: False)
Skipping document 60/81 with OID {FFDD4F3A-4A5B-47E6-B9E9-6555E4C65613} because it's missing its XML file!! (stt exists: False)
Skipping document 61/81 with OID {65C68807-5CB3-447A-826A-665CC280DDC9} because it's missing its XML file!! (stt exists: False)
Skipping document 62/81 with OID {D55D8880-3286-4EA7-BBCF-72F2E9F28992} because it's missing its XML file!! (stt exists: False)
Skipping document 63/81 with OID {55DD0FEF-E1F0-4044-B17D-79EBB3109C5D} because it's missing its XML file!! (stt exists: False)
Skipping document 64/81 with OID {2716ACC5-1F1D-4206-AD93-7CC7ED182364} because it's missing its XML file!! (stt exists: False)
Skipping document 65/81 with OID {40944AF0-726B-4F4D-8F4D-827C64042E1B} because it's missing its XML file!! (stt exists: False)
Skipping document 66/81 with OID {5E3B04C9-900F-4787-B0B6-865EF368406B} because it's missing its XML file!! (stt exists: False)
Skipping document 67/81 with OID {57EB593B-5B08-442E-8BCC-8C3FED945743} because it's missing its XML file!! (stt exists: False)
Skipping document 68/81 with OID {5CC62B12-3471-4C60-97D6-9A277C5263FC} because it's missing its XML file!! (stt exists: False)
Skipping document 69/81 with OID {1058E4EC-4088-4AED-A9D5-A00BBD62CA42} because it's missing its XML file!! (stt exists: False)
Skipping document 70/81 with OID {81D119DA-F64E-42C3-97C0-9C8B2D253B8E} because it's missing its XML file!! (stt exists: False)
Skipping document 71/81 with OID {24536CB9-9ECF-48E0-9FEF-A14D410FB42B} because it's missing its XML file!! (stt exists: False)
Skipping document 72/81 with OID {04E72A1A-22A6-40B6-AD17-A3D8CF961D2D} because it's missing its XML file!! (stt exists: False)
Skipping document 73/81 with OID {23C47FE0-0ED0-4097-B403-AE886360FC87} because it's missing its XML file!! (stt exists: False)
Skipping document 74/81 with OID {7479EA3A-2D75-4CFF-915B-569EE59DB01D} because it's missing its XML file!! (stt exists: False)
Skipping document 75/81 with OID {A37BAACC-71C4-456C-8535-05E2F0CADFFA} because it's missing its XML file!! (stt exists: False)
Skipping document 76/81 with OID {8AA54108-1EF1-4E97-B6E1-018F97E50E9F} because it's missing its XML file!! (stt exists: False)
Skipping document 77/81 with OID {ED3E6E1F-9D1D-4AC3-AC2C-F3980FA610A1} because it's missing its XML file!! (stt exists: False)
Skipping document 78/81 with OID {C249073E-3DF8-4B21-B0B1-FDB3F1D0A16C} because it's missing its XML file!! (stt exists: False)
Skipping document 80/81 with OID {537E0E81-330F-4B90-980D-B55B15E462BE} because it's missing its XML file!! (stt exists: False)
Skipping document 81/81 with OID {F4EFBBAD-8040-4728-8DF7-F57089678AAB} because it's missing its XML file!! (stt exists: False)
monde_sem - returning 9 documents, 72 were skipped due to missing necessary info.
 --> Adding 9 to the out csv for monde_sem

PROCESSING PROGRAM nickel (36/47) - 1 files:

Starting extracting 242 documents for program nickel
Skipping document 2/242 with OID {5769D04F-0CE9-4BE3-B998-DF0E8860D8AE} because it's missing its XML file!! (stt exists: False)
Skipping document 4/242 with OID {A33DB8B5-7FA6-445A-90F6-F0FE58C12C52} because it's missing its XML file!! (stt exists: False)
Skipping document 5/242 with OID {680E5849-2697-444C-8F55-0BEC4EF800F0} because it's missing its XML file!! (stt exists: False)
Skipping document 8/242 with OID {9AEDCB5E-CBDE-4C16-9764-91E3FE8DA87C} because it's missing its XML file!! (stt exists: False)
Skipping document 9/242 with OID {B5AF82A8-DA98-4219-84E7-2DA936A942B0} because it's missing its XML file!! (stt exists: False)
Skipping document 10/242 with OID {884460F0-B1AA-40DB-ADA5-63FFE6474BFE} because it's missing its XML file!! (stt exists: False)
Skipping document 13/242 with OID {B478501F-B552-4D3E-91AE-CB7DF61B9467} because it's missing its XML file!! (stt exists: False)
Skipping document 14/242 with OID {71A1E0D5-3B6E-4CA8-ABF2-D449D9661820} because it's missing its XML file!! (stt exists: False)
Skipping document 18/242 with OID {F6424203-372C-40F8-BFC4-25A960EEA8DA} because it's missing its XML file!! (stt exists: False)
Skipping document 20/242 with OID {25B3246E-2890-429A-ABAB-2E329019E580} because it's missing its XML file!! (stt exists: False)
Skipping document 21/242 with OID {94E3CBB1-3FA5-4538-8A32-4029B77833A0} because it's missing its XML file!! (stt exists: False)
Skipping document 22/242 with OID {08D5A533-DDC6-475E-A7A9-0DB1312D849E} because it's missing its XML file!! (stt exists: False)
Skipping document 23/242 with OID {4BB88BF7-A7E3-440E-98BB-6CF93F7722A0} because it's missing its XML file!! (stt exists: False)
Skipping document 24/242 with OID {6D826826-53A9-479E-88DB-4B3CDE033DF8} because it's missing its XML file!! (stt exists: False)
Skipping document 44/242 with OID {CA51F442-2B51-452C-A67B-A92A03442DE4} because it's missing its XML file!! (stt exists: False)
Skipping document 54/242 with OID {35670D42-41DD-4B34-A548-217ACCA29514} because it's missing its XML file!! (stt exists: False)
Skipping document 69/242 with OID {2C83F1B5-D148-4757-A2B2-2BAE33612CAA} because it's missing its XML file!! (stt exists: False)
Skipping document 73/242 with OID {D1407FA3-2724-4EA2-B520-F797A25BAB27} because it's missing its XML file!! (stt exists: False)
Skipping document 84/242 with OID {FDAD6113-927A-4B11-8A87-724BFC4CB512} because it's missing its XML file!! (stt exists: False)
Skipping document 89/242 with OID {E097F03F-A844-451E-8579-8350D351BB04} because it's missing its XML file!! (stt exists: False)
Skipping document 90/242 with OID {1FD3FDA5-DD7F-4907-84D1-291C2796C35E} because it's missing its XML file!! (stt exists: False)
Skipping document 93/242 with OID {EBD920FB-1701-4D99-B0B1-CB947D0EC460} because it's missing its XML file!! (stt exists: False)
Skipping document 107/242 with OID {B67E267F-EAAD-4E50-ABAB-F3B6AB1F359C} because it's missing its XML file!! (stt exists: False)
Skipping document 115/242 with OID {FE314F86-AC59-4494-84B2-AD093883CCC0} because it's missing its XML file!! (stt exists: False)
Skipping document 118/242 with OID {BB1575E5-3FA0-4D00-833C-CB87B79A6C58} because it's missing its XML file!! (stt exists: False)
Skipping document 143/242 with OID {055896FB-7F79-45C0-83E3-E9D693DE4F5E} because it's missing its XML file!! (stt exists: False)
Skipping document 144/242 with OID {A7C259D7-14B6-46C6-9B92-6168BDA690AA} because it's missing its XML file!! (stt exists: False)
Skipping document 145/242 with OID {CDE2E6D1-BBD5-422A-AE5D-4EE0B6C71AB1} because it's missing its XML file!! (stt exists: False)
Skipping document 146/242 with OID {FF9FE8F2-85CB-4909-ACB2-AE61ECF490A7} because it's missing its XML file!! (stt exists: False)
Skipping document 147/242 with OID {EE6B2C2F-D823-4AB0-9ADC-545EA9F27132} because it's missing its XML file!! (stt exists: False)
Skipping document 148/242 with OID {E32AA5EF-193E-40B2-B47C-F8EC1E94CBC7} because it's missing its XML file!! (stt exists: False)
Skipping document 149/242 with OID {0152F564-DA95-4AD7-B43D-33443001D115} because it's missing its XML file!! (stt exists: False)
Skipping document 150/242 with OID {B445450C-4EC1-4481-AD00-D143A9605F43} because it's missing its XML file!! (stt exists: False)
Skipping document 153/242 with OID {2D5A8567-02F2-4E94-ACA9-94085CC1F216} because it's missing its XML file!! (stt exists: False)
Skipping document 157/242 with OID {7EE90FFD-6490-43E7-9816-4549C72F755C} because it's missing its XML file!! (stt exists: False)
Skipping document 158/242 with OID {4C8E7CFA-D1AE-4360-BE18-EC25A8F0839C} because it's missing its XML file!! (stt exists: False)
Skipping document 159/242 with OID {B7F4D748-8F27-41AE-8F61-E5D4453133FB} because it's missing its XML file!! (stt exists: False)
Skipping document 160/242 with OID {5FF2D11F-8E85-4012-9789-6842483BED79} because it's missing its XML file!! (stt exists: False)
Skipping document 161/242 with OID {2DBD16E1-5C0E-47E5-B9CD-C2BBD3C2547F} because it's missing its XML file!! (stt exists: False)
Skipping document 162/242 with OID {29FE2CDD-8AF5-49B7-9DF4-7A5A2FB2EDB3} because it's missing its XML file!! (stt exists: False)
Skipping document 163/242 with OID {B0EEDCC3-2543-4820-9BF5-A5768562DDDF} because it's missing its XML file!! (stt exists: False)
Skipping document 164/242 with OID {6C7E1AE8-732B-4CC3-B79F-BB478A42F0BD} because it's missing its XML file!! (stt exists: False)
Skipping document 165/242 with OID {DDBF12DD-591F-418E-9E57-1414323E6351} because it's missing its XML file!! (stt exists: False)
Skipping document 166/242 with OID {0AAFC65D-1BC3-4FDF-8142-A12FA4B05A7F} because it's missing its XML file!! (stt exists: False)
Skipping document 167/242 with OID {A5FDA560-F87D-4A1B-906A-4E134DBD7444} because it's missing its XML file!! (stt exists: False)
Skipping document 168/242 with OID {1812AEBA-623B-47B2-B757-C417E75CA7F5} because it's missing its XML file!! (stt exists: False)
Skipping document 169/242 with OID {083359AE-80F2-4725-806C-1526CEDF2CAA} because it's missing its XML file!! (stt exists: False)
Skipping document 170/242 with OID {BBFA1F5A-C1CC-4126-8CF0-649CA55F4F2C} because it's missing its XML file!! (stt exists: False)
Skipping document 171/242 with OID {62DF4A7F-AD52-47C0-B5DB-C8A764A2ABC2} because it's missing its XML file!! (stt exists: False)
Skipping document 173/242 with OID {347CBEDB-98D8-46D1-B1CA-15A111108435} because it's missing its XML file!! (stt exists: False)
Skipping document 174/242 with OID {544038A7-D625-4BB7-AE62-5F6BCD568C92} because it's missing its XML file!! (stt exists: False)
Skipping document 175/242 with OID {0F46D4CF-AE17-4CDB-AA21-2F80AA635DEA} because it's missing its XML file!! (stt exists: False)
Skipping document 176/242 with OID {FD2E37D9-AB8D-4691-BF6F-355DB0498B05} because it's missing its XML file!! (stt exists: False)
Skipping document 177/242 with OID {6196C70D-C04E-4841-A578-BEF833997992} because it's missing its XML file!! (stt exists: False)
Skipping document 178/242 with OID {B4FB05A6-0F7D-4DD1-81ED-4F2BE16C52A2} because it's missing its XML file!! (stt exists: False)
Skipping document 180/242 with OID {9FFBF2FE-71F6-46B3-8779-2BFA806A7459} because it's missing its XML file!! (stt exists: False)
Skipping document 181/242 with OID {ACA6C8C4-461C-4E40-9D0D-FDAFF080C264} because it's missing its XML file!! (stt exists: False)
Skipping document 182/242 with OID {828A972E-16DE-45F1-99D9-DE29312004CC} because it's missing its XML file!! (stt exists: False)
The date for document with OID {9462672B-9BA5-4FFD-8912-181BAB0FBC2D} was invalid (__/02/1994) - changed it to 01/02/1994
The date for document with OID {9462672B-9BA5-4FFD-8912-181BAB0FBC2D} was invalid (__/02/1994) - changed it to 01/02/1994
Skipping document 184/242 with OID {280341DD-4AC7-478F-A51C-74B63354B119} because it's missing its XML file!! (stt exists: False)
Skipping document 185/242 with OID {668A8266-E1B1-4C57-A70E-1E6D3637669D} because it's missing its XML file!! (stt exists: False)
Skipping document 186/242 with OID {770EDC08-A88F-419C-A0AA-2578AC258C5A} because it's missing its XML file!! (stt exists: False)
Skipping document 187/242 with OID {ABB3879A-4BD0-4475-A408-A77EAD2BB073} because it's missing its XML file!! (stt exists: False)
Skipping document 188/242 with OID {AFFB2B0C-1914-436A-8942-070DF3A4D44D} because it's missing its XML file!! (stt exists: False)
Skipping document 191/242 with OID {A7E3FBDA-57B2-41E9-8650-90E5B8BE1A15} because it's missing its XML file!! (stt exists: False)
Skipping document 192/242 with OID {53B78576-D931-43C9-B8CA-F367990D258B} because it's missing its XML file!! (stt exists: False)
Skipping document 193/242 with OID {D034319A-63F5-447E-A955-8C3AC9571A96} because it's missing its XML file!! (stt exists: False)
Skipping document 194/242 with OID {354A6C99-40C0-4605-8109-ABFF7F7333C7} because it's missing its XML file!! (stt exists: False)
Skipping document 196/242 with OID {E5BE2C5E-9800-42F3-9A7B-0E7F40EEB2AE} because it's missing its XML file!! (stt exists: False)
Skipping document 197/242 with OID {47199878-10F2-41CE-9841-2834029D102E} because it's missing its XML file!! (stt exists: False)
Skipping document 198/242 with OID {EC17E0FF-4A28-4FB6-A992-BA4626A76AB5} because it's missing its XML file!! (stt exists: False)
Skipping document 199/242 with OID {0F8A13F9-10A7-4573-AB17-283403FD06EB} because it's missing its XML file!! (stt exists: False)
Skipping document 200/242 with OID {49C6408F-95A1-48E1-81AB-F419787285B2} because it's missing its XML file!! (stt exists: False)
Skipping document 201/242 with OID {C50AB800-8AD0-4998-98F4-D3D97A9C450A} because it's missing its XML file!! (stt exists: False)
Skipping document 202/242 with OID {0D245B52-B429-4313-8F25-E96D29316F99} because it's missing its XML file!! (stt exists: False)
Skipping document 203/242 with OID {85AFA006-7F57-4714-AE5E-BDB611EE2F05} because it's missing its XML file!! (stt exists: False)
Skipping document 204/242 with OID {3FB1CC55-2C40-43C4-B6C3-B21B89ACDBA2} because it's missing its XML file!! (stt exists: False)
Skipping document 205/242 with OID {B4641EB9-1373-4832-88AF-230579676CC2} because it's missing its XML file!! (stt exists: False)
Skipping document 207/242 with OID {055ABB24-BC58-4239-8501-8AF502A10238} because it's missing its XML file!! (stt exists: False)
Skipping document 208/242 with OID {7BCE146C-7B8B-4F1D-AFEA-CCAEF4E94FAE} because it's missing its XML file!! (stt exists: False)
Skipping document 209/242 with OID {2B041ED5-DA76-4C06-87BA-2AC66A521097} because it's missing its XML file!! (stt exists: False)
Skipping document 212/242 with OID {06B94D64-1A28-40CD-AB26-AB3F0DC32649} because it's missing its XML file!! (stt exists: False)
Skipping document 214/242 with OID {0C8E9DE7-96E0-4E0C-BA0C-4192557F073D} because it's missing its XML file!! (stt exists: False)
Skipping document 215/242 with OID {4C437A2B-31A2-428D-8B95-10CA8CD98947} because it's missing its XML file!! (stt exists: False)
Skipping document 216/242 with OID {A49F4E5A-C3AE-40CF-B6D5-85109B081AB4} because it's missing its XML file!! (stt exists: False)
Skipping document 218/242 with OID {0FB830F3-B912-418D-A5E2-73D961E69D07} because it's missing its XML file!! (stt exists: False)
Skipping document 219/242 with OID {88817AF5-809F-42AC-AB82-E584621924AC} because it's missing its XML file!! (stt exists: False)
Skipping document 220/242 with OID {1D52D316-98C9-4582-AD4E-7F1A4BFB0FD6} because it's missing its XML file!! (stt exists: False)
Skipping document 221/242 with OID {63F0CE03-0228-4D2D-B739-F11284224889} because it's missing its XML file!! (stt exists: False)
Skipping document 222/242 with OID {E92ECB50-EA62-4C93-9201-49C2B0CC8C77} because it's missing its XML file!! (stt exists: False)
Skipping document 223/242 with OID {F8D9E54A-C614-474E-8172-DF67AD507A8E} because it's missing its XML file!! (stt exists: False)
Skipping document 224/242 with OID {224BD9AB-C4D3-4BE4-AD53-AF875074D980} because it's missing its XML file!! (stt exists: False)
Skipping document 225/242 with OID {83ECA5AB-461D-4165-B63C-FB4F63C46AC5} because it's missing its XML file!! (stt exists: False)
Skipping document 226/242 with OID {49D66390-D54B-42BE-BCB2-B89595608168} because it's missing its XML file!! (stt exists: False)
Skipping document 227/242 with OID {BA0CF3E3-1676-4017-B302-86FD7FF687F3} because it's missing its XML file!! (stt exists: False)
Skipping document 228/242 with OID {B9DFA7C0-198B-4208-AD7E-FA8C12C63CE8} because it's missing its XML file!! (stt exists: False)
Skipping document 229/242 with OID {52577E75-7ECD-409F-BB8E-272B1C82C3B8} because it's missing its XML file!! (stt exists: False)
Skipping document 230/242 with OID {09457B67-E7E1-4802-899E-902463BE8C47} because it's missing its XML file!! (stt exists: False)
Skipping document 231/242 with OID {CFB5EE1D-C672-4638-8982-FDE2B819F841} because it's missing its XML file!! (stt exists: False)

100%|██████████| 1/1 [00:01<00:00,  1.19s/it]
36it [02:24,  2.53s/it]

Skipping document 235/242 with OID {99704260-D88A-446D-9571-BD1212C3170D} because it's missing its XML file!! (stt exists: False)
Skipping document 236/242 with OID {070D29F6-701C-4F99-BE7D-65B3E399F0FA} because it's missing its XML file!! (stt exists: False)
Skipping document 237/242 with OID {2B0B7723-8AF2-490B-A4E5-EA02C3F73D19} because it's missing its XML file!! (stt exists: False)
Skipping document 239/242 with OID {4DC4144D-C275-40B3-89A9-6F65EA7483ED} because it's missing its XML file!! (stt exists: False)
Skipping document 240/242 with OID {53CA36ED-6A03-4CA3-B9A4-2F6219662EF5} because it's missing its XML file!! (stt exists: False)
Skipping document 241/242 with OID {88036E0F-F7EC-4388-AB29-3F6E82AF01AA} because it's missing its XML file!! (stt exists: False)
Skipping document 242/242 with OID {4002C71A-12F3-4AEB-9ECB-2F552CDA02F3} because it's missing its XML file!! (stt exists: False)
nickel - returning 137 documents, 105 were skipped due to missing necessary info.
 --> Adding 137 to the out csv for nickel

PROCESSING PROGRAM nu_parle (37/47) - 1 files:

100%|██████████| 1/1 [00:00<00:00,  2.40it/s]
37it [02:25,  1.92s/it]

Starting extracting 161 documents for program nu_parle
Skipping document 1/161 with OID {8C388577-16E0-4993-9FE6-D603D89504B4} because it's missing its XML file!! (stt exists: False)
Skipping document 2/161 with OID {22E32504-03D2-4216-B9D3-AA150A9737E7} because it's missing its XML file!! (stt exists: False)
Skipping document 3/161 with OID {D55F71E4-BBC1-460C-AB54-61B458D9B626} because it's missing its XML file!! (stt exists: False)
Skipping document 4/161 with OID {A3C6C33D-88C6-4D3F-8BB6-EEB7D50B934D} because it's missing its XML file!! (stt exists: False)
Skipping document 5/161 with OID {1A0F6426-2857-408D-A776-23DC0B60441A} because it's missing its XML file!! (stt exists: False)
Skipping document 6/161 with OID {DBAB511D-FFBF-4188-B035-1AA25E65AB05} because it's missing its XML file!! (stt exists: False)
Skipping document 7/161 with OID {EA29B113-FFBD-4206-92A9-380AD50B754F} because it's missing its XML file!! (stt exists: False)
Skipping document 8/161 with OID {90A0C79C-BB6C-462D-B494-E4493B14615A} because it's missing its XML file!! (stt exists: False)
Skipping document 9/161 with OID {7099126F-D42A-4970-8E22-38F95418F087} because it's missing its XML file!! (stt exists: False)
Skipping document 10/161 with OID {F1ED7198-7ECF-43C9-A9CA-D2C3495C0696} because it's missing its XML file!! (stt exists: False)
Skipping document 11/161 with OID {96293944-5AE6-4F9B-B376-5764CB604832} because it's missing its XML file!! (stt exists: False)
Skipping document 12/161 with OID {0CFDC5B2-5F35-4CD6-A39A-C728492639AA} because it's missing its XML file!! (stt exists: False)
Skipping document 13/161 with OID {4A9730FE-AB4E-4798-8FEA-3B5B265C7710} because it's missing its XML file!! (stt exists: False)
Skipping document 14/161 with OID {29139A97-F38F-43A5-8EA2-08DD54E25916} because it's missing its XML file!! (stt exists: False)
Skipping document 15/161 with OID {3D8CEA7B-E132-4FEA-BA7B-F1A89F28949E} because it's missing its XML file!! (stt exists: False)
Skipping document 16/161 with OID {1B691555-99EB-4AB0-A8DA-008F248CA9B3} because it's missing its XML file!! (stt exists: False)
Skipping document 17/161 with OID {C3BEABE7-506E-4D5C-9134-C8DF7F953893} because it's missing its XML file!! (stt exists: False)
Skipping document 18/161 with OID {1231211D-D680-427D-8395-C6E0B1650C8D} because it's missing its XML file!! (stt exists: False)
Skipping document 19/161 with OID {2DCDD4EB-3DEA-412E-80D9-FF30259393CE} because it's missing its XML file!! (stt exists: False)
Skipping document 20/161 with OID {94F2BB5A-821D-4598-A154-65EC73555931} because it's missing its XML file!! (stt exists: False)
Skipping document 21/161 with OID {74077D56-80A3-46DC-AB77-4F5B051416B2} because it's missing its XML file!! (stt exists: False)
Skipping document 22/161 with OID {84F66982-1676-4C2E-AC8B-394295C5334F} because it's missing its XML file!! (stt exists: False)
Skipping document 23/161 with OID {77BF53D6-8C17-4E86-9154-9FB21367D92B} because it's missing its XML file!! (stt exists: False)
Skipping document 24/161 with OID {F3AB0C0B-FC1D-4A0B-B81D-99641D6C6ACA} because it's missing its XML file!! (stt exists: False)
Skipping document 25/161 with OID {9A913CFF-A11B-4BCF-B98E-60D2F99836B8} because it's missing its XML file!! (stt exists: False)
Skipping document 26/161 with OID {06FCC839-CFEB-4C15-805B-9E4EB009EB6E} because it's missing its XML file!! (stt exists: False)
Skipping document 27/161 with OID {06C269C8-BC00-438A-A6CD-5FEF89C98DE4} because it's missing its XML file!! (stt exists: False)
Skipping document 28/161 with OID {52E70F37-31D2-4428-B104-4D41F67E8FC6} because it's missing its XML file!! (stt exists: False)
Skipping document 29/161 with OID {CBC84A8B-D43B-4C7F-99B5-628513F3E6F5} because it's missing its XML file!! (stt exists: False)
Skipping document 30/161 with OID {FD73F28E-7E48-4444-BC2B-094B0747220D} because it's missing its XML file!! (stt exists: False)
Skipping document 31/161 with OID {1BFEF1B2-AA95-4646-9522-C36D703512E0} because it's missing its XML file!! (stt exists: False)
Skipping document 32/161 with OID {478C9C6F-878F-4D83-9F97-E07E2103E177} because it's missing its XML file!! (stt exists: False)
Skipping document 33/161 with OID {6219E1CA-EC61-40B1-8384-7DB869498D2F} because it's missing its XML file!! (stt exists: False)
Skipping document 34/161 with OID {218D8528-F68B-4583-A4C4-75D1EC795A67} because it's missing its XML file!! (stt exists: False)
Skipping document 35/161 with OID {98584A4C-536B-493C-99A5-9190B398581E} because it's missing its XML file!! (stt exists: False)
Skipping document 36/161 with OID {6EDD8300-82BD-4677-95BB-BCA6BE6A4C39} because it's missing its XML file!! (stt exists: False)
Skipping document 37/161 with OID {7435DA77-BD90-4F95-BB21-BB3A3776B121} because it's missing its XML file!! (stt exists: False)
Skipping document 38/161 with OID {48536CB8-D3D2-4F3C-A884-D148556A00F7} because it's missing its XML file!! (stt exists: False)
Skipping document 39/161 with OID {E709596B-494A-4BCF-A172-E0A107945BD6} because it's missing its XML file!! (stt exists: False)
Skipping document 40/161 with OID {3C2498AA-130A-4387-A346-0347FE1A9335} because it's missing its XML file!! (stt exists: False)
Skipping document 41/161 with OID {9BD89CC8-0212-49AC-BF60-005FB590C2B7} because it's missing its XML file!! (stt exists: False)
Skipping document 42/161 with OID {43B4B949-587C-4F11-9ECA-334CC03C1FA6} because it's missing its XML file!! (stt exists: False)
Skipping document 43/161 with OID {8AC4ADFD-FB0F-4F2A-8E13-12734D5FD019} because it's missing its XML file!! (stt exists: False)
Skipping document 44/161 with OID {3A31AFEB-665C-40B3-88F8-3FCC1D046337} because it's missing its XML file!! (stt exists: False)
Skipping document 45/161 with OID {466814B6-F109-4FA1-B839-9958F4C120D1} because it's missing its XML file!! (stt exists: False)
Skipping document 46/161 with OID {5E666276-A507-4067-995D-0F5776AC9AFF} because it's missing its XML file!! (stt exists: False)
Skipping document 47/161 with OID {B180BDCB-08C2-43A5-A5D6-799987CA11E1} because it's missing its XML file!! (stt exists: False)
Skipping document 48/161 with OID {4B7A8604-077E-4CEC-83AF-0670108EE81D} because it's missing its XML file!! (stt exists: False)
Skipping document 49/161 with OID {9B33A00F-5F78-4FAB-8CCF-6C8F2E536DF0} because it's missing its XML file!! (stt exists: False)
Skipping document 50/161 with OID {5F437BBC-C246-41B0-87BE-D8FA360DB7D7} because it's missing its XML file!! (stt exists: False)
Skipping document 51/161 with OID {9F4F3052-5BDF-4843-85B4-341698777666} because it's missing its XML file!! (stt exists: False)
Skipping document 52/161 with OID {36620F46-B5DE-41E4-811C-A9A9770C1214} because it's missing its XML file!! (stt exists: False)
Skipping document 53/161 with OID {46C3DBC9-DB1B-4817-AD6D-DF4B9C32E3A5} because it's missing its XML file!! (stt exists: False)
Skipping document 54/161 with OID {B16A8C31-6AFA-4AED-9AA5-5BC8E3F3F0FE} because it's missing its XML file!! (stt exists: False)
Skipping document 55/161 with OID {8CF9BC9F-123B-49EC-BEDB-20AD42FD77D8} because it's missing its XML file!! (stt exists: False)
Skipping document 56/161 with OID {E8EC4942-5D36-40C9-9ECA-CE0F9793DDAB} because it's missing its XML file!! (stt exists: False)
Skipping document 57/161 with OID {710B49CE-63C7-44C6-B482-F6B78AE04302} because it's missing its XML file!! (stt exists: False)
The date for document with OID {0302707A-0D3B-4095-8C17-2E3AF4739C3F} was invalid (~__/05/1951) - changed it to ~01/05/1951
The date for document with OID {0302707A-0D3B-4095-8C17-2E3AF4739C3F} was invalid (~__/05/1951) - changed it to ~01/05/1951
Skipping document 59/161 with OID {94CFA2B6-D99D-4B09-91EC-F36A3A413B1E} because it's missing its XML file!! (stt exists: False)
Skipping document 60/161 with OID {6A96DC4A-8442-4A8F-9650-F1982619054D} because it's missing its XML file!! (stt exists: False)
Skipping document 61/161 with OID {554E0BCC-7691-40C3-B1E5-D6B9B30F4BBA} because it's missing its XML file!! (stt exists: False)
Skipping document 62/161 with OID {5211853C-0FC4-4D7F-B975-65A780D21284} because it's missing its XML file!! (stt exists: False)
Skipping document 63/161 with OID {9CE2A8C7-5BBE-4943-966D-53F9C42A41B9} because it's missing its XML file!! (stt exists: False)
Skipping document 64/161 with OID {CE1258BF-FF1D-4FD7-A912-B98CFD219067} because it's missing its XML file!! (stt exists: False)
Skipping document 65/161 with OID {6FDFA3CB-0F46-46A3-9CFD-EE5C6A3A1DE7} because it's missing its XML file!! (stt exists: False)
Skipping document 66/161 with OID {0A5AD55E-4ADF-4DB0-A661-A10662A0CB3F} because it's missing its XML file!! (stt exists: False)
Skipping document 67/161 with OID {4694AD8A-2891-4B2E-BF38-F27F9519F0D4} because it's missing its XML file!! (stt exists: False)
Skipping document 68/161 with OID {934B4A4C-3021-4ADF-B20E-C812811BCD47} because it's missing its XML file!! (stt exists: False)
Skipping document 69/161 with OID {F6F96CAB-D150-4B1F-911D-548971CF35B5} because it's missing its XML file!! (stt exists: False)
Skipping document 70/161 with OID {F487E863-70B7-4EB4-B682-22F87887FEBB} because it's missing its XML file!! (stt exists: False)
Skipping document 71/161 with OID {B9484F3F-6E9B-4950-AB52-448291B97E28} because it's missing its XML file!! (stt exists: False)
Skipping document 72/161 with OID {E247163F-AEE7-4E12-91E3-C6F56D83275A} because it's missing its XML file!! (stt exists: False)
Skipping document 73/161 with OID {8729D551-F5AD-4B1E-99FC-DEFFA9876245} because it's missing its XML file!! (stt exists: False)
Skipping document 74/161 with OID {BC9E9F3C-EB2D-46C8-AA5D-B277E534D82D} because it's missing its XML file!! (stt exists: False)
Skipping document 75/161 with OID {BEB77C47-C1DB-4533-8CED-3C8B086DF221} because it's missing its XML file!! (stt exists: False)
Skipping document 76/161 with OID {8774D549-B416-4F15-B32F-3F27B51274D3} because it's missing its XML file!! (stt exists: False)
Skipping document 77/161 with OID {4090A7AF-7A8C-4A33-93E2-27CB807D3C9E} because it's missing its XML file!! (stt exists: False)
Skipping document 78/161 with OID {FB17888C-AD8C-492D-B953-63F98796716E} because it's missing its XML file!! (stt exists: False)
Skipping document 79/161 with OID {95154FE6-AF44-49B3-B34A-54853E1B57F6} because it's missing its XML file!! (stt exists: False)
Skipping document 80/161 with OID {6AB3DEF6-2B5E-49FB-9090-9E333BDE3401} because it's missing its XML file!! (stt exists: False)
Skipping document 81/161 with OID {F6EAF166-FDB3-4A4A-B908-273AB16322C5} because it's missing its XML file!! (stt exists: False)
Skipping document 82/161 with OID {77ABA2BB-389F-48BC-8922-012BDC1CE408} because it's missing its XML file!! (stt exists: False)
Skipping document 83/161 with OID {53B2CB6C-D2F0-4865-820D-6C7DEC593178} because it's missing its XML file!! (stt exists: False)
Skipping document 84/161 with OID {2DC5500F-7A65-46EB-9E77-D8A6486E38C3} because it's missing its XML file!! (stt exists: False)
Skipping document 85/161 with OID {C55FF603-FA32-4DB5-981A-D1B523D256D3} because it's missing its XML file!! (stt exists: False)
Skipping document 86/161 with OID {34E08CB6-60CD-4B7A-8BAD-8E3473E37DCE} because it's missing its XML file!! (stt exists: False)
Skipping document 87/161 with OID {BDD051AB-CB6E-4EB3-A3D9-232B4F87F582} because it's missing its XML file!! (stt exists: False)
Skipping document 88/161 with OID {C8EC8715-A983-48A4-AF7C-AE9BACCC303D} because it's missing its XML file!! (stt exists: False)
Skipping document 89/161 with OID {4F285F21-11BE-47C4-B260-74A726F47AF0} because it's missing its XML file!! (stt exists: False)
Skipping document 90/161 with OID {A0897426-108E-42CB-801D-160B2726822B} because it's missing its XML file!! (stt exists: False)
Skipping document 91/161 with OID {2620B715-189E-4828-93BC-C0867E69534D} because it's missing its XML file!! (stt exists: False)
Skipping document 92/161 with OID {1AE61571-A611-4C82-8283-D65FEC677A29} because it's missing its XML file!! (stt exists: False)
Skipping document 93/161 with OID {4A4D1B9F-FE77-4D45-94C9-FD0C50515DA3} because it's missing its XML file!! (stt exists: False)
Skipping document 94/161 with OID {A3EC8C19-8323-4954-9DB2-374FEE96BF76} because it's missing its XML file!! (stt exists: False)
Skipping document 95/161 with OID {9523C9CD-7348-4F82-85B6-51CEE79C9DCF} because it's missing its XML file!! (stt exists: False)
Skipping document 96/161 with OID {038CD769-B963-4FFC-AABE-8A4C9EC1DCA7} because it's missing its XML file!! (stt exists: False)
Skipping document 97/161 with OID {9F6736C3-F386-4303-8C96-DE58A8D46FB8} because it's missing its XML file!! (stt exists: False)
Skipping document 98/161 with OID {C2A66A06-4F13-46FD-B544-274E7AF5EA18} because it's missing its XML file!! (stt exists: False)
Skipping document 99/161 with OID {B98675C2-E67A-450F-BAA0-D7C161EB8B49} because it's missing its XML file!! (stt exists: False)
Skipping document 100/161 with OID {09F1F6B7-0F33-4EE7-B224-0296A6CA41E0} because it's missing its XML file!! (stt exists: False)
Skipping document 101/161 with OID {0B8C8F17-43CF-4004-9A99-43A5CCFD203D} because it's missing its XML file!! (stt exists: False)
Skipping document 102/161 with OID {A827F33F-E868-4E00-BFA3-35BE83229A6F} because it's missing its XML file!! (stt exists: False)
Skipping document 103/161 with OID {21FE3A3E-CBD3-47D8-A740-0F76BF72977E} because it's missing its XML file!! (stt exists: False)
Skipping document 104/161 with OID {AB52FDE7-A838-45B4-9927-83EF3279A5F2} because it's missing its XML file!! (stt exists: False)
Skipping document 105/161 with OID {12311E49-65A5-4EA0-BF7F-8A303DA86D3B} because it's missing its XML file!! (stt exists: False)
Skipping document 106/161 with OID {4C29AD47-5B3E-4244-ACDF-030E7DDB3861} because it's missing its XML file!! (stt exists: False)
Skipping document 107/161 with OID {C866B7B8-F9FA-455F-982D-8DD52A5819E2} because it's missing its XML file!! (stt exists: False)
Skipping document 108/161 with OID {B7BBE8E6-24E7-4FDC-82FA-107A61E813BD} because it's missing its XML file!! (stt exists: False)
Skipping document 109/161 with OID {683A7B02-5888-430E-A558-7D4D6E5F5430} because it's missing its XML file!! (stt exists: False)
Skipping document 110/161 with OID {7975BE14-ACED-4C74-A425-A5BBCFCE9B5D} because it's missing its XML file!! (stt exists: False)
Skipping document 111/161 with OID {564D0E4A-2D1D-4653-B794-482059896CF3} because it's missing its XML file!! (stt exists: False)
Skipping document 112/161 with OID {179F590C-D388-49FA-947D-B3A1B2E60619} because it's missing its XML file!! (stt exists: False)
Skipping document 113/161 with OID {E85AFF2A-CB06-4123-A55C-7C23C7AB33C8} because it's missing its XML file!! (stt exists: False)
Skipping document 114/161 with OID {352723E1-9992-43F0-93F1-C6F4B2994419} because it's missing its XML file!! (stt exists: False)
Skipping document 115/161 with OID {FAE6AC68-248C-4CF3-9021-4674EDD68197} because it's missing its XML file!! (stt exists: False)
Skipping document 116/161 with OID {2DACB2AB-DC26-4FA0-BF18-B1AA80CE026E} because it's missing its XML file!! (stt exists: False)
Skipping document 117/161 with OID {7AA23B3A-3702-44BE-A726-7219FA5E13A0} because it's missing its XML file!! (stt exists: False)
Skipping document 118/161 with OID {23FF6EAC-6453-423D-A9E8-770E5115C850} because it's missing its XML file!! (stt exists: False)
Skipping document 119/161 with OID {5D856122-B43F-4CB2-A9F0-32F0BD3104DF} because it's missing its XML file!! (stt exists: False)
Skipping document 120/161 with OID {89980695-B5F5-4834-AFAE-1603C87494CB} because it's missing its XML file!! (stt exists: False)
Skipping document 121/161 with OID {9C49210C-5BF7-4998-84D3-F388C905F6C1} because it's missing its XML file!! (stt exists: False)
Skipping document 122/161 with OID {4601843B-89F4-43BD-860E-2C2EB924ECA9} because it's missing its XML file!! (stt exists: False)
Skipping document 123/161 with OID {D0EA53B5-B7B0-4EE8-9D1E-8B30F3B846C3} because it's missing its XML file!! (stt exists: False)
Skipping document 124/161 with OID {2567E9E8-1660-4F4F-B22E-B6BB2BE331DA} because it's missing its XML file!! (stt exists: False)
Skipping document 125/161 with OID {168140B3-7C5A-48BD-8E8B-DC6ABF830F80} because it's missing its XML file!! (stt exists: False)
Skipping document 126/161 with OID {1867A354-2444-43BA-871F-5FB938A75077} because it's missing its XML file!! (stt exists: False)
Skipping document 127/161 with OID {261838BB-73AF-4661-8339-08B93A7C3653} because it's missing its XML file!! (stt exists: False)
Skipping document 128/161 with OID {4A8721F0-7A69-41ED-BBF0-E1769FF66A61} because it's missing its XML file!! (stt exists: False)
Skipping document 129/161 with OID {F205B3BC-1198-4FB6-8DDB-B9C3F05D82D6} because it's missing its XML file!! (stt exists: False)
Skipping document 130/161 with OID {49FBED26-F96A-4D3F-9434-1B75B71D164B} because it's missing its XML file!! (stt exists: False)
Skipping document 131/161 with OID {053C3EE9-EA49-49E1-8051-B6678DA65F30} because it's missing its XML file!! (stt exists: False)
Skipping document 132/161 with OID {C987015D-56D4-4ABC-88E3-716819BE0A8A} because it's missing its XML file!! (stt exists: False)
Skipping document 133/161 with OID {DB8D8192-95D7-43D1-B541-3706A123C510} because it's missing its XML file!! (stt exists: False)
Skipping document 134/161 with OID {54DBEA7A-CFDF-4C2B-9485-D9138E4B4F90} because it's missing its XML file!! (stt exists: False)
Skipping document 135/161 with OID {763BBA80-642F-4CD1-9AD7-BB38CE2799CF} because it's missing its XML file!! (stt exists: False)
Skipping document 136/161 with OID {02568B54-E338-4011-AD6F-FC3CEFF4287A} because it's missing its XML file!! (stt exists: False)
Skipping document 137/161 with OID {CFC4F1D8-0557-411A-AC8B-0CDCCDCB7020} because it's missing its XML file!! (stt exists: False)
Skipping document 138/161 with OID {33A65884-19E6-4AF1-B098-1C4DCE7C74E5} because it's missing its XML file!! (stt exists: False)
Skipping document 139/161 with OID {9490B9DC-A396-46AA-A33B-DC058235BEF6} because it's missing its XML file!! (stt exists: False)
Skipping document 140/161 with OID {AB4E2F57-BB94-4B57-95FE-304F1E1554B5} because it's missing its XML file!! (stt exists: False)
Skipping document 141/161 with OID {4525E736-55CF-4610-B91A-E03C90DF9D52} because it's missing its XML file!! (stt exists: False)
Skipping document 142/161 with OID {333DD6BC-6D5D-41F5-8DA8-0117DEB01D4C} because it's missing its XML file!! (stt exists: False)
Skipping document 143/161 with OID {B4D5AFA6-5BFD-4E27-95CA-3FE295CD71D8} because it's missing its XML file!! (stt exists: False)
Skipping document 144/161 with OID {4A1128B8-E76E-46DA-913F-BC8FDAAE82DF} because it's missing its XML file!! (stt exists: False)
Skipping document 145/161 with OID {7199DADE-23B1-41B2-9E02-F763C8812A83} because it's missing its XML file!! (stt exists: False)
Skipping document 146/161 with OID {A6A73B69-E447-4392-A8C0-88E88C694A6C} because it's missing its XML file!! (stt exists: False)
Skipping document 147/161 with OID {4D6CE390-4B17-4268-BBED-92CE5140B27B} because it's missing its XML file!! (stt exists: False)
Skipping document 148/161 with OID {2A013E71-2D82-465D-ADE8-BD2F80879275} because it's missing its XML file!! (stt exists: False)
Skipping document 149/161 with OID {12DB99E4-5E1D-4F3A-8F0A-4749CC009F95} because it's missing its XML file!! (stt exists: False)
Skipping document 150/161 with OID {C0B777FB-AE01-4AE1-AE79-FE1524CC60A2} because it's missing its XML file!! (stt exists: False)
Skipping document 151/161 with OID {CF226327-DD5D-4520-902B-A75E8ED9C45C} because it's missing its XML file!! (stt exists: False)
Skipping document 152/161 with OID {282A04B0-E9A1-4976-B42C-A95698BB7980} because it's missing its XML file!! (stt exists: False)
Skipping document 153/161 with OID {9072FBAF-AADA-4207-8B49-00A89BEE1628} because it's missing its XML file!! (stt exists: False)

Starting extracting 43 documents for program ombres_eco
Did not find any date for doc with OID {7A576FAF-7CE9-4679-9FF0-37BB4FB7BC6E}. Trying to use the recording date. doc_dict: {'alias': 'ombres_eco', 'date_str': None, 'stt_filename': '7A576FAF-7CE9-4679-9FF0-37BB4FB7BC6E_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{7A576FAF-7CE9-4679-9FF0-37BB4FB7BC6E}', 'stripped_OID': '7A576FAF-7CE9-4679-9FF0-37BB4FB7BC6E', 'login': '', 'broadcast_episode_title': "Le tourisme d'hiver et son financement : Entretien avec Jean-Fran?ois Bergier, professeur ? l'EPFZ", 'sequence': '2', 'broadcast_program_name': "Ombres et lumi?res de l'?conomie suisse", 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'sco (NumA)', 'modified_on': '07.06.2022 20:29:10', 'physical_support_history': "Cote d'origine : A 23250 Resp. RSR : sco Lot : Caisse 1101", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': None, 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Bergier, Jean-Fran?ois', 'function': 'Interview?/e', 'role': "professeur d'histoire ?conomique ? l'EPFZ"}, {'name': 'Nicod, Bernard', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Suisse'], 'person_descriptors': None, 'thematical_descriptors': ['?conomie', 'assurance', 'tourisme', 'hiver'], 'rights_usage_possibilities': None, 'radio_channels': ['La Premi?re'], 'subdomains': ['Interview'], 'recording_dates': ['~12/06/1994 - ~12/06/1994'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {2F9BA510-D5F4-4817-83EF-6ADC44F4E7AB}. Trying to use the recording date. doc_dict: {'alias': 'ombres_eco', 'date_str': None, 'stt_filename': '2F9BA510-D5F4-4817-83EF-6ADC44F4E7AB_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{2F9BA510-D5F4-4817-83EF-6ADC44F4E7AB}', 'stripped_OID': '2F9BA510-D5F4-4817-83EF-6ADC44F4E7AB', 'login': '', 'broadcast_episode_title': "Les assurances et le tourisme : Entretien avec Jean-Fran?ois Bergier, professeur ? l'EPFZ", 'sequence': '2', 'broadcast_program_name': "Ombres et lumi?res de l'?conomie suisse", 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'sco (NumA)', 'modified_on': '09.03.2023 09:33:04', 'physical_support_history': "Cote d'origine : A 23238 Resp. RSR : sco Lot : Caisse 1101", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': None, 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Bergier, Jean-Fran?ois', 'function': 'Interview?/e', 'role': "professeur d'histoire ?conomique ? l'EPFZ"}, {'name': 'Nicod, Bernard', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Suisse'], 'person_descriptors': None, 'thematical_descriptors': ['?conomie', 'assurance', 'tourisme'], 'rights_usage_possibilities': None, 'radio_channels': ['La Premi?re'], 'subdomains': ['Interview'], 'recording_dates': ['~05/06/1994 - ~05/06/1994'], 'first_broadcast_dates': None}
ombres_eco - returning 43 documents, 0 were skipped due to missing necessary info.

Starting extracting 43 documents for program ombres_eco

100%|██████████| 2/2 [00:00<00:00,  5.37it/s]
38it [02:25,  1.47s/it]

Did not find any date for doc with OID {7A576FAF-7CE9-4679-9FF0-37BB4FB7BC6E}. Trying to use the recording date. doc_dict: {'alias': 'ombres_eco', 'date_str': None, 'stt_filename': '7A576FAF-7CE9-4679-9FF0-37BB4FB7BC6E_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{7A576FAF-7CE9-4679-9FF0-37BB4FB7BC6E}', 'stripped_OID': '7A576FAF-7CE9-4679-9FF0-37BB4FB7BC6E', 'login': '', 'broadcast_episode_title': "Le tourisme d'hiver et son financement : Entretien avec Jean-Fran?ois Bergier, professeur ? l'EPFZ", 'sequence': '2', 'broadcast_program_name': "Ombres et lumi?res de l'?conomie suisse", 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'sco (NumA)', 'modified_on': '07.06.2022 20:29:10', 'physical_support_history': "Cote d'origine : A 23250 Resp. RSR : sco Lot : Caisse 1101", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': None, 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Bergier, Jean-Fran?ois', 'function': 'Interview?/e', 'role': "professeur d'histoire ?conomique ? l'EPFZ"}, {'name': 'Nicod, Bernard', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Suisse'], 'person_descriptors': None, 'thematical_descriptors': ['?conomie', 'assurance', 'tourisme', 'hiver'], 'rights_usage_possibilities': None, 'radio_channels': ['La Premi?re'], 'subdomains': ['Interview'], 'recording_dates': ['~12/06/1994 - ~12/06/1994'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {2F9BA510-D5F4-4817-83EF-6ADC44F4E7AB}. Trying to use the recording date. doc_dict: {'alias': 'ombres_eco', 'date_str': None, 'stt_filename': '2F9BA510-D5F4-4817-83EF-6ADC44F4E7AB_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{2F9BA510-D5F4-4817-83EF-6ADC44F4E7AB}', 'stripped_OID': '2F9BA510-D5F4-4817-83EF-6ADC44F4E7AB', 'login': '', 'broadcast_episode_title': "Les assurances et le tourisme : Entretien avec Jean-Fran?ois Bergier, professeur ? l'EPFZ", 'sequence': '2', 'broadcast_program_name': "Ombres et lumi?res de l'?conomie suisse", 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'sco (NumA)', 'modified_on': '09.03.2023 09:33:04', 'physical_support_history': "Cote d'origine : A 23238 Resp. RSR : sco Lot : Caisse 1101", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': None, 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Bergier, Jean-Fran?ois', 'function': 'Interview?/e', 'role': "professeur d'histoire ?conomique ? l'EPFZ"}, {'name': 'Nicod, Bernard', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Suisse'], 'person_descriptors': None, 'thematical_descriptors': ['?conomie', 'assurance', 'tourisme'], 'rights_usage_possibilities': None, 'radio_channels': ['La Premi?re'], 'subdomains': ['Interview'], 'recording_dates': ['~05/06/1994 - ~05/06/1994'], 'first_broadcast_dates': None}
ombres_eco - returning 43 documents, 0 were skipped due to missing necessary info.
 --> Adding 86 to the out csv for ombres_eco

PROCESSING PROGRAM paraboles (39/47) - 1 files:

Starting extracting 281 documents for program paraboles
Skipping document 3/281 with OID {9CD456A6-B7AF-4FAC-A670-F3BDF15C3F27} because it's missing its XML file!! (stt exists: False)
Skipping document 24/281 with OID {817D7217-B8F2-4313-B0E7-FE00E5B9BEF1} because it's missing its XML file!! (stt exists: False)
WARNING! MISSING DATE FOR DOC WITH OID {0E007521-4FAB-49A3-B16B-A79191C63328}!!
Document: {'alias': 'paraboles', 'date_str': None, 'stt_filename': '0E007521-4FAB-49A3-B16B-A79191C63328_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{0E007521-4FAB-49A3-B16B-A79191C63328}', 'stripped_OID': '0E007521-4FAB-49A3-B16B-A79191C63328', 'login': '', 'broadcast_episode_title': 'Alastair Hubert de la Mission populaire aux Institutions europ?ennes, par Cyril D?praz', 'sequence': '1', 'broadcast_program_name': 'Paraboles', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'AQT (NumA)', 'modified_on': '27.05.2022 20:48:15', 'physical_support_history': "Cote d'origine : Bd 7541.02 Resp. RSR : AQT Lot : Caisse 2342", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Participant: inte:Hubert, Alastair', 'workflow_status': 'Accept?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'D?praz, Cyril', 'function': 'Intervieweur/euse', 'role': 'collaborateur/trice RSR'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': None, 'recording_dates': None, 'first_broadcast_dates': None},
original: <DOCUMENT><CLSID>{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}</CLSID><OID>{0E007521-4FAB-49A3-B16B-A79191C63328}</OID><LOGIN/><TITLE>Alastair Hubert de la Mission populaire aux Institutions europ?ennes, par Cyril D?praz</TITLE><HIERARCHY OID="{0E007521-4FAB-49A3-B16B-A79191C63328}" current="*" depth="---" title="Alastair Hubert de la Mission populaire aux Institutions europ?ennes, par Cyril D?praz"/><SEQUENCE>1</SEQUENCE><BROADCAST>Paraboles</BROADCAST><DOCUMENTTYPE>Parl?</DOCUMENTTYPE><HIERARCHYLEVEL>Sujet</HIERARCHYLEVEL><MODIFIEDBY>AQT (NumA)</MODIFIEDBY><MODIFIEDON>27.05.2022 20:48:15</MODIFIEDON><NOTES>dat_diff : mai 1993</NOTES><HISTORY>Cote d'origine : Bd 7541.02 Resp. RSR : AQT Lot : Caisse 2342</HISTORY><PARTICIPANTS><PARTICIPANT><NAME>D?praz, Cyril</NAME><FUNCTION>Intervieweur/euse</FUNCTION><ROLE>collaborateur/trice RSR</ROLE></PARTICIPANT></PARTICIPANTS><PRODUCTIONTYPE>Production propre</PRODUCTIONTYPE><RIGHTSSTATUS>Clarifi?</RIGHTSSTATUS><RIGHTSUSAGEPOSSIBILITIES><RIGHTSUSAGEPOSSIBILITY>Tous</RIGHTSUSAGEPOSSIBILITY></RIGHTSUSAGEPOSSIBILITIES><SERIESTITLE>Sauvegarde d'archives</SERIESTITLE><SUMMARY>Participant: inte:Hubert, Alastair</SUMMARY><WORKFLOWSTATUS>Accept?</WORKFLOWSTATUS><LIVE>Non live</LIVE><MODULATIONTYPE>St?r?o</MODULATIONTYPE><WORKDURATION>00:00:00.000</WORKDURATION><WORKDURATIONCOMPL>Non</WORKDURATIONCOMPL><SUPPORTS><SUPPORT><CLSID>{9C19C69A-A4DC-479E-94F1-61FF72CA7889}</CLSID><OID>{82D1FDB1-016E-4375-A03C-034D6A31A335}</OID><TITLE>Alastair Hubert de la Mission populaire aux Institutions europ?ennes, par Cyril D?praz</TITLE><ISDIGITAL>True</ISDIGITAL><FILENAME>Bd 7541.02{AC0A10BE-AC2E-4332-BA8D-1FB46B6563AC}.wav</FILENAME><ACQUISITIONDATES><ACQUISITIONDATE>25/11/2008</ACQUISITIONDATE></ACQUISITIONDATES><BRAND>Enr. RSR</BRAND><CATALOGUINGSTATUS>Transitoire</CATALOGUINGSTATUS><SOURCE>NumA</SOURCE><UNITDURATION>00:30:25.684</UNITDURATION><UNITDURATIONCOMPL>Non</UNITDURATIONCOMPL><PHYSICALPROPERTIES><ANNOTATIONS>Non</ANNOTATIONS><NUMBEROFCOPIES>0</NUMBEROFCOPIES><NUMBEROFSUPPORTS>0</NUMBEROFSUPPORTS></PHYSICALPROPERTIES></SUPPORT></SUPPORTS></DOCUMENT>
Skipping document 37/281 with OID {B49D8F48-390C-40DA-8C5F-8D3B012B41C7} because it's missing its XML file!! (stt exists: False)
Skipping document 38/281 with OID {D4F495E2-488A-4CBB-B0EF-98EC1D1CD9D9} because it's missing its XML file!! (stt exists: False)
Skipping document 39/281 with OID {AFF0D160-F661-4ED2-9EB6-539E4B99B4E5} because it's missing its XML file!! (stt exists: False)
Skipping document 41/281 with OID {C67D00E2-2CD2-451F-8135-DFBB978DAA97} because it's missing its XML file!! (stt exists: False)
Skipping document 42/281 with OID {B955B01E-D2F7-4161-96D1-675BC2B989F3} because it's missing its XML file!! (stt exists: False)
Skipping document 47/281 with OID {A5DB702A-2BCD-4385-9451-5E4997DAFAA4} because it's missing its XML file!! (stt exists: False)
Skipping document 49/281 with OID {41E85EDA-5D15-48DF-A655-9FFEA10630BB} because it's missing its XML file!! (stt exists: False)
Skipping document 50/281 with OID {A541CD46-A65F-4C7B-BD13-5D8D50FB985A} because it's missing its XML file!! (stt exists: False)
Skipping document 51/281 with OID {C2C0C98E-2ED1-4EDC-A470-131DEC53AE84} because it's missing its XML file!! (stt exists: False)
Skipping document 53/281 with OID {AC0C9A25-EC1D-4C6D-BB2B-4DC3225D3217} because it's missing its XML file!! (stt exists: False)
Skipping document 72/281 with OID {3C6C38EE-3A36-4128-BE56-06CAD6FEE54B} because it's missing its XML file!! (stt exists: False)
Skipping document 73/281 with OID {99483DFF-E870-48BE-BEF3-1518DEDF0060} because it's missing its XML file!! (stt exists: False)
Skipping document 74/281 with OID {C03F7038-8E1C-4B63-9753-24CFEF23D75F} because it's missing its XML file!! (stt exists: False)
Skipping document 78/281 with OID {962233DA-210E-404F-9867-6A8E6A2CE34A} because it's missing its XML file!! (stt exists: False)
Skipping document 85/281 with OID {0A7D42C5-C5C7-455D-B8EC-FE2CFCF9890D} because it's missing its XML file!! (stt exists: False)
Skipping document 87/281 with OID {4C3192F3-01BB-43D3-AEE9-99FA0B0BE0BC} because it's missing its XML file!! (stt exists: False)
Skipping document 126/281 with OID {0E975FCD-2C16-4279-B2AC-C7B58D91BD37} because it's missing its XML file!! (stt exists: False)
Skipping document 130/281 with OID {1EB9CA74-18CC-4B6F-A8D9-68FC6B976841} because it's missing its XML file!! (stt exists: False)
Skipping document 136/281 with OID {B4E95FBE-6E6A-4F62-8092-07DA29C7B7C9} because it's missing its XML file!! (stt exists: False)
Skipping document 146/281 with OID {32F18A89-54E6-4729-80A9-6CC6AB437979} because it's missing its XML file!! (stt exists: False)
Skipping document 158/281 with OID {C20613AD-ACF2-4BD0-8854-E73BDCE837E3} because it's missing its XML file!! (stt exists: False)
Skipping document 159/281 with OID {F393218C-FE13-4932-B649-9ED5E650F7C3} because it's missing its XML file!! (stt exists: False)
Skipping document 171/281 with OID {5AB5BA94-BCF4-4885-9D01-1604F31D89E0} because it's missing its XML file!! (stt exists: False)
Skipping document 172/281 with OID {789DC3BB-D9D1-4C81-8768-CD50C2A08199} because it's missing its XML file!! (stt exists: False)
Skipping document 181/281 with OID {42738790-4444-4EEA-96EE-39D8FC0DE3D5} because it's missing its XML file!! (stt exists: False)
Skipping document 182/281 with OID {D63816EE-FC4B-4BEF-9EE8-AFBFA660654D} because it's missing its XML file!! (stt exists: False)
Skipping document 195/281 with OID {FAB983E1-D9E2-4FD4-8516-FFD270BF2D89} because it's missing its XML file!! (stt exists: False)
Skipping document 197/281 with OID {201160DD-7DFD-40C5-A0E3-02828AFFB67B} because it's missing its XML file!! (stt exists: False)
Skipping document 198/281 with OID {DBF1360B-4892-41CE-BDA7-F01F60E5BB1D} because it's missing its XML file!! (stt exists: False)
Skipping document 199/281 with OID {A6F9271E-3010-4E8F-98D1-9FF0E995B8FC} because it's missing its XML file!! (stt exists: False)
Skipping document 200/281 with OID {074DE46E-5FE8-4F24-97E4-7996A99A775F} because it's missing its XML file!! (stt exists: False)
Skipping document 205/281 with OID {C49F384F-9505-423C-A533-B38526DD89AF} because it's missing its XML file!! (stt exists: False)
Skipping document 208/281 with OID {36EF250E-6A15-417D-B86C-FEB208710B77} because it's missing its XML file!! (stt exists: False)
Skipping document 212/281 with OID {A8BCACFE-1A38-402D-8EB2-5F56F267D833} because it's missing its XML file!! (stt exists: False)
Skipping document 222/281 with OID {6CA1944A-ECAC-4494-9B1D-13633BAC98AA} because it's missing its XML file!! (stt exists: False)
Skipping document 223/281 with OID {E104AB4D-AABE-4E86-8011-CEC79577A659} because it's missing its XML file!! (stt exists: False)
Skipping document 224/281 with OID {032FBE42-45F6-44EC-96A9-6560AC9397B0} because it's missing its XML file!! (stt exists: False)
Skipping document 225/281 with OID {EFBEADED-9742-4A5F-A7CF-FF6FC500DB24} because it's missing its XML file!! (stt exists: False)
Skipping document 227/281 with OID {7EAE12F6-6ED5-4C5E-A241-663DFD48BE46} because it's missing its XML file!! (stt exists: False)

100%|██████████| 1/1 [00:01<00:00,  1.28s/it]
39it [02:27,  1.47s/it]

Skipping document 239/281 with OID {B00730F1-34D1-40A7-AE9F-A546C72C8636} because it's missing its XML file!! (stt exists: False)
Skipping document 244/281 with OID {C41DDCB4-555D-45B3-8797-EACA36A85679} because it's missing its XML file!! (stt exists: False)
Skipping document 245/281 with OID {3E79EA18-98C2-4094-A7DA-B481F325816B} because it's missing its XML file!! (stt exists: False)
Skipping document 252/281 with OID {FC6BFCED-B8FE-4B8D-914B-FFD706448637} because it's missing its XML file!! (stt exists: False)
Skipping document 256/281 with OID {79EB2BED-B204-4F00-B8F8-2104803E768E} because it's missing its XML file!! (stt exists: False)
Skipping document 257/281 with OID {C361A028-0C8B-484F-935D-190C44C6114D} because it's missing its XML file!! (stt exists: False)
Skipping document 258/281 with OID {308021FC-172D-4827-B73F-4B27B6A4F418} because it's missing its XML file!! (stt exists: False)
Skipping document 259/281 with OID {FE710D88-48BE-4A04-A331-8B69812221A3} because it's missing its XML file!! (stt exists: False)
Skipping document 261/281 with OID {6FF61A01-2B32-4EDB-A4E6-B0B6FD91F824} because it's missing its XML file!! (stt exists: False)
Skipping document 262/281 with OID {977FCC35-77BC-4C9D-BFD9-D9E55FCD9333} because it's missing its XML file!! (stt exists: False)
Skipping document 263/281 with OID {AD4B89D1-38BD-405B-A390-3A60146199BC} because it's missing its XML file!! (stt exists: False)
Skipping document 264/281 with OID {BC7CC069-5FEB-4EF4-97E2-FAEAC8463309} because it's missing its XML file!! (stt exists: False)
Skipping document 267/281 with OID {B858A755-1700-4025-8C59-B58336D775CC} because it's missing its XML file!! (stt exists: False)
Skipping document 269/281 with OID {0921282B-24F3-4858-BE6D-E59FF1116581} because it's missing its XML file!! (stt exists: False)
Skipping document 279/281 with OID {2DB36213-71D2-4391-AB46-5F4A7A0CA11C} because it's missing its XML file!! (stt exists: False)
paraboles - returning 225 documents, 56 were skipped due to missing necessary info.
 --> Adding 225 to the out csv for paraboles

PROCESSING PROGRAM paris_parle (40/47) - 1 files:

Starting extracting 295 documents for program paris_parle
Did not find any date for doc with OID {40E9C6D5-BE98-44C0-88EC-9034C14474A8}. Trying to use the recording date. doc_dict: {'alias': 'paris_parle', 'date_str': None, 'stt_filename': '40E9C6D5-BE98-44C0-88EC-9034C14474A8_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{40E9C6D5-BE98-44C0-88EC-9034C14474A8}', 'stripped_OID': '40E9C6D5-BE98-44C0-88EC-9034C14474A8', 'login': '', 'broadcast_episode_title': '1. Allocution du G?n?ral Lauris Nordstad, commandant des forces atlantiques. - 2. Echos de la conf?rence de presse de Wladimir Porch? sur la reconversion de la cha?ne parisienne', 'sequence': '1', 'broadcast_program_name': 'Paris vous parle', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'AQT (NumA)', 'modified_on': '01.08.2016 19:11:06', 'physical_support_history': "Cote d'origine : MA 5656.k Resp. RSR : AQT Lot : Caisse 3047", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Participant: decl:Nordstad, Lauris', 'workflow_status': 'Accept?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Porch?, Wladimir', 'function': "Auteur d'une d?claration", 'role': None}, {'name': 'P?ricard, Michel', 'function': 'Commentateur/trice', 'role': 'collaborateur/trice RSR'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Radio Sottens'], 'subdomains': None, 'recording_dates': ['06/12/1956 - 06/12/1956'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {77C6E73B-A7E3-472F-A857-D8572B61B76D}. Trying to use the recording date. doc_dict: {'alias': 'paris_parle', 'date_str': None, 'stt_filename': '77C6E73B-A7E3-472F-A857-D8572B61B76D_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{77C6E73B-A7E3-472F-A857-D8572B61B76D}', 'stripped_OID': '77C6E73B-A7E3-472F-A857-D8572B61B76D', 'login': '', 'broadcast_episode_title': "1. D?claration de Robert Schumann, homme d'?tat fran?ais, ? l'occasion du 10?me anniversaire du March? commun ? Luxembourg. - 2. Commentaire sur la d?claration", 'sequence': '1', 'broadcast_program_name': 'Paris vous parle', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'brucklbo', 'modified_on': '27.02.2020 09:20:50', 'physical_support_history': "Cote d'origine: MA 60_17.G.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'A rechercher', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': None, 'modulation_type': 'Mono', 'work_duration': '00:01:27.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Schuman, Robert', 'function': "Auteur d'une d?claration", 'role': "homme d'?tat fran?ais"}, {'name': 'Inconnu', 'function': 'Commentateur/trice', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Europe'], 'person_descriptors': ['March? Commun', "Communaut? europ?enne du charbon et de l'acier (CECA)"], 'thematical_descriptors': ['politique'], 'rights_usage_possibilities': None, 'radio_channels': None, 'subdomains': ['D?claration'], 'recording_dates': ['09/05/1960 - 09/05/1960'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {A461EBC0-DEA8-4D71-86EC-154C73A7BFEE}. Trying to use the recording date. doc_dict: {'alias': 'paris_parle', 'date_str': None, 'stt_filename': 'A461EBC0-DEA8-4D71-86EC-154C73A7BFEE_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{A461EBC0-DEA8-4D71-86EC-154C73A7BFEE}', 'stripped_OID': 'A461EBC0-DEA8-4D71-86EC-154C73A7BFEE', 'login': '', 'broadcast_episode_title': "1. Proc?s autour de l'h?ritage du peintre Pierre Bonnard. - 2. Interview de Bourvil", 'sequence': '1', 'broadcast_program_name': 'Paris vous parle', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'AQT (NumA)', 'modified_on': '30.07.2016 10:59:33', 'physical_support_history': "Cote d'origine : MA 5656.j Resp. RSR : AQT Lot : Caisse 3047", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Participant: inte:Bourvil,', 'workflow_status': 'Accept?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Elina, Lise', 'function': 'Intervieweur/euse', 'role': 'collaborateur/trice RSR'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Radio Sottens'], 'subdomains': None, 'recording_dates': ['04/12/1956 - 04/12/1956'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {2A68F9B2-33DF-4E32-9F10-26945A785BF1}. Trying to use the recording date. doc_dict: {'alias': 'paris_parle', 'date_str': None, 'stt_filename': '2A68F9B2-33DF-4E32-9F10-26945A785BF1_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{2A68F9B2-33DF-4E32-9F10-26945A785BF1}', 'stripped_OID': '2A68F9B2-33DF-4E32-9F10-26945A785BF1', 'login': '', 'broadcast_episode_title': '1er mai [1956?] ? Moscou. Avec la voix du mar?chal Gueorgui Konstandinovitch Joukov', 'sequence': '1', 'broadcast_program_name': 'Paris vous parle', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '01.08.2016 05:08:37', 'physical_support_history': "Cote d'origine : MA 5632.a", 'production_type': 'Production ext?rieure (?change)', 'recording_place': None, 'rights_notes': None, 'rights_status': 'A rechercher', 'series_title': "Sauvegarde d'archives", 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Joukov, Gueorgui Konstantinovitch', 'function': "Auteur d'une d?claration", 'role': 'mar?chal russe'}, {'name': 'Neuvecelle, Jean', 'function': 'Reporter', 'role': 'journaliste'}], 'geographical_descriptors': ['URSS'], 'person_descriptors': ['Joukov, Gueorgui Konstantinovitch'], 'thematical_descriptors': ['f?te du travail'], 'rights_usage_possibilities': ['FM'], 'radio_channels': ['Radio Sottens'], 'subdomains': ['Reportage'], 'recording_dates': ['03/05/1956 - 03/05/1956'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {3FA6B53A-7DB6-4F47-B8A0-947BF0EF2606}. Trying to use the recording date. doc_dict: {'alias': 'paris_parle', 'date_str': None, 'stt_filename': '3FA6B53A-7DB6-4F47-B8A0-947BF0EF2606_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{3FA6B53A-7DB6-4F47-B8A0-947BF0EF2606}', 'stripped_OID': '3FA6B53A-7DB6-4F47-B8A0-947BF0EF2606', 'login': '', 'broadcast_episode_title': "Adieux du mar?chal Alphonse Juin, militaire fran?ais, g?n?ral et mar?chal de France, au Haut Commandement de l'OTAN", 'sequence': '1', 'broadcast_program_name': 'Paris vous parle', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '03.08.2016 18:30:39', 'physical_support_history': "Cote d'origine : MA 5645.n", 'production_type': 'Production ext?rieure (?change)', 'recording_place': None, 'rights_notes': None, 'rights_status': 'A rechercher', 'series_title': "Sauvegarde d'archives", 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Juin, Alphonse', 'function': "Auteur d'une d?claration", 'role': 'g?n?ral et mar?chal de France'}], 'geographical_descriptors': None, 'person_descriptors': ['OTAN'], 'thematical_descriptors': None, 'rights_usage_possibilities': ['FM'], 'radio_channels': ['Radio Sottens'], 'subdomains': ['D?claration'], 'recording_dates': ['28/09/1956 - 28/09/1956'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {6B3AAF97-1C27-48F8-803D-9DD22D89A1E8}. Trying to use the recording date. doc_dict: {'alias': 'paris_parle', 'date_str': None, 'stt_filename': '6B3AAF97-1C27-48F8-803D-9DD22D89A1E8_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{6B3AAF97-1C27-48F8-803D-9DD22D89A1E8}', 'stripped_OID': '6B3AAF97-1C27-48F8-803D-9DD22D89A1E8', 'login': '', 'broadcast_episode_title': 'Allocution du g?n?ral Gr?nther : Adieux ? Marne la Coquette', 'sequence': '1', 'broadcast_program_name': 'Paris vous parle', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'AQT (NumA)', 'modified_on': '05.08.2016 12:37:15', 'physical_support_history': "Cote d'origine : MA 5656.l Resp. RSR : AQT Lot : Caisse 3047", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': None, 'workflow_status': 'Accept?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Radio Sottens'], 'subdomains': None, 'recording_dates': ['05/12/1956 - 05/12/1956'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {1C921B42-2F7B-4853-BFD7-A4AA370741AE}. Trying to use the recording date. doc_dict: {'alias': 'paris_parle', 'date_str': None, 'stt_filename': '1C921B42-2F7B-4853-BFD7-A4AA370741AE_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{1C921B42-2F7B-4853-BFD7-A4AA370741AE}', 'stripped_OID': '1C921B42-2F7B-4853-BFD7-A4AA370741AE', 'login': '', 'broadcast_episode_title': 'Allocution du pape Pie XII : A propos du rassemblement JOC (Jeunesse Ouvri?re Chr?tienne)', 'sequence': '1', 'broadcast_program_name': 'Paris vous parle', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '01.08.2016 14:54:46', 'physical_support_history': "Cote d'origine : MA 5720.j", 'production_type': 'Production ext?rieure (?change)', 'recording_place': None, 'rights_notes': None, 'rights_status': 'A rechercher', 'series_title': "Sauvegarde d'archives", 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Pie XII [= Pacelli, Eugenio]', 'function': "Auteur d'une d?claration", 'role': 'pape'}], 'geographical_descriptors': None, 'person_descriptors': ['Pie XII [= Pacelli, Eugenio]', 'Jeunesse ouvri?re chr?tienne'], 'thematical_descriptors': ['catholicisme'], 'rights_usage_possibilities': ['FM'], 'radio_channels': None, 'subdomains': ['D?claration'], 'recording_dates': ['25/08/1957 - 25/08/1957'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {22902B74-BFF5-4B38-B424-94B0D814033A}. Trying to use the recording date. doc_dict: {'alias': 'paris_parle', 'date_str': None, 'stt_filename': '22902B74-BFF5-4B38-B424-94B0D814033A_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{22902B74-BFF5-4B38-B424-94B0D814033A}', 'stripped_OID': '22902B74-BFF5-4B38-B424-94B0D814033A', 'login': '', 'broadcast_episode_title': "Anecdote ? la mort d'A. Gerbault, par Raymond Yemerry et F. A. Roch", 'sequence': '1', 'broadcast_program_name': 'Paris vous parle', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'CTE (NumA)', 'modified_on': '03.08.2016 00:30:12', 'physical_support_history': "Cote d'origine : MA 5667.03 Resp. RSR : CTE Lot : Caisse 2430", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': None, 'workflow_status': 'Accept?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': None, 'recording_dates': ['18/12/1956 - 18/12/1956'], 'first_broadcast_dates': None}
Skipping document 10/295 with OID {92CEE961-1069-4D4D-8022-88A8515A8725} because it's missing its XML file!! (stt exists: False)
Skipping document 11/295 with OID {CC853DD9-9975-4E81-A5F0-545A8E669BDF} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {E3E277BB-FCFB-4D8A-AC90-D435A8D064AB}. Trying to use the recording date. doc_dict: {'alias': 'paris_parle', 'date_str': None, 'stt_filename': 'E3E277BB-FCFB-4D8A-AC90-D435A8D064AB_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{E3E277BB-FCFB-4D8A-AC90-D435A8D064AB}', 'stripped_OID': 'E3E277BB-FCFB-4D8A-AC90-D435A8D064AB', 'login': '', 'broadcast_episode_title': "Arriv?e de Harry Truman, ancien pr?sident des Etats-Unis, ? Paris : A l'occasion de son voyage ? travers l'Europe", 'sequence': '1', 'broadcast_program_name': 'Paris vous parle', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '30.07.2016 21:09:37', 'physical_support_history': "Cote d'origine : MA 5632.p", 'production_type': 'Production ext?rieure (?change)', 'recording_place': None, 'rights_notes': None, 'rights_status': 'A rechercher', 'series_title': "Sauvegarde d'archives", 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Werther, Maurice', 'function': 'Commentateur/trice', 'role': 'jounaliste'}, {'name': 'Truman, Harry', 'function': 'Interview?/e', 'role': 'ancien pr?sident des Etats-Unis'}, {'name': 'Werther, Maurice', 'function': 'Intervieweur/euse', 'role': 'journaliste'}], 'geographical_descriptors': ['Etats-Unis', 'France'], 'person_descriptors': ['Truman, Harry'], 'thematical_descriptors': ['relations internationales'], 'rights_usage_possibilities': ['FM'], 'radio_channels': ['Radio Sottens'], 'subdomains': ['Commentaire', 'Interview'], 'recording_dates': ['15/05/1956 - 15/05/1956'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {F52E4375-810D-4B72-98B4-3944A8A31B4C}. Trying to use the recording date. doc_dict: {'alias': 'paris_parle', 'date_str': None, 'stt_filename': 'F52E4375-810D-4B72-98B4-3944A8A31B4C_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{F52E4375-810D-4B72-98B4-3944A8A31B4C}', 'stripped_OID': 'F52E4375-810D-4B72-98B4-3944A8A31B4C', 'login': '', 'broadcast_episode_title': 'Bapt?me catholique ? Reims de Tsugouharu Foujita, artiste peintre, qui devient L?onard Foutjita', 'sequence': '1', 'broadcast_program_name': 'Paris vous parle', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'brucklbo', 'modified_on': '17.07.2020 10:46:58', 'physical_support_history': "Cote d'origine: MA 59.43 PL. D.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'A rechercher', 'series_title': None, 'content_summary': 'choisit nom de L?onard par Mgr Bezot(?), ?v?que auxiliare de Reims', 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': None, 'modulation_type': 'Mono', 'work_duration': '00:01:33.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Foujita, L?onard', 'function': "Auteur d'une d?claration", 'role': 'artiste peintre'}], 'geographical_descriptors': None, 'person_descriptors': ['Foujita, L?onard'], 'thematical_descriptors': ['bapt?me'], 'rights_usage_possibilities': None, 'radio_channels': None, 'subdomains': ['D?claration'], 'recording_dates': ['21/07/1959 - 21/07/1959'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {085E7818-74AF-487E-B20C-3FFC1C294577}. Trying to use the recording date. doc_dict: {'alias': 'paris_parle', 'date_str': None, 'stt_filename': '085E7818-74AF-487E-B20C-3FFC1C294577_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{085E7818-74AF-487E-B20C-3FFC1C294577}', 'stripped_OID': '085E7818-74AF-487E-B20C-3FFC1C294577', 'login': '', 'broadcast_episode_title': "B?n?diction d'un temple ? Monaco par Marc Boegner, pasteur", 'sequence': '1', 'broadcast_program_name': 'Paris vous parle', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'brucklbo', 'modified_on': '02.07.2020 10:09:28', 'physical_support_history': "Cote d'origine: MA 59.43 PL. A.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'A rechercher', 'series_title': None, 'content_summary': '+choeur', 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': None, 'modulation_type': 'Mono', 'work_duration': '00:01:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Boegner, Marc', 'function': "Auteur d'une d?claration", 'role': 'pasteur'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': ['b?n?diction', 'christianisme'], 'rights_usage_possibilities': None, 'radio_channels': None, 'subdomains': ['D?claration'], 'recording_dates': ['12/10/1959 - 12/10/1959'], 'first_broadcast_dates': None}
Skipping document 15/295 with OID {A276492C-AF18-46B7-B0EE-4CEC3E8BD76E} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {4C121CD9-9DA2-47C7-A3C1-85D4BD8F66C9}. Trying to use the recording date. doc_dict: {'alias': 'paris_parle', 'date_str': None, 'stt_filename': '4C121CD9-9DA2-47C7-A3C1-85D4BD8F66C9_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{4C121CD9-9DA2-47C7-A3C1-85D4BD8F66C9}', 'stripped_OID': '4C121CD9-9DA2-47C7-A3C1-85D4BD8F66C9', 'login': '', 'broadcast_episode_title': "Comm?moration ? Paris du 11?me anniversaire de l'armistice. Le pr?sident de la R?publique fran?aise Ren? Coty ? la place de l'Etoile", 'sequence': '1', 'broadcast_program_name': 'Paris vous parle', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '04.08.2016 13:44:10', 'physical_support_history': "Cote d'origine : MA 5632.f", 'production_type': 'Production ext?rieure (?change)', 'recording_place': None, 'rights_notes': None, 'rights_status': 'A rechercher', 'series_title': "Sauvegarde d'archives", 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Droit, Michel', 'function': 'Reporter', 'role': 'journaliste'}], 'geographical_descriptors': ['France'], 'person_descriptors': None, 'thematical_descriptors': ['comm?moration', 'guerre mondiale (deuxi?me)'], 'rights_usage_possibilities': ['FM'], 'radio_channels': ['Radio Sottens'], 'subdomains': ['Reportage'], 'recording_dates': ['08/05/1956 - 08/05/1956'], 'first_broadcast_dates': None}
Skipping document 17/295 with OID {C190E8D8-18C2-43F1-9F87-EBCE9C43DCAD} because it's missing its XML file!! (stt exists: False)

100%|██████████| 1/1 [00:01<00:00,  1.29s/it]
40it [02:28,  1.46s/it]

Did not find any date for doc with OID {1BB6B790-402E-42BA-9419-323AB72EE276}. Trying to use the recording date. doc_dict: {'alias': 'paris_parle', 'date_str': None, 'stt_filename': '1BB6B790-402E-42BA-9419-323AB72EE276_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{1BB6B790-402E-42BA-9419-323AB72EE276}', 'stripped_OID': '1BB6B790-402E-42BA-9419-323AB72EE276', 'login': '', 'broadcast_episode_title': "Le pape Jean XXIII en visite ? l'?glise Saint-Louis des Fran?ais de Rome", 'sequence': '1', 'broadcast_program_name': 'Paris vous parle', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '04.08.2016 08:18:38', 'physical_support_history': "Cote d'origine: MA 59.12 PL. J.", 'production_type': 'Production ext?rieure (?change)', 'recording_place': 'Rome (Eglise Saint-Louis)', 'rights_notes': 'Memoriav', 'rights_status': 'A rechercher', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Commentaires, discours et cantiques.', 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:02:04.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Inconnu', 'function': 'Commentateur/trice', 'role': 'journaliste'}, {'name': 'Jean XXIII [= Roncalli, Angelo Giuseppe]', 'function': "Auteur d'une d?claration", 'role': 'pape'}], 'geographical_descriptors': ['Rome'], 'person_descriptors': None, 'thematical_descriptors': ['pape'], 'rights_usage_possibilities': ['FM'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Reportage', 'D?claration'], 'recording_dates': ['18/02/1959 - 18/02/1959'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {156F6A05-D300-47BF-84DB-57185618431A}. Trying to use the recording date. doc_dict: {'alias': 'paris_parle', 'date_str': None, 'stt_filename': '156F6A05-D300-47BF-84DB-57185618431A_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{156F6A05-D300-47BF-84DB-57185618431A}', 'stripped_OID': '156F6A05-D300-47BF-84DB-57185618431A', 'login': '', 'broadcast_episode_title': 'Le Prix Nobel de litt?rature 1960 est attribu? au po?te Alexis L?ger, dit Saint-John Perse', 'sequence': '1', 'broadcast_program_name': 'Paris vous parle', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '08.05.2018 16:23:13', 'physical_support_history': "Cote d'origine: MA 60.62 Pl. F", 'production_type': 'Production propre', 'recording_place': 'Marseille', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': 'Une journaliste t?l?phone ? Saint-John Perse chez lui avec en bruit de fond le brouhaha des journalistes. (02.48) Alexandre Malraux, ministre de la culture. (03.55) Fran?ois Mauriac, amis d?s 18 ans. (06.16) Jean Paulhan, directeur NRF.', 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:09:24.835', 'work_duration_compl': 'Non', 'participants': [{'name': 'Saint-John Perse', 'function': 'Interview?/e', 'role': 'po?te, prix Nobel de litt?rature'}, {'name': 'Bonfils, Violette', 'function': 'Intervieweur/euse', 'role': 'journaliste fran?aise, correspondante ? Marseille'}, {'name': 'Mauriac, Fran?ois', 'function': 'Interview?/e', 'role': '?crivain'}, {'name': 'Chonez, Claudine', 'function': 'Intervieweur/euse', 'role': 'journaliste fran?aise'}, {'name': 'Malraux, Andr?', 'function': 'Interview?/e', 'role': '?crivain'}, {'name': 'Paulhan, Jean', 'function': 'Interview?/e', 'role': 'directeur de la Nouvelle Revue fran?aise'}], 'geographical_descriptors': None, 'person_descriptors': ['NRF', 'Saint-John Perse'], 'thematical_descriptors': ['litt?rature', 'po?sie'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Reportage', 'Interview'], 'recording_dates': ['26/10/1960 - 26/10/1960'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {B1FD5A20-3FB3-4006-BAAD-29DD88F644FF}. Trying to use the recording date. doc_dict: {'alias': 'paris_parle', 'date_str': None, 'stt_filename': 'B1FD5A20-3FB3-4006-BAAD-29DD88F644FF_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{B1FD5A20-3FB3-4006-BAAD-29DD88F644FF}', 'stripped_OID': 'B1FD5A20-3FB3-4006-BAAD-29DD88F644FF', 'login': '', 'broadcast_episode_title': "Lecture d'un d?claration de Charles de Gaulle, pr?sident de la r?publique fran?aise par Louis Terrenoire, ministre de l'information : A propos de la situation en Alg?rie", 'sequence': '1', 'broadcast_program_name': 'Paris vous parle', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '06.04.2020 14:55:20', 'physical_support_history': "Cote d'origine: MA 61.8 PL. L.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:04:04.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Terrenoire, Louis', 'function': "Auteur d'une d?claration", 'role': "ministre de l'information"}], 'geographical_descriptors': ['Alg?rie', 'France'], 'person_descriptors': ['Gaulle, Charles de'], 'thematical_descriptors': ["guerre d'Alg?rie", 'colonialisme'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Premier programme'], 'subdomains': ['Interview'], 'recording_dates': ['25/04/1961 - 25/04/1961'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {ED7BDE8D-3D61-4AE1-BE3C-0AFEB84843B1}. Trying to use the recording date. doc_dict: {'alias': 'paris_parle', 'date_str': None, 'stt_filename': 'ED7BDE8D-3D61-4AE1-BE3C-0AFEB84843B1_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{ED7BDE8D-3D61-4AE1-BE3C-0AFEB84843B1}', 'stripped_OID': 'ED7BDE8D-3D61-4AE1-BE3C-0AFEB84843B1', 'login': '', 'broadcast_episode_title': 'Les Harlem Globetrotters, baketeurs, ? Paris : Souvenir de leur r?ception par le pape Pi XII', 'sequence': '1', 'broadcast_program_name': 'Paris vous parle', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'BBR (NumA)', 'modified_on': '02.08.2016 22:48:03', 'physical_support_history': "Cote d'origine : MA 5642.f Resp. RSR : BBR Lot : Caisse 2134", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Participant: com:Cypriani, Ren?;  production ext?rieur, d?tenteurs droits INA', 'workflow_status': 'Accept?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': None, 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Radio Sottens'], 'subdomains': None, 'recording_dates': ['07/06/1956 - 07/06/1956'], 'first_broadcast_dates': None}
Skipping document 248/295 with OID {5837BEAE-2416-45A4-96FF-F0741B986FC8} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {1D710DAF-72F1-4750-A482-80046B8D2D02}. Trying to use the recording date. doc_dict: {'alias': 'paris_parle', 'date_str': None, 'stt_filename': '1D710DAF-72F1-4750-A482-80046B8D2D02_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{1D710DAF-72F1-4750-A482-80046B8D2D02}', 'stripped_OID': '1D710DAF-72F1-4750-A482-80046B8D2D02', 'login': '', 'broadcast_episode_title': "M. Vinogradov, ambassadeur de l'URSS ? Paris", 'sequence': '1', 'broadcast_program_name': 'Paris vous parle', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'BBR (NumA)', 'modified_on': '04.08.2016 12:28:57', 'physical_support_history': "Cote d'origine : MA 5632.m Resp. RSR : BBR Lot : Caisse 2134", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Participant: div:Vinogradov, Sergue?;  production ext?rieur, d?tenteurs droits INA', 'workflow_status': 'Accept?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': None, 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Werther, Maurice', 'function': 'Commentateur/trice', 'role': 'collaborateur/trice RSR'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Radio Sottens'], 'subdomains': None, 'recording_dates': ['12/05/1956 - 12/05/1956'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {00387E2E-D1FC-47E7-AD23-C5ADB92E968F}. Trying to use the recording date. doc_dict: {'alias': 'paris_parle', 'date_str': None, 'stt_filename': '00387E2E-D1FC-47E7-AD23-C5ADB92E968F_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{00387E2E-D1FC-47E7-AD23-C5ADB92E968F}', 'stripped_OID': '00387E2E-D1FC-47E7-AD23-C5ADB92E968F', 'login': '', 'broadcast_episode_title': 'Mariage de Genevi?ve de Gallard', 'sequence': '1', 'broadcast_program_name': 'Paris vous parle', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'BBR (NumA)', 'modified_on': '04.08.2016 21:12:43', 'physical_support_history': "Cote d'origine : MA 5642.i Resp. RSR : BBR Lot : Caisse 2134", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': 'production ext?rieur, d?tenteurs droits INA', 'workflow_status': 'Accept?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': None, 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Elina, Lise', 'function': 'Reporter', 'role': 'collaborateur/trice RSR'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Radio Sottens'], 'subdomains': None, 'recording_dates': ['14/06/1956 - 14/06/1956'], 'first_broadcast_dates': None}
Skipping document 252/295 with OID {3BF411B9-7A55-4980-8D4B-1DF5A0CAEE7A} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {2F7F04D7-DE0E-474E-AB16-063A02064BCD}. Trying to use the recording date. doc_dict: {'alias': 'paris_parle', 'date_str': None, 'stt_filename': '2F7F04D7-DE0E-474E-AB16-063A02064BCD_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{2F7F04D7-DE0E-474E-AB16-063A02064BCD}', 'stripped_OID': '2F7F04D7-DE0E-474E-AB16-063A02064BCD', 'login': '', 'broadcast_episode_title': "Ouverture de la convention d?mocrate pour la campagne ?lectorale am?ricaine ? Los Angeles : D?claration d'ouverture Paul M. Butler, pr?sident du comit? d?mocrate [en anglais]", 'sequence': '1', 'broadcast_program_name': 'Paris vous parle', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'brucklbo', 'modified_on': '18.06.2020 10:50:04', 'physical_support_history': "Cote d'origine: MA60_38A.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': "Ouverture convention d?mocrate ? Los Angeles JF Kennedy sera probablement ?lu mercredi ? la pr?sidence au 1er tour 0'40'': Pr?sident Butter use de son marteau", 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:00:53.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Butler, Paul', 'function': "Auteur d'une d?claration", 'role': 'pr?sident du comit? d?mocrate'}, {'name': 'Inconnu', 'function': 'Commentateur/trice', 'role': 'journaliste'}], 'geographical_descriptors': ['Etats-Unis'], 'person_descriptors': None, 'thematical_descriptors': ['?lection', '?lection pr?sidentielle'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': ['Commentaire', 'D?claration'], 'recording_dates': ['12/07/1960 - 12/07/1960'], 'first_broadcast_dates': None}
Skipping document 254/295 with OID {215069FD-3C7D-4D18-B052-E7E6D22B2FDC} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {DD26F963-A396-4F2F-A0CF-83FE1FE4A9E5}. Trying to use the recording date. doc_dict: {'alias': 'paris_parle', 'date_str': None, 'stt_filename': 'DD26F963-A396-4F2F-A0CF-83FE1FE4A9E5_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{DD26F963-A396-4F2F-A0CF-83FE1FE4A9E5}', 'stripped_OID': 'DD26F963-A396-4F2F-A0CF-83FE1FE4A9E5', 'login': '', 'broadcast_episode_title': "Passage d'un discours de Georges Chastenet : A propos de son entr?e ? l'Acad?mie", 'sequence': '1', 'broadcast_program_name': 'Paris vous parle', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'BBR (NumA)', 'modified_on': '05.08.2016 16:15:46', 'physical_support_history': "Cote d'origine : MA 5727.i Resp. RSR : BBR Lot : Caisse 2134", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Participant: decl:Chastenet, Georges;  production ext?rieur, d?tenteurs droits INA', 'workflow_status': 'Accept?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': None, 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': None, 'recording_dates': ['28/12/1957 - 28/12/1957'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {C29E0A3E-E465-4CF6-88CC-D7FED962ACF7}. Trying to use the recording date. doc_dict: {'alias': 'paris_parle', 'date_str': None, 'stt_filename': 'C29E0A3E-E465-4CF6-88CC-D7FED962ACF7_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{C29E0A3E-E465-4CF6-88CC-D7FED962ACF7}', 'stripped_OID': 'C29E0A3E-E465-4CF6-88CC-D7FED962ACF7', 'login': '', 'broadcast_episode_title': "Passage d'un discours de Monsieur F. Gaillard aux Assises Radicales", 'sequence': '1', 'broadcast_program_name': 'Paris vous parle', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'BBR (NumA)', 'modified_on': '01.08.2016 12:18:49', 'physical_support_history': "Cote d'origine : MA 5727.h Resp. RSR : BBR Lot : Caisse 2134", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': 'production ext?rieur, d?tenteurs droits INA', 'workflow_status': 'Accept?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': None, 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Rossini, Pascal', 'function': 'Reporter', 'role': 'collaborateur/trice RSR'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': None, 'recording_dates': ['23/12/1957 - 23/12/1957'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {F9D396BA-CB61-411B-B699-15AB87760E1F}. Trying to use the recording date. doc_dict: {'alias': 'paris_parle', 'date_str': None, 'stt_filename': 'F9D396BA-CB61-411B-B699-15AB87760E1F_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{F9D396BA-CB61-411B-B699-15AB87760E1F}', 'stripped_OID': 'F9D396BA-CB61-411B-B699-15AB87760E1F', 'login': '', 'broadcast_episode_title': "Philibert Tsiranana, pr?sident malgache est satisfait des entretiens portant sur l'ind?pendance de Madagascar", 'sequence': '1', 'broadcast_program_name': 'Paris vous parle', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '25.04.2017 12:10:56', 'physical_support_history': "Cote d'origine: MA 603 Pl. G", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'A rechercher', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:33.780', 'work_duration_compl': 'Non', 'participants': [{'name': 'Tsiranana, Philibert', 'function': 'Interview?/e', 'role': 'pr?sident malgache'}], 'geographical_descriptors': ['Madagascar', 'France'], 'person_descriptors': ['Tsiranana, Philibert'], 'thematical_descriptors': ['ind?pendantisme', 'diplomatie', 'r?union internationale'], 'rights_usage_possibilities': None, 'radio_channels': None, 'subdomains': ['Interview'], 'recording_dates': ['11/02/1960 - 11/02/1960'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {DC98546E-3F1F-41B3-9593-DD69D683A585}. Trying to use the recording date. doc_dict: {'alias': 'paris_parle', 'date_str': None, 'stt_filename': 'DC98546E-3F1F-41B3-9593-DD69D683A585_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{DC98546E-3F1F-41B3-9593-DD69D683A585}', 'stripped_OID': 'DC98546E-3F1F-41B3-9593-DD69D683A585', 'login': '', 'broadcast_episode_title': 'Pierre Commun, chef d?l?g. soc. ? Moscou : A propos des rapports entre les partis socialistes et communistes fran?ais', 'sequence': '1', 'broadcast_program_name': 'Paris vous parle', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'BBR (NumA)', 'modified_on': '04.08.2016 11:01:48', 'physical_support_history': "Cote d'origine : MA 5632.n Resp. RSR : BBR Lot : Caisse 2134", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': 'production ext?rieur, d?tenteurs droits INA', 'workflow_status': 'Accept?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': None, 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Commun, Pierre', 'function': 'Interview?/e', 'role': None}, {'name': 'Rabaud, Jean', 'function': 'Intervieweur/euse', 'role': 'collaborateur/trice RSR'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Radio Sottens'], 'subdomains': None, 'recording_dates': ['14/05/1956 - 14/05/1956'], 'first_broadcast_dates': None}

Starting extracting 187 documents for program parole_prem
Did not find any date for doc with OID {9073622E-DBE5-4A08-89F8-480162302836}. Trying to use the recording date. doc_dict: {'alias': 'parole_prem', 'date_str': None, 'stt_filename': '9073622E-DBE5-4A08-89F8-480162302836_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{9073622E-DBE5-4A08-89F8-480162302836}', 'stripped_OID': '9073622E-DBE5-4A08-89F8-480162302836', 'login': '', 'broadcast_episode_title': "Jura, l'?tat de la question. Reportage de Frank Musy, collaborateur RSR, dans le Jura bernois et dans le canton du Jura", 'sequence': '1', 'broadcast_program_name': 'Parole de Premi?re', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'prongudo', 'modified_on': '27.04.2015 14:48:40', 'physical_support_history': "Cote d'origine: A 20805", 'production_type': 'Production propre', 'recording_place': 'Moutier. Tavannes. Del?mont', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives. Jura", 'content_summary': "Reportage au sein du FC Moutier, qui n'a pas ?clat? ? cause de la question jurassienne. Extrait du programme RJB-Horizon 9. Fr?d?rique Santal explique que la r?gion doit apprendre ? vivre avec la d?chirure qu'elle a v?cu. Jean-Claude Rennwald dit sa d?ception de ce qui se passe dans le Jura. Roland B?guelin dit que le RJ n'est pas l?ch? par le gouvernement et Fran?ois Mertenat, ministre jurassien affirme que le gouvernement n'est pas sous la coupe du RJ. Vino Montavon, dentiste ? Moutier, tourne un film de fiction sur la pierre d'Uspunnen. Fran?ois Boillat, avocat ? Moutier, qui affirme que les gens du sud doivent compter sur eux et non sur les gens du nord. Pour Robert Huttenlocher, pasteur ? Moutier, qui explique que deux populations vivent l'une ? c?t? de l'autre ? Moutier. H?l?ne et Jean-Louis Cano, ? la t?te d'une entreprise de pompes fun?bres ? Moutier, qui disent la division de la ville", 'workflow_status': 'Valid?', 'assembly_status': 'Pr?t', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:18:45.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Dubois, Marianne', 'function': 'Interview?/e', 'role': 'auditrice qui a propos? le sujet de ce Parole de Premi?re, habitante de Muri'}, {'name': 'Sbaraglia, Vincent', 'function': 'Interview?/e', 'role': 'entra?neur du FC Moutier'}, {'name': 'Santal, Fr?d?rique', 'function': 'Interview?/e', 'role': 'RJB Tavannes'}, {'name': 'Rennwald, Jean-Claude', 'function': 'Interview?/e', 'role': 'r?dacteur en chef de Fr?quence Jura'}, {'name': 'B?guelin, Roland', 'function': 'Interview?/e', 'role': 'secr?taire g?n?ral du Rassemblement jurassien'}, {'name': 'Mertenat, Fran?ois', 'function': 'Interview?/e', 'role': 'ministre jurassien'}, {'name': 'Montavon, Vino', 'function': 'Interview?/e', 'role': 'dentiste ? Moutier'}, {'name': 'Boillat, Fran?ois', 'function': 'Interview?/e', 'role': 'avovat ? Moutier'}, {'name': 'Huttenlocher, Robert', 'function': 'Interview?/e', 'role': 'pasteur ? Moutier'}, {'name': 'Cano, H?l?ne', 'function': 'Interview?/e', 'role': 'entreprise de pompes fun?bres Moutier'}, {'name': 'Cano, Jean-Louis', 'function': 'Interview?/e', 'role': 'entreprise de pompes fun?bres Moutier'}, {'name': 'Musy, Frank', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Jura bernois', 'Jura (canton)'], 'person_descriptors': None, 'thematical_descriptors': ['question jurassienne'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Interview'], 'recording_dates': ['20/09/1986 - 20/09/1986'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {CF4ADD75-DDA8-4621-BA7C-1F394525F0AC}. Trying to use the recording date. doc_dict: {'alias': 'parole_prem', 'date_str': None, 'stt_filename': 'CF4ADD75-DDA8-4621-BA7C-1F394525F0AC_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{CF4ADD75-DDA8-4621-BA7C-1F394525F0AC}', 'stripped_OID': 'CF4ADD75-DDA8-4621-BA7C-1F394525F0AC', 'login': '', 'broadcast_episode_title': "L'art du langage : le verbe arc-en-ciel. T?moignages (avec ?l?ments d'archives RSR)", 'sequence': '1', 'broadcast_program_name': 'Parole de Premi?re', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'albrecjo', 'modified_on': '28.04.2015 02:53:37', 'physical_support_history': "Cote d'origine: A 21370.", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives. Fribourg", 'content_summary': "Elocution et prononciation des mots. La voix comme reflet de notre caract?re et moyen de persuasion. Communication, m?dias et politique. Les pr?dicateurs et l'art de convaincre. Les troubles de l'?locution et du langage.", 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:19:06.924', 'work_duration_compl': 'Non', 'participants': [{'name': 'Zollikofer, Lucette', 'function': 'Divers', 'role': 'auditrice de Marin'}, {'name': 'Savigny, Jane', 'function': 'Interview?/e', 'role': 'com?dienne'}, {'name': 'Dutoit Marco, Mary-Louise', 'function': 'Interview?/e', 'role': 'sp?cialiste ORL'}, {'name': 'Sonnay, Bertrand', 'function': 'Interview?/e', 'role': 'vendeur ? la cri?e'}, {'name': 'Katz, Roland', 'function': 'Interview?/e', 'role': 'publicitaire'}, {'name': 'Rossi, Pierre-Pascal', 'function': 'Interview?/e', 'role': 'journaliste RTSR'}, {'name': 'Girardin, Manuel', 'function': 'Intervieweur/euse', 'role': 'collaborateur/trice RSR'}, {'name': 'Morand, Philippe', 'function': 'Interview?/e', 'role': 'com?dien'}, {'name': 'Crausaz, Roselyne', 'function': 'Interview?/e', 'role': "conseill?re d'Etat fribourgeoise"}, {'name': 'Babel, Henry', 'function': 'Interview?/e', 'role': 'pasteur'}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': ['expression orale', 'langage politique', 'langage', 'politique', 'trouble du langage', 'voix', 'mass m?dia', "communication de l'information", 'com?dien'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Premier programme'], 'subdomains': ['Interview'], 'recording_dates': ['11/04/1987 - 11/04/1987'], 'first_broadcast_dates': None}
The date for document with OID {EF8741F7-4ED6-4B15-A64D-E200B865391A} was invalid (__/__/1989) - changed it to 01/01/1989
The date for document with OID {EF8741F7-4ED6-4B15-A64D-E200B865391A} was invalid (__/__/1989) - changed it to 01/01/1989
Did not find any date for doc with OID {AEC1EFCD-F9C4-42FD-BEC1-0FFC48262270}. Trying to use the recording date. doc_dict: {'alias': 'parole_prem', 'date_str': None, 'stt_filename': 'AEC1EFCD-F9C4-42FD-BEC1-0FFC48262270_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{AEC1EFCD-F9C4-42FD-BEC1-0FFC48262270}', 'stripped_OID': 'AEC1EFCD-F9C4-42FD-BEC1-0FFC48262270', 'login': '', 'broadcast_episode_title': "Le travail et la vie des correspondants de la Radio Suisse Romande. T?moignages (avec ?l?ments d'archives RSR)", 'sequence': '1', 'broadcast_program_name': 'Parole de Premi?re', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'albrecjo', 'modified_on': '24.04.2015 11:22:37', 'physical_support_history': "Cote d'origine: A 21024", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': '"Sans leur voix, sans leur pr?sence r?guli?re ? l\'antenne et sans leur chasse permanente ? l\'information en coulisse, la radio n\'offrirait pas d\'images!" Le travail du correspondant dans un pays en guerre, ? l\'?tranger, dans une r?gion suisse romande ou au Conseil f?d?ral.', 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:19:19.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Inconnu', 'function': 'Divers', 'role': 'auditeur'}, {'name': 'Froidevaux, Claude', 'function': 'Interview?/e', 'role': 'correspondant RSR ? Washington'}, {'name': 'Roch, Dominique', 'function': 'Interview?/e', 'role': 'correspondante RSR ? Beyrouth'}, {'name': 'Kottelat, Philippe', 'function': 'Interview?/e', 'role': 'correspoondant RSR ? Paris'}, {'name': 'Jaccard, Mich?le', 'function': 'Interview?/e', 'role': 'correspondante ? Neuch?tel'}], 'geographical_descriptors': ['Beyrouth', 'Neuch?tel (canton)', 'Paris', 'Washington'], 'person_descriptors': ['Radio Suisse Romande'], 'thematical_descriptors': ['conflit arm?', 'journaliste', 'radio', 'journalisme'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Interview'], 'recording_dates': ['03/06/1989 - 03/06/1989'], 'first_broadcast_dates': None}

100%|██████████| 1/1 [00:00<00:00,  1.11it/s]

Did not find any date for doc with OID {4B65391D-B2D5-4D0C-A265-FC657B265BC3}. Trying to use the recording date. doc_dict: {'alias': 'parole_prem', 'date_str': None, 'stt_filename': '4B65391D-B2D5-4D0C-A265-FC657B265BC3_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{4B65391D-B2D5-4D0C-A265-FC657B265BC3}', 'stripped_OID': '4B65391D-B2D5-4D0C-A265-FC657B265BC3', 'login': '', 'broadcast_episode_title': "Les myst?res du Temple ou la franc-ma?onnerie aujourd'hui. T?moignages", 'sequence': '1', 'broadcast_program_name': 'Parole de Premi?re', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'albrecjo', 'modified_on': '28.04.2015 02:44:25', 'physical_support_history': "Cote d'origine: A 6565", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives. Fribourg", 'content_summary': "Origine et constitution des francs-ma?ons en loges. Pr?sentation de la Grande loge de Suisse. Introduction des nouveaux membres par cooptation. Entr?e dans le temple, c?r?monie et rituels. Le r?le et la signification des symboles. La Grande loge f?minine de Suisse. Le r?le de la franc-ma?onnerie dans la formation de l'Europe moderne. Les r?ticences de l'Eglise catholique romaine et les relations avec l'Eglise r?form?e.", 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:19:44.680', 'work_duration_compl': 'Non', 'participants': [{'name': 'Dunand, Jean-Philippe', 'function': 'Divers', 'role': 'auditeur'}, {'name': 'Girod, Paul', 'function': 'Interview?/e', 'role': 'grand ma?tre de la grande loge de Suisse'}, {'name': 'Chevallaz, Georges-Andr?', 'function': 'Interview?/e', 'role': 'ancien conseiller f?d?ral'}, {'name': 'Cottier, Georges', 'function': 'Interview?/e', 'role': 'dominicain et membre du secr?tariat pour les non-croyants'}, {'name': 'Barbier, Jean-Pierre', 'function': 'Interview?/e', 'role': 'pasteur'}], 'geographical_descriptors': ['Suisse romande'], 'person_descriptors': None, 'thematical_descriptors': ['franc-ma?onnerie', 'symbole (signe)', 'rite', 'secret', 'histoire', 'catholicisme', 'protestantisme', 'Eglise (soci?t?)'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Interview'], 'recording_dates': ['23/05/1987 - 23/05/1987'], 'first_broadcast_dates': None}
Did not find any date for doc with OID {4855A799-4E99-417D-96E0-40DCEE39E918}. Trying to use the recording date. doc_dict: {'alias': 'parole_prem', 'date_str': None, 'stt_filename': '4855A799-4E99-417D-96E0-40DCEE39E918_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{4855A799-4E99-417D-96E0-40DCEE39E918}', 'stripped_OID': '4855A799-4E99-417D-96E0-40DCEE39E918', 'login': '', 'broadcast_episode_title': 'Paroles de chasseurs. T?moignages', 'sequence': '1', 'broadcast_program_name': 'Parole de Premi?re', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'albrecjo', 'modified_on': '30.04.2015 00:28:44', 'physical_support_history': "Cote d'origine: A 21661", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives. Fribourg", 'content_summary': "L'observation des animaux dans leur habitat naturel. Le r?le des chasseurs dans la r?gulation des esp?ces animales. La position du WWF sur la chasse et le braconnage. Les activit?s d'un garde-chasse dans la commune du Ch?telard. La chasse entre r?glementation et droit naturel. Changement des mentalit?s.", 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:19:02.101', 'work_duration_compl': 'Non', 'participants': [{'name': 'Mathey, Blaise', 'function': 'Divers', 'role': 'auditeur de Saint-Aubin'}, {'name': 'Rime, Jacques', 'function': 'Interview?/e', 'role': 'dessinateur et peintre animalier'}, {'name': 'Inconnus', 'function': 'Interview?/e', 'role': 'chasseurs de Conthey'}, {'name': 'Ansermet, Serge', 'function': 'Interview?/e', 'role': 'secr?taire g?n?ral du WWF, section vaudoise'}, {'name': 'Fragni?re, Andr?', 'function': 'Interview?/e', 'role': 'garde-chasse, Avry-devant-Pont'}, {'name': 'Niclasse, Hubert', 'function': 'Interview?/e', 'role': 'dominicain ? Fribourg'}, {'name': 'Rohrbasser, Bernard', 'function': 'Interview?/e', 'role': 'pr?fet de la Veveyse'}], 'geographical_descriptors': ['Fribourg (canton)', 'Le Ch?telard', 'Conthey', 'Veveyse (district, FR)'], 'person_descriptors': None, 'thematical_descriptors': ['chasse', 'faune', 'braconnage', "protection de l'environnement", 'r?glementation', 'art animalier'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Interview'], 'recording_dates': ['20/10/1990 - 20/10/1990'], 'first_broadcast_dates': None}
parole_prem - returning 187 documents, 0 were skipped due to missing necessary info.
 --> Adding 187 to the out csv for parole_prem

41it [02:29,  1.34s/it]

PROCESSING PROGRAM petitdej (42/47) - 3 files:

Starting extracting 998 documents for program petitdej
Skipping document 9/998 with OID {D623A5B4-16FE-458E-AEE5-06CC40229300} because it's missing its XML file!! (stt exists: False)
Skipping document 18/998 with OID {C7D7A18B-E50A-4331-ADD1-8E4514C110E6} because it's missing its XML file!! (stt exists: False)
Skipping document 20/998 with OID {BE70867C-7B4F-45F9-B667-47B80CA332B1} because it's missing its XML file!! (stt exists: False)
Skipping document 22/998 with OID {D5BCF14A-C5BA-4141-865C-83602CE946F1} because it's missing its XML file!! (stt exists: False)
Skipping document 27/998 with OID {E95E2728-8887-409B-8E7B-EDCCB8B97C5B} because it's missing its XML file!! (stt exists: False)
Skipping document 28/998 with OID {6D4685E0-2BAC-4FD7-8B39-6875C877CED5} because it's missing its XML file!! (stt exists: False)
Skipping document 32/998 with OID {CAEE0BB7-CF07-4F8A-A5D5-EC1438D3A9ED} because it's missing its XML file!! (stt exists: False)
Skipping document 35/998 with OID {ADF79145-0CCE-4F4C-A8AF-4F15004BCD63} because it's missing its XML file!! (stt exists: False)
Skipping document 39/998 with OID {57C328BF-CF4F-401D-A208-4B271CC0ABB1} because it's missing its XML file!! (stt exists: False)
Skipping document 43/998 with OID {841EC159-C56C-4927-8A50-FDAEEE9CE3D2} because it's missing its XML file!! (stt exists: False)
Skipping document 48/998 with OID {4568B5C7-7F73-4F96-99E4-2C4BA855C251} because it's missing its XML file!! (stt exists: False)
Skipping document 55/998 with OID {1DF04FC5-4EEC-46A9-B5A4-315AECC9BE58} because it's missing its XML file!! (stt exists: False)
Skipping document 56/998 with OID {55D8D238-972B-4BE1-BE1B-AFF56B6C3D73} because it's missing its XML file!! (stt exists: False)
Skipping document 58/998 with OID {05B27A18-416A-4317-A2E2-BC8D74C78B8D} because it's missing its XML file!! (stt exists: True)
Skipping document 86/998 with OID {2F4283C3-F720-447A-A59B-FF2BFF1F787A} because it's missing its XML file!! (stt exists: False)
Skipping document 91/998 with OID {AB6EFA65-77C1-43AE-B279-9A615A57528E} because it's missing its XML file!! (stt exists: False)
Skipping document 94/998 with OID {BFE306C3-22CE-4919-924E-DDEBFA0EAC1B} because it's missing its XML file!! (stt exists: True)
Skipping document 106/998 with OID {144AFC0A-770D-4C66-B3A8-A37A37F9B940} because it's missing its XML file!! (stt exists: False)
Skipping document 116/998 with OID {ECAD527A-1E40-4B93-8CFA-88D088A35F9B} because it's missing its XML file!! (stt exists: False)
Skipping document 117/998 with OID {C2B92637-9BDE-4570-974D-A1DB8C389BC6} because it's missing its XML file!! (stt exists: False)
Skipping document 122/998 with OID {08A3F6F6-DCAA-4F7A-96E2-5DAA700F6DC9} because it's missing its XML file!! (stt exists: False)
Skipping document 125/998 with OID {1E6B0447-BAA1-49AE-A954-93F707573F0C} because it's missing its XML file!! (stt exists: False)
Skipping document 130/998 with OID {82BF840D-34CF-4940-A7A3-D96885295502} because it's missing its XML file!! (stt exists: False)
Skipping document 134/998 with OID {C8FA34C3-4A20-4969-9774-8A37011C586D} because it's missing its XML file!! (stt exists: True)
Skipping document 136/998 with OID {C74B794E-F1E7-45BF-BE78-AB0F2211F84D} because it's missing its XML file!! (stt exists: False)
Skipping document 137/998 with OID {38F1EA58-78C7-4FFF-811D-29FDC701D811} because it's missing its XML file!! (stt exists: False)
Skipping document 143/998 with OID {5FA31A97-FA0C-4784-965B-4F0AEF0509D5} because it's missing its XML file!! (stt exists: False)
Skipping document 157/998 with OID {C8C729D5-F0E2-4A6C-8A49-C1F3A502B05E} because it's missing its XML file!! (stt exists: False)
Skipping document 158/998 with OID {4D69E9C8-65A6-4555-BBAE-735495B491D8} because it's missing its XML file!! (stt exists: False)
Skipping document 159/998 with OID {93C80C3F-6048-4E7D-AA29-9B94E5588188} because it's missing its XML file!! (stt exists: False)
Skipping document 163/998 with OID {ADB18616-2874-4529-967A-F30E5B9F5965} because it's missing its XML file!! (stt exists: False)
Skipping document 165/998 with OID {60862ADD-F2B0-4B4F-AD4C-E54AA294DA3C} because it's missing its XML file!! (stt exists: False)
Skipping document 180/998 with OID {792B5EEA-F297-44F3-BC35-3DC923CFF3B9} because it's missing its XML file!! (stt exists: False)
Skipping document 181/998 with OID {DC6FC4C1-E6F9-4839-A652-6F8DAC2725E2} because it's missing its XML file!! (stt exists: False)
Skipping document 182/998 with OID {9D60F323-F626-4D5C-A9DC-4F542A41F6CC} because it's missing its XML file!! (stt exists: False)
Skipping document 184/998 with OID {A8E6BE30-664C-4242-BE61-2CA3E656E157} because it's missing its XML file!! (stt exists: False)
Skipping document 186/998 with OID {D855C03F-1944-4545-8B38-1669E506D4B9} because it's missing its XML file!! (stt exists: False)
Skipping document 187/998 with OID {ABDE589B-8659-490E-9C55-F0ED6638F58F} because it's missing its XML file!! (stt exists: False)
Skipping document 190/998 with OID {68013C3B-FC3C-4EFD-A6E1-44A3516A364F} because it's missing its XML file!! (stt exists: False)
Skipping document 196/998 with OID {CCCEDA7F-593E-4AF4-8CB1-EC4BDDDFBE30} because it's missing its XML file!! (stt exists: False)
Skipping document 203/998 with OID {48A22D39-5718-4624-B314-2C8FFA545B15} because it's missing its XML file!! (stt exists: False)
Skipping document 204/998 with OID {CF64B2F4-BDF4-472E-9D99-4B63B91CD88B} because it's missing its XML file!! (stt exists: False)
Skipping document 207/998 with OID {99879965-BA42-4297-8389-3D17C2AB8FF8} because it's missing its XML file!! (stt exists: False)
Skipping document 208/998 with OID {DAE39D8C-6CB6-4B29-B1F1-46266A2A7D6A} because it's missing its XML file!! (stt exists: True)
Skipping document 211/998 with OID {F6FD984B-4B29-4FB5-A7E2-9C5A8D52FC79} because it's missing its XML file!! (stt exists: False)
Skipping document 217/998 with OID {2F74D112-75F8-4AFE-824C-2B3753C8ACA2} because it's missing its XML file!! (stt exists: False)
Skipping document 221/998 with OID {197003A7-26C2-4F9D-9DFA-722A09C5D7F8} because it's missing its XML file!! (stt exists: False)
Skipping document 222/998 with OID {36005444-8226-4591-972B-3591E2C8FE08} because it's missing its XML file!! (stt exists: False)
Skipping document 223/998 with OID {AA997715-3A27-459D-BF15-80185B6FE9D4} because it's missing its XML file!! (stt exists: False)
Skipping document 224/998 with OID {EEF407B7-33DD-4248-AD5E-1734CD21017B} because it's missing its XML file!! (stt exists: False)
Skipping document 230/998 with OID {C72CD73A-046E-4D7A-A405-5B79869A69F7} because it's missing its XML file!! (stt exists: False)
Skipping document 233/998 with OID {D409ED18-13B6-4F0F-B8A2-9D4210A19F11} because it's missing its XML file!! (stt exists: False)
Skipping document 244/998 with OID {FABE89D8-65CA-4E83-BB33-B2BB8E7BD212} because it's missing its XML file!! (stt exists: True)
Skipping document 249/998 with OID {9256290E-38D4-4BF5-A7AF-56D939698FBF} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {2DA70FF1-C3AC-4391-8EF2-39D6950EE0FD}. Trying to use the recording date. doc_dict: {'alias': 'petitdej', 'date_str': None, 'stt_filename': '2DA70FF1-C3AC-4391-8EF2-39D6950EE0FD_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{2DA70FF1-C3AC-4391-8EF2-39D6950EE0FD}', 'stripped_OID': '2DA70FF1-C3AC-4391-8EF2-39D6950EE0FD', 'login': '', 'broadcast_episode_title': 'Entretien avec Louis Malle, cin�aste, lors du 40e festival de Cannes', 'sequence': '1', 'broadcast_program_name': 'Petit d�jeuner', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '10.09.2016 16:08:40', 'physical_support_history': "Cote d'origine: 33436.", 'production_type': 'Production propre', 'recording_place': 'Paris (Festival de Cannes)', 'rights_notes': None, 'rights_status': 'Clarifi�', 'series_title': None, 'content_summary': "L'entretien d�bute � 2.14.", 'workflow_status': 'Valid�', 'assembly_status': 'Mont�', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '01:03:37.205', 'work_duration_compl': 'Non', 'participants': [{'name': 'Mastroianni, Marcello', 'function': 'Interview�/e', 'role': 'acteur italien'}, {'name': 'Malle, Louis', 'function': 'Interview�/e', 'role': 'cin�aste fran�ais'}, {'name': 'Ferla, Patrick', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['France'], 'person_descriptors': ['Malle, Louis'], 'thematical_descriptors': ['cin�ma', 'immigration'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi�re'], 'subdomains': ['Interview'], 'recording_dates': ['11/05/1987 - 11/05/1987'], 'first_broadcast_dates': None}
Skipping document 255/998 with OID {BC200374-7E84-44EE-BCC0-46A56CBD0916} because it's missing its XML file!! (stt exists: False)
Skipping document 260/998 with OID {7231E3D9-056F-4703-8180-DCB17BC0DCC9} because it's missing its XML file!! (stt exists: False)
Skipping document 261/998 with OID {2AF0F42B-9634-46ED-A5D1-E3F6C15F0977} because it's missing its XML file!! (stt exists: False)
Skipping document 264/998 with OID {3D89EBCF-32C9-4600-8E7B-B021789DFFE7} because it's missing its XML file!! (stt exists: False)
Skipping document 267/998 with OID {C80D7863-8BFB-4150-A6C0-D7ED712CE7E4} because it's missing its XML file!! (stt exists: False)
Skipping document 274/998 with OID {CD617245-F062-4B72-B261-14D739942EBE} because it's missing its XML file!! (stt exists: False)
Skipping document 280/998 with OID {B59118AF-3C77-43A1-B862-AD38A4FF837A} because it's missing its XML file!! (stt exists: False)
Skipping document 281/998 with OID {5E8FDA68-C2AC-4B43-B56A-198BBFF956BC} because it's missing its XML file!! (stt exists: False)
Skipping document 283/998 with OID {FEA3F9E3-9A98-4747-8D40-60A7F539B630} because it's missing its XML file!! (stt exists: False)
Skipping document 284/998 with OID {1AFB491D-336C-44D1-A559-6B6DD132AA1B} because it's missing its XML file!! (stt exists: False)
Skipping document 286/998 with OID {6BC19D5F-6E18-44CD-9F3E-EF2C3F452E15} because it's missing its XML file!! (stt exists: False)
The date for document with OID {554115CB-3AB4-47FA-AA33-21156015F088} was invalid (__/__/1994) - changed it to 01/01/1994
The date for document with OID {554115CB-3AB4-47FA-AA33-21156015F088} was invalid (__/__/1994) - changed it to 01/01/1994
Skipping document 294/998 with OID {7AB00280-F8B8-4A4A-B884-D0A9D24C254F} because it's missing its XML file!! (stt exists: False)
Skipping document 295/998 with OID {423A50B1-8F8C-4714-B584-7B1B47FE41A8} because it's missing its XML file!! (stt exists: False)
Skipping document 304/998 with OID {415C67FB-6E9C-4DC0-B7E0-7BDFF72E4A73} because it's missing its XML file!! (stt exists: False)
Skipping document 305/998 with OID {86BC8232-C0E3-4200-8104-F2B8186713E8} because it's missing its XML file!! (stt exists: False)
Skipping document 306/998 with OID {08EA029F-C4F7-41EE-9675-83432A48CD7F} because it's missing its XML file!! (stt exists: False)
Skipping document 309/998 with OID {C01273A7-42A0-45DB-9AF3-8B6A3E1FD3FD} because it's missing its XML file!! (stt exists: False)
Skipping document 310/998 with OID {AB87713D-9794-4B8D-AC63-8D420B97FD57} because it's missing its XML file!! (stt exists: False)
Skipping document 312/998 with OID {11CB0143-1BED-439B-AD88-395438A9B4F4} because it's missing its XML file!! (stt exists: False)
Skipping document 316/998 with OID {245CC857-42B1-49CA-A735-D3E7415A4783} because it's missing its XML file!! (stt exists: False)
Skipping document 321/998 with OID {A1B2B66D-9F7D-4994-9AD8-CE1F544632B6} because it's missing its XML file!! (stt exists: False)
Skipping document 329/998 with OID {21BEE902-C708-47F6-AEFC-B4817DFC4C4F} because it's missing its XML file!! (stt exists: False)
Skipping document 331/998 with OID {DB689841-34E6-48A7-ADBB-CD45D6F4FDC5} because it's missing its XML file!! (stt exists: False)
Skipping document 335/998 with OID {4288C6A7-A2E6-4468-A8FC-F4693B69304E} because it's missing its XML file!! (stt exists: False)
Skipping document 336/998 with OID {979D1FD0-824E-4550-AA48-AAC9ECDCC66A} because it's missing its XML file!! (stt exists: False)
Skipping document 339/998 with OID {27C09DC0-E39A-43B4-AD4F-04687A5D852A} because it's missing its XML file!! (stt exists: False)
Skipping document 343/998 with OID {7D36C435-A0F1-421D-B8CF-ABCF1FB5E444} because it's missing its XML file!! (stt exists: False)
Skipping document 345/998 with OID {E07525DC-9159-4D40-8895-B11AF2B704EC} because it's missing its XML file!! (stt exists: False)
Skipping document 356/998 with OID {CA529B52-8746-44F8-98EB-15E2066DDBAC} because it's missing its XML file!! (stt exists: False)
Skipping document 362/998 with OID {88615686-74A9-4BB6-A397-898EAC2FBEAC} because it's missing its XML file!! (stt exists: False)
Skipping document 364/998 with OID {9F90B340-2525-47FE-B8DC-3ADDCAB8CC3C} because it's missing its XML file!! (stt exists: False)
Skipping document 365/998 with OID {859C24E9-B148-477A-8054-FF88A9860E97} because it's missing its XML file!! (stt exists: False)
Skipping document 369/998 with OID {20CC7440-898F-4829-B3FC-9C496469CB24} because it's missing its XML file!! (stt exists: False)
Skipping document 374/998 with OID {18CD0422-5EAC-40F0-9FD6-E9DAA81BCE62} because it's missing its XML file!! (stt exists: False)
Skipping document 383/998 with OID {A547BCA9-C675-47F1-BCF2-868A26B1E221} because it's missing its XML file!! (stt exists: False)
Skipping document 393/998 with OID {9508FF44-C56A-4066-B333-3FB5BE5A4178} because it's missing its XML file!! (stt exists: False)
Skipping document 394/998 with OID {5042F4CD-A131-49A4-A5A6-85C80D5D073D} because it's missing its XML file!! (stt exists: False)
Skipping document 401/998 with OID {7B4AA885-833C-4FB7-97FA-CB0B2D7AAEB0} because it's missing its XML file!! (stt exists: False)
Skipping document 402/998 with OID {C62BF518-29ED-42FA-92DF-A6CFEC83F07A} because it's missing its XML file!! (stt exists: False)
Skipping document 405/998 with OID {D5FACEFB-35E1-4E1E-A882-B04ADCD41E1D} because it's missing its XML file!! (stt exists: False)
Skipping document 407/998 with OID {8EA2EF20-E474-4013-A61B-A5AB0207ADCC} because it's missing its XML file!! (stt exists: False)
Skipping document 409/998 with OID {C5520363-B7AF-4A83-90F7-A78F9CC3856B} because it's missing its XML file!! (stt exists: False)
Skipping document 411/998 with OID {6CA61ABD-4762-491D-8A75-BA8BD6E4DD9E} because it's missing its XML file!! (stt exists: False)
Skipping document 412/998 with OID {5CF7A0DF-C5D6-4BDE-8C88-33824A64E77D} because it's missing its XML file!! (stt exists: False)
Skipping document 417/998 with OID {7313C532-B08F-4656-9EB2-9FE85498B289} because it's missing its XML file!! (stt exists: False)
Skipping document 423/998 with OID {51C8C200-52B1-4BD1-8876-B7325723FBAF} because it's missing its XML file!! (stt exists: False)
Skipping document 425/998 with OID {54C7AB7E-7B8F-4FE2-A4FB-3ADB2F58CA76} because it's missing its XML file!! (stt exists: False)
Skipping document 432/998 with OID {7EFCDBF5-2971-44A7-81F7-3014EBF974B0} because it's missing its XML file!! (stt exists: False)
Skipping document 438/998 with OID {5920F87A-E06D-49E8-AFAA-10A6F3279030} because it's missing its XML file!! (stt exists: False)
Skipping document 449/998 with OID {DFDEE8DF-72EF-4D2D-A45B-033468FBE01A} because it's missing its XML file!! (stt exists: False)
Skipping document 450/998 with OID {70A956F5-62E8-45E3-A081-580A4C3A9BCF} because it's missing its XML file!! (stt exists: False)
Skipping document 454/998 with OID {9ACC6293-6DA2-4D5A-B0C1-7D27D80698F9} because it's missing its XML file!! (stt exists: False)
Skipping document 460/998 with OID {5F264AF8-0D40-491B-B4A7-CADD458AA972} because it's missing its XML file!! (stt exists: False)
Skipping document 462/998 with OID {3C87E532-A49A-40D5-AA33-752FE29B8E92} because it's missing its XML file!! (stt exists: False)
Skipping document 466/998 with OID {0D38FCE2-4979-48D9-A277-2A31BC1E3F47} because it's missing its XML file!! (stt exists: False)
Skipping document 468/998 with OID {5E10925D-5AE8-4004-A1F9-E4E29A625824} because it's missing its XML file!! (stt exists: False)
Skipping document 469/998 with OID {C8518ADA-EDBC-4EA8-9CD0-AA760281CB4D} because it's missing its XML file!! (stt exists: False)
Skipping document 470/998 with OID {6C63E77D-D63C-4542-93A9-ECBFFBF13EDE} because it's missing its XML file!! (stt exists: False)
Skipping document 472/998 with OID {4F78040C-7D1A-433B-A707-B40379919A7B} because it's missing its XML file!! (stt exists: False)
Skipping document 474/998 with OID {2E078D56-BF8E-4404-9CAA-0C4F6191354A} because it's missing its XML file!! (stt exists: False)
Skipping document 477/998 with OID {422635A2-A6E1-4C35-BAB2-0F93B3AD8CF6} because it's missing its XML file!! (stt exists: False)
Skipping document 478/998 with OID {5F117168-24E4-4602-AA3E-625BA22EF3F8} because it's missing its XML file!! (stt exists: False)
Skipping document 480/998 with OID {D7B891FD-26B6-4DDA-8E78-E7DA1F69724E} because it's missing its XML file!! (stt exists: True)
Skipping document 485/998 with OID {B72DE490-174A-40E7-81B7-5825AE8BAB0E} because it's missing its XML file!! (stt exists: False)
Skipping document 487/998 with OID {CC938F88-F580-4451-9DDE-2CB0793C19AF} because it's missing its XML file!! (stt exists: False)
Skipping document 488/998 with OID {3BB2F500-DD63-4CCE-AD72-303BF1E9928C} because it's missing its XML file!! (stt exists: False)
Skipping document 493/998 with OID {E74B739C-8D8A-48ED-843E-C0F3C2D1543D} because it's missing its XML file!! (stt exists: False)
Skipping document 497/998 with OID {023026A8-DB3E-4A73-AFB9-833F4C4B9CD0} because it's missing its XML file!! (stt exists: False)
Skipping document 499/998 with OID {53C73813-313E-4DE0-9B87-FC41264BC953} because it's missing its XML file!! (stt exists: False)
Skipping document 502/998 with OID {2436DCFE-14C7-4526-A197-3954252E975E} because it's missing its XML file!! (stt exists: True)
Skipping document 504/998 with OID {0CC76958-905F-49D6-B5CC-AE2BA6D59D09} because it's missing its XML file!! (stt exists: False)
Skipping document 509/998 with OID {F2C26127-3BB2-48E2-A376-E91334FF0FC8} because it's missing its XML file!! (stt exists: False)
Skipping document 512/998 with OID {AF29F74B-AA8A-448A-AE06-218966B42C50} because it's missing its XML file!! (stt exists: False)
Skipping document 514/998 with OID {79EF762E-425A-474F-90AD-454C20B4C4A6} because it's missing its XML file!! (stt exists: False)
Skipping document 515/998 with OID {6A27D732-7033-4D8F-8B8E-B39B9E14D063} because it's missing its XML file!! (stt exists: False)
Skipping document 517/998 with OID {7AA4DEAC-A26F-4CAF-8F67-AE8D7E9208D5} because it's missing its XML file!! (stt exists: False)
Skipping document 521/998 with OID {680D145D-2826-4CF8-B91A-963800EE5B2C} because it's missing its XML file!! (stt exists: False)
Skipping document 529/998 with OID {DBCB8C4E-129A-4012-8744-436F0BBAC560} because it's missing its XML file!! (stt exists: False)
Skipping document 534/998 with OID {D5B100AA-66FE-48D5-A617-6CCBD4EF7238} because it's missing its XML file!! (stt exists: True)
Skipping document 535/998 with OID {CECEEBA1-32F9-4731-B227-C8830E676858} because it's missing its XML file!! (stt exists: False)
Skipping document 541/998 with OID {C3196AAA-1917-40D7-87C2-91DF225F9C3F} because it's missing its XML file!! (stt exists: False)
Skipping document 542/998 with OID {862A25D4-C9F3-45FE-9E39-4F6F66BAB5C1} because it's missing its XML file!! (stt exists: False)
Skipping document 544/998 with OID {F61BBB6F-1963-49B4-83B2-276FDCCDCA1F} because it's missing its XML file!! (stt exists: False)
Skipping document 546/998 with OID {159A5E36-80E6-4DE8-ACC1-E6A473FA3CBB} because it's missing its XML file!! (stt exists: False)

Skipping document 920/998 with OID {67E54516-4A76-4D63-A82E-6097091B83CA} because it's missing its XML file!! (stt exists: True)
Skipping document 921/998 with OID {128652B4-C8E4-4BA7-B467-34884469F21C} because it's missing its XML file!! (stt exists: False)
Skipping document 924/998 with OID {D0AAB032-2D4A-418B-BCF9-9CCBEB781224} because it's missing its XML file!! (stt exists: False)
Skipping document 927/998 with OID {86A3E4F8-CFCF-4FD4-9BE7-DD0C338C43CC} because it's missing its XML file!! (stt exists: False)
Skipping document 929/998 with OID {4E3F9693-FFB2-409D-9030-555ECA491197} because it's missing its XML file!! (stt exists: False)
Skipping document 937/998 with OID {D1A20EB6-1385-4C44-AAAB-321A95760146} because it's missing its XML file!! (stt exists: False)
Skipping document 939/998 with OID {2CE2A843-351F-41BC-AD6F-76284C617CA4} because it's missing its XML file!! (stt exists: False)
Skipping document 941/998 with OID {DDCE9E7B-1CAD-4B34-9062-ADB4BE76FD60} because it's missing its XML file!! (stt exists: False)
Skipping document 942/998 with OID {8FB8B2A7-5B7B-4500-B221-4FFCBFF207A1} because it's missing its XML file!! (stt exists: False)
Skipping document 946/998 with OID {A7DA8AC8-B69B-49CC-9B31-71BB9B5940B0} because it's missing its XML file!! (stt exists: False)
Skipping document 947/998 with OID {51DCC06F-935B-40DA-8DF7-AAEA9DBD96CD} because it's missing its XML file!! (stt exists: False)
Skipping document 952/998 with OID {31C51BC8-16F5-41B5-AA71-B9DA96E840D1} because it's missing its XML file!! (stt exists: False)
Skipping document 953/998 with OID {2F23F42E-BD95-411D-B9FA-5F6CC0BD59C2} because it's missing its XML file!! (stt exists: False)
Skipping document 962/998 with OID {B56CF3D6-E2DD-4F51-9955-88EA89116CFD} because it's missing its XML file!! (stt exists: False)
Skipping document 964/998 with OID {A8479F8F-8534-4B09-B16E-FA93F4D007D0} because it's missing its XML file!! (stt exists: False)
Skipping document 971/998 with OID {E823F2AD-6727-48DF-BCB4-650D62D55B38} because it's missing its XML file!! (stt exists: False)
Skipping document 979/998 with OID {1AF894D1-7B91-430E-A29D-E5A2D972DF02} because it's missing its XML file!! (stt exists: False)
Skipping document 984/998 with OID {73400DEB-6E3C-41AF-AA6E-932130EF76BC} because it's missing its XML file!! (stt exists: False)
Skipping document 988/998 with OID {EACEC117-D313-48F9-B1E5-E3BA086850BF} because it's missing its XML file!! (stt exists: False)
Skipping document 991/998 with OID {14AA8B14-A08A-4D4C-947A-7CA27A7B6CD3} because it's missing its XML file!! (stt exists: False)
Skipping document 992/998 with OID {48635E99-BCC7-42F8-889E-8B7C50F89E32} because it's missing its XML file!! (stt exists: False)
Skipping document 998/998 with OID {4073A5CA-96AC-44AF-9CF2-CD918E7A0DB5} because it's missing its XML file!! (stt exists: False)
petitdej - returning 744 documents, 254 were skipped due to missing necessary info.

Starting extracting 999 documents for program petitdej
Skipping document 3/999 with OID {9D6C0CC8-1C48-423D-A9BD-281A7CF8F89F} because it's missing its XML file!! (stt exists: False)
Skipping document 4/999 with OID {715B8190-8BD3-4BD1-920E-F69624F6AE6F} because it's missing its XML file!! (stt exists: False)
Skipping document 7/999 with OID {95876439-5D30-4925-B538-53A8E3721109} because it's missing its XML file!! (stt exists: False)
Skipping document 8/999 with OID {D13CAD42-6CE6-4999-B209-749798BAD2D8} because it's missing its XML file!! (stt exists: False)
Skipping document 12/999 with OID {6ADA611F-B5C0-4DB5-A742-B4878F5E08CC} because it's missing its XML file!! (stt exists: False)
Skipping document 13/999 with OID {1F24563F-5A48-4EE0-8733-33E9995FBBAA} because it's missing its XML file!! (stt exists: False)
Skipping document 14/999 with OID {02FF47B0-B756-4CD1-A753-DF32B11145DF} because it's missing its XML file!! (stt exists: False)
Skipping document 15/999 with OID {C656457D-8D8A-406A-BCEE-7278093772FE} because it's missing its XML file!! (stt exists: False)
Skipping document 17/999 with OID {033E77A3-F582-44F1-B7F0-7209BC0748B3} because it's missing its XML file!! (stt exists: False)
Skipping document 19/999 with OID {4E01013B-232B-4321-928A-705ECCBAE072} because it's missing its XML file!! (stt exists: False)
Skipping document 23/999 with OID {353F7AAC-1610-4B0F-9148-28138B311E8B} because it's missing its XML file!! (stt exists: False)
Skipping document 24/999 with OID {BEC11D51-6CF5-43B0-8C30-57931A8EC288} because it's missing its XML file!! (stt exists: False)
Skipping document 27/999 with OID {37D2BF43-3A8D-4B25-BD08-90C78F762FFA} because it's missing its XML file!! (stt exists: False)
Skipping document 28/999 with OID {6362D283-CBF7-4848-A079-8405D5655007} because it's missing its XML file!! (stt exists: False)
Skipping document 29/999 with OID {20B44F27-A925-4523-98E8-8DF697B7BA83} because it's missing its XML file!! (stt exists: False)
Skipping document 30/999 with OID {2BB55531-148B-4817-B49B-65BB53F5AE72} because it's missing its XML file!! (stt exists: False)
Skipping document 31/999 with OID {3D0DE68A-393E-41E3-8208-69583C44A555} because it's missing its XML file!! (stt exists: False)
Skipping document 32/999 with OID {E3DF6813-8046-4454-A5CE-F661784C1620} because it's missing its XML file!! (stt exists: False)
Skipping document 33/999 with OID {268180A2-570D-4F56-ACA5-09EE330BFEB8} because it's missing its XML file!! (stt exists: False)
Skipping document 35/999 with OID {242C17D2-CD6A-4620-B151-A38D79F7D026} because it's missing its XML file!! (stt exists: False)
Skipping document 36/999 with OID {E212D130-93F1-4C1C-A63C-31327DFD64FE} because it's missing its XML file!! (stt exists: False)
Skipping document 38/999 with OID {E45D8786-3BA2-4182-B750-F7CBE2B3A460} because it's missing its XML file!! (stt exists: False)
Skipping document 40/999 with OID {6A678799-F6E5-4DB1-8573-D9E5EE491C1B} because it's missing its XML file!! (stt exists: False)
Skipping document 46/999 with OID {AE58DBE6-B422-427E-8F7C-DEF8BC309ED1} because it's missing its XML file!! (stt exists: False)
Skipping document 51/999 with OID {ACB2A71F-A3DC-4608-B772-E74DB415D30B} because it's missing its XML file!! (stt exists: False)
Skipping document 54/999 with OID {EED948B3-1EEC-48D5-AE54-0AA54A7A64C4} because it's missing its XML file!! (stt exists: False)
Skipping document 58/999 with OID {863E11A1-BAA6-4429-8803-B5A51B379303} because it's missing its XML file!! (stt exists: False)
Skipping document 67/999 with OID {89D47264-0E6F-4B0F-A987-305612D93768} because it's missing its XML file!! (stt exists: False)
Skipping document 72/999 with OID {61E52CF8-019B-4029-8A11-73BC1C3CA3AA} because it's missing its XML file!! (stt exists: False)
Skipping document 76/999 with OID {F053F62E-C02C-4E8A-81EF-37265C77F026} because it's missing its XML file!! (stt exists: False)
The date for document with OID {23ABAC0F-5502-43DC-A034-7E06FFB3D52F} was invalid (__/01/1987) - changed it to 01/01/1987
Did not find any date for doc with OID {1369D33C-33EB-4A08-867E-2DB21D5A730B}. Trying to use the recording date. doc_dict: {'alias': 'petitdej', 'date_str': None, 'stt_filename': '1369D33C-33EB-4A08-867E-2DB21D5A730B_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{1369D33C-33EB-4A08-867E-2DB21D5A730B}', 'stripped_OID': '1369D33C-33EB-4A08-867E-2DB21D5A730B', 'login': '', 'broadcast_episode_title': 'Entretien avec Alain Tanner, cin�aste suisse : En marge de la sortie de son dernier film "Fourbi"', 'sequence': '2', 'broadcast_program_name': 'Petit d�jeuner', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'BBR (NumA)', 'modified_on': '05.09.2016 14:52:12', 'physical_support_history': "Cote d'origine : A 13877 ST\nResp. RSR : BBR\nLot : Caisse 1546", 'production_type': 'Production propre', 'recording_place': 'Gen�ve', 'rights_notes': None, 'rights_status': None, 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid�', 'assembly_status': None, 'live': 'Non live', 'modulation_type': 'St�r�o', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Tanner, Alain', 'function': 'Interview�/e', 'role': 'cin�aste suisse'}, {'name': 'Ferla, Patrick', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}], 'geographical_descriptors': None, 'person_descriptors': ['Tanner, Alain'], 'thematical_descriptors': ['cin�ma', 'oeuvre cin�matographique'], 'rights_usage_possibilities': None, 'radio_channels': ['La Premi�re'], 'subdomains': ['Interview'], 'recording_dates': ['14/02/1996 - 14/02/1996'], 'first_broadcast_dates': None}
Skipping document 91/999 with OID {9CECBC87-0618-4C1B-9B3E-4899D500A1AE} because it's missing its XML file!! (stt exists: False)
Skipping document 100/999 with OID {7116CE1A-EBDD-440A-A7A6-C683CAE3D239} because it's missing its XML file!! (stt exists: False)
Skipping document 104/999 with OID {BF2936CB-EA90-4B6F-8EB8-983DABA9BBB7} because it's missing its XML file!! (stt exists: False)
Skipping document 105/999 with OID {1D304E78-8AAA-4590-923D-74F238C33625} because it's missing its XML file!! (stt exists: False)
Skipping document 106/999 with OID {90005FC8-7AF9-47D9-8E52-52F49B34C3DA} because it's missing its XML file!! (stt exists: True)
Skipping document 107/999 with OID {A1E10082-12B0-4DBA-967A-4D17A59A3B4C} because it's missing its XML file!! (stt exists: False)
Skipping document 122/999 with OID {4B278290-5400-4E63-AE1B-160F24A21F48} because it's missing its XML file!! (stt exists: False)
Skipping document 128/999 with OID {C3E1914E-EDAF-4F4D-87D7-A83520DFE284} because it's missing its XML file!! (stt exists: False)
Skipping document 143/999 with OID {8358C7CE-6F2F-47C8-9DE5-ABE0701B9236} because it's missing its XML file!! (stt exists: False)
Skipping document 144/999 with OID {1B249458-8ED7-481C-B667-6B01CBECCC89} because it's missing its XML file!! (stt exists: False)
Skipping document 158/999 with OID {23AA02FD-A915-4040-A5CE-AAA0E75EBE20} because it's missing its XML file!! (stt exists: False)
Skipping document 172/999 with OID {0D6366DD-742E-47F6-81B8-B013E2E98846} because it's missing its XML file!! (stt exists: False)
Skipping document 174/999 with OID {542553D7-70D6-4739-AD97-860A8758E847} because it's missing its XML file!! (stt exists: False)
Skipping document 182/999 with OID {9CA820AB-D254-4654-8360-BA5E66C66F14} because it's missing its XML file!! (stt exists: False)
Skipping document 189/999 with OID {E5536280-F68E-4691-A7C2-D9981FF5C7F0} because it's missing its XML file!! (stt exists: False)
Skipping document 191/999 with OID {80E8DE3F-3CDD-42FA-9246-82A119903A37} because it's missing its XML file!! (stt exists: False)
Skipping document 196/999 with OID {B5DE676E-2F34-4230-8A42-7A538F8A6189} because it's missing its XML file!! (stt exists: False)
Skipping document 200/999 with OID {2A7D4642-E8CC-4BFC-98E1-657F36F111A1} because it's missing its XML file!! (stt exists: False)
Skipping document 201/999 with OID {5C1AAF6D-1ADA-417E-B70B-178B7B18E5A2} because it's missing its XML file!! (stt exists: False)
Skipping document 203/999 with OID {7F47BA5E-32B5-43DE-8F8F-1941A917AC4A} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {7F3DCD2E-2BA2-4759-B16E-396EACE686CC}. Trying to use the recording date. doc_dict: {'alias': 'petitdej', 'date_str': None, 'stt_filename': '7F3DCD2E-2BA2-4759-B16E-396EACE686CC_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{7F3DCD2E-2BA2-4759-B16E-396EACE686CC}', 'stripped_OID': '7F3DCD2E-2BA2-4759-B16E-396EACE686CC', 'login': '', 'broadcast_episode_title': 'Entretien avec Barbara Hendricks, cantatrice et Johnny Hallyday, chanteur', 'sequence': '1', 'broadcast_program_name': 'Petit d�jeuner', 'document_type': 'Parl�', 'hierarchy_level': 'Sujet', 'modified_by': 'comtesi', 'modified_on': '04.09.2016 10:37:19', 'physical_support_history': "Cote d'origine: 33377", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'RSR', 'rights_status': 'Clarifi�', 'series_title': "Sauvegarde d'archives. Petit d�jeuner imaginaire", 'content_summary': None, 'workflow_status': 'Valid�', 'assembly_status': 'Pr�t', 'live': 'Non live', 'modulation_type': 'St�r�o', 'work_duration': '00:57:03.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Hendricks, Barbara', 'function': 'Interview�/e', 'role': 'cantatrice'}, {'name': 'Hallyday, Johnny', 'function': 'Interview�/e', 'role': 'chanteur'}, {'name': 'Ferla, Patrick', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}], 'geographical_descriptors': None, 'person_descriptors': ['Hendricks, Barbara', 'Hallyday, Johnny'], 'thematical_descriptors': ['chanteur', 'cantatrice', 'chanson de vari�t�s'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi�re'], 'subdomains': ['Interview'], 'recording_dates': ['29/12/1987 - 29/12/1987'], 'first_broadcast_dates': None}
Skipping document 210/999 with OID {9F74B44D-C6B2-4F5B-BCF3-69732678CF81} because it's missing its XML file!! (stt exists: False)
Skipping document 211/999 with OID {6809B2BD-C661-4EF7-A408-D5013C72BCF1} because it's missing its XML file!! (stt exists: False)
Skipping document 212/999 with OID {2E25F4C5-572F-4C06-848F-81273DD0C962} because it's missing its XML file!! (stt exists: False)
Skipping document 220/999 with OID {236C8D13-FCD2-4A32-8AC3-FC63B3DD4598} because it's missing its XML file!! (stt exists: False)
Skipping document 223/999 with OID {F49138DE-7391-49DA-852A-378885F81AB4} because it's missing its XML file!! (stt exists: False)
Skipping document 224/999 with OID {A1BBA8CF-A692-45E1-9487-3D563A183EBB} because it's missing its XML file!! (stt exists: False)
Skipping document 225/999 with OID {CB0239B5-20C9-4C81-AE68-78698CF368CB} because it's missing its XML file!! (stt exists: False)
Skipping document 230/999 with OID {1B365FCD-3281-4E28-8870-7B5705514C8E} because it's missing its XML file!! (stt exists: False)
Skipping document 233/999 with OID {3C298D65-9FC1-4C06-827A-DED0597D6355} because it's missing its XML file!! (stt exists: False)
Skipping document 240/999 with OID {C17F62E0-4CEA-4A82-86BA-285DC148547E} because it's missing its XML file!! (stt exists: False)
Skipping document 245/999 with OID {C7D30B21-76EC-4B72-BF1F-1F6BFC02037B} because it's missing its XML file!! (stt exists: False)
Skipping document 252/999 with OID {478E16E1-F249-4C62-96FA-8822A724A11A} because it's missing its XML file!! (stt exists: False)
Skipping document 254/999 with OID {C993B2F1-7763-401B-8153-49211FD4143C} because it's missing its XML file!! (stt exists: False)
Skipping document 262/999 with OID {842514C1-28D9-4F7A-9E6B-80D6E223F2CB} because it's missing its XML file!! (stt exists: False)
Skipping document 263/999 with OID {6A403BD0-3EE0-427C-9BE9-0B38E37CCB90} because it's missing its XML file!! (stt exists: False)
Skipping document 264/999 with OID {42A6141F-003A-4A59-A4AB-8F4C93F65CA4} because it's missing its XML file!! (stt exists: False)
Skipping document 266/999 with OID {EB8140DA-1366-4EA3-BB36-A1885121823F} because it's missing its XML file!! (stt exists: False)
Skipping document 273/999 with OID {C8423CA6-FB06-47A3-B55F-D3BB43340A27} because it's missing its XML file!! (stt exists: False)
Skipping document 281/999 with OID {9E92ACB0-17CD-4DC1-8B7C-0D7DED54C083} because it's missing its XML file!! (stt exists: False)
Skipping document 282/999 with OID {5874A313-1009-4C09-A572-5852A2015730} because it's missing its XML file!! (stt exists: False)
Skipping document 283/999 with OID {D7AD2512-3F53-4D46-97A7-B6344DB1BDFF} because it's missing its XML file!! (stt exists: False)
Skipping document 286/999 with OID {34162527-4039-4052-9226-8B122F302253} because it's missing its XML file!! (stt exists: False)
Skipping document 290/999 with OID {DE055892-0CB2-4B2B-97E8-7E055BF7092C} because it's missing its XML file!! (stt exists: False)
Skipping document 291/999 with OID {03B43ED7-99F5-4AD2-8C69-C732410B1582} because it's missing its XML file!! (stt exists: False)
Skipping document 295/999 with OID {DBAF6234-9E79-4DA9-B04D-24E558FEBC24} because it's missing its XML file!! (stt exists: False)
Skipping document 300/999 with OID {0B5E0CAC-14E5-444D-80FB-0CA25FC835DD} because it's missing its XML file!! (stt exists: False)
Skipping document 303/999 with OID {6FFF95F6-CC3C-4B3C-AFF5-60C3287BF2E3} because it's missing its XML file!! (stt exists: True)
Skipping document 304/999 with OID {E3AFB089-9077-49B0-9F8B-5EE245259864} because it's missing its XML file!! (stt exists: False)
Skipping document 305/999 with OID {3FACDCC7-BDDD-46D5-A19B-C87FBE5F0ACC} because it's missing its XML file!! (stt exists: False)
Skipping document 310/999 with OID {15153A7B-9C1B-47BA-A8E7-B9D4842B608E} because it's missing its XML file!! (stt exists: False)
Skipping document 311/999 with OID {344C41BB-1BC2-4890-9128-FB22F8A2E0AD} because it's missing its XML file!! (stt exists: False)
Skipping document 315/999 with OID {116D29A7-04A2-4AB3-9512-8C29F6C3A37D} because it's missing its XML file!! (stt exists: False)
Skipping document 324/999 with OID {3473E98A-5134-4E21-BA60-C00F50925C12} because it's missing its XML file!! (stt exists: False)
Skipping document 332/999 with OID {5E65407A-2B00-4AF5-9E09-601B64512344} because it's missing its XML file!! (stt exists: False)
Skipping document 333/999 with OID {98C59223-77F0-428C-93CD-1A1B887A409B} because it's missing its XML file!! (stt exists: False)
Skipping document 335/999 with OID {593B3F6D-AA6A-4861-815F-05E858C34ED4} because it's missing its XML file!! (stt exists: False)
Skipping document 337/999 with OID {F920A4A7-7EA3-4BA2-BCFB-60597232582A} because it's missing its XML file!! (stt exists: False)
Skipping document 338/999 with OID {AF73BABC-2E03-4BF0-ACFC-D902B133A51E} because it's missing its XML file!! (stt exists: False)
Skipping document 340/999 with OID {796B5D1C-8806-4B56-8659-BF962E8A82A3} because it's missing its XML file!! (stt exists: False)
Skipping document 341/999 with OID {1466A918-B238-4388-8655-DD1C76E3099F} because it's missing its XML file!! (stt exists: False)
Skipping document 342/999 with OID {3C0ACA2C-828E-4980-B8C1-FE8FD6EFD6C5} because it's missing its XML file!! (stt exists: False)
Skipping document 344/999 with OID {C821D391-8123-4070-BE32-A94C78F50705} because it's missing its XML file!! (stt exists: False)
Skipping document 347/999 with OID {AF08CD00-F47F-44CF-BEDE-9D1E6C051566} because it's missing its XML file!! (stt exists: False)
The date for document with OID {C3BAC014-AFBD-4E30-9315-BAD4B8C0A673} was invalid (__/12/1986) - changed it to 01/12/1986
Skipping document 361/999 with OID {26CB0990-9FC2-45F6-8160-BB856767BCB6} because it's missing its XML file!! (stt exists: False)
Skipping document 373/999 with OID {85FD7A70-E38A-4E57-ACC0-7E50E68241D9} because it's missing its XML file!! (stt exists: False)
Skipping document 385/999 with OID {033C6D9E-DA0E-4558-AFB9-7E655410ED20} because it's missing its XML file!! (stt exists: False)
Skipping document 393/999 with OID {DE1C230E-2124-45B1-9784-946DE48E652C} because it's missing its XML file!! (stt exists: False)
Skipping document 413/999 with OID {08E5FE59-B356-4C32-BAC1-92A012A5A08F} because it's missing its XML file!! (stt exists: False)
Skipping document 419/999 with OID {517D5DC0-6235-4E8F-9852-0FBA3AFED6E0} because it's missing its XML file!! (stt exists: False)
Skipping document 420/999 with OID {06C57552-65D0-4D4B-B82C-97C188F18442} because it's missing its XML file!! (stt exists: False)
Skipping document 423/999 with OID {A9BAACE1-6DB7-4AA8-B60F-A755B4F34300} because it's missing its XML file!! (stt exists: False)
Skipping document 429/999 with OID {5C9DF743-0CA2-4511-90C5-AFB78679AC63} because it's missing its XML file!! (stt exists: False)

Skipping document 968/999 with OID {3C1D05D6-714F-4AE8-9D2D-93D5F65B33E5} because it's missing its XML file!! (stt exists: False)
Skipping document 975/999 with OID {2CCB0D99-3EBE-46C5-A736-0499C4858814} because it's missing its XML file!! (stt exists: False)
Skipping document 981/999 with OID {F1F10018-93D7-487F-9244-02AD1CC7B370} because it's missing its XML file!! (stt exists: False)
Skipping document 986/999 with OID {59776249-3365-4BF6-B715-F48590B70426} because it's missing its XML file!! (stt exists: False)
Skipping document 998/999 with OID {1B769CCC-E4BA-4CD3-B5F3-430A256028D7} because it's missing its XML file!! (stt exists: False)
petitdej - returning 775 documents, 224 were skipped due to missing necessary info.

Starting extracting 128 documents for program petitdej
Skipping document 2/128 with OID {31BA7D70-6F88-4725-B07F-DB09D9DDF286} because it's missing its XML file!! (stt exists: False)
Skipping document 7/128 with OID {F645E9F8-ACCC-42B6-B8CA-C7647898F233} because it's missing its XML file!! (stt exists: False)
Skipping document 11/128 with OID {3C28B6DA-88C9-43A9-914E-6967DCD7E55C} because it's missing its XML file!! (stt exists: False)
Skipping document 19/128 with OID {13BD3B74-4DDE-4D5B-B859-87AB6CDFD0CB} because it's missing its XML file!! (stt exists: False)
Skipping document 21/128 with OID {53981F51-8CDE-4600-B4C8-090056E83469} because it's missing its XML file!! (stt exists: False)
Skipping document 22/128 with OID {8EF672F6-2CDC-4411-8B8C-925E6A643A7B} because it's missing its XML file!! (stt exists: False)
Skipping document 24/128 with OID {62956764-5987-4465-AA11-75079AEE9BF5} because it's missing its XML file!! (stt exists: False)
Skipping document 26/128 with OID {17C16F45-D9B7-4E9F-BEF4-38D69F9A908D} because it's missing its XML file!! (stt exists: False)
Skipping document 28/128 with OID {D2406EAD-E7A8-4217-B34E-E0BEFF87290F} because it's missing its XML file!! (stt exists: False)
Skipping document 30/128 with OID {3DC6D041-C38E-4749-A902-A3EE0BBE15AE} because it's missing its XML file!! (stt exists: False)
Skipping document 31/128 with OID {E3EB404D-69F3-49F7-82FD-6F75BBC1D71F} because it's missing its XML file!! (stt exists: False)
Skipping document 32/128 with OID {4C00739C-691D-468A-B20F-7728C931374D} because it's missing its XML file!! (stt exists: False)
Skipping document 33/128 with OID {2669351A-2289-4F32-9EA8-6AFBAA20C054} because it's missing its XML file!! (stt exists: False)
Skipping document 34/128 with OID {021DEA45-31F0-45D3-B3AB-B082947D00B6} because it's missing its XML file!! (stt exists: False)
Skipping document 37/128 with OID {44EE5C9D-420E-4A9E-A566-F4412FF93E08} because it's missing its XML file!! (stt exists: False)
Skipping document 38/128 with OID {B8177E35-C845-4696-A553-79F52CD3EF3D} because it's missing its XML file!! (stt exists: False)
Skipping document 41/128 with OID {8D3ECD0F-9CB6-4E69-9B22-9BFEF8F65878} because it's missing its XML file!! (stt exists: False)
Skipping document 42/128 with OID {D76E52C5-18D0-4FCF-BCD3-456A1B4D9E37} because it's missing its XML file!! (stt exists: False)
The date for document with OID {0CC1CC1C-1929-4BB9-B7D7-07CCD1886866} was invalid (__/07/1996) - changed it to 01/07/1996
The date for document with OID {0CC1CC1C-1929-4BB9-B7D7-07CCD1886866} was invalid (__/07/1996) - changed it to 01/07/1996
Skipping document 44/128 with OID {EB9E71B5-3640-469D-B474-30CCCA66EC1F} because it's missing its XML file!! (stt exists: False)
Skipping document 46/128 with OID {B22A44DE-061E-4A10-9B57-3B5AA8BD3448} because it's missing its XML file!! (stt exists: False)
Skipping document 47/128 with OID {290EC92A-D8A5-46A0-A870-66833BDE84E1} because it's missing its XML file!! (stt exists: False)
Skipping document 49/128 with OID {0C304D8A-9837-4714-B51F-B38603245758} because it's missing its XML file!! (stt exists: False)
Skipping document 52/128 with OID {B53F1D8D-39EA-4218-9E1D-CD34961B80C0} because it's missing its XML file!! (stt exists: False)
Skipping document 53/128 with OID {B4D9E410-F670-4135-A3C2-CC317D087D48} because it's missing its XML file!! (stt exists: False)
Skipping document 54/128 with OID {BE5CDB6D-CB5C-4F31-A691-EAE5830A6DD0} because it's missing its XML file!! (stt exists: False)
Skipping document 59/128 with OID {AC8704CF-2202-4DF2-A111-6EF34E18F1F8} because it's missing its XML file!! (stt exists: False)
Skipping document 62/128 with OID {FAC98BCE-00C1-4D73-9384-BD46B5668239} because it's missing its XML file!! (stt exists: False)
Skipping document 67/128 with OID {FBDC5BA4-4E20-4C87-ADBF-329F2B05FAA3} because it's missing its XML file!! (stt exists: False)
Skipping document 68/128 with OID {4CAE73D9-EED4-45B7-822E-AA3EDD912DF6} because it's missing its XML file!! (stt exists: False)
Skipping document 71/128 with OID {14485189-DD5E-4DEB-B17A-16435FC05B8B} because it's missing its XML file!! (stt exists: False)
Skipping document 72/128 with OID {2C7A6D6A-6FD4-42CB-9203-5B1D920BE4A0} because it's missing its XML file!! (stt exists: False)
Skipping document 73/128 with OID {E0D128A4-B2D5-4A2B-94CF-458F6A3199C1} because it's missing its XML file!! (stt exists: False)
Skipping document 74/128 with OID {8FAEFA01-1DC8-4FA1-862F-6B11036C8F1E} because it's missing its XML file!! (stt exists: False)
Skipping document 75/128 with OID {C0E1B076-56AD-4367-B85E-D7F6F1AE5930} because it's missing its XML file!! (stt exists: False)
Skipping document 77/128 with OID {AF899C5F-E387-405B-A6D1-345F8FF25049} because it's missing its XML file!! (stt exists: False)
Skipping document 78/128 with OID {FC6CC30A-D2F0-4CD5-AF82-471141221E84} because it's missing its XML file!! (stt exists: False)
Skipping document 79/128 with OID {70B6BB58-69A3-4A0A-9AAA-EC0F128EB158} because it's missing its XML file!! (stt exists: False)
Skipping document 80/128 with OID {B66EC9FF-C1B4-4708-B0A1-AC45C5FE53B7} because it's missing its XML file!! (stt exists: False)
Skipping document 81/128 with OID {BBB85381-1B4D-41AC-B708-09FB73C6F3A4} because it's missing its XML file!! (stt exists: False)
Skipping document 82/128 with OID {611BEE9C-B9D9-4F47-8318-BE7DA966E14F} because it's missing its XML file!! (stt exists: False)
Skipping document 83/128 with OID {D518DD97-DFED-4DA0-BEBA-C9A06F8BF60C} because it's missing its XML file!! (stt exists: False)
Skipping document 84/128 with OID {73A13E45-B104-42DE-B2A5-A6CF6ACDB196} because it's missing its XML file!! (stt exists: False)
Skipping document 85/128 with OID {476EBD07-84BD-4AC0-B783-0F312D12560A} because it's missing its XML file!! (stt exists: False)
Skipping document 86/128 with OID {00A6D38E-1E74-4786-9C35-5ABACFF22C0D} because it's missing its XML file!! (stt exists: False)
Skipping document 88/128 with OID {CB288C9A-8A75-4E5D-B978-ABFEEFE119B5} because it's missing its XML file!! (stt exists: False)
Skipping document 89/128 with OID {E26E7F5B-1775-4571-8808-E07959E28272} because it's missing its XML file!! (stt exists: False)

100%|██████████| 3/3 [00:10<00:00,  3.33s/it]
42it [02:40,  4.27s/it]

Skipping document 91/128 with OID {69055891-3196-4EB7-BA96-FB9DE2714A65} because it's missing its XML file!! (stt exists: False)
Skipping document 92/128 with OID {421DBB02-262A-4993-A8A4-FE6D31A9CC0C} because it's missing its XML file!! (stt exists: False)
Skipping document 93/128 with OID {84C8E0CD-B6D2-4032-BA73-E2FD7C1AC01C} because it's missing its XML file!! (stt exists: False)
Skipping document 95/128 with OID {50D4ED3D-F3DF-466D-9369-EA4FD497BAD6} because it's missing its XML file!! (stt exists: False)
Skipping document 96/128 with OID {CED5B2F2-F0AE-4A34-B6F3-0716F7141604} because it's missing its XML file!! (stt exists: False)
Skipping document 98/128 with OID {FBC5ECFD-0E3F-4C79-9D9F-B525443B1D7C} because it's missing its XML file!! (stt exists: False)
Skipping document 99/128 with OID {DEA2C1DE-8032-4128-BC5C-48F8E9A495E1} because it's missing its XML file!! (stt exists: False)
Skipping document 102/128 with OID {22ED2F78-410B-4087-A759-15B9D5D98BFA} because it's missing its XML file!! (stt exists: False)
Skipping document 104/128 with OID {C3CD85E8-B059-40B0-B5F7-9BA719C81342} because it's missing its XML file!! (stt exists: False)
Skipping document 107/128 with OID {247C76AB-7088-4AD6-A586-AB9C40F928AF} because it's missing its XML file!! (stt exists: False)
Skipping document 108/128 with OID {9B0E3672-ECF2-4CAC-BAF7-9A7E036C2CE1} because it's missing its XML file!! (stt exists: False)
Skipping document 109/128 with OID {404414B5-69EB-4EB7-AACD-09412EFAF00D} because it's missing its XML file!! (stt exists: False)
Skipping document 115/128 with OID {F6C73589-AFC4-4899-88E3-361DFA73CF6D} because it's missing its XML file!! (stt exists: False)
Skipping document 116/128 with OID {44D1662C-BAF4-480A-8FBE-D1A0813F1C30} because it's missing its XML file!! (stt exists: False)
Skipping document 117/128 with OID {1341865A-DE94-434C-8B81-39E6AC62EAA0} because it's missing its XML file!! (stt exists: False)
Skipping document 118/128 with OID {36985BF3-BF15-4152-AB3C-B3A79E38910D} because it's missing its XML file!! (stt exists: False)
Skipping document 119/128 with OID {350E6500-671E-4453-91EB-BDC44BE9736E} because it's missing its XML file!! (stt exists: False)
Skipping document 126/128 with OID {74E4B857-6E9E-4FF6-B190-79E6DF0B7C80} because it's missing its XML file!! (stt exists: False)
Skipping document 127/128 with OID {D4929211-C7C9-401A-AF45-F181B2CE160B} because it's missing its XML file!! (stt exists: False)
petitdej - returning 63 documents, 65 were skipped due to missing necessary info.
 --> Adding 1582 to the out csv for petitdej

PROCESSING PROGRAM suisse_euro (43/47) - 1 files:

Starting extracting 315 documents for program suisse_euro
Skipping document 37/315 with OID {381B046C-8F99-43E0-A3F7-662B6562F772} because it's missing its XML file!! (stt exists: False)

100%|██████████| 1/1 [00:01<00:00,  1.19s/it]
43it [02:42,  3.41s/it]

suisse_euro - returning 314 documents, 1 were skipped due to missing necessary info.
 --> Adding 314 to the out csv for suisse_euro

PROCESSING PROGRAM terre_ciel (44/47) - 1 files:

Starting extracting 304 documents for program terre_ciel
Skipping document 28/304 with OID {D3BDF043-B95D-4B21-8861-5930CCE71634} because it's missing its XML file!! (stt exists: False)
The date for document with OID {A60ABA23-C27B-41C2-B796-178A96CDE012} was invalid (__/__/1976) - changed it to 01/01/1976
WARNING! MISSING DATE FOR DOC WITH OID {6463ACD4-FDC5-4795-82DA-A19AA3263664}!!
Document: {'alias': 'terre_ciel', 'date_str': None, 'stt_filename': '6463ACD4-FDC5-4795-82DA-A19AA3263664_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{6463ACD4-FDC5-4795-82DA-A19AA3263664}', 'stripped_OID': '6463ACD4-FDC5-4795-82DA-A19AA3263664', 'login': '', 'broadcast_episode_title': 'Interview de Didier Rimaud, po?te (2/2) : A propos de ses textes pour la liturgie', 'sequence': '1', 'broadcast_program_name': 'Sur la terre comme au ciel', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'SCO (NumA)', 'modified_on': '04.08.2016 17:08:10', 'physical_support_history': "Cote d'origine : ER 201.02 Resp. RSR : SCO Lot : Caisse 3547", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives. Emissions catholiques", 'content_summary': 'Participant: int:Inconnu,', 'workflow_status': 'Accept?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': None, 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Rimaud, Didier', 'function': 'Interview?/e', 'role': None}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': None, 'recording_dates': None, 'first_broadcast_dates': None},
original: <DOCUMENT><CLSID>{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}</CLSID><OID>{6463ACD4-FDC5-4795-82DA-A19AA3263664}</OID><LOGIN/><TITLE>Interview de Didier Rimaud, po?te (2/2) : A propos de ses textes pour la liturgie</TITLE><HIERARCHY OID="{6463ACD4-FDC5-4795-82DA-A19AA3263664}" current="*" depth="---" title="Interview de Didier Rimaud, po?te (2/2) : A propos de ses textes pour la liturgie"/><SEQUENCE>1</SEQUENCE><BROADCAST>Sur la terre comme au ciel</BROADCAST><DOCUMENTTYPE>Parl?</DOCUMENTTYPE><HIERARCHYLEVEL>Sujet</HIERARCHYLEVEL><MODIFIEDBY>SCO (NumA)</MODIFIEDBY><MODIFIEDON>04.08.2016 17:08:10</MODIFIEDON><HISTORY>Cote d'origine : ER 201.02 Resp. RSR : SCO Lot : Caisse 3547</HISTORY><PARTICIPANTS><PARTICIPANT><NAME>Rimaud, Didier</NAME><FUNCTION>Interview?/e</FUNCTION></PARTICIPANT></PARTICIPANTS><PRODUCTIONTYPE>Production propre</PRODUCTIONTYPE><RIGHTSSTATUS>Clarifi?</RIGHTSSTATUS><RIGHTSUSAGEPOSSIBILITIES><RIGHTSUSAGEPOSSIBILITY>Tous</RIGHTSUSAGEPOSSIBILITY></RIGHTSUSAGEPOSSIBILITIES><SERIESTITLE>Sauvegarde d'archives. Emissions catholiques</SERIESTITLE><SUMMARY>Participant: int:Inconnu, </SUMMARY><WORKFLOWSTATUS>Accept?</WORKFLOWSTATUS><LIVE>Non live</LIVE><WORKDURATION>00:00:00.000</WORKDURATION><WORKDURATIONCOMPL>Non</WORKDURATIONCOMPL><SUPPORTS><SUPPORT><CLSID>{9C19C69A-A4DC-479E-94F1-61FF72CA7889}</CLSID><OID>{1C76706C-D16F-486B-BE09-4C59E789F008}</OID><TITLE>Interview de Didier Rimaud, po?te (2/2) : A propos de ses textes pour la liturgie</TITLE><ISDIGITAL>True</ISDIGITAL><FILENAME>ER201.02{B7FFDD9C-D4EB-4ABC-A16C-A1A2E9398D6D}.wav</FILENAME><ACQUISITIONDATES><ACQUISITIONDATE>10/01/2011</ACQUISITIONDATE></ACQUISITIONDATES><BRAND>Enr. RSR</BRAND><CATALOGUINGSTATUS>Transitoire</CATALOGUINGSTATUS><SOURCE>NumA</SOURCE><UNITDURATION>00:06:16.429</UNITDURATION><UNITDURATIONCOMPL>Non</UNITDURATIONCOMPL><PHYSICALPROPERTIES><ANNOTATIONS>Non</ANNOTATIONS><NUMBEROFCOPIES>0</NUMBEROFCOPIES><NUMBEROFSUPPORTS>0</NUMBEROFSUPPORTS></PHYSICALPROPERTIES></SUPPORT></SUPPORTS></DOCUMENT>
WARNING! MISSING DATE FOR DOC WITH OID {FB8CCA65-C227-447D-AD0A-330485C10F75}!!
Document: {'alias': 'terre_ciel', 'date_str': None, 'stt_filename': 'FB8CCA65-C227-447D-AD0A-330485C10F75_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{FB8CCA65-C227-447D-AD0A-330485C10F75}', 'stripped_OID': 'FB8CCA65-C227-447D-AD0A-330485C10F75', 'login': '', 'broadcast_episode_title': 'Interview de Soeur Hortense Berthet, M?re Abbesse de la Fille-Dieu ? Romont et docteur en physique nucl?aire (2/2)', 'sequence': '1', 'broadcast_program_name': 'Sur la terre comme au ciel', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'SCO (NumA)', 'modified_on': '01.08.2016 05:09:22', 'physical_support_history': "Cote d'origine : ER 133.02 Resp. RSR : SCO Lot : Caisse 3448", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives. Fribourg. Emissions catholiques", 'content_summary': 'Participant: inte:Berthet, Hortense;  int:Inconnu,', 'workflow_status': 'Accept?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'geographical_descriptors': ['Romont', 'Gl?ne (district, FR)', 'Fribourg (canton)'], 'person_descriptors': ['M?re Hortense'], 'thematical_descriptors': ['religion r?v?l?e', 'physique nucl?aire', 'monast?re'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': None, 'recording_dates': None, 'first_broadcast_dates': None},
original: <DOCUMENT><CLSID>{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}</CLSID><OID>{FB8CCA65-C227-447D-AD0A-330485C10F75}</OID><LOGIN/><TITLE>Interview de Soeur Hortense Berthet, M?re Abbesse de la Fille-Dieu ? Romont et docteur en physique nucl?aire (2/2)</TITLE><HIERARCHY OID="{FB8CCA65-C227-447D-AD0A-330485C10F75}" current="*" depth="---" title="Interview de Soeur Hortense Berthet, M?re Abbesse de la Fille-Dieu ? Romont et docteur en physique nucl?aire (2/2)"/><SEQUENCE>1</SEQUENCE><BROADCAST>Sur la terre comme au ciel</BROADCAST><DOCUMENTTYPE>Parl?</DOCUMENTTYPE><GEOGRAPHICALDESCRIPTORS><GEOGRAPHICALDESCRIPTOR>Romont</GEOGRAPHICALDESCRIPTOR><GEOGRAPHICALDESCRIPTOR>Gl?ne (district, FR)</GEOGRAPHICALDESCRIPTOR><GEOGRAPHICALDESCRIPTOR>Fribourg (canton)</GEOGRAPHICALDESCRIPTOR></GEOGRAPHICALDESCRIPTORS><HIERARCHYLEVEL>Sujet</HIERARCHYLEVEL><MODIFIEDBY>SCO (NumA)</MODIFIEDBY><MODIFIEDON>01.08.2016 05:09:22</MODIFIEDON><HISTORY>Cote d'origine : ER 133.02 Resp. RSR : SCO Lot : Caisse 3448</HISTORY><PERSONDESCRIPTORS><PERSONDESCRIPTOR>M?re Hortense</PERSONDESCRIPTOR></PERSONDESCRIPTORS><PRODUCTIONTYPE>Production propre</PRODUCTIONTYPE><RIGHTSSTATUS>Clarifi?</RIGHTSSTATUS><RIGHTSUSAGEPOSSIBILITIES><RIGHTSUSAGEPOSSIBILITY>Tous</RIGHTSUSAGEPOSSIBILITY></RIGHTSUSAGEPOSSIBILITIES><SERIESTITLE>Sauvegarde d'archives. Fribourg. Emissions catholiques</SERIESTITLE><SUMMARY>Participant: inte:Berthet, Hortense;  int:Inconnu,</SUMMARY><THEMATICALDESCRIPTORS><THEMATICALDESCRIPTOR>religion r?v?l?e</THEMATICALDESCRIPTOR><THEMATICALDESCRIPTOR>physique nucl?aire</THEMATICALDESCRIPTOR><THEMATICALDESCRIPTOR>monast?re</THEMATICALDESCRIPTOR></THEMATICALDESCRIPTORS><WORKFLOWSTATUS>Accept?</WORKFLOWSTATUS><LIVE>Non live</LIVE><MODULATIONTYPE>Mono</MODULATIONTYPE><WORKDURATION>00:00:00.000</WORKDURATION><WORKDURATIONCOMPL>Non</WORKDURATIONCOMPL><SUPPORTS><SUPPORT><CLSID>{9C19C69A-A4DC-479E-94F1-61FF72CA7889}</CLSID><OID>{739AE444-5C25-4435-90E6-B59CDFDBD281}</OID><TITLE>Interview de S?ur Hortense Berthet, M?re Abbesse de la Fille-Dieu et docteur en physique nucl?aire (2/2)</TITLE><ISDIGITAL>True</ISDIGITAL><FILENAME>ER133.02{F59AA3BC-64C2-4909-8DDC-92F4067BA2AD}.wav</FILENAME><ACQUISITIONDATES><ACQUISITIONDATE>10/01/2011</ACQUISITIONDATE></ACQUISITIONDATES><BRAND>Enr. RSR</BRAND><CATALOGUINGSTATUS>Transitoire</CATALOGUINGSTATUS><SOURCE>NumA</SOURCE><UNITDURATION>00:08:21.126</UNITDURATION><UNITDURATIONCOMPL>Non</UNITDURATIONCOMPL><PHYSICALPROPERTIES><ANNOTATIONS>Non</ANNOTATIONS><NUMBEROFCOPIES>0</NUMBEROFCOPIES><NUMBEROFSUPPORTS>0</NUMBEROFSUPPORTS></PHYSICALPROPERTIES></SUPPORT></SUPPORTS></DOCUMENT>
WARNING! MISSING DATE FOR DOC WITH OID {8F4415A9-FB2D-49FE-9BC6-DAC42B1A4EA5}!!
Document: {'alias': 'terre_ciel', 'date_str': None, 'stt_filename': '8F4415A9-FB2D-49FE-9BC6-DAC42B1A4EA5_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{8F4415A9-FB2D-49FE-9BC6-DAC42B1A4EA5}', 'stripped_OID': '8F4415A9-FB2D-49FE-9BC6-DAC42B1A4EA5', 'login': '', 'broadcast_episode_title': 'Interview de Xavier L?on-Dufour, ex?g?te : Textes eucharistiques (2/3)', 'sequence': '1', 'broadcast_program_name': 'Sur la terre comme au ciel', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'SCO (NumA)', 'modified_on': '02.08.2016 12:12:31', 'physical_support_history': "Cote d'origine : ER 135.02 Resp. RSR : SCO Lot : Caisse 3448", 'production_type': 'Production propre', 'recording_place': 'Paris', 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Participant: inte:L?on-Dufour, Xavier;  int:Inconnu,', 'workflow_status': 'Accept?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': None, 'recording_dates': None, 'first_broadcast_dates': None},
original: <DOCUMENT><CLSID>{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}</CLSID><OID>{8F4415A9-FB2D-49FE-9BC6-DAC42B1A4EA5}</OID><LOGIN/><TITLE>Interview de Xavier L?on-Dufour, ex?g?te : Textes eucharistiques (2/3)</TITLE><HIERARCHY OID="{8F4415A9-FB2D-49FE-9BC6-DAC42B1A4EA5}" current="*" depth="---" title="Interview de Xavier L?on-Dufour, ex?g?te : Textes eucharistiques (2/3)"/><SEQUENCE>1</SEQUENCE><BROADCAST>Sur la terre comme au ciel</BROADCAST><DOCUMENTTYPE>Parl?</DOCUMENTTYPE><HIERARCHYLEVEL>Sujet</HIERARCHYLEVEL><MODIFIEDBY>SCO (NumA)</MODIFIEDBY><MODIFIEDON>02.08.2016 12:12:31</MODIFIEDON><HISTORY>Cote d'origine : ER 135.02 Resp. RSR : SCO Lot : Caisse 3448</HISTORY><PRODUCTIONTYPE>Production propre</PRODUCTIONTYPE><RECORDINGPLACE>Paris</RECORDINGPLACE><RIGHTSSTATUS>Clarifi?</RIGHTSSTATUS><RIGHTSUSAGEPOSSIBILITIES><RIGHTSUSAGEPOSSIBILITY>Tous</RIGHTSUSAGEPOSSIBILITY></RIGHTSUSAGEPOSSIBILITIES><SERIESTITLE>Sauvegarde d'archives</SERIESTITLE><SUMMARY>Participant: inte:L?on-Dufour, Xavier;  int:Inconnu,</SUMMARY><WORKFLOWSTATUS>Accept?</WORKFLOWSTATUS><LIVE>Non live</LIVE><MODULATIONTYPE>Mono</MODULATIONTYPE><WORKDURATION>00:00:00.000</WORKDURATION><WORKDURATIONCOMPL>Non</WORKDURATIONCOMPL><SUPPORTS><SUPPORT><CLSID>{9C19C69A-A4DC-479E-94F1-61FF72CA7889}</CLSID><OID>{785DCEA9-E2FD-46EF-8335-019657D54C9B}</OID><TITLE>Interview de Xavier L?on-Dufour, ex?g?te : Textes eucharistiques (2/3)</TITLE><ISDIGITAL>True</ISDIGITAL><FILENAME>ER135.02{27DFA64A-E73E-484D-AFDA-B05DF4DFF202}.wav</FILENAME><ACQUISITIONDATES><ACQUISITIONDATE>10/01/2011</ACQUISITIONDATE></ACQUISITIONDATES><BRAND>Enr. RSR</BRAND><CATALOGUINGSTATUS>Transitoire</CATALOGUINGSTATUS><SOURCE>NumA</SOURCE><UNITDURATION>00:05:47.627</UNITDURATION><UNITDURATIONCOMPL>Non</UNITDURATIONCOMPL><PHYSICALPROPERTIES><ANNOTATIONS>Non</ANNOTATIONS><NUMBEROFCOPIES>0</NUMBEROFCOPIES><NUMBEROFSUPPORTS>0</NUMBEROFSUPPORTS></PHYSICALPROPERTIES></SUPPORT></SUPPORTS></DOCUMENT>
WARNING! MISSING DATE FOR DOC WITH OID {5C6E2EC2-8E06-4C1F-9B05-D7CB1A6F58C7}!!
Document: {'alias': 'terre_ciel', 'date_str': None, 'stt_filename': '5C6E2EC2-8E06-4C1F-9B05-D7CB1A6F58C7_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{5C6E2EC2-8E06-4C1F-9B05-D7CB1A6F58C7}', 'stripped_OID': '5C6E2EC2-8E06-4C1F-9B05-D7CB1A6F58C7', 'login': '', 'broadcast_episode_title': 'Interview de Xavier L?on-Dufour, ex?g?te : Textes eucharistiques (3/3)', 'sequence': '1', 'broadcast_program_name': 'Sur la terre comme au ciel', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'SCO (NumA)', 'modified_on': '31.07.2016 05:11:37', 'physical_support_history': "Cote d'origine : ER 135.03 Resp. RSR : SCO Lot : Caisse 3448", 'production_type': 'Production propre', 'recording_place': 'Paris', 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Participant: inte:L?on-Dufour, Xavier;  int:Inconnu,', 'workflow_status': 'Accept?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': None, 'recording_dates': None, 'first_broadcast_dates': None},
original: <DOCUMENT><CLSID>{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}</CLSID><OID>{5C6E2EC2-8E06-4C1F-9B05-D7CB1A6F58C7}</OID><LOGIN/><TITLE>Interview de Xavier L?on-Dufour, ex?g?te : Textes eucharistiques (3/3)</TITLE><HIERARCHY OID="{5C6E2EC2-8E06-4C1F-9B05-D7CB1A6F58C7}" current="*" depth="---" title="Interview de Xavier L?on-Dufour, ex?g?te : Textes eucharistiques (3/3)"/><SEQUENCE>1</SEQUENCE><BROADCAST>Sur la terre comme au ciel</BROADCAST><DOCUMENTTYPE>Parl?</DOCUMENTTYPE><HIERARCHYLEVEL>Sujet</HIERARCHYLEVEL><MODIFIEDBY>SCO (NumA)</MODIFIEDBY><MODIFIEDON>31.07.2016 05:11:37</MODIFIEDON><HISTORY>Cote d'origine : ER 135.03 Resp. RSR : SCO Lot : Caisse 3448</HISTORY><PRODUCTIONTYPE>Production propre</PRODUCTIONTYPE><RECORDINGPLACE>Paris</RECORDINGPLACE><RIGHTSSTATUS>Clarifi?</RIGHTSSTATUS><RIGHTSUSAGEPOSSIBILITIES><RIGHTSUSAGEPOSSIBILITY>Tous</RIGHTSUSAGEPOSSIBILITY></RIGHTSUSAGEPOSSIBILITIES><SERIESTITLE>Sauvegarde d'archives</SERIESTITLE><SUMMARY>Participant: inte:L?on-Dufour, Xavier;  int:Inconnu,</SUMMARY><WORKFLOWSTATUS>Accept?</WORKFLOWSTATUS><LIVE>Non live</LIVE><MODULATIONTYPE>Mono</MODULATIONTYPE><WORKDURATION>00:00:00.000</WORKDURATION><WORKDURATIONCOMPL>Non</WORKDURATIONCOMPL><SUPPORTS><SUPPORT><CLSID>{9C19C69A-A4DC-479E-94F1-61FF72CA7889}</CLSID><OID>{B0F442E0-99C0-46BD-ABE7-CE0F8B93B660}</OID><TITLE>Interview de Xavier L?on-Dufour, ex?g?te : Textes eucharistiques (3/3)</TITLE><ISDIGITAL>True</ISDIGITAL><FILENAME>ER135.03{6FAED12D-8C77-4998-86D7-2821440C316C}.wav</FILENAME><ACQUISITIONDATES><ACQUISITIONDATE>10/01/2011</ACQUISITIONDATE></ACQUISITIONDATES><BRAND>Enr. RSR</BRAND><CATALOGUINGSTATUS>Transitoire</CATALOGUINGSTATUS><SOURCE>NumA</SOURCE><UNITDURATION>00:10:39.565</UNITDURATION><UNITDURATIONCOMPL>Non</UNITDURATIONCOMPL><PHYSICALPROPERTIES><ANNOTATIONS>Non</ANNOTATIONS><NUMBEROFCOPIES>0</NUMBEROFCOPIES><NUMBEROFSUPPORTS>0</NUMBEROFSUPPORTS></PHYSICALPROPERTIES></SUPPORT></SUPPORTS></DOCUMENT>
WARNING! MISSING DATE FOR DOC WITH OID {A02A978B-4D77-48C3-8A9E-05BBAD7462A0}!!
Document: {'alias': 'terre_ciel', 'date_str': None, 'stt_filename': 'A02A978B-4D77-48C3-8A9E-05BBAD7462A0_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{A02A978B-4D77-48C3-8A9E-05BBAD7462A0}', 'stripped_OID': 'A02A978B-4D77-48C3-8A9E-05BBAD7462A0', 'login': '', 'broadcast_episode_title': 'Interview du p?re Emiliano Tardif, figure du renouveau charismatique (2/2) : Conf?rences dans le monde et perspectives oecum?niques', 'sequence': '1', 'broadcast_program_name': 'Sur la terre comme au ciel', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'SCO (NumA)', 'modified_on': '05.08.2016 06:01:25', 'physical_support_history': "Cote d'origine : ER 175.02 Resp. RSR : SCO Lot : Caisse 3547", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives. Emissions catholiques", 'content_summary': 'Participant:  int:Inconnu,', 'workflow_status': 'Accept?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Tardif, Emiliano', 'function': 'Interview?/e', 'role': None}], 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': ['Tous'], 'radio_channels': None, 'subdomains': None, 'recording_dates': None, 'first_broadcast_dates': None},
original: <DOCUMENT><CLSID>{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}</CLSID><OID>{A02A978B-4D77-48C3-8A9E-05BBAD7462A0}</OID><LOGIN/><TITLE>Interview du p?re Emiliano Tardif, figure du renouveau charismatique (2/2) : Conf?rences dans le monde et perspectives oecum?niques</TITLE><HIERARCHY OID="{A02A978B-4D77-48C3-8A9E-05BBAD7462A0}" current="*" depth="---" title="Interview du p?re Emiliano Tardif, figure du renouveau charismatique (2/2) : Conf?rences dans le monde et perspectives oecum?niques"/><SEQUENCE>1</SEQUENCE><BROADCAST>Sur la terre comme au ciel</BROADCAST><DOCUMENTTYPE>Parl?</DOCUMENTTYPE><HIERARCHYLEVEL>Sujet</HIERARCHYLEVEL><MODIFIEDBY>SCO (NumA)</MODIFIEDBY><MODIFIEDON>05.08.2016 06:01:25</MODIFIEDON><HISTORY>Cote d'origine : ER 175.02 Resp. RSR : SCO Lot : Caisse 3547</HISTORY><PARTICIPANTS><PARTICIPANT><NAME>Tardif, Emiliano</NAME><FUNCTION>Interview?/e</FUNCTION></PARTICIPANT></PARTICIPANTS><PRODUCTIONTYPE>Production propre</PRODUCTIONTYPE><RIGHTSSTATUS>Clarifi?</RIGHTSSTATUS><RIGHTSUSAGEPOSSIBILITIES><RIGHTSUSAGEPOSSIBILITY>Tous</RIGHTSUSAGEPOSSIBILITY></RIGHTSUSAGEPOSSIBILITIES><SERIESTITLE>Sauvegarde d'archives. Emissions catholiques</SERIESTITLE><SUMMARY>Participant:  int:Inconnu,</SUMMARY><WORKFLOWSTATUS>Accept?</WORKFLOWSTATUS><LIVE>Non live</LIVE><MODULATIONTYPE>Mono</MODULATIONTYPE><WORKDURATION>00:00:00.000</WORKDURATION><WORKDURATIONCOMPL>Non</WORKDURATIONCOMPL><SUPPORTS><SUPPORT><CLSID>{9C19C69A-A4DC-479E-94F1-61FF72CA7889}</CLSID><OID>{AF281C58-EB90-46B6-9F24-D4C7E237282C}</OID><TITLE>Interview du p?re Emiliano Tardif, figure du renouveau charismatique (2/2) : Conf?rences dans le monde et perspectives oecum?niques</TITLE><ISDIGITAL>True</ISDIGITAL><FILENAME>ER175.02{4BB561EC-83CB-4151-8341-3781D86B528C}.wav</FILENAME><ACQUISITIONDATES><ACQUISITIONDATE>10/01/2011</ACQUISITIONDATE></ACQUISITIONDATES><BRAND>Enr. RSR</BRAND><CATALOGUINGSTATUS>Transitoire</CATALOGUINGSTATUS><SOURCE>NumA</SOURCE><UNITDURATION>00:16:51.343</UNITDURATION><UNITDURATIONCOMPL>Non</UNITDURATIONCOMPL><PHYSICALPROPERTIES><ANNOTATIONS>Non</ANNOTATIONS><NUMBEROFCOPIES>0</NUMBEROFCOPIES><NUMBEROFSUPPORTS>0</NUMBEROFSUPPORTS></PHYSICALPROPERTIES></SUPPORT></SUPPORTS></DOCUMENT>
Skipping document 197/304 with OID {1D36EAA5-F963-4F11-9648-121F600F83B1} because it's missing its XML file!! (stt exists: False)
Skipping document 198/304 with OID {63E0C4A7-7F62-4172-90D9-A031A48DCCF9} because it's missing its XML file!! (stt exists: False)
Skipping document 206/304 with OID {A6AE3FB0-6E11-414A-9008-4881B831511A} because it's missing its XML file!! (stt exists: False)
Skipping document 209/304 with OID {FEE4DB9B-8DFE-48DF-B0B3-4C1C99326041} because it's missing its XML file!! (stt exists: False)
Skipping document 211/304 with OID {F6489BA0-FE78-4007-8290-55B96A6AFF14} because it's missing its XML file!! (stt exists: False)
Skipping document 212/304 with OID {4FE431DE-72CE-4108-A035-AD893394AABC} because it's missing its XML file!! (stt exists: False)
Skipping document 213/304 with OID {96D974FC-B85A-4958-BF2F-3C0D194411F9} because it's missing its XML file!! (stt exists: False)
Skipping document 214/304 with OID {FB408ED7-7293-483E-ADC2-1B0208C2B7D3} because it's missing its XML file!! (stt exists: False)
Skipping document 216/304 with OID {91129EAB-4A7A-443D-A0D1-24DB21AA6901} because it's missing its XML file!! (stt exists: False)

100%|██████████| 1/1 [00:01<00:00,  1.53s/it]
44it [02:43,  2.90s/it]

Skipping document 236/304 with OID {7A7677BA-BCB3-4183-83B5-2FCF7D68FC57} because it's missing its XML file!! (stt exists: False)
Skipping document 243/304 with OID {29DB91D6-AE3E-4EB9-B040-51B0B8A22FA0} because it's missing its XML file!! (stt exists: False)
The date for document with OID {891E7BBC-4D59-4FAD-8DD5-F6B58907C8D5} was invalid (__/10/1970) - changed it to 01/10/1970
The date for document with OID {EFABA965-477D-46E7-B274-A87CCE16CD93} was invalid (__/10/1970) - changed it to 01/10/1970
Skipping document 256/304 with OID {A05BF2CD-E025-42B3-A20B-7E8ADCC9F111} because it's missing its XML file!! (stt exists: False)
Skipping document 285/304 with OID {A33DEECC-318F-4C47-9730-6DC2DEDB990F} because it's missing its XML file!! (stt exists: False)
terre_ciel - returning 290 documents, 14 were skipped due to missing necessary info.
 --> Adding 290 to the out csv for terre_ciel

PROCESSING PROGRAM trib_prem (45/47) - 1 files:

Starting extracting 527 documents for program trib_prem
Skipping document 2/527 with OID {05935AB3-A70B-4D12-B865-CB6BEA6D7F26} because it's missing its XML file!! (stt exists: False)
Skipping document 3/527 with OID {E7288F10-D496-42FB-92FE-44D3FF374C20} because it's missing its XML file!! (stt exists: False)
Skipping document 4/527 with OID {E7186C42-E74B-446C-B9F7-35D943A02DA5} because it's missing its XML file!! (stt exists: False)
Skipping document 6/527 with OID {492F9F59-62E6-4E5B-A9D3-97997C77072C} because it's missing its XML file!! (stt exists: False)
Skipping document 8/527 with OID {987E5CAC-5AB2-41AD-A2C8-7C26629601F4} because it's missing its XML file!! (stt exists: False)
Skipping document 12/527 with OID {903606F0-F9A1-4958-A8EA-46FBE45B03C1} because it's missing its XML file!! (stt exists: False)
Skipping document 16/527 with OID {52313D52-106C-4225-BC2D-D8714885B92C} because it's missing its XML file!! (stt exists: False)
Skipping document 30/527 with OID {354E8AE2-69C1-4346-90F6-4FE570955357} because it's missing its XML file!! (stt exists: True)
Skipping document 34/527 with OID {289C38DC-35E5-4F51-B93C-4B5E4E870CE9} because it's missing its XML file!! (stt exists: False)
Skipping document 40/527 with OID {FFC117E8-9F8B-4AE0-9BEA-8201F029D33D} because it's missing its XML file!! (stt exists: False)
Skipping document 51/527 with OID {B0E5D68A-48EB-4EAF-9943-8A8D5B82F0B5} because it's missing its XML file!! (stt exists: True)
Skipping document 59/527 with OID {FAFF4263-A0D5-4CC3-97A5-9B506A32E9F3} because it's missing its XML file!! (stt exists: False)
Skipping document 74/527 with OID {61BD51A5-8CE0-4156-8264-7F8427C12E1E} because it's missing its XML file!! (stt exists: False)
Skipping document 78/527 with OID {6E8006D1-0FAB-4439-9EB9-E6A781B72CB9} because it's missing its XML file!! (stt exists: False)
Skipping document 90/527 with OID {8F978F7F-CC28-427D-8DF4-B5F6CED597CC} because it's missing its XML file!! (stt exists: True)
Skipping document 92/527 with OID {55ED0C22-C039-4658-9823-236A4F81FFC7} because it's missing its XML file!! (stt exists: False)
Skipping document 97/527 with OID {0BE39267-1703-4644-80E8-C03529F8C4AB} because it's missing its XML file!! (stt exists: False)
Skipping document 100/527 with OID {775C612B-A257-4DDC-B933-F9D74AF21F02} because it's missing its XML file!! (stt exists: False)
Skipping document 102/527 with OID {CDF1DFED-B3BF-40BB-8E01-AAAFF9A3C90D} because it's missing its XML file!! (stt exists: False)
Skipping document 103/527 with OID {9BD589B5-D396-4CBA-8BA0-575432823C2F} because it's missing its XML file!! (stt exists: False)
Skipping document 105/527 with OID {8A122B7E-B17B-43A8-86CA-3BF84C304BED} because it's missing its XML file!! (stt exists: False)
Skipping document 115/527 with OID {A3CF0C11-229E-41EA-A053-6571CBD078D5} because it's missing its XML file!! (stt exists: True)
Skipping document 134/527 with OID {23A2E9F0-6E5A-4322-91C3-283532413322} because it's missing its XML file!! (stt exists: False)
Skipping document 135/527 with OID {357B6016-6727-448E-B8C0-6CD25E2C12FD} because it's missing its XML file!! (stt exists: False)
Skipping document 136/527 with OID {2E55CB8C-7052-4758-8298-A03975C3163A} because it's missing its XML file!! (stt exists: False)
Skipping document 156/527 with OID {8F083D2C-DFEF-4D1C-881E-0D57A379E250} because it's missing its XML file!! (stt exists: False)
Skipping document 167/527 with OID {E8226933-E156-4315-A795-7BAE8ABE5115} because it's missing its XML file!! (stt exists: True)
Skipping document 176/527 with OID {CBDF966C-269C-4AA2-86A0-D5BB9C8B623F} because it's missing its XML file!! (stt exists: False)
Skipping document 180/527 with OID {80DA3B1A-E582-4247-A5C9-1EB8D67ADC8B} because it's missing its XML file!! (stt exists: True)
Skipping document 189/527 with OID {C7FEF3C1-7D9C-4863-93DC-C736553BFE44} because it's missing its XML file!! (stt exists: False)
Skipping document 192/527 with OID {572DE4F0-DAE6-468C-87D4-78AB41EE2FF1} because it's missing its XML file!! (stt exists: True)
Skipping document 193/527 with OID {B04498C3-7D3C-49B1-B858-BB529BF88376} because it's missing its XML file!! (stt exists: True)
Skipping document 200/527 with OID {8BA794CE-3982-4C4B-8E15-98D4467A4A20} because it's missing its XML file!! (stt exists: False)
Skipping document 218/527 with OID {4EB6FEC5-0627-4835-84B3-EC3210CA98BA} because it's missing its XML file!! (stt exists: True)
Skipping document 222/527 with OID {504A5265-A05A-4566-8620-853EC0D37860} because it's missing its XML file!! (stt exists: True)
Skipping document 227/527 with OID {DC1465C2-98C2-4FE1-A873-CAF8EB60CF0A} because it's missing its XML file!! (stt exists: True)
Skipping document 237/527 with OID {70033DC7-C9EC-4B2F-B970-407D0271580E} because it's missing its XML file!! (stt exists: False)
Skipping document 238/527 with OID {7091482C-9D2C-44C2-A3DE-51E7E738C34C} because it's missing its XML file!! (stt exists: True)
Skipping document 240/527 with OID {9065882B-6313-4536-963C-478FF7C905CD} because it's missing its XML file!! (stt exists: True)
Skipping document 253/527 with OID {E69B12EE-78EF-43BB-AA3C-6605E23E6216} because it's missing its XML file!! (stt exists: True)
Skipping document 257/527 with OID {11BFD9A3-70D3-422B-A2F5-2714F96FC448} because it's missing its XML file!! (stt exists: True)
Skipping document 277/527 with OID {DAA27E7F-A265-4B89-95ED-E732D3C3DD62} because it's missing its XML file!! (stt exists: False)
Skipping document 306/527 with OID {896F97BA-069B-46CD-AC80-2B7CE6FB3DD7} because it's missing its XML file!! (stt exists: False)
Skipping document 309/527 with OID {CA6BB5C0-C107-45DE-8691-3FDC97C3EDD0} because it's missing its XML file!! (stt exists: False)
Skipping document 313/527 with OID {FC439219-187C-4CC0-9176-A76001DB1E27} because it's missing its XML file!! (stt exists: False)
Skipping document 319/527 with OID {CBA0A390-EA3E-4F89-952D-50B85AA3A8F0} because it's missing its XML file!! (stt exists: True)
Skipping document 320/527 with OID {7A232D57-309E-484A-910D-07F95F9A0DD6} because it's missing its XML file!! (stt exists: True)
Skipping document 323/527 with OID {6533D064-F920-4AD6-89C0-07CA686F5E2B} because it's missing its XML file!! (stt exists: False)
Skipping document 328/527 with OID {FE07D0BE-CCC7-4E0A-9378-637E076A7EDB} because it's missing its XML file!! (stt exists: False)
Skipping document 341/527 with OID {1F8F7232-E638-404E-A88D-66F974745AB4} because it's missing its XML file!! (stt exists: False)
Skipping document 347/527 with OID {4C8863DD-3356-465B-A324-BBEBACCF0909} because it's missing its XML file!! (stt exists: True)
Skipping document 358/527 with OID {1565456C-469F-4D99-969C-FB9BBAF8BB43} because it's missing its XML file!! (stt exists: True)
Skipping document 378/527 with OID {3602093D-9E0C-40EF-8BE9-7A06DC1E1A25} because it's missing its XML file!! (stt exists: False)
Skipping document 385/527 with OID {B90F6ACA-5F65-46F5-BAE3-FFFE6CE56644} because it's missing its XML file!! (stt exists: False)
Skipping document 388/527 with OID {2B825832-AC22-4EB9-815E-0FFB678BE99B} because it's missing its XML file!! (stt exists: False)
Skipping document 390/527 with OID {DC336317-2E3A-468A-9C99-791B2F869DA8} because it's missing its XML file!! (stt exists: False)
Skipping document 392/527 with OID {1245D810-799D-46DD-93AF-54363637878F} because it's missing its XML file!! (stt exists: False)
Skipping document 396/527 with OID {22889B29-8C50-4FA0-9630-9ADBBBFA80AF} because it's missing its XML file!! (stt exists: True)
Skipping document 399/527 with OID {07BAD843-BC6E-4EB2-A7A9-DC5262B2638A} because it's missing its XML file!! (stt exists: False)
Skipping document 401/527 with OID {B058EA11-0595-4016-9F74-37BA6CCF94CA} because it's missing its XML file!! (stt exists: False)
Skipping document 402/527 with OID {7F15E1A0-4236-4DE0-B123-8629DF9CB92C} because it's missing its XML file!! (stt exists: True)
Skipping document 403/527 with OID {D629EB6F-0169-42B1-A420-8FE1B5438D07} because it's missing its XML file!! (stt exists: True)
Skipping document 404/527 with OID {57990090-51F8-4019-96EE-540E83E2B43F} because it's missing its XML file!! (stt exists: False)
Skipping document 405/527 with OID {AA87CDBB-CF99-4A43-BDEE-C79EEA9C695A} because it's missing its XML file!! (stt exists: True)
Skipping document 412/527 with OID {AA67B867-31EB-4340-BE2C-C68642BFD558} because it's missing its XML file!! (stt exists: True)
Skipping document 413/527 with OID {4CC639AA-6904-4E78-A19C-7D3809171B83} because it's missing its XML file!! (stt exists: True)
Skipping document 414/527 with OID {89B99950-E9E2-41F2-BC3D-AFF455D9E1D2} because it's missing its XML file!! (stt exists: False)
Skipping document 417/527 with OID {AFB22F85-51DA-4D13-8840-6B1737BCEFC8} because it's missing its XML file!! (stt exists: False)
Skipping document 423/527 with OID {EEEBF89B-5E53-475A-B304-B955839E53DE} because it's missing its XML file!! (stt exists: True)

100%|██████████| 1/1 [00:02<00:00,  2.36s/it]
45it [02:46,  2.85s/it]

Did not find any date for doc with OID {7271522B-DD9F-43F2-8194-E7BC10F897D9}. Trying to use the recording date. doc_dict: {'alias': 'trib_prem', 'date_str': None, 'stt_filename': '7271522B-DD9F-43F2-8194-E7BC10F897D9_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{7271522B-DD9F-43F2-8194-E7BC10F897D9}', 'stripped_OID': '7271522B-DD9F-43F2-8194-E7BC10F897D9', 'login': '', 'broadcast_episode_title': "Interview de Pier-Luigi Giovannini, secr?taire romand de la D?claration de Berne, ? l'occasion du 20e anniversaire de la D?claration de Berne", 'sequence': '1', 'broadcast_program_name': 'Tribune de Premi?re', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'albrecjo', 'modified_on': '06.05.2022 07:04:49', 'physical_support_history': "Cote d'origine: A 10427", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives. Fribourg", 'content_summary': "Cr??e en 1968, la D?claration de Berne (DB) avait une double revendication : un accroissement de l'aide au d?veloppement et la modification des structures ?conomiques. La DB a-t-elle depuis modifi? son discours? Pier-Luigi Giovannini ?voque les changements qui ont marqu? la soci?t?. La DB focalise d?sormais ses efforts sur les pressions politiques et ?conomiques, ainsi que sur la sensibilisation des jeunes aux probl?mes du Tiers-Monde. Si la DB descendait dans la rue pour manifester, l'action est davantage orient?e vers le dialogue avec les diff?rents acteurs. Financement provenant de la cotisation des membres et des dons d'organisations nationales. Evocation de quelques actions pour un commerce plus ?quitable, contre le secret bancaire ou encore contre le lait infantile de Nestl?.", 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:20:00.988', 'work_duration_compl': 'Non', 'participants': [{'name': 'Giovannini, Pier-Luigi', 'function': 'Interview?/e', 'role': 'secr?taire romand de la D?claration de Berne'}, {'name': 'Inconnu', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}, {'name': 'Inconnu', 'function': 'Pr?sentateur/trice', 'role': 'collaborateur RSR'}], 'geographical_descriptors': ['Suisse'], 'person_descriptors': ['D?claration de Berne'], 'thematical_descriptors': ['d?veloppement ?conomique', 'pays en voie de d?veloppement', 'commerce international', 'r?fugi?', 'tiers-mondisme'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['La Premi?re'], 'subdomains': ['Interview'], 'recording_dates': ['24/04/1988 - 24/04/1988'], 'first_broadcast_dates': None}
Skipping document 505/527 with OID {231FFF03-B413-44FC-B3E1-8D2D36F9C42A} because it's missing its XML file!! (stt exists: False)
Skipping document 509/527 with OID {B23DD39D-4FF5-4424-B801-20C834EC7F23} because it's missing its XML file!! (stt exists: False)
Skipping document 524/527 with OID {A4B737AC-0BEA-46DD-B25D-D48477E03844} because it's missing its XML file!! (stt exists: False)
trib_prem - returning 455 documents, 72 were skipped due to missing necessary info.
 --> Adding 455 to the out csv for trib_prem

PROCESSING PROGRAM vie_monde (46/47) - 1 files:

Starting extracting 281 documents for program vie_monde
Skipping document 11/281 with OID {043C4BF7-E19E-4991-89AE-978D85646A3E} because it's missing its XML file!! (stt exists: False)
Skipping document 12/281 with OID {452DAC3F-BE74-49D7-8440-AB3CC8DB5267} because it's missing its XML file!! (stt exists: False)
Skipping document 14/281 with OID {67FFDC96-133E-4DF7-BDB7-74A1BA9111D9} because it's missing its XML file!! (stt exists: False)
Skipping document 20/281 with OID {069393AA-86BC-4104-A912-4E324D914EAA} because it's missing its XML file!! (stt exists: True)
Skipping document 21/281 with OID {2BF917F8-AB69-4352-A4D7-C9B5AC5B82E7} because it's missing its XML file!! (stt exists: False)
Skipping document 23/281 with OID {B6E423E6-9456-44BE-AA3A-BEAE8D9B845C} because it's missing its XML file!! (stt exists: False)
Skipping document 25/281 with OID {89BDE7C3-1AF4-401E-9771-245DEDC2A81E} because it's missing its XML file!! (stt exists: False)
Skipping document 26/281 with OID {01F899B3-D6B6-419D-B5BC-A57A4E74960A} because it's missing its XML file!! (stt exists: False)
Skipping document 27/281 with OID {B974FBA0-D8BE-4467-BD91-CC8D4DAC10AD} because it's missing its XML file!! (stt exists: False)
Skipping document 28/281 with OID {3E36FFAB-B5D4-473E-AB94-2AD2448A5A67} because it's missing its XML file!! (stt exists: False)
Skipping document 29/281 with OID {6599D6B5-FC2F-482D-9B4D-2A92EC504E84} because it's missing its XML file!! (stt exists: False)
Skipping document 30/281 with OID {EAFB4426-0FAD-453F-8B0E-A62C01127E1D} because it's missing its XML file!! (stt exists: False)
Skipping document 31/281 with OID {9615C948-FECA-477A-AE6B-D4921A921D72} because it's missing its XML file!! (stt exists: False)
Skipping document 32/281 with OID {B022D290-28DE-4BE3-9175-F642EE533458} because it's missing its XML file!! (stt exists: False)
Skipping document 33/281 with OID {5C687A93-B7E2-464A-A29B-13E417BE2F71} because it's missing its XML file!! (stt exists: False)
Skipping document 34/281 with OID {7C757173-5EB4-4D04-9531-616B0E7462AB} because it's missing its XML file!! (stt exists: False)
Skipping document 35/281 with OID {19E80B37-18FE-4CDA-8BD6-1C0DB71E9947} because it's missing its XML file!! (stt exists: False)
Skipping document 37/281 with OID {E74B00E8-C3E2-4AF6-9F22-54E887F5B92C} because it's missing its XML file!! (stt exists: False)
Skipping document 38/281 with OID {746223EA-B4D7-4A34-BFF5-90E4FA9A4596} because it's missing its XML file!! (stt exists: False)
Skipping document 39/281 with OID {C8DCE00C-4C7A-48AB-8D69-7D762F99E6D4} because it's missing its XML file!! (stt exists: False)
Skipping document 40/281 with OID {DF962B1C-FDB6-4751-A5E7-660FA39D1C26} because it's missing its XML file!! (stt exists: False)
Skipping document 41/281 with OID {5051DE15-A5B4-485F-A4B8-43EB75E76B15} because it's missing its XML file!! (stt exists: False)
Skipping document 42/281 with OID {8C74C137-DC70-47BF-8DF7-1E9218F509B9} because it's missing its XML file!! (stt exists: False)
Skipping document 43/281 with OID {048EEC1E-B8EE-42BC-8E3C-10F1134B6117} because it's missing its XML file!! (stt exists: False)
Skipping document 44/281 with OID {3F32C137-DBB0-4FFF-A741-1A3EFD6827D9} because it's missing its XML file!! (stt exists: False)
Skipping document 46/281 with OID {C312A18C-B9C9-462E-88BA-51A7A401B551} because it's missing its XML file!! (stt exists: False)
Skipping document 47/281 with OID {02322222-2B72-4CF3-B53D-A146968E4EB3} because it's missing its XML file!! (stt exists: False)
Skipping document 49/281 with OID {26ABEADB-1089-4FE6-B90F-57FD3E8C4535} because it's missing its XML file!! (stt exists: False)
Skipping document 50/281 with OID {72139D97-CB92-4BC3-877C-FDA3B1909893} because it's missing its XML file!! (stt exists: False)
Skipping document 51/281 with OID {7FA32AEB-29E8-4EEA-9321-C5C0309A780B} because it's missing its XML file!! (stt exists: False)
Skipping document 52/281 with OID {2C2C389A-909C-44BF-B33D-F09A689C7DB1} because it's missing its XML file!! (stt exists: False)
Skipping document 53/281 with OID {8A9D43D4-64C2-4711-9402-74AB6C8627BF} because it's missing its XML file!! (stt exists: False)
Skipping document 54/281 with OID {112FFDA5-256B-4F8A-B794-BDFDAEFF3D1B} because it's missing its XML file!! (stt exists: False)
Skipping document 56/281 with OID {48A505FF-BEFD-4A15-96EB-217559EB83FB} because it's missing its XML file!! (stt exists: False)
Skipping document 57/281 with OID {C0D9BCA2-28F2-4122-BF1B-07656F7A9232} because it's missing its XML file!! (stt exists: False)
Skipping document 58/281 with OID {668DEFB7-DCC8-4983-8DC3-910D943D6589} because it's missing its XML file!! (stt exists: False)
Skipping document 60/281 with OID {64DA6318-C1C7-4721-A295-9B6C045B5C99} because it's missing its XML file!! (stt exists: False)
Skipping document 61/281 with OID {BC30669A-8C55-4C17-A731-4445B0284C7F} because it's missing its XML file!! (stt exists: False)
Skipping document 63/281 with OID {0AA91E42-B935-484E-9889-246E1BB3BB07} because it's missing its XML file!! (stt exists: False)
Skipping document 64/281 with OID {74170604-7AD3-4F74-8297-63E7C4F3F707} because it's missing its XML file!! (stt exists: False)
Skipping document 67/281 with OID {A98F3BB0-ACB2-4691-9B46-173B0436DA0E} because it's missing its XML file!! (stt exists: False)
Skipping document 68/281 with OID {5B2F8288-4DED-41BD-8486-1D2A8300F85B} because it's missing its XML file!! (stt exists: False)
Skipping document 71/281 with OID {8014E80F-E702-4778-92A6-8EE43FCBE276} because it's missing its XML file!! (stt exists: False)
Skipping document 72/281 with OID {1CD6DE4B-B4F3-4C69-B078-0061CED5C41A} because it's missing its XML file!! (stt exists: False)
Skipping document 73/281 with OID {9852CAF3-62DE-46D8-A935-EDF454A56205} because it's missing its XML file!! (stt exists: False)
Skipping document 76/281 with OID {2747F79D-61C4-4EFA-8DA4-154B93D909E2} because it's missing its XML file!! (stt exists: False)
Skipping document 77/281 with OID {95CFE7E9-F422-426E-A4A8-A24876305AFC} because it's missing its XML file!! (stt exists: False)
Skipping document 78/281 with OID {4C04800B-B959-4807-8BD7-2C68D8B7268F} because it's missing its XML file!! (stt exists: False)
Skipping document 79/281 with OID {3BC79A37-21AB-4D2A-95B2-BE16DF56A8BE} because it's missing its XML file!! (stt exists: False)
Skipping document 80/281 with OID {2F9B8B74-0B0B-45F2-A262-643753934FA3} because it's missing its XML file!! (stt exists: False)
Skipping document 81/281 with OID {CC9B2A28-D40B-45CF-870C-36430F0F7CD1} because it's missing its XML file!! (stt exists: False)
Skipping document 82/281 with OID {4F432CC1-44C8-4D55-AA23-4A4AC533E7AA} because it's missing its XML file!! (stt exists: False)
Skipping document 83/281 with OID {08C9CC63-495F-45F8-A633-F95892A9A868} because it's missing its XML file!! (stt exists: False)
Skipping document 84/281 with OID {3E54258A-A1A9-43AC-8067-33C43AA777AA} because it's missing its XML file!! (stt exists: False)
Skipping document 85/281 with OID {934453DA-D940-4037-AE82-D54F007A2810} because it's missing its XML file!! (stt exists: False)
Skipping document 86/281 with OID {62C8A228-F52B-4098-BFAE-DDE0AA572FD3} because it's missing its XML file!! (stt exists: False)
Skipping document 87/281 with OID {4284538E-1E20-4C00-A97B-E9F6B5A38AA4} because it's missing its XML file!! (stt exists: False)
Skipping document 88/281 with OID {88137E76-8EF0-4F5C-848C-ACB9D8531EFF} because it's missing its XML file!! (stt exists: False)
Skipping document 89/281 with OID {1CB3B8DD-EC44-409D-A28D-512EC5180D37} because it's missing its XML file!! (stt exists: False)
Skipping document 92/281 with OID {9859F075-C6A2-4E46-821C-E51FCBBE5686} because it's missing its XML file!! (stt exists: False)
Skipping document 93/281 with OID {C16F5A53-1364-4CAD-9D51-12CF5287AAAA} because it's missing its XML file!! (stt exists: False)
Skipping document 94/281 with OID {994DA595-1490-427C-B0CF-F60E3E73AD38} because it's missing its XML file!! (stt exists: False)
Skipping document 95/281 with OID {EF4D9AFA-E414-4F88-9C41-5CD28AE8F224} because it's missing its XML file!! (stt exists: False)
Skipping document 96/281 with OID {D5102A57-465C-493F-B876-8BDC24526245} because it's missing its XML file!! (stt exists: False)
Skipping document 97/281 with OID {B95D161F-1E4D-45F9-8171-D6C6D0FE39F2} because it's missing its XML file!! (stt exists: False)
Skipping document 98/281 with OID {1417C476-A35E-4E83-BC4F-9C7718F1BDA6} because it's missing its XML file!! (stt exists: False)
Skipping document 99/281 with OID {C453F6BA-8CC4-4BF3-99A3-6F53A4B13A0D} because it's missing its XML file!! (stt exists: False)
Skipping document 101/281 with OID {E82F0269-5D72-4A56-B259-C93B569ACF8E} because it's missing its XML file!! (stt exists: False)
Skipping document 103/281 with OID {C29A1A44-7B90-48D3-B591-C6A5BE845A97} because it's missing its XML file!! (stt exists: False)
Skipping document 104/281 with OID {A35E815D-8F33-4C9C-9710-2B32E9DC99B5} because it's missing its XML file!! (stt exists: False)
Skipping document 105/281 with OID {29DE6B3E-ADF1-4F4D-8081-FB1356AAB773} because it's missing its XML file!! (stt exists: False)
Skipping document 106/281 with OID {59260B94-9945-44B7-8796-D4381A0EAB12} because it's missing its XML file!! (stt exists: False)
Skipping document 107/281 with OID {9403C03F-5C71-4810-887E-382503EB09AD} because it's missing its XML file!! (stt exists: False)
Skipping document 109/281 with OID {978D3CE8-C3DC-4E6C-A52C-F58B9DE860EA} because it's missing its XML file!! (stt exists: False)
Skipping document 111/281 with OID {7B4598B6-7ABA-40A7-8767-89CE5F577225} because it's missing its XML file!! (stt exists: False)
Skipping document 112/281 with OID {B5F42368-B51B-4461-91BE-8367C9193FBB} because it's missing its XML file!! (stt exists: False)
Skipping document 113/281 with OID {23109675-4A28-48A0-80B6-7CE0BCCF4DEC} because it's missing its XML file!! (stt exists: False)
Skipping document 114/281 with OID {815B8B17-D663-472A-890E-B8EA0CD85FE4} because it's missing its XML file!! (stt exists: False)
Skipping document 116/281 with OID {C59D30B8-73AD-43A9-B092-B4A0A0DE9A5B} because it's missing its XML file!! (stt exists: False)
Skipping document 117/281 with OID {1C30F627-BB25-4A64-AB62-D2AD75BEA140} because it's missing its XML file!! (stt exists: False)
Skipping document 118/281 with OID {6783B896-B696-4505-97EF-CE5A97745135} because it's missing its XML file!! (stt exists: False)
Skipping document 119/281 with OID {9A920F1A-A2C5-4B70-A6D6-55C5CD2ABCD0} because it's missing its XML file!! (stt exists: False)
Skipping document 120/281 with OID {E054CC97-7764-493E-A67E-127F976AD71D} because it's missing its XML file!! (stt exists: False)
Skipping document 121/281 with OID {39976458-7EBD-4390-AFF6-FB7DA5B65B88} because it's missing its XML file!! (stt exists: False)
Skipping document 122/281 with OID {8990B9E8-57AB-4F2D-BBBC-B9C4E4B3B343} because it's missing its XML file!! (stt exists: False)
Skipping document 123/281 with OID {E9DF0AE6-216A-4828-81B6-C12996C19B2F} because it's missing its XML file!! (stt exists: False)
Skipping document 124/281 with OID {B5E194D7-177E-4850-9E6D-5F3B4396401E} because it's missing its XML file!! (stt exists: False)
Skipping document 125/281 with OID {49C04C54-52EB-4ABA-94AA-99AB7B562EBE} because it's missing its XML file!! (stt exists: False)
Skipping document 127/281 with OID {4A9BC083-EBDE-4086-BDBC-2D379CB3DE36} because it's missing its XML file!! (stt exists: False)
Skipping document 129/281 with OID {70D1AB8F-F732-4F11-B3F1-DE6D49EB67AB} because it's missing its XML file!! (stt exists: False)
Skipping document 130/281 with OID {412589D3-CB61-4963-9D51-40DE7BB62383} because it's missing its XML file!! (stt exists: False)
Skipping document 131/281 with OID {043BC60E-621C-4746-A560-72F0F08640D7} because it's missing its XML file!! (stt exists: False)
Skipping document 132/281 with OID {3A618E7F-569D-41AA-8FEC-167CAA11A768} because it's missing its XML file!! (stt exists: False)
Skipping document 134/281 with OID {A080CDBA-03C3-4BAD-813D-46DAC944B168} because it's missing its XML file!! (stt exists: False)
Skipping document 135/281 with OID {F890B4B5-94FE-4E5D-BF5B-7453CC176009} because it's missing its XML file!! (stt exists: False)
Skipping document 136/281 with OID {F6480E2B-6EB2-41B9-AA1F-7C2F2D3032E7} because it's missing its XML file!! (stt exists: False)
Skipping document 137/281 with OID {A3DB28A6-0A44-4293-9671-60DFD9406D8D} because it's missing its XML file!! (stt exists: False)
Skipping document 139/281 with OID {F7F86BFD-DFBA-4D95-8862-B2010913EEBE} because it's missing its XML file!! (stt exists: False)
Skipping document 140/281 with OID {BC93F131-FD49-449D-804B-E1EEA8A9AAB4} because it's missing its XML file!! (stt exists: False)
Skipping document 142/281 with OID {31A45088-DCA0-4327-A6AD-BBFB7247FA9A} because it's missing its XML file!! (stt exists: False)
Skipping document 143/281 with OID {A2B87688-D2A0-4815-8EA5-6A8A17DCF84A} because it's missing its XML file!! (stt exists: False)
Skipping document 144/281 with OID {25417B7F-6E49-4CA4-B724-C6D782CABFD2} because it's missing its XML file!! (stt exists: False)
Skipping document 145/281 with OID {062AAC88-2604-4F02-B5AC-79A2ED439FC5} because it's missing its XML file!! (stt exists: False)
Skipping document 146/281 with OID {D2BDAAA1-F715-4088-8E5A-E53C8118A3BB} because it's missing its XML file!! (stt exists: False)
Skipping document 148/281 with OID {B3E9B1C9-B266-4CC5-880E-6A811C73F35A} because it's missing its XML file!! (stt exists: False)
Skipping document 149/281 with OID {85BD270A-D2AC-4543-939B-C29DB26B8DF1} because it's missing its XML file!! (stt exists: False)
Skipping document 150/281 with OID {20758930-6251-42C9-8CB7-440D66FB7C9E} because it's missing its XML file!! (stt exists: False)
Skipping document 151/281 with OID {B6847669-68E3-4019-BC4F-21A088B562BE} because it's missing its XML file!! (stt exists: False)
Skipping document 152/281 with OID {F8B81816-CF6E-4F70-9C4D-105C4E63654F} because it's missing its XML file!! (stt exists: False)
Skipping document 153/281 with OID {D67A63EA-DC0E-4C4D-9D48-D6043F42534C} because it's missing its XML file!! (stt exists: False)
Skipping document 154/281 with OID {20E99A45-1EC1-41F3-89ED-848811228E18} because it's missing its XML file!! (stt exists: False)
Skipping document 155/281 with OID {6D93D322-F950-405F-AC78-AB65841045CE} because it's missing its XML file!! (stt exists: False)
Skipping document 156/281 with OID {AF711A5D-D5E2-439D-96E4-B661C079D7AF} because it's missing its XML file!! (stt exists: False)
Skipping document 158/281 with OID {16BBF56E-35CF-41F7-B37E-B04D7B6D7B2B} because it's missing its XML file!! (stt exists: False)
Skipping document 159/281 with OID {1E5BBBA2-429B-443F-97C4-8C07BA95A5DF} because it's missing its XML file!! (stt exists: False)
Skipping document 160/281 with OID {E262AE65-0328-4DAC-9FE7-454B9254D386} because it's missing its XML file!! (stt exists: False)
Skipping document 161/281 with OID {8E74324D-E9C9-439D-80AC-3E5009A722B3} because it's missing its XML file!! (stt exists: False)
Skipping document 162/281 with OID {933F9B01-E228-4EB5-961F-8E9BC2B5AA6A} because it's missing its XML file!! (stt exists: False)
Skipping document 165/281 with OID {79F90767-FB64-4655-B2FD-AEAEE7104873} because it's missing its XML file!! (stt exists: False)
Skipping document 166/281 with OID {693F187D-93EE-490F-9224-E34AA10AEA50} because it's missing its XML file!! (stt exists: False)
Skipping document 167/281 with OID {F209DC87-0D9C-40C9-AB9F-2E425911C3A0} because it's missing its XML file!! (stt exists: False)
Skipping document 168/281 with OID {18E4815A-886E-4351-AB0C-016E22D522A8} because it's missing its XML file!! (stt exists: False)
Skipping document 169/281 with OID {531ED394-FBC2-4854-8396-F1829A212D82} because it's missing its XML file!! (stt exists: False)
Skipping document 170/281 with OID {15AE8377-4688-40F8-A6C2-DDBD314975B4} because it's missing its XML file!! (stt exists: False)
Skipping document 171/281 with OID {110EA0F3-28DD-4B8E-8ED2-69D296242B0F} because it's missing its XML file!! (stt exists: False)
Skipping document 172/281 with OID {8E3CFCFA-36D2-4A03-B079-054C4AB33B70} because it's missing its XML file!! (stt exists: False)
Skipping document 173/281 with OID {66F4C947-5702-4E2F-84AB-F61BA5B5C299} because it's missing its XML file!! (stt exists: False)

100%|██████████| 1/1 [00:01<00:00,  1.09s/it]
46it [02:47,  2.34s/it]

Skipping document 174/281 with OID {702CC5AB-8731-4188-AED1-686E0BEE217D} because it's missing its XML file!! (stt exists: False)
Skipping document 175/281 with OID {7A1F7137-B21C-4CB4-8ABE-3BE384EA0B2C} because it's missing its XML file!! (stt exists: False)
Skipping document 176/281 with OID {C084D9F6-7DF0-4EF2-A09C-E461C2CFB8A5} because it's missing its XML file!! (stt exists: False)
Skipping document 177/281 with OID {B126E6B2-F0FD-406D-9F58-8D055001D2C2} because it's missing its XML file!! (stt exists: False)
Skipping document 178/281 with OID {98167841-9284-4134-8ABB-FB82539D6507} because it's missing its XML file!! (stt exists: False)
Skipping document 179/281 with OID {5E43F5D7-78E1-4D45-BB46-5ED763B522BA} because it's missing its XML file!! (stt exists: False)
Skipping document 180/281 with OID {ACCA77DB-3930-4961-8B09-7E094FE9B8DB} because it's missing its XML file!! (stt exists: False)
Skipping document 182/281 with OID {1A917B8A-F511-41C4-8ECD-BC2776AB31CA} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {60401CC8-A9A2-427C-A7AA-FFC39051FC36}. Trying to use the recording date. doc_dict: {'alias': 'vie_monde', 'date_str': None, 'stt_filename': '60401CC8-A9A2-427C-A7AA-FFC39051FC36_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{60401CC8-A9A2-427C-A7AA-FFC39051FC36}', 'stripped_OID': '60401CC8-A9A2-427C-A7AA-FFC39051FC36', 'login': '', 'broadcast_episode_title': 'Emission du 27.2.1953', 'sequence': '1', 'broadcast_program_name': 'Vingt-quatre heures de la vie du monde', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'Fonsart', 'modified_on': '02.06.2022 18:51:12', 'physical_support_history': "Cote d'origine: 6417", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': None, 'series_title': None, 'content_summary': None, 'workflow_status': 'Accept?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': None, 'radio_channels': None, 'subdomains': None, 'recording_dates': ['12/04/1968 - 12/04/1968'], 'first_broadcast_dates': None}
Skipping document 184/281 with OID {B1E51BD3-B7F8-444C-99E0-E363165F61F6} because it's missing its XML file!! (stt exists: False)
Skipping document 185/281 with OID {974C93DA-0D39-40CF-98DF-6CFE576CCD7E} because it's missing its XML file!! (stt exists: False)
Skipping document 186/281 with OID {E27D2CF4-338E-4091-AF54-7D1CBEF0F56B} because it's missing its XML file!! (stt exists: False)
Skipping document 187/281 with OID {3AD60C8D-9D1E-4580-8844-A8F91CC4662D} because it's missing its XML file!! (stt exists: False)
Skipping document 189/281 with OID {4EB84E27-8013-4BA5-8C6B-B37F5B4A5258} because it's missing its XML file!! (stt exists: False)
Skipping document 193/281 with OID {C173D124-1A4B-436B-ABB9-6EFBA0DFED47} because it's missing its XML file!! (stt exists: False)
Skipping document 194/281 with OID {0840C4A3-9086-4626-B934-E3EC63941237} because it's missing its XML file!! (stt exists: False)
Skipping document 196/281 with OID {6102F2BB-ED90-4528-9189-63AD50D4BBEB} because it's missing its XML file!! (stt exists: False)
Skipping document 199/281 with OID {C7A192F4-F5D8-42C9-B66F-6508B02C6F1E} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {F67428ED-306C-4858-92F7-2478B2ED860A}. Trying to use the recording date. doc_dict: {'alias': 'vie_monde', 'date_str': None, 'stt_filename': 'F67428ED-306C-4858-92F7-2478B2ED860A_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{F67428ED-306C-4858-92F7-2478B2ED860A}', 'stripped_OID': 'F67428ED-306C-4858-92F7-2478B2ED860A', 'login': '', 'broadcast_episode_title': 'Emission du 3 avril 1968', 'sequence': '1', 'broadcast_program_name': 'Vingt-quatre heures de la vie du monde', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '02.06.2022 22:24:25', 'physical_support_history': "Cote d'origine:  6973", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': None, 'workflow_status': 'Valid?', 'assembly_status': 'Brut', 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'geographical_descriptors': ['France'], 'person_descriptors': ['Pompidou, Georges', 'RTF'], 'thematical_descriptors': ['politique', 'communisme', 'parti politique', 'presse', 'publicit?', 't?l?vision'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Deuxi?me programme'], 'subdomains': ['Commentaire'], 'recording_dates': ['03/04/1968 - 03/04/1968'], 'first_broadcast_dates': None}
Skipping document 203/281 with OID {D45968BB-5A45-48B9-AF9F-A515FAFFA7AC} because it's missing its XML file!! (stt exists: False)
Skipping document 204/281 with OID {5904F2BA-2BBA-4503-9657-B3C5EFD11D99} because it's missing its XML file!! (stt exists: False)
Skipping document 205/281 with OID {4A54E7E3-06A3-473C-A2D1-EE9D9B6B8C07} because it's missing its XML file!! (stt exists: False)
Skipping document 206/281 with OID {7DE4A17F-8E44-4E53-8660-C917F835FDF3} because it's missing its XML file!! (stt exists: False)
Skipping document 207/281 with OID {55D2C294-C2FE-4BA3-96FA-147BC81D9DE2} because it's missing its XML file!! (stt exists: False)
Skipping document 208/281 with OID {B28F2F4B-9463-4A61-9F76-264EBE6914CE} because it's missing its XML file!! (stt exists: False)
Skipping document 210/281 with OID {A3E1E7F1-552C-4DC2-9551-1D5EEE3D7027} because it's missing its XML file!! (stt exists: False)
Skipping document 211/281 with OID {B6A7AE99-FAAE-45EF-BEDF-E88620505E52} because it's missing its XML file!! (stt exists: False)
Skipping document 212/281 with OID {332753F9-A2CB-4BA8-8793-EDF299002016} because it's missing its XML file!! (stt exists: False)
Skipping document 213/281 with OID {2AFC5EE5-10E6-4211-9E7D-C8C631F180E0} because it's missing its XML file!! (stt exists: False)
Skipping document 214/281 with OID {559EEDA3-46F1-4070-8DA0-9495CF9445CB} because it's missing its XML file!! (stt exists: False)
Skipping document 215/281 with OID {4F6FD163-DCD4-415D-8EFC-A93675AC40D9} because it's missing its XML file!! (stt exists: False)
Skipping document 216/281 with OID {1D52AAD7-A306-455B-8F5A-5D5694CCDAB3} because it's missing its XML file!! (stt exists: False)
Skipping document 217/281 with OID {543CD455-2975-4883-84B8-69804BCC0270} because it's missing its XML file!! (stt exists: False)
Skipping document 218/281 with OID {36B8F454-98A9-4830-B062-DF480CDAB35C} because it's missing its XML file!! (stt exists: False)
Skipping document 222/281 with OID {AF9582D4-3B77-4A8D-BFCD-073961965577} because it's missing its XML file!! (stt exists: False)
Skipping document 223/281 with OID {3C2405AF-1B2F-42F4-BD76-30CDED6F77ED} because it's missing its XML file!! (stt exists: False)
Skipping document 224/281 with OID {BCD265D3-8445-4F12-95C9-5EFB01E6253B} because it's missing its XML file!! (stt exists: False)
Skipping document 226/281 with OID {ED87129B-3BA6-4EED-9F3F-ECB070057D55} because it's missing its XML file!! (stt exists: False)
Skipping document 227/281 with OID {1E37B7F3-1162-421C-8309-B6C81470DB15} because it's missing its XML file!! (stt exists: False)
Skipping document 229/281 with OID {A6036E26-DEBE-4465-B7CB-D08F1CF327DD} because it's missing its XML file!! (stt exists: False)
Skipping document 230/281 with OID {C6D8CD3B-3982-4814-B73B-ADADFF8D3B66} because it's missing its XML file!! (stt exists: False)
Skipping document 231/281 with OID {5A3EDB34-AEC9-4172-8AB7-356E28447BAB} because it's missing its XML file!! (stt exists: False)
Skipping document 232/281 with OID {D234316F-6A56-4CB4-AF61-4138EFFC30AA} because it's missing its XML file!! (stt exists: False)
Skipping document 233/281 with OID {841C7F23-E6DD-40EB-A3CC-DED5B22651F0} because it's missing its XML file!! (stt exists: False)
Skipping document 234/281 with OID {AE66FAED-11CA-4F75-A46E-7D76FE9C266F} because it's missing its XML file!! (stt exists: False)
Skipping document 235/281 with OID {C793362E-0055-4EC0-8B39-A3DD7F644C91} because it's missing its XML file!! (stt exists: False)
Skipping document 236/281 with OID {AA00157C-4776-433A-9F73-E2D02B241D6F} because it's missing its XML file!! (stt exists: False)
Skipping document 238/281 with OID {D3199546-4DBD-4E27-BFEF-359165774BAC} because it's missing its XML file!! (stt exists: False)
Skipping document 239/281 with OID {0D4ABF93-2A6E-4251-AA0D-B93310CE413C} because it's missing its XML file!! (stt exists: False)
Skipping document 240/281 with OID {4F51D480-3FFB-4675-87F0-BA6AA5768C43} because it's missing its XML file!! (stt exists: False)
Skipping document 241/281 with OID {B4AC217D-B598-42E7-9D2B-5E52E7B31998} because it's missing its XML file!! (stt exists: False)
Skipping document 242/281 with OID {1620F6DD-2368-4125-B94B-ED97C27D12B1} because it's missing its XML file!! (stt exists: False)
Skipping document 243/281 with OID {8A6E9F7F-3E83-4D01-9364-4C4B3FAEBC5E} because it's missing its XML file!! (stt exists: False)
Skipping document 244/281 with OID {2A4AD0DE-1779-4922-A210-5C2F10749E42} because it's missing its XML file!! (stt exists: False)
Skipping document 245/281 with OID {274D1BBE-CD37-4DA0-9524-DBC6D90777D5} because it's missing its XML file!! (stt exists: False)
Skipping document 246/281 with OID {AF8F0657-6463-4B3C-B6EE-28FBBE7CF858} because it's missing its XML file!! (stt exists: False)
Skipping document 247/281 with OID {DD80674D-99A4-4CFD-80F5-5D52A65B3398} because it's missing its XML file!! (stt exists: False)
Skipping document 248/281 with OID {A505BDEE-1DAD-4715-909A-08A3C134F3BA} because it's missing its XML file!! (stt exists: False)
Skipping document 249/281 with OID {F4054D9A-89B7-4804-8983-0FC2FAACE8CC} because it's missing its XML file!! (stt exists: False)
Skipping document 252/281 with OID {831816DE-BF89-4A7F-A138-47CBDA0C90AA} because it's missing its XML file!! (stt exists: False)
Skipping document 253/281 with OID {51FB90B7-8C1C-46EE-8069-1DE302F8B063} because it's missing its XML file!! (stt exists: False)
Skipping document 254/281 with OID {623EE279-3FFE-436F-80D3-7682276BC9B5} because it's missing its XML file!! (stt exists: False)
Skipping document 255/281 with OID {1D9B398F-364A-4611-8F84-E61CF6B83BEA} because it's missing its XML file!! (stt exists: False)
Skipping document 256/281 with OID {2E1224D3-410D-48EF-A190-103A39FDB285} because it's missing its XML file!! (stt exists: False)
Skipping document 257/281 with OID {95A0C4A4-ACCD-45CE-B1B7-955ECFC6771B} because it's missing its XML file!! (stt exists: False)
Skipping document 258/281 with OID {D87D9541-D893-440B-BEA2-9E8F1F444EF0} because it's missing its XML file!! (stt exists: False)
Skipping document 259/281 with OID {9F82D6DC-5BAD-4FC3-B3E7-308D4D27BA02} because it's missing its XML file!! (stt exists: False)
Skipping document 261/281 with OID {1868B2A6-F26E-49C7-9D3D-9E745BA17D1A} because it's missing its XML file!! (stt exists: False)
Skipping document 263/281 with OID {5EA4B11C-0039-492F-AE2C-E2FEB2D4386B} because it's missing its XML file!! (stt exists: False)
Skipping document 264/281 with OID {CDFD2719-632C-4AB9-B8FE-9D8E65BB6802} because it's missing its XML file!! (stt exists: False)
Skipping document 265/281 with OID {F2E4CDFB-F6D3-4371-AA0A-A3834E74D355} because it's missing its XML file!! (stt exists: False)
Skipping document 267/281 with OID {34BBED54-A8E3-4736-B012-7557BDE61FD3} because it's missing its XML file!! (stt exists: False)
Skipping document 268/281 with OID {7C497D3B-6AB9-48C9-A749-CE915E027DC2} because it's missing its XML file!! (stt exists: False)
Skipping document 269/281 with OID {155E6334-3E93-4235-9D47-7B89CEE64CB4} because it's missing its XML file!! (stt exists: False)
Skipping document 270/281 with OID {95DF1A78-C0FB-4664-A78C-57E5F163A3BB} because it's missing its XML file!! (stt exists: False)
Skipping document 273/281 with OID {73718154-72CD-496E-88D4-B020B892E7CA} because it's missing its XML file!! (stt exists: False)
Skipping document 276/281 with OID {A293D231-AF7C-40AB-8086-29A4C0ADB9DE} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {7956DB3F-CB65-46D8-BB81-4FAD0A5B1D65}. Trying to use the recording date. doc_dict: {'alias': 'vie_monde', 'date_str': None, 'stt_filename': '7956DB3F-CB65-46D8-BB81-4FAD0A5B1D65_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{7956DB3F-CB65-46D8-BB81-4FAD0A5B1D65}', 'stripped_OID': '7956DB3F-CB65-46D8-BB81-4FAD0A5B1D65', 'login': '', 'broadcast_episode_title': "Reportage sur l'arriv?e en Corse de Michel Cacciaguerra, adjudant-chef, fait prisonnier au Sahara occidental par l'arm?e de lib?ratrion depuis le 15.02.1957", 'sequence': '1', 'broadcast_program_name': 'Vingt-quatre heures de la vie du monde', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'prongudo', 'modified_on': '22.07.2022 11:34:28', 'physical_support_history': "Cote d'origine: A 158", 'production_type': 'Production propre', 'recording_place': 'Corse', 'rights_notes': 'Memoriav', 'rights_status': 'Clarifi?', 'series_title': "Sauvegarde d'archives", 'content_summary': 'Moulay Hassan, prince marocain, est intervenu pour sa lib?ration.', 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:03:10.897', 'work_duration_compl': 'Non', 'participants': [{'name': 'Inconnu', 'function': "Auteur d'une d?claration", 'role': 'pr?fet de Corse'}, {'name': 'Inconnu', 'function': 'Commentateur/trice', 'role': 'reporter'}, {'name': 'Cacciaguerra, Michel', 'function': 'Interview?/e', 'role': 'adjudant-chef'}, {'name': 'Inconnu', 'function': 'Intervieweur/euse', 'role': 'reporter'}], 'geographical_descriptors': ['Sahara occidental', 'Maroc', 'France'], 'person_descriptors': None, 'thematical_descriptors': ['enl?vement', 'crise politique', 'd?colonisation', 'ind?pendantisme'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Deuxi?me programme'], 'subdomains': ['Reportage'], 'recording_dates': ['19/02/1959 - 19/02/1959'], 'first_broadcast_dates': None}
Skipping document 280/281 with OID {88EAAD4A-763E-45FB-A242-50436BE7B45B} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {1287EAA7-4929-439C-B29C-DC89B8F27D60}. Trying to use the recording date. doc_dict: {'alias': 'vie_monde', 'date_str': None, 'stt_filename': '1287EAA7-4929-439C-B29C-DC89B8F27D60_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{1287EAA7-4929-439C-B29C-DC89B8F27D60}', 'stripped_OID': '1287EAA7-4929-439C-B29C-DC89B8F27D60', 'login': '', 'broadcast_episode_title': 'Vingt-quatre heures de la vie du monde', 'sequence': '1', 'broadcast_program_name': 'Vingt-quatre heures de la vie du monde', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'suillojo', 'modified_on': '16.07.2023 15:44:29', 'physical_support_history': None, 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': None, 'series_title': None, 'content_summary': None, 'workflow_status': 'Accept?', 'assembly_status': None, 'live': 'Non live', 'modulation_type': 'St?r?o', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'geographical_descriptors': None, 'person_descriptors': None, 'thematical_descriptors': None, 'rights_usage_possibilities': None, 'radio_channels': ['Deuxi?me programme'], 'subdomains': None, 'recording_dates': ['14/11/1968 - 14/11/1968'], 'first_broadcast_dates': None}
vie_monde - returning 78 documents, 203 were skipped due to missing necessary info.
 --> Adding 78 to the out csv for vie_monde

PROCESSING PROGRAM vie_va (47/47) - 1 files:

Starting extracting 295 documents for program vie_va
Skipping document 2/295 with OID {E77A33B9-F6E7-4110-A5FE-BE2BB93EBD22} because it's missing its XML file!! (stt exists: False)
Skipping document 3/295 with OID {9AC3A303-77E8-4127-9BE0-CC45935A7540} because it's missing its XML file!! (stt exists: False)
Skipping document 4/295 with OID {7B2B089A-C736-47E6-8BF0-63C8B8309363} because it's missing its XML file!! (stt exists: False)
Skipping document 5/295 with OID {FDE71322-57FA-4D9D-93FD-170155D065FC} because it's missing its XML file!! (stt exists: False)
Skipping document 6/295 with OID {1145C635-C7C5-4B28-94A7-AA61C72E4E78} because it's missing its XML file!! (stt exists: False)
Skipping document 7/295 with OID {A0C7D77E-205E-456F-ABC5-EEFAB87B8EC4} because it's missing its XML file!! (stt exists: False)
Skipping document 8/295 with OID {82FFEEF2-09FC-4B91-9C08-36595828A9DE} because it's missing its XML file!! (stt exists: False)
Skipping document 9/295 with OID {5633B243-30A9-4E48-893B-17FB5269A8F3} because it's missing its XML file!! (stt exists: False)
Skipping document 10/295 with OID {A77F534B-537D-47DD-8D0F-83E0CE05254B} because it's missing its XML file!! (stt exists: False)
Skipping document 11/295 with OID {5319D4DE-8250-4562-9811-AB5325E44EDA} because it's missing its XML file!! (stt exists: False)
Skipping document 12/295 with OID {24B2651F-A246-4D54-8C9B-DB6D1E764802} because it's missing its XML file!! (stt exists: False)
Skipping document 13/295 with OID {39384DA4-6998-4A60-B644-3748A4BC197F} because it's missing its XML file!! (stt exists: False)
Skipping document 14/295 with OID {AF933F64-43DE-4A7E-A1E2-DBE29B4243A6} because it's missing its XML file!! (stt exists: False)
Skipping document 15/295 with OID {1A82412A-C071-46CB-AD19-C1AB04A27063} because it's missing its XML file!! (stt exists: False)
Skipping document 16/295 with OID {ECEB778E-6D1D-4317-90DE-45B7CE403084} because it's missing its XML file!! (stt exists: False)
Skipping document 17/295 with OID {B968DEA5-8F91-4ACF-B8EA-68EF560E4980} because it's missing its XML file!! (stt exists: False)
Did not find any date for doc with OID {9D773331-7159-4431-9B20-F3F83757A07C}. Trying to use the recording date. doc_dict: {'alias': 'vie_va', 'date_str': None, 'stt_filename': '9D773331-7159-4431-9B20-F3F83757A07C_STT.xml', 'mp3_filenames': None, 'cls_ID': '{D2593F4E-C887-4E48-8982-5BD08BA4DAE0}', 'OID': '{9D773331-7159-4431-9B20-F3F83757A07C}', 'stripped_OID': '9D773331-7159-4431-9B20-F3F83757A07C', 'login': '', 'broadcast_episode_title': '1. Comm?moration du 125e anniversaire de la clinique de la Source ? Lausanne. - 2. Formation professionnelle et ?conomie. - 3. Emission concours de Michel D?n?riaz', 'sequence': '1', 'broadcast_program_name': 'Vie qui va', 'document_type': 'Parl?', 'hierarchy_level': 'Sujet', 'modified_by': 'colombis', 'modified_on': '29.05.2022 03:51:19', 'physical_support_history': "Cote d'origine: 25006", 'production_type': 'Production propre', 'recording_place': None, 'rights_notes': None, 'rights_status': 'Clarifi?', 'series_title': None, 'content_summary': "Le d?roulement d'une op?ration ? la fin du 19e si?cle. Les exigences de l'?cole de la Source. Programme de la journ?e festive. (16:43 - 24:34) Formation professionnelle et ?conomie. (24:40) Michel D?n?riaz.", 'workflow_status': 'Valid?', 'assembly_status': 'Mont?', 'live': 'Non live', 'modulation_type': 'Mono', 'work_duration': '00:00:00.000', 'work_duration_compl': 'Non', 'participants': [{'name': 'Buffat, Jean-David', 'function': 'Interview?/e', 'role': 'pr?sident de la Source, m?decin'}, {'name': 'Boyer, Micheline', 'function': 'Interview?/e', 'role': 'directrice de la Source'}, {'name': 'Manzi, Emmanuel', 'function': 'Intervieweur/euse', 'role': 'collaborateur RSR'}, {'name': 'Beuchat, Roger', 'function': 'Interview?/e', 'role': "chef du service de la formation professionnelle et de l'orientation professionnelle de Gen?ve"}, {'name': 'Robert, Jacques', 'function': 'Interview?/e', 'role': 'secr?taire syndical de la FOBB'}], 'geographical_descriptors': ['Lausanne'], 'person_descriptors': ['Gasparin, Val?rie de', 'Gasparin, Ag?nor de'], 'thematical_descriptors': ['h?pital', 'infirmier', 'clinique', 'formation', 'informatique', 'apprentissage professionnel', 'technologie', 'subvention'], 'rights_usage_possibilities': ['Tous'], 'radio_channels': ['Radio-Gen?ve'], 'subdomains': ['Interview', 'Jeu radiophonique'], 'recording_dates': ['20/06/1984 - 20/06/1984'], 'first_broadcast_dates': None}
Skipping document 19/295 with OID {A69873BA-1E3A-425F-8667-A08539010C38} because it's missing its XML file!! (stt exists: False)
Skipping document 20/295 with OID {F8D44023-2119-4F3E-8EA1-423C45CFC35A} because it's missing its XML file!! (stt exists: False)
Skipping document 21/295 with OID {6E5FAFE6-C180-471B-9263-4CF79E12BB22} because it's missing its XML file!! (stt exists: False)
Skipping document 22/295 with OID {A57B3139-ECD7-4F69-9CE1-4B4C68C3C86A} because it's missing its XML file!! (stt exists: False)
Skipping document 26/295 with OID {1700C476-7F10-4E3D-86DA-F9BC8D672A66} because it's missing its XML file!! (stt exists: False)
Skipping document 31/295 with OID {EE54B4D9-957F-4BBB-87B6-61D3861A9092} because it's missing its XML file!! (stt exists: False)
Skipping document 37/295 with OID {EB93AE7D-A69E-43C9-828C-4F9BA7C55FAA} because it's missing its XML file!! (stt exists: False)
Skipping document 39/295 with OID {E4B1B229-5309-4E43-A7B9-AE21F7E71533} because it's missing its XML file!! (stt exists: False)
Skipping document 42/295 with OID {D8366B9A-14E4-4F91-9D3B-43802E5984C0} because it's missing its XML file!! (stt exists: False)
Skipping document 46/295 with OID {ADFF6CA8-DF00-4E51-A860-23857769F4F8} because it's missing its XML file!! (stt exists: False)
Skipping document 47/295 with OID {1D5258BB-342C-4B07-832E-61BF52D105FD} because it's missing its XML file!! (stt exists: False)
Skipping document 48/295 with OID {E5BAB9BC-46CF-4065-ABF8-8AB44D063BB4} because it's missing its XML file!! (stt exists: False)
Skipping document 63/295 with OID {AF150DB2-9056-4EB7-B58B-5C541E01DA65} because it's missing its XML file!! (stt exists: False)
Skipping document 65/295 with OID {E36ECCE4-2871-4A66-B6D1-FA63DBD65792} because it's missing its XML file!! (stt exists: False)
Skipping document 66/295 with OID {DAA37BE5-B57C-47E0-AC52-86A41255F828} because it's missing its XML file!! (stt exists: False)
Skipping document 68/295 with OID {5F7CA76B-33EF-46A0-B971-4C09E32BBBA1} because it's missing its XML file!! (stt exists: False)
Skipping document 69/295 with OID {88DB77A6-1E03-49B1-8938-FEE116DA2ABC} because it's missing its XML file!! (stt exists: False)
Skipping document 77/295 with OID {D5EB3C2E-DD7C-4E69-BE56-F4FD86BCB2BE} because it's missing its XML file!! (stt exists: False)
Skipping document 78/295 with OID {C623BCB4-D753-4836-85D2-013416D5B232} because it's missing its XML file!! (stt exists: False)
Skipping document 79/295 with OID {69E69106-1B40-4B6B-965A-6A32D1FF0850} because it's missing its XML file!! (stt exists: False)
Skipping document 80/295 with OID {FABBBB73-3E3A-480E-9259-66863A883AF4} because it's missing its XML file!! (stt exists: False)
Skipping document 84/295 with OID {CAF7327B-BA7D-4E1B-AEB2-0853C383CB89} because it's missing its XML file!! (stt exists: False)
Skipping document 85/295 with OID {94368C31-897B-400F-9487-7C6DABD75C98} because it's missing its XML file!! (stt exists: False)
Skipping document 87/295 with OID {638481FB-7F5D-4F43-BEBF-C7E8D4DE74FA} because it's missing its XML file!! (stt exists: False)
Skipping document 88/295 with OID {725732FB-0A2B-4550-BF78-5F585E36D429} because it's missing its XML file!! (stt exists: False)
Skipping document 90/295 with OID {EC931660-FC92-4DDC-8573-615A427BF1DD} because it's missing its XML file!! (stt exists: False)
Skipping document 92/295 with OID {0204F9CE-E9BF-4FF7-817C-96C8EC85FE3B} because it's missing its XML file!! (stt exists: False)
Skipping document 99/295 with OID {DD19F3C8-5F88-480B-A9D4-9C45BF591BCB} because it's missing its XML file!! (stt exists: False)
Skipping document 102/295 with OID {3C4EF842-9965-4961-A4C1-7D24E8339252} because it's missing its XML file!! (stt exists: False)
Skipping document 103/295 with OID {36563E81-9DA5-4B0D-941F-AEC077E8AC5F} because it's missing its XML file!! (stt exists: False)
Skipping document 104/295 with OID {89DC2A66-0874-4288-86B4-71EED98F1063} because it's missing its XML file!! (stt exists: False)
Skipping document 108/295 with OID {D2DA362E-B5CA-4EF3-8B2F-D16AC6A097D1} because it's missing its XML file!! (stt exists: False)
Skipping document 111/295 with OID {FC5DB49F-18BC-4F5F-A854-F6A87738C57F} because it's missing its XML file!! (stt exists: False)
Skipping document 112/295 with OID {60E0A3CD-06A7-4253-8C63-7350683A75A6} because it's missing its XML file!! (stt exists: False)
Skipping document 113/295 with OID {9A2D0661-45F4-4897-98FB-0BD8D8BA6C49} because it's missing its XML file!! (stt exists: False)
Skipping document 114/295 with OID {A4CDDB72-8003-4A49-9050-D49B9BA7D239} because it's missing its XML file!! (stt exists: False)
Skipping document 115/295 with OID {D764486C-505D-4F97-90D8-0143148B0941} because it's missing its XML file!! (stt exists: False)
Skipping document 116/295 with OID {3EA25B1A-3733-488C-9334-85EDC6E60C8D} because it's missing its XML file!! (stt exists: False)
Skipping document 117/295 with OID {3F8E5CB6-C5A9-4967-B718-E4D9BAB2778C} because it's missing its XML file!! (stt exists: False)
Skipping document 122/295 with OID {6936D678-FC2F-45A9-AF18-B896719EAEED} because it's missing its XML file!! (stt exists: False)
Skipping document 124/295 with OID {99287849-D7FF-4DF1-8DC7-C701D954B1A5} because it's missing its XML file!! (stt exists: False)
Skipping document 126/295 with OID {AC47DB2F-BD8C-4845-BCC7-96FB1D196FE9} because it's missing its XML file!! (stt exists: False)
Skipping document 136/295 with OID {3133BDAE-9CDF-4C28-8C38-66F536C32D59} because it's missing its XML file!! (stt exists: False)
Skipping document 146/295 with OID {506DDAF0-849A-4986-AA5A-C370BBACFC42} because it's missing its XML file!! (stt exists: False)
Skipping document 150/295 with OID {2604FB88-9C2E-4BD6-8E10-9ED70EA9A613} because it's missing its XML file!! (stt exists: False)
Skipping document 151/295 with OID {5B13999D-1830-4C13-9957-DB189A9401B2} because it's missing its XML file!! (stt exists: False)
Skipping document 168/295 with OID {EE0F030A-CDA0-46B7-8253-F7F9DB2C2528} because it's missing its XML file!! (stt exists: False)
The date for document with OID {819BD060-1206-4F2C-9E20-2AC0D5694977} was invalid (__/12/1982) - changed it to 01/12/1982
Skipping document 187/295 with OID {EDD51253-9F15-4E82-9491-23E425A4CFBC} because it's missing its XML file!! (stt exists: False)

100%|██████████| 1/1 [00:01<00:00,  1.29s/it]
47it [02:49,  3.60s/it]

Skipping document 219/295 with OID {B8270A05-67CB-4DE4-AD0C-2C949FDEF755} because it's missing its XML file!! (stt exists: False)
Skipping document 263/295 with OID {8ABC766C-111F-4935-9112-74D993871D14} because it's missing its XML file!! (stt exists: False)
Skipping document 280/295 with OID {46E9ACB2-1871-4B2E-BE7F-6D019D99B0C6} because it's missing its XML file!! (stt exists: False)
Skipping document 281/295 with OID {D98C42AA-D98A-4180-A124-FF1B3CB42910} because it's missing its XML file!! (stt exists: False)
Skipping document 283/295 with OID {6D1F27BC-C83A-4A91-B10B-1F4EA5C8F01F} because it's missing its XML file!! (stt exists: False)
Skipping document 294/295 with OID {D978B28D-CAB3-4165-B3EE-77D973E36587} because it's missing its XML file!! (stt exists: False)
vie_va - returning 225 documents, 70 were skipped due to missing necessary info.
 --> Adding 225 to the out csv for vie_va

There were many duplicates due to a small mistake: the rows were all written again for each program

In [18]:
metadata_df = pd.read_csv(out_csv_name)
#metadata_df = metadata_df.drop_duplicates()
len(metadata_df)

26197

In [17]:
metadata_df.to_csv(out_csv_name, index=True)

In [10]:
v1_csv_name = out_csv_name.replace("rts", "rts_v1")
v1_csv_name

'/home/piconti/impresso-text-acquisition/text_preparation/data/sample_data/RTS/programs_metadata.rts_v1.csv'

In [20]:
metadata_v1_df = pd.read_csv(v1_csv_name)
metadata_v1_df = metadata_v1_df.drop_duplicates()
len(metadata_v1_df)

36856

### Claude fix of the corrupted text where '?' replaces characters with accents

In [ ]:

# Now I understand all failures. Most of these are in MANUAL_MAP already.
# The rule failures are for tokens NOT in the manual map.
# Let me add the remaining edge cases to MANUAL_MAP and tighten the rules:
#
# Issues:
# 1. "St?r?o" - MANUAL_MAP has it, works ✓
# 2. "?lections" - MANUAL_MAP has it, works ✓ (same for all ?-initial words)
# 3. "Conf?rence" - MANUAL_MAP has it ✓
# 4. "m?me" - MANUAL_MAP has it ✓
# 5. "si?cle" - MANUAL_MAP has it ✓
# 6. "for?ts" - MANUAL_MAP has it ✓
# 7. "fa?on" - MANUAL_MAP has it ✓
# 8. "re?u" - MANUAL_MAP has it ✓
#
# ALL failures in the test are for tokens that ARE in the manual map!
# The test was using correct_by_rules directly without checking manual map first.
# The actual correct_token function checks manual map first, then falls back to rules.
# So the test was misleading.
#
# The ONLY critical rule fix is:
# 1. ç rule: '' in 'aou' = True -> need "after != '' and after.lower() in 'aou'"
# 2. à rule: fires before word-initial check - need to only fire when it's truly standalone
#    (not at position 0 of a word-token, since word-tokens don't start with spaces)
#    Actually, word-tokens extracted by re.split never have spaces, so before='' means i=0
#    Fix: only apply à rule if before=' ' (in context, not token-start)
#    Since we extract pure word tokens, before='' always means start of token -> should be é/è
#
# Let me write the final clean version and apply it.

import pandas as pd, re

# ─── FINAL MANUAL MAP (comprehensive) ───
MANUAL_MAP = {
    "?": "à",
    "Parl?": "Parlé", "'Parl?": "'Parlé", "Clarifi?": "Clarifié", "Valid?": "Validé",
    "Premi?re'": "Première'", "Accept?": "Accepté", "Mont?": "Monté",
    "Premi?re": "Première", "St?r?o": "Stéréo",
    "'Pr?sentateur": "'Présentateur", "Pr?sentateur": "Présentateur",
    "'Interview?": "'Interviewé", "Interview?": "Interviewé",
    "Gen?ve": "Genève", "'Gen?ve": "'Genève", "Gen?ve'": "Genève'",
    "Radio-Gen?ve": "Radio-Genève", "Radio-Gen?ve'": "Radio-Genève'",
    "Neuch?tel": "Neuchâtel", "'Neuch?tel": "'Neuchâtel", "Neuch?tel'": "Neuchâtel'",
    "neuch?telois": "neuchâtelois", "neuch?teloise": "neuchâteloise",
    "B?le": "Bâle", "Del?mont": "Delémont", "Z?rich": "Zürich",
    "Montr?al": "Montréal", "J?rusalem": "Jérusalem", "J?rusalem'": "Jérusalem'",
    "T?h?ran": "Téhéran", "Qu?bec": "Québec",
    "Alg?rie": "Algérie", "'Alg?rie'": "'Algérie'", "d'Alg?rie": "d'Algérie",
    "l'Alg?rie": "l'Algérie", "P?kin": "Pékin", "Cor?e": "Corée",
    "Ha?ti": "Haïti", "Za?re": "Zaïre", "Isra?l": "Israël",
    "'Isra?l'": "'Israël'", "d'Isra?l": "d'Israël", "Gr?ce": "Grèce",
    "Su?de": "Suède", "Kowe?t": "Koweït", "Am?rique": "Amérique",
    "Bosnie-Herz?govine": "Bosnie-Herzégovine",
    "'Bosnie-Herz?govine'": "'Bosnie-Herzégovine'", "Herz?govine": "Herzégovine",
    "Andr?": "André", "Andr?'": "André'", "d'Andr?": "d'André",
    "Ren?": "René", "Ren?'": "René'", "Jean-Ren?'": "Jean-René'",
    "Fran?ois": "François", "Fran?ois'": "François'",
    "Jean-Fran?ois": "Jean-François", "Jean-Fran?ois'": "Jean-François'",
    "Fran?oise": "Françoise", "Fran?oise'": "Françoise'",
    "G?rard": "Gérard", "G?rard'": "Gérard'",
    "Rapha?l": "Raphaël", "Rapha?l'": "Raphaël'",
    "Jos?": "José", "Mich?le": "Michèle", "Mich?le'": "Michèle'",
    "Marie-Jos?'": "Marie-José'", "L?on": "Léon", "L?o": "Léo",
    "Fr?d?ric": "Frédéric", "Fr?d?ric'": "Frédéric'",
    "G?rald": "Gérald", "F?lix": "Félix", "F?licien": "Félicien",
    "Mikha?l": "Mikhaïl", "J?rg": "Jörg", "J?rg'": "Jörg'",
    "Val?ry": "Valéry", "R?my": "Rémy", "G?n?ral": "Général",
    "No?l": "Noël", "Genevi?ve": "Geneviève", "B?at'": "Béat'",
    "C?cile'": "Cécile'", "Marl?ne'": "Marlène'",
    "Pierre-Andr?": "Pierre-André", "Pierre-Andr?'": "Pierre-André'",
    "Georges-Andr?": "Georges-André", "Georges-Andr?'": "Georges-André'",
    "St?phane": "Stéphane", "St?phane'": "Stéphane'",
    "Fran?ais": "Français", "Ma?tre": "Maître",
    "B?guin": "Béguin", "'B?guin": "'Béguin", "B?guelin": "Béguelin", "'B?guelin": "'Béguelin",
    "Fran?ois-Achille'": "François-Achille'",
    "Nussl?": "Nusslé", "'Nussl?": "'Nusslé", "Werl?": "Werlé", "'Werl?": "'Werlé",
    "K?nzler": "Künzler", "'K?nzler": "'Künzler",
    "M?ller": "Müller", "'M?ller": "'Müller",
    "Gilli?ron": "Gilliéron", "'Gilli?ron": "'Gilliéron",
    "Moss?": "Mossé", "'Moss?": "'Mossé",
    "D?caillet": "Décaillet", "'D?caillet": "'Décaillet",
    "D?cotte": "Décotte", "'D?cotte": "'Décotte",
    "pr?sident": "président", "'pr?sident": "'président",
    "vice-pr?sident": "vice-président", "'vice-pr?sident": "'vice-président",
    "Pr?sident": "Président", "Pr?sentation": "Présentation",
    "pr?sidente": "présidente", "pr?sidentielle": "présidentielle",
    "pr?sidentielle'": "présidentielle'", "pr?sidentielles": "présidentielles",
    "pr?sidence": "présidence", "pr?sent": "présent",
    "pr?sent?": "présenté", "pr?sente": "présente", "pr?sentation": "présentation",
    "f?d?ral": "fédéral", "f?d?ral'": "fédéral'", "f?d?rale": "fédérale",
    "f?d?rale'": "fédérale'", "f?d?rales": "fédérales",
    "f?d?ration": "fédération", "F?d?ration": "Fédération", "F?d?ral": "Fédéral",
    "Conf?d?ration": "Confédération", "Conf?d?ration'": "Confédération'",
    "fran?ais": "français", "fran?ais'": "français'",
    "fran?aise": "française", "fran?aise'": "française'", "fran?aises": "françaises",
    "d?claration": "déclaration", "D?claration": "Déclaration",
    "'D?claration": "'Déclaration", "'D?claration'": "'Déclaration'",
    "d?clarations": "déclarations",
    "apr?s": "après", "Apr?s": "Après", "Apr?s'": "Après'", "aupr?s": "auprès",
    "g?n?ral": "général", "g?n?rale": "générale",
    "?t?": "été", "?crivain": "écrivain", "'?crivain'": "'écrivain'",
    "'?crivain": "'écrivain", "?crivain'": "écrivain'", "l'?crivain": "l'écrivain",
    "?crivaine": "écrivaine", "'?crivaine'": "'écrivaine'", "?crivaine'": "écrivaine'",
    "secr?taire": "secrétaire", "'secr?taire": "'secrétaire",
    "D?partement": "Département", "d?partement": "département",
    "?me": "ème", "Conf?rence": "Conférence", "'Conf?rence": "'Conférence",
    "conf?rence": "conférence", "sp?cial": "spécial", "sp?ciale": "spéciale",
    "sp?cialiste": "spécialiste", "l'Universit?": "l'Université",
    "l'universit?": "l'université",
    "?conomique": "économique", "?conomique'": "économique'",
    "?conomiques": "économiques", "?conomie": "économie",
    "l'?conomie": "l'économie", "'?conomie'": "'économie'",
    "d'?conomie": "d'économie", "?conomiste": "économiste", "?conomiste'": "économiste'",
    "R?action": "Réaction", "r?action": "réaction", "r?actions": "réactions",
    "R?actions": "Réactions", "R?publique": "République", "r?publique": "république",
    "T?moignage": "Témoignage", "t?moignage": "témoignage",
    "t?moignages": "témoignages", "T?moignages": "Témoignages", "t?moin": "témoin",
    "?tre": "être", "d'?tre": "d'être", "Pr?t": "Prêt", "pr?t": "prêt",
    "pr?ts": "prêts", "pr?tre": "prêtre", "'pr?tre'": "'prêtre'", "pr?tres": "prêtres",
    "?missions": "émissions", "l'?mission": "l'émission", "'?mission": "'émission",
    "?mission": "émission",
    "premi?re": "première", "premi?res": "premières",
    "oecum?nique": "œcuménique", "'oecum?nisme'": "'œcuménisme'",
    "sovi?tique": "soviétique", "sovi?tiques": "soviétiques", "Sovi?tiques": "Soviétiques",
    "am?ricain": "américain", "am?ricaine": "américaine",
    "am?ricains": "américains", "am?ricaines": "américaines", "Am?ricains": "Américains",
    "l'arm?e": "l'armée", "'arm?e'": "'armée'", "arm?e": "armée", "arm?'": "armé'",
    "soci?t?": "société", "Soci?t?": "Société", "soci?t?s": "sociétés",
    "'Deuxi?me": "'Deuxième", "Deuxi?me": "Deuxième", "deuxi?me": "deuxième",
    "r?fugi?s": "réfugiés", "r?fugi?": "réfugié", "r?fugi?'": "réfugié'",
    "'r?fugi?'": "'réfugié'", "r?fugi?e": "réfugiée",
    "?lections": "élections", "'?lection": "'élection", "?lection": "élection",
    "'?lection'": "'élection'", "l'?lection": "l'élection", "?lectorale": "électorale",
    "isra?lien": "israélien", "isra?lienne": "israélienne",
    "r?gion": "région", "r?gions": "régions", "n?gociations": "négociations",
    "c?r?monie": "cérémonie", "C?r?monie": "Cérémonie",
    "m?me": "même", "m?mes": "mêmes", "sc?ne": "scène",
    "Comit?": "Comité", "comit?": "comité",
    "g?n?rale": "générale", "com?dien": "comédien",
    "'com?dien'": "'comédien'", "'com?dien": "'comédien",
    "com?dienne": "comédienne", "'com?dienne'": "'comédienne'",
    "Congr?s": "Congrès", "congr?s": "congrès",
    "l'ann?e": "l'année", "ann?e": "année", "ann?es": "années",
    "Enqu?te": "Enquête", "d'enqu?te": "d'enquête", "enqu?te": "enquête",
    "l'enqu?te": "l'enquête", "d?part": "départ", "march?": "marché",
    "March?": "Marché", "d?mission": "démission", "D?mission": "Démission",
    "d?but": "début", "D?but": "Début", "charg?": "chargé", "d?fense": "défense",
    "gr?ve": "grève", "'gr?ve'": "'grève'",
    "l'Assembl?e": "l'Assemblée", "l'assembl?e": "l'assemblée",
    "communaut?": "communauté", "Communaut?": "Communauté", "r?gime": "régime",
    "?lu": "élu", "?lus": "élus", "?lue": "élue",
    "d?veloppement": "développement", "po?te": "poète",
    "autorit?s": "autorités", "cons?quences": "conséquences", "libert?": "liberté",
    "th??tre": "théâtre", "Th??tre": "Théâtre",
    "'cin?ma'": "'cinéma'", "cin?ma": "cinéma",
    "m?re": "mère", "P?re": "Père", "p?re": "père",
    "fr?re": "frère", "fr?res": "frères",
    "F?te": "Fête", "f?te": "fête", "'f?te": "'fête", "f?tes": "fêtes",
    "f?vrier": "février",
    "?tat": "État", "d'?tat": "d'État", "l'?tat": "l'État", "?tats": "États",
    "t?te": "tête", "bless?s": "blessés", "r?alisateur": "réalisateur",
    "d?bat": "débat", "D?bat": "Débat", "'D?bat'": "'Débat'",
    "d?bat'": "débat'", "D?bat'": "Débat'",
    "ch?mage": "chômage", "'ch?mage'": "'chômage'", "ch?meurs": "chômeurs",
    "pr?sence": "présence", "pass?": "passé", "journ?e": "journée", "Journ?e": "Journée",
    "l'?tranger": "l'étranger", "ing?nieur": "ingénieur", "d?s": "dès",
    "?ge": "âge", "l'?ge": "l'âge",
    "?galement": "également", "?v?nements": "événements", "'?v?nement": "'événement",
    "difficult?s": "difficultés", "D?c?s": "Décès", "d?c?s": "décès",
    "d?cembre": "décembre",
    "l'?cole": "l'école", "?cole": "école", "'?coles": "'écoles", "?coles": "écoles",
    "re?u": "reçu", "contr?le": "contrôle",
    "r?union": "réunion", "R?union": "Réunion", "'r?union": "'réunion",
    "solidarit?": "solidarité", "Solidarit?": "Solidarité",
    "si?ge": "siège", "l'a?roport": "l'aéroport",
    "a?rienne": "aérienne", "a?rienne'": "aérienne'", "a?rien'": "aérien'",
    "a?rostier": "aérostier", "ao?t": "août",
    "cha?ne": "chaîne", "Cha?ne": "Chaîne",
    "condamn?": "condamné", "r?sistance": "résistance",
    "?tudiants": "étudiants", "?tudiant": "étudiant",
    "r?forme": "réforme", "r?formes": "réformes", "d?mocratie": "démocratie",
    "'d?mocratie": "'démocratie", "carri?re": "carrière",
    "ext?rieur": "extérieur", "ext?rieure": "extérieure",
    "l?gislatives": "législatives", "'l?gislation'": "'législation'",
    "'l?gislatif": "'législatif",
    "?v?que": "évêque", "?v?ques": "évêques",
    "?trangers": "étrangers", "?trang?res": "étrangères",
    "?trang?re": "étrangère", "?trang?res'": "étrangères'",
    "fronti?res": "frontières", "fronti?re": "frontière",
    "r?f?rendum": "référendum", "'r?f?rendum'": "'référendum'",
    "?voque": "évoque", "'ex?cutif": "'exécutif",
    "Mus?e": "Musée", "mus?e": "musée", "pi?ce": "pièce",
    "Pr?dication": "Prédication", "pr?dication": "prédication",
    "r?volution": "révolution", "litt?rature": "littérature",
    "'litt?rature'": "'littérature'", "litt?raire": "littéraire",
    "litt?raire'": "littéraire'",
    "l'ind?pendance": "l'indépendance", "'ind?pendantisme'": "'indépendantisme'",
    "r?daction": "rédaction", "mati?re": "matière", "donn?": "donné",
    "d?cid?": "décidé", "syst?me": "système", "succ?s": "succès",
    "r?vision": "révision", "d?couverte": "découverte",
    "arr?t?": "arrêté", "Arr?t": "Arrêt",
    "financi?re": "financière", "sign?": "signé",
    "m?decine": "médecine", "'m?decine'": "'médecine'",
    "m?decin": "médecin", "'m?decin": "'médecin", "'m?decin'": "'médecin'",
    "m?decins": "médecins", "M?decins": "Médecins",
    "T?l?vision": "Télévision", "'t?l?vision'": "'télévision'",
    "t?l?vision": "télévision", "t?l?phone": "téléphone",
    "derni?re": "dernière", "derni?res": "dernières",
    "l'int?rieur": "l'intérieur", "l'Int?rieur": "l'Intérieur",
    "l'arriv?e": "l'arrivée", "arriv?e": "arrivée", "Arriv?e": "Arrivée",
    "?taient": "étaient", "?tait": "était",
    "M?moire": "Mémoire", "m?moire": "mémoire",
    "Lib?ration": "Libération", "lib?ration": "libération",
    "lib?ral": "libéral", "lib?rale": "libérale",
    "cr?ation": "création", "Cr?ation": "Création",
    "envoy?": "envoyé", "'envoy?": "'envoyé",
    "d?l?gation": "délégation", "d?l?gu?": "délégué",
    "'d?l?gu?": "'délégué", "d?l?gu?s": "délégués", "'d?l?gu?s": "'délégués",
    "r?le": "rôle", "r?les": "rôles",
    "s?curit?": "sécurité", "proc?s": "procès", "'proc?s'": "'procès'",
    "r?dacteur": "rédacteur", "'r?dacteur": "'rédacteur",
    "si?cle": "siècle", "si?cle'": "siècle'",
    "d?put?": "député", "'d?put?": "'député", "d?put?e": "députée",
    "d?put?s": "députés", "d?put?es": "députées",
    "d?cision": "décision", "D?cision": "Décision",
    "l'?nergie": "l'énergie", "'?nergie": "'énergie", "?nergies": "énergies",
    "repr?sentant": "représentant", "repr?sentants": "représentants",
    "conseill?re": "conseillère", "'conseill?re": "'conseillère",
    "d'?tat": "d'État", "pr?s": "près",
    "comp?tition": "compétition", "sant?": "santé",
    "R?trospective": "Rétrospective", "c?t?": "côté", "m?dias": "médias",
    "l'adh?sion": "l'adhésion", "r?sultats": "résultats", "r?sultat": "résultat",
    "Europ?enne": "Européenne", "europ?enne": "européenne",
    "europ?enne'": "européenne'", "europ?ennes": "européennes",
    "europ?en": "européen", "europ?ens": "européens",
    "malgr?": "malgré", "coop?ration": "coopération",
    "th?ologie": "théologie", "th?ologien": "théologien",
    "alg?rien": "algérien", "minist?re": "ministère",
    "d?": "dé", "d?mocrate-chr?tien": "démocrate-chrétien",
    "pr?nom": "prénom", "chr?tiens": "chrétiens", "chr?tien": "chrétien",
    "th?me": "thème", "employ?s": "employés",
    "f?d?ration": "fédération", "organis?": "organisé",
    "S?rie": "Série", "s?rie": "série",
    "diff?rents": "différents", "diff?rentes": "différentes",
    "diff?rent": "différent", "m?tier": "métier",
    "entra?neur": "entraîneur", "laur?at": "lauréat",
    "consacr?": "consacré", "consacr?e": "consacrée",
    "?tudes": "études", "d'?tudes": "d'études", "?tude": "étude",
    "?pouse": "épouse", "r?ponse": "réponse",
    "n?cessit?": "nécessité", "?meutes": "émeutes",
    "l'?le": "l'île", "for?ts": "forêts",
    "m?dicale": "médicale", "responsabilit?": "responsabilité",
    "personnalit?s": "personnalités", "personnalit?": "personnalité",
    "op?ration": "opération", "Op?ration": "Opération", "op?rations": "opérations",
    "proc?dure": "procédure", "d?tenus": "détenus", "trouv?": "trouvé",
    "pr?vention": "prévention", "publicit?": "publicité",
    "neutralit?": "neutralité", "r?unification": "réunification",
    "nucl?aire": "nucléaire", "nucl?aire'": "nucléaire'", "nucl?aires": "nucléaires",
    "l'?quipe": "l'équipe", "?change": "échange", "o?": "où", "tr?s": "très",
    "probl?me": "problème", "probl?mes": "problèmes",
    "nomm?": "nommé", "strat?gie": "stratégie",
    "activit?": "activité", "activit?s": "activités",
    "exp?rience": "expérience", "propri?taire": "propriétaire",
    "Nestl?": "Nestlé", "annonc?": "annoncé", "priv?e": "privée",
    "col?re": "colère", "accept?": "accepté",
    "Tch?coslovaquie": "Tchécoslovaquie", "rencontr?": "rencontré",
    "Di?te": "Diète", "lanc?": "lancé", "cr?er": "créer",
    "Proc?s": "Procès", "m?daille": "médaille",
    "p?dophile": "pédophile", "horlog?re": "horlogère",
    "fa?on": "façon", "reconna?t": "reconnaît",
    "al?manique": "alémanique", "v?cu": "vécu",
    "'comm?moration'": "'commémoration'", "p?trole": "pétrole",
    "lumi?res": "lumières", "l'abb?": "l'abbé", "l'h?pital": "l'hôpital",
    "mani?re": "manière", "helv?tique": "helvétique",
    "d?mocrate": "démocrate", "?l?ments": "éléments",
    "d?nonce": "dénonce", "d?faite": "défaite", "plut?t": "plutôt",
    "gr?ce": "grâce", "volont?": "volonté", "b?timent": "bâtiment",
    "l'op?ration": "l'opération", "stup?fiants'": "stupéfiants'",
    "jusqu'?": "jusqu'à",
    "requ?rant": "requérant", "requ?rants": "requérants",
    "assassin?": "assassiné", "r?alit?": "réalité",
    "l'Acad?mie": "l'Académie", "d?cide": "décide",
    "cin?aste": "cinéaste", "d?tention": "détention",
    "l'?volution": "l'évolution", "l'?gard": "l'égard",
    "?glise": "église", "l'?glise": "l'église", "?glises": "églises",
    "'?glise": "'église",
    "R?cit": "Récit", "r?cit": "récit", "'R?citant": "'Récitant",
    "?crit": "écrit", "?crits": "écrits", "?crite": "écrite",
    "f?minin": "féminin", "occup?s": "occupés",
    "majorit?": "majorité", "?tabli": "établi", "?tablie": "établie",
    "?le": "île", "?le'": "île'",
    "?lecteur": "électeur", "?lecteurs": "électeurs",
    "?lection": "élection", "?lection'": "élection'",
    "?lectricit?": "électricité",
    "?levage": "élevage", "?leveur": "éleveur", "?leveurs": "éleveurs",
    "?lite": "élite", "?loge": "éloge",
    "?boueur": "éboueur", "?branlement": "ébranlement",
    "?cart": "écart", "?chafaud": "échafaud",
    "?chec": "échec", "?checs'": "échecs'",
    "?chographie'": "échographie'", "?clairage": "éclairage",
    "?clipse'": "éclipse'", "?coli?re": "écolière",
    "?colier": "écolier", "?colier'": "écolier'", "?coliers": "écoliers",
    "?cologie": "écologie", "?cologie'": "écologie'", "?cologisme'": "écologisme'",
    "?conomie": "économie", "?conomie'": "économie'", "?conomies": "économies",
    "?coute": "écoute", "?craser": "écraser", "?crevisse'": "écrevisse'",
    "?criture": "écriture", "?criture'": "écriture'",
    "?crivain": "écrivain", "?crivains": "écrivains",
    "?dition": "édition", "?dition'": "édition'",
    "?ducateur": "éducateur", "?ducateur'": "éducateur'",
    "?ducateurs": "éducateurs", "?ducation": "éducation", "?ducation'": "éducation'",
    "?ducatrice": "éducatrice",
    "?galit?": "égalité", "?galit?'": "égalité'",
    "?gyptologue": "égyptologue", "?gyptologue'": "égyptologue'",
    "?largir": "élargir",
    "?l?ve'": "élève'", "?l?ves": "élèves", "?l?phant'": "éléphant'",
    "?cologiste": "écologiste", "?cologiste'": "écologiste'",
    "?ll?s": "elles",
    "d?j?": "déjà",
    "carr?": "carré",
    "t?l?vis?": "télévisé",
    "f?d?r?": "fédéré",
    "diff?renci?": "différencié",
    "?v?nement": "événement", "?v?nements": "événements",
    "?v?que": "évêque",
    "soci?t?": "société",
    "t?moignage": "témoignage",
    "repr?senter": "représenter",
    "s?curit?s": "sécurités",
    "r?sistance": "résistance",
    "th?orie": "théorie",
    "cin?matographique": "cinématographique",
    "po?sie": "poésie",
    "'po?sie'": "'poésie'",
    "int?gration": "intégration",
    "'int?gration": "'intégration",
    "l'int?gration": "l'intégration",
    "d?l?gu?s": "délégués",
    "'d?put?": "'député",
    "d?bats": "débats",
    "repr?sente": "représente",
    "abb?": "abbé",
    "t?l?": "télé",
    "?crivains": "écrivains",
    "?dition": "édition",
    "p?re": "père",
    "carr?": "carré",
    "arm?": "armé",
    "g?ographe": "géographe",
    "g?ographie": "géographie",
    "g?ographique": "géographique",
    "arch?ologue": "archéologue",
    "arch?ologie": "archéologie",
    "Universit?s": "Universités",
    "universit?s": "universités",
    "M?t?o": "Météo",
    "li?": "lié",
    "L'?volution": "L'évolution",
    "l'?ch?ance": "l'échéance",
    "adh?sion": "adhésion",
    "El?ment": "Elément",
    "el?ments": "eléments",
    "install?s": "installés",
    "chass?s": "chassés",
    "marqu?s": "marqués",
    "marqu?": "marqué",
    "cha?nes": "chaînes",
    "l'entra?neur": "l'entraîneur",
    "au-del?": "au-delà",
    "Jusqu'o?": "Jusqu'où",
    "men?s": "menés",
    "Plan?te": "Planète",
    "concr?tement": "concrètement",
    "d?veloppment": "développement",
    "J?r?me": "Jérôme",
    "requ?tes": "requêtes",
    # all the words ending in -s to remove the rule which broke many participe passés
    "proc?s": "procès",
    "apr?s": "après",
    "tr?s": "très",
    "succ?s": "succès",
    "exc?s": "excès",
    "acc?s": "accès",
    "progr?s": "progrès",
    "congr?s": "congrès",
    "d?c?s": "décès",
    "expr?s": "exprès",
    "aupr?s": "auprès",
    "pr?s": "près",
    "d?s": "dès",
}

# Suffixes after which a word-final ? is a real question mark, not an accent
_REAL_QUESTION_SUFFIXES = (
    # verb infinitives
    'er', 'ir', 're', 'dre', 'tre', 'ndre', 'indre', 'oudre',
    # common noun/adj endings that don't take accents
    'eur', 'eur', 'oir', 'our', 'eur', "istes",
    # explicit vowel endings
    'a', 'e', 'i', 'o', 'u', 'y',
)


def _is_real_question_mark(token, pos):
    """Return True if the ? at position pos in token is a genuine question mark."""
    # Only applies to word-final ?
    if pos != len(token) - 1:
        return False
    before = token[:pos].lower()
    # After a vowel directly
    if before and before[-1] in 'aeiouy':
        return True
    # After known suffixes that never take a final accent
    for suffix in _REAL_QUESTION_SUFFIXES:
        if before.endswith(suffix):
            return True
    return False

def correct_by_rules(token, char='?'):
    if char not in token:
        return token
    result = list(token)
    i = 0
    while i < len(result):
        if result[i] != char:
            i += 1
            continue
        before = result[i-1] if i > 0 else ''
        after = result[i+1] if i < len(result)-1 else ''
        after2 = result[i+2] if i < len(result)-2 else ''

        # ── Real question mark? (word-final after verb/noun endings) ──
        if char=='?' and _is_real_question_mark(token, i):
            result[i] = '?'

        # ç: ? before a/o/u after consonant (after MUST be non-empty)
        elif after and after.lower() in 'aou' and before.lower() in 'cfglmnst':
            # Restrict ç: mainly after n, c, l, s, g, f (not r which is rare)
            result[i] = 'ç'
        # è before -re at non-word-final position (ère endings)
        # Only if followed by 're' and that's near end of word
        elif after.lower() == 'r' and after2.lower() == 'e' and (i+3 >= len(result) or result[i+3] in ('s', '', 'z')):
            result[i] = 'è'
        # è before -me (problème, même) - ê for même is in manual map
        elif after.lower() == 'm' and after2.lower() == 'e':
            result[i] = 'è'
        # è before -ve (grève) - in manual map
        elif after.lower() == 'v' and after2.lower() == 'e':
            result[i] = 'è'
        # è before -ge (siège) - in manual map
        elif after.lower() == 'g' and after2.lower() == 'e':
            result[i] = 'è'
        # è before final -s (procès, après, très)
        #elif after.lower() == 's' and (i+2 >= len(result) or result[i+2] in (' ', '', "'", ',', '.', ')', ']', '"', '-')):
        #    result[i] = 'è'
        # è before -ce (pièce)
        elif after.lower() == 'c' and after2.lower() == 'e':
            result[i] = 'è'
        # è: i?r pattern (première)
        elif before.lower() == 'i' and after.lower() == 'r':
            result[i] = 'è'
        # è: ?v (Genève: n?v → è)
        elif after.lower() == 'v':
            result[i] = 'è'
        # ê before final -t (arrêt, forêt) - in manual map
        elif after.lower() == 't' and (i+2 >= len(result) or result[i+2] in (' ', '', "'", ',', '.', ')')):
            result[i] = 'ê'
        # ô after h
        elif before.lower() == 'h':
            result[i] = 'ô'
        # Word-initial (i=0 in token): ? → mostly é
        elif i == 0:
            if after.lower() == 'l' and after2 and after2.lower() not in 'aeioué':
                result[i] = 'î'   # île
            elif after.lower() == 'g' and after2.lower() == 'e':
                result[i] = 'â'   # âge
            else:
                result[i] = 'é'
        # Word-final ? after vowel 'e' → likely real question mark
        elif not after and before.lower() in 'aeiouy':
            result[i] = '?'   # Keep as real ?
        # Default: é
        else:
            result[i] = 'é'
        i += 1
    return ''.join(result)

def correct_token(token, char="?", _map = MANUAL_MAP):
    if token in _map:
        return _map[token]
    return correct_by_rules(token, char=char)

def fix_cell(cell_value, char="?", _map=MANUAL_MAP):
    if not isinstance(cell_value, str) or char not in cell_value:
        return cell_value
    if char == "?":
        parts = re.split(r"([A-Za-z?àâäéèêëîïôùûüçœæ'-]+)", cell_value)
    elif char == "�":
        parts = re.split(r"([A-Za-z�àâäéèêëîïôùûüçœæ'-]+)", cell_value)
    result = []
    for part in parts:
        if char in part and re.search(r'[A-Za-z]', part):
            result.append(correct_token(part, char=char, _map=_map))
        elif part == char:
            result.append('à')   # standalone ? is always "à"
        else:
            result.append(part)
    return ''.join(result)

ID_COLS = {
    'alias', 'date_str', 'stt_filename', 'mp3_filenames', 'stripped_OID',
    'exact_date', 'broadcast_date', 'cls_ID', 'OID', 'login',
    'sequence', 'modified_by', 'modified_on', 'work_duration',
    'work_duration_compl', 'spt_filenames'
}

# ─── Apply to CSV ───
print("Loading CSV...")
df = pd.read_csv('/mnt/user-data/uploads/programs_metadata_rts_v3.csv', dtype=str)

TEXT_COLS = [c for c in df.columns if c not in ID_COLS]

print("Processing cells...")
total_fixes = 0
for col in TEXT_COLS:
    before = df[col].copy()
    df[col] = df[col].apply(fix_cell)
    fixes = (before != df[col]).sum()
    total_fixes += fixes
    if fixes > 0:
        print(f"  {col}: {fixes} cells modified")

print(f"\nTotal cells modified: {total_fixes}")

# Verify key rows
print("\n--- Sample verification ---")
check_cols = ['broadcast_episode_title', 'content_summary', 'workflow_status', 'document_type', 'modulation_type']
for col in check_cols:
    samples = df[col].dropna().head(5).tolist()
    print(f"\n{col}:")
    for s in samples[:3]:
        print(f"  {str(s)[:120]}")

print("\nSaving...")
df.to_csv('/mnt/user-data/outputs/programs_metadata_rts_v3_fixed.csv', index=False)
print("Done!")
"""PYEOF

Output
Loading CSV...
Processing cells...
  broadcast_episode_title: 19138 cells modified
  broadcast_program_name: 1549 cells modified
  document_type: 20956 cells modified
  physical_support_history: 3579 cells modified
  production_type: 521 cells modified
  recording_place: 19605 cells modified
  rights_notes: 22818 cells modified
  rights_status: 22332 cells modified
  series_title: 8917 cells modified
  content_summary: 21476 cells modified
  workflow_status: 20956 cells modified
  assembly_status: 22585 cells modified
  live: 670 cells modified
  modulation_type: 4832 cells modified
  geographical_descriptors: 15692 cells modified
  person_descriptors: 16951 cells modified
  thematical_descriptors: 18174 cells modified
  rights_usage_possibilities: 8538 cells modified
  radio_channels: 15075 cells modified
  subdomains: 10830 cells modified
  recording_dates: 492 cells modified
  first_broadcast_dates: 1056 cells modified
  supports: 16951 cells modified
  participants: 17656 cells modified

Total cells modified: 311349

--- Sample verification ---

broadcast_episode_title:
  "X-Files" ou "Aux frontières du réel"
  Internet à l'Ecole primaire d'Avully (GE)
  Le carré blanc

content_summary:
  Présentation de la série-culte. Le succès, comment le comprendre? Analyse des personnages, des dialogues. Thèmes de la s
  Analyse de la série et des raisons de son succès.
  1992, c'est la prochaine grande étape de l'Europe communautaire. Les régles et les lois qui régissent les personnes et l

workflow_status:
  Validé
  Validé
  Validé

document_type:
  Parlé
  Parlé
  Parlé

modulation_type:
  Stéréo
  Stéréo
  Stéréo

Saving...
Done!"""

#### Try to repreat the approach with the character "�"

Claude's approach fixed the problems with the character "?" but another character is there.

However there are still quite a bit of problems with the fix. I found more examples which had erroneous corrections but much more probably exist.
What we did was the best we could.

In [48]:
SECOND_MANUAL_MAP = {k.replace("?", "�"): v for k,v in MANUAL_MAP.items()}
# add examples by hand from errors remaining spotted
SECOND_MANUAL_MAP["Ch�teaureynaud"] = "Châteaureynaud"
SECOND_MANUAL_MAP

{'�': 'à',
 'Parl�': 'Parlé',
 "'Parl�": "'Parlé",
 'Clarifi�': 'Clarifié',
 'Valid�': 'Validé',
 "Premi�re'": "Première'",
 'Accept�': 'Accepté',
 'Mont�': 'Monté',
 'Premi�re': 'Première',
 'St�r�o': 'Stéréo',
 "'Pr�sentateur": "'Présentateur",
 'Pr�sentateur': 'Présentateur',
 "'Interview�": "'Interviewé",
 'Interview�': 'Interviewé',
 'Gen�ve': 'Genève',
 "'Gen�ve": "'Genève",
 "Gen�ve'": "Genève'",
 'Radio-Gen�ve': 'Radio-Genève',
 "Radio-Gen�ve'": "Radio-Genève'",
 'Neuch�tel': 'Neuchâtel',
 "'Neuch�tel": "'Neuchâtel",
 "Neuch�tel'": "Neuchâtel'",
 'neuch�telois': 'neuchâtelois',
 'neuch�teloise': 'neuchâteloise',
 'B�le': 'Bâle',
 'Del�mont': 'Delémont',
 'Z�rich': 'Zürich',
 'Montr�al': 'Montréal',
 'J�rusalem': 'Jérusalem',
 "J�rusalem'": "Jérusalem'",
 'T�h�ran': 'Téhéran',
 'Qu�bec': 'Québec',
 'Alg�rie': 'Algérie',
 "'Alg�rie'": "'Algérie'",
 "d'Alg�rie": "d'Algérie",
 "l'Alg�rie": "l'Algérie",
 'P�kin': 'Pékin',
 'Cor�e': 'Corée',
 'Ha�ti': 'Haïti',
 'Za�re': 'Zaïre',
 'Isra�l': 'Israël',
 "'Isra�l'": "'Israël'",
 "d'Isra�l": "d'Israël",
 'Gr�ce': 'Grèce',
 'Su�de': 'Suède',
 'Kowe�t': 'Koweït',
 'Am�rique': 'Amérique',
 'Bosnie-Herz�govine': 'Bosnie-Herzégovine',
 "'Bosnie-Herz�govine'": "'Bosnie-Herzégovine'",
 'Herz�govine': 'Herzégovine',
 'Andr�': 'André',
 "Andr�'": "André'",
 "d'Andr�": "d'André",
 'Ren�': 'René',
 "Ren�'": "René'",
 "Jean-Ren�'": "Jean-René'",
 'Fran�ois': 'François',
 "Fran�ois'": "François'",
 'Jean-Fran�ois': 'Jean-François',
 "Jean-Fran�ois'": "Jean-François'",
 'Fran�oise': 'Françoise',
 "Fran�oise'": "Françoise'",
 'G�rard': 'Gérard',
 "G�rard'": "Gérard'",
 'Rapha�l': 'Raphaël',
 "Rapha�l'": "Raphaël'",
 'Jos�': 'José',
 'Mich�le': 'Michèle',
 "Mich�le'": "Michèle'",
 "Marie-Jos�'": "Marie-José'",
 'L�on': 'Léon',
 'L�o': 'Léo',
 'Fr�d�ric': 'Frédéric',
 "Fr�d�ric'": "Frédéric'",
 'G�rald': 'Gérald',
 'F�lix': 'Félix',
 'F�licien': 'Félicien',
 'Mikha�l': 'Mikhaïl',
 'J�rg': 'Jörg',
 "J�rg'": "Jörg'",
 'Val�ry': 'Valéry',
 'R�my': 'Rémy',
 'G�n�ral': 'Général',
 'No�l': 'Noël',
 'Genevi�ve': 'Geneviève',
 "B�at'": "Béat'",
 "C�cile'": "Cécile'",
 "Marl�ne'": "Marlène'",
 'Pierre-Andr�': 'Pierre-André',
 "Pierre-Andr�'": "Pierre-André'",
 'Georges-Andr�': 'Georges-André',
 "Georges-Andr�'": "Georges-André'",
 'St�phane': 'Stéphane',
 "St�phane'": "Stéphane'",
 'Fran�ais': 'Français',
 'Ma�tre': 'Maître',
 'B�guin': 'Béguin',
 "'B�guin": "'Béguin",
 'B�guelin': 'Béguelin',
 "'B�guelin": "'Béguelin",
 "Fran�ois-Achille'": "François-Achille'",
 'Nussl�': 'Nusslé',
 "'Nussl�": "'Nusslé",
 'Werl�': 'Werlé',
 "'Werl�": "'Werlé",
 'K�nzler': 'Künzler',
 "'K�nzler": "'Künzler",
 'M�ller': 'Müller',
 "'M�ller": "'Müller",
 'Gilli�ron': 'Gilliéron',
 "'Gilli�ron": "'Gilliéron",
 'Moss�': 'Mossé',
 "'Moss�": "'Mossé",
 'D�caillet': 'Décaillet',
 "'D�caillet": "'Décaillet",
 'D�cotte': 'Décotte',
 "'D�cotte": "'Décotte",
 'pr�sident': 'président',
 "'pr�sident": "'président",
 'vice-pr�sident': 'vice-président',
 "'vice-pr�sident": "'vice-président",
 'Pr�sident': 'Président',
 'Pr�sentation': 'Présentation',
 'pr�sidente': 'présidente',
 'pr�sidentielle': 'présidentielle',
 "pr�sidentielle'": "présidentielle'",
 'pr�sidentielles': 'présidentielles',
 'pr�sidence': 'présidence',
 'pr�sent': 'présent',
 'pr�sent�': 'présenté',
 'pr�sente': 'présente',
 'pr�sentation': 'présentation',
 'f�d�ral': 'fédéral',
 "f�d�ral'": "fédéral'",
 'f�d�rale': 'fédérale',
 "f�d�rale'": "fédérale'",
 'f�d�rales': 'fédérales',
 'f�d�ration': 'fédération',
 'F�d�ration': 'Fédération',
 'F�d�ral': 'Fédéral',
 'Conf�d�ration': 'Confédération',
 "Conf�d�ration'": "Confédération'",
 'fran�ais': 'français',
 "fran�ais'": "français'",
 'fran�aise': 'française',
 "fran�aise'": "française'",
 'fran�aises': 'françaises',
 'd�claration': 'déclaration',
 'D�claration': 'Déclaration',
 "'D�claration": "'Déclaration",
 "'D�claration'": "'Déclaration'",
 'd�clarations': 'déclarations',
 'apr�s': 'après',
 'Apr�s': 'Après',
 "Apr�s'": "Après'",
 'aupr�s': 'auprès',
 'g�n�ral': 'général',
 'g�n�rale': 'générale',
 '�t�': 'été',
 '�crivain': 'écrivain',
 "'�crivain'": "'écrivain'",
 "'�crivain": "'écrivain",
 "�crivain'": "écrivain'",
 "l'�crivain": "l'écrivain",
 '�crivaine': 'écrivaine',
 "'�crivaine'": "'écrivaine'",
 "�crivaine'": "écrivaine'",
 'secr�taire': 'secrétaire',
 "'secr�taire": "'secrétaire",
 'D�partement': 'Département',
 'd�partement': 'département',
 '�me': 'ème',
 'Conf�rence': 'Conférence',
 "'Conf�rence": "'Conférence",
 'conf�rence': 'conférence',
 'sp�cial': 'spécial',
 'sp�ciale': 'spéciale',
 'sp�cialiste': 'spécialiste',
 "l'Universit�": "l'Université",
 "l'universit�": "l'université",
 '�conomique': 'économique',
 "�conomique'": "économique'",
 '�conomiques': 'économiques',
 '�conomie': 'économie',
 "l'�conomie": "l'économie",
 "'�conomie'": "'économie'",
 "d'�conomie": "d'économie",
 '�conomiste': 'économiste',
 "�conomiste'": "économiste'",
 'R�action': 'Réaction',
 'r�action': 'réaction',
 'r�actions': 'réactions',
 'R�actions': 'Réactions',
 'R�publique': 'République',
 'r�publique': 'république',
 'T�moignage': 'Témoignage',
 't�moignage': 'témoignage',
 't�moignages': 'témoignages',
 'T�moignages': 'Témoignages',
 't�moin': 'témoin',
 '�tre': 'être',
 "d'�tre": "d'être",
 'Pr�t': 'Prêt',
 'pr�t': 'prêt',
 'pr�ts': 'prêts',
 'pr�tre': 'prêtre',
 "'pr�tre'": "'prêtre'",
 'pr�tres': 'prêtres',
 '�missions': 'émissions',
 "l'�mission": "l'émission",
 "'�mission": "'émission",
 '�mission': 'émission',
 'premi�re': 'première',
 'premi�res': 'premières',
 'oecum�nique': 'œcuménique',
 "'oecum�nisme'": "'œcuménisme'",
 'sovi�tique': 'soviétique',
 'sovi�tiques': 'soviétiques',
 'Sovi�tiques': 'Soviétiques',
 'am�ricain': 'américain',
 'am�ricaine': 'américaine',
 'am�ricains': 'américains',
 'am�ricaines': 'américaines',
 'Am�ricains': 'Américains',
 "l'arm�e": "l'armée",
 "'arm�e'": "'armée'",
 'arm�e': 'armée',
 "arm�'": "armé'",
 'soci�t�': 'société',
 'Soci�t�': 'Société',
 'soci�t�s': 'sociétés',
 "'Deuxi�me": "'Deuxième",
 'Deuxi�me': 'Deuxième',
 'deuxi�me': 'deuxième',
 'r�fugi�s': 'réfugiés',
 'r�fugi�': 'réfugié',
 "r�fugi�'": "réfugié'",
 "'r�fugi�'": "'réfugié'",
 'r�fugi�e': 'réfugiée',
 '�lections': 'élections',
 "'�lection": "'élection",
 '�lection': 'élection',
 "'�lection'": "'élection'",
 "l'�lection": "l'élection",
 '�lectorale': 'électorale',
 'isra�lien': 'israélien',
 'isra�lienne': 'israélienne',
 'r�gion': 'région',
 'r�gions': 'régions',
 'n�gociations': 'négociations',
 'c�r�monie': 'cérémonie',
 'C�r�monie': 'Cérémonie',
 'm�me': 'même',
 'm�mes': 'mêmes',
 'sc�ne': 'scène',
 'Comit�': 'Comité',
 'comit�': 'comité',
 'com�dien': 'comédien',
 "'com�dien'": "'comédien'",
 "'com�dien": "'comédien",
 'com�dienne': 'comédienne',
 "'com�dienne'": "'comédienne'",
 'Congr�s': 'Congrès',
 'congr�s': 'congrès',
 "l'ann�e": "l'année",
 'ann�e': 'année',
 'ann�es': 'années',
 'Enqu�te': 'Enquête',
 "d'enqu�te": "d'enquête",
 'enqu�te': 'enquête',
 "l'enqu�te": "l'enquête",
 'd�part': 'départ',
 'march�': 'marché',
 'March�': 'Marché',
 'd�mission': 'démission',
 'D�mission': 'Démission',
 'd�but': 'début',
 'D�but': 'Début',
 'charg�': 'chargé',
 'd�fense': 'défense',
 'gr�ve': 'grève',
 "'gr�ve'": "'grève'",
 "l'Assembl�e": "l'Assemblée",
 "l'assembl�e": "l'assemblée",
 'communaut�': 'communauté',
 'Communaut�': 'Communauté',
 'r�gime': 'régime',
 '�lu': 'élu',
 '�lus': 'élus',
 '�lue': 'élue',
 'd�veloppement': 'développement',
 'po�te': 'poète',
 'autorit�s': 'autorités',
 'cons�quences': 'conséquences',
 'libert�': 'liberté',
 'th��tre': 'théâtre',
 'Th��tre': 'Théâtre',
 "'cin�ma'": "'cinéma'",
 'cin�ma': 'cinéma',
 'm�re': 'mère',
 'P�re': 'Père',
 'p�re': 'père',
 'fr�re': 'frère',
 'fr�res': 'frères',
 'F�te': 'Fête',
 'f�te': 'fête',
 "'f�te": "'fête",
 'f�tes': 'fêtes',
 'f�vrier': 'février',
 '�tat': 'État',
 "d'�tat": "d'État",
 "l'�tat": "l'État",
 '�tats': 'États',
 't�te': 'tête',
 'bless�s': 'blessés',
 'r�alisateur': 'réalisateur',
 'd�bat': 'débat',
 'D�bat': 'Débat',
 "'D�bat'": "'Débat'",
 "d�bat'": "débat'",
 "D�bat'": "Débat'",
 'ch�mage': 'chômage',
 "'ch�mage'": "'chômage'",
 'ch�meurs': 'chômeurs',
 'pr�sence': 'présence',
 'pass�': 'passé',
 'journ�e': 'journée',
 'Journ�e': 'Journée',
 "l'�tranger": "l'étranger",
 'ing�nieur': 'ingénieur',
 'd�s': 'dès',
 '�ge': 'âge',
 "l'�ge": "l'âge",
 '�galement': 'également',
 '�v�nements': 'événements',
 "'�v�nement": "'événement",
 'difficult�s': 'difficultés',
 'D�c�s': 'Décès',
 'd�c�s': 'décès',
 'd�cembre': 'décembre',
 "l'�cole": "l'école",
 '�cole': 'école',
 "'�coles": "'écoles",
 '�coles': 'écoles',
 're�u': 'reçu',
 'contr�le': 'contrôle',
 'r�union': 'réunion',
 'R�union': 'Réunion',
 "'r�union": "'réunion",
 'solidarit�': 'solidarité',
 'Solidarit�': 'Solidarité',
 'si�ge': 'siège',
 "l'a�roport": "l'aéroport",
 'a�rienne': 'aérienne',
 "a�rienne'": "aérienne'",
 "a�rien'": "aérien'",
 'a�rostier': 'aérostier',
 'ao�t': 'août',
 'cha�ne': 'chaîne',
 'Cha�ne': 'Chaîne',
 'condamn�': 'condamné',
 'r�sistance': 'résistance',
 '�tudiants': 'étudiants',
 '�tudiant': 'étudiant',
 'r�forme': 'réforme',
 'r�formes': 'réformes',
 'd�mocratie': 'démocratie',
 "'d�mocratie": "'démocratie",
 'carri�re': 'carrière',
 'ext�rieur': 'extérieur',
 'ext�rieure': 'extérieure',
 'l�gislatives': 'législatives',
 "'l�gislation'": "'législation'",
 "'l�gislatif": "'législatif",
 '�v�que': 'évêque',
 '�v�ques': 'évêques',
 '�trangers': 'étrangers',
 '�trang�res': 'étrangères',
 '�trang�re': 'étrangère',
 "�trang�res'": "étrangères'",
 'fronti�res': 'frontières',
 'fronti�re': 'frontière',
 'r�f�rendum': 'référendum',
 "'r�f�rendum'": "'référendum'",
 '�voque': 'évoque',
 "'ex�cutif": "'exécutif",
 'Mus�e': 'Musée',
 'mus�e': 'musée',
 'pi�ce': 'pièce',
 'Pr�dication': 'Prédication',
 'pr�dication': 'prédication',
 'r�volution': 'révolution',
 'litt�rature': 'littérature',
 "'litt�rature'": "'littérature'",
 'litt�raire': 'littéraire',
 "litt�raire'": "littéraire'",
 "l'ind�pendance": "l'indépendance",
 "'ind�pendantisme'": "'indépendantisme'",
 'r�daction': 'rédaction',
 'mati�re': 'matière',
 'donn�': 'donné',
 'd�cid�': 'décidé',
 'syst�me': 'système',
 'succ�s': 'succès',
 'r�vision': 'révision',
 'd�couverte': 'découverte',
 'arr�t�': 'arrêté',
 'Arr�t': 'Arrêt',
 'financi�re': 'financière',
 'sign�': 'signé',
 'm�decine': 'médecine',
 "'m�decine'": "'médecine'",
 'm�decin': 'médecin',
 "'m�decin": "'médecin",
 "'m�decin'": "'médecin'",
 'm�decins': 'médecins',
 'M�decins': 'Médecins',
 'T�l�vision': 'Télévision',
 "'t�l�vision'": "'télévision'",
 't�l�vision': 'télévision',
 't�l�phone': 'téléphone',
 'derni�re': 'dernière',
 'derni�res': 'dernières',
 "l'int�rieur": "l'intérieur",
 "l'Int�rieur": "l'Intérieur",
 "l'arriv�e": "l'arrivée",
 'arriv�e': 'arrivée',
 'Arriv�e': 'Arrivée',
 '�taient': 'étaient',
 '�tait': 'était',
 'M�moire': 'Mémoire',
 'm�moire': 'mémoire',
 'Lib�ration': 'Libération',
 'lib�ration': 'libération',
 'lib�ral': 'libéral',
 'lib�rale': 'libérale',
 'cr�ation': 'création',
 'Cr�ation': 'Création',
 'envoy�': 'envoyé',
 "'envoy�": "'envoyé",
 'd�l�gation': 'délégation',
 'd�l�gu�': 'délégué',
 "'d�l�gu�": "'délégué",
 'd�l�gu�s': 'délégués',
 "'d�l�gu�s": "'délégués",
 'r�le': 'rôle',
 'r�les': 'rôles',
 's�curit�': 'sécurité',
 'proc�s': 'procès',
 "'proc�s'": "'procès'",
 'r�dacteur': 'rédacteur',
 "'r�dacteur": "'rédacteur",
 'si�cle': 'siècle',
 "si�cle'": "siècle'",
 'd�put�': 'député',
 "'d�put�": "'député",
 'd�put�e': 'députée',
 'd�put�s': 'députés',
 'd�put�es': 'députées',
 'd�cision': 'décision',
 'D�cision': 'Décision',
 "l'�nergie": "l'énergie",
 "'�nergie": "'énergie",
 '�nergies': 'énergies',
 'repr�sentant': 'représentant',
 'repr�sentants': 'représentants',
 'conseill�re': 'conseillère',
 "'conseill�re": "'conseillère",
 'pr�s': 'près',
 'comp�tition': 'compétition',
 'sant�': 'santé',
 'R�trospective': 'Rétrospective',
 'c�t�': 'côté',
 'm�dias': 'médias',
 "l'adh�sion": "l'adhésion",
 'r�sultats': 'résultats',
 'r�sultat': 'résultat',
 'Europ�enne': 'Européenne',
 'europ�enne': 'européenne',
 "europ�enne'": "européenne'",
 'europ�ennes': 'européennes',
 'europ�en': 'européen',
 'europ�ens': 'européens',
 'malgr�': 'malgré',
 'coop�ration': 'coopération',
 'th�ologie': 'théologie',
 'th�ologien': 'théologien',
 'alg�rien': 'algérien',
 'minist�re': 'ministère',
 'd�': 'dé',
 'd�mocrate-chr�tien': 'démocrate-chrétien',
 'pr�nom': 'prénom',
 'chr�tiens': 'chrétiens',
 'chr�tien': 'chrétien',
 'th�me': 'thème',
 'employ�s': 'employés',
 'organis�': 'organisé',
 'S�rie': 'Série',
 's�rie': 'série',
 'diff�rents': 'différents',
 'diff�rentes': 'différentes',
 'diff�rent': 'différent',
 'm�tier': 'métier',
 'entra�neur': 'entraîneur',
 'laur�at': 'lauréat',
 'consacr�': 'consacré',
 'consacr�e': 'consacrée',
 '�tudes': 'études',
 "d'�tudes": "d'études",
 '�tude': 'étude',
 '�pouse': 'épouse',
 'r�ponse': 'réponse',
 'n�cessit�': 'nécessité',
 '�meutes': 'émeutes',
 "l'�le": "l'île",
 'for�ts': 'forêts',
 'm�dicale': 'médicale',
 'responsabilit�': 'responsabilité',
 'personnalit�s': 'personnalités',
 'personnalit�': 'personnalité',
 'op�ration': 'opération',
 'Op�ration': 'Opération',
 'op�rations': 'opérations',
 'proc�dure': 'procédure',
 'd�tenus': 'détenus',
 'trouv�': 'trouvé',
 'pr�vention': 'prévention',
 'publicit�': 'publicité',
 'neutralit�': 'neutralité',
 'r�unification': 'réunification',
 'nucl�aire': 'nucléaire',
 "nucl�aire'": "nucléaire'",
 'nucl�aires': 'nucléaires',
 "l'�quipe": "l'équipe",
 '�change': 'échange',
 'o�': 'où',
 'tr�s': 'très',
 'probl�me': 'problème',
 'probl�mes': 'problèmes',
 'nomm�': 'nommé',
 'strat�gie': 'stratégie',
 'activit�': 'activité',
 'activit�s': 'activités',
 'exp�rience': 'expérience',
 'propri�taire': 'propriétaire',
 'Nestl�': 'Nestlé',
 'annonc�': 'annoncé',
 'priv�e': 'privée',
 'col�re': 'colère',
 'accept�': 'accepté',
 'Tch�coslovaquie': 'Tchécoslovaquie',
 'rencontr�': 'rencontré',
 'Di�te': 'Diète',
 'lanc�': 'lancé',
 'cr�er': 'créer',
 'Proc�s': 'Procès',
 'm�daille': 'médaille',
 'p�dophile': 'pédophile',
 'horlog�re': 'horlogère',
 'fa�on': 'façon',
 'reconna�t': 'reconnaît',
 'al�manique': 'alémanique',
 'v�cu': 'vécu',
 "'comm�moration'": "'commémoration'",
 'p�trole': 'pétrole',
 'lumi�res': 'lumières',
 "l'abb�": "l'abbé",
 "l'h�pital": "l'hôpital",
 'mani�re': 'manière',
 'helv�tique': 'helvétique',
 'd�mocrate': 'démocrate',
 '�l�ments': 'éléments',
 'd�nonce': 'dénonce',
 'd�faite': 'défaite',
 'plut�t': 'plutôt',
 'gr�ce': 'grâce',
 'volont�': 'volonté',
 'b�timent': 'bâtiment',
 "l'op�ration": "l'opération",
 "stup�fiants'": "stupéfiants'",
 "jusqu'�": "jusqu'à",
 'requ�rant': 'requérant',
 'requ�rants': 'requérants',
 'assassin�': 'assassiné',
 'r�alit�': 'réalité',
 "l'Acad�mie": "l'Académie",
 'd�cide': 'décide',
 'cin�aste': 'cinéaste',
 'd�tention': 'détention',
 "l'�volution": "l'évolution",
 "l'�gard": "l'égard",
 '�glise': 'église',
 "l'�glise": "l'église",
 '�glises': 'églises',
 "'�glise": "'église",
 'R�cit': 'Récit',
 'r�cit': 'récit',
 "'R�citant": "'Récitant",
 '�crit': 'écrit',
 '�crits': 'écrits',
 '�crite': 'écrite',
 'f�minin': 'féminin',
 'occup�s': 'occupés',
 'majorit�': 'majorité',
 '�tabli': 'établi',
 '�tablie': 'établie',
 '�le': 'île',
 "�le'": "île'",
 '�lecteur': 'électeur',
 '�lecteurs': 'électeurs',
 "�lection'": "élection'",
 '�lectricit�': 'électricité',
 '�levage': 'élevage',
 '�leveur': 'éleveur',
 '�leveurs': 'éleveurs',
 '�lite': 'élite',
 '�loge': 'éloge',
 '�boueur': 'éboueur',
 '�branlement': 'ébranlement',
 '�cart': 'écart',
 '�chafaud': 'échafaud',
 '�chec': 'échec',
 "�checs'": "échecs'",
 "�chographie'": "échographie'",
 '�clairage': 'éclairage',
 "�clipse'": "éclipse'",
 '�coli�re': 'écolière',
 '�colier': 'écolier',
 "�colier'": "écolier'",
 '�coliers': 'écoliers',
 '�cologie': 'écologie',
 "�cologie'": "écologie'",
 "�cologisme'": "écologisme'",
 "�conomie'": "économie'",
 '�conomies': 'économies',
 '�coute': 'écoute',
 '�craser': 'écraser',
 "�crevisse'": "écrevisse'",
 '�criture': 'écriture',
 "�criture'": "écriture'",
 '�crivains': 'écrivains',
 '�dition': 'édition',
 "�dition'": "édition'",
 '�ducateur': 'éducateur',
 "�ducateur'": "éducateur'",
 '�ducateurs': 'éducateurs',
 '�ducation': 'éducation',
 "�ducation'": "éducation'",
 '�ducatrice': 'éducatrice',
 '�galit�': 'égalité',
 "�galit�'": "égalité'",
 '�gyptologue': 'égyptologue',
 "�gyptologue'": "égyptologue'",
 '�largir': 'élargir',
 "�l�ve'": "élève'",
 '�l�ves': 'élèves',
 "�l�phant'": "éléphant'",
 '�cologiste': 'écologiste',
 "�cologiste'": "écologiste'",
 '�ll�s': 'elles',
 'd�j�': 'déjà',
 'carr�': 'carré',
 't�l�vis�': 'télévisé',
 'f�d�r�': 'fédéré',
 'diff�renci�': 'différencié',
 '�v�nement': 'événement',
 'repr�senter': 'représenter',
 's�curit�s': 'sécurités',
 'th�orie': 'théorie',
 'cin�matographique': 'cinématographique',
 'po�sie': 'poésie',
 "'po�sie'": "'poésie'",
 'int�gration': 'intégration',
 "'int�gration": "'intégration",
 "l'int�gration": "l'intégration",
 'd�bats': 'débats',
 'repr�sente': 'représente',
 'abb�': 'abbé',
 't�l�': 'télé',
 'arm�': 'armé',
 'g�ographe': 'géographe',
 'g�ographie': 'géographie',
 'g�ographique': 'géographique',
 'arch�ologue': 'archéologue',
 'arch�ologie': 'archéologie',
 'Universit�s': 'Universités',
 'universit�s': 'universités',
 'M�t�o': 'Météo',
 'li�': 'lié',
 "L'�volution": "L'évolution",
 "l'�ch�ance": "l'échéance",
 'adh�sion': 'adhésion',
 'El�ment': 'Elément',
 'el�ments': 'eléments',
 'install�s': 'installés',
 'chass�s': 'chassés',
 'marqu�s': 'marqués',
 'marqu�': 'marqué',
 'cha�nes': 'chaînes',
 "l'entra�neur": "l'entraîneur",
 'au-del�': 'au-delà',
 "Jusqu'o�": "Jusqu'où",
 'men�s': 'menés',
 'Plan�te': 'Planète',
 'concr�tement': 'concrètement',
 'd�veloppment': 'développement',
 'J�r�me': 'Jérôme',
 'requ�tes': 'requêtes',
 'Ch�teaureynaud': 'Châteaureynaud'}

In [51]:
df_to_fix_path = "/home/piconti/impresso-text-acquisition/text_preparation/data/sample_data/RTS/programs_metadata.rts_v3.csv"
df_fixed_path_int = "/home/piconti/impresso-text-acquisition/text_preparation/data/sample_data/RTS/programs_metadata_rts_fixed_int.csv"
df_fixed_path = "/home/piconti/impresso-text-acquisition/text_preparation/data/sample_data/RTS/programs_metadata_rts_fixed.csv"

df_to_fix = pd.read_csv(df_to_fix_path)

TEXT_COLS = [c for c in df_to_fix.columns if c not in ID_COLS]

print("Processing cells for char = '?' ...")
total_fixes = 0
for col in TEXT_COLS:
    before = df_to_fix[col].copy()
    df_to_fix[col] = df_to_fix[col].apply(fix_cell)
    fixes = (before != df_to_fix[col]).sum()
    total_fixes += fixes
    if fixes > 0:
        print(f"  {col}: {fixes} cells modified")

print(f"\nTotal cells modified: {total_fixes}")

# Verify key rows
print("\n--- Sample verification ---")
check_cols = ['broadcast_episode_title', 'content_summary', 'workflow_status', 'document_type', 'modulation_type']
for col in check_cols:
    samples = df_to_fix[col].dropna().head(5).tolist()
    print(f"\n{col}:")
    for s in samples[:3]:
        print(f"  {str(s)[:120]}")


print("\nSaving...")
df_to_fix.to_csv(df_fixed_path_int, index=False)


print("Processing cells for char = '�' ...")
total_fixes = 0
for col in TEXT_COLS:
    before = df_to_fix[col].copy()
    df_to_fix[col] = df_to_fix[col].apply(fix_cell, char='�', _map=SECOND_MANUAL_MAP)
    fixes = (before != df_to_fix[col]).sum()
    total_fixes += fixes
    if fixes > 0:
        print(f"  {col}: {fixes} cells modified")

print(f"\nTotal cells modified: {total_fixes}")

# Verify key rows
print("\n--- Sample verification ---")
check_cols = ['broadcast_episode_title', 'content_summary', 'workflow_status', 'document_type', 'modulation_type']
for col in check_cols:
    samples = df_to_fix[col].dropna().head(5).tolist()
    print(f"\n{col}:")
    for s in samples[:3]:
        print(f"  {str(s)[:120]}")

print("\nSaving...")
df_to_fix.to_csv(df_fixed_path, index=False)
print("Done!")

Processing cells for char = '?' ...
  broadcast_episode_title: 19134 cells modified
  broadcast_program_name: 1549 cells modified
  document_type: 20956 cells modified
  physical_support_history: 3576 cells modified
  production_type: 521 cells modified
  recording_place: 19605 cells modified
  rights_notes: 22818 cells modified
  rights_status: 22332 cells modified
  series_title: 8917 cells modified
  content_summary: 21474 cells modified
  workflow_status: 20956 cells modified
  assembly_status: 22585 cells modified
  live: 670 cells modified
  modulation_type: 4832 cells modified
  geographical_descriptors: 15692 cells modified
  person_descriptors: 16951 cells modified
  thematical_descriptors: 18174 cells modified
  rights_usage_possibilities: 8538 cells modified
  radio_channels: 15075 cells modified
  subdomains: 10830 cells modified
  recording_dates: 492 cells modified
  first_broadcast_dates: 1056 cells modified
  supports: 16948 cells modified
  participants: 17654 cells modified

Total cells modified: 311335

--- Sample verification ---

broadcast_episode_title:
  "X-Files" ou "Aux frontières du réel"
  Internet à l'Ecole primaire d'Avully (GE)
  Le carré blanc

content_summary:
  Présentation de la série-culte. Le succès, comment le comprendre? Analyse des personnages, des dialogues. Thèmes de la s
  Analyse de la série et des raisons de son succès.
  1992, c'est la prochaine grande étape de l'Europe communautaire. Les régles et les lois qui régissent les personnes et l

workflow_status:
  Validé
  Validé
  Validé

document_type:
  Parlé
  Parlé
  Parlé

modulation_type:
  Stéréo
  Stéréo
  Stéréo

Saving...
Processing cells for char = '�' ...
  broadcast_episode_title: 4860 cells modified
  broadcast_program_name: 1582 cells modified
  document_type: 5305 cells modified
  physical_support_history: 3374 cells modified
  production_type: 30 cells modified
  recording_place: 18992 cells modified
  rights_notes: 22801 cells modified
  rights_status: 11672 cells modified
  series_title: 8099 cells modified
  content_summary: 17733 cells modified
  workflow_status: 5305 cells modified
  assembly_status: 20647 cells modified
  live: 670 cells modified
  modulation_type: 2279 cells modified
  geographical_descriptors: 14433 cells modified
  person_descriptors: 16537 cells modified
  thematical_descriptors: 13434 cells modified
  rights_usage_possibilities: 8538 cells modified
  radio_channels: 6306 cells modified
  subdomains: 10487 cells modified
  recording_dates: 415 cells modified
  first_broadcast_dates: 1056 cells modified
  supports: 4694 cells modified
  participants: 5998 cells modified

Total cells modified: 205247

--- Sample verification ---

broadcast_episode_title:
  "X-Files" ou "Aux frontières du réel"
  Internet à l'Ecole primaire d'Avully (GE)
  Le carré blanc

content_summary:
  Présentation de la série-culte. Le succès, comment le comprendre? Analyse des personnages, des dialogues. Thèmes de la s
  Analyse de la série et des raisons de son succès.
  1992, c'est la prochaine grande étape de l'Europe communautaire. Les régles et les lois qui régissent les personnes et l

workflow_status:
  Validé
  Validé
  Validé

document_type:
  Parlé
  Parlé
  Parlé

modulation_type:
  Stéréo
  Stéréo
  Stéréo

Saving...
Done!

## Perform some additional post-processing and cleaning 

This is specifically to separate the case for the metadata and issue index creation

In [ ]:
rts_metadata_filepath = "/home/piconti/impresso-text-acquisition/text_preparation/data/sample_data/RTS/programs_metadata_rts.csv"

rts_metadata_df = pd.read_csv(rts_metadata_filepath)
print(len(rts_metadata_df))
rts_metadata_df.head()

26261

,alias,date_str,stt_filename,mp3_filenames,stripped_OID,exact_date,broadcast_date,cls_ID,OID,login,...,person_descriptors,thematical_descriptors,rights_usage_possibilities,radio_channels,subdomains,recording_dates,first_broadcast_dates,supports,spt_filenames,participants
0,ana_media,16/12/1996,677E6735-8DEA-44F1-A52F-142BFEF9AB2E_STT.xml,['677e6735-8dea-44f1-a52f-142bfef9ab2e_7UBM_05...,677E6735-8DEA-44F1-A52F-142BFEF9AB2E,True,True,{D2593F4E-C887-4E48-8982-5BD08BA4DAE0},{677E6735-8DEA-44F1-A52F-142BFEF9AB2E},NaN,...,"['X-Files', 'Aux frontières du réel']","['série télèvisée', 'science-fiction']",NaN,['Espace 2'],['Interview'],['~__/12/1996 - ~__/12/1996'],['16/12/1996 - 16/12/1996'],[{'spt_clsid': '{9C19C69A-A4DC-479E-94F1-61FF7...,"[None, '7UBM_057338_1{8cfcf300-a815-4f92-bea2-...","[{'name': 'Frias, Roxanne', 'function': 'Inter..."
1,ana_media,26/05/1997,640E3C0B-40F0-4BD9-83C6-1FF4BCE16484_STT.xml,['640e3c0b-40f0-4bd9-83c6-1ff4bce16484_1BBM_05...,640E3C0B-40F0-4BD9-83C6-1FF4BCE16484,True,True,{D2593F4E-C887-4E48-8982-5BD08BA4DAE0},{640E3C0B-40F0-4BD9-83C6-1FF4BCE16484},NaN,...,NaN,"['école primaire', 'Internet', 'technique péda...",NaN,['Espace 2'],"['Commentaire', 'Parlé divers']",['~__/05/1997 - ~__/05/1997'],['26/05/1997 - 26/05/1997'],[{'spt_clsid': '{9C19C69A-A4DC-479E-94F1-61FF7...,['1BBM_058066_6{2782ba11-7050-44d3-bef1-a81252...,"[{'name': 'Dubois, Laurent', 'function': 'Inte..."
2,ana_media,20/01/1997,2AF13E50-C6A2-49E5-9851-06C441833B50_STT.xml,['2af13e50-c6a2-49e5-9851-06c441833b50_RPBM_05...,2AF13E50-C6A2-49E5-9851-06C441833B50,True,True,{D2593F4E-C887-4E48-8982-5BD08BA4DAE0},{2AF13E50-C6A2-49E5-9851-06C441833B50},NaN,...,"['SSR', 'TSR']","['censure', 'télévision', 'morale']",NaN,['Espace 2'],['Interview'],['~__/04/1997 - ~__/04/1997'],['20/01/1997 - 20/01/1997'],[{'spt_clsid': '{9C19C69A-A4DC-479E-94F1-61FF7...,"[None, 'RPBM_057474_1{8116d0d3-1c12-44cf-a8a2-...","[{'name': 'Duparc, Nicole', 'function': 'Inter..."
3,ana_media,11/11/1996,C940BD19-5503-4918-852B-D40C1C18B359_STT.xml,['c940bd19-5503-4918-852b-d40c1c18b359_O1BM_05...,C940BD19-5503-4918-852B-D40C1C18B359,True,True,{D2593F4E-C887-4E48-8982-5BD08BA4DAE0},{C940BD19-5503-4918-852B-D40C1C18B359},NaN,...,NaN,"['série télèvisée', 'urgence médicale', 'télés...",NaN,['Espace 2'],['Interview'],['~__/11/1996 - ~__/11/1996'],['11/11/1996 - 11/11/1996'],[{'spt_clsid': '{9C19C69A-A4DC-479E-94F1-61FF7...,['O1BM_057153_2{396b576c-7ed9-4018-a251-c12a84...,"[{'name': 'Kiefer, B.', 'function': 'Interview..."
4,ana_media,21/04/1997,6EE0054C-042D-42E6-B11F-FEB6C0353B5A_STT.xml,['6ee0054c-042d-42e6-b11f-feb6c0353b5a_FHBM_05...,6EE0054C-042D-42E6-B11F-FEB6C0353B5A,True,True,{D2593F4E-C887-4E48-8982-5BD08BA4DAE0},{6EE0054C-042D-42E6-B11F-FEB6C0353B5A},NaN,...,NaN,"['enseignement secondaire', 'technique pédagog...",NaN,['Espace 2'],['Interview'],['~__/04/1997 - ~__/04/1997'],['21/04/1997 - 21/04/1997'],[{'spt_clsid': '{9C19C69A-A4DC-479E-94F1-61FF7...,['FHBM_055791_2{e8455981-078d-44f2-bb94-2e22cd...,"[{'name': 'Prophan, Geneviève', 'function': 'I..."

#### Columns filtering 

There was originally 36856 documents in the metadata, 10659 of which were missing MP3 and/or XML files (26261 had both). 

First remove the unused columns in this context, as well as all broadcasts which have no dates.

There are two main uses: the metadata, and the issue index. The filtering for the issue index columns will take place later on

In [5]:
rts_metadata_df.columns

Index(['alias', 'date_str', 'stt_filename', 'mp3_filenames', 'stripped_OID',
       'exact_date', 'broadcast_date', 'cls_ID', 'OID', 'login',
       'broadcast_episode_title', 'sequence', 'broadcast_program_name',
       'document_type', 'hierarchy_level', 'modified_by', 'modified_on',
       'physical_support_history', 'production_type', 'recording_place',
       'rights_notes', 'rights_status', 'series_title', 'content_summary',
       'workflow_status', 'assembly_status', 'live', 'modulation_type',
       'work_duration', 'work_duration_compl', 'geographical_descriptors',
       'person_descriptors', 'thematical_descriptors',
       'rights_usage_possibilities', 'radio_channels', 'subdomains',
       'recording_dates', 'first_broadcast_dates', 'supports', 'spt_filenames',
       'participants'],
      dtype='str')

In [6]:
# remove all the broadcasts without a date as we cannot process them
valid_rts_df = rts_metadata_df[~rts_metadata_df['date_str'].isna()]
valid_rts_df = valid_rts_df[['alias', 'date_str', 'stt_filename', 'mp3_filenames', 'stripped_OID', 'OID', 'exact_date', 'broadcast_date', 
                             'broadcast_episode_title', 'broadcast_program_name',
                             'recording_place', 'series_title', 'content_summary', 'live', 
                             'work_duration', 'participants', 'radio_channels', 
                             'recording_dates', 'first_broadcast_dates']]
print(len(valid_rts_df))
valid_rts_df.head()

26225

,alias,date_str,stt_filename,mp3_filenames,stripped_OID,OID,exact_date,broadcast_date,broadcast_episode_title,broadcast_program_name,recording_place,series_title,content_summary,live,work_duration,participants,radio_channels,recording_dates,first_broadcast_dates
0,ana_media,16/12/1996,677E6735-8DEA-44F1-A52F-142BFEF9AB2E_STT.xml,['677e6735-8dea-44f1-a52f-142bfef9ab2e_7UBM_05...,677E6735-8DEA-44F1-A52F-142BFEF9AB2E,{677E6735-8DEA-44F1-A52F-142BFEF9AB2E},True,True,"""X-Files"" ou ""Aux frontières du réel""",Analyse des médias,NaN,NaN,"Présentation de la série-culte. Le succès, com...",Non live,00:00:00.000,"[{'name': 'Frias, Roxanne', 'function': 'Inter...",['Espace 2'],['~__/12/1996 - ~__/12/1996'],['16/12/1996 - 16/12/1996']
1,ana_media,26/05/1997,640E3C0B-40F0-4BD9-83C6-1FF4BCE16484_STT.xml,['640e3c0b-40f0-4bd9-83c6-1ff4bce16484_1BBM_05...,640E3C0B-40F0-4BD9-83C6-1FF4BCE16484,{640E3C0B-40F0-4BD9-83C6-1FF4BCE16484},True,True,Internet à l'Ecole primaire d'Avully (GE),Analyse des médias,Avully,NaN,NaN,Non live,00:00:00.000,"[{'name': 'Dubois, Laurent', 'function': 'Inte...",['Espace 2'],['~__/05/1997 - ~__/05/1997'],['26/05/1997 - 26/05/1997']
2,ana_media,20/01/1997,2AF13E50-C6A2-49E5-9851-06C441833B50_STT.xml,['2af13e50-c6a2-49e5-9851-06c441833b50_RPBM_05...,2AF13E50-C6A2-49E5-9851-06C441833B50,{2AF13E50-C6A2-49E5-9851-06C441833B50},True,True,Le carré blanc,Analyse des médias,Genève;Fribourg,NaN,NaN,Non live,00:00:00.000,"[{'name': 'Duparc, Nicole', 'function': 'Inter...",['Espace 2'],['~__/04/1997 - ~__/04/1997'],['20/01/1997 - 20/01/1997']
3,ana_media,11/11/1996,C940BD19-5503-4918-852B-D40C1C18B359_STT.xml,['c940bd19-5503-4918-852b-d40c1c18b359_O1BM_05...,C940BD19-5503-4918-852B-D40C1C18B359,{C940BD19-5503-4918-852B-D40C1C18B359},True,True,"Le feuilleton télévisé ""Urgences""",Analyse des médias,Genève,NaN,Analyse de la série et des raisons de son succès.,Non live,00:00:00.000,"[{'name': 'Kiefer, B.', 'function': 'Interview...",['Espace 2'],['~__/11/1996 - ~__/11/1996'],['11/11/1996 - 11/11/1996']
4,ana_media,21/04/1997,6EE0054C-042D-42E6-B11F-FEB6C0353B5A_STT.xml,['6ee0054c-042d-42e6-b11f-feb6c0353b5a_FHBM_05...,6EE0054C-042D-42E6-B11F-FEB6C0353B5A,{6EE0054C-042D-42E6-B11F-FEB6C0353B5A},True,True,Le journal à l'école,Analyse des médias,Genève;Fribourg,NaN,NaN,Non live,00:00:00.000,"[{'name': 'Prophan, Geneviève', 'function': 'I...",['Espace 2'],['~__/04/1997 - ~__/04/1997'],['21/04/1997 - 21/04/1997']

Finally we removed 36 broadcasts which were missing their date, ending up with 26225 radio issues

In [7]:
26261-26225

36

In [ ]:
"Valid�"

## index_file building (not final nor correct)

In [70]:
# Function to build issue index structure similar to issue_index.sub.json
def build_issue_index(documents, program_alias, program_dir):
    """
    Build an issue index structure from parsed documents.
    
    Structure:
    {
        "program_alias": {
            "year": {
                "month": [
                    {
                        "day": int,
                        "edition": str (a, b, c, etc.),
                        "local_path": str,
                        "audio_file": str or list,
                        ... other document metadata
                    },
                    ...
                ],
                ...
            },
            ...
        }
    }
    
    Args:
        documents: list of parsed document dictionaries
        program_alias: the program name/alias (e.g., "causerie_uni")
        program_dir: the path to the program directory
    
    Returns:
        tuple: (issue_index_dict, missing_audio_files_dict)
    """
    from datetime import datetime
    from collections import defaultdict
    
    issue_index = {program_alias: {}}
    missing_audio_files = {program_alias: []}
    
    # Group documents by recording date
    date_groups = defaultdict(list)
    
    for doc in documents:
        # Parse recording date (format: "DD/MM/YYYY - DD/MM/YYYY")
        recording_dates = doc.get('recordingdates', [])
        if not recording_dates:
            missing_audio_files[program_alias].append({
                'title': doc.get('TITLE'),
                'reason': 'No recording date'
            })
            continue
        
        date_str = recording_dates[0].split(' - ')[0]  # Get first date
        try:
            date_obj = datetime.strptime(date_str, "%d/%m/%Y")
            year = str(date_obj.year)
            month = f"{date_obj.month:02d}"
            day = date_obj.day
            date_key = (year, month, day)
            date_groups[date_key].append(doc)
        except:
            missing_audio_files[program_alias].append({
                'title': doc.get('TITLE'),
                'reason': f'Could not parse date: {date_str}'
            })
            continue
    
    # Build the nested structure
    for (year, month, day), docs_for_day in sorted(date_groups.items()):
        # Initialize year and month if not exist
        if year not in issue_index[program_alias]:
            issue_index[program_alias][year] = {}
        if month not in issue_index[program_alias][year]:
            issue_index[program_alias][year][month] = []
        
        # Assign editions (a, b, c, etc.) to documents on the same day
        for edition_idx, doc in enumerate(docs_for_day):
            edition = chr(ord('a') + edition_idx)  # 'a', 'b', 'c', ...
            
            # Extract audio files
            audio_files = []
            if doc.get('supports'):
                for support in doc['supports']:
                    filename = support.get('filename')
                    if filename:
                        audio_files.append(filename)
            
            # Create issue entry
            issue_entry = {
                'day': day,
                'edition': edition,
                'local_path': program_dir,
                'title': doc.get('TITLE'),
                'broadcast': doc.get('BROADCAST'),
                'summary': doc.get('SUMMARY'),
                'participants': doc.get('participants', []),
                'geographic_descriptors': doc.get('geographicaldescriptors', []),
                'thematic_descriptors': doc.get('thematicaldescriptors', []),
                'duration': doc.get('WORKDURATION'),
                'recording_dates': doc.get('recordingdates', [])
            }
            
            # Handle audio_file field (single value if 1 file, list if multiple)
            if not audio_files:
                # Missing audio files - add to separate tracking dict
                missing_audio_files[program_alias].append({
                    'title': doc.get('TITLE'),
                    'date': f"{day}/{month}/{year}",
                    'edition': edition,
                    'reason': 'No audio files in metadata'
                })
            elif len(audio_files) == 1:
                issue_entry['audio_file'] = audio_files[0]
            else:
                issue_entry['audio_file'] = audio_files
            
            issue_index[program_alias][year][month].append(issue_entry)
    
    return issue_index, missing_audio_files


# Test with the example documents
issue_index, missing_files = build_issue_index(all_documents, 'causerie_uni', '/mnt/project_impresso/original/RTS/causerie_uni')

print(f"Issue Index built successfully!")
print(f"Programs: {list(issue_index.keys())}")

for program, years_data in issue_index.items():
    print(f"\n{program}:")
    print(f"  Years: {sorted(years_data.keys())}")
    
    for year, months_data in sorted(years_data.items()):
        print(f"    {year}:")
        for month, issues in sorted(months_data.items()):
            print(f"      {month}: {len(issues)} issue(s)")
            for issue in issues[:2]:  # Show first 2
                audio_info = f"audio: {issue.get('audio_file', 'N/A')}"
                if isinstance(issue.get('audio_file'), list):
                    audio_info = f"audio: {len(issue['audio_file'])} files"
                print(f"        Day {issue['day']}-{issue['edition']}: {audio_info}")

print(f"\n\nMissing audio files:")
for program, missing in missing_files.items():
    print(f"{program}: {len(missing)} document(s) with missing audio")
    for m in missing[:3]:  # Show first 3
        print(f"  - {m.get('title', 'N/A')[:60]}... ({m.get('reason', 'N/A')})")

Issue Index built successfully!
Programs: ['causerie_uni']

causerie_uni:
  Years: ['1939', '1940', '1942']
    1939:
      11: 6 issue(s)
        Day 4-a: audio: 1204286700-1542X_p_complet_wav958-SIROM{A3020B9E-9A94-4DFD-B1E0-CC34FE2F13AC}.wav
        Day 20-a: audio: 1211554131-1466X_complet_wav_958-SIROM{CFEC57B3-AADF-47BB-8ACF-49BE06EB6AD3}.wav
    1940:
      11: 1 issue(s)
        Day 26-a: audio: 1209129877-3151_p_complet_wav_958-SIROM{8357777C-7412-4674-98A8-B3AC6AB572DB}.wav
    1942:
      10: 1 issue(s)
        Day 3-a: audio: N/A


Missing audio files:
causerie_uni: 2 document(s) with missing audio
  - Le Tessin, facteur de coh?sion nationale : Causerie de Giova... (No audio files in metadata)
  - Epicure ou la religion du plaisir : Causerie de Ren? Schaere... (No audio files in metadata)

In [71]:
issue_index

{'causerie_uni': {'1939': {'11': [{'day': 4,
     'edition': 'a',
     'local_path': '/mnt/project_impresso/original/RTS/causerie_uni',
     'title': "L'enseignement de l'histoire. Causerie de Gonzague de Reynold",
     'broadcast': 'Causerie universitaire',
     'summary': "Cr?ation ? l'Universit? de Fribourg de la Chaire d'histoire de la civilisation moderne. L'enseignement de l'histoire a pour but d'initier les auditeurs ? la vie, de leur donner les connaissances et la compr?hension de l'Europe actuelle et tragique. L'?ducation de la pens?e doit d?velopper le sens critique en multipliant les termes de comparaison. La m?connaissance de l'histoire comme sympt?me de l'inculture d'une grande partie de la jeunesse. Devenir contemporain du pass? pour mieux le comprendre et appr?hender le pr?sent ? la lumi?re des origines.",
     'participants': [{'name': 'Reynold, Gonzague de',
       'function': 'Conf?rencier/e',
       'role': '?crivain'}],
     'geographic_descriptors': ['Fribourg (canton)', 'Europe'],
     'thematic_descriptors': ['universit?',
      'histoire',
      "enseignement de l'histoire",
      'temps (philosophie)'],
     'duration': '00:14:16.308',
     'recording_dates': ['04/11/1939 - 04/11/1939'],
     'audio_file': '1204286700-1542X_p_complet_wav958-SIROM{A3020B9E-9A94-4DFD-B1E0-CC34FE2F13AC}.wav'},
    {'day': 20,
     'edition': 'a',
     'local_path': '/mnt/project_impresso/original/RTS/causerie_uni',
     'title': "Adolphe Dygasinski, un Kipling avant Kipling. Causerie de Edouard Cros, privat-docent ? l'Universit? de Fribourg",
     'broadcast': 'Causerie universitaire',
     'summary': "Conf?rence sur l'oeuvre de l'?crivain polonais Dygasinsky, ? l'occasion du 100e anniversaire de sa naissance. Publiciste, conteur et traducteur, il repr?sente l'esprit positiviste de l'?poque et contribue ? la propagation des nouveaux courants d'id?es. Pr?curseur de Montessori. Romancier sensible ? la r?alit? des d?sh?rit?s des grandes villes, des paysans. Romancier animalier, il dresse le portrait psychologique des animaux de son pays natal, sans tomber dans l'anthropomorphisme. Exemple avec son portrait de la cigogne.",
     'participants': [{'name': 'Cros, Edouard',
       'function': 'Conf?rencier/e',
       'role': "privat-docent ? l'Universit? de Fribourg"}],
     'geographic_descriptors': ['Pologne'],
     'thematic_descriptors': ['?crivain',
      'litt?rature',
      '19e si?cle',
      'paysan',
      'portrait (art)',
      'cigogne',
      'naturalisme'],
     'duration': '00:13:38.975',
     'recording_dates': ['20/11/1939 - 20/11/1939'],
     'audio_file': '1211554131-1466X_complet_wav_958-SIROM{CFEC57B3-AADF-47BB-8ACF-49BE06EB6AD3}.wav'},
    {'day': 23,
     'edition': 'a',
     'local_path': '/mnt/project_impresso/original/RTS/causerie_uni',
     'title': "Le message de Claudel. Causerie de Marcel Pob?, professeur ? l'Universit? de Fribourg",
     'broadcast': 'Causerie universitaire',
     'summary': "Claudel s'est lui-m?me pench? sur son r?le d'?crivain. L'oeuvre n'est pas une fin en soi, mais un moyen de d?passement, au risque de contredire la th?orie de l'art pour l'art. Claudel, po?te libre prenant au s?rieux la spiritualit?. L'ordre et le sacrifice comme conditions ? la joie.",
     'participants': [{'name': 'Pob?, Marcel',
       'function': 'Conf?rencier/e',
       'role': "privat-docent chancelier de l'Universit? de Fribourg"}],
     'geographic_descriptors': ['France'],
     'thematic_descriptors': ['litt?rature',
      'po?sie',
      'christianisme',
      'courant artistique (20e)'],
     'duration': '00:13:01.087',
     'recording_dates': ['23/11/1939 - 23/11/1939'],
     'audio_file': '1205742867-1482X_p_complet_wav958-SIROM{BDD1F56E-A6DE-428B-99D4-A1792628729F}.wav'},
    {'day': 23,
     'edition': 'b',
     'local_path': '/mnt/project_impresso/original/RTS/causerie_uni',
     'title': "L'introduction du code p?nal suisse et les attributions des cantons. Causerie d' Alfred von Overbeck, professeur de droit ? l'Universit? de Fribourg",
     'broadcast': 'Causerie universitaire',
     'summary': "Le nouveau code p?nal suisse s'occupe des lois importantes. Les cantons devront l?gif?rer sur les contraventions de police et les sanctions mineures. R?le important des tribunaux cantonaux et libert? d'appr?ciation des juges, qui pourront rester fid?les aux traditions r?gionales. R?habilitation et droit de gr?ce.",
     'participants': [{'name': 'Overbeck, Alfred von',
       'function': 'Conf?rencier/e',
       'role': 'professeur de droit, Universit? de Fribourg'}],
     'geographic_descriptors': ['Suisse'],
     'thematic_descriptors': ['canton',
      'f?d?ralisme',
      'l?gislation',
      'droit p?nal',
      'juridiction p?nale',
      'juge'],
     'duration': '00:14:04.234',
     'recording_dates': ['23/11/1939 - 23/11/1939'],
     'audio_file': '1204286698-1488X_p_complet_wav958-SIROM{649BB0B7-9038-4080-8480-BA8C06AB315C}.wav'},
    {'day': 23,
     'edition': 'c',
     'local_path': '/mnt/project_impresso/original/RTS/causerie_uni',
     'title': "Virgile, po?te mondain. Causerie de Georges de Plinval, professeur ? l'Universit? de Fribourg",
     'broadcast': 'Causerie universitaire',
     'summary': 'Portrait de Virgile et analyse de quelques ?glogues',
     'participants': [{'name': 'Plinval, Georges de',
       'function': 'Conf?rencier/e',
       'role': "professeur ? l'Universit? de Fribourg"}],
     'geographic_descriptors': [],
     'thematic_descriptors': ['litt?rature',
      'po?sie',
      'civilisation romaine',
      'courant artistique (Antiquit?)'],
     'duration': '00:13:37.458',
     'recording_dates': ['23/11/1939 - 23/11/1939'],
     'audio_file': '1204286697-1486X_p_complet_wav958-SIROM{65CACD7F-4AD0-44EF-AA62-C4EEDEC7F189}.wav'},
    {'day': 25,
     'edition': 'a',
     'local_path': '/mnt/project_impresso/original/RTS/causerie_uni',
     'title': "Le Tessin, facteur de coh?sion nationale : Causerie de Giovanni Laini, lecteur de langue fran?aise ? l'Universit? de Fribourg",
     'broadcast': 'Causerie universitaire',
     'summary': "Prestige d'hier et d'aujourd'hui du Tessin. Exemples du pass? au 12e et au 13e si?cle: r?voltes contre Barberousse puis contre le duc de Milan. L'enthousiasme r?publicain des Tessinois. Exemples de fid?lit? du Tessin ? la Suisse. Sa sagesse civique.",
     'participants': [{'name': 'Laini, Giovanni',
       'function': 'Conf?rencier/e',
       'role': "lecteur de langue fran?aise ? l'Universit? de Fribourg"}],
     'geographic_descriptors': ['Tessin', 'Suisse', 'Fribourg (ville)'],
     'thematic_descriptors': ['guerre mondiale (deuxi?me)', 'patriotisme'],
     'duration': '00:00:00.000',
     'recording_dates': ['25/11/1939 - 25/11/1939']}]},
  '1940': {'11': [{'day': 26,
     'edition': 'a',
     'local_path': '/mnt/project_impresso/original/RTS/causerie_uni',
     'title': "Au coeur des lettres fran?aises : Georges Duhamel. Causerie de Ren? Bady, professeur ? l'Universit? de Fribourg",
     'broadcast': 'Causerie universitaire',
     'summary': "Portrait de l'?crivain fran?ais. Une question traverse toute l'oeuvre de Duhamel : quels sont les pouvoirs de l'homme face ? sa destin?e? M?decin major durant la Grande Guerre et t?moin de l'h?ro?sme des soldats. La probl?matique du h?ros et du saint dans ses oeuvres. Humanisme, observation et recherche.",
     'participants': [{'name': 'Bady, Ren?',
       'function': 'Conf?rencier/e',
       'role': "professeur ? l'Universit? de Fribourg"}],
     'geographic_descriptors': ['France'],
     'thematic_descriptors': ['litt?rature',
      'guerre mondiale (premi?re)',
      'religion et croyances',
      '?crivain'],
     'duration': '00:13:51.582',
     'recording_dates': ['26/11/1940 - 26/11/1940'],
     'audio_file': '1209129877-3151_p_complet_wav_958-SIROM{8357777C-7412-4674-98A8-B3AC6AB572DB}.wav'}]},
  '1942': {'10': [{'day': 3,
     'edition': 'a',
     'local_path': '/mnt/project_impresso/original/RTS/causerie_uni',
     'title': "Epicure ou la religion du plaisir : Causerie de Ren? Schaerer, charg? de cours ? l'Universit? de Neuch?tel",
     'broadcast': 'Causerie universitaire',
     'summary': "Vie d'Epicure. Ses adversaires et ses disciples. Sa morale en formules br?ves. Le bonheur r?side dans le plaisir. Comment faire durer le plaisir malgr? la douleur, la maladie, la vieillesse par le souvenir des plaisirs pass?s et par anticipation. L'?picurisme. La place d'Epicure dans l'histoire des id?es.",
     'participants': [{'name': 'Schaerer, Ren?',
       'function': 'Commentateur/trice',
       'role': "charg? de cours ? l'Universit? de Neuch?tel"}],
     'geographic_descriptors': ['Gr?ce',
      'Neuch?tel (canton)',
      'Antiquit? (civilisation)'],
     'thematic_descriptors': ['philosophie',
      'syst?me philosophique',
      'bonheur'],
     'duration': '00:00:00.000',
     'recording_dates': ['03/10/1942 - 03/10/1942']}]}}}